import {requireAccess,accessResponse} from '@/lib/authorization';
import {caseAccess,fail,monthsAfter} from '@/lib/after-sales';
const escape=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const day=(s:string)=>s?new Date(s+'T12:00:00Z').toLocaleDateString('fa-IR'):'—';
export async function GET(request:Request){try{const u=await requireAccess(),q=new URL(request.url).searchParams,c=await caseAccess(q.get('case')||'',u),d=c.data,kind=q.get('kind')||'receipt';if(!['receipt','warranty','invoice'].includes(kind))fail('نوع چاپ معتبر نیست.');if(kind==='receipt'&&!d.intake)fail('ابتدا پذیرش ثبت شود.');if(kind==='warranty'&&!d.deliveredDay)fail('ابتدا تحویل واقعی دستگاه ثبت شود.');if(kind==='invoice'&&!d.repairedAt)fail('ابتدا تعمیر ثبت شود.');
 const parts=(d.repairs||[]).map((r:any)=>{const l=d.lines.find((l:any)=>l.id===r.lineId);return {name:l?.name||r.partCode,quantity:r.quantity/1000,batch:r.batchId}}),message=kind==='warranty'?'سریال '+d.serial+'؛ قطعات تعویض‌شده: '+parts.map((p:any)=>p.name+' ('+p.quantity+')').join('، ')+'؛ گارانتی قطعات از '+day(d.deliveredDay)+' تا پیش از '+day(monthsAfter(d.deliveredDay,6))+' است.':'';
 if(q.get('format')==='text')return Response.json({text:message,sent:false},{headers:{'Cache-Control':'private, no-store'}});
 const pairs=[['شماره پرونده',c.id],['سریال',d.serial],['مدل',d.model],['مشتری',d.customer],['تلفن',d.phone],['تاریخ پذیرش',day(d.intake?.day||'')],['کارکرد',d.intake?.hours||'نامشخص'],['تحویل‌دهنده',d.intake?.deliverer],['لوازم همراه',d.intake?.accessories],['ظاهر دستگاه',d.intake?.appearance],['شرح مشتری',d.complaint]];
 const content=kind==='receipt'?pairs.map(([k,v])=>'<p><b>'+escape(k)+': </b>'+escape(v)+'</p>').join(''):kind==='warranty'?'<p>'+escape(message)+'</p>':'<p>سریال: '+escape(d.serial)+' — '+escape(d.customer)+'</p><table><tr><th>قطعه / خدمت</th><th>تعداد</th><th>مبلغ مشتری (ریال)</th></tr>'+d.lines.map((l:any)=>'<tr><td>'+escape(l.name)+'</td><td>'+escape(l.quantity/1000)+'</td><td>'+escape((BigInt(l.customerUnitRial)*BigInt(l.quantity)+BigInt(999))/BigInt(1000))+'</td></tr>').join('')+d.laborLines.map((l:any)=>'<tr><td>'+escape(l.name)+'</td><td>۱</td><td>'+escape(l.customerRial)+'</td></tr>').join('')+'</table><p>جمع: '+escape(d.customerTotal)+' ریال</p><p>برگه داخلی خدمات؛ ارسال به سامانه حسابداری یا صورتحساب مالیاتی انجام نشده است.</p>';
 const title=kind==='receipt'?'رسید پذیرش خدمات':kind==='warranty'?'گواهی گارانتی قطعات تعویض‌شده':'صورتحساب خدمات';
 return new Response('<!doctype html><html lang="fa" dir="rtl"><meta charset="utf-8"><title>'+title+'</title><style>@font-face{font-family:Vazirmatn;src:url(/fonts/Vazirmatn.woff2)}body{font-family:Vazirmatn,Tahoma;padding:24px;line-height:1.6;color:#23305d}article{border:1px solid #bbb;padding:22px;margin-bottom:24px;break-inside:avoid}p{margin:7px 0}table{width:100%;border-collapse:collapse}td,th{padding:8px;border:1px solid #ddd}@media print{body{padding:0}button{display:none}}</style><button onclick="window.print()">چاپ / ذخیره PDF</button>'+Array.from({length:kind==='receipt'?2:1},(_,i)=>'<article><h2>هم‌نفس · '+title+'</h2>'+(kind==='receipt'?'<p>'+(!i?'نسخه مشتری':'نسخه شرکت')+'</p>':'')+content+'<p>نام و امضای تحویل‌دهنده: .................... نام و امضای مسئول: ....................</p></article>').join('')+'</html>',{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'private, no-store','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; font-src 'self'; frame-ancestors 'self'"}});
 }catch(e){return accessResponse(e)||Response.json({error:'آماده‌سازی چاپ انجام نشد.'},{status:503})}}
