import {requireAccess,checkOrigin,accessResponse} from '@/lib/authorization';
import {boundedBody,firmwareBucket} from '@/lib/firmware-storage';
import {validateBatchFile,MAX_BATCH_FILE_BYTES} from '@/lib/batch-files';
import {sha256} from '@/lib/firmware';
import {storage} from '@/lib/storage';
import {gFail as fail,gText as txt} from '@/lib/guarantees';
import {guaranteeRoles} from '@/lib/guarantees';
async function settlementUser(){const u=await requireAccess();const roles=await guaranteeRoles(u);if(!roles.read)fail('دسترسی مالی لازم است.',403);return u;}
async function settlementRows(){return (await storage().prepare("SELECT * FROM flow_entities WHERE type IN ('bank_guarantee','guarantee_file')").all()).results.map((r:any)=>({...r,data:JSON.parse(r.data)}));}
function settlementBy(rows:any[],id:string,u:any){const r=rows.find(x=>x.id===id&&x.type==='bank_guarantee');if(!r)fail('پرونده در دسترس نیست.',404);return r;}

export async function GET(request:Request){try{const u=await settlementUser(),q=new URL(request.url).searchParams,rows=await settlementRows(),f=rows.find(r=>r.id===q.get('id')&&r.type==='guarantee_file');if(!f)fail('فایل یافت نشد.',404);settlementBy(rows,f.data.caseId,u);const o=await firmwareBucket().get(f.data.objectKey);if(!o)fail('فایل در دسترس نیست.',404);const bytes=await o!.arrayBuffer();if(bytes.byteLength!==f.data.byteSize||await sha256(bytes)!==f.data.sha256)fail('یکپارچگی فایل تأیید نشد.',503);return new Response(bytes,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(f.data.filename),'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"sandbox; default-src 'none'"}});}catch(e){return accessResponse(e)||Response.json({error:'دریافت مدرک ضمانت‌نامه انجام نشد.'},{status:503});}}
export async function POST(request:Request){let key='';try{checkOrigin(request);const u=await settlementUser(),q=new URL(request.url).searchParams,id=txt(q.get('id')),sid=txt(q.get('caseId')),filename=txt(q.get('filename'),180);if(!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(id))fail('شناسه فایل معتبر نیست.');const rows=await settlementRows(),s=settlementBy(rows,sid,u),positions=(await guaranteeRoles(u)).positions,member:any=await storage().prepare('SELECT id,status,permissions FROM app_members WHERE subject=? OR id=?').bind(u.userId,u.userId.startsWith('local:')?u.userId.slice(6):u.userId).first();if(!(await guaranteeRoles(u)).treasury||s.data.state==='closed')fail('افزودن مدرک در این مرحله مجاز نیست.',403);const bytes=await boundedBody(request,MAX_BATCH_FILE_BYTES);try{validateBatchFile(filename,bytes.length);}catch(e){fail((e as Error).message);}const hash=await sha256(bytes.buffer as ArrayBuffer),old=rows.find(r=>r.id===id);if(old){if(old.type!=='guarantee_file'||old.data.caseId!==sid||old.data.actor!==u.userId||old.data.sha256!==hash||old.data.filename!==filename)fail('شناسه فایل برای داده دیگری استفاده شده است.',409);return Response.json({id,repeated:true});}
 const db=storage(),now=new Date().toISOString();key='guarantees/'+sid+'/'+id+'/'+crypto.randomUUID();await firmwareBucket().put(key,bytes,{httpMetadata:{contentType:'application/octet-stream'}});const op=crypto.randomUUID(),guards=positions.map((p:any)=>db.prepare('UPDATE inventory_operations SET guard=CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN 1 ELSE 0 END WHERE id=?').bind(p.id,p.revision,op));if(member)guards.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN EXISTS(SELECT 1 FROM app_members WHERE id=? AND status=? AND permissions=?) THEN 1 ELSE 0 END WHERE id=?').bind(member.id,member.status,member.permissions,op));await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'guarantee_upload',?,?,?,CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN 1 ELSE 0 END)").bind(op,JSON.stringify({id,sid,filename,hash}),u.userId,now,sid,s.revision),...guards,db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,'guarantee_file',?,1,?,?)").bind(id,JSON.stringify({caseId:sid,filename,sha256:hash,byteSize:bytes.length,actor:u.userId,objectKey:key}),now,now),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,sid,'guarantee_upload',JSON.stringify({id,filename,hash}),now)]);return Response.json({id,filename},{headers:{'Cache-Control':'no-store'}});
 }catch(e){if(key){try{const linked=await storage().prepare("SELECT id FROM flow_entities WHERE type='guarantee_file' AND json_extract(data,'$.objectKey')=?").bind(key).first();if(!linked)await firmwareBucket().delete(key);}catch{}}return accessResponse(e)||Response.json({error:'بارگذاری تأیید نشد؛ فهرست مدارک را تازه کنید.'},{status:409});}}
