import {requireAdmin,checkOrigin,accessResponse,AccessError} from '@/lib/authorization';
import {storage} from '@/lib/storage';
import {tokenHash} from '@/lib/mcp/auth';
import {boundedBody} from '@/lib/firmware-storage';
const json=(d:unknown,status=200)=>Response.json(d,{status,headers:{'Cache-Control':'no-store','Referrer-Policy':'no-referrer'}});
export async function GET(){try{const actor=await requireAdmin();const rows=await storage().prepare('SELECT id,name,scope,expires,revoked,created FROM mcp_tokens WHERE subject=? ORDER BY created DESC').bind(actor.userId).all();return json({tokens:rows.results});}catch(e){return accessResponse(e)||json({error:'دریافت توکن‌ها انجام نشد.'},503);}}
export async function POST(request:Request){try{checkOrigin(request);const actor=await requireAdmin();let b:any;try{b=JSON.parse(new TextDecoder().decode(await boundedBody(request,2000)));}catch{throw new AccessError('درخواست معتبر نیست.',400);}if(!b||typeof b.name!=='string'||!b.name.trim()||b.name.length>100||!['read','read_write'].includes(b.scope)||!Number.isInteger(b.days)||b.days<1||b.days>90)throw new AccessError('نام، سطح دسترسی و اعتبار ۱ تا ۹۰ روز را وارد کنید.',400);
 const id=crypto.randomUUID(),token='nfy_'+[...crypto.getRandomValues(new Uint8Array(32))].map(n=>n.toString(16).padStart(2,'0')).join(''),created=new Date().toISOString(),expires=new Date(Date.now()+b.days*86400000).toISOString();
 await storage().batch([storage().prepare('INSERT INTO mcp_tokens(id,token_hash,subject,email,name,scope,expires,revoked,created) VALUES(?,?,?,?,?,?,?,0,?)').bind(id,await tokenHash(token),actor.userId,actor.email,b.name.trim(),b.scope,expires,created),storage().prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),actor.userId,id,'create_mcp_token',JSON.stringify({scope:b.scope,expires}),created)]);
 return json({id,token,expires},201);
 }catch(e){return accessResponse(e)||json({error:'ساخت توکن تأیید نشد؛ فهرست را بررسی کنید.'},503);}}
export async function DELETE(request:Request){try{checkOrigin(request);const actor=await requireAdmin(),id=new URL(request.url).searchParams.get('id');if(!id)throw new AccessError('شناسه لازم است.',400);const db=storage();await db.batch([db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) SELECT ?,?,?,?,?,? FROM mcp_tokens WHERE id=? AND subject=? AND revoked=0').bind(crypto.randomUUID(),actor.userId,id,'revoke_mcp_token','{}',new Date().toISOString(),id,actor.userId),db.prepare('UPDATE mcp_tokens SET revoked=1 WHERE id=? AND subject=?').bind(id,actor.userId),db.prepare('DELETE FROM mcp_streams WHERE token_id IN (SELECT id FROM mcp_tokens WHERE id=? AND subject=?)').bind(id,actor.userId)]);return json({revoked:true});}catch(e){return accessResponse(e)||json({error:'لغو انجام نشد.'},503);}}
