import {requireAccess,checkOrigin,accessResponse} from '@/lib/authorization';
import {storage} from '@/lib/storage';
import {firmwareBucket,boundedBody} from '@/lib/firmware-storage';
import {sha256} from '@/lib/firmware';
import {MAX_BATCH_FILE_BYTES,validateBatchFile} from '@/lib/batch-files';
import {taskRequired as req,taskText as txt,validDay,dayAt} from '@/lib/duties';
import {supplierEntity,supplierManage,supplierQuality,supplierCommercial} from '@/lib/suppliers';
import {supplierScope,publicDocument,documentVisible,qualityMember,syncSupplierQuality,sqFail as fail} from '@/lib/supplier-quality';
import {supplierDocumentKinds} from '@/lib/supplier-quality-contract';
const json=(d:any,status=200)=>Response.json(d,{status,headers:{'Cache-Control':'private, no-store'}});
export async function GET(request:Request){try{const u=await requireAccess(),q=new URL(request.url).searchParams,e=await supplierEntity(q.get('id')||'','supplier_document'),{supplier}=await supplierScope(u,e.data.supplierId,e.data.linkId||'');if(!documentVisible(u,e.data,supplier.data.route))fail('دسترسی این مدرک را ندارید.',403);if(q.get('metadata')==='1')return json({document:publicDocument(e),downloadUrl:new URL('/api/suppliers/files?id='+encodeURIComponent(e.id),request.url).toString()});const object=await firmwareBucket().get(e.data.objectKey);if(!object)fail('فایل موقتاً در دسترس نیست.',503);const bytes=await object!.arrayBuffer();if(bytes.byteLength!==e.data.size||await sha256(bytes)!==e.data.sha256)fail('یکپارچگی فایل تأیید نشد.',503);const name=encodeURIComponent(e.data.filename).replace(/['()*]/g,c=>'%'+c.charCodeAt(0).toString(16).toUpperCase());return new Response(bytes,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':"attachment; filename=supplier-document; filename*=UTF-8''"+name,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"sandbox; default-src 'none'"}});
 }catch(e){return accessResponse(e)||json({error:'دریافت مدرک انجام نشد.'},503)}}
export async function POST(request:Request){let key='',id='';try{checkOrigin(request);const u=await requireAccess();if(!supplierManage(u)&&!supplierQuality(u))fail('مجوز بارگذاری ندارید.',403);const ct=request.headers.get('content-type')||'';if(!ct.startsWith('multipart/form-data;'))fail('فایل و مشخصات انتخاب کنید.');const raw=await boundedBody(request,MAX_BATCH_FILE_BYTES+128000),form=await new Response(raw,{headers:{'Content-Type':ct}}).formData(),meta=form.get('metadata'),f=form.get('file');if(typeof meta!=='string'||meta.length>20000||!f||typeof f==='string'||form.getAll('file').length!==1)fail('یک فایل و مشخصات معتبر لازم است.');const b=JSON.parse(meta as string);id=req(b.id,80);if(!/^[a-f0-9-]{36}$/i.test(id)||b.confirmed!==true)fail('شناسه و تأیید صریح لازم است.');try{validateBatchFile((f as File).name,(f as File).size);}catch(e){fail((e as Error).message);}
 const file=f as File,{supplier,link}=await supplierScope(u,req(b.supplierId),b.linkId?req(b.linkId):'');const bytes=await file.arrayBuffer(),hash=await sha256(bytes),signature=JSON.stringify({metadata:b,filename:file.name,size:file.size,hash}),db=storage();const old:any=await db.prepare('SELECT * FROM flow_entities WHERE id=?').bind(id).first();if(old){const d=JSON.parse(old.data);if(old.type!=='supplier_document'||d.uploadSignature!==signature||d.actor!==u.userId)fail('شناسه برای فایل یا اطلاعات دیگری استفاده شده است.',409);return json({saved:true,repeated:true,id});}
 if(!Object.hasOwn(supplierDocumentKinds,b.kind)||!['quality','commercial'].includes(b.visibility))fail('نوع مدرک و سطح دسترسی معتبر لازم است.');if(b.visibility==='commercial'&&!supplierCommercial(u,supplier.data.route))fail('مجوز مدرک مالی ندارید.',403);
 const owner=await qualityMember(req(b.ownerId),supplier.data.route,'owner'),reviewer=await qualityMember(req(b.reviewerId),supplier.data.route,'reviewer');if(b.visibility==='commercial'&&(!supplierCommercial({permissions:JSON.parse(owner.permissions)} as any,supplier.data.route)||!supplierCommercial({permissions:JSON.parse(reviewer.permissions)} as any,supplier.data.route)))fail('مسئول و بررسی‌کننده مدرک مالی باید مجوز مالی همین مسیر را داشته باشند.');
 const issuedOn=req(b.issuedOn,10),expiresOn=txt(b.expiresOn||'',10),noExpiryReason=txt(b.noExpiryReason||'',1000);if(!validDay(issuedOn)||issuedOn>dayAt()||expiresOn&&(!validDay(expiresOn)||expiresOn<issuedOn)||!expiresOn&&!noExpiryReason)fail('تاریخ صدور/انقضا یا دلیل نداشتن انقضا معتبر لازم است.');
 let previous:any=null,capa:any=null;if(b.previousId){previous=await supplierEntity(req(b.previousId),'supplier_document');if(previous.revision!==b.previousRevision||previous.data.supplierId!==supplier.id||(previous.data.linkId||'')!==(link?.id||'')||previous.data.kind!==b.kind||previous.data.visibility!==b.visibility||previous.data.state==='superseded')fail('نسخه قبلی با پرونده منطبق نیست یا تغییر کرده است.',409);}
 if(b.capaId){capa=await supplierEntity(req(b.capaId),'supplier_capa');if(!link||capa.data.linkId!==link.id||capa.data.state==='closed'||b.kind!=='capa')fail('مدرک اقدام اصلاحی به پرونده باز همین کالا متصل باشد.');}
 key='supplier-documents/'+id+'/'+crypto.randomUUID();await firmwareBucket().put(key,bytes,{httpMetadata:{contentType:'application/octet-stream'},sha256:hash});const now=new Date().toISOString(),data={supplierId:supplier.id,supplierName:supplier.data.name,route:supplier.data.route,linkId:link?.id||'',capaId:capa?.id||'',kind:b.kind,visibility:b.visibility,title:req(b.title,200),issuer:req(b.issuer,200),reference:req(b.reference,300),issuedOn,expiresOn,noExpiryReason,ownerId:owner.id,reviewerId:reviewer.id,version:previous?previous.data.version+1:1,previousId:previous?.id||'',state:'pending',suggestedRequirement:previous?.data.requiredForPurchase||false,objectKey:key,filename:file.name,size:file.size,sha256:hash,actor:u.userId,uploadSignature:signature,history:[{mode:'upload',actor:u.userId,at:now}]};
 const guards=[supplier,link,previous,capa].filter(Boolean).map(e=>db.prepare('UPDATE inventory_operations SET guard=CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN guard ELSE 0 END WHERE id=?').bind(e.id,e.revision,id));
 await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'supplier_document',?,?,?,1)").bind(id,signature,u.userId,now),...guards,db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,'supplier_document',?,1,?,?)").bind(id,JSON.stringify(data),now,now),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,supplier.id,'supplier_document',JSON.stringify({id,linkId:link?.id||'',filename:file.name,sha256:hash}),now)]);
 try{await syncSupplierQuality();}catch{console.error('Supplier document task projection deferred');}return json({saved:true,id},201);
 }catch(e){if(key&&id)try{const saved:any=await storage().prepare('SELECT data FROM flow_entities WHERE id=?').bind(id).first();if(saved&&JSON.parse(saved.data).objectKey===key)return json({saved:true,id},201);await firmwareBucket().delete(key);}catch{console.error('Supplier file reconciliation deferred');}return accessResponse(e)||json({error:'مدرک ثبت نشد؛ فهرست را تازه کنید و با همان شناسه دوباره تلاش کنید.'},409)}}
