import {syncQmsTasks} from '@/lib/qms-tasks';
import {requireAccess,checkOrigin,accessResponse} from '@/lib/authorization';
import {boundedBody} from '@/lib/firmware-storage';
import {storage} from '@/lib/storage';
import {leadMembers} from '@/lib/sales-leads';
import {qtoday,qactor,qrows,qvisible,qpresent,applyQms,qpermission,designMember} from '@/lib/qms';
import {qmsKinds,qmsRoles,qmsStates,qmsHelp,QMS_PART_SIZE} from '@/lib/qms-contract';
export const qheaders={'Cache-Control':'private, no-store','Vary':'Cookie, Authorization','X-Content-Type-Options':'nosniff'};
export async function GET(){try{const u=await requireAccess(),members=await leadMembers(),a=await qactor(u,members),rows=await qrows(),visible=rows.filter(r=>r.type!=='qms_part'&&qvisible(r,a,rows));const products=(await storage().prepare("SELECT id,payload FROM records WHERE kind='product'").all()).results.map((p:any)=>({id:p.id,name:JSON.parse(p.payload).name||JSON.parse(p.payload).code}));const today=qtoday(),records=visible.filter(r=>r.type==='qms_record');if(visible.some(r=>r.type==='qms_record'&&r.data.private))await storage().prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,'qms','qms_read','{}',new Date().toISOString()).run();return Response.json({records:visible.map(qpresent),products,me:a.id,design:a.design,ceo:a.ceo,admin:a.admin,roles:a.roles,members:members.filter(m=>qpermission(m)).map(m=>({id:m.id,name:m.name,design:designMember(m),roles:qpermission(m)?.qmsRoles||[],ceo:qpermission(m)?.supplyRoles?.includes('ceo')||false})),kinds:Object.fromEntries(Object.entries(qmsKinds).filter(([,k])=>!k.private||a.design)),roleLabels:qmsRoles,states:qmsStates,help:qmsHelp,partSize:QMS_PART_SIZE,summary:{total:records.length,review:records.filter(r=>r.data.state==='review').length,overdue:records.filter(r=>!['closed','superseded'].includes(r.data.state)&&r.data.due<today).length,expiring:records.filter(r=>r.data.state==='approved'&&r.data.values?.expires&&r.data.values.expires<=new Date(Date.now()+30*86400000).toISOString().slice(0,10)).length}},{headers:qheaders});}catch(e){return accessResponse(e)||Response.json({error:'دریافت پرونده‌های کیفیت ممکن نشد.'},{status:503,headers:qheaders})}}
export async function POST(request:Request){try{checkOrigin(request);const result=await applyQms(await requireAccess(),JSON.parse(new TextDecoder().decode(await boundedBody(request,256000))));let followupPending=false;try{await syncQmsTasks()}catch{followupPending=true}return Response.json({...result,followupPending},{headers:qheaders});}catch(e){return accessResponse(e)||Response.json({error:'ثبت انجام نشد؛ اطلاعات را تازه کنید و دوباره تلاش کنید.'},{status:409,headers:qheaders})}}
