import {requireAccess,checkOrigin,AccessError,accessResponse} from '@/lib/authorization';
import {storage} from '@/lib/storage';
import {boundedBody} from '@/lib/firmware-storage';
import {moneyMicro,moneyText,calculateCosts} from '@/lib/costing';
import {projectRoles,projectReport,projectHelp} from '@/lib/build-projects';
import {holdChecks,supplyLock} from '@/lib/sourcing';
import {tehranDay} from '@/lib/serials';
const fail=(m:string,s=400):never=>{throw new AccessError(m,s)};
const txt=(v:any,max=2000)=>{if(typeof v!=='string'||!v.trim()||v.length>max)fail('متن الزامی یا نامعتبر است.');return v.trim();};
const amount=(v:any)=>{try{return moneyText(moneyMicro(v));}catch{return fail('مبلغ ریالی نامنفی لازم است.');}};
const qty=(v:any)=>{if(typeof v!=='string'||!/^\d{1,9}(\.\d{1,3})?$/.test(v))fail('مقدار معتبر با حداکثر سه اعشار لازم است.');const n=Math.round(Number(v)*1000);if(n<=0)fail('مقدار مثبت لازم است.');return n;};
const day=(v:any)=>{const s=txt(v,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(Date.parse(s))||new Date(s).toISOString().slice(0,10)!==s)fail('تاریخ معتبر لازم است.');return s;};
const arr=(v:any,n=100)=>{if(!Array.isArray(v)||v.length>n)fail('فهرست معتبر لازم است.');return v;};
const json=(v:any)=>Response.json(v,{headers:{'Cache-Control':'private, no-store'}});
async function source(){const db=storage();const [e,r,b,en,op,orders,slots,holds,members]=await Promise.all([db.prepare('SELECT * FROM flow_entities ORDER BY id').all(),db.prepare("SELECT * FROM records WHERE kind IN ('product','batch','device') ORDER BY id").all(),db.prepare('SELECT * FROM bom_versions ORDER BY version DESC,id').all(),db.prepare('SELECT * FROM inventory_entries ORDER BY id').all(),db.prepare('SELECT rowid AS sequence,* FROM inventory_operations WHERE id IN (SELECT operation_id FROM inventory_entries) ORDER BY created,rowid').all(),db.prepare('SELECT * FROM production_orders ORDER BY id').all(),db.prepare('SELECT * FROM flow_slots ORDER BY location').all(),db.prepare('SELECT * FROM sourcing_holds ORDER BY id').all(),db.prepare("SELECT id,name,permissions FROM app_members WHERE status='active'").all()]);return {entities:e.results.map((x:any)=>({...x,data:JSON.parse(x.data)})),records:r.results,boms:b.results,entries:en.results,operations:op.results,orders:orders.results,slots:slots.results as any[],holds:holds.results as any[],members:members.results as any[]};}
async function token(s:any,p:any){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify({p:{...p,closes:undefined,history:undefined},entries:s.entries,purchasedServices:s.entities.filter((x:any)=>x.type==='purchase_service'||x.type==='purchase_payable'),prices:s.entities.filter((x:any)=>x.type==='cost_price'),records:s.records,expenses:s.entities.filter((e:any)=>e.type==='expense_register'&&p.expenses.some((x:any)=>!x.voided&&x.sourceId===e.id))}))))).map(x=>x.toString(16).padStart(2,'0')).join('');}
function publicProject(r:any,financial:boolean){if(financial)return r;const d=structuredClone(r.data);delete d.contractAmount;delete d.budgets;delete d.remaining;delete d.closes;d.times=d.times.map(({rate,...t}:any)=>t);d.expenses=d.expenses.map(({amount,shares,...e}:any)=>e);d.commitments=d.commitments.map(({amount,...c}:any)=>c);d.history=d.history.filter((h:any)=>!['budget','expense','approve_time','commitment','close_commitment','void','close'].includes(h.mode));return {...r,data:d};}
export async function GET(){try{const u=await requireAccess(),roles=projectRoles(u);if(!roles.read)fail('دسترسی پروژه ساخت ندارید.',403);const s=await source(),costs=roles.financial?calculateCosts(s):null;const projects=await Promise.all(s.entities.filter((x:any)=>x.type==='build_project').map(async(p:any)=>{const t=roles.financial?await token(s,p.data):'';return {...publicProject(p,roles.financial),...(roles.financial?{report:projectReport(p.data,costs,s.entities,p.id),token:t,closes:p.data.closes.map((c:any)=>({...c,stale:c.token!==t}))}:{})};}));
 return json({roles,projects,materials:s.entities.filter((x:any)=>x.type==='material').map((x:any)=>({id:x.id,code:x.data.code,name:x.data.name,unit:x.data.unit})),boms:s.boms,products:s.records.filter((r:any)=>r.kind==='product').map((r:any)=>({id:r.id,...JSON.parse(r.payload)})),batches:s.records.filter((r:any)=>r.kind==='batch').map((r:any)=>({id:r.id,...JSON.parse(r.payload)})),slots:s.slots,holds:s.holds,members:s.members.map((m:any)=>({id:m.id,name:m.name})),purchaseOrders:s.entities.filter((r:any)=>r.type==='purchase_order').map((r:any)=>({id:r.id,title:r.data.partCode+' · '+r.data.supplier,state:r.data.state})),expenses:roles.finance?s.entities.filter((r:any)=>r.type==='expense_register'&&r.data.state==='approved'):[],help:projectHelp});
 }catch(e){return accessResponse(e)||Response.json({error:'خواندن پروژه‌ها ممکن نشد.'},{status:503});}}
export async function POST(request:Request){try{checkOrigin(request);const u=await requireAccess(),roles=projectRoles(u);if(!roles.read)fail('دسترسی پروژه ندارید.',403);const b=JSON.parse(new TextDecoder().decode(await boundedBody(request,160000)));if(b.confirmed!==true||typeof b.id!=='string'||! /^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(b.id))fail('تأیید و UUID معتبر لازم است.');const db=storage(),signature=JSON.stringify(b),prior:any=await db.prepare('SELECT payload,actor FROM inventory_operations WHERE id=?').bind(b.id).first();if(prior){if(prior.payload!==signature||prior.actor!==u.userId)fail('شناسه تکراری نامعتبر است.',409);return json({saved:true,repeated:true});}
 const s=await source(),old=s.entities.find((r:any)=>r.type==='build_project'&&r.id===b.projectId);if(b.projectId&&!old)fail('پروژه یافت نشد.',404);if(b.revision!==(old?.revision||0))fail('نسخه پروژه تغییر کرده است.',409);const id=old?.id||b.id,now=new Date().toISOString(),notes=txt(b.notes,4000),stamp={actor:u.userId,name:u.name,at:now,notes};let p:any=old?structuredClone(old.data):null;const stmts:any[]=[],guards:any[]=[],touched:string[]=[];
 const need=(role:string)=>{if(!(roles as any)[role])fail('دسترسی مرحله '+role+' لازم است.',403);};
 const guard=(q:string,...a:any[])=>guards.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN '+q+' THEN guard ELSE 0 END WHERE id=?').bind(...a,b.id));
 guard('COALESCE((SELECT revision FROM flow_entities WHERE id=?),0)=?',id,old?.revision||0);
 const unit=()=>{const x=p.units.find((x:any)=>x.id===b.unitId);if(!x)fail('تجهیز پروژه یافت نشد.');return x;};
 const member=(mid:string)=>{const m:any=s.members.find((m:any)=>m.id===mid);if(!m)fail('کاربر فعال انتخاب کنید.');return m;};
 const material=(mid:string)=>{const m=s.entities.find((m:any)=>m.type==='material'&&m.id===mid);if(!m)fail('کالای معتبر انتخاب کنید.');return m;};
 const find=(key:string)=>{const x=p[key].find((x:any)=>x.id===b.itemId&&!x.voided);if(!x)fail('ردیف یافت نشد.');return x;};
 const entry=(bid:string,wh:string,n:number)=>{touched.push(bid);stmts.push(db.prepare('INSERT INTO inventory_balances(id,item_id,warehouse,quantity) VALUES(?,?,?,0) ON CONFLICT(item_id,warehouse) DO NOTHING').bind(bid+'@'+wh,bid,wh),db.prepare('UPDATE inventory_balances SET quantity=quantity+? WHERE item_id=? AND warehouse=?').bind(n,bid,wh),db.prepare('INSERT INTO inventory_entries(id,operation_id,item_id,warehouse,delta) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),b.id,bid,wh,n));};
 if(b.mode==='create'){need('engineering');const owner=member(txt(b.ownerId,200));if(!projectRoles({isAdmin:false,permissions:JSON.parse(owner.permissions)}).read)fail('مسئول باید دسترسی پروژه داشته باشد.');p={title:txt(b.title,200),customer:txt(b.customer,200),contract:txt(b.contract,500),due:day(b.due),ownerId:owner.id,state:'open',units:[],budgets:[],remaining:null,requests:[],movements:[],times:[],expenses:[],commitments:[],issues:[],closes:[],history:[]};}
 else{if(!p)fail('ابتدا پروژه بسازید.');if(p.state==='closed'&&b.mode!=='reopen')fail('پروژه بسته است؛ مالی باید بازگشایی کند.');
 if(b.mode==='unit'){need('engineering');const title=txt(b.title,200),bom=s.boms.find((x:any)=>x.id===b.bomId);if(b.bomId&&!bom)fail('BOM پایه یافت نشد.');const lines=bom?JSON.parse(bom.lines as string).map((l:any)=>{const m=s.entities.find((m:any)=>m.type==='material'&&m.data.code===l.partCode&&m.data.unit===l.unit);if(!m)fail('کالای BOM در شناسنامه مواد یافت نشد: '+l.partCode);return {id:crypto.randomUUID(),materialId:m.id,partCode:m.data.code,name:m.data.name,unit:m.data.unit,quantity:qty(String(l.quantity))};}):[];p.units.push({id:b.id,title,bomId:b.bomId||'',bomVersion:bom?.version||null,lines,versions:[{number:1,lines:structuredClone(lines),...stamp}],approved:null,quality:null});}
 else if(b.mode==='bom'){need('engineering');const x=unit(),lines=arr(b.lines,150).map((l:any)=>{const m=material(l.materialId);return {id:l.id&&x.lines.some((v:any)=>v.id===l.id)?l.id:crypto.randomUUID(),materialId:m.id,partCode:m.data.code,name:m.data.name,unit:m.data.unit,quantity:qty(l.quantity)};});if(!lines.length||new Set(lines.map((l:any)=>l.materialId)).size!==lines.length)fail('اقلام یکتا لازم است.');for(const l of x.lines){const used=p.requests.filter((r:any)=>r.unitId===x.id&&r.lineId===l.id&&r.state!=='cancelled').reduce((n:number,r:any)=>n+r.quantity,0);const changed=lines.find((n:any)=>n.id===l.id);if(used&&(!changed||changed.materialId!==l.materialId||changed.quantity<used))fail('مقدار یا هویت اقلام دارای درخواست فعال قابل حذف/کاهش نیست.');}x.lines=lines;x.versions.push({number:x.versions.length+1,lines:structuredClone(lines),...stamp});x.approved=null;x.quality=null;}
 else if(b.mode==='approve_bom'){need('manager');const x=unit();if(!x.lines.length)fail('فهرست قطعات خالی است.');x.approved={version:x.versions.length,...stamp};}
 else if(b.mode==='budget'){need('finance');p.budgets.push({amount:amount(b.amount),...stamp});p.contractAmount=amount(b.contractAmount);p.remaining=amount(b.remaining);}
 else if(b.mode==='request'){if(!roles.production&&!roles.engineering)fail('دسترسی تولید/مهندسی لازم است.',403);const x=unit();if(!x.approved)fail('BOM باید تأیید شود.');const l=x.lines.find((l:any)=>l.id===b.lineId);if(!l)fail('ردیف BOM معتبر لازم است.');const n=qty(b.quantity),used=p.requests.filter((r:any)=>r.unitId===x.id&&r.lineId===l.id&&r.state!=='cancelled').reduce((v:number,r:any)=>v+r.quantity,0);if(used+n>l.quantity)fail('مقدار از BOM بیشتر است؛ ابتدا تغییر مهندسی را ثبت و تأیید کنید.');p.requests.push({id:b.id,unitId:x.id,lineId:l.id,materialId:l.materialId,partCode:l.partCode,unit:l.unit,quantity:n,state:'pending',lots:[],...stamp});x.quality=null;}
 else if(b.mode==='reserve'){
 need('warehouse');const r=find('requests');if(r.state!=='pending')fail('درخواست باید در انتظار انبار باشد.');const list=arr(b.allocations,50),seen=new Set();let total=0;
 r.lots=list.map((a:any)=>{const q=qty(a.quantity),loc=txt(a.location,100),slot=s.slots.find((v:any)=>v.location===loc&&v.batch_id===a.batchId);if(seen.has(loc)||!slot||slot.quantity<q)fail('محل تکراری یا موجودی ناکافی است.');seen.add(loc);const rec=s.entities.find((v:any)=>v.type==='receipt'&&v.data.batchId===a.batchId),batch:any=s.records.find((v:any)=>v.id===a.batchId&&v.kind==='batch');if(!rec||rec.data.state!=='stored'||rec.data.materialId!==r.materialId||rec.data.expiry&&rec.data.expiry<tehranDay()||!batch||JSON.parse(batch.payload).status!=='تأیید')fail('بچ تأییدشده و غیرمنقضی همین کالا لازم است.');guard('EXISTS(SELECT 1 FROM flow_slots WHERE location=? AND batch_id=? AND quantity>=?)',loc,a.batchId,q);guard('EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?)',rec.id,rec.revision);guard('EXISTS(SELECT 1 FROM records WHERE id=? AND payload=?)',batch.id,batch.payload);
 const hid='project-hold:'+id+':'+a.batchId;stmts.push(db.prepare("INSERT INTO sourcing_holds(id,plan_id,part_code,unit,source_type,source_id,quantity) VALUES(?,?,?,?,'stock',?,?) ON CONFLICT(plan_id,source_type,source_id) DO UPDATE SET quantity=sourcing_holds.quantity+excluded.quantity").bind(hid,id,r.partCode,r.unit,a.batchId,q));touched.push(a.batchId);total+=q;return {id:crypto.randomUUID(),batchId:a.batchId,location:loc,quantity:q};});if(total!==r.quantity)fail('جمع رزرو باید برابر درخواست باشد.');r.state='reserved';r.reserved=stamp;
 }else if(b.mode==='shortage'){
 need('warehouse');const r=find('requests');if(r.state!=='pending')fail('فقط درخواست در انتظار انبار به تأمین ارجاع می‌شود.');const m=material(r.materialId);const bidSet=new Set(s.records.filter((v:any)=>v.kind==='batch'&&JSON.parse(v.payload).partCode===r.partCode).map((v:any)=>v.id));let available=0;for(const bid of bidSet){const raw=s.slots.filter((v:any)=>v.batch_id===bid).reduce((n:number,v:any)=>n+v.quantity,0),held=s.holds.filter((h:any)=>h.source_type==='stock'&&h.source_id===bid).reduce((n:number,h:any)=>n+h.quantity,0);available+=Math.max(0,raw-held);}const shortage=Math.max(0,r.quantity-available);if(!shortage)fail('کسری موجودی مشاهده نشد.');const existing=s.entities.find((x:any)=>x.type==='supply'&&x.data.materialId===r.materialId&&x.data.state==='open');if(existing){r.supplyId=existing.id;}else{r.supplyId=b.id;stmts.push(db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,'supply',?,1,?,?)").bind(b.id,JSON.stringify({materialId:m.id,snapshot:m.data,quantity:shortage,notes,projectId:id,requestId:r.id,state:'open',owner:m.data.procurementOwner||'',by:u.name}),now,now));}r.shortage={quantity:shortage,...stamp};
 }else if(b.mode==='issue'||b.mode==='cancel_request'){
 need('warehouse');const r=find('requests');if(b.mode==='issue'&&r.state!=='reserved'||b.mode==='cancel_request'&&!['pending','reserved'].includes(r.state))fail('وضعیت درخواست مجاز نیست.');
 const grouped=new Map<string,number>();for(const l of r.lots)grouped.set(l.batchId,(grouped.get(l.batchId)||0)+l.quantity);
 for(const [bid,q] of grouped){const h:any=s.holds.find((h:any)=>h.plan_id===id&&h.source_type==='stock'&&h.source_id===bid);if(!h||h.quantity<q)fail('رزرو معتبر وجود ندارد.');guard('EXISTS(SELECT 1 FROM sourcing_holds WHERE id=? AND quantity=?)',h.id,h.quantity);stmts.push(h.quantity===q?db.prepare('DELETE FROM sourcing_holds WHERE id=?').bind(h.id):db.prepare('UPDATE sourcing_holds SET quantity=quantity-? WHERE id=?').bind(q,h.id));}
 if(b.mode==='issue'){for(const l of r.lots){const rec=s.entities.find((v:any)=>v.type==='receipt'&&v.data.batchId===l.batchId);if(!rec||rec.data.state!=='stored'||rec.data.expiry&&rec.data.expiry<tehranDay())fail('وضعیت یا انقضای بچ را بررسی کنید.');const batch:any=s.records.find((v:any)=>v.id===l.batchId);if(!batch||JSON.parse(batch.payload).status!=='تأیید')fail('بچ دیگر قابل تحویل نیست.');guard('EXISTS(SELECT 1 FROM records WHERE id=? AND payload=?)',batch.id,batch.payload);guard('EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?)',rec.id,rec.revision);guard('EXISTS(SELECT 1 FROM flow_slots WHERE location=? AND batch_id=? AND quantity>=?)',l.location,l.batchId,l.quantity);stmts.push(db.prepare('UPDATE flow_slots SET quantity=quantity-? WHERE location=?').bind(l.quantity,l.location));entry(l.batchId,'raw',-l.quantity);entry(l.batchId,'project:'+id,l.quantity);}r.state='issued';r.issued=stamp;}else r.state='cancelled';
 }else if(['consume','return','scrap'].includes(b.mode)){
 if(b.mode==='return')need('warehouse');else if(!roles.production&&!roles.engineering)fail('دسترسی تولید لازم است.',403);const r=p.requests.find((r:any)=>r.state==='issued'&&r.lots.some((l:any)=>l.id===b.lotId)),l=r?.lots.find((l:any)=>l.id===b.lotId);if(!l)fail('قطعه تحویل‌شده یافت نشد.');const q=qty(b.quantity),used=p.movements.filter((m:any)=>m.lotId===l.id).reduce((n:number,m:any)=>n+m.quantity,0);if(q>l.quantity-used)fail('مقدار از موجودی نزد پروژه بیشتر است.');entry(l.batchId,'project:'+id,-q);
 if(b.mode==='return'){const loc=txt(b.location,100);if(!/^[^\s]+-[^\s]+-[^\s]+-[^\s]+$/.test(loc))fail('محل انبار چهار بخش داشته باشد.');const batch:any=s.records.find((r:any)=>r.id===l.batchId);if(!batch||JSON.parse(batch.payload).status!=='تأیید')fail('بازگشت مستقیم فقط برای بچ سالم تأییدشده است.');guard('NOT EXISTS(SELECT 1 FROM flow_slots WHERE location=? AND quantity>0 AND batch_id<>?)',loc,l.batchId);stmts.push(db.prepare('INSERT INTO flow_slots(location,batch_id,quantity) VALUES(?,?,?) ON CONFLICT(location) DO UPDATE SET batch_id=excluded.batch_id,quantity=flow_slots.quantity+excluded.quantity').bind(loc,l.batchId,q));entry(l.batchId,'raw',q);}
 if(b.mode==='scrap')entry(l.batchId,'nonconforming',q);
 p.movements.push({id:b.id,operationId:b.id,unitId:r.unitId,lotId:l.id,batchId:l.batchId,quantity:q,kind:b.mode,...stamp});p.units.find((x:any)=>x.id===r.unitId).quality=null;
 }else if(b.mode==='time'){
 if(!roles.production&&!roles.engineering&&!roles.finance)fail('دسترسی ثبت زمان لازم است.',403);const x=unit(),m=member(txt(b.memberId,200));if(!Number.isSafeInteger(b.minutes)||b.minutes<1||b.minutes>1440)fail('دقیقه معتبر لازم است.');const date=day(b.day),sum=s.entities.filter((r:any)=>r.type==='build_project').reduce((n:number,r:any)=>n+r.data.times.filter((t:any)=>!t.voided&&t.memberId===m.id&&t.day===date).reduce((a:number,t:any)=>a+t.minutes,0),0);if(sum+b.minutes>1440)fail('جمع زمان فرد در روز بیشتر از ۲۴ ساعت است.');p.times.push({id:b.id,unitId:x.id,memberId:m.id,day:date,minutes:b.minutes,approved:null,rate:null,...stamp});
 }else if(b.mode==='approve_time'){need('finance');const t=find('times');t.rate=amount(b.rate);t.approved=stamp;}
 else if(b.mode==='expense'){
 need('finance');const reference=txt(b.reference,500);if(s.entities.filter((r:any)=>r.type==='build_project').some((r:any)=>r.data.expenses.some((e:any)=>!e.voided&&e.reference===reference)))fail('مرجع هزینه قبلاً به پروژه تخصیص یافته است؛ از ثبت دوباره جلوگیری کنید.',409);
 if(!['manufacturing','execution','loss'].includes(b.bucket))fail('نوع احتساب هزینه معتبر نیست.');let value=amount(b.amount),sourceId=b.sourceId||'',lineIndex=b.lineIndex,sourceRevision=0;
 if(sourceId){const e=s.entities.find((e:any)=>e.type==='expense_register'&&e.id===sourceId&&e.data.state==='approved');if(!e||!Number.isSafeInteger(lineIndex)||!e.data.lines[lineIndex])fail('ردیف هزینه تأییدشده لازم است.');const l=e.data.lines[lineIndex];if(l.treatment!=='period'&&l.treatment!=='production')fail('خرید موجودی/دارایی یا پیش‌پرداخت را دوباره هزینه پروژه نکنید.');if(s.entities.filter((r:any)=>r.type==='build_project').some((r:any)=>r.data.expenses.some((e:any)=>!e.voided&&e.sourceId===sourceId&&e.lineIndex===lineIndex)))fail('این ردیف قبلاً مصرف شده است.');value=l.amount;sourceRevision=e.revision;}
 let rawShares=b.shares,allocationMethod=b.allocationMethod||'manual';if(!['manual','time'].includes(allocationMethod))fail('روش تخصیص معتبر نیست.');if(allocationMethod==='time'){const times=p.times.filter((t:any)=>!t.voided);if(times.some((t:any)=>!t.approved))fail('ابتدا زمان‌ها و نرخ‌ها را تأیید کنید.');const total=times.reduce((n:number,t:any)=>n+t.minutes,0);if(!total)fail('زمان تأییدشده لازم است.');let used=BigInt(0);rawShares=p.units.map((u:any,n:number)=>{const minutes=times.filter((t:any)=>t.unitId===u.id).reduce((a:number,t:any)=>a+t.minutes,0),share=n===p.units.length-1?moneyMicro(value)-used:moneyMicro(value)*BigInt(minutes)/BigInt(total);used+=share;return {unitId:u.id,amount:moneyText(share)};});}
 const shares=arr(rawShares,100).map((a:any)=>{if(!p.units.some((x:any)=>x.id===a.unitId))fail('تجهیز تخصیص معتبر نیست.');return {unitId:a.unitId,amount:amount(a.amount)};});if(new Set(shares.map((a:any)=>a.unitId)).size!==shares.length||!shares.length||shares.reduce((n:bigint,a:any)=>n+moneyMicro(a.amount),BigInt(0))!==moneyMicro(value))fail('جمع سهم تجهیزات باید دقیقاً برابر مبلغ هزینه باشد.');p.expenses.push({id:b.id,title:txt(b.title),reference,amount:value,bucket:b.bucket,sourceId,sourceRevision,lineIndex:lineIndex??null,shares,allocationMethod,timeBasis:allocationMethod==='time'?JSON.stringify(p.times.filter((t:any)=>!t.voided).map((t:any)=>({id:t.id,minutes:t.minutes,unitId:t.unitId}))):null,basis:txt(b.basis),approved:stamp,...stamp});
 }else if(b.mode==='commitment'){need('finance');const order=b.orderId?s.entities.find((r:any)=>r.type==='purchase_order'&&r.id===b.orderId):null;if(b.orderId&&!order)fail('سفارش خرید معتبر لازم است.');if(b.orderId&&s.entities.filter((r:any)=>r.type==='build_project').some((r:any)=>r.data.commitments.some((c:any)=>!c.closed&&c.orderId===b.orderId)))fail('سفارش قبلاً در تعهد پروژه ثبت شده است.');p.commitments.push({id:b.id,title:txt(b.title),orderId:b.orderId||'',amount:amount(b.amount),closed:null,...stamp});}
 else if(b.mode==='close_commitment'){need('finance');find('commitments').closed=stamp;}
 else if(b.mode==='issue_note'){if(!roles.engineering&&!roles.finance&&!roles.production)fail('مجوز لازم است.',403);const m=member(txt(b.ownerId,200));if(!projectRoles({isAdmin:false,permissions:JSON.parse(m.permissions)}).read)fail('مسئول باید دسترسی پروژه داشته باشد.');const due=day(b.due),title=txt(b.title,200);p.issues.push({id:b.id,title,ownerId:m.id,due,resolved:null,...stamp});stmts.push(db.prepare("INSERT INTO duty_runs(id,template_id,period,assignee,supervisor,due,state,data,revision,created,updated) VALUES(?,?,?,?,NULL,?,'open',?,1,?,?)").bind('project-task:'+b.id,'build-project:'+id,b.id,m.id,due+'T13:30:00.000Z',JSON.stringify({title:'پروژه '+p.title+' · '+title,sourceSection:'build-projects',sourcePlanId:id,instructions:notes,evidence:'text',history:[]}),now,now));}
 else if(b.mode==='resolve_note'){need('finance');const x=find('issues');x.resolved=stamp;stmts.push(db.prepare("UPDATE duty_runs SET state='completed',revision=revision+1,updated=? WHERE id=?").bind(now,'project-task:'+x.id));}
 else if(b.mode==='quality'){need('quality');const x=unit();if(!x.approved)fail('BOM باید تأیید شود.');if(!p.movements.some((m:any)=>m.unitId===x.id&&m.kind==='consume'))fail('مصرف واقعی برای این تجهیز ثبت نشده است.');x.quality={reference:txt(b.reference),...stamp};}
 else if(b.mode==='void'){need('finance');if(!['times','expenses'].includes(b.kind))fail('فقط زمان یا هزینه قابل ابطال است.');find(b.kind).voided=stamp;}
 else if(b.mode==='close'){
 need('finance');if(b.completeCostsConfirmed!==true)fail('تکمیل تمام صورتحساب‌ها، زمان‌ها، سربار و تعهدات را مالی صریحاً تأیید کند.');const t=await token(s,p);if(t!==b.token)fail('منابع تغییر کرده‌اند؛ گزارش تازه را بررسی کنید.',409);const report=projectReport(p,calculateCosts(s),s.entities,id);if(!report.complete)fail(report.problems.join(' / '));p.state='closed';const closedToken=await token(s,p);p.closes.push({id:b.id,report,token:closedToken,...stamp});
 }else if(b.mode==='reopen'){need('finance');if(p.state!=='closed')fail('پروژه بسته نیست.');p.state='open';}
 else fail('عملیات معتبر نیست.');}
 // Reuse role inbox; only the domain operation completes its related work.
 const work:{key:string;role:string;title:string}[]=[];
 if(p.state!=='closed'){
 for(const x of p.units)if(!x.approved)work.push({key:'bom:'+x.id,role:'manager',title:'بررسی BOM '+x.title});
 for(const r of p.requests)if(['pending','reserved'].includes(r.state))work.push({key:'stock:'+r.id,role:'warehouse',title:r.state==='pending'?'رزرو / تأمین قطعه '+r.partCode:'تحویل قطعه '+r.partCode});
 for(const t of p.times)if(!t.voided&&!t.approved)work.push({key:'time:'+t.id,role:'finance',title:'تأیید زمان و نرخ کار'});
 }
 const recipients=(role:string)=>s.members.filter((m:any)=>role==='procurement'?JSON.parse(m.permissions).flowRoles?.includes('procurement'):(projectRoles({isAdmin:false,permissions:JSON.parse(m.permissions)}) as any)[role]);
 for(const r of p.requests)if(r.state==='pending'&&r.supplyId&&s.entities.some((x:any)=>x.id===r.supplyId&&x.data.state==='open')||r.state==='pending'&&b.mode==='shortage'&&r.id===b.itemId)work.push({key:'shortage:'+r.id,role:'procurement',title:'کسری قطعه پروژه؛ پرونده تأمین را بررسی کنید'});
 p.unassignedWork=work.filter(w=>!recipients(w.role).length).map(w=>w.title);
 stmts.push(db.prepare("UPDATE duty_runs SET state='completed',revision=revision+1,updated=? WHERE template_id=? AND state NOT IN ('completed','cancelled')").bind(now,'build-auto:'+id));
 for(const w of work)for(const m of recipients(w.role))stmts.push(db.prepare("INSERT INTO duty_runs(id,template_id,period,assignee,due,state,data,revision,created,updated) VALUES(?,?,?,?,?,'open',?,1,?,?) ON CONFLICT(id) DO UPDATE SET state='open',data=excluded.data,revision=duty_runs.revision+1,updated=excluded.updated").bind('build-auto:'+id+':'+w.key+':'+m.id,'build-auto:'+id,w.key,m.id,new Date(Date.parse(now)+48*3600000).toISOString(),JSON.stringify({title:p.title+' · '+w.title,sourceSection:w.role==='procurement'?'flow':'build-projects',sourcePlanId:w.role==='procurement'?'':id,instructions:w.title+'؛ ثبت پاسخ متنی جای اقدام در پرونده پروژه نیست.',evidence:'text',history:[]}),now,now));
 p.history.push({mode:b.mode,itemId:b.itemId||b.id,...stamp});
 // All project budgets, consumption, duplicate references and source prices are guarded atomically.
 guard('(SELECT COALESCE(SUM(revision),0) FROM flow_entities)=?',s.entities.reduce((n:number,r:any)=>n+r.revision,0));guard('(SELECT COUNT(*) FROM inventory_entries)=?',s.entries.length);
 if(b.mode==='close'){for(const r of s.records)guard('EXISTS(SELECT 1 FROM records WHERE id=? AND payload=?)',r.id,r.payload);}
 const write=old?db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=?').bind(JSON.stringify(p),now,id):db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,'build_project',?,1,?,?)").bind(id,JSON.stringify(p),now,now);
 // Parent first for project sourcing holds; movements and holds share one transaction.
 await db.batch([db.prepare('INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,?,?,?,?,1)').bind(b.id,'project_'+b.mode,signature,u.userId,now),...guards,write,...stmts,...holdChecks(db,b.id,touched),...await supplyLock(db,b.id),db.prepare('INSERT INTO access_audit(id,actor,target,action,before,after,at) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,id,'project_'+b.mode,old?JSON.stringify(old.data):null,JSON.stringify(p),now)]);return json({saved:true,id});
 }catch(e){return accessResponse(e)||Response.json({error:'ثبت انجام نشد؛ موجودی، نسخه و اطلاعات را تازه‌سازی کنید.'},{status:409});}}
