using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
namespace Nafasyar;
public class Accounts(Database database,Rules rules,IConfiguration config){
 public string Owner=>config["TRACE_OWNER_EMAIL"]?.Trim().ToLowerInvariant()??throw new Exception("TRACE_OWNER_EMAIL is required");
 public Dictionary<string,object?>? Find(string email){using var db=database.Open();return db.One("SELECT * FROM dotnet_accounts WHERE email=? OR username=?",email,email);} 
 public Actor? Resolve(ClaimsPrincipal claims){var email=claims.FindFirstValue(ClaimTypes.Email);if(email==null)return null;using var db=database.Open();var account=db.One("SELECT * FROM dotnet_accounts WHERE email=?",email);if(account==null||claims.FindFirstValue("stamp")!=(string)account["stamp"]!)return null;var sub=(string)account["subject"]!;
 if(email==Owner){var pin=db.One("SELECT subject FROM app_identity WHERE id='owner'");if(pin==null||(string)pin["subject"]! !=sub)return null;return new(sub,email,(string)account["name"]!,true,new(rules.Modules,rules.Modules,rules.Stages),Convert.ToInt64(account["must_change"])==1);}
 var member=db.One("SELECT * FROM app_members WHERE email=?",email);if(member==null||(string)member["status"]! !="active"||member["subject"]!=null&&(string)member["subject"]! !=sub)return null;
 if(member["subject"]==null)db.Exec("UPDATE app_members SET subject=? WHERE id=? AND subject IS NULL",sub,member["id"]);
 return new(sub,email,(string)member["name"]!,false,rules.Permissions(JsonNode.Parse((string)member["permissions"]!)),Convert.ToInt64(account["must_change"])==1);}
 public bool Valid(string email,string password){var account=Find(email);if(account==null)return false;return new PasswordHasher<string>().VerifyHashedPassword(email,(string)account["password_hash"]!,password)!=PasswordVerificationResult.Failed;}
 public ClaimsPrincipal Principal(Dictionary<string,object?> a)=>new(new ClaimsIdentity([new Claim(ClaimTypes.Email,(string)a["email"]!),new Claim(ClaimTypes.NameIdentifier,(string)a["subject"]!),new Claim("stamp",(string)a["stamp"]!)],"Cookies"));
 public void Password(string email,string password,string? username=null,bool mustChange=true){email=email.Trim().ToLowerInvariant();if(password.Length<12||password.Length>256)throw new ApiError("رمز باید ۱۲ تا ۲۵۶ نویسه باشد.");using var db=database.Open();db.Atomic(()=>{string subject,name;var account=db.One("SELECT * FROM dotnet_accounts WHERE email=?",email);username=(username??(string?)account?.GetValueOrDefault("username")??email.Split('@')[0]).Trim().ToLowerInvariant();if(!J.Match(username,@"^[a-z0-9._-]{3,40}$"))throw new ApiError("نام کاربری ۳ تا ۴۰ حرف انگلیسی یا عدد و . _ - باشد.");if(email==Owner){subject=(string?)db.One("SELECT subject FROM app_identity WHERE id='owner'")?.GetValueOrDefault("subject")??Guid.NewGuid().ToString();name=config["OWNER_NAME"]??"مدیر نفس‌یار";db.Exec("INSERT INTO app_identity(id,subject) VALUES('owner',?) ON CONFLICT(id) DO NOTHING",subject);}else{var m=db.One("SELECT * FROM app_members WHERE email=?",email);if(m==null||(string)m["status"]! !="active")throw new ApiError("ابتدا حساب همکار را فعال کنید.");subject=(string?)m["subject"]??(string?)account?.GetValueOrDefault("subject")??Guid.NewGuid().ToString();name=(string)m["name"]!;}
 db.Exec("INSERT INTO dotnet_accounts(email,subject,name,password_hash,stamp,username,must_change) VALUES(?,?,?,?,?,?,?) ON CONFLICT(email) DO UPDATE SET subject=excluded.subject,name=excluded.name,password_hash=excluded.password_hash,stamp=excluded.stamp,username=excluded.username,must_change=excluded.must_change",email,subject,name,new PasswordHasher<string>().HashPassword(email,password),Guid.NewGuid().ToString(),username,mustChange?1:0);return 0;});}
 object Present(Dictionary<string,object?> row){var d=new Dictionary<string,object?>(row);d["userId"]=row.GetValueOrDefault("subject");d["permissions"]=JsonNode.Parse((string)row["permissions"]!);return d;}
 public object List(Actor a){a.Admin();using var db=database.Open();return new{members=db.All("SELECT * FROM app_members ORDER BY created DESC").Select(Present)};}
 public object Save(Actor a,JsonNode b,bool update){a.Admin();var email=J.Text(b,"email").Trim().ToLowerInvariant();var name=J.Text(b,"name").Trim();var unit=J.Text(b,"unit").Trim();var status=J.Text(b,"status");if(!J.Match(email,@"^[^\s@]+@[^\s@]+\.[^\s@]+$")||email.Length>254||email==Owner||name.Length is <1 or >100||unit.Length is <1 or >100||status is not("active" or "disabled"))throw new ApiError("مشخصات حساب معتبر نیست.");var permissions=rules.Permissions(b["permissions"]);using var db=database.Open();return db.Atomic(()=>{var now=J.Now();string id;
 if(!update){id=Guid.NewGuid().ToString();db.Exec("INSERT INTO app_members(id,email,name,unit,status,permissions,revision,created,updated) VALUES(?,?,?,?,?,?,1,?,?)",id,email,name,unit,status,J.Write(permissions),now,now);db.Audit(a,id,"create_member",db.One("SELECT * FROM app_members WHERE id=?",id));}else{id=J.Text(b,"id");var old=db.One("SELECT * FROM app_members WHERE id=?",id)??throw new ApiError("حساب یافت نشد.",404);if((string)old["email"]! !=email)throw new ApiError("ایمیل ثابت است.");if(Convert.ToInt64(old["revision"])!=b["revision"]?.GetValue<long>())throw new ApiError("حساب تغییر کرده است.",409);db.Exec("UPDATE app_members SET name=?,unit=?,status=?,permissions=?,updated=?,revision=revision+1 WHERE id=?",name,unit,status,J.Write(permissions),now,id);db.Audit(a,id,"update_member",db.One("SELECT * FROM app_members WHERE id=?",id),J.Write(old));}return new{member=Present(db.One("SELECT * FROM app_members WHERE id=?",id)!)};});}
}
