namespace Nafasyar;
public class AccountPages(Database database,Accounts accounts,Rules rules){
 static string Field(string label,string name,string value="",string type="text",bool required=true)=>$"<label>{J.Esc(label)}<input name='{name}' type='{type}' value='{J.Esc(value)}' {(required?"required":"")} {(type=="password"?"minlength='12' maxlength='256' autocomplete='new-password'":"")} dir='ltr'></label>";
 public static string Shell(string title,string body)=>"<!doctype html><html lang='fa' dir='rtl'><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>"+J.Esc(title)+"</title><style>body{font:16px Tahoma;line-height:1.9;background:#f4f6fb;color:#25346b;margin:0}main{max-width:850px;margin:30px auto;background:white;border:1px solid #dce3ef;border-radius:18px;padding:28px}label{display:block;margin:10px 0}input,select,button{font:inherit}input:not([type=checkbox]),select{box-sizing:border-box;width:100%;padding:10px;border:1px solid #ccd5e5;border-radius:8px}button,a.btn{display:inline-block;background:#16804a;color:white;padding:10px 18px;border:0;border-radius:8px;cursor:pointer;margin:12px 0;text-decoration:none}a{color:#364c9a}img{width:150px}form,details{padding:18px;border:1px solid #e2e8f0;border-radius:12px;margin:16px 0}.checks{display:flex;gap:18px;flex-wrap:wrap}.checks label{display:inline-flex;align-items:center;gap:7px}.notice{padding:14px;background:#fff1d9;color:#70430c}summary{cursor:pointer;font-weight:bold}h1{font-size:24px}h2{font-size:19px}p{overflow-wrap:anywhere}@media(max-width:600px){main{margin:12px;padding:16px}}</style><main><img src='/brand/nafasyar-logo.png' alt='نفس‌یار'><h1>"+J.Esc(title)+"</h1>"+body+"</main></html>";
 public string Login(string message="")=>Shell("ورود به سامانه نفس‌یار",(message==""?"":"<p class='notice'>"+J.Esc(message)+"</p>")+"<form method='post' action='/login'>"+Field("نام کاربری یا ایمیل","login")+Field("رمز عبور","password","","password")+"<button>ورود</button></form>");
 string PermissionFields(Permissions? p=null){p??=new([],[],[]);return "<h3>سطح دسترسی</h3>"+string.Concat(rules.Modules.Select(k=>"<div class='checks'><strong>"+J.Esc(k switch {"product"=>"محصولات","device"=>"دستگاه‌ها و سریال","batch"=>"قطعات و بچ‌ها","event"=>"رویدادهای تولید","service"=>"خدمات پس از فروش","action"=>"اقدامات اصلاحی","distribution"=>"نماینده و مشتری","firmware"=>"نسخه‌های نرم‌افزار",_=>k})+"</strong><label><input type='checkbox' name='read' value='"+k+"' "+(p.Read.Contains(k)?"checked":"")+">مشاهده</label><label><input type='checkbox' name='write' value='"+k+"' "+(p.Write.Contains(k)?"checked":"")+">ثبت و ویرایش</label></div>"))+"<p>ثبت شامل مشاهده همان بخش است. برای رویدادهای تولید، مرحله مجاز را نیز انتخاب کنید.</p><div class='checks'>"+string.Concat(rules.Stages.Select(s=>"<label><input type='checkbox' name='stage' value='"+J.Esc(s)+"' "+(p.EventStages.Contains(s)?"checked":"")+">"+J.Esc(s)+"</label>"))+"</div>";}
 public Permissions ParsePermissions(IFormCollection f){var read=f["read"].Select(x=>x!).ToHashSet();var write=f["write"].Select(x=>x!).ToArray();read.UnionWith(write);if(write.Contains("device"))read.Add("product");if(write.Any(k=>k is "event" or "service" or "action")){read.Add("device");read.Add("batch");}if(read.Contains("distribution"))read.Add("device");return rules.Permissions(JsonSerializer.SerializeToNode(new Permissions(read.ToArray(),write,f["stage"].Select(x=>x!).ToArray()),J.Options));}
 public string Home(Actor a){using var db=database.Open();var own=db.One("SELECT username FROM dotnet_accounts WHERE email=?",a.Email)!;var body=(a.MustChange?"<p class='notice'>قبل از استفاده از سامانه، رمز اولیه را تغییر دهید. می‌توانید نام کاربری را هم همین‌جا عوض کنید.</p>":"<a class='btn' href='/'>بازگشت به برنامه</a>")+"<form method='post' action='/account/change'><h2>نام کاربری و رمز خودم</h2>"+Field("نام کاربری","username",(string)own["username"]!)+Field("رمز فعلی","currentPassword","","password")+Field("رمز جدید","password","","password")+Field("تکرار رمز جدید","confirmPassword","","password")+"<button>ذخیره و ورود مجدد</button></form>";
 if(a.IsAdmin&&!a.MustChange){body+="<form method='post' action='/account/create'><h2>ساخت حساب همکار</h2>"+Field("نام و نام خانوادگی","name")+Field("واحد","unit")+Field("ایمیل","email","","email")+Field("نام کاربری","username")+Field("رمز اولیه","password","","password")+PermissionFields()+"<button>ساخت حساب و رمز</button></form>";
 foreach(var m in db.All("SELECT m.*,a.username FROM app_members m LEFT JOIN dotnet_accounts a ON a.email=m.email ORDER BY m.created DESC")){var email=(string)m["email"]!;body+="<details><summary>"+J.Esc((string)m["name"]!)+" · "+J.Esc(email)+"</summary><form method='post' action='/account/reset'><input type='hidden' name='email' value='"+J.Esc(email)+"'><h3>نام کاربری و بازنشانی رمز</h3>"+Field("نام کاربری","username",(string?)m["username"]??"")+Field("رمز اولیه جدید","password","","password")+"<button>تعیین رمز جدید</button></form><form method='post' action='/account/permissions'><input type='hidden' name='id' value='"+J.Esc((string)m["id"]!)+"'><input type='hidden' name='revision' value='"+m["revision"]+"'><input type='hidden' name='email' value='"+J.Esc(email)+"'>"+Field("نام","name",(string)m["name"]!)+Field("واحد","unit",(string)m["unit"]!)+"<label>وضعیت<select name='status'><option value='active' "+((string)m["status"]! =="active"?"selected":"")+">فعال</option><option value='disabled' "+((string)m["status"]! =="disabled"?"selected":"")+">غیرفعال</option></select></label>"+PermissionFields(rules.Permissions(JsonNode.Parse((string)m["permissions"]!)))+"<button>ذخیره دسترسی‌ها</button></form></details>";}}
 return Shell("حساب و دسترسی کاربران",body+"<form method='post' action='/logout'><button>خروج از حساب</button></form>");}
 public void Change(Actor a,IFormCollection f){var current=f["currentPassword"].ToString();var password=f["password"].ToString();if(!accounts.Valid(a.Email,current))throw new ApiError("رمز فعلی درست نیست.",403);if(password!=f["confirmPassword"].ToString()||password==current)throw new ApiError("رمز جدید باید متفاوت باشد و تکرار آن تطابق داشته باشد.");accounts.Password(a.Email,password,f["username"],false);using var db=database.Open();db.Audit(a,a.UserId,"change_own_credentials",new{username=f["username"].ToString()});}
 public void Reset(Actor a,IFormCollection f){a.Admin();if(f["email"].ToString().ToLowerInvariant()==accounts.Owner)throw new ApiError("رمز خود را از بخش حساب شخصی تغییر دهید.");accounts.Password(f["email"]!,f["password"]!,f["username"]!);using var db=database.Open();db.Audit(a,f["email"]!,"reset_member_credentials",new{username=f["username"].ToString(),mustChange=true});}
 public void Member(Actor a,IFormCollection f,bool update){
 a.Admin();var perms=ParsePermissions(f);
 var email=f["email"].ToString().Trim().ToLowerInvariant();var name=f["name"].ToString().Trim();var unit=f["unit"].ToString().Trim();
 if(update){var body=new JsonObject{["email"]=email,["name"]=name,["unit"]=unit,["status"]=f["status"].ToString(),["id"]=f["id"].ToString(),["revision"]=long.Parse(f["revision"]!),["permissions"]=JsonSerializer.SerializeToNode(perms,J.Options)};accounts.Save(a,body,true);return;}
 var password=f["password"].ToString();var username=f["username"].ToString().Trim().ToLowerInvariant();
 if(password.Length is <12 or >256||!J.Match(username,@"^[a-z0-9._-]{3,40}$")||!J.Match(email,@"^[^\s@]+@[^\s@]+\.[^\s@]+$")||email.Length>254||email==accounts.Owner||name.Length is <1 or >100||unit.Length is <1 or >100)throw new ApiError("نام، واحد، ایمیل، نام کاربری و رمز حداقل ۱۲ نویسه لازم است.");
 using var db=database.Open();db.Atomic(()=>{var id=Guid.NewGuid().ToString();var subject=Guid.NewGuid().ToString();var now=J.Now();db.Exec("INSERT INTO app_members(id,email,name,unit,status,subject,permissions,revision,created,updated) VALUES(?,?,?,?,'active',?,?,1,?,?)",id,email,name,unit,subject,J.Write(perms),now,now);
 db.Exec("INSERT INTO dotnet_accounts(email,subject,name,password_hash,stamp,username,must_change) VALUES(?,?,?,?,?,?,1)",email,subject,name,new Microsoft.AspNetCore.Identity.PasswordHasher<string>().HashPassword(email,password),Guid.NewGuid().ToString(),username);
 db.Audit(a,id,"create_member",new{email,name,unit,permissions=perms,username,mustChange=true});return 0;});
 }
}
