namespace Nafasyar;
public class AttachmentService(Database database){
 const int Max=10*1024*1024;
 static string Table(bool quality)=>quality?"quality_files":"batch_files";
 static string Parent(bool quality)=>quality?"report_id":"batch_id";
 static void Access(Actor a,bool quality,bool write){if(quality)QualityService.Access(a,write);else a.Require("batch",write?"write":"read");}
 static void Verify(Store db,string parent,bool quality){if(quality)QualityService.Report(db,parent);else QualityService.Record(db,parent,"batch");}
 static object Present(Dictionary<string,object?> r)=>r.Where(x=>x.Key!="object_key").ToDictionary(x=>x.Key,x=>x.Value);
 public object List(Actor a,string parent,bool quality){Access(a,quality,false);using var db=database.Open();Verify(db,parent,quality);return new{files=db.All("SELECT * FROM "+Table(quality)+" WHERE "+Parent(quality)+"=? ORDER BY uploaded_at DESC,id",parent).Select(Present).ToArray()};}
 public object Upload(Actor a,string parent,string id,string filename,byte[] bytes,bool quality){Access(a,quality,true);if(!Guid.TryParse(id,out _)||filename.Trim()==""||filename.Length>180||filename.Any(c=>char.IsControl(c)||c is '/' or '\\')||bytes.Length is <=0 or >Max)throw new ApiError("شناسه، نام فایل یا حجم معتبر نیست؛ هر فایل حداکثر ۱۰ مگابایت.");using var db=database.Open();string? path=null;var hash=J.Hash(bytes);try{return db.Atomic(()=>{Verify(db,parent,quality);var old=db.One("SELECT * FROM "+Table(quality)+" WHERE id=?",id);if(old!=null){if((string)old[Parent(quality)]! !=parent||(string)old["sha256"]! !=hash||(string)old["filename"]! !=filename)throw new ApiError("شناسه برای فایل دیگری استفاده شده است.",409);return (object)new{file=Present(old)};}
 var key=(quality?"quality-files/":"batch-files/")+id+"/"+Guid.NewGuid();path=database.ObjectPath(key);Directory.CreateDirectory(Path.GetDirectoryName(path)!);File.WriteAllBytes(path,bytes);var now=J.Now();db.Exec("INSERT INTO "+Table(quality)+"(id,"+Parent(quality)+",object_key,filename,byte_size,sha256,uploaded_at,uploaded_by) VALUES(?,?,?,?,?,?,?,?)",id,parent,key,filename,bytes.Length,hash,now,a.Name);var file=db.One("SELECT * FROM "+Table(quality)+" WHERE id=?",id)!;db.Audit(a,parent,quality?"attach_quality_file":"attach_batch_file",file);return new{file=Present(file)};});}catch{if(path!=null){try{var committed=db.One("SELECT object_key FROM "+Table(quality)+" WHERE id=?",id);if(committed==null||database.ObjectPath((string)committed["object_key"]!)!=path)File.Delete(path);}catch{}}throw;}}
 public (byte[],string,string) Download(Actor a,string parent,string id,bool quality){Access(a,quality,false);using var db=database.Open();Verify(db,parent,quality);var file=db.One("SELECT * FROM "+Table(quality)+" WHERE id=? AND "+Parent(quality)+"=?",id,parent)??throw new ApiError("فایل پیدا نشد.",404);var path=database.ObjectPath((string)file["object_key"]!);if(!File.Exists(path))throw new ApiError("فایل در دسترس نیست.",503);var bytes=File.ReadAllBytes(path);var hash=J.Hash(bytes);if(bytes.Length!=Convert.ToInt64(file["byte_size"])||hash!=(string)file["sha256"]!)throw new ApiError("یکپارچگی فایل تأیید نشد.",503);return(bytes,(string)file["filename"]!,hash);}
}
