namespace Nafasyar;
public record Preview(int Row,Dictionary<string,string> Data,string Status,string Message,string? Device=null,string? Previous=null,string[]? Changes=null);
public class DistributionService(Database database){
 static readonly string[] Keys=["serial","dealerCode","dealerName","dealerDate","invoice","customerName","customerMobile","customerNationalId","customerCity","customerAddress","notes"];
 static readonly string[] IdKeys=["serial","dealerCode","invoice","customerMobile","customerNationalId"];
 Dictionary<string,string> Normalize(JsonNode? n){var input=J.Data(n);var d=new Dictionary<string,string>();foreach(var k in Keys){var v=input.Text(k).Trim();if(v.Length>(k is "notes" or "customerAddress"?2000:200))throw new ApiError("متن بیش از حد طولانی است.");d[k]=IdKeys.Contains(k)?J.Digits(v):v;}d["serial"]=J.Serial(d["serial"]);if(d["serial"]==""||d["dealerName"]=="")throw new ApiError("سریال و نماینده لازم است.");if(d["customerNationalId"]!=""&&!J.Match(d["customerNationalId"],@"^\d{10}$"))throw new ApiError("کد ملی باید ۱۰ رقم باشد.");if(d["customerMobile"]!=""&&!J.Match(d["customerMobile"],@"^(?:09\d{9}|\+989\d{9})$"))throw new ApiError("موبایل معتبر نیست.");if(d["dealerDate"]!="")J.Jalali(d["dealerDate"]);if(d["customerName"]==""&&new[]{"customerMobile","customerNationalId","customerCity","customerAddress"}.Any(k=>d[k]!=""))throw new ApiError("نام مشتری لازم است.");return d;}
 List<Row> State(Store db)=>db.All("SELECT * FROM records WHERE kind IN ('device','distribution')").Select(Row.From).ToList();
 Preview PreviewRow(JsonNode? input,int index,List<Row> rows){Dictionary<string,string>d;try{d=Normalize(input);}catch(ApiError e){return new(index,new(),"invalid",e.Message);}var matches=rows.Where(r=>r.Kind=="device"&&J.Serial(r.Data.Text("code"))==d["serial"]).ToArray();if(matches.Length!=1)return new(index,d,matches.Length>1?"conflict":"unknown","سریال باید یک شناسنامه ثبت‌شده داشته باشد.");var id=matches[0].Id;var current=rows.FirstOrDefault(r=>r.Kind=="distribution"&&r.Data.Text("device")==id);if(current==null)return new(index,d,"new","ثبت ارتباط جدید",id,"");var conflicts=Keys.Where(k=>k!="serial"&&current.Data.Text(k)!=""&&d[k]!=""&&current.Data.Text(k)!=d[k]).ToArray();if(conflicts.Length>0)return new(index,d,"conflict","تفاوت با اطلاعات قبلی: "+string.Join("، ",conflicts),id,J.Write(current.Data));var changes=Keys.Where(k=>d[k]!=""&&current.Data.Text(k)=="").ToArray();return new(index,d,changes.Length>0?"complete":"same",changes.Length>0?"تکمیل فیلدهای خالی":"قبلاً ثبت شده؛ بدون تغییر",id,J.Write(current.Data),changes);}
 Row Save(Store db,Actor a,Dictionary<string,string>d,string device,string previous,string source,string reason){var id="distribution:"+device;var old=db.Record(id);if(old==null?previous!="":previous==""||!J.Same(J.Write(old.Data),previous))throw new ApiError("اطلاعات تغییر کرده؛ صفحه را تازه کنید.",409);var next=new Dictionary<string,string>(d);if(old?.Data.TryGetValue("deliveryDate",out var legacy)==true)next["deliveryDate"]=legacy;next["device"]=device;next["updatedAt"]=J.Now();next["updatedBy"]=a.Name;next["source"]=source;next["reason"]=reason;var row=new Row(id,"distribution",old?.Created??J.Now(),next);if(old==null)db.Exec("INSERT INTO records VALUES(?,?,?,?)",id,"distribution",J.Write(next),row.Created);else db.Exec("UPDATE records SET payload=? WHERE id=?",J.Write(next),id);db.Audit(a,id,old==null?"create_distribution":"update_distribution",next,old==null?null:J.Write(old.Data));return row;}
 public object Get(Actor a,string device,bool warranty){a.Require("distribution");a.Require("device");if(device=="")throw new ApiError("دستگاه را انتخاب کنید.");using var db=database.Open();var time=db.One("SELECT MIN(at) AS at FROM access_audit WHERE action='issue_warranty_code' AND target=?","warranty:"+device)?["at"];if(warranty)return new{warrantyActivatedAt=time};var history=db.All("SELECT action,before,after,at FROM access_audit WHERE target=? ORDER BY at DESC LIMIT 30","distribution:"+device).Select(r=>new{action=r["action"],before=r["before"]==null?null:JsonNode.Parse((string)r["before"]!),after=JsonNode.Parse((string)r["after"]!),at=r["at"]});return new{warrantyActivatedAt=time,history};}
 public object Post(Actor a,JsonNode b){a.Require("distribution","write");a.Require("device");var mode=J.Text(b,"mode");using var db=database.Open();return db.Atomic(()=>{var rows=State(db);if(mode=="manual"){var d=Normalize(b["data"]);var matched=rows.Where(r=>r.Kind=="device"&&J.Serial(r.Data.Text("code"))==d["serial"]).ToArray();if(matched.Length!=1)throw new ApiError("سریال باید یک شناسنامه داشته باشد.");if(b["previous"]==null)throw new ApiError("فرم را دوباره باز کنید.");var reason=J.Text(b,"reason").Trim();if(reason.Length>500||rows.Any(r=>r.Kind=="distribution"&&r.Data.Text("device")==matched[0].Id)&&reason.Length<3)throw new ApiError("دلیل اصلاح بین ۳ تا ۵۰۰ نویسه است.");return (object)new{record=Save(db,a,d,matched[0].Id,J.Text(b,"previous"),"ثبت دستی",reason==""?"ثبت اولیه":reason)};}
 if(mode is not("preview" or "import")||b["rows"] is not JsonArray input||input.Count>500||mode=="import"&&input.Count>25)throw new ApiError("تعداد ردیف یا نوع درخواست معتبر نیست.");var seen=new HashSet<string>();var preview=input.Select((r,i)=>{var p=PreviewRow(r?["data"],r?["row"]?.GetValue<int>()??i+2,rows);if(p.Data.Text("serial")!=""&&!seen.Add(p.Data["serial"]))p=p with{Status="invalid",Message="سریال در فایل تکرار شده است."};return p;}).ToList();if(mode=="preview")return new{preview};if(preview.Any(p=>p.Status is not("new" or "complete" or "same")))throw new ApiError("برخی ردیف‌ها قابل ثبت نیستند؛ پیش‌نمایش را تازه کنید.",409);
 var results=new List<object>();foreach(var p in preview){if(p.Status=="same"){results.Add(new{row=p.Row,status="same",message=p.Message});continue;}var prior=rows.FirstOrDefault(r=>r.Kind=="distribution"&&r.Data.Text("device")==p.Device);var merged=prior==null?new Dictionary<string,string>():new(prior.Data);foreach(var k in Keys)if(p.Data[k]!="")merged[k]=p.Data[k];var data=Normalize(JsonSerializer.SerializeToNode(merged,J.Options));var filename=J.Text(b,"filename");var record=Save(db,a,data,p.Device!,p.Previous??"",filename==""?"ورود اکسل":"اکسل: "+filename[..Math.Min(filename.Length,180)],p.Status=="complete"?"تکمیل فیلدهای خالی از اکسل":"ثبت اولیه از اکسل");results.Add(new{row=p.Row,status="saved",record});}return new{results};});}
}
