using System.Security.Cryptography;
using System.Text.RegularExpressions;
namespace Nafasyar;
public class FirmwareService(Database database){
 public const int MaxBytes=10*1024*1024;
 static string Normalize(string s)=>Regex.Replace(J.Digits(s).Normalize(NormalizationForm.FormKC).Replace('ي','ی').Replace('ك','ک'),@"\s+"," ").Trim().ToLowerInvariant();
 Row WithFile(Store db,Row r){var f=db.One("SELECT * FROM firmware_files WHERE version_id=?",r.Id);if(f==null)return r;var d=new Dictionary<string,string>(r.Data){["fileName"]=(string)f["filename"]!,["fileSize"]=Convert.ToString(f["byte_size"],CultureInfo.InvariantCulture)!,["fileHash"]=(string)f["sha256"]!,["fileUploadedAt"]=(string)f["uploaded_at"]!,["fileUploadedBy"]=(string)f["uploaded_by"]!};return r with{Data=d};}
 public object List(Actor a){a.Require("firmware");using var db=database.Open();return new{records=db.All("SELECT * FROM records WHERE kind='firmware' ORDER BY created DESC,id").Select(Row.From).Select(r=>WithFile(db,r))};}
 public object Create(Actor a,JsonNode b){a.Require("firmware","write");var input=J.Data(b);var d=new Dictionary<string,string>();foreach(var k in new[]{"name","version","deviceModel","board","notes"}){d[k]=input.Text(k).Trim();if(d[k].Length>(k=="notes"?4000:160))throw new ApiError("متن طولانی است.");}if(d["name"]==""||d["version"]=="")throw new ApiError("نام و نسخه الزامی است.");d["version"]=J.Digits(d["version"]);var id="firmware:"+J.Hash(Encoding.UTF8.GetBytes(J.Write(new[]{"name","version","deviceModel","board"}.Select(k=>Normalize(d[k])).ToArray())));d["createdBy"]=a.Name;var row=new Row(id,"firmware",J.Now(),d);using var db=database.Open();db.Atomic(()=>{db.Exec("INSERT INTO records VALUES(?,?,?,?)",id,"firmware",J.Write(d),row.Created);db.Audit(a,id,"create_firmware",row);return 0;});return new{record=row};}
 public static void Validate(byte[] bytes,string filename){if(!filename.EndsWith(".hex",StringComparison.OrdinalIgnoreCase)||filename.Length>180||filename.Any(c=>char.IsControl(c)||c is '/' or '\\'))throw new ApiError("نام فایل HEX معتبر نیست.");if(bytes.Length==0||bytes.Length>MaxBytes)throw new ApiError("فایل باید غیرخالی و حداکثر ۱۰ مگابایت باشد.");string text;try{text=new UTF8Encoding(false,true).GetString(bytes);}catch{throw new ApiError("قالب متنی معتبر نیست.");}bool eof=false;int data=0,lineNo=0;foreach(var raw in Regex.Split(text,@"\r\n|\r|\n")){lineNo++;var line=raw.Trim().TrimStart('\uFEFF');if(line=="")continue;void Fail()=>throw new ApiError("ساختار یا checksum خط "+lineNo+" معتبر نیست.");if(eof||line.Length is <11 or >521||(line.Length-1)%2!=0||!J.Match(line,@"^:[0-9a-fA-F]+$"))Fail();var p=Convert.FromHexString(line[1..]);if(p.Length!=p[0]+5||p.Sum(x=>(int)x)%256!=0||p[3]>5)Fail();if(p[3]==0)data+=p[0];else{var n=p[3]==1?0:p[3] is 2 or 4?2:4;if(p[0]!=n||p[1]!=0||p[2]!=0)Fail();if(p[3]==1)eof=true;}}if(!eof||data==0)throw new ApiError("داده و پایان فایل لازم است.");}
 public object Upload(Actor a,string version,string filename,byte[] bytes){a.Require("firmware","write");Validate(bytes,filename);using var db=database.Open();string? path=null;try{return db.Atomic(()=>{var row=db.Record(version);if(row?.Kind!="firmware")throw new ApiError("نسخه پیدا نشد.",404);if(db.One("SELECT version_id FROM firmware_files WHERE version_id=?",version)!=null)throw new ApiError("فایل این نسخه قبلاً ثبت شده است.",409);var key="firmware/"+version+"/"+Guid.NewGuid()+".hex";path=database.ObjectPath(key);Directory.CreateDirectory(Path.GetDirectoryName(path)!);File.WriteAllBytes(path,bytes);var hash=J.Hash(bytes);var now=J.Now();db.Exec("INSERT INTO firmware_files VALUES(?,?,?,?,?,?,?)",version,key,filename,bytes.Length,hash,now,a.Name);db.Audit(a,version,"attach_firmware_hex",new{filename,sha256=hash,byte_size=bytes.Length,object_key=key});return new{record=WithFile(db,row)};});}catch{if(path!=null&&File.Exists(path)){try{File.Delete(path);}catch{}}throw;}}
 public (byte[],string,string) Download(Actor a,string version){a.Require("firmware");using var db=database.Open();var file=db.One("SELECT * FROM firmware_files WHERE version_id=?",version)??throw new ApiError("فایل پیدا نشد.",404);var path=database.ObjectPath((string)file["object_key"]!);if(!File.Exists(path))throw new ApiError("فایل در دسترس نیست.",503);var bytes=File.ReadAllBytes(path);var hash=J.Hash(bytes);if(bytes.Length!=Convert.ToInt64(file["byte_size"])||hash!=(string)file["sha256"]!)throw new ApiError("یکپارچگی فایل تأیید نشد.",503);return(bytes,(string)file["filename"]!,hash);}
}
