using Microsoft.Data.Sqlite;
namespace Nafasyar;
public static class Maintenance {
 static readonly string[] Tables=["app_identity","records","app_members","access_audit","firmware_files","serial_runs","serial_reservations","batch_files","quality_templates","quality_reports","quality_files"];
 public static string ReadPassword(){if(Console.IsInputRedirected)return Console.In.ReadToEnd().TrimEnd('\r','\n');var s=new StringBuilder();ConsoleKeyInfo k;while((k=Console.ReadKey(true)).Key!=ConsoleKey.Enter){if(k.Key==ConsoleKey.Backspace){if(s.Length>0)s.Length--;}else if(!char.IsControl(k.KeyChar))s.Append(k.KeyChar);}Console.Error.WriteLine();return s.ToString();}
 public static void Import(Database database,string file){var dump=JsonNode.Parse(File.ReadAllText(file))!;if(J.Text(dump,"format")!="nafasyar-d1-export-v1")throw new Exception("Unsupported export");using var db=database.Open();db.Atomic(()=>{foreach(var t in Tables)if(Convert.ToInt64(db.One("SELECT COUNT(*) AS n FROM "+t)!["n"])>0)throw new Exception("Target must be empty; import before first normal server start");foreach(var t in Tables){var item=dump["tables"]?[t];if(item==null){if(new[]{"batch_files","quality_templates","quality_reports","quality_files"}.Contains(t))continue;throw new Exception("Missing table "+t);}var columns=db.All("PRAGMA table_info("+t+")").Select(r=>(string)r["name"]!).ToArray();if(!columns.SequenceEqual(item["columns"]!.AsArray().Select(x=>x!.GetValue<string>())))throw new Exception("Column mismatch");foreach(var row in item["rows"]!.AsArray()){var values=columns.Select(k=>row?[k] is null?null:row[k] is JsonValue v&&v.TryGetValue<long>(out var n)?(object)n:row[k]!.GetValue<string>()).ToArray();db.Exec("INSERT INTO "+t+"("+string.Join(',',columns.Select(c=>"\""+c.Replace("\"","\"\"")+"\""))+") VALUES("+string.Join(',',columns.Select(_=>"?"))+")",values);}}return 0;});Console.WriteLine("Imported all domain tables.");}
 public static void Check(Database database){using var db=database.Open();var integrity=db.All("PRAGMA integrity_check");var foreign=db.All("PRAGMA foreign_key_check");Console.WriteLine(J.Write(new{integrity,foreignKeyErrors=foreign.Count,counts=Tables.ToDictionary(t=>t,t=>db.One("SELECT count(*) AS n FROM "+t)!["n"])}));if(foreign.Count>0||integrity.Any(r=>(string)r["integrity_check"]! !="ok"))throw new Exception("Database integrity failed");}
 public static void Backup(Database database,string destination){var dest=Path.GetFullPath(destination);if(Directory.Exists(dest)||dest.StartsWith(database.DirectoryPath+Path.DirectorySeparatorChar))throw new Exception("Use a new backup directory outside DATA_DIR");Directory.CreateDirectory(dest);using var db=database.Open();using var target=new SqliteConnection("Data Source="+Path.Combine(dest,"nafasyar.sqlite"));target.Open();db.Connection.BackupDatabase(target);Copy(Path.Combine(database.DirectoryPath,"objects"),Path.Combine(dest,"objects"));Console.WriteLine("Database and firmware copied; data-protection keys are intentionally excluded, so old cookies will not be reusable on a fresh restore.");}
 static void Copy(string from,string to){Directory.CreateDirectory(to);foreach(var f in Directory.GetFiles(from))File.Copy(f,Path.Combine(to,Path.GetFileName(f)));foreach(var d in Directory.GetDirectories(from))Copy(d,Path.Combine(to,Path.GetFileName(d)));}
}
