namespace Nafasyar;
public class QualityService(Database database){
 public static void Access(Actor a,bool write=false){a.Require("device");a.Require("event",write?"write":"read");if(write&&!a.IsAdmin&&!a.Permissions.EventStages.Contains("آزمون نهایی"))throw new ApiError("مجوز مرحله آزمون نهایی لازم است.",403);}
 public static Row Record(Store db,string id,string kind){var r=db.Record(id);if(r?.Kind!=kind)throw new ApiError("محصول یا دستگاه پیدا نشد.",404);return r;}
 public static JsonObject Template(Store db,string id){var r=db.One("SELECT * FROM quality_templates WHERE id=?",id)??throw new ApiError("فرم پیدا نشد.",404);var o=JsonSerializer.SerializeToNode(r,J.Options)!.AsObject();o["fields"]=JsonNode.Parse((string)r["fields"]!);return o;}
 public static JsonObject Report(Store db,string id){var r=db.One("SELECT * FROM quality_reports WHERE id=?",id)??throw new ApiError("برگ کنترل کیفیت پیدا نشد.",404);var o=JsonSerializer.SerializeToNode(r,J.Options)!.AsObject();o["values"]=JsonNode.Parse((string)r["values"]!);o["template"]=Template(db,(string)r["template_id"]!);return o;}
 public object Templates(Actor a,string product,string device){using var db=database.Open();if(device!=""){Access(a);product=Record(db,device,"device").Data.Text("product");}else a.Require("product");Record(db,product,"product");return new{templates=db.All("SELECT id FROM quality_templates WHERE product_id=? ORDER BY version DESC",product).Select(r=>Template(db,(string)r["id"]!)).ToArray()};}
 static string Str(JsonNode? n,string k,int max=4000){if(n?[k] is not JsonValue v||!v.TryGetValue<string>(out var s)||s.Length>max)throw new ApiError("مشخصات فرم معتبر نیست.");return s.Trim();}
 static double Number(string s){if(!double.TryParse(J.Digits(s),NumberStyles.Float,CultureInfo.InvariantCulture,out var v)||!double.IsFinite(v))throw new ApiError("مقدار باید عدد باشد.");return v;}
 public object CreateTemplate(Actor a,JsonNode b){a.Require("product","write");string product=Str(b,"productId"),title=Str(b,"title",160);if(title==""||b["fields"] is not JsonArray fields||fields.Count is <1 or >40)throw new ApiError("عنوان و ۱ تا ۴۰ معیار لازم است.");var normalized=new JsonArray();var keys=new HashSet<string>();foreach(var f in fields){var key=Str(f,"key",40);var label=Str(f,"label",120);var type=Str(f,"type",10);var unit=Str(f,"unit",40);var min=J.Digits(Str(f,"min"));var max=J.Digits(Str(f,"max"));if(!J.Match(key,@"^[a-z][a-z0-9_]{0,39}$")||!keys.Add(key)||label==""||type is not("number" or "text" or "result")||f?["required"] is not JsonValue v||!v.TryGetValue<bool>(out var required))throw new ApiError("کد یکتا و مشخصات معتبر برای معیار لازم است.");if(type=="number"){if(min!="")Number(min);if(max!="")Number(max);if(min!=""&&max!=""&&Number(min)>Number(max))throw new ApiError("حد پایین از حد بالا بیشتر است.");}else{unit="";min="";max="";}normalized.Add(new JsonObject{["key"]=key,["label"]=label,["type"]=type,["unit"]=unit,["min"]=min,["max"]=max,["required"]=required});}
 using var db=database.Open();return db.Atomic(()=>{Record(db,product,"product");var last=Convert.ToInt64(db.One("SELECT MAX(version) AS v FROM quality_templates WHERE product_id=?",product)?["v"]??0);if(b["previousVersion"]?.GetValue<long>()!=last)throw new ApiError("نسخه فرم تغییر کرده است؛ فهرست را تازه کنید.",409);var id=Guid.NewGuid().ToString();var now=J.Now();db.Exec("INSERT INTO quality_templates(id,product_id,version,title,fields,created,created_by) VALUES(?,?,?,?,?,?,?)",id,product,last+1,title,normalized.ToJsonString(J.Options),now,a.Name);var template=Template(db,id);db.Audit(a,product,"create_quality_template",template);return new{template};});}
 public object Reports(Actor a,string device){Access(a);using var db=database.Open();Record(db,device,"device");return new{reports=db.All("SELECT id FROM quality_reports WHERE device_id=? ORDER BY created DESC,id",device).Select(r=>Report(db,(string)r["id"]!)).ToArray()};}
 public object CreateReport(Actor a,JsonNode b){Access(a,true);string device=Str(b,"deviceId"),templateId=Str(b,"templateId"),id=Str(b,"requestId"),notes=Str(b,"notes"),verdict=Str(b,"verdict");if(!Guid.TryParse(id,out _)||verdict is not("pass" or "fail"))throw new ApiError("مشخصات آزمون معتبر نیست.");var input=J.Data(b["values"]);using var db=database.Open();return db.Atomic(()=>{var d=Record(db,device,"device");var template=Template(db,templateId);if(J.Text(template,"product_id")!=d.Data.Text("product"))throw new ApiError("این فرم متعلق به محصول دستگاه نیست.");var fields=template["fields"]!.AsArray();if(input.Keys.Any(k=>!fields.Any(f=>J.Text(f,"key")==k)))throw new ApiError("معیار خارج از فرم ارسال شده است.");var values=new Dictionary<string,string>();bool failed=false;foreach(var f in fields){var key=J.Text(f,"key");var value=input.Text(key).Trim();if(value.Length>2000||f!["required"]!.GetValue<bool>()&&value=="")throw new ApiError(J.Text(f,"label")+" الزامی است یا متن طولانی است.");var type=J.Text(f,"type");if(value!=""&&type=="number"){var n=Number(value);string min=J.Text(f,"min"),max=J.Text(f,"max");if(min!=""&&n<Number(min)||max!=""&&n>Number(max))failed=true;value=n.ToString("G",CultureInfo.InvariantCulture);}if(value!=""&&type=="result"){if(value is not("pass" or "fail"))throw new ApiError("نتیجه معیار معتبر نیست.");failed|=value=="fail";}values[key]=value;}if(failed&&verdict=="pass")throw new ApiError("معیار مردود یا خارج از محدوده وجود دارد.");var old=db.One("SELECT id FROM quality_reports WHERE id=?",id);if(old!=null){var r=Report(db,id);if(J.Text(r,"device_id")!=device||J.Text(r,"template_id")!=templateId||J.Text(r,"notes")!=notes||J.Text(r,"verdict")!=verdict||!J.Same(r["values"]!.ToJsonString(),J.Write(values)))throw new ApiError("شناسه برای آزمون دیگری استفاده شده است.",409);return (object)new{report=r};}
 var now=J.Now();db.Exec("INSERT INTO quality_reports(id,device_id,template_id,\"values\",verdict,notes,created,created_by) VALUES(?,?,?,?,?,?,?,?)",id,device,templateId,J.Write(values),verdict,notes,now,a.Name);var data=new Dictionary<string,string>{{"device",device},{"stage","آزمون نهایی"},{"date",J.Day()},{"operator",a.Name},{"result",verdict=="pass"?"تأیید":"مردود"},{"notes",J.Text(template,"title")+" · نسخه "+template["version"]+" · "+notes},{"qcReportId",id}};var ev=new Row("qc-event:"+id,"event",now,data);db.Exec("INSERT INTO records(id,kind,payload,created) VALUES(?,?,?,?)",ev.Id,ev.Kind,J.Write(data),now);var report=Report(db,id);db.Audit(a,device,"record_quality_report",new{report,@event=ev});return new{report,@event=ev};});}
}
