namespace Nafasyar;
public class RecordService(Database database,Rules rules){
 public List<Row> List(Actor a){using var db=database.Open();return db.All("SELECT * FROM records ORDER BY created DESC,id").Select(Row.From).Where(r=>a.IsAdmin||a.Permissions.Read.Contains(r.Kind)).ToList();}
 public Row Create(Actor a,JsonNode body){var kind=J.Text(body,"kind");a.Require(kind,"write");if(kind is "distribution" or "firmware")throw new ApiError("از بخش اختصاصی ثبت کنید.");var d=J.Data(body["data"]);using var db=database.Open();return db.Atomic(()=>{
 if(kind is "batch" or "product" or "device")d["code"]=J.Serial(d.Text("code"));
 if(kind=="batch"&&d.Text("partCode")!="")d["partCode"]=J.Digits(d["partCode"]).Trim();
 if(kind=="device"){a.Require("product");var p=db.Record(d.Text("product"));if(p?.Kind!="product"||p.Data.Text("status")!="فعال")throw new ApiError("محصول فعال انتخاب کنید.");var reserved=db.One("SELECT product_id FROM serial_reservations WHERE serial=?",d.Text("code"));if(reserved!=null&&(string)reserved["product_id"]! != p.Id)throw new ApiError("سریال برای محصول دیگری رزرو شده است.",409);d["model"]=p.Data.Text("model");d["productCode"]=p.Data.Text("code");d["productName"]=p.Data.Text("name");d["warrantyMonths"]=p.Data.Text("warrantyMonths");}
 rules.Validate(kind,d);if(kind=="event"&&!a.IsAdmin&&!a.Permissions.EventStages.Contains(d.Text("stage")))throw new ApiError("مرحله مجاز نیست.",403);
 foreach(var f in rules.Fields(kind)){var k=J.Text(f,"key");var refKind=J.Text(f,"ref");if(refKind==""||d.Text(k)=="")continue;var r=db.Record(d[k]);if(r?.Kind!=refKind)throw new ApiError("رکورد مرتبط پیدا نشد.");if((kind=="event"&&d.Text("stage")=="مصرف قطعه"&&k=="batch"||kind=="service"&&k=="replacement")&&r.Data.Text("status")!="تأیید")throw new ApiError("فقط بچ تأییدشده قابل مصرف است.");}
 if(kind=="service"&&d.Text("batch")!=""&&db.One("SELECT id FROM records WHERE (kind='event' AND json_extract(payload,'$.device')=? AND json_extract(payload,'$.batch')=?) OR (kind='service' AND json_extract(payload,'$.device')=? AND json_extract(payload,'$.replacement')=?)",d.Text("device"),d.Text("batch"),d.Text("device"),d.Text("batch"))==null)throw new ApiError("بچ در سابقه دستگاه نیست.");
 var id=kind is "batch" or "device" or "product"?kind+":"+d["code"]:Guid.NewGuid().ToString();var row=new Row(id,kind,J.Now(),d);db.Exec("INSERT INTO records(id,kind,payload,created) VALUES(?,?,?,?)",id,kind,J.Write(d),row.Created);db.Audit(a,id,"create_record",row);return row;});}
 public Row Update(Actor a,JsonNode body){var id=J.Text(body,"id");var d=J.Data(body["data"]);var previous=J.Text(body,"previous");using var db=database.Open();return db.Atomic(()=>{var old=db.Record(id)??throw new ApiError("رکورد پیدا نشد.",404);a.Require(old.Kind,"write");var edit=rules.Editable(old.Kind);if(edit.Length==0)throw new ApiError("رکورد قابل ویرایش نیست.");rules.Validate(old.Kind,d);foreach(var k in old.Data.Keys.Union(d.Keys))if(!edit.Contains(k)&&old.Data.GetValueOrDefault(k)!=d.GetValueOrDefault(k))throw new ApiError("هویت و ارتباطات قابل تغییر نیست.");if(!J.Same(previous,J.Write(old.Data)))throw new ApiError("رکورد تغییر کرده؛ صفحه را تازه کنید.",409);db.Exec("UPDATE records SET payload=? WHERE id=?",J.Write(d),id);db.Audit(a,id,"update_record",d,J.Write(old.Data));return old with{Data=d};});}
 public object Suggest(Actor a,string part,string date){a.Require("batch");part=Rules.Part(part);var prefix=part+"-"+J.Jalali(date)+"-";using var db=database.Open();var codes=db.All("SELECT json_extract(payload,'$.code') AS code FROM records WHERE kind='batch'").Select(r=>(string?)r["code"]??"");long last=0;foreach(var c in codes){if(c.StartsWith(prefix)&&J.Match(c[prefix.Length..],@"^\d{3,}$")&&long.TryParse(c[prefix.Length..],out var n))last=Math.Max(last,n);}if(last>=9007199254740991)throw new ApiError("شماره ترتیب خارج از محدوده است.");var sequence=(last+1).ToString("000");return new{code=prefix+sequence,partCode=part,jalaliDate=J.Jalali(date,true),sequence,scheme="part-jalali-v1",reserved=false};}
}
