import {requireAccess,checkOrigin,AccessError,accessResponse} from '@/lib/authorization';
import {storage} from '@/lib/storage';
import {boundedBody} from '@/lib/firmware-storage';
import {routineRoles,targetFor,routineHelp} from '@/lib/routine-production';
import {calculateCosts,moneyMicro,moneyText} from '@/lib/costing';
import {holdChecks,supplyLock} from '@/lib/sourcing';
import {tehranDay} from '@/lib/serials';
import {trainingContext} from '@/lib/training-context';
const fail=(m:string,s=400):never=>{throw new AccessError(m,s)};
const text=(v:any,max=2000)=>{if(typeof v!=='string'||!v.trim()||v.length>max)fail('متن الزامی یا نامعتبر است.');return v.trim();};
const num=(v:any,max=1000000,min=0)=>{if(!Number.isSafeInteger(v)||v<min||v>max)fail('عدد صحیح در محدوده معتبر وارد کنید.');return v as number;};
const date=(v:any)=>{if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v)fail('تاریخ معتبر لازم است.');return v;};
const clock=(v:any)=>{if(typeof v!=='string'||!/^([01]\d|2[0-3]):[0-5]\d$/.test(v))fail('ساعت معتبر لازم است.');return Number(v.slice(0,2))*60+Number(v.slice(3));};
const list=(v:any,max=60)=>{if(!Array.isArray(v)||v.length>max)fail('فهرست معتبر لازم است.');return v;};
const quantity=(v:any)=>{if(typeof v!=='string'||!/^\d{1,9}(\.\d{1,3})?$/.test(v)||Number(v)<=0)fail('مقدار مثبت با حداکثر سه اعشار لازم است.');return Math.round(Number(v)*1000);};
const json=(v:any)=>Response.json(v,{headers:{'Cache-Control':'private, no-store'}});
async function source(){const db=storage();const [e,r,m,b,en,op,orders,boms]=await Promise.all([db.prepare('SELECT * FROM flow_entities ORDER BY id').all(),db.prepare("SELECT * FROM records WHERE kind IN ('batch','product','device') ORDER BY id").all(),db.prepare("SELECT id,subject,name,permissions FROM app_members WHERE status='active'").all(),db.prepare('SELECT * FROM inventory_balances').all(),db.prepare('SELECT * FROM inventory_entries ORDER BY id').all(),db.prepare('SELECT rowid AS sequence,* FROM inventory_operations ORDER BY created,rowid').all(),db.prepare('SELECT * FROM production_orders').all(),db.prepare('SELECT * FROM bom_versions').all()]);return {entities:e.results.map((x:any)=>({...x,data:JSON.parse(x.data)})),records:r.results as any[],members:m.results as any[],balances:b.results as any[],entries:en.results as any[],operations:op.results as any[],orders:orders.results,boms:boms.results};}
const own=(u:any,s:any,j:any)=>j.memberId===u.userId||s.members.some((m:any)=>m.id===j.memberId&&m.subject===u.userId);
export async function GET(){try{const u=await requireAccess(),roles=routineRoles(u);if(!roles.read)fail('دسترسی ندارید.',403);if(trainingContext.getStore())fail('این بخش فعلاً فقط برای اطلاعات شرکت است.',403);const s=await source();
 const jobs=s.entities.filter((e:any)=>e.type==='routine_job'&&(roles.staff||own(u,s,e.data))).map((e:any)=>({...e,data:{...e.data,report:e.data.closedReport||targetFor(e.data)}}));
 return json({roles,jobs,policies:roles.staff?s.entities.filter((e:any)=>e.type==='routine_policy'):[],routes:roles.staff?s.entities.filter((e:any)=>e.type==='routine_route'):[],lots:roles.staff?s.entities.filter((e:any)=>e.type==='routine_lot').map((e:any)=>({...e,data:{...e.data,...(!roles.financial?{cost:undefined}: {})}})):[],materials:roles.staff?s.entities.filter((e:any)=>e.type==='material').map((e:any)=>({id:e.id,...e.data})):[],members:roles.staff?s.members.filter((m:any)=>routineRoles({permissions:JSON.parse(m.permissions)}).read).map((m:any)=>({id:m.id,name:m.name})):[],line:roles.staff?s.balances.filter((b:any)=>b.warehouse==='line'&&b.quantity>0).map((b:any)=>({...JSON.parse(s.records.find((r:any)=>r.id===b.item_id)?.payload||'{}'),...b})):[],help:routineHelp});
 }catch(e){return accessResponse(e)||Response.json({error:'خواندن تولید روزانه ممکن نشد.'},{status:503});}}
export async function POST(request:Request){try{checkOrigin(request);const u=await requireAccess(),roles=routineRoles(u);if(!roles.read||trainingContext.getStore())fail('این عملیات فقط در اطلاعات شرکت و با دسترسی مجاز انجام می‌شود.',403);const b=JSON.parse(new TextDecoder().decode(await boundedBody(request,100000)));if(b.confirmed!==true||typeof b.id!=='string'||! /^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(b.id))fail('تأیید و UUID تازه لازم است.');
 const db=storage(),signature=JSON.stringify(b),prior:any=await db.prepare('SELECT payload,actor FROM inventory_operations WHERE id=?').bind(b.id).first();if(prior){if(prior.payload!==signature||prior.actor!==u.userId)fail('شناسه تکراری نامعتبر است.',409);return json({saved:true,repeated:true});}
 const s=await source(),now=new Date().toISOString(),notes=text(b.notes,4000),stamp={actor:u.userId,actorName:u.name,at:now,notes},stmts:any[]=[],guards:any[]=[],touched:string[]=[];const changes=new Map<string,any>();
 const need=(r:string)=>{if(!(roles as any)[r])fail('مجوز این مرحله را ندارید.',403);};
 const get=(id:string,type:string)=>{const e=s.entities.find((x:any)=>x.id===id&&x.type===type);if(!e)fail('رکورد مرتبط یافت نشد.',404);return e;};
 const edit=(id:string,type:string)=>{const e=get(id,type);if(b.revision!==e.revision)fail('اطلاعات تغییر کرده؛ تازه‌سازی کنید.',409);return structuredClone(e.data);};
 const put=(id:string,type:string,data:any)=>changes.set(id,{id,type,data});
 const guard=(sql:string,...args:any[])=>guards.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN '+sql+' THEN guard ELSE 0 END WHERE id=?').bind(...args,b.id));
 const entry=(bid:string,wh:string,n:number)=>{touched.push(bid);stmts.push(db.prepare('INSERT INTO inventory_balances(id,item_id,warehouse,quantity) VALUES(?,?,?,0) ON CONFLICT(item_id,warehouse) DO NOTHING').bind(bid+'@'+wh,bid,wh),db.prepare('UPDATE inventory_balances SET quantity=quantity+? WHERE item_id=? AND warehouse=?').bind(n,bid,wh),db.prepare('INSERT INTO inventory_entries(id,operation_id,item_id,warehouse,delta) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),b.id,bid,wh,n));};
 const material=(id:string)=>get(id,'material');
 if(b.mode==='policy'){need('manager');const optional=(k:string,max:number,min=0)=>b[k]===null||b[k]===undefined?null:num(b[k],max,min);const p={version:s.entities.filter((e:any)=>e.type==='routine_policy').length+1,effective:date(b.effective),restMinutes:optional('restMinutes',600),setupMinutes:optional('setupMinutes',600),efficiencyPercent:optional('efficiencyPercent',100,1),lowerPercent:optional('lowerPercent',100),upperPercent:optional('upperPercent',200,100),...stamp};if(s.entities.some((e:any)=>e.type==='routine_policy'&&e.data.effective>p.effective))fail('تاریخ نسخه جدید نباید قبل از نسخه قبلی باشد.');put(b.id,'routine_policy',p);}
 else if(b.mode==='route'){need('engineering');const m=material(text(b.materialId,200));if(m.data.unit!=='عدد')fail('این نسخه برای قطعات شمارشی با واحد عدد است.');const steps=list(b.steps,30).map((x:any)=>({title:text(x.title,200),seconds:num(x.seconds,86400,1),allowancesIncluded:typeof x.allowancesIncluded==='boolean'?x.allowancesIncluded:null,bom:list(x.bom,40).map((l:any)=>{const a=material(l.materialId);if(a.id===m.id)fail('قطعه نمی‌تواند ماده مصرفی خودش باشد.');return {materialId:a.id,partCode:a.data.code,name:a.data.name,unit:a.data.unit,quantity:quantity(l.quantity)};})}));if(!steps.length)fail('حداقل یک مرحله لازم است.');for(const x of steps)if(new Set(x.bom.map((l:any)=>l.materialId)).size!==x.bom.length)fail('ماده تکراری در مرحله مجاز نیست.');const version=1+Math.max(0,...s.entities.filter((e:any)=>e.type==='routine_route'&&e.data.materialId===m.id).map((e:any)=>e.data.version));put(b.id,'routine_route',{materialId:m.id,partCode:m.data.code,name:m.data.name,unit:m.data.unit,version,steps,...stamp});}
 else if(b.mode==='lot'){need('foreman');const route=get(b.routeId,'routine_route'),count=num(b.count,1000000,1);put(b.id,'routine_lot',{title:text(b.title,200),routeId:route.id,route:structuredClone(route.data),count,ready:route.data.steps.map((_:any,i:number)=>i===0?count:0),rework:route.data.steps.map(()=>0),pending:0,received:0,scrap:0,movements:[],quality:[],cost:null,history:[stamp]});}
 else if(b.mode==='assign'){need('foreman');const lot=edit(b.lotId,'routine_lot');if(lot.cost)fail('بچ مالی بسته است.');const stage=num(b.stage,lot.route.steps.length-1),queue=b.rework===true?'rework':'ready',count=num(b.count,lot[queue][stage],1),member=s.members.find((m:any)=>m.id===b.memberId);if(!member||!routineRoles({permissions:JSON.parse(member.permissions)}).read)fail('کارگر فعال داخلی لازم است.');const day=date(b.day),start=clock(b.start),end=clock(b.end);if(end<=start)fail('پایان باید بعد از شروع همان روز باشد؛ شیفت عبوری را به دو روز تقسیم کنید.');if(s.entities.some((e:any)=>e.type==='routine_job'&&e.data.memberId===member.id&&e.data.day===day&&e.data.start<end&&e.data.end>start))fail('این فرد در این بازه تخصیص دیگری دارد.');const policy=s.entities.filter((e:any)=>e.type==='routine_policy'&&e.data.effective<=day).sort((a:any,c:any)=>c.data.effective.localeCompare(a.data.effective)||c.data.version-a.data.version)[0];
 const j={lotId:b.lotId,lotTitle:lot.title,partName:lot.route.name,stage,step:lot.route.steps[stage],memberId:member.id,memberName:member.name,day,start,end,rework:queue==='rework',assigned:count,remaining:count,policy:policy?.data||{restMinutes:null,setupMinutes:null,efficiencyPercent:null,lowerPercent:null,upperPercent:null},policyId:policy?.id||null,leaveMinutes:0,downtimeMinutes:0,setupMinutes:null,restMinutes:null,outputs:[],state:'open',workerReason:'',review:null,history:[stamp]};lot[queue][stage]-=count;put(b.id,'routine_job',j);put(b.lotId,'routine_lot',lot);
 }else if(['adjust','output','close','reason','review'].includes(b.mode)){
 const j=edit(b.jobId,'routine_job');if(b.mode==='reason'){if(!own(u,s,j)&&!roles.foreman)fail('فقط کارگر یا سرکارگر می‌تواند توضیح ثبت کند.',403);j.workerReason=notes;j.history.push({...stamp,mode:b.mode});put(b.jobId,'routine_job',j);}
 else{need('foreman');if(b.mode==='review'){if(j.state!=='closed')fail('ابتدا خروجی روز را ببندید.');j.review=stamp;put(b.jobId,'routine_job',j);}else{
 if(j.state!=='open')fail('گزارش بسته‌شده تغییر نمی‌کند.');const lot=structuredClone(get(j.lotId,'routine_lot').data);if(lot.cost)fail('بچ مالی بسته است.');
 if(b.mode==='adjust'){j.restMinutes=b.restMinutes==null?null:num(b.restMinutes,1440);j.leaveMinutes=num(b.leaveMinutes,1440);j.downtimeMinutes=num(b.downtimeMinutes,1440);j.setupMinutes=b.setupMinutes===null?null:num(b.setupMinutes,1440);const rest=j.step.allowancesIncluded?0:(j.restMinutes??j.policy.restMinutes??0);if(j.leaveMinutes+j.downtimeMinutes+(j.setupMinutes??j.policy.setupMinutes??0)+rest>j.end-j.start)fail('کسورات از بازه حضور بیشتر است.');}
 else if(b.mode==='output'){
 const good=num(b.good),scrap=num(b.scrap),rework=num(b.reworkCount),total=good+scrap+rework;if(!total||total>j.remaining)fail('خروجی از کار باقیمانده بیشتر است یا صفر است.');if(typeof b.overtime!=='boolean')fail('عادی یا اضافه‌کاری را مشخص کنید.');if(b.overtime&&(!b.overtimeReference||!j.overtimeApproved))fail('ابتدا اضافه‌کاری مجاز و مدت آن را هنگام تنظیم روز ثبت کنید.');const allocations=list(b.allocations,60),seen=new Set(),totals:Record<string,number>={};
 for(const a of allocations){if(seen.has(a.batchId))fail('بچ مصرفی تکراری است.');seen.add(a.batchId);const r=s.records.find((r:any)=>r.id===a.batchId&&r.kind==='batch');if(!r)fail('بچ مصرفی یافت نشد.');const d=JSON.parse(r.payload),rec=s.entities.find((e:any)=>e.type==='receipt'&&e.id===r.id);if(d.status!=='تأیید'||rec?.data.expiry&&rec.data.expiry<tehranDay())fail('بچ تأییدشده و غیرمنقضی لازم است.');const line=j.step.bom.find((l:any)=>l.partCode===d.partCode&&l.unit===d.unit);if(!line)fail('ماده خارج از BOM این مرحله است.');const q=quantity(a.quantity);totals[line.materialId]=(totals[line.materialId]||0)+q;guard('EXISTS(SELECT 1 FROM records WHERE id=? AND payload=?)',r.id,r.payload);entry(r.id,'line',-q);lot.movements.push({operationId:b.id,batchId:r.id,quantity:q,jobId:b.jobId,stage:j.stage,...stamp});}
 if(!j.rework&&j.step.bom.some((l:any)=>(totals[l.materialId]||0)!==l.quantity*total)&&!b.varianceReason)fail('مصرف متفاوت از BOM به دلیل مغایرت نیاز دارد.');if(j.rework&&allocations.length&&!b.varianceReason)fail('مواد اضافی دوباره‌کاری به دلیل نیاز دارند.');j.outputs.push({id:b.id,good,scrap,rework,consumed:allocations,varianceReason:b.varianceReason?text(b.varianceReason):'',overtime:b.overtime,overtimeReference:b.overtime?text(b.overtimeReference):'',...stamp});j.remaining-=total;lot.scrap+=scrap;lot.rework[j.stage]+=rework;if(j.stage===lot.route.steps.length-1)lot.pending+=good;else lot.ready[j.stage+1]+=good;
 }else if(b.mode==='close'){j.actualMinutes=num(b.actualMinutes,j.end-j.start-j.leaveMinutes-j.downtimeMinutes);j.overtimeMinutes=num(b.overtimeMinutes,600);if(j.outputs.some((o:any)=>o.overtime)&&!j.overtimeMinutes)fail('زمان اضافه‌کاری را ثبت کنید.');if(j.overtimeMinutes&&!b.overtimeReference)fail('مرجع اضافه‌کاری لازم است.');if(j.overtimeMinutes&&!j.overtimeApproved)fail('اضافه‌کاری باید قبلاً مجاز شده باشد.');const other=s.entities.filter((e:any)=>e.type==='routine_job'&&e.id!==b.jobId&&e.data.memberId===j.memberId&&e.data.day===j.day&&e.data.state==='closed').reduce((n:number,e:any)=>n+e.data.actualMinutes+e.data.overtimeMinutes,0);if(other+j.actualMinutes+j.overtimeMinutes>1440)fail('زمان واقعی فرد از ۲۴ ساعت بیشتر است.');j.overtimeReference=b.overtimeReference||'';if(j.outputs.length&&!j.actualMinutes&&!j.overtimeMinutes)fail('زمان واقعی کار لازم است.');lot[j.rework?'rework':'ready'][j.stage]+=j.remaining;j.remaining=0;j.state='closed';j.closedReport=targetFor(j);j.closed=stamp;}
 if(b.mode==='adjust'){j.overtimeApproved=b.overtimeApproved===true;}
 j.history.push({...stamp,mode:b.mode});put(b.jobId,'routine_job',j);put(j.lotId,'routine_lot',lot);
 }}
 }else if(b.mode==='quality'){need('quality');const lot=edit(b.lotId,'routine_lot');if(lot.cost)fail('بچ مالی بسته است.');const good=num(b.good),scrap=num(b.scrap),rework=num(b.reworkCount);if(!good&&!scrap&&!rework||good+scrap+rework>lot.pending)fail('تعداد با خروجی در انتظار کیفیت منطبق نیست.');const reference=text(b.reference);lot.pending-=good+scrap+rework;lot.scrap+=scrap;lot.rework[lot.rework.length-1]+=rework;lot.quality.push({id:b.id,good,scrap,rework,reference,...stamp});
 if(good){const bid='routine-batch:'+b.lotId,existing=s.records.find((r:any)=>r.id===bid);const data={code:'ساخت '+lot.title,part:lot.route.name,partCode:lot.route.partCode,unit:'عدد',quantity:String(lot.received+good),status:'تأیید',supplier:'ساخت داخل',date:tehranDay(),routineLotId:b.lotId};if(existing){guard('EXISTS(SELECT 1 FROM records WHERE id=? AND payload=?)',bid,existing.payload);stmts.push(db.prepare('UPDATE records SET payload=? WHERE id=?').bind(JSON.stringify(data),bid));}else stmts.push(db.prepare("INSERT INTO records(id,kind,payload,created) VALUES(?,'batch',?,?)").bind(bid,JSON.stringify(data),now),db.prepare('INSERT INTO inventory_batches(batch_id,part_code,unit,created) VALUES(?,?,?,?)').bind(bid,lot.route.partCode,'عدد',now));lot.received+=good;put(bid,'receipt',{batchId:bid,materialId:lot.route.materialId,quantity:lot.received*1000,accepted:lot.received*1000,rejected:0,state:'stored',expiry:'',day:tehranDay(),source:'routine',routineLotId:b.lotId,qc:{reference,...stamp}});entry(bid,'line',good*1000);}
 put(b.lotId,'routine_lot',lot);
 }else if(b.mode==='cost'){need('finance');const lot=edit(b.lotId,'routine_lot'),jobs=s.entities.filter((e:any)=>e.type==='routine_job'&&e.data.lotId===b.lotId);if(lot.cost)fail('بهای بچ قبلاً نهایی شده است.');if(lot.ready.some((n:number)=>n)||lot.rework.some((n:number)=>n)||lot.pending||jobs.some((e:any)=>e.data.state!=='closed')||!lot.received)fail('ابتدا تمام کار، دوباره‌کاری و کیفیت بچ را تعیین تکلیف کنید.');
 const cs=calculateCosts(s),opids=new Set(lot.movements.map((m:any)=>m.operationId)),consumed=cs.unassigned.filter((c:any)=>opids.has(c.operationId));if(consumed.some((c:any)=>c.cost===null))fail('قیمت مواد مصرفی ناقص است.');const rates=list(b.rates,500);if(rates.length!==jobs.length||new Set(rates.map((r:any)=>r.jobId)).size!==jobs.length)fail('نرخ هر کار روزانه را یک بار مشخص کنید.');let labor=BigInt(0);for(const j of jobs){const r=rates.find((r:any)=>r.jobId===j.id);if(!r)fail('نرخ کار ناقص است.');labor+=moneyMicro(r.hourly)*BigInt(j.data.actualMinutes)/BigInt(60)+moneyMicro(r.overtimeHourly)*BigInt(j.data.overtimeMinutes)/BigInt(60);}
 const materials=consumed.reduce((n:bigint,c:any)=>n+moneyMicro(c.cost),BigInt(0)),overhead=moneyMicro(b.overhead),total=materials+labor+overhead,unitCost=moneyText(total/BigInt(lot.received));lot.cost={materials:moneyText(materials),labor:moneyText(labor),overhead:moneyText(overhead),total:moneyText(total),unitCost,rates,basis:text(b.basis),reference:text(b.reference),...stamp};put('cost-price:routine-batch:'+b.lotId,'cost_price',{batchId:'routine-batch:'+b.lotId,unitCost,source:'routine',routineLotId:b.lotId,reference:b.reference,notes:b.basis});put(b.lotId,'routine_lot',lot);
 }else fail('عملیات ناشناخته است.');
 // A consistent domain snapshot prevents duplicate allocation, stock consumption and simultaneous receipts.
 guard('(SELECT COALESCE(SUM(revision),0) FROM flow_entities)=?',s.entities.reduce((n:number,e:any)=>n+e.revision,0));guard('(SELECT COUNT(*) FROM flow_entities)=?',s.entities.length);guard('(SELECT COUNT(*) FROM inventory_entries)=?',s.entries.length);
 const writes=[...changes.values()].map(e=>s.entities.some((x:any)=>x.id===e.id)?db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=?').bind(JSON.stringify(e.data),now,e.id):db.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').bind(e.id,e.type,JSON.stringify(e.data),now,now));
 await db.batch([db.prepare('INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,?,?,?,?,1)').bind(b.id,'routine_'+b.mode,signature,u.userId,now),...guards,...writes,...stmts,...holdChecks(db,b.id,touched),...await supplyLock(db,b.id),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,b.jobId||b.lotId||b.id,'routine_'+b.mode,signature,now)]);return json({saved:true,id:b.id});
 }catch(e){return accessResponse(e)||Response.json({error:'ثبت انجام نشد؛ موجودی، نسخه و مقادیر را بررسی و تازه‌سازی کنید.'},{status:409});}}
