const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');const root=path.resolve(__dirname,'..');
function load(file,imports={}){const exports={};const source=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(source,{exports,require:name=>{if(!(name in imports))throw new Error('Missing import '+name);return imports[name]},Response,Request,URL,Error,crypto:globalThis.crypto,Date,Intl,Set,console:{error(){}}});return exports;}
const sql=new DatabaseSync(':memory:');for(const file of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',file),'utf8'));
const db={prepare(query){let args=[];return{bind(...values){args=values;return this},async first(){return sql.prepare(query).get(...args)||null},async all(){return{results:sql.prepare(query).all(...args)}},async run(){return{meta:{changes:sql.prepare(query).run(...args).changes}}}}},async batch(statements){sql.exec('BEGIN');try{const results=[];for(const statement of statements)results.push(await statement.run());sql.exec('COMMIT');return results}catch(e){sql.exec('ROLLBACK');throw e}}};
let identity=null;const env={TRACE_OWNER_EMAIL:'owner@example.com'};
const permissions=load('lib/permissions.ts');for(const preset of Object.values(permissions.presets))permissions.validatePermissions(preset);
const numbers=load('lib/batch-number.ts');const model=load('lib/model.ts',{'./batch-number':numbers});
const auth=load('lib/authorization.ts',{'cloudflare:workers':{env},'@/app/chatgpt-auth':{getChatGPTUser:async()=>identity},'@/lib/storage':{storage:()=>db},'@/lib/permissions':permissions});
const imports={'cloudflare:workers':{env},'@/lib/authorization':auth,'@/lib/storage':{storage:()=>db},'@/lib/permissions':permissions,'@/lib/batch-number':numbers,'@/lib/model':model};
const users=load('app/api/users/route.ts',imports),records=load('app/api/records/route.ts',imports),suggestion=load('app/api/batch-suggestion/route.ts',imports);
const request=(method,body,origin='https://test.local')=>new Request('https://test.local/api/records',{method,headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(body)});
const user=(id,email)=>({userId:id,email,displayName:id});
(async()=>{
 assert.equal((await records.GET()).status,401);assert.equal((await users.GET()).status,401);
 identity=user('intruder','unknown@example.com');assert.equal((await records.GET()).status,403);
 identity=user('owner-subject','owner@example.com');assert.equal((await auth.session()).isAdmin,true);
 let response=await users.POST(request('POST',{email:'stock@example.com',name:'Stock',unit:'انبار',status:'active',permissions:permissions.presets['انبار']}));assert.equal(response.status,201);let stock=(await response.json()).member;
 response=await users.POST(request('POST',{email:'prod@example.com',name:'Production',unit:'تولید',status:'active',permissions:permissions.presets['تولید']}));assert.equal(response.status,201);const production=(await response.json()).member;
 assert.equal((await users.POST(request('POST',{email:'OWNER@example.com',name:'x',unit:'x',status:'active',permissions:permissions.allPermissions}))).status,400);
 const batch={code:'B-1',part:'P',supplier:'S',date:'2026-09-13',quantity:'10',unit:'عدد',status:'تأیید'};
 assert.equal((await records.POST(request('POST',{kind:'batch',data:batch}))).status,201);
 assert.equal((await records.POST(request('POST',{kind:'device',data:{code:'D-1',model:'NF5',design:'R1',date:'2026-09-13'}}))).status,201);
 identity=user('stock-subject','stock@example.com');let session=await auth.session();assert.equal(session.isAdmin,false);
 const visible=(await (await records.GET()).json()).records;assert.equal(visible.length,1);assert.equal(visible[0].kind,'batch');
 assert.equal((await users.GET()).status,403);assert.equal((await users.POST(request('POST',{email:'evil@example.com'}))).status,403);
 assert.equal((await records.POST(request('POST',{kind:'device',data:{code:'D-2'},isAdmin:true}))).status,403);
 assert.equal((await records.POST(request('POST',{kind:'batch',data:{...batch,code:'B-2'}},'https://evil.local'))).status,403);
 identity=user('other-subject','stock@example.com');assert.equal((await records.GET()).status,403,'Email must not rebind a verified subject');
 identity=user('prod-subject','prod@example.com');assert.equal((await records.POST(request('POST',{kind:'event',data:{device:'device:D-1',stage:'تحویل',customer:'customer',date:'2026-09-13',operator:'test'}}))).status,403);
 assert.equal((await records.POST(request('POST',{kind:'event',data:{device:'device:D-1',stage:'مونتاژ',date:'2026-09-13',operator:'test'}}))).status,201);
 const batchRow=(await (await records.GET()).json()).records.find(r=>r.kind==='batch');assert.equal((await records.PATCH(request('PATCH',{id:batchRow.id,previous:JSON.stringify(batchRow.data),data:{...batchRow.data,status:'رد'}}))).status,403);
 identity=user('owner-subject','owner@example.com');response=await users.PATCH(request('PATCH',{...stock,status:'disabled'}));assert.equal(response.status,200);assert.equal((await users.PATCH(request('PATCH',{...stock,status:'active'}))).status,409);
 identity=user('stock-subject','stock@example.com');assert.equal((await records.GET()).status,403);assert.equal((await suggestion.GET(new Request('https://test.local/api/batch-suggestion?partCode=1023&date=2026-09-13'))).status,403);
 identity=user('another-owner-subject','owner@example.com');assert.equal((await records.GET()).status,403,'Owner subject is pinned');
 assert.ok(sql.prepare('SELECT count(*) n FROM access_audit').get().n>=6);assert.equal(sql.prepare("SELECT count(*) n FROM records WHERE kind='event'").get().n,1);
 identity=user('owner-subject','owner@example.com');delete env.TRACE_OWNER_EMAIL;assert.equal((await records.GET()).status,503,'Missing configuration fails closed');
 console.log('Access checks passed: anonymous/unlisted rejection, owner subject pinning, member binding, scoped reads, forbidden writes, stage restrictions, forged role rejection, CSRF, revocation, optimistic updates and audit records.');
})().catch(e=>{console.error(e);process.exitCode=1});
