const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');const root=path.resolve(__dirname,'..');const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',f),'utf8'));
const db={prepare(q){let args=[];return{bind(...a){args=a;return this},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:{changes:sql.prepare(q).run(...args).changes}}}}},async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const objects=new Map();const bucket={async put(k,b){objects.set(k,b.slice(0));return {key:k}},async get(k){const b=objects.get(k);return b?{arrayBuffer:async()=>b.slice(0)}:null},async delete(k){objects.delete(k)}};
let identity=null;const env={TRACE_OWNER_EMAIL:'owner@example.com',LLM_CONFIG_ENCRYPTION_KEY:require('node:crypto').randomBytes(32).toString('base64'),DB:db,BUCKET:bucket};
const cache={};function load(file){file=path.resolve(root,file);if(cache[file])return cache[file];const exports={};cache[file]=exports;const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
vm.runInNewContext(source,{exports,require:n=>{if(n==='cloudflare:workers')return {env};if(n==='@/app/chatgpt-auth')return {getChatGPTUser:async()=>identity};if(n.startsWith('@/')||n.startsWith('.')){const p=n.startsWith('@/')?path.join(root,n.slice(2)):path.resolve(path.dirname(file),n);return load(p+(path.extname(p)?'':'.ts'));}return require(n)},Response,Request,URL,URLSearchParams,Error,crypto:globalThis.crypto,Date,Intl,Set,Map,FormData,Blob,File,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,AbortController,ReadableStream,btoa,atob,setTimeout:(f,n)=>setTimeout(f,Math.min(n,10)),clearTimeout,console},{filename:file});return exports;}
const auth=load('lib/authorization.ts'),http=load('app/mcp/route.ts'),sse=load('lib/mcp/sse.ts'),tokens=load('app/api/mcp-tokens/route.ts'),configs=load('app/api/llm-config/route.ts'),secrets=load('lib/llm-secrets.ts'),catalog=load('lib/mcp/tools.ts');
const base='https://test.local';const owner={userId:'owner',email:'owner@example.com',displayName:'Owner',fullName:null};
const request=(path,method='GET',body,headers={})=>new Request(base+path,{method,headers:{origin:base,...(body?{'Content-Type':'application/json'}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});
const rpc=(method,params={},id=1)=>({jsonrpc:'2.0',method,params,id});
let token;
async function call(name,args={},key=token){const r=await http.POST(request('/mcp','POST',rpc('tools/call',{name,arguments:args}),key?{authorization:'Bearer '+key}:{}));assert.equal(r.status,200);const d=await r.json();if(d.result?.isError)return {error:d.result.content[0].text};return JSON.parse(d.result.content[0].text);}
async function mint(scope='read'){return (await (await tokens.POST(request('/api/mcp-tokens','POST',{name:'test',scope,days:1}))).json());}


const api=load('app/api/activation-code/route.ts'),context=load('lib/mcp/context.ts').mcpActor,algorithm=load('lib/activation-code.ts'),policy=load('lib/activation-code-access.ts');
const perms={read:[],write:[],eventStages:[],salesRoles:['manager']};
function actor(id,p=perms){const u={userId:id,email:id+'@test.local',name:id,isAdmin:false,permissions:p};sql.prepare("INSERT INTO app_members(id,email,name,unit,status,subject,permissions,created,updated) VALUES(?,?,?,'test','active',?,?,?,?)").run(id,u.email,id,id,JSON.stringify(p),new Date().toISOString(),new Date().toISOString());return u;}
const body=(deviceCode='1230123456')=>({id:crypto.randomUUID(),confirmed:true,deviceCode,reason:'درخواست مشتری'});
async function post(u,b=body(),headers={}){const r=await context.run(u,()=>api.POST(request('/api/activation-code','POST',b,headers)));return {status:r.status,d:await r.json()};}
async function get(u){const r=await context.run(u,()=>api.GET(request('/api/activation-code')));return {status:r.status,d:await r.json()};}
(async()=>{
 // Exact independent integer implementation of the supplied VB formula.
 const coeff=[[427n,123n],[742n,485n],[72n,363n],[10n,742n],[537n,181n],[763n,211n],[219n,431n],[745n,521n],[436n,858n],[910n,435n]];
 for(let n=0;n<10000;n++){const code=String((n*976543+17)%10000000000).padStart(10,'0').split('');code[3]=String(n%4);const input=code.join(''),a=BigInt(input.slice(0,5)),b=BigInt(input.slice(5))/10n,[x,y]=coeff[Number((a*a+b*b)%10n)],expected=String(((x*a*a+y*b)%1000000n)%100000n).padStart(5,'0');assert.equal(algorithm.generateActivationCode(input),expected);}
 assert.equal(algorithm.generateActivationCode('0000000000'),'00000');assert.equal(algorithm.generateActivationCode('۰۰۰۰۰۰۰۰۰۰'),'00000');assert.equal(algorithm.generateActivationCode('٠٠٠٠٠٠٠٠٠٠'),'00000');assert.equal(algorithm.generateActivationCode('1230123456'),algorithm.generateActivationCode('1230123459'));
 assert.equal((await api.POST(request('/api/activation-code','POST',body()))).status,401);
 const manager=actor('manager'),home=actor('home',{...perms,salesRoles:[],serviceDomains:['home'],serviceRoles:['support']}),other=actor('other');
 for(const [id,p] of Object.entries({sales:{...perms,salesRoles:['staff']},hospital:{...home.permissions,serviceDomains:['hospital']},agent:{...home.permissions,serviceAgentId:'agent'},agentRole:{...perms,serviceRoles:['agent']},finance:{...home.permissions,serviceRoles:['finance']},customer:{...perms,hospitalCenterId:'hospital'},external:{...perms,salesAgentId:'sales'}})){const u=actor(id,p);assert.equal(policy.canGenerateActivationCode(u),false);assert.equal((await post(u)).status,403);assert.equal((await get(u)).status,403);}
 for(const role of ['intake','technician']){const u=actor(role,{...home.permissions,serviceRoles:[role]});assert.equal((await post(u)).status,200)}
 for(const value of ['1234123456','123012345','12301234567','+123012345','1e00000009','1230 23456','1230.23456',1230123456])assert.equal((await post(manager,body(value))).status,400,String(value));
 for(const extra of [{confirmed:false},{reason:''},{id:'bad'},{extra:'bad'}])assert.equal((await post(manager,{...body(),...extra})).status,400);
 assert.equal((await post(manager,body(),{'x-assistant-account':'other'})).status,409);assert.equal((await post(manager,body(),{origin:'https://evil.test'})).status,403);
 const b=body('۱۲۳۰۱۲۳۴۵۶'),r=await post(manager,b);assert.equal(r.status,200,JSON.stringify(r));assert.match(r.d.activationCode,/^[0-9]{5}$/);assert.equal(r.d.deviceCode,'1230123456');assert.equal((await post(manager,b)).d.repeated,true);assert.equal(sql.prepare('SELECT COUNT(*) n FROM inventory_operations WHERE id=?').get(b.id).n,1);
 assert.equal((await post(manager,{...b,reason:'different'})).status,409);assert.equal((await post(other,b)).status,409);
 const h=await get(manager);assert.equal(h.status,200);assert.equal(h.d.history.length,1);assert.equal(h.d.history[0].activationCode,r.d.activationCode);assert.equal((await get(home)).d.history.length,0);
 assert.equal((await post(home)).status,200);
 sql.prepare("UPDATE app_members SET permissions=? WHERE id='home'").run(JSON.stringify({...home.permissions,serviceRoles:['finance']}));assert.equal((await post(home)).status,403);assert.equal((await get(home)).status,403);
 sql.prepare("UPDATE app_members SET status='disabled' WHERE id='other'").run();assert.equal((await post(other)).status,403);
 // A concurrent revocation invalidates the atomic audit guard and rolls back.
 const batch=db.batch.bind(db),race=body();db.batch=async(stmts)=>{sql.prepare("UPDATE app_members SET status='disabled' WHERE id='manager'").run();return batch(stmts)};assert.equal((await post(manager,race)).status,409);assert.equal(sql.prepare('SELECT id FROM inventory_operations WHERE id=?').get(race.id),undefined);db.batch=batch;sql.prepare("UPDATE app_members SET status='active' WHERE id='manager'").run();
 // Existing reset triggers stop new codes, while the same existing operation remains retryable.
 sql.prepare("UPDATE reset_control SET phase='maintenance',job_id='test-freeze',internal=0,updated=? WHERE id=1").run(new Date().toISOString());const frozen=body();assert.equal((await post(manager,frozen)).status,423);assert.equal(sql.prepare('SELECT id FROM inventory_operations WHERE id=?').get(frozen.id),undefined);sql.prepare("UPDATE reset_control SET phase='testing',job_id=NULL WHERE id=1").run();
 const reset=load('lib/reset-contract.ts');assert.ok(reset.resetTables.inventory_operations);for(const scope of ['operations','full']){const where=reset.resetWhere('inventory_operations',scope);sql.exec('BEGIN');sql.exec('DELETE FROM inventory_operations WHERE '+where);assert.equal(sql.prepare('SELECT COUNT(*) n FROM inventory_operations').get().n,0);sql.exec('ROLLBACK');assert.ok(sql.prepare('SELECT id FROM inventory_operations WHERE id=?').get(b.id));}
 assert.equal(sql.prepare('SELECT COUNT(*) n FROM service_activations').get().n,0);assert.equal(sql.prepare('SELECT COUNT(*) n FROM records').get().n,0);
 const training=load('lib/training-context.ts').trainingContext;assert.equal((await training.run({},()=>post(manager))).status,403);
 // Real MCP auth enforces write scope and the identical domain handler.
 identity=owner;const read=await mint('read'),write=await mint('read_write');assert.match(write.token,/^nfy_/);assert.match(read.token,/^nfy_/);identity=null;const denied=await call('generate_activation_code',body(),read.token);assert.ok(denied.error);const generated=await call('generate_activation_code',body(),write.token);assert.match(generated.activationCode,/^[0-9]{5}$/);const hist=await call('get_activation_code_history',{},read.token);assert.equal(hist.history.length,1);
 assert.equal(load('lib/assistant-policy.ts').actionSection('generate_activation_code',{}),'activation-code');assert.ok(load('lib/assistant-policy.ts').assistantWriteNames.has('generate_activation_code'));
 console.log('PASS activation: 10,000 VB-compatible vectors; normalization, leading zeros, roles, account/origin, fresh permissions, rollback, reset freeze/backup contract, retry audit, isolated history and MCP scopes.');
})().catch(e=>{console.error(e);process.exit(1)});
