const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');const root=path.resolve(__dirname,'..');const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',f),'utf8'));
const db={prepare(q){let args=[];return{bind(...a){args=a;return this},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:{changes:sql.prepare(q).run(...args).changes}}}}},async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const objects=new Map();const bucket={async put(k,b){objects.set(k,b.slice(0));return {key:k}},async get(k){const b=objects.get(k);return b?{arrayBuffer:async()=>b.slice(0)}:null},async delete(k){objects.delete(k)}};
let identity=null;const env={TRACE_OWNER_EMAIL:'owner@example.com',LLM_CONFIG_ENCRYPTION_KEY:require('node:crypto').randomBytes(32).toString('base64'),DB:db,BUCKET:bucket};
const cache={};function load(file){file=path.resolve(root,file);if(cache[file])return cache[file];const exports={};cache[file]=exports;const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
vm.runInNewContext(source,{exports,require:n=>{if(n==='cloudflare:workers')return {env};if(n==='@/app/chatgpt-auth')return {getChatGPTUser:async()=>identity};if(n.startsWith('@/')||n.startsWith('.')){const p=n.startsWith('@/')?path.join(root,n.slice(2)):path.resolve(path.dirname(file),n);return load(p+(path.extname(p)?'':'.ts'));}return require(n)},structuredClone,Response,Request,URL,URLSearchParams,Error,crypto:globalThis.crypto,Date,Intl,Set,Map,FormData,Blob,File,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,AbortController,ReadableStream,btoa,atob,setTimeout:(f,n)=>setTimeout(f,Math.min(n,10)),clearTimeout,console},{filename:file});return exports;}


const ctx=load('lib/mcp/context.ts').mcpActor,api=load('app/api/personnel/route.ts'),files=load('app/api/personnel/files/route.ts'),domain=load('lib/personnel.ts'),catalog=load('lib/mcp/tools.ts'),tasks=load('app/api/tasks/route.ts'),duties=load('lib/duties.ts');
let tail=Promise.resolve();const batch=db.batch.bind(db);db.batch=stmts=>{const next=tail.then(()=>batch(stmts));tail=next.catch(()=>{});return next};
const base='https://test.local',now=new Date().toISOString(),today=duties.dayAt(),day=duties.addDay(today,-10),next=duties.addDay(today,2);
const req=(url,b,origin=base)=>new Request(base+url,{method:b?'POST':'GET',headers:{origin,'Content-Type':'application/json'},...(b?{body:JSON.stringify(b)}:{})});
function actor(id,roles=[],extra={}){const u={userId:'local:'+id,email:id+'@test.local',name:id,isAdmin:false,permissions:{read:[],write:[],eventStages:[],personnelRoles:roles,...extra}};sql.prepare("INSERT INTO app_members(id,email,name,unit,status,subject,permissions,created,updated) VALUES(?,?,?,'company','active',?,?,?,?)").run(id,u.email,id,u.userId,JSON.stringify(u.permissions),now,now);return u;}

const assets=load('app/api/assets/route.ts'),afiles=load('app/api/assets/files/route.ts'),ad=load('lib/assets.ts'),sync=load('lib/assets-tasks.ts');
const owner={userId:'owner',email:'owner@example.com',name:'owner',isAdmin:true,permissions:load('lib/permissions.ts').allPermissions},keeper=actor('keeper',[],{assetRoles:['custodian']}),alice=actor('alice'),bob=actor('bob'),hr=actor('hr',['hr']),external=actor('external',[],{salesAgentId:'outside',salesRoles:['agent']});
const entity=id=>{const r=sql.prepare('SELECT * FROM flow_entities WHERE id=?').get(id);return r?{...r,data:JSON.parse(r.data)}:null};
async function get(u){const r=await ctx.run(u,()=>assets.GET());return {status:r.status,data:await r.json()}}
async function post(u,b){const r=await ctx.run(u,()=>assets.POST(req('/api/assets',{id:crypto.randomUUID(),confirmed:true,revision:0,notes:'Actual test evidence',...b})));return {status:r.status,data:await r.json()}}
const reg={mode:'register',code:'A-001',name:'قالب تزریق',category:'قالب',brand:'brand',model:'model',serial:'serial',specifications:'steel 2 cavities',condition:'good',location:'انبار شرکت',day:today,reference:'receipt-001'};
const transfer=(id,revision,kind='employee',extra={})=>({mode:'transfer',recordId:id,revision,holderKind:kind,holderId:'alice',holderName:'Contractor',contractorCode:'C-1',location:'Factory',condition:'good',day:today,reference:'handover-001',...extra});
(async()=>{
assert.equal((await assets.GET()).status,401);assert.equal((await get(external)).status,403);assert.equal((await ctx.run(keeper,()=>assets.GET(new Request(base+'/api/assets',{headers:{'x-asset-account':'wrong'}})))).status,409);assert.equal((await post(alice,reg)).status,403);assert.equal((await post(hr,reg)).status,403);
const id=crypto.randomUUID();let r=await post(keeper,{...reg,id});assert.equal(r.status,200,JSON.stringify(r));assert.equal(entity(id).data.holderKind,'stock');assert.equal((await post(keeper,{...reg,id})).data.repeated,true);assert.equal((await post(keeper,{...reg,id,name:'changed'})).status,409);assert.equal((await post(keeper,reg)).status,409);assert.equal((await post(keeper,{...reg,code:'A-002',confirmed:false})).status,400);
assert.equal((await post(keeper,transfer(id,1,'employee',{holderId:'external'}))).status,400);assert.equal((await post(keeper,transfer(id,1))).status,200);assert.equal((await get(alice)).data.records.filter(r=>r.type==='asset_item').length,1);assert.equal((await get(bob)).data.records.length,0);assert.equal((await get(hr)).data.records.filter(r=>r.type==='asset_item').length,1);assert.equal((await post(keeper,transfer(id,1))).status,409);
let clearance=await post(alice,{mode:'request_clearance'});assert.equal(clearance.status,200,JSON.stringify(clearance));const cid=clearance.data.id;assert.equal((await post(bob,{mode:'request_clearance',memberId:'alice'})).status,403);assert.equal((await post(keeper,{mode:'approve_clearance',recordId:cid,revision:1,reference:'exit'})).status,409);assert.equal((await post(keeper,transfer(id,2))).status,409);assert.equal((await post(alice,{mode:'approve_clearance',recordId:cid,revision:1,reference:'exit'})).status,403);
assert.equal((await post(keeper,transfer(id,2,'stock'))).status,200);assert.equal((await post(keeper,{mode:'approve_clearance',recordId:cid,revision:1,reference:'asset-exit-1'})).status,200);assert.equal((await post(keeper,transfer(id,3))).status,409);assert.equal((await post(hr,{mode:'cancel_clearance',recordId:cid,revision:2})).status,200);assert.equal((await post(keeper,transfer(id,3,'contractor'))).status,200);
const asset=entity(id);assert.equal(asset.data.holderName,'Contractor');const p=load('lib/persian-date.ts').solarParts(today),np=load('lib/persian-date.ts').solarParts(asset.data.annualDue);assert.equal(np.year,p.year+1);let tasksFor=()=>sql.prepare("SELECT * FROM duty_runs WHERE template_id='assets' AND json_extract(data,'$.recordId')=? AND state='open'").all(id);assert.equal(tasksFor().length,1);await sync.syncAssetTasks();assert.equal(tasksFor().length,1,'annual tasks must deduplicate');
const task=tasksFor()[0];let taskres=await ctx.run(keeper,()=>tasks.POST(req('/api/tasks',{id:crypto.randomUUID(),mode:'submit',taskId:task.id,revision:task.revision,note:'fake completion'})));assert.equal(taskres.status,400,'generic task submission cannot close a written confirmation');
const confirm={mode:'confirm_annual',recordId:id,revision:4,day:today,signer:'Actual contractor signer',reference:'letter-1',fileId:'missing',actualConfirmation:true,location:'Factory',condition:'good'};assert.equal((await post(keeper,confirm)).status,400);
const fid=crypto.randomUUID(),bytes='actual letter evidence';function upload(u,fid,revision=4){return ctx.run(u,()=>afiles.POST(new Request(base+'/api/assets/files?id='+fid+'&assetId='+id+'&revision='+revision+'&filename=letter.pdf&confirmed=true',{method:'POST',headers:{origin:base,'Content-Type':'application/octet-stream'},body:bytes})))}
assert.equal((await upload(alice,fid)).status,404);assert.equal((await upload(keeper,fid)).status,200);assert.equal((await upload(keeper,fid)).status,200);assert.ok(!(await get(keeper)).data.records.find(r=>r.id===fid).data.objectKey);assert.equal((await post(keeper,{...confirm,fileId:fid,actualConfirmation:false})).status,400);assert.equal((await post(keeper,{...confirm,fileId:fid})).status,200);assert.equal(entity(id).data.lastSigner,confirm.signer);await sync.syncAssetTasks();assert.equal(sql.prepare('SELECT state FROM duty_runs WHERE id=?').get(task.id).state,'completed');
let download=await ctx.run(keeper,()=>afiles.GET(req('/api/assets/files?id='+fid)));assert.equal(download.status,200);assert.equal(await download.text(),bytes);download=await ctx.run(bob,()=>afiles.GET(req('/api/assets/files?id='+fid)));assert.equal(download.status,404);
const principal={user:keeper,scope:'read_write',tokenId:null};const read=await catalog.executeTool('get_company_assets',{},base,principal);assert.ok(read.records.some(r=>r.id===id));await assert.rejects(()=>catalog.executeTool('assets_apply',{id:crypto.randomUUID(),confirmed:true,mode:'register',revision:0,notes:'test',...reg,code:'MCP'},base,{...principal,scope:'read'}));const mc=await catalog.executeTool('assets_apply',{id:crypto.randomUUID(),confirmed:true,revision:0,notes:'test',...reg,code:'MCP'},base,principal);assert.ok(mc.saved);
const current=entity(id);assert.equal((await post(keeper,transfer(id,current.revision,'stock'))).status,200);const oldLetter=await ctx.run(alice,()=>afiles.GET(req('/api/assets/files?id='+fid)));assert.equal(oldLetter.status,404,'old contractor letter cannot follow a new employee holder');
const before=entity(id).revision;const raced=await Promise.all([post(keeper,transfer(id,before,'employee',{holderId:'bob'})),post(keeper,transfer(id,before,'employee',{holderId:'alice'}))]);assert.equal(raced.filter(r=>r.status===200).length,1,'only one concurrent handover wins');assert.equal(entity(id).revision,before+1);
// Personnel end-of-employment cannot bypass the asset return/clearance gate.
let final=entity(id);if(final.data.holderId!=='alice'){assert.equal((await post(keeper,transfer(id,final.revision,'employee',{holderId:'alice'}))).status,200);final=entity(id)}
const employeeId=crypto.randomUUID(),empBody={id:employeeId,confirmed:true,revision:0,notes:'HR test',mode:'employee',memberId:'alice',managerId:'bob',code:'E-A',unit:'company',title:'employee',location:'HQ',start:day,employment:'full time',leaveMinutes:0};
await ctx.run(hr,()=>domain.applyPersonnel(hr,empBody));
await assert.rejects(()=>ctx.run(hr,()=>domain.applyPersonnel(hr,{...empBody,id:crypto.randomUUID(),recordId:employeeId,revision:1,active:false})),/اموال/);
assert.equal((await post(keeper,transfer(id,final.revision,'stock'))).status,200);await assert.rejects(()=>ctx.run(hr,()=>domain.applyPersonnel(hr,{...empBody,id:crypto.randomUUID(),recordId:employeeId,revision:1,active:false})),/اموال/);
const exit=await post(hr,{mode:'request_clearance',memberId:'alice'});assert.equal(exit.status,200);assert.equal((await post(keeper,{mode:'approve_clearance',recordId:exit.data.id,revision:1,reference:'exit-actual'})).status,200);await ctx.run(hr,()=>domain.applyPersonnel(hr,{...empBody,id:crypto.randomUUID(),recordId:employeeId,revision:1,active:false}));assert.equal(entity(employeeId).data.state,'disabled');
// Generic maintenance freeze covers these new operational rows and immutable file manifests.
sql.prepare("UPDATE reset_control SET phase='maintenance' WHERE id=1").run();
const frozen=await post(keeper,{...reg,code:'FROZEN'});assert.ok(frozen.status>=400);assert.equal(sql.prepare("SELECT COUNT(*) n FROM flow_entities WHERE type='asset_item' AND json_extract(data,'$.code')='FROZEN'").get().n,0);sql.prepare("UPDATE reset_control SET phase='testing' WHERE id=1").run();
assert.ok(sql.prepare("SELECT COUNT(*) n FROM access_audit WHERE action GLOB 'asset_*'").get().n>5);assert.equal(load('lib/reset-contract.ts').resetWhere('flow_entities','operations').includes('asset_item'),false,'assets are operational reset data');
console.log('PASS assets: role/privacy, idempotency, unique code, custody revision/race, exit return gate, real annual letter, Persian anniversary, scheduler dedup, immutable file access, MCP and freeze rollback');
})().catch(e=>{console.error(e);process.exitCode=1});
