const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');const root=path.resolve(__dirname,'..');const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',f),'utf8'));
const db={prepare(q){let args=[];return{bind(...a){args=a;return this},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:{changes:sql.prepare(q).run(...args).changes}}}}},async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const objects=new Map();const bucket={async put(k,b){objects.set(k,b.slice(0));return {key:k}},async get(k){const b=objects.get(k);return b?{arrayBuffer:async()=>b.slice(0)}:null},async delete(k){objects.delete(k)}};
let cookie="";let identity=null;const env={TRACE_OWNER_EMAIL:'owner@example.com',LLM_CONFIG_ENCRYPTION_KEY:require('node:crypto').randomBytes(32).toString('base64'),DB:db,BUCKET:bucket};
let providerCalls=0,providerMode="normal",sent=[];const cache={};function load(file){file=path.resolve(root,file);if(cache[file])return cache[file];const exports={};cache[file]=exports;const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
vm.runInNewContext(source,{exports,require:n=>{if(n==='next/headers')return {cookies:async()=>({get:()=>cookie?{value:cookie}:undefined})};if(n==='cloudflare:workers')return {env};if(n==='@/app/chatgpt-auth')return {getChatGPTUser:async()=>identity};if(n.startsWith('@/')||n.startsWith('.')){const p=n.startsWith('@/')?path.join(root,n.slice(2)):path.resolve(path.dirname(file),n);return load(p+(path.extname(p)?'':'.ts'));}return require(n)},fetch:async(url,options)=>{providerCalls++;const body=JSON.parse(options.body);sent.push(body);assert.equal(options.redirect,'manual');assert.equal(options.headers.Authorization,'Bearer provider-test-key');if(providerMode==='redirect')return new Response('',{status:302,headers:{location:'https://other.test'}});if(providerMode==='error')return new Response('',{status:401});if(providerMode==='write'&&providerCalls===1)return Response.json({choices:[{message:{tool_calls:[{id:'bad',type:'function',function:{name:'create_record',arguments:JSON.stringify({kind:'product',data:{},confirmed:true})}}]}}]});if(providerMode==='read'&&providerCalls===1)return Response.json({choices:[{message:{tool_calls:[{id:'read',type:'function',function:{name:'list_records',arguments:JSON.stringify({kind:'batch',limit:5})}}]}}]});return Response.json({choices:[{message:{content:'پاسخ آزمایشی دستیار'}}]});},Response,Request,URL,URLSearchParams,Error,crypto:globalThis.crypto,Date,Intl,Set,Map,FormData,Blob,File,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,AbortController,ReadableStream,btoa,atob,setTimeout:(f,n)=>setTimeout(f,Math.min(n,10)),clearTimeout,console},{filename:file});return exports;}
const auth=load('lib/authorization.ts'),http=load('app/mcp/route.ts'),sse=load('lib/mcp/sse.ts'),tokens=load('app/api/mcp-tokens/route.ts'),configs=load('app/api/llm-config/route.ts'),secrets=load('lib/llm-secrets.ts'),catalog=load('lib/mcp/tools.ts');
const base='https://test.local';const owner={userId:'owner',email:'owner@example.com',displayName:'Owner',fullName:null};
const request=(path,method='GET',body,headers={})=>new Request(base+path,{method,headers:{origin:base,...(body?{'Content-Type':'application/json'}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});
const rpc=(method,params={},id=1)=>({jsonrpc:'2.0',method,params,id});
let token;
async function call(name,args={},key=token){const r=await http.POST(request('/mcp','POST',rpc('tools/call',{name,arguments:args}),key?{authorization:'Bearer '+key}:{}));assert.equal(r.status,200);const d=await r.json();if(d.result?.isError)return {error:d.result.content[0].text};return JSON.parse(d.result.content[0].text);}
async function mint(scope='read'){return (await (await tokens.POST(request('/api/mcp-tokens','POST',{name:'test',scope,days:1}))).json());}

const chat=load('app/api/assistant/route.ts');
(async()=>{
 assert.equal((await chat.GET()).status,401);identity=owner;await auth.session();
 const profileId=crypto.randomUUID();let r=await configs.PUT(request('/api/llm-config','PUT',{id:profileId,revision:0,name:'Test model',model:'compatible-model',baseUrl:'https://example.test/v1',systemPrompt:'Answer briefly.',temperature:0.4,maxTokens:1000,apiToken:'provider-test-key'}));assert.equal(r.status,201);
 const send=(message,id=crypto.randomUUID())=>chat.POST(request('/api/assistant','POST',{requestId:id,profileId,message}));
 let d=await (await chat.GET()).json();assert.equal(d.profiles.length,1);assert.ok(!JSON.stringify(d).includes('provider-test-key'));assert.equal(d.history.length,0);
 providerMode='read';const id=crypto.randomUUID();r=await send('فهرست بچ‌ها',id);assert.equal(r.status,200,await r.clone().text());assert.equal(providerCalls,2);assert.ok(sent[0].tools.every(t=>!['create_record','ask_assistant','list_llm_configs'].includes(t.function.name)));
 r=await send('فهرست بچ‌ها',id);assert.equal(r.status,200);assert.equal(providerCalls,2);d=await (await chat.GET()).json();assert.equal(d.history.length,1);
 providerCalls=0;providerMode='write';r=await send('یک محصول بساز');assert.equal(r.status,200);assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM records').get().n,0);assert.ok(sent.at(-1).messages.some(m=>m.role==='tool'&&m.content.includes('مجاز نیست')));
 const permissions={read:['batch'],write:[],eventStages:[],finance:'none'};sql.prepare('INSERT INTO app_members(id,email,name,unit,status,subject,permissions,created,updated) VALUES(?,?,?,?,?,?,?,?,?)').run('reader','reader@example.com','Reader','unit','active','reader',JSON.stringify(permissions),'now','now');identity={userId:'reader',email:'reader@example.com',displayName:'Reader',fullName:null};d=await (await chat.GET()).json();assert.equal(d.history.length,0);
 providerMode='error';r=await send('سلام');assert.equal(r.status,502);assert.ok(!(await r.text()).includes('provider-test-key'));assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM assistant_turns WHERE owner=?').get('reader').n,0);
 providerMode='redirect';const before=providerCalls;r=await send('redirect test');assert.equal(r.status,502);assert.equal(providerCalls,before+1);assert.ok(!(await r.text()).includes('provider-test-key'));

 const accounts=load('app/api/users/route.ts'),login=load('app/api/auth/login/route.ts');identity=owner;providerMode='normal';
 for(const username of ['alice','bob']){const response=await accounts.POST(request('/api/users','POST',{username,password:'Private-user-pass-123',name:username,unit:'unit',status:'active',permissions}));assert.equal(response.status,201);}
 async function enter(username){cookie='';identity=null;const r=await login.POST(request('/api/auth/login','POST',{username,password:'Private-user-pass-123'}));assert.equal(r.status,200);cookie=r.headers.get('set-cookie').split(';')[0].split('=')[1];return (await auth.session()).userId;}
 const alice=await enter('alice'),aliceRequest=crypto.randomUUID();r=await send('ALICE_PRIVATE_QUESTION',aliceRequest);assert.equal(r.status,200);d=await (await chat.GET()).json();assert.equal(d.accountId,alice);assert.equal(d.history.length,1);
 const bob=await enter('bob');r=await chat.GET(request('/api/assistant','GET',undefined,{'x-assistant-account':alice}));assert.equal(r.status,409);assert.ok(!(await r.text()).includes('ALICE_PRIVATE'));
 r=await chat.POST(request('/api/assistant','POST',{requestId:crypto.randomUUID(),profileId,message:'stale UI'},{'x-assistant-account':alice}));assert.equal(r.status,409);
 r=await send('ALICE_PRIVATE_QUESTION',aliceRequest);assert.equal(r.status,409);
 r=await send('BOB_PRIVATE_QUESTION');assert.equal(r.status,200);assert.ok(!JSON.stringify(sent.at(-1).messages).includes('ALICE_PRIVATE_QUESTION'));
 r=await chat.GET();assert.match(r.headers.get('cache-control'),/private.*no-store/);assert.match(r.headers.get('vary'),/Cookie/);d=await r.json();assert.equal(d.accountId,bob);assert.equal(d.history.length,1);assert.equal(d.history[0].question,'BOB_PRIVATE_QUESTION');
 await enter('alice');d=await (await chat.GET()).json();assert.equal(d.history.length,1);assert.equal(d.history[0].question,'ALICE_PRIVATE_QUESTION');
 cookie='';identity=owner;d=await (await chat.GET()).json();assert.ok(!JSON.stringify(d.history).includes('PRIVATE_QUESTION'));
 console.log('Chat privacy passed: two password accounts, private history and provider context, stale-account requests rejected, cross-owner retries blocked, admin isolated.');
 console.log('Assistant passed: auth, private histories, redacted config, mocked provider, authorized read tools, blocked writes/recursion, duplicate retry and provider errors.');
})().catch(e=>{console.error(e);process.exit(1)});
