const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { DatabaseSync } = require('node:sqlite');
const ts = require('typescript');
const root = path.resolve(__dirname, '..');
function load(file, imports = {}) {
  const exports = {};
  const code = ts.transpileModule(fs.readFileSync(path.join(root, file), 'utf8'), {compilerOptions: {module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022}}).outputText;
  vm.runInNewContext(code, {exports, require: name => {if (!(name in imports)) throw new Error('Unmapped import: ' + name); return imports[name];}, Response, Request, URL, Error, crypto: globalThis.crypto, console: {error() {}}, Intl, Date, Set});
  return exports;
}
const numbers = load('lib/batch-number.ts');
assert.equal(numbers.receiptDay('2026-09-13').compact, '14050622');
assert.equal(numbers.receiptDay('2025-03-20').compact, '14031230');
assert.equal(numbers.receiptDay('2025-03-21').compact, '14040101');
assert.throws(() => numbers.receiptDay('2026-02-30'));
assert.equal(numbers.normalizePartCode(' ۰۰۱۲۳ '), '00123');
assert.equal(numbers.normalizePartCode('١٠٢٣'), '1023');
assert.throws(() => numbers.normalizePartCode('10-23'));
assert.equal(numbers.suggestBatchNumber('1023', '2026-09-13', []).code, '1023-14050622-001');
assert.equal(numbers.suggestBatchNumber('1023', '2026-09-13', ['1023-14050622-001', '1023-14050622-009', '9999-14050622-999', '1023-14050621-099']).code, '1023-14050622-010');
assert.equal(numbers.suggestBatchNumber('1023', '2026-09-13', ['1023-14050622-999']).sequence, '1000');
assert.equal(numbers.suggestBatchNumber('1023', '2026-09-14', ['1023-14050622-001']).sequence, '001');
assert.throws(() => numbers.validateBatchIdentity({batchScheme: numbers.BATCH_SCHEME, partCode: '1023', date: '2026-09-14', code: '1023-14050622-001'}));
assert.throws(() => numbers.validateBatchIdentity({batchScheme: numbers.BATCH_SCHEME, partCode: '1023', date: '2026-09-13', code: '1023-14050622-000'}));
numbers.validateBatchIdentity({code: 'CMP-2608-01'});
const sqlite = new DatabaseSync(':memory:');
for(const file of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync(path.join(root,'drizzle',file),'utf8'));
const storage = {async batch(statements){sqlite.exec('BEGIN');try{const results=[];for(const statement of statements)results.push(await statement.run());sqlite.exec('COMMIT');return results;}catch(error){sqlite.exec('ROLLBACK');throw error;}},prepare(query) {let args = []; return {bind(...values) {args = values; return this;}, async all() {return {results: sqlite.prepare(query).all(...args)};}, async first() {return sqlite.prepare(query).get(...args) || null;}, async run() {return {meta: {changes: sqlite.prepare(query).run(...args).changes}};}};}};
const model = load('lib/model.ts', {'./batch-number': numbers});
const auth={requireAccess:async()=>({userId:'owner',isAdmin:true,permissions:{read:['batch','device','event','service','action']}}),can:()=>true,checkOrigin:()=>{},accessResponse:()=>null,AccessError:Error};
const imports = {'@/lib/authorization':auth,'@/lib/storage': {storage: () => storage}, '@/lib/model': model, '@/lib/batch-number': numbers};
const api = load('app/api/records/route.ts', imports);
const suggestion = load('app/api/batch-suggestion/route.ts', imports);
const request = (method, body) => new Request('https://test.local/api/records', {method, headers: {'Content-Type': 'application/json', Origin: 'https://test.local'}, body: JSON.stringify(body)});
(async () => {
  const url = 'https://test.local/api/batch-suggestion?partCode=1023&date=2026-09-13';
  let result = await suggestion.GET(new Request(url)); assert.equal(result.status, 200);
  let candidate = await result.json(); assert.equal(candidate.code, '1023-14050622-001');
  assert.equal(sqlite.prepare('SELECT count(*) n FROM records').get().n, 0, 'Suggestion must not reserve or mutate records');
  const data = {partCode: '۱۰۲۳', date: '2026-09-13', code: candidate.code, batchScheme: candidate.scheme, part: 'Compressor', supplier: 'Supplier A', quantity: '10', unit: 'عدد', status: 'تأیید', manufacturerLot: 'LOT-A/001'};
  const saved = await api.POST(request('POST', {kind: 'batch', data})); assert.equal(saved.status, 201);
  const row = (await saved.json()).record; assert.equal(row.data.partCode, '1023'); assert.equal(row.data.manufacturerLot, 'LOT-A/001');
  const collision = await api.POST(request('POST', {kind: 'batch', data})); assert.equal(collision.status, 409);
  candidate = await (await suggestion.GET(new Request(url))).json(); assert.equal(candidate.code, '1023-14050622-002');
  const stale = await api.POST(request('POST', {kind: 'batch', data: {...data, code: candidate.code, date: '2026-09-14'}})); assert.equal(stale.status, 400);
  const manual = await api.POST(request('POST', {kind: 'batch', data: {...data, code: 'MANUAL-2026-A', batchScheme: ''}})); assert.equal(manual.status, 201);
  const existing = {...data, code: 'LEGACY-A', partCode: '', batchScheme: ''}; assert.equal((await api.POST(request('POST', {kind: 'batch', data: existing}))).status, 201);
  const changed = await api.PATCH(request('PATCH', {id: row.id, data: {...row.data, code: 'NEW'}, previous: JSON.stringify(row.data)})); assert.equal(changed.status, 400);
  const records = (await (await api.GET()).json()).records;
  assert.equal(records.length, 3); assert.ok(records.some(r => r.data.code === 'LEGACY-A'));
  const invalid = await suggestion.GET(new Request(url.replace('1023', 'invalid'))); assert.equal(invalid.status, 400);
  console.log('Batch numbering checks passed: Jalali boundaries, invalid dates, digit normalization, sequences, read-only suggestions, persistence, collision/stale rejection, manual and legacy compatibility.');
})().catch(err => {console.error(err); process.exitCode = 1;});
