const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite'),root=path.resolve(__dirname,'..');
const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',f),'utf8'));
const db={prepare(q){let args=[];return{bind(...a){args=a;return this},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:{changes:sql.prepare(q).run(...args).changes}}}}},async batch(stmts){sql.exec('BEGIN');try{for(const s of stmts)await s.run();sql.exec('COMMIT');}catch(e){sql.exec('ROLLBACK');throw e;}}};
let user={userId:'owner',name:'Owner',isAdmin:true,permissions:{finance:'write'}};
class AccessError extends Error{constructor(m,s){super(m);this.status=s;}}
const auth={AccessError,requireAccess:async()=>user,checkOrigin:r=>{if(r.headers.get('origin')!=='https://test.local')throw new AccessError('origin',403);},accessResponse:e=>e instanceof AccessError?Response.json({error:e.message},{status:e.status}):null};
const cache={};function load(file){file=path.resolve(root,file);if(cache[file])return cache[file];const exports={};cache[file]=exports;vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>{if(n==='@/lib/storage')return {storage:()=>db};if(n==='@/lib/authorization')return auth;if(n==='@/lib/firmware-storage')return {boundedBody:async r=>new Uint8Array(await r.arrayBuffer())};if(n.startsWith('@/'))return load(n.slice(2)+'.ts');return require(n)},Response,Request,URL,Error,Date,Intl,Map,Set,TextEncoder,TextDecoder,Uint8Array,crypto:globalThis.crypto,console},{filename:file});return exports;}
const lib=load('lib/costing.ts'),api=load('app/api/costing/route.ts');
const rec=(id,kind,data)=>sql.prepare('INSERT INTO records(id,kind,payload,created) VALUES(?,?,?,?)').run(id,kind,JSON.stringify(data),'2026-09-01T08:00:00Z');
const entity=(id,type,data)=>sql.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').run(id,type,JSON.stringify(data),'2026-09-01T08:00:00Z','2026-09-01T08:00:00Z');
let sequence=0;function op(kind,body,entries,date='2026-09-02T08:00:00Z'){const id=crypto.randomUUID();sql.prepare('INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,?,?,?,?,1)').run(id,kind,JSON.stringify(body),'owner',date);for(const [item,wh,delta] of entries)sql.prepare('INSERT INTO inventory_entries(id,operation_id,item_id,warehouse,delta) VALUES(?,?,?,?,?)').run(String(++sequence),id,item,wh,delta);return id;}
const body=(mode,extra={})=>({mode,id:crypto.randomUUID(),confirmed:true,notes:'evidence verified',revision:0,...extra});
async function post(b,status=200){const r=await api.POST(new Request('https://test.local/api/costing',{method:'POST',headers:{origin:'https://test.local'},body:JSON.stringify(b)}));const d=await r.json();assert.equal(r.status,status,JSON.stringify(d));return d;}
const get=async()=>{const r=await api.GET();assert.equal(r.status,200);return r.json();};
(async()=>{
rec('p','product',{name:'5L'});rec('d','device',{code:'S1',product:'p'});for(const b of ['b1','b2'])rec(b,'batch',{code:b,partCode:'11',unit:'عدد'});entity('material:11','material',{code:'11',name:'compressor',unit:'عدد'});
sql.prepare('INSERT INTO bom_versions(id,product_id,version,lines,created,actor) VALUES(?,?,?,?,?,?)').run('bom','p',1,JSON.stringify([{partCode:'11',name:'compressor',unit:'عدد',quantity:'1'}]),'2026-09-01','owner');entity('d','build',{bomId:'bom',state:'assembled'});
// 10 @100 then 10 @300 => average 200; warehouse transfer and QC rejection are not consumption.
op('flow_receipt',{},[['b1','quarantine',12000]],'2026-09-01T08:00:00Z');op('flow_shelve',{},[['b1','quarantine',-10000],['b1','raw',10000]],'2026-09-01T09:00:00Z');op('flow_shelve',{},[['b2','raw',10000]],'2026-09-01T10:00:00Z');op('flow_issue',{},[['b1','raw',-2000],['b1','line',2000]],'2026-09-01T11:00:00Z');op('flow_build',{deviceId:'d'},[['b1','line',-1000]]);op('flow_repair',{deviceId:'d'},[['b1','nonconforming',1000],['b1','line',-1000]],'2026-09-03T08:00:00Z');
let v=await get();assert.equal(v.devices[0].material,null);assert.equal(v.devices[0].lines.length,2);assert.equal(v.pools[0].quantity,18);
const price=body('price',{batchId:'b1',unitCost:'100',reference:'invoice1'});await post(price);await post(price);await post({...price,unitCost:'999'},409);await post(body('price',{batchId:'b2',unitCost:'300',reference:'invoice2'}));v=await get();assert.equal(v.devices[0].material,'400');assert.equal(v.pools[0].value,'3600');assert.equal(v.pools[0].unitCost,'200');assert.equal(v.devices[0].state,'wip');
await post(body('material',{partCode:'11',unitCost:'180'}));await post(body('standard',{bomId:'bom',minutes:60,laborHourly:'60',overheadHourly:'30'}));v=await get();assert.equal(v.standards[0].total,'270');assert.equal(v.devices[0].materialVariance,'220');await post(body('material',{partCode:'11',childBomId:'bom',revision:1}),400);
await post(body('time',{deviceId:'d',day:'2026-09-02',minutes:60}));await post(body('time',{deviceId:'d',day:'2026-09-02',minutes:60}),409);await post(body('time',{deviceId:'d',day:'2026-09-03',minutes:30}));
await post(body('period',{title:'September',start:'2026-09-01',end:'2026-09-30',laborTotal:'900',fixedOverhead:'1800',variableOverhead:'90',normalMinutes:180,nonproduction:'500',methodConfirmed:false}));v=await get();assert.equal(v.periods[0].preview.complete,false);await post(body('close',{periodId:v.periods[0].id,token:v.token}),400);
await post(body('period',{title:'September',start:'2026-09-01',end:'2026-09-30',laborTotal:'900',fixedOverhead:'1800',variableOverhead:'90',normalMinutes:180,nonproduction:'500',methodConfirmed:true,revision:1}));v=await get();assert.equal(v.periods[0].preview.devices[0].total,'2290');assert.equal(v.periods[0].preview.unabsorbedFixed,'900');assert.equal(v.periods[0].preview.complete,true);
await post(body('period',{title:'overlap',start:'2026-09-15',end:'2026-10-01',laborTotal:'0',fixedOverhead:'0',variableOverhead:'0',normalMinutes:1,nonproduction:'0'}),400);
const close=body('close',{periodId:v.periods[0].id,token:v.token});await post(close);await post(close);v=await get();assert.equal(v.closes.length,1);assert.equal(v.closes[0].stale,false);
await post(body('price',{batchId:'b1',unitCost:'200',reference:'correction',revision:1}));v=await get();assert.equal(v.closes[0].stale,true);assert.equal(v.closes[0].data.report.devices[0].total,'2290');assert.equal(v.devices[0].material,'500');await post(body('close',{periodId:v.periods[0].id,token:close.token}),409);
user={userId:'read',isAdmin:false,permissions:{finance:'read'}};assert.equal((await api.GET()).status,200);await post(body('price',{batchId:'b1',unitCost:'1',reference:'x',revision:2}),403);user.permissions={finance:'none'};assert.equal((await api.GET()).status,403);user.permissions={finance:'write',salesAgentId:'agent'};assert.equal((await api.GET()).status,403);
// Reset semantics preserve standards with catalog, remove actual operational valuation; rollback remains FK safe.
const reset=load('lib/reset-contract.ts');assert.equal(sql.prepare('SELECT COUNT(*) n FROM flow_entities WHERE '+reset.resetWhere('flow_entities','operations')+" AND type='cost_standard'").get().n,0);assert.equal(sql.prepare('SELECT COUNT(*) n FROM flow_entities WHERE '+reset.resetWhere('flow_entities','operations')+" AND type='cost_price'").get().n,2);
sql.exec('BEGIN');for(const t of Object.keys(reset.resetTables))sql.exec('DELETE FROM '+t+' WHERE '+reset.resetWhere(t,'operations'));assert.equal(sql.prepare("SELECT COUNT(*) n FROM flow_entities WHERE type='cost_price'").get().n,0);sql.exec('ROLLBACK');assert.equal(sql.prepare("SELECT COUNT(*) n FROM flow_entities WHERE type='cost_price'").get().n,2);
user={userId:'owner',name:'Owner',isAdmin:true,permissions:{finance:'write'}};sql.exec("UPDATE reset_control SET phase='maintenance'");await post(body('price',{batchId:'b1',unitCost:'201',reference:'x',revision:2}),409);sql.exec("UPDATE reset_control SET phase='testing'");
assert.equal(lib.moneyText(lib.moneyMicro('0.123456')),'0.123456');assert.throws(()=>lib.moneyMicro('-1'));assert.throws(()=>lib.moneyMicro('NaN'));
console.log('PASS costing: weighted average, no transfer/QC double count, rework, missing prices, standard cycle, period allocation, immutable close/staleness, role checks, idempotency, reset predicates');
})().catch(e=>{console.error(e);process.exit(1)});
