const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');const root=path.resolve(__dirname,'..');
function load(file,imports={}){const exports={};const source=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(source,{exports,require:name=>{if(!(name in imports))throw new Error('Missing import '+name);return imports[name]},Response,Request,URL,Error,crypto:globalThis.crypto,Date,Intl,Set,console:{error(){}}});return exports;}
const sql=new DatabaseSync(':memory:');for(const file of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',file),'utf8'));
const db={prepare(query){let args=[];return{bind(...values){args=values;return this},async first(){return sql.prepare(query).get(...args)||null},async all(){return{results:sql.prepare(query).all(...args)}},async run(){return{meta:{changes:sql.prepare(query).run(...args).changes}}}}},async batch(statements){sql.exec('BEGIN');try{const results=[];for(const statement of statements)results.push(await statement.run());sql.exec('COMMIT');return results}catch(e){sql.exec('ROLLBACK');throw e}}};
let identity=null;const env={TRACE_OWNER_EMAIL:'owner@example.com'};
const permissions=load('lib/permissions.ts');for(const preset of Object.values(permissions.presets))permissions.validatePermissions(preset);
const numbers=load('lib/batch-number.ts');const distribution=load('lib/distribution.ts',{'./batch-number':numbers});const model=load('lib/model.ts',{'./batch-number':numbers,'./distribution':distribution});
const auth=load('lib/authorization.ts',{'cloudflare:workers':{env},'@/app/chatgpt-auth':{getChatGPTUser:async()=>identity},'@/lib/storage':{storage:()=>db},'@/lib/permissions':permissions});
const imports={'cloudflare:workers':{env},'@/lib/authorization':auth,'@/lib/storage':{storage:()=>db},'@/lib/permissions':permissions,'@/lib/batch-number':numbers,'@/lib/model':model,'@/lib/distribution':distribution};
const users=load('app/api/users/route.ts',imports),records=load('app/api/records/route.ts',imports),suggestion=load('app/api/batch-suggestion/route.ts',imports);
const request=(method,body,origin='https://test.local')=>new Request('https://test.local/api/records',{method,headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(body)});
const user=(id,email)=>({userId:id,email,displayName:id});
const sales=load('app/api/distribution/route.ts',imports);
(async()=>{
 assert.equal((await sales.GET(new Request('https://test.local/api/distribution?device=x'))).status,401);
 identity=user('owner','owner@example.com');
 const createDevice=code=>records.POST(request('POST',{kind:'device',data:{code,model:'NF5',design:'R1',date:'2026-09-01'}}));
 assert.equal((await createDevice('NF5-001')).status,201);assert.equal((await createDevice('NF5-002')).status,201);
 const first={serial:'nf5-001',dealerCode:'۰۰۱',dealerName:'نماینده نمونه',dealerDate:'2026-09-01'};
 const previewRows=rows=>sales.POST(request('POST',{mode:'preview',rows}));
 let response=await previewRows([{row:2,data:first},{row:3,data:{...first,serial:'UNKNOWN'}},{row:4,data:first}]);assert.equal(response.status,200);let result=await response.json();assert.equal(result.preview[0].status,'new');assert.equal(result.preview[1].status,'unknown');assert.equal(result.preview[2].status,'invalid');assert.equal(sql.prepare("SELECT count(*) n FROM records WHERE kind='distribution'").get().n,0);
 response=await sales.POST(request('POST',{mode:'import',filename:'test.xlsx',rows:[{row:2,data:first}]}));assert.equal(response.status,200);let saved=(await response.json()).results[0].record;assert.equal(saved.data.dealerCode,'001');assert.equal(saved.data.device,'device:NF5-001');assert.ok(!('warrantyStart' in saved.data));
 response=await sales.POST(request('POST',{mode:'import',filename:'test.xlsx',rows:[{row:2,data:first}]}));assert.equal((await response.json()).results[0].status,'same');assert.equal(sql.prepare("SELECT count(*) n FROM records WHERE kind='distribution'").get().n,1);
 const complete={...first,customerName:'مشتری نمونه',customerMobile:'09123456789',customerNationalId:'0000123456',deliveryDate:'2026-09-03'};
 response=await previewRows([{row:2,data:complete}]);assert.equal((await response.json()).preview[0].status,'complete');
 response=await sales.POST(request('POST',{mode:'import',rows:[{row:2,data:complete}]}));saved=(await response.json()).results[0].record;assert.equal(saved.data.customerNationalId,'0000123456');assert.equal(saved.data.dealerCode,'001');
 const change={...complete,dealerName:'نماینده دیگر'};
 response=await previewRows([{row:2,data:change}]);assert.equal((await response.json()).preview[0].status,'conflict');
 response=await sales.POST(request('POST',{mode:'import',rows:[{row:2,data:{...first,serial:'NF5-002'}},{row:3,data:change}]}));assert.equal(response.status,409);assert.equal(sql.prepare("SELECT count(*) n FROM records WHERE kind='distribution'").get().n,1,'Validation rejects batch before any writes');
 response=await sales.POST(request('POST',{mode:'manual',data:change,previous:JSON.stringify(saved.data),reason:''}));assert.equal(response.status,400);
 response=await sales.POST(request('POST',{mode:'manual',data:change,previous:JSON.stringify(saved.data),reason:'اصلاح فاکتور اشتباه'}));assert.equal(response.status,200);
 response=await sales.POST(request('POST',{mode:'manual',data:complete,previous:JSON.stringify(saved.data),reason:'اطلاعات قدیمی'}));assert.equal(response.status,409);
 response=await sales.GET(new Request('https://test.local/api/distribution?device=device%3ANF5-001'));let history=(await response.json()).history;assert.equal(history.length,3);assert.ok(history.some(h=>h.before?.dealerName==='نماینده نمونه'&&h.after.dealerName==='نماینده دیگر'));
 response=await previewRows([{row:2,data:{...first,serial:12345}},{row:3,data:{...first,deliveryDate:'2026-02-30',customerName:'x'}},{row:4,data:{...first,customerMobile:'9123456789',customerName:'x'}}]);assert.ok((await response.json()).preview.every(r=>r.status==='invalid'));
 assert.equal((await records.POST(request('POST',{kind:'distribution',data:first}))).status,400,'Generic endpoint cannot bypass import checks');
 response=await users.POST(request('POST',{email:'stock@example.com',name:'Stock',unit:'انبار',status:'active',permissions:permissions.presets['انبار']}));assert.equal(response.status,201);
 identity=user('stock','stock@example.com');assert.equal((await sales.POST(request('POST',{mode:'preview',rows:[]}))).status,403);assert.equal((await sales.GET(new Request('https://test.local/api/distribution?device=device%3ANF5-001'))).status,403);assert.ok(!(await (await records.GET()).json()).records.some(r=>r.kind==='distribution'));
 console.log('Distribution checks passed: preview/no mutation, unknown/duplicate serials, normalized identifiers, idempotent import, blank-field completion, conflicts, no partial writes on validation failure, reasoned updates, concurrency, history, date/phone errors and permission isolation.');
})().catch(e=>{console.error(e);process.exitCode=1});
