const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');const root=path.resolve(__dirname,'..');const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',f),'utf8'));
const db={prepare(q){let args=[];return{bind(...a){args=a;return this},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:{changes:sql.prepare(q).run(...args).changes}}}}},async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const objects=new Map();const bucket={async put(k,b){objects.set(k,b.slice(0));return {key:k}},async get(k){const b=objects.get(k);return b?{body:b,arrayBuffer:async()=>b.slice(0)}:null},async delete(k){objects.delete(k)}};
let modelReply={sourceIds:[],unanswered:true},modelCalls=[];let identity=null;const env={TRACE_OWNER_EMAIL:'owner@example.com',LLM_CONFIG_ENCRYPTION_KEY:require('node:crypto').randomBytes(32).toString('base64'),DB:db,BUCKET:bucket};
const cache={};function load(file){file=path.resolve(root,file);if(cache[file])return cache[file];const exports={};cache[file]=exports;const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
vm.runInNewContext(source,{exports,require:n=>{if(n==='cloudflare:workers')return {env};if(n==='@/app/chatgpt-auth')return {getChatGPTUser:async()=>identity};if(n.startsWith('@/')||n.startsWith('.')){const p=n.startsWith('@/')?path.join(root,n.slice(2)):path.resolve(path.dirname(file),n);return load(p+(path.extname(p)?'':'.ts'));}return require(n)},fetch:async(url,options)=>{modelCalls.push(JSON.parse(options.body));return Response.json({choices:[{message:{content:JSON.stringify(modelReply)}}]})},Response,Request,Headers,URL,URLSearchParams,Error,crypto:globalThis.crypto,Date,Intl,Set,Map,FormData,Blob,File,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,AbortController,ReadableStream,btoa,atob,setTimeout:(f,n)=>setTimeout(f,Math.min(n,10)),clearTimeout,console},{filename:file});return exports;}

const context=load('lib/mcp/context.ts').mcpActor, training=load('lib/training.ts'), roles=load('lib/training-contract.ts').trainingRoles;
const real={userId:'real-tester',email:'tester@example.com',name:'Tester',isAdmin:false,permissions:{read:[],write:[],eventStages:[]}};
const base='https://test.local';
const request=(path,body)=>new Request(base+path,{method:body?'POST':'GET',headers:{origin:base,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
async function call(name,path,body){const role=roles.find(r=>r.name===name);const r=await context.run(real,()=>training.trainingDispatch(request('/api/training/'+path+(path.includes('?')?'&':'?')+'_role='+role.id,body)));let d;try{d=await r.json()}catch{d={}};return {status:r.status,d};}

(async()=>{
 const init=await context.run(real,()=>training.trainingInitialize(request('/api/training',{confirmed:true})));assert.equal(init.status,200,await init.text());
 const center='مسئول مرکز بیمارستانی ۱',other='مسئول مرکز بیمارستانی ۲',manager='هماهنگ‌کننده خدمات',tech='تکنسین خدمات',finance='مالی خدمات';
 const entity=id=>{const r=sql.prepare('SELECT * FROM training_flow_entities WHERE id=?').get(id);return {...r,data:JSON.parse(r.data)}};
 const act=async(role,mode,fields={},expected=200)=>{const b={id:crypto.randomUUID(),mode,confirmed:true,...fields};const r=await call(role,'hospital',b);assert.equal(r.status,expected,mode+' '+JSON.stringify(r.d));return {id:b.id,...r.d,body:b}};
 const view=await call(center,'hospital');assert.equal(view.status,200);assert.equal(view.d.centers.length,1);assert.equal(view.d.centers[0].id,'training-hospital-1');assert.ok(view.d.rows.every(r=>r.data.centerId==='training-hospital-1'));
 assert.equal((await call(center,'hospital?center=training-hospital-2')).status,404);
 for(const p of ['records','inbox','tasks','sales','flow'])assert.equal((await call(center,p)).status,403,p);
 await act(center,'request',{assetId:'training-hospital-asset-2',kind:'fault',urgency:'normal',description:'test',contact:'test'},404);
 const j=await act(center,'request',{assetId:'training-hospital-asset-1',kind:'fault',urgency:'normal',description:'خرابی آزمایشی',contact:'مرکز فرضی'});
 assert.ok(sql.prepare("SELECT id FROM training_duty_runs WHERE template_id LIKE ? AND state='open'").get('hospital:'+j.id+':%'));
 assert.equal((await call(center,'hospital',j.body)).status,200);assert.equal(entity(j.id).revision,1);
 await act(manager,'dispatch',{jobId:j.id,revision:1,notes:'test'},400);
 const quote=async()=>act(manager,'quote',{jobId:j.id,revision:entity(j.id).revision,lines:[{kind:'labor',label:'بازدید فرضی',quantity:2,unitPrice:'500',partCode:''}],validUntil:load('lib/duties.ts').dayAt(),notes:'برآورد'});
 await quote();await act(manager,'consent',{jobId:j.id,revision:entity(j.id).revision,quoteVersion:1,approved:true,notes:'test'},403);
 await act(other,'consent',{jobId:j.id,revision:entity(j.id).revision,quoteVersion:1,approved:true,notes:'test'},404);
 await act(center,'consent',{jobId:j.id,revision:entity(j.id).revision,quoteVersion:0,approved:true,notes:'test'},409);
 const approve=()=>act(center,'consent',{jobId:j.id,revision:entity(j.id).revision,quoteVersion:entity(j.id).data.quoteVersion,approved:true,notes:'تأیید تست'});
 await approve();await quote();assert.equal(entity(j.id).data.consent,null);
 const technicianId=roles.find(r=>r.name===tech).memberId;
 await act(manager,'schedule',{jobId:j.id,revision:entity(j.id).revision,technicianId,day:load('lib/duties.ts').dayAt(),notes:'test'},400);
 await approve();await act(manager,'schedule',{jobId:j.id,revision:entity(j.id).revision,technicianId,day:load('lib/duties.ts').dayAt(),notes:'اعزام آزمایشی'});
 await act(tech,'dispatch',{jobId:j.id,revision:entity(j.id).revision,notes:'اعزام فرضی'});
 await act(tech,'complete',{jobId:j.id,revision:entity(j.id).revision,work:'خدمات فرضی',parts:'بدون قطعه',test:'آزمون نرم‌افزار'});
 await act(center,'confirm',{jobId:j.id,revision:entity(j.id).revision,approved:false,rating:2,notes:'نیازمند پیگیری'});
 const dispute=sql.prepare("SELECT id FROM training_duty_runs WHERE template_id=?").get('hospital:'+j.id+':disputed');assert.ok(dispute);
 await act(center,'confirm',{jobId:j.id,revision:entity(j.id).revision,approved:true,rating:5,notes:'بررسی شد'});
 assert.equal(sql.prepare('SELECT state FROM training_duty_runs WHERE id=?').get(dispute.id).state,'completed');
 const inv=await act(finance,'invoice',{jobId:j.id,revision:entity(j.id).revision,reference:'TEST-INV-1',due:load('lib/duties.ts').dayAt()});assert.equal(entity(inv.id).data.amount,'1000');
 await act(manager,'quote',{jobId:j.id,revision:entity(j.id).revision},400);
 const tc=load('lib/training-context.ts'),fileApi=load('app/api/hospital/files/route.ts');
 const asRole=(role,fn)=>tc.trainingContext.run({actor:'test',role:'test'},()=>context.run(roles.find(r=>r.name===role).session,fn));
 const fileId=crypto.randomUUID(),fileReq=new Request(base+'/api/hospital/files?'+new URLSearchParams({id:fileId,center:'training-hospital-1',purpose:'payment',filename:'receipt.pdf'}),{method:'POST',headers:{origin:base,'Content-Type':'application/pdf'},body:'%PDF-1.4\nTEST'});
 const uploaded=await asRole(center,()=>fileApi.POST(fileReq));assert.equal(uploaded.status,200,await uploaded.text());
 assert.equal((await asRole(other,()=>fileApi.GET(request('/api/hospital/files?id='+fileId)))).status,404);
 assert.equal((await asRole(center,()=>fileApi.GET(request('/api/hospital/files?id='+fileId)))).status,200);
 const payment=await act(center,'payment',{invoiceId:inv.id,fileId,amount:'600',day:load('lib/duties.ts').dayAt(),reference:'PAY-1',notes:'تست'});
 let balance=(await call(center,'hospital')).d.balances[0];assert.equal(balance.balance,'1000');
 await act(center,'payment_review',{paymentId:payment.id,revision:1,approved:true,notes:'test'},403);
 await act(finance,'payment_review',{paymentId:payment.id,revision:1,approved:true,notes:'رسید بررسی شد'});
 balance=(await call(center,'hospital')).d.balances[0];assert.equal(balance.balance,'400');assert.equal(balance.invoices[0].remaining,'400');
 await act(center,'payment',{invoiceId:inv.id,fileId,amount:'600',day:load('lib/duties.ts').dayAt(),reference:'PAY-1',notes:'تکراری'},409);
 const check=await act(center,'form_submit',{formId:'training-hospital-form-1',revision:1,values:{label:'fail'},notes:'آزمایشی'});assert.equal(entity(check.id).data.failed,true);
 await act(manager,'check_review',{checkId:check.id,revision:1,notes:'پیگیری شد'});assert.ok(entity(check.id).data.review);
 const d=await act(manager,'manual',{assetId:'training-hospital-asset-1',previousId:'training-hospital-manual-1',revision:1,state:'draft',title:'پیش‌نویس',reference:'TEST',body:'متن پیش نویس'});
 assert.equal(entity('training-hospital-manual-1').data.state,'published');assert.ok(!(await call(center,'hospital')).d.rows.some(r=>r.id===d.id));
 await act(manager,'manual',{assetId:'training-hospital-asset-1',previousId:d.id,revision:1,state:'published',title:'راهنما ۲',reference:'TEST-2',body:'فقط آموزش نرم افزار'});
 assert.equal(entity('training-hospital-manual-1').data.state,'superseded');
 const ai=await call(center,'hospital/assistant',{id:crypto.randomUUID(),assetId:'training-hospital-asset-1',question:'راهنما؟',confirmed:true});assert.equal(ai.status,409,JSON.stringify(ai.d));
 assert.equal((await call(center,'hospital/assistant',{id:crypto.randomUUID(),assetId:'training-hospital-asset-2',question:'راهنما؟',confirmed:true})).status,404);

 const configs=load('app/api/llm-config/route.ts'),profileId=crypto.randomUUID();const admin=roles.find(r=>r.session.isAdmin);assert.ok(admin);
 const cfg=await asRole(admin.name,()=>configs.PUT(new Request(base+'/api/llm-config',{method:'PUT',headers:{origin:base,'Content-Type':'application/json'},body:JSON.stringify({id:profileId,revision:0,name:'Test',model:'test',baseUrl:'https://test.invalid/v1',systemPrompt:'',temperature:0.2,maxTokens:1000,apiToken:'test-secret'})})));assert.equal(cfg.status,201,await cfg.text());
 await act(manager,'center',{centerId:'training-hospital-1',revision:1,name:'مرکز فرضی',phone:'TEST',address:'TEST',active:true,profileId});
 const published=(await call(center,'hospital')).d.rows.find(r=>r.type==='hospital_manual');modelReply={sourceIds:[published.id+':0','invented'],unanswered:false};
 let answer=await call(center,'hospital/assistant',{id:crypto.randomUUID(),assetId:'training-hospital-asset-1',question:'راهنمای پنل؟',confirmed:true});assert.equal(answer.status,200,JSON.stringify(answer.d));assert.equal(answer.d.answer,published.data.body);assert.equal(answer.d.sources.length,1);
 assert.ok(!JSON.stringify(modelCalls).includes('test-secret'));assert.ok(!JSON.stringify(modelCalls).includes('training-hospital-2'));
 modelReply={sourceIds:['invented'],unanswered:false};answer=await call(center,'hospital/assistant',{id:crypto.randomUUID(),assetId:'training-hospital-asset-1',question:'پاسخ نامستند؟',confirmed:true});assert.equal(answer.status,200);assert.equal(answer.d.sources.length,0);assert.ok(answer.d.answer.includes('پاسخ صریحی'));
 const catalog=load('lib/mcp/tools.ts'),principal={user:roles.find(r=>r.name===center).session,scope:'read_write',tokenId:null};
 await assert.rejects(()=>catalog.executeTool('list_records',{},base,principal),/Hospital portal/);
 const mcp=await tc.trainingContext.run({actor:'test',role:'test'},()=>catalog.executeTool('hospital_get_workspace',{},base,principal));assert.equal(mcp.centers.length,1);
 await assert.rejects(()=>catalog.executeTool('hospital_apply',{body:'{}',confirmed:true},base,{...principal,scope:'read'}),/read-only/);
 const accounts=load('app/api/hospital/accounts/route.ts');const body={id:crypto.randomUUID(),centerId:'training-hospital-1',revision:2,name:'مرکز تست',username:'hospital-test',password:'HospitalTest!1234',confirmed:true};
 const ar=await asRole(manager,()=>accounts.POST(request('/api/hospital/accounts',body)));assert.equal(ar.status,201,await ar.clone().text());assert.ok(!(await ar.text()).includes(body.password));
 const member=sql.prepare("SELECT permissions FROM training_app_members WHERE id=?").get(body.id);assert.equal(JSON.parse(member.permissions).hospitalCenterId,'training-hospital-1');
 assert.ok(!JSON.stringify(sql.prepare('SELECT * FROM training_access_audit').all()).includes(body.password));
 assert.equal(sql.prepare('PRAGMA foreign_key_check').all().length,0);
 for(const t of ['records','flow_entities','app_members','inventory_balances','duty_runs','access_audit'])assert.equal(sql.prepare('SELECT count(*) n FROM '+t).get().n,0,t);
 console.log('Hospital center isolation, quote approval/dispatch, service confirmation, finance balances, private files, versioned forms/manuals, credentials, notifications and idempotency PASS');
})().catch(e=>{console.error(e);process.exitCode=1});
