const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');const root=path.resolve(__dirname,'..');const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',f),'utf8'));
const db={prepare(q){let args=[];return{bind(...a){args=a;return this},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:{changes:sql.prepare(q).run(...args).changes}}}}},async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const objects=new Map();const bucket={async put(k,b){objects.set(k,b.slice(0));return {key:k}},async get(k){const b=objects.get(k);return b?{body:b,arrayBuffer:async()=>b.slice(0)}:null},async delete(k){objects.delete(k)}};
let modelReply={sourceIds:[],unanswered:true},modelCalls=[];let identity=null;const env={TRACE_OWNER_EMAIL:'owner@example.com',LLM_CONFIG_ENCRYPTION_KEY:require('node:crypto').randomBytes(32).toString('base64'),DB:db,BUCKET:bucket};
const cache={};function load(file){file=path.resolve(root,file);if(cache[file])return cache[file];const exports={};cache[file]=exports;const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
vm.runInNewContext(source,{exports,require:n=>{if(n==='cloudflare:workers')return {env};if(n==='@/app/chatgpt-auth')return {getChatGPTUser:async()=>identity};if(n.startsWith('@/')||n.startsWith('.')){const p=n.startsWith('@/')?path.join(root,n.slice(2)):path.resolve(path.dirname(file),n);return load(p+(path.extname(p)?'':'.ts'));}return require(n)},fetch:async(url,options)=>{modelCalls.push(JSON.parse(options.body));return Response.json({choices:[{message:{content:JSON.stringify(modelReply)}}]})},Response,Request,Headers,URL,URLSearchParams,Error,crypto:globalThis.crypto,Date,Intl,Set,Map,FormData,Blob,File,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,AbortController,ReadableStream,btoa,atob,setTimeout:(f,n)=>setTimeout(f,Math.min(n,10)),clearTimeout,console},{filename:file});return exports;}

const context=load('lib/mcp/context.ts').mcpActor, training=load('lib/training.ts'), roles=load('lib/training-contract.ts').trainingRoles;
const real={userId:'real-tester',email:'tester@example.com',name:'Tester',isAdmin:false,permissions:{read:[],write:[],eventStages:[]}};
const base='https://test.local';
const request=(path,body)=>new Request(base+path,{method:body?'POST':'GET',headers:{origin:base,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
async function call(name,path,body){const role=roles.find(r=>r.name===name);const r=await context.run(real,()=>training.trainingDispatch(request('/api/training/'+path+(path.includes('?')?'&':'?')+'_role='+role.id,body)));let d;try{d=await r.json()}catch{d={}};return {status:r.status,d};}

(async()=>{
 await context.run(real,()=>training.trainingInitialize(request('/api/training',{confirmed:true})));
 const specialist=roles.find(r=>r.name==='تکنسین فنی بیمارستانی');assert.deepEqual(Array.from(specialist.session.permissions.serviceDomains),['hospital']);assert.deepEqual(Array.from(specialist.session.permissions.serviceRoles),['technician']);
 const before=sql.prepare('SELECT count(*) n FROM training_flow_entities').get().n;
 await context.run(real,()=>training.trainingInitialize(request('/api/training',{confirmed:true})));
 assert.equal(sql.prepare('SELECT count(*) n FROM training_flow_entities').get().n,before);
 const specialistView=await call('تکنسین فنی بیمارستانی','hospital');assert.equal(specialistView.status,200);assert.equal(specialistView.d.memberId,specialist.memberId);assert.ok(specialistView.d.rows.some(r=>r.id==='training-technician-job'&&r.data.technicianId===specialist.memberId));
 assert.equal((await call('تکنسین فنی خانگی','hospital')).status,403);
 const specialistExpense=await call('تکنسین فنی بیمارستانی','hospital/expenses');assert.equal(specialistExpense.status,200);assert.ok(specialistExpense.d.policies.some(p=>p.data.assignments.some(a=>a.ownerId===specialist.memberId)));
 const tech='تکنسین خدمات',manager='هماهنگ‌کننده خدمات',center='مسئول مرکز بیمارستانی ۱',finance='مالی خدمات',aid='training-hospital-asset-1',job='field-test-job',today=load('lib/duties.ts').dayAt();
 const entity=id=>{const r=sql.prepare('SELECT * FROM training_flow_entities WHERE id=?').get(id);return {...r,data:JSON.parse(r.data)}};
 const act=async(role,mode,fields={},expected=200)=>{const b={id:crypto.randomUUID(),mode,confirmed:true,...fields},r=await call(role,'hospital',b);assert.equal(r.status,expected,JSON.stringify(r));return {id:b.id,...r.d};};
 sql.prepare("INSERT INTO training_flow_entities VALUES(?,'hospital_job',?,1,?,?)").run(job,JSON.stringify({centerId:'training-hospital-1',assetId:aid,serial:'TEST',technicianId:roles.find(r=>r.name===tech).memberId,state:'dispatched',dispatch:{at:new Date().toISOString()}}),today,today);
 const fields=[{key:'visual',label:'Visual test only',type:'result',unit:'',min:'',max:'',required:true}];
 const form=await act(manager,'form',{assetId:aid,title:'Field test',reference:'Training',state:'published',audience:'technician',fields});
 assert.ok(!(await call(center,'hospital')).d.rows.some(r=>r.id===form.id));
 await act(center,'form_submit',{formId:form.id,revision:1,values:{visual:'pass'}},400);
 await act(finance,'part_request',{jobId:job,partName:'Test',quantity:'1',notes:'Test'},403);
 const part=await act(tech,'part_request',{jobId:job,partName:'Test component',quantity:'1',notes:'Fault at visit'});
 assert.ok(sql.prepare("SELECT id FROM training_duty_runs WHERE state='open' AND template_id LIKE ?").get('hospital:'+part.id+':%'));
 await act(manager,'part_review',{requestId:part.id,revision:1,approved:true,partCode:'1001',notes:'Approve mapped component'});
 assert.equal(entity(part.id).data.state,'approved');
 const balance=(batch,wh)=>sql.prepare('SELECT quantity FROM training_inventory_balances WHERE item_id=? AND warehouse=?').get(batch,wh)?.quantity||0;
 const qtyBefore=balance('training-batch-1','raw'),slotsBefore=sql.prepare("SELECT quantity FROM training_flow_slots WHERE batch_id='training-batch-1'").get().quantity;
 const issue={requestId:part.id,revision:2,allocations:[{batchId:'training-batch-1',location:'A-1-1-1',quantity:'1'}],notes:'Actual warehouse issue'};
 const taskFor=(name,state)=>sql.prepare("SELECT * FROM training_duty_runs WHERE assignee=? AND template_id=? AND state='open'").get(roles.find(r=>r.name===name).memberId,'hospital:'+part.id+':'+state);
 assert.ok(taskFor('انبار خدمات','approved'));
 const taskAccess=load('lib/duties.ts').dutyVisible;assert.ok(taskAccess(roles.find(r=>r.name==='انبار خدمات').session,{hospitalWorkflow:true,workflowRole:'inventory'}));
 await act(tech,'part_issue',issue,403);
 await act(manager,'part_ship',{requestId:part.id,revision:2,carrier:'Test',tracking:'Test',notes:'Premature'},403);
 await act('ارسال خدمات','part_ship',{requestId:part.id,revision:2,carrier:'Test',tracking:'Test',notes:'Premature'},400);
 await act('انبار خدمات','part_issue',{...issue,revision:1},409);
 await act('انبار خدمات','part_issue',{...issue,allocations:[{batchId:'training-batch-2',location:'A-2-1-1',quantity:1}]},400);
 await act('انبار خدمات','part_issue',{...issue,allocations:[{batchId:'training-batch-9',location:'',quantity:1}]},400);
 await act('انبار خدمات','part_issue',{...issue,allocations:[{batchId:'training-batch-1',location:'WRONG',quantity:1}]},409);
 await act('انبار خدمات','part_issue',{...issue,allocations:[{batchId:'training-batch-1',location:'A-1-1-1',quantity:2}]},400);
 // Protect stock allocated to sourcing, with all ledger/slot writes rolled back.
 sql.prepare("INSERT INTO training_flow_entities VALUES('hospital-test-plan','sourcing_plan','{}',1,?,?)").run(today,today);
 sql.prepare("INSERT INTO training_sourcing_holds VALUES('hospital-test-hold','hospital-test-plan','1001','عدد','stock','training-batch-1',100000)").run();
 await act('انبار خدمات','part_issue',issue,409);
 assert.equal(balance('training-batch-1','raw'),qtyBefore);assert.equal(entity(part.id).revision,2);
 assert.equal(sql.prepare("SELECT quantity FROM training_flow_slots WHERE batch_id='training-batch-1'").get().quantity,slotsBefore);
 sql.prepare("DELETE FROM training_sourcing_holds WHERE id='hospital-test-hold'").run();
 sql.prepare("UPDATE training_inventory_balances SET quantity=0 WHERE item_id='training-batch-1' AND warehouse='raw'").run();
 await act('انبار خدمات','part_issue',issue,409);assert.equal(entity(part.id).revision,2);assert.equal(balance('training-batch-1','hospital:staged:'+part.id),0);
 sql.prepare("UPDATE training_inventory_balances SET quantity=? WHERE item_id='training-batch-1' AND warehouse='raw'").run(qtyBefore);
 const receiptBefore=entity('training-batch-1');sql.prepare("UPDATE training_flow_entities SET data=? WHERE id='training-batch-1'").run(JSON.stringify({...receiptBefore.data,expiry:'2000-01-01'}));
 await act('انبار خدمات','part_issue',issue,400);sql.prepare("UPDATE training_flow_entities SET data=? WHERE id='training-batch-1'").run(JSON.stringify(receiptBefore.data));
 const issued=await act('انبار خدمات','part_issue',issue);
 assert.equal(entity(part.id).data.state,'issued');assert.ok(!taskFor('انبار خدمات','approved'));assert.ok(taskFor('ارسال خدمات','issued'));
 assert.equal(balance('training-batch-1','raw'),qtyBefore-1000);assert.equal(balance('training-batch-1','hospital:staged:'+part.id),1000);
 const retry=await call('انبار خدمات','hospital',{id:issued.id,mode:'part_issue',confirmed:true,...issue});assert.equal(retry.status,200);assert.equal(retry.d.repeated,true);
 assert.equal(balance('training-batch-1','raw'),qtyBefore-1000);
 await act('انبار خدمات','part_issue',{...issue,revision:3},400);
 await act(tech,'part_receive',{requestId:part.id,revision:3,confirmedReceived:true,notes:'Premature'},400);
 await act('ارسال خدمات','part_ship',{requestId:part.id,revision:3,carrier:'Training carrier',tracking:'TEST-SHIP-1',notes:'Actually dispatched'});
 assert.equal(balance('training-batch-1','hospital:staged:'+part.id),0);assert.equal(balance('training-batch-1','hospital:transit:'+part.id),1000);
 assert.ok(taskFor(tech,'shipped'));assert.ok(!taskFor('ارسال خدمات','issued'));
 await act('تکنسین فنی بیمارستانی','part_receive',{requestId:part.id,revision:4,confirmedReceived:true,notes:'Not my delivery'},403);
 await act(manager,'part_receive',{requestId:part.id,revision:4,confirmedReceived:true,notes:'Manager cannot impersonate'},403);
 await act(tech,'part_receive',{requestId:part.id,revision:4,confirmedReceived:false,notes:'Missing item'},400);
 const received=await act(tech,'part_receive',{requestId:part.id,revision:4,confirmedReceived:true,notes:'All items received'});
 assert.equal(entity(part.id).data.state,'received');assert.ok(!taskFor(tech,'shipped'));
 assert.equal(balance('training-batch-1','hospital:transit:'+part.id),0);assert.equal(balance('training-batch-1','hospital:technician:'+roles.find(r=>r.name===tech).memberId),1000);
 await act(tech,'part_receive',{requestId:part.id,revision:5,confirmedReceived:true,notes:'Second receipt'},400);
 assert.equal(sql.prepare('SELECT count(*) n FROM inventory_entries').get().n,0,'Company inventory must remain untouched');
 console.log('Hospital parts: role chain, mapped material, QC, locations, stock holds, atomic rollback, replay safety, task completion and technician custody passed');

 assert.ok(!(await call(center,'hospital')).d.rows.some(r=>r.id===part.id));
 const file=crypto.randomUUID(),role=roles.find(r=>r.name===tech);const upload=new Request(base+'/api/training/hospital/files?_role='+role.id+'&id='+file+'&center=training-hospital-1&asset='+aid+'&job='+job+'&purpose=report&filename=minutes.pdf',{method:'POST',headers:{origin:base,'Content-Type':'application/pdf'},body:'%PDF-training minutes'});
 const ur=await context.run(real,()=>training.trainingDispatch(upload));assert.equal(ur.status,200,await ur.text());
 assert.equal((await call(center,'hospital/files?id='+file)).status,403);
 const complete={jobId:job,revision:entity(job).revision,work:'Actual test work',test:'Measured result',fileIds:[file],formId:form.id};
 await act(tech,'complete',{...complete,values:{}},409);
 await act(tech,'complete',{...complete,values:{visual:'pass'}});
 assert.equal(entity(job).data.state,'completed');assert.equal(entity(job).data.report.checklist.version,1);assert.equal(entity(job).data.report.fileIds[0],file);
 assert.equal((await call(center,'hospital/files?id='+file)).status,200);assert.equal((await call('مسئول مرکز بیمارستانی ۲','hospital/files?id='+file)).status,404);
 assert.equal(entity(job).data.confirmation,undefined);
 console.log('Field technician: job evidence, signed minutes separation, device checklist, part request workflow and center privacy passed');
})().catch(e=>{console.error(e);process.exitCode=1});
