const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');const root=path.resolve(__dirname,'..');const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',f),'utf8'));
const db={prepare(q){let args=[];return{bind(...a){args=a;return this},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:{changes:sql.prepare(q).run(...args).changes}}}}},async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const objects=new Map();const bucket={async put(k,b){objects.set(k,b.slice(0));return {key:k}},async get(k){const b=objects.get(k);return b?{arrayBuffer:async()=>b.slice(0)}:null},async delete(k){objects.delete(k)}};
let identity=null;const env={TRACE_OWNER_EMAIL:'owner@example.com',LLM_CONFIG_ENCRYPTION_KEY:require('node:crypto').randomBytes(32).toString('base64'),DB:db,BUCKET:bucket};
const cache={};function load(file){file=path.resolve(root,file);if(cache[file])return cache[file];const exports={};cache[file]=exports;const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
vm.runInNewContext(source,{exports,require:n=>{if(n==='cloudflare:workers')return {env};if(n==='@/app/chatgpt-auth')return {getChatGPTUser:async()=>identity};if(n.startsWith('@/')||n.startsWith('.')){const p=n.startsWith('@/')?path.join(root,n.slice(2)):path.resolve(path.dirname(file),n);return load(p+(path.extname(p)?'':'.ts'));}return require(n)},structuredClone,Response,Request,URL,URLSearchParams,Error,crypto:globalThis.crypto,Date,Intl,Set,Map,FormData,Blob,File,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,AbortController,ReadableStream,btoa,atob,setTimeout:(f,n)=>setTimeout(f,Math.min(n,10)),clearTimeout,console},{filename:file});return exports;}

const printApi=load('app/api/personnel/print/route.ts');
const ctx=load('lib/mcp/context.ts').mcpActor,api=load('app/api/personnel/route.ts'),files=load('app/api/personnel/files/route.ts'),domain=load('lib/personnel.ts'),catalog=load('lib/mcp/tools.ts'),tasks=load('app/api/tasks/route.ts'),duties=load('lib/duties.ts');
let tail=Promise.resolve();const batch=db.batch.bind(db);db.batch=stmts=>{const next=tail.then(()=>batch(stmts));tail=next.catch(()=>{});return next};
const base='https://test.local',now=new Date().toISOString(),today=duties.dayAt(),day=duties.addDay(today,-10),next=duties.addDay(today,2);
const req=(url,b,origin=base)=>new Request(base+url,{method:b?'POST':'GET',headers:{origin,'Content-Type':'application/json'},...(b?{body:JSON.stringify(b)}:{})});
function actor(id,roles=[],extra={}){const u={userId:'local:'+id,email:id+'@test.local',name:id,isAdmin:false,permissions:{read:[],write:[],eventStages:[],personnelRoles:roles,...extra}};sql.prepare("INSERT INTO app_members(id,email,name,unit,status,subject,permissions,created,updated) VALUES(?,?,?,'company','active',?,?,?,?)").run(id,u.email,id,u.userId,JSON.stringify(u.permissions),now,now);return u;}
const alice=actor('alice'),bob=actor('bob'),manager=actor('manager'),hr=actor('hr',['hr']),payroll=actor('payroll',['payroll']),approver=actor('approver',['approver']),finance=actor('finance',['finance']),treasury=actor('treasury',['treasury']),external=actor('external',[],{salesAgentId:'outside',salesRoles:['agent']});
const row=id=>{const r=sql.prepare('SELECT * FROM flow_entities WHERE id=?').get(id);return r?{...r,data:JSON.parse(r.data)}:null};
async function get(u,q=''){const r=await ctx.run(u,()=>api.GET(req('/api/personnel'+q)));return {status:r.status,data:await r.json()}}
async function post(u,b){const r=await ctx.run(u,()=>api.POST(req('/api/personnel',{id:crypto.randomUUID(),confirmed:true,revision:0,notes:'Actual evidence',...b})));return {status:r.status,data:await r.json()}}
async function ok(u,b){const r=await post(u,b);assert.equal(r.status,200,JSON.stringify({b,r}));return r.data.id;}
const apply=(u,id,mode,extra={})=>post(u,{recordId:id,revision:row(id).revision,mode,...extra});
const success=async(u,id,mode,extra={})=>{const r=await apply(u,id,mode,extra);assert.equal(r.status,200,JSON.stringify({mode,r}));return r};
const seed=(id,type,data)=>sql.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').run(id,type,JSON.stringify(data),now,now);
const profile={mode:'employee',code:'A01',memberId:'alice',managerId:'manager',start:day,end:'',title:'Engineer',unit:'Production',location:'Factory',employment:'Full time',leaveMinutes:960,bankAccount:'PRIVATE-BANK',personal:'PRIVATE-PERSONAL'};
(async()=>{
 assert.equal((await get(external)).status,403);assert.equal((await post(alice,profile)).status,403);
 const eid=await ok(hr,profile);await ok(hr,{...profile,memberId:'bob',code:'B01'});
 assert.equal((await post(hr,{...profile,code:'A02'})).status,409);
 const managerView=(await get(manager)).data;assert.ok(!JSON.stringify(managerView).includes('PRIVATE-BANK'));assert.ok(!JSON.stringify(managerView).includes('PRIVATE-PERSONAL'));assert.equal((await get(bob)).data.records.filter(r=>r.type==='hr_employee').length,1);
 const sid=await ok(hr,{mode:'shift',title:'Day shift',startTime:'08:00',endTime:'16:00',weekdays:[0,1,2,3,4,5,6],holidays:[],breakMinutes:0});
 for(const mid of ['alice','bob'])await ok(hr,{mode:'assignment',memberId:mid,start:day,end:duties.addDay(today,30),shiftId:sid});
 const leave={mode:'request',kind:'leave',memberId:'alice',leaveType:'annual',start:next,end:next};const lid=await ok(alice,leave);
 assert.equal((await apply(alice,lid,'approve')).status,403);assert.equal((await post(bob,{...leave,start:today,end:today})).status,403);
 assert.equal((await get(alice)).data.balances[0].availableMinutes,480);assert.equal((await post(alice,leave)).status,400);
 const task=sql.prepare("SELECT * FROM duty_runs WHERE template_id='personnel' AND period=? AND assignee='manager'").get(lid);assert.ok(task);
 const generic=await ctx.run(manager,()=>tasks.POST(req('/api/tasks',{id:crypto.randomUUID(),confirmed:true,mode:'submit',taskId:task.id,revision:task.revision,note:'Shortcut'})));assert.equal(generic.status,400);
 await success(manager,lid,'approve');await success(hr,lid,'approve');assert.equal(row(lid).data.state,'approved');
 const cancel=await ok(alice,{mode:'request',kind:'cancel',targetId:lid});await success(manager,cancel,'approve');await success(hr,cancel,'approve');assert.equal(row(lid).data.state,'cancelled');assert.equal((await get(alice)).data.balances[0].availableMinutes,960);
 // Role revocation changes both access and task ownership immediately.
 const second=await ok(alice,{...leave,start:today,end:today});await success(manager,second,'approve');const oldPermissions=JSON.stringify(hr.permissions);sql.prepare('UPDATE app_members SET permissions=? WHERE id=?').run(JSON.stringify({read:[],write:[],eventStages:[]}), 'hr');assert.equal((await apply(hr,second,'approve')).status,404);sql.prepare('UPDATE app_members SET permissions=? WHERE id=?').run(oldPermissions,'hr');await success(hr,second,'reject');
 // Evidence inherits the parent's current permissions and remains immutable.
 const doc=await ok(hr,{mode:'document',memberId:'alice',title:'Employment certificate',text:'PRIVATE-DOCUMENT',effective:day});const fid=crypto.randomUUID(),uploadReq=()=>new Request(base+'/api/personnel/files?'+new URLSearchParams({id:fid,caseId:doc,filename:'certificate.pdf',confirmed:'true'}),{method:'POST',headers:{origin:base},body:new TextEncoder().encode('%PDF-1.4 actual')});
 const upload=await ctx.run(hr,()=>files.POST(uploadReq()));assert.equal(upload.status,200,await upload.text());assert.equal((await ctx.run(alice,()=>files.GET(req('/api/personnel/files?id='+fid)))).status,404);
 await success(hr,doc,'submit');assert.equal((await apply(hr,doc,'publish')).status,403);await success(approver,doc,'publish');assert.equal((await ctx.run(alice,()=>files.GET(req('/api/personnel/files?id='+fid)))).status,200);assert.equal((await ctx.run(manager,()=>files.GET(req('/api/personnel/files?id='+fid)))).status,404);await success(alice,doc,'acknowledge');
 // No duplicate concurrent request can reserve the same remaining leave.
 const race=await Promise.all([post(alice,{...leave,start:next,end:duties.addDay(next,1)}),post(alice,{...leave,start:next,end:duties.addDay(next,1)})]);assert.equal(race.filter(r=>r.status===200).length,1);const raceId=race.find(r=>r.status===200).data.id;await success(alice,raceId,'withdraw');
 // Old raw attendance is never edited: approved correction supplies a separately audited effective interval.
 const correction=await ok(alice,{mode:'request',kind:'correction',start:day,end:day,inAt:day+'T08:00:00+03:30',outAt:day+'T16:00:00+03:30'});await success(manager,correction,'approve');await success(hr,correction,'approve');
 const work=(await get(alice,'?from='+day+'&to='+day)).data.summaries[0];assert.equal(work.worked,480);assert.equal(work.shortfall,0);
 const policy=await ok(payroll,{mode:'policy',title:'Approved contract rates',insuranceBps:1000,insuranceCap:'0',taxBps:1000,taxExemption:'0'});await success(payroll,policy,'submit');assert.equal((await apply(payroll,policy,'publish')).status,403);await success(approver,policy,'publish');
 const ruling=await ok(hr,{mode:'ruling',memberId:'alice',title:'Pay ruling',text:'Agreed contract',effective:day,monthlyBase:'100000',monthlyAllowance:'0',overtimeHourly:'600',policyId:policy});await success(hr,ruling,'submit');await success(approver,ruling,'publish');assert.equal((await get(manager)).data.records.some(r=>r.id===ruling),false);
 const loan=await ok(alice,{mode:'request',kind:'loan',amount:'2000',installments:2,repaymentStart:day});await success(hr,loan,'approve');await success(finance,loan,'approve');await success(treasury,loan,'pay',{amount:'2000',day,reference:'LOAN-TRANSFER'});
 const period=await ok(hr,{mode:'period',title:'Test payroll period',start:day,end:day,deadline:duties.addDay(day,1),memberIds:['alice']});await success(hr,period,'close_work');assert.equal((await post(hr,{mode:'punch',memberId:'alice',day,at:day+'T08:00:00+03:30',direction:'in',reference:'Manual'})).status,409);
 await success(payroll,period,'calculate');const slip=sql.prepare("SELECT id FROM flow_entities WHERE type='hr_payroll'").get().id;assert.equal(row(slip).data.gross,'100000');assert.equal(row(slip).data.insurance,'10000');assert.equal(row(slip).data.tax,'9000');assert.equal(row(slip).data.net,'80000');assert.equal(row(loan).data.recovered,'0');assert.equal((await get(alice)).data.records.some(r=>r.id===slip),false);
 await success(approver,slip,'approve_payroll');await success(approver,slip,'publish');assert.equal((await get(alice)).data.records.some(r=>r.id===slip),true);assert.equal((await get(manager)).data.records.some(r=>r.id===slip),false);await success(finance,slip,'approve_payment');
 await success(treasury,slip,'pay',{amount:'30000',day,reference:'SALARY-PART-1'});assert.equal(row(slip).data.state,'partial');assert.equal(row(loan).data.recovered,'0');assert.equal((await apply(treasury,slip,'pay',{amount:'60000',day,reference:'TOO-MUCH'})).status,400);
 await success(treasury,slip,'pay',{amount:'50000',day,reference:'SALARY-PART-2'});assert.equal(row(slip).data.state,'paid');assert.equal(row(loan).data.recovered,'1000');await success(approver,period,'close_period');assert.equal(row(slip).data.state,'closed');const printed=await ctx.run(alice,()=>printApi.GET(req('/api/personnel/print?id='+slip)));assert.equal(printed.status,200);assert.ok((await printed.text()).includes('کد پرسنلی'));assert.equal((await ctx.run(manager,()=>printApi.GET(req('/api/personnel/print?id='+slip)))).status,404);assert.equal((await apply(approver,period,'reopen_work')).status,400);

 // Payroll may be rejected and recalculated before publication/payment, preserving superseded slips.
 const day2=duties.addDay(day,1),period2=await ok(hr,{mode:'period',title:'Correction period',start:day2,end:day2,deadline:duties.addDay(day2,1),memberIds:['bob']});
 const ruling2=await ok(hr,{mode:'ruling',memberId:'bob',title:'Bob ruling',text:'Contract',effective:day,monthlyBase:'1000',monthlyAllowance:'0',overtimeHourly:'0',policyId:policy});await success(hr,ruling2,'submit');await success(approver,ruling2,'publish');
 await success(hr,period2,'close_work');await success(payroll,period2,'calculate');const rejectedSlip=sql.prepare("SELECT id FROM flow_entities WHERE type='hr_payroll' AND json_extract(data,'$.memberId')='bob'").get().id;await success(approver,rejectedSlip,'reject');await success(approver,period2,'cancel_calculation');assert.equal(row(rejectedSlip).data.state,'cancelled');assert.equal(row(period2).data.state,'draft');await success(hr,period2,'close_work');await success(payroll,period2,'calculate');
 // Overnight hourly leave uses the next calendar morning, and work on an off day is approved overtime.
 const fixtures=[{id:'night',type:'hr_shift',data:{weekdays:[0,1,2,3,4,5,6],holidays:[],startTime:'22:00',endTime:'06:00',breakMinutes:0}},{id:'assignment',type:'hr_assignment',data:{memberId:'x',start:day,end:day,shiftId:'night'}},{id:'x',type:'hr_employee',data:{memberId:'x',start:day,end:''}}];
 assert.equal(domain.leaveMinutes(fixtures,'x',{start:day,end:day,hourly:true,startTime:'01:00',endTime:'03:00'}),120);
 const off=structuredClone(fixtures);off[0].data.holidays=[day];off.push({id:'i',type:'hr_punch',data:{memberId:'x',day,at:day+'T22:00:00+03:30',direction:'in'}},{id:'o',type:'hr_punch',data:{memberId:'x',day,at:duties.addDay(day,1)+'T06:00:00+03:30',direction:'out'}},{id:'ot',type:'hr_request',data:{memberId:'x',kind:'overtime',state:'approved',start:day,end:day,inAt:day+'T22:00:00+03:30',outAt:duties.addDay(day,1)+'T06:00:00+03:30'}});assert.equal(domain.workSummary(off,'x',day,day).overtime,480);
 // Concurrent permission changes invalidate the whole prepared mutation.
 const oldBatch=db.batch;db.batch=async statements=>{db.batch=oldBatch;sql.prepare("UPDATE app_members SET name='Changed payroll' WHERE id='payroll'").run();return oldBatch(statements)};const raceOp=crypto.randomUUID();assert.equal((await post(alice,{id:raceOp,mode:'request',kind:'certificate'})).status,409);assert.equal(row(raceOp),null);
 // Forced DB failure rolls back operation, data and audit, not just the last statement.
 sql.exec("CREATE TRIGGER hr_forced BEFORE INSERT ON flow_entities WHEN NEW.type='hr_request' BEGIN SELECT RAISE(ABORT,'forced'); END");const n=sql.prepare('SELECT COUNT(*) n FROM inventory_operations').get().n;assert.equal((await post(alice,{mode:'request',kind:'certificate'})).status,409);assert.equal(sql.prepare('SELECT COUNT(*) n FROM inventory_operations').get().n,n);sql.exec('DROP TRIGGER hr_forced');
 const body={id:crypto.randomUUID(),mode:'request',kind:'certificate'},created=await ok(alice,body);assert.equal((await post(alice,body)).data.repeated,true);assert.equal((await post(alice,{...body,notes:'Changed'})).status,409);
 const p={user:alice,scope:'read_write',tokenId:null};assert.equal((await catalog.executeTool('get_personnel',{},base,p)).me,'alice');await assert.rejects(()=>catalog.executeTool('personnel_apply',{id:crypto.randomUUID(),confirmed:true,mode:'request',revision:0,notes:'Certificate',kind:'certificate'},base,{...p,scope:'read'}),/read-only/);
 const csrf=await ctx.run(alice,()=>api.POST(req('/api/personnel',{mode:'request'},'https://evil.local')));assert.equal(csrf.status,403);
 const training=load('lib/training-context.ts').trainingContext;assert.equal((await training.run({actor:alice.userId,role:'sales'},()=>get(alice))).status,403);
 sql.prepare("UPDATE reset_control SET phase='maintenance',internal=0 WHERE id=1").run();assert.equal((await post(alice,{mode:'request',kind:'certificate'})).status,423);assert.equal(sql.prepare('PRAGMA foreign_key_check').all().length,0);
 console.log('Personnel passed: scoped identity/roles, salary and file privacy, no self approval, leave reservation/cancellation/concurrency, tasks, correction, payroll snapshots/tax/loan/partial payment, closed period, rollback/idempotency, MCP, CSRF, training and maintenance.');
})().catch(e=>{console.error(e);process.exit(1)});
