const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');const root=path.resolve(__dirname,'..');const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',f),'utf8'));
const db={prepare(q){let args=[];return{bind(...a){args=a;return this},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:{changes:sql.prepare(q).run(...args).changes}}}}},async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const objects=new Map();const bucket={async put(k,b){objects.set(k,b.slice(0));return {key:k}},async get(k){const b=objects.get(k);return b?{arrayBuffer:async()=>b.slice(0)}:null},async delete(k){objects.delete(k)}};
let identity=null;const env={TRACE_OWNER_EMAIL:'owner@example.com',LLM_CONFIG_ENCRYPTION_KEY:require('node:crypto').randomBytes(32).toString('base64'),DB:db,BUCKET:bucket};
const cache={};function load(file){file=path.resolve(root,file);if(cache[file])return cache[file];const exports={};cache[file]=exports;const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
vm.runInNewContext(source,{exports,require:n=>{if(n==='cloudflare:workers')return {env};if(n==='@/app/chatgpt-auth')return {getChatGPTUser:async()=>identity};if(n.startsWith('@/')||n.startsWith('.')){const p=n.startsWith('@/')?path.join(root,n.slice(2)):path.resolve(path.dirname(file),n);return load(p+(path.extname(p)?'':'.ts'));}return require(n)},structuredClone,Response,Request,URL,URLSearchParams,Error,crypto:globalThis.crypto,Date,Intl,Set,Map,FormData,Blob,File,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,AbortController,ReadableStream,btoa,atob,setTimeout:(f,n)=>setTimeout(f,Math.min(n,10)),clearTimeout,console},{filename:file});return exports;}

const printApi=load('app/api/personnel/print/route.ts');
const ctx=load('lib/mcp/context.ts').mcpActor,api=load('app/api/personnel/route.ts'),files=load('app/api/personnel/files/route.ts'),domain=load('lib/personnel.ts'),catalog=load('lib/mcp/tools.ts'),tasks=load('app/api/tasks/route.ts'),duties=load('lib/duties.ts');
let tail=Promise.resolve();const batch=db.batch.bind(db);db.batch=stmts=>{const next=tail.then(()=>batch(stmts));tail=next.catch(()=>{});return next};
const base='https://test.local',now=new Date().toISOString(),today=duties.dayAt(),day=duties.addDay(today,-10),next=duties.addDay(today,2);
const req=(url,b,origin=base)=>new Request(base+url,{method:b?'POST':'GET',headers:{origin,'Content-Type':'application/json'},...(b?{body:JSON.stringify(b)}:{})});
function actor(id,roles=[],extra={}){const u={userId:'local:'+id,email:id+'@test.local',name:id,isAdmin:false,permissions:{read:[],write:[],eventStages:[],personnelRoles:roles,...extra}};sql.prepare("INSERT INTO app_members(id,email,name,unit,status,subject,permissions,created,updated) VALUES(?,?,?,'company','active',?,?,?,?)").run(id,u.email,id,u.userId,JSON.stringify(u.permissions),now,now);return u;}
const alice=actor('alice'),bob=actor('bob'),manager=actor('manager'),hr=actor('hr',['hr']),payroll=actor('payroll',['payroll']),approver=actor('approver',['approver']),finance=actor('finance',['finance']),treasury=actor('treasury',['treasury']),external=actor('external',[],{salesAgentId:'outside',salesRoles:['agent']});
const row=id=>{const r=sql.prepare('SELECT * FROM flow_entities WHERE id=?').get(id);return r?{...r,data:JSON.parse(r.data)}:null};
async function get(u,q=''){const r=await ctx.run(u,()=>api.GET(req('/api/personnel'+q)));return {status:r.status,data:await r.json()}}
async function post(u,b){const r=await ctx.run(u,()=>api.POST(req('/api/personnel',{id:crypto.randomUUID(),confirmed:true,revision:0,notes:'Actual evidence',...b})));return {status:r.status,data:await r.json()}}
async function ok(u,b){const r=await post(u,b);assert.equal(r.status,200,JSON.stringify({b,r}));return r.data.id;}
const apply=(u,id,mode,extra={})=>post(u,{recordId:id,revision:row(id).revision,mode,...extra});
const success=async(u,id,mode,extra={})=>{const r=await apply(u,id,mode,extra);assert.equal(r.status,200,JSON.stringify({mode,r}));return r};
const seed=(id,type,data)=>sql.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').run(id,type,JSON.stringify(data),now,now);
const profile={mode:'employee',code:'A01',memberId:'alice',managerId:'manager',start:day,end:'',title:'Engineer',unit:'Production',location:'Factory',employment:'Full time',leaveMinutes:960,bankAccount:'PRIVATE-BANK',personal:'PRIVATE-PERSONAL'};
(async()=>{
 await ok(hr,profile);await ok(hr,{...profile,memberId:'bob',code:'B01'});
 const input={id:crypto.randomUUID(),mode:'request',kind:'advance',amount:'2000',installments:1,repaymentStart:today,requestMonth:'1900-01',limitAssessment:{status:'approved',limit:'999999'}};
 const aid=await ok(alice,input);assert.equal((await post(alice,input)).data.repeated,true);assert.equal(row(aid).data.requestMonth,load('lib/personnel-contract.ts').advanceMonth(today));assert.equal(row(aid).data.limitAssessment.status,'unconfigured');assert.equal(row(aid).data.limitAssessment.limit,null);
 const summary=async u=>(await get(u)).data.advances;
 assert.equal((await summary(alice))[0].pending,'2000');assert.equal((await summary(alice))[0].remainingLimit,null);assert.equal((await summary(bob))[0].requestCount,0);assert.equal((await summary(manager)).length,0);
 assert.equal((await apply(alice,aid,'approve')).status,403);assert.equal((await post(bob,{...input,id:crypto.randomUUID(),memberId:'alice'})).status,403);
 await success(hr,aid,'approve');await success(finance,aid,'approve');assert.equal((await summary(alice))[0].pending,'0');assert.equal((await summary(alice))[0].approved,'2000');
 await success(treasury,aid,'pay',{amount:'500',day:today,reference:'ADV-PART'});assert.equal((await summary(alice))[0].paid,'500');assert.equal(row(aid).data.state,'partial');
 await success(treasury,aid,'pay',{amount:'1500',day:today,reference:'ADV-FINAL'});assert.equal(row(aid).data.state,'paid');assert.equal((await summary(alice))[0].paid,'2000');
 const denied=await ok(alice,{...input,id:crypto.randomUUID(),amount:'10'});await success(hr,denied,'reject');assert.equal((await summary(alice))[0].pending,'0');
 const mcpInput={id:crypto.randomUUID(),confirmed:true,amount:'300',installments:1,repaymentStart:today,notes:'Actual advance reason'};
 await assert.rejects(()=>catalog.executeTool('request_personnel_advance',mcpInput,base,{user:alice,scope:'read',tokenId:null}),/read-only/);
 const mcp=await catalog.executeTool('request_personnel_advance',mcpInput,base,{user:alice,scope:'read_write',tokenId:null});assert.equal(row(mcp.id).data.kind,'advance');assert.equal((await summary(alice))[0].pending,'300');await success(alice,mcp.id,'withdraw');assert.equal((await summary(alice))[0].pending,'0');
 const fn=load('lib/personnel-contract.ts').advanceSummary;assert.equal(fn([{type:'hr_request',created:'2026-03-20T21:00:00Z',data:{memberId:'alice',kind:'advance',state:'hr',amount:'12'}}],'alice','2026-03-21').pending,'12');assert.equal(fn([{type:'hr_request',created:'2026-03-20T19:00:00Z',data:{memberId:'alice',kind:'advance',state:'hr',amount:'12'}}],'alice','2026-03-21').pending,'0');
 const reset=load('lib/reset-contract.ts');for(const scope of ['operations','full'])assert.ok(sql.prepare('SELECT COUNT(*) n FROM flow_entities WHERE '+reset.resetWhere('flow_entities',scope)+" AND type='hr_request'").get().n>=3);
 sql.exec('BEGIN');for(const t of Object.keys(reset.resetTables))sql.exec('DELETE FROM '+t+' WHERE '+reset.resetWhere(t,'operations'));assert.equal(sql.prepare('PRAGMA foreign_key_check').all().length,0);sql.exec('ROLLBACK');assert.equal(row(aid).data.state,'paid');
 sql.prepare("UPDATE reset_control SET phase='maintenance',internal=0 WHERE id=1").run();assert.equal((await post(alice,{...input,id:crypto.randomUUID()})).status,423);
 console.log('Advance passed: own scope, financial privacy, independent approvals, partial/full payment, rejected/withdrawn totals, Persian month boundary, unset ceiling, MCP, retry, reset/freeze rollback.');
})().catch(e=>{console.error(e);process.exitCode=1});
