const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');const root=path.resolve(__dirname,'..');
function load(file,imports={}){const exports={};const source=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(source,{exports,require:name=>{if(!(name in imports))throw new Error('Missing import '+name);return imports[name]},Response,Request,URL,Error,crypto:globalThis.crypto,Date,Intl,Set,console:{error(){}}});return exports;}
const sql=new DatabaseSync(':memory:');for(const file of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',file),'utf8'));
const db={prepare(query){let args=[];return{bind(...values){args=values;return this},async first(){return sql.prepare(query).get(...args)||null},async all(){return{results:sql.prepare(query).all(...args)}},async run(){return{meta:{changes:sql.prepare(query).run(...args).changes}}}}},async batch(statements){sql.exec('BEGIN');try{const results=[];for(const statement of statements)results.push(await statement.run());sql.exec('COMMIT');return results}catch(e){sql.exec('ROLLBACK');throw e}}};
let identity=null;const env={TRACE_OWNER_EMAIL:'owner@example.com'};
const permissions=load('lib/permissions.ts');for(const preset of Object.values(permissions.presets))permissions.validatePermissions(preset);
const numbers=load('lib/batch-number.ts');const distribution=load('lib/distribution.ts',{'./batch-number':numbers,'./persian-date':load('lib/persian-date.ts')});const model=load('lib/model.ts',{'./batch-number':numbers,'./distribution':distribution});
const auth=load('lib/authorization.ts',{'@/lib/mcp/context':{mcpActor:new (require('node:async_hooks').AsyncLocalStorage)()},'cloudflare:workers':{env},'@/app/chatgpt-auth':{getChatGPTUser:async()=>identity},'@/lib/storage':{storage:()=>db},'@/lib/permissions':permissions});
const imports={'cloudflare:workers':{env},'@/lib/authorization':auth,'@/lib/storage':{storage:()=>db},'@/lib/permissions':permissions,'@/lib/batch-number':numbers,'@/lib/model':model};
const users=load('app/api/users/route.ts',imports),records=load('app/api/records/route.ts',imports),suggestion=load('app/api/batch-suggestion/route.ts',imports);
const request=(method,body,origin='https://test.local')=>new Request('https://test.local/api/records',{method,headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(body)});
const user=(id,email)=>({userId:id,email,displayName:id});
(async()=>{
 identity=user('owner-subject','owner@example.com');
 const product={code:' nf۵ ',name:'Oxygen five',group:'Oxygen',model:'NF5',warrantyMonths:'24',status:'فعال'};
 let response=await records.POST(request('POST',{kind:'product',data:product}));assert.equal(response.status,201);let p=(await response.json()).record;assert.equal(p.id,'product:NF5');
 assert.equal((await records.POST(request('POST',{kind:'product',data:{...product,code:'NF5'}}))).status,409);
 for(const months of ['-1','1.5','NaN'])assert.equal((await records.POST(request('POST',{kind:'product',data:{...product,code:'OTHER',warrantyMonths:months}}))).status,400);
 const data={code:'DEV-1',product:p.id,model:'Forged model',productName:'Forged name',warrantyMonths:'999',design:'R1',date:'2026-09-13'};
 response=await records.POST(request('POST',{kind:'device',data}));assert.equal(response.status,201);const d=(await response.json()).record;
 assert.equal(d.data.model,'NF5');assert.equal(d.data.warrantyMonths,'24');assert.equal(d.data.productName,'Oxygen five');assert.equal(d.data.productCode,'NF5');
 assert.equal((await records.POST(request('POST',{kind:'device',data:{...data,code:'NO-PRODUCT',product:''}}))).status,400);
 assert.equal((await records.POST(request('POST',{kind:'device',data:{...data,code:'BAD-REF',product:d.id}}))).status,400);
 const patch=extra=>records.PATCH(request('PATCH',{id:p.id,previous:JSON.stringify(p.data),data:{...p.data,...extra}}));
 assert.equal((await patch({code:'NEW'})).status,400);
 response=await patch({model:'NF5-B',warrantyMonths:'36',status:'توقف تولید'});assert.equal(response.status,200);
 assert.equal((await patch({name:'Stale edit'})).status,409);
 assert.equal((await records.POST(request('POST',{kind:'device',data:{...data,code:'PAUSED'}}))).status,400);
 const savedDevice=JSON.parse(sql.prepare('SELECT payload FROM records WHERE id=?').get(d.id).payload);assert.equal(savedDevice.model,'NF5');assert.equal(savedDevice.warrantyMonths,'24');
 p=(await response.json()).record;response=await patch({status:'فعال'});assert.equal(response.status,200);p=(await response.json()).record;
 const batch=db.batch;db.batch=async statements=>{sql.prepare('UPDATE records SET payload=? WHERE id=?').run(JSON.stringify({...p.data,status:'توقف تولید'}),p.id);return batch(statements)};
 assert.equal((await records.POST(request('POST',{kind:'device',data:{...data,code:'RACE'}}))).status,409);db.batch=batch;
 assert.equal(sql.prepare("SELECT count(*) n FROM records WHERE id='device:RACE'").get().n,0);assert.equal(sql.prepare("SELECT count(*) n FROM access_audit WHERE target='device:RACE'").get().n,0);
 sql.prepare('INSERT INTO records(id,kind,payload,created) VALUES(?,?,?,?)').run('legacy','device',JSON.stringify({code:'OLD',model:'Legacy model'}),'2020-01-01');
 assert.ok((await (await records.GET()).json()).records.some(r=>r.id==='legacy'&&r.data.model==='Legacy model'&&!r.data.product));
 await users.POST(request('POST',{email:'prod@example.com',name:'Production',unit:'تولید',status:'active',permissions:permissions.presets['تولید']}));
 await users.POST(request('POST',{email:'old@example.com',name:'Legacy account',unit:'تولید',status:'active',permissions:{read:['device'],write:['device'],eventStages:[]}}));
 identity=user('prod','prod@example.com');assert.ok((await (await records.GET()).json()).records.some(r=>r.kind==='product'));assert.equal((await records.POST(request('POST',{kind:'product',data:{...product,code:'DENIED'}}))).status,403);assert.equal((await patch({status:'فعال'})).status,403);
 identity=user('old','old@example.com');assert.ok(!(await (await records.GET()).json()).records.some(r=>r.kind==='product'));assert.equal((await records.POST(request('POST',{kind:'device',data:{...data,code:'FORBIDDEN'}}))).status,403);
 assert.equal(sql.prepare("SELECT count(*) n FROM access_audit WHERE action='issue_warranty_code'").get().n,0);
 console.log('Product checks passed: unique normalized code, validation, authoritative device snapshots, immutable code, optimistic edits, stop production, concurrent change rejection without orphan audit, legacy passports, permissions and no warranty activation.');
})().catch(e=>{console.error(e);process.exitCode=1});
