const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite'),root=path.resolve(__dirname,'..');
const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',f),'utf8'));
const db={prepare(q){let args=[];return{bind(...a){args=a;return this},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:{changes:sql.prepare(q).run(...args).changes}}}}},async batch(stmts){sql.exec('BEGIN');try{for(const s of stmts)await s.run();sql.exec('COMMIT');}catch(e){sql.exec('ROLLBACK');console.error('DB rollback',e.message);throw e;}}};
let user={userId:'owner',name:'Owner',isAdmin:true,permissions:{finance:'write'}};
class AccessError extends Error{constructor(m,s){super(m);this.status=s;}}
const auth={AccessError,requireAccess:async()=>user,checkOrigin:r=>{if(r.headers.get('origin')!=='https://test.local')throw new AccessError('origin',403);},accessResponse:e=>e instanceof AccessError?Response.json({error:e.message},{status:e.status}):null};
const objects=new Map();const bucket={async put(k,v){objects.set(k,new Uint8Array(v));},async get(k){const v=objects.get(k);return v?{arrayBuffer:async()=>v.buffer.slice(v.byteOffset,v.byteOffset+v.byteLength)}:null;},async delete(k){objects.delete(k);}};
const cache={};function load(file){file=path.resolve(root,file);if(cache[file])return cache[file];const exports={};cache[file]=exports;vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>{if(n==='cloudflare:workers')return {env:{DB:db,BUCKET:bucket}};const p=n.startsWith('@/')?path.resolve(root,n.slice(2)+'.ts'):n.startsWith('.')?path.resolve(path.dirname(file),n+'.ts'):'';if(p.replace(/\\/g,'/').endsWith('/lib/storage.ts'))return {storage:()=>db};if(p.replace(/\\/g,'/').endsWith('/lib/authorization.ts'))return auth;if(p.replace(/\\/g,'/').endsWith('/lib/firmware-storage.ts'))return {firmwareBucket:()=>bucket,boundedBody:async(r,max)=>{const v=new Uint8Array(await r.arrayBuffer());if(v.length>max)throw new AccessError('large',413);return v;}};if(p.replace(/\\/g,'/').endsWith('/lib/sourcing.ts'))return {hasSupply:(u,r)=>u.isAdmin||u.permissions.supplyRoles?.includes(r),day:v=>{assert.match(v,/^\d{4}-\d{2}-\d{2}$/);return v;}};if(p.replace(/\\/g,'/').endsWith('/lib/firmware.ts'))return {sha256:async v=>require('node:crypto').createHash('sha256').update(new Uint8Array(v)).digest('hex')};if(p)return load(p);return require(n)},Response,Request,URL,Error,Date,Intl,Map,Set,TextEncoder,TextDecoder,Uint8Array,crypto:globalThis.crypto,structuredClone,console},{filename:file});return exports;}

const api=load('app/api/purchase-payables/route.ts'),filesApi=load('app/api/purchase-payables/files/route.ts');
const entity=(id,type,data)=>sql.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').run(id,type,JSON.stringify(data),'2026-10-01','2026-10-01');
const body=(mode,extra={})=>({mode,id:crypto.randomUUID(),confirmed:true,notes:'Actual evidence reviewed',revision:0,...extra});
async function post(b,status=200){const r=await api.POST(new Request('https://test.local/api/purchase-payables',{method:'POST',headers:{origin:'https://test.local'},body:JSON.stringify(b)}));const d=await r.json();assert.equal(r.status,status,b.mode+': '+JSON.stringify(d));return d;}
async function get(){const r=await api.GET();assert.equal(r.status,200);return r.json();}
let cid;async function current(){return (await get()).cases.find(c=>c.id===cid);}async function action(mode,extra={},status=200){const c=await current();return post(body(mode,{caseId:cid,revision:c.revision,...extra}),status);}
const buyer={userId:'buyer',name:'Buyer',isAdmin:false,permissions:{supplyRoles:['domestic'],finance:'none'}},finance={userId:'finance',name:'Finance',isAdmin:false,permissions:{supplyRoles:['finance'],finance:'write'}};
const invoiceDomain=load('lib/purchase-invoice.ts'),scheduler=load('lib/purchase-invoice-tasks.ts');
async function report(query=''){const r=await api.GET(new Request('https://test.local/api/purchase-payables?view=formal&'+query));return {status:r.status,data:await r.json()};}
async function file(caseId=cid){const id=crypto.randomUUID(),r=await filesApi.POST(new Request('https://test.local/api/purchase-payables/files?'+new URLSearchParams({id,caseId,filename:'invoice.pdf'}),{method:'POST',headers:{origin:'https://test.local'},body:'%PDF fixture'}));assert.equal(r.status,200,await r.text());return id;}
function order(id){entity(id,'purchase_order',{supplierId:'s',route:'domestic',partCode:id,unit:'عدد',quantity:1000,state:'shipped'});entity('r'+id,'receipt',{purchaseOrderId:id,quantity:1000,accepted:1000,rejected:0,state:'stored'});entity('m'+id,'material',{code:id,name:'کالای '+id});}
async function invoice(id,type){order(id);await action('invoice',{invoiceType:type,reference:id,day:'2026-01-01',amount:'100',purpose:'خرید کالا',terms:'نقدی',evidence:'Text only',lines:[{orderId:id,quantity:'1',amount:'100',receiptIds:['r'+id]}]});return (await current()).data.invoices.at(-1).id;}
async function pay(reference,amount='40'){await action('payment',{reference,amount,day:'2026-01-01',purpose:'خرید',evidence:'bank'});return (await current()).data.payments.at(-1).id;}
const snapshot=()=>sql.prepare("SELECT * FROM flow_entities WHERE type IN ('purchase_payable','payable_file','purchase_order','receipt')").all().map(r=>({...r,data:JSON.parse(r.data)}));
(async()=>{
 entity('s','supplier',{name:'تأمین‌کننده آزمایشی'});for(const m of [buyer,finance])sql.prepare("INSERT INTO app_members(id,email,name,unit,status,permissions,created,updated) VALUES(?,?,?,?, 'active',?,?,?)").run(m.userId,m.userId+'@test',m.name,'team',JSON.stringify(m.permissions),'2026-01-01','2026-01-01');
 user=buyer;cid=(await post(body('create',{supplierId:'s',route:'domestic',title:'خرید'}))).id;
 const iid=await invoice('NON','informal');user=finance;await action('recognize',{itemId:iid,account:'AP',basis:'خرید بررسی شد'});await action('schedule',{itemId:iid,schedule:[{amount:'100',due:'2026-01-01',condition:'cash'}]});await action('release',{itemId:iid});assert.equal((await current()).view.invoices[0].released,true,'Informal payment must not be blocked by missing invoice file');
 const pid=await pay('PAY');await action('allocate',{invoiceId:iid,paymentId:pid,amount:'40'});
 let all=snapshot(),c=all.find(c=>c.id===cid);assert.equal(invoiceDomain.invoiceFollowups(c,all,'2026-01-07').length,0);assert.equal(invoiceDomain.invoiceFollowups(c,all,'2026-01-08')[0].paid,'40');
 await scheduler.syncPurchaseInvoiceTasks('2026-01-07');assert.equal(sql.prepare("SELECT COUNT(*) n FROM duty_runs WHERE template_id='purchase-invoice-document'").get().n,0);
 await scheduler.syncPurchaseInvoiceTasks('2026-01-08');let tasks=sql.prepare("SELECT * FROM duty_runs WHERE template_id='purchase-invoice-document' AND state='open'").all();assert.equal(tasks.length,2);assert.deepEqual(tasks.map(t=>t.assignee).sort(),['buyer','finance']);await scheduler.syncPurchaseInvoiceTasks('2026-01-08');assert.equal(sql.prepare("SELECT COUNT(*) n FROM duty_notices WHERE phase='invoice-document-missing'").get().n,2);
 // Workflow closure cannot be forged from the generic task endpoint.
 const taskApi=load('app/api/tasks/route.ts');user=buyer;const assigned=tasks.find(t=>t.assignee==='buyer');for(const mode of ['submit','approve','cancel','extend']){const response=await taskApi.POST(new Request('https://test.local/api/tasks',{method:'POST',headers:{origin:'https://test.local'},body:JSON.stringify({id:crypto.randomUUID(),mode,taskId:assigned.id,revision:assigned.revision,note:'fake completion'})}));assert.equal(response.status,400,mode+await response.text());}
 // A text reference cannot close the warning; only a real same-case upload may link.
 user=buyer;await action('invoice_document',{itemId:iid,documentId:'Text only'},400);const otherCase=(await post(body('create',{supplierId:'s',route:'domestic',title:'دیگر'}))).id,wrong=await file(otherCase);await action('invoice_document',{itemId:iid,documentId:wrong},400);
 const doc=await file();await action('invoice_document',{itemId:iid,documentId:doc});await scheduler.syncPurchaseInvoiceTasks('2026-01-08');assert.equal(sql.prepare("SELECT COUNT(*) n FROM duty_runs WHERE template_id='purchase-invoice-document' AND state='open'").get().n,0);
 // Formal invoices need a linked upload, not arbitrary evidence text.
 const formal=await invoice('OFFICIAL','formal');user=finance;await action('recognize',{itemId:formal,account:'AP',basis:'reviewed'},400);await action('release',{itemId:formal},400);const formalDoc=await file();await action('invoice_document',{itemId:formal,documentId:formalDoc});await action('recognize',{itemId:formal,account:'AP',basis:'reviewed'});
 user=buyer;await action('invoice_tax',{itemId:formal,taxState:'accepted',taxId:'',taxDay:'2026-01-02'},400);await action('invoice_tax',{itemId:formal,taxState:'awaiting_review',taxId:'TAX-123',taxDay:'2026-01-02'});await action('invoice_tax',{itemId:formal,taxState:'rejected',taxId:'TAX-123',taxDay:'2026-01-03',notes:'مغایرت کالا'});
 let rep=await report(new URLSearchParams({supplier:'آزمایشی',product:'کالای OFFICIAL',from:'2026-01-01',to:'2026-01-01',state:'rejected'}));assert.equal(rep.status,200);assert.equal(rep.data.total,1);assert.equal(rep.data.items[0].document.id,formalDoc);assert.equal(rep.data.items[0].taxNote,'مغایرت کالا');assert.equal(rep.data.manualTaxTracking,true);assert.equal((await report('product=NON')).data.total,0);assert.equal((await report('from=bad')).status,400);assert.equal((await report('from=2026-01-02&to=2026-01-01')).status,400);
 await action('invoice_tax',{itemId:iid,taxState:'accepted',taxId:'TAX',taxDay:'2026-01-02'},400);
 user={userId:'foreign',permissions:{supplyRoles:['foreign']}};assert.equal((await report()).data.total,0);user={userId:'rep',permissions:{salesAgentId:'r',finance:'write'}};assert.equal((await report()).status,403);
 // Payment before any invoice also gets a seven-day task, and voiding that payment retires it.
 user=finance;const free=await pay('UNALLOCATED','30');await scheduler.syncPurchaseInvoiceTasks('2026-01-08');assert.equal(sql.prepare("SELECT COUNT(*) n FROM duty_runs WHERE template_id='purchase-invoice-document' AND state='open'").get().n,2);await action('void',{kind:'payments',itemId:free});await scheduler.syncPurchaseInvoiceTasks('2026-01-08');assert.equal(sql.prepare("SELECT COUNT(*) n FROM duty_runs WHERE template_id='purchase-invoice-document' AND state='open'").get().n,0);
 // Legacy invoice types remain explicit; classification does not change debt or paid amounts.
 const raw=sql.prepare('SELECT data FROM flow_entities WHERE id=?').get(cid),legacy=JSON.parse(raw.data);delete legacy.invoices[0].invoiceType;sql.prepare('UPDATE flow_entities SET data=?,revision=revision+1 WHERE id=?').run(JSON.stringify(legacy),cid);await action('invoice_classify',{itemId:iid,invoiceType:'informal'});assert.equal((await current()).view.invoices[0].paid,'40');await action('invoice_classify',{itemId:iid,invoiceType:'formal'},400);
 const mcp=load('lib/mcp/tools.ts').tools.find(t=>t.name==='get_formal_purchase_invoices');assert.ok(mcp&&!mcp.write);const result=await mcp.run({reference:'TAX-123'},'https://test.local');assert.equal(result.total,1);assert.equal(result.items[0].taxState,'rejected');
 // Freeze and rollback protect follow-up rows and notices, and reset includes them.
 await pay('FREEZE','10');sql.exec("UPDATE reset_control SET phase='maintenance'");await assert.rejects(()=>scheduler.syncPurchaseInvoiceTasks('2026-01-08'),/RESET_MAINTENANCE/);sql.exec("UPDATE reset_control SET phase='testing'");await scheduler.syncPurchaseInvoiceTasks('2026-01-08');
 const reset=load('lib/reset-contract.ts');for(const scope of ['operations','full']){sql.exec('BEGIN');for(const t of Object.keys(reset.resetTables))sql.exec('DELETE FROM '+t+' WHERE '+reset.resetWhere(t,scope));assert.equal(sql.prepare("SELECT COUNT(*) n FROM duty_runs WHERE template_id='purchase-invoice-document'").get().n,0);sql.exec('ROLLBACK');}
 console.log('PASS invoice types/report: informal release, real-file formal gate, paid/partial/unallocated seven-day boundary, both role tasks and dedup/closure, ownership, date/product/supplier filters, manual tax state, legacy classification, MCP and reset rollback.');
})().catch(e=>{console.error(e);process.exit(1)});
