const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');const root=path.resolve(__dirname,'..');const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',f),'utf8'));
const db={prepare(q){let args=[];return{bind(...a){args=a;return this},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:{changes:sql.prepare(q).run(...args).changes}}}}},async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const objects=new Map();const bucket={async put(k,b){objects.set(k,typeof b==='string'?b:new Uint8Array(b).slice());return {key:k}},async get(k){const b=objects.get(k);return b?{arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),text:async()=>typeof b==='string'?b:new TextDecoder().decode(b)}:null},async delete(k){objects.delete(k)}};
let identity=null;const env={TRACE_OWNER_EMAIL:'owner@example.com',LLM_CONFIG_ENCRYPTION_KEY:require('node:crypto').randomBytes(32).toString('base64'),DB:db,BUCKET:bucket};
const cache={};function load(file){file=path.resolve(root,file);if(cache[file])return cache[file];const exports={};cache[file]=exports;const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
vm.runInNewContext(source,{exports,require:n=>{if(n==='cloudflare:workers')return {env};if(n==='@/app/chatgpt-auth')return {getChatGPTUser:async()=>identity};if(n.startsWith('@/')||n.startsWith('.')){const p=n.startsWith('@/')?path.join(root,n.slice(2)):path.resolve(path.dirname(file),n);return load(p+(path.extname(p)?'':'.ts'));}return require(n)},structuredClone,Response,Request,URL,URLSearchParams,Error,crypto:globalThis.crypto,Date,Intl,Set,Map,FormData,Blob,File,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,AbortController,ReadableStream,btoa,atob,setTimeout:(f,n)=>setTimeout(f,Math.min(n,10)),clearTimeout,console},{filename:file});return exports;}


const ctx=load('lib/mcp/context.ts').mcpActor,api=load('app/api/qms/route.ts'),files=load('app/api/qms/files/route.ts'),domain=load('lib/qms.ts'),catalog=load('lib/mcp/tools.ts'),tasks=load('app/api/tasks/route.ts'),flow=load('app/api/flow/route.ts'),resetApi=load('app/api/system-reset/backup/route.ts');
let tail=Promise.resolve();const batch=db.batch.bind(db);db.batch=stmts=>{const next=tail.then(()=>batch(stmts));tail=next.catch(()=>{});return next};
const base='https://test.local',now=new Date().toISOString(),today=now.slice(0,10);
const req=(url,b)=>new Request(base+url,{method:b?'POST':'GET',headers:{origin:base,'Content-Type':'application/json'},...(b?{body:JSON.stringify(b)}:{})});
function actor(id,permissions={},isAdmin=false){const u={userId:'local:'+id,email:id+'@test.local',name:id,isAdmin,permissions:{read:[],write:[],eventStages:[],...permissions}};sql.prepare("INSERT INTO app_members(id,email,name,unit,status,subject,permissions,created,updated) VALUES(?,?,?,'company','active',?,?,?,?)").run(id,u.email,id,u.userId,JSON.stringify(u.permissions),now,now);return u;}
const eng=actor('eng',{supplyRoles:['engineering']}),ceo=actor('ceo',{supplyRoles:['ceo']}),eng2=actor('eng2',{supplyRoles:['engineering']}),qa=actor('qa',{qmsRoles:['qa']}),qa2=actor('qa2',{qmsRoles:['qa']}),viewer=actor('viewer',{qmsRoles:['observer']}),admin=actor('admin',{},true),external=actor('external',{salesAgentId:'outside',salesRoles:['agent']}),ordinary=actor('ordinary');
const row=id=>{const r=sql.prepare('SELECT * FROM flow_entities WHERE id=?').get(id);return r?{...r,data:JSON.parse(r.data)}:null};
async function invoke(u,handler,url,b){const r=await ctx.run(u,()=>handler(req(url,b)));return {status:r.status,data:await r.json()}}
const get=u=>invoke(u,api.GET,'/api/qms');const post=(u,b)=>invoke(u,api.POST,'/api/qms',{id:crypto.randomUUID(),confirmed:true,revision:0,notes:'Actual evidence',...b});
async function ok(u,b){const r=await post(u,b);assert.equal(r.status,200,JSON.stringify({b,r}));return r.data.id;}
const apply=(u,id,mode,extra={})=>post(u,{recordId:id,revision:row(id).revision,mode,...extra});
const success=async(u,id,mode,extra={})=>{const r=await apply(u,id,mode,extra);assert.equal(r.status,200,JSON.stringify({mode,r}));return r.data.id};
const seed=(id,type,data)=>sql.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').run(id,type,JSON.stringify(data),now,now);
const values=kind=>Object.fromEntries(load('lib/qms-contract.ts').qmsKinds[kind].fields.map(f=>[f.key,f.type==='date'?today:'Recorded evidence']));
const basic=(kind,extra={})=>({mode:'save',kind,title:kind==='design'?'SECRET-DESIGN':'Actual '+kind,productId:'p1',ownerId:'eng',reviewerId:'ceo',due:today,values:values(kind),...extra});
const filepost=(u,b)=>invoke(u,files.POST,'/api/qms/files',{id:crypto.randomUUID(),confirmed:true,...b});
async function part(u,id,index,bytes,op=crypto.randomUUID()){const r=await ctx.run(u,()=>files.PUT(new Request(base+'/api/qms/files?fileId='+id+'&part='+index,{method:'PUT',headers:{origin:base,'x-operation-id':op},body:bytes})));return {status:r.status,data:await r.json()}}
(async()=>{
 sql.prepare("INSERT INTO records(id,kind,payload,created) VALUES('p1','product',?,?)").run(JSON.stringify({name:'Product',code:'P1',status:'فعال'}),now);
 assert.equal((await get(ordinary)).status,403);assert.equal((await get(external)).status,403);
 const create={...basic('design'),id:crypto.randomUUID()};const design=await ok(eng,create);assert.equal((await post(eng,create)).data.repeated,true);assert.equal((await post(eng,{...create,title:'changed'})).status,409);
 assert.equal(row(design).data.private,true);assert.equal((await get(admin)).data.records.some(r=>r.id===design),false);assert.equal((await get(qa)).data.records.some(r=>r.id===design),false);assert.ok((await get(ceo)).data.records.some(r=>r.id===design));
 assert.equal((await apply(admin,design,'save',{...basic('design')})).status,404);assert.equal((await apply(qa,design,'approve')).status,404);
 assert.equal((await apply(eng,design,'save',{...basic('design'),private:false})).status,200);assert.equal(row(design).data.private,true);
 assert.ok(!JSON.stringify((await invoke(admin,flow.GET,'/api/flow')).data).includes('SECRET-DESIGN'));
 assert.ok(!JSON.stringify(sql.prepare('SELECT * FROM access_audit').all()).includes('SECRET-DESIGN'));assert.ok(!JSON.stringify(sql.prepare('SELECT * FROM inventory_operations').all()).includes('SECRET-DESIGN'));
 const chunkSize=load('lib/qms-contract.ts').QMS_PART_SIZE;
 const start=await filepost(eng,{mode:'start',parentId:design,filename:'SECRET-DESIGN.bin',size:chunkSize+3});assert.equal(start.status,200);const fid=start.data.id;
 assert.equal((await invoke(admin,files.GET,'/api/qms/files?fileId='+fid)).status,404);
 assert.equal((await part(eng2,fid,0,new Uint8Array(chunkSize))).status,403);
 assert.equal((await apply(eng,design,'submit')).status,400);
 assert.equal((await filepost(eng,{mode:'complete',fileId:fid})).status,409);
 const bytes=new Uint8Array(chunkSize).fill(7);assert.equal((await part(eng,fid,0,bytes)).status,200);assert.equal((await part(eng,fid,0,bytes)).data.repeated,true);assert.equal((await part(eng,fid,0,new Uint8Array(chunkSize).fill(8))).status,409);
 assert.equal((await part(eng,fid,1,new Uint8Array([1,2]))).status,400);assert.equal((await part(eng,fid,1,new Uint8Array([1,2,3]))).status,200);
 assert.equal((await filepost(eng,{mode:'complete',fileId:fid})).status,200);
 const download=await ctx.run(ceo,()=>files.GET(req('/api/qms/files?download=1&fileId='+fid)));assert.equal(download.status,200);const downloaded=new Uint8Array(await download.arrayBuffer());assert.equal(downloaded.length,chunkSize+3);assert.equal(downloaded[0],7);assert.equal(downloaded.at(-1),3);
 const memberBefore=sql.prepare("SELECT permissions FROM app_members WHERE id='eng'").get().permissions;sql.prepare("UPDATE app_members SET permissions=? WHERE id='eng'").run(JSON.stringify({read:[],write:[],eventStages:[],qmsRoles:['observer']}));assert.equal((await invoke(eng,files.GET,'/api/qms/files?fileId='+fid)).status,404);const revokedTasks=await invoke(eng,tasks.GET,'/api/tasks');assert.ok(!JSON.stringify(revokedTasks.data).includes(design));sql.prepare("UPDATE app_members SET permissions=? WHERE id='eng'").run(memberBefore);
 await success(eng,design,'submit');assert.equal((await apply(eng,design,'approve')).status,403);await success(ceo,design,'approve');assert.equal((await apply(eng,design,'save',{...basic('design')})).status,409);assert.equal((await filepost(eng,{mode:'start',parentId:design,filename:'late.bin',size:1})).status,400);
 const revision=await success(eng,design,'revise');assert.equal(row(design).data.state,'approved');assert.equal(row(revision).data.version,2);await success(eng,revision,'submit');await success(ceo,revision,'approve');assert.equal(row(design).data.state,'superseded');
 const form=await ok(eng,basic('form',{private:true,fields:[{key:'test',label:'Test',type:'choice',required:true,options:['pass','fail']}]}));await success(eng,form,'submit');await success(ceo,form,'approve');
 const response=await ok(eng,basic('response',{templateId:form,values:{test:'pass'}}));assert.equal(row(response).data.private,true);await success(eng,response,'submit');await success(ceo,response,'approve');assert.equal(row(response).data.template.version,1);
 assert.equal((await post(eng,basic('response',{templateId:form,values:{test:'hacked'}}))).status,400);
 const doc=await ok(qa,basic('document',{ownerId:'qa',reviewerId:'qa2',private:false}));assert.equal((await apply(viewer,doc,'save',{...basic('document')})).status,403);await success(qa,doc,'submit');await success(qa2,doc,'approve');assert.ok((await get(viewer)).data.records.some(r=>r.id===doc));
 const cap=await ok(qa,basic('capa',{ownerId:'qa',reviewerId:'qa2'}));await success(qa,cap,'submit');await success(qa2,cap,'approve');assert.equal((await apply(qa,cap,'close',{evidence:'Self'})).status,403);await success(qa2,cap,'close',{evidence:'Measured independent effectiveness'});
 const mcp={id:crypto.randomUUID(),confirmed:true,mode:'save',data:{...basic('design'),notes:'MCP actual evidence',revision:0}};delete mcp.data.mode;
 await assert.rejects(()=>catalog.executeTool('apply_qms_record',mcp,base,{user:eng,scope:'read',tokenId:null}),/read-only/);const mcpRecord=await catalog.executeTool('apply_qms_record',mcp,base,{user:eng,scope:'read_write',tokenId:null});assert.equal(row(mcpRecord.id).data.private,true);const adminView=await catalog.executeTool('get_qms_workspace',{},base,{user:admin,scope:'read',tokenId:null});assert.ok(!JSON.stringify(adminView).includes('SECRET-DESIGN'));
 await assert.rejects(()=>domain.guardQmsBackup(admin));await domain.guardQmsBackup(ceo);
 const tables={flow_entities:sql.prepare('SELECT * FROM flow_entities').all()};const manifest=load('lib/system-reset.ts').resetFiles(tables);assert.equal(manifest.filter(f=>f.key.startsWith('qms/v1/')).length,2);
 const positionsOp={id:crypto.randomUUID(),mode:'install_positions'};assert.equal((await post(admin,positionsOp)).status,200);assert.equal((await post(admin,positionsOp)).data.repeated,true);assert.equal(sql.prepare("SELECT COUNT(*) n FROM flow_entities WHERE type='position' AND id GLOB 'qms-position:*'").get().n,11);
 // A permission change during the operation rolls the record write back.
 const guarded=crypto.randomUUID(),normalBatch=db.batch;let injected=false;db.batch=async stmts=>{if(!injected){injected=true;sql.prepare("UPDATE app_members SET permissions=? WHERE id='eng'").run(JSON.stringify({read:[],write:[],eventStages:[]}));}return normalBatch(stmts)};
 assert.equal((await post(eng,{...basic('design'),id:guarded})).status,409);assert.equal(row(guarded),null);db.batch=normalBatch;sql.prepare("UPDATE app_members SET permissions=? WHERE id='eng'").run(memberBefore);
 const reset=load('lib/reset-contract.ts');assert.equal(sql.prepare('SELECT COUNT(*) n FROM flow_entities WHERE '+reset.resetWhere('flow_entities','operations')+" AND type GLOB 'qms_*'").get().n,0);assert.ok(sql.prepare('SELECT COUNT(*) n FROM flow_entities WHERE '+reset.resetWhere('flow_entities','full')+" AND type GLOB 'qms_*'").get().n>0);
 sql.exec('BEGIN');for(const t of Object.keys(reset.resetTables))sql.exec('DELETE FROM '+t+' WHERE '+reset.resetWhere(t,'full'));assert.equal(sql.prepare('PRAGMA foreign_key_check').all().length,0);sql.exec('ROLLBACK');assert.equal(row(fid).data.state,'ready');
 const release=load('lib/qms-release.ts');sql.prepare("INSERT INTO records(id,kind,payload,created) VALUES('d1','device',?,?)").run(JSON.stringify({code:'SERIAL1',product:'p1'}),now);await release.qmsDispatchGuard('d1','op');const rid=await ok(qa,basic('release',{ownerId:'qa',reviewerId:'qa2',values:{...values('release'),serials:'SERIAL1'}}));await assert.rejects(()=>release.qmsDispatchGuard('d1','op'));await success(qa,rid,'submit');assert.equal((await apply(qa2,rid,'approve')).status,400);
 sql.prepare("INSERT INTO quality_templates(id,product_id,version,title,fields,created,created_by) VALUES('qt','p1',1,'QC','[]',?,'qa')").run(now);sql.prepare('INSERT INTO quality_reports(id,device_id,template_id,"values",verdict,notes,created,created_by) VALUES(?,?,?,?,?,?,?,?)').run('qr','d1','qt','{}','pass','Evidence',now,'qa');await success(qa2,rid,'approve');await release.qmsDispatchGuard('d1','op');sql.prepare("UPDATE quality_reports SET verdict='fail' WHERE id='qr'").run();await assert.rejects(()=>release.qmsDispatchGuard('d1','op'));sql.prepare("UPDATE quality_reports SET verdict='pass' WHERE id='qr'").run();const dispatchOp=crypto.randomUUID(),dispatchCheck=await release.qmsDispatchGuard('d1',dispatchOp);await success(qa,rid,'hold');await assert.rejects(()=>release.qmsDispatchGuard('d1','op'));await assert.rejects(()=>db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'test','{}','test',?,1)").bind(dispatchOp,now),dispatchCheck]));assert.equal(sql.prepare('SELECT id FROM inventory_operations WHERE id=?').get(dispatchOp),undefined);
 sql.prepare("UPDATE reset_control SET phase='maintenance',internal=0 WHERE id=1").run();assert.equal((await post(eng,{...basic('design')})).status,423);
 console.log('QMS passed: private design HTTP/MCP/flow/audit/backup, revocation, immutable forms/versions, maker-checker, CAPA, chunk integrity/resume/streaming, release hold, reset preservation/FK rollback and freeze.');
})().catch(e=>{console.error(e);process.exitCode=1});
