const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');const root=path.resolve(__dirname,'..');const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',f),'utf8'));
const db={prepare(q){let args=[];return{bind(...a){args=a;return this},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:{changes:sql.prepare(q).run(...args).changes}}}}},async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const objects=new Map();const bucket={async put(k,b){objects.set(k,b.slice(0));return {key:k}},async get(k){const b=objects.get(k);return b?{arrayBuffer:async()=>b.slice(0)}:null},async delete(k){objects.delete(k)}};
let identity=null;const env={TRACE_OWNER_EMAIL:'owner@example.com',LLM_CONFIG_ENCRYPTION_KEY:require('node:crypto').randomBytes(32).toString('base64'),DB:db,BUCKET:bucket};
const cache={};function load(file){file=path.resolve(root,file);if(cache[file])return cache[file];const exports={};cache[file]=exports;const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
vm.runInNewContext(source,{exports,require:n=>{if(n==='cloudflare:workers')return {env};if(n==='@/app/chatgpt-auth')return {getChatGPTUser:async()=>identity};if(n.startsWith('@/')||n.startsWith('.')){const p=n.startsWith('@/')?path.join(root,n.slice(2)):path.resolve(path.dirname(file),n);return load(p+(path.extname(p)?'':'.ts'));}return require(n)},Response,Request,URL,URLSearchParams,Error,crypto:globalThis.crypto,Date,Intl,Set,Map,FormData,Blob,File,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,AbortController,ReadableStream,btoa,atob,setTimeout:(f,n)=>setTimeout(f,Math.min(n,10)),clearTimeout,console},{filename:file});return exports;}
const context=load('lib/mcp/context.ts').mcpActor,permissions=load('lib/permissions.ts'),sales=load('app/api/sales/route.ts'),quoteApi=load('app/api/sales/quote/route.ts'),files=load('app/api/sales/files/route.ts'),accounts=load('app/api/sales/accounts/route.ts'),fulfillment=load('app/api/fulfillment/route.ts'),transport=load('app/api/transport/route.ts'),catalog=load('lib/mcp/tools.ts');
let tail=Promise.resolve();const batch=db.batch.bind(db);db.batch=stmts=>{const next=tail.then(()=>batch(stmts));tail=next.catch(()=>{});return next;};
const base='https://test.local',today=load('lib/duties.ts').dayAt(),past=load('lib/duties.ts').addDay(today,-20),future=load('lib/duties.ts').addDay(today,20),now=new Date().toISOString();
const request=(path,body,origin=base)=>new Request(base+path,{method:body?'POST':'GET',headers:{origin,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
const actor=(id,roles,extra={})=>({userId:'local:'+id,email:id+'@example.com',name:id,isAdmin:false,permissions:{read:[],write:[],eventStages:[],salesRoles:roles,...extra}});
const admin={...actor('admin',[]),isAdmin:true,permissions:permissions.allPermissions},manager=actor('manager',['manager']),staff=actor('staff',['staff']),finance=actor('finance',['finance']),viewer=actor('viewer',['viewer']),warehouse=actor('warehouse',[],{flowRoles:['inventory'],warehouses:['quarantine','finished']}),driver=actor('driver',[],{transportRoles:['driver']}),transportManager=actor('transport',[],{transportRoles:['manager']});
const member=u=>sql.prepare("INSERT INTO app_members(id,email,name,unit,status,subject,permissions,revision,created,updated) VALUES(?,?,?,'test','active',NULL,?,1,?,?)").run(u.userId.slice(6),u.email,u.name,JSON.stringify(u.permissions),now,now);
const seed=(id,type,data)=>sql.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').run(id,type,JSON.stringify(data),now,now);
const entity=id=>{const r=sql.prepare('SELECT * FROM flow_entities WHERE id=?').get(id);return r?{...r,data:JSON.parse(r.data)}:null;};
const all=type=>sql.prepare('SELECT * FROM flow_entities WHERE type=?').all(type).map(r=>({...r,data:JSON.parse(r.data)}));
async function post(api,path,body,u=admin,status=200){const r=await context.run(u,()=>api.POST(request(path,body)));const d=await r.json();assert.equal(r.status,status,body.mode+': '+JSON.stringify(d));return {...d,body};}
let a,b,rep,other;
const op=(mode,extra={},u=finance,status=200)=>post(sales,'/api/sales',{id:crypto.randomUUID(),mode,agentId:a,confirmed:true,notes:'Verified source',...extra},u,status);
const get=async(u=rep,agent='',status=200)=>{const r=await context.run(u,()=>sales.GET(request('/api/sales'+(agent?'?agent='+agent:''))));assert.equal(r.status,status);return r.json();};
const balance=async()=>((await get()).accounts[0]);
const quote=(qty=3,u=rep)=>post(quoteApi,'/api/sales/quote',{agentId:a,items:[{productId:'product',quantity:qty}]},u);
const version=id=>entity(id).revision;
async function upload(u=rep,extra={},status=201){const meta={id:crypto.randomUUID(),agentId:a,confirmed:true,title:'Evidence',...extra},form=new FormData();form.set('metadata',JSON.stringify(meta));form.set('file',new File(['%PDF-test'],'receipt.pdf'));const r=await context.run(u,()=>files.POST(new Request(base+'/api/sales/files',{method:'POST',headers:{origin:base},body:form})));const d=await r.json();assert.equal(r.status,status,JSON.stringify(d));return {...d,meta};}

const monitor=load('lib/sales-monitor.ts'),monitorApi=load('app/api/sales/monitor/route.ts'),contract=load('lib/sales-monitor-contract.ts'),calendar=load('lib/persian-date.ts');
const config=contract.monitorDefaults;
const nowClock=new Date();
const watch=(mode,extra={},u=manager,status=200)=>post(monitorApi,'/api/sales/monitor',{id:crypto.randomUUID(),mode,confirmed:true,notes:'Verified actual follow-up',...extra},u,status);
async function view(u=manager,query='',status=200){const r=await context.run(u,()=>monitorApi.GET(request('/api/sales/monitor'+query)));assert.equal(r.status,status,await r.clone().text());return r.json();}
(async()=>{
 for(const u of [manager,staff,finance,viewer,warehouse,driver])member(u);
 const create={name:'Representative A',phone:'021123',contact:'Contact A',province:'تهران',city:'تهران',address:'A',active:true,ownerId:'staff',financeId:'finance',managerId:'manager'};
 a=(await op('agent',{...create,agentId:''},manager)).id;b=(await op('agent',{...create,name:'Representative B',agentId:''},manager)).id;
 rep=actor('rep',['agent'],{salesAgentId:a});other=actor('other',['agent'],{salesAgentId:b});member(rep);member(other);
 sql.prepare("INSERT INTO records(id,kind,payload,created) VALUES('product','product',?,?)").run(JSON.stringify({name:'Device',status:'فعال'}),now);
 const old=contract.shiftDay(today,-40),due=contract.shiftDay(today,-35),oldAt=old+'T08:00:00Z';
 seed('invoiceA','sales_invoice',{agentId:a,day:old,reference:'INV-A',amount:'100000',discount:'0',lines:[{productId:'product',name:'Device',quantity:5,net:'100000'}],installments:[{id:'1',due,amount:'100000'}]});
 seed('bouncedA','sales_payment',{agentId:a,method:'check',state:'bounced',day:old,checkDue:due,reference:'CHK-A',bank:'Test bank',amount:'1000',financialEvents:[],history:[]});
 seed('pendingA','sales_payment',{agentId:a,method:'cash',state:'pending',day:old,reference:'PAY-A',amount:'10',history:[]});sql.prepare('UPDATE flow_entities SET updated=? WHERE id=?').run(oldAt,'pendingA');
 const goal=await watch('goal',{agentId:a,title:'Approved goal',start:contract.shiftDay(today,-50),end:contract.shiftDay(today,10),basis:'units',amount:'100',productIds:[]});
 assert.equal(entity(goal.id).data.state,'active');await watch('goal',{agentId:a,title:'Overlap',start:today,end:future,basis:'units',amount:'100',productIds:[]},manager,400);await watch('goal',{agentId:a,title:'Unauthorized',start:today,end:future,basis:'units',amount:'100',productIds:[]},staff,403);
 await watch('configure',{revision:(await monitor.monitorPolicy()).revision,settings:{...config,dailyTime:'00:00'}},manager);
 await monitor.scanSalesMonitor({now:nowClock,source:'background'});
 let data=await view();assert.equal(data.health.backgroundStale,false);assert.ok(data.alerts.some(a=>a.data.kind==='overdue'));assert.ok(data.alerts.some(a=>a.data.kind==='bounced_check'));assert.ok(data.alerts.some(a=>a.data.kind==='goal_gap'));assert.ok(data.alerts.some(a=>a.data.kind==='pending_payment'));assert.ok(data.reports.some(r=>r.kind==='daily'));
 const overdueId='sales-alert:overdue:'+a,checkId='sales-alert:bounced_check:bouncedA',goalId='sales-alert:goal_gap:'+goal.id;
 assert.ok((await view(staff)).alerts.every(a=>a.data.ownerId==='staff'));assert.ok((await view(finance)).alerts.every(a=>a.data.ownerId==='finance'));await view(rep,'',403);await view(viewer,'',403);await view(staff,'?preview=daily',403);
 const archived=data.reports[0],archiveBefore=JSON.stringify(entity(archived.id).data);await view(staff,'?report='+encodeURIComponent(archived.id),403);assert.ok((await view(manager,'?report='+encodeURIComponent(archived.id))).report.data.summary.length);
 const noticeCount=sql.prepare('SELECT count(*) n FROM duty_notices').get().n,reportCount=all('sales_report').length;
 await monitor.scanSalesMonitor({now:nowClock,source:'background'});assert.equal(all('sales_report').length,reportCount);assert.equal(sql.prepare('SELECT count(*) n FROM duty_notices').get().n,noticeCount);
 await watch('followup',{alertId:checkId,revision:version(checkId),nextAction:'Ask finance for cleared replacement'},staff);assert.equal(entity(checkId).data.state,'acknowledged');assert.ok(entity(checkId).data.lastFollowup);await watch('followup',{alertId:checkId,revision:1,nextAction:'Stale'},staff,409);
 await watch('review_goal',{alertId:goalId,revision:version(goalId)},manager,400);await watch('recover_check',{paymentId:'bouncedA',revision:version('bouncedA'),creditId:'pendingA',amount:'1000'},staff,403);
 const creditBody={method:'cash',amount:'1000',day:today,reference:'RECOVERY',requestSource:{channel:'phone',contactName:'A',day:today,reference:'Verified bank receipt'}};
 const credit=await op('payment',creditBody,finance);await watch('recover_check',{paymentId:'bouncedA',revision:version('bouncedA'),creditId:credit.id,amount:'1000'},finance,400);await op('payment_review',{paymentId:credit.id,revision:version(credit.id),approved:true});
 const before=await balance(),recovery=await watch('recover_check',{paymentId:'bouncedA',revision:version('bouncedA'),creditId:credit.id,amount:'1000'},finance);assert.equal(entity(checkId).data.state,'resolved');assert.deepEqual(JSON.stringify(await balance()),JSON.stringify(before));assert.equal((await watch('recover_check',recovery.body,finance)).repeated,true);
 await watch('recover_check',{paymentId:'bouncedA',revision:version('bouncedA'),creditId:credit.id,amount:'1'},finance,400);
 await op('payment_reverse',{paymentId:credit.id,revision:version(credit.id)});assert.equal(entity(checkId).data.state,'open');assert.equal(entity(checkId).data.cycle,2);
 const task=sql.prepare("SELECT * FROM duty_runs WHERE json_extract(data,'$.salesAlertId')=? AND assignee='staff'").get(checkId);assert.ok(task);await post(load('app/api/tasks/route.ts'),'/api/tasks',{id:crypto.randomUUID(),mode:'submit',taskId:task.id,revision:task.revision,note:'A statement does not resolve risk'},staff,400);
 await watch('assign',{alertId:overdueId,revision:version(overdueId),ownerId:'manager',due:new Date(Date.now()+86400000).toISOString()},manager);assert.equal(entity(overdueId).data.ownerId,'manager');assert.ok(!(await view(staff)).alerts.some(a=>a.id===overdueId));

 // Late delivery and physically received returns; mere return requests do not count.
 seed('orderLate','sales_order',{agentId:a,state:'approved',code:'SO-LATE',amount:'100',lines:[{productId:'product',quantity:2}],promisedDay:contract.shiftDay(today,-3),milestone:'preparing',history:[]});
 seed('return1','sales_return',{agentId:a,state:'returned',receivedAt:now,amount:'1',lines:[]});seed('return2','sales_return',{agentId:a,state:'returned',receivedAt:now,amount:'1',lines:[]});seed('return3','sales_return',{agentId:a,state:'requested',amount:'1',lines:[]});
 await monitor.scanSalesMonitor({reports:false});assert.equal(entity('sales-alert:late_delivery:orderLate').data.state,'open');assert.equal(entity('sales-alert:repeat_returns:'+a),null);
 const r3=entity('return3');sql.prepare('UPDATE flow_entities SET data=? WHERE id=?').run(JSON.stringify({...r3.data,state:'returned',receivedAt:now}),'return3');await monitor.scanSalesMonitor({reports:false});assert.ok(entity('sales-alert:repeat_returns:'+a));
 seed('lateShipment','sale',{salesOrderId:'orderLate',salesAgentId:a,productId:'product',count:2,state:'delivered'});await monitor.scanSalesMonitor({reports:false});assert.equal(entity('sales-alert:late_delivery:orderLate').data.state,'resolved');
 const recovery2=await op('payment',{...creditBody,reference:'RECOVERY-2'},finance);await op('payment_review',{paymentId:recovery2.id,revision:version(recovery2.id),approved:true});
 const recoveries=await Promise.all([1,2].map(()=>context.run(finance,()=>monitorApi.POST(request('/api/sales/monitor',{id:crypto.randomUUID(),mode:'recover_check',confirmed:true,paymentId:'bouncedA',revision:version('bouncedA'),creditId:recovery2.id,amount:'600',notes:'Actual partial recovery'})))));assert.equal(recoveries.filter(r=>r.status===200).length,1);assert.equal(contract.checkRecovery(entity('bouncedA'),await load('lib/sales.ts').salesRows()).remaining,'400');
 const overdue=entity('invoiceA');sql.prepare('UPDATE flow_entities SET data=?,revision=revision+1 WHERE id=?').run(JSON.stringify({...overdue.data,amount:'150000',installments:[{id:'1',due,amount:'150000'}]}),'invoiceA');const noticesBeforeWorse=sql.prepare('SELECT count(*) n FROM duty_notices').get().n;await monitor.scanSalesMonitor({reports:false});assert.ok(sql.prepare('SELECT count(*) n FROM duty_notices').get().n>noticesBeforeWorse);assert.ok(entity(overdueId).data.history.some(h=>h.mode==='worsened'));
 const lateClock=new Date(Date.now()+4*86400000);await monitor.scanSalesMonitor({now:lateClock,reports:false});assert.ok(sql.prepare("SELECT id FROM duty_notices WHERE phase LIKE 'escalated:%'").get());
 // Restore amount snapshot for period metrics; no metadata changes the underlying cash ledger.
 sql.prepare('UPDATE flow_entities SET data=?,revision=revision+1 WHERE id=?').run(JSON.stringify(overdue.data),'invoiceA');
 // Independent reports preserve source facts and never count opening/pending payments as fresh revenue.
 const rows=await load('lib/sales.ts').salesRows(),period={start:old,end:today,previousStart:contract.shiftDay(old,-41),previousEnd:contract.shiftDay(old,-1)};
 seed('openingInvoice','sales_invoice',{agentId:a,openingId:'OLD',amount:'999999',day:today,reference:'OPEN',installments:[{id:'1',due:future,amount:'999999'}],lines:[],discount:'0'});
 const report=contract.buildSalesReport('weekly',await load('lib/sales.ts').salesRows(),[],[],[],await monitor.monitorMembers(),new Date(),period);assert.equal(report.current.netSales,'100000');assert.equal(report.current.collections,'1000');assert.equal(report.current.discount,undefined);assert.equal(report.comparisonComplete,false);assert.equal(JSON.stringify(entity(archived.id).data),archiveBefore);
 assert.equal(contract.goalProgress(entity(goal.id),rows,today).actual,'5');assert.ok(!rows.some(r=>r.type==='sales_report'));
 // Persian season and Tehran clock boundaries, weekly Saturday and delayed idempotent windows.
 const farvardin=calendar.solarToIso(1405,1,1),q=contract.reportPeriod('quarterly',farvardin);assert.equal(q.start,calendar.solarToIso(1404,10,1));assert.equal(q.end,calendar.solarToIso(1404,12,29));assert.equal(q.yearAgoEnd,calendar.solarToIso(1403,12,30));
 const saturday='2026-10-10',week=contract.reportPeriod('weekly',saturday);assert.equal(week.start,'2026-10-03');assert.equal(week.end,'2026-10-09');
 const pol={...config,startedDay:saturday};assert.equal(contract.dueReports(new Date(saturday+'T08:29:00+03:30'),pol).length,0);assert.equal(contract.dueReports(new Date(saturday+'T08:30:00+03:30'),pol).length,1);assert.equal(contract.dueReports(new Date(saturday+'T09:00:00+03:30'),pol).length,2);
 // An ended missed goal requires explicit manager review; later source changes reopen it.
 seed('endedGoal','sales_goal',{agentId:b,title:'Ended',state:'active',start:old,end:contract.shiftDay(today,-1),basis:'units',amount:'10',productIds:[],version:1});await monitor.scanSalesMonitor({reports:false});const endedId='sales-alert:goal_gap:endedGoal';await watch('review_goal',{alertId:endedId,revision:version(endedId)},manager);assert.equal(entity(endedId).data.state,'reviewed');await monitor.scanSalesMonitor({reports:false});assert.equal(entity(endedId).data.state,'reviewed');
 seed('invoiceB','sales_invoice',{agentId:b,amount:'50',discount:'0',day:old,reference:'B',lines:[{productId:'product',quantity:1,net:'50'}],installments:[{id:'1',due:future,amount:'50'}]});await monitor.scanSalesMonitor({reports:false});assert.equal(entity(endedId).data.state,'open');
 // Rule edits cannot be done by staff; pause stops scans, acknowledgement never switches it off.
 const pp=await monitor.monitorPolicy();await watch('configure',{revision:pp.revision,settings:{...config,enabled:false}},staff,403);await watch('configure',{revision:pp.revision,settings:{...config,enabled:false}},manager);const paused=(await monitor.scanSalesMonitor());assert.equal(paused.enabled,false);
 await watch('configure',{revision:(await monitor.monitorPolicy()).revision,settings:config},manager);
 const beforeConcurrent=all('sales_report').length,result=await Promise.allSettled([monitor.scanSalesMonitor({source:'background'}),monitor.scanSalesMonitor({source:'background'})]);assert.ok(result.some(r=>r.status==='fulfilled'));assert.ok(all('sales_report').length<=beforeConcurrent+3);assert.equal(new Set(all('sales_report').map(r=>r.id)).size,all('sales_report').length);
 const mcp=await catalog.executeTool('get_sales_monitor',{},base,{user:manager,scope:'read',tokenId:null});assert.ok(mcp.reports.length);await assert.rejects(()=>catalog.executeTool('sales_monitor_apply',{id:crypto.randomUUID(),mode:'scan',confirmed:true,data:{}},base,{user:manager,scope:'read',tokenId:null}),/read-only/);assert.ok((await catalog.executeTool('sales_monitor_apply',{id:crypto.randomUUID(),mode:'scan',confirmed:true,data:{}},base,{user:manager,scope:'read_write',tokenId:null})).saved);
 const reset=load('lib/reset-contract.ts');for(const scope of ['operations','full']){sql.exec('SAVEPOINT monitor_reset');for(const table of Object.keys(reset.resetTables))sql.exec('DELETE FROM '+table+' WHERE '+reset.resetWhere(table,scope));assert.ok(entity(a));for(const id of [goal.id,checkId,archived.id,recovery.id,'sales-monitor-policy'])assert.equal(entity(id),null);assert.equal(sql.prepare('PRAGMA foreign_key_check').all().length,0);sql.exec('ROLLBACK TO monitor_reset');sql.exec('RELEASE monitor_reset');assert.ok(entity(checkId));}
 sql.exec("UPDATE reset_control SET phase='maintenance',internal=0 WHERE id=1");const count=sql.prepare('SELECT count(*) n FROM flow_entities').get().n;await assert.rejects(()=>monitor.scanSalesMonitor(),/RESET_MAINTENANCE/);await watch('followup',{alertId:checkId,revision:version(checkId),nextAction:'Frozen'},manager,423);assert.equal(sql.prepare('SELECT count(*) n FROM flow_entities').get().n,count);
 console.log('Sales monitor passed: Tehran/Persian schedules, immutable report/financial arithmetic, independent goals, scoped roles, deduplicated alerts, actual check recovery/reversal, follow-up vs completion, assignment, pause, MCP, concurrent scans, reset/FK/freeze rollback.');
})().catch(e=>{console.error(e);process.exit(1)});
