const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');const root=path.resolve(__dirname,'..');const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',f),'utf8'));
const db={prepare(q){let args=[];return{bind(...a){args=a;return this},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:{changes:sql.prepare(q).run(...args).changes}}}}},async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const objects=new Map();const bucket={async put(k,b){objects.set(k,b.slice(0));return {key:k}},async get(k){const b=objects.get(k);return b?{arrayBuffer:async()=>b.slice(0)}:null},async delete(k){objects.delete(k)}};
let identity=null;const env={TRACE_OWNER_EMAIL:'owner@example.com',LLM_CONFIG_ENCRYPTION_KEY:require('node:crypto').randomBytes(32).toString('base64'),DB:db,BUCKET:bucket};
const cache={};function load(file){file=path.resolve(root,file);if(cache[file])return cache[file];const exports={};cache[file]=exports;const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
vm.runInNewContext(source,{exports,require:n=>{if(n==='cloudflare:workers')return {env};if(n==='@/app/chatgpt-auth')return {getChatGPTUser:async()=>identity};if(n.startsWith('@/')||n.startsWith('.')){const p=n.startsWith('@/')?path.join(root,n.slice(2)):path.resolve(path.dirname(file),n);return load(p+(path.extname(p)?'':'.ts'));}return require(n)},Response,Request,URL,URLSearchParams,Error,crypto:globalThis.crypto,Date,Intl,Set,Map,FormData,Blob,File,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,AbortController,ReadableStream,btoa,atob,setTimeout:(f,n)=>setTimeout(f,Math.min(n,10)),clearTimeout,console},{filename:file});return exports;}

const ctx=load('lib/mcp/context.ts').mcpActor,api=load('app/api/sales/leads/route.ts'),sales=load('app/api/sales/route.ts'),quoteApi=load('app/api/sales/quote/route.ts'),catalog=load('lib/mcp/tools.ts'),tasks=load('app/api/tasks/route.ts'),scanner=load('lib/sales-lead-tasks.ts'),domain=load('lib/sales-leads.ts'),duties=load('lib/duties.ts');
let tail=Promise.resolve();const batch=db.batch.bind(db);db.batch=stmts=>{const next=tail.then(()=>batch(stmts));tail=next.catch(()=>{});return next};
const base='https://test.local',today=duties.dayAt(),future=duties.addDay(today,2),now=new Date().toISOString();
const req=(path,body,origin=base)=>new Request(base+path,{method:body?'POST':'GET',headers:{origin,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
function actor(id,roles,extra={}){const u={userId:'local:'+id,email:id+'@test.local',name:id,isAdmin:false,permissions:{read:[],write:[],eventStages:[],salesRoles:roles,...extra}};sql.prepare("INSERT INTO app_members(id,email,name,unit,status,subject,permissions,created,updated) VALUES(?,?,?,'sales','active',?,?,?,?)").run(id,u.email,id,u.userId,JSON.stringify(u.permissions),now,now);return u}
const manager=actor('manager',['manager']),alice=actor('alice',['staff']),bob=actor('bob',['staff']),finance=actor('finance',['finance']),external=actor('external',['agent'],{salesAgentId:'agent'});
function seed(id,type,data){sql.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').run(id,type,JSON.stringify(data),now,now)}
const row=id=>{const r=sql.prepare('SELECT * FROM flow_entities WHERE id=?').get(id);return r?{...r,data:JSON.parse(r.data)}:null};
async function get(u,q=''){const r=await ctx.run(u,()=>api.GET(req('/api/sales/leads'+q)));return {status:r.status,data:await r.json()}}
async function post(u,body,route=api,path='/api/sales/leads'){const r=await ctx.run(u,()=>route.POST(req(path,{id:crypto.randomUUID(),confirmed:true,...body})));return {status:r.status,data:await r.json()}}
const fields={mode:'save',revision:0,title:'First opportunity',contactName:'Customer',phone:'۰۹۱۲۱۲۳۴۵۶۷',city:'Tehran',source:'referral',segment:'home',ownerId:'alice',items:[{productId:'product',quantity:2}],interest:'Oxygen device',agentId:'agent',estimatedAmount:'5000',nextAction:'Call customer',nextDue:future,notes:'Actual call request'};
const apply=(u,id,mode,extra={})=>post(u,{leadId:id,revision:row(id).revision,mode,notes:'Actual result',nextAction:'Next call',nextDue:future,...extra});
(async()=>{
 sql.prepare("INSERT INTO records(id,kind,payload,created) VALUES('product','product',?,?)").run(JSON.stringify({name:'Device',model:'P1',status:'فعال'}),now);
 seed('agent','sales_agent',{name:'Customer account',active:true,termDays:0,creditLimit:'0',phone:'02112345678',address:'Address',province:'Tehran',city:'Tehran'});seed('price','sales_price',{agentId:'',productId:'product',unitPrice:'1000',active:true});
 assert.equal((await get(finance)).status,403);assert.equal((await get(external)).status,403);assert.equal((await post(alice,{...fields,ownerId:'bob'})).status,403);assert.equal((await post(alice,{...fields,nextAction:''})).status,400);assert.equal((await post(alice,{...fields,confirmed:false})).status,400);
 const body={...fields,id:crypto.randomUUID()},created=await post(alice,body);assert.equal(created.status,200,JSON.stringify(created));assert.equal(created.data.followupPending,false);const id=created.data.id;
 assert.equal((await post(alice,body)).data.repeated,true);assert.equal((await post(alice,{...body,title:'changed'})).status,409);assert.equal((await get(bob)).data.records.length,0);assert.equal((await get(manager)).data.records.length,1);assert.equal((await apply(bob,id,'activity',{activityType:'call',day:today})).status,404);
 const duplicate=await post(bob,{...fields,ownerId:'bob',phone:'+98 912-123-4567'});assert.equal(duplicate.status,409);assert.ok(!JSON.stringify(duplicate).includes(id));assert.equal((await post(alice,{...fields,leadId:id,revision:0})).status,409);
 const task=sql.prepare("SELECT * FROM duty_runs WHERE template_id='sales-lead' AND state='open'").get();assert.ok(task);assert.equal((await post(alice,{mode:'submit',taskId:task.id,revision:task.revision,note:'note only'},tasks,'/api/tasks')).status,400);
 assert.equal((await apply(alice,id,'activity',{activityType:'call',day:today})).status,200);assert.equal(row(id).data.lastContact.day,today);assert.equal(sql.prepare('SELECT state FROM duty_runs WHERE id=?').get(task.id).state,'open');
 assert.equal((await apply(alice,id,'assign',{ownerId:'bob'})).status,403);assert.equal((await apply(manager,id,'assign',{ownerId:'bob'})).status,200);assert.equal((await get(alice)).data.records.length,0);assert.equal((await get(bob)).data.records.length,1);await assert.rejects(()=>duties.taskAccess(task.id,alice));assert.equal(sql.prepare('SELECT state FROM duty_runs WHERE id=?').get(task.id).state,'cancelled');
 assert.equal((await apply(bob,id,'lose',{lossReason:''})).status,400);assert.equal((await apply(bob,id,'lose',{lossReason:'price'})).status,200);assert.equal((await apply(bob,id,'reopen')).status,403);assert.equal((await apply(manager,id,'reopen')).status,200);
 assert.equal((await apply(bob,id,'stage',{stage:'negotiation'})).status,200);
 const qr=await ctx.run(bob,()=>quoteApi.POST(req('/api/sales/quote',{agentId:'agent',items:fields.items})));assert.equal(qr.status,200);const quote=await qr.json();
 const order={mode:'order',agentId:'agent',items:fields.items,quoteHash:quote.quoteHash,leadId:id,leadRevision:row(id).revision,requestSource:{channel:'phone',contactName:'Customer',day:today,reference:'Call confirmation'},notes:'Customer accepted'};
 assert.equal((await post(alice,order,sales,'/api/sales')).status,404);assert.equal((await post(bob,{...order,quoteHash:'stale'},sales,'/api/sales')).status,409);assert.equal(row(id).data.stage,'negotiation');
 // Forced transaction failure leaves no order, lead transition or operation log.
 sql.exec("CREATE TRIGGER force_order_failure BEFORE INSERT ON flow_entities WHEN NEW.type='sales_order' BEGIN SELECT RAISE(ABORT,'forced rollback'); END;");const failedId=crypto.randomUUID();assert.equal((await post(bob,{...order,id:failedId},sales,'/api/sales')).status,409);assert.equal(row(id).data.stage,'negotiation');assert.equal(sql.prepare('SELECT id FROM inventory_operations WHERE id=?').get(failedId),undefined);sql.exec('DROP TRIGGER force_order_failure');
 const race=await Promise.all([post(bob,order,sales,'/api/sales'),post(bob,order,sales,'/api/sales')]);assert.equal(race.filter(r=>r.status===200).length,1,JSON.stringify(race));const oid=race.find(r=>r.status===200).data.id;assert.equal(row(id).data.orderId,oid);assert.equal(row(oid).data.leadId,id);assert.equal(row(oid).data.amount,'2000');assert.equal(row(id).data.estimatedAmount,'5000');assert.equal((await get(manager)).data.dashboard.conversionRate,100);
 const other=await post(alice,{...fields,phone:'09121111111',segment:'hospital',decisionMaker:'Procurement',tenderDeadline:future});assert.equal(other.status,200);const id2=other.data.id;assert.equal((await apply(alice,id2,'link_order',{orderId:oid})).status,400);
 // Existing-order linkage keeps the same customer/items and is owner-scoped.
 const standalone=await post(alice,{mode:'order',agentId:'agent',items:fields.items,quoteHash:quote.quoteHash,requestSource:order.requestSource},sales,'/api/sales');assert.equal(standalone.status,200,JSON.stringify(standalone));assert.equal((await apply(alice,id2,'link_order',{orderId:standalone.data.id})).status,200);assert.equal(row(standalone.data.id).data.leadId,id2);
 const third=await post(alice,{...fields,phone:'09123333333'});assert.equal(third.status,200);const id3=third.data.id;
 // Detect duplicate creation races after phone normalization, without exposing another owner's data.
 const duplicateRace=await Promise.all([post(alice,{...fields,phone:'09122222222'}),post(bob,{...fields,ownerId:'bob',phone:'00989122222222'})]);assert.equal(duplicateRace.filter(r=>r.status===200).length,1);
 // Overdue follow-ups notify the owner and escalate to the sales manager once per due date.
 const overdueId=duplicateRace.find(r=>r.status===200).data.id;
 sql.prepare("UPDATE flow_entities SET data=json_set(data,'$.nextDue',?),revision=revision+1 WHERE id=?").run(duties.addDay(today,-3),overdueId);
 await scanner.syncLeadTasks();await duties.tickDuties();const overdueTask=sql.prepare("SELECT id FROM duty_runs WHERE template_id='sales-lead' AND period=? AND state='open'").get(overdueId);
 assert.ok(sql.prepare("SELECT id FROM duty_notices WHERE task_id=? AND recipient='manager' AND phase LIKE 'escalate:%'").get(overdueTask.id));const noticeCount=sql.prepare('SELECT COUNT(*) n FROM duty_notices').get().n;await duties.tickDuties();assert.equal(sql.prepare('SELECT COUNT(*) n FROM duty_notices').get().n,noticeCount);
 const mp={user:alice,scope:'read_write',tokenId:null};assert.equal((await catalog.executeTool('get_sales_leads',{leadId:id},base,mp)).records.length,0);await assert.rejects(()=>catalog.executeTool('sales_lead_apply',{id:crypto.randomUUID(),confirmed:true,mode:'lose',leadId:id3,revision:row(id3).revision,lossReason:'other',notes:'No budget'},base,{...mp,scope:'read'}),/read-only/);
 assert.equal((await catalog.executeTool('sales_lead_apply',{id:crypto.randomUUID(),confirmed:true,mode:'lose',leadId:id3,revision:row(id3).revision,lossReason:'other',notes:'No budget'},base,mp)).saved,true);
 // A concurrent owner-permission change is caught by the transaction guard.
 const previousBatch=db.batch,op=crypto.randomUUID(),auditCount=sql.prepare('SELECT COUNT(*) n FROM access_audit').get().n;
 db.batch=async statements=>{db.batch=previousBatch;sql.prepare("UPDATE app_members SET name='Changed Manager' WHERE id='manager'").run();return previousBatch(statements)};
 const staleRole=await post(manager,{id:op,mode:'reopen',leadId:id3,revision:row(id3).revision,ownerId:'alice',nextAction:'Contact again',nextDue:future,notes:'Manager review'});assert.equal(staleRole.status,409);assert.equal(row(id3).data.stage,'lost');assert.equal(sql.prepare('SELECT COUNT(*) n FROM access_audit').get().n,auditCount);
 const report=(await get(manager)).data;assert.equal(report.dashboard.lossReasons.other,1);assert.equal((await get(manager,'?from='+future)).data.records.length,0);
 const csrf=await ctx.run(alice,()=>api.POST(req('/api/sales/leads',fields,'https://other.local')));assert.equal(csrf.status,403);const training=load('lib/training-context.ts').trainingContext;assert.equal((await training.run({actor:alice.userId,role:'sales'},()=>get(alice))).status,403);
 sql.prepare("UPDATE app_members SET permissions=? WHERE id='alice'").run(JSON.stringify({read:[],write:[],eventStages:[]}));assert.equal((await get(alice)).status,403);await scanner.syncLeadTasks();
 sql.prepare("UPDATE reset_control SET phase='maintenance',internal=0 WHERE id=1").run();const before=row(id3).revision;assert.equal((await apply(manager,id3,'reopen',{ownerId:'bob'})).status,423);assert.equal(row(id3).revision,before);assert.equal(sql.prepare('PRAGMA foreign_key_check').all().length,0);
 console.log('Sales leads passed: scoped roles, normalized duplicates and races, required follow-up/loss reason, history, reassignment/task privacy, quote-based atomic order conversion/rollback, dashboard cohorts, MCP, training, revocation and reset freeze.');
})().catch(e=>{console.error(e);process.exit(1)});
