const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');const root=path.resolve(__dirname,'..');const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',f),'utf8'));
const db={prepare(q){let args=[];return{bind(...a){args=a;return this},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:{changes:sql.prepare(q).run(...args).changes}}}}},async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const objects=new Map();const bucket={async put(k,b){objects.set(k,b.slice(0));return {key:k}},async get(k){const b=objects.get(k);return b?{arrayBuffer:async()=>b.slice(0)}:null},async delete(k){objects.delete(k)}};
let identity=null;const env={TRACE_OWNER_EMAIL:'owner@example.com',LLM_CONFIG_ENCRYPTION_KEY:require('node:crypto').randomBytes(32).toString('base64'),DB:db,BUCKET:bucket};
const cache={};function load(file){file=path.resolve(root,file);if(cache[file])return cache[file];const exports={};cache[file]=exports;const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
vm.runInNewContext(source,{exports,require:n=>{if(n==='cloudflare:workers')return {env};if(n==='@/app/chatgpt-auth')return {getChatGPTUser:async()=>identity};if(n.startsWith('@/')||n.startsWith('.')){const p=n.startsWith('@/')?path.join(root,n.slice(2)):path.resolve(path.dirname(file),n);return load(p+(path.extname(p)?'':'.ts'));}return require(n)},Response,Request,URL,URLSearchParams,Error,crypto:globalThis.crypto,Date,Intl,Set,Map,FormData,Blob,File,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,AbortController,ReadableStream,btoa,atob,setTimeout:(f,n)=>setTimeout(f,Math.min(n,10)),clearTimeout,console},{filename:file});return exports;}
const context=load('lib/mcp/context.ts').mcpActor,permissions=load('lib/permissions.ts'),sales=load('app/api/sales/route.ts'),quoteApi=load('app/api/sales/quote/route.ts'),files=load('app/api/sales/files/route.ts'),accounts=load('app/api/sales/accounts/route.ts'),fulfillment=load('app/api/fulfillment/route.ts'),transport=load('app/api/transport/route.ts'),catalog=load('lib/mcp/tools.ts');
let tail=Promise.resolve();const batch=db.batch.bind(db);db.batch=stmts=>{const next=tail.then(()=>batch(stmts));tail=next.catch(()=>{});return next;};
const base='https://test.local',today=load('lib/duties.ts').dayAt(),past=load('lib/duties.ts').addDay(today,-20),future=load('lib/duties.ts').addDay(today,20),now=new Date().toISOString();
const request=(path,body,origin=base)=>new Request(base+path,{method:body?'POST':'GET',headers:{origin,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
const actor=(id,roles,extra={})=>({userId:'local:'+id,email:id+'@example.com',name:id,isAdmin:false,permissions:{read:[],write:[],eventStages:[],salesRoles:roles,...extra}});
const admin={...actor('admin',[]),isAdmin:true,permissions:permissions.allPermissions},manager=actor('manager',['manager']),staff=actor('staff',['staff']),finance=actor('finance',['finance']),viewer=actor('viewer',['viewer']),warehouse=actor('warehouse',[],{flowRoles:['inventory'],warehouses:['quarantine','finished']}),driver=actor('driver',[],{transportRoles:['driver']}),transportManager=actor('transport',[],{transportRoles:['manager']});
const member=u=>sql.prepare("INSERT INTO app_members(id,email,name,unit,status,subject,permissions,revision,created,updated) VALUES(?,?,?,'test','active',NULL,?,1,?,?)").run(u.userId.slice(6),u.email,u.name,JSON.stringify(u.permissions),now,now);
const seed=(id,type,data)=>sql.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').run(id,type,JSON.stringify(data),now,now);
const entity=id=>{const r=sql.prepare('SELECT * FROM flow_entities WHERE id=?').get(id);return r?{...r,data:JSON.parse(r.data)}:null;};
const all=type=>sql.prepare('SELECT * FROM flow_entities WHERE type=?').all(type).map(r=>({...r,data:JSON.parse(r.data)}));
async function post(api,path,body,u=admin,status=200){const r=await context.run(u,()=>api.POST(request(path,body)));const d=await r.json();assert.equal(r.status,status,body.mode+': '+JSON.stringify(d));return {...d,body};}
let a,b,rep,other;
const op=(mode,extra={},u=finance,status=200)=>post(sales,'/api/sales',{id:crypto.randomUUID(),mode,agentId:a,confirmed:true,notes:'Verified source',...extra},u,status);
const get=async(u=rep,agent='',status=200)=>{const r=await context.run(u,()=>sales.GET(request('/api/sales'+(agent?'?agent='+agent:''))));assert.equal(r.status,status);return r.json();};
const balance=async()=>((await get()).accounts[0]);
const quote=(qty=3,u=rep)=>post(quoteApi,'/api/sales/quote',{agentId:a,items:[{productId:'product',quantity:qty}]},u);
const version=id=>entity(id).revision;
async function upload(u=rep,extra={},status=201){const meta={id:crypto.randomUUID(),agentId:a,confirmed:true,title:'Evidence',...extra},form=new FormData();form.set('metadata',JSON.stringify(meta));form.set('file',new File(['%PDF-test'],'receipt.pdf'));const r=await context.run(u,()=>files.POST(new Request(base+'/api/sales/files',{method:'POST',headers:{origin:base},body:form})));const d=await r.json();assert.equal(r.status,status,JSON.stringify(d));return {...d,meta};}
(async()=>{
 for(const u of [manager,staff,finance,viewer,warehouse,driver,transportManager])member(u);
 const create={name:'Rep A',phone:'02112345678',contact:'Sales contact',province:'تهران',city:'تهران',address:'Address',contractRef:'C1',active:true,ownerId:'staff',financeId:'finance'};
 a=(await op('agent',{...create,agentId:''},manager)).id;b=(await op('agent',{...create,name:'SECRET REP B',agentId:''},manager)).id;
 rep=actor('rep',['agent'],{salesAgentId:a});other=actor('other',['agent'],{salesAgentId:b});member(rep);member(other);
 assert.throws(()=>permissions.validatePermissions({...rep.permissions,finance:'read'}));assert.throws(()=>permissions.validatePermissions({...rep.permissions,read:['product']}));assert.throws(()=>permissions.validatePermissions({...rep.permissions,serviceRoles:['manager'],serviceDomains:['home']}));
 await op('terms',{revision:version(a),creditLimit:'100000',termDays:20},manager,403);await op('terms',{revision:version(a),creditLimit:'100000',termDays:20});
 sql.prepare("INSERT INTO records(id,kind,payload,created) VALUES('product','product',?,?)").run(JSON.stringify({name:'Device',model:'N1',code:'P1',status:'فعال'}),now);
 const price=(await op('price',{agentId:'',productId:'product',unitPrice:'1000',active:true,reference:'PRICE1'},manager)).id;
 const target=(await op('target',{title:'Monthly',start:today,end:future,basis:'units',productIds:[],tiers:[{threshold:'2',discountBps:1000},{threshold:'10',discountBps:2000}]},manager)).id;
 await op('target',{title:'Overlap',start:today,end:future,basis:'units',productIds:[],tiers:[{threshold:'2',discountBps:1000}]},manager,400);
 await op('payment',{method:'cash',amount:'1',day:today,reference:'UNCONFIRMED',confirmed:false},rep,400);const wrongOrigin=await context.run(rep,()=>sales.POST(request('/api/sales',{id:crypto.randomUUID(),mode:'payment',agentId:a,confirmed:true,method:'cash',amount:'1',day:today,reference:'ORIGIN'},'https://evil.local')));assert.equal(wrongOrigin.status,403);
 const q=await quote();assert.equal(q.amount,'3000');await op('price',{agentId:'',priceId:price,revision:version(price),productId:'product',unitPrice:'2000',active:true,reference:'PRICE2'},manager);
 await op('order',{items:q.body.items,quoteHash:q.quoteHash},rep,409);await op('price',{agentId:'',priceId:price,revision:version(price),productId:'product',unitPrice:'1000',active:true,reference:'PRICE3'},manager);
 const q1=await quote(),order=await op('order',{items:q1.body.items,quoteHash:q1.quoteHash},rep);assert.equal((await op('order',order.body,rep)).repeated,true);await op('order',{...order.body,notes:'changed'},rep,409);
 await op('order_review',{orderId:order.id,revision:version(order.id),approved:true},rep,403);await op('order_review',{orderId:order.id,revision:version(order.id),approved:true},staff);
 const invoiceBody={orderId:order.id,revision:version(order.id),reference:'INV1',installments:[{due:today,amount:'1000'},{due:future,amount:'2000'}],creditException:false};
 await op('invoice',invoiceBody,staff,403);await op('invoice',{...invoiceBody,installments:[{due:today,amount:'1'}]},finance,400);await op('invoice',invoiceBody);const invoice=entity(order.id).data.invoiceId;
 assert.equal((await balance()).debt,'3000');assert.equal((await quote(2)).amount,'1800');assert.equal(entity(order.id).data.amount,'3000');
 assert.equal((await get()).agents.length,1);assert.ok(!JSON.stringify(await get()).includes('SECRET REP B'));await get(rep,b,404);await op('order_cancel',{agentId:b,orderId:order.id,revision:version(order.id)},rep,404);
 const payment=await op('payment',{method:'cash',amount:'5000',day:today,reference:'REC1',bank:''},rep);assert.equal((await balance()).debt,'3000');assert.equal((await balance()).credit,'0');
 await op('payment',{method:'cash',amount:'5000',day:today,reference:'REC1',bank:''},rep,409);await op('allocate',{creditId:payment.id,allocations:[{invoiceId:invoice,installmentId:'1',amount:'1000'}]},finance,400);
 await op('payment_review',{paymentId:payment.id,revision:version(payment.id),approved:true});assert.equal((await balance()).credit,'5000');assert.equal((await balance()).debt,'3000');
 await op('allocate',{creditId:payment.id,allocations:[{invoiceId:invoice,installmentId:'1',amount:'1001'}]},finance,400);
 const allocation=await op('allocate',{creditId:payment.id,allocations:[{invoiceId:invoice,installmentId:'1',amount:'1000'},{invoiceId:invoice,installmentId:'2',amount:'2000'}]});assert.equal((await op('allocate',allocation.body)).repeated,true);assert.equal((await balance()).debt,'0');assert.equal((await balance()).credit,'2000');
 await op('payment_reverse',{paymentId:payment.id,revision:version(payment.id)});assert.equal((await balance()).debt,'3000');assert.equal((await balance()).credit,'0');
 assert.equal(entity(payment.id).data.financialEvents.reduce((n,e)=>n+BigInt(e.delta),0n),0n);
 const correction=await op('payment',{method:'cash',amount:'4',day:today,reference:'CORRECT'},rep);await op('payment_review',{paymentId:correction.id,revision:version(correction.id),approved:false});await op('payment',{paymentId:correction.id,revision:version(correction.id),method:'cash',amount:'5',day:today,reference:'CORRECT'},rep);assert.equal(entity(correction.id).data.state,'pending');assert.equal(entity(correction.id).data.amount,'5');
 const file=await upload();assert.equal((await upload(rep,file.meta,200)).repeated,true);await upload(other,{},404);let r=await context.run(other,()=>files.GET(request('/api/sales/files?id='+file.id)));assert.equal(r.status,404);r=await context.run(rep,()=>files.GET(request('/api/sales/files?id='+file.id)));assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'application/octet-stream');assert.ok(!JSON.stringify(await get()).includes('objectKey'));
 const check=await op('payment',{method:'check',amount:'1000',day:today,checkDue:today,bank:'Bank',reference:'CH1',fileId:file.id},rep);await op('payment_review',{paymentId:check.id,revision:version(check.id),approved:true});assert.equal((await balance()).uncollectedChecks,'1000');assert.equal((await balance()).credit,'0');await op('check_status',{paymentId:check.id,revision:version(check.id),state:'cleared'});
 const concurrent=await Promise.all([1,2].map(()=>context.run(finance,()=>sales.POST(request('/api/sales',{id:crypto.randomUUID(),mode:'allocate',agentId:a,creditId:check.id,allocations:[{invoiceId:invoice,installmentId:'1',amount:'1000'}],confirmed:true,notes:'Allocate'})))));assert.equal(concurrent.filter(r=>r.status===200).length,1);assert.equal((await balance()).debt,'2000');await op('check_status',{paymentId:check.id,revision:version(check.id),state:'bounced'});assert.equal((await balance()).debt,'3000');
 // Real stock, partial reservation, transport receipt by the scoped destination representative.
 for(let i=1;i<=3;i++){sql.prepare("INSERT INTO records(id,kind,payload,created) VALUES(?,'device',?,?)").run('device'+i,JSON.stringify({code:'SN'+i,product:'product'}),now);seed('device'+i,'build',{state:'finished',receivedAt:now});sql.prepare("INSERT INTO inventory_balances(id,item_id,warehouse,quantity) VALUES(?,?,'finished',1000)").run('device'+i+'@finished','device'+i);}
 const reserve=(count,status=200,u=staff)=>post(fulfillment,'/api/fulfillment',{id:crypto.randomUUID(),mode:'reserve',salesOrderId:order.id,productId:'product',count},u,status);
 await reserve(1,403,rep);const shipment=await reserve(1),shipmentId=shipment.body.id;await reserve(3,400);await reserve(2);assert.equal(all('sale').length,2);assert.equal((await get()).deliveries[0].devices[0].serial,'SN1');
 await post(fulfillment,'/api/fulfillment',{id:crypto.randomUUID(),mode:'dispatch',saleId:shipmentId,deviceIds:['device1'],carrierId:'driver',handedOver:true},warehouse);
 seed('vehicle','transport_vehicle',{name:'Van',plate:'A1',active:true});const move=await post(transport,'/api/transport',{id:crypto.randomUUID(),mode:'create',sourceKey:'sale:'+shipmentId,receiverId:'',route:'direct',due:today,packages:1,pickup:'Factory',destination:'Rep A',recipient:'Rep A',phone:'123',notes:'Delivery'},transportManager);
 const tr=(mode,extra={},u=transportManager,status=200)=>post(transport,'/api/transport',{id:crypto.randomUUID(),mode,missionId:move.id,revision:version(move.id),notes:'Checked',...extra},u,status);
 await tr('assign',{driverId:'driver',vehicleId:'vehicle',due:today});await tr('collect',{packages:1,day:today,condition:'Intact'},driver);await tr('offer',{handoverTo:'Rep A',day:today},driver);await tr('receipt',{packages:1,day:today,result:'complete'},other,404);await tr('receipt',{packages:1,day:today,result:'complete'},rep);assert.equal(entity('device1').data.state,'delivered');assert.equal(entity(shipmentId).data.state,'delivered');
 const ret=await op('return_request',{invoiceId:invoice,deviceIds:['device1']},rep);await op('return_review',{returnId:ret.id,revision:version(ret.id),approved:true},finance,409);await op('return_receive',{returnId:ret.id,revision:version(ret.id),physicallyReceived:true,receipt:'GR1'},staff,403);await op('return_receive',{returnId:ret.id,revision:version(ret.id),physicallyReceived:true,receipt:'GR1'},warehouse);assert.equal(entity('device1').data.state,'sales_return_quarantine');assert.equal(sql.prepare("SELECT quantity FROM inventory_balances WHERE item_id='device1' AND warehouse='quarantine'").get().quantity,1000);await op('return_review',{returnId:ret.id,revision:version(ret.id),approved:true});assert.equal((await balance()).credit,'1000');assert.equal((await get()).targets[0].progress.progress,'2');
 const warehouseView=await get(warehouse);assert.ok(!JSON.stringify(warehouseView).includes('creditLimit'));assert.ok(!JSON.stringify(warehouseView).includes('amount'));assert.equal(warehouseView.returns.length,1);
 // Legacy balances are pending until finance reconciles; unique source-row keys prevent reimport.
 const openingBody={source:'Legacy',reference:'IMPORT1',asOf:today,expectedDebt:'700',expectedCredit:'100',items:[{kind:'invoice',legacyId:'INV-OLD:1',reference:'INV-OLD',day:past,due:past,amount:'700'},{kind:'credit',legacyId:'ADV1',reference:'ADV1',day:past,amount:'100'}]};
 await op('opening',{...openingBody,expectedDebt:'701'},staff,400);const opening=await op('opening',openingBody,staff);assert.equal((await balance()).debt,'3000');await op('opening_review',{openingId:opening.id,revision:version(opening.id),approved:true});assert.equal((await balance()).debt,'3700');assert.equal((await balance()).overdue,'700');assert.equal((await quote(2)).discountBps,0);const duplicate=await op('opening',openingBody,staff);await op('opening_review',{openingId:duplicate.id,revision:version(duplicate.id),approved:true},finance,409);
 const q2=await quote(1),order2=await op('order',{items:q2.body.items,quoteHash:q2.quoteHash},rep);await op('order_review',{orderId:order2.id,revision:version(order2.id),approved:true},staff);await op('invoice',{orderId:order2.id,revision:version(order2.id),reference:'INV2',installments:[{due:future,amount:q2.amount}]},finance,400);await op('invoice',{orderId:order2.id,revision:version(order2.id),reference:'INV2',installments:[{due:future,amount:q2.amount}],creditException:true,exceptionReason:'Authorized credit exception'});
 // Separate account with fixed isolated rights; no secret persisted in payloads/audits.
 const accountBody={id:crypto.randomUUID(),agentId:a,revision:version(a),name:'Rep User',username:'rep.user',password:'test-password-unique',confirmed:true};await post(accounts,'/api/sales/accounts',accountBody,staff,403);await post(accounts,'/api/sales/accounts',{...accountBody,permissions:permissions.allPermissions},manager,400);await post(accounts,'/api/sales/accounts',accountBody,manager,201);await post(accounts,'/api/sales/accounts',{...accountBody,password:'different-on-retry'},manager);const memberPermissions=JSON.parse(sql.prepare('SELECT permissions FROM app_members WHERE id=?').get(accountBody.id).permissions);assert.equal(memberPermissions.salesAgentId,a);assert.equal(memberPermissions.read.length,0);assert.ok(!JSON.stringify(sql.prepare('SELECT * FROM access_audit').all()).includes('test-password-unique'));
 const task=sql.prepare("SELECT * FROM duty_runs WHERE assignee='rep' AND template_id LIKE 'sales:due:%' AND state='open'").get();assert.ok(task);const tasks=load('app/api/tasks/route.ts');await post(tasks,'/api/tasks',{id:crypto.randomUUID(),mode:'submit',taskId:task.id,revision:task.revision,note:'Done'},rep,400);
 const directory=await context.run(rep,()=>load('lib/inbox.ts').inboxDirectory(rep));assert.ok(!directory.people.some(p=>p.id==='other'||p.id==='driver'));assert.equal(directory.positions.length,0);
 const mcpView=await catalog.executeTool('get_sales',{},base,{user:rep,scope:'read',tokenId:null});assert.equal(mcpView.agents.length,1);assert.equal(catalog.tools.find(t=>t.name==='preview_sales_order').write,false);await assert.rejects(()=>catalog.executeTool('sales_apply',{id:crypto.randomUUID(),mode:'payment',agentId:a,confirmed:true,method:'cash',amount:'1',day:today,reference:'MCP'},base,{user:rep,scope:'read',tokenId:null}),/read-only/);
 const mcpPay=await catalog.executeTool('sales_apply',{id:crypto.randomUUID(),mode:'payment',agentId:a,confirmed:true,method:'cash',amount:'1',day:today,reference:'MCP'},base,{user:rep,scope:'read_write',tokenId:null});assert.ok(mcpPay.saved);const mcpQuote=await catalog.executeTool('preview_sales_order',{agentId:a,items:[{productId:'product',quantity:1}]},base,{user:rep,scope:'read',tokenId:null});assert.equal(mcpQuote.amount,'1000');

 // Delegated workflow: a representative needs no login account for sales staff to operate their profile.
 const source={channel:'phone',contactName:'Actual rep contact',day:today,reference:'Call log 104: agreed price, quantity and terms'};
 const c=(await op('agent',{...create,agentId:'',name:'Offline rep',managerId:'manager'},manager)).id;
 assert.equal(sql.prepare("SELECT count(*) n FROM app_members WHERE json_extract(permissions,'$.salesAgentId')=?").get(c).n,0);
 await op('terms',{agentId:c,revision:version(c),creditLimit:'100000',termDays:0});
 const cq=await post(quoteApi,'/api/sales/quote',{agentId:c,items:[{productId:'product',quantity:1}]},staff);
 const cb={agentId:c,items:cq.body.items,quoteHash:cq.quoteHash};await op('order',cb,staff,400);await op('order',{...cb,requestSource:{...source,day:future}},staff,400);
 const co=await op('order',{...cb,requestSource:{...source,actor:'forged-rep'}},staff);
 assert.equal(entity(co.id).data.submission.actor,'local:staff');assert.equal(entity(co.id).data.submission.onBehalf,true);assert.equal(entity(co.id).data.createdBy,'local:staff');
 await op('payment',{agentId:c,method:'cash',amount:'30',day:today,reference:'OFFLINE',requestSource:source},viewer,403);
 const cp=await op('payment',{agentId:c,method:'cash',amount:'30',day:today,reference:'OFFLINE',requestSource:source},staff);
 assert.equal((await get(staff,c)).accounts[0].credit,'0');await op('payment_review',{agentId:c,paymentId:cp.id,revision:version(cp.id),approved:true},staff,403);
 await op('order_review',{agentId:c,orderId:co.id,revision:version(co.id),approved:true},manager);
 await op('invoice',{agentId:c,orderId:co.id,revision:version(co.id),reference:'OFFLINE-INV',installments:[{due:today,amount:cq.amount}]});
 const offlineDue=sql.prepare("SELECT * FROM duty_runs WHERE assignee='staff' AND json_extract(data,'$.salesAgentId')=? AND template_id LIKE 'sales:due:%' AND state='open'").get(c);assert.ok(offlineDue);assert.equal(offlineDue.supervisor,'manager');
 const summary=await get(manager,c);assert.ok(summary.tasks.some(t=>t.assignee==='staff'));assert.ok(summary.tasks.some(t=>t.assignee==='finance'));assert.ok(!JSON.stringify(summary.tasks).includes('answer'));assert.ok((await get(staff,c)).tasks.every(t=>t.assignee==='staff'||t.supervisor==='staff'));assert.ok(!(await get(rep)).tasks.some(t=>t.agentId===c));
 sql.prepare("UPDATE app_members SET status='inactive' WHERE id='staff'").run();await load('lib/sales-tasks.ts').syncSalesTasks();assert.ok(sql.prepare("SELECT id FROM duty_runs WHERE assignee='manager' AND json_extract(data,'$.salesAgentId')=? AND state='open'").get(c));sql.prepare("UPDATE app_members SET status='active' WHERE id='staff'").run();await load('lib/sales-tasks.ts').syncSalesTasks();
 const cqb=await post(quoteApi,'/api/sales/quote',{agentId:c,items:[{productId:'product',quantity:1}]},manager),cancelOrder=await op('order',{agentId:c,items:cqb.body.items,quoteHash:cqb.quoteHash,requestSource:source},manager);await op('order_cancel',{agentId:c,orderId:cancelOrder.id,revision:version(cancelOrder.id),requestSource:source},staff);assert.equal(entity(cancelOrder.id).data.state,'cancelled');
 await op('payment',{method:'cash',amount:'1',day:today,reference:'SPOOF',requestSource:source},rep,400);
 const mcpProxy=await catalog.executeTool('sales_apply',{id:crypto.randomUUID(),mode:'payment',agentId:c,confirmed:true,method:'cash',amount:'2',day:today,reference:'MCP-OFFLINE',requestSource:source},base,{user:staff,scope:'read_write',tokenId:null});assert.equal(entity(mcpProxy.id).data.submission.actor,'local:staff');
 // Finish the remaining two real serials through delegated receipt, with proof and revision-safe retries.
 assert.equal((await get(manager)).pipeline.find(p=>p.orderId===order.id).stage,'partial');
 const shipment2=all('sale').find(s=>s.id!==shipmentId);await post(fulfillment,'/api/fulfillment',{id:crypto.randomUUID(),mode:'dispatch',saleId:shipment2.id,deviceIds:['device2','device3'],carrierId:'driver',handedOver:true},warehouse);
 const move2=await post(transport,'/api/transport',{id:crypto.randomUUID(),mode:'create',sourceKey:'sale:'+shipment2.id,receiverId:'',route:'direct',due:today,packages:2,pickup:'Factory',destination:'Rep A',recipient:'Rep A',phone:'123',notes:'Second shipment'},staff);
 const tr2=(mode,extra={},u=transportManager,status=200)=>post(transport,'/api/transport',{id:crypto.randomUUID(),mode,missionId:move2.id,revision:version(move2.id),notes:'Checked',...extra},u,status);
 await tr2('assign',{driverId:'driver',vehicleId:'vehicle',due:today});await tr2('collect',{packages:2,day:today,condition:'Intact'},driver);await tr2('offer',{handoverTo:'Rep A',day:today},driver);
 const receipt={packages:2,day:today,result:'complete',requestSource:source,confirmed:true};await tr2('receipt',{...receipt,confirmed:false},staff,400);await tr2('receipt',{...receipt,requestSource:undefined},staff,400);await tr2('receipt',receipt,staff,400);await tr2('receipt',receipt,finance,403);await tr2('receipt',receipt,driver,403);await tr2('receipt',receipt,other,404);
 const tf=load('app/api/transport/files/route.ts');
 async function uploadTransport(mission,u,purpose='receipt',expected=version(mission),fileId=crypto.randomUUID(),status=201){const form=new FormData();form.set('file',new File(['%PDF-Actual-test-proof'],'handover.pdf'));const res=await context.run(u,()=>tf.POST(new Request(base+'/api/transport/files?'+new URLSearchParams({mission,purpose,revision:String(expected),requestId:fileId}),{method:'POST',headers:{origin:base},body:form})));const d=await res.json();assert.equal(res.status,status,JSON.stringify(d));return d;}
 await uploadTransport(move2.id,staff,'expense',version(move2.id),crypto.randomUUID(),403);await uploadTransport(move2.id,staff,'receipt',1,crypto.randomUUID(),409);
 const wrong=await uploadTransport(move.id,staff);await tr2('receipt',{...receipt,receiptFileId:wrong.id},staff,400);
 const condition=await uploadTransport(move2.id,staff,'condition');await tr2('receipt',{...receipt,receiptFileId:condition.id},staff,400);
 const baseRevision=version(move2.id),proofId=crypto.randomUUID(),proof=await uploadTransport(move2.id,staff,'receipt',baseRevision,proofId);assert.equal(proof.revision,baseRevision+1);assert.equal((await uploadTransport(move2.id,staff,'receipt',baseRevision,proofId,200)).revision,proof.revision);
 await uploadTransport(move2.id,staff,'condition');assert.equal((await uploadTransport(move2.id,staff,'receipt',baseRevision,proofId,200)).revision,proof.revision);await tr2('receipt',{...receipt,receiptFileId:proof.id,revision:proof.revision},staff,409);
 const sourceSale=entity(shipment2.id);sql.prepare('UPDATE flow_entities SET data=? WHERE id=?').run(JSON.stringify({...sourceSale.data,salesAgentId:b}),sourceSale.id);await tr2('receipt',{...receipt,receiptFileId:proof.id},staff,409);sql.prepare('UPDATE flow_entities SET data=? WHERE id=?').run(JSON.stringify(sourceSale.data),sourceSale.id);
 const mr={id:crypto.randomUUID(),mode:'receipt',revision:version(move2.id),confirmed:true,data:{missionId:move2.id,...receipt,receiptFileId:proof.id,notes:'Actual signed delivery'}};
 assert.ok((await catalog.executeTool('transport_apply',mr,base,{user:staff,scope:'read_write',tokenId:null})).saved);assert.ok((await catalog.executeTool('transport_apply',mr,base,{user:staff,scope:'read_write',tokenId:null})).repeated);
 assert.equal(entity(move2.id).data.receipt.submission.actor,'local:staff');assert.equal(entity(move2.id).data.receipt.submission.agentId,a);assert.equal(entity('device2').data.state,'delivered');assert.equal(sql.prepare("SELECT quantity FROM inventory_balances WHERE item_id='device2' AND warehouse='in_transit'").get().quantity,0);
 assert.equal((await get(staff)).pipeline.find(p=>p.orderId===order.id).stage,'delivered');assert.ok(!sql.prepare("SELECT id FROM duty_runs WHERE template_id=? AND state='open'").get('sales:delivery:'+order.id));
 const staffReturn=await op('return_request',{invoiceId:invoice,deviceIds:['device2'],requestSource:source},staff);assert.equal(entity(staffReturn.id).data.submission.onBehalf,true);assert.equal(entity(staffReturn.id).data.submission.actor,'local:staff');
 const progress=load('lib/sales-contract.ts').salesOrderProgress;assert.equal(progress({...entity(co.id),data:{...entity(co.id).data,promisedDay:past}},[],today).late,true);assert.equal(progress({...entity(cancelOrder.id),data:{...entity(cancelOrder.id).data,promisedDay:past}},[],today).late,false);
 const transportManifest=load('lib/system-reset.ts').resetFiles({flow_entities:[sql.prepare('SELECT * FROM flow_entities WHERE id=?').get(proof.id)]});assert.equal(transportManifest.length,1);
 const records=load('app/api/records/route.ts');const prod=sql.prepare("SELECT payload FROM records WHERE id='product'").get();const dr=await context.run(admin,()=>records.DELETE(new Request(base+'/api/records',{method:'DELETE',headers:{origin:base,'Content-Type':'application/json'},body:JSON.stringify({id:'product',previous:prod.payload,confirmed:true})})));assert.equal(dr.status,409);
 const reset=load('lib/reset-contract.ts'),manifest=load('lib/system-reset.ts').resetFiles({flow_entities:[sql.prepare('SELECT * FROM flow_entities WHERE id=?').get(file.id)]});assert.equal(manifest.length,1);assert.ok(reset.resetFlowPreserved.includes('sales_agent'));assert.ok(reset.resetFlowCatalog.includes('sales_price'));
 for(const scope of ['operations','full']){const before=sql.prepare('SELECT count(*) AS n FROM flow_entities').get().n;sql.exec('SAVEPOINT reset_test');for(const table of Object.keys(reset.resetTables))sql.exec('DELETE FROM '+table+' WHERE '+reset.resetWhere(table,scope));assert.ok(entity(a));assert.equal(entity(c).data.managerId,'manager');assert.equal(entity(co.id),null);assert.equal(entity(proof.id),null);assert.ok(sql.prepare('SELECT id FROM app_members WHERE id=?').get(accountBody.id));assert.equal(entity(invoice),null);assert.equal(entity(target),null);assert.equal(!!entity(price),scope==='operations');assert.equal(sql.prepare('PRAGMA foreign_key_check').all().length,0);sql.exec('ROLLBACK TO reset_test');sql.exec('RELEASE reset_test');assert.equal(sql.prepare('SELECT count(*) AS n FROM flow_entities').get().n,before);}
 sql.exec("UPDATE reset_control SET phase='maintenance',internal=0 WHERE id=1");await op('payment',{method:'cash',amount:'1',day:today,reference:'FROZEN'},rep,423);const filesBefore=objects.size;await upload(rep,{},423);assert.equal(objects.size,filesBefore);sql.exec("UPDATE reset_control SET phase='testing' WHERE id=1");
 const disabled=entity(a);disabled.data.active=false;sql.prepare('UPDATE flow_entities SET data=?,revision=revision+1 WHERE id=?').run(JSON.stringify(disabled.data),a);await get(rep,'',403);
 assert.equal(sql.prepare('PRAGMA foreign_key_check').all().length,0);
 console.log('Sales passed: scoped roles/accounts/files; immutable quotes and target rules; finance approval; pending/cleared/bounced/reversed payments; allocation idempotency/concurrency; real partial stock/transport; physical returns and credits; opening reconciliation/dedup; due tasks; offline representative delegation and actor attribution; scoped task/pipeline reports; evidence-bound staff receipt and stale retry; MCP parity; reset freeze/manifests/FK rollback.');
})().catch(e=>{console.error(e);process.exit(1)});
