const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');const root=path.resolve(__dirname,'..');const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of fs.readdirSync(path.join(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(path.join(root,'drizzle',f),'utf8'));
const db={prepare(q){let args=[];return{bind(...a){args=a;return this},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){if(/^SELECT\b/i.test(q.trim()))return {results:sql.prepare(q).all(...args)};return {meta:{changes:sql.prepare(q).run(...args).changes}}}}},async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const objects=new Map();let failPut=false;
const bucket={async put(k,b){if(failPut)throw Error('R2 unavailable');objects.set(k,typeof b==='string'?new TextEncoder().encode(b):new Uint8Array(b));return {key:k}},async get(k){const b=objects.get(k);return b?{text:async()=>new TextDecoder().decode(b),arrayBuffer:async()=>b.slice().buffer}:null},async delete(k){objects.delete(k)}};
let identity=null;const env={TRACE_OWNER_EMAIL:'owner@example.com',LLM_CONFIG_ENCRYPTION_KEY:require('node:crypto').randomBytes(32).toString('base64'),DB:db,BUCKET:bucket};
let proposedTool='submit_development_request',proposedArgs={},modelPayloads=[];
const cache={};function load(file){file=path.resolve(root,file);if(cache[file])return cache[file];const exports={};cache[file]=exports;const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
vm.runInNewContext(source,{exports,require:n=>{if(n==='cloudflare:workers')return {env};if(n==='@/app/chatgpt-auth')return {getChatGPTUser:async()=>identity};if(n.startsWith('@/')||n.startsWith('.')){const p=n.startsWith('@/')?path.join(root,n.slice(2)):path.resolve(path.dirname(file),n);return load(p+(path.extname(p)?'':'.ts'));}return require(n)},fetch:async(url,options)=>{const body=JSON.parse(options.body);modelPayloads.push(body);return Response.json({choices:[{message:{tool_calls:[{id:'proposal',type:'function',function:{name:proposedTool,arguments:JSON.stringify(proposedArgs)}}]}}]});},Response,Request,URL,URLSearchParams,Error,crypto:globalThis.crypto,Date,Intl,Set,Map,FormData,Blob,File,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,AbortController,ReadableStream,btoa,atob,setTimeout:(f,n)=>setTimeout(f,Math.min(n,10)),clearTimeout,console},{filename:file});return exports;}
const auth=load('lib/authorization.ts'),http=load('app/mcp/route.ts'),sse=load('lib/mcp/sse.ts'),tokens=load('app/api/mcp-tokens/route.ts'),configs=load('app/api/llm-config/route.ts'),secrets=load('lib/llm-secrets.ts'),catalog=load('lib/mcp/tools.ts');
const base='https://test.local';const owner={userId:'owner',email:'owner@example.com',displayName:'Owner',fullName:null};
const request=(path,method='GET',body,headers={})=>new Request(base+path,{method,headers:{origin:base,...(body?{'Content-Type':'application/json'}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});
const rpc=(method,params={},id=1)=>({jsonrpc:'2.0',method,params,id});
let token;
async function call(name,args={},key=token){const r=await http.POST(request('/mcp','POST',rpc('tools/call',{name,arguments:args}),key?{authorization:'Bearer '+key}:{}));assert.equal(r.status,200);const d=await r.json();if(d.result?.isError)return {error:d.result.content[0].text};return JSON.parse(d.result.content[0].text);}
async function mint(scope='read'){return (await (await tokens.POST(request('/api/mcp-tokens','POST',{name:'test',scope,days:1}))).json());}

const api=load('app/api/system-reset/route.ts'),backup=load('app/api/system-reset/backup/route.ts'),ctx=load('lib/mcp/context.ts').mcpActor,contract=load('lib/reset-contract.ts');
const now=new Date().toISOString(),secret='Independent-reset-secret-123',u={userId:'owner',name:'Owner',email:'owner@example.com',isAdmin:true,permissions:load('lib/permissions.ts').allPermissions},staff={...u,userId:'staff',isAdmin:false,permissions:{read:[],write:[],eventStages:[]}};
const run=(who,fn)=>ctx.run(who,fn);
async function get(who=u,scope='operations'){const r=await run(who,()=>api.GET(request('/api/system-reset?scope='+scope)));return {status:r.status,data:await r.json()}}
async function post(body,who=u,headers={}){const r=await run(who,()=>api.POST(request('/api/system-reset','POST',{confirmed:true,...body},headers)));return {status:r.status,data:await r.json()}}
const count=t=>sql.prepare('SELECT COUNT(*) n FROM '+t).get().n;
function seed(id,type,data){sql.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').run(id,type,JSON.stringify(data),now,now)}
function record(id,kind,payload={}){sql.prepare('INSERT INTO records(id,kind,payload,created) VALUES(?,?,?,?)').run(id,kind,JSON.stringify(payload),now)}
function control(){return sql.prepare('SELECT * FROM reset_control').get()}
function restoreTest(){sql.exec("UPDATE reset_control SET phase='testing',job_id=NULL,password_hash=NULL,internal=0,revision=revision+1");sql.exec('DELETE FROM login_attempts');}
let chain=Promise.resolve();const batch=db.batch.bind(db);db.batch=s=>{const p=chain.then(()=>batch(s));chain=p.catch(()=>{});return p};
(async()=>{
 assert.equal((await api.GET(request('/api/system-reset'))).status,401);assert.equal((await get(staff)).status,403);
 assert.equal((await post({mode:'password',password:secret,revision:1},staff)).status,403);
 assert.equal((await post({mode:'password',password:secret,revision:1,confirmed:false})).status,400);
 assert.equal((await post({mode:'password',password:secret,revision:1},{...u},{origin:'https://other.test'})).status,403);
 assert.equal((await post({mode:'password',password:secret,revision:1},u,{'x-assistant-account':'other'})).status,409);
 let r=await post({mode:'password',password:secret,revision:1});assert.equal(r.status,200,JSON.stringify(r));assert.ok(!JSON.stringify((await get()).data).includes(secret));assert.ok(!JSON.stringify((await get()).data).includes('pbkdf2'));
 record('product','product');record('firmware','firmware');record('batch','batch',{code:'LOT'});record('device','device',{code:'SERIAL'});record('event','event');
 seed('replenishment-policy','replenishment_policy',{enabled:true});seed('replenishment-background','workflow_health',{});
 for(const t of ['supplier','supplier_material','supplier_review','supplier_document','supplier_capa'])seed(t,t,{snapshot:'retained evidence'});
 seed('profile:staff','account_profile',{image:'preserved-photo'});
 seed('agent','as_agent',{name:'Agent'});seed('material','material',{code:'PART'});seed('position','position',{name:'Warehouse',members:[]});seed('template','duty_template',{active:true,lastDay:'2026-09-01',startDate:'2026-09-01'});seed('dev','development_request',{title:'Keep this feedback'});seed('case','as_case',{serial:'SERIAL'});seed('vehicle','transport_vehicle',{name:'truck'});seed('party','party',{});seed('flow','build',{});
 sql.prepare("INSERT INTO app_members(id,email,name,unit,status,permissions,created,updated) VALUES('staff','staff@test','Staff','unit','active',?,?,?)").run(JSON.stringify(staff.permissions),now,now);
 sql.prepare("INSERT INTO password_accounts(member_id,username,password_hash,password_ciphertext,must_change) VALUES('staff','staff','HASH-PRESERVED','CIPHER-PRESERVED',1)").run();
 sql.prepare("INSERT INTO password_sessions(hash,member_id,version,expires,created) VALUES('SESSION-SECRET','staff',1,'2099',?)").run(now);
 sql.prepare("INSERT INTO llm_configs(id,name,model,base_url,system_prompt,temperature,max_tokens,token_ciphertext,updated,updated_by) VALUES('llm','model','x','https://example.test','system','0.4',1000,'PROVIDER-SECRET',?,'owner')").run(now);
 sql.prepare("INSERT INTO bom_versions(id,product_id,version,lines,created,actor) VALUES('bom','product',1,'[]',?,'owner')").run(now);
 sql.prepare("INSERT INTO quality_templates(id,product_id,version,title,fields,created,created_by) VALUES('qct','product',1,'QC','[]',?,'owner')").run(now);
 sql.prepare("INSERT INTO quality_reports(id,device_id,template_id,\"values\",verdict,notes,created,created_by) VALUES('qcr','device','qct','{}','pass','',?,'owner')").run(now);
 sql.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES('operation','test','{}','owner',?,1)").run(now);
 sql.prepare("INSERT INTO inventory_entries(id,operation_id,item_id,warehouse,delta) VALUES('entry','operation','batch','raw',1)").run();
 sql.prepare("INSERT INTO production_orders(id,device_id,bom_id,day,operator,notes,actor,created) VALUES('order','device','bom','2026-10-03','A','','owner',?)").run(now);
 sql.prepare("INSERT INTO production_materials(id,order_id,batch_id,warehouse,quantity) VALUES('used','order','batch','line',1)").run();
 sql.prepare("INSERT INTO production_receipts(order_id,operation_id,created) VALUES('order','operation',?)").run(now);
 sql.prepare("INSERT INTO service_lots(id,owner,domain,batch_id,quantity,unit_rial,created) VALUES('lot','agent','home','batch',1,'0',?)").run(now);
 sql.prepare("INSERT INTO service_reservations(id,case_id,line_id,lot_id,quantity) VALUES('reserve','case','line','lot',1)").run();
 const fileBytes=new TextEncoder().encode('FILE_CONTENT'),hash=await load('lib/firmware.ts').sha256(fileBytes.buffer);objects.set('batch-files/file',fileBytes);
 sql.prepare("INSERT INTO batch_files(id,batch_id,object_key,filename,byte_size,sha256,uploaded_at,uploaded_by) VALUES('file','batch','batch-files/file','photo.txt',?,?,?,'owner')").run(fileBytes.length,hash,now);
 let id=crypto.randomUUID();r=await post({mode:'prepare',id,scope:'operations',password:'incorrect-password'});assert.equal(r.status,403);assert.equal(count('records'),5);assert.equal(control().phase,'testing');
 failPut=true;r=await post({mode:'prepare',id,scope:'operations',password:secret});assert.equal(r.status,409);assert.equal(count('records'),5);assert.equal(control().phase,'testing');assert.equal(sql.prepare('SELECT state FROM reset_jobs WHERE id=?').get(id).state,'failed');failPut=false;
 id=crypto.randomUUID();r=await post({mode:'prepare',id,scope:'operations',password:secret});assert.equal(r.status,200,JSON.stringify(r));let job=r.data.job;assert.equal(job.state,'ready');assert.equal(control().phase,'maintenance');assert.equal(count('records'),5,'prepare never deletes');
 assert.throws(()=>sql.exec("UPDATE flow_entities SET data='{}' WHERE id='replenishment-policy'"),/RESET_MAINTENANCE/);
 for(const t of ['supplier','supplier_material','supplier_review','supplier_document','supplier_capa'])assert.throws(()=>sql.prepare("UPDATE flow_entities SET data='{}' WHERE id=?").run(t),/RESET_MAINTENANCE/);
 assert.throws(()=>record('concurrent','device'),/RESET_MAINTENANCE/);assert.throws(()=>sql.exec("UPDATE records SET payload='{}' WHERE id='batch'"),/RESET_MAINTENANCE/);assert.throws(()=>sql.exec("DELETE FROM quality_reports"),/RESET_MAINTENANCE/);
 assert.equal((await post({mode:'prepare',id,scope:'operations',password:secret})).data.job.id,id);
 assert.equal((await post({mode:'execute',id,password:secret,confirmationCode:job.confirmationCode,backupAcknowledged:true})).status,400,'backup must be downloaded');
 let br=await run(staff,()=>backup.GET(request('/api/system-reset/backup?id='+id)));assert.equal(br.status,403);
 br=await run(u,()=>backup.GET(request('/api/system-reset/backup?id='+id)));assert.equal(br.status,200);const snapshot=JSON.parse(await br.text());assert.ok(!JSON.stringify(snapshot).includes('CIPHER-PRESERVED'));assert.ok(!JSON.stringify(snapshot).includes('HASH-PRESERVED'));assert.ok(snapshot.tables.flow_entities.some(e=>e.id==='replenishment-policy'));assert.ok(snapshot.tables.flow_entities.some(e=>e.id==='replenishment-background'));assert.equal(snapshot.tables.records.length,3);assert.equal(snapshot.files.length,1);assert.ok(!JSON.stringify(snapshot).includes('PROVIDER-SECRET'));assert.ok(!JSON.stringify(snapshot).includes('SESSION-SECRET'));assert.equal(snapshot.preservedTemplateState.length,1);
 assert.equal((await post({mode:'execute',id,password:secret,confirmationCode:'WRONG',backupAcknowledged:true})).status,400);assert.equal(count('records'),5);
 r=await post({mode:'cancel',id});assert.equal(r.status,200);assert.equal(control().phase,'testing');assert.equal(count('records'),5);assert.equal((await post({mode:'execute',id,password:secret,confirmationCode:job.confirmationCode,backupAcknowledged:true})).status,409);
 // Expiry rejects execution, not silently unfreezing data; any admin can cancel an abandoned preview.
 id=crypto.randomUUID();job=(await post({mode:'prepare',id,scope:'operations',password:secret})).data.job;sql.prepare("UPDATE reset_jobs SET expires='2000' WHERE id=?").run(id);assert.equal((await post({mode:'execute',id,password:secret,confirmationCode:job.confirmationCode,backupAcknowledged:true})).status,409);await post({mode:'cancel',id},{...u,userId:'second-admin'});assert.equal(control().phase,'testing');
 // New prepare captures records added after cancel; competing prepares never release the winner's freeze.
 record('another','device');const ids=[crypto.randomUUID(),crypto.randomUUID()];const racers=await Promise.all(ids.map(id=>post({mode:'prepare',id,scope:'operations',password:secret})));assert.equal(racers.filter(r=>r.status===200).length,1);id=control().job_id;job=(await get()).data.jobs.find(j=>j.id===id);assert.equal(job.summary.counts.find(x=>x.table==='records').count,4);
 await run(u,()=>backup.GET(request('/api/system-reset/backup?id='+id)));
 const jobRecord=sql.prepare('SELECT * FROM reset_jobs WHERE id=?').get(id),bytes=objects.get(jobRecord.backup_key);objects.set(jobRecord.backup_key,new TextEncoder().encode('{}'));
 assert.equal((await post({mode:'execute',id,password:secret,confirmationCode:job.confirmationCode,backupAcknowledged:true})).status,503);assert.equal(count('records'),6);objects.set(jobRecord.backup_key,bytes);
 // Force an error midway through delete: the whole DB batch must roll back, retaining the lock and data.
 sql.exec("CREATE TRIGGER test_rollback BEFORE DELETE ON records BEGIN SELECT RAISE(ABORT,'forced rollback'); END;");r=await post({mode:'execute',id,password:secret,confirmationCode:job.confirmationCode,backupAcknowledged:true});assert.equal(r.status,409);assert.equal(count('batch_files'),1);assert.equal(count('production_materials'),1);assert.equal(control().internal,0);assert.equal(control().phase,'maintenance');sql.exec('DROP TRIGGER test_rollback');
 const finalBody={mode:'execute',id,password:secret,confirmationCode:job.confirmationCode,backupAcknowledged:true};const finals=await Promise.all([post(finalBody),post(finalBody)]);assert.ok(finals.some(r=>r.status===200));assert.equal(control().phase,'live');assert.equal(control().internal,0);assert.equal(control().password_hash,null);assert.equal(count('records'),2);assert.equal(count('bom_versions'),1);assert.equal(count('quality_templates'),1);assert.equal(count('service_reservations'),0);assert.equal(count('production_orders'),0);assert.equal(count('password_sessions'),0);assert.equal(count('password_accounts'),1);assert.equal(count('llm_configs'),1);assert.equal(sql.prepare("SELECT COUNT(*) n FROM flow_entities WHERE type IN ('replenishment_policy','workflow_health')").get().n,0);
 for(const t of ['supplier','supplier_material','supplier_review','supplier_document','supplier_capa'])assert.ok(sql.prepare('SELECT id FROM flow_entities WHERE id=?').get(t));
 assert.equal(JSON.parse(sql.prepare("SELECT data FROM flow_entities WHERE id='template'").get().data).active,false);assert.ok(sql.prepare("SELECT id FROM flow_entities WHERE id='dev'").get());assert.ok(sql.prepare("SELECT id FROM flow_entities WHERE id='agent'").get());assert.ok(sql.prepare("SELECT id FROM flow_entities WHERE id='profile:staff'").get());assert.equal((await post(finalBody)).data.repeated,true);assert.equal((await post({mode:'prepare',id:crypto.randomUUID(),scope:'full',password:secret})).status,409);
 br=await run(u,()=>backup.GET(request('/api/system-reset/backup?id='+id+'&file=0')));assert.equal(br.status,200);assert.equal(await br.text(),'FILE_CONTENT');assert.equal((await run(u,()=>backup.GET(request('/api/system-reset/backup?id='+id+'&file=999')))).status,400);
 assert.ok(!JSON.stringify(sql.prepare('SELECT * FROM access_audit').all()).includes(secret));assert.ok(!JSON.stringify(sql.prepare('SELECT * FROM reset_jobs').all()).includes(secret));
 // Test-only re-arm for the other scope; app offers no way to undo go-live.
 restoreTest();await post({mode:'password',revision:control().revision,password:secret});id=crypto.randomUUID();job=(await post({mode:'prepare',id,scope:'full',password:secret})).data.job;await run(u,()=>backup.GET(request('/api/system-reset/backup?id='+id)));r=await post({mode:'execute',id,password:secret,confirmationCode:job.confirmationCode,backupAcknowledged:true});assert.equal(r.status,200,JSON.stringify(r));assert.equal(count('records'),0);assert.equal(count('quality_templates'),0);assert.equal(count('bom_versions'),0);assert.equal(sql.prepare("SELECT COUNT(*) n FROM flow_entities WHERE type IN ('supplier','supplier_material','supplier_review','supplier_document','supplier_capa','material','party','transport_vehicle')").get().n,0);assert.ok(sql.prepare("SELECT id FROM flow_entities WHERE id='agent'").get());assert.ok(sql.prepare("SELECT id FROM flow_entities WHERE id='profile:staff'").get());
 const p={user:staff,scope:'read_write',tokenId:null};await assert.rejects(()=>catalog.executeTool('get_system_reset_status',{},base,p),/Administrator/);await assert.rejects(()=>catalog.executeTool('execute_system_reset',{id,password:secret,confirmationCode:job.confirmationCode,backupAcknowledged:true,confirmed:true},base,{...p,user:u,scope:'read'}),/read-only/);
 const policy=load('lib/assistant-policy.ts');for(const n of ['set_system_reset_password','prepare_system_reset','execute_system_reset','cancel_system_reset'])assert.equal(policy.assistantWriteNames.has(n),false);
 assert.equal(policy.canOpenSection(staff,'system-reset'),false);assert.equal(policy.canOpenSection(u,'system-reset'),true);
 restoreTest();await post({mode:'password',revision:control().revision,password:secret});for(let i=0;i<5;i++)assert.equal((await post({mode:'prepare',id:crypto.randomUUID(),scope:'full',password:'incorrect-secret'})).status,403);assert.equal((await post({mode:'prepare',id:crypto.randomUUID(),scope:'full',password:secret})).status,429);
 assert.equal(sql.prepare('PRAGMA foreign_key_check').all().length,0);
 const keptPassword=sql.prepare("SELECT password_hash,password_ciphertext,must_change FROM password_accounts WHERE member_id='staff'").get();assert.equal(keptPassword.password_hash,'HASH-PRESERVED');assert.equal(keptPassword.password_ciphertext,'CIPHER-PRESERVED');assert.equal(keptPassword.must_change,1);
 console.log('System reset passed: explicit admin/secret/backup/confirmation, origin/account protection, no delete on prepare or R2 failure, frozen concurrent writes, expiry/cancel, corrupted backup rejection, atomic rollback, concurrent execute once, both scopes, preserved accounts/settings/feedback/agent IDs, paused templates, cleared sessions, archived file access, go-live lock, rate limits, MCP roles and secret-free assistant.');
})().catch(e=>{console.error(e);process.exit(1)});
