import * as afterSales from '@/app/api/after-sales/route';
import * as serviceFiles from '@/app/api/after-sales/files/route';
import * as servicePrint from '@/app/api/after-sales/print/route';
import {serviceForms,serviceWorkflowHelp} from '@/lib/after-sales-contract';
import {serviceActions,serviceRoles,serviceDomains} from '@/lib/after-sales-labels';
import * as assistantProfiles from '@/app/api/assistant/profiles/route';
import * as llmTest from '@/app/api/llm-config/test/route';
import * as assistantActions from '@/app/api/assistant/actions/route';
import * as sourcing from '@/app/api/sourcing/route';
import * as duties from '@/app/api/tasks/route';
import * as dutyTick from '@/app/api/tasks/tick/route';
import * as dutyFiles from '@/app/api/tasks/files/route';
import * as fulfillment from '@/app/api/fulfillment/route';
import * as flow from '@/app/api/flow/route';
import * as assistant from "@/app/api/assistant/route";
import * as production from "@/app/api/production/route";
import * as records from '@/app/api/records/route';
import * as serials from '@/app/api/serials/route';
import * as printing from '@/app/api/serials/print/route';
import * as batches from '@/app/api/batch-suggestion/route';
import * as batchFiles from '@/app/api/batch-files/route';
import * as distribution from '@/app/api/distribution/route';
import * as firmware from '@/app/api/firmware/route';
import * as firmwareFiles from '@/app/api/firmware/files/route';
import * as templates from '@/app/api/quality/templates/route';
import * as reports from '@/app/api/quality/reports/route';
import * as qualityFiles from '@/app/api/quality/files/route';
import * as finance from '@/app/api/finance/route';
import * as financeFiles from '@/app/api/finance/files/route';
import * as analytics from '@/app/api/device-analytics/route';
import * as users from '@/app/api/users/route';
import * as llm from '@/app/api/llm-config/route';
import {fields,editable,adminBatchEditable,type Kind} from '@/lib/model';
import {financeReports} from '@/lib/finance-control';
import {can,AccessError} from '@/lib/authorization';
import {mcpActor} from './context';
import type {McpPrincipal} from './auth';
import {storage} from '@/lib/storage';
import {presets} from '@/lib/permissions';

type Schema=Record<string,any>;
const text=(description='',maxLength=4000):Schema=>({type:'string',description,maxLength});
const enumeration=(values:string[]):Schema=>({type:'string',enum:values});
const obj=(properties:Record<string,Schema>,required=Object.keys(properties)):Schema=>({type:'object',properties,required,additionalProperties:false});
const list=(items:Schema,maxItems=500):Schema=>({type:'array',items,maxItems});
const integer=(minimum:number,maximum:number):Schema=>({type:'integer',minimum,maximum});
const id=text('Record ID (not a serial number).',200);
const data:Schema={type:'object',additionalProperties:text(),maxProperties:80,description:'Field-name/string-value map. Call get_record_schema for required fields, options, references and editable fields. Dates: Gregorian YYYY-MM-DD; numeric values as strings.'};
const confirmed={type:'boolean',const:true,description:'True only after the user has approved these exact changes.'};
const payload=(extra:Record<string,Schema>)=>obj({...extra,confirmed});
const kinds=['product','batch','device','event','service','action','distribution','firmware'];
const period={cadence:enumeration(['daily','weekly']),period:text('Gregorian YYYY-MM-DD. Weekly periods start on Saturday.',10)};
const perms=obj({serviceRoles:list(enumeration(Object.keys(serviceRoles)),9),serviceDomains:list(enumeration(Object.keys(serviceDomains)),2),serviceAgentId:text('Organization ID for agent-only account; no broad company permissions.',200),supplyRoles:list(enumeration(['sales','ceo','engineering','inventory','finance','domestic','foreign']),7),warehouses:list(enumeration(['raw','line','quarantine','nonconforming','finished']),5),flowRoles:list(enumeration(['inventory','qc','production','procurement','sales','logistics']),6),read:list(enumeration(kinds),8),write:list(enumeration(kinds),8),eventStages:list(enumeration(['مصرف قطعه','مونتاژ','آزمون نهایی','بسته‌بندی','تحویل']),5),finance:enumeration(['none','read','write'])},['read','write','eventStages']);
const member={email:text('',254),name:text('',100),unit:text('Organizational unit. Commerce: بازرگانی — داخلی or بازرگانی — خارجی; explicit permissions are separate.',100),status:enumeration(['active','disabled']),permissions:perms};
const config={id,revision:integer(0,1e9),name:text('',100),model:text('',160),baseUrl:text('HTTPS provider base URL. No request is sent when saving.',1000),systemPrompt:text('',16000),temperature:{type:'number',minimum:0,maximum:2},maxTokens:integer(1,131072),apiToken:text('Optional replacement secret; never returned. Blank preserves saved secret.',4096),clearToken:{type:'boolean'}};
type Tool={name:string;description:string;inputSchema:Schema;write:boolean;admin?:boolean;kind?:Kind;finance?:boolean;run:(a:any,origin:string,p:McpPrincipal)=>Promise<unknown>};
export const tools:Tool[]=[];
const add=(t:Tool)=>tools.push(t);
function argsValid(s:Schema,v:any):boolean{
 if(s.const!==undefined&&v!==s.const)return false;if(s.enum&&!s.enum.includes(v))return false;
 if(s.type==='object'){if(!v||typeof v!=='object'||Array.isArray(v))return false;if(s.maxProperties&&Object.keys(v).length>s.maxProperties)return false;if((s.required||[]).some((k:string)=>!(k in v)))return false;return Object.entries(v).every(([k,x])=>s.properties?.[k]?argsValid(s.properties[k],x):s.additionalProperties===false?false:typeof s.additionalProperties==='object'?argsValid(s.additionalProperties,x):true);}
 if(s.type==='array')return Array.isArray(v)&&v.length<=(s.maxItems??Infinity)&&v.every(x=>argsValid(s.items,x));
 if(s.type==='string')return typeof v==='string'&&v.length<=(s.maxLength??Infinity);
 if(s.type==='boolean')return typeof v==='boolean';
 if(s.type==='integer'||s.type==='number')return typeof v==='number'&&Number.isFinite(v)&&(s.type!=='integer'||Number.isInteger(v))&&v>=(s.minimum??-Infinity)&&v<=(s.maximum??Infinity);
 return false;
}
function req(origin:string,path:string,method='GET',body?:unknown,query:Record<string,unknown>={}){const u=new URL(path,origin);for(const [k,v]of Object.entries(query))if(v!==undefined&&v!==null)u.searchParams.set(k,String(v));return new Request(u,{method,headers:method==='GET'?{}:{origin,'Content-Type':'application/json'},...(method==='GET'?{}:{body:body===undefined?undefined:JSON.stringify(body)})});}
async function result(r:Response){if(!r.ok){let message='Operation failed.';try{message=(await r.json() as any).error||message;}catch{}throw new AccessError(message,r.status);}return r.headers.get('content-type')?.includes('application/json')?r.json():{html:await r.text()};}
function api(name:string,description:string,inputSchema:Schema,path:string,method:string,handler:(request:Request)=>Promise<Response>,options:Partial<Tool>={},queryKeys:string[]=[],body?:(a:any)=>unknown){
 add({name,description,inputSchema,write:method!=='GET',...options,run:async(a,o)=>{
  const requestBody=body?body(a):Object.fromEntries(Object.entries(a).filter(([k])=>k!=='confirmed'&&!queryKeys.includes(k)));
  const query=Object.fromEntries(queryKeys.map(k=>[k,a[k]]));
  return result(await handler(req(o,path,method,requestBody,query)));
 }});
}
add({name:'get_session',description:'Current authenticated account and effective permissions. All MCP data is real company data, never demo data.',inputSchema:obj({}),write:false,run:async(_a,_o,p)=>p.user});
add({name:'get_record_schema',description:'Field definitions, required fields, allowed options, relationships and editable fields for a record type.',inputSchema:obj({kind:enumeration(kinds)}),write:false,run:async a=>({fields:fields[a.kind as Kind],editable:editable[a.kind as Kind]||[],adminEditable:a.kind==="batch"?adminBatchEditable:editable[a.kind as Kind]||[],notes:'Device model snapshots are derived from product. Only use existing IDs. Distribution and firmware have dedicated tools.'})});
add({name:'list_records',description:'Search visible company records. Returns pagination, total and exact previous payload for optimistic updates. No demo records.',inputSchema:obj({kind:enumeration(kinds),query:text('',200),offset:integer(0,1000000),limit:integer(1,200)},[]),write:false,run:async a=>{const r=await result(await records.GET()) as any;const rows=r.records.filter((r:any)=>(!a.kind||r.kind===a.kind)&&(!a.query||JSON.stringify(r.data).toLowerCase().includes(a.query.toLowerCase())));const offset=a.offset||0,limit=a.limit||50;return {total:rows.length,offset,nextOffset:offset+limit<rows.length?offset+limit:null,records:rows.slice(offset,offset+limit).map((r:any)=>({...r,previous:JSON.stringify(r.data)}))};}});
add({name:'get_device_passport',description:'Find one exact device serial and its visible production, component batch, service, action and distribution records. Quality reports/files use their own tools.',kind:'device',inputSchema:obj({serial:text('',160)}),write:false,run:async a=>{const r=await result(await records.GET()) as any;const normal=(s:string)=>s.replace(/[۰-۹]/g,c=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(c))).replace(/[٠-٩]/g,c=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(c))).trim().toUpperCase();const d=r.records.find((v:any)=>v.kind==='device'&&normal(v.data.code)===normal(a.serial));if(!d)throw new AccessError('Device not found in accessible records.',404);const related=r.records.filter((v:any)=>v.data.device===d.id),batchIds=new Set(related.flatMap((v:any)=>[v.data.batch,v.data.replacement]).filter(Boolean));return {device:d,related,batches:r.records.filter((v:any)=>v.kind==='batch'&&batchIds.has(v.id)),product:r.records.find((v:any)=>v.id===d.data.product)||null};}});
api('create_record','Create a product, batch, device, production event (including batch consumption), service report or corrective action. Ask for approval first; do not retry blindly after a timeout.',payload({kind:enumeration(kinds.slice(0,6)),data}),'/api/records','POST',records.POST);
api('update_record','Update allowed fields of a product, batch, service report or corrective action. Supply full data and exact previous from list_records; identity fields cannot change.',payload({id,data,previous:text('Exact JSON data string returned by list_records.',100000)}),'/api/records','PATCH',records.PATCH);
api('delete_record','Admin-only deletion of an unused product or batch without attachments, QC templates or reserved serials. Exact previous and explicit user confirmation required; referenced records cannot be deleted.',payload({id,previous:text('Exact previous record data JSON.',100000)}),'/api/records','DELETE',records.DELETE,{admin:true},[],a=>a);
api('suggest_batch_number','Suggest a meaningful batch number; suggestion does not reserve it.',obj({partCode:text('',12),date:text('Gregorian YYYY-MM-DD',10)}),'/api/batch-suggestion','GET',batches.GET,{kind:'batch'},['partCode','date']);
api('list_serial_runs','List production serial runs, or details of one run.',obj({id},[]),'/api/serials','GET',serials.GET,{kind:'device'},['id']);
api('generate_serials','Reserve serials for a product. Reuse the same UUID requestId for safe retry.',payload({requestId:id,productId:id,count:integer(1,100)}),'/api/serials','POST',serials.POST,{kind:'device'});
api('print_serials','Return printable HTML for a serial run (A4 or thermal); does not operate a physical printer.',obj({id,layout:enumeration(['a4','thermal']),label:enumeration(['large','small'])},['id','layout']),'/api/serials/print','GET',printing.GET,{kind:'device'},['id','layout','label']);
api('device_analytics','Daily production and warranty activation counts; activation only when permitted. Dates are Gregorian; client may aggregate into Jalali months.',obj({}),'/api/device-analytics','GET',analytics.GET,{kind:'device'});
api('distribution_history','Distribution edit history and first warranty-code issue date for a device.',obj({device:id}),'/api/distribution','GET',distribution.GET,{kind:'distribution'},['device']);
api('save_distribution','Assign representative/end customer to a serial. previous is exact prior data JSON (empty for new); reason required for changes.',payload({data,previous:text('',100000),reason:text('',500)}),'/api/distribution','POST',distribution.POST,{kind:'distribution'},[],a=>({mode:'manual',data:a.data,previous:a.previous,reason:a.reason}));
const importRows=list(obj({row:integer(1,1000000),data}),500);
api('preview_distribution_import','Validate parsed Excel rows before import. Requires the same distribution-write permission as the UI.',obj({rows:importRows}),'/api/distribution','POST',distribution.POST,{kind:'distribution',write:false},[],a=>({mode:'preview',rows:a.rows}));
api('import_distribution','Import up to 25 previously previewed rows. Review per-row errors; partial success is possible.',payload({rows:list(obj({row:integer(1,1000000),data}),25),filename:text('',180)}),'/api/distribution','POST',distribution.POST,{kind:'distribution'},[],a=>({mode:'import',rows:a.rows,filename:a.filename}));
api('list_firmware','List firmware versions and HEX attachment metadata.',obj({}),'/api/firmware','GET',firmware.GET,{kind:'firmware'});
api('create_firmware','Create firmware version metadata. Upload Intel HEX using upload_firmware_file.',payload({name:text('',160),version:text('',160),deviceModel:text('',160),board:text('',160),notes:text()}),'/api/firmware','POST',firmware.POST,{kind:'firmware'});
api('list_quality_templates','Get quality form versions for a product or a device. Supply exactly one of product/device.',obj({product:id,device:id},[]),'/api/quality/templates','GET',templates.GET,{},['product','device']);
const qfield=obj({key:text('',40),label:text('',120),type:enumeration(['number','text','result']),unit:text('',40),min:text('',40),max:text('',40),required:{type:'boolean'}});
api('create_quality_template','Create a new version of a product quality form, preserving previous versions.',payload({productId:id,title:text('',160),fields:list(qfield,40),previousVersion:integer(0,1e9)}),'/api/quality/templates','POST',templates.POST,{kind:'product'});
api('list_quality_reports','Read device quality reports and their form versions.',obj({device:id}),'/api/quality/reports','GET',reports.GET,{},['device']);
api('record_quality_report','Record measured values, verdict and notes; also creates the final-test event. Requires QC-stage permission. Reuse requestId for retries.',payload({requestId:id,deviceId:id,templateId:id,values:data,verdict:enumeration(['pass','fail']),notes:text(),cause:enumeration(['part','assembly','design','test','unknown'])}),'/api/quality/reports','POST',reports.POST);
add({name:'finance_report_catalog',description:'Daily/weekly financial report requirements and purpose.',inputSchema:obj({}),write:false,finance:true,run:async()=>financeReports});
api('get_finance_period','List report files and review results/questions/answers/closures for a day or week.',obj(period),'/api/finance','GET',finance.GET,{finance:true},['cadence','period']);
api('add_finance_note','Append review result, question, answer or closure. Questions need responsible; answers/closures need parent_id. Reuse id for retries.',obj({...period,id,report_id:text('',80),kind:enumeration(['result','question','answer','closure']),body:text('',5000),responsible:text('',150),parent_id:id,confirmed},['cadence','period','id','report_id','kind','body','confirmed']),'/api/finance','POST',finance.POST,{finance:true},['cadence','period']);
add({name:'get_user_creation_guide',description:'Admin: account fields, permission presets and role labels. Ask one question at a time; position does not grant permissions. Never request passwords in chat; the assistant confirmation card collects the password privately.',inputSchema:obj({}),write:false,admin:true,run:async()=>({fields:['name','username','unit','status','permissions'],presets,serviceRoles,serviceDomains,notes:'Ask explicitly for access scope; suggest a least-privilege preset for approval. Commerce needs domestic or foreign unit. Agent accounts need exact organization and domain. New accounts are staff, not administrators. Password is entered in the secure confirmation field, never chat.'})});
api('list_users','List app accounts and permissions. Admin only.',obj({}),'/api/users','GET',users.GET,{admin:true});
api('create_user','Create an account with explicit permissions. Admin only; confirm the email and grants.',payload(member),'/api/users','POST',users.POST,{admin:true});
api('update_user','Change account status or permissions using current revision. Cannot change email. Admin only.',payload({...member,id,revision:integer(1,1e9)}),'/api/users','PATCH',users.PATCH,{admin:true});
api('list_llm_configs','List saved LLM profiles. Secrets are never returned. These settings do not change the MCP client model.',obj({}),'/api/llm-config','GET',llm.GET,{admin:true});
api('save_llm_config','Create/update LLM settings. revision=0 for new UUID. API token encrypted and write-only; changing destination requires token replacement/removal.',obj({...config,confirmed},Object.keys(config).filter(k=>!['apiToken','clearToken'].includes(k)).concat('confirmed')),'/api/llm-config','PUT',llm.PUT,{admin:true});
api('delete_llm_config','Delete a saved LLM profile using its current revision.',payload({id,revision:integer(1,1e9)}),'/api/llm-config','DELETE',llm.DELETE,{admin:true},['id','revision']);

add({name:'get_after_sales_contract',description:'Required first: after-sales workflow, input forms, units, warranty, finance and evidence rules. Input fields refer to after_sales_apply.data; operation mode is top-level.',inputSchema:obj({}),write:false,run:async()=>({forms:serviceForms,actions:serviceActions,roles:serviceRoles,domains:serviceDomains,help:serviceWorkflowHelp})});
api('get_after_sales','Scoped service workspace. Read exact case to get revision, evidence, available next steps and installed lots. Agent accounts see only their own organization. Optional agent reads its financial ledger; serial filters cases.',obj({domain:enumeration(['home','hospital']),case:id,agent:id,serial:text('',160)},['domain']),'/api/after-sales','GET',afterSales.GET,{},['domain','case','agent','serial']);
api('get_after_sales_report','Scoped after-sales aggregates by inclusive contact-date range: parts/batch faults, technicians, agents, delivery duration and rating response counts. Counts are not failure rates or causal employee rankings.',obj({domain:enumeration(['home','hospital']),from:text('YYYY-MM-DD',10),to:text('YYYY-MM-DD',10)}),'/api/after-sales?report=1','GET',afterSales.GET,{},['domain','from','to']);
api('after_sales_apply','Apply one approved after-sales action through the UI handler. Get contract and current entity first. data contains mode-specific form fields plus caseId/orderId/shipmentId/claimId/agentId/tariffId where applicable. New entities use revision 0. Existing entities require current revision. No bank transfer or SMS is performed.',payload({id,domain:enumeration(['home','hospital']),mode:enumeration(Object.keys(serviceActions).filter(k=>k!=='activation_preview')),revision:integer(0,1e9),data:{type:'object',additionalProperties:true,maxProperties:40}}),'/api/after-sales','POST',afterSales.POST,{},[],a=>({...a.data,mode:a.mode,id:a.id,domain:a.domain,revision:a.revision}));
api('preview_service_activations','Validate legacy activation rows without writing. Native/imported conflicts are blocked, never silently overwritten. CSV/XLSX must first be parsed into rows.',obj({domain:enumeration(['home','hospital']),source:text('',500),rows:list(obj({serial:text('',160),day:text('Gregorian YYYY-MM-DD',10),months:integer(1,120)}),200)}),'/api/after-sales','POST',afterSales.POST,{write:false},[],a=>({...a,mode:'activation_preview',id:crypto.randomUUID()}));
api('print_service_document','Return receipt (two copies), internal service invoice or six-month part-warranty HTML; format text returns warranty message without sending SMS. Does not operate a printer.',obj({case:id,kind:enumeration(['receipt','invoice','warranty']),format:enumeration(['html','text'])},['case','kind']),'/api/after-sales/print','GET',servicePrint.GET,{},['case','kind','format']);
// File transport: base64 upload, metadata lists, and bounded chunk downloads.
const groups:{name:string;path:string;route:{GET:(r:Request)=>Promise<Response>;POST:(r:Request)=>Promise<Response>};keys:Record<string,Schema>;kind?:Kind;finance?:boolean}[]=[{name:'service',path:'/api/after-sales/files',route:serviceFiles,keys:{case:id}},{name:'task',path:'/api/tasks/files',route:dutyFiles,keys:{task:id}},{name:'batch',path:'/api/batch-files',route:batchFiles,keys:{batch:id},kind:'batch' as Kind},{name:'quality',path:'/api/quality/files',route:qualityFiles,keys:{report:id}},{name:'finance',path:'/api/finance/files',route:financeFiles,keys:{...period,report:text('',80)},finance:true},{name:'firmware',path:'/api/firmware/files',route:firmwareFiles,keys:{version:id},kind:'firmware' as Kind}];
for(const g of groups){
 const queryKeys=Object.keys(g.keys);
 if(g.name!=='firmware'&&g.name!=='service')api('list_'+g.name+'_files','List authorized attachment metadata.',obj(g.keys),g.path,'GET',g.route.GET,{kind:g.kind,finance:g.finance},queryKeys);
 add({name:'upload_'+g.name+'_file',description:'Upload one file as base64; original file validators and limits apply (HEX 10 MiB, other files 20 MiB). No remote URL fetching. Reuse requestId for retries where supported.',inputSchema:payload({...g.keys,...(g.name==='service'?{purpose:enumeration(['before','intake','diagnosis','after','delivery','other'])}:{}),...(g.name==='firmware'?{}:{requestId:id}),filename:text('',180),base64:text('Standard base64 file bytes, without data URL prefix.',28*1024*1024)}),write:true,kind:g.kind,finance:g.finance,run:async(a,o)=>{if(!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(a.base64))throw new AccessError('Invalid base64.',400);const decoded=atob(a.base64);if(decoded.length>20*1024*1024)throw new AccessError('File too large.',413);const bytes=Uint8Array.from(decoded,c=>c.charCodeAt(0)),form=new FormData();form.append('file',new Blob([bytes],{type:'application/octet-stream'}),a.filename);const u=new URL(g.path,o);for(const k of [...queryKeys,'requestId',...(g.name==='service'?['purpose']:[])])if(a[k])u.searchParams.set(k,a[k]);return result(await g.route.POST(new Request(u,{method:'POST',headers:{origin:o},body:form})));}});
 add({name:'download_'+g.name+'_file',description:'Read an attachment in base64 chunks (at most 64 KiB). Use nextOffset until null. Original permissions and integrity checks apply.',inputSchema:obj({...g.keys,...(g.name==='firmware'?{}:{id}),offset:integer(0,25*1024*1024),length:integer(1,65536)},[...queryKeys,...(g.name==='firmware'?[]:['id'])]),write:false,kind:g.kind,finance:g.finance,run:async(a,o)=>{const r=await g.route.GET(req(o,g.path,'GET',undefined,Object.fromEntries([...queryKeys,'id'].map(k=>[k,a[k]]))));if(!r.ok)return result(r);const bytes=new Uint8Array(await r.arrayBuffer()),offset=a.offset||0,end=Math.min(bytes.length,offset+(a.length||65536));if(offset>bytes.length)throw new AccessError('Offset exceeds file length.',400);return {base64:btoa(String.fromCharCode(...bytes.slice(offset,end))),offset,nextOffset:end<bytes.length?end:null,totalBytes:bytes.length,contentDisposition:r.headers.get('content-disposition')};}});
}
export function validateToolArguments(name:string,args:unknown){const t=tools.find(t=>t.name===name);return !!t&&argsValid(t.inputSchema,args);}
export function discoverTools(){return tools.map(t=>({name:t.name,description:t.description,inputSchema:t.inputSchema,annotations:{readOnlyHint:!t.write,destructiveHint:t.write,idempotentHint:!t.write,openWorldHint:false}}));}
export async function executeTool(name:string,args:unknown,origin:string,p:McpPrincipal){
 const t=tools.find(t=>t.name===name);if(!t)throw new AccessError('Unknown tool.',404);if(!argsValid(t.inputSchema,args))throw new AccessError('Arguments do not match the tool schema.',400);
 if(t.write&&p.scope==='read')throw new AccessError('This reference token is read-only.',403);
 if(t.admin&&!p.user.isAdmin)throw new AccessError('Administrator access required.',403);
 if(t.kind&&!can(p.user,t.kind,t.write?'write':'read'))throw new AccessError('Module permission denied.',403);
 if(t.finance&&!p.user.isAdmin&&!(t.write?p.user.permissions.finance==='write':['read','write'].includes(p.user.permissions.finance||'')))throw new AccessError('Finance permission denied.',403);
 let outcome='failed';try{const data=await mcpActor.run(p.user,()=>t.run(args,origin,p));outcome='succeeded';return data;}finally{
 // Domain mutations already write their atomic audit rows. Never log arguments or secrets here.
 try{await storage().prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),p.user.userId,name,'mcp_call',JSON.stringify({outcome,tokenId:p.tokenId}),new Date().toISOString()).run();}catch{console.error('MCP audit write failed');}
 }
}

api('get_production_inventory','Read permitted BOM versions, production sheets and warehouse balances. Quantities in balances/materials are thousandths of units.',obj({}),'/api/production','GET',production.GET);
api('save_product_bom','Save a versioned bill of materials for ONE device. Quantities are decimal strings (up to 3 decimal places).',payload({id,productId:id,previousVersion:integer(0,100000),lines:list(obj({partCode:text('',12),name:text('',200),unit:enumeration(['عدد','کیلوگرم','متر','لیتر']),quantity:text('',20)}),40)}),'/api/production','POST',production.POST,{},[],a=>({...a,mode:'bom'}));
api('initialize_batch_stock','Admin: establish physically verified remaining stock ONCE per batch. Does not assume original receipt quantity is remaining stock.',payload({id,batchId:id,quantity:text('',20),to:enumeration(['raw','line','quarantine','nonconforming'])}),'/api/production','POST',production.POST,{admin:true},[],a=>({...a,mode:'opening'}));
api('move_batch_stock','Move batch stock between material warehouses. Negative stock forbidden. Reuse request UUID when retrying.',payload({id,batchId:id,quantity:text('',20),from:enumeration(['raw','line','quarantine','nonconforming']),to:enumeration(['raw','line','quarantine','nonconforming'])}),'/api/production','POST',production.POST,{},[],a=>({...a,mode:'move'}));
api('create_production_sheet','Create one device production sheet with frozen BOM and selected batches, without deducting stock. One batch per BOM line.',payload({id,deviceId:id,bomId:id,day:text('',10),operator:text('',200),notes:text(),allocations:list(obj({partCode:text('',12),batchId:id,warehouse:enumeration(['raw','line'])}),40)}),'/api/production','POST',production.POST,{},[],a=>({...a,mode:'order'}));
api('transfer_finished_device','Atomically deduct BOM materials and receive one device into finished warehouse. Each sheet transfers once; insufficient stock rolls back all changes.',payload({id,orderId:id}),'/api/production','POST',production.POST,{},[],a=>({...a,mode:'finish'}));

api('create_password_user','Admin: create a local username/password account without ChatGPT email. Password is never returned or logged. Confirm exact permissions.',payload({username:text('',40),password:text('10–128 characters; never reuse secrets in other tools.',128),name:text('',100),unit:text('Organizational unit. Commerce: بازرگانی — داخلی or بازرگانی — خارجی; explicit permissions are separate.',100),status:enumeration(['active','disabled']),permissions:perms}),'/api/users','POST',users.POST,{admin:true});
api('update_password_user','Admin: update a local account or reset its password. Blank password preserves it; reset invalidates old sessions. Exact revision required.',payload({id,revision:integer(1,1e9),password:text('',128),name:text('',100),unit:text('Organizational unit. Commerce: بازرگانی — داخلی or بازرگانی — خارجی; explicit permissions are separate.',100),status:enumeration(['active','disabled']),permissions:perms}),'/api/users','PATCH',users.PATCH,{admin:true});

api('get_assistant_chat','List available model names and the current user’s saved chat history. Provider secrets are never returned.',obj({}),'/api/assistant','GET',assistant.GET);
api('ask_assistant','Send a message to the configured external model (may incur provider cost). The assistant reads authorized records, asks for missing fields and stages proposed changes; no changes execute until decide_assistant_action confirms the exact saved proposal. Reuse requestId on retry.',obj({requestId:id,profileId:id,message:text('',4000)}),'/api/assistant','POST',assistant.POST,{write:false});

api('get_material_flow','Read authorized material master data, quarantine/QC tasks, locations, requests, daily serial plans, builds, repair history and replenishment alerts. Stock quantities are in thousandths.',obj({}),'/api/flow','GET',flow.GET);
const flowPost=(name:string,description:string,mode:string,properties:Record<string,Schema>)=>api(name,description,payload({id,...properties}),'/api/flow','POST',flow.POST,{},[],a=>({...a,mode}));
flowPost('save_material_master','Create/update material master and incoming QC form. Receipt snapshots preserve prior forms. Roles inventory/admin. Revision 0 for new.', 'material',{code:text('',12),name:text('',200),unit:enumeration(['عدد','کیلوگرم','متر','لیتر']),specs:text(),defaultLocation:text('',100),reorderPoint:text('',20),targetStock:text('',20),fields:list(qfield,40),qcOwner:text('',100),warehouseOwner:text('',100),procurementOwner:text('',100),revision:integer(0,1e9)});
flowPost('receive_material_batch','Receive a NEW lot into quarantine with a generated meaningful batch code. Does not copy previous QC decisions or lot-specific attachments.', 'receipt',{materialId:id,day:text('',10),quantity:text('',20),supplier:text('',200),maker:text('',200),manufacturerLot:text('',200),purchase:text('',200),specs:text(),notes:text(),expiry:text('',10)});
flowPost('inspect_incoming_batch','Record immutable incoming QC measurements and accepted/rejected quantities totaling receipt quantity. Assigned QC/admin only.', 'incoming_qc',{receiptId:id,accepted:text('',20),rejected:text('',20),values:data,notes:text()});
flowPost('shelve_approved_batch','Warehouse approval moves accepted quantity only from quarantine to raw stock and assigns empty aisle-rack-level-bin location.', 'shelve',{receiptId:id,location:text('',100)});
flowPost('request_production_material','Request materials for a production plan (planId may be blank). Does not move stock.', 'request',{materialId:id,quantity:text('',20),planId:text('',200),notes:text()});
flowPost('issue_production_material','Approve full request using one/multiple batch-location allocations, raw to line. FEFO/FIFO exception needs technical reason. Negative stock prohibited.', 'issue',{requestId:id,allocations:list(obj({batchId:id,location:text('',100),quantity:text('',20)}),40),reason:text()});
flowPost('request_replenishment','Warehouse confirms or edits proposed procurement quantity. Only one open request per material; includes specification snapshot.', 'supply',{materialId:id,quantity:text('',20),notes:text()});
flowPost('close_replenishment','Assigned procurement officer records outcome and closes request. Does not manufacture a goods receipt.', 'supply_close',{supplyId:id,result:text()});
flowPost('set_daily_capacity','Configure per-product daily capacity and small labels per serial; no serials are generated until a plan is confirmed.', 'capacity',{productId:id,capacity:integer(1,100),smallLabels:integer(0,20),revision:integer(0,1e9)});
flowPost('create_daily_production_plan','Reserve today’s serials and create device/build records atomically. Pins BOM and QC template. Over-capacity requires reason. Does not operate physical printer.', 'plan',{productId:id,count:integer(1,100),design:text('',200),firmware:text('',200),reason:text()});
flowPost('assign_serial_assembler','Assign selected planned serials to assembler. Reassignment requires reason and retains history.', 'assign',{deviceIds:list(id,100),assembler:text('',200),reason:text()});
flowPost('finalize_material_consumption','After prepare_device_materials and passed final QC, finalize a serial production sheet; immediately consumes actual quantities from line stock. Supports multiple lots per BOM part; deviations require notes. No finished-goods receipt.', 'build',{deviceId:id,allocations:list(obj({batchId:id,quantity:text('',20)}),80),notes:text()});
flowPost('reject_line_material','Move unused rejected components from line stock to nonconforming stock with reason.', 'reject',{batchId:id,quantity:text('',20),reason:text()});
flowPost('replace_installed_component','Record removal of installed batch to nonconforming and consume replacement batch from line; preserve cause and require a fresh final QC test.', 'repair',{deviceId:id,oldBatchId:id,newBatchId:id,quantity:text('',20),cause:enumeration(['part','assembly','design','test','unknown']),reason:text()});
flowPost('record_serial_print','Record serial print/reprint intent for daily plan without generating new serials. Use print_serials to obtain printable HTML.', 'print',{planId:id,notes:text()});

// Optional additions preserve compatibility with earlier clients.
const qcTool=tools.find(t=>t.name==='record_quality_report')!;qcTool.inputSchema.required=qcTool.inputSchema.required.filter((k:string)=>k!=='cause');

api('decide_assistant_action','Confirm or cancel an immutable proposed assistant action owned by this account. Read its exact args in get_assistant_chat first. Confirm only after explicit user approval. Repeated confirmation never executes twice.',obj({id,decision:enumeration(['confirm','cancel']),confirmed,password:text('Only for creating a password account. Supply securely at confirmation; never place in chat or proposal.',128)},['id','decision','confirmed']),'/api/assistant/actions','POST',assistantActions.POST,{},[],a=>a);

api('test_llm_connection','Admin: list models from a saved provider profile or probe Chat Completions tool calling. Probe may incur provider cost; confirmed must be true. Does not change saved settings or company data.',obj({id,mode:enumeration(['models','probe']),confirmed}),'/api/llm-config/test','POST',llmTest.POST,{admin:true,write:false},[],a=>a);

api('list_assistant_profiles','List saved model names for the signed-in account independently of chat history/actions storage. Never returns provider keys.',obj({}),'/api/assistant/profiles','GET',assistantProfiles.GET);

flowPost('prepare_device_materials','Record actual installed batch allocations before final QC without deducting materials. Any edit invalidates QC. Oldest line batches are preferred; deviations require notes.', 'prepare',{deviceId:id,allocations:list(obj({batchId:id,quantity:text('',20)}),80),notes:text()});
api('get_fulfillment','Read authorized finished-goods, printed line serial candidates, handoff inbox, sales reservations, recipients and assigned transport inbox.',obj({}),'/api/fulfillment','GET',fulfillment.GET);
const fulfillmentPost=(name:string,description:string,mode:string,properties:Record<string,Schema>)=>api(name,description,payload({id,...properties}),'/api/fulfillment','POST',fulfillment.POST,{},[],a=>({...a,mode}));
fulfillmentPost('save_sales_recipient','Sales: create/edit agent, representative or branch. Blank partyId creates; edits need exact revision.', 'party',{partyId:text('',200),revision:integer(0,1e9),name:text('',200),kind:enumeration(['agent','representative','branch']),phone:text('',50),address:text('',2000),active:{type:'boolean'}});
fulfillmentPost('request_finished_handoff','Production: select printed serials still in line, with finalized production and passed QC. Confirm physical packaging; creates warehouse inbox, no stock receipt.', 'handoff',{deviceIds:list(id,100),packaged:{type:'boolean',const:true},notes:text()});
fulfillmentPost('receive_finished_handoff','Assigned finished-goods warehouse officer receives selected pending serials, supports partial receipt with reason. Does not consume materials again.', 'receive',{handoffId:id,deviceIds:list(id,100),notes:text()});
fulfillmentPost('cancel_finished_handoff','Production: return selected still-pending handoff serials to line for correction, reason required. Received serials cannot be returned here.', 'cancel_handoff',{handoffId:id,deviceIds:list(id,100),notes:text()});
fulfillmentPost('reserve_finished_sale','Sales: reserve available same-model serials for recipient. Empty deviceIds automatically selects oldest received free devices. Count must match. No warehouse exit.', 'reserve',{partyId:id,productId:id,count:integer(1,100),deviceIds:list(id,100),notes:text()});
fulfillmentPost('cancel_finished_sale','Sales: cancel an unshipped reservation and free its serials, with reason.', 'cancel_sale',{saleId:id,reason:text()});
fulfillmentPost('dispatch_finished_sale','Assigned finished warehouse officer: verify serials and physical handover to active logistics account. Swap only available same-model serials with reason. Moves finished to in_transit once, not customer delivery or warranty activation.', 'dispatch',{saleId:id,deviceIds:list(id,100),carrierId:id,handedOver:{type:'boolean',const:true},reason:text(),receiptReference:text('',300)});
fulfillmentPost('acknowledge_transport_receipt','Only assigned logistics recipient (or admin) confirms custody of dispatched devices. Does not confirm destination delivery or warranty activation.', 'acknowledge',{saleId:id,notes:text()});

api('get_task_inbox','Read own assigned/supervised duties, own position job descriptions and private notifications. Admin can manage position and recurring templates; assignment never grants financial/inventory permissions.',obj({}),'/api/tasks','GET',async request=>{const r=await duties.GET(request);if(!r.ok)return r;const d:any=await r.json();d.definitions=d.definitions.map((x:any)=>({id:x.id,type:x.type,revision:x.revision,name:x.data.name,title:x.data.title,positionId:x.data.positionId,active:x.data.active}));d.catalogHint='Use get_position_programs to read exact position and template fields before editing.';return Response.json(d);});
api('get_position_programs','List visible position summaries when positionId is blank, or read exact job description and editable program definitions for one position. Admin sees all; staff only their positions. Read this before save_position or save_duty_template.',obj({positionId:text('Blank to list; exact position ID for detail.',200)}),'/api/tasks','GET',request=>{const u=new URL(request.url);u.searchParams.set('view','positions');u.searchParams.set('position',u.searchParams.get('positionId')||'');return duties.GET(new Request(u));},{},['positionId']);
api('run_task_scheduler','Install the requested draft position starter once for admin, then run due generation and in-app reminders with deduplication. No LLM calls. Server clock/Tehran calendar only. Rate limited to once per minute.',payload({}),'/api/tasks/tick','POST',dutyTick.POST,{admin:true});
const dutyPost=(name:string,description:string,mode:string,properties:Record<string,Schema>,admin=false,optional:string[]=[])=>{const schema=payload({id,...properties});schema.required=schema.required.filter((k:string)=>!optional.includes(k));api(name,description,schema,'/api/tasks','POST',duties.POST,{admin},[],a=>({...a,mode}));};
dutyPost('install_duty_starter','Admin: install the requested 16 positions and 64 editable paused task templates once. Preserves existing edits and accounts; no assignment or active duty is created.','install_starter',{},true);
dutyPost('save_position','Admin: define organizational position, active members and independent reviewer. Blank definitionId creates. Edits need revision. Existing task owners stay unchanged.', 'position',{definitionId:text('',200),revision:integer(0,1e9),name:text('',200),unit:text('',200),members:list(id,20),supervisor:text('Blank means administrators.',200),active:{type:'boolean'},mission:text('Purpose; omitted preserves existing value.',8000),responsibilities:text('Job responsibilities.',8000),authorityBoundaries:text('Authority and separation of duties.',8000),reportingTo:text('Suggested reporting role, not a permission grant.',8000),handoffs:text('Inputs and outputs with other roles.',8000),metrics:text('Suggested measures; no automatic employee rating.',8000)},true,['mission','responsibilities','authorityBoundaries','reportingTo','handoffs','metrics']);
dutyPost('save_duty_template','Admin: recurring duty with explicit instructions, evidence and reviewer approval. Daily weekdays are JS 0 Sunday through 6 Saturday; monthly day is Persian/Jalali with clamp to final day. Start date Gregorian, time Tehran. Enabling a paused template requires a start date today or later, clears catch-up cursor and does not alter existing instances.', 'template',{definitionId:text('',200),revision:integer(0,1e9),positionId:id,title:text('',200),instructions:text('',12000),cadence:enumeration(['once','daily','weekly','monthly']),evidence:enumeration(['text','file']),startDate:text('',10),time:text('',5),weekdays:list(integer(0,6),7),weekday:integer(0,6),monthDay:integer(1,31),remindHours:integer(4,168),escalateHours:integer(1,720),sourceSection:enumeration(['','after-sales','finance-control','fulfillment','flow','inventory','product','sourcing']),active:{type:'boolean'}},true);
for(const mode of ['answer','submit','blocked','request_extension','approve','return','cancel'])dutyPost('task_'+mode,'Duty '+mode+': owner responds; reviewer/admin approves or returns. Exact revision and note required. File-evidence submission requires uploaded file. No inventory or accounting mutation.',mode,{taskId:id,revision:integer(1,1e9),note:text('',12000)});
dutyPost('task_extend','Reviewer/admin: grant new future deadline in Tehran with reason. Requesting an extension does not change deadline.','extend',{taskId:id,revision:integer(1,1e9),note:text('',12000),newDue:text('YYYY-MM-DDTHH:mm:00+03:30',40)});
dutyPost('task_reassign','Admin explicitly transfers an existing duty; retains audit and evidence, resets response and requires fresh evidence.','reassign',{taskId:id,revision:integer(1,1e9),note:text('',12000),assignee:id},true);
dutyPost('read_task_notice','Mark only own notification as read; does not complete task.','read_notice',{noticeId:id});


api('get_sourcing_plan','List production/sourcing case summaries with blank planId; use exact ID for frozen BOM, stock coverage, route quotes, approved purchase, receipts and work inbox. Role-based quote redaction.',obj({planId:text('Blank for index, exact ID for detail.',200)}),'/api/sourcing','GET',r=>{const u=new URL(r.url);u.searchParams.set('id',u.searchParams.get('planId')||'');return sourcing.GET(new Request(u));},{},['planId']);
const supplyPost=(name:string,description:string,mode:string,properties:Record<string,Schema>)=>api(name,description,payload({id,...properties}),'/api/sourcing','POST',sourcing.POST,{},[],a=>({...a,mode}));
const supplyCase={planId:id,revision:integer(1,1e9)};
supplyPost('create_sourcing_plan','Sales: request production from forecast or customer order. With forecastId, consume its unallocated forecast quantity without creating duplicate material demand. Dates Gregorian.', 'create',{productId:id,count:integer(1,100000),needBy:text('',10),origin:enumeration(['forecast','customer']),reference:text('',500),notes:text(),forecastId:text('Blank for independent request.',200)});
supplyPost('approve_sourcing_plan','CEO: approve quantity/deadline and freeze current BOM. Missing BOM routes to engineering. Not a payment authorization.', 'approve',{...supplyCase,count:integer(1,100000),needBy:text('',10),notes:text()});
supplyPost('reject_sourcing_plan','CEO: reject a pending production request with reason.', 'reject',{...supplyCase,notes:text()});
supplyPost('attach_sourcing_bom','Engineering: attach an existing version belonging to this product to a waiting-BOM case. Later master BOM edits never rewrite this snapshot.', 'bom',{...supplyCase,bomId:id,notes:text()});
supplyPost('set_material_sourcing_routes','Engineering: allowable quote routes per material. Both means parallel RFQs for ONE need; never duplicate orders. Recalculate case to use new route definitions.', 'routes',{materialId:id,revision:integer(1,1e9),routes:list(enumeration(['domestic','foreign']),2)});
supplyPost('calculate_sourcing_materials','Inventory: net frozen BOM demand against unreserved approved raw/line stock and unallocated timely open purchases. Creates reservations, not consumption. Existing planned builds protected. Existing active orders must be resolved before recalculation.', 'calculate',{...supplyCase,notes:text()});
supplyPost('set_sourcing_finance','Finance: proposed/approved budget and date funds available. Does not move money. Rial integer ceiling cannot fall below issued commitments.', 'finance',{...supplyCase,status:enumeration(['planned','approved']),budgetRial:text('',18),availableOn:text('',10),notes:text()});
supplyPost('save_sourcing_quote','Domestic/foreign buyer: enter comparable quote for net shortage or explicit no-quote reason. Costs normalize to IRR using declared FX, date and source. Editing resets technical approval. Blank quoteId creates.', 'quote',{...supplyCase,partCode:text('',12),route:enumeration(['domestic','foreign']),quoteId:text('',200),quoteRevision:integer(0,1e9),unavailable:{type:'boolean'},reason:text(),supplier:text('',200),unitPrice:text('',24),currency:enumeration(['IRR','IRT','USD','CNY','EUR']),fxRate:text('',24),fxDate:text('',10),fxSource:text('',500),extrasRial:text('',18),costNotes:text('',2000),eta:text('',10),validUntil:text('',10),paymentTerms:text('',2000),specs:text(),reference:text('',500)});
supplyPost('review_sourcing_quote','Engineering: technical pass/fail with reason. Cannot change an awarded proposal.', 'technical',{...supplyCase,quoteId:id,quoteRevision:integer(1,1e9),result:enumeration(['pass','fail']),notes:text()});
supplyPost('award_sourcing_quote','CEO: choose exactly ONE active purchase route after both requested routes respond and technical checks finish. Lowest timely eligible landed cost is recommendation; exceptions need reason. Creates selected order awaiting funding, not issued purchase.', 'award',{...supplyCase,partCode:text('',12),quoteId:id,notes:text()});
supplyPost('issue_sourcing_purchase','Finance: issue only selected valid quote when approved case budget and available-funds date permit. Never a bank transfer.', 'issue_order',{...supplyCase,orderId:id,reference:text('',500)});
supplyPost('track_sourcing_purchase','Buyer reports preparation/shipping/update; only finance may report paid. Record supporting reference and ETA; payment is a report, not bank action.', 'track',{...supplyCase,orderId:id,stage:enumeration(['paid','preparing','shipped','update']),eta:text('',10),notes:text(),reference:text('',500)});
supplyPost('receive_sourcing_purchase','Inventory: partial delivery to quarantine via existing receipt workflow; needs quarantine warehouse and flow inventory rights. Generates batch, does not close shortage until QC and shelving. Rejects duplicate/over-receipt; rejected QC quantities may be replaced.', 'receive',{orderId:id,day:text('',10),quantity:text('',20),manufacturerLot:text('',200),expiry:text('',10),notes:text()});
supplyPost('close_sourcing_purchase','Inventory: close only when all ordered quantity has passed QC and entered raw warehouse.', 'close_order',{...supplyCase,orderId:id,notes:text()});
supplyPost('cancel_sourcing_purchase','CEO: cancel selected/issued order only before any receipt, with reason; releases purchase reservations.', 'cancel_order',{...supplyCase,orderId:id,notes:text()});
supplyPost('mark_sourcing_ready','Inventory: mark ready only when every BOM line is physically available, approved and reserved for case.', 'ready',{...supplyCase,notes:text()});
supplyPost('release_sourcing_to_production','Inventory: hand over fully ready case to production, with reference; releases planning holds without consuming stock. All related purchases must be closed/cancelled.', 'release',{...supplyCase,notes:text(),reference:text('',500)});
supplyPost('cancel_sourcing_plan','CEO: cancel case without any non-cancelled purchase and release holds. Does not delete history.', 'cancel',{...supplyCase,notes:text()});
supplyPost('followup_sourcing_plan','Authorized sourcing participant: record current follow-up and refresh stage task projection. Does not change commercial/stock approvals.', 'followup',{...supplyCase,notes:text()});
