import {requireAccess,checkOrigin,AccessError,accessResponse} from '@/lib/authorization';
import {storage} from '@/lib/storage';
import {boundedBody} from '@/lib/firmware-storage';
import {costRead,costWrite,moneyMicro,costingHelp,calculateCosts,periodCosts} from '@/lib/costing';
const fail=(m:string,s=400):never=>{throw new AccessError(m,s)};
const txt=(v:any,max=200)=>{if(typeof v!=='string'||!v.trim()||v.length>max)fail('فیلد متنی لازم یا نامعتبر است.');return v.trim();};
const integer=(v:any,min=0,max=100000000)=>{if(!Number.isSafeInteger(v)||v<min||v>max)fail('عدد صحیح خارج از محدوده است.');return v;};
const amount=(v:any)=>{try{moneyMicro(v);return v;}catch{fail('مبلغ ریالی معتبر وارد کنید.');}};
const day=(v:any)=>{if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v)fail('تاریخ معتبر لازم است.');return v;};
const json=(v:any,s=200)=>Response.json(v,{status:s,headers:{'Cache-Control':'private, no-store','Vary':'Cookie, Authorization'}});
async function source(){const db=storage();const [entities,records,boms,entries,operations,orders]=await Promise.all([
 db.prepare("SELECT * FROM flow_entities WHERE type LIKE 'cost_%' OR type IN ('material','build') ORDER BY id").all(),
 db.prepare("SELECT * FROM records WHERE kind IN ('product','batch','device') ORDER BY id").all(),
 db.prepare('SELECT * FROM bom_versions ORDER BY version DESC,id').all(),db.prepare('SELECT * FROM inventory_entries ORDER BY id').all(),
 db.prepare("SELECT rowid AS sequence,* FROM inventory_operations WHERE kind NOT LIKE 'cost_%' AND id IN (SELECT operation_id FROM inventory_entries) ORDER BY created,rowid").all(),db.prepare('SELECT * FROM production_orders ORDER BY id').all()]);
 return {entities:entities.results.map((e:any)=>({...e,data:JSON.parse(e.data)})),records:records.results,boms:boms.results,entries:entries.results,operations:operations.results,orders:orders.results};}
async function fingerprint(src:any){const data={...src,entities:src.entities.filter((e:any)=>e.type!=='cost_close')};return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(data))))).map(b=>b.toString(16).padStart(2,'0')).join('');}
export async function GET(){try{const u=await requireAccess();if(!costRead(u))fail('دسترسی مالی لازم است.',403);const src=await source(),view=calculateCosts(src),token=await fingerprint(src);return json({...view,help:costingHelp,write:costWrite(u),token,boms:src.boms,settings:src.entities.filter((e:any)=>e.type.startsWith('cost_')),periods:src.entities.filter((e:any)=>e.type==='cost_period').map((p:any)=>({...p,preview:periodCosts(view,src.entities,p.data)})),closes:src.entities.filter((e:any)=>e.type==='cost_close').map((e:any)=>({...e,stale:e.data.token!==token}))});}catch(e){return accessResponse(e)||json({error:'دریافت بهای تمام‌شده ممکن نشد.'},503);}}
export async function POST(request:Request){try{checkOrigin(request);const u=await requireAccess();if(!costWrite(u))fail('ثبت بهای تمام‌شده فقط با دسترسی نوشتن مالی مجاز است.',403);const b=JSON.parse(new TextDecoder().decode(await boundedBody(request,64000)));if(b.confirmed!==true||typeof b.id!=='string'||! /^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(b.id))fail('تأیید و شناسه UUID تازه لازم است.');
 const db=storage(),signature=JSON.stringify(b),prior:any=await db.prepare('SELECT payload,actor FROM inventory_operations WHERE id=?').bind(b.id).first();if(prior){if(prior.payload!==signature||prior.actor!==u.userId)fail('شناسه برای درخواست دیگری استفاده شده است.',409);return json({saved:true,repeated:true});}
 const src=await source(),now=new Date().toISOString();let target='',type='',data:any={};const notes=txt(b.notes,4000);const find=(id:string,kind:string)=>{const r:any=src.records.find((r:any)=>r.id===id&&r.kind===kind);if(!r)fail('رکورد مرتبط یافت نشد.');return {...r,data:JSON.parse(r.payload)};};
 if(b.mode==='price'){const batch=find(txt(b.batchId),'batch');if(batch.data.routineLotId)fail('بهای قطعه ساخت داخل را در پرونده بچ ساخت و پس از تکمیل مواد، زمان و سربار ثبت کنید.');if(src.entities.some((e:any)=>e.type==='cost_price'&&e.data.batchId===batch.id&&e.data.settlementId))fail('قیمت این بچ از تسویه خرید است؛ همان پرونده را با مالی بازگشایی و اصلاح کنید.');type='cost_price';target='cost-price:'+batch.id;data={batchId:batch.id,partCode:batch.data.partCode,unit:batch.data.unit,unitCost:amount(b.unitCost),reference:txt(b.reference,500),notes};}
 else if(b.mode==='material'){const m:any=src.entities.find((e:any)=>e.type==='material'&&e.data.code===b.partCode);if(!m)fail('ماده اولیه معتبر انتخاب کنید.');type='cost_material';target='cost-material:'+m.data.code;const childBomId=b.childBomId?txt(b.childBomId):'';if(childBomId&&!src.boms.some((v:any)=>v.id===childBomId))fail('BOM زیرمجموعه یافت نشد.');if(childBomId&&m.data.unit!=='عدد')fail('اتصال زیرمجموعه فقط برای واحد عدد است.');data={partCode:m.data.code,unit:m.data.unit,unitCost:childBomId?'0':amount(b.unitCost),childBomId,notes};}
 else if(b.mode==='standard'){if(!src.boms.some((v:any)=>v.id===b.bomId))fail('BOM معتبر انتخاب کنید.');type='cost_standard';target='cost-standard:'+b.bomId;data={bomId:b.bomId,minutes:integer(b.minutes,1,100000),laborHourly:amount(b.laborHourly),overheadHourly:amount(b.overheadHourly),notes};}
 else if(b.mode==='time'){find(txt(b.deviceId),'device');type='cost_time';const d=day(b.day);target='cost-time:'+b.deviceId+':'+d;data={deviceId:b.deviceId,day:d,minutes:integer(b.minutes,1,1440),notes};}
 else if(b.mode==='period'){const start=day(b.start),end=day(b.end);if(start>end||(Date.parse(end)-Date.parse(start))/86400000>31)fail('بازه حداکثر ۳۲ روز و با ترتیب صحیح باشد.');target='cost-period:'+start;type='cost_period';if(src.entities.some((e:any)=>e.type==='cost_period'&&e.id!==target&&e.data.start<=end&&e.data.end>=start))fail('بازه با دوره دیگری هم‌پوشانی دارد.');data={start,end,title:txt(b.title),laborTotal:amount(b.laborTotal),fixedOverhead:amount(b.fixedOverhead),variableOverhead:amount(b.variableOverhead),nonproduction:amount(b.nonproduction),normalMinutes:integer(b.normalMinutes,1),methodConfirmed:b.methodConfirmed===true,notes};}
 else if(b.mode==='close'){const period=src.entities.find((e:any)=>e.type==='cost_period'&&e.id===b.periodId);if(!period)fail('دوره یافت نشد.');if(period.data.end>=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tehran',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()))fail('نهایی‌سازی پس از پایان دوره امکان‌پذیر است.');const token=await fingerprint(src);if(b.token!==token)fail('منابع تغییر کرده‌اند؛ پیش‌نمایش تازه را بررسی کنید.',409);const report=periodCosts(calculateCosts(src),src.entities,period.data);if(!report.complete)fail('قیمت، زمان یا تأیید روش ناقص است؛ پیش‌نمایش را بررسی کنید.');target=b.id;type='cost_close';data={periodId:period.id,period:period.data,report,token,notes,closedAt:now,closedBy:u.name};}
 else fail('عملیات معتبر نیست.');
 const old=src.entities.find((e:any)=>e.id===target);if(integer(b.revision??0)!==(old?.revision||0))fail('نسخه تغییر کرده است؛ تازه‌سازی کنید.',409);
 // Validate recursive standard before committing any component link.
 if(type==='cost_material'&&data.childBomId){const test={...src,entities:[...src.entities.filter((e:any)=>e.id!==target),{id:target,type,data}]};if(calculateCosts(test).standards.some((s:any)=>s.missing.some((m:string)=>m.includes('چرخه'))))fail('اتصال باعث چرخه در BOM می‌شود.');}
 const guards:any[]=[];const guard=(condition:string,...args:any[])=>guards.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN '+condition+' THEN guard ELSE 0 END WHERE id=?').bind(...args,b.id));
 // Compare the entire source snapshot inside the write transaction. Concurrent stock changes invalidate a close.
 if(type==='cost_close'){
  for(const [table,rows,column] of [['inventory_entries',src.entries,'id'],['records',src.records,'id'],['bom_versions',src.boms,'id'],['production_orders',src.orders,'id']] as any[]){
   const where=table==='records'?" WHERE kind IN ('product','batch','device')":'';guard('(SELECT COUNT(*) FROM '+table+where+')=?',rows.length);
   for(const r of rows){const col=table==='records'?'payload':table==='bom_versions'?'lines':null;if(col)guard('EXISTS(SELECT 1 FROM '+table+' WHERE id=? AND '+col+'=?)',r.id,r[col]);}
  }
  guard("(SELECT COUNT(*) FROM flow_entities WHERE (type LIKE 'cost_%' AND type!='cost_close') OR type IN ('material','build'))=?",src.entities.filter((e:any)=>e.type!=='cost_close').length);
  for(const e of src.entities.filter((e:any)=>e.type!=='cost_close'))guard('EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?)',e.id,e.revision);
 }
 guard('COALESCE((SELECT revision FROM flow_entities WHERE id=?),0)=?',target,old?.revision||0);
 // Reference guards also protect non-close edits from concurrent deletion / source edits.
 for(const r of src.records.filter((r:any)=>r.id===b.batchId||r.id===b.deviceId))guard('EXISTS(SELECT 1 FROM records WHERE id=? AND payload=?)',r.id,r.payload);
 if(type==='cost_material'||type==='cost_period'){guard("(SELECT COALESCE(SUM(revision),0) FROM flow_entities WHERE type LIKE 'cost_%')=?",src.entities.filter((e:any)=>e.type.startsWith('cost_')).reduce((n:number,e:any)=>n+e.revision,0));}
 data={...data,history:[...(old?.data.history||[]),{at:now,actor:u.userId,name:u.name,notes,previous:old?{...old.data,history:undefined}:null}]};
 const write=old?db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=? AND revision=?').bind(JSON.stringify(data),now,target,old.revision):db.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').bind(target,type,JSON.stringify(data),now,now);
 await db.batch([db.prepare('INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,?,?,?,?,1)').bind(b.id,'cost_'+b.mode,signature,u.userId,now),...guards,write,db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,target,'cost_'+b.mode,JSON.stringify(data),now)]);return json({saved:true,id:target});
 }catch(e){return accessResponse(e)||json({error:'ثبت انجام نشد؛ اطلاعات را تازه‌سازی و نتیجه را بررسی کنید.'},409);}}
