import {requireAccess,checkOrigin,accessResponse} from '@/lib/authorization';
import {boundedBody,firmwareBucket} from '@/lib/firmware-storage';
import {validateBatchFile,MAX_BATCH_FILE_BYTES} from '@/lib/batch-files';
import {sha256} from '@/lib/firmware';
import {assetAccess,assetMembers,commitAssets,assetFail} from '@/lib/assets';
import {taskRequired} from '@/lib/duties';
import {storage} from '@/lib/storage';
const headers={'Cache-Control':'private, no-store','Vary':'Cookie, Authorization','X-Content-Type-Options':'nosniff'};
export async function GET(request:Request){try{const u=await requireAccess(),{r:f}=await assetAccess(u,new URL(request.url).searchParams.get('id')||'');if(f.type!=='asset_file')assetFail('مدرک یافت نشد.',404);const object=await firmwareBucket().get(f.data.objectKey);if(!object)assetFail('فایل در دسترس نیست.',404);const bytes=await object!.arrayBuffer();if(bytes.byteLength!==f.data.byteSize||await sha256(bytes)!==f.data.sha256)assetFail('یکپارچگی فایل تأیید نشد.',503);return new Response(bytes,{headers:{...headers,'Content-Type':'application/octet-stream','Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(f.data.filename).replace(/['()*]/g,c=>'%'+c.charCodeAt(0).toString(16)),'Content-Security-Policy':"sandbox; default-src 'none'"}})}catch(e){return accessResponse(e)||Response.json({error:'دریافت نامه ممکن نشد.'},{status:503,headers})}}
export async function POST(request:Request){let key='',fileId='';try{checkOrigin(request);const u=await requireAccess();if(request.headers.get('x-asset-account')&&request.headers.get('x-asset-account')!==u.userId)assetFail('حساب ورود تغییر کرده است؛ صفحه را تازه کنید.',409);const q=new URL(request.url).searchParams;fileId=taskRequired(q.get('id'));const assetId=taskRequired(q.get('assetId')),filename=taskRequired(q.get('filename'),180);if(q.get('confirmed')!=='true'||! /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(fileId))assetFail('تأیید و شناسه فایل لازم است.');const members=await assetMembers(),{r,a,rows}=await assetAccess(u,assetId,members);if(!a.custodian||r.type!=='asset_item')assetFail('پیوست نامه فقط توسط اموال‌دار مجاز است.',403);if(String(r.revision)!==q.get('revision'))assetFail('تحویل یا پرونده تغییر کرده؛ تازه‌سازی کنید.',409);const bytes=await boundedBody(request,MAX_BATCH_FILE_BYTES);validateBatchFile(filename,bytes.length);const hash=await sha256(bytes.buffer as ArrayBuffer),old=rows.find(x=>x.id===fileId);if(old){if(old.type!=='asset_file'||old.data.assetId!==r.id||old.data.custodyId!==r.data.custodyId||old.data.actor!==u.userId||old.data.sha256!==hash||old.data.filename!==filename)assetFail('شناسه فایل تکراری است.',409);return Response.json({id:fileId,repeated:true},{headers});}key='assets/'+assetId+'/'+fileId+'/'+crypto.randomUUID();await firmwareBucket().put(key,bytes,{httpMetadata:{contentType:'application/octet-stream'}});await commitAssets(u,crypto.randomUUID(),JSON.stringify({fileId,assetId,filename,hash}),rows,members,[{id:fileId,type:'asset_file',revision:0,data:{assetId,custodyId:r.data.custodyId,filename,actor:u.userId,objectKey:key,sha256:hash,byteSize:bytes.length}}],'upload');return Response.json({id:fileId,filename},{headers})}catch(e){if(key)try{const linked:any=await storage().prepare("SELECT data FROM flow_entities WHERE id=? AND type='asset_file'").bind(fileId).first();if(linked&&JSON.parse(linked.data).objectKey===key)return Response.json({id:fileId},{headers});await firmwareBucket().delete(key)}catch{}return accessResponse(e)||Response.json({error:'نامه ذخیره نشد؛ فهرست مدارک را تازه کنید.'},{status:409,headers})}}
