import {requireAccess,checkOrigin,accessResponse} from '@/lib/authorization';
import {storage} from '@/lib/storage';
import {boundedBody} from '@/lib/firmware-storage';
import {memberId,dayAt} from '@/lib/duties';
import {salesFail as fail,salesManager,salesStaff,salesFinance,salesRep,salesRows,salesEntity,salesLock,sreq as req,stxt as txt,integer,money,sday} from '@/lib/sales';
import {rial,total} from '@/lib/sales-contract';
import {monitorDefaults,reportKinds,monitorHelp,goalProgress,buildSalesReport,checkRecovery} from '@/lib/sales-monitor-contract';
import {monitorPolicy,monitorMembers,monitorTasks,monitorDeliveries,monitorHealth,scanSalesMonitor} from '@/lib/sales-monitor';
const json=(d:any,status=200)=>Response.json(d,{status,headers:{'Cache-Control':'private, no-store','Vary':'Cookie, Authorization'}});
const entry=(u:any)=>!salesRep(u)&&(salesManager(u)||salesStaff(u)||salesFinance(u));
export async function GET(request:Request){try{
 const u=await requireAccess();if(!entry(u))fail('دسترسی پیگیری فروش ندارید.',403);const mid=await memberId(u),manager=salesManager(u),q=new URL(request.url).searchParams;
 const [rows,policy,members,health]=await Promise.all([salesRows(),monitorPolicy(),monitorMembers(),monitorHealth()]);const alerts=rows.filter(r=>r.type==='sales_alert'&&(manager||r.data.ownerId===mid));
 const reportId=q.get('report');if(reportId){if(!manager)fail('گزارش مدیریت فقط برای مدیر فروش است.',403);return json({report:await salesEntity(reportId,'sales_report')});}
 const preview=q.get('preview');if(preview){if(!manager)fail('گزارش مدیریت فقط برای مدیر فروش است.',403);if(!Object.hasOwn(reportKinds,preview))fail('دوره معتبر انتخاب کنید.');return json({report:{id:'',data:buildSalesReport(preview,rows,await monitorDeliveries(),await monitorTasks(),alerts,members,new Date())}});}
 return json({today:dayAt(),me:mid,manager,finance:salesFinance(u),policy:manager?policy:null,health,help:monitorHelp,alerts:alerts.sort((a,b)=>b.updated.localeCompare(a.updated)),goals:rows.filter(r=>r.type==='sales_goal').map(g=>({...g,progress:goalProgress(g,rows,dayAt())})),reports:manager?(await storage().prepare("SELECT id,revision,created,json_extract(data,'$.kind') kind,json_extract(data,'$.start') start,json_extract(data,'$.end') end,json_extract(data,'$.asOf') asOf FROM flow_entities WHERE type='sales_report' ORDER BY created DESC LIMIT 90").all()).results:[],members:members.map(({permissions,...m})=>m),agents:rows.filter(r=>r.type==='sales_agent').map(r=>({id:r.id,name:r.data.name,active:r.data.active})),products:(await storage().prepare("SELECT id,payload FROM records WHERE kind='product'").all()).results.map((r:any)=>({id:r.id,name:JSON.parse(r.payload).name||JSON.parse(r.payload).model||r.id})),bounced:salesFinance(u)?rows.filter(r=>r.type==='sales_payment'&&r.data.state==='bounced').map(r=>({...r,recovery:checkRecovery(r,rows)})):[],credits:salesFinance(u)?rows.filter(r=>r.type==='sales_payment'&&r.data.state==='cleared'&&!r.data.openingId).map(r=>({id:r.id,agentId:r.data.agentId,reference:r.data.reference,amount:r.data.amount,recoveryAvailable:String(rial(r.data.amount)-total(rows.filter(v=>v.type==='sales_check_recovery'&&v.data.creditId===r.id),v=>v.data.amount))})):[]});
 }catch(e){return accessResponse(e)||json({error:'دریافت گزارش و هشدارها انجام نشد.'},503)}}
export async function POST(request:Request){try{
 checkOrigin(request);const u=await requireAccess();if(!entry(u))fail('دسترسی پیگیری فروش ندارید.',403);const b=JSON.parse(new TextDecoder().decode(await boundedBody(request,64000))),id=req(b.id,80),mode=req(b.mode),db=storage(),now=new Date().toISOString(),today=dayAt(),mid=await memberId(u),manager=salesManager(u);
 if(!/^[a-f0-9-]{36}$/i.test(id)||b.confirmed!==true)fail('شناسه معتبر و تأیید صریح لازم است.');
 if(['configure','goal','retire_goal','scan','assign','review_goal','report_read'].includes(mode)&&!manager)fail('این اقدام با مدیر فروش است.',403);
 if(mode==='recover_check'&&!salesFinance(u))fail('تعیین تکلیف وصول چک با مالی است.',403);
 if(!['configure','goal','retire_goal','scan','assign','review_goal','report_read','followup','acknowledge','recover_check'].includes(mode))fail('عملیات معتبر انتخاب کنید.');
 const signature=JSON.stringify(b),prior:any=await db.prepare('SELECT payload,actor FROM inventory_operations WHERE id=?').bind(id).first();if(prior){if(prior.payload!==signature||prior.actor!==u.userId)fail('شناسه برای درخواست دیگری مصرف شده است.',409);return json({saved:true,repeated:true});}
 if(mode==='scan'){const result=await scanSalesMonitor({source:'interactive'});await db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'sales_monitor_manual',?,?,?,1)").bind(id,signature,u.userId,now).run();return json({saved:true,result});}
 const checks=await salesLock(db,id),rows=await salesRows(),stmts:D1PreparedStatement[]=[],members=await monitorMembers();let target=id;
 const guard=(q:string,...v:any[])=>checks.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN '+q+' THEN guard ELSE 0 END WHERE id=?').bind(...v,id));
 const version=(r:any)=>{if(r.revision!==b.revision)fail('نسخه تغییر کرده است؛ تازه‌سازی کنید.',409);guard('EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?)',r.id,r.revision);};
 const put=(eid:string,type:string,data:any,old?:any)=>{const d={...data,history:[...(old?.data.history||[]),{mode,actor:u.userId,actorName:u.name,at:now,notes:txt(b.notes||'',4000)}]};stmts.push(old?db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=? AND revision=?').bind(JSON.stringify(d),now,eid,old.revision):db.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').bind(eid,type,JSON.stringify(d),now,now));};
 const activeMember=(member:string,finance=false)=>{const m=members.find(m=>m.id===member&&(finance?m.finance:m.sales));if(!m)fail('مسئول فعال با دسترسی این مرحله انتخاب کنید.');guard("EXISTS(SELECT 1 FROM app_members WHERE id=? AND status='active' AND permissions=?)",m!.id,m!.permissions);return m!.id;};
 if(mode==='configure'){
  const current=await monitorPolicy();if(current.revision!==b.revision)fail('تنظیمات تغییر کرده است؛ تازه‌سازی کنید.',409);const p=b.settings;if(!p||typeof p.enabled!=='boolean')fail('تنظیمات معتبر لازم است.');const d:any={enabled:p.enabled};
  for(const key of ['dailyTime','weeklyTime','quarterlyTime']){const v=req(p[key],5);if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(v))fail('ساعت معتبر وارد کنید.');d[key]=v;}
  for(const [key,min,max] of [['overdueDays',1,365],['goalElapsed',1,99],['goalAchievement',1,100],['goalFinalElapsed',2,100],['goalFinalAchievement',1,100],['deliveryLateDays',1,90],['paymentHours',1,168],['returnCount',2,100],['returnDays',7,365],['responseHours',1,168],['escalationHours',1,336]] as [string,number,number][])d[key]=integer(p[key],min,max);
  d.overdueAmount=money(p.overdueAmount);if(d.goalFinalElapsed<=d.goalElapsed||d.goalFinalAchievement<d.goalAchievement)fail('حد دوم هدف باید پس از حد اول و با تحقق بیشتر باشد.');req(b.notes,4000);d.startedDay=current.revision&&current.data.enabled?current.data.startedDay:today;put(current.id,'sales_monitor_policy',d,current.revision?current:undefined);target=current.id;
 }else if(mode==='goal'){
  const agent=await salesEntity(req(b.agentId),'sales_agent');if(!agent.data.active)fail('نماینده فعال انتخاب کنید.');guard('EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?)',agent.id,agent.revision);
  const start=sday(b.start),end=sday(b.end);if(start>end||end<today)fail('بازه هدف معتبر و پایان آن امروز یا آینده باشد.');if(!['net','units'].includes(b.basis))fail('مبنای هدف معتبر نیست.');const productIds=b.productIds;if(!Array.isArray(productIds)||productIds.length>100||new Set(productIds).size!==productIds.length)fail('فهرست محصولات معتبر نیست.');for(const pid of productIds){if(!await db.prepare("SELECT id FROM records WHERE id=? AND kind='product'").bind(req(pid)).first())fail('محصول هدف یافت نشد.');guard("EXISTS(SELECT 1 FROM records WHERE id=? AND kind='product')",pid);}
  const old=b.previousId?await salesEntity(req(b.previousId),'sales_goal'):null;if(old){version(old);if(old.data.agentId!==agent.id||old.data.state!=='active')fail('هدف قبلی فعال همین نماینده باشد.');put(old.id,'sales_goal',{...old.data,state:'retired',replacementId:id},old);}
  if(rows.some(r=>r.type==='sales_goal'&&r.id!==old?.id&&r.data.agentId===agent.id&&r.data.state==='active'&&r.data.start<=end&&r.data.end>=start))fail('برای این نماینده هدف فعال با بازه هم‌پوشان وجود دارد.');req(b.notes,4000);put(id,'sales_goal',{agentId:agent.id,title:req(b.title),start,end,basis:b.basis,amount:money(b.amount,true),productIds,state:'active',version:(old?.data.version||0)+1,previousId:old?.id||''});
 }else if(mode==='retire_goal'){
  const goal=await salesEntity(req(b.goalId),'sales_goal');version(goal);if(goal.data.state!=='active')fail('هدف فعال انتخاب کنید.');req(b.notes,4000);put(goal.id,'sales_goal',{...goal.data,state:'retired'},goal);target=goal.id;
 }else if(mode==='recover_check'){
  const payment=await salesEntity(req(b.paymentId),'sales_payment'),credit=await salesEntity(req(b.creditId),'sales_payment');version(payment);guard('EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?)',credit.id,credit.revision);if(payment.data.state!=='bounced'||credit.data.state!=='cleared'||credit.data.openingId||credit.data.agentId!==payment.data.agentId)fail('چک برگشتی و وصول واقعی همین نماینده را انتخاب کنید.');const amount=money(b.amount,true),recovery=checkRecovery(payment,rows),used=total(rows.filter(r=>r.type==='sales_check_recovery'&&r.data.creditId===credit.id),r=>r.data.amount);if(rial(amount)>rial(recovery.remaining)||used+rial(amount)>rial(credit.data.amount))fail('مبلغ از مانده چک یا ظرفیت وصول جایگزین بیشتر است.');req(b.notes,4000);put(id,'sales_check_recovery',{agentId:payment.data.agentId,paymentId:payment.id,creditId:credit.id,amount,reference:credit.data.reference,notes:b.notes});
 }else if(mode==='report_read'){
  const report=await salesEntity(req(b.reportId),'sales_report');target=report.id;for(const t of await monitorTasks())if(t.data.salesReportId===report.id&&t.assignee===mid&&!['completed','cancelled'].includes(t.state))stmts.push(db.prepare("UPDATE duty_runs SET state='completed',revision=revision+1,updated=? WHERE id=? AND revision=?").bind(now,t.id,t.revision));
 }else{
  const alert=await salesEntity(req(b.alertId),'sales_alert');if(!manager&&alert.data.ownerId!==mid)fail('این پیگیری در دسترسی شما نیست.',404);version(alert);if(['resolved','reviewed'].includes(alert.data.state))fail('هشدار بسته شده است.');target=alert.id;const d={...alert.data};req(b.notes,4000);
  if(mode==='assign'){d.ownerId=activeMember(req(b.ownerId),d.kind==='pending_payment');d.due=req(b.due,30);if(!Number.isFinite(Date.parse(d.due))||Date.parse(d.due)<Date.now()||Date.parse(d.due)>Date.now()+30*86400000)fail('مهلت معتبر، حداکثر ۳۰ روز آینده انتخاب کنید.');d.due=new Date(d.due).toISOString();}
  else if(mode==='review_goal'){if(d.kind!=='goal_gap')fail('جمع‌بندی فقط برای هدف پایان‌یافته است.');const goal=await salesEntity(d.sourceId,'sales_goal'),progress=goalProgress(goal,rows,today);if(!progress.ended)fail('قبل از پایان دوره، پیگیری هدف قابل بستن نیست.');d.state='reviewed';d.reviewFingerprint=d.fingerprint;d.resolvedAt=now;d.finalReview=req(b.notes,4000);}
  else {d.state='acknowledged';d.lastFollowup=req(b.notes,4000);d.nextAction=req(b.nextAction,2000);}
  put(alert.id,'sales_alert',d,alert);
 }
 await db.batch([db.prepare('INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,?,?,?,?,1)').bind(id,'sales_monitor_'+mode,signature,u.userId,now),...checks,...stmts,db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,target,'sales_monitor_'+mode,signature,now)]);
 let followupPending=false;try{await scanSalesMonitor({reports:false,source:'event'});}catch{followupPending=true;}return json({saved:true,id:target,followupPending});
 }catch(e){return accessResponse(e)||json({error:'ثبت انجام نشد؛ ممکن است اطلاعات هم‌زمان تغییر کرده باشد. نتیجه را بررسی و تازه‌سازی کنید.'},409)}}
