import {hospitalUser,hospitalManager,hospitalCenter,hreq} from '@/lib/hospital';
import {checkOrigin,AccessError,accessResponse} from '@/lib/authorization';
import {storage} from '@/lib/storage';
import {boundedBody} from '@/lib/firmware-storage';
import {username,password,hashPassword} from '@/lib/password-auth';
import {validatePermissions} from '@/lib/permissions';
export async function GET(){try{const u=await hospitalUser();if(!hospitalManager(u))throw new AccessError('فقط مدیر خدمات مجاز است.',403);return Response.json({accounts:(await storage().prepare("SELECT m.id,m.name,m.status,a.username,json_extract(m.permissions,'$.hospitalCenterId') centerId FROM app_members m JOIN password_accounts a ON a.member_id=m.id WHERE COALESCE(json_extract(m.permissions,'$.hospitalCenterId'),'')<>''").all()).results},{headers:{'Cache-Control':'no-store'}});}catch(e){return accessResponse(e)||Response.json({error:'دریافت حساب‌ها انجام نشد.'},{status:503})}}
export async function POST(request:Request){try{checkOrigin(request);const u=await hospitalUser();if(!hospitalManager(u))throw new AccessError('فقط مدیر خدمات مجاز است.',403);const b=JSON.parse(new TextDecoder().decode(await boundedBody(request,4096)));if(b.confirmed!==true||! /^[a-f0-9-]{36}$/i.test(b.id)||Object.keys(b).some(k=>!['id','centerId','revision','name','username','password','confirmed'].includes(k)))throw new AccessError('ورودی حساب معتبر نیست؛ دسترسی ثابت است.',400);const c=await hospitalCenter(u,hreq(b.centerId)),login=username(b.username),name=hreq(b.name,100),summary=JSON.stringify({centerId:c.id,name,username:login}),db=storage();const old:any=await db.prepare('SELECT actor,after FROM access_audit WHERE id=?').bind('hospital-account:'+b.id).first();if(old){if(old.actor!==u.userId||old.after!==summary)throw new AccessError('شناسه تکراری متفاوت است.',409);return Response.json({id:b.id,repeated:true});}if(c.revision!==b.revision)throw new AccessError('مرکز تغییر کرده است.',409);const hash=await hashPassword(password(b.password)),permissions=validatePermissions({hospitalCenterId:c.id,read:[],write:[],eventStages:[]}),now=new Date().toISOString();await db.batch([db.prepare("INSERT INTO app_members(id,email,name,unit,status,permissions,revision,created,updated) SELECT ?,?,?,'مسئول مرکز بیمارستانی','active',?,1,?,? FROM flow_entities WHERE id=? AND revision=? AND json_extract(data,'$.active')=1").bind(b.id,b.id+'@local.invalid',name,JSON.stringify(permissions),now,now,c.id,c.revision),db.prepare('INSERT INTO password_accounts(member_id,username,password_hash,version) VALUES(?,?,?,1)').bind(b.id,login,hash),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind('hospital-account:'+b.id,u.userId,b.id,'hospital_account',summary,now)]);return Response.json({id:b.id,username:login},{status:201,headers:{'Cache-Control':'no-store'}});
 }catch(e){return accessResponse(e)||Response.json({error:'نام کاربری تکراری یا اطلاعات حساب نامعتبر است.'},{status:409})}}
