import {requireAccess,checkOrigin,accessResponse} from '@/lib/authorization';
import {boundedBody,firmwareBucket} from '@/lib/firmware-storage';
import {validateBatchFile,MAX_BATCH_FILE_BYTES} from '@/lib/batch-files';
import {sha256} from '@/lib/firmware';
import {storage} from '@/lib/storage';
import {treasuryRows,treasuryRoles,tFail,tText,tUUID} from '@/lib/treasury';
export async function GET(request:Request){try{const u=await requireAccess(),rows=await treasuryRows();await treasuryRoles(u,rows);const id=new URL(request.url).searchParams.get('id'),f=rows.find(r=>r.id===id&&r.type==='treasury_file');if(!f)tFail('مدرک یافت نشد.',404);const o=await firmwareBucket().get(f!.data.objectKey);if(!o)tFail('مدرک در دسترس نیست.',404);const bytes=await o!.arrayBuffer();if(bytes.byteLength!==f!.data.byteSize||await sha256(bytes)!==f!.data.sha256)tFail('یکپارچگی فایل تأیید نشد.',503);return new Response(bytes,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(f!.data.filename),'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"sandbox; default-src 'none'"}});}catch(e){return accessResponse(e)||Response.json({error:'دریافت مدرک انجام نشد.'},{status:503});}}
export async function POST(request:Request){let key='';try{checkOrigin(request);const u=await requireAccess(),rows=await treasuryRows(),roles=await treasuryRoles(u,rows);if(!roles.write)tFail('دسترسی نوشتن مالی لازم است.',403);const q=new URL(request.url).searchParams,id=tUUID(q.get('id')),caseId=tText(q.get('caseId'),200),filename=tText(q.get('filename'),180),r=rows.find(r=>r.id===caseId&&['treasury_request','treasury_check','treasury_expense','treasury_statement'].includes(r.type));if(!r)tFail('پرونده خزانه یافت نشد.',404);const bytes=await boundedBody(request,MAX_BATCH_FILE_BYTES);try{validateBatchFile(filename,bytes.length);}catch(e){tFail((e as Error).message);}const hash=await sha256(bytes.buffer as ArrayBuffer),old=await storage().prepare('SELECT type,data FROM flow_entities WHERE id=?').bind(id).first<any>();if(old){const d=JSON.parse(old.data);if(old.type!=='treasury_file'||d.caseId!==caseId||d.actor!==u.userId||d.sha256!==hash||d.filename!==filename)tFail('شناسه مدرک تکراری است.',409);return Response.json({id,repeated:true});}
 const db=storage(),now=new Date().toISOString();key='treasury/'+caseId+'/'+id+'/'+crypto.randomUUID();await firmwareBucket().put(key,bytes,{httpMetadata:{contentType:'application/octet-stream'}});await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'treasury_upload',?,?,?,CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN 1 ELSE 0 END)").bind(crypto.randomUUID(),JSON.stringify({id,caseId,filename,hash}),u.userId,now,caseId,r!.revision),db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,'treasury_file',?,1,?,?)").bind(id,JSON.stringify({caseId,filename,sha256:hash,byteSize:bytes.length,actor:u.userId,objectKey:key}),now,now),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,caseId,'treasury_upload',JSON.stringify({id,filename,hash}),now)]);return Response.json({id,filename},{headers:{'Cache-Control':'private, no-store'}});
 }catch(e){if(key){try{const linked=await storage().prepare("SELECT id FROM flow_entities WHERE type='treasury_file' AND json_extract(data,'$.objectKey')=?").bind(key).first();if(!linked)await firmwareBucket().delete(key);}catch{}}return accessResponse(e)||Response.json({error:'بارگذاری تأیید نشد؛ فهرست مدارک را تازه کنید.'},{status:409});}}
