import {hospitalUser,hospitalManager,hospitalCenter,hospitalAsset,hrow,hreq} from '@/lib/hospital';
import {checkOrigin,AccessError,accessResponse} from '@/lib/authorization';
import {firmwareBucket,boundedBody} from '@/lib/firmware-storage';
import {storage} from '@/lib/storage';
import {sha256} from '@/lib/firmware';
export async function GET(request:Request){try{const u=await hospitalUser(),f=await hrow(hreq(new URL(request.url).searchParams.get('id')),'hospital_file');await hospitalCenter(u,f.data.centerId);if(u.permissions.hospitalCenterId&&f.data.purpose==='manual'&&!await storage().prepare("SELECT id FROM flow_entities WHERE type='hospital_manual' AND json_extract(data,'$.state')='published' AND json_extract(data,'$.fileId')=?").bind(f.id).first())throw new AccessError('راهنمای منتشرشده پیدا نشد.',404);const object=await firmwareBucket().get(f.data.objectKey);if(!object)throw new AccessError('فایل در دسترس نیست.',404);return new Response(object.body,{headers:{'Content-Type':f.data.mime,'Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(f.data.filename),'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}catch(e){return accessResponse(e)||Response.json({error:'دریافت فایل انجام نشد.'},{status:503})}}
export async function POST(request:Request){try{checkOrigin(request);const u=await hospitalUser(),q=new URL(request.url).searchParams,centerId=hreq(q.get('center')),purpose=hreq(q.get('purpose')),assetId=q.get('asset')||'',id=hreq(q.get('id'));if(!/^[a-f0-9-]{36}$/i.test(id)||!['manual','payment'].includes(purpose))throw new AccessError('نوع فایل و شناسه معتبر لازم است.',400);const c=await hospitalCenter(u,centerId);if(purpose==='manual'&&!hospitalManager(u)||purpose==='payment'&&!u.permissions.hospitalCenterId)throw new AccessError('مجوز بارگذاری ندارید.',403);if(purpose==='manual'){const a=await hospitalAsset(u,assetId);if(a.data.centerId!==centerId)throw new AccessError('دستگاه همان مرکز لازم است.',400);}const data=await boundedBody(request,10*1024*1024),mime=request.headers.get('content-type')?.split(';')[0]||'',filename=hreq(q.get('filename'),200);const head=new TextDecoder().decode(data.slice(0,5));if(!data.length||!(mime==='application/pdf'&&head==='%PDF-'||mime==='image/png'&&data[0]===137&&data[1]===80&&data[2]===78&&data[3]===71||mime==='image/jpeg'&&data[0]===255&&data[1]===216&&data[2]===255))throw new AccessError('فقط PDF، PNG یا JPEG معتبر تا ۱۰ مگابایت.',400);const hash=await sha256(data.buffer as ArrayBuffer),db=storage(),old:any=await db.prepare("SELECT data FROM flow_entities WHERE id=? AND type='hospital_file'").bind(id).first();if(old){const d=JSON.parse(old.data);if(d.actor!==u.userId||d.sha256!==hash||d.centerId!==centerId||d.purpose!==purpose||d.assetId!==assetId||d.filename!==filename)throw new AccessError('شناسه فایل با محتوای دیگری استفاده شده.',409);return Response.json({id,repeated:true});}const key='hospital/'+id+'/'+crypto.randomUUID(),now=new Date().toISOString();await firmwareBucket().put(key,data,{httpMetadata:{contentType:mime}});const info={centerId,assetId,purpose,filename,mime,byteSize:data.length,sha256:hash,objectKey:key,actor:u.userId};
 try{await db.batch([db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,'hospital_file',?,1,?,?)").bind(id,JSON.stringify(info),now,now),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,id,'hospital_upload',JSON.stringify({centerId,purpose,filename,sha256:hash}),now)]);}catch(e){await firmwareBucket().delete(key);throw e;}return Response.json({id},{headers:{'Cache-Control':'no-store'}});
 }catch(e){return accessResponse(e)||Response.json({error:'بارگذاری انجام نشد.'},{status:409})}}
