import {termsPlan,allocationPlan} from '@/lib/sales-network-contract';
import {leadMembers,leadMemberGuard} from '@/lib/sales-leads';
import {salesVisible,liveSalesUser} from '@/lib/sales';
import {trainingContext} from '@/lib/training-context';
import {leadConvert} from '@/lib/sales-leads';
import {syncLeadTasks} from '@/lib/sales-lead-tasks';
import {goalProgress} from '@/lib/sales-monitor-contract';
import {scanSalesMonitor} from '@/lib/sales-monitor';
import {requireAccess,checkOrigin,accessResponse} from '@/lib/authorization';
import {storage} from '@/lib/storage';
import {boundedBody} from '@/lib/firmware-storage';
import {dayAt,addDay,memberId} from '@/lib/duties';
import {salesRoles,salesActions,salesHelp,salesAccounts,salesTargetProgress,salesMilestones,salesProxyModes,salesOrderProgress,rial,total} from '@/lib/sales-contract';
import {salesFail as fail,salesRep,salesManager,salesStaff,salesFinance,salesRead,salesWarehouse,salesScope,salesLock,salesRows,salesEntity,salesQuote,salesSubmission,salesDelivery,publicSalesFile,sreq as req,stxt as txt,money,integer,arr,sday} from '@/lib/sales';
import {syncSalesTasks} from '@/lib/sales-tasks';
const json=(d:any,status=200)=>Response.json(d,{status,headers:{'Cache-Control':'private, no-store','Vary':'Cookie, Authorization'}});
export async function GET(request:Request){try{
 const u=await liveSalesUser(await requireAccess());if(!salesRead(u)&&!salesWarehouse(u))fail('دسترسی فروش ندارید.',403);const all=await salesRows(),selected=new URL(request.url).searchParams.get('agent')||'',own=salesRep(u)?u.permissions.salesAgentId!:selected;if(salesRep(u)&&selected&&selected!==own)fail('پرونده پیدا نشد یا دسترسی ندارید.',404);if(own)await salesScope(u,own);
 const candidates=all.filter(r=>r.type==='sales_agent'&&(!own||r.id===own)),visible=await Promise.all(candidates.map(a=>salesVisible(u,a))),agents=candidates.filter((_,i)=>visible[i]),ids=agents.map(a=>a.id),rows=all.filter(r=>ids.includes(r.data.agentId)||r.type==='sales_price'&&r.data.agentId==='');const today=dayAt();
 const warehouseOnly=!salesRead(u);if(warehouseOnly)return json({warehouseOnly:true,roles:{warehouse:true},agents:agents.map(a=>({id:a.id,data:{name:a.data.name}})),returns:rows.filter(r=>r.type==='sales_return').map(r=>({...r,data:{agentId:r.data.agentId,state:r.data.state,deviceIds:r.data.deviceIds,serials:r.data.serials,reason:r.data.reason,receipt:r.data.receipt}})),help:salesHelp});
 const products=(await storage().prepare("SELECT id,payload FROM records WHERE kind='product'").all()).results.map((r:any)=>{const p=JSON.parse(r.payload);return {id:r.id,name:p.name||p.model||p.code,model:p.model||'',status:p.status};});
 const accounts=agents.map(a=>({agentId:a.id,...salesAccounts(rows,a.id,today)}));
 const members=!salesRep(u)?(await storage().prepare("SELECT id,name,permissions FROM app_members WHERE status='active'").all()).results.map((m:any)=>{const p=JSON.parse(m.permissions),s={isAdmin:false,permissions:p} as any;return {id:m.id,name:m.name,sales:salesStaff(s),manager:salesManager(s),finance:salesFinance(s)};}).filter(m=>m.sales||m.finance):[];
 const deliveries=await salesDelivery(rows,ids),mid=await memberId(u);
 const tasks=(await storage().prepare("SELECT id,assignee,supervisor,due,state,data FROM duty_runs WHERE template_id LIKE 'sales:%' AND state NOT IN ('completed','cancelled')").all()).results.flatMap((t:any)=>{const d=JSON.parse(t.data);if(!d.salesWorkflow||!ids.includes(d.salesAgentId)||!(salesManager(u)||t.assignee===mid||t.supervisor===mid))return [];return [{id:t.id,agentId:d.salesAgentId,title:d.title,role:d.workflowRole,assignee:t.assignee,assigneeName:members.find(m=>m.id===t.assignee)?.name||(t.assignee===mid?u.name:'نماینده'),supervisor:t.supervisor,due:t.due,state:t.state,late:t.due<new Date().toISOString()}];});
 const pipeline=rows.filter(r=>r.type==='sales_order').map(o=>salesOrderProgress(o,deliveries,today));
 const invoices=accounts.flatMap(a=>a.invoices),returns=rows.filter(r=>r.type==='sales_return'&&r.data.state==='credited');
 const reportProducts=products.map(p=>{const lines=invoices.filter(i=>!i.data.openingId).flatMap(i=>i.data.lines||[]).filter((l:any)=>l.productId===p.id),back=returns.flatMap(r=>r.data.lines).filter(l=>l.productId===p.id);return {...p,quantity:lines.reduce((n:number,l:any)=>n+l.quantity,0)-back.reduce((n:number,l:any)=>n+l.quantity,0),net:String(total(lines,l=>l.net)-total(back,l=>l.net))};}).filter(p=>p.quantity||p.net!=='0');
 return json({templates:all.filter(r=>r.type==='sales_template'),allocationPlans:accounts.flatMap(a=>a.credits.map(c=>({agentId:a.agentId,creditId:c.id,...allocationPlan(all,a.agentId,c.id,today)}))),today,me:u.userId,meName:u.name,roles:{leads:!trainingContext.getStore()&&!u.permissions.serviceAgentId&&!u.permissions.hospitalCenterId&&salesStaff(u),agent:salesRep(u),manager:salesManager(u),staff:salesStaff(u),finance:salesFinance(u),warehouse:salesWarehouse(u)},agents,products,members,goals:rows.filter(r=>r.type==='sales_goal'&&r.data.state==='active').map(g=>({...g,progress:goalProgress(g,rows,today)})),prices:rows.filter(r=>r.type==='sales_price'),targets:rows.filter(r=>r.type==='sales_target').map(t=>({...t,progress:salesTargetProgress(t,rows,today)})),orders:rows.filter(r=>r.type==='sales_order'),accounts,openings:rows.filter(r=>r.type==='sales_opening'),files:rows.filter(r=>r.type==='sales_file').map(publicSalesFile),deliveries,pipeline,tasks,reports:{products:reportProducts,netSales:String(total(invoices.filter(i=>!i.data.openingId),i=>i.data.amount)-total(returns,r=>r.data.amount)),collections:String(total(rows.filter(r=>r.type==='sales_payment'&&!r.data.openingId).flatMap(r=>r.data.financialEvents||[]),e=>e.delta)),discounts:String(total(invoices.filter(i=>!i.data.openingId),i=>i.data.discount)),returns:String(total(returns,r=>r.data.amount))},help:salesHelp});
 }catch(e){return accessResponse(e)||json({error:'دریافت فروش انجام نشد.'},503)}}
export async function POST(request:Request){try{
 checkOrigin(request);const u=await liveSalesUser(await requireAccess()),b=JSON.parse(new TextDecoder().decode(await boundedBody(request,128000))),db=storage(),id=req(b.id,80),mode=req(b.mode),now=new Date().toISOString(),today=dayAt();
 if(!/^[0-9a-f-]{36}$/i.test(id)||b.confirmed!==true||!Object.hasOwn(salesActions,mode))fail('شناسه عملیات و تأیید صریح لازم است.');
 const allowed=['agent','price','target'].includes(mode)?salesManager(u):['terms','invoice','payment_review','check_status','allocate','payment_reverse','return_review','opening_review'].includes(mode)?salesFinance(u):mode==='return_receive'?salesWarehouse(u):['order_review','order_progress','opening'].includes(mode)?salesStaff(u)||mode==='opening'&&salesFinance(u):salesRep(u)||salesStaff(u)||salesFinance(u);
 if(!allowed)fail('مجوز این مرحله فروش را ندارید.',403);
 const agent=mode==='price'&&!b.agentId?null:mode==='agent'&&!b.agentId?null:await salesScope(u,req(b.agentId));
 if(agent?.data.kind==='referrer'&&['payment','opening','invoice','order'].includes(mode))fail('عامل معرف حساب پورسانت دارد؛ ثبت خرید یا دریافت وجه خرید مجاز نیست.');
 const signature=JSON.stringify(b),prior:any=await db.prepare('SELECT actor,payload FROM inventory_operations WHERE id=?').bind(id).first();if(prior){if(prior.actor!==u.userId||prior.payload!==signature)fail('شناسه برای درخواست دیگری استفاده شده است.',409);return json({saved:true,repeated:true,id:prior.target||id});}
 const checks=await salesLock(db,id),stmts:D1PreparedStatement[]=[],rows=await salesRows(),membersSnapshot=await leadMembers();checks.push(leadMemberGuard(db,id,membersSnapshot));if(!u.isAdmin&&!trainingContext.getStore()){const m=membersSnapshot.find(m=>m.status==='active'&&(m.subject===u.userId||'local:'+m.id===u.userId));if(!m||JSON.stringify(JSON.parse(m.permissions))!==JSON.stringify(u.permissions))fail('دسترسی تغییر کرده است.',403);}
 const guard=(q:string,...v:any[])=>checks.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN '+q+' THEN guard ELSE 0 END WHERE id=?').bind(...v,id));
 if(agent)guard("EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?)",agent.id,agent.revision);
 const get=async(eid:string,type:string)=>{const e=await salesEntity(eid,type);if(agent&&e.data.agentId!==agent.id)fail('رکورد متعلق به این نماینده نیست.',404);guard('EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?)',e.id,e.revision);return e;};
 const revision=(e:any)=>{if(e.revision!==b.revision)fail('نسخه پرونده تغییر کرده است؛ تازه‌سازی کنید.',409);};
 const submission=salesProxyModes.includes(mode)?salesSubmission(u,agent!.id,b.requestSource,now):null;
 const put=(eid:string,type:string,data:any,old?:any)=>{const updated={...data,...(submission?{submission:old?.data.submission||submission,lastSubmission:submission}:{}),history:[...(old?.data.history||[]),{mode,actor:u.userId,actorName:u.name,at:now,notes:txt(b.notes||'',4000),...(submission?{submission}:{})}]};stmts.push(old?db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=? AND revision=?').bind(JSON.stringify(updated),now,eid,old.revision):db.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').bind(eid,type,JSON.stringify(updated),now,now));const at=rows.findIndex(r=>r.id===eid),virtual={id:eid,type,data:updated,revision:(old?.revision||0)+1,created:old?.created||now,updated:now};if(at<0)rows.push(virtual);else rows[at]=virtual;return updated;};
 const state=(e:any,states:string[])=>{if(!states.includes(e.data.state))fail('وضعیت این پرونده برای اقدام انتخابی معتبر نیست.',409);};
 const notes=()=>req(b.notes,4000);const own=()=>{if(!agent)fail('نماینده لازم است.');return agent!;};const account=()=>salesAccounts(rows,own().id,today);
 async function member(mid:string,role:'sales'|'finance'|'manager'){if(!mid)return '';const r:any=await db.prepare("SELECT permissions FROM app_members WHERE id=? AND status='active'").bind(mid).first();const actor={isAdmin:false,permissions:r?JSON.parse(r.permissions):{}} as any;if(!r||!(role==='sales'?salesStaff(actor):role==='manager'?salesManager(actor):salesFinance(actor)))fail('مسئول فعال با دسترسی این مرحله انتخاب کنید.');guard("EXISTS(SELECT 1 FROM app_members WHERE id=? AND status='active' AND permissions=?)",mid,r.permissions);return mid;}
 const installments=(items:any[],amount:string)=>{const result=arr(items,36).map((i,index)=>({id:String(index+1),due:sday(i.due),amount:money(i.amount,true)}));if(total(result,i=>i.amount)!==rial(amount))fail('جمع اقساط باید دقیقاً برابر مبلغ فاکتور باشد.');return result;};
 let target=id;
 if(mode==='agent'){
  if(agent)revision(agent);const active=b.active;if(typeof active!=='boolean')fail('وضعیت نماینده لازم است.');const name=req(b.name),phone=req(b.phone,50),address=req(b.address,2000),province=req(b.province,100),city=req(b.city,100),contact=req(b.contact,200);
  target=agent?.id||id;put(target,'sales_agent',{...agent?.data,name,phone,address,province,city,contact,contractRef:txt(b.contractRef||'',500),active,ownerId:await member(txt(b.ownerId||'',200),'sales'),financeId:await member(txt(b.financeId||'',200),'finance'),managerId:await member(txt(b.managerId??agent?.data.managerId??'',200),'manager'),kind:agent?.data.kind||'representative',creditLimit:agent?.data.creditLimit||'0',termDays:agent?.data.termDays||0},agent);
 }else if(mode==='terms'){
  revision(own());notes();put(agent!.id,'sales_agent',{...agent!.data,creditLimit:money(b.creditLimit),termDays:integer(b.termDays,0,365)},agent);target=agent!.id;
 }else if(mode==='price'){
  const productId=req(b.productId),product:any=await db.prepare("SELECT payload FROM records WHERE id=? AND kind='product'").bind(productId).first();if(!product)fail('محصول یافت نشد.',404);guard("EXISTS(SELECT 1 FROM records WHERE id=? AND kind='product' AND payload=?)",productId,product.payload);const old=b.priceId?await salesEntity(req(b.priceId),'sales_price'):null;if(old){revision(old);if(old.data.agentId!==(agent?.id||'')||old.data.productId!==productId)fail('نماینده و محصول قیمت قابل تغییر نیست.');}if(typeof b.active!=='boolean')fail('وضعیت قیمت لازم است.');
  if(rows.some(r=>r.type==='sales_price'&&r.id!==old?.id&&r.data.agentId===(agent?.id||'')&&r.data.productId===productId))fail('این قیمت وجود دارد؛ همان ردیف را ویرایش کنید.',409);target=old?.id||id;put(target,'sales_price',{agentId:agent?.id||'',productId,unitPrice:money(b.unitPrice,true),active:b.active,reference:req(b.reference,300)},old);
 }else if(mode==='target'){
  const start=sday(b.start),end=sday(b.end);if(start>end||end<today)fail('بازه تارگت معتبر نیست.');if(!['net','units'].includes(b.basis))fail('مبنای تارگت معتبر نیست.');const productIds=b.productIds;if(!Array.isArray(productIds)||productIds.length>100||new Set(productIds).size!==productIds.length)fail('فهرست محصولات معتبر نیست.');for(const pid of productIds){if(!await db.prepare("SELECT id FROM records WHERE id=? AND kind='product'").bind(req(pid)).first())fail('محصول تارگت یافت نشد.');guard("EXISTS(SELECT 1 FROM records WHERE id=? AND kind='product')",pid);}
  const tiers=arr(b.tiers,12).map(t=>({threshold:money(t.threshold,true),discountBps:integer(t.discountBps,0,9000)}));if(tiers.some((t,i)=>i>0&&(rial(t.threshold)<=rial(tiers[i-1].threshold)||t.discountBps<=tiers[i-1].discountBps)))fail('آستانه و درصد هر پلکان باید صعودی باشد.');
  const previous=b.previousId?await get(req(b.previousId),'sales_target'):null;if(previous){revision(previous);state(previous,['active']);put(previous.id,'sales_target',{...previous.data,state:'retired',replacementId:id},previous);}if(rows.some(r=>r.type==='sales_target'&&r.id!==previous?.id&&r.data.agentId===own().id&&r.data.state==='active'&&r.data.start<=end&&r.data.end>=start))fail('بازه با تارگت فعال دیگر همپوشانی دارد.');
  put(id,'sales_target',{agentId:own().id,start,end,basis:b.basis,productIds,tiers,title:req(b.title),state:'active',previousId:previous?.id||'',version:(previous?.data.version||0)+1,policy:'net-invoiced-next-order-v1',notes:notes()});
 }else if(mode==='order'){
  if(b.referrerId)await salesScope(u,req(b.referrerId));const quote=await salesQuote(own(),b.items,rows,b);for(const l of quote.lines){const p:any=await db.prepare("SELECT payload FROM records WHERE id=? AND kind='product'").bind(l.productId).first();if(!p||JSON.parse(p.payload).status!=='فعال')fail('محصول فعال نیست.');guard("EXISTS(SELECT 1 FROM records WHERE id=? AND kind='product' AND payload=?)",l.productId,p.payload);}if(quote.quoteHash!==b.quoteHash)fail('پیش‌فاکتور تغییر کرده؛ قیمت تازه را ببینید و تأیید کنید.',409);if(b.leadId){const conversion=await leadConvert(u,req(b.leadId),b.leadRevision,id,own().id,b.items,id);stmts.push(...conversion.statements);}put(id,'sales_order',{...quote,...(b.leadId?{leadId:b.leadId}:{}),code:'SO-'+id.slice(0,8).toUpperCase(),state:'submitted',createdBy:u.userId,customerReference:txt(b.customerReference||'',200),notes:txt(b.notes||'',4000),promisedDay:'',milestone:'waiting_stock'});
 }else if(['order_review','order_progress','order_cancel','invoice'].includes(mode)){
  const order=await get(req(b.orderId),'sales_order');revision(order);target=order.id;
  if(mode==='order_review'){if(order.data.salesTerms&&!salesManager(u))fail('تأیید پیش‌فاکتور فقط با مدیر فروش است.',403);if(order.data.salesTerms&&order.data.createdBy===u.userId)fail('پیشنهاد خود را مدیر دیگری تأیید کند.',403);state(order,['submitted']);if(typeof b.approved!=='boolean')fail('نتیجه بررسی لازم است.');put(order.id,'sales_order',{...order.data,state:b.approved?'sales_approved':'rejected',salesReview:notes()},order);
  }else if(mode==='order_cancel'){state(order,['submitted','sales_approved']);put(order.id,'sales_order',{...order.data,state:'cancelled',cancelReason:notes()},order);
  }else if(mode==='order_progress'){state(order,['sales_approved','approved']);if(!Object.hasOwn(salesMilestones,b.milestone))fail('مرحله معتبر انتخاب کنید.');const promisedDay=sday(b.promisedDay);if(promisedDay<today)fail('موعد وعده جدید در گذشته نباشد.');put(order.id,'sales_order',{...order.data,promisedDay,milestone:b.milestone,progressNote:notes()},order);
  }else{
   state(order,['sales_approved']);if(!own().data.active)fail('نمایندگی غیرفعال است.');const a=account(),exposure=rial(a.balance)+rial(order.data.amount),limit=rial(agent!.data.creditLimit);const exception=exposure>limit||rial(a.overdue)>BigInt(0);if(exception&&(b.creditException!==true||!txt(b.exceptionReason||'',2000)))fail('سقف اعتبار یا بدهی معوق مانع تأیید است؛ تصمیم استثنای مستند مالی لازم است.');
   const reference=req(b.reference,300);if(rows.some(r=>r.type==='sales_invoice'&&r.data.reference===reference))fail('شماره فاکتور تکراری است.');const plan=order.data.salesTerms?termsPlan(order.data.amount,order.data.salesTerms,today):installments(b.installments,order.data.amount);if(order.data.salesTerms&&b.installments&&JSON.stringify(b.installments.map((p:any)=>({due:p.due,amount:p.amount})))!==JSON.stringify(plan.map(p=>({due:p.due,amount:p.amount}))))fail('اقساط باید عین شرایط مصوب مدیر باشد.');if(plan.some(i=>i.due<today))fail('سررسید فاکتور جدید در گذشته نباشد.');
   put(id,'sales_invoice',{agentId:own().id,orderId:order.id,reference,day:today,salesTerms:order.data.salesTerms||null,referral:order.data.referral||null,lines:order.data.lines,amount:order.data.amount,discount:order.data.discount,installments:plan,openingId:'',creditReview:{exposure:String(exposure),limit:String(limit),overdue:a.overdue,exception,reason:exception?req(b.exceptionReason,2000):'',by:u.userId},province:own().data.province});
   put(order.id,'sales_order',{...order.data,state:'approved',invoiceId:id,approvedBy:u.userId,approvedAt:now},order);
  }
 }else if(mode==='payment'){
  const old=b.paymentId?await get(req(b.paymentId),'sales_payment'):null;if(old){revision(old);state(old,['pending','rejected']);if(old.data.openingId)fail('افتتاحیه از فرم پرداخت تغییر نمی‌کند.');}
  if(!['bank','cash','check'].includes(b.method))fail('روش پرداخت معتبر نیست.');const amount=money(b.amount,true),day=sday(b.day);if(day>today)fail('تاریخ پرداخت در آینده نیست.');const bank=txt(b.bank||'',200),normalizedBank=bank.toLowerCase().replace(/\s+/g,''),reference=req(b.reference,300),normalizedReference=reference.toLowerCase().replace(/\s+/g,'');if(b.method!=='cash'&&!bank)fail('بانک لازم است.');if(rows.some(r=>r.type==='sales_payment'&&r.id!==old?.id&&r.data.method===b.method&&(r.data.normalizedBank||r.data.bank?.toLowerCase().replace(/\s+/g,''))===normalizedBank&&r.data.normalizedReference===normalizedReference))fail('این مرجع پرداخت قبلاً ثبت شده است؛ سابقه را بررسی کنید.',409);
  const file=b.fileId?await get(req(b.fileId),'sales_file'):null;if(b.method!=='cash'&&!file)fail('تصویر رسید یا چک همین نماینده لازم است.');const checkDue=b.method==='check'?sday(b.checkDue):'';const cashOrderId=txt(b.cashOrderId||'',200),checkInvoiceId=txt(b.checkInvoiceId||'',200);if(cashOrderId){if(b.method==='check')fail('وجه نقد خرید جدید نمی‌تواند چک باشد.');const o=await get(cashOrderId,'sales_order');state(o,['sales_approved','approved']);if(!o.data.salesTerms)fail('خرید فاقد شرایط مصوب است.');if(!rows.some(r=>r.type==='sales_invoice'&&r.data.orderId===o.id))fail('ابتدا فاکتور خرید جدید صادر شود تا وجه نقد به قسط مصوب متصل شود.');}if(checkInvoiceId)await get(checkInvoiceId,'sales_invoice');target=old?.id||id;put(target,'sales_payment',{agentId:own().id,method:b.method,amount,day,bank,normalizedBank,reference,normalizedReference,fileId:file?.id||'',checkDue,cashOrderId,checkInvoiceId,state:'pending',submittedBy:u.userId,notes:txt(b.notes||'',4000)},old);
 }else if(['payment_review','check_status','payment_reverse'].includes(mode)){
  const p=await get(req(b.paymentId),'sales_payment');revision(p);target=p.id;let next='';
  if(mode==='payment_review'){state(p,['pending']);if(typeof b.approved!=='boolean')fail('نتیجه بررسی لازم است.');next=b.approved?(p.data.method==='check'?'received':'cleared'):'rejected';}
  if(mode==='check_status'){if(p.data.method!=='check')fail('این پرداخت چک نیست.');if(!['cleared','bounced'].includes(b.state))fail('وضعیت چک معتبر نیست.');state(p,b.state==='cleared'?['received']:['received','cleared']);if(b.state==='cleared'&&p.data.checkDue>today)fail('تاریخ وصول چک هنوز نرسیده است.');next=b.state;}
  if(mode==='payment_reverse'){state(p,['cleared']);next='reversed';}
  const events=[...(p.data.financialEvents||[])];if(next==='cleared'||p.data.state==='cleared')events.push({id,day:today,at:now,delta:next==='cleared'?p.data.amount:String(-rial(p.data.amount)),state:next});
  put(p.id,'sales_payment',{...p.data,financialEvents:events,state:next,reviewedBy:u.userId,reviewedAt:now,reviewNotes:notes()},p);
 }else if(mode==='allocate'){
  const plan=allocationPlan(rows,own().id,req(b.creditId),today);if(!plan.allocations.length)fail('اعتبار آزاد قابل تخصیص وجود ندارد.');
  if(b.allocations&&JSON.stringify(b.allocations)!==JSON.stringify(plan.allocations))fail('تخصیص باید مطابق اولویت خودکار باشد؛ پیش‌نمایش را تازه کنید.',409);
  plan.allocations.forEach((l,i)=>put(id+':'+i,'sales_allocation',{agentId:own().id,creditId:b.creditId,...l,by:u.userId,policy:plan.policy}));
  plan.recoveries.forEach((r,i)=>put(id+':recovery:'+i,'sales_check_recovery',{agentId:own().id,creditId:b.creditId,...r,by:u.userId}));notes();
 }else if(mode==='return_request'){
  const invoice=await get(req(b.invoiceId),'sales_invoice');if(invoice.data.openingId)fail('برگشت افتتاحیه بدون اتصال سریال قابل ثبت نیست.');const deviceIds=arr(b.deviceIds,100).map(v=>req(v));if(new Set(deviceIds).size!==deviceIds.length)fail('سریال تکراری است.');const deliveries=await salesDelivery(rows,[own().id]),lines:any[]=[],serials:string[]=[];
  for(const did of deviceIds){const sale=deliveries.find(s=>s.orderId===invoice.data.orderId&&s.state==='delivered'&&s.deviceIds.includes(did))!;if(!sale)fail('سریال باید تحویل‌شده همین فاکتور باشد.');if(rows.some(r=>r.type==='sales_return'&&r.data.state!=='rejected'&&r.data.deviceIds.includes(did)))fail('برای این سریال پرونده برگشت موجود است.');const original=invoice.data.lines.find((l:any)=>l.productId===sale.productId);if(!original)fail('ردیف فاکتور با سریال منطبق نیست.');const productLine=lines.find(l=>l.productId===sale.productId);if(productLine){productLine.quantity++;productLine.net=String(rial(productLine.net)+rial(original.unitNet));}else lines.push({productId:sale.productId,name:original.name,quantity:1,unitNet:original.unitNet,net:original.unitNet});const r:any=await db.prepare("SELECT payload FROM records WHERE id=? AND kind='device'").bind(did).first();serials.push(r?JSON.parse(r.payload).code:did);}
  put(id,'sales_return',{agentId:own().id,invoiceId:invoice.id,deviceIds,serials,lines,amount:String(total(lines,l=>l.net)),state:'requested',reason:notes()});
 }else if(mode==='return_receive'){
  const r=await get(req(b.returnId),'sales_return');revision(r);state(r,['requested']);if(b.physicallyReceived!==true)fail('دریافت فیزیکی باید تأیید شود.');const receipt=req(b.receipt,300);for(const did of r.data.deviceIds){const build=await salesEntity(did,'build');guard('EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?)',build.id,build.revision);if(build.data.state!=='delivered')fail('وضعیت دستگاه برای برگشت معتبر نیست.');stmts.push(db.prepare('INSERT INTO inventory_balances(id,item_id,warehouse,quantity) VALUES(?,?,?,0) ON CONFLICT(id) DO NOTHING').bind(did+'@quarantine',did,'quarantine'),db.prepare("UPDATE inventory_balances SET quantity=quantity+1000 WHERE item_id=? AND warehouse='quarantine'").bind(did),db.prepare('INSERT INTO inventory_entries(id,operation_id,item_id,warehouse,delta) VALUES(?,?,?,?,1000)').bind(crypto.randomUUID(),id,did,'quarantine'));put(did,'build',{...build.data,state:'sales_return_quarantine',returnId:r.id},build);}
  put(r.id,'sales_return',{...r.data,state:'returned',receipt,receivedBy:u.userId,receivedAt:now,condition:notes()},r);target=r.id;
 }else if(mode==='return_review'){
  const r=await get(req(b.returnId),'sales_return');revision(r);if(typeof b.approved!=='boolean')fail('نتیجه بررسی لازم است.');state(r,b.approved?['returned']:['requested']);put(r.id,'sales_return',{...r.data,state:b.approved?'credited':'rejected',reviewedBy:u.userId,reviewedAt:now,reviewNotes:notes()},r);target=r.id;
 }else if(mode==='opening'){
  const source=req(b.source,200),asOf=sday(b.asOf),reference=req(b.reference,300);if(asOf>today)fail('تاریخ مبنا در آینده نیست.');const items=arr(b.items,100).map((i,index)=>{if(!['invoice','credit','check'].includes(i.kind))fail('نوع ردیف افتتاحیه معتبر نیست.');const day=sday(i.day);if(day>asOf)fail('تاریخ ردیف پس از تاریخ مبنا نیست.');return {index,kind:i.kind,legacyId:req(i.legacyId,200),reference:req(i.reference,300),amount:money(i.amount,true),day,due:i.kind==='credit'?'':sday(i.due),bank:i.kind==='check'?req(i.bank,200):'',key:JSON.stringify([source,req(i.legacyId,200)])};});
  if(new Set(items.map(i=>i.key)).size!==items.length)fail('شناسه قدیمی در فایل تکرار شده است.');const debt=String(total(items.filter(i=>i.kind==='invoice'),i=>i.amount)),credit=String(total(items.filter(i=>i.kind==='credit'),i=>i.amount));if(money(b.expectedDebt)!==debt||money(b.expectedCredit)!==credit)fail('جمع اعلامی منبع با ردیف‌ها تطبیق ندارد.');
  put(id,'sales_opening',{agentId:own().id,source,asOf,reference,items,debt,credit,state:'pending',preparedBy:u.userId,notes:notes()});
 }else if(mode==='opening_review'){
  const o=await get(req(b.openingId),'sales_opening');revision(o);state(o,['pending']);if(typeof b.approved!=='boolean')fail('نتیجه تطبیق لازم است.');if(b.approved){for(const i of o.data.items){if(rows.some(r=>['sales_invoice','sales_payment'].includes(r.type)&&r.data.openingKey===i.key||i.kind==='invoice'&&r.type==='sales_invoice'&&!r.data.openingId&&r.data.reference===i.reference||i.kind==='check'&&r.type==='sales_payment'&&r.data.method==='check'&&r.data.reference===i.reference&&r.data.bank.toLowerCase().replace(/\s+/g,'')===i.bank.toLowerCase().replace(/\s+/g,'')))fail('این ردیف قدیمی قبلاً وارد شده است: '+i.legacyId,409);const eid=o.id+':'+i.index,common={agentId:own().id,openingId:o.id,openingKey:i.key,legacyId:i.legacyId,source:o.data.source,reference:i.reference,amount:i.amount,day:i.day};if(i.kind==='invoice')put(eid,'sales_invoice',{...common,orderId:'',lines:[],discount:'0',installments:[{id:'1',due:i.due,amount:i.amount}],province:own().data.province});else put(eid,'sales_payment',{...common,method:i.kind==='check'?'check':'opening',state:i.kind==='check'?'received':'cleared',checkDue:i.due,bank:i.bank,normalizedReference:i.reference.toLowerCase().replace(/\s+/g,''),reviewedBy:u.userId});}}
  put(o.id,'sales_opening',{...o.data,state:b.approved?'approved':'rejected',reconciledBy:u.userId,reconciledAt:now,reconciliation:notes()},o);target=o.id;
 }else fail('عملیات ناشناخته است.');
 // Allocate newly confirmed credit and free balances atomically with the financial event.
 if(agent&&['invoice','payment_review','check_status','return_review','opening_review'].includes(mode)){
  const credits=salesAccounts(rows,agent.id,today).credits.sort((a,b)=>a.created.localeCompare(b.created)||a.id.localeCompare(b.id));
  for(const [ci,c] of credits.entries()){const plan=allocationPlan(rows,agent.id,c.id,today);plan.allocations.forEach((l,i)=>put(id+':auto:'+ci+':'+i,'sales_allocation',{agentId:agent.id,creditId:c.id,...l,policy:plan.policy,by:u.userId}));plan.recoveries.forEach((r,i)=>put(id+':recovery:'+ci+':'+i,'sales_check_recovery',{agentId:agent.id,creditId:c.id,...r,by:u.userId}));}
 }
 await db.batch([db.prepare('INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,?,?,?,?,1)').bind(id,'sales_'+mode,signature,u.userId,now),...checks,...stmts,db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,target,'sales_'+mode,signature,now)]);
 let followupPending=false;try{await syncSalesTasks();if(b.leadId)await syncLeadTasks();await scanSalesMonitor({reports:false,source:'event'});}catch{followupPending=true;}return json({saved:true,id:target,followupPending});
 }catch(e){return accessResponse(e)||json({error:/constraint|SQLITE|D1/i.test(String(e))?'اطلاعات هم‌زمان تغییر کرده است؛ فهرست را تازه و نتیجه را بررسی کنید.':'ثبت انجام نشد؛ ورودی‌ها را بررسی کنید.'},409)}}
