import {checkOrigin,AccessError,accessResponse} from '@/lib/authorization';
import {boundedBody,firmwareBucket} from '@/lib/firmware-storage';
import {expenseUser,expenseRows,expenseJob,expenseVisible} from '@/lib/hospital-expenses';
import {hrow,hreq} from '@/lib/hospital';
import {memberId} from '@/lib/duties';
import {storage} from '@/lib/storage';
import {sha256} from '@/lib/firmware';
export async function GET(request:Request){try{const u=await expenseUser(),mid=await memberId(u)||'',f=await hrow(hreq(new URL(request.url).searchParams.get('id')),'expense_file');if(f.data.ownerId!==mid&&!u.isAdmin&&!(await expenseRows()).some(r=>r.type==='expense_claim'&&r.data.fileIds.includes(f.id)&&expenseVisible(u,mid,r)))throw new AccessError('فایل پیدا نشد.',404);const object=await firmwareBucket().get(f.data.objectKey);if(!object)throw new AccessError('فایل در دسترس نیست.',404);return new Response(object.body,{headers:{'Content-Type':f.data.mime,'Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(f.data.filename),'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}catch(e){return accessResponse(e)||Response.json({error:'دریافت فایل انجام نشد.'},{status:503})}}
export async function POST(request:Request){try{checkOrigin(request);const u=await expenseUser(),mid=await memberId(u)||'',q=new URL(request.url).searchParams,id=hreq(q.get('id')),jobId=hreq(q.get('job')),j=await expenseJob(u,jobId);if(!mid||mid!==j.data.technicianId)throw new AccessError('فقط تکنسین تعیین‌شده مجاز است.',403);if(!/^[a-f0-9-]{36}$/i.test(id))throw new AccessError('شناسه نامعتبر.',400);const bytes=await boundedBody(request,10*1024*1024),mime=request.headers.get('content-type')?.split(';')[0]||'',filename=hreq(q.get('filename'),200),head=new TextDecoder().decode(bytes.slice(0,5));if(!bytes.length||!(mime==='application/pdf'&&head==='%PDF-'||mime==='image/png'&&bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71||mime==='image/jpeg'&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255))throw new AccessError('PDF یا عکس PNG/JPEG معتبر، حداکثر ۱۰ مگابایت لازم است.',400);const hash=await sha256(bytes.buffer as ArrayBuffer),db=storage(),old:any=await db.prepare("SELECT data FROM flow_entities WHERE id=? AND type='expense_file'").bind(id).first();if(old){const d=JSON.parse(old.data);if(d.ownerId!==mid||d.jobId!==jobId||d.sha256!==hash||d.filename!==filename)throw new AccessError('شناسه فایل تکراری متفاوت.',409);return Response.json({id,repeated:true});}const key='expense/'+id+'/'+crypto.randomUUID(),now=new Date().toISOString();await firmwareBucket().put(key,bytes,{httpMetadata:{contentType:mime}});try{await db.batch([db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,'expense_file',?,1,?,?)").bind(id,JSON.stringify({ownerId:mid,actor:u.userId,jobId,filename,mime,byteSize:bytes.length,sha256:hash,objectKey:key}),now,now),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,id,'expense_upload',JSON.stringify({filename,jobId,sha256:hash}),now)]);}catch(e){await firmwareBucket().delete(key);throw e;}return Response.json({id,filename},{headers:{'Cache-Control':'no-store'}});}catch(e){return accessResponse(e)||Response.json({error:'بارگذاری انجام نشد.'},{status:409})}}
