"use client";
import {useState,useEffect,useMemo} from "react";
import {Activity,Boxes,PackageCheck,ClipboardCheck,Wrench,ShieldCheck,Search,Plus,ArrowUpLeft,Download,FlaskConical,RefreshCw,Link2,Box,Factory,ChevronLeft} from "lucide-react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from "@/components/ui/table";
import {fields,names,label,editable,type Row,type Kind} from "@/lib/model";
import {demo as examples} from "@/lib/demo";
const nf=new Intl.NumberFormat("fa-IR");const num=(n:number)=>nf.format(n);
const date=(s?:string)=>s?new Date(s.length===10?s+"T12:00:00Z":s).toLocaleDateString("fa-IR"):"—";
const sections=[{key:"overview",title:"نمای کلی",icon:Activity},{key:"device",title:"شناسنامه دستگاه‌ها",icon:PackageCheck},{key:"batch",title:"قطعات و بچ‌ها",icon:Boxes},{key:"event",title:"تولید و تحویل",icon:Factory},{key:"service",title:"خدمات پس از فروش",icon:Wrench},{key:"action",title:"اقدامات اصلاحی",icon:ShieldCheck}];
function Badge({value}:{value:string}){return <span className={"badge "+(["تأیید","تحویل","بسته‌شده","تعمیرشده"].includes(value)?"good":["قرنطینه","رد","مردود"].includes(value)?"bad":["باز","در حال بررسی","در حال اجرا","نیاز به دوباره‌کاری"].includes(value)?"warn":"")}>{value}</span>}
export default function Home(){
 const [live,setLive]=useState<Row[]>([]),[demo,setDemo]=useState(true),[tab,setTab]=useState("overview"),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[selected,setSelected]=useState<Row|null>(null),[form,setForm]=useState<Kind|null>(null),[draft,setDraft]=useState<Record<string,string>>({}),[editing,setEditing]=useState<Row|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[formError,setFormError]=useState(""),[message,setMessage]=useState("");
 const rows=demo?examples:live;const of=(k:Kind)=>rows.filter(r=>r.kind===k);const find=(id?:string)=>rows.find(r=>r.id===id);const refLabel=(id?:string)=>{const r=find(id);return r?label(r):"—"};
 async function reload(){setLoading(true);setError("");try{const r=await fetch("/api/records");const d=await r.json() as {error?:string;records:Row[]};if(!r.ok)throw new Error(d.error);setLive(d.records);}catch(e){setError(e instanceof Error?e.message:"دریافت اطلاعات انجام نشد.");}finally{setLoading(false)}}
 useEffect(()=>{void reload()},[]);
 useEffect(()=>{const c=(document as any).modelContext;if(!c?.registerTool)return;const controller=new AbortController();try{Promise.resolve(c.registerTool({name:"search_trace_records",title:"جست‌وجوی سوابق رهگیری",description:"Search visible demo or real traceability records without modifying them.",inputSchema:{type:"object",properties:{query:{type:"string"}},required:["query"],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:unknown)=>{if(!input||typeof (input as any).query!=="string")throw new Error("query must be a string");const q=(input as any).query.trim();setQuery(q);setFilter("all");setTab("device");return {mode:demo?"demo":"real",matches:rows.filter(r=>JSON.stringify(r.data).toLowerCase().includes(q.toLowerCase())).map(r=>({id:r.id,kind:r.kind,label:label(r)}))};}},{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();},[demo,rows]);
 const events=(id:string)=>of("event").filter(r=>r.data.device===id).sort((a,b)=>(a.data.date||a.created).localeCompare(b.data.date||b.created)||a.created.localeCompare(b.created));
 function status(d:Row){const e=events(d.id);return e.length?e[e.length-1].data.stage:"شروع تولید";}
 const devices=of("device"),batches=of("batch"),services=of("service"),actions=of("action");const delivered=devices.filter(d=>events(d.id).some(e=>e.data.stage==="تحویل"));
 const openServices=services.filter(s=>!["بسته‌شده","تعمیرشده"].includes(s.data.status));const openActions=actions.filter(a=>a.data.status!=="بسته‌شده");
 function navigate(t:string){setTab(t);setQuery("");setFilter("all");}
 function start(k:Kind,initial:Record<string,string>={}){setEditing(null);setForm(k);setDraft({date:new Date().toISOString().slice(0,10),...initial});setFormError("");setSelected(null);}
 async function submit(e:React.FormEvent){e.preventDefault();if(!form||busy)return;setFormError("");if(demo){setFormError("برای ثبت اطلاعات، ابتدا به «اطلاعات شرکت» بروید.");return;}setBusy(true);try{const res=await fetch("/api/records",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing?{id:editing.id,data:draft,previous:JSON.stringify(editing.data)}:{kind:form,data:draft})});const result=await res.json() as {error?:string;record:Row};if(!res.ok)throw new Error(result.error);setLive(prev=>[result.record,...prev.filter(r=>r.id!==result.record.id)]);setMessage("اطلاعات با موفقیت ذخیره شد.");setForm(null);setEditing(null);}catch(e){setFormError(e instanceof Error?e.message:"ذخیره انجام نشد.");}finally{setBusy(false)}}
 function exportData(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),mode:demo?"demo":"real",records:rows},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="nafasyar-trace-"+(demo?"demo":"records")+".json";a.click();URL.revokeObjectURL(url);}
 function match(r:Row){const q=query.toLowerCase().trim();if(!q)return true;let values=JSON.stringify(r.data);if(r.data.device)values+=refLabel(r.data.device);if(r.kind==="device")values+=events(r.id).map(e=>refLabel(e.data.batch)).join(" ");return values.toLowerCase().includes(q);}
 const current=tab==="overview"?[]:of(tab as Kind).filter(r=>match(r)&&(filter==="all"||(r.kind==="device"?status(r):r.data.status||r.data.stage)===filter));
 function recordTable(list:Row[],kind:Kind){const headers:Record<Kind,string[]>={device:["سریال / مدل","نسخه طراحی","آخرین مرحله","تاریخ تولید",""],batch:["کد بچ / قطعه","تأمین‌کننده","مقدار ورودی","کنترل ورودی",""],event:["دستگاه","مرحله","مسئول","تاریخ",""],service:["دستگاه / شکایت","کارکرد","کارشناس","وضعیت",""],action:["موضوع","مسئول","مهلت","وضعیت",""]};return list.length?<Table><TableHeader><TableRow>{headers[kind].map((h,i)=><TableHead className="tablehead" key={i}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{list.map(r=><TableRow key={r.id}>
 <TableCell className="tablecell"><button className="link" onClick={()=>setSelected(r)}>{kind==="device"||kind==="batch"?<><span className="code">{r.data.code}</span><p className="subtle">{r.data.model||r.data.part}</p></>:kind==="action"?r.data.title:<><span className="code">{refLabel(r.data.device)}</span>{kind==="service"&&<p className="subtle">{r.data.complaint}</p>}</>}</button></TableCell>
 <TableCell className="tablecell">{kind==="device"?<span className="code">{r.data.design}</span>:kind==="batch"?r.data.supplier:kind==="event"?<Badge value={r.data.stage}/>:kind==="service"?num(Number(r.data.hours))+" ساعت":r.data.owner}</TableCell>
 <TableCell className="tablecell">{kind==="device"?<Badge value={status(r)}/>:kind==="batch"?num(Number(r.data.quantity))+" "+r.data.unit:kind==="action"?date(r.data.due):r.data.operator}</TableCell>
 <TableCell className="tablecell">{kind==="device"||kind==="event"?date(r.data.date):<Badge value={r.data.status}/>}</TableCell>
 <TableCell className="tablecell"><button className="link" onClick={()=>setSelected(r)} aria-label={"مشاهده "+label(r)}><ArrowUpLeft size={18}/></button></TableCell>
 </TableRow>)}</TableBody></Table>:<div className="empty"><Box size={30}/><h3>رکوردی پیدا نشد</h3><p className="subtle">{query||filter!=="all"?"جست‌وجو یا فیلتر را تغییر بدهید.":"با ثبت اولین "+names[kind]+" شروع کنید."}</p>{!query&&filter==="all"&&<button className="btn primary" style={{marginTop:15}} onClick={()=>start(kind)}>ثبت {names[kind]}<Plus size={16}/></button>}</div>}
 const detail=selected?find(selected.id)||selected:null;
 return <><header className="topbar"><div className="topinner"><div className="brand"><Activity size={35}/><div><div className="wordmark">nafasyar<span style={{color:"#72d5d0"}}> / </span><span style={{fontSize:18,fontFamily:"Tahoma"}}>رهگیری</span></div><p className="subtle">تولید، کیفیت و خدمات پس از فروش</p></div></div><span className="topbadge">نفس‌یار طب · نسخه اولیه</span></div></header>
 <main className="shell"><div className="heading"><div><p className="subtle">مدیریت چرخه عمر محصول</p><h1>از قطعه تا عملکرد دستگاه</h1></div><div className="tools"><button className="btn" onClick={exportData}><Download size={16}/>خروجی اطلاعات</button><button className="btn primary" onClick={()=>start("device")}><Plus size={18}/>ثبت دستگاه</button></div></div>
 <div className="notice"><span><FlaskConical size={17} style={{display:"inline",marginLeft:8}}/>{demo?"محیط نمونه — تمام رکوردها و شاخص‌های این نما آموزشی هستند.":"اطلاعات شرکت — ثبت‌ها ذخیره می‌شوند. اتصال به همکاران سیستم فعال نیست."}</span><button className="link" onClick={()=>{setDemo(!demo);setSelected(null);setForm(null);setQuery("");setFilter("all");setMessage("")}}>{demo?"شروع ثبت اطلاعات شرکت":"مشاهده داده‌های نمونه"}<ChevronLeft size={16} style={{display:"inline"}}/></button></div>
 {!demo&&error&&<div className="notice error" role="alert" style={{marginTop:12}}>{error}<button className="link" onClick={reload}>تلاش مجدد</button></div>}{message&&<div className="notice" role="status" style={{marginTop:12}}>{message}<button onClick={()=>setMessage("")} aria-label="بستن پیام">×</button></div>}
 <div className="stats">{[{n:devices.length,t:"دستگاه ثبت‌شده",i:PackageCheck},{n:batches.length,t:"بچ قابل رهگیری",i:Boxes},{n:openServices.length,t:"پرونده خدمات باز",i:Wrench,w:true},{n:openActions.length,t:"اقدام اصلاحی باز",i:ShieldCheck,w:true}].map(s=><div className={"stat "+(s.w?"warn":"")} key={s.t}><div><p className="subtle">{s.t}</p><strong>{!demo&&loading?"…":num(s.n)}</strong></div><s.i/></div>)}</div>
 <Tabs value={tab} onValueChange={navigate} dir="rtl"><TabsList className="navtabs" aria-label="بخش‌های رهگیری">{sections.map(s=><TabsTrigger key={s.key} value={s.key}><s.icon className="tabicon"/>{s.title}</TabsTrigger>)}</TabsList>
 <TabsContent value="overview"><div className="panel"><div className="panelhead"><div><h2>شناسنامه دستگاه‌ها</h2><p className="subtle">رد قطعات، رویدادهای تولید و سوابق خدمات در یک نگاه</p></div><button className="link" onClick={()=>navigate("device")}>همه دستگاه‌ها <ArrowUpLeft size={16} style={{display:"inline"}}/></button></div>{recordTable(devices.slice(0,5),"device")}</div>
 <div className="twocol"><section className="panel"><div className="panelhead"><h2>پیگیری‌های کیفیت</h2><span className="badge warn">{num(openActions.length)} اقدام باز</span></div><div className="inside">{openActions.length?openActions.slice(0,4).map(a=><div className="recordline" key={a.id}><div><button className="link" onClick={()=>setSelected(a)}>{a.data.title}</button><p className="subtle">{a.data.owner} · مهلت {date(a.data.due)}</p></div><Badge value={a.data.status}/></div>):<p className="subtle">اقدام اصلاحی بازی ثبت نشده است.</p>}<button className="btn" style={{marginTop:18}} onClick={()=>start("action")}><Plus size={16}/>ثبت اقدام اصلاحی</button></div></section>
 <section className="panel"><div className="panelhead"><h2>گزارش خدمات به تفکیک بچ</h2></div><div className="inside">{batches.length?batches.slice(0,4).map(b=>{const ds=devices.filter(d=>events(d.id).some(e=>e.data.batch===b.id)||services.some(s=>s.data.device===d.id&&s.data.replacement===b.id));const report=ds.filter(d=>services.some(s=>s.data.device===d.id));return <div className="recordline" key={b.id}><div style={{width:"100%"}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><button className="link code" onClick={()=>setSelected(b)}>{b.data.code}</button><span className="subtle">{num(report.length)} از {num(ds.length)} دستگاه</span></div><div className="bar"><span style={{width:(ds.length?report.length/ds.length*100:0)+"%"}}/></div></div></div>}):<p className="subtle">پس از ثبت قطعات مصرفی، مقایسه در این بخش نمایش داده می‌شود.</p>}</div><p className="footnote">وجود گزارش خدمات به معنی خرابی این قطعه نیست؛ عمر کارکرد دستگاه‌ها نیز ممکن است متفاوت باشد.</p></section></div></TabsContent>
 {sections.slice(1).map(section=><TabsContent value={section.key} key={section.key}><div className="panel"><div className="panelhead"><div className="search"><Search size={18}/><input aria-label="جست‌وجوی رکورد" placeholder={section.key==="device"?"جست‌وجوی سریال، مدل یا کد بچ…":"جست‌وجو در رکوردها…"} value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="tools"><Select dir="rtl" value={filter} onValueChange={setFilter}><SelectTrigger aria-label="فیلتر وضعیت"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">همه وضعیت‌ها</SelectItem>{Array.from(new Set(of(section.key as Kind).map(r=>r.kind==="device"?status(r):r.data.status||r.data.stage).filter(Boolean))).map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><button className="btn primary" onClick={()=>start(section.key as Kind)}><Plus size={16}/>ثبت {names[section.key as Kind]}</button></div></div>{!demo&&loading?<div className="empty" role="status">در حال دریافت اطلاعات…</div>:recordTable(current,section.key as Kind)}<div className="footnote">{num(current.length)} رکورد {demo?"نمونه":"ثبت‌شده"}{section.key==="device"&&" · برای باز کردن شناسنامه، روی سریال کلیک کنید."}</div></div></TabsContent>)}
 </Tabs><div style={{display:"flex",justifyContent:"space-between",marginTop:24,gap:10}}><span className="subtle">{demo?"داده‌های آموزشی برای بررسی گردش کار":"ثبت مستقل از همکاران سیستم"}</span><button className="link subtle" onClick={reload} disabled={loading}><RefreshCw size={14} style={{display:"inline",marginLeft:6}}/>تازه‌سازی</button></div></main>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy)setForm(null)}}><DialogContent className="modal sm:max-w-2xl"><DialogTitle style={{paddingRight:22}}>{editing?"به‌روزرسانی":"ثبت"} {form?names[form]:""}</DialogTitle><DialogDescription>{demo?"برای ثبت، به محیط اطلاعات شرکت بروید.":"موارد ستاره‌دار الزامی‌اند. تاریخ را با تقویم انتخاب کنید."}</DialogDescription>{form&&<form onSubmit={submit}><div className="formgrid">{fields[form].map(f=><label className={"field "+(f.type==="textarea"?"wide":"")} key={f.key}><span>{f.label}{f.required&&<span style={{color:"#b45b33"}}> *</span>}</span>{f.options||f.ref?<Select dir="rtl" value={draft[f.key]||"__none"} onValueChange={v=>setDraft({...draft,[f.key]:v==="__none"?"":v})} disabled={!!editing&&!editable[editing.kind]?.includes(f.key)}><SelectTrigger className="full" aria-label={f.label}><SelectValue placeholder="انتخاب کنید"/></SelectTrigger><SelectContent><SelectItem value="__none">انتخاب کنید</SelectItem>{f.options?.map(o=><SelectItem value={o} key={o}>{o}</SelectItem>)}{f.ref&&of(f.ref).map(r=><SelectItem value={r.id} key={r.id}>{label(r)}{r.data.part?" · "+r.data.part:""}</SelectItem>)}</SelectContent></Select>:f.type==="textarea"?<textarea disabled={!!editing&&!editable[editing.kind]?.includes(f.key)} required={f.required} maxLength={4000} value={draft[f.key]||""} onChange={e=>setDraft({...draft,[f.key]:e.target.value})}/>:<input disabled={!!editing&&!editable[editing.kind]?.includes(f.key)} required={f.required} type={f.type||"text"} step={f.type==="number"?"any":undefined} min={f.type==="number"?0:undefined} maxLength={4000} value={draft[f.key]||""} onChange={e=>setDraft({...draft,[f.key]:e.target.value})}/>}</label>)}</div>{formError&&<p className="notice error" role="alert" style={{marginTop:16}}>{formError}</p>}<div className="tools" style={{marginTop:22}}>{demo?<button type="button" className="btn primary" onClick={()=>{setDemo(false);setForm(null);setSelected(null)}}>رفتن به اطلاعات شرکت</button>:<button className="btn primary" disabled={busy||loading||!!error} type="submit">{busy?"در حال ذخیره…":"ذخیره اطلاعات"}</button>}<button type="button" className="btn" disabled={busy} onClick={()=>setForm(null)}>انصراف</button></div></form>}</DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="modal sm:max-w-3xl"><DialogTitle style={{paddingRight:22}}>{detail?names[detail.kind]:""} <span className="code">{detail?label(detail):""}</span></DialogTitle><DialogDescription>{demo?"شناسنامه نمونه · اطلاعات آموزشی":"سوابق ثبت‌شده در سامانه"}</DialogDescription>{detail&&<>
 {detail.kind==="device"&&<div className="steps">{["مونتاژ","آزمون نهایی","بسته‌بندی","تحویل"].map(stage=><div className={"step "+(events(detail.id).some(e=>e.data.stage===stage)?"done":"")} key={stage}>{stage}</div>)}</div>}
 <div className="detailgrid">{fields[detail.kind].filter(f=>detail.data[f.key]).map(f=><div className="kv" key={f.key}><p>{f.label}</p>{f.ref?<button className="link code" onClick={()=>setSelected(find(detail.data[f.key])||null)}>{refLabel(detail.data[f.key])} <Link2 size={14} style={{display:"inline"}}/></button>:<strong>{f.type==="date"?date(detail.data[f.key]):detail.data[f.key]}</strong>}</div>)}</div>
 {detail.kind==="device"&&<><div className="detailsection"><h2>قطعات و مواد مصرفی اولیه</h2>{events(detail.id).filter(e=>e.data.stage==="مصرف قطعه").map(e=><div className="recordline" key={e.id}><div><button className="link" onClick={()=>setSelected(find(e.data.batch)||null)}>{find(e.data.batch)?.data.part} <span className="code">{refLabel(e.data.batch)}</span></button><p className="subtle">{e.data.partSerial?"سریال قطعه: "+e.data.partSerial:"ثبت در سطح بچ"}</p></div><span>{num(Number(e.data.quantity))} {find(e.data.batch)?.data.unit}</span></div>)}{!events(detail.id).some(e=>e.data.stage==="مصرف قطعه")&&<p className="subtle">هنوز قطعه‌ای به این دستگاه متصل نشده است.</p>}</div>
 <div className="detailsection"><h2>تاریخچه تولید و تحویل</h2><div className="timeline" style={{marginTop:16}}>{events(detail.id).map(e=><article key={e.id}><button className="link" onClick={()=>setSelected(e)}>{e.data.stage}</button><p className="subtle">{date(e.data.date)} · {e.data.operator}</p><p>{e.data.customer||e.data.notes||refLabel(e.data.batch)}</p>{e.data.result&&<Badge value={e.data.result}/>}</article>)}</div></div>
 <div className="detailsection"><h2>خدمات و تعویض قطعات</h2>{services.filter(s=>s.data.device===detail.id).map(s=><div className="recordline" key={s.id}><div><button className="link" onClick={()=>setSelected(s)}>{s.data.complaint}</button><p className="subtle">{date(s.data.date)} · {num(Number(s.data.hours))} ساعت</p>{s.data.replacement&&<p className="subtle">تعویض {refLabel(s.data.batch)} با {refLabel(s.data.replacement)}</p>}</div><Badge value={s.data.status}/></div>)}{!services.some(s=>s.data.device===detail.id)&&<p className="subtle">گزارش خدماتی ثبت نشده است.</p>}</div>
 <div className="tools"><button className="btn primary" onClick={()=>start("event",{device:detail.id})}>ثبت رویداد تولید / تحویل</button><button className="btn" onClick={()=>start("service",{device:detail.id})}>ثبت خدمات</button></div></>}
 {detail.kind==="batch"&&<div className="detailsection"><h2>دستگاه‌های مرتبط با این بچ</h2><p className="subtle">مصرف اولیه یا نصب در خدمات پس از فروش</p>{recordTable(devices.filter(d=>events(d.id).some(e=>e.data.batch===detail.id)||services.some(s=>s.data.device===d.id&&s.data.replacement===detail.id)),"device")}<button className="btn" style={{marginTop:14}} onClick={()=>start("action",{batch:detail.id})}>ثبت اقدام اصلاحی برای این بچ</button></div>}
 {detail.kind==="service"&&<button className="btn primary" onClick={()=>start("action",{device:detail.data.device,batch:detail.data.batch||"",title:detail.data.complaint})}>ایجاد اقدام اصلاحی</button>}
 {editable[detail.kind]&&<button className="btn primary" onClick={()=>{setEditing(detail);setDraft({...detail.data});setForm(detail.kind);setFormError("");setSelected(null)}}>{detail.kind==="action"?"ثبت پیشرفت و بررسی اثربخشی":detail.kind==="batch"?"ثبت نتیجه کنترل ورودی":"به‌روزرسانی وضعیت خدمات"}</button>}
 </>}</DialogContent></Dialog></>;
}
