import {requireAccess,checkOrigin,accessResponse} from '@/lib/authorization';
import {boundedBody} from '@/lib/firmware-storage';
import {foreignRoles,foreignRows,foreignPublic,foreignApply,foreignFileVisible,memberRole,foreignFail,installForeignPosition} from '@/lib/foreign-purchase';
import {foreignAlerts,foreignLabels,foreignHelp,foreignSelectionStates,foreignPhysicalStates,foreignMoney,foreignMoneyText} from '@/lib/foreign-purchase-contract';
import {supplierRows} from '@/lib/suppliers';
import {leadMembers} from '@/lib/sales-leads';
import {dayAt} from '@/lib/duties';
import {syncForeignTasks} from '@/lib/foreign-purchase-tasks';
const json=(v:any,s=200)=>Response.json(v,{status:s,headers:{'Cache-Control':'private, no-store','Vary':'Cookie, Authorization'}});
export async function GET(request:Request){try{const u=await requireAccess(),roles=foreignRoles(u);if(!roles.read)foreignFail('دسترسی بازرگانی خارجی ندارید.',403);const rows=await foreignRows(),q=new URL(request.url).searchParams,search=(q.get('search')||'').trim().toLowerCase(),all=rows.filter(r=>r.type==='purchase_shipment'&&r.data.route==='foreign'),shipments=all.filter(s=>(!q.get('id')||s.id===q.get('id'))&&(!search||JSON.stringify({title:s.data.title,supplier:s.data.supplierName,lines:s.data.initial.lines}).toLowerCase().includes(search))),selections=rows.filter(r=>r.type==='foreign_selection'&&(!search||JSON.stringify(r.data).toLowerCase().includes(search))),statements=rows.filter(r=>r.type==='foreign_statement'),statementRows=rows.filter(r=>r.type==='foreign_statement_row'),files=rows.filter(r=>['foreign_file','shipment_file'].includes(r.type)&&rows.some(s=>s.id===(r.data.caseId||r.data.shipmentId)&&s.type==='purchase_shipment'&&s.data.route==='foreign'||s.id===r.data.caseId&&s.type==='foreign_selection')&&foreignFileVisible(u,r.data)).map(r=>({...r,data:{...r.data,caseId:r.data.caseId||r.data.shipmentId,objectKey:undefined,signature:undefined}}));
 const supplierList=(await supplierRows('supplier')).filter(s=>s.data.route==='foreign'),materials=await supplierRows('material'),links=(await supplierRows('supplier_material')).filter(l=>supplierList.some(s=>s.id===l.data.supplierId)).map(l=>({...l,material:materials.find(m=>m.id===l.data.materialId)}));const members=(await leadMembers()).filter(m=>m.status==='active').map(m=>({id:m.id,name:m.name,roles:['buyer','manager','engineering','finance','inventory','logistics'].filter(r=>memberRole(m,r))}));
 const alerts=all.flatMap(s=>foreignAlerts(s,statements,dayAt()).filter(a=>roles.commercial||a.role==='inventory'&&roles.inventory||a.role==='logistics'&&roles.logistics).map(a=>({...a,caseId:s.id,title:a.title+' · '+s.data.title})));const candidates=roles.commercial?shipments.flatMap(s=>(s.data.foreign?.fxPurchases||[]).filter((p:any)=>!p.received).map((p:any)=>({caseId:s.id,fxId:p.id,rows:statementRows.filter(r=>r.data.account===p.account&&r.data.currency===p.currency&&r.data.day>=p.day&&!p.matches.some((x:any)=>x.rowId===r.id)&&foreignMoney(r.data.amount)>(r.data.allocations||[]).reduce((n:bigint,x:any)=>n+foreignMoney(x.amount),BigInt(0))).map(r=>({...r,available:foreignMoneyText(foreignMoney(r.data.amount)-(r.data.allocations||[]).reduce((n:bigint,x:any)=>n+foreignMoney(x.amount),BigInt(0))),exactReference:!!p.expectedReference&&r.data.reference===p.expectedReference}))}))):[];
 return json({roles,shipments:shipments.map(s=>foreignPublic(u,s)),selections,files,suppliers:supplierList,materials:materials.map(m=>({id:m.id,...m.data,revision:m.revision})),links,members,alerts,candidates,statements:roles.commercial?statements:[],today:dayAt(),help:foreignHelp,selectionStates:foreignSelectionStates,physicalStates:foreignPhysicalStates});}catch(e){return accessResponse(e)||json({error:'دریافت پرونده خارجی ممکن نشد.'},503);}}
export async function POST(request:Request){try{checkOrigin(request);const u=await requireAccess(),b=JSON.parse(new TextDecoder().decode(await boundedBody(request,220000))),saved=await foreignApply(u,b);try{await syncForeignTasks();}catch(e){console.error('Foreign task projection deferred',e);}return json(saved);}catch(e){return accessResponse(e)||json({error:e instanceof Error&&!/SQLITE|D1|constraint/i.test(e.message)?e.message:'ثبت انجام نشد؛ تازه‌سازی و با همان شناسه تلاش کنید.'},409);}}
