import {requireAccess,checkOrigin,accessResponse} from '@/lib/authorization';
import {boundedBody} from '@/lib/firmware-storage';
import {supplierRows} from '@/lib/suppliers';
import {shipmentVisible,shipmentWrite,shipmentRows,applyShipment,shipmentFail} from '@/lib/purchase-shipments';
import {packingPrediction,shipmentHelp,shipmentStates,shipmentDocumentKinds} from '@/lib/shipment-contract';
const json=(v:any)=>Response.json(v,{headers:{'Cache-Control':'private, no-store','Vary':'Cookie, Authorization'}});
export async function GET(request:Request){try{const u=await requireAccess();if(!['domestic','foreign'].some(r=>shipmentVisible(u,r)))shipmentFail('دسترسی بازرگانی یا مالی لازم است.',403);const q=new URL(request.url).searchParams,all=(await shipmentRows()).filter(s=>shipmentVisible(u,s.data.route)),suppliers=(await supplierRows('supplier')).filter(s=>shipmentVisible(u,s.data.route)),materials=await supplierRows('material'),links=(await supplierRows('supplier_material')).filter(l=>suppliers.some(s=>s.id===l.data.supplierId)).map(l=>({...l,material:materials.find(m=>m.id===l.data.materialId)})),search=(q.get('search')||'').trim().toLocaleLowerCase(),shipments=all.filter(s=>(!q.get('supplier')||s.data.supplierId===q.get('supplier'))&&(!q.get('material')||s.data.initial.lines.some((l:any)=>l.materialId===q.get('material')))&&(!search||JSON.stringify({title:s.data.title,reference:s.data.reference,supplier:s.data.supplierName,lines:s.data.initial.lines,actual:s.data.actual?.lines}).toLocaleLowerCase().includes(search))),files=(await supplierRows('shipment_file')).filter(f=>shipments.some(s=>s.id===f.data.shipmentId)).map(f=>({...f,data:{...f.data,objectKey:undefined}})),specifications=(await supplierRows('purchase_specification')).filter(s=>shipmentVisible(u,s.data.route));let prediction=null;
 if(q.get('link')){const l=links.find(l=>l.id===q.get('link'));if(!l)shipmentFail('کالا در دسترس نیست.',404);const quantity=q.get('quantity')||'';if(!/^\d{1,9}(\.\d{1,6})?$/.test(quantity)||Number(quantity)<=0)shipmentFail('مقدار مثبت لازم است.');prediction=packingPrediction(all,{linkId:l!.id,quantity,unit:l!.material?.data.unit,generalSpecs:l!.material?.data.specs||'',supplierSpecs:l!.data.supplierSpecs||'',packaging:q.get('packaging')||''});}
 const orders=(await supplierRows('purchase_order')).filter(o=>shipmentVisible(u,o.data.route)&&(!q.get('supplier')||o.data.supplierId===q.get('supplier')||links.some(l=>l.id===o.data.supplierLinkId&&l.data.supplierId===q.get('supplier')))&&(!q.get('material')||links.some(l=>l.id===o.data.supplierLinkId&&l.data.materialId===q.get('material')))&&(!search||JSON.stringify(o.data).toLocaleLowerCase().includes(search)));return json({orders,shipments,suppliers,links,files,specifications,prediction,canWrite:Object.fromEntries(['domestic','foreign'].map(r=>[r,shipmentWrite(u,r)])),help:shipmentHelp,states:shipmentStates,documentKinds:shipmentDocumentKinds});}catch(e){return accessResponse(e)||Response.json({error:'دریافت پرونده محموله انجام نشد.'},{status:503});}}
export async function POST(request:Request){try{checkOrigin(request);const u=await requireAccess(),b=JSON.parse(new TextDecoder().decode(await boundedBody(request,180000)));return json(await applyShipment(u,b));}catch(e){return accessResponse(e)||Response.json({error:'ثبت انجام نشد؛ اطلاعات را تازه و با همان شناسه تلاش کنید.'},{status:409});}}
