import {requireAccess,checkOrigin,accessResponse,AccessError} from '@/lib/authorization';
import {storage} from '@/lib/storage';
import {inboxAccess,inboxClosed} from '@/lib/inbox';
import {firmwareBucket,boundedBody} from '@/lib/firmware-storage';
import {sha256} from '@/lib/firmware';
import {validateFinanceFile,MAX_FINANCE_BYTES} from '@/lib/finance-control';
const present=(r:any)=>{const d=JSON.parse(r.data);delete d.objectKey;return {id:r.id,...d};};
export async function GET(request:Request){try{const u=await requireAccess(),q=new URL(request.url).searchParams,thread=q.get('thread')||'';await inboxAccess(thread,u);const db=storage(),id=q.get('id');if(!id)return Response.json({files:(await db.prepare("SELECT * FROM flow_entities WHERE type='inbox_file' AND json_extract(data,'$.thread')=? ORDER BY created DESC").bind(thread).all()).results.map(present)},{headers:{'Cache-Control':'private, no-store'}});
 const row:any=await db.prepare("SELECT * FROM flow_entities WHERE id=? AND type='inbox_file' AND json_extract(data,'$.thread')=?").bind(id,thread).first();if(!row)throw new AccessError('فایل یافت نشد.',404);const f=JSON.parse(row.data),object=await firmwareBucket().get(f.objectKey);if(!object)throw new Error('missing');const bytes=await object.arrayBuffer();if(await sha256(bytes)!==f.sha256)throw new Error('integrity');return new Response(bytes,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':"attachment; filename=inbox-file; filename*=UTF-8''"+encodeURIComponent(f.filename).replace(/['()*]/g,c=>'%'+c.charCodeAt(0).toString(16)),'X-Content-Type-Options':'nosniff','Content-Security-Policy':"sandbox; default-src 'none'",'Cache-Control':'private, no-store'}});
 }catch(e){return accessResponse(e)||Response.json({error:'دریافت پیوست انجام نشد.'},{status:503})}}
export async function POST(request:Request){let key='',id='';try{checkOrigin(request);const u=await requireAccess(),q=new URL(request.url).searchParams,thread=q.get('thread')||'',t=await inboxAccess(thread,u);if(inboxClosed(t.data.state))throw new AccessError('گفت‌وگو بسته است.',400);id=q.get('requestId')||'';if(!/^[a-f0-9-]{36}$/i.test(id))throw new AccessError('شناسه فایل معتبر نیست.',400);
 const ct=request.headers.get('content-type')||'',bytes=await boundedBody(request,MAX_FINANCE_BYTES+128000),form=await new Response(bytes,{headers:{'Content-Type':ct}}).formData(),file=form.get('file');if(!file||typeof file==='string'||form.getAll('file').length!==1)throw new AccessError('یک فایل انتخاب کنید.',400);try{validateFinanceFile(file.name,file.size)}catch(e){throw new AccessError((e as Error).message,400)}const buffer=await file.arrayBuffer(),hash=await sha256(buffer),db=storage(),old:any=await db.prepare("SELECT * FROM flow_entities WHERE id=?").bind(id).first();if(old){const f=JSON.parse(old.data);if(old.type!=='inbox_file'||f.thread!==thread||f.sha256!==hash||f.filename!==file.name||f.author!==t.me)throw new AccessError('شناسه فایل تکراری است.',409);return Response.json({file:present(old)})}
 const count:any=await db.prepare("SELECT COUNT(*) n FROM flow_entities WHERE type='inbox_file' AND json_extract(data,'$.thread')=?").bind(thread).first();if(count.n>=100)throw new AccessError('حداکثر ۱۰۰ پیوست در هر گفت‌وگو.',400);
 key='inbox-files/'+id+'/'+crypto.randomUUID();await firmwareBucket().put(key,buffer,{httpMetadata:{contentType:'application/octet-stream'},sha256:hash});const now=new Date().toISOString(),f={thread,objectKey:key,filename:file.name,byteSize:buffer.byteLength,sha256:hash,author:t.me,authorName:u.name,created:now};
 const checks=[];if(t.data.recipientType==='position'&&!t.isSender)checks.push(db.prepare("UPDATE inventory_operations SET guard=CASE WHEN EXISTS(SELECT 1 FROM flow_entities p,json_each(p.data,'$.members') m WHERE p.id=? AND p.type='position' AND json_extract(p.data,'$.active')=1 AND m.value=?) THEN guard ELSE 0 END WHERE id=?").bind(t.data.recipientId,t.me,id));
 await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'inbox_file','{}',?,?,CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN 1 ELSE 0 END)").bind(id,u.userId,now,thread,t.revision),...checks,db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,'inbox_file',?,1,?,?)").bind(id,JSON.stringify(f),now,now),db.prepare('UPDATE flow_entities SET revision=revision+1,updated=? WHERE id=? AND revision=?').bind(now,thread,t.revision),db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,'inbox_message',?,1,?,?)").bind('inbox-upload:'+id,JSON.stringify({thread,mode:'attachment',body:'پیوست: '+file.name,author:t.me,authorName:u.name,viaAssistant:false}),now,now),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,thread,'inbox_file',JSON.stringify({fileId:id}),now)]);return Response.json({file:{id,...f,objectKey:undefined}},{status:201});
 }catch(e){if(key&&id)try{const linked:any=await storage().prepare("SELECT * FROM flow_entities WHERE id=? AND type='inbox_file'").bind(id).first();if(linked&&JSON.parse(linked.data).objectKey===key)return Response.json({file:present(linked)},{status:201});await firmwareBucket().delete(key)}catch{}return accessResponse(e)||Response.json({error:'پیوست ذخیره نشد؛ صندوق را تازه کنید.'},{status:409})}}
