import {maintenanceForecast,scanHospitalMaintenance,dayDiff} from '@/lib/hospital-maintenance';
import {syncHospitalTasks} from '@/lib/hospital-tasks';
import {storage} from '@/lib/storage';
import {checkOrigin,AccessError,accessResponse} from '@/lib/authorization';
import {hospitalUser,hospitalManager,hospitalFinance,hospitalTech,hospitalCenter,hospitalAsset,hospitalRows,hospitalBalance,hospitalPublic,hrow,hreq,htext,hospitalStates} from '@/lib/hospital';
import {boundedBody} from '@/lib/firmware-storage';
import {qualityFields,qualityValues} from '@/lib/quality';
import {money,integer,sday,salesLock} from '@/lib/sales';
import {dayAt,memberId,tickDuties} from '@/lib/duties';
const json=(d:unknown,status=200)=>Response.json(d,{status,headers:{'Cache-Control':'private, no-store'}});
const fail=(m:string,s=400):never=>{throw new AccessError(m,s)};
export async function GET(request:Request){try{const u=await hospitalUser(),q=new URL(request.url).searchParams,own=u.permissions.hospitalCenterId||'',centerId=own||q.get('center')||'',all=await hospitalRows();if(own&&q.get('center')&&q.get('center')!==own)fail('مرکز پیدا نشد.',404);if(centerId)await hospitalCenter(u,centerId);const centers=all.filter(r=>r.type==='hospital_center'&&(!centerId||r.id===centerId));const ids=new Set(centers.map(c=>c.id));
 const rows=all.filter(r=>ids.has(r.data.centerId)&&!['hospital_chat','hospital_lock'].includes(r.type)&&(!own||r.type!=='hospital_manual'||r.data.state==='published')&&(!own||r.type!=='hospital_form'||r.data.state==='published'));
 const staff=!own?(await storage().prepare("SELECT id,name,permissions FROM app_members WHERE status='active'").all()).results.map((m:any)=>({...m,p:JSON.parse(m.permissions)})).filter(m=>hospitalTech({isAdmin:false,permissions:m.p} as any)).map(m=>({id:m.id,name:m.name})):[];
 const devices=hospitalManager(u)?(await storage().prepare("SELECT id,payload FROM records WHERE kind='device'").all()).results.map((r:any)=>({id:r.id,...JSON.parse(r.payload)})):[];
 const profiles=hospitalManager(u)?(await storage().prepare('SELECT id,name FROM llm_configs').all()).results:[];
 const mid=await memberId(u);const myTasks=own&&mid?(await storage().prepare("SELECT id,due,state,data FROM duty_runs WHERE assignee=? AND template_id LIKE 'hospital:%' AND state='open'").bind(mid).all()).results.map((r:any)=>({id:r.id,due:r.due,state:r.state,...JSON.parse(r.data)})).filter((t:any)=>rows.some(r=>r.id===t.sourceId)):[];
 return json({myTasks,accountId:u.userId,own:!!own,roles:{manager:!!hospitalManager(u),finance:!!hospitalFinance(u),tech:!!hospitalTech(u)},centers:own?centers.map(hospitalPublic):centers,rows:own?rows.map(hospitalPublic):rows,balances:centers.map(c=>({centerId:c.id,...hospitalBalance(all,c.id)})),staff,devices,profiles,maintenance:rows.filter(r=>r.type==='hospital_asset').map(a=>({assetId:a.id,...maintenanceForecast(a,all)})),monitorHealth:!own?all.find(r=>r.id==='hospital-monitor-health')?.data:null,states:hospitalStates});
 }catch(e){return accessResponse(e)||json({error:'دریافت پنل بیمارستانی انجام نشد.'},503)}}
export async function POST(request:Request){try{checkOrigin(request);const u=await hospitalUser(),b=JSON.parse(new TextDecoder().decode(await boundedBody(request,180000))),id=hreq(b.id),mode=hreq(b.mode),db=storage(),now=new Date().toISOString(),today=dayAt();if(!/^[a-f0-9-]{36}$/i.test(id)||b.confirmed!==true)fail('شناسه و تأیید عملیات لازم است.');
 const own=!!u.permissions.hospitalCenterId,manager=!!hospitalManager(u),finance=!!hospitalFinance(u),tech=!!hospitalTech(u),signature=JSON.stringify(b),prior:any=await db.prepare('SELECT actor,payload FROM inventory_operations WHERE id=?').bind(id).first();if(prior){if(prior.actor!==u.userId||prior.payload!==signature)fail('شناسه درخواست تکراری متفاوت است.',409);return json({saved:true,repeated:true});}
 const stmts:D1PreparedStatement[]=[],checks=await salesLock(db,id),guard=(sql:string,...args:any[])=>checks.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN '+sql+' THEN guard ELSE 0 END WHERE id=?').bind(...args,id));
 const put=(eid:string,type:string,data:any,old?:any)=>{const v={...data,history:[...(old?.data.history||[]),{mode,actor:u.userId,name:u.name,at:now}]};stmts.push(old?db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=?').bind(JSON.stringify(v),now,eid):db.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').bind(eid,type,JSON.stringify(v),now,now));};
 const get=async(eid:string,type:string,revision=false)=>{const r=await hrow(eid,type);const c=type==='hospital_center'&&mode==='center'&&manager?r:await hospitalCenter(u,type==='hospital_center'?r.id:r.data.centerId);guard('EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?)',c.id,c.revision);guard('EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?)',r.id,r.revision);if(revision&&r.revision!==b.revision)fail('پرونده تغییر کرده؛ تازه‌سازی کنید.',409);return r;};
 const need=(ok:boolean)=>{if(!ok)fail('مجوز این عملیات را ندارید.',403)};
 if(mode==='center'){
  need(manager);const old=b.centerId?await get(hreq(b.centerId),'hospital_center',true):null;const profileId=htext(b.profileId||'',200);if(profileId&&!await db.prepare('SELECT id FROM llm_configs WHERE id=?').bind(profileId).first())fail('مدل پیکربندی‌شده انتخاب کنید.');if(typeof b.active!=='boolean')fail('وضعیت مرکز لازم است.');put(old?.id||id,'hospital_center',{name:hreq(b.name),phone:hreq(b.phone,50),address:hreq(b.address,2000),active:b.active,profileId,contacts:old?.data.contacts||[]},old);
 }else if(mode==='contacts'){
  need(manager);const c=await get(hreq(b.centerId),'hospital_center',true);
  if(!Array.isArray(b.contacts)||b.contacts.length>50)fail('حداکثر ۵۰ فرد تماس وارد کنید.');
  const contacts=[];const seen=new Set();
  for(const v of b.contacts){const contactId=hreq(v.id,100);if(seen.has(contactId))fail('شناسه فرد تماس تکراری است.');seen.add(contactId);
   const assetId=htext(v.assetId||'',200);if(assetId){const a=await get(assetId,'hospital_asset');if(a.data.centerId!==c.id)fail('دستگاه متعلق به این مرکز نیست.');}
   const phone=(x:any)=>{const n=htext(x||'',50).replace(/[۰-۹]/g,(d:string)=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[٠-٩]/g,(d:string)=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d)));if(n&&!/^[+()0-9 .-]{3,50}$/.test(n))fail('شماره تماس معتبر وارد کنید.');return n;};
   const mobile=phone(v.mobile),landline=phone(v.landline);if(!mobile&&!landline)fail('حداقل یک شماره برای هر فرد لازم است.');
   if(typeof v.active!=='boolean')fail('وضعیت فرد تماس لازم است.');
   contacts.push({id:contactId,name:hreq(v.name,200),role:hreq(v.role,200),mobile,landline,extension:phone(v.extension),assetId,active:v.active,notes:htext(v.notes||'',1000)});
  }
  put(c.id,'hospital_center',{...c.data,contacts},c);
 }else if(mode==='asset'){
  need(manager);const center=await get(hreq(b.centerId),'hospital_center'),old=b.assetId?await get(hreq(b.assetId),'hospital_asset',true):null;if(old&&old.data.centerId!==center.id)fail('انتقال دستگاه به مرکز دیگر در این عملیات مجاز نیست.');const deviceId=hreq(b.deviceId),r:any=await db.prepare("SELECT payload FROM records WHERE id=? AND kind='device'").bind(deviceId).first();if(!r)fail('ابتدا شناسنامه دستگاه را ثبت کنید.');if(old&&old.data.deviceId!==deviceId)fail('شناسه دستگاه ثابت است.');guard("NOT EXISTS(SELECT 1 FROM flow_entities WHERE type='hospital_asset' AND json_extract(data,'$.deviceId')=? AND id<>?)",deviceId,old?.id||id);const p=JSON.parse(r.payload);put(old?.id||id,'hospital_asset',{...old?.data,centerId:center.id,deviceId,serial:p.code,model:p.model,productId:p.product||'',productName:p.productName||'',design:p.design||'',firmware:p.firmware||'',warrantyMonths:p.warrantyMonths||'',name:hreq(b.name),department:hreq(b.department),location:hreq(b.location),installedOn:sday(b.installedOn),notes:htext(b.notes||'')},old);
 }else if(mode==='components'){
  need(manager);const a=await get(hreq(b.assetId),'hospital_asset',true);if(!Array.isArray(b.components)||b.components.length>100)fail('حداکثر ۱۰۰ قطعه ثبت کنید.');
  const components=b.components.map((v:any)=>({name:hreq(v.name),code:htext(v.code||'',100),model:htext(v.model||'',200),serial:htext(v.serial||'',200),quantity:integer(v.quantity,1,10000),notes:htext(v.notes||'',2000)}));put(a.id,'hospital_asset',{...a.data,components},a);
 }else if(mode==='maintenance'){
  need(manager);const a=await get(hreq(b.assetId),'hospital_asset',true),rows=await hospitalRows();if(rows.some(r=>r.type==='hospital_job'&&r.data.assetId===a.id&&r.data.pm&&r.data.state!=='confirmed'))fail('ابتدا پرونده سرویس دوره‌ای باز را تعیین تکلیف کنید.');
  const baselineHours=integer(b.baselineHours,0,10000000),baselineDay=sday(b.baselineDay);if(baselineDay>today)fail('تاریخ مبنا در آینده نیست.');
  if(rows.some(r=>r.type==='hospital_reading'&&r.data.assetId===a.id&&!r.data.voided&&r.data.day>=baselineDay&&r.data.hours<baselineHours))fail('مبنای سرویس با قرائت‌های بعدی ناسازگار است.');
  if(typeof b.enabled!=='boolean')fail('وضعیت پایش لازم است.');
  const maintenance={enabled:b.enabled,baselineHours,baselineDay,interval:integer(b.interval,1,100000),leadHours:integer(b.leadHours,0,100000),leadDays:integer(b.leadDays,1,365),staleDays:integer(b.staleDays,1,365),notes:hreq(b.notes,2000),version:(a.data.maintenance?.version||0)+1};if(maintenance.leadHours>=maintenance.interval)fail('هشدار ساعتی باید کمتر از فاصله سرویس باشد.');put(a.id,'hospital_asset',{...a.data,maintenance},a);
 }else if(mode==='reading'){
  need(own||tech);const a=await get(hreq(b.assetId),'hospital_asset'),day=sday(b.day),hours=integer(b.hours,0,10000000);if(day>today)fail('تاریخ مشاهده در آینده نیست.');if(a.data.installedOn&&day<a.data.installedOn)fail('قرائت پیش از نصب دستگاه نیست.');
  const rows=(await hospitalRows()).filter(r=>r.type==='hospital_reading'&&r.data.assetId===a.id&&!r.data.voided);
  if(rows.some(r=>r.data.day===day&&r.data.hours===hours))fail('این قرائت قبلاً ثبت شده است.',409);
  for(const r of rows){const days=dayDiff(day,r.data.day),delta=hours-r.data.hours;if(days===0){if(delta<0||delta>24)fail('اختلاف قرائت‌های همان روز باید بین صفر و ۲۴ ساعت باشد.');continue;}if(delta*days<0||Math.abs(delta)>Math.abs(days)*24+24)fail('ساعت با ترتیب تاریخ یا حداکثر کارکرد روزانه سازگار نیست؛ قرائت را بررسی کنید.');}
  if(a.data.maintenance&&day>=a.data.maintenance.baselineDay&&(hours<a.data.maintenance.baselineHours||hours-a.data.maintenance.baselineHours>(dayDiff(day,a.data.maintenance.baselineDay)+1)*24))fail('عدد کمتر از مبنای سرویس است. برای تعویض یا صفرشدن کنتور، ابتدا با مدیر خدمات هماهنگ کنید.');
  put(id,'hospital_reading',{centerId:a.data.centerId,assetId:a.id,day,hours,observer:u.name,observerId:u.userId,source:own?'center':'technician',notes:htext(b.notes||'',2000)});
 }else if(mode==='reading_void'){
  need(manager);const r=await get(hreq(b.readingId),'hospital_reading',true);if(r.data.voided)fail('قرائت قبلاً باطل شده است.');if((await hospitalRows()).some(j=>j.type==='hospital_job'&&j.data.report?.readingId===r.id))fail('این قرائت مبنای گزارش سرویس است و قابل ابطال نیست.');put(r.id,r.type,{...r.data,voided:{by:u.userId,at:now,notes:hreq(b.notes,2000)}},r);
 }else if(mode==='pm_scan'){
  need(manager);
 }else if(mode==='request'){
  const a=await get(hreq(b.assetId),'hospital_asset');if(!['fault','service'].includes(b.kind)||!['normal','urgent','stopped'].includes(b.urgency))fail('نوع درخواست و فوریت معتبر لازم است.');put(id,'hospital_job',{centerId:a.data.centerId,assetId:a.id,deviceId:a.data.deviceId,serial:a.data.serial,model:a.data.model,kind:b.kind,urgency:b.urgency,description:hreq(b.description,4000),contact:hreq(b.contact),state:'requested',quote:null,quoteVersion:0,consent:null,technicianId:'',report:null,confirmation:null});
 }else if(['quote','consent','schedule','dispatch','complete','confirm'].includes(mode)){
  const j=await get(hreq(b.jobId),'hospital_job',true),d={...j.data};
  if(mode==='quote'){need(tech);if(await db.prepare("SELECT id FROM flow_entities WHERE type='hospital_invoice' AND json_extract(data,'$.jobId')=?").bind(j.id).first())fail('برای این پیش‌فاکتور فاکتور ثبت شده؛ تغییر مبلغ در این عملیات مجاز نیست.');if(['dispatched','completed','confirmed'].includes(d.state))fail('پس از اعزام، برآورد این مأموریت قابل تغییر نیست.');if(!Array.isArray(b.lines)||!b.lines.length||b.lines.length>50)fail('حداقل یک خدمت یا قطعه وارد کنید.');const lines=b.lines.map((l:any)=>({kind:['part','labor','travel'].includes(l.kind)?l.kind:fail('نوع ردیف معتبر نیست.'),label:hreq(l.label),quantity:integer(l.quantity,1,10000),unitPrice:money(l.unitPrice),partCode:htext(l.partCode||'',12)}));for(const l of lines)if(l.kind==='part'){if(!l.partCode)fail('برای قطعه کد کالا لازم است.');await hrow('material:'+l.partCode,'material');}const total=lines.reduce((n:bigint,l:any)=>n+BigInt(l.quantity)*BigInt(l.unitPrice),BigInt(0));if(total>BigInt('999999999999999999'))fail('مبلغ بیش از محدوده است.');const validUntil=sday(b.validUntil);if(validUntil<today)fail('اعتبار در گذشته نباشد.');d.previousQuotes=[...(d.previousQuotes||[]),...(d.quote?[{...d.quote,version:d.quoteVersion,consent:d.consent}]:[])];d.quoteVersion++;d.quote={lines,total:String(total),validUntil,notes:hreq(b.notes,4000),at:now};d.consent=null;d.state='quoted';d.schedule=null;}
  if(mode==='consent'){need(own);if(d.state!=='quoted'||b.quoteVersion!==d.quoteVersion||d.quote.validUntil<today||typeof b.approved!=='boolean')fail('نسخه معتبر پیش‌فاکتور را تأیید یا رد کنید.',409);d.consent={approved:b.approved,version:d.quoteVersion,amount:d.quote.total,by:u.userId,name:u.name,at:now,notes:hreq(b.notes,4000)};d.state=b.approved?'accepted':'declined';}
  if(mode==='schedule'){need(manager);if(!['accepted','scheduled'].includes(d.state)||!d.consent?.approved||d.consent.version!==d.quoteVersion||d.quote.validUntil<today)fail('پیش‌فاکتور معتبر و تأیید همان نسخه لازم است.');const technicianId=hreq(b.technicianId),m:any=await db.prepare("SELECT permissions FROM app_members WHERE id=? AND status='active'").bind(technicianId).first();if(!m||!hospitalTech({isAdmin:false,permissions:JSON.parse(m.permissions)} as any))fail('تکنسین فعال بیمارستانی انتخاب کنید.');const day=sday(b.day);if(day<today)fail('تاریخ اعزام در گذشته نیست.');d.technicianId=technicianId;d.schedule={day,notes:hreq(b.notes,4000)};d.state='scheduled';}
  if(mode==='dispatch'){need(tech);if(d.state!=='scheduled'||!d.consent?.approved||d.consent.version!==d.quoteVersion||d.quote.validUntil<today)fail('اعزام به تأیید مرکز و پیش‌فاکتور معتبر نیاز دارد.');if(!manager&&await memberId(u)!==d.technicianId)fail('فقط تکنسین تعیین‌شده مجاز است.',403);d.dispatch={at:now,notes:hreq(b.notes,4000),by:u.userId};d.state='dispatched';}
  if(mode==='complete'){need(tech);if(d.state!=='dispatched'||!manager&&await memberId(u)!==d.technicianId)fail('مأموریت اعزام‌شده همین تکنسین لازم است.',403);let service:any={};if(d.pm){const a=await get(d.assetId,'hospital_asset'),reading=await get(hreq(b.readingId),'hospital_reading');if(reading.data.assetId!==a.id||reading.data.source!=='technician'||reading.data.observerId!==u.userId||reading.data.voided||reading.data.day<dayAt(new Date(d.dispatch.at))||reading.data.hours<=d.pm.baselineHours)fail('قرائت معتبر همین دستگاه در زمان بازدید لازم است.');service={readingId:reading.id,serviceHours:reading.data.hours,serviceDay:reading.data.day};}d.report={...service,work:hreq(b.work,6000),parts:htext(b.parts||'',3000),test:hreq(b.test,4000),at:now,by:u.userId,name:u.name};d.state='completed';}
  if(mode==='confirm'){need(own);if(!['completed','disputed'].includes(d.state)||typeof b.approved!=='boolean')fail('خدمات انجام‌شده را بررسی کنید.');d.confirmation={approved:b.approved,rating:integer(b.rating,1,5),notes:hreq(b.notes,4000),name:u.name,by:u.userId,at:now};d.state=b.approved?'confirmed':'disputed';}
  put(j.id,'hospital_job',d,j);
 }else if(mode==='invoice'){
  need(finance);const j=await get(hreq(b.jobId),'hospital_job',true);if(!j.data.consent?.approved||j.data.consent.version!==j.data.quoteVersion||!['accepted','scheduled','dispatched','completed','confirmed'].includes(j.data.state))fail('پیش‌فاکتور تأییدشده لازم است.');guard("NOT EXISTS(SELECT 1 FROM flow_entities WHERE type='hospital_invoice' AND json_extract(data,'$.jobId')=?)",j.id);put(id,'hospital_invoice',{centerId:j.data.centerId,jobId:j.id,assetId:j.data.assetId,quoteVersion:j.data.quoteVersion,amount:j.data.quote.total,reference:hreq(b.reference,300),due:sday(b.due),createdBy:u.userId});
 }else if(mode==='payment'){
  need(own);const inv=await get(hreq(b.invoiceId),'hospital_invoice'),file=await get(hreq(b.fileId),'hospital_file');if(file.data.purpose!=='payment'||file.data.centerId!==inv.data.centerId)fail('رسید پرداخت همان مرکز لازم است.');const amount=money(b.amount,true),day=sday(b.day);if(day>today)fail('تاریخ پرداخت در آینده نیست.');const reference=hreq(b.reference,300);guard("NOT EXISTS(SELECT 1 FROM flow_entities WHERE type='hospital_payment' AND json_extract(data,'$.centerId')=? AND json_extract(data,'$.reference')=?)",inv.data.centerId,reference);put(id,'hospital_payment',{centerId:inv.data.centerId,invoiceId:inv.id,amount,day,reference,fileId:file.id,state:'pending',submittedBy:u.userId,notes:htext(b.notes||'')});
 }else if(mode==='payment_review'){
  need(finance);const p=await get(hreq(b.paymentId),'hospital_payment',true);if(p.data.state!=='pending'||typeof b.approved!=='boolean')fail('رسید منتظر تأیید انتخاب کنید.');if(p.data.submittedBy===u.userId)fail('تأییدکننده باید مستقل از ثبت‌کننده باشد.',403);put(p.id,'hospital_payment',{...p.data,state:b.approved?'approved':'rejected',review:{notes:hreq(b.notes,4000),by:u.userId,at:now}},p);
 }else if(mode==='manual'||mode==='form'){
  need(manager);const a=await get(hreq(b.assetId),'hospital_asset');const old=b.previousId?await get(hreq(b.previousId),'hospital_'+mode,true):null;if(old&&old.data.assetId!==a.id)fail('راهنما یا فرم متعلق به دستگاه دیگری است.');if(old?.data.state==='superseded')fail('آخرین نسخه را انتخاب کنید.',409);if(!['draft','published'].includes(b.state))fail('وضعیت انتشار معتبر نیست.');const base={seriesId:old?.data.seriesId||old?.id||id,centerId:a.data.centerId,assetId:a.id,title:hreq(b.title),version:(old?.data.version||0)+1,state:b.state,previousId:old?.id||'',approvedBy:b.state==='published'?u.userId:'',reference:hreq(b.reference,500)};
  if(mode==='manual'){const fileId=htext(b.fileId||'',200);if(fileId){const f=await get(fileId,'hospital_file');if(f.data.assetId!==a.id||f.data.purpose!=='manual')fail('فایل راهنمای همین دستگاه لازم است.');}put(id,'hospital_manual',{...base,body:hreq(b.body,30000),fileId});}else put(id,'hospital_form',{...base,fields:qualityFields(b.fields)});
  if(old&&(old.data.state!=='published'||b.state==='published'))put(old.id,old.type,{...old.data,state:'superseded'},old);if(b.state==='published'&&old){for(const prior of (await hospitalRows()).filter(r=>r.type==='hospital_'+mode&&r.id!==old.id&&r.data.state==='published'&&(r.data.seriesId||r.id)===base.seriesId)){const current=await get(prior.id,prior.type);put(current.id,current.type,{...current.data,state:'superseded'},current);}}
 }else if(mode==='history'){
  need(manager);const a=await get(hreq(b.assetId),'hospital_asset');const day=sday(b.day);if(day>today)fail('تاریخ سابقه در آینده نباشد.');put(id,'hospital_history',{centerId:a.data.centerId,assetId:a.id,day,title:hreq(b.title),notes:hreq(b.notes,6000),reference:hreq(b.reference,500),publishedBy:u.userId});
 }else if(mode==='check_review'){
  need(manager);const c=await get(hreq(b.checkId),'hospital_check',true);if(!c.data.failed||c.data.review)fail('فرم نامنطبق بررسی‌نشده لازم است.');put(c.id,'hospital_check',{...c.data,review:{notes:hreq(b.notes,4000),at:now,by:u.userId}},c);
 }else if(mode==='form_submit'){
  need(own);const f=await get(hreq(b.formId),'hospital_form',true);if(f.data.state!=='published')fail('فرم منتشرشده معتبر لازم است.');const checked=qualityValues(f.data.fields,b.values);put(id,'hospital_check',{centerId:f.data.centerId,assetId:f.data.assetId,formId:f.id,formVersion:f.data.version,title:f.data.title,fields:f.data.fields,values:checked.values,failed:checked.failed,notes:htext(b.notes||''),submittedBy:u.userId,name:u.name,at:now});
 }else fail('عملیات ناشناخته است.');
 await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'hospital_action',?,?,?,1)").bind(id,signature,u.userId,now),...checks,...stmts,db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,b.jobId||b.assetId||b.centerId||id,'hospital_'+mode,signature,now)]);
 try{await scanHospitalMaintenance(mode==='pm_scan'?'requested':'interactive');await syncHospitalTasks();if(mode==='pm_scan')await tickDuties(new Date(),'hospital-monitor');}catch{return json({saved:true,id,followupPending:true});}
 return json({saved:true,id});
 }catch(e){return accessResponse(e)||json({error:/constraint|SQLITE/i.test(String(e))?'اطلاعات هم‌زمان تغییر کرده یا قبلاً ثبت شده؛ تازه‌سازی کنید.':e instanceof Error?e.message:'ثبت انجام نشد.'},409)}}
