import {requireAccess,checkOrigin,accessResponse} from '@/lib/authorization';
import {storage} from '@/lib/storage';
import {firmwareBucket,boundedBody} from '@/lib/firmware-storage';
import {sha256} from '@/lib/firmware';
import {MAX_BATCH_FILE_BYTES,validateBatchFile} from '@/lib/batch-files';
import {salesScope,salesRead,salesRep,salesStaff,salesFinance,salesEntity,publicSalesFile,salesFail as fail,sreq as req} from '@/lib/sales';
const json=(d:any,status=200)=>Response.json(d,{status,headers:{'Cache-Control':'private, no-store'}});
export async function GET(request:Request){try{const u=await requireAccess();if(!salesRead(u))fail('دسترسی ندارید.',403);const q=new URL(request.url).searchParams,e=await salesEntity(q.get('id')||'','sales_file');await salesScope(u,e.data.agentId);if(q.get('metadata')==='1')return json({file:publicSalesFile(e),downloadUrl:new URL('/api/sales/files?id='+encodeURIComponent(e.id),request.url).toString()});const object=await firmwareBucket().get(e.data.objectKey);if(!object)fail('فایل در دسترس نیست.',503);const bytes=await object!.arrayBuffer();if(bytes.byteLength!==e.data.size||await sha256(bytes)!==e.data.sha256)fail('یکپارچگی فایل تأیید نشد.',503);const name=encodeURIComponent(e.data.filename).replace(/['()*]/g,c=>'%'+c.charCodeAt(0).toString(16).toUpperCase());return new Response(bytes,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':"attachment; filename=sales-file; filename*=UTF-8''"+name,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"sandbox; default-src 'none'"}});}catch(e){return accessResponse(e)||json({error:'فایل دریافت نشد.'},503)}}
export async function POST(request:Request){let key='',id='';try{checkOrigin(request);const u=await requireAccess();if(!salesRep(u)&&!salesStaff(u)&&!salesFinance(u))fail('مجوز بارگذاری ندارید.',403);const ct=request.headers.get('content-type')||'';if(!ct.startsWith('multipart/form-data;'))fail('فایل لازم است.');const bytes=await boundedBody(request,MAX_BATCH_FILE_BYTES+12000),form=await new Response(bytes,{headers:{'Content-Type':ct}}).formData(),meta=form.get('metadata'),f=form.get('file');if(typeof meta!=='string'||meta.length>8000||!f||typeof f==='string'||form.getAll('file').length!==1)fail('یک فایل و مشخصات معتبر لازم است.');const b=JSON.parse(meta as string);id=req(b.id,80);if(!/^[a-f0-9-]{36}$/i.test(id)||b.confirmed!==true)fail('شناسه و تأیید لازم است.');const file=f as File;try{validateBatchFile(file.name,file.size);}catch(e){fail((e as Error).message);}const a=await salesScope(u,req(b.agentId)),raw=await file.arrayBuffer(),hash=await sha256(raw),title=req(b.title,200),signature=JSON.stringify({agentId:a.id,title,filename:file.name,size:file.size,hash}),db=storage();const old:any=await db.prepare('SELECT * FROM flow_entities WHERE id=?').bind(id).first();if(old){const d=JSON.parse(old.data);if(old.type!=='sales_file'||d.uploadSignature!==signature||d.actor!==u.userId)fail('شناسه برای فایل دیگری استفاده شده است.',409);return json({saved:true,repeated:true,id});}
 key='sales-files/'+id+'/'+crypto.randomUUID();await firmwareBucket().put(key,raw,{httpMetadata:{contentType:'application/octet-stream'},sha256:hash});const now=new Date().toISOString(),data={agentId:a.id,title,filename:file.name,size:file.size,sha256:hash,objectKey:key,actor:u.userId,uploadSignature:signature};await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'sales_file',?,?,?,CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN 1 ELSE 0 END)").bind(id,signature,u.userId,now,a.id,a.revision),db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,'sales_file',?,1,?,?)").bind(id,JSON.stringify(data),now,now),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,a.id,'sales_file',JSON.stringify({id,title,filename:file.name,sha256:hash}),now)]);return json({saved:true,id},201);
 }catch(e){if(key&&id)try{const saved:any=await storage().prepare('SELECT data FROM flow_entities WHERE id=?').bind(id).first();if(saved&&JSON.parse(saved.data).objectKey===key)return json({saved:true,id},201);await firmwareBucket().delete(key);}catch{console.error('Sales file reconciliation deferred');}return accessResponse(e)||json({error:'فایل ثبت نشد؛ فهرست را تازه و با همان شناسه تلاش کنید.'},409)}}
