import {requireAccess,checkOrigin,accessResponse} from '@/lib/authorization';
import {storage} from '@/lib/storage';
import {boundedBody} from '@/lib/firmware-storage';
import {taskRequired as req,taskText as txt,validDay,dayAt,memberId} from '@/lib/duties';
import {supplierRows,supplierEntity,supplierManage,supplierQuality} from '@/lib/suppliers';
import {supplierScope,documentVisible,publicDocument,qualityDirectory,qualityMember,sqFail as fail,syncSupplierQuality} from '@/lib/supplier-quality';
import {supplierQualityHelp,supplierSeverities} from '@/lib/supplier-quality-contract';
const json=(d:any,status=200)=>Response.json(d,{status,headers:{'Cache-Control':'private, no-store'}});
export async function GET(request:Request){try{const u=await requireAccess(),q=new URL(request.url).searchParams,{supplier,link}=await supplierScope(u,q.get('supplier')||'',q.get('link')||'');
 const documents=(await supplierRows('supplier_document')).filter(e=>e.data.supplierId===supplier.id&&(!link||!e.data.linkId||e.data.linkId===link.id)&&documentVisible(u,e.data,supplier.data.route)),actions=(await supplierRows('supplier_capa')).filter(e=>e.data.supplierId===supplier.id&&(!link||e.data.linkId===link.id));
 const orders=(await supplierRows('purchase_order')).filter(e=>e.data.supplierId===supplier.id&&(!link||e.data.supplierLinkId===link.id));
 const receipts=(await supplierRows('receipt')).filter(e=>orders.some(o=>o.id===e.data.purchaseOrderId));
 return json({supplier:{id:supplier.id,name:supplier.data.name},linkId:link?.id||'',documents:documents.map(publicDocument),actions,orders:orders.map(o=>({id:o.id,partCode:o.data.partCode})),receipts:receipts.map(e=>({id:e.id,day:e.data.day,manufacturerLot:e.data.manufacturerLot,quantity:e.data.quantity,unit:e.data.unit})),members:await qualityDirectory(supplier.data.route),canManage:supplierManage(u)||supplierQuality(u),canQuality:supplierQuality(u),memberId:await memberId(u),isAdmin:u.isAdmin,help:supplierQualityHelp,today:dayAt()});
 }catch(e){return accessResponse(e)||json({error:'مدارک و اقدامات دریافت نشد.'},503)}}
export async function POST(request:Request){try{checkOrigin(request);const u=await requireAccess(),b=JSON.parse(new TextDecoder().decode(await boundedBody(request,60000))),id=req(b.id,80),mode=req(b.mode,40),db=storage(),now=new Date().toISOString();if(!/^[a-f0-9-]{36}$/i.test(id)||b.confirmed!==true)fail('شناسه و تأیید صریح لازم است.');
 const {supplier,link}=await supplierScope(u,req(b.supplierId),b.linkId?req(b.linkId):'');if(!supplierManage(u)&&!supplierQuality(u))fail('مجوز ثبت ندارید.',403);
 const signature=JSON.stringify(b),oldOp:any=await db.prepare('SELECT * FROM inventory_operations WHERE id=?').bind(id).first();if(oldOp){if(oldOp.actor!==u.userId||oldOp.payload!==signature)fail('شناسه عملیات تکراری متفاوت است.',409);return json({saved:true,repeated:true});}
 const checks:D1PreparedStatement[]=[],writes:D1PreparedStatement[]=[],guard=(e:any)=>checks.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN guard ELSE 0 END WHERE id=?').bind(e.id,e.revision,id));guard(supplier);if(link)guard(link);
 const get=async(eid:string,type:string)=>{const e=await supplierEntity(eid,type);if(e.data.supplierId!==supplier.id||(e.data.linkId||'')!==(link?.id||''))fail('رکورد متعلق به این پرونده نیست.',404);guard(e);return e;};
 const put=(eid:string,type:string,d:any,old?:any)=>writes.push(old?db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=? AND revision=?').bind(JSON.stringify(d),now,eid,old.revision):db.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').bind(eid,type,JSON.stringify(d),now,now));
 const date=(v:any,future=false)=>{const d=req(v,10);if(!validDay(d)||future&&d<dayAt())fail('تاریخ معتبر لازم است؛ موعد جدید در گذشته نباشد.');return d;};
 const files=async(v:any,capaId='')=>{if(!Array.isArray(v)||v.length<1||v.length>20||new Set(v).size!==v.length)fail('یک تا بیست مدرک غیرتکراری انتخاب کنید.');const list=[];for(const did of v){const e=await supplierEntity(req(did),'supplier_document');if(e.data.supplierId!==supplier.id||e.data.linkId&&e.data.linkId!==link?.id||e.data.capaId&&e.data.capaId!==capaId||!documentVisible(u,e.data,supplier.data.route)||['rejected','withdrawn'].includes(e.data.state))fail('مدرک انتخاب‌شده متعلق به این پرونده یا قابل استفاده نیست.');guard(e);list.push({id:e.id,revision:e.revision,sha256:e.data.sha256,filename:e.data.filename});}return list;};
 let target=id;
 if(mode==='document_review'){
  if(!supplierQuality(u))fail('بررسی مدرک فقط با کنترل کیفیت است.',403);const e=await get(req(b.documentId),'supplier_document');target=e.id;if(!documentVisible(u,e.data,supplier.data.route))fail('مجوز مدرک مالی ندارید.',403);if(e.revision!==b.revision)fail('مدرک تغییر کرده است.',409);if(e.data.state==='superseded')fail('نسخه پیشین قابل تغییر نیست.');if(!['approved','rejected','withdrawn'].includes(b.result)||typeof b.requiredForPurchase!=='boolean')fail('نتیجه و الزام خرید معتبر لازم است.');if(b.requiredForPurchase&&!link)fail('الزام خرید را روی مدرک مرتبط با کالا تعیین کنید.');if(b.result==='approved'&&e.data.expiresOn&&e.data.expiresOn<dayAt())fail('مدرک منقضی قابل تأیید نیست.');
  let required=[...(link?.data.requiredDocumentIds||[])];const note=req(b.notes,4000);if(b.result==='approved'&&e.data.previousId){const prev=await get(e.data.previousId,'supplier_document');if(prev.data.state==='superseded'&&prev.data.supersededBy!==e.id)fail('نسخه جدید دیگری قبلاً تأیید شده است.',409);if(prev.data.state!=='superseded')put(prev.id,'supplier_document',{...prev.data,state:'superseded',supersededBy:e.id,history:[...(prev.data.history||[]),{mode:'superseded',next:e.id,actor:u.userId,at:now}]},prev);required=required.filter(x=>x!==prev.id);}
  // Revocation of a mandatory document keeps the requirement until QC explicitly removes it.
  required=required.filter(x=>x!==e.id);if(b.requiredForPurchase)required.push(e.id);
  put(e.id,'supplier_document',{...e.data,state:b.result,requiredForPurchase:b.requiredForPurchase,reviewedBy:u.userId,reviewedAt:now,history:[...(e.data.history||[]),{mode,result:b.result,requiredForPurchase:b.requiredForPurchase,note,actor:u.userId,at:now}]},e);
  if(link)link.data.requiredDocumentIds=required;
 }else if(mode==='capa_create'){
  if(!link)fail('اقدام اصلاحی باید به یک کالای تأمین‌کننده متصل باشد.');if(!Object.hasOwn(supplierSeverities,b.severity))fail('شدت مشکل معتبر نیست.');const detectedOn=date(b.detectedOn);if(detectedOn>dayAt())fail('تاریخ کشف در آینده نباشد.');const owner=await qualityMember(req(b.ownerId),supplier.data.route,'owner'),reviewer=await qualityMember(req(b.reviewerId),supplier.data.route,'reviewer');if(owner.id===reviewer.id)fail('مسئول اجرا و بررسی‌کننده مستقل باشند.');
  if(!Array.isArray(b.receiptIds)||b.receiptIds.length>50||new Set(b.receiptIds).size!==b.receiptIds.length)fail('فهرست بچ‌های درگیر معتبر نیست.');const receipts=[];for(const rid of b.receiptIds){const r=await supplierEntity(req(rid),'receipt'),o=await supplierEntity(r.data.purchaseOrderId||'','purchase_order');if(o.data.supplierLinkId!==link.id)fail('بچ به خرید همین تأمین‌کننده و کالا متصل نیست.');guard(r);guard(o);receipts.push({id:r.id,manufacturerLot:r.data.manufacturerLot||'',day:r.data.day,quantity:r.data.quantity,unit:r.data.unit,orderId:o.id});}
  const externalLots=txt(b.externalLots||'',3000);if(!receipts.length&&!externalLots)fail('بچ‌های درگیر یا شرح دامنه اثر/عدم کاربرد را بنویسید.');const hold=b.holdPurchase===true;if(hold&&!supplierQuality(u))fail('توقف خرید فقط با کنترل کیفیت است.',403);
  put(id,'supplier_capa',{supplierId:supplier.id,supplierName:supplier.data.name,route:supplier.data.route,linkId:link.id,materialId:link.data.materialId,partCode:link.data.partCode,title:req(b.title,200),description:req(b.description,4000),severity:b.severity,detectedOn,containment:req(b.containment,4000),externalLots,receipts,ownerId:owner.id,ownerName:owner.name,reviewerId:reviewer.id,reviewerName:reviewer.name,responseDue:date(b.responseDue,true),state:'open',cycle:1,holdPurchase:hold,history:[{mode,actor:u.userId,at:now}]});
 }else{
  if(!link)fail('کالا را انتخاب کنید.');const e=await get(req(b.capaId),'supplier_capa'),d={...e.data};target=e.id;if(e.revision!==b.revision)fail('پرونده تغییر کرده است.',409);const mid=await memberId(u),note=req(b.notes,4000);
  if(mode==='capa_respond'){
   if(!u.isAdmin&&mid!==d.ownerId)fail('ثبت پاسخ با مسئول پیگیری است.',403);if(d.state!=='open')fail('پرونده منتظر پاسخ نیست.');const implementedOn=date(b.implementedOn);if(implementedOn>dayAt()||implementedOn<d.detectedOn)fail('تاریخ اجرا از کشف مشکل تا امروز باشد.');const verificationDue=date(b.verificationDue,true);if(verificationDue<implementedOn)fail('موعد اثربخشی پس از اجرا باشد.');d.response={supplierResponse:req(b.supplierResponse,4000),rootCause:req(b.rootCause,4000),correction:req(b.correction,4000),correctiveAction:req(b.correctiveAction,4000),verificationMethod:req(b.verificationMethod,4000),implementedOn,evidence:await files(b.evidenceIds,e.id),by:u.userId,at:now};d.verificationDue=verificationDue;d.state='verification';
  }else if(mode==='capa_verify'){
   if(!supplierQuality(u)||!u.isAdmin&&mid!==d.reviewerId)fail('بررسی اثربخشی با بررسی‌کننده کنترل کیفیت است.',403);if(d.state!=='verification')fail('ابتدا پاسخ و شواهد اجرا ثبت شود.');if(!['effective','ineffective'].includes(b.result))fail('نتیجه معتبر نیست.');if(b.result==='effective'&&dayAt()<d.verificationDue)fail('موعد مشاهده اثربخشی هنوز نرسیده است.');const evidence=await files(b.evidenceIds,e.id);d.verification={result:b.result,notes:note,evidence,by:u.userId,at:now};if(b.result==='effective'){d.state='closed';d.closedAt=now;d.holdPurchase=false;}else{d.state='open';d.cycle++;d.responseDue=date(b.responseDue,true);}
  }else if(mode==='capa_reopen'){
   if(!supplierQuality(u))fail('بازگشایی با کنترل کیفیت است.',403);if(d.state!=='closed')fail('پرونده بسته نیست.');d.state='open';d.cycle++;d.responseDue=date(b.responseDue,true);delete d.closedAt;
  }else if(mode==='capa_hold'){
   if(!supplierQuality(u))fail('تصمیم خرید با کنترل کیفیت است.',403);if(d.state==='closed'||typeof b.holdPurchase!=='boolean')fail('پرونده باز و تصمیم معتبر لازم است.');d.holdPurchase=b.holdPurchase;
  }else fail('عملیات ناشناخته است.');
  d.history=[...d.history,{mode,actor:u.userId,at:now,note,result:b.result,holdPurchase:d.holdPurchase,response:mode==='capa_respond'?d.response:undefined,verification:mode==='capa_verify'?d.verification:undefined}];put(e.id,'supplier_capa',d,e);
 }
 // Link revision protects purchase decisions against concurrent document/CAPA changes.
 if(link)put(link.id,'supplier_material',link.data,link);
 await db.batch([db.prepare('INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,?,?,?,?,1)').bind(id,'supplier_quality_'+mode,signature,u.userId,now),...checks,...writes,db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,target,'supplier_quality_'+mode,signature,now)]);
 try{await syncSupplierQuality();}catch{console.error('Supplier quality task projection deferred');}return json({saved:true,id:target});
 }catch(e){return accessResponse(e)||json({error:/constraint|SQLITE|D1/i.test(String(e))?'اطلاعات هم‌زمان تغییر کرده؛ تازه‌سازی کنید.':e instanceof Error?e.message:'ثبت انجام نشد.'},409)}}
