import {storage} from '@/lib/storage';
import {holdChecks,supplyLock,allocateAcceptedPurchase} from '@/lib/sourcing';
import {requireAccess,checkOrigin,AccessError,accessResponse} from '@/lib/authorization';
import {flowRole,flowRoles,entity,suggestion,warehouseAccess} from '@/lib/material-flow';
import {qualityFields,qualityValues} from '@/lib/quality';
import {scaled} from '@/lib/production';
import {normalizePartCode,receiptDay,suggestBatchNumber} from '@/lib/batch-number';
import {tehranDay,serialPrefix,nextSerials} from '@/lib/serials';
import {boundedBody} from '@/lib/firmware-storage';
const fail=(s:string,status=400):never=>{throw new AccessError(s,status)};
const text=(s:unknown,max=4000)=>{if(typeof s!=='string'||s.length>max)fail('متن معتبر نیست.');return (s as string).trim()};
const needed=(s:unknown,max=200)=>{const v=text(s,max);if(!v)fail('فیلد الزامی خالی است.');return v};
const zero=(s:unknown)=>String(s)==='0'?0:scaled(s);
const arr=(a:any,max=80)=>{if(!Array.isArray(a)||!a.length||a.length>max)fail('فهرست خالی یا بیش از حد مجاز است.');return a as any[]};
const json=(data:unknown)=>Response.json(data,{headers:{'Cache-Control':'no-store'}});
export async function GET(){try{
 const u=await requireAccess();if(!['inventory','qc','production','procurement'].some(r=>flowRole(u,r)))fail('دسترسی گردش مواد ندارید.',403);const db=storage();
 const all=(await db.prepare('SELECT * FROM flow_entities ORDER BY created DESC,id').all()).results.map(entity);
 const rows=(await db.prepare("SELECT * FROM records WHERE kind IN ('batch','product','device')").all()).results.map((r:any)=>({...r,data:JSON.parse(r.payload),payload:undefined}));
 const balances=(await db.prepare('SELECT * FROM inventory_balances').all()).results;
 const boms=(await db.prepare('SELECT * FROM bom_versions ORDER BY version DESC').all()).results;
 const builds=all.filter(r=>r.type==='build'),receipts=all.filter(r=>r.type==='receipt'),materials=all.filter(r=>r.type==='material');
 const lowStock=materials.map(m=>({materialId:m.id,...suggestion(m,balances,receipts,builds,boms)}));
 const allowed=u.isAdmin?all:all.filter(e=>e.type==='material'||e.type==='capacity'||e.type==='supply'&&flowRole(u,'procurement')||['receipt','request'].includes(e.type)&&['inventory','qc','production'].some(r=>flowRole(u,r))||['plan','build','repair','finaltest','assignment'].includes(e.type)&&['production','qc'].some(r=>flowRole(u,r)));
 const members=(await db.prepare("SELECT id,name,subject,permissions FROM app_members WHERE status='active'").all()).results.map((m:any)=>({id:m.id,name:m.name,roles:JSON.parse(m.permissions).flowRoles||[]}));
 return json({warehouseIds:["raw","line","quarantine","nonconforming","finished"].filter(w=>warehouseAccess(u,w)),entities:allowed,rows:rows.filter((r:any)=>r.kind!=='device'||flowRole(u,'production')||flowRole(u,'qc')),balances:balances.filter((b:any)=>!String(b.item_id).startsWith('device:')||flowRole(u,'production')||flowRole(u,'qc')),slots:(await db.prepare('SELECT * FROM flow_slots WHERE quantity>0').all()).results,boms,members,lowStock,roles:flowRoles.filter(r=>flowRole(u,r))});
 }catch(e){return accessResponse(e)||Response.json({error:'دریافت گردش مواد ممکن نشد.'},{status:503})}}
export async function POST(request:Request){try{
 checkOrigin(request);const u=await requireAccess();const b=JSON.parse(new TextDecoder().decode(await boundedBody(request,180000)));const id=needed(b.id,80);if(!/^[a-f0-9-]{36}$/i.test(id))fail('شناسه عملیات معتبر نیست.');const mode=needed(b.mode,40),db=storage(),now=new Date().toISOString();
 const role:Record<string,string>={material:'inventory',receipt:'inventory',incoming_qc:'qc',shelve:'inventory',request:'production',issue:'inventory',supply:'inventory',supply_close:'procurement',capacity:'production',plan:'production',assign:'production',prepare:'production',build:'production',reject:'production',repair:'production',print:'production'};
 if(!role[mode]||!flowRole(u,role[mode]))fail('دسترسی این عملیات را ندارید.',403);
 if(mode==='receipt'&&!warehouseAccess(u,'quarantine')||mode==='shelve'&&(!warehouseAccess(u,'quarantine')||!warehouseAccess(u,'raw'))||mode==='issue'&&!warehouseAccess(u,'raw'))fail('این انبار در مسئولیت شما نیست.',403);
 const signature=JSON.stringify(b),prior:any=await db.prepare('SELECT payload,actor FROM inventory_operations WHERE id=?').bind(id).first();if(prior){if(prior.payload!==signature||prior.actor!==u.userId)fail('شناسه درخواست تکراری است.',409);return json({saved:true,repeated:true});}
 const stmts:D1PreparedStatement[]=[],guards:string[]=[],params:any[]=[],checks:D1PreparedStatement[]=await supplyLock(db,id);
 const flush=()=>{if(guards.length){checks.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN '+guards.join(' AND ')+' THEN 1 ELSE 0 END WHERE id=?').bind(...params,id));guards.length=0;params.length=0;}};
 const guard=(s:string,...p:any[])=>{if(params.length+p.length>75)flush();guards.push(s);params.push(...p)};
 async function get(eid:string,type:string){const r:any=await db.prepare('SELECT * FROM flow_entities WHERE id=? AND type=?').bind(eid,type).first();if(!r)fail('رکورد گردش کار پیدا نشد.');guard('EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?)',r.id,r.revision);return entity(r)}
 async function record(eid:string,kind:string){const r:any=await db.prepare('SELECT * FROM records WHERE id=? AND kind=?').bind(eid,kind).first();if(!r)fail('کالا یا دستگاه پیدا نشد.');guard('EXISTS(SELECT 1 FROM records WHERE id=? AND payload=?)',r.id,r.payload);return {...r,data:JSON.parse(r.payload)}}
 const put=(eid:string,type:string,data:any,old?:any)=>{if(old)stmts.push(db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=? AND revision=?').bind(JSON.stringify(data),now,eid,old.revision));else stmts.push(db.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').bind(eid,type,JSON.stringify(data),now,now));};
 const touchedStock:string[]=[];
 const entry=(item:string,warehouse:string,delta:number)=>{touchedStock.push(item);const bid=item+'@'+warehouse;stmts.push(db.prepare('INSERT INTO inventory_balances(id,item_id,warehouse,quantity) VALUES(?,?,?,0) ON CONFLICT(id) DO NOTHING').bind(bid,item,warehouse),db.prepare('UPDATE inventory_balances SET quantity=quantity+? WHERE id=?').bind(delta,bid),db.prepare('INSERT INTO inventory_entries(id,operation_id,item_id,warehouse,delta) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),id,item,warehouse,delta));};
 const event=(device:string,stage:string,data:any)=>stmts.push(db.prepare("INSERT INTO records(id,kind,payload,created) VALUES(?,'event',?,?)").bind(crypto.randomUUID(),JSON.stringify({device,stage,date:tehranDay(),operator:u.name,...data}),now));
 async function assignee(mid:string,role:string){if(!mid)return '';const m:any=await db.prepare("SELECT permissions FROM app_members WHERE id=? AND status='active'").bind(mid).first();if(!m||!(JSON.parse(m.permissions).flowRoles||[]).includes(role))fail('مسئول انتخاب‌شده دسترسی این مرحله را ندارد.');return mid;}
 function assigned(e:any,key:string){if(u.isAdmin)return;const owner=e.data[key];if(owner&&u.userId!=='local:'+owner&&u.userId!==owner)guard('EXISTS(SELECT 1 FROM app_members WHERE id=? AND subject=?)',owner,u.userId);}
 if(mode==='material'){
 const code=normalizePartCode(needed(b.code,12)),eid='material:'+code;const oldRaw:any=await db.prepare('SELECT * FROM flow_entities WHERE id=?').bind(eid).first();let old:any;if(oldRaw){old=await get(eid,'material');if(b.revision!==old.revision)fail('شناسنامه تغییر کرده است.',409);}
 const unit=needed(b.unit,20);if(!['عدد','کیلوگرم','متر','لیتر'].includes(unit))fail('واحد معتبر نیست.');if(old&&old.data.unit!==unit)fail('واحد کالای تعریف‌شده ثابت است.');
 const reorderPoint=zero(b.reorderPoint),targetStock=zero(b.targetStock);if(targetStock<reorderPoint)fail('موجودی هدف کمتر از حد سفارش نباشد.');
 put(eid,'material',{...(old?.data||{}),code,name:needed(b.name),unit,specs:text(b.specs||''),defaultLocation:text(b.defaultLocation||'',100),reorderPoint,targetStock,fields:qualityFields(b.fields),qcOwner:await assignee(text(b.qcOwner||'',100),'qc'),warehouseOwner:await assignee(text(b.warehouseOwner||'',100),'inventory'),procurementOwner:await assignee(text(b.procurementOwner||'',100),'procurement')},old);
 }else if(mode==='receipt'){
 const m=await get(needed(b.materialId),'material'),day=needed(b.day,10);receiptDay(day);const quantity=scaled(b.quantity),expiry=text(b.expiry||'',10);if(expiry){receiptDay(expiry);if(expiry<day)fail('تاریخ انقضا قبل از ورود است.');}
 let purchaseOrder:any;const purchaseOrderId=text(b.purchaseOrderId||'',200);if(purchaseOrderId){purchaseOrder=await get(purchaseOrderId,'purchase_order');if(!['issued','paid','preparing','shipped'].includes(purchaseOrder.data.state)||purchaseOrder.data.materialId!==m.id)fail('سفارش خرید صادرشده و منطبق با کالا لازم است.');const arrivals=(await db.prepare("SELECT data FROM flow_entities WHERE type='receipt' AND json_extract(data,'$.purchaseOrderId')=?").bind(purchaseOrderId).all()).results.map((r:any)=>JSON.parse(r.data));const committed=arrivals.reduce((n:number,r:any)=>n+(r.state==='pending_qc'?r.quantity:r.accepted),0);if(committed+quantity>purchaseOrder.data.quantity)fail('مقدار از مانده سفارش پس از کسر اقلام پذیرفته/در انتظار QC بیشتر است.');put(purchaseOrder.id,'purchase_order',{...purchaseOrder.data,lastReceiptAt:now},purchaseOrder);}
 const existing=(await db.prepare("SELECT json_extract(payload,'$.code') AS code FROM records WHERE kind='batch'").all()).results.map((r:any)=>r.code);const code=suggestBatchNumber(m.data.code,day,existing).code,batchId='batch:'+code;
 const data={partCode:m.data.code,part:m.data.name,date:day,code,quantity:String(quantity/1000),unit:m.data.unit,status:'قرنطینه',supplier:needed(b.supplier),maker:text(b.maker||'',200),manufacturerLot:text(b.manufacturerLot||'',200),purchase:text(b.purchase||'',200),notes:text(b.notes||''),specs:text(b.specs??m.data.specs),batchScheme:'part-jalali-v1',expiry};
 stmts.push(db.prepare("INSERT INTO records(id,kind,payload,created) VALUES(?,'batch',?,?)").bind(batchId,JSON.stringify(data),now),db.prepare('INSERT INTO inventory_batches(batch_id,part_code,unit,created) VALUES(?,?,?,?)').bind(batchId,m.data.code,m.data.unit,now));entry(batchId,'quarantine',quantity);
 put(batchId,'receipt',{batchId,materialId:m.id,materialRevision:m.revision,fields:m.data.fields,specs:data.specs,quantity,accepted:0,rejected:0,state:'pending_qc',purchaseOrderId,qcOwner:m.data.qcOwner,warehouseOwner:m.data.warehouseOwner,expiry,day,actor:u.userId});
 }else if(mode==='incoming_qc'){
 const r=await get(needed(b.receiptId),'receipt');assigned(r,'qcOwner');if(r.data.state!=='pending_qc')fail('کنترل ورودی قبلاً ثبت شده است.',409);
 const accepted=zero(b.accepted),rejected=zero(b.rejected);if(accepted+rejected!==r.data.quantity)fail('جمع تعداد پذیرفته و ردشده باید برابر مقدار ورودی باشد.');const checked=qualityValues(r.data.fields,b.values);const notes=needed(b.notes,4000);if(checked.failed&&accepted===r.data.quantity)fail('با معیار مردود، تأیید کامل مجاز نیست.');
 put(r.id,'receipt',{...r.data,accepted,rejected,state:accepted?'awaiting_warehouse':'rejected',qc:{values:checked.values,failed:checked.failed,notes,by:u.name,actor:u.userId,at:now}},r);
 const batch=await record(r.data.batchId,'batch');stmts.push(db.prepare('UPDATE records SET payload=? WHERE id=?').bind(JSON.stringify({...batch.data,status:accepted?'تأیید':'رد',test:notes}),batch.id));
 }else if(mode==='shelve'){
 const r=await get(needed(b.receiptId),'receipt');assigned(r,'warehouseOwner');if(r.data.state!=='awaiting_warehouse')fail('این بچ آماده انتقال نیست.');const loc=needed(b.location,100);if(!/^[^\s]+-[^\s]+-[^\s]+-[^\s]+$/.test(loc))fail('محل را به صورت راهرو-قفسه-طبقه-خانه وارد کنید.');
 guard('NOT EXISTS(SELECT 1 FROM flow_slots WHERE location=? AND quantity>0 AND batch_id<>?)',loc,r.data.batchId);
 stmts.push(db.prepare('INSERT INTO flow_slots(location,batch_id,quantity) VALUES(?,?,?) ON CONFLICT(location) DO UPDATE SET batch_id=excluded.batch_id,quantity=flow_slots.quantity+excluded.quantity').bind(loc,r.data.batchId,r.data.accepted));entry(r.data.batchId,'quarantine',-r.data.accepted);entry(r.data.batchId,'raw',r.data.accepted);if(r.data.purchaseOrderId)stmts.push(...await allocateAcceptedPurchase(r.data.purchaseOrderId,r.data.batchId,r.data.accepted));put(r.id,'receipt',{...r.data,state:'stored',location:loc,storedBy:u.name,storedAt:now},r);
 }else if(mode==='request'){
 const m=await get(needed(b.materialId),'material');const planId=text(b.planId||'',200);if(planId)await get(planId,'plan');put(id,'request',{materialId:m.id,quantity:scaled(b.quantity),planId,notes:text(b.notes||''),state:'pending',requestedBy:u.name,warehouseOwner:m.data.warehouseOwner});
 }else if(mode==='issue'){
 const r=await get(needed(b.requestId),'request');assigned(r,'warehouseOwner');if(r.data.state!=='pending')fail('درخواست قبلاً تحویل شده است.',409);const allocations=arr(b.allocations,40);let total=0;const seen=new Set();const reason=text(b.reason||'');
 const candidates=(await db.prepare("SELECT f.*,s.location,s.quantity AS stock FROM flow_entities f JOIN flow_slots s ON s.batch_id=f.id WHERE f.type='receipt' AND json_extract(f.data,'$.materialId')=? AND s.quantity>0 ORDER BY CASE WHEN json_extract(f.data,'$.expiry')<>'' THEN 0 ELSE 1 END,json_extract(f.data,'$.expiry'),json_extract(f.data,'$.day'),f.created,s.location").bind(r.data.materialId).all()).results;
 // Check all slot balances used in the recommendation, so a concurrent issue cannot invalidate FIFO silently.
 for(const c of candidates as any[])guard('EXISTS(SELECT 1 FROM flow_slots WHERE location=? AND batch_id=? AND quantity=?)',c.location,c.id,c.stock);
 const expected:Record<string,number>={};let remaining=r.data.quantity;for(const c of candidates as any[]){const d=JSON.parse(c.data);if(d.expiry&&d.expiry<tehranDay())continue;const n=Math.min(remaining,c.stock);if(n>0)expected[c.location]=n;remaining-=n;if(!remaining)break;}
 const actual:Record<string,number>={};for(const a of allocations){const loc=needed(a.location,100);if(seen.has(loc))fail('محل تکراری است.');seen.add(loc);const q=scaled(a.quantity),batch=await get(needed(a.batchId),'receipt');if(batch.data.materialId!==r.data.materialId||batch.data.state!=='stored'||batch.data.expiry&&batch.data.expiry<tehranDay())fail('بچ قابل برداشت نیست.');const rec=await record(batch.data.batchId,'batch');if(rec.data.status!=='تأیید')fail('بچ تأیید نشده است.');guard('EXISTS(SELECT 1 FROM flow_slots WHERE location=? AND batch_id=? AND quantity>=?)',loc,batch.id,q);stmts.push(db.prepare('UPDATE flow_slots SET quantity=quantity-? WHERE location=?').bind(q,loc));entry(batch.id,'raw',-q);entry(batch.id,'line',q);actual[loc]=q;total+=q;}
 if(total!==r.data.quantity)fail('جمع برداشت با مقدار درخواست برابر نیست.');if(JSON.stringify(Object.entries(expected).sort())!==JSON.stringify(Object.entries(actual).sort())&&!reason)fail('برای تغییر پیشنهاد قدیمی‌ترین بچ / نزدیک‌ترین انقضا دلیل فنی بنویسید.');put(r.id,'request',{...r.data,state:'issued',allocations,reason,issuedBy:u.name,issuedAt:now},r);
 }else if(mode==='supply'){
 const m=await get(needed(b.materialId),'material');guard("NOT EXISTS(SELECT 1 FROM flow_entities WHERE type='supply' AND json_extract(data,'$.materialId')=? AND json_extract(data,'$.state')='open')",m.id);put(id,'supply',{materialId:m.id,snapshot:m.data,quantity:scaled(b.quantity),notes:needed(b.notes,4000),state:'open',owner:m.data.procurementOwner,by:u.name});
 }else if(mode==='supply_close'){
 const r=await get(needed(b.supplyId),'supply');assigned(r,'owner');if(r.data.state!=='open')fail('درخواست تأمین بسته است.');put(r.id,'supply',{...r.data,state:'closed',result:needed(b.result,4000),closedBy:u.name},r);
 }else if(mode==='capacity'){
 const product=await record(needed(b.productId),'product');const cap=Number(b.capacity),small=Number(b.smallLabels);if(!Number.isInteger(cap)||cap<1||cap>100||!Number.isInteger(small)||small<0||small>20)fail('ظرفیت ۱ تا ۱۰۰ و تعداد برچسب کوچک صفر تا ۲۰ باشد.');const eid='capacity:'+product.id,raw:any=await db.prepare('SELECT * FROM flow_entities WHERE id=?').bind(eid).first(),old=raw?await get(eid,'capacity'):undefined;if(old&&b.revision!==old.revision)fail('تنظیمات تغییر کرده است.',409);put(eid,'capacity',{productId:product.id,capacity:cap,smallLabels:small},old);
 }else if(mode==='plan'){
 const product=await record(needed(b.productId),'product');if(product.data.status!=='فعال')fail('محصول فعال نیست.');const capacity=await get('capacity:'+product.id,'capacity');const count=Number(b.count);if(!Number.isInteger(count)||count<1||count>100)fail('تعداد باید بین ۱ تا ۱۰۰ باشد.');const bom:any=await db.prepare('SELECT * FROM bom_versions WHERE product_id=? ORDER BY version DESC LIMIT 1').bind(product.id).first();if(!bom)fail('ابتدا BOM تعریف کنید.');for(const l of JSON.parse(bom.lines)){const m=await get('material:'+l.partCode,'material');if(m.data.unit!==l.unit)fail('واحد BOM باید با شناسنامه ماده اولیه یکسان باشد.');}const form:any=await db.prepare('SELECT * FROM quality_templates WHERE product_id=? ORDER BY version DESC LIMIT 1').bind(product.id).first();if(!form)fail('ابتدا فرم کنترل کیفیت نهایی محصول را تعریف کنید.');
 const day=tehranDay(),prefix=serialPrefix(product.data.code,day);const existing=(await db.prepare("SELECT serial FROM serial_reservations WHERE serial>=? AND serial<? UNION ALL SELECT substr(id,8) AS serial FROM records WHERE id>=? AND id<? AND kind='device'").bind(prefix,prefix+'\uffff','device:'+prefix,'device:'+prefix+'\uffff').all()).results.map((r:any)=>r.serial);const serials=nextSerials(prefix,existing,count);
 const booked:any=await db.prepare("SELECT COALESCE(SUM(json_extract(data,'$.count')),0) AS n FROM flow_entities WHERE type='plan' AND json_extract(data,'$.productId')=? AND json_extract(data,'$.day')=?").bind(product.id,day).first();const reason=text(b.reason||'');if(booked.n+count>capacity.data.capacity&&!reason)fail('تعداد بیش از ظرفیت روز است؛ دلیل ثبت کنید.');
 guard("(SELECT COALESCE(SUM(json_extract(data,'$.count')),0) FROM flow_entities WHERE type='plan' AND json_extract(data,'$.productId')=? AND json_extract(data,'$.day')=?)=?",product.id,day,booked.n);
 const design=needed(b.design),runData={name:product.data.name,model:product.data.model,code:product.data.code,count,operator:u.name,jalaliDate:receiptDay(day).display,smallLabels:capacity.data.smallLabels};stmts.push(db.prepare('INSERT INTO serial_runs(id,product_id,actor,day,payload,created) VALUES(?,?,?,?,?,?)').bind(id,product.id,u.userId,day,JSON.stringify(runData),now));
 put(id,'plan',{productId:product.id,count,day,bomId:bom.id,templateId:form.id,smallLabels:capacity.data.smallLabels,reason,by:u.name});
 for(const serial of serials){const did='device:'+serial;stmts.push(db.prepare('INSERT INTO serial_reservations(serial,run_id,product_id) VALUES(?,?,?)').bind(serial,id,product.id),db.prepare("INSERT INTO records(id,kind,payload,created) VALUES(?,'device',?,?)").bind(did,JSON.stringify({product:product.id,productName:product.data.name,productCode:product.data.code,warrantyMonths:product.data.warrantyMonths||'',code:serial,model:product.data.model,design,firmware:text(b.firmware||'',200),date:day}),now));put(did,'build',{deviceId:did,planId:id,bomId:bom.id,templateId:form.id,state:'planned',assembler:'',materials:[],workflowVersion:2});}
 }else if(mode==='assign'){
 const assembler=needed(b.assembler),reason=text(b.reason||'');for(const did of arr(b.deviceIds,100)){const build=await get(did,'build');if(build.data.state!=='planned')fail('تخصیص پس از ثبت مصرف قابل تغییر نیست.');if(build.data.assembler&&!reason)fail('علت تغییر مونتاژکار لازم است.');put(did,'build',{...build.data,assembler},build);put(id+':'+did,'assignment',{deviceId:did,from:build.data.assembler,to:assembler,reason,by:u.name});}
 }else if(mode==='prepare'||mode==='build'){
 const build=await get(needed(b.deviceId),'build');if(!build.data.assembler||!(mode==='prepare'?['planned','prepared'].includes(build.data.state):build.data.workflowVersion===2?build.data.state==='prepared':build.data.state==='planned'))fail('وضعیت سریال برای این مرحله معتبر نیست.');
 if(mode==='build'&&build.data.workflowVersion===2&&build.data.latestQc?.verdict!=='pass')fail('ابتدا کنترل کیفیت نهایی را با موفقیت ثبت کنید.');
 if(mode==='build'&&build.data.workflowVersion===2&&JSON.stringify(Array.isArray(b.allocations)?b.allocations.map((a:any)=>({batchId:a.batchId,quantity:String(Number(a.quantity))})):[])!==JSON.stringify(build.data.materials.filter((m:any)=>m.quantity>0).map((m:any)=>({batchId:m.batchId,quantity:String(m.quantity/1000)}))))fail('مصرف نهایی باید همان بچ‌های بررسی‌شده باشد؛ برای تغییر ابتدا مواد را ویرایش و آزمون را تکرار کنید.');const bom:any=await db.prepare('SELECT * FROM bom_versions WHERE id=?').bind(build.data.bomId).first();const lines=JSON.parse(bom.lines),allocations=arr(b.allocations,80),totals:Record<string,number>={},materials:any[]=[],notes=text(b.notes||'');const seen=new Set();
 for(const a of allocations){const batch=await record(needed(a.batchId),'batch'),r=await get(batch.id,'receipt'),q=scaled(a.quantity);if(seen.has(batch.id))fail('بچ مصرفی تکراری است.');seen.add(batch.id);if(batch.data.status!=='تأیید'||r.data.expiry&&r.data.expiry<tehranDay())fail('بچ مصرفی تأییدشده و معتبر نیست.');const l=lines.find((l:any)=>l.partCode===batch.data.partCode&&l.unit===batch.data.unit);if(!l)fail('قطعه خارج از BOM است.');totals[l.partCode]=(totals[l.partCode]||0)+q;if(mode==='build')entry(batch.id,'line',-q);else guard("EXISTS(SELECT 1 FROM inventory_balances WHERE item_id=? AND warehouse='line' AND quantity>=?)",batch.id,q);materials.push({batchId:batch.id,partCode:l.partCode,quantity:q});if(mode==='build')event(build.id,'مصرف قطعه',{batch:batch.id,quantity:String(q/1000),operator:build.data.assembler,productionOrder:build.id,notes:'ثبت مصرف واقعی در برگ تولید'});}
 if(mode==='prepare'){
 const expected:Record<string,number>={};for(const l of lines){let remaining=scaled(l.quantity);const candidates=(await db.prepare("SELECT f.id,f.data,i.quantity FROM flow_entities f JOIN inventory_balances i ON i.item_id=f.id AND i.warehouse='line' JOIN records r ON r.id=f.id WHERE f.type='receipt' AND json_extract(r.payload,'$.partCode')=? AND json_extract(r.payload,'$.status')='تأیید' AND i.quantity>0 ORDER BY json_extract(f.data,'$.day'),f.created,f.id").bind(l.partCode).all()).results;for(const c of candidates as any[]){const receipt=JSON.parse(c.data);if(receipt.expiry&&receipt.expiry<tehranDay())continue;const q=Math.min(remaining,c.quantity);if(q)expected[c.id]=q;remaining-=q;if(!remaining)break;}}
 const actual=Object.fromEntries(materials.map(m=>[m.batchId,m.quantity]));if(JSON.stringify(Object.entries(actual).sort())!==JSON.stringify(Object.entries(expected).sort())&&!notes)fail('برای تغییر بچ قدیمی‌تر پیشنهادی یا مقدار BOM، توضیح فنی بنویسید.');
 }
 if(lines.some((l:any)=>!totals[l.partCode]))fail('همه قطعات BOM را مشخص کنید.');if(lines.some((l:any)=>totals[l.partCode]!==scaled(l.quantity))&&!notes)fail('تفاوت مصرف واقعی با BOM به توضیح نیاز دارد.');put(build.id,'build',{...build.data,state:mode==='prepare'?'prepared':'assembled',materials,notes,...(mode==='prepare'?{latestQc:null}:{builtAt:now,builtBy:u.name})},build);if(mode==='build')event(build.id,'مونتاژ',{operator:build.data.assembler,notes});
 }else if(mode==='reject'){
 const batch=await record(needed(b.batchId),'batch');await get(batch.id,'receipt');const quantity=scaled(b.quantity),reason=needed(b.reason,4000);entry(batch.id,'line',-quantity);entry(batch.id,'nonconforming',quantity);put(id,'repair',{kind:'line_reject',batchId:batch.id,quantity,reason,by:u.name});
 }else if(mode==='repair'){
 const build=await get(needed(b.deviceId),'build');if(!['prepared','assembled'].includes(build.data.state))fail('ابتدا بچ‌های مصرفی را ثبت کنید.');const oldBatch=needed(b.oldBatchId),replacement=await record(needed(b.newBatchId),'batch'),r=await get(replacement.id,'receipt'),quantity=scaled(b.quantity),reason=needed(b.reason,4000),cause=needed(b.cause,40);if(!['part','assembly','design','test','unknown'].includes(cause))fail('علت معتبر نیست.');const old=build.data.materials.find((m:any)=>m.batchId===oldBatch);if(!old||old.quantity<quantity||old.partCode!==replacement.data.partCode||replacement.data.status!=='تأیید'||r.data.expiry&&r.data.expiry<tehranDay())fail('قطعه جایگزین یا تعداد خروج معتبر نیست.');entry(oldBatch,'nonconforming',quantity);if(build.data.state==='prepared')entry(oldBatch,'line',-quantity);else entry(replacement.id,'line',-quantity);
 const materials=build.data.materials.map((m:any)=>({...m,quantity:m.quantity-(m.batchId===oldBatch?quantity:0)}));const matching=materials.find((m:any)=>m.batchId===replacement.id);if(matching)matching.quantity+=quantity;else materials.push({batchId:replacement.id,partCode:old.partCode,quantity});put(build.id,'build',{...build.data,materials,latestQc:null,repairAt:now},build);put(id,'repair',{deviceId:build.id,oldBatchId:oldBatch,newBatchId:replacement.id,quantity,reason,cause,assembler:build.data.assembler,by:u.name});event(build.id,'تعویض قطعه',{batch:oldBatch,replacement:replacement.id,quantity:String(quantity/1000),notes:reason,cause});
 }else if(mode==='print'){
 const p=await get(needed(b.planId),'plan');put(id,'print',{planId:p.id,by:u.name,notes:text(b.notes||'')});
 }
 flush();await db.batch([db.prepare('INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,?,?,?,?,1)').bind(id,'flow_'+mode,signature,u.userId,now),...checks,...stmts,...holdChecks(db,id,touchedStock),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,id,'flow_'+mode,signature,now)]);
 return json({saved:true});
 }catch(e){const denial=accessResponse(e);if(denial)return denial;const s=String(e);return Response.json({error:/constraint|SQLITE|D1|Database/i.test(s)?'اطلاعات هم‌زمان تغییر کرده، محل اشغال است یا موجودی کافی نیست؛ هیچ تغییری ثبت نشد. تازه‌سازی کنید.':e instanceof Error?e.message:'ثبت انجام نشد.'},{status:/constraint|SQLITE/i.test(s)?409:400});}}
