import {storage} from '@/lib/storage';
import {checkOrigin,accessResponse} from '@/lib/authorization';
import {bootstrapAdmin,username,verifyPassword,digest,newToken,cookieName} from '@/lib/password-auth';
export async function POST(request:Request){try{checkOrigin(request);const b=await request.json() as any;const name=username(b.username);if(typeof b.password!=='string'||b.password.length>128)throw new Error('نام کاربری یا رمز عبور صحیح نیست.');const db=storage(),now=new Date().toISOString(),reset=new Date(Date.now()+15*60000).toISOString();
 await db.prepare('DELETE FROM login_attempts WHERE reset<=?').bind(now).run();
 const ip=request.headers.get('cf-connecting-ip')||'unknown';
 for(const [value,max] of [['user:'+name,10],['ip:'+ip,60]] as const){const k=await digest(value);const counter:any=await db.prepare('INSERT INTO login_attempts(key,count,reset) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN reset<=? THEN 1 ELSE count+1 END,reset=CASE WHEN reset<=? THEN excluded.reset ELSE reset END RETURNING count').bind(k,reset,now,now).first();if(counter.count>max)return Response.json({error:'تعداد تلاش‌ها زیاد است؛ ۱۵ دقیقه دیگر امتحان کنید.'},{status:429,headers:{'Retry-After':'900'}});}
 await bootstrapAdmin(name,b.password);
 const account:any=await db.prepare('SELECT a.*,m.status FROM password_accounts a JOIN app_members m ON m.id=a.member_id WHERE a.username=?').bind(name).first();const ok=await verifyPassword(b.password,account?.password_hash||'pbkdf2-sha256$100000$00000000000000000000000000000000$'+'0'.repeat(64));if(!account||!ok||account.status!=='active')return Response.json({error:'نام کاربری یا رمز عبور صحیح نیست.'},{status:401});const token=newToken(),expires=new Date(Date.now()+8*3600000).toISOString();const result=await db.batch([db.prepare('DELETE FROM password_sessions WHERE expires<=?').bind(now),db.prepare("INSERT INTO password_sessions(hash,member_id,version,expires,created) SELECT ?,a.member_id,a.version,?,? FROM password_accounts a JOIN app_members m ON m.id=a.member_id WHERE a.member_id=? AND a.version=? AND m.status='active'").bind(await digest(token),expires,now,account.member_id,account.version),db.prepare('DELETE FROM login_attempts WHERE key=?').bind(await digest('user:'+name))]);if(!result[1].meta.changes)return Response.json({error:'حساب تغییر کرده است؛ دوباره وارد شوید.'},{status:401});return Response.json({loggedIn:true},{headers:{'Cache-Control':'no-store','Set-Cookie':cookieName+'='+token+'; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=28800'}});
 }catch(e){return accessResponse(e)||Response.json({error:e instanceof Error&&!/D1|SQLITE/.test(e.message)?e.message:'ورود ممکن نشد؛ دوباره تلاش کنید.'},{status:400});}}
