import {parseCalendarDay} from './persian-date';
import {storage} from './storage';
import {AccessError} from './authorization';
import type {Session} from './permissions';
import {dayAt,taskRequired,taskText,validDay,addDay} from './duties';
import {solarParts,solarToIso,solarMonthDays,localDay} from './device-analytics';
import {firstWarrantyCodeIssuedAt} from './warranty';
import {normalizeSerial} from './distribution';
import {scaled} from './production';
import {serviceRoles,serviceDomains} from './after-sales-labels';
export function fail(s:string,status=400):never{throw new AccessError(s,status)}
export const req=taskRequired,txt=(v:unknown,max=4000)=>taskText(v??'',max);
export const decode=(r:any)=>({...r,data:JSON.parse(r.data)});
export const isAgent=(u:Session)=>!u.isAdmin&&!!u.permissions.serviceAgentId;
export const role=(u:Session,r:string)=>u.isAdmin||!!u.permissions.serviceRoles?.includes(r)||!isAgent(u)&&!!u.permissions.serviceRoles?.includes('manager');
export function domainAccess(u:Session,d:string){return !!serviceDomains[d]&&(u.isAdmin||!!u.permissions.serviceDomains?.includes(d)&&!!u.permissions.serviceRoles?.length);}
export function need(u:Session,d:string,...roles:string[]){if(!domainAccess(u,d)||!roles.some(r=>role(u,r)))fail('مجوز این مرحله خدمات را ندارید.',403);}
export async function visible(u:Session,r:any){if(!r||!domainAccess(u,r.data.domain)||isAgent(u)&&r.data.agentId!==u.permissions.serviceAgentId)fail('پرونده پیدا نشد یا دسترسی ندارید.',404);if(isAgent(u)){const a:any=await storage().prepare("SELECT data FROM flow_entities WHERE id=? AND type='as_agent'").bind(u.permissions.serviceAgentId).first();if(!a||!JSON.parse(a.data).active)fail('نمایندگی غیرفعال است.',403);}return r;}
export async function entity(id:string,type:string){const r:any=await storage().prepare('SELECT * FROM flow_entities WHERE id=? AND type=?').bind(id,type).first();if(!r)fail('رکورد مرتبط پیدا نشد.',404);return decode(r);}
export async function caseAccess(id:string,u:Session){return visible(u,await entity(id,'as_case'));}
export async function list(type:string){return (await storage().prepare('SELECT * FROM flow_entities WHERE type=? ORDER BY created DESC,id').bind(type).all()).results.map(decode);}
export function date(v:unknown){const d=parseCalendarDay(req(v,40));if(!validDay(d)||d<'1900-01-01'||d>'2200-01-01')fail('تاریخ معتبر لازم است.');return d;}
export function past(v:unknown){const d=date(v);if(d>dayAt())fail('تاریخ انجام کار در آینده نباشد.');return d;}
export function monthsAfter(d:string,n:number){const p=solarParts(d),index=p.year*12+p.month-1+n,y=Math.floor(index/12),m=index%12+1;return solarToIso(y,m,Math.min(p.day,solarMonthDays(y,m)));}
export function amount(v:unknown){const s=txt(v,18);if(!/^\d{1,18}$/.test(s))fail('مبلغ ریال باید عدد صحیح نامنفی باشد.');return BigInt(s).toString();}
export function qty(v:unknown):number{try{return scaled(v)}catch(e){return fail((e as Error).message)}}
export const total=(price:string,q:number)=>((BigInt(price)*BigInt(q)+BigInt(999))/BigInt(1000)).toString();
export function array(v:any,max=40):any[]{if(!Array.isArray(v)||v.length>max)fail('تعداد ردیف‌ها معتبر نیست.');return v;}
export const unique=(v:string[])=>new Set(v).size===v.length;
export const warehouse=(owner:string,domain:string)=>'service:'+domain+':'+owner;
export async function warranty(serial:string,at:string){const db=storage(),s=normalizeSerial(serial),a:any=await db.prepare('SELECT * FROM service_activations WHERE serial=?').bind(s).first();const row:any=await db.prepare("SELECT * FROM records WHERE kind='device' AND json_extract(payload,'$.code')=?").bind(s).first();const device=row?{...row,data:JSON.parse(row.payload)}:null;const activation=a?.day||(device?localDay(await firstWarrantyCodeIssuedAt(device.id)||''):'');const months=a?.months||Number(device?.data.warrantyMonths||0);const end=activation&&months?monthsAfter(activation,months):'';return {serial:s,deviceId:device?.id||'',model:device?.data.model||'',productId:device?.data.product||'',activatedAt:activation,months,endsAt:end,state:end?(at>=activation&&at<end?'active':'expired'):'unknown',checkedAt:at,source:a?.source||'activation-history'};}
export async function lineage(serial:string){
 const cases=(await list('as_case')).filter(c=>c.data.serial===serial),d:any=await storage().prepare("SELECT id FROM records WHERE kind='device' AND json_extract(payload,'$.code')=?").bind(serial).first(),events:any[]=[],installed:any[]=[];
 if(d){const rows=(await storage().prepare("SELECT * FROM records WHERE json_extract(payload,'$.device')=? AND kind IN ('event','service') ORDER BY created,id").bind(d.id).all()).results as any[];for(const r of rows){const p=JSON.parse(r.payload);if(p.serviceCase)continue;if(p.stage==='مصرف قطعه'&&p.batch)events.push({at:r.created,batchId:p.batch,quantity:Number(p.quantity)*1000,source:r.id});if(p.replacement)events.push({at:r.created,batchId:p.replacement,oldBatchId:p.batch,quantity:Number(p.quantity||1)*1000,source:r.id});}}
 for(const c of cases)for(const a of c.data.repairs||[])events.push({...a,at:c.data.repairedAt,source:c.id,warrantyStart:c.data.deliveredDay||'',warrantyEnd:c.data.deliveredDay?monthsAfter(c.data.deliveredDay,6):''});
 for(const e of events.sort((a,b)=>a.at.localeCompare(b.at))){let left=e.quantity;if(e.oldBatchId)for(const p of installed.filter(p=>p.batchId===e.oldBatchId&&p.quantity>0)){const n=Math.min(p.quantity,left);p.quantity-=n;left-=n;if(!left)break;}installed.push({...e});}
 return installed.filter(p=>p.quantity>0);
}
export async function ledger(agent:string){const db=storage(),rows=(await db.prepare('SELECT * FROM service_ledger WHERE agent_id=? ORDER BY created,id').bind(agent).all()).results as any[],offsets=(await db.prepare('SELECT x.* FROM service_offsets x JOIN service_ledger l ON l.id=x.debit_id WHERE l.agent_id=?').bind(agent).all()).results as any[];return rows.map(r=>({...r,data:JSON.parse(r.data),remaining:(BigInt(r.debit||0)+BigInt(r.credit||0)-offsets.filter(x=>x.debit_id===r.id||x.credit_id===r.id).reduce((n,x)=>n+BigInt(x.amount),BigInt(0))).toString()}));}
export async function serviceSteps(c:any){const d=c.data,steps:any[]=[],stageDay=(d.stageSince||c.created).slice(0,10);const add=(key:string,r:string,title:string,due=addDay(dayAt(),1))=>steps.push({key,role:r,title,due});const domain=d.domain;
 if(['contact','followup','referred'].includes(d.state))add('contact','support','پیگیری راهنمایی یا مراجعه',d.nextDue||addDay(c.created.slice(0,10),1));
 if(d.state==='declined')add('return',d.agentId?'agent':'intake','تحویل بدون تعمیر به مشتری',addDay(stageDay,1));
 if(d.state==='received')add('diagnose',d.agentId?'agent':'technician','عیب‌یابی دستگاه',d.nextDue||addDay(stageDay,1));
 if(d.state==='diagnosed'){if(!d.authorization)add('authorize','coordinator','بررسی مستندات و پوشش گارانتی',d.nextDue||addDay(stageDay,1));if(d.customerTotal!=='0'&&d.consent?.approved!==true)add('consent',d.agentId?'agent':'support','دریافت پاسخ مشتری به هزینه',d.nextDue||addDay(stageDay,1));}
 if(d.state==='approved')add('repair',d.agentId?'agent':'technician','تأمین قطعه و انجام تعمیر',d.nextDue||addDay(stageDay,2));
 if(d.state==='repaired')add('test',d.agentId?'agent':'technician','ثبت آزمون پس از تعمیر',addDay(stageDay,1));
 if(d.state==='tested')add('deliver',d.agentId?'agent':'intake','تحویل دستگاه',addDay(stageDay,1));
 if(d.state==='delivered'&&d.confirmation?.result!=='confirmed')add('confirm','support','تماس تأیید مشتری',addDay(d.deliveredDay,1));
 if(d.agentId&&d.confirmation?.result==='confirmed'&&!d.laborApproved)add('labor','coordinator','تأیید اجرت نماینده',addDay(stageDay,1));
 return steps.map(s=>({...s,key:s.key+':v'+(d.estimateVersion||0),domain,agentId:d.agentId||'',ownerId:d.ownerId||''}));}
export async function syncServiceTasks(){const db=storage(),members=(await db.prepare("SELECT id,permissions FROM app_members WHERE status='active'").all()).results as any[],cases=await list('as_case'),orders=await list('as_order'),claims=await list('as_claim'),shipments=await list('as_shipment');const work:any[]=[];
 for(const c of cases)work.push({entity:c,steps:await serviceSteps(c)});
 for(const o of orders){const d=o.data,s:any[]=[];if(d.state==='requested')s.push({key:'approve',role:'coordinator',title:'بررسی درخواست قطعه',due:addDay(o.created.slice(0,10),1)});if(d.state==='approved'&&d.lines.some((l:any)=>l.prepared<l.quantity))s.push({key:'prepare',role:'inventory',title:'جمع‌آوری کسری قطعات',due:addDay(o.created.slice(0,10),2)});const led=await ledger(d.agentId),invoice=led.find(l=>l.source_id===o.id&&l.kind==='invoice');if(invoice&&BigInt(invoice.remaining)>BigInt(0))s.push({key:'invoice',role:'finance',title:'پیگیری سررسید فاکتور نماینده',due:invoice.due});work.push({entity:o,steps:s.map(x=>({...x,domain:d.domain,agentId:d.agentId}))});}
 for(const s of shipments){const d=s.data;work.push({entity:s,steps:!d.transportId&&['prepared','shipped'].includes(d.state)?[{key:d.state,role:d.state==='prepared'?'coordinator':'agent',title:d.state==='prepared'?'درخواست حمل بسته از تدارکات مشترک':'تأیید دریافت بسته قطعات',due:d.eta||addDay(s.created.slice(0,10),2),domain:d.domain,agentId:d.agentId}]:[]});}
 for(const c of claims){const d=c.data,r=d.state==='awaiting_return'||d.state==='sent'?'agent':d.state==='received'?'coordinator':d.state==='approved'?'finance':'';work.push({entity:c,steps:r?[{key:d.state,role:r,title:d.state==='approved'?'تعدیل مالی داغی تأییدشده':'پیگیری داغی قطعه',due:d.due||addDay(c.created.slice(0,10),7),domain:d.domain,agentId:d.agentId}]:[]});}
 for(const w of work){const prefix='after-sales:'+w.entity.id+':',previous=(await db.prepare('SELECT * FROM duty_runs WHERE template_id LIKE ?').bind(prefix+'%').all()).results as any[],stmts:D1PreparedStatement[]=[],wanted=new Set<string>(),now=new Date().toISOString();
 for(const s of w.steps)for(const m of members){const p=JSON.parse(m.permissions);if(!p.serviceDomains?.includes(s.domain)||!p.serviceRoles?.includes(s.role)||s.role==='agent'&&p.serviceAgentId!==s.agentId||s.role!=='agent'&&p.serviceAgentId||s.ownerId&&['support','intake','technician'].includes(s.role)&&m.id!==s.ownerId)continue;const key=prefix+s.key,tid=key+':'+m.id;wanted.add(tid);const data={title:s.title,instructions:'از بخش خدمات پس از فروش، پرونده '+w.entity.id+' را باز کنید. اقدام، مدرک و مانع را ثبت کنید. پاسخ متنی جای عملیات تأیید یا انبار را نمی‌گیرد.',evidence:'text',positionName:serviceRoles[s.role],sourceSection:'after-sales',serviceWorkflow:true,serviceDomain:s.domain,serviceAgentId:s.agentId||'',serviceRole:s.role,remindHours:24,escalateHours:24,history:[],answer:'',extensionRequested:''};
 const old=previous.find(t=>t.id===tid);if(old){if(['completed','cancelled'].includes(old.state))stmts.push(db.prepare("UPDATE duty_runs SET state='open',due=?,revision=revision+1,updated=? WHERE id=? AND revision=?").bind(s.due+'T12:30:00Z',now,tid,old.revision));else if(old.due!==s.due+'T12:30:00Z')stmts.push(db.prepare('UPDATE duty_runs SET due=?,revision=revision+1,updated=? WHERE id=? AND revision=?').bind(s.due+'T12:30:00Z',now,tid,old.revision));}
 else stmts.push(db.prepare("INSERT INTO duty_runs(id,template_id,period,assignee,supervisor,due,state,data,revision,created,updated) VALUES(?,?,?,?,NULL,?,'open',?,1,?,?)").bind(tid,key,'workflow',m.id,s.due+'T12:30:00Z',JSON.stringify(data),now,now));}
 for(const t of previous)if(!wanted.has(t.id)&&!['completed','cancelled'].includes(t.state)){const d=JSON.parse(t.data);d.history=[...(d.history||[]),{mode:'workflow',note:'مرحله یا مسئول مجاز خدمات تغییر کرد.',at:now,actor:'workflow'}];stmts.push(db.prepare("UPDATE duty_runs SET state='completed',data=?,revision=revision+1,updated=? WHERE id=? AND revision=?").bind(JSON.stringify(d),now,t.id,t.revision));}
 if(stmts.length){const op=crypto.randomUUID();try{await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'service_tasks','{}','scheduler',?,CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN 1 ELSE 0 END)").bind(op,new Date().toISOString(),w.entity.id,w.entity.revision),...stmts]);}catch(e){if(!/constraint|guard/i.test(String(e)))throw e;}}
}
}
export async function installServicePositions(u:Session){if(!u.isAdmin)return;const db=storage(),now=new Date().toISOString();const duties:Record<string,string>={manager:'کنترل پرونده‌های معطل، پوشش فنی، کیفیت تعمیر، شکایات و عملکرد نمایندگان.',support:'ثبت شرح تماس؛ راهنمایی؛ تعیین نتیجه؛ تماس مستقل پس از تحویل و ثبت پاسخ و رضایت مشتری.',intake:'ثبت سریال، کارکرد، لوازم و ظاهر؛ تحویل رسید دو نسخه؛ ثبت تحویل واقعی و هویت تحویل‌گیرنده.',technician:'عیب‌یابی مستند؛ تعیین قطعات و بچ واقعی؛ رزرو و مصرف؛ ثبت اندازه‌گیری و آزمون نهایی.',coordinator:'بررسی مدارک سریال و عیب قبل از تعمیر؛ تأیید پوشش و سفارش؛ بررسی داغی؛ تأیید اجرت پس از پاسخ مشتری.',inventory:'برداشت بچ تأییدشده و ثبت محل؛ آماده‌سازی بسته؛ تحویل به تدارکات؛ دریافت و محل نگهداری داغی.',logistics:'ثبت حامل، رهگیری و موعد بسته؛ پیگیری رسیدن به نماینده.',finance:'کنترل فاکتور و سررسید؛ ثبت بستانکاری داغی تأییدشده؛ دریافت، پرداخت و تهاتر مستند.',agent:'ثبت پرونده فقط برای نمایندگی خود؛ ارسال مدارک قبل از تعمیر؛ درخواست و دریافت قطعه؛ ثبت مصرف، تحویل و داغی.'};
 for(const domain of Object.keys(serviceDomains))for(const r of Object.keys(serviceRoles).filter(r=>r!=='logistics')){const id='service-position:'+domain+':'+r,name=serviceRoles[r]+' — '+serviceDomains[domain],data={name,unit:'خدمات پس از فروش — '+serviceDomains[domain],mission:'انجام مرحله تخصصی خدمات و حفظ رهگیری سریال و قطعه.',responsibilities:duties[r],authorityBoundaries:'ثبت فقط در حدود مجوز مستقل حساب؛ گفتار مشتری یا متن وظیفه جای تأیید واقعی و مدرک نیست.',reportingTo:'مدیر خدمات پس از فروش',handoffs:'پذیرش، تعمیر، نمایندگان، انبار، تدارکات و مالی',metrics:'زمان پاسخ با تفکیک انتظار؛ پرونده کامل؛ آزمون مجدد؛ رضایت با تعداد پاسخ؛ تأخیر قطعه و تسویه',members:[],supervisor:'',active:true};await db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) SELECT ?,'position',?,1,?,? WHERE NOT EXISTS(SELECT 1 FROM flow_entities WHERE type='position' AND (id=? OR json_extract(data,'$.name')=?))").bind(id,JSON.stringify(data),now,now,id,name).run();}
}
