import {storage} from './storage';
import {AccessError} from './authorization';
import {trainingContext} from './training-context';
import {dayAt,taskRequired,taskText,validDay} from './duties';
import {solarParts,solarToIso,solarMonthDays} from './persian-date';
import {assetModes,assetConditions,assetHolderKinds} from './assets-contract';
import type {Session} from './permissions';
export const assetFail=(m:string,s=400):never=>{throw new AccessError(m,s)};
export const assetInternal=(m:any)=>m?.status==='active'&&(()=>{const p=JSON.parse(m.permissions);return !p.salesAgentId&&!p.serviceAgentId&&!p.hospitalCenterId&&!p.salesRoles?.includes('agent')&&!p.serviceRoles?.includes('agent')})();
export async function assetMembers(){return (await storage().prepare('SELECT id,name,status,subject,permissions FROM app_members ORDER BY id').all()).results as any[]}
export async function assetActor(u:Session,members?:any[]){const ms=members||await assetMembers(),m=ms.find(m=>m.subject===u.userId||m.id===(u.userId.startsWith('local:')?u.userId.slice(6):u.userId));if(trainingContext.getStore()||u.permissions.salesAgentId||u.permissions.serviceAgentId||u.permissions.hospitalCenterId||!u.isAdmin&&!assetInternal(m))assetFail('اموال فقط برای کارکنان شرکت است.',403);const p=m?JSON.parse(m.permissions):{};return {id:m?.id||'',admin:u.isAdmin,custodian:u.isAdmin||p.assetRoles?.includes('custodian')===true,hr:u.isAdmin||p.personnelRoles?.includes('hr')===true}}
export async function assetRows(){return (await storage().prepare("SELECT * FROM flow_entities WHERE type GLOB 'asset_*' ORDER BY created,id").all()).results.map((r:any)=>({...r,data:JSON.parse(r.data)}))}
export function assetVisible(r:any,a:Awaited<ReturnType<typeof assetActor>>,rows:any[]):boolean{if(a.custodian)return true;if(r.type==='asset_item')return r.data.holderKind==='employee'&&(r.data.holderId===a.id||a.hr);if(r.type==='asset_clearance')return r.data.memberId===a.id||a.hr;if(r.type==='asset_file'){const parent=rows.find(x=>x.id===r.data.assetId);return !!parent&&assetVisible(parent,a,rows)&&parent.data.custodyId===r.data.custodyId}return false}
export function presentAsset(r:any,a:Awaited<ReturnType<typeof assetActor>>){if(r.type==='asset_file'){const {objectKey,actor,...data}=r.data;return {...r,data}}if(r.type==='asset_item'&&!a.custodian){const {history,...data}=r.data;return {...r,data:{...data,history:(history||[]).filter((h:any)=>a.hr||h.holderKind==='employee'&&h.holderId===a.id).map((h:any)=>({...h,actor:undefined}))}}}return r}
export async function assetAccess(u:Session,id:string,members?:any[]){const rows=await assetRows(),a=await assetActor(u,members),r=rows.find(r=>r.id===id);if(!r||!assetVisible(r,a,rows))assetFail('پرونده اموال در دسترس نیست.',404);return {r,a,rows}}
export function nextAssetYear(day:string){const p=solarParts(day),next=solarToIso(p.year+1,p.month,Math.min(p.day,solarMonthDays(p.year+1,p.month)));if(!next)assetFail('تاریخ تأیید معتبر نیست.');return next}
export function heldAssets(rows:any[],mid:string){return rows.filter(r=>r.type==='asset_item'&&r.data.holderKind==='employee'&&r.data.holderId===mid)}
export function assetMemberGuard(db:D1Database,op:string,members:any[]){return db.prepare("UPDATE inventory_operations SET guard=CASE WHEN (SELECT json_group_array(json_object('id',id,'name',name,'status',status,'subject',subject,'permissions',permissions)) FROM (SELECT * FROM app_members ORDER BY id))=? THEN guard ELSE 0 END WHERE id=?").bind(JSON.stringify(members),op)}
export function assetSnapshotGuard(db:D1Database,op:string,rows:any[]){return db.prepare("UPDATE inventory_operations SET guard=CASE WHEN (SELECT COUNT(*) FROM flow_entities WHERE type GLOB 'asset_*')=? AND (SELECT COALESCE(SUM(revision),0) FROM flow_entities WHERE type GLOB 'asset_*')=? THEN guard ELSE 0 END WHERE id=?").bind(rows.length,rows.reduce((n,r)=>n+r.revision,0),op)}
export async function commitAssets(u:Session,op:string,signature:string,rows:any[],members:any[],changes:any[],mode:string,extra:D1PreparedStatement[]=[]){const db=storage(),now=new Date().toISOString();await db.batch([db.prepare('INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,?,?,?,?,1)').bind(op,'asset_'+mode,signature,u.userId,now),assetMemberGuard(db,op,members),assetSnapshotGuard(db,op,rows),...extra,...changes.map(r=>r.revision?db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=? AND type=? AND revision=?').bind(JSON.stringify(r.data),now,r.id,r.type,r.revision):db.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').bind(r.id,r.type,JSON.stringify(r.data),now,now)),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(op,u.userId,changes.at(-1)?.id||op,'asset_'+mode,JSON.stringify(changes.map(r=>({id:r.id,type:r.type,revision:r.revision+1,holderKind:r.data.holderKind,holderId:r.data.holderId,state:r.data.state}))),now)])}
const req=(v:unknown,max=200)=>taskRequired(v,max),txt=(v:unknown,max=4000)=>taskText(v??'',max);
function date(v:unknown){const s=req(v,10);if(!validDay(s)||s>dayAt())assetFail('تاریخ واقعی معتبر و حداکثر امروز لازم است.');return s}
export async function applyAssets(u:Session,b:any){const members=await assetMembers(),a=await assetActor(u,members),rows=await assetRows(),db=storage(),now=new Date().toISOString();if(!b||b.confirmed!==true||!assetModes.includes(b.mode)||! /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(b.id))assetFail('تأیید و شناسه عملیات معتبر لازم است.');const signature=JSON.stringify(b),prior:any=await db.prepare('SELECT actor,payload FROM inventory_operations WHERE id=?').bind(b.id).first();if(prior){if(prior.actor!==u.userId||prior.payload!==signature)assetFail('شناسه عملیات با محتوای دیگری استفاده شده است.',409);return {saved:true,id:b.recordId||b.id,repeated:true}}
const mode=b.mode,note=req(b.notes,4000),changes:any[]=[],checks:D1PreparedStatement[]=[];let id=b.recordId||b.id,old=rows.find(r=>r.id===id),d:any=old?structuredClone(old.data):{},type=old?.type||'';
if(b.recordId&&!old)assetFail('پرونده یافت نشد.',404);if(old&&!assetVisible(old,a,rows))assetFail('پرونده در دسترس نیست.',404);if(!Number.isInteger(b.revision)||b.revision!==(old?.revision||0))assetFail('نسخه پرونده تغییر کرده؛ تازه‌سازی کنید.',409);
const custodian=()=>{if(!a.custodian)assetFail('دسترسی اموال‌دار لازم است.',403)},member=(mid:string)=>{const m=members.find(m=>m.id===mid&&assetInternal(m));if(!m)assetFail('کارمند فعال شرکت انتخاب کنید.');return m},item=()=>{if(type!=='asset_item')assetFail('پرونده مال لازم است.')},history=(data:any)=>{if((d.history||[]).length>=500)assetFail('ظرفیت سابقه تکمیل شده است.');return {...data,history:[...(d.history||[]),{at:now,mode,notes:note,name:u.name,actor:u.userId,holderKind:data.holderKind,holderId:data.holderId,holderName:data.holderName,location:data.location,condition:data.condition,reference:data.reference,custodyId:data.custodyId}]}};
if(mode==='register'||mode==='edit'){custodian();if(mode==='register'&&old||mode==='edit'&&!old)assetFail('نوع ثبت معتبر نیست.');if(old)item();type='asset_item';const code=req(b.code,80).toUpperCase();if(rows.some(r=>r.type===type&&r.id!==id&&r.data.code===code))assetFail('کد اموال تکراری است.',409);if(!Object.hasOwn(assetConditions,b.condition))assetFail('وضعیت سلامت انتخاب کنید.');d=history({...d,code,name:req(b.name),category:req(b.category,100),brand:txt(b.brand,100),model:txt(b.model,100),serial:txt(b.serial,200),specifications:txt(b.specifications,6000),condition:b.condition,...(!old?{holderKind:'stock',holderId:'',holderName:'شرکت',location:req(b.location,300),custodyId:b.id,handedDay:date(b.day),reference:req(b.reference),annualDue:'',lastConfirmedDay:''}:{})});
}else if(mode==='transfer'){custodian();item();if(!Object.hasOwn(assetHolderKinds,b.holderKind)||!Object.hasOwn(assetConditions,b.condition))assetFail('تحویل‌گیرنده و وضعیت سلامت معتبر لازم است.');const day=date(b.day);if(day<d.handedDay)assetFail('تاریخ تحویل قبل از تحویل قبلی است.');let holderId='',holderName='شرکت';if(b.holderKind==='employee'){holderId=req(b.holderId);holderName=member(holderId).name;if(rows.some(r=>r.type==='asset_clearance'&&r.data.memberId===holderId&&r.data.state!=='cancelled'))assetFail('این فرد در فرایند ترک کار است؛ تحویل جدید مجاز نیست.',409);const hr:any=await db.prepare("SELECT data FROM flow_entities WHERE type='hr_employee' AND json_extract(data,'$.memberId')=?").bind(holderId).first();if(hr&&JSON.parse(hr.data).state!=='active')assetFail('پرونده پرسنلی فرد غیرفعال است.');checks.push(db.prepare("UPDATE inventory_operations SET guard=CASE WHEN NOT EXISTS(SELECT 1 FROM flow_entities WHERE type='hr_employee' AND json_extract(data,'$.memberId')=? AND json_extract(data,'$.state')<>'active') THEN guard ELSE 0 END WHERE id=?").bind(holderId,b.id));}else if(b.holderKind==='contractor'){holderName=req(b.holderName);holderId=req(b.contractorCode,100)}
d=history({...d,holderKind:b.holderKind,holderId,holderName,location:req(b.location,300),condition:b.condition,custodyId:b.id,handedDay:day,reference:req(b.reference),annualDue:b.holderKind==='contractor'?nextAssetYear(day):'',lastConfirmedDay:'',lastConfirmationId:'',lastLetterId:'',lastSigner:'',lastConfirmationReference:'',contractorContact:b.holderKind==='contractor'?txt(b.contractorContact,300):'',purpose:txt(b.purpose,2000)});
}else if(mode==='confirm_annual'){custodian();item();if(d.holderKind!=='contractor')assetFail('تأیید سالانه برای اموال نزد پیمانکار است.');const day=date(b.day);if(day<d.handedDay||d.lastConfirmedDay&&day<=d.lastConfirmedDay)assetFail('تاریخ تأیید باید بعد از تأیید قبلی و از تاریخ تحویل باشد.');const file=rows.find(r=>r.id===b.fileId&&r.type==='asset_file'&&r.data.assetId===id&&r.data.custodyId===d.custodyId);if(!file)assetFail('نامه کتبی همین تحویل را ابتدا پیوست کنید.');if(rows.some(r=>r.type==='asset_confirmation'&&r.data.fileId===file.id))assetFail('برای تأیید جدید، نامه کتبی جدید پیوست کنید.');if(b.actualConfirmation!==true)assetFail('دریافت تأیید واقعی پیمانکار را تأیید کنید.');if(!Object.hasOwn(assetConditions,b.condition))assetFail('وضعیت سلامت معتبر لازم است.');changes.push({id:b.id,type:'asset_confirmation',revision:0,data:{assetId:id,custodyId:d.custodyId,holderId:d.holderId,holderName:d.holderName,day,signer:req(b.signer),reference:req(b.reference),fileId:file.id,condition:b.condition,location:req(b.location,300),notes:note,actor:u.userId}});d=history({...d,lastConfirmedDay:day,annualDue:nextAssetYear(day),condition:b.condition,location:req(b.location,300),lastConfirmationId:b.id,lastLetterId:file.id,lastSigner:req(b.signer),lastConfirmationReference:req(b.reference)});
}else if(mode==='request_clearance'){const mid=b.memberId?req(b.memberId):a.id;if(!a.custodian&&!a.hr&&mid!==a.id)assetFail('فقط تسویه اموال خودتان را درخواست کنید.',403);member(mid);if(old||rows.some(r=>r.type==='asset_clearance'&&r.data.memberId===mid&&r.data.state!=='cancelled'))assetFail('پرونده تسویه فعال این فرد موجود است.',409);type='asset_clearance';d={memberId:mid,memberName:member(mid).name,state:'open',requestedDay:dayAt(),notes:note,history:[{at:now,name:u.name,mode,notes:note}]};
}else if(mode==='approve_clearance'||mode==='cancel_clearance'){if(type!=='asset_clearance')assetFail('پرونده تسویه لازم است.');if(mode==='approve_clearance'){custodian();if(d.state!=='open')assetFail('پرونده تسویه باز نیست.');if(heldAssets(rows,d.memberId).length)assetFail('تا برگشت همه اموال امانی، تسویه اموال ممکن نیست.',409);d={...d,state:'cleared',approvedBy:u.userId,approvedName:u.name,approvedAt:now,reference:req(b.reference)}}else{if(!a.hr&&!a.admin)assetFail('لغو ترک کار فقط توسط اداری مجاز است.',403);if(d.state==='cancelled')assetFail('پرونده قبلاً لغو شده است.');d={...d,state:'cancelled'}}d.history=[...(d.history||[]),{at:now,name:u.name,mode,notes:note}];
}else if(mode==='install_position'){if(!a.admin)assetFail('تعریف سمت فقط توسط مدیر مجاز است.',403);const position:any=await db.prepare("SELECT id FROM flow_entities WHERE id='asset-custodian-position'").first();if(position)return {saved:true,id:position.id,repeated:true};changes.push({id:'asset-custodian-position',type:'position',revision:0,data:{name:'اموال‌دار',unit:'اداری و اموال',members:[],supervisor:'',active:true,mission:'ثبت و نگهداری مشخصات اموال، سوابق تحویل و برگشت، تسویه اموال ترک کار و اخذ تأیید کتبی سالانه اموال نزد پیمانکار',instructions:'نقش اموال‌دار را در دسترسی‌های کاربر نیز فعال کنید. تأیید پیمانکار همراه با نامه واقعی در پرونده اموال ثبت می‌شود.'}});id='asset-custodian-position';
}
if(mode!=='install_position')changes.push({id,type,revision:old?.revision||0,data:d});await commitAssets(u,b.id,signature,rows,members,changes,mode,checks);return {saved:true,id};}
