// Presentation only: keep original tool arguments and validation intact.
export const leadFieldTitles:Record<string,string>={title:'نام سرنخ فروش',contactName:'نام فرد رابط',company:'نام شرکت / بیمارستان / مرکز',phone:'شماره تماس',email:'ایمیل',city:'شهر',source:'نحوه آشنایی مشتری',sourceDetail:'توضیح نحوه آشنایی',segment:'حوزه فروش',ownerId:'مسئول پیگیری',agentId:'نماینده یا عامل مرتبط',items:'محصولات موردنیاز',productId:'محصول',quantity:'تعداد موردنیاز',interest:'نیاز مشتری',estimatedAmount:'مبلغ برآوردی (ریال)',expectedDay:'تاریخ احتمالی خرید',competitor:'رقیب یا پیشنهاد جایگزین',decisionMaker:'تصمیم‌گیرنده خرید',tenderDeadline:'مهلت مناقصه',nextAction:'اقدام بعدی پیگیری',nextDue:'موعد پیگیری بعدی',stage:'مرحله فروش',activityType:'نوع ارتباط',day:'تاریخ ارتباط',lossReason:'علت ازدست‌رفتن سرنخ',orderId:'سفارش مرتبط',notes:'توضیحات ثبت / نتیجه پیگیری',leadId:'سرنخ انتخاب‌شده'};
const options:Record<string,Record<string,string>>={source:{phone:'تماس تلفنی',website:'وب‌سایت',exhibition:'نمایشگاه',referral:'معرفی',social:'شبکه اجتماعی',visit:'مراجعه حضوری',other:'سایر'},segment:{home:'خانگی',hospital:'بیمارستانی'},stage:{new:'جدید',contacted:'تماس اولیه',qualified:'نیازسنجی',proposal:'ارائه پیشنهاد',negotiation:'مذاکره',nurture:'فعلاً آماده خرید نیست'},activityType:{call:'تماس تلفنی',meeting:'جلسه',email:'ایمیل',message:'پیام',visit:'مراجعه حضوری'},lossReason:{price:'قیمت',timing:'زمان خرید',competitor:'رقیب',product:'تناسب محصول',no_response:'عدم پاسخ',other:'سایر'}};
const follow=['nextAction','nextDue','notes'];
const modeFields:Record<string,string[]>={save:['title','contactName','company','phone','email','city','source','sourceDetail','segment','ownerId','agentId','items','interest','estimatedAmount','expectedDay','competitor','decisionMaker','tenderDeadline',...follow],stage:['stage',...follow],activity:['activityType','day',...follow],assign:['ownerId',...follow],lose:['lossReason','notes'],reopen:['ownerId',...follow],link_order:['orderId','notes']};
const titles:Record<string,string>={stage:'تغییر مرحله سرنخ فروش',activity:'ثبت تماس و پیگیری سرنخ',assign:'تعیین مسئول پیگیری سرنخ',lose:'ثبت علت ازدست‌رفتن سرنخ',reopen:'بازگشایی سرنخ فروش',link_order:'اتصال سرنخ به سفارش فروش'};
export function formPresentation(tool:string,args:any,input:any,title:string){
 const schema=JSON.parse(JSON.stringify(input));
 for(const key of ['id','requestId','confirmed','revision','previousVersion','quoteHash','previous'])if(schema.properties?.[key])schema.properties[key].uiHidden=true;
 if(tool!=='sales_lead_apply')return {schema,title};
 const mode=args.mode||'save',visible=modeFields[mode]||modeFields.save,required=mode==='save'?['title','contactName','phone','city','source','segment','ownerId','interest',...follow]:mode==='reopen'?follow:visible;
 const decorate=(s:any)=>{for(const [key,field] of Object.entries(s.properties||{}) as [string,any][]){if(leadFieldTitles[key])field.title=leadFieldTitles[key];if(options[key])field.enumLabels=options[key];if(['expectedDay','tenderDeadline','nextDue','day'].includes(key))field.format='date';if(['interest','nextAction','notes','sourceDetail'].includes(key))field.multiline=true;if(field.items)decorate(field.items);if(field.properties)decorate(field);}};
 decorate(schema);
 schema.properties=Object.fromEntries([...visible,...Object.keys(schema.properties||{}).filter(k=>!visible.includes(k))].filter(k=>schema.properties?.[k]).map(k=>[k,{...schema.properties[k],uiHidden:!visible.includes(k)}]));
 schema.required=[...new Set([...(schema.required||[]),...required])];
 return {schema,title:mode==='save'?(args.leadId?'ویرایش سرنخ فروش':'ایجاد سرنخ فروش'):titles[mode]||'پیگیری سرنخ فروش'};
}
