import {can} from '@/lib/authorization';
import type {Session} from '@/lib/permissions';
export const assistantReadNames=new Set(['get_session','get_record_schema','list_records','get_device_passport','list_serial_runs','suggest_batch_number','device_analytics','distribution_history','list_firmware','list_quality_templates','list_quality_reports','finance_report_catalog','get_finance_period','get_production_inventory','get_material_flow']);
// Credentials, permissions, provider settings and file bytes stay in their dedicated forms.
export const assistantWriteNames=new Set(['create_record','update_record','delete_record','generate_serials','save_distribution','create_firmware','create_quality_template','record_quality_report','add_finance_note','save_product_bom','initialize_batch_stock','move_batch_stock','create_production_sheet','transfer_finished_device','save_material_master','receive_material_batch','inspect_incoming_batch','shelve_approved_batch','request_production_material','issue_production_material','request_replenishment','close_replenishment','set_daily_capacity','create_daily_production_plan','assign_serial_assembler','finalize_material_consumption','reject_line_material','replace_installed_component','record_serial_print']);
export const sectionTitles:Record<string,string>={overview:'نمای کلی',flow:'گردش مواد و تولید',product:'تعریف محصولات',batch:'قطعات و بچ‌ها',device:'شناسنامه دستگاه‌ها',event:'ثبت تولید',inventory:'انبارها و موجودی',serials:'تولید و چاپ سریال',analytics:'گزارش تولید و فعال‌سازی',service:'خدمات پس از فروش',action:'اقدامات اصلاحی',distribution:'نماینده و مشتری',firmware:'نسخه‌های نرم‌افزار','finance-control':'کنترل مالی',finance:'اتصال حسابداری',users:'کاربران و دسترسی‌ها',llm:'تنظیمات LLM و MCP'};
export function canOpenSection(u:Session,s:string){if(!sectionTitles[s])return false;if(u.isAdmin||s==='overview')return true;if(['users','llm','finance'].includes(s))return false;if(s==='flow')return !!u.permissions.flowRoles?.length;if(s==='finance-control')return ['read','write'].includes(u.permissions.finance||'');return can(u,(s==='inventory'?'batch':['serials','analytics'].includes(s)?'device':s) as any,'read');}
export function actionSection(tool:string,args:any){if(tool.includes('record')&&args.kind)return args.kind;if(tool.includes('finance'))return 'finance-control';if(tool.includes('firmware'))return 'firmware';if(tool.includes('distribution'))return 'distribution';if(tool.includes('quality'))return 'device';if(tool.includes('bom'))return 'product';return 'flow';}
export const actionTitles:Record<string,string>={create_record:'ثبت رکورد',update_record:'ویرایش رکورد',delete_record:'حذف رکورد',generate_serials:'تولید سریال',save_distribution:'ثبت نماینده و مشتری',create_firmware:'ثبت نسخه نرم‌افزار',create_quality_template:'تعریف فرم کنترل کیفیت',record_quality_report:'ثبت نتیجه کنترل کیفیت',add_finance_note:'ثبت بررسی مالی',save_product_bom:'ثبت BOM محصول',initialize_batch_stock:'ثبت موجودی اولیه',move_batch_stock:'انتقال مواد',create_production_sheet:'ثبت برگ تولید',transfer_finished_device:'انتقال محصول نهایی',save_material_master:'تعریف یا ویرایش کالا',receive_material_batch:'ورود بچ به قرنطینه',inspect_incoming_batch:'کنترل کیفیت ورودی',shelve_approved_batch:'انتقال به انبار مواد اولیه',request_production_material:'درخواست مواد خط تولید',issue_production_material:'تحویل مواد به خط تولید',request_replenishment:'درخواست تأمین',close_replenishment:'بستن درخواست تأمین',set_daily_capacity:'تنظیم ظرفیت روزانه',create_daily_production_plan:'ایجاد برنامه تولید و سریال',assign_serial_assembler:'تخصیص مونتاژکار',finalize_material_consumption:'ثبت مصرف مواد',reject_line_material:'انتقال به نامنطبق',replace_installed_component:'تعویض قطعه نصب‌شده',record_serial_print:'ثبت درخواست چاپ'};
