import {costRead,costWrite,moneyMicro,moneyText} from './costing';
export function projectRoles(u:any){const p=u.permissions,internal=!p.salesAgentId&&!p.serviceAgentId&&!p.hospitalCenterId;
 const manager=internal&&(u.isAdmin||p.supplyRoles?.includes('ceo')),engineering=internal&&(manager||p.supplyRoles?.includes('engineering')),
 warehouse=internal&&(u.isAdmin||p.flowRoles?.includes('inventory')||p.supplyRoles?.includes('inventory'))&&(u.isAdmin||!p.warehouses||p.warehouses.includes('raw')),
 production=internal&&(manager||p.flowRoles?.includes('production')||p.serviceRoles?.includes('technician')&&p.serviceDomains?.includes('hospital')),
 quality=internal&&(u.isAdmin||p.flowRoles?.includes('qc')),finance=internal&&costWrite(u),financial=internal&&(costRead(u)||manager);
 return {manager:!!manager,engineering:!!engineering,warehouse:!!warehouse,production:!!production,quality:!!quality,finance:!!finance,financial:!!financial,read:!!(internal&&(manager||engineering||warehouse||production||quality||costRead(u)))};
}
export const projectHelp=[
 'هر پروژه ساخت بیمارستانی یک کد، مشتری، قرارداد، مسئول و تجهیزات تحویلی دارد. هر تجهیز یک BOM مستقل دارد؛ کپی BOM پایه، نسخه اصلی را تغییر نمی‌دهد. نسخه اولیه و همه اصلاحات حفظ می‌شوند.',
 'مهندسی اقلام را آماده و مدیریت نسخه را تأیید می‌کند. درخواست مواد فقط از BOM تأییدشده است؛ افزایش یا جایگزینی نیازمند نسخه جدید و دلیل است. زیرمجموعه را به صورت کالای کامل یا اجزای آن وارد کنید؛ هر دو هم‌زمان هزینه نشوند.',
 'انبار درخواست را از بچ پذیرفته و غیرمنقضی رزرو و سپس تحویل می‌دهد. تحویل به محل پروژه مصرف نیست. مصرف، برگشت سالم به محل انبار و خرابی هر کدام جدا ثبت می‌شوند. موجودی تحویلی و رزروشده پروژه نباید در پایان بلاتکلیف بماند.',
 'بهای مواد از میانگین متحرک همان گردش موجودی محاسبه می‌شود؛ قیمت ناقص صفر فرض نمی‌شود. انتقال raw به project و برگشت، هزینه مصرف ایجاد نمی‌کند. هزینه زیرمجموعه آماده از ارزش موجودی آن می‌آید.',
 'ساعت واقعی با تاریخ و فرد ثبت می‌شود و مالی نرخ را تأیید می‌کند. هزینه مستقیم به تجهیز و هزینه مشترک با سهم دستی یا ساعت کار تأییدشده تخصیص می‌یابد. سربار نیازمند مبلغ و مبنای مصوب مالی است؛ برآورد با واقعی مخلوط نمی‌شود.',
 'بودجه اولیه، بودجه اصلاح‌شده، هزینه واقعی، سفارش/تعهد باز و برآورد هزینه باقیمانده جدا نمایش داده می‌شوند. تعهدات و برآورد باقی‌مانده دو شاخص‌اند؛ به‌طور پیش‌فرض با هم جمع نمی‌شوند تا خرید آینده دوباره شمرده نشود.',
 'نهایی‌سازی مالی نیازمند تأیید کیفیت تجهیزات، تعیین تکلیف قطعات، زمان و هزینه‌های بررسی‌شده، بسته‌شدن تعهدات و نواقص و ثبت برآورد باقیمانده صفر است. گزارش ثابت ذخیره می‌شود؛ تغییر دیرهنگام قیمت منابع، گزارش را نیازمند بازبینی می‌کند.',
 'این بخش دفتر مدیریتی ساخت و اجرای قرارداد است؛ سند سپیدار، درآمد حسابداری و صورتحساب مشتری خودکار صادر نمی‌شود. سود مدیریتی قرارداد با سود شناسایی‌شده حسابداری یکسان نیست.'
];
const total=(a:any[],key:string)=>a.reduce((n:bigint,x:any)=>n+moneyMicro(x[key]||'0'),BigInt(0));
export function projectReport(p:any,costs:any,sources:any[]=[]){
 const problems:string[]=[],units=p.units.map((u:any)=>{const materials=p.movements.filter((m:any)=>m.unitId===u.id&&['consume','scrap'].includes(m.kind)).map((m:any)=>{const cs=costs.unassigned.filter((c:any)=>c.operationId===m.operationId),complete=cs.length>0&&cs.every((c:any)=>c.cost!==null);return {...m,cost:complete?moneyText(total(cs,'cost')):null};});
 const labor=p.times.filter((t:any)=>t.unitId===u.id&&!t.voided);const laborTotal=labor.reduce((n:bigint,t:any)=>n+(t.approved?moneyMicro(t.rate)*BigInt(t.minutes)/BigInt(60):BigInt(0)),BigInt(0));
 if(materials.some((m:any)=>m.cost===null))problems.push('قیمت مواد ناقص: '+u.title);if(labor.some((t:any)=>!t.approved))problems.push('زمان/نرخ تأییدنشده: '+u.title);if(!labor.length)problems.push('زمان کار ثبت نشده: '+u.title);if(!u.quality)problems.push('تحویل فنی و کیفیت تأیید نشده: '+u.title);
 return {id:u.id,title:u.title,minutes:labor.reduce((n:number,t:any)=>n+t.minutes,0),material:materials.some((m:any)=>m.cost===null)?null:moneyText(total(materials.filter((m:any)=>m.kind==='consume'),'cost')),knownMaterial:moneyText(total(materials.filter((m:any)=>m.cost!==null&&m.kind==='consume'),'cost')),labor:moneyText(laborTotal),manufacturing:BigInt(0),execution:BigInt(0),loss:total(materials.filter((m:any)=>m.cost!==null&&m.kind==='scrap'),'cost'),materials};});
 const expenses=p.expenses.filter((e:any)=>!e.voided);for(const e of expenses){if(e.allocationMethod==='time'&&e.timeBasis!==JSON.stringify(p.times.filter((t:any)=>!t.voided).map((t:any)=>({id:t.id,minutes:t.minutes,unitId:t.unitId}))))problems.push('زمان مبنای هزینه مشترک تغییر کرده؛ تخصیص را بازبینی کنید: '+e.title);if(e.sourceId&&!sources.some((x:any)=>x.id===e.sourceId&&x.type==='expense_register'&&x.revision===e.sourceRevision&&x.data.state==='approved'))problems.push('منبع هزینه تغییر کرده یا دیگر تأییدشده نیست: '+e.title);if(!e.approved){problems.push('هزینه تأییدنشده: '+e.title);continue;}for(const s of e.shares){const u=units.find((u:any)=>u.id===s.unitId);if(u)u[e.bucket as 'manufacturing'|'execution'|'loss']+=moneyMicro(s.amount);}}
 for(const r of p.requests){if(!['issued','cancelled'].includes(r.state))problems.push('درخواست باز / رزرو بلاتکلیف');for(const l of r.lots||[]){const out=p.movements.filter((m:any)=>m.lotId===l.id).reduce((n:number,m:any)=>n+m.quantity,0);if(l.quantity>out)problems.push('قطعه مصرف‌نشده نزد پروژه');}}
 if(p.issues.some((i:any)=>!i.resolved))problems.push('نقص مدرک یا پیگیری باز');if(p.commitments.some((c:any)=>!c.closed))problems.push('تعهد خرید باز');if(p.remaining===null||moneyMicro(p.remaining)>BigInt(0))problems.push('برآورد هزینه باقیمانده تعیین تکلیف نشده');if(!p.units.length)problems.push('تجهیزی تعریف نشده است');if(p.units.some((u:any)=>!u.approved))problems.push('BOM تأییدنشده');
 const result=units.map((u:any)=>{const material=moneyMicro(u.knownMaterial),manufacturing=material+moneyMicro(u.labor)+u.manufacturing,execution=manufacturing+u.execution+u.loss;return {...u,manufacturing:moneyText(manufacturing),execution:moneyText(execution),loss:moneyText(u.loss),complete:u.material!==null};});
 const actual=total(result,'execution'),budget=p.budgets.at(-1)?.amount||null,initial=p.budgets[0]?.amount||null;
 return {units:result,knownActual:moneyText(actual),actual:result.every((u:any)=>u.complete)&&!expenses.some((e:any)=>!e.approved)&&!p.times.some((t:any)=>!t.voided&&!t.approved)?moneyText(actual):null,manufacturing:moneyText(total(result,'manufacturing')),openCommitments:moneyText(total(p.commitments.filter((c:any)=>!c.closed),'amount')),remaining:p.remaining,forecast:p.remaining===null?null:moneyText(actual+moneyMicro(p.remaining)),initialBudget:initial,budget,variance:budget===null?null:moneyText(actual-moneyMicro(budget)),problems:[...new Set(problems)],complete:!problems.length};
}
