export const foreignSelectionStates:Record<string,string>={searching:'انتخاب تأمین‌کننده',awaiting_sample:'انتظار دریافت نمونه',review:'بررسی نمونه در تحقیق‌وتوسعه',approved:'نمونه و تأمین‌کننده تأییدشده',rejected:'نمونه یا تأمین‌کننده ردشده'};
export const foreignPhysicalStates:Record<string,string>={planned:'برنامه خرید',ordered:'سفارش تولید',preparing:'در حال آماده‌سازی',ready:'آمادهٔ حمل',shipping:'در حال حمل',clearing:'در حال ترخیص',cleared:'ترخیص‌شده',received:'تحویل انبار؛ منتظر کنترل کیفیت'};
export const foreignModes=['selection_create','selection_candidate','sample_received','sample_review','selection_reopen','configure','fx_queue','fx_allocate','fx_buy','obligation_due','fx_receipt','fx_receipt_undo','obligation_close','order','prepayment','delivery','ready','ship','clearing','clear','receive','cost_add','cost_review','register','permit','actual','amend'] as const;
export const foreignFileKinds:Record<string,string>={...{sample:'مدرک نمونه / نتیجه بررسی',technical:'مشخصات فنی',proforma:'پروفرما',invoice:'اینویس',packing:'پکینگ',green_sheet:'برگ سبز',registration:'ثبت سفارش',permit:'مجوز واردات'},fx_allocation:'تخصیص ارز',fx_purchase:'خرید ارز',fx_statement:'اکسل حساب صراف',obligation:'مدرک رفع تعهد',production_order:'سفارش تولید',payment:'مدرک پیش‌پرداخت',shipping:'مدرک حمل',cost:'مدرک هزینه'};
export const foreignHelp='سه مسیر انتخاب منبع، ارز و مجوز، و خرید و حمل مستقل‌اند. نبود تأیید ثبت سفارش یا تخصیص ارز مانع سفارش تولید، حمل یا ترخیص در این گردش نیست و تأیید ویژه مدیرعامل لازم ندارد. بدون ثبت تخصیص، برچسب «بدون تخصیص ارز» باقی می‌ماند. تاریخ رفع تعهد را مدیر بازرگانی تعیین می‌کند؛ هیچ مهلت قانونی فرض نمی‌شود. اکسل حساب باید حساب، ارز، مبلغ، تاریخ و مرجع تراکنش و بازه پوشش مشخص داشته باشد؛ تطبیق فقط با تأیید مالی انجام می‌شود.';
export function foreignLabels(s:any){const d=s.data;return {allocation:d.foreign?.allocation?'تخصیص ارز ثبت‌شده':'بدون تخصیص ارز',administrative:d.registration?'ثبت سفارش ثبت‌شده':'ثبت سفارش ثبت نشده',physical:foreignPhysicalStates[d.foreign?.physical||'planned']};}
export function foreignAlerts(s:any,statements:any[],today:string){
 const d=s.data,f=d.foreign||{},out:any[]=[];
 for(const p of f.fxPurchases||[]){if(!p.obligationDue&&!p.closed)out.push({key:'deadline:'+p.id,kind:'missing_deadline',role:'manager',due:p.day,title:'تعیین تاریخ رفع تعهد توسط مدیر بازرگانی',fxId:p.id});
 if(p.obligationDue&&!p.closed)out.push({key:'obligation:'+p.id,kind:today>p.obligationDue?'obligation_overdue':'obligation_due',role:'manager',due:p.obligationDue,title:'پیگیری رفع تعهد ارزی',fxId:p.id});
 if(!p.received){const covering=statements.some(r=>r.data.account===p.account&&r.data.from<=p.day&&r.data.to>=p.receiptDue);out.push({key:'broker:'+p.id,kind:today>=p.receiptDue?(covering?'receipt_not_found':'statement_stale'):'broker_pending',role:'buyer',due:p.receiptDue,title:today>=p.receiptDue?(covering?'دریافت صراف در حساب تأیید نشده':'اکسل حساب برای بررسی دریافت صراف به‌روز نیست'):'پیگیری دریافت صراف',fxId:p.id});}}
 if(['ordered','preparing'].includes(f.physical)&&f.deliveryDay)for(const role of ['buyer','logistics'])out.push({key:'delivery:'+role,kind:today>f.deliveryDay?'delivery_overdue':'delivery_due',role,due:f.deliveryDay,title:'پیگیری تاریخ تحویل و هماهنگی حمل'});
 if(f.physical==='cleared')out.push({key:'warehouse',kind:'warehouse',role:'inventory',due:today,title:'کنترل پکینگ و دریافت محموله در قرنطینه'});
 return out;
}
export const foreignMoney=(v:string)=>{if(typeof v!=='string'||!/^\d{1,15}(\.\d{1,6})?$/.test(v))throw Error('مبلغ نامنفی با حداکثر شش رقم اعشار لازم است.');const [a,b='']=v.split('.');return BigInt(a)*BigInt(1000000)+BigInt(b.padEnd(6,'0'));};
export const foreignMoneyText=(v:bigint)=>{const x=v/BigInt(1000000),y=(v%BigInt(1000000)).toString().padStart(6,'0').replace(/0+$/,'');return x.toString()+(y?'.'+y:'');};
export function foreignCostAllocation(s:any,cost:any){const lines=s.data.actual?.lines||[],total=foreignMoney(cost.amountRial);if(!lines.length)throw Error('پکینگ واقعی برای تخصیص هزینه لازم است.');const weights=lines.map((l:any)=>cost.basis==='weight'?foreignMoney(l.grossKg):cost.basis==='value'?foreignMoney(l.unitPrice)*foreignMoney(l.quantity)/BigInt(1000000):foreignMoney(cost.manual?.find((x:any)=>x.linkId===l.linkId)?.amountRial||'0')),sum=weights.reduce((n:bigint,w:bigint)=>n+w,BigInt(0));if(sum<=BigInt(0)||cost.basis==='manual'&&sum!==total)throw Error('مبنای تخصیص مثبت و جمع تخصیص دستی برابر کل هزینه لازم است.');let allocated=BigInt(0);return lines.map((l:any,i:number)=>{const amount=cost.basis==='manual'?weights[i]:i===lines.length-1?total-allocated:total*weights[i]/sum;allocated+=amount;return {linkId:l.linkId,materialId:l.materialId,amountRial:foreignMoneyText(amount)};});}
