import {storage} from './storage';
import {foreignRows,memberRole} from './foreign-purchase';
import {foreignAlerts,foreignSelectionStates} from './foreign-purchase-contract';
import {leadMembers,leadMemberGuard} from './sales-leads';
import {dayAt,addDay,notice} from './duties';
import {trainingContext} from './training-context';
export async function syncForeignTasks(nowDate=new Date()){
 if(trainingContext.getStore())return;const db=storage(),rows=await foreignRows(),members=await leadMembers(),now=nowDate.toISOString(),today=dayAt(nowDate),existing=(await db.prepare("SELECT * FROM duty_runs WHERE template_id='foreign-purchase'").all()).results as any[],wanted=new Set<string>(),statements=rows.filter(r=>r.type==='foreign_statement');
 const run=async(r:any,key:string,role:string,title:string,due:string,preferred:string,manager:string,stage:string)=>{
 let assignees=members.filter(m=>memberRole(m,role)&&(!preferred||m.id===preferred));if(!assignees.length)assignees=members.filter(m=>memberRole(m,role));
 if(!assignees.length)assignees=[{id:'@admin'}];
 for(const m of assignees){const tid='foreign:'+r.id+':'+key+':'+m.id;wanted.add(tid);const old=existing.find(t=>t.id===tid),snapshot={foreignPurchaseWorkflow:true,recordId:r.id,workflowRole:role,missingOwner:m.id==='@admin',sourceSection:'sourcing',sourceId:'foreign:'+r.id,title, instructions:'پرونده بازرگانی خارجی را باز کنید و مرحله واقعی و مدرک را ثبت کنید. یادداشت کارتابل این مرحله را تکمیل نمی‌کند.',evidence:'text',remindHours:24,escalateHours:48,reminderDays:r.data.foreign?.reminderDays||[14,7,3,1],stage,history:old?JSON.parse(old.data).history||[]:[]};const deadline=due+'T16:00:00+03:30';
 if(old&&old.state==='open'&&old.due===deadline&&JSON.parse(old.data).stage===stage&&old.supervisor===manager&&JSON.stringify(JSON.parse(old.data).reminderDays)===JSON.stringify(snapshot.reminderDays))continue;
 const op=crypto.randomUUID();await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'foreign_task','{}','scheduler',?,CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) AND COALESCE((SELECT revision FROM duty_runs WHERE id=?),0)=? THEN 1 ELSE 0 END)").bind(op,now,r.id,r.revision,tid,old?.revision||0),leadMemberGuard(db,op,members),old?db.prepare("UPDATE duty_runs SET state='open',data=?,due=?,supervisor=?,revision=revision+1,updated=? WHERE id=? AND revision=?").bind(JSON.stringify(snapshot),deadline,manager,now,tid,old.revision):db.prepare("INSERT INTO duty_runs(id,template_id,period,assignee,supervisor,due,state,data,revision,created,updated) VALUES(?,'foreign-purchase',?,?,?,?,'open',?,1,?,?)").bind(tid,r.id+':'+key,m.id,manager,deadline,JSON.stringify(snapshot),now,now),notice(tid,m.id,'foreign:'+stage,title,now)]);
 }};
 for(const r of rows){if(r.type==='foreign_selection'&&!['approved'].includes(r.data.state)){const d=r.data,role=d.state==='review'?'engineering':'buyer';await run(r,'selection',role,foreignSelectionStates[d.state]+' · '+d.name,d.state==='awaiting_sample'?d.sampleDue:d.due,role==='buyer'?d.ownerId:'',d.managerId,d.state+':'+d.round);}
 if(r.type==='purchase_shipment'&&r.data.route==='foreign'){const f=r.data.foreign||{};for(const a of foreignAlerts(r,statements,today)){const assignee=a.role==='manager'?f.managerId:a.role==='buyer'?f.ownerId:a.role==='logistics'?f.logisticsId:f.inventoryId;await run(r,a.key,a.role,a.title+' · '+r.data.title,a.due,assignee||'',f.managerId||'@admin',a.kind+':'+a.due);}
 for(const c of (f.costs||[]).filter((c:any)=>c.state==='review'))await run(r,'cost:'+c.id,'finance','بررسی و تخصیص هزینه بار · '+c.title,addDay(c.day,2),'',f.managerId,'cost:'+c.id);
 }}
 for(const t of existing.filter(t=>!wanted.has(t.id)&&!['completed','cancelled'].includes(t.state))){const recordId=JSON.parse(t.data).recordId,r=rows.find(r=>r.id===recordId),op=crypto.randomUUID();await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'foreign_task_retire','{}','scheduler',?,CASE WHEN COALESCE((SELECT revision FROM flow_entities WHERE id=?),0)=? AND EXISTS(SELECT 1 FROM duty_runs WHERE id=? AND revision=?) THEN 1 ELSE 0 END)").bind(op,now,recordId,r?.revision||0,t.id,t.revision),leadMemberGuard(db,op,members),db.prepare("UPDATE duty_runs SET state='completed',revision=revision+1,updated=? WHERE id=? AND revision=?").bind(now,t.id,t.revision)]);}
}
export function foreignTaskNotices(r:any,nowDate:Date){const d=JSON.parse(r.data),today=dayAt(nowDate),due=r.due.slice(0,10),now=nowDate.toISOString(),out:any[]=[];for(const days of d.reminderDays||[14,7,3,1])if(today>=addDay(due,-days)&&today<=due)out.push(notice(r.id,r.assignee,'foreign-before:'+due+':'+days,'یادآوری '+days+' روز پیش از موعد: '+d.title,now));if(today>due){out.push(notice(r.id,r.assignee,'foreign-late:'+today,d.title+' از موعد گذشته است.',now));out.push(notice(r.id,r.supervisor||'@admin','foreign-manager:'+today,'پیگیری فوری: '+d.title,now));}return out;}
