import {storage} from './storage';
import {AccessError} from './authorization';
import {supplierRows,supplierEntity,checkPurchaseTechnical} from './suppliers';
import {applyShipment,shipmentLines} from './purchase-shipments';
import {dayAt,validDay,addDay,taskRequired as req,taskText as txt} from './duties';
import {leadMembers,leadMemberGuard} from './sales-leads';
import {trainingContext} from './training-context';
import {foreignModes,foreignMoney,foreignMoneyText,foreignCostAllocation,foreignLabels,foreignAlerts} from './foreign-purchase-contract';
import {scaled} from './production';
import {suggestBatchNumber} from './batch-number';
import {sha256} from './firmware';
export const foreignFail=(m:string,status=400):never=>{throw new AccessError(m,status)};
export function foreignRoles(u:any){const p=u.permissions||{},internal=!p.salesAgentId&&!p.serviceAgentId&&!p.hospitalCenterId&&!p.salesRoles?.includes('agent')&&!p.serviceRoles?.includes('agent')&&!trainingContext.getStore(),admin=internal&&u.isAdmin;return {read:internal&&(admin||p.supplyRoles?.some((r:string)=>['foreign','commerce_manager','ceo','engineering','finance','inventory'].includes(r))||p.flowRoles?.some((r:string)=>['inventory','logistics'].includes(r))||p.transportRoles?.includes('manager')||p.finance==='write'),buyer:internal&&(admin||p.supplyRoles?.includes('foreign')||p.supplyRoles?.includes('commerce_manager')),manager:internal&&(admin||p.supplyRoles?.includes('commerce_manager')),engineering:internal&&(admin||p.supplyRoles?.includes('engineering')),finance:internal&&(admin||p.finance==='write'||p.supplyRoles?.includes('finance')),inventory:internal&&(admin||p.flowRoles?.includes('inventory')||p.supplyRoles?.includes('inventory')),logistics:internal&&(admin||p.transportRoles?.includes('manager')||p.flowRoles?.includes('logistics')),commercial:internal&&(admin||p.supplyRoles?.some((r:string)=>['foreign','commerce_manager','ceo','finance'].includes(r))||p.finance==='write')};}
export async function foreignRows(){const types=['foreign_selection','foreign_file','shipment_file','foreign_statement','foreign_statement_row','purchase_shipment'];const rows=[];for(const t of types)rows.push(...await supplierRows(t));return rows;}
export async function foreignBy(u:any,id:string){if(!foreignRoles(u).read)foreignFail('دسترسی بازرگانی خارجی ندارید.',403);const r:any=await storage().prepare("SELECT * FROM flow_entities WHERE id=? AND type IN ('purchase_shipment','foreign_selection')").bind(id).first();if(!r)foreignFail('پرونده در دسترس نیست.',404);const e={...r,data:JSON.parse(r.data)};if(e.type==='purchase_shipment'&&e.data.route!=='foreign')foreignFail('پرونده خارجی لازم است.',404);return e;}
export function foreignFileVisible(u:any,f:any){const r=foreignRoles(u);return r.commercial||r.engineering&&['sample','technical'].includes(f.kind)||(r.inventory||r.logistics)&&['packing','technical','shipping'].includes(f.kind);}
export function foreignFileWrite(u:any,kind:string){const r=foreignRoles(u);return r.buyer||r.finance&&['payment','cost','fx_statement','fx_purchase','obligation'].includes(kind)||r.engineering&&['sample','technical'].includes(kind)||r.logistics&&kind==='shipping';}
export function foreignPublic(u:any,s:any){const roles=foreignRoles(u);if(s.type==='foreign_selection')return s;const labels=foreignLabels(s);if(roles.commercial)return {...s,labels};const packing=(s.data.actual?.lines||s.data.initial.lines).map((l:any)=>({linkId:l.linkId,materialId:l.materialId,code:l.code,name:l.name,unit:l.unit,quantity:l.quantity,packaging:l.packaging,netKg:l.netKg,grossKg:l.grossKg,volumeM3:l.volumeM3,generalSpecs:l.generalSpecs,supplierSpecs:l.supplierSpecs,supplierCode:l.supplierCode}));return {id:s.id,type:s.type,revision:s.revision,created:s.created,labels,data:{title:s.data.title,supplierName:s.data.supplierName,route:'foreign',initial:{day:s.data.initial.day,lines:packing},actual:s.data.actual?{day:s.data.actual.day,lines:packing,document:s.data.actual.document}:null,foreign:{physical:s.data.foreign?.physical,ownerId:s.data.foreign?.ownerId,logisticsId:s.data.foreign?.logisticsId,inventoryId:s.data.foreign?.inventoryId,deliveryDay:s.data.foreign?.deliveryDay,receiving:s.data.foreign?.receiving,orderIds:s.data.foreign?.orderIds},history:[]}};}
const actualDay=(v:any)=>{const d=req(v,10);if(!validDay(d)||d>dayAt())foreignFail('تاریخ واقعی تا امروز لازم است.');return d;};
const dueDay=(v:any)=>{const d=req(v,10);if(!validDay(d))foreignFail('تاریخ مهلت معتبر لازم است.');return d;};
const amount=(v:any)=>{const n=foreignMoney(v);if(n<=BigInt(0))foreignFail('مبلغ مثبت لازم است.');return foreignMoneyText(n);};
const uuid=(v:any)=>{const s=req(v,80);if(!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(s))foreignFail('شناسه معتبر لازم است.');return s;};
export const memberRole=(m:any,role:string)=>m?.status==='active'&&!!(foreignRoles({isAdmin:false,permissions:JSON.parse(m.permissions)}) as any)[role];
export async function foreignApply(u:any,b:any){
 const roles=foreignRoles(u);if(!roles.read)foreignFail('دسترسی ندارید.',403);const id=uuid(b.id),mode=req(b.mode,40);if(b.confirmed!==true||!foreignModes.includes(mode as any))foreignFail('عملیات و تأیید صریح لازم است.');
 if(['register','permit','actual','amend'].includes(mode)){const s=await foreignBy(u,req(b.caseId));if(s.type!=='purchase_shipment')foreignFail('محموله لازم است.');return applyShipment(u,{...b,shipmentId:s.id});}
 const db=storage(),now=new Date().toISOString(),notes=req(b.notes,3000),signature=JSON.stringify(b),prior:any=await db.prepare('SELECT actor,payload FROM inventory_operations WHERE id=?').bind(id).first();if(prior){if(prior.actor!==u.userId||prior.payload!==signature)foreignFail('شناسه عملیات قبلاً استفاده شده است.',409);return {saved:true,repeated:true};}
 const checks:any[]=[],writes:any[]=[],members=await leadMembers(),need=(role:keyof ReturnType<typeof foreignRoles>)=>{if(!roles[role])foreignFail('مجوز این مرحله را ندارید.',403);};
 const guard=(q:string,...p:any[])=>checks.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN '+q+' THEN guard ELSE 0 END WHERE id=?').bind(...p,id));const version=(e:any)=>guard('EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?)',e.id,e.revision);
 const get=async(eid:string,type:string)=>{const e=await supplierEntity(eid,type);version(e);return e;};
 const put=(eid:string,type:string,data:any,old?:any)=>writes.push(old?db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=? AND revision=?').bind(JSON.stringify(data),now,eid,old.revision):db.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').bind(eid,type,JSON.stringify(data),now,now));
 const member=(mid:any,role:string)=>{const m=members.find(m=>m.id===mid);if(!memberRole(m,role))foreignFail('مسئول فعال با مجوز '+role+' لازم است.');return m!.id;};
 let target=id,old:any=null,data:any={};if(mode!=='selection_create'){old=await foreignBy(u,req(b.caseId));target=old.id;version(old);if(b.revision!==old.revision)foreignFail('نسخه پرونده تغییر کرده است.',409);data=JSON.parse(JSON.stringify(old.data));}
 const history=(d:any)=>{d.history=[...(d.history||[]),{mode,actor:u.userId,at:now,notes}];};
 const evidence=async(kind:string)=>{const did=req(b.documentId),f:any=await db.prepare("SELECT * FROM flow_entities WHERE id=? AND type IN ('foreign_file','shipment_file')").bind(did).first();if(!f)foreignFail('مدرک همین پرونده لازم است.');const e={...f,data:JSON.parse(f.data)};if((e.data.caseId||e.data.shipmentId)!==target||e.data.kind!==kind||!foreignFileVisible(u,e.data))foreignFail('مدرک مرحله و پرونده منطبق نیست.',403);version(e);return {id:e.id,sha256:e.data.sha256,issuedOn:e.data.issuedOn,reference:e.data.reference};};
 if(mode.startsWith('selection_')||['sample_received','sample_review'].includes(mode)){
 if(mode==='selection_create'){need('buyer');const m=await get(req(b.materialId),'material');data={materialId:m.id,name:m.data.name,code:m.data.code,generalSpecs:m.data.specs||'',state:'searching',ownerId:member(b.ownerId,'buyer'),managerId:member(b.managerId,'manager'),due:dueDay(b.due),round:1,candidates:[],history:[]};}
 else{if(old.type!=='foreign_selection')foreignFail('پرونده انتخاب منبع لازم است.');if(mode==='selection_candidate'){need('buyer');if(!['searching','rejected'].includes(data.state))foreignFail('برای تغییر منبع دور تازه باز کنید.',409);const l=await get(req(b.linkId),'supplier_material'),s=await get(l.data.supplierId,'supplier');if(l.data.materialId!==data.materialId||s.data.route!=='foreign'||!s.data.active)foreignFail('منبع فعال خارجی همان کالا لازم است.');data.linkId=l.id;data.supplierId=s.id;data.supplierName=s.data.name;data.supplierSpecs=req(l.data.supplierSpecs||'',10000);data.generalSpecs=(await get(data.materialId,'material')).data.specs||'';data.sampleDue=dueDay(b.sampleDue);data.state='awaiting_sample';data.candidates.push({linkId:l.id,supplierId:s.id,day:actualDay(b.day),notes,round:data.round});}
 else if(mode==='sample_received'){need('buyer');if(data.state!=='awaiting_sample')foreignFail('نمونه در انتظار دریافت نیست.',409);data.sample={day:actualDay(b.day),reference:req(b.reference,200),document:await evidence('sample')};data.state='review';}
 else if(mode==='sample_review'){need('engineering');if(data.state!=='review'||typeof b.approved!=='boolean')foreignFail('نمونه آماده بررسی نیست.',409);const l=await get(data.linkId,'supplier_material'),m=await get(data.materialId,'material');if(l.data.supplierSpecs!==data.supplierSpecs||m.data.specs!==data.generalSpecs)foreignFail('مشخصات از زمان درخواست نمونه تغییر کرده؛ دور تازه لازم است.',409);data.review={approved:b.approved,day:actualDay(b.day),document:await evidence('sample'),actor:u.userId,notes};data.state=b.approved?'approved':'rejected';put(l.id,'supplier_material',{...l.data,sampleApproval:{selectionId:target,approved:b.approved,at:now,generalSpecs:data.generalSpecs,supplierSpecs:data.supplierSpecs,actor:u.userId,notes}},l);}
 else if(mode==='selection_reopen'){need('buyer');data.round+=1;data.previousRounds=[...(data.previousRounds||[]),{round:data.round-1,linkId:data.linkId,sample:data.sample,review:data.review,generalSpecs:data.generalSpecs,supplierSpecs:data.supplierSpecs}];data.state='searching';data.due=dueDay(b.due);delete data.sample;delete data.review;if(data.linkId){const l=await get(data.linkId,'supplier_material');put(l.id,'supplier_material',{...l.data,sampleApproval:{...l.data.sampleApproval,approved:false,reopenedAt:now}},l);}delete data.linkId;}}
 history(data);put(target,'foreign_selection',data,old);
 }else{
 if(old.type!=='purchase_shipment'||data.route!=='foreign')foreignFail('محموله خارجی لازم است.');const f=data.foreign||{physical:'planned',fxPurchases:[],prepayments:[],costs:[],receiving:[]};data.foreign=f;
 if(mode==='configure'){need('buyer');f.ownerId=member(b.ownerId,'buyer');f.managerId=member(b.managerId,'manager');f.logisticsId=member(b.logisticsId,'logistics');f.inventoryId=member(b.inventoryId,'inventory');f.receiptDays=Number(b.receiptDays??10);if(!Number.isInteger(f.receiptDays)||f.receiptDays<1||f.receiptDays>60)foreignFail('مهلت دریافت صراف ۱ تا ۶۰ روز است.');const reminders=b.reminderDays||[14,7,3,1];if(!Array.isArray(reminders)||reminders.length>10||reminders.some((n:any)=>!Number.isInteger(n)||n<0||n>90))foreignFail('فاصله یادآوری معتبر لازم است.');f.reminderDays=[...new Set(reminders)].sort((a:any,b:any)=>b-a);}
 else{
 if(!f.ownerId||!f.managerId)foreignFail('ابتدا مسئول‌ها و مدیر بازرگانی را تعیین کنید.');
 if(mode==='fx_queue'){need('buyer');if(!data.registration)foreignFail('ثبت سفارش برای صف تخصیص لازم است.');if(f.allocation)foreignFail('تخصیص قبلاً ثبت شده است.',409);f.queue={day:actualDay(b.day),reference:req(b.reference)};}
 else if(mode==='fx_allocate'){need('buyer');if(!f.queue)foreignFail('ابتدا ورود به صف تخصیص ثبت شود.');if(f.allocation)foreignFail('تخصیص قبلاً ثبت شده است.',409);f.allocation={day:actualDay(b.day),reference:req(b.reference),amount:amount(b.amount),currency:data.currency,document:await evidence('fx_allocation')};}
 else if(mode==='fx_buy'){need('finance');if(!f.allocation)foreignFail('خرید تخصیص ارز به تخصیص ثبت‌شده نیاز دارد.');const day=actualDay(b.day),a=amount(b.amount),total=(f.fxPurchases||[]).reduce((n:bigint,p:any)=>n+foreignMoney(p.amount),BigInt(0))+foreignMoney(a);if(total>foreignMoney(f.allocation.amount))foreignFail('خرید ارز از تخصیص بیشتر است.');f.fxPurchases=[...(f.fxPurchases||[]),{id,day,amount:a,currency:data.currency,reference:req(b.reference),account:req(b.account),expectedReference:txt(b.expectedReference||'',200),receiptDue:addDay(day,f.receiptDays||10),document:await evidence('fx_purchase'),matches:[],received:false,obligationDue:null,closed:false}];}
 else if(['obligation_due','fx_receipt','fx_receipt_undo','obligation_close'].includes(mode)){
 const p=(f.fxPurchases||[]).find((p:any)=>p.id===b.fxId);if(!p)foreignFail('خرید ارز یافت نشد.');
 if(mode==='obligation_due'){need('manager');if(p.closed)foreignFail('رفع تعهد بسته است.');const due=dueDay(b.due);if(due<p.day)foreignFail('تاریخ رفع تعهد قبل از خرید ارز نیست.');p.deadlineHistory=[...(p.deadlineHistory||[]),{old:p.obligationDue,due,actor:u.userId,at:now,notes}];p.obligationDue=due;}
 else if(mode==='obligation_close'){need('manager');if(!p.obligationDue||p.closed)foreignFail('موعد تعیین‌شده و پرونده باز لازم است.');p.closed={day:actualDay(b.day),document:await evidence('obligation'),actor:u.userId,notes};}
 else if(mode==='fx_receipt'){need('finance');const row=await get(req(b.rowId),'foreign_statement_row'),a=amount(b.amount),n=foreignMoney(a),used=(row.data.allocations||[]).reduce((sum:bigint,x:any)=>sum+foreignMoney(x.amount),BigInt(0)),matched=(p.matches||[]).reduce((sum:bigint,x:any)=>sum+foreignMoney(x.amount),BigInt(0));if(row.data.account!==p.account||row.data.currency!==p.currency||row.data.day<p.day||used+n>foreignMoney(row.data.amount)||matched+n>foreignMoney(p.amount))foreignFail('ردیف حساب یا مبلغ با خرید ارز منطبق نیست.');if((p.matches||[]).some((x:any)=>x.rowId===row.id))foreignFail('این ردیف قبلاً تطبیق شده است.',409);p.matches.push({rowId:row.id,amount:a,day:row.data.day,reference:row.data.reference,actor:u.userId,at:now,notes});p.received=matched+n===foreignMoney(p.amount);put(row.id,'foreign_statement_row',{...row.data,allocations:[...(row.data.allocations||[]),{caseId:target,fxId:p.id,amount:a,operationId:id}]},row);}
 else{need('finance');if(p.closed)foreignFail('پس از رفع تعهد، ابطال دریافت از این مسیر مجاز نیست.');const match=(p.matches||[]).find((x:any)=>x.rowId===b.rowId);if(!match)foreignFail('تطبیق یافت نشد.');const row=await get(req(b.rowId),'foreign_statement_row');put(row.id,'foreign_statement_row',{...row.data,allocations:(row.data.allocations||[]).filter((x:any)=>!(x.caseId===target&&x.fxId===p.id))},row);p.matchHistory=[...(p.matchHistory||[]),{...match,undoneAt:now,undoneBy:u.userId,reason:notes}];p.matches=p.matches.filter((x:any)=>x.rowId!==row.id);p.received=false;}
 }
 else if(mode==='order'){need('buyer');if(f.physical!=='planned')foreignFail('سفارش تولید قبلاً ثبت شده است.',409);const day=actualDay(b.day),deliveryDay=dueDay(b.deliveryDay);if(deliveryDay<day)foreignFail('تحویل قبل از سفارش نیست.');const orders=[];for(const l of data.initial.lines){const checked=await checkPurchaseTechnical(l.materialId,l.linkId,{specs:l.generalSpecs,designVersion:l.designVersion,supplierSpecs:l.supplierSpecs});for(const e of Object.values(checked))version(e);const link=await get(l.linkId,'supplier_material'),approval=link.data.sampleApproval;if(!approval?.approved||approval.generalSpecs!==l.generalSpecs||approval.supplierSpecs!==l.supplierSpecs)foreignFail('تأیید تحقیق‌وتوسعه نمونه با مشخصات همین خرید لازم است.');const supplier=await get(link.data.supplierId,'supplier');if(!supplier.data.active)foreignFail('تأمین‌کننده غیرفعال است.');const oid=crypto.randomUUID();put(oid,'purchase_order',{planId:target,foreignShipmentId:target,supplier:data.supplierName,supplierId:data.supplierId,supplierLinkId:l.linkId,materialId:l.materialId,partCode:l.code,unit:l.unit,quantity:scaled(l.quantity),unitPrice:l.unitPrice,currency:data.currency,route:'foreign',state:'preparing',eta:deliveryDay,promisedEta:deliveryDay,specs:l.supplierSpecs,generalSpecs:l.generalSpecs,history:[{stage:'preparing',notes,reference:req(b.reference),eta:deliveryDay}],sampleApproval:approval});orders.push({linkId:l.linkId,orderId:oid});}f.orderIds=orders;f.physical='ordered';f.order={day,reference:req(b.reference),document:await evidence('production_order')};f.deliveryDay=deliveryDay;}
 else if(mode==='prepayment'){need('finance');if(!f.order)foreignFail('سفارش تولید لازم است.');const a=amount(b.amount),paid=(f.prepayments||[]).reduce((n:bigint,p:any)=>n+foreignMoney(p.amount),BigInt(0))+foreignMoney(a),total=data.initial.lines.reduce((n:bigint,l:any)=>n+foreignMoney(l.unitPrice)*foreignMoney(l.quantity)/BigInt(1000000),BigInt(0));if(paid>total)foreignFail('پیش‌پرداخت از مبلغ سفارش بیشتر است.');f.prepayments=[...(f.prepayments||[]),{id,day:actualDay(b.day),amount:a,currency:data.currency,reference:req(b.reference),document:await evidence('payment'),actor:u.userId}];if(f.physical==='ordered')f.physical='preparing';}
 else if(mode==='delivery'){need('buyer');if(!['ordered','preparing'].includes(f.physical))foreignFail('سفارش در مرحله انتظار تحویل نیست.');f.deliveryHistory=[...(f.deliveryHistory||[]),{previous:f.deliveryDay,day:dueDay(b.deliveryDay),at:now,notes}];f.deliveryDay=dueDay(b.deliveryDay);for(const mapping of f.orderIds||[]){const o=await get(mapping.orderId,'purchase_order');put(o.id,'purchase_order',{...o.data,eta:f.deliveryDay},o);}}
 else if(mode==='ready'){need('buyer');if(!['ordered','preparing'].includes(f.physical)||!data.actual)foreignFail('پکینگ واقعی و سفارش فعال لازم است.');const fileList=[...await supplierRows('foreign_file'),...await supplierRows('shipment_file')];if(!fileList.some(x=>(x.data.caseId||x.data.shipmentId)===target&&x.data.kind==='invoice'))foreignFail('اینویس همین بار را بارگذاری کنید.');f.physical='ready';f.readyDay=actualDay(b.day);}
 else if(['ship','clearing','clear'].includes(mode)){if(mode==='clear')need('buyer');if(!roles.buyer&&!roles.logistics)foreignFail('مجوز بازرگانی یا تدارکات لازم است.',403);const transitions:any={ship:['ready','shipping'],clearing:['shipping','clearing'],clear:['clearing','cleared']};if(f.physical!==transitions[mode][0])foreignFail('مرحله حمل یا ترخیص ناسازگار است.',409);const doc=await evidence(mode==='clear'?'green_sheet':'shipping');f[mode]={day:actualDay(b.day),reference:req(b.reference),document:doc,notes};f.physical=transitions[mode][1];if(mode==='ship')for(const mapping of f.orderIds||[]){const o=await get(mapping.orderId,'purchase_order');put(o.id,'purchase_order',{...o.data,state:'shipped'},o);}}
 else if(mode==='receive'){
 need('inventory');if(!u.isAdmin&&(!u.permissions.warehouses||!u.permissions.warehouses.includes('quarantine')))foreignFail('مجوز انبار قرنطینه لازم است.',403);if(f.physical!=='cleared'||!data.actual)foreignFail('ترخیص و پکینگ واقعی لازم است.');if(!Array.isArray(b.lines)||!b.lines.length||b.lines.length>60||new Set(b.lines.map((l:any)=>l.linkId)).size!==b.lines.length)foreignFail('ردیف دریافت معتبر لازم است.');const day=actualDay(b.day),received=[...(f.receiving||[])],existing=(await db.prepare("SELECT json_extract(payload,'$.code') AS code FROM records WHERE kind='batch'").all()).results.map((r:any)=>r.code);
 for(const raw of b.lines){const l=data.actual.lines.find((l:any)=>l.linkId===raw.linkId);if(!l)foreignFail('کالا در پکینگ نیست.');const mapping=(f.orderIds||[]).find((x:any)=>x.linkId===l.linkId);if(!mapping)foreignFail('سفارش خرید مرتبط لازم است.');const quantity=scaled(raw.quantity),priorQty=received.filter((r:any)=>r.linkId===l.linkId).reduce((n:number,r:any)=>n+r.quantity,0),packed=scaled(l.quantity),discrepancy=txt(raw.discrepancy||'',3000);if(priorQty+quantity!==packed&&!discrepancy)foreignFail('شرح کسری، دریافت جزئی یا اضافه در مقایسه پکینگ لازم است.');const m=await get(l.materialId,'material'),o=await get(mapping.orderId,'purchase_order');if(m.data.unit!==l.unit||!m.data.fields?.length)foreignFail('واحد ثابت و فرم کنترل کیفیت ماده باید کامل باشد.');const code=suggestBatchNumber(m.data.code,day,existing).code;existing.push(code);const batchId='batch:'+code,record={partCode:m.data.code,part:m.data.name,date:day,code,quantity:String(quantity/1000),unit:l.unit,status:'قرنطینه',supplier:data.supplierName,maker:'',manufacturerLot:txt(raw.manufacturerLot||'',200),purchase:data.reference,specs:l.supplierSpecs,notes,expiry:'',batchScheme:'part-jalali-v1'};
 writes.push(db.prepare("INSERT INTO records(id,kind,payload,created) VALUES(?,'batch',?,?)").bind(batchId,JSON.stringify(record),now),db.prepare('INSERT INTO inventory_batches(batch_id,part_code,unit,created) VALUES(?,?,?,?)').bind(batchId,l.code,l.unit,now),db.prepare('INSERT INTO inventory_balances(id,item_id,warehouse,quantity) VALUES(?,?,?,?)').bind(batchId+'@quarantine',batchId,'quarantine',quantity),db.prepare('INSERT INTO inventory_entries(id,operation_id,item_id,warehouse,delta) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),id,batchId,'quarantine',quantity));
 put(batchId,'receipt',{batchId,materialId:m.id,materialRevision:m.revision,fields:m.data.fields,specs:l.supplierSpecs,quantity,quantityCheck:{invoiceQuantity:packed,invoiceDifference:priorQty+quantity-packed,orderQuantity:o.data.quantity,priorReceived:priorQty,cumulativeReceived:priorQty+quantity,notes:discrepancy,actor:u.userId,at:now},accepted:0,rejected:0,state:'pending_qc',purchaseOrderId:o.id,foreignShipmentId:target,packingDocumentId:data.actual.document.id,packingSnapshot:l,qcOwner:m.data.qcOwner||'',warehouseOwner:f.inventoryId,expiry:'',day,actor:u.userId});received.push({linkId:l.linkId,batchId,receiptId:batchId,quantity,day,discrepancy,actor:u.userId});put(o.id,'purchase_order',{...o.data,lastReceiptAt:now},o);}
 f.receiving=received;if(b.finish===true){for(const l of data.actual.lines){const q=received.filter((r:any)=>r.linkId===l.linkId).reduce((n:number,r:any)=>n+r.quantity,0);if(q!==scaled(l.quantity)&&!txt(b.discrepancyResolution||'',3000))foreignFail('قبل از پایان دریافت، مغایرت همه ردیف‌های پکینگ را تعیین تکلیف کنید.');}f.physical='received';f.receivedAt=now;f.discrepancyResolution=txt(b.discrepancyResolution||'',3000);}
 }
 else if(mode==='cost_add'){need('buyer');const a=amount(b.amountRial),reference=req(b.reference);if((f.costs||[]).some((c:any)=>c.reference===reference))foreignFail('هزینه با این مرجع قبلاً ثبت شده است.',409);f.costs=[...(f.costs||[]),{id,title:req(b.title),amountRial:a,day:actualDay(b.day),reference,document:await evidence('cost'),state:'review',actor:u.userId}];}
 else if(mode==='cost_review'){need('finance');const c=(f.costs||[]).find((c:any)=>c.id===b.costId);if(!c||c.state!=='review'||typeof b.approved!=='boolean')foreignFail('هزینه در انتظار بررسی لازم است.');if(c.actor===u.userId)foreignFail('ثبت‌کننده هزینه نمی‌تواند همان هزینه را تأیید کند.',403);if(b.approved){if(!['value','weight','manual'].includes(b.basis))foreignFail('روش تخصیص لازم است.');c.basis=b.basis;c.manual=b.manual||[];c.allocations=foreignCostAllocation({data},c);c.packingSnapshot=data.actual; }c.state=b.approved?'approved':'rejected';c.review={actor:u.userId,at:now,notes};}
 else foreignFail('عملیات ناشناخته است.');
 }
 history(data);put(target,'purchase_shipment',data,old);
 }
 await db.batch([db.prepare('INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,?,?,?,?,1)').bind(id,'foreign_'+mode,signature,u.userId,now),leadMemberGuard(db,id,members),...checks,...writes,db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,target,'foreign_'+mode,JSON.stringify({operationId:id,notes}),now)]);return {saved:true,id:target};
}
export async function foreignStatementImport(u:any,b:any){if(!foreignRoles(u).finance)foreignFail('مجوز مالی لازم است.',403);if(b.confirmed!==true)foreignFail('تأیید ردیف‌های پیش‌نمایش لازم است.');const id=uuid(b.id),account=req(b.account),from=actualDay(b.from),to=actualDay(b.to);if(to<from)foreignFail('بازه حساب معتبر نیست.');const file=await supplierEntity(req(b.fileId),'foreign_file');if(file.data.kind!=='fx_statement'||!foreignFileVisible(u,file.data))foreignFail('فایل اکسل حساب صراف لازم است.');
 if(!Array.isArray(b.rows)||b.rows.length>500)foreignFail('حداکثر ۵۰۰ ردیف واریز لازم است؛ حساب بدون واریز نیز با پوشش تاریخ ثبت می‌شود.');const rows=[];for(const raw of b.rows){const day=actualDay(raw.day);if(day<from||day>to)foreignFail('ردیف خارج از بازه حساب است.');if(!['USD','EUR','CNY','IRR','IRT'].includes(raw.currency))foreignFail('ارز ردیف معتبر نیست.');const amountValue=amount(raw.amount),reference=req(raw.reference,200),key='foreign-statement-row:'+await sha256(new TextEncoder().encode(JSON.stringify({account,day,currency:raw.currency,amount:amountValue,reference})).buffer);rows.push({id:key,account,day,currency:raw.currency,amount:amountValue,reference});}if(new Set(rows.map(r=>r.id)).size!==rows.length)foreignFail('ردیف تکراری داخل فایل حساب است.');
 const db=storage(),now=new Date().toISOString(),signature=JSON.stringify(b),prior:any=await db.prepare('SELECT * FROM inventory_operations WHERE id=?').bind(id).first();if(prior){if(prior.actor!==u.userId||prior.payload!==signature)foreignFail('شناسه واردسازی تکراری است.',409);return {saved:true,repeated:true};}
 const writes=[];for(const row of rows)writes.push(db.prepare("INSERT OR IGNORE INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,'foreign_statement_row',?,1,?,?)").bind(row.id,JSON.stringify({...row,fileId:file.id,allocations:[]}),now,now));writes.push(db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,'foreign_statement',?,1,?,?)").bind(id,JSON.stringify({account,from,to,fileId:file.id,fileSha256:file.data.sha256,rowIds:rows.map(r=>r.id),actor:u.userId,notes:req(b.notes,3000)}),now,now));await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'foreign_statement',?,?,?,CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN 1 ELSE 0 END)").bind(id,signature,u.userId,now,file.id,file.revision),...writes,db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,id,'foreign_statement',JSON.stringify({account,from,to,rowCount:rows.length,fileId:file.id}),now)]);return {saved:true,id,rows:rows.length};
}
export async function installForeignPosition(u:any){if(!u.isAdmin)return;const db=storage(),now=new Date().toISOString(),data={name:'مدیر بازرگانی',unit:'بازرگانی',active:true,members:[],supervisor:'',mission:'نظارت بر تأمین داخلی و خارجی و تعهدات ارزی',responsibilities:'تعیین مستند مهلت رفع تعهد هر خرید ارز؛ پایش دریافت صراف، تحویل و مغایرت‌ها.',authorityBoundaries:'سمت مجوز نمی‌دهد؛ نقش مدیر بازرگانی مستقل تنظیم شود. مهلت قانونی در سامانه فرض نمی‌شود.',reportingTo:'مدیرعامل',handoffs:'بازرگانی داخلی و خارجی، مالی، تحقیق‌وتوسعه، تدارکات و انبار'};await db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) SELECT 'foreign-commerce-manager','position',?,1,?,? WHERE NOT EXISTS(SELECT 1 FROM flow_entities WHERE type='position' AND (id='foreign-commerce-manager' OR json_extract(data,'$.name')='مدیر بازرگانی'))").bind(JSON.stringify(data),now,now).run();}
