// Shared presentation vocabulary. Values/identifiers sent to domain APIs remain unchanged.
export const fieldTitles:Record<string,string>={
  "notes": "توضیحات",
  "day": "تاریخ",
  "quantity": "تعداد / مقدار",
  "approved": "تأیید می‌کنم",
  "name": "نام",
  "code": "کد",
  "province": "استان محل استقرار",
  "city": "شهر",
  "coverage": "محدوده خدمت‌دهی (یک ردیف برای هر استان)",
  "allCities": "تمام شهرهای استان",
  "cities": "شهرها با ویرگول جدا شوند؛ برای تمام استان خالی بگذارید",
  "phone": "تلفن",
  "address": "نشانی",
  "active": "فعال",
  "kind": "نوع رکورد",
  "partCode": "کد قطعه",
  "priceRial": "قیمت فروش قطعه / اجرت نماینده (ریال)",
  "costRial": "بهای مرجع داخلی (ریال)",
  "validFrom": "شروع اعتبار",
  "serial": "سریال دستگاه",
  "model": "مدل",
  "customer": "نام مشتری",
  "agentId": "نماینده",
  "complaint": "شرح مشکل مشتری",
  "result": "نتیجه",
  "nextDue": "موعد پیگیری",
  "hours": "ساعت کارکرد",
  "deliverer": "تحویل‌دهنده",
  "accessories": "لوازم همراه",
  "appearance": "وضعیت ظاهری",
  "lines": "اقلام BOM",
  "customerUnitRial": "قیمت واحد برای مشتری (ریال)",
  "oldBatchId": "بچ قبلی",
  "unknownReason": "علت نامشخص بودن بچ",
  "fault": "عیب مشاهده‌شده",
  "cause": "علت",
  "coverageReason": "دلیل شمول یا عدم شمول گارانتی",
  "laborLines": "خدمات و اجرت",
  "tariffId": "تعرفه خدمت",
  "covered": "اجرت بر عهده شرکت است",
  "customerRial": "اجرت قابل پرداخت مشتری (ریال)",
  "person": "نام پاسخ‌دهنده",
  "method": "روش",
  "exceptionReason": "دلیل استثنا",
  "allocations": "بچ‌ها و مقدار مصرف",
  "lineId": "ردیف مرتبط",
  "lotId": "بچ موجودی",
  "tests": "آزمون‌های پس از تعمیر",
  "value": "مقدار واقعی",
  "unit": "واحد",
  "min": "حداقل",
  "max": "حداکثر",
  "passed": "قبول",
  "reference": "مرجع سند",
  "paidRial": "مبلغ اعلام‌شده مشتری (ریال)",
  "rating": "امتیاز مشتری",
  "caseId": "پرونده",
  "batchId": "شناسه بچ",
  "location": "مکان انبار",
  "carrier": "باربری",
  "tracking": "کد رهگیری",
  "eta": "موعد دریافت",
  "confirmedReceived": "تمام اقلام همین بسته دریافت شد",
  "direction": "جهت",
  "amountRial": "مبلغ ریالی",
  "debitId": "سند بدهکار با مانده",
  "creditId": "منبع اعتبار",
  "ownerId": "مسئول پیگیری",
  "source": "منشأ",
  "rows": "ردیف‌ها",
  "months": "مدت (ماه)",
  "scope": "دامنه کاربرد",
  "procedure": "شرح روش اجرایی",
  "effective": "تاریخ اجرا",
  "reviewDate": "بازنگری بعدی",
  "issuer": "مرجع صادرکننده",
  "requirements": "الزامات و مدارک مورد نیاز",
  "missing": "مدارک ناقص / نتیجه بررسی",
  "correspondence": "شماره پیگیری و مکاتبات",
  "expires": "تاریخ انقضا",
  "criteria": "استاندارد / بندها و چک‌لیست",
  "evidence": "شواهد مشاهده‌شده",
  "findings": "یافته‌ها و عدم انطباق‌ها",
  "response": "پاسخ و برنامه پیگیری",
  "containment": "مهار فوری و تعیین تکلیف",
  "rootCause": "تحلیل علت ریشه‌ای",
  "actions": "اقدام، مسئول و زمان‌بندی",
  "effectivenessDate": "موعد بررسی اثربخشی",
  "inputs": "ورودی‌ها و الزامات طراحی",
  "outputs": "خروجی‌ها و مشخصات طراحی",
  "review": "بازنگری طراحی",
  "verification": "تصدیق و شواهد آزمون",
  "validation": "صحه‌گذاری کاربرد موردنظر",
  "transfer": "انتقال به تولید و پذیرش",
  "baseline": "نسخه مبنا / BOM / نرم‌افزار",
  "change": "شرح تغییر و علت",
  "impact": "اهمیت و تکرار نیاز",
  "regulatory": "اثر بر مجوزها و الزامات",
  "hazards": "خطر، توالی رخداد و پیامد",
  "initial": "ارزیابی اولیه و مبنای پذیرش",
  "controls": "کنترل‌های ریسک",
  "residual": "ریسک باقیمانده و تصمیم پذیرش",
  "equipment": "کد / سریال تجهیز",
  "range": "دامنه و دقت / کاربرد مجاز",
  "certificate": "شماره گواهی و آزمایشگاه",
  "serials": "سریال‌ها (هر خط یک سریال)",
  "disposition": "تعیین تکلیف عدم انطباق‌ها",
  "service": "شناسه پرونده خدمات / شکایت",
  "incident": "شرح رخداد و تکرار خرابی",
  "affected": "سریال‌ها و دامنه محصولات متأثر",
  "risk": "ارزیابی ریسک و فوریت",
  "action": "اقدام میدانی / فراخوان / اطلاع‌رسانی",
  "followup": "نتیجه پیگیری و تعیین تکلیف",
  "attendees": "افراد و وظایف موردنیاز",
  "document": "مدرک و نسخه مورد آموزش",
  "assessment": "روش ارزیابی و نتیجه",
  "competence": "وظایف مجاز و محدودیت‌ها",
  "decisions": "تصمیمات مدیریت",
  "resources": "منابع موردنیاز",
  "version": "نسخه",
  "intended": "کاربرد موردنظر و ریسک",
  "protocol": "پروتکل و سناریوهای آزمون",
  "results": "نتایج واقعی و شواهد",
  "deviations": "انحرافات و تعیین تکلیف",
  "purpose": "هدف و راهنمای تکمیل",
  "packages": "تعداد بسته",
  "reason": "دلیل",
  "retryDay": "تاریخ پیگیری بعدی",
  "reportKind": "نوع گزارش",
  "odometer": "کیلومتر فعلی",
  "fuelLitres": "مقدار سوخت، لیتر",
  "fuelCostRial": "مبلغ رسید سوخت، ریال",
  "sourceKey": "مرجع حمل",
  "route": "روش تحویل",
  "pickup": "محل دریافت",
  "destination": "مقصد",
  "recipient": "تحویل‌گیرنده",
  "due": "موعد",
  "receiverId": "مسئول دریافت",
  "driverId": "راننده",
  "vehicleId": "خودرو",
  "condition": "وضعیت ظاهری بسته‌ها",
  "waybill": "بارنامه",
  "handoverTo": "نام فرد تحویل‌گیرنده",
  "resolution": "نتیجه بررسی",
  "expenseId": "هزینه مورد بررسی",
  "plate": "پلاک",
  "partyId": "گیرنده فروش",
  "title": "عنوان",
  "contract": "شماره قرارداد / مرجع سفارش",
  "bomId": "نسخه BOM",
  "amount": "مبلغ",
  "contractAmount": "مبلغ قرارداد (ریال)",
  "remaining": "برآورد کل هزینه باقیمانده، شامل خریدهای باز (ریال)",
  "unitId": "تجهیز",
  "memberId": "فرد انجام‌دهنده",
  "minutes": "زمان واقعی (دقیقه)",
  "rate": "نرخ هر ساعت کار (ریال)",
  "bucket": "نحوه احتساب",
  "allocationMethod": "روش تقسیم هزینه",
  "basis": "مبنای تخصیص و تأیید مالی",
  "sourceId": "مدرک ثبت و تشخیص هزینه (اختیاری)",
  "lineIndex": "شماره ردیف منبع از صفر",
  "orderId": "برگ تولید",
  "unitCost": "بهای تمام‌شده واحد، شامل هزینه مستقیم خرید (ریال)",
  "laborHourly": "نرخ ساعتی دستمزد (ریال)",
  "overheadHourly": "نرخ ساعتی سربار (ریال)",
  "laborTotal": "کل دستمزد مستقیم دوره (ریال)",
  "fixedOverhead": "کل سربار ثابت تولید (ریال)",
  "variableOverhead": "کل سربار متغیر تولید (ریال)",
  "nonproduction": "هزینه اداری و فروش، جدا از تولید (ریال)",
  "materialId": "شناسه کالا",
  "linkId": "کالا و تأمین‌کننده",
  "receiptDays": "مهلت دریافت صراف (روز)",
  "reminderDays": "روزهای یادآوری پیش از موعد",
  "account": "حساب صراف",
  "expectedReference": "مرجع تراکنش مورد انتظار",
  "documentId": "مدرک",
  "discrepancyResolution": "تعیین تکلیف مغایرت",
  "number": "شماره ضمانت‌نامه",
  "bank": "بانک",
  "branch": "شعبه",
  "applicant": "متقاضی",
  "beneficiary": "ذی‌نفع",
  "currency": "ارز",
  "deposit": "سپرده نقدی؛ به همان ارز",
  "fees": "کارمزد؛ به همان ارز",
  "issueDate": "تاریخ صدور",
  "expiry": "انقضا",
  "actionDeadline": "آخرین مهلت اقدام",
  "originalLocation": "محل نگهداری اصل سند",
  "collateral": "شرح وثایق",
  "nextAction": "اقدام بعدی",
  "demandId": "مطالبه باز",
  "fileId": "فایل مرتبط",
  "vendor": "نام فروشنده",
  "explanation": "علت هزینه بالاتر از سقف",
  "department": "بخش مرکز",
  "contact": "مسئول تماس و شماره",
  "description": "شرح",
  "partName": "نام و مشخصات قطعه",
  "work": "خدمات انجام‌شده",
  "parts": "قطعات مصرف‌شده / تعویض‌شده",
  "test": "شرح آزمون عملکرد و نتیجه واقعی",
  "body": "متن",
  "username": "نام کاربری",
  "password": "رمز اولیه امن",
  "employment": "نوع همکاری",
  "managerId": "مدیر بازرگانی",
  "start": "شروع",
  "end": "پایان",
  "leaveMinutes": "اعتبار پایه مرخصی (دقیقه)",
  "bankAccount": "شماره حساب / شبا",
  "personal": "اطلاعات شخصی",
  "startTime": "شروع (ساعت تهران)",
  "endTime": "پایان (ساعت تهران؛ کمتر از شروع یعنی روز بعد)",
  "breakMinutes": "استراحت بدون کار (دقیقه)",
  "shiftId": "شیفت",
  "insuranceBps": "نرخ بیمه: هر ۱۰۰ واحد برابر ۱٪",
  "insuranceCap": "سقف مبنای بیمه (ریال؛ صفر بدون سقف)",
  "taxBps": "نرخ مالیات: هر ۱۰۰ واحد برابر ۱٪",
  "taxExemption": "معافیت مالیات دوره (ریال)",
  "monthlyBase": "حقوق پایه کل دوره (ریال)",
  "monthlyAllowance": "مزایای کل دوره (ریال)",
  "overtimeHourly": "نرخ ساعتی اضافه‌کاری (ریال)",
  "policyId": "قواعد مصوب کسورات",
  "at": "زمان واقعی به ساعت تهران",
  "leaveType": "نوع مرخصی",
  "hourly": "درخواست ساعتی",
  "inAt": "از زمان (تهران)",
  "outAt": "تا زمان (تهران)",
  "substituteId": "جانشین",
  "targetId": "دوره کارکرد یا فیش مورد اعتراض",
  "installments": "اقساط",
  "repaymentStart": "شروع بازپرداخت",
  "deadline": "آخرین روز اعتراض",
  "supplierId": "تأمین‌کننده",
  "terms": "شرایط واقعی خرید و سررسید قرارداد",
  "settlementId": "اتصال به تسویه خرید و قیمت بچ (اختیاری)",
  "paymentId": "پرداخت",
  "invoiceNumber": "شماره فاکتور نهایی",
  "fxRate": "هر واحد ارز، چند ریال؟",
  "fxSource": "مدرک / منبع نرخ تبدیل",
  "shipmentScope": "این فاکتور یا سهم آن مربوط به کدام محموله است؟",
  "recoverableTaxRial": "مالیات قابل بازیافت، جدا از قیمت (ریال)",
  "reportedPaidRial": "مبلغ پرداخت اعلام‌شده (ریال)",
  "paymentReference": "مرجع پرداخت یا «پرداخت گزارش نشده»",
  "restMinutes": "استراحت؛ خالی = تعیین‌نشده",
  "setupMinutes": "آماده‌سازی؛ خالی = تعیین‌نشده",
  "efficiencyPercent": "درصد زمان مفید (۱ تا ۱۰۰)",
  "lowerPercent": "کف بازه، درصد استاندارد (۰ تا ۱۰۰)",
  "upperPercent": "سقف بازه، درصد استاندارد (۱۰۰ تا ۲۰۰)",
  "routeId": "نسخه مسیر ساخت",
  "count": "تعداد",
  "stage": "مرحله",
  "downtimeMinutes": "توقف تأییدشده؛ کمبود مواد، خرابی و… (دقیقه)",
  "good": "تعداد سالم",
  "scrap": "تعداد ضایعات",
  "reworkCount": "تعداد نیازمند دوباره‌کاری",
  "overtimeReference": "مرجع تأیید اضافه‌کاری",
  "varianceReason": "دلیل مغایرت مصرف / مواد دوباره‌کاری",
  "actualMinutes": "زمان واقعی کار عادی (دقیقه)",
  "overtimeMinutes": "زمان واقعی اضافه‌کاری (دقیقه)",
  "overhead": "سربار تخصیصی (ریال؛ صفر را صریح وارد کنید)",
  "contactName": "نام مخاطب",
  "company": "شرکت / مرکز",
  "email": "ایمیل",
  "sourceDetail": "جزئیات منبع / معرف",
  "interest": "نیاز مشتری",
  "estimatedAmount": "مبلغ تخمینی به ریال؛ خالی یعنی نامشخص",
  "expectedDay": "زمان احتمالی خرید",
  "competitor": "رقیب / گزینه جایگزین",
  "decisionMaker": "تصمیم‌گیران مرکز",
  "tenderDeadline": "آخرین مهلت مناقصه",
  "contactDays": "فاصله پیگیری (روز)",
  "reorderDays": "فاصله سفارش مجدد (روز)",
  "channel": "روش ارتباط",
  "state": "وضعیت",
  "invoiceId": "فاکتور",
  "contractRef": "مرجع قرارداد",
  "financeId": "مسئول مالی (خالی: اعضای نقش مالی)",
  "creditLimit": "سقف اعتبار، ریال",
  "termDays": "مهلت خرید، روز",
  "productId": "شناسه محصول",
  "unitPrice": "قیمت واحد",
  "referrerId": "عامل معرف (اختیاری)",
  "customerReference": "شماره درخواست نماینده",
  "milestone": "مرحله",
  "creditException": "تأیید استثنای اعتبار",
  "cashOrderId": "وجه نقد خرید جدید (اختیاری)",
  "checkInvoiceId": "فاکتور مرتبط با چک (اختیاری)",
  "receipt": "شماره رسید انبار",
  "physicallyReceived": "دریافت فیزیکی",
  "expectedDebt": "جمع بدهی منبع",
  "expectedCredit": "جمع اعتبار منبع",
  "budgetRial": "سقف بودجه همین پرونده، ریال",
  "supplier": "تأمین‌کننده",
  "extrasRial": "جمع هزینه‌های جانبی همین مقدار، ریال",
  "invoiceQuantity": "مقدار فاکتور این محموله",
  "purchase": "مرجع خرید",
  "discrepancyNotes": "شرح مغایرت تعداد / تحویل جایگزین",
  "manufacturerLot": "بچ سازنده",
  "supplierCode": "کد کالا نزد تأمین‌کننده",
  "status": "وضعیت",
  "qualityRisk": "ریسک کیفیت",
  "supplyRisk": "ریسک تأمین",
  "rationale": "دلایل تصمیم",
  "restrictions": "محدودیت و کنترل اضافی",
  "maxQuantity": "سقف مقدار هر سفارش مشروط، واحد کالا",
  "visibility": "سطح دسترسی",
  "issuedOn": "تاریخ صدور",
  "expiresOn": "تاریخ انقضا؛ در صورت داشتن اعتبار محدود",
  "noExpiryReason": "دلیل نداشتن تاریخ انقضا",
  "reviewerId": "بررسی‌کننده",
  "severity": "شدت",
  "detectedOn": "تاریخ کشف",
  "externalLots": "بچ‌های قدیمی، دامنه اثر یا علت نداشتن بچ مرتبط",
  "responseDue": "مهلت پاسخ و اجرا",
  "supplierResponse": "پاسخ دریافت‌شده از تأمین‌کننده",
  "correction": "اصلاح و تعیین تکلیف اقلام معیوب",
  "correctiveAction": "اقدام جلوگیری از تکرار",
  "implementedOn": "تاریخ اجرای اصلاح",
  "verificationMethod": "روش و معیار پذیرش اثربخشی",
  "verificationDue": "موعد بررسی اثربخشی",
  "fxId": "خرید ارز",
  "deliveryDay": "موعد تحویل",
  "netKg": "وزن خالص (کیلوگرم)",
  "grossKg": "وزن ناخالص (کیلوگرم)",
  "volumeM3": "حجم (مترمکعب)",
  "supplierSpecs": "مشخصات تأمین‌کننده",
  "generalSpecs": "مشخصات عمومی",
  "salesAgentId": "نماینده فروش",
  "salesRoles": "نقش‌های فروش",
  "quoteHash": "نسخه پیش‌فاکتور",
  "installmentId": "قسط",
  "openingId": "افتتاحیه",
  "asOf": "تاریخ مبنا",
  "legacyId": "شناسه قبلی",
  "threshold": "آستانه تارگت",
  "discountBps": "نرخ تخفیف (هر ۱۰۰ واحد: ۱٪)",
  "promisedDay": "موعد تحویل",
  "tiers": "پلکان‌ها",
  "problem": "مشکل فعلی",
  "desired": "نتیجه مورد انتظار",
  "example": "مثال",
  "note": "پاسخ و پیگیری",
  "saved": "ذخیره شد",
  "duplicate": "درخواست تکراری",
  "startDate": "تاریخ شروع",
  "needBy": "موعد نیاز",
  "availableOn": "تاریخ تأمین وجه",
  "fxDate": "تاریخ نرخ ارز",
  "validUntil": "پایان اعتبار",
  "newDue": "مهلت جدید",
  "recipientName": "نام گیرنده",
  "threadId": "گفت‌وگو",
  "recipientType": "نوع گیرنده",
  "recipientId": "گیرنده",
  "priority": "اولویت",
  "until": "زمان یادآوری",
  "link": "پرونده مرتبط",
  "section": "بخش",
  "mode": "اقدام",
  "transportRoles": "نقش‌های تدارکات",
  "missionId": "مأموریت",
  "permissions": "دسترسی‌ها",
  "read": "مشاهده",
  "write": "ثبت و ویرایش",
  "eventStages": "مراحل تولید",
  "flowRoles": "نقش گردش مواد",
  "supplyRoles": "نقش تأمین",
  "serviceRoles": "نقش خدمات",
  "serviceDomains": "حوزه خدمات",
  "serviceAgentId": "نمایندگی",
  "warehouses": "انبارهای مجاز",
  "finance": "کنترل مالی",
  "group": "گروه محصول",
  "data": "اطلاعات",
  "category": "گروه",
  "warrantyMonths": "گارانتی (ماه)",
  "part": "قطعه",
  "maker": "سازنده",
  "date": "تاریخ",
  "deviceId": "شناسه دستگاه",
  "deviceIds": "شناسه دستگاه‌ها",
  "receiptId": "شناسه رسید",
  "requestId": "شناسه درخواست",
  "planId": "شناسه برنامه",
  "supplyId": "شناسه تأمین",
  "id": "شناسه",
  "revision": "نسخه رکورد",
  "previousVersion": "نسخه قبلی",
  "previous": "اطلاعات پیش از ویرایش",
  "from": "از انبار",
  "to": "به انبار",
  "operator": "مسئول",
  "assembler": "مونتاژکار",
  "responsible": "مسئول پاسخ",
  "report_id": "گزارش",
  "period": "بازه",
  "cadence": "دوره",
  "values": "مقادیر اندازه‌گیری",
  "verdict": "نتیجه",
  "accepted": "مقدار قبول",
  "rejected": "مقدار رد",
  "design": "نسخه طراحی",
  "firmware": "نسخه نرم‌افزار",
  "capacity": "ظرفیت",
  "smallLabels": "تعداد برچسب کوچک",
  "specs": "مشخصات",
  "defaultLocation": "مکان پیش‌فرض",
  "reorderPoint": "حد سفارش",
  "targetStock": "موجودی هدف",
  "fields": "فیلدهای کنترل کیفیت",
  "qcOwner": "مسئول کنترل کیفیت",
  "warehouseOwner": "مسئول انبار",
  "procurementOwner": "مسئول تأمین",
  "newBatchId": "بچ جایگزین",
  "device": "دستگاه",
  "templateId": "الگوی فرم",
  "accountName": "نام حساب",
  "activityType": "نوع ارتباط",
  "adjustments": "تعدیل‌های حقوق",
  "advanceId": "پیش‌پرداخت مرتبط",
  "agent": "نماینده",
  "alertDays": "روزهای هشدار پیش از موعد",
  "alertId": "هشدار مرتبط",
  "allCollateralReleased": "تمام وثیقه‌ها آزاد شده‌اند",
  "allocation": "مبنای تخصیص",
  "apiToken": "کلید اتصال سرویس",
  "asset": "دارایی",
  "assetId": "دارایی مرتبط",
  "assignee": "مسئول انجام",
  "authorityBoundaries": "حدود اختیارات",
  "backupAcknowledged": "دریافت نسخه پشتیبان را تأیید می‌کنم",
  "base64": "محتوای فایل",
  "baseUrl": "نشانی سرویس",
  "batch": "بچ تولید",
  "board": "مدل یا نسخه برد",
  "calendar": "تقویم کاری",
  "capaId": "اقدام اصلاحی مرتبط",
  "carrierId": "مسئول حمل",
  "case": "پرونده مرتبط",
  "cashBps": "سهم نقدی (هر ۱۰۰ واحد برابر ۱٪)",
  "catalogSnapshot": "نسخه فهرست کالاها",
  "center": "مرکز هزینه",
  "centerId": "مرکز مرتبط",
  "ceo": "مدیرعامل",
  "checkDue": "سررسید چک",
  "childBomId": "فهرست قطعات زیرمجموعه",
  "clearToken": "حذف کلید اتصال ذخیره‌شده",
  "completeCostsConfirmed": "کامل بودن هزینه‌ها تأیید شد",
  "conditionChecked": "وضعیت ظاهری بسته‌ها بررسی شد",
  "confirmationCode": "کد تأیید",
  "confirmed": "تأیید انجام عملیات",
  "contentBase64": "محتوای فایل",
  "cost": "هزینه",
  "costNotes": "شرح هزینه‌ها",
  "country": "کشور",
  "criticalSlaMinutes": "مهلت موارد بحرانی (دقیقه)",
  "currentPassword": "رمز عبور فعلی",
  "dailyTime": "ساعت گزارش روزانه",
  "dates": "تاریخ‌ها",
  "decision": "تصمیم",
  "definitionId": "الگوی وظیفه",
  "delivery": "تحویل",
  "deliveryLateDays": "حد تأخیر تحویل (روز)",
  "deviceModel": "مدل دستگاه",
  "discount": "مبلغ تخفیف",
  "documentIds": "مدارک مرتبط",
  "documents": "مدارک",
  "documentsChecked": "مدارک بررسی شدند",
  "domain": "حوزه فعالیت",
  "domestic": "بازرگانی داخلی",
  "enabled": "فعال باشد",
  "engineering": "تحقیق و توسعه",
  "escalateHours": "ارجاع به مدیر پس از (ساعت)",
  "escalationHours": "مهلت ارجاع به مدیر (ساعت)",
  "escalationMinutes": "مهلت ارجاع به مدیر (دقیقه)",
  "evidenceIds": "مدارک اثبات انجام کار",
  "excludedRial": "مبلغ خارج از ارزش موجودی (ریال)",
  "expenses": "هزینه‌ها",
  "factory": "کارخانه",
  "filename": "نام فایل",
  "forecastId": "پیش‌بینی مرتبط",
  "foreign": "بازرگانی خارجی",
  "format": "قالب خروجی",
  "goalAchievement": "حداقل تحقق هدف در آستانه اول (درصد)",
  "goalElapsed": "زمان سپری‌شده در آستانه اول (درصد)",
  "goalFinalAchievement": "حداقل تحقق هدف در آستانه دوم (درصد)",
  "goalFinalElapsed": "زمان سپری‌شده در آستانه دوم (درصد)",
  "goalId": "هدف مرتبط",
  "grid": "جدول اطلاعات",
  "guaranteeId": "ضمانت‌نامه مرتبط",
  "handedOver": "تحویل انجام شد",
  "handoffId": "تحویل مرتبط",
  "handoffs": "مراحل تحویل مسئولیت",
  "header": "عنوان ستون",
  "holdPurchase": "خرید متوقف شود",
  "holidays": "روزهای تعطیل",
  "hospitalCenterId": "مرکز بیمارستانی",
  "image": "تصویر",
  "instructions": "راهنمای انجام کار",
  "inventory": "انبار",
  "invoiceDay": "تاریخ فاکتور",
  "itemId": "ردیف مرتبط",
  "items": "اقلام",
  "itemsChecked": "اقلام بررسی شدند",
  "job": "عملیات مرتبط",
  "key": "نام فیلد",
  "label": "عنوان نمایشی",
  "layout": "چیدمان چاپ",
  "leadDays": "هشدار پیش از موعد (روز)",
  "leadId": "سرنخ فروش",
  "leadRevision": "نسخه سرنخ",
  "length": "طول بخش فایل",
  "limit": "حداکثر تعداد",
  "lossReason": "علت ازدست‌رفتن سرنخ",
  "manufacturer": "سازنده اصلی",
  "mapping": "تطبیق ستون‌ها",
  "material": "کالا",
  "maxTokens": "سقف پاسخ دستیار",
  "memberIds": "کارکنان مشمول",
  "members": "اعضا",
  "message": "متن پیام",
  "messenger": "راه ارتباطی پیام‌رسان",
  "methodConfirmed": "روش محاسبه تأیید شد",
  "metrics": "شاخص‌های ارزیابی",
  "mime": "نوع فایل",
  "mission": "مأموریت",
  "monthDay": "روز ماه",
  "normalMinutes": "ظرفیت عادی کار (دقیقه)",
  "noticeId": "اعلان مرتبط",
  "offset": "نقطه شروع بخش فایل",
  "operation": "عملیات",
  "origin": "منشأ درخواست",
  "overdueAmount": "آستانه مبلغ معوق (ریال)",
  "overdueDays": "آستانه تأخیر معوق (روز)",
  "owners": "مسئولان",
  "packaged": "بسته‌بندی انجام شد",
  "packagesChecked": "تعداد بسته‌ها بررسی شد",
  "packaging": "نوع بسته‌بندی",
  "page": "صفحه",
  "pageSize": "تعداد در هر صفحه",
  "parent_id": "پرونده مادر",
  "parentId": "پرونده مادر",
  "path": "مسیر",
  "paymentHours": "مهلت بررسی پرداخت (ساعت)",
  "paymentTerms": "شرایط پرداخت",
  "periodId": "دوره مرتبط",
  "personnelRoles": "نقش‌های پرسنلی",
  "plan": "برنامه",
  "policy": "قواعد",
  "positionId": "سمت سازمانی",
  "preview": "پیش‌نمایش",
  "previousId": "رکورد قبلی",
  "previousRevision": "نسخه قبلی",
  "priceId": "قیمت مرجع",
  "product": "محصول",
  "productIds": "محصولات",
  "profileId": "پروفایل دستیار",
  "projectId": "پروژه مرتبط",
  "purchaseOrderId": "سفارش خرید",
  "qc": "کنترل کیفیت",
  "qmsRoles": "نقش‌های تضمین کیفیت",
  "quality": "کیفیت",
  "quarterlyTime": "ساعت گزارش فصلی",
  "query": "عبارت جست‌وجو",
  "question": "پرسش",
  "quoteId": "پیشنهاد قیمت",
  "quoteRevision": "نسخه پیشنهاد قیمت",
  "receiptIds": "رسیدهای مرتبط",
  "receiptReference": "شماره رسید تحویل",
  "recordId": "رکورد انتخاب‌شده",
  "remindHours": "فاصله یادآوری (ساعت)",
  "reminderMinutes": "فاصله یادآوری (دقیقه)",
  "report": "گزارش",
  "reportId": "گزارش مرتبط",
  "reportingTo": "گزارش‌دهی به",
  "requestSource": "منشأ درخواست",
  "required": "تکمیل الزامی است",
  "requiredForPurchase": "برای خرید الزامی است",
  "responseHours": "مهلت پاسخ (ساعت)",
  "responsibilities": "شرح مسئولیت‌ها",
  "returnCount": "آستانه تعداد برگشتی",
  "returnDays": "بازه بررسی برگشتی (روز)",
  "returnId": "برگشت مرتبط",
  "reviewDue": "مهلت بررسی",
  "roleId": "نقش سازمانی",
  "routes": "مسیرهای تأمین",
  "row": "ردیف",
  "saleId": "فروش مرتبط",
  "salesOrderId": "سفارش فروش",
  "salesTerms": "شرایط فروش",
  "schedule": "برنامه زمانی",
  "scores": "امتیازهای ارزیابی",
  "search": "جست‌وجو",
  "segment": "حوزه فروش",
  "settings": "تنظیمات",
  "settlement": "تسویه",
  "shares": "سهم‌های تخصیص",
  "shipment": "محموله",
  "slaMinutes": "مهلت رسیدگی (دقیقه)",
  "sourceSection": "بخش مبدأ",
  "supervisor": "سرپرست",
  "supplierLinkId": "ارتباط کالا و تأمین‌کننده",
  "systemPrompt": "دستورالعمل دستیار",
  "task": "وظیفه",
  "taskId": "وظیفه مرتبط",
  "temperature": "میزان تنوع پاسخ",
  "text": "متن",
  "thread": "گفت‌وگو",
  "time": "زمان",
  "token": "کلید دسترسی",
  "total": "جمع کل",
  "treatment": "نحوه احتساب هزینه",
  "type": "نوع داده",
  "unavailable": "ناموجود",
  "userId": "کاربر",
  "userPage": "صفحه کاربران",
  "viewerIds": "افراد مجاز به مشاهده",
  "warehouse": "انبار",
  "weekday": "روز هفته",
  "weekdays": "روزهای کاری",
  "weeklyTime": "ساعت گزارش هفتگی",
  "weight": "وزن",
  "size": "حجم فایل (بایت)",
  "links": "پرونده‌های مرتبط",
  "private": "محرمانه",
  "answers": "پاسخ‌های فرم",
  "options": "گزینه‌های قابل انتخاب",
  "logisticsId": "مسئول تدارکات",
  "inventoryId": "مسئول انبار",
  "sampleDue": "موعد دریافت نمونه",
  "rowId": "ردیف گردش حساب",
  "costId": "هزینه مرتبط",
  "manual": "تخصیص دستی",
  "finish": "دریافت محموله کامل شد",
  "discrepancy": "شرح مغایرت",
  "obligationDue": "مهلت رفع تعهد",
  "bps": "نرخ (هر ۱۰۰ واحد برابر ۱٪)",
  "contractId": "قرارداد مرتبط",
  "partnerKind": "نوع همکاری",
  "error": "پیام خطا"
};
export const toolFieldTitles:Record<string,Record<string,string>>={
  "personnel_apply": {
    "memberId": "درخواست برای",
    "code": "کد پرسنلی",
    "unit": "واحد",
    "title": "عنوان دوره",
    "location": "محل کار",
    "employment": "نوع همکاری",
    "managerId": "مدیر اصلی",
    "start": "از روز کاری",
    "end": "تا روز کاری",
    "leaveMinutes": "اعتبار پایه مرخصی (دقیقه)",
    "bankAccount": "حساب / شبای جدید",
    "personal": "اطلاعات شخصی جدید",
    "active": "پرونده فعال",
    "startTime": "از ساعت",
    "endTime": "تا ساعت",
    "breakMinutes": "استراحت بدون کار (دقیقه)",
    "shiftId": "شیفت جدید",
    "insuranceBps": "نرخ بیمه: هر ۱۰۰ واحد برابر ۱٪",
    "insuranceCap": "سقف مبنای بیمه (ریال؛ صفر بدون سقف)",
    "taxBps": "نرخ مالیات: هر ۱۰۰ واحد برابر ۱٪",
    "taxExemption": "معافیت مالیات دوره (ریال)",
    "effective": "تاریخ اثر",
    "monthlyBase": "حقوق پایه کل دوره (ریال)",
    "monthlyAllowance": "مزایای کل دوره (ریال)",
    "overtimeHourly": "نرخ ساعتی اضافه‌کاری (ریال)",
    "policyId": "قواعد مصوب کسورات",
    "day": "تاریخ پرداخت",
    "at": "زمان واقعی به ساعت تهران",
    "direction": "تردد",
    "reference": "شناسه بانکی / مرجع یکتای پرداخت",
    "kind": "نوع درخواست",
    "leaveType": "نوع مرخصی",
    "hourly": "درخواست ساعتی",
    "inAt": "از زمان (تهران)",
    "outAt": "تا زمان (تهران)",
    "substituteId": "همکار تأییدکننده تغییر (اختیاری)",
    "targetId": "درخواست مصوب برای لغو",
    "amount": "مبلغ پرداخت واقعی (ریال)",
    "installments": "تعداد اقساط",
    "repaymentStart": "شروع بازپرداخت",
    "deadline": "آخرین روز اعتراض"
  },
  "guarantee_apply": {
    "direction": "جهت",
    "kind": "نوع",
    "number": "شماره ضمانت‌نامه",
    "bank": "بانک",
    "branch": "شعبه",
    "applicant": "متقاضی",
    "beneficiary": "ذی‌نفع",
    "currency": "ارز",
    "amount": "مبلغ به ارز پرونده",
    "deposit": "سپرده نقدی؛ به همان ارز",
    "fees": "کارمزد؛ به همان ارز",
    "issueDate": "تاریخ صدور",
    "expiry": "انقضای جدید",
    "actionDeadline": "مهلت اقدام جدید",
    "linkId": "اتصال به پروژه / سفارش / طرف حساب",
    "contract": "شماره قرارداد یا توضیح ارتباط",
    "originalLocation": "محل نگهداری اصل سند",
    "collateral": "شرح وثایق",
    "due": "موعد پیگیری",
    "nextAction": "اقدام بعدی",
    "day": "تاریخ واقعی",
    "reference": "شماره مرجع واقعی",
    "demandId": "مطالبه باز",
    "fileId": "مدرک همین پرونده"
  },
  "sales_apply": {
    "notes": "توضیح حواله",
    "name": "نام کاربر",
    "contact": "مسئول تماس",
    "phone": "شماره تماس",
    "province": "استان",
    "city": "شهر",
    "address": "نشانی تحویل",
    "contractRef": "مرجع قرارداد",
    "ownerId": "کارشناس مسئول (خالی: اعضای نقش فروش)",
    "financeId": "مسئول مالی (خالی: اعضای نقش مالی)",
    "managerId": "مدیر پیگیری (خالی: مدیر فروش فعال موجود)",
    "active": "قیمت فعال",
    "creditLimit": "سقف بدهی مجاز، ریال",
    "termDays": "مهلت خرید، روز",
    "productId": "محصول",
    "unitPrice": "قیمت نهایی واحد، ریال",
    "reference": "شماره گزارش منبع",
    "title": "عنوان مدرک",
    "basis": "مبنای محاسبه",
    "referrerId": "عامل معرف (اختیاری)",
    "customerReference": "شماره درخواست نماینده",
    "approved": "تأیید می‌کنم (برداشتن علامت: رد درخواست)",
    "milestone": "مرحله",
    "creditException": "استثنای سقف اعتبار یا بدهی معوق را تأیید می‌کنم",
    "exceptionReason": "دلیل و مرجع اجازه استثنا",
    "cashOrderId": "وجه نقد خرید جدید (اختیاری)",
    "checkInvoiceId": "فاکتور مرتبط با چک (اختیاری)",
    "method": "روش",
    "amount": "مبلغ، ریال",
    "bank": "بانک",
    "state": "نتیجه",
    "invoiceId": "فاکتور",
    "receipt": "شماره رسید انبار",
    "physicallyReceived": "همه سریال‌های این درخواست را فیزیکی دریافت و کنترل کردم",
    "source": "نام سامانه / منبع قبلی",
    "expectedDebt": "جمع بدهی باز در منبع، ریال",
    "expectedCredit": "جمع اعتبار در منبع، ریال",
    "username": "نام کاربری انگلیسی",
    "count": "تعداد این حواله",
    "packages": "تعداد بسته دریافت‌شده",
    "result": "نتیجه"
  },
  "sales_network_apply": {
    "kind": "موضوع",
    "title": "عنوان درخواست",
    "months": "مهلت باقیمانده، ماه شمسی",
    "ownerId": "کارشناس مسئول",
    "contactDays": "فاصله تماس، روز",
    "reorderDays": "فاصله خرید مجدد، روز",
    "channel": "روش ارتباط",
    "day": "تاریخ پرداخت",
    "state": "وضعیت",
    "nextAction": "اقدام بعدی",
    "nextDue": "موعد پیگیری",
    "reference": "مرجع واقعی پرداخت",
    "start": "شروع قرارداد",
    "end": "پایان قرارداد",
    "invoiceId": "فاکتور مرتبط",
    "amount": "مبلغ تسویه، ریال",
    "notes": "شرح، نتیجه یا مستند تصمیم (در پرونده شریک قابل مشاهده است)"
  },
  "foreign_purchase_apply": {
    "notes": "شرح اقدام / علت",
    "materialId": "کالا",
    "linkId": "محصول تأمین‌کننده",
    "receiptDays": "مهلت پیگیری دریافت صراف / روز",
    "reminderDays": "روزهای یادآوری قبل از موعد، با ویرگول",
    "reference": "شماره / مرجع واقعی",
    "amount": "مبلغ به ارز پرونده",
    "account": "شناسه حساب صراف",
    "expectedReference": "مرجع مورد انتظار در حساب، اگر معلوم است",
    "title": "نوع و عنوان هزینه",
    "amountRial": "مبلغ هزینه / ریال",
    "basis": "روش تخصیص",
    "documentId": "مدرک همین مرحله",
    "discrepancyResolution": "تعیین تکلیف مغایرت نهایی، اگر وجود دارد"
  },
  "build_project_apply": {
    "title": "مدرک یا موضوع ناقص",
    "customer": "بیمارستان / مشتری",
    "contract": "شماره قرارداد / مرجع سفارش",
    "ownerId": "مسئول پیگیری",
    "bomId": "BOM پایه (اختیاری)",
    "amount": "مبلغ تعهد باز (ریال)",
    "contractAmount": "مبلغ قرارداد (ریال)",
    "remaining": "برآورد کل هزینه باقیمانده، شامل خریدهای باز (ریال)",
    "quantity": "مقدار در واحد اصلی قطعه",
    "location": "محل برگشت: راهرو-قفسه-طبقه-خانه",
    "unitId": "تجهیز",
    "memberId": "فرد انجام‌دهنده",
    "minutes": "زمان واقعی (دقیقه)",
    "rate": "نرخ هر ساعت کار (ریال)",
    "reference": "مرجع آزمون و تحویل فنی تجهیز",
    "bucket": "نحوه احتساب",
    "allocationMethod": "روش تقسیم هزینه",
    "basis": "مبنای تخصیص و تأیید مالی",
    "sourceId": "مدرک ثبت و تشخیص هزینه (اختیاری)",
    "lineIndex": "شماره ردیف منبع از صفر",
    "orderId": "سفارش خرید مرتبط (اختیاری)",
    "notes": "توضیح، دلیل تغییر یا مدرک تأیید"
  },
  "costing_apply": {
    "unitCost": "بهای تمام‌شده واحد، شامل هزینه مستقیم خرید (ریال)",
    "reference": "شماره سند خرید / مدرک قیمت",
    "laborHourly": "نرخ ساعتی دستمزد (ریال)",
    "overheadHourly": "نرخ ساعتی سربار (ریال)",
    "title": "عنوان دوره",
    "laborTotal": "کل دستمزد مستقیم دوره (ریال)",
    "fixedOverhead": "کل سربار ثابت تولید (ریال)",
    "variableOverhead": "کل سربار متغیر تولید (ریال)",
    "nonproduction": "هزینه اداری و فروش، جدا از تولید (ریال)"
  },
  "purchase_payables_apply": {
    "title": "مدرک یا مغایرت مورد پیگیری",
    "supplierId": "تأمین‌کننده",
    "route": "مسیر خرید",
    "amount": "مبلغ اختلاف که از صف پرداخت کنار گذاشته شود (ریال)",
    "purpose": "هدف خرید یا پرداخت",
    "evidence": "مدرک رفع نقص / نتیجه بررسی",
    "terms": "شرایط واقعی خرید و سررسید قرارداد",
    "settlementId": "اتصال به تسویه خرید و قیمت بچ (اختیاری)",
    "account": "کد و عنوان حساب واقعی",
    "basis": "مبنای شناسایی بدهی مطابق شرایط خرید",
    "paymentId": "پرداخت قابل تخصیص",
    "orderId": "سفارش مرتبط (اختیاری)",
    "condition": "شرط پیش‌پرداخت طبق قرارداد",
    "ownerId": "مسئول پیگیری",
    "notes": "توضیح و دلیل تأیید این عملیات"
  },
  "purchase_settlement_apply": {
    "invoiceNumber": "شماره فاکتور نهایی",
    "fxRate": "هر واحد ارز، چند ریال؟",
    "fxSource": "مدرک / منبع نرخ تبدیل",
    "shipmentScope": "این فاکتور یا سهم آن مربوط به کدام محموله است؟",
    "recoverableTaxRial": "مالیات قابل بازیافت، جدا از قیمت (ریال)",
    "reportedPaidRial": "مبلغ پرداخت اعلام‌شده (ریال)",
    "paymentReference": "مرجع پرداخت یا «پرداخت گزارش نشده»"
  },
  "routine_production_apply": {
    "restMinutes": "استراحت همین بازه؛ خالی = سیاست",
    "setupMinutes": "آماده‌سازی همین کار؛ خالی = سیاست",
    "efficiencyPercent": "درصد زمان مفید (۱ تا ۱۰۰)",
    "lowerPercent": "کف بازه، درصد استاندارد (۰ تا ۱۰۰)",
    "upperPercent": "سقف بازه، درصد استاندارد (۱۰۰ تا ۲۰۰)",
    "materialId": "قطعه واسط",
    "title": "عنوان / شماره بچ ساخت",
    "routeId": "نسخه مسیر ساخت",
    "count": "تعداد تحویلی به فرد",
    "stage": "مرحله",
    "memberId": "کارگر",
    "start": "شروع بازه",
    "end": "پایان بازه",
    "leaveMinutes": "مرخصی (دقیقه)",
    "downtimeMinutes": "توقف تأییدشده؛ کمبود مواد، خرابی و… (دقیقه)",
    "good": "تعداد سالم",
    "scrap": "تعداد ضایعات",
    "reworkCount": "تعداد نیازمند دوباره‌کاری",
    "overtimeReference": "مرجع اضافه‌کاری",
    "varianceReason": "دلیل مغایرت مصرف / مواد دوباره‌کاری",
    "actualMinutes": "زمان واقعی کار عادی (دقیقه)",
    "overtimeMinutes": "زمان واقعی اضافه‌کاری (دقیقه)",
    "reference": "مرجع تأیید مالی",
    "overhead": "سربار تخصیصی (ریال؛ صفر را صریح وارد کنید)",
    "basis": "مبنای مصوب تخصیص سربار"
  },
  "expense_register_apply": {},
  "sales_monitor_apply": {
    "title": "عنوان هدف",
    "amount": "مبلغ وصول جایگزین، ریال",
    "nextAction": "اقدام بعدی مشخص"
  },
  "apply_qms_record": {}
};
export const toolModeTitles:Record<string,Record<string,string>>={
  "personnel_apply": {
    "employee": "پرونده پرسنلی",
    "shift": "تعریف شیفت",
    "assignment": "برنامه کاری",
    "delegate": "جانشین مدیر",
    "policy": "قواعد حقوق",
    "request": "درخواست جدید",
    "punch": "ثبت تردد دستی",
    "ruling": "حکم کارگزینی",
    "document": "سند پرسنلی",
    "period": "دوره کارکرد",
    "approve": "تأیید مرحله",
    "reject": "رد با علت",
    "withdraw": "انصراف",
    "submit": "ارسال برای تأیید",
    "publish": "تأیید و انتشار",
    "acknowledge": "مشاهده کردم",
    "close_work": "تأیید و قفل کارکرد",
    "reopen_work": "بازگشایی کارکرد",
    "calculate": "محاسبه حقوق",
    "approve_payroll": "تأیید فیش",
    "approve_payment": "تأیید پرداخت",
    "pay": "ثبت پرداخت واقعی",
    "close_period": "بستن دوره",
    "cancel_calculation": "ابطال محاسبات و بازگشایی کارکرد"
  },
  "guarantee_apply": {
    "return_review": "برگشت برای اصلاح",
    "cancel_amendment": "لغو اصلاح پیشنهادی",
    "save": "ثبت / ویرایش پرونده",
    "submit": "ارسال برای تأیید مالی",
    "approve": "تأیید مستقل مالی",
    "issue": "ثبت صدور / دریافت",
    "request_extension": "درخواست تمدید",
    "request_release": "درخواست آزادسازی",
    "followup": "ثبت پیگیری",
    "amend": "پیشنهاد تمدید / تغییر مبلغ",
    "approve_amendment": "تأیید اصلاح",
    "confirm_amendment": "ثبت اصلاح بانکی",
    "demand": "ثبت مطالبه",
    "collection": "ثبت وصول / پرداخت مطالبه",
    "resolve_demand": "تعیین تکلیف مطالبه",
    "terminate": "ثبت خاتمه تعهد",
    "return_original": "استرداد اصل سند",
    "release_collateral": "آزادسازی سپرده و وثیقه",
    "close": "بستن نهایی پرونده"
  },
  "sales_apply": {
    "terms": "شرایط اعتباری نماینده",
    "agent": "پرونده نماینده",
    "price": "قیمت فروش",
    "target": "انتشار تارگت و پلکان تخفیف",
    "order": "ثبت سفارش",
    "order_review": "بررسی فروش",
    "order_progress": "موعد و پیشرفت سفارش",
    "order_cancel": "لغو سفارش فاکتورنشده",
    "invoice": "تأیید مالی و صدور فاکتور",
    "payment": "اعلام پرداخت",
    "payment_review": "بررسی پرداخت",
    "check_status": "وصول یا برگشت چک",
    "allocate": "تخصیص اعتبار به قسط",
    "payment_reverse": "برگشت ثبت پرداخت",
    "return_request": "درخواست برگشت دستگاه",
    "return_receive": "دریافت فیزیکی برگشتی",
    "return_review": "بررسی مالی برگشت",
    "opening": "پیش‌نویس مانده افتتاحیه",
    "opening_review": "تطبیق و تأیید افتتاحیه"
  },
  "sales_network_apply": {
    "commission_cancel": "لغو تسویه پرداخت‌نشده",
    "check_link": "اتصال چک به خرید",
    "template": "الگوی عمومی فروش",
    "partner": "نوع همکاری و برنامه پیگیری",
    "contact": "ثبت تماس یا بازدید",
    "case": "درخواست همکاری و پشتیبانی",
    "case_update": "پیگیری / بستن پرونده",
    "contract": "قرارداد پورسانت",
    "contract_review": "بررسی مالی قرارداد",
    "commission_settlement": "درخواست تسویه پورسانت",
    "commission_review": "بررسی تسویه",
    "commission_pay": "ثبت پرداخت واقعی پورسانت"
  },
  "foreign_purchase_apply": {
    "selection_create": "جست‌وجوی جدید تأمین‌کننده",
    "selection_candidate": "انتخاب منبع و درخواست نمونه",
    "sample_received": "ثبت دریافت نمونه",
    "sample_review": "تأیید یا رد نمونه و تأمین‌کننده",
    "selection_reopen": "جست‌وجوی مجدد منبع",
    "configure": "تعیین مسئول‌ها و یادآوری",
    "register": "ثبت سفارش سیستمی",
    "permit": "ثبت مجوز واردات",
    "fx_queue": "ورود به صف تخصیص ارز",
    "fx_allocate": "ثبت تخصیص ارز",
    "fx_buy": "ثبت خرید ارز",
    "obligation_due": "تعیین / اصلاح مهلت رفع تعهد",
    "fx_receipt": "تأیید دریافت صراف از حساب",
    "fx_receipt_undo": "ابطال تطبیق دریافت",
    "obligation_close": "ثبت رفع تعهد",
    "order": "سفارش تولید به تأمین‌کننده",
    "prepayment": "ثبت پیش‌پرداخت واقعی",
    "delivery": "اصلاح وعده تحویل",
    "actual": "ثبت قیمت و پکینگ واقعی بار",
    "ready": "اعلام آمادگی بار",
    "ship": "ثبت حمل",
    "clearing": "ورود به ترخیص",
    "clear": "ثبت ترخیص",
    "receive": "تأیید دریافت انبار",
    "cost_add": "ثبت هزینه همان بار",
    "cost_review": "بررسی و تخصیص هزینه",
    "amend": "اصلاح ثبت سفارش با پکینگ واقعی"
  },
  "build_project_apply": {
    "shortage": "ارجاع کسری به تأمین",
    "create": "تعریف پروژه ساخت",
    "unit": "افزودن تجهیز",
    "bom": "ویرایش BOM پروژه",
    "approve_bom": "تأیید نسخه BOM",
    "budget": "بودجه و برآورد باقی‌مانده",
    "request": "درخواست قطعه از انبار",
    "reserve": "رزرو بچ‌های انبار",
    "issue": "تحویل قطعات به پروژه",
    "cancel_request": "لغو درخواست و آزادسازی رزرو",
    "consume": "ثبت مصرف واقعی",
    "return": "برگشت سالم به انبار",
    "scrap": "ثبت قطعه خراب / نامنطبق",
    "time": "ثبت زمان کار",
    "approve_time": "تأیید زمان و نرخ",
    "expense": "ثبت هزینه و تخصیص",
    "commitment": "ثبت تعهد خرید",
    "close_commitment": "تعیین تکلیف تعهد",
    "issue_note": "ثبت نقص و پیگیری",
    "resolve_note": "تأیید رفع نقص",
    "quality": "تأیید فنی و کیفیت تجهیز",
    "void": "ابطال مستند",
    "close": "نهایی‌سازی مالی پروژه",
    "reopen": "بازگشایی پروژه"
  },
  "costing_apply": {
    "price": "قیمت مستند بچ",
    "material": "نرخ استاندارد قطعه",
    "standard": "زمان و نرخ استاندارد",
    "time": "زمان واقعی دستگاه",
    "period": "هزینه‌های دوره",
    "close": "تأیید و ذخیره گزارش نهایی"
  },
  "purchase_payables_apply": {
    "dispute": "تعیین مبلغ اختلاف و توقف آن",
    "clear_dispute": "رفع اختلاف",
    "close_advance": "بستن مانده برنامه پیش‌پرداخت",
    "create": "پرونده خرید جدید",
    "invoice": "ثبت / اصلاح فاکتور",
    "match": "تطبیق رسیدهای انبار",
    "payment": "ثبت پرداخت انجام‌شده",
    "recognize": "تأیید بدهی",
    "unrecognize": "برگشت تأیید بدهی",
    "allocate": "تخصیص پرداخت به فاکتور",
    "schedule": "شرایط و اقساط پرداخت",
    "release": "اجازه پرداخت",
    "hold": "توقف پرداخت",
    "advance": "برنامه پیش‌پرداخت",
    "release_advance": "اجازه پیش‌پرداخت",
    "issue": "پیگیری نقص و مدرک",
    "resolve_issue": "تأیید رفع نقص",
    "void": "ابطال مستند"
  },
  "routine_production_apply": {
    "policy": "نسخه تنظیم زمان مفید",
    "route": "نسخه مسیر ساخت و کارسنجی",
    "lot": "بچ ساخت قطعه واسط",
    "assign": "تخصیص کار روزانه",
    "adjust": "اصلاح زمان در دسترس",
    "output": "ثبت خروجی و مصرف",
    "close": "بستن کار روز",
    "reason": "توضیح کارگر",
    "review": "نتیجه بررسی سرکارگر",
    "quality": "تأیید کیفیت و رسید نیمه‌ساخته",
    "cost": "نهایی‌سازی بهای بچ"
  },
  "apply_qms_record": {
    "submit": "ارسال برای بررسی",
    "approve": "تأیید مستقل",
    "return": "برگشت برای اصلاح",
    "close": "ثبت اثربخشی و بستن",
    "revise": "ساخت نسخه جدید",
    "acknowledge": "مطالعه کردم",
    "hold": "توقف آزادسازی",
    "save": "ثبت / ویرایش پرونده کیفیت",
    "install_positions": "ایجاد سمت‌های تضمین کیفیت"
  },
  "transport_apply": {
    "checklist": "چک‌لیست پیش از حرکت",
    "blocker": "ثبت مانع انجام کار",
    "blocker_resolve": "رفع مانع و ادامه پیگیری",
    "vehicle_report": "گزارش کیلومتر، سوخت یا خرابی",
    "create": "درخواست حمل",
    "assign": "تخصیص / تغییر مأموریت",
    "collect": "تأیید دریافت راننده",
    "carrier": "تحویل به باربری",
    "offer": "اعلام تحویل به مقصد",
    "receipt": "تأیید دریافت مقصد",
    "resolve": "بررسی مغایرت",
    "documents": "تکمیل اطلاعات بارنامه",
    "expense": "ثبت هزینه حمل",
    "expense_review": "بررسی هزینه حمل",
    "cancel": "لغو درخواست",
    "vehicle": "تعریف / ویرایش خودرو",
    "link_party": "اتصال گیرنده فروش به نمایندگی"
  },
  "after_sales_apply": {
    "agent": "تعریف نماینده",
    "tariff": "تعرفه خدمت",
    "create": "پرونده جدید",
    "contact": "ثبت تماس",
    "intake": "پذیرش دستگاه",
    "diagnose": "عیب‌یابی و برآورد",
    "consent": "پاسخ مشتری به هزینه",
    "authorize": "بررسی گارانتی",
    "reserve": "رزرو قطعات",
    "repair": "ثبت تعمیر و مصرف",
    "test": "آزمون نهایی",
    "deliver": "تحویل به مشتری",
    "return_unrepaired": "تحویل بدون تعمیر",
    "confirm": "تماس تأیید مشتری",
    "labor": "تأیید اجرت",
    "order": "درخواست قطعه و فاکتور",
    "approve_order": "تأیید درخواست قطعه",
    "prepare": "جمع‌آوری قطعات",
    "ship": "ارسال قطعات",
    "receive": "دریافت قطعات",
    "return_send": "ارسال داغی",
    "return_receive": "دریافت داغی",
    "return_review": "بررسی داغی",
    "credit": "تأیید تعدیل مالی داغی",
    "payment": "ثبت پرداخت",
    "offset": "تهاتر حساب",
    "office_stock": "تأمین قطعات دفتر",
    "followup": "پیگیری / تعیین مسئول",
    "activation_preview": "بررسی اطلاعات گارانتی",
    "activation_import": "ثبت اطلاعات گارانتی"
  },
  "inbox_apply": {
    "create": "ارسال پیام جدید",
    "reply": "ارسال پاسخ",
    "claim": "پذیرش مسئولیت",
    "start": "شروع رسیدگی",
    "blocked": "ثبت مانع",
    "submit": "اعلام انجام برای تأیید",
    "approve": "تأیید انجام",
    "reopen": "درخواست اصلاح",
    "close": "بستن گفت‌وگو",
    "cancel": "لغو درخواست",
    "convert": "تبدیل به درخواست کاری",
    "reschedule": "تغییر مهلت",
    "read": "ثبت مشاهده",
    "snooze": "یادآوری بعداً"
  },
  "sales_lead_apply": {
    "save": "ثبت / ویرایش سرنخ",
    "stage": "تغییر مرحله",
    "activity": "ثبت تماس و پیگیری",
    "assign": "انتقال مسئولیت",
    "lose": "ثبت فروش ازدست‌رفته",
    "reopen": "بازگشایی",
    "link_order": "اتصال سفارش موجود",
    "convert": "تبدیل به سفارش"
  }
};
export const baseModeTitles:Record<string,string>={
  "save": "ذخیره اطلاعات",
  "create": "ایجاد پرونده",
  "review": "بررسی اطلاعات",
  "submit": "ارسال برای بررسی",
  "approve": "تأیید",
  "reject": "رد با علت",
  "return": "برگشت برای اصلاح",
  "cancel": "لغو",
  "close": "بستن پرونده",
  "reopen": "بازگشایی پرونده",
  "assign": "تعیین مسئول",
  "adjust": "اصلاح مقدار",
  "output": "ثبت خروجی",
  "rule": "تعریف قاعده",
  "retire_rule": "غیرفعال‌کردن قاعده",
  "match": "تطبیق اطلاعات",
  "pay": "ثبت پرداخت",
  "period": "دوره مالی",
  "configure": "تنظیم قواعد و مسئولان",
  "goal": "تعریف هدف",
  "retire_goal": "غیرفعال‌کردن هدف",
  "scan": "بررسی وضعیت",
  "review_goal": "بازبینی هدف",
  "report_read": "ثبت مطالعه گزارش",
  "acknowledge": "ثبت مشاهده",
  "recover_check": "ثبت جبران چک برگشتی",
  "material": "اطلاعات کالا",
  "standard": "تعریف استاندارد",
  "time": "ثبت زمان",
  "price": "ثبت قیمت",
  "register": "ثبت اطلاعات",
  "permit": "ثبت مجوز",
  "actual": "ثبت اطلاعات واقعی",
  "historical": "ثبت سابقه",
  "specifications": "ثبت مشخصات",
  "upload": "بارگذاری فایل",
  "remove": "حذف فایل",
  "complete": "تکمیل بارگذاری",
  "start": "شروع",
  "policy": "تعریف قواعد",
  "allocation": "تخصیص",
  "read": "ثبت مشاهده",
  "models": "دریافت مدل‌ها",
  "probe": "آزمون اتصال"
};

Object.assign(fieldTitles,{
 routeId:'مسیر ساخت',jobId:'کار تخصیص‌یافته',materialRevision:'نسخه مشخصات کالا',shipmentId:'محموله مرتبط',
 restMinutes:'زمان استراحت (دقیقه)',setupMinutes:'زمان آماده‌سازی (دقیقه)',efficiencyPercent:'بازده هدف (درصد)',lowerPercent:'حد پایین عملکرد (درصد)',upperPercent:'حد بالای عملکرد (درصد)',
 steps:'مراحل ساخت',seconds:'زمان استاندارد (ثانیه)',allowancesIncluded:'زمان‌های مجاز در استاندارد منظور شده‌اند',bom:'فهرست مواد و قطعات',rework:'کار دوباره‌کاری است',downtimeMinutes:'توقف (دقیقه)',overtimeApproved:'اضافه‌کاری تأیید شده است',good:'تعداد سالم',scrap:'تعداد ضایعات',reworkCount:'تعداد دوباره‌کاری',overtime:'انجام در اضافه‌کاری',overtimeReference:'مرجع تأیید اضافه‌کاری',varianceReason:'علت اختلاف با استاندارد',actualMinutes:'زمان واقعی کار (دقیقه)',overtimeMinutes:'زمان اضافه‌کاری (دقیقه)',rates:'نرخ‌های دستمزد',overhead:'سربار (ریال)'
});
Object.assign(toolFieldTitles.routine_production_apply,{stage:'شماره مرحله ساخت (از صفر)',start:'ساعت شروع',end:'ساعت پایان',hourly:'نرخ ساعتی (ریال)',basis:'مبنای محاسبه سربار'});
Object.assign(toolFieldTitles.personnel_apply,{kind:'نوع درخواست یا سند',amount:'مبلغ درخواست (ریال)',installments:'تعداد اقساط بازپرداخت',notes:'شرح درخواست / علت اقدام'});
Object.assign(toolFieldTitles.sales_apply,{orderId:'سفارش فروش',lines:'اقلام سفارش',amount:'مبلغ (ریال)'});
Object.assign(toolModeTitles,{
 purchase_settlement_apply:{save:'ثبت / ویرایش تسویه خرید',submit:'ارسال برای بررسی مالی',review:'بررسی و تخصیص هزینه',approve:'تأیید و قیمت‌گذاری',return:'برگشت برای اصلاح',reopen:'بازگشایی تسویه'},
 expense_register_apply:{save:'ثبت هزینه',approve:'تأیید هزینه',reopen:'بازگشایی هزینه',rule:'تعریف قاعده تشخیص هزینه',retire_rule:'غیرفعال‌کردن قاعده'},
 purchase_shipment_apply:{specifications:'ثبت مشخصات کالا و تأمین‌کننده',create:'ثبت محموله خرید',register:'ثبت سفارش',permit:'ثبت مجوز',actual:'ثبت بسته‌بندی واقعی',historical:'ثبت سابقه مستند محموله',amend:'ثبت اصلاحیه'}
});

Object.assign(fieldTitles,{lines:'ردیف‌ها',fields:'فیلدهای فرم',orderId:'سفارش مرتبط',allocations:'تخصیص‌ها',partCode:'کد قطعه',productId:'محصول',notes:'توضیحات',version:'نسخه'});
for(const tool of ['foreign_purchase_apply','purchase_shipment_apply'])toolFieldTitles[tool]={...toolFieldTitles[tool],lines:'اقلام محموله',quantity:'مقدار کالا',unitPrice:'قیمت واحد به ارز پرونده',notes:'شرح اقدام / علت'};
for(const tool of ['purchase_settlement_apply','purchase_payables_apply'])toolFieldTitles[tool]={...toolFieldTitles[tool],lines:'ردیف‌های فاکتور و رسید',orderId:'سفارش خرید',items:'اقلام خرید'};
toolFieldTitles.expense_register_apply={...toolFieldTitles.expense_register_apply,lines:'ردیف‌های تفکیک هزینه',group:'گروه هزینه',center:'مرکز هزینه',account:'حساب هزینه'};
toolFieldTitles.save_product_bom={lines:'قطعات و مقدار مصرف در محصول',quantity:'مقدار مصرف هر محصول'};
toolFieldTitles.create_production_sheet={orderId:'برگ تولید',lines:'اقلام مصرف تولید'};
toolFieldTitles.apply_qms_record={...toolFieldTitles.apply_qms_record,fields:'تعریف فیلدهای فرم محصول',values:'پاسخ‌ها و مدارک پرونده',private:'دسترسی محرمانه طراحی',kind:'نوع پرونده کیفیت',title:'نام پرونده یا فرم'};

toolFieldTitles.generate_activation_code={deviceCode:'کد ۱۰رقمی نمایش‌داده‌شده روی دستگاه',reason:'علت تولید کد / شماره پیگیری مشتری'};

Object.assign(fieldTitles,{activationCode:'کد پنج‌رقمی مشتری',deviceCode:'کد ۱۰رقمی دستگاه'});

Object.assign(fieldTitles,{assetRoles:'نقش‌های مدیریت اموال',holderKind:'نوع تحویل‌گیرنده',holderId:'تحویل‌گیرنده',holderName:'نام پیمانکار',contractorCode:'کد پیمانکار',contractorContact:'اطلاعات تماس پیمانکار',actualConfirmation:'تأیید دریافت واقعی نامه',specifications:'مشخصات اموال',signer:'نام امضاکننده نامه'});

toolFieldTitles.assets_apply={brand:'برند اموال',condition:'وضعیت سلامت اموال',code:'کد اموال',name:'نام اموال',category:'گروه اموال',serial:'شماره سریال',recordId:'پرونده اموال',reference:'شماره رسید یا نامه',purpose:'علت تحویل / کاربرد'};

Object.assign(toolFieldTitles.purchase_payables_apply,{invoiceType:'نوع فاکتور خرید',documentId:'سند بارگذاری‌شده فاکتور',taxState:'وضعیت مؤدیان',taxId:'شناسه مالیاتی فاکتور',taxDay:'تاریخ اقدام در سامانه مؤدیان'});
toolFieldTitles.get_formal_purchase_invoices={supplier:'نام تأمین‌کننده',product:'نام یا کد کالا',reference:'شماره فاکتور / شناسه مالیاتی',from:'تاریخ فاکتور از',to:'تاریخ فاکتور تا',state:'وضعیت مؤدیان',offset:'شروع صفحه گزارش'};

// Treasury manual forms and assistant proposals share labels.
toolFieldTitles.treasury_apply={entityId:'پرونده خزانه',sourceKey:'قسط یا پیش‌پرداخت آزادشده خرید',accountId:'حساب اجرای واقعی',requestId:'درخواست پرداخت مصوب',destination:'شماره حساب ذی‌نفع / مقصد',beneficiaryMemberId:'کارمند ذی‌نفع',opening:'مانده اول',closing:'مانده آخر',bankId:'شناسه یکتای تراکنش بانک',rowId:'ردیف صورتحساب',movementId:'گردش دفتر',referenceDocument:'مرجع قرارداد / فاکتور / سند',fileId:'مدرک همین پرونده',amount:'مبلغ به ارز حساب',location:'محل نگهداری چک',accepted:'تأیید هزینه',party:'طرف حساب'};
toolModeTitles.treasury_apply={account:'تعریف بانک / صندوق',approve_account:'تأیید مستقل حساب',request:'درخواست دریافت / پرداخت',approve:'تأیید پرداخت و حساب مقصد',reject:'رد درخواست',cancel:'توقف مانده درخواست',execute:'ثبت اجرای واقعی',statement:'ورود صورتحساب',match:'تأیید تطبیق بانکی',unmatch:'برگشت تطبیق',check:'ثبت چک',check_issue:'تأیید صدور / دریافت چک',check_settle:'ثبت وصول واقعی',check_cancel:'ابطال / برگشت چک',expense:'ثبت هزینه تنخواه',expense_review:'بررسی مستقل هزینه',advance_return:'ثبت برگشت مانده تنخواه'};

Object.assign(fieldTitles,{reminderId:"یادآور موردنظر",dueAt:"تاریخ و ساعت یادآوری با منطقه زمانی",trigger:"نوع یادآوری",linkType:"فرایند مرتبط",linkId:"پرونده مرتبط",eventField:"نقطه موردنظر در فرایند",eventCondition:"شرط رویداد",eventValue:"مرحله مقصد"});
