import {storage} from './storage';
import {AccessError} from './authorization';
import {costRead,costWrite,moneyMicro,moneyText} from './costing';
import {trainingContext} from './training-context';
import type {Session} from './permissions';

export const guaranteeStates:Record<string,string>={draft:'پیش‌نویس',review:'بررسی مالی',approved:'منتظر صدور / دریافت',active:'فعال',terminated:'خاتمه؛ پیگیری استرداد',closed:'بسته'};
export const guaranteeModes=['save','submit','return_review','approve','issue','request_extension','request_release','followup','amend','approve_amendment','cancel_amendment','confirm_amendment','demand','collection','resolve_demand','terminate','return_original','release_collateral','close'] as const;
export const guaranteeHelp='خزانه‌دار ثبت و پیگیری می‌کند؛ مدیر مالی مستقل تأیید می‌کند. ثبت مطالبه یا وصول به معنی اجرای عملیات بانکی یا ثبت حسابداری نیست. انقضا پرونده را نمی‌بندد. خاتمه، استرداد اصل و آزادسازی کامل سپرده و وثایق به مدرک واقعی نیاز دارند. مبلغ‌ها فقط در ارز یکسان جمع می‌شوند.';
export const gFail=(message:string,status=400):never=>{throw new AccessError(message,status)};
export const gText=(value:unknown,max=2000)=>{if(typeof value!=='string'||!value.trim()||value.length>max)gFail('متن الزامی یا نامعتبر است.');return (value as string).trim()};
export function gDay(value:unknown){const s=gText(value,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||isNaN(Date.parse(s))||new Date(s).toISOString().slice(0,10)!==s)gFail('تاریخ معتبر لازم است.');return s;}
export function gMoney(value:unknown,zero=false){if(typeof value!=='string')gFail('مبلغ را به صورت عدد متنی وارد کنید.');if(!/^\d{1,15}(\.\d{1,6})?$/.test(value as string))gFail('مبلغ با حداکثر شش رقم اعشار لازم است.');const n=moneyMicro(value);if(n<BigInt(0)||!zero&&n===BigInt(0))gFail('مبلغ نامعتبر است.');return moneyText(n);}
export async function guaranteeRows(){return (await storage().prepare("SELECT * FROM flow_entities WHERE type IN ('bank_guarantee','guarantee_file','position') ORDER BY id").all()).results.map((r:any)=>({...r,data:JSON.parse(r.data)}));}
export async function guaranteeRoles(u:Session,rows?:any[]){
 if(trainingContext.getStore()||u.permissions.hospitalCenterId||u.permissions.salesAgentId||u.permissions.serviceAgentId)gFail('این بخش فقط برای کاربران داخلی شرکت است.',403);
 const all=rows||await guaranteeRows(),mid:any=await storage().prepare("SELECT id,permissions FROM app_members WHERE status='active' AND (subject=? OR id=?)").bind(u.userId,u.userId.startsWith('local:')?u.userId.slice(6):u.userId).first();
 const normalized=(v:string)=>v.replace(/[\s\u200c]/g,'').replace(/ي/g,'ی').replace(/ك/g,'ک');
 const positions=all.filter(r=>r.type==='position'&&r.data.active),treasury=positions.filter(r=>normalized(r.data.name)==='خزانه دار'.replace(/ /g,'')),manager=positions.filter(r=>normalized(r.data.name)==='مدیرمالی');
 const principal=mid?{...u,permissions:JSON.parse(mid.permissions)}:u;if(principal.permissions.salesAgentId||principal.permissions.serviceAgentId||principal.permissions.hospitalCenterId)gFail('این بخش برای کاربران داخلی است.',403);const canRead=u.isAdmin||!!mid&&costRead(principal),canWrite=u.isAdmin||!!mid&&costWrite(principal);
 const has=(list:any[])=>list.some(r=>r.data.members?.includes(mid?.id));
 return {memberId:mid?.id||'',read:canRead,treasury:canWrite&&(u.isAdmin||has(treasury)),manager:canWrite&&(u.isAdmin||has(manager)),positions,treasuryPositions:treasury,managers:manager};
}
export function guaranteeBy(rows:any[],id:string,u:Session,roles:any){const r=rows.find(x=>x.type==='bank_guarantee'&&x.id===id);if(!r||!roles.read&&!r.data.viewerIds?.includes(roles.memberId))gFail('پرونده در دسترس نیست.',404);return r;}
export function guaranteeEvidence(rows:any[],caseId:string,id:unknown){const f=rows.find(r=>r.type==='guarantee_file'&&r.id===id&&r.data.caseId===caseId);if(!f)gFail('مدرک بارگذاری‌شده همین پرونده لازم است.');return f.id;}
export function guaranteeDashboard(records:any[],today:string){const currencies:Record<string,{active:string;deposit:string}>= {};for(const r of records){const d=r.data;if(!['active','terminated'].includes(d.state))continue;const c=currencies[d.currency]||{active:'0',deposit:'0'};if(d.state==='active')c.active=moneyText(moneyMicro(c.active)+moneyMicro(d.amount));c.deposit=moneyText(moneyMicro(c.deposit)+moneyMicro(d.deposit)-moneyMicro(d.releasedDeposit||'0'));currencies[d.currency]=c;}return {currencies,near:records.filter(r=>r.data.state==='active'&&r.data.actionDeadline<=new Date(Date.parse(today+'T12:00:00Z')+30*86400000).toISOString().slice(0,10)).length,overdue:records.filter(r=>r.data.state==='active'&&r.data.actionDeadline<today).length,release:records.filter(r=>r.data.state==='terminated').length};}
export async function applyGuarantee(u:Session,b:any){
 const db=storage(),memberSnapshot:any=await db.prepare("SELECT json_group_array(json_object('id',id,'status',status,'permissions',permissions,'subject',subject)) AS value FROM (SELECT * FROM app_members ORDER BY id)").first(),rows=await guaranteeRows(),roles=await guaranteeRoles(u,rows);
 if(b.confirmed!==true||! /^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(b.id)||!guaranteeModes.includes(b.mode))gFail('عملیات، تأیید و UUID معتبر لازم است.');
 const signature=JSON.stringify(b),prior:any=await db.prepare('SELECT payload,actor FROM inventory_operations WHERE id=?').bind(b.id).first();if(prior){if(prior.actor!==u.userId||prior.payload!==signature)gFail('شناسه عملیات قبلاً برای درخواست دیگری استفاده شده است.',409);return {saved:true,repeated:true,id:b.guaranteeId||b.id};}
 const id=b.guaranteeId||b.id,old=rows.find(r=>r.id===id);if(old&&old.type!=='bank_guarantee')gFail('شناسه پرونده نامعتبر است.');if(old)guaranteeBy(rows,id,u,roles);if(!Number.isSafeInteger(b.revision)||b.revision!==(old?.revision||0))gFail('نسخه پرونده تغییر کرده؛ تازه‌سازی کنید.',409);
 const manager=['return_review','approve','approve_amendment','cancel_amendment','resolve_demand','close'].includes(b.mode),request=['request_extension','request_release'].includes(b.mode);
 if(manager?!roles.manager:request?!roles.treasury&&!old?.data.viewerIds?.includes(roles.memberId):!roles.treasury)gFail('جایگاه مالی مجاز برای این عملیات لازم است.',403);
 const notes=gText(b.notes,4000),now=new Date().toISOString();let linked:any=null;let d:any=old?JSON.parse(JSON.stringify(old.data)):{};
 const state=(...allowed:string[])=>{if(!old||!allowed.includes(d.state))gFail('عملیات در وضعیت فعلی مجاز نیست.',409)};
 const proof=()=>guaranteeEvidence(rows,id,b.fileId);
 const independent=(actor:string)=>{if(actor===u.userId)gFail('تأیید باید توسط فرد دیگری انجام شود.',403)};
 if(b.mode==='save'){
  if(old)state('draft');if(!['outgoing','incoming'].includes(b.direction)||!['tender','performance','advance','other'].includes(b.kind))gFail('جهت و نوع ضمانت‌نامه معتبر نیست.');
  const issueDate=gDay(b.issueDate),expiry=b.expiry?gDay(b.expiry):'',actionDeadline=gDay(b.actionDeadline);if(expiry&&expiry<issueDate||actionDeadline<issueDate||expiry&&actionDeadline>expiry)gFail('ترتیب تاریخ صدور، اقدام و انقضا را بررسی کنید.');
  const currency=gText(b.currency,3).toUpperCase();if(!['IRR','USD','EUR','AED','CNY','GBP','TRY'].includes(currency))gFail('ارز پشتیبانی نمی‌شود.');
  const number=gText(b.number,200),bank=gText(b.bank,200);if(rows.some(r=>r.type==='bank_guarantee'&&r.id!==id&&r.data.number===number&&r.data.bank===bank&&r.data.direction===b.direction))gFail('این ضمانت‌نامه قبلاً ثبت شده است.',409);
  if(b.linkId){linked=await db.prepare("SELECT id,type,revision FROM flow_entities WHERE id=? AND type IN ('build_project','purchase_order','sales_order','supplier','party','hospital_job')").bind(gText(b.linkId,200)).first();if(!linked)gFail('مرجع مرتبط در دسترس نیست.');}
  const amount=gMoney(b.amount),deposit=gMoney(b.deposit||'0',true);if(moneyMicro(deposit)>moneyMicro(amount))gFail('سپرده بیشتر از مبلغ ضمانت‌نامه است.');
  const viewers=b.viewerIds||[];if(!Array.isArray(viewers)||viewers.length>30)gFail('فهرست کاربران مرتبط معتبر نیست.');const members=(await db.prepare("SELECT id,permissions FROM app_members WHERE status='active'").all()).results as any[];for(const v of viewers){const m=members.find(m=>m.id===v),p=m?JSON.parse(m.permissions):{};if(!m||p.hospitalCenterId||p.salesAgentId||p.serviceAgentId)gFail('کاربر مرتبط باید عضو داخلی فعال باشد.');}
  const alerts=b.alertDays||[30,15,7,1];if(!Array.isArray(alerts)||!alerts.length||alerts.length>10||alerts.some((n:any)=>!Number.isInteger(n)||n<1||n>365))gFail('بازه هشدار معتبر نیست.');
  d={...d,direction:b.direction,kind:b.kind,number,bank,branch:typeof b.branch==='string'?b.branch.slice(0,200):'',applicant:gText(b.applicant,200),beneficiary:gText(b.beneficiary,200),amount,currency,deposit,fees:gMoney(b.fees||'0',true),issueDate,expiry,actionDeadline,linkId:linked?.id||'',linkType:linked?.type||'',contract:typeof b.contract==='string'?b.contract.slice(0,500):'',originalLocation:gText(b.originalLocation,500),collateral:typeof b.collateral==='string'?b.collateral.slice(0,2000):'',collateralReleased:false,originalReturned:false,releasedDeposit:'0',viewerIds:[...new Set(viewers)],alertDays:[...new Set(alerts)].sort((a:any,b:any)=>b-a),state:'draft',lastEditor:u.userId,demands:[],requests:[],createdBy:d.createdBy||u.userId};
 }else if(b.mode==='submit'){state('draft');d.state='review';d.submittedBy=u.userId;}
 else if(b.mode==='return_review'){state('review');d.state='draft';}
 else if(b.mode==='approve'){state('review');independent(d.submittedBy);independent(d.lastEditor);d.state='approved';d.approvedBy=u.userId;}
 else if(b.mode==='issue'){state('approved');d.issueFileId=proof();d.state='active';}
 else if(request){state('active');d.requests.push({id:b.id,kind:b.mode,actor:u.userId,at:now,notes,due:gDay(b.due),resolved:false});}
 else if(b.mode==='followup'){state('active','terminated','approved');d.nextAction=gText(b.nextAction);d.nextDue=gDay(b.due);}
 else if(b.mode==='amend'){state('active');if(d.amendment)gFail('اصلاح قبلی هنوز تأیید و ثبت بانکی نشده است.');const amount=gMoney(b.amount),expiry=b.expiry?gDay(b.expiry):'',actionDeadline=gDay(b.actionDeadline);if(actionDeadline<d.issueDate||expiry&&expiry<actionDeadline||moneyMicro(amount)<(d.demands||[]).reduce((n:bigint,x:any)=>n+moneyMicro(x.amount),BigInt(0))||moneyMicro(amount)<moneyMicro(d.deposit))gFail('مبلغ یا تاریخ اصلاح معتبر نیست.');d.amendment={amount,expiry,actionDeadline,actor:u.userId,notes,approved:false};}
 else if(b.mode==='approve_amendment'){state('active');if(!d.amendment||d.amendment.approved)gFail('اصلاح در انتظار تأیید نیست.');independent(d.amendment.actor);d.amendment.approved=true;d.amendment.approvedBy=u.userId;}
 else if(b.mode==='cancel_amendment'){state('active');if(!d.amendment)gFail('اصلاح بازی وجود ندارد.');d.cancelledAmendments=[...(d.cancelledAmendments||[]),{...d.amendment,notes,at:now,actor:u.userId}];delete d.amendment;}
 else if(b.mode==='confirm_amendment'){state('active');if(!d.amendment?.approved)gFail('ابتدا تأیید مستقل مالی لازم است.');d.amendment.fileId=proof();d.amount=d.amendment.amount;d.expiry=d.amendment.expiry;d.actionDeadline=d.amendment.actionDeadline;d.requests=d.requests.map((x:any)=>x.kind==='request_extension'?{...x,resolved:true,fileId:b.fileId}:x);d.amendments=[...(d.amendments||[]),{...d.amendment,at:now}];delete d.amendment;delete d.nextDue;delete d.nextAction;}
 else if(b.mode==='demand'){state('active');const amount=gMoney(b.amount);if((d.demands||[]).reduce((n:bigint,x:any)=>n+moneyMicro(x.amount),BigInt(0))+moneyMicro(amount)>moneyMicro(d.amount))gFail('جمع مطالبه بیشتر از مبلغ ضمانت‌نامه است.');if(d.demands.some((x:any)=>x.reference===b.reference))gFail('این مطالبه قبلاً ثبت شده است.',409);d.demands.push({id:b.id,amount,collected:'0',reference:gText(b.reference,200),day:gDay(b.day),fileId:proof(),resolved:false});}
 else if(b.mode==='collection'){state('active','terminated');const demand=d.demands.find((x:any)=>x.id===b.demandId);if(!demand||demand.resolved)gFail('مطالبه باز یافت نشد.');const amount=gMoney(b.amount);if(d.demands.some((x:any)=>(x.receipts||[]).some((y:any)=>y.reference===b.reference)))gFail('این رسید قبلاً ثبت شده است.',409);if(moneyMicro(demand.collected)+moneyMicro(amount)>moneyMicro(demand.amount))gFail('وصول بیشتر از مانده مطالبه است.');demand.collected=moneyText(moneyMicro(demand.collected)+moneyMicro(amount));demand.receipts=[...(demand.receipts||[]),{amount,day:gDay(b.day),reference:gText(b.reference,200),fileId:proof()}];}
 else if(b.mode==='resolve_demand'){state('active','terminated');const demand=d.demands.find((x:any)=>x.id===b.demandId);if(!demand||demand.resolved)gFail('مطالبه باز یافت نشد.');demand.resolved=true;demand.resolution={notes,fileId:proof(),actor:u.userId};}
 else if(b.mode==='terminate'){state('active');if(d.amendment)gFail('اصلاح باز را ابتدا تعیین تکلیف کنید.');d.terminationFileId=proof();d.state='terminated';d.terminatedBy=u.userId;d.requests=d.requests.map((x:any)=>({...x,resolved:true,fileId:b.fileId}));delete d.nextDue;delete d.nextAction;}
 else if(b.mode==='return_original'){state('terminated');if(d.originalReturned)gFail('اصل سند قبلاً مسترد شده است.');d.originalReturned=true;d.originalFileId=proof();d.lastSettlementBy=u.userId;}
 else if(b.mode==='release_collateral'){state('terminated');const amount=gMoney(b.amount||'0',true);if(moneyMicro(d.releasedDeposit)+moneyMicro(amount)>moneyMicro(d.deposit))gFail('استرداد بیشتر از سپرده است.');if(amount==='0'&&b.allCollateralReleased!==true)gFail('استرداد مبلغ یا تأیید آزادسازی وثیقه لازم است.');d.releasedDeposit=moneyText(moneyMicro(d.releasedDeposit)+moneyMicro(amount));if(b.allCollateralReleased===true)d.collateralReleased=true;d.collateralReleases=[...(d.collateralReleases||[]),{amount,fileId:proof(),notes,at:now}];d.lastSettlementBy=u.userId;}
 else if(b.mode==='close'){state('terminated');independent(d.terminatedBy);independent(d.lastSettlementBy);if(!d.originalReturned||moneyMicro(d.deposit)!==moneyMicro(d.releasedDeposit)||d.collateral&&!d.collateralReleased||d.demands.some((x:any)=>!x.resolved)||d.requests.some((x:any)=>!x.resolved))gFail('اصل سند، سپرده، وثایق و مطالبات باز باید تعیین تکلیف شوند.');d.state='closed';d.closedBy=u.userId;d.closedAt=now;}
 const previous=old?{...old.data,history:undefined}:null;d.history=[...(old?.data.history||[]),{mode:b.mode,actor:u.userId,name:u.name,at:now,notes,fileId:b.fileId||'',previous}];
 if(d.history.length>1000)gFail('تعداد رویدادهای پرونده به سقف رسیده است.');
 const statements=[db.prepare('INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,?,?,?,?,1)').bind(b.id,'guarantee_'+b.mode,signature,u.userId,now),db.prepare('UPDATE inventory_operations SET guard=CASE WHEN COALESCE((SELECT revision FROM flow_entities WHERE id=?),0)=? THEN 1 ELSE 0 END WHERE id=?').bind(id,old?.revision||0,b.id)];
 statements.push(db.prepare("UPDATE inventory_operations SET guard=CASE WHEN (SELECT COUNT(*) FROM flow_entities WHERE type='bank_guarantee')=? AND (SELECT COALESCE(SUM(revision),0) FROM flow_entities WHERE type='bank_guarantee')=? AND (SELECT json_group_array(json_object('id',id,'status',status,'permissions',permissions,'subject',subject)) FROM (SELECT * FROM app_members ORDER BY id))=? THEN 1 ELSE 0 END WHERE id=?").bind(rows.filter(r=>r.type==='bank_guarantee').length,rows.filter(r=>r.type==='bank_guarantee').reduce((n,r)=>n+r.revision,0),memberSnapshot.value,b.id));
 for(const p of rows.filter(r=>r.type==='position'))statements.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN 1 ELSE 0 END WHERE id=?').bind(p.id,p.revision,b.id));
 if(linked)statements.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN 1 ELSE 0 END WHERE id=?').bind(linked.id,linked.revision,b.id));
 statements.push(old?db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=?').bind(JSON.stringify(d),now,id):db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,'bank_guarantee',?,1,?,?)").bind(id,JSON.stringify(d),now,now),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,id,'guarantee_'+b.mode,JSON.stringify(d),now));await db.batch(statements);return {saved:true,id};
}
