import {storage} from './storage';
import {trainingRoles} from './training-contract';
import {trainingContext} from './training-context';
import {dayAt,addDay} from './duties';
export async function prepareHospitalTraining(){if(!trainingContext.getStore())throw Error('Training only');const db=storage();if(await db.prepare("SELECT id FROM flow_entities WHERE id='training-hospital-ready'").first())return;const now=new Date().toISOString(),stmts:D1PreparedStatement[]=[];const put=(id:string,type:string,data:any)=>stmts.push(db.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').bind(id,type,JSON.stringify(data),now,now));
 for(const r of trainingRoles.filter(r=>r.session.permissions.hospitalCenterId))stmts.push(db.prepare("INSERT OR IGNORE INTO app_members(id,email,name,unit,status,subject,permissions,revision,created,updated) VALUES(?,?,?,'آموزش','active',?,?,1,?,?)").bind(r.memberId,r.session.email,r.session.name,r.session.userId,JSON.stringify(r.session.permissions),now,now));
 for(let i=1;i<=2;i++){const centerId='training-hospital-'+i,assetId='training-hospital-asset-'+i;put(centerId,'hospital_center',{name:'مرکز بیمارستانی فرضی '+i,phone:'000-TEST',address:'نشانی آموزشی',active:true,profileId:''});put(assetId,'hospital_asset',{centerId,deviceId:'training-device-'+i+'-2',serial:'TEST-TP'+i+'-002',model:'مدل آموزشی '+i,productId:'training-product-'+i,name:'دستگاه آموزشی مرکز '+i,department:'بخش فرضی',location:'اتاق آموزشی',installedOn:addDay(dayAt(),-20),notes:'فقط برای آزمون نرم‌افزار؛ دستگاه یا مرکز واقعی نیست.'});put('training-hospital-manual-'+i,'hospital_manual',{centerId,assetId,title:'راهنمای آزمایش پنل',version:1,state:'published',reference:'دستورالعمل آموزش نرم‌افزار',body:'برای ثبت درخواست آزمایشی، دکمه اعلام خرابی / درخواست سرویس را انتخاب و شرح مورد فرضی را وارد کنید.\nاین سند راهنمای پزشکی یا راهنمای استفاده از دستگاه واقعی نیست.',fileId:''});put('training-hospital-form-'+i,'hospital_form',{centerId,assetId,title:'چک‌لیست آموزشی',version:1,state:'published',reference:'تست رابط کاربری',fields:[{key:'label',label:'برچسب فرضی خوانا است',type:'result',unit:'',min:'',max:'',required:true}]});put('training-hospital-history-'+i,'hospital_history',{centerId,assetId,title:'بازدید آموزشی قبلی',day:addDay(dayAt(),-10),notes:'سابقه فرضی برای بررسی نمایش تاریخچه',reference:'TEST-VISIT-'+i});}
 put('training-hospital-ready','hospital_training',{ready:true});await db.batch(stmts);
}
