import {salesScope,salesStaff,salesFinance} from './sales';
import {storage} from './storage';
import {AccessError,can} from './authorization';
import {memberId,taskAccess} from './duties';
import type {Session} from './permissions';
import {AsyncLocalStorage} from 'node:async_hooks';
export const inboxAssistantExecution=new AsyncLocalStorage<boolean>();
export const inboxDecode=(r:any)=>r?({...r,data:JSON.parse(r.data)}):null;
export async function inboxIdentity(u:Session){const id=await memberId(u);if(id)return id;if(u.isAdmin)return '@owner';throw new AccessError('حساب فعال برای مکاتبه یافت نشد.',403);}
export async function inboxDirectory(u:Session){const me=await inboxIdentity(u),db=storage();let users=(await db.prepare("SELECT id,name,unit,permissions FROM app_members WHERE status='active' ORDER BY name,id").all()).results as any[];
 if(!u.isAdmin&&u.permissions.serviceAgentId)users=users.filter(r=>{const p=JSON.parse(r.permissions);return !p.serviceAgentId&&p.serviceRoles?.some((x:string)=>['manager','coordinator'].includes(x))&&p.serviceDomains?.some((x:string)=>u.permissions.serviceDomains?.includes(x));});
 if(!u.isAdmin&&u.permissions.salesAgentId){await salesScope(u,u.permissions.salesAgentId);users=users.filter(r=>{const p=JSON.parse(r.permissions),actor={isAdmin:false,permissions:p} as Session;return !p.salesAgentId&&!p.serviceAgentId&&(salesStaff(actor)||salesFinance(actor));});}
 const people=users.map(({id,name,unit})=>({id,name,unit}));if(await db.prepare("SELECT subject FROM app_identity WHERE id='owner'").first())people.unshift({id:'@owner',name:'مدیر سامانه',unit:'مدیریت'});
 const positions=(await db.prepare("SELECT * FROM flow_entities WHERE type='position' AND json_extract(data,'$.active')=1 ORDER BY created,id").all()).results.map(inboxDecode).filter((r:any)=>!u.permissions.serviceAgentId||r.data.members.some((id:string)=>people.some(p=>p.id===id))).map((r:any)=>({id:r.id,name:r.data.name,unit:r.data.unit,members:r.data.members.filter((id:string)=>people.some(p=>p.id===id))}));
 return {me,people,positions:!u.isAdmin&&(u.permissions.serviceAgentId||u.permissions.salesAgentId)?[]:positions};}
export async function positionMembers(id:string){const p:any=await storage().prepare("SELECT data FROM flow_entities WHERE id=? AND type='position' AND json_extract(data,'$.active')=1").bind(id).first();if(!p)return [];const ids=JSON.parse(p.data).members||[];const active=(await storage().prepare("SELECT id FROM app_members WHERE status='active'").all()).results as any[];return ids.filter((id:string)=>active.some(a=>a.id===id));}
export async function inboxAccess(id:string,u:Session){const row=inboxDecode(await storage().prepare("SELECT * FROM flow_entities WHERE id=? AND type='inbox_thread'").bind(id).first()),me=await inboxIdentity(u);if(!row)throw new AccessError('گفت‌وگو یافت نشد.',404);const d=row.data,recipients=d.recipientType==='position'?await positionMembers(d.recipientId):[d.recipientId];if(d.sender!==me&&!recipients.includes(me))throw new AccessError('گفت‌وگو یافت نشد.',404);const responsible=d.recipientType==='person'?d.recipientId:recipients.includes(d.assignee)?d.assignee:'';return {...row,me,isSender:d.sender===me,isRecipient:recipients.includes(me),responsible,canWork:recipients.includes(me)&&responsible===me};}
export async function inboxLink(u:Session,link:any){if(!link?.id||!link?.section)return null;const db=storage();if(link.section==='tasks')await taskAccess(link.id,u);else if(link.section==='transport'){await (await import('./transport')).transportAccess(u,link.id);}else if(link.section==='after-sales'){await (await import('./after-sales')).caseAccess(link.id,u);}else if(link.section==='sourcing'){if(!u.isAdmin&&!u.permissions.supplyRoles?.length)throw new AccessError('دسترسی ندارید.',403);if(!await db.prepare("SELECT id FROM flow_entities WHERE id=? AND type='sourcing_plan'").bind(link.id).first())throw new AccessError('برنامه یافت نشد.',404);}else{const r:any=await db.prepare('SELECT kind FROM records WHERE id=?').bind(link.id).first();if(!r||r.kind!==link.section||!can(u,r.kind,'read'))throw new AccessError('دسترسی پرونده ندارید.',404);}return {section:link.section,id:link.id};}
export const inboxClosed=(state:string)=>['completed','closed','cancelled'].includes(state);
export async function inboxState(thread:string,me:string){const row:any=await storage().prepare("SELECT data FROM flow_entities WHERE id=? AND type='inbox_state'").bind('inbox-state:'+thread+':'+me).first();return row?JSON.parse(row.data):{readRevision:0,snoozeUntil:''};}
export async function inboxView(t:any,savedState?:any){const state=savedState||await inboxState(t.id,t.me),d=t.data,needsReview=t.isSender&&d.state==='submitted',needsWork=d.kind==='request'&&t.isRecipient&&(!t.responsible||t.canWork)&&!inboxClosed(d.state)&&d.state!=='submitted',unread=state.readRevision<t.revision;
 return {id:t.id,revision:t.revision,created:t.created,updated:t.updated,...d,isSender:t.isSender,isRecipient:t.isRecipient,canWork:t.canWork,responsible:t.responsible,unread,snoozeUntil:state.snoozeUntil,needsReview,overdue:!!d.due&&Date.parse(d.due)<Date.now()&&!inboxClosed(d.state),needsAttention:(!state.snoozeUntil||Date.parse(state.snoozeUntil)<=Date.now())&&(unread||needsReview||needsWork)};}
export async function inboxList(u:Session){const me=await inboxIdentity(u),rows=(await storage().prepare("SELECT t.* FROM flow_entities t WHERE t.type='inbox_thread' AND (json_extract(t.data,'$.sender')=? OR (json_extract(t.data,'$.recipientType')='person' AND json_extract(t.data,'$.recipientId')=?) OR (json_extract(t.data,'$.recipientType')='position' AND EXISTS(SELECT 1 FROM flow_entities p,json_each(p.data,'$.members') m WHERE p.type='position' AND p.id=json_extract(t.data,'$.recipientId') AND json_extract(p.data,'$.active')=1 AND m.value=?))) ORDER BY t.updated DESC,t.id LIMIT 301").bind(me,me,me).all()).results;const positions=(await storage().prepare("SELECT id,data FROM flow_entities WHERE type='position' AND json_extract(data,'$.active')=1").all()).results as any[],active=(await storage().prepare("SELECT id FROM app_members WHERE status='active'").all()).results as any[],states=(await storage().prepare("SELECT id,data FROM flow_entities WHERE type='inbox_state' AND substr(id,-length(?))=?").bind(':'+me,':'+me).all()).results as any[],stateMap=new Map(states.map(r=>[r.id,JSON.parse(r.data)]));const threads=[];for(const row of rows.slice(0,300) as any[]){const t=inboxDecode(row),d=t.data,p=positions.find(p=>p.id===d.recipientId),recipients=d.recipientType==='person'?[d.recipientId]:(p?JSON.parse(p.data).members.filter((id:string)=>active.some(a=>a.id===id)):[]),responsible=d.recipientType==='person'?d.recipientId:recipients.includes(d.assignee)?d.assignee:'';threads.push(await inboxView({...t,me,isSender:d.sender===me,isRecipient:recipients.includes(me),responsible,canWork:recipients.includes(me)&&responsible===me},stateMap.get('inbox-state:'+t.id+':'+me)||{readRevision:0,snoozeUntil:''}));}return {threads,limited:rows.length>300};}
