import {distributionFields} from "./distribution";
import {validateBatchIdentity} from "./batch-number";
export type Kind="product"|"batch"|"device"|"event"|"service"|"action"|"distribution"|"firmware";
export type Row={id:string;kind:Kind;created:string;data:Record<string,string>};
export type Field={key:string;label:string;required?:boolean;type?:string;options?:string[];ref?:Kind};
export const names:Record<Kind,string>={product:"محصول",batch:"بچ قطعات",device:"دستگاه",event:"رویداد تولید و تحویل",service:"گزارش خدمات",action:"اقدام اصلاحی",distribution:"نماینده و مشتری",firmware:"نسخه‌های نرم‌افزار"};
export const fields:Record<Kind,Field[]>={
product:[{key:"code",label:"کد یکتای محصول",required:true},{key:"name",label:"نام محصول",required:true},{key:"group",label:"گروه محصول",required:true},{key:"model",label:"مدل محصول",required:true},{key:"warrantyMonths",label:"مدت گارانتی (ماه؛ صفر یعنی بدون گارانتی)",type:"number",required:true},{key:"status",label:"وضعیت محصول",options:["فعال","توقف تولید"],required:true},{key:"notes",label:"توضیحات",type:"textarea"}],
distribution:distributionFields,
firmware:[{key:"name",label:"نام نرم‌افزار",required:true},{key:"version",label:"شماره نسخه",required:true},{key:"deviceModel",label:"مدل دستگاه"},{key:"board",label:"نسخه / مدل برد"},{key:"notes",label:"توضیحات و تغییرات این نسخه",type:"textarea"}],
batch:[{key:"partCode",label:"کد ثابت قطعه / کد انبار (برای پیشنهاد بچ)"},{key:"part",label:"نام و مدل قطعه / ماده",required:true},{key:"date",label:"تاریخ ورود",type:"date",required:true},{key:"code",label:"کد یکتای بچ",required:true},{key:"manufacturerLot",label:"شماره لات سازنده (عین برچسب؛ در صورت وجود)"},{key:"supplier",label:"تأمین‌کننده",required:true},{key:"maker",label:"سازنده"},{key:"purchase",label:"شماره خرید در همکاران سیستم"},{key:"quantity",label:"مقدار ورودی",type:"number",required:true},{key:"unit",label:"واحد",options:["عدد","کیلوگرم","گرم","متر","سانتی‌متر","سانتی‌متر مربع","لیتر"],required:true},{key:"status",label:"کنترل ورودی",options:["در انتظار بررسی","تأیید","قرنطینه","رد"],required:true},{key:"test",label:"نتیجه آزمون ورودی",type:"textarea"},{key:"notes",label:"توضیحات و تفاوت با بچ قبلی",type:"textarea"}],
device:[{key:"product",label:"محصول",ref:"product",required:true},{key:"productName",label:"نام محصول هنگام ثبت",type:"snapshot"},{key:"productCode",label:"کد محصول هنگام ثبت",type:"snapshot"},{key:"warrantyMonths",label:"مدت گارانتی هنگام ثبت (ماه)",type:"snapshot"},{key:"code",label:"سریال یکتای دستگاه",required:true},{key:"model",label:"مدل دستگاه",required:true},{key:"design",label:"نسخه طراحی",required:true},{key:"firmware",label:"نسخه نرم‌افزار"},{key:"date",label:"تاریخ شروع تولید",type:"date",required:true}],
event:[{key:"device",label:"دستگاه",ref:"device",required:true},{key:"stage",label:"مرحله",options:["مصرف قطعه","مونتاژ","آزمون نهایی","بسته‌بندی","تحویل"],required:true},{key:"date",label:"تاریخ",type:"date",required:true},{key:"operator",label:"مسئول ثبت / اجرا",required:true},{key:"batch",label:"بچ قطعه (برای مصرف قطعه الزامی)",ref:"batch"},{key:"partSerial",label:"سریال قطعه (در صورت وجود)"},{key:"quantity",label:"مقدار مصرف",type:"number"},{key:"station",label:"ایستگاه / نسخه دستورالعمل"},{key:"result",label:"نتیجه آزمون",options:["تأیید","مردود","نیاز به دوباره‌کاری"]},{key:"purity",label:"خلوص اکسیژن (%)",type:"number"},{key:"flow",label:"دبی آزمون (L/min)",type:"number"},{key:"instrument",label:"شناسه ابزار اندازه‌گیری"},{key:"customer",label:"نماینده / مشتری (برای تحویل الزامی)"},{key:"notes",label:"جزئیات، اندازه‌گیری‌ها و توضیحات",type:"textarea"}],
service:[{key:"device",label:"دستگاه",ref:"device",required:true},{key:"date",label:"تاریخ گزارش",type:"date",required:true},{key:"hours",label:"ساعت کارکرد",type:"number",required:true},{key:"complaint",label:"شکایت مشتری",required:true},{key:"diagnosis",label:"عیب تأییدشده"},{key:"cause",label:"علت ریشه‌ای (در صورت احراز)"},{key:"batch",label:"بچ قطعه معیوب / خارج‌شده",ref:"batch"},{key:"replacement",label:"بچ قطعه جایگزین",ref:"batch"},{key:"replacementSerial",label:"سریال قطعه جایگزین"},{key:"operator",label:"کارشناس خدمات",required:true},{key:"cost",label:"هزینه خدمات (تومان)",type:"number"},{key:"status",label:"وضعیت",options:["باز","در حال بررسی","تعمیرشده","بسته‌شده"],required:true},{key:"notes",label:"اقدام تعمیر و نتیجه آزمون پس از تعمیر",type:"textarea"}],
action:[{key:"title",label:"موضوع مشکل",required:true},{key:"batch",label:"بچ مرتبط",ref:"batch"},{key:"device",label:"دستگاه مرتبط",ref:"device"},{key:"cause",label:"تحلیل علت ریشه‌ای",type:"textarea"},{key:"plan",label:"اقدام اصلاحی",type:"textarea",required:true},{key:"owner",label:"مسئول پیگیری",required:true},{key:"due",label:"مهلت اقدام",type:"date",required:true},{key:"status",label:"وضعیت",options:["باز","در حال اجرا","بررسی اثربخشی","بسته‌شده"],required:true},{key:"effectiveness",label:"شواهد بررسی اثربخشی",type:"textarea"}]};
export function validate(kind:Kind,d:Record<string,string>){
 if(!fields[kind])throw new Error("نوع رکورد معتبر نیست.");
 for(const f of fields[kind]){const v=d[f.key];if(f.required&&!v?.trim())throw new Error(f.label+" الزامی است.");if(v&&v.length>4000)throw new Error("متن بیش از حد طولانی است.");if(v&&f.options&&!f.options.includes(v))throw new Error(f.label+" معتبر نیست.");if(v&&f.type==="number"&&(!Number.isFinite(Number(v))||Number(v)<0))throw new Error(f.label+" باید عدد نامنفی باشد.");if(v&&f.type==="date"&&(!/^\d{4}-\d{2}-\d{2}$/.test(v)||Number.isNaN(Date.parse(v))))throw new Error("تاریخ معتبر نیست.");}
 if(kind==="product"&&(!/^[A-Z0-9][A-Z0-9._-]{0,79}$/.test(d.code)||!Number.isSafeInteger(Number(d.warrantyMonths))))throw new Error("کد محصول باید حداکثر ۸۰ نویسه و شامل حروف انگلیسی، عدد، نقطه، خط تیره یا زیرخط باشد؛ مدت گارانتی باید تعداد ماه صحیح باشد.");
 if(kind==="batch")validateBatchIdentity(d);
 if(kind==="batch"&&Number(d.quantity)<=0)throw new Error("مقدار ورودی باید مثبت باشد.");
 if(kind==="event"&&d.stage==="مصرف قطعه"&&(!d.batch||!d.quantity||Number(d.quantity)<=0))throw new Error("بچ و مقدار مثبت مصرف را وارد کنید.");
 if(kind==="event"&&d.stage==="تحویل"&&!d.customer?.trim())throw new Error("مقصد تحویل را وارد کنید.");
 if(kind==="event"&&d.stage==="آزمون نهایی"&&(!d.result||!d.notes?.trim()))throw new Error("نتیجه و جزئیات آزمون را ثبت کنید.");
 if(d.purity&&Number(d.purity)>100)throw new Error("خلوص نمی‌تواند بیش از ۱۰۰ درصد باشد.");
 if(kind==="action"&&d.status==="بسته‌شده"&&(!d.effectiveness?.trim()||!d.cause?.trim()))throw new Error("برای بستن اقدام، علت ریشه‌ای و شواهد اثربخشی لازم است.");
 if(kind==="service"&&d.replacement&&!d.batch)throw new Error("بچ قطعه خارج‌شده را مشخص کنید.");
}
export function label(r:Row){if(r.kind==="product")return r.data.code+" — "+r.data.name+" · "+r.data.model;if(r.kind==="firmware")return r.data.name+" — "+r.data.version;return r.data.code||r.data.title||r.data.complaint||r.data.stage||r.id;}

export const editable:Partial<Record<Kind,string[]>>={product:["name","group","model","warrantyMonths","status","notes"],batch:["status","test","notes"],service:["status","diagnosis","cause","notes","cost","operator"],action:["title","cause","plan","owner","due","status","effectiveness"]};

// Admin may correct batch business details with audit history; identifiers remain stable.
export const adminBatchEditable=[...editable.batch!,"part","supplier","maker","purchase","manufacturerLot","quantity","unit"];
