import {storage} from './storage';
import {hrRows,responsible} from './personnel';
import {leadMembers,leadMemberGuard} from './sales-leads';
import {notice,addDay,dayAt} from './duties';
import {trainingContext} from './training-context';
export async function syncPersonnelTasks(){if(trainingContext.getStore())return;const db=storage(),rows=await hrRows(),members=await leadMembers(),now=new Date().toISOString(),existing=(await db.prepare("SELECT * FROM duty_runs WHERE template_id='personnel'").all()).results as any[],wanted=new Set<string>();
 for(const r of rows)for(const mid of responsible(r,rows,members)){const id='personnel:'+r.id+':'+mid;wanted.add(id);const old=existing.find(t=>t.id===id),data={personnelWorkflow:true,recordId:r.id,sourceSection:'personnel',sourceId:r.id,title:'بررسی پرونده پرسنلی',instructions:'تصمیم و مدارک را در پرتال پرسنلی بررسی کنید.',evidence:'text',remindHours:24,escalateHours:48,stage:r.data.state,history:old?JSON.parse(old.data).history||[]:[]},due=(r.data.due||addDay(r.created.slice(0,10),2))+'T16:00:00+03:30';if(old&&old.state==='open'&&JSON.parse(old.data).stage===data.stage)continue;const op=crypto.randomUUID();await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'hr_task','{}','scheduler',?,CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) AND COALESCE((SELECT revision FROM duty_runs WHERE id=?),0)=? THEN 1 ELSE 0 END)").bind(op,now,r.id,r.revision,id,old?.revision||0),leadMemberGuard(db,op,members),old?db.prepare("UPDATE duty_runs SET state='open',data=?,due=?,revision=revision+1,updated=? WHERE id=?").bind(JSON.stringify(data),due,now,id):db.prepare("INSERT INTO duty_runs(id,template_id,period,assignee,supervisor,due,state,data,revision,created,updated) VALUES(?,'personnel',?,?,'@admin',?,'open',?,1,?,?)").bind(id,r.id,mid,due,JSON.stringify(data),now,now),notice(id,mid,'hr:'+r.revision,'درخواست پرسنلی منتظر بررسی شماست.',now)]);}
 for(const t of existing.filter(t=>!wanted.has(t.id)&&['open','blocked','submitted'].includes(t.state))){const r=rows.find(r=>r.id===JSON.parse(t.data).recordId),op=crypto.randomUUID();await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'hr_task_retire','{}','scheduler',?,CASE WHEN COALESCE((SELECT revision FROM flow_entities WHERE id=?),0)=? AND EXISTS(SELECT 1 FROM duty_runs WHERE id=? AND revision=?) THEN 1 ELSE 0 END)").bind(op,now,JSON.parse(t.data).recordId,r?.revision||0,t.id,t.revision),leadMemberGuard(db,op,members),db.prepare("UPDATE duty_runs SET state='completed',revision=revision+1,updated=? WHERE id=?").bind(now,t.id)]);}
}
