import {storage} from './storage';
import {AccessError} from './authorization';
import {trainingContext} from './training-context';
import {leadMembers,leadMemberGuard} from './sales-leads';
import {dayAt,addDay} from './duties';
import {sreq,stxt,sday,integer,money} from './sales';
import {personnelKinds,personnelModes,personnelRoles} from './personnel-contract';
import type {Session} from './permissions';
export const hrFail=(message:string,status=400):never=>{throw new AccessError(message,status)};
export const internal=(m:any)=>m?.status==='active'&&!['salesAgentId','serviceAgentId','hospitalCenterId'].some(k=>JSON.parse(m.permissions)[k]);
export async function hrRows(){return (await storage().prepare("SELECT * FROM flow_entities WHERE type GLOB 'hr_*' ORDER BY created,id").all()).results.map((r:any)=>({...r,data:JSON.parse(r.data)}));}
export async function hrActor(u:Session,members?:any[]){const ms=members||await leadMembers(),m=ms.find(m=>m.subject===u.userId||m.id===(u.userId.startsWith('local:')?u.userId.slice(6):u.userId));if(trainingContext.getStore()||u.permissions.salesAgentId||u.permissions.serviceAgentId||u.permissions.hospitalCenterId||!u.isAdmin&&!internal(m))hrFail('پرتال پرسنلی فقط برای کارکنان فعال شرکت است.',403);const roles=u.isAdmin?Object.keys(personnelRoles):JSON.parse(m.permissions).personnelRoles||[];return {id:m?.id||'',userId:u.userId,admin:u.isAdmin,roles,has:(r:string)=>roles.includes(r)};}
export type HrActor=Awaited<ReturnType<typeof hrActor>>;
export const findHr=(rows:any[],id:string,type?:string)=>{const r=rows.find(r=>r.id===id&&(!type||r.type===type));if(!r)hrFail('پرونده در دسترس نیست.',404);return r};
export function employee(rows:any[],id:string){return findHr(rows,id,'hr_employee');}
export function managerOf(rows:any[],memberId:string,ownerId:string,day=dayAt()){const e=rows.find(r=>r.type==='hr_employee'&&r.data.memberId===ownerId);if(!e||memberId===ownerId)return false;return e.data.managerId===memberId||rows.some(r=>r.type==='hr_delegate'&&r.data.managerId===e.data.managerId&&r.data.memberId===memberId&&r.data.start<=day&&r.data.end>=day);}
export const financialKinds=['loan','advance','profile','objection'];
export function hrVisible(r:any,a:HrActor,rows:any[]):boolean{const d=r.data,own=d.memberId===a.id;if(a.admin)return true;if(['hr_shift','hr_policy'].includes(r.type))return d.state==='published'||a.has('hr')||a.has('payroll')||a.has('approver');if(r.type==='hr_delegate')return d.managerId===a.id||own||a.has('hr');if(r.type==='hr_employee')return own||a.roles.length>0||managerOf(rows,a.id,d.memberId);if(r.type==='hr_assignment'||r.type==='hr_punch')return own||a.has('hr')||a.has('payroll')||managerOf(rows,a.id,d.memberId);if(r.type==='hr_period')return a.roles.length>0||d.memberIds.includes(a.id);if(r.type==='hr_request')return own||a.has('hr')||d.substituteId===a.id||(!financialKinds.includes(d.kind)&&managerOf(rows,a.id,d.memberId))||['loan','advance'].includes(d.kind)&&(a.has('finance')||a.has('treasury')||a.has('payroll'))||d.kind==='objection'&&a.has('payroll');if(r.type==='hr_ruling'||r.type==='hr_document')return own&&d.state==='published'||a.has('hr')||a.has('approver')||r.type==='hr_ruling'&&a.has('payroll');if(r.type==='hr_payroll')return own&&d.published||a.has('payroll')||a.has('approver')||['approved','payable','partial','paid','closed'].includes(d.state)&&(a.has('finance')||a.has('treasury'));if(r.type==='hr_file'){const parent=rows.find(x=>x.id===d.caseId);return !!parent&&hrVisible(parent,a,rows)}return false;}
export function presentHr(r:any,a:HrActor,rows:any[]){const d=r.data;if(r.type==='hr_employee'&&d.memberId!==a.id&&!a.has('hr')&&!a.has('payroll'))return {...r,data:{memberId:d.memberId,code:d.code,name:d.name,unit:d.unit,title:d.title,location:d.location,managerId:d.managerId,start:d.start,end:d.end,state:d.state}};if(r.type==='hr_period'&&!a.has('hr')&&!a.has('payroll')&&!a.has('approver'))return {...r,data:{title:d.title,start:d.start,end:d.end,deadline:d.deadline,state:d.state}};if(r.type==='hr_request'&&d.memberId!==a.id&&!a.has('hr')&&!a.has('payroll')&&!a.has('finance')&&!a.has('treasury'))return {...r,data:{...d,bankAccount:undefined,personal:undefined,amount:undefined,history:(d.history||[]).map((h:any)=>({at:h.at,mode:h.mode,name:h.name,state:h.state}))}};if(r.type==='hr_payroll'&&(a.has('finance')||a.has('treasury'))&&!a.has('payroll')&&!a.has('approver')&&d.memberId!==a.id)return {...r,data:{memberId:d.memberId,periodId:d.periodId,title:d.title,state:d.state,net:d.net,bankAccount:d.bankAccount,payments:d.payments,published:d.published}};if(r.type==='hr_file')return {...r,data:{caseId:d.caseId,filename:d.filename,byteSize:d.byteSize,sha256:d.sha256}};return r;}
export async function hrAccess(u:Session,id:string){const a=await hrActor(u),rows=await hrRows(),r=findHr(rows,id);if(!hrVisible(r,a,rows))hrFail('پرونده در دسترس نیست.',404);return {a,rows,r};}
export function range(start:unknown,end:unknown,max=366){const s=sday(start),e=sday(end);if(e<s||(Date.parse(e)-Date.parse(s))/86400000>=max)hrFail('بازه تاریخ معتبر نیست.');return {start:s,end:e};}
export function clock(v:unknown){const s=sreq(v,5);if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(s))hrFail('ساعت معتبر لازم است.');return s;}
export function timestamp(v:unknown){const s=sreq(v,40);if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2})?(Z|[+-]\d{2}:\d{2})$/.test(s)||!Number.isFinite(Date.parse(s)))hrFail('زمان با منطقه زمانی لازم است.');sday(s.slice(0,10));return new Date(s).toISOString();}
export function scheduled(rows:any[],mid:string,day:string){const assignments=rows.filter(r=>r.type==='hr_assignment'&&r.data.memberId===mid&&r.data.start<=day&&r.data.end>=day);if(assignments.length!==1)hrFail('برنامه کاری یکتا برای '+day+' لازم است.');let shiftId=assignments[0].data.shiftId;const changes=rows.filter(r=>r.type==='hr_request'&&r.data.memberId===mid&&r.data.kind==='shift'&&r.data.state==='approved'&&r.data.start<=day&&r.data.end>=day);if(changes.length)shiftId=changes[changes.length-1].data.shiftId;const d=findHr(rows,shiftId,'hr_shift').data;const working=d.weekdays.includes(new Date(day+'T12:00:00Z').getUTCDay())&&!d.holidays.includes(day);const start=Date.parse(day+'T'+d.startTime+':00+03:30'),end=Date.parse((d.endTime<=d.startTime?addDay(day,1):day)+'T'+d.endTime+':00+03:30');return {start,end,minutes:working?(end-start)/60000-d.breakMinutes:0,breakMinutes:d.breakMinutes,working,shiftId};}
export function shiftClock(day:string,time:string,s:{start:number}){let t=Date.parse(day+'T'+time+':00+03:30');if(t<s.start)t+=86400000;return t;}
export function leaveMinutes(rows:any[],mid:string,d:any){let total=0;for(let day=d.start;day<=d.end;day=addDay(day,1)){const s=scheduled(rows,mid,day);if(d.hourly){if(d.start!==d.end)hrFail('مرخصی ساعتی باید یک روز باشد.');const start=shiftClock(day,d.startTime,s),end=shiftClock(day,d.endTime,s);if(!s.working||start<s.start||end>s.end||end<=start)hrFail('بازه مرخصی داخل شیفت باشد.');total+=Math.min(s.minutes,(end-start)/60000);}else total+=s.minutes;}if(!total)hrFail('در این بازه ساعت کاری وجود ندارد.');return total;}
export function leaveBalance(rows:any[],mid:string,exclude=''){const e=rows.find(r=>r.type==='hr_employee'&&r.data.memberId===mid);return (e?.data.leaveMinutes||0)-rows.filter(r=>r.id!==exclude&&r.type==='hr_request'&&r.data.memberId===mid&&r.data.kind==='leave'&&r.data.leaveType==='annual'&&['manager','hr','approved'].includes(r.data.state)).reduce((n,r)=>n+r.data.minutes,0);}
export function assertUnlocked(rows:any[],mid:string,start:string,end:string){if(rows.some(r=>r.type==='hr_period'&&r.data.state!=='draft'&&r.data.start<=end&&r.data.end>=start&&r.data.memberIds.includes(mid)))hrFail('کارکرد این بازه قفل شده است؛ بازگشایی مجاز یا تعدیل دوره بعد لازم است.',409);}
export function workSummary(rows:any[],mid:string,start:string,end:string){const days:any[]=[];let expected=0,worked=0,credited=0,overtime=0,late=0,early=0;for(let day=start;day<=end;day=addDay(day,1)){const e=rows.find(r=>r.type==='hr_employee'&&r.data.memberId===mid);if(!e||day<e.data.start||e.data.end&&day>e.data.end)continue;const s=scheduled(rows,mid,day);const approved=rows.filter(r=>r.type==='hr_request'&&r.data.memberId===mid&&r.data.state==='approved'&&r.data.start<=day&&r.data.end>=day);const correction=approved.filter(r=>r.data.kind==='correction').at(-1);const punches=rows.filter(r=>r.type==='hr_punch'&&r.data.memberId===mid&&r.data.day===day).sort((a,b)=>a.data.at.localeCompare(b.data.at));let intervals:number[][]=[],inAt:number|null=null,incomplete=false;
 for(const p of punches){const t=Date.parse(p.data.at);if(p.data.direction==='in'){if(inAt!==null)incomplete=true;inAt=t;}else{if(inAt===null)incomplete=true;else{intervals.push([inAt,t]);inAt=null}}}if(inAt!==null)incomplete=true;if(correction){intervals=[[Date.parse(correction.data.inAt),Date.parse(correction.data.outAt)]];incomplete=false;}
 const overlap=(a:number,b:number)=>intervals.reduce((n,[i,o])=>n+Math.max(0,Math.min(o,b)-Math.max(i,a))/60000,0),inside=Math.max(0,overlap(s.start,s.end)-(intervals.length?s.breakMinutes:0)),actual=intervals.reduce((n,[i,o])=>n+(o-i)/60000,0),regular=Math.min(s.minutes,inside);
 let paid=0;for(const r of approved.filter(r=>r.data.kind==='mission'||r.data.kind==='leave'&&r.data.leaveType!=='unpaid')){if(r.data.hourly){const a=shiftClock(day,r.data.startTime,s),b=shiftClock(day,r.data.endTime,s);paid+=Math.max(0,(b-a)/60000-overlap(a,b));}else paid+=Math.max(0,s.minutes-regular);}
 const credit=Math.min(s.minutes,regular+paid);const approvedOT=approved.filter(r=>r.data.kind==='overtime').reduce((n,r)=>n+Math.max(0,overlap(Date.parse(r.data.inAt),Date.parse(r.data.outAt))-Math.max(0,(s.working?overlap(Math.max(s.start,Date.parse(r.data.inAt)),Math.min(s.end,Date.parse(r.data.outAt))):0))),0);
 const l=s.working&&intervals.length?Math.max(0,(intervals[0][0]-s.start)/60000):0,ear=s.working&&intervals.length?Math.max(0,(s.end-intervals.at(-1)![1])/60000):0;expected+=s.minutes;worked+=actual;overtime+=approvedOT;credited+=credit;late+=l;early+=ear;days.push({day,expected:s.minutes,worked:actual,credited:credit,overtime:approvedOT,late:l,early:ear,incomplete,shiftId:s.shiftId,correctionId:correction?.id||''});}
 return {days,expected,worked,credited,overtime,late,early,shortfall:Math.max(0,expected-credited),incomplete:days.filter(d=>d.incomplete).length};}
export function responsible(r:any,rows:any[],members:any[]){const d=r.data;let ids:string[]=[];if(r.type==='hr_request'&&d.state==='substitute')ids=[d.substituteId];else if(r.type==='hr_request'&&d.state==='manager'){const e=rows.find(x=>x.type==='hr_employee'&&x.data.memberId===d.memberId);if(e){const delegate=rows.find(x=>x.type==='hr_delegate'&&x.data.managerId===e.data.managerId&&x.data.start<=dayAt()&&x.data.end>=dayAt());ids=[delegate?.data.memberId||e.data.managerId]}}else{let role='';if(r.type==='hr_request')role=d.state==='hr'?'hr':d.state==='finance'?'finance':d.state==='payable'?'treasury':'';if(['hr_ruling','hr_document','hr_policy'].includes(r.type)&&d.state==='review')role='approver';if(r.type==='hr_payroll')role=d.state==='review'?'approver':d.state==='approved'?'finance':['payable','partial'].includes(d.state)?'treasury':'';if(role)ids=members.filter(internal).filter(m=>JSON.parse(m.permissions).personnelRoles?.includes(role)).map(m=>m.id)}return ids.filter(id=>id&&id!==d.memberId&&members.some(m=>m.id===id&&internal(m)&&(!['substitute','manager','hr','finance','review','approved'].includes(d.state)||d.createdBy!==m.subject&&d.createdBy!=='local:'+m.id)));}
// Sum rational daily shares exactly; round down once per earnings component, not once per day.
function fractionAdd(a:{n:bigint;d:bigint},n:bigint,d:bigint){const gcd=(x:bigint,y:bigint):bigint=>y===BigInt(0)?x:gcd(y,x%y);const numerator=a.n*d+n*a.d,denominator=a.d*d,g=gcd(numerator,denominator);return {n:numerator/g,d:denominator/g};}
export async function applyPersonnel(u:Session,b:any){
 const db=storage(),members=await leadMembers(),a=await hrActor(u,members),rows=await hrRows(),now=new Date().toISOString();
 if(b.confirmed!==true||!personnelModes.includes(b.mode)||! /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(b.id))hrFail('شناسه عملیات و تأیید صریح لازم است.');
 const signature=JSON.stringify(b),prior:any=await db.prepare('SELECT actor,payload FROM inventory_operations WHERE id=?').bind(b.id).first();if(prior){if(prior.actor!==u.userId||prior.payload!==signature)hrFail('شناسه عملیات تکراری با محتوای متفاوت است.',409);return {saved:true,id:b.recordId||b.id,repeated:true};}
 const id=b.recordId||b.id,old=rows.find(r=>r.id===id);if(old&&!hrVisible(old,a,rows))hrFail('پرونده در دسترس نیست.',404);if(!Number.isSafeInteger(b.revision)||b.revision!==(old?.revision||0))hrFail('نسخه تغییر کرده؛ تازه‌سازی کنید.',409);
 const note=sreq(b.notes,4000),mode=b.mode;let type=old?.type||'',d:any=old?structuredClone(old.data):{},changes:any[]=[];
 const role=(r:string)=>{if(!a.has(r))hrFail('دسترسی '+personnelRoles[r]+' لازم است.',403)};
 const member=(mid:string)=>{if(!members.some(m=>m.id===mid&&internal(m)))hrFail('کارمند فعال انتخاب کنید.');return mid};
 const emp=(mid:string)=>{const e=rows.find(r=>r.type==='hr_employee'&&r.data.memberId===mid);if(!e||e.data.state!=='active')hrFail('پرونده پرسنلی فعال لازم است.');return e};
 const isType=(t:string)=>{if(!old||type!==t)hrFail('نوع پرونده معتبر نیست.')};
 const independent=()=>{if(d.memberId===a.id||d.createdBy===u.userId)hrFail('تهیه‌کننده یا صاحب پرونده نمی‌تواند تأییدکننده باشد.',403)};
 const put=(r:any,data:any)=>changes.push({...r,data});
 const history=(prev:any,data:any)=>{if((prev?.history||[]).length>=500)hrFail('سقف تاریخچه پرونده پر شده است؛ پرونده جایگزین بسازید.');return ({...data,history:[...(prev?.history||[]),{at:now,actor:u.userId,name:u.name,mode,notes:note,state:data.state,...(mode==='employee'&&prev?{previous:{...prev,history:undefined}}:{})}]});};
 if(['employee','shift','assignment','delegate','policy','ruling','document','period','punch','request'].includes(mode)&&old&&mode!=='employee')hrFail('برای این عملیات رکورد تازه بسازید؛ سوابق پیشین حفظ می‌شوند.');
 if(mode==='employee'){
  role('hr');type='hr_employee';if(old&&old.type!==type)hrFail('نوع رکورد نامعتبر است.');const mid=member(sreq(b.memberId)),m=members.find(m=>m.id===mid);if(old&&old.data.memberId!==mid)hrFail('حساب متصل قابل تعویض نیست.');if(rows.some(r=>r.type===type&&r.id!==id&&(r.data.memberId===mid||r.data.code===b.code)))hrFail('حساب یا کد پرسنلی تکراری است.',409);
  const managerId=member(sreq(b.managerId));if(managerId===mid)hrFail('مدیر مستقیم باید شخص دیگری باشد.');let cursor=managerId;const seen=new Set([mid]);while(cursor){if(seen.has(cursor))hrFail('زنجیره مدیران حلقه دارد.');seen.add(cursor);cursor=rows.find(r=>r.type==='hr_employee'&&r.data.memberId===cursor)?.data.managerId||'';}
  const start=sday(b.start),end=b.end?sday(b.end):'';if(end&&end<start)hrFail('تاریخ پایان قبل از شروع است.');if(old&&(start!==d.start||end!==d.end))assertUnlocked(rows,mid,'0001-01-01','9999-12-31');const opening=integer(b.leaveMinutes,0,1000000);if(old&&opening<d.leaveMinutes-leaveBalance(rows,mid))hrFail('مانده پایه کمتر از مرخصی مصرف یا رزروشده است.');
  d={...d,memberId:mid,name:m.name,code:sreq(b.code,50),unit:sreq(b.unit,100),title:sreq(b.title,100),location:sreq(b.location,200),managerId,start,end,employment:sreq(b.employment,100),state:b.active===false?'disabled':'active',leaveMinutes:opening,bankAccount:stxt(b.bankAccount||'',100),personal:stxt(b.personal||'',2000)};
 }else if(mode==='shift'){
  role('hr');type='hr_shift';const startTime=clock(b.startTime),endTime=clock(b.endTime),mins=((Number(endTime.slice(0,2))*60+Number(endTime.slice(3)))-(Number(startTime.slice(0,2))*60+Number(startTime.slice(3)))+1440)%1440;const breakMinutes=integer(b.breakMinutes,0,480);if(!mins||breakMinutes>=mins)hrFail('طول شیفت معتبر نیست.');if(!Array.isArray(b.weekdays)||!b.weekdays.length||b.weekdays.some((n:any)=>!Number.isInteger(n)||n<0||n>6)||new Set(b.weekdays).size!==b.weekdays.length)hrFail('روزهای کاری معتبر لازم است.');if(!Array.isArray(b.holidays)||b.holidays.length>366)hrFail('تعطیلات معتبر لازم است.');d={title:sreq(b.title,200),startTime,endTime,breakMinutes,weekdays:b.weekdays,holidays:b.holidays.map(sday),state:'published'};
 }else if(mode==='assignment'){
  role('hr');type='hr_assignment';const mid=member(sreq(b.memberId));emp(mid);const dates=range(b.start,b.end);assertUnlocked(rows,mid,dates.start,dates.end);const shift=findHr(rows,sreq(b.shiftId),'hr_shift');if(rows.some(r=>r.type===type&&r.data.memberId===mid&&r.data.start<=dates.end&&r.data.end>=dates.start))hrFail('برنامه کاری با بازه موجود تداخل دارد.');d={memberId:mid,shiftId:shift.id,...dates,state:'published'};
 }else if(mode==='delegate'){
  const managerId=member(sreq(b.managerId));if(a.id!==managerId)role('hr');type='hr_delegate';const mid=member(sreq(b.memberId)),dates=range(b.start,b.end,93);if(mid===managerId)hrFail('جانشین باید متفاوت باشد.');if(rows.some(r=>r.type===type&&r.data.managerId===managerId&&r.data.start<=dates.end&&r.data.end>=dates.start))hrFail('جانشینی هم‌زمان ثبت شده است.');d={managerId,memberId:mid,...dates,state:'published'};
 }else if(mode==='policy'){
  role('payroll');type='hr_policy';d={title:sreq(b.title,200),state:'draft',insuranceBps:integer(b.insuranceBps,0,10000),taxBps:integer(b.taxBps,0,10000),taxExemption:money(b.taxExemption),insuranceCap:money(b.insuranceCap),notes:note};
 }else if(mode==='ruling'||mode==='document'){
  role('hr');type=mode==='ruling'?'hr_ruling':'hr_document';const mid=member(sreq(b.memberId));emp(mid);d={memberId:mid,title:sreq(b.title,200),text:sreq(b.text,12000),state:'draft',effective:sday(b.effective),acknowledgedAt:''};if(mode==='ruling'){assertUnlocked(rows,mid,d.effective,'9999-12-31');if(rows.some(r=>r.type===type&&r.data.memberId===mid&&r.data.effective===d.effective&&r.data.state!=='rejected'))hrFail('حکم با این تاریخ اثر وجود دارد.');d={...d,monthlyBase:money(b.monthlyBase),monthlyAllowance:money(b.monthlyAllowance),overtimeHourly:money(b.overtimeHourly),policyId:findHr(rows,sreq(b.policyId),'hr_policy').id};if(findHr(rows,d.policyId).data.state!=='published')hrFail('قواعد حقوق ابتدا باید تأیید و منتشر شوند.');}
 }else if(mode==='punch'){
  role('hr');type='hr_punch';const mid=member(sreq(b.memberId));emp(mid);const day=sday(b.day);assertUnlocked(rows,mid,day,day);const at=timestamp(b.at);if(Date.parse(at)>Date.now()||Date.parse(at)<Date.parse(day+'T00:00:00+03:30')||Date.parse(at)>=Date.parse(addDay(day,2)+'T00:00:00+03:30'))hrFail('زمان تردد نسبت به روز کاری معتبر نیست.');if(!['in','out'].includes(b.direction))hrFail('نوع تردد معتبر نیست.');const previous=rows.filter(r=>r.type===type&&r.data.memberId===mid).sort((x,y)=>x.data.at.localeCompare(y.data.at)).at(-1);if(previous&&(at<=previous.data.at||previous.data.direction===b.direction)||!previous&&b.direction!=='in')hrFail('ترتیب ورود و خروج معتبر نیست؛ برای سابقه قدیمی درخواست اصلاح ثبت کنید.');if(previous&&Date.parse(at)-Date.parse(previous.data.at)<60000)hrFail('تردد تکراری در فاصله کمتر از یک دقیقه.');d={memberId:mid,day,at,direction:b.direction,location:emp(mid).data.location,source:'manual',reference:sreq(b.reference,200),state:'published'};
 }else if(mode==='request'){
  type='hr_request';const mid=member(b.memberId||a.id);if(mid!==a.id)role('hr');const e=emp(mid);if(!Object.hasOwn(personnelKinds,b.kind))hrFail('نوع درخواست معتبر نیست.');d={memberId:mid,kind:b.kind,title:personnelKinds[b.kind],description:note,state:financialKinds.includes(b.kind)||b.kind==='certificate'?'hr':b.kind==='shift'&&b.substituteId?'substitute':'manager',due:addDay(dayAt(),2)};
  if(['leave','mission','correction','overtime','shift'].includes(b.kind)){
   Object.assign(d,range(b.start,b.end,93));assertUnlocked(rows,mid,d.start,d.end);if(d.start<e.data.start||e.data.end&&d.end>e.data.end)hrFail('درخواست خارج از دوره همکاری است.');
   if(['leave','mission'].includes(b.kind)){d.hourly=!!b.hourly;d.startTime=d.hourly?clock(b.startTime):'';d.endTime=d.hourly?clock(b.endTime):'';d.minutes=leaveMinutes(rows,mid,d);if(b.kind==='leave'){if(!['annual','sick','unpaid','special'].includes(b.leaveType))hrFail('نوع مرخصی لازم است.');d.leaveType=b.leaveType;if(d.leaveType==='annual'&&leaveBalance(rows,mid)<d.minutes)hrFail('مانده مرخصی کافی نیست.');}if(rows.some(r=>r.type===type&&r.data.memberId===mid&&['leave','mission'].includes(r.data.kind)&&!['rejected','cancelled'].includes(r.data.state)&&r.data.start<=d.end&&r.data.end>=d.start&&(!r.data.hourly||!d.hourly||r.data.startTime<d.endTime&&r.data.endTime>d.startTime)))hrFail('درخواست با مرخصی یا مأموریت قبلی تداخل دارد.');}
   if(['correction','overtime'].includes(b.kind)){if(d.start!==d.end)hrFail('اصلاح تردد و اضافه‌کاری برای یک روز ثبت شوند.');d.inAt=timestamp(b.inAt);d.outAt=timestamp(b.outAt);if(d.outAt<=d.inAt||Date.parse(d.outAt)-Date.parse(d.inAt)>86400000||Date.parse(d.inAt)<Date.parse(d.start+'T00:00:00+03:30')||Date.parse(d.outAt)>Date.parse(addDay(d.start,2)+'T00:00:00+03:30')||b.kind==='correction'&&Date.parse(d.outAt)>Date.now())hrFail('بازه ورود و خروج معتبر نیست.');if(rows.some(r=>r.type===type&&r.data.memberId===mid&&r.data.kind===b.kind&&r.data.start===d.start&&!['cancelled','rejected'].includes(r.data.state)))hrFail('درخواست همین روز موجود است؛ ابتدا تعیین تکلیف کنید.');}
   if(b.kind==='shift'){if(rows.some(r=>r.type==='hr_request'&&r.data.memberId===mid&&['leave','mission','correction','overtime'].includes(r.data.kind)&&!['rejected','cancelled'].includes(r.data.state)&&r.data.start<=d.end&&r.data.end>=d.start))hrFail('ابتدا درخواست‌های متداخل با تغییر شیفت را تعیین تکلیف یا لغو کنید.');d.shiftId=findHr(rows,sreq(b.shiftId),'hr_shift').id;if(b.substituteId){d.substituteId=member(b.substituteId);if(d.substituteId===mid)hrFail('همکار جایگزین متفاوت باشد.');}if(rows.some(r=>r.type===type&&r.data.memberId===mid&&r.data.kind==='shift'&&!['rejected','cancelled'].includes(r.data.state)&&r.data.start<=d.end&&r.data.end>=d.start))hrFail('درخواست تغییر شیفت هم‌پوشان وجود دارد.');}
  }
  if(b.kind==='objection'){const target=findHr(rows,sreq(b.targetId));if(!hrVisible(target,a,rows)||!(target.type==='hr_payroll'&&target.data.memberId===mid||target.type==='hr_period'&&target.data.memberIds.includes(mid)))hrFail('فیش یا دوره کارکرد خود فرد انتخاب شود.');d.targetId=target.id;d.periodId=target.type==='hr_period'?target.id:target.data.periodId;}
  if(b.kind==='profile'){d.bankAccount=stxt(b.bankAccount||'',100);d.personal=stxt(b.personal||'',2000);if(!d.bankAccount&&!d.personal)hrFail('اطلاعات جدید لازم است.');}
  if(['loan','advance'].includes(b.kind)){d.amount=money(b.amount,true);d.installments=integer(b.installments,1,60);d.repaymentStart=sday(b.repaymentStart);d.payments=[];d.recovered='0';}
  if(b.kind==='cancel'){const target=findHr(rows,sreq(b.targetId),'hr_request');if(target.data.memberId!==mid||target.data.state!=='approved'||!['leave','mission','overtime','shift','correction'].includes(target.data.kind))hrFail('فقط درخواست مصوب خود فرد قابل لغو است.');assertUnlocked(rows,mid,target.data.start,target.data.end);d.targetId=target.id;d.start=target.data.start;d.end=target.data.end;}
  if(!financialKinds.includes(b.kind)&&b.kind!=='certificate'&&!internal(members.find(m=>m.id===e.data.managerId)))hrFail('مدیر مستقیم فعال برای بررسی درخواست تعیین کنید.');
 }else if(mode==='reject'&&['hr_policy','hr_ruling','hr_document','hr_payroll'].includes(type)){role('approver');if(d.state!=='review')hrFail('پرونده در مرحله بررسی نیست.');independent();d.state='rejected';
 }else if(['approve','reject'].includes(mode)){
  isType('hr_request');if(!['substitute','manager','hr','finance'].includes(d.state))hrFail('درخواست در مرحله بررسی نیست.');if(d.memberId===a.id||d.createdBy===u.userId)hrFail('درخواست خودتان قابل تأیید یا رد نیست.',403);
  if(d.state==='substitute'){if(d.substituteId!==a.id)hrFail('تأیید همکار جایگزین لازم است.',403)}else if(d.state==='manager'){if(!managerOf(rows,a.id,d.memberId))hrFail('تأیید مدیر مستقیم یا جانشین لازم است.',403)}else role(d.state);
  if(mode==='reject')d.state='rejected';else if(d.state==='substitute')d.state='manager';else if(d.state==='manager')d.state='hr';else if(d.state==='finance')d.state='payable';else{
   if(d.start)assertUnlocked(rows,d.memberId,d.start,d.end);if(d.kind==='overtime'&&Date.parse(d.outAt)>Date.now())hrFail('تأیید نهایی اضافه‌کاری پس از پایان بازه انجام می‌شود.');if(d.kind==='shift'&&rows.some(r=>r.type==='hr_request'&&r.data.memberId===d.memberId&&['leave','mission','correction','overtime'].includes(r.data.kind)&&!['rejected','cancelled'].includes(r.data.state)&&r.data.start<=d.end&&r.data.end>=d.start))hrFail('درخواست جدید با تغییر شیفت تداخل دارد.');if(d.kind==='leave'&&d.leaveType==='annual'&&leaveBalance(rows,d.memberId,id)<d.minutes)hrFail('مانده مرخصی کافی نیست.');
   if(d.kind==='cancel'){const target=findHr(rows,d.targetId,'hr_request');if(target.data.state!=='approved')hrFail('درخواست اصلی تغییر کرده است.',409);if(target.data.kind==='shift'&&rows.some(r=>r.type==='hr_request'&&r.data.memberId===d.memberId&&['leave','mission','correction','overtime'].includes(r.data.kind)&&!['rejected','cancelled'].includes(r.data.state)&&r.data.start<=target.data.end&&r.data.end>=target.data.start))hrFail('لغو شیفت با درخواست‌های دیگر تداخل دارد.');put(target,history(target.data,{...target.data,state:'cancelled'}));}
   if(d.kind==='profile'){const e=emp(d.memberId);put(e,history(e.data,{...e.data,...(d.bankAccount?{bankAccount:d.bankAccount}:{}),...(d.personal?{personal:d.personal}:{})}));}
   d.state=['loan','advance'].includes(d.kind)?'finance':'approved';
  }d.due=addDay(dayAt(),2);
 }else if(mode==='withdraw'){
  isType('hr_request');if(a.id!==d.memberId||!['substitute','manager','hr'].includes(d.state))hrFail('فقط درخواست معطل خودتان قابل انصراف است.',403);d.state='cancelled';
 }else if(mode==='submit'){
  if(!['hr_ruling','hr_document','hr_policy'].includes(type)||d.state!=='draft')hrFail('پیش‌نویس معتبر لازم است.');role(type==='hr_policy'?'payroll':'hr');d.state='review';
 }else if(mode==='publish'){
  if(type==='hr_payroll'){role('approver');if(!['approved','payable','partial','paid','closed'].includes(d.state))hrFail('فیش هنوز تأیید نشده است.');d.published=true;d.publishedAt=now;}
  else{if(!['hr_ruling','hr_document','hr_policy'].includes(type)||d.state!=='review')hrFail('سند آماده تأیید نیست.');role('approver');independent();if(type==='hr_ruling')assertUnlocked(rows,d.memberId,d.effective,'9999-12-31');d.state='published';d.approvedBy=u.userId;d.publishedAt=now;}
 }else if(mode==='acknowledge'){
  if(!['hr_ruling','hr_document','hr_payroll'].includes(type)||d.memberId!==a.id||!(d.state==='published'||d.published))hrFail('سند منتشرشده خودتان لازم است.');d.acknowledgedAt=now;
 }else if(mode==='period'){
  role('hr');type='hr_period';const dates=range(b.start,b.end,32);if(!Array.isArray(b.memberIds)||!b.memberIds.length||b.memberIds.length>100||new Set(b.memberIds).size!==b.memberIds.length)hrFail('۱ تا ۱۰۰ کارمند یکتا انتخاب کنید.');for(const mid of b.memberIds){member(mid);emp(mid);if(rows.some(r=>r.type===type&&r.data.memberIds.includes(mid)&&r.data.start<=dates.end&&r.data.end>=dates.start))hrFail('دوره کارکرد هم‌پوشان وجود دارد.');workSummary(rows,mid,dates.start,dates.end);}const deadline=sday(b.deadline);if(deadline<dates.end)hrFail('مهلت اعتراض قبل از پایان دوره نباشد.');d={title:sreq(b.title,200),...dates,deadline,memberIds:b.memberIds,state:'draft'};
 }else if(mode==='close_work'){
  role('hr');isType('hr_period');if(d.state!=='draft'||d.end>=dayAt()||d.deadline>=dayAt())hrFail('پایان دوره و مهلت اعتراض باید گذشته باشد.');if(rows.some(r=>r.type==='hr_request'&&d.memberIds.includes(r.data.memberId)&&['manager','substitute','hr'].includes(r.data.state)&&(r.data.kind==='objection'?r.data.periodId===id:['leave','mission','correction','overtime','shift','cancel'].includes(r.data.kind)&&r.data.start<=d.end&&r.data.end>=d.start)))hrFail('درخواست‌های معطل این دوره را تعیین تکلیف کنید.');d.work={};for(const mid of d.memberIds){const w=workSummary(rows,mid,d.start,d.end);if(w.incomplete)hrFail('تردد ناقص برای '+emp(mid).data.name);d.work[mid]=w;}d.state='approved';d.closedWorkBy=u.userId;d.closedWorkAt=now;
 }else if(mode==='reopen_work'){
  role('approver');isType('hr_period');if(d.state!=='approved'||rows.some(r=>r.type==='hr_payroll'&&r.data.periodId===id))hrFail('پس از ایجاد فیش، اصلاح از مسیر تعدیل دوره بعد انجام می‌شود.');if(d.closedWorkBy===u.userId)hrFail('بازگشایی نیاز به تأیید فرد دیگر دارد.',403);d.state='draft';delete d.work;
 }else if(mode==='calculate'){
  role('payroll');isType('hr_period');if(d.state!=='approved')hrFail('کارکرد باید تأیید شده باشد.');if(rows.some(r=>r.type==='hr_payroll'&&r.data.periodId===id&&r.data.state!=='cancelled'))hrFail('حقوق دوره قبلاً محاسبه شده است.');if(!Array.isArray(b.adjustments||[])||(b.adjustments||[]).some((x:any)=>!d.memberIds.includes(x.memberId)))hrFail('تعدیلات باید برای افراد همین دوره باشد.');
  for(const mid of d.memberIds){const e=emp(mid),w=d.work[mid];let baseSum={n:BigInt(0),d:BigInt(1)},allowanceSum={n:BigInt(0),d:BigInt(1)},otSum={n:BigInt(0),d:BigInt(1)};const snapshots:any[]=[];let policyId='';const count=(Date.parse(d.end)-Date.parse(d.start))/86400000+1;
   for(const day of w.days){const ruling=rows.filter(r=>r.type==='hr_ruling'&&r.data.memberId===mid&&r.data.state==='published'&&r.data.effective<=day.day).sort((x,y)=>x.data.effective.localeCompare(y.data.effective)).at(-1);if(!ruling)hrFail('حکم معتبر برای '+e.data.name+' در '+day.day+' ثبت نشده است.');const rd=ruling.data;if(policyId&&policyId!==rd.policyId)hrFail('تغییر قواعد کسورات در میانه دوره؛ دوره را تفکیک کنید.');policyId=rd.policyId;const denominator=BigInt(count)*BigInt(Math.max(day.expected,1)),credit=BigInt(day.expected?Math.floor(day.credited):1);baseSum=fractionAdd(baseSum,BigInt(rd.monthlyBase)*credit,denominator);allowanceSum=fractionAdd(allowanceSum,BigInt(rd.monthlyAllowance)*credit,denominator);otSum=fractionAdd(otSum,BigInt(rd.overtimeHourly)*BigInt(Math.floor(day.overtime)),BigInt(60));if(!snapshots.some(r=>r.id===ruling.id))snapshots.push({id:ruling.id,revision:ruling.revision,data:rd});}
   const base=baseSum.n/baseSum.d,allowance=allowanceSum.n/allowanceSum.d,ot=otSum.n/otSum.d;const policy=findHr(rows,policyId,'hr_policy');if(policy.data.state!=='published')hrFail('قواعد مصوب لازم است.');const gross=base+allowance+ot,cap=BigInt(policy.data.insuranceCap),insurance=(cap>BigInt(0)&&gross>cap?cap:gross)*BigInt(policy.data.insuranceBps)/BigInt(10000),taxable=gross-insurance-BigInt(policy.data.taxExemption),tax=(taxable>BigInt(0)?taxable:BigInt(0))*BigInt(policy.data.taxBps)/BigInt(10000);
   const deductions:any[]=[];for(const loan of rows.filter(r=>r.type==='hr_request'&&r.data.memberId===mid&&['loan','advance'].includes(r.data.kind)&&r.data.state==='paid'&&r.data.repaymentStart<=d.end)){if(rows.some(r=>r.type==='hr_payroll'&&!['paid','closed','cancelled'].includes(r.data.state)&&r.data.loanDeductions?.some((l:any)=>l.id===loan.id)))hrFail('قسط وام در فیش تسویه‌نشده رزرو شده است.');const remain=BigInt(loan.data.amount)-BigInt(loan.data.recovered||'0'),installment=(BigInt(loan.data.amount)+BigInt(loan.data.installments)-BigInt(1))/BigInt(loan.data.installments);if(remain>BigInt(0))deductions.push({id:loan.id,amount:String(remain<installment?remain:installment)});}
   const deduction=deductions.reduce((n,l)=>n+BigInt(l.amount),BigInt(0)),adjustments=(b.adjustments||[]).filter((x:any)=>x.memberId===mid);let adjustment=BigInt(0);if(adjustments.length>20)hrFail('سقف تعدیلات رعایت شود.');const adj=adjustments.map((x:any)=>{if(!['earning','deduction'].includes(x.kind))hrFail('نوع تعدیل معتبر نیست.');const amount=money(x.amount,true);adjustment+=(x.kind==='earning'?BigInt(1):-BigInt(1))*BigInt(amount);return {kind:x.kind,amount,reason:sreq(x.reason,1000)}});const net=gross-insurance-tax-deduction+adjustment;if(net<BigInt(0))hrFail('خالص حقوق منفی است؛ اقساط یا تعدیلات را بررسی کنید.');const pid=crypto.randomUUID();changes.push({id:pid,type:'hr_payroll',revision:0,data:{memberId:mid,periodId:id,title:d.title,name:e.data.name,bankAccount:e.data.bankAccount,state:'review',createdBy:u.userId,work:w,rulings:snapshots,policy:{id:policy.id,revision:policy.revision,data:policy.data},base:String(base),allowance:String(allowance),overtime:String(ot),gross:String(gross),insurance:String(insurance),tax:String(tax),loanDeductions:deductions,adjustments:adj,net:String(net),payments:[],published:false,history:[{mode,at:now,actor:u.userId,name:u.name,notes:note}]}});
  }d.state='review';
 }else if(mode==='approve_payroll'){
  role('approver');isType('hr_payroll');if(d.state!=='review')hrFail('فیش در مرحله بررسی نیست.');independent();d.state='approved';d.approvedBy=u.userId;
 }else if(mode==='approve_payment'){
  role('finance');isType('hr_payroll');if(d.state!=='approved')hrFail('حقوق هنوز تأیید نشده است.');independent();d.state='payable';d.paymentApprovedBy=u.userId;
 }else if(mode==='pay'){
  role('treasury');if(!(type==='hr_payroll'||type==='hr_request'&&['loan','advance'].includes(d.kind))||!['payable','partial'].includes(d.state))hrFail('سند آماده پرداخت نیست.');if(d.memberId===a.id)hrFail('پرداخت به خود نیاز به خزانه‌دار دیگر دارد.',403);const amount=money(b.amount,BigInt(d.net||d.amount)>BigInt(0)),total=BigInt(d.net||d.amount),paid=d.payments.reduce((n:bigint,p:any)=>n+BigInt(p.amount),BigInt(0));if(paid+BigInt(amount)>total)hrFail('پرداخت بیشتر از مانده است.');const reference=sreq(b.reference,200);if(rows.some(r=>['hr_payroll','hr_request'].includes(r.type)&&r.data.payments?.some((p:any)=>p.reference===reference)))hrFail('مرجع پرداخت قبلاً ثبت شده است.');const day=sday(b.day);if(day>dayAt())hrFail('تاریخ پرداخت واقعی در آینده نیست.');d.payments=[...d.payments,{id:b.id,amount,day,reference,actor:u.userId,at:now}];d.state=paid+BigInt(amount)===total?'paid':'partial';if(d.state==='paid'&&type==='hr_payroll')for(const l of d.loanDeductions){const loan=findHr(rows,l.id,'hr_request');const recovered=BigInt(loan.data.recovered||'0')+BigInt(l.amount);if(recovered>BigInt(loan.data.amount))hrFail('مانده وام تغییر کرده است.',409);put(loan,history(loan.data,{...loan.data,recovered:String(recovered)}));}
 }else if(mode==='cancel_calculation'){
  role('approver');isType('hr_period');if(d.state!=='review')hrFail('فقط دوره محاسبه‌شده بازگشایی می‌شود.');const slips=rows.filter(r=>r.type==='hr_payroll'&&r.data.periodId===id&&r.data.state!=='cancelled');if(slips.some(r=>r.data.published||r.data.payments.length||['payable','partial','paid','closed'].includes(r.data.state)||r.data.createdBy===u.userId))hrFail('فیش منتشرشده، تأیید پرداخت یا پرداخت‌شده قابل ابطال نیست؛ تعدیل دوره بعد ثبت کنید.');for(const slip of slips)put(slip,history(slip.data,{...slip.data,state:'cancelled'}));d.state='draft';delete d.work;
 }else if(mode==='close_period'){
  role('approver');isType('hr_period');if(d.state!=='review')hrFail('دوره آماده بستن نیست.');const slips=rows.filter(r=>r.type==='hr_payroll'&&r.data.periodId===id&&r.data.state!=='cancelled');if(slips.length!==d.memberIds.length||slips.some(r=>r.data.state!=='paid'||!r.data.published))hrFail('همه فیش‌ها باید منتشر و پرداخت کامل شده باشند.');for(const slip of slips)put(slip,history(slip.data,{...slip.data,state:'closed'}));d.state='closed';
 }else hrFail('عملیات ناشناخته است.');
 if(!old){d.createdBy=u.userId;d.createdAt=now;}d=history(old?.data,d);changes.push({id,type,revision:old?.revision||0,data:d});
 await commitHr(u,b.id,signature,rows,members,changes,mode);return {saved:true,id};
}
export async function commitHr(u:Session,op:string,signature:string,rows:any[],members:any[],changes:any[],mode:string){const db=storage(),now=new Date().toISOString();await db.batch([db.prepare('INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,?,?,?,?,1)').bind(op,'personnel_'+mode,signature,u.userId,now),leadMemberGuard(db,op,members),db.prepare("UPDATE inventory_operations SET guard=CASE WHEN (SELECT COUNT(*) FROM flow_entities WHERE type GLOB 'hr_*')=? AND (SELECT COALESCE(SUM(revision),0) FROM flow_entities WHERE type GLOB 'hr_*')=? THEN guard ELSE 0 END WHERE id=?").bind(rows.length,rows.reduce((n,r)=>n+r.revision,0),op),...changes.map(r=>r.revision?db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=? AND type=? AND revision=?').bind(JSON.stringify(r.data),now,r.id,r.type,r.revision):db.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').bind(r.id,r.type,JSON.stringify(r.data),now,now)),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(op,u.userId,changes.at(-1)?.id||op,'personnel_'+mode,JSON.stringify(changes.map(r=>({id:r.id,type:r.type,revision:r.revision+1,state:r.data.state}))),now)]);}
