import {storage} from './storage';
import {AccessError} from './authorization';
import {memberId} from './duties';
import {apFinance,apVisible,apRead,apBuyer} from './purchase-payables';
import {leadMembers,leadMemberGuard} from './sales-leads';
import {qpermission,designMember} from './qms';
import {moneyMicro,moneyText} from './costing';
import {serviceSummary,serviceCosts,purchaseCompletion} from './purchase-fulfillment';
import {settleText as txt} from './purchase-settlement';
import {day} from './sourcing';
import {trainingContext} from './training-context';
export const serviceTypes="'purchase_service','purchase_payable','payable_file','purchase_order','receipt','purchase_settlement','cost_price','build_project','qms_record','qms_file'";
export const serviceFail=(m:string,s=400):never=>{throw new AccessError(m,s)};
export async function serviceRows(){return (await storage().prepare('SELECT * FROM flow_entities WHERE type IN ('+serviceTypes+') ORDER BY id').all()).results.map((r:any)=>({...r,data:JSON.parse(r.data)}));}
export async function serviceActor(u:any){const members=await leadMembers(),mid=await memberId(u),m=members.find(m=>m.id===mid);if(trainingContext.getStore()||u.permissions.salesAgentId||u.permissions.serviceAgentId||u.permissions.hospitalCenterId||(!u.isAdmin||m)&&!qpermission(m))serviceFail('کارمند فعال داخلی لازم است.',403);const effective=m?{...u,permissions:JSON.parse(m.permissions)}:u;return {mid,members,design:designMember(m),finance:apFinance(u)&&apFinance(effective),user:effective};}
export function serviceVisible(u:any,a:any,s:any,rows:any[]){const c=rows.find(r=>r.id===s.data.caseId&&r.type==='purchase_payable');return s.data.ownerId===a.mid||!!c&&apVisible(u,c);}
export function serviceBy(u:any,a:any,rows:any[],id:string){const s=rows.find(r=>r.type==='purchase_service'&&r.id===id);if(!s||!serviceVisible(u,a,s,rows))serviceFail('خدمت در دسترس نیست.',404);return s;}
export function serviceOutputAllowed(a:any,s:any){return s.data.design?a.design:s.data.ownerId===a.mid||a.finance;}
export async function getServices(u:any){const a=await serviceActor(u),rows=await serviceRows();u=a.user;const services=rows.filter(r=>r.type==='purchase_service'&&serviceVisible(u,a,r,rows)).map(s=>{const visible=serviceOutputAllowed(a,s),d={...s.data,delivery:visible?s.data.delivery:s.data.delivery?{submitted:true}:null,acceptance:visible?s.data.acceptance:s.data.acceptance?{at:s.data.acceptance.at,actor:s.data.acceptance.actor}:null,history:s.data.history.map((h:any)=>({mode:h.mode,at:h.at,actor:h.actor}))};return {...s,data:d,summary:serviceSummary(s,rows),canReceive:s.data.ownerId===a.mid&&(!s.data.design||a.design),files:visible?rows.filter(r=>r.type==='payable_file'&&r.data.serviceId===s.id).map(r=>({id:r.id,filename:r.data.filename})):[]};});
 const cases=rows.filter(r=>r.type==='purchase_payable'&&apVisible(u,r));return {accountId:u.userId,me:a.mid,finance:a.finance,services,cases:cases.map(c=>({id:c.id,title:c.data.title,supplier:c.data.supplier,revision:c.revision,completion:purchaseCompletion(c,rows)})),members:apRead(u)?a.members.filter(m=>qpermission(m)).map(m=>({id:m.id,name:m.name,design:designMember(m)})):[],targets:apRead(u)?rows.filter(r=>['receipt','build_project','qms_record'].includes(r.type)).filter(r=>r.type!=='receipt'||rows.some(o=>o.type==='purchase_order'&&o.id===r.data.purchaseOrderId&&apVisible(u,o))).map(r=>({id:r.id,kind:r.type==='receipt'?'receipt':r.type==='build_project'?'project':'qms',title:r.type==='qms_record'&&r.data.private&&!a.design?'پرونده محرمانه تحقیق‌وتوسعه':r.data.title||r.data.batchId||r.id})):[],qmsFiles:a.design?rows.filter(r=>r.type==='qms_file'&&r.data.state==='ready'&&rows.some(p=>p.id===r.data.parentId&&p.data.private)).map(r=>({id:r.id,parentId:r.data.parentId,filename:r.data.filename})):[],projectCosts:apFinance(u)?rows.filter(r=>['build_project','qms_record'].includes(r.type)).map(r=>({id:r.id,title:r.type==='qms_record'&&r.data.private&&!a.design?'پروژه محرمانه':r.data.title||r.id,items:serviceCosts(rows,r.type==='build_project'?'project':'qms',r.id)})).filter(p=>p.items.length):[]};}
export async function applyService(u:any,b:any){const a=await serviceActor(u),db=storage();u=a.user;if(b.confirmed!==true||typeof b.id!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(b.id))serviceFail('تأیید و شناسه عملیات معتبر لازم است.');const signature=JSON.stringify(b),prior:any=await db.prepare('SELECT payload,actor FROM inventory_operations WHERE id=?').bind(b.id).first();if(prior){if(prior.actor!==u.userId||prior.payload!==signature)serviceFail('شناسه تکراری متفاوت است.',409);return {saved:true,repeated:true,id:b.serviceId||b.id};}
 const rows=await serviceRows(),old=b.serviceId?serviceBy(u,a,rows,b.serviceId):null;if(b.revision!==(old?.revision||0))serviceFail('نسخه تغییر کرده؛ تازه‌سازی کنید.',409);const now=new Date().toISOString(),stamp={at:now,actor:u.userId},notes=txt(b.notes,4000),target=old?.id||b.id;let d:any=old?structuredClone(old.data):null;
 const finance=()=>{if(!a.finance)serviceFail('مجوز نوشتن مالی لازم است.',403);};const owner=()=>{if(d.ownerId!==a.mid||d.design&&!a.design)serviceFail('تأیید دریافت فقط با مسئول دریافت مجاز است.',403);};
 if(b.mode==='create'){const c=rows.find(r=>r.id===b.caseId&&r.type==='purchase_payable');if(!c||!apVisible(u,c)||!a.finance&&!apBuyer(u,c.data.route))serviceFail('پرونده خرید مجاز لازم است.',403);if(c.data.completion)serviceFail('ابتدا پرونده خرید را بازگشایی کنید.');const m=a.members.find(m=>m.id===b.ownerId);if(!qpermission(m)||b.design===true&&!designMember(m))serviceFail('مسئول فعال و مجاز دریافت انتخاب کنید.');const amount=moneyText(moneyMicro(b.amount));if(moneyMicro(amount)<=BigInt(0))serviceFail('مبلغ مثبت ریالی لازم است.');d={caseId:c.id,title:txt(b.title,200),expected:txt(b.expected,4000),amount,ownerId:m!.id,due:day(b.due),design:b.design===true,state:'open',costs:[],history:[],createdBy:u.userId};}
 else{if(!old)serviceFail('خدمت را ابتدا ثبت کنید.');const c=rows.find(r=>r.id===d.caseId);if(c?.data.completion)serviceFail('ابتدا پرونده خرید را بازگشایی کنید.');
 if(b.mode==='reassign'){finance();if(d.state==='accepted')serviceFail('دریافت تأییدشده قابل انتقال نیست.');const m=a.members.find(m=>m.id===b.ownerId);if(!qpermission(m)||d.design&&!designMember(m))serviceFail('مسئول فعال و مجاز لازم است.');d.ownerId=m!.id;d.due=day(b.due);}
 else if(b.mode==='deliver'){owner();if(!['open','returned'].includes(d.state))serviceFail('خدمت در انتظار خروجی نیست.');const f=rows.find(r=>r.id===b.fileId);if(d.design){const parent=rows.find(r=>r.id===f?.data.parentId&&r.type==='qms_record');if(f?.type!=='qms_file'||f.data.state!=='ready'||!parent?.data.private)serviceFail('فایل کامل در پرونده محرمانه تحقیق‌وتوسعه لازم است.');}else if(f?.type!=='payable_file'||f.data.serviceId!==target)serviceFail('فایل واقعی همین خدمت لازم است.');d.delivery={fileId:f!.id,kind:f!.type,notes,...stamp};d.state='submitted';}
 else if(b.mode==='accept'||b.mode==='return'){owner();if(d.state!=='submitted')serviceFail('خروجی ارسال‌شده لازم است.');d.state=b.mode==='accept'?'accepted':'returned';d.acceptance=b.mode==='accept'?{...stamp,notes}:null;}
 else if(b.mode==='reopen'){finance();if(d.costApproval)serviceFail('تخصیص هزینه را ابتدا برگشت دهید.');d.state='returned';d.acceptance=null;}
 else if(b.mode==='cost'){finance();if(d.state!=='accepted'||d.costApproval)serviceFail('خدمت تأیید دریافت‌شده بدون تخصیص نهایی لازم است.');if(!Array.isArray(b.costs)||!b.costs.length||b.costs.length>60)serviceFail('ردیف‌های تخصیص لازم است.');const keys=new Set<string>();d.costs=b.costs.map((x:any)=>{const t=rows.find(r=>r.id===x.targetId),type=({receipt:'receipt',project:'build_project',qms:'qms_record'} as any)[x.kind];if(!type||t?.type!==type||keys.has(x.kind+':'+x.targetId))serviceFail('مقصد هزینه معتبر و یکتا لازم است.');keys.add(x.kind+':'+x.targetId);if(x.kind==='project'&&t.data.state==='closed')serviceFail('ابتدا پروژه مقصد را برای هزینه جدید بازگشایی کنید.');if(x.kind==='receipt'&&!rows.some(o=>o.type==='purchase_order'&&o.id===t.data.purchaseOrderId&&apVisible(u,o)))serviceFail('دسترسی کالای مقصد لازم است.',403);const amount=moneyText(moneyMicro(x.amount));if(moneyMicro(amount)<=BigInt(0))serviceFail('سهم هزینه مثبت باشد.');return {kind:x.kind,targetId:x.targetId,amount};});if(d.costs.reduce((n:bigint,x:any)=>n+moneyMicro(x.amount),BigInt(0))!==moneyMicro(d.amount))serviceFail('جمع تخصیص باید دقیقاً برابر مبلغ خدمت باشد.');d.costApproval={...stamp,notes};}
 else if(b.mode==='undo_cost'){finance();if(!d.costApproval)serviceFail('تخصیص نهایی وجود ندارد.');if(rows.some(r=>r.type==='cost_price'&&r.data.serviceCosts?.some((x:any)=>x.serviceId===target)&&rows.some(st=>st.id===r.data.settlementId&&st.data.state==='approved')))serviceFail('هزینه در بهای بچ ثبت شده؛ ابتدا تسویه خرید را بازگشایی و سهم خدمت را از مسیر اصلاح مالی تعیین تکلیف کنید.');d.costApproval=null;d.costs=[];}
 else serviceFail('عملیات معتبر نیست.');}
 d.history.push({mode:b.mode,...stamp});const due=d.due+'T13:30:00.000Z',taskId='purchase-service:'+target;
 const snapshot={title:'دریافت خدمت: '+d.title,instructions:'خروجی واقعی خدمت را در بخش «تحویل خرید و خدمات» کارتابل بارگذاری و دریافت را تأیید کنید. پرداخت به معنی تحویل نیست.',sourceSection:'tasks',purchaseServiceWorkflow:true,serviceId:target,ownerId:d.ownerId,design:d.design,evidence:'مدرک واقعی تحویل خدمت',history:[]};
 const lock=db.prepare('UPDATE inventory_operations SET guard=CASE WHEN (SELECT COALESCE(SUM(revision),0) FROM flow_entities WHERE type IN ('+serviceTypes+'))=? THEN guard ELSE 0 END WHERE id=?').bind(rows.reduce((n,r)=>n+r.revision,0),b.id);
 await db.batch([db.prepare('INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,?,?,?,?,1)').bind(b.id,'purchase_service_'+b.mode,signature,u.userId,now),lock,leadMemberGuard(db,b.id,a.members),old?db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=? AND revision=?').bind(JSON.stringify(d),now,target,old.revision):db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,'purchase_service',?,1,?,?)").bind(target,JSON.stringify(d),now,now),db.prepare("INSERT INTO duty_runs(id,template_id,period,assignee,supervisor,due,state,data,revision,created,updated) VALUES(?,?,?,?,NULL,?,?,?,1,?,?) ON CONFLICT(id) DO UPDATE SET assignee=excluded.assignee,due=excluded.due,state=excluded.state,data=excluded.data,revision=duty_runs.revision+1,updated=excluded.updated").bind(taskId,'purchase-service:'+target,target,d.ownerId,due,d.state==='accepted'?'completed':d.state==='submitted'?'submitted':'open',JSON.stringify(snapshot),now,now),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,target,'purchase_service_'+b.mode,JSON.stringify({state:d.state,ownerId:d.ownerId,costs:d.costs,notes:b.mode==='deliver'||b.mode==='accept'?undefined:notes}),now)]);return {saved:true,id:target};}
// Derived financial follow-ups: refreshed with the task inbox, never by the read-only guidance handler.
export async function syncServiceFinanceTasks(){const rows=await serviceRows(),members=await leadMembers(),db=storage(),now=new Date().toISOString(),services=rows.filter(r=>r.type==='purchase_service'),existing=(await db.prepare("SELECT id,state,assignee,data FROM duty_runs WHERE template_id='purchase-service-finance'").all()).results as any[],writes:any[]=[],seen=new Set<string>();
 for(const s of services){const v=serviceSummary(s,rows);if(v.complete)continue;for(const m of members.filter(m=>qpermission(m)&&apFinance({isAdmin:false,permissions:JSON.parse(m.permissions)}))){const id='purchase-service-finance:'+s.id+':'+m.id;seen.add(id);const data=JSON.stringify({title:'پیگیری مالی خدمت: '+s.data.title,instructions:v.blockers.join(' / ')+'؛ در تحویل خرید و خدمات کارتابل، وضعیت واقعی را بررسی کنید. تأیید دریافت فقط با مسئول دریافت است.',sourceSection:'tasks',purchaseServiceWorkflow:true,serviceId:s.id,workflowRole:'finance',design:false,evidence:'تخصیص هزینه و اسناد مالی',history:[]});const old=existing.find(t=>t.id===id);if(old?.data===data&&old.state==='open')continue;writes.push(db.prepare("INSERT INTO duty_runs(id,template_id,period,assignee,supervisor,due,state,data,revision,created,updated) VALUES(?,'purchase-service-finance',?,?,NULL,?,'open',?,1,?,?) ON CONFLICT(id) DO UPDATE SET state='open',data=excluded.data,revision=duty_runs.revision+1,updated=excluded.updated").bind(id,s.id,m.id,s.data.due+'T13:30:00.000Z',data,now,now));}}
 for(const old of existing)if(!seen.has(old.id)&&!['completed','cancelled'].includes(old.state))writes.push(db.prepare("UPDATE duty_runs SET state='completed',revision=revision+1,updated=? WHERE id=?").bind(now,old.id));
 if(writes.length){const id=crypto.randomUUID();await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'purchase_service_followup','{}','scheduler',?,1)").bind(id,now),db.prepare('UPDATE inventory_operations SET guard=CASE WHEN (SELECT COALESCE(SUM(revision),0) FROM flow_entities WHERE type IN ('+serviceTypes+'))=? THEN guard ELSE 0 END WHERE id=?').bind(rows.reduce((n,r)=>n+r.revision,0),id),leadMemberGuard(db,id,members),...writes]);}}
