import {moneyMicro,moneyText} from './costing';
const active=(a:any[]=[])=>a.filter(x=>!x.voided);
export const serviceStates:Record<string,string>={open:'منتظر تحویل',submitted:'خروجی ارائه‌شده؛ منتظر تأیید دریافت',returned:'نیازمند اصلاح خروجی',accepted:'دریافت خدمت تأییدشده'};
export function serviceCosts(rows:any[],kind:string,targetId:string){return rows.filter(r=>r.type==='purchase_service'&&r.data.state==='accepted'&&r.data.costApproval).flatMap(r=>(r.data.costs||[]).filter((a:any)=>a.kind===kind&&a.targetId===targetId).map((a:any)=>({serviceId:r.id,caseId:r.data.caseId,title:r.data.title,amount:a.amount,approval:r.data.costApproval.at,key:r.id+':'+kind+':'+targetId})));}
export function serviceSummary(s:any,rows:any[]){const c=rows.find(r=>r.id===s.data.caseId&&r.type==='purchase_payable'),invoices=active(c?.data.invoices).filter((i:any)=>i.lines.some((l:any)=>l.serviceId===s.id));const billed=invoices.reduce((n:bigint,i:any)=>n+moneyMicro(i.amount),BigInt(0)),allocatedPaid=active(c?.data.allocations).filter((a:any)=>invoices.some((i:any)=>i.id===a.invoiceId)).reduce((n:bigint,a:any)=>n+moneyMicro(a.amount),BigInt(0));
 const unallocated=active(c?.data.payments).filter((p:any)=>p.serviceId===s.id||active(c?.data.advances).some((a:any)=>a.id===p.advanceId&&a.serviceId===s.id)).reduce((n:bigint,p:any)=>n+moneyMicro(p.amount)-active(c?.data.allocations).filter((a:any)=>a.paymentId===p.id).reduce((v:bigint,a:any)=>v+moneyMicro(a.amount),BigInt(0)),BigInt(0)),paid=allocatedPaid+unallocated;
 const costIssues=(s.data.costs||[]).flatMap((a:any)=>{const target=rows.find(r=>r.id===a.targetId);if(!target)return ['مقصد هزینه در دسترس نیست'];if(a.kind==='receipt'){const price=rows.find(r=>r.type==='cost_price'&&r.data.batchId===target.data.batchId);if(target.data.state!=='stored'||!price?.data.serviceCosts?.some((x:any)=>x.serviceId===s.id&&x.amount===a.amount&&x.approval===s.data.costApproval?.at))return ['دریافت کالا یا ثبت سهم خدمت در بهای بچ کامل نیست'];}return [];});
 const blockers=[...(s.data.state!=='accepted'?['دریافت خدمت تأیید نشده']:[]),...(!s.data.costApproval?['تخصیص هزینه تأیید نشده']:[]),...(billed!==moneyMicro(s.data.amount)?['فاکتورهای خدمت با مبلغ تعهد برابر نیست']:[]),...(allocatedPaid!==billed||!billed||unallocated>BigInt(0)?['تسویه مالی خدمت کامل نیست']:[]),...costIssues];
 return {unallocated:moneyText(unallocated),allocatedPaid:moneyText(allocatedPaid),billed:moneyText(billed),paid:moneyText(paid),remaining:moneyText(moneyMicro(s.data.amount)-paid),delivery:serviceStates[s.data.state],cost:s.data.costApproval?'تخصیص تأییدشده':'تخصیص ناقص',blockers:[...new Set(blockers)],complete:!blockers.length,overdue:s.data.state!=='accepted'&&s.data.due<new Date().toISOString().slice(0,10)};}
export function purchaseCompletion(c:any,rows:any[]){const d=c.data,delivery:string[]=[],cost:string[]=[],financial:string[]=[];const invoices=active(d.invoices),payments=active(d.payments),allocations=active(d.allocations);
 if(!invoices.length){financial.push('فاکتور خرید ثبت نشده');if(!rows.some(r=>r.type==='purchase_service'&&r.data.caseId===c.id)){delivery.push('کالا یا خدمت مرتبط با پرداخت هنوز مشخص نشده');cost.push('مقصد هزینه هنوز مشخص نشده');}}
 for(const i of invoices){const paid=allocations.filter((a:any)=>a.invoiceId===i.id).reduce((n:bigint,a:any)=>n+moneyMicro(a.amount),BigInt(0));if(!i.recognition||paid!==moneyMicro(i.amount))financial.push('بدهی یا تسویه فاکتور '+i.reference+' کامل نیست');
 for(const l of i.lines){if(l.serviceId){const s=rows.find(r=>r.id===l.serviceId&&r.type==='purchase_service');if(!s||s.data.state!=='accepted')delivery.push('خدمت فاکتور '+i.reference+' تأیید دریافت ندارد');if(!s?.data.costApproval)cost.push('تخصیص هزینه خدمت '+i.reference+' کامل نیست');continue;}
 const rs=l.receiptIds.map((id:string)=>rows.find(r=>r.id===id&&r.type==='receipt'));const accepted=rs.reduce((n:number,r:any)=>n+(r?.data.accepted||0),0);if(!rs.length||rs.some((r:any)=>!r||r.data.state!=='stored')||accepted!==l.quantity||rs.some((r:any)=>r.data.rejected))delivery.push('تعداد / کیفیت / جانمایی فاکتور '+i.reference+' کامل نیست');
 for(const r of rs.filter(Boolean)){const st=rows.find(x=>x.type==='purchase_settlement'&&x.data.state==='approved'&&x.data.lines.some((v:any)=>v.receiptId===r.id));const priced=rows.find(x=>x.type==='cost_price'&&x.data.batchId===r.data.batchId);if(!st||priced?.data.settlementId!==st.id||priced?.data.settlementRevision!==st.revision||st.data.approvals?.at(-1)?.preview?.lines.find((x:any)=>x.receiptId===r.id)?.receiptRevision!==r.revision)cost.push('بهای نهایی بچ '+r.id+' تأیید نشده یا نیازمند بازبینی است');}
 }}
 for(const p of payments)if(allocations.filter((a:any)=>a.paymentId===p.id).reduce((n:bigint,a:any)=>n+moneyMicro(a.amount),BigInt(0))!==moneyMicro(p.amount))financial.push('پرداخت تخصیص‌نیافته: '+p.reference);
 if(active(d.advances).some((a:any)=>!a.closed))financial.push('برنامه پیش‌پرداخت باز است');
 if(active(d.issues).some((a:any)=>a.state!=='resolved'))delivery.push('نقص باز وجود دارد');
 const services=rows.filter(r=>r.type==='purchase_service'&&r.data.caseId===c.id);for(const s of services){if(s.data.state!=='accepted')delivery.push('دریافت خدمت '+s.data.title+' تأیید نشده');const v=serviceSummary(s,rows);if(!v.complete)cost.push(...v.blockers.map(b=>s.data.title+': '+b));}
 const receiptIds=new Set(invoices.flatMap((i:any)=>i.lines.flatMap((l:any)=>l.receiptIds||[])));for(const s of rows.filter(r=>r.type==='purchase_service'&&(r.data.costs||[]).some((a:any)=>a.kind==='receipt'&&receiptIds.has(a.targetId)))){const v=serviceSummary(s,rows);if(!v.complete)cost.push('خدمت وابسته '+s.data.title+': '+v.blockers.join(' / '));}
 const blockers=[...new Set([...delivery,...cost,...financial])];return {delivery:[...new Set(delivery)],cost:[...new Set(cost)],financial:[...new Set(financial)],blockers,ready:!blockers.length,closed:!!d.completion&&!blockers.length,stale:!!d.completion&&!!blockers.length};}
