export type QField={key:string;label:string;type:'text'|'number'|'date'|'choice'|'boolean';required?:boolean;options?:string[]};
export const qmsRoles:Record<string,string>={qa:'مدیر تضمین کیفیت',documents:'کارشناس تضمین کیفیت و کنترل مدارک',qc:'مسئول کنترل کیفیت',regulatory:'کارشناس مجوزها',technical:'مسئول فنی',calibration:'مسئول تجهیزات آزمون',auditor:'ممیز داخلی',observer:'ممیز بیرونی — فقط مشاهده'};
const f=(key:string,label:string,type:QField['type']='text',required=true):QField=>({key,label,type,required});
export const qmsKinds:Record<string,{title:string;roles:string[];private?:boolean;product?:boolean;fields:QField[]}>={
 document:{title:'مدارک و روش‌های اجرایی',roles:['qa','documents'],fields:[f('code','کد مدرک'),f('scope','دامنه کاربرد'),f('procedure','شرح روش اجرایی'),f('effective','تاریخ اجرا','date'),f('reviewDate','بازنگری بعدی','date')]},
 permit:{title:'مجوزها و گواهینامه‌ها',roles:['qa','regulatory','technical'],fields:[f('issuer','مرجع صادرکننده'),f('scope','دامنه / مدل‌های تحت پوشش'),f('requirements','الزامات و مدارک مورد نیاز'),f('missing','مدارک ناقص / نتیجه بررسی'),f('correspondence','شماره پیگیری و مکاتبات'),f('expires','تاریخ انقضا','date')]},
 audit:{title:'ممیزی داخلی و بیرونی',roles:['qa','auditor'],fields:[f('scope','نوع ممیزی و دامنه'),f('criteria','استاندارد / بندها و چک‌لیست'),f('evidence','شواهد مشاهده‌شده'),f('findings','یافته‌ها و عدم انطباق‌ها'),f('response','پاسخ و برنامه پیگیری')]},
 capa:{title:'عدم انطباق و اقدام اصلاحی',roles:['qa','qc','technical'],fields:[f('source','منشأ و شرح عدم انطباق'),f('containment','مهار فوری و تعیین تکلیف'),f('rootCause','تحلیل علت ریشه‌ای'),f('actions','اقدام، مسئول و زمان‌بندی'),f('criteria','معیار سنجش اثربخشی'),f('effectivenessDate','موعد بررسی اثربخشی','date')]},
 design:{title:'طراحی و توسعه محصول',roles:[],private:true,product:true,fields:[f('inputs','ورودی‌ها و الزامات طراحی'),f('outputs','خروجی‌ها و مشخصات طراحی'),f('review','بازنگری طراحی'),f('verification','تصدیق و شواهد آزمون'),f('validation','صحه‌گذاری کاربرد موردنظر'),f('transfer','انتقال به تولید و پذیرش')]},
 change:{title:'تغییر مهندسی',roles:[],private:true,product:true,fields:[f('baseline','نسخه مبنا / BOM / نرم‌افزار'),f('change','شرح تغییر و علت'),f('impact','اثر بر ریسک، موجودی و دستگاه‌های قبلی'),f('regulatory','اثر بر مجوزها و الزامات'),f('verification','آزمون و شواهد'),f('effective','نقطه اجرای تغییر / سریال یا بچ')]},
 risk:{title:'پرونده ریسک محصول',roles:[],private:true,product:true,fields:[f('hazards','خطر، توالی رخداد و پیامد'),f('initial','ارزیابی اولیه و مبنای پذیرش'),f('controls','کنترل‌های ریسک'),f('evidence','اثبات اجرای کنترل و اثربخشی'),f('residual','ریسک باقیمانده و تصمیم پذیرش'),f('review','بازنگری بر اساس شکایت و تغییر')]},
 calibration:{title:'تجهیزات آزمون و کالیبراسیون',roles:['qa','calibration'],fields:[f('equipment','کد / سریال تجهیز'),f('range','دامنه و دقت / کاربرد مجاز'),f('certificate','شماره گواهی و آزمایشگاه'),f('result','نتیجه و وضعیت تجهیز'),f('expires','موعد کالیبراسیون','date'),f('impact','بررسی نتایج قبلی در صورت خروج از حدود')]},
 release:{title:'آزادسازی محصول',roles:['qa','qc'],product:true,fields:[f('serials','سریال‌ها (هر خط یک سریال)'),f('tests','آزمون‌ها و مدارک الزامی'),f('disposition','تعیین تکلیف عدم انطباق‌ها'),f('equipment','تجهیزات آزمون و اعتبار کالیبراسیون'),f('evidence','جمع‌بندی شواهد آزادسازی')]},
 complaint:{title:'شکایت، پایش و اقدام میدانی',roles:['qa','technical','regulatory'],product:true,fields:[f('service','شناسه پرونده خدمات / شکایت'),f('incident','شرح رخداد و تکرار خرابی'),f('affected','سریال‌ها و دامنه محصولات متأثر'),f('risk','ارزیابی ریسک و فوریت'),f('action','اقدام میدانی / فراخوان / اطلاع‌رسانی'),f('followup','نتیجه پیگیری و تعیین تکلیف')]},
 training:{title:'آموزش و صلاحیت',roles:['qa','documents','technical'],fields:[f('attendees','افراد و وظایف موردنیاز'),f('document','مدرک و نسخه مورد آموزش'),f('assessment','روش ارزیابی و نتیجه'),f('competence','وظایف مجاز و محدودیت‌ها'),f('expires','موعد بازآموزی','date')]},
 management:{title:'بازنگری مدیریت',roles:['qa'],fields:[f('inputs','شاخص‌ها، شکایات، ممیزی و عملکرد'),f('decisions','تصمیمات مدیریت'),f('resources','منابع موردنیاز'),f('actions','اقدام‌ها، مسئول‌ها و زمان‌بندی'),f('followup','پیگیری تصمیمات قبلی')]},
 software:{title:'اعتبارسنجی نرم‌افزار',roles:['qa','technical'],fields:[f('version','نام سامانه و نسخه'),f('intended','کاربرد موردنظر و ریسک'),f('requirements','الزامات و معیارهای پذیرش'),f('protocol','پروتکل و سناریوهای آزمون'),f('results','نتایج واقعی و شواهد'),f('deviations','انحرافات و تعیین تکلیف')]},
 form:{title:'فرم‌ساز محصول',roles:['qa','documents'],product:true,fields:[f('purpose','هدف و راهنمای تکمیل')]},
 response:{title:'فرم‌های تکمیل‌شده',roles:['qa','documents','qc','technical'],product:true,fields:[]},
};
export const qmsStates:Record<string,string>={draft:'پیش‌نویس',review:'در انتظار بررسی',approved:'تأییدشده',closed:'بسته‌شده با تأیید اثربخشی',superseded:'نسخه پیشین',hold:'توقف / قرنطینه'};
export const qmsModes=['save','submit','approve','return','close','revise','acknowledge','hold','install_positions'];
export const qmsHelp=['هر محصول پرونده، فرم‌های نام‌دار و پیوست‌های مستقل دارد. فرم منتشرشده تغییر نمی‌کند؛ بازنگری، نسخه جدید می‌سازد.','طراحی، تغییر مهندسی و ریسک محصول همیشه محرمانه‌اند؛ صرفاً حساب فعال با نقش صریح تحقیق‌وتوسعه یا مدیرعامل دسترسی دارد. مدیر سامانه به‌تنهایی مجاز نیست.','تأیید باید توسط بررسی‌کننده تعیین‌شده و مستقل از سازنده و ویرایش‌کنندگان انجام شود. CAPA و شکایت برای بسته‌شدن نیاز به مدرک اثربخشی دارند.','فایل‌ها خصوصی و به قطعه‌های ۸ مگابایتی بارگذاری می‌شوند؛ سهمیه کل تجاری تعیین نشده است. ظرفیت و هزینه واقعی مخزن و اتصال همچنان محدودیت فنی دارند. پس از قطع، همان فایل را دوباره انتخاب کنید.','مدرک ناقص یا پیش‌نویس به معنی تأیید قانونی نیست. مرجع مجوز، بندهای استاندارد و موعدها باید مطابق مدارک واقعی ثبت شوند.','برای فعال‌کردن کنترل آزادسازی، یک پرونده آزادسازی برای محصول ثبت کنید. پس از آن ارسال هر سریال آن محصول نیاز به آزادسازی مصوب دارد.'];
export const QMS_PART_SIZE=8*1024*1024;

export const qmsPositions:Record<string,{name:string;unit:string;responsibilities:string;reportingTo:string}>={
 qa:{name:'مدیر تضمین کیفیت و نماینده مدیریت',unit:'تضمین کیفیت',responsibilities:'مدیریت نظام کیفیت، ممیزی، کنترل مدارک، CAPA و بازنگری مدیریت؛ اختیار توقف و آزادسازی نهایی محصول بر اساس شواهد.',reportingTo:'مدیرعامل'},
 documents:{name:'کارشناس تضمین کیفیت و کنترل مدارک',unit:'تضمین کیفیت',responsibilities:'کنترل نسخه و توزیع روش‌ها و فرم‌ها، بایگانی شواهد، پیگیری آموزش و موعد اقدام‌ها.',reportingTo:'مدیر تضمین کیفیت'},
 qc:{name:'مسئول کنترل کیفیت',unit:'کنترل کیفیت',responsibilities:'کنترل ورودی، حین تولید و نهایی؛ ثبت نتایج و قرنطینه؛ آماده‌سازی مدارک آزادسازی برای تأیید مستقل.',reportingTo:'مدیر تضمین کیفیت'},
 inspector:{name:'بازرس کنترل کیفیت ورودی، حین تولید و نهایی',unit:'کنترل کیفیت',responsibilities:'اجرای آزمون طبق نسخه معتبر دستورالعمل، ردیابی سریال و تجهیزات، ثبت نتیجه واقعی و گزارش مغایرت.',reportingTo:'مسئول کنترل کیفیت'},
 regulatory:{name:'کارشناس امور مجوزها',unit:'فنی و مجوزها',responsibilities:'تکمیل پرونده مجوز محصول و گواهینامه سازمان؛ پیگیری مکاتبات، نقص مدارک، تغییرات و تمدیدها.',reportingTo:'مسئول فنی'},
 technical:{name:'مسئول فنی',unit:'فنی و مجوزها',responsibilities:'بازبینی مدارک انطباق و پرونده‌های محصول، ارتباط با مرجع مجوز، بررسی رخداد و اقدام میدانی در حدود اختیار قانونی تعیین‌شده.',reportingTo:'مدیرعامل'},
 calibration:{name:'مسئول تجهیزات آزمون و کالیبراسیون',unit:'تضمین کیفیت',responsibilities:'شناسنامه تجهیزات و گواهی کالیبراسیون، پایش اعتبار و محدودیت استفاده، بررسی اثر خروج از حدود بر آزمون‌های گذشته.',reportingTo:'مدیر تضمین کیفیت'},
 auditor:{name:'ممیز داخلی',unit:'تضمین کیفیت',responsibilities:'برنامه و چک‌لیست ممیزی، ثبت شواهد و یافته‌ها، پیگیری پاسخ با استقلال از فعالیت ممیزی‌شده.',reportingTo:'مدیر تضمین کیفیت'},
 observer:{name:'ممیز بیرونی — مشاهده',unit:'ممیزی',responsibilities:'مطالعه پرونده‌های عمومی کیفیت؛ بدون اختیار تغییر و بدون دسترسی طراحی. حساب پس از پایان ممیزی غیرفعال شود.',reportingTo:'مدیر تضمین کیفیت'},
 engineering:{name:'مدیر تحقیق‌وتوسعه و مهندسی',unit:'تحقیق‌وتوسعه',responsibilities:'ورودی و خروجی طراحی، تصدیق، صحه‌گذاری و انتقال به تولید، ریسک و کنترل تغییر مهندسی و نگهداری محرمانه مدارک.',reportingTo:'مدیرعامل'},
 designer:{name:'مهندس طراحی، الکترونیک و نرم‌افزار',unit:'تحقیق‌وتوسعه',responsibilities:'توسعه و ثبت نسخه نقشه، مدار و نرم‌افزار، تکمیل فرم‌های محصول و شواهد آزمون؛ ارجاع به بررسی‌کننده مستقل.',reportingTo:'مدیر تحقیق‌وتوسعه'},
};
