import {storage} from './storage';
import {qrows,qpermission,designMember,qmsResponsible as responsible} from './qms';
import {leadMembers,leadMemberGuard} from './sales-leads';
import {notice,addDay,dayAt} from './duties';
import {trainingContext} from './training-context';
export async function syncQmsTasks(){if(trainingContext.getStore())return;const db=storage(),rows=await qrows(),members=await leadMembers(),now=new Date().toISOString(),existing=(await db.prepare("SELECT * FROM duty_runs WHERE template_id='qms'").all()).results as any[],wanted=new Set<string>();
 for(const r of rows.filter(r=>r.type==='qms_record'))for(const mid of responsible(r,rows,members)){const id='qms:'+r.id+':'+mid;wanted.add(id);const old=existing.find(t=>t.id===id),data={qmsWorkflow:true,recordId:r.id,sourceSection:'qms',sourceId:r.id,title:'پیگیری پرونده کیفیت',instructions:'تصمیم و مدارک را فقط در بخش کیفیت بررسی کنید.',evidence:'text',remindHours:24,escalateHours:48,stage:r.data.state,history:old?JSON.parse(old.data).history||[]:[]},due=(r.data.state==='approved'&&(r.data.values.expires||r.data.values.reviewDate)?addDay(r.data.values.expires||r.data.values.reviewDate,-30):r.data.state==='approved'&&r.data.kind==='capa'?r.data.values.effectivenessDate:r.data.due||addDay(r.created.slice(0,10),2))+'T16:00:00+03:30';if(old&&old.state==='open'&&JSON.parse(old.data).stage===data.stage&&old.due===due)continue;const op=crypto.randomUUID();await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'qms_task','{}','scheduler',?,CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) AND COALESCE((SELECT revision FROM duty_runs WHERE id=?),0)=? THEN 1 ELSE 0 END)").bind(op,now,r.id,r.revision,id,old?.revision||0),leadMemberGuard(db,op,members),old?db.prepare("UPDATE duty_runs SET state='open',data=?,due=?,revision=revision+1,updated=? WHERE id=?").bind(JSON.stringify(data),due,now,id):db.prepare("INSERT INTO duty_runs(id,template_id,period,assignee,supervisor,due,state,data,revision,created,updated) VALUES(?,'qms',?,?,'',?,'open',?,1,?,?)").bind(id,r.id,mid,due,JSON.stringify(data),now,now),notice(id,mid,'qms:'+r.revision,'پرونده کیفیت منتظر پیگیری شماست.',now)]);}
 for(const t of existing.filter(t=>!wanted.has(t.id)&&['open','blocked','submitted'].includes(t.state))){const r=rows.find(r=>r.id===JSON.parse(t.data).recordId),op=crypto.randomUUID();await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'qms_task_retire','{}','scheduler',?,CASE WHEN COALESCE((SELECT revision FROM flow_entities WHERE id=?),0)=? AND EXISTS(SELECT 1 FROM duty_runs WHERE id=? AND revision=?) THEN 1 ELSE 0 END)").bind(op,now,JSON.parse(t.data).recordId,r?.revision||0,t.id,t.revision),leadMemberGuard(db,op,members),db.prepare("UPDATE duty_runs SET state='completed',revision=revision+1,updated=? WHERE id=?").bind(now,t.id)]);}
}
