import {storage} from './storage';
import {AccessError} from './authorization';
import {trainingContext} from './training-context';
import {leadMembers,leadMemberGuard} from './sales-leads';
import {qmsKinds,qmsRoles,qmsModes,qmsPositions,type QField} from './qms-contract';
import type {Session} from './permissions';
export const qtoday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tehran',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const qfail=(m:string,status=400):never=>{throw new AccessError(m,status)};
export const qt=(v:unknown,max=8000)=>{if(typeof v!=='string'||v.length>max)qfail('متن معتبر با طول مجاز وارد کنید.');return (v as string).trim()};
export const qr=(v:unknown,max=8000)=>{const s=qt(v,max);if(!s)qfail('اطلاعات الزامی کامل نیست.');return s};
export const qid=(v:unknown)=>{const s=qr(v,80);if(!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s))qfail('شناسه عملیات معتبر لازم است.');return s};
export const qday=(v:unknown)=>{const s=qr(v,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(Date.parse(s))||new Date(s).toISOString().slice(0,10)!==s)qfail('تاریخ معتبر وارد کنید.');return s};
export function qpermission(m:any){if(!m||m.status!=='active')return null;const p=JSON.parse(m.permissions);return p.hospitalCenterId||p.salesAgentId||p.serviceAgentId||p.salesRoles?.includes('agent')||p.serviceRoles?.includes('agent')?null:p;}
export function designMember(m:any){return qpermission(m)?.supplyRoles?.some((r:string)=>['engineering','ceo'].includes(r))||false;}
export async function qactor(u:Session,members?:any[]){const ms=members||await leadMembers(),m=ms.find(m=>m.subject===u.userId||u.userId==='local:'+m.id),p=qpermission(m);
 if(trainingContext.getStore()||u.permissions.hospitalCenterId||u.permissions.salesAgentId||u.permissions.serviceAgentId||!u.isAdmin&&!p)qfail('این بخش برای کارکنان مجاز شرکت است.',403);
 const roles=p?.qmsRoles||[],design=designMember(m),ceo=!!p?.supplyRoles?.includes('ceo');
 if(!u.isAdmin&&!roles.length&&!design)qfail('دسترسی کیفیت یا تحقیق‌وتوسعه لازم است.',403);
 return {id:m?.id||u.userId,design,ceo,roles,admin:u.isAdmin,has:(r:string)=>ceo||roles.includes(r)};
}
export type QActor=Awaited<ReturnType<typeof qactor>>;
export async function qrows(){return (await storage().prepare("SELECT * FROM flow_entities WHERE type IN ('qms_record','qms_file') ORDER BY created,id").all()).results.map((r:any)=>({...r,data:JSON.parse(r.data)}));}
export function qvisible(r:any,a:QActor,rows:any[]):boolean {if(r.type==='qms_file'||r.type==='qms_part'){const parent=rows.find(x=>x.id===(r.type==='qms_file'?r.data.parentId:r.data.fileId));return !!parent&&qvisible(parent,a,rows)}return r.type==='qms_record'&&(!r.data.private||a.design);}
export function qwrite(d:any,a:QActor){return d.private?a.design:a.ceo||qmsKinds[d.kind]?.roles.some(r=>a.roles.includes(r));}
export function qfind(rows:any[],id:string,a:QActor,type='qms_record'){const r=rows.find(r=>r.id===id&&r.type===type);if(!r||!qvisible(r,a,rows))qfail('پرونده در دسترس نیست.',404);return r;}
export function qpresent(r:any){if(r.type==='qms_file'){const {parentId,filename,size,state,parts,createdBy}=r.data;return {...r,data:{parentId,filename,size,state,parts,createdBy}}}return r;}
export function qfields(v:unknown):QField[]{if(!Array.isArray(v)||!v.length||v.length>100)qfail('فرم باید ۱ تا ۱۰۰ فیلد داشته باشد.');const keys=new Set();return (v as any[]).map(f=>{const key=qr(f.key,60),label=qr(f.label,200);if(!/^[a-z][a-z0-9_]*$/.test(key)||keys.has(key)||['__proto__','constructor','prototype'].includes(key)||!['text','number','date','choice','boolean'].includes(f.type))qfail('شناسه یا نوع فیلد معتبر نیست یا تکراری است.');keys.add(key);const options=f.type==='choice'?(Array.isArray(f.options)?f.options.map((s:unknown)=>qr(s,200)):[]):undefined;if(options&&(!options.length||options.length>100||new Set(options).size!==options.length))qfail('گزینه‌های معتبر و غیرتکراری لازم است.');return {key,label,type:f.type,required:f.required===true,...(options?{options}:{})}});}
export function qvalues(fields:QField[],input:any,complete:boolean){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!fields.some(f=>f.key===k)))qfail('فیلد ناشناخته در اطلاعات فرم.');const output:Record<string,string>={};for(const f of fields){const v=qt(input[f.key]??'');if(!v){if(complete&&f.required)qfail('تکمیل «'+f.label+'» لازم است.');output[f.key]='';continue;}if(f.type==='number'&&!/^-?\d+(\.\d+)?$/.test(v))qfail('عدد معتبر برای '+f.label+' لازم است.');if(f.type==='date')qday(v);if(f.type==='boolean'&&!['yes','no'].includes(v))qfail('گزینه بله یا خیر لازم است.');if(f.type==='choice'&&!f.options?.includes(v))qfail('گزینه فرم معتبر نیست.');output[f.key]=v;}return output;}
export async function qcommit(u:Session,op:string,signature:string,rows:any[],members:any[],changes:any[],mode:string){const db=storage(),now=new Date().toISOString();await db.batch([
 db.prepare('INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,?,?,?,?,1)').bind(op,'qms_'+mode,signature,u.userId,now),leadMemberGuard(db,op,members),
 db.prepare("UPDATE inventory_operations SET guard=CASE WHEN (SELECT COUNT(*) FROM flow_entities WHERE type IN ('qms_record','qms_file'))=? AND (SELECT COALESCE(SUM(revision),0) FROM flow_entities WHERE type IN ('qms_record','qms_file'))=? THEN guard ELSE 0 END WHERE id=?").bind(rows.length,rows.reduce((n,r)=>n+r.revision,0),op),
 ...changes.filter(r=>r.type==='qms_record'&&r.data.productId).map(r=>db.prepare("UPDATE inventory_operations SET guard=CASE WHEN EXISTS(SELECT 1 FROM records WHERE id=? AND kind='product') THEN guard ELSE 0 END WHERE id=?").bind(r.data.productId,op)),
 ...changes.map(r=>r.revision?db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=? AND revision=?').bind(JSON.stringify(r.data),now,r.id,r.revision):db.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').bind(r.id,r.type,JSON.stringify(r.data),now,now)),
 ...changes.filter(r=>r.data.kind==='release'&&r.data.state==='approved').flatMap(r=>(r.data.qualityEvidence||[]).map((e:any)=>db.prepare("UPDATE inventory_operations SET guard=CASE WHEN (SELECT id FROM quality_reports WHERE device_id=? ORDER BY created DESC,id DESC LIMIT 1)=? THEN guard ELSE 0 END WHERE id=?").bind(e.deviceId,e.reportId,op))),
 // Never put confidential titles, contents, file names or snapshots in the general audit log.
 db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(op,u.userId,changes.at(-1)?.id||op,'qms_'+mode,JSON.stringify(changes.map(r=>({id:r.id,type:r.type,revision:(r.revision||0)+1}))),now)]);}
export async function qsignature(b:any){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(b))))).map(x=>x.toString(16).padStart(2,'0')).join('');}
export async function qretry(u:Session,id:string,signature:string){const p:any=await storage().prepare('SELECT actor,payload FROM inventory_operations WHERE id=?').bind(id).first();if(p&&(p.actor!==u.userId||p.payload!==signature))qfail('شناسه تکراری با اطلاعات متفاوت است.',409);return !!p;}
export async function applyQms(u:Session,b:any){const members=await leadMembers(),a=await qactor(u,members),rows=await qrows(),op=qid(b.id),signature=await qsignature(b);if(b.confirmed!==true||!qmsModes.includes(b.mode))qfail('تأیید صریح و عملیات معتبر لازم است.');
 const old=b.recordId?qfind(rows,qr(b.recordId,200),a):null;
 if(await qretry(u,op,signature))return {saved:true,id:b.mode==='revise'?op:old?.id||op,repeated:true};
 if(b.mode==='install_positions'){if(!a.admin&&!a.ceo)qfail('مدیر مجاز لازم است.',403);const existing=(await storage().prepare("SELECT id FROM flow_entities WHERE type='position' AND id GLOB 'qms-position:*'").all()).results as any[];const changes=Object.entries(qmsPositions).filter(([role])=>!existing.some(r=>r.id==='qms-position:'+role)).map(([role,profile])=>({id:'qms-position:'+role,type:'position',revision:0,data:{...profile,members:[],supervisor:'',active:true,sourceSection:'qms',authorityBoundaries:'تعیین عضو و مجوز حساب مستقل است. تهیه‌کننده و ویرایش‌کنندگان حق تأیید همان پرونده را ندارند. سمت به‌تنهایی مجوز طراحی نمی‌دهد.'}}));await qcommit(u,op,signature,rows,members,changes,'positions');return {saved:true,positions:true};}
 if(b.revision!==(old?.revision||0))qfail('نسخه تغییر کرده؛ اطلاعات را تازه کنید.',409);
 const now=new Date().toISOString(),mode=b.mode,note=qr(b.notes,4000),changes:any[]=[];let d:any=old?structuredClone(old.data):{},id=old?.id||op;
 const mustWrite=()=>{if(!qwrite(d,a))qfail('مجوز ثبت این نوع پرونده لازم است.',403)};
 const reviewer=()=>{if(d.reviewerId!==a.id||d.editors.includes(a.id)||!qwrite(d,a))qfail('بررسی‌کننده مستقلِ تعیین‌شده باید تأیید کند.',403);};
 const validate=()=>{if(rows.some(r=>r.type==='qms_file'&&r.data.parentId===id&&r.data.state==='uploading'))qfail('بارگذاری باز را تکمیل یا لغو کنید.');const fields=d.kind==='response'?d.template.fields:qmsKinds[d.kind].fields;d.values=qvalues(fields,d.values,true);if(d.kind==='form')d.fields=qfields(d.fields);if(!d.ownerId||!d.reviewerId||d.ownerId===d.reviewerId)qfail('مسئول و بررسی‌کننده مستقل تعیین کنید.');const rm=members.find(m=>m.id===d.reviewerId),rp=qpermission(rm);if(!rp||d.private&&!designMember(rm)||!d.private&&!rp.supplyRoles?.includes('ceo')&&!qmsKinds[d.kind].roles.some(r=>rp.qmsRoles?.includes(r)))qfail('بررسی‌کننده مجاز و فعال انتخاب کنید.');};
 if(mode==='save'){
  if(old&&d.state!=='draft')qfail('فقط پیش‌نویس قابل ویرایش است.',409);
  const kind=old?d.kind:qr(b.kind,40);if(!qmsKinds[kind])qfail('نوع پرونده معتبر نیست.');
  let productId=old?d.productId:qt(b.productId||'',200),priv=old?d.private:!!qmsKinds[kind].private||b.private===true;
  if(productId&&!await storage().prepare("SELECT id FROM records WHERE id=? AND kind='product'").bind(productId).first())qfail('محصول معتبر انتخاب کنید.');if(qmsKinds[kind].product&&!productId)qfail('محصول لازم است.');
  d={...d,kind,productId,private:priv,title:qr(b.title,200),ownerId:qr(b.ownerId,200),reviewerId:qr(b.reviewerId,200),due:qday(b.due),state:'draft',version:d.version||1,series:d.series||id,editors:[...new Set([...(d.editors||[]),a.id])],createdBy:d.createdBy||a.id};
  if(kind==='response'&&!old){const t=qfind(rows,qr(b.templateId,200),a);if(t.data.kind!=='form'||t.data.state!=='approved'||t.data.productId!==productId)qfail('فرم مصوب همان محصول انتخاب کنید.');d.private=t.data.private;d.template={id:t.id,title:t.data.title,version:t.data.version,fields:t.data.fields};}
  mustWrite();const owner=members.find(m=>m.id===d.ownerId);if(!qpermission(owner)||d.private&&!designMember(owner))qfail('مسئول فعال و مجاز لازم است.');
  d.values=qvalues(kind==='response'?d.template.fields:qmsKinds[kind].fields,b.values||{},false);if(kind==='form')d.fields=qfields(b.fields);
  if(b.links!==undefined){if(!Array.isArray(b.links)||b.links.length>100)qfail('ارتباط پرونده‌ها معتبر نیست.');d.links=[...new Set(b.links.map((x:unknown)=>qr(x,200)))];for(const link of d.links){const target=qfind(rows,link,a);if(link===id||target.data.private&&!d.private)qfail('اطلاعات محرمانه نمی‌تواند به پرونده عمومی متصل شود.');}}
 }else if(mode==='revise'){
  mustWrite();if(!['approved','closed','hold'].includes(d.state))qfail('برای بازنگری، نسخه تأییدشده انتخاب کنید.');if(rows.some(r=>r.type==='qms_record'&&r.data.series===d.series&&['draft','review'].includes(r.data.state)))qfail('بازنگری باز دیگری وجود دارد.',409);id=op;d={...d,state:'draft',version:d.version+1,previousId:old.id,createdBy:a.id,editors:[a.id],history:[],acknowledgments:[],approval:undefined};
 }else if(mode==='acknowledge'){if(d.state!=='approved')qfail('فقط نسخه مصوب قابل اعلام مطالعه است.');d.acknowledgments=[...(d.acknowledgments||[]).filter((x:any)=>x.memberId!==a.id),{memberId:a.id,at:now}];
 }else if(mode==='submit'){mustWrite();if(d.state!=='draft')qfail('ابتدا پیش‌نویس را تکمیل کنید.');validate();d.state='review';
 }else if(mode==='return'){reviewer();if(d.state!=='review')qfail('پرونده در مرحله بررسی نیست.');d.state='draft';
 }else if(mode==='approve'){
  reviewer();if(d.state!=='review')qfail('پرونده در مرحله بررسی نیست.');validate();
  if(d.kind==='release'){if(!a.has('qa'))qfail('آزادسازی نهایی با مدیر تضمین کیفیت است.',403);d.qualityEvidence=[];if(rows.some(r=>r.type==='qms_record'&&r.data.productId===d.productId&&r.data.kind==='capa'&&!['closed','superseded'].includes(r.data.state)))qfail('عدم انطباق باز محصول باید تعیین تکلیف شود.');for(const link of d.links||[]){const linked=qfind(rows,link,a);if(linked.data.kind==='calibration'&&(linked.data.state!=='approved'||linked.data.values.expires<qtoday()))qfail('کالیبراسیون تجهیز مرتبط معتبر نیست.');}const serials=d.values.serials.split(/\r?\n/).map((x:string)=>x.trim()).filter(Boolean);if(!serials.length||new Set(serials).size!==serials.length)qfail('سریال‌ها یکتا باشند.');for(const serial of serials){const device:any=await storage().prepare("SELECT id,payload FROM records WHERE kind='device' AND json_extract(payload,'$.code')=? AND json_extract(payload,'$.product')=?").bind(serial,d.productId).first();if(!device)qfail('سریال ثبت‌شده متعلق به محصول نیست.');const report:any=await storage().prepare("SELECT id,verdict FROM quality_reports WHERE device_id=? ORDER BY created DESC,id DESC LIMIT 1").bind(device.id).first();if(report?.verdict!=='pass')qfail('آخرین آزمون نهایی سریال باید قبول باشد.');d.qualityEvidence=[...(d.qualityEvidence||[]),{deviceId:device.id,reportId:report.id}];}d.serials=serials;}
  d.state='approved';d.approval={by:a.id,at:now};if(d.previousId){const previous=qfind(rows,d.previousId,a);if(!['approved','closed','hold'].includes(previous.data.state))qfail('نسخه مبنا تغییر کرده است.',409);changes.push({...previous,data:{...previous.data,state:'superseded',supersededBy:id}});}
 }else if(mode==='close'){reviewer();if(d.kind==='capa'&&d.values.effectivenessDate>qtoday())qfail('موعد بررسی اثربخشی هنوز نرسیده است.');if(d.state!=='approved'||!['capa','complaint','audit','management'].includes(d.kind))qfail('این پرونده در مرحله بستن نیست.');d.effectiveness=qr(b.evidence);d.state='closed';
 }else if(mode==='hold'){if(!a.has('qa')&&!a.ceo)qfail('اختیار توقف با تضمین کیفیت است.',403);if(d.private&&!a.design)qfail('مجوز طراحی لازم است.',403);if(d.kind!=='release'||!['approved','review'].includes(d.state))qfail('آزادسازی قابل توقف انتخاب کنید.');d.state='hold';}
 else qfail('عملیات معتبر نیست.');
 d.history=[...(d.history||[]),{mode,by:a.id,at:now,notes:note,state:d.state}];changes.push({id,type:'qms_record',revision:mode==='revise'?0:old?.revision||0,data:d});await qcommit(u,op,signature,rows,members,changes,mode);return {saved:true,id};
}
export async function guardQmsBackup(u:Session,tables?:Record<string,any[]>){const privateExists=tables?(tables.flow_entities||[]).some(r=>r.type==='qms_record'&&JSON.parse(r.data).private):!!await storage().prepare("SELECT id FROM flow_entities WHERE type='qms_record' AND json_extract(data,'$.private')=1 LIMIT 1").first();if(privateExists&&!(await qactor(u)).design)qfail('پشتیبان شامل طراحی محرمانه است؛ نقش صریح تحقیق‌وتوسعه یا مدیرعامل لازم است.',403);}

export function qmsResponsible(r:any,_rows:any[],members:any[]){if(r.type!=='qms_record'||['closed','superseded'].includes(r.data.state))return [];const d=r.data,id=d.state==='review'?d.reviewerId:d.ownerId,m=members.find(m=>m.id===id);return qpermission(m)&&(!d.private||designMember(m))?[id]:[];}
