import {storage} from './storage';
import {salesManager,salesStaff} from './sales-access';
import {salesScope,salesLock,salesFail as fail,sreq,stxt,sday,money,integer} from './sales';
import {dayAt} from './duties';
import {trainingContext} from './training-context';
import type {Session} from './permissions';
export const leadStages:Record<string,string>={new:'جدید',contacted:'تماس اولیه',qualified:'نیازسنجی',proposal:'ارائه پیشنهاد',negotiation:'مذاکره',nurture:'فعلاً آماده خرید نیست',converted:'تبدیل به سفارش',lost:'ازدست‌رفته'};
export const leadSources:Record<string,string>={phone:'تماس',website:'سایت',exhibition:'نمایشگاه',referral:'معرفی',social:'شبکه اجتماعی',visit:'مراجعه',other:'سایر'};
export const leadLosses:Record<string,string>={price:'قیمت',timing:'زمان خرید',competitor:'رقیب',product:'تناسب محصول',no_response:'عدم پاسخ',other:'سایر'};
export const leadModes=['save','stage','activity','assign','lose','reopen','link_order'] as const;
export const leadOpen=(d:any)=>!['converted','lost'].includes(d.stage);
export const leadHelp='سرنخ باز باید مسئول، اقدام بعدی و موعد داشته باشد. کارشناس فقط پرونده‌های خودش و مدیر فروش همه تیم را می‌بیند. شماره تماس سرنخ‌های باز تکراری نمی‌شود. تبدیل به سفارش با پیش‌نمایش قیمت و تأیید صریح انجام می‌شود؛ به معنی صدور فاکتور یا وصول نیست. مبلغ فرصت تخمینی و ریالی است. نرخ تبدیل، سهم پرونده‌های تبدیل‌شده به سفارش از سرنخ‌های ایجادشده در بازه انتخابی است.';
export function leadPhone(v:unknown){let s=sreq(v,60).replace(/[۰-۹]/g,c=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(c))).replace(/[٠-٩]/g,c=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(c))).replace(/[\s()\-]/g,'');if(s.startsWith('0098'))s='0'+s.slice(4);if(s.startsWith('+98'))s='0'+s.slice(3);if(/^9\d{9}$/.test(s))s='0'+s;if(!/^(?:0\d{10}|\+[1-9]\d{7,14})$/.test(s))fail('شماره تماس کامل با کد شهر یا کشور لازم است.');return s;}
export async function leadMembers(){return (await storage().prepare('SELECT id,name,status,subject,permissions FROM app_members ORDER BY id').all()).results as any[];}
export const leadEligible=(m:any)=>m?.status==='active'&&(()=>{const p=JSON.parse(m.permissions);return !p.salesAgentId&&!p.serviceAgentId&&!p.hospitalCenterId&&salesStaff({isAdmin:false,permissions:p} as Session)})();
export async function leadActor(u:Session,members?:any[]){if(trainingContext.getStore()||u.permissions.salesAgentId||u.permissions.serviceAgentId||u.permissions.hospitalCenterId)fail('این بخش برای فروش داخلی شرکت است.',403);const all=members||await leadMembers(),m=all.find(m=>m.status==='active'&&(m.subject===u.userId||m.id===(u.userId.startsWith('local:')?u.userId.slice(6):u.userId)));if(!u.isAdmin&&!leadEligible(m))fail('دسترسی فروش لازم است.',403);return {id:m?.id||'',manager:u.isAdmin||salesManager({...u,permissions:JSON.parse(m!.permissions)})};}
export async function leadRows(){return (await storage().prepare("SELECT * FROM flow_entities WHERE type='sales_lead' ORDER BY updated DESC,id").all()).results.map((r:any)=>({...r,data:JSON.parse(r.data)}));}
export function leadVisible(r:any,a:{id:string;manager:boolean}){return a.manager||r.data.ownerId===a.id;}
export async function leadAccess(u:Session,id:string){const a=await leadActor(u),r:any=await storage().prepare("SELECT * FROM flow_entities WHERE id=? AND type='sales_lead'").bind(id).first();if(!r)fail('سرنخ در دسترس نیست.',404);const lead={...r,data:JSON.parse(r.data)};if(!leadVisible(lead,a))fail('سرنخ در دسترس نیست.',404);return lead;}
export function leadMemberGuard(db:D1Database,id:string,members:any[]){return db.prepare("UPDATE inventory_operations SET guard=CASE WHEN (SELECT json_group_array(json_object('id',id,'name',name,'status',status,'subject',subject,'permissions',permissions)) FROM (SELECT * FROM app_members ORDER BY id))=? THEN guard ELSE 0 END WHERE id=?").bind(JSON.stringify(members.map(m=>({id:m.id,name:m.name,status:m.status,subject:m.subject,permissions:m.permissions}))),id);}
export function leadHistory(d:any,u:Session,mode:string,notes:string,extra:any={}){if((d.history||[]).length>=500)fail('سقف تاریخچه پرونده پر شده است.');return [...(d.history||[]),{at:new Date().toISOString(),actor:u.userId,name:u.name,mode,notes,...extra}];}
export async function leadConvert(u:Session,leadId:string,revision:number,orderId:string,agentId:string,items:any[],opId:string){
 const db=storage(),members=await leadMembers(),a=await leadActor(u,members),r=await leadAccess(u,leadId),d=r.data;
 if(r.revision!==revision)fail('سرنخ تغییر کرده؛ تازه‌سازی کنید.',409);if(!leadOpen(d)||!d.agentId||d.agentId!==agentId)fail('سرنخ باز و طرف حساب یکسان لازم است.');
 if(!leadEligible(members.find(m=>m.id===d.ownerId)))fail('ابتدا مسئول فعال تعیین کنید.');
 const key=(lines:any[])=>JSON.stringify(lines.map(l=>[l.productId,l.quantity]).sort((x,y)=>String(x[0]).localeCompare(String(y[0]))));if(!d.items.length||key(d.items)!==key(items))fail('محصول و تعداد سفارش باید با نیاز تأییدشده فرصت یکسان باشد.');
 if(!leadVisible(r,a))fail('دسترسی این فرصت تغییر کرده است.',403);
 const next={...d,stage:'converted',orderId,convertedAt:new Date().toISOString(),history:leadHistory(d,u,'convert','تبدیل به سفارش؛ تأیید مالی و تحویل در گردش سفارش ادامه دارد.',{orderId,previousStage:d.stage})};
 return {data:next,statements:[leadMemberGuard(db,opId,members),db.prepare('UPDATE inventory_operations SET guard=CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN guard ELSE 0 END WHERE id=?').bind(r.id,r.revision,opId),db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=?').bind(JSON.stringify(next),new Date().toISOString(),r.id),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,r.id,'sales_lead_convert',JSON.stringify({orderId,previousStage:d.stage}),new Date().toISOString())]};
}
export async function applyLead(u:Session,b:any){
 const db=storage(),members=await leadMembers(),a=await leadActor(u,members),all=await leadRows();
 if(b.confirmed!==true||! /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(b.id)||!leadModes.includes(b.mode))fail('عملیات، تأیید و شناسه معتبر لازم است.');
 const signature=JSON.stringify(b),prior:any=await db.prepare('SELECT actor,payload FROM inventory_operations WHERE id=?').bind(b.id).first();if(prior){if(prior.actor!==u.userId||prior.payload!==signature)fail('شناسه عملیات قبلاً استفاده شده است.',409);return {saved:true,id:b.leadId||b.id,repeated:true};}
 const id=b.leadId||b.id,old=all.find(r=>r.id===id);if(old&&!leadVisible(old,a))fail('سرنخ در دسترس نیست.',404);if(!Number.isSafeInteger(b.revision)||b.revision!==(old?.revision||0))fail('نسخه پرونده تغییر کرده؛ تازه‌سازی کنید.',409);if(!old&&b.mode!=='save')fail('سرنخ یافت نشد.',404);
 const notes=sreq(b.notes,4000),now=new Date().toISOString(),today=dayAt(),checks=await salesLock(db,b.id),stmts:D1PreparedStatement[]=[];let d:any=old?JSON.parse(JSON.stringify(old.data)):{};
 const open=()=>{if(!leadOpen(d))fail('پرونده بسته است؛ مدیر باید سرنخ ازدست‌رفته را بازگشایی کند.');};
 const owner=(id:string)=>{if(!leadEligible(members.find(m=>m.id===id)))fail('مسئول فروش فعال لازم است.');return id;};
 const followup=()=>{d.nextAction=sreq(b.nextAction,1000);d.nextDue=sday(b.nextDue);if(d.nextDue<today)fail('موعد اقدام بعدی در گذشته نباشد.');};
 if(b.mode==='save'){
  if(old)open();if(!['home','hospital'].includes(b.segment)||!Object.hasOwn(leadSources,b.source))fail('مسیر فروش و منبع آشنایی معتبر لازم است.');
  const ownerId=owner(sreq(b.ownerId,200));if(!a.manager&&ownerId!==(old?.data.ownerId||a.id))fail('ارجاع به کارشناس دیگر فقط با مدیر فروش است.',403);
  const phone=leadPhone(b.phone);if(all.some(r=>r.id!==id&&leadOpen(r.data)&&r.data.phone===phone))fail('سرنخ بازی با این شماره وجود دارد؛ مدیر فروش پرونده موجود را بررسی کند.',409);
  const email=stxt(b.email||'',200).toLowerCase();if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail('ایمیل معتبر نیست.');
  if(!Array.isArray(b.items)||b.items.length>30||new Set(b.items.map((l:any)=>l.productId)).size!==b.items.length)fail('محصولات تکراری یا نامعتبرند.');
  const items=[];for(const l of b.items){const p:any=await db.prepare("SELECT id,payload FROM records WHERE id=? AND kind='product'").bind(sreq(l.productId,200)).first();if(!p||JSON.parse(p.payload).status!=='فعال')fail('محصول فعال انتخاب کنید.');checks.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN EXISTS(SELECT 1 FROM records WHERE id=? AND payload=?) THEN guard ELSE 0 END WHERE id=?').bind(p.id,p.payload,b.id));items.push({productId:p.id,quantity:integer(l.quantity,1,10000)});}
  if(['qualified','proposal','negotiation'].includes(d.stage)&&!items.length)fail('فرصت نیازسنجی‌شده باید محصول و تعداد داشته باشد.');
  const agentId=stxt(b.agentId||'',200);if(agentId){await salesScope(u,agentId);const agent:any=await db.prepare("SELECT id,revision,data FROM flow_entities WHERE id=? AND type='sales_agent'").bind(agentId).first();if(!agent||!JSON.parse(agent.data).active)fail('طرف حساب فروش فعال انتخاب کنید.');checks.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN guard ELSE 0 END WHERE id=?').bind(agentId,agent.revision,b.id));}
  d={...d,title:sreq(b.title,200),contactName:sreq(b.contactName,200),company:stxt(b.company||'',200),phone,email,city:sreq(b.city,100),source:b.source,sourceDetail:stxt(b.sourceDetail||'',500),segment:b.segment,ownerId,items,interest:sreq(b.interest,2000),estimatedAmount:b.estimatedAmount?money(b.estimatedAmount):'',expectedDay:b.expectedDay?sday(b.expectedDay):'',competitor:stxt(b.competitor||'',500),decisionMaker:stxt(b.decisionMaker||'',500),tenderDeadline:b.tenderDeadline?sday(b.tenderDeadline):'',agentId,stage:d.stage||'new',createdDay:d.createdDay||today,createdBy:d.createdBy||u.userId};followup();
 }else if(b.mode==='assign'){if(!a.manager)fail('انتقال مسئولیت فقط با مدیر فروش است.',403);open();d.ownerId=owner(sreq(b.ownerId,200));followup();}
 else if(b.mode==='stage'){open();if(!['new','contacted','qualified','proposal','negotiation','nurture'].includes(b.stage))fail('مرحله نامعتبر است.');if(['qualified','proposal','negotiation'].includes(b.stage)&&!d.items.length)fail('ابتدا محصول و تعداد موردنیاز را ثبت کنید.');d.stage=b.stage;followup();}
 else if(b.mode==='activity'){open();if(!['call','meeting','email','message','visit'].includes(b.activityType))fail('نوع ارتباط معتبر نیست.');const day=sday(b.day);if(day>today||day<d.createdDay)fail('تاریخ تماس باید از ایجاد پرونده تا امروز باشد.');if(!d.lastContact||d.lastContact.day<=day)d.lastContact={day,type:b.activityType,summary:notes,actor:u.userId};followup();}
 else if(b.mode==='lose'){open();if(!Object.hasOwn(leadLosses,b.lossReason))fail('دلیل ازدست‌رفتن فروش لازم است.');d.stage='lost';d.lossReason=b.lossReason;d.lossDetail=notes;d.closedAt=now;}
 else if(b.mode==='reopen'){if(!a.manager)fail('بازگشایی فقط با مدیر فروش است.',403);if(d.stage!=='lost')fail('فقط سرنخ ازدست‌رفته بازگشایی می‌شود.');if(all.some(r=>r.id!==id&&leadOpen(r.data)&&r.data.phone===d.phone))fail('سرنخ باز دیگری با این شماره وجود دارد.',409);d.ownerId=owner(b.ownerId||d.ownerId);d.stage='contacted';delete d.lossReason;delete d.lossDetail;delete d.closedAt;followup();}
 else if(b.mode==='link_order'){
  const order:any=await db.prepare("SELECT * FROM flow_entities WHERE id=? AND type='sales_order'").bind(sreq(b.orderId,200)).first();if(!order)fail('سفارش یافت نشد.');const o=JSON.parse(order.data);if(!['submitted','sales_approved','approved'].includes(o.state)||o.leadId&&o.leadId!==id||all.some(r=>r.id!==id&&r.data.orderId===order.id))fail('سفارش معتبر یا آزاد برای اتصال نیست.');
  const conversion=await leadConvert(u,id,b.revision,order.id,o.agentId,o.lines,b.id);d=conversion.data;checks.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN guard ELSE 0 END WHERE id=?').bind(order.id,order.revision,b.id));stmts.push(db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=?').bind(JSON.stringify({...o,leadId:id}),now,order.id));
 }
 if(leadOpen(d))owner(d.ownerId);
 d.history=leadHistory(old?.data||{},u,b.mode,notes,{previous:old?{...old.data,history:undefined}:null,...(b.mode==='activity'?{activityType:b.activityType,day:b.day}:{}),...(b.mode==='link_order'?{orderId:b.orderId}:{})});
 await db.batch([db.prepare('INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,?,?,?,?,1)').bind(b.id,'sales_lead_'+b.mode,signature,u.userId,now),...checks,leadMemberGuard(db,b.id,members),db.prepare("UPDATE inventory_operations SET guard=CASE WHEN COALESCE((SELECT revision FROM flow_entities WHERE id=?),0)=? AND (SELECT COUNT(*) FROM flow_entities WHERE type='sales_lead')=? AND (SELECT COALESCE(SUM(revision),0) FROM flow_entities WHERE type='sales_lead')=? THEN guard ELSE 0 END WHERE id=?").bind(id,old?.revision||0,all.length,all.reduce((n,r)=>n+r.revision,0),b.id),...stmts,old?db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=?').bind(JSON.stringify(d),now,id):db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,'sales_lead',?,1,?,?)").bind(id,JSON.stringify(d),now,now),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,id,'sales_lead_'+b.mode,JSON.stringify(d),now)]);return {saved:true,id};
}
