import {salesAccounts,rial,total} from './sales-contract';
import {solarParts,solarToIso,solarMonthDays} from './persian-date';
export const partnerKinds:Record<string,string>={representative:'نماینده خریدار',reseller:'عامل خریدار',referrer:'عامل معرف / پورسانتی'};
export const networkModes=['template','partner','contact','case','case_update','contract','contract_review','commission_settlement','commission_review','commission_pay','commission_cancel','check_link'] as const;
export const networkHelp='سبد هر کارشناس فقط نمایندگان و عاملین مسئول خودش است. الگوی عمومی نماینده و عامل خریدار نسخه‌دار است؛ شرایط مذاکره‌شده پیش از صدور فاکتور باید به تأیید مدیر فروش برسد. پرداخت وصول‌شده ابتدا خرید قدیمی را تسویه می‌کند. برای وجه نقد خرید جدید، کسری خریدهای قبلی سررسیدشده یا مرتبط با چک برگشتی اولویت دارد؛ این اولویت بدهی جدید ایجاد نمی‌کند. چک برگشتی بدون ارتباط معتبر به خرید، استثنای خرید جدید را متوقف می‌کند. عامل معرف بدهکار خرید نیست؛ پورسانت قرارداد مصوب بر وصول خالص فروش معرفی‌شده محاسبه می‌شود، با اثر برگشت کالا و وصول. اعلان‌ها داخل سامانه و اجرای پس‌زمینه وابسته به زمان‌بند است.';
export function addSolarMonths(day:string,months:number){const p=solarParts(day),n=p.month-1+months,y=p.year+Math.floor(n/12),m=n%12+1;return solarToIso(y,m,Math.min(p.day,solarMonthDays(y,m)));}
export function termsPlan(amount:string,terms:any,day:string){const cash=rial(amount)*BigInt(terms.cashBps)/BigInt(10000),rest=rial(amount)-cash;return [...(cash>BigInt(0)?[{id:'cash',kind:'cash',amount:String(cash),due:day}]:[]),...(rest>BigInt(0)?[{id:'balance',kind:'balance',amount:String(rest),due:addSolarMonths(day,terms.months)}]:[])];}
export function allocationPlan(rows:any[],agentId:string,creditId:string,today:string){
 const account=salesAccounts(rows,agentId,today),credit=account.credits.find(c=>c.id===creditId);if(!credit)return {allocations:[],recoveries:[],held:'0',unallocated:'0',unlinkedChecks:[],policy:'fifo-v1'};
 let available=rial(credit.available);const invoices=[...account.invoices].sort((a,b)=>a.data.day.localeCompare(b.data.day)||a.created.localeCompare(b.created)||a.id.localeCompare(b.id));
 const parts=invoices.flatMap(i=>[...i.installments].sort((a,b)=>a.due.localeCompare(b.due)||a.id.localeCompare(b.id)).map(p=>({...p,invoiceId:i.id,day:i.data.day,created:i.created,key:i.id+':'+p.id,left:rial(p.remaining)})));
 const bounced=account.payments.filter(p=>p.data.state==='bounced').map(p=>{const recovered=total(rows.filter(r=>r.type==='sales_check_recovery'&&r.data.paymentId===p.id&&account.credits.some(c=>c.id===r.data.creditId&&c.type==='sales_payment')),r=>r.data.amount);return {...p,left:rial(p.data.amount)>recovered?rial(p.data.amount)-recovered:BigInt(0),links:rows.filter(r=>r.type==='sales_allocation'&&r.data.creditId===p.id).map(r=>({invoiceId:r.data.invoiceId,installmentId:r.data.installmentId,amount:r.data.amount}))}}).filter(p=>p.left>BigInt(0));
 for(const p of bounced)if(!p.links.length&&p.data.checkInvoiceId)p.links=parts.filter(v=>v.invoiceId===p.data.checkInvoiceId).map(v=>({invoiceId:v.invoiceId,installmentId:v.id,amount:v.amount}));
 const unlinkedChecks=bounced.filter(p=>!p.links.length).map(p=>p.id),allocations:any[]=[],recoveries:any[]=[];
 function take(p:any,cap=p.left){const n=[available,p.left,cap].reduce((a,b)=>a<b?a:b);if(n<=BigInt(0))return;const old=allocations.find(v=>v.invoiceId===p.invoiceId&&v.installmentId===p.id);if(old)old.amount=String(rial(old.amount)+n);else allocations.push({invoiceId:p.invoiceId,installmentId:p.id,amount:String(n)});p.left-=n;available-=n;let recover=n;for(const check of bounced){const link=check.links.find((l:any)=>l.invoiceId===p.invoiceId&&l.installmentId===p.id);if(!link||check.left<=BigInt(0)||recover<=BigInt(0))continue;const n=[recover,check.left,rial(link.amount)].reduce((a,b)=>a<b?a:b);check.left-=n;link.amount=String(rial(link.amount)-n);recover-=n;const old=recoveries.find(r=>r.paymentId===check.id);if(old)old.amount=String(rial(old.amount)+n);else recoveries.push({paymentId:check.id,amount:String(n)});}}
 const order=credit.data.cashOrderId?rows.find(r=>r.id===credit.data.cashOrderId&&r.type==='sales_order'&&r.data.agentId===agentId&&!['cancelled','rejected'].includes(r.data.state)):null,target=order?invoices.find(i=>i.data.orderId===order.id):null;
 let held=BigInt(0);if(order?.data.salesTerms&&!unlinkedChecks.length){const older=(p:any)=>target?invoices.findIndex(i=>i.id===p.invoiceId)<invoices.findIndex(i=>i.id===target.id):true;
  for(const p of parts.filter(p=>older(p)&&p.due<=today))take(p);
  for(const p of parts.filter(older)){const risk=bounced.reduce((n,c)=>n+(c.links.filter((l:any)=>l.invoiceId===p.invoiceId&&l.installmentId===p.id).reduce((n:bigint,l:any)=>n+rial(l.amount),BigInt(0))<c.left?c.links.filter((l:any)=>l.invoiceId===p.invoiceId&&l.installmentId===p.id).reduce((n:bigint,l:any)=>n+rial(l.amount),BigInt(0)):c.left),BigInt(0));take(p,risk);}
  if(target){for(const p of parts.filter(p=>p.invoiceId===target.id&&p.kind==='cash'))take(p);}else{const need=rial(order.data.amount)*BigInt(order.data.salesTerms.cashBps)/BigInt(10000);held=available<need?available:need;available-=held;}
 }
 for(const p of parts)take(p);
 return {allocations,recoveries:credit.type==='sales_payment'?recoveries:[],held:String(held),unallocated:String(available),unlinkedChecks,policy:order&&!unlinkedChecks.length?'arrears-then-cash-then-fifo-v1':'fifo-v1'};
}
export function commissionAccount(rows:any[],referrerId:string){const payments=rows.filter(r=>r.type==='sales_commission_settlement'&&r.data.agentId===referrerId&&r.data.state==='paid');const invoices=rows.filter(r=>r.type==='sales_invoice'&&r.data.referral?.agentId===referrerId).map(i=>{const returned=total(rows.filter(r=>r.type==='sales_return'&&r.data.invoiceId===i.id&&r.data.state==='credited'),r=>r.data.amount),paid=total(rows.filter(r=>r.type==='sales_allocation'&&r.data.invoiceId===i.id&&rows.some(p=>p.id===r.data.creditId&&p.type==='sales_payment'&&p.data.state==='cleared')),r=>r.data.amount),net=rial(i.data.amount)-returned,collected=paid<net?paid:net,earned=collected*BigInt(i.data.referral.bps)/BigInt(10000);return {invoiceId:i.id,reference:i.data.reference,day:i.data.day,net:String(net),collected:String(collected),bps:i.data.referral.bps,earned:String(earned),contractId:i.data.referral.contractId}});const earned=total(invoices,i=>i.earned),paid=total(payments,p=>p.data.amount),reserved=total(rows.filter(r=>r.type==='sales_commission_settlement'&&r.data.agentId===referrerId&&['pending','approved'].includes(r.data.state)),r=>r.data.amount);return {invoices,earned:String(earned),paid:String(paid),reserved:String(reserved),balance:String(earned-paid),available:String(earned-paid-reserved)};}
