import {storage} from './storage';
import {salesRows,salesScope,salesVisible,salesLock,salesFail as fail,sreq,stxt,sday,integer,money} from './sales';
import {salesRead,salesManager,salesStaff,salesFinance,salesRep} from './sales-access';
import {leadMembers,leadMemberGuard,leadEligible} from './sales-leads';
import {dayAt,addDay} from './duties';
import {networkModes,partnerKinds,networkHelp,commissionAccount} from './sales-network-contract';
import {salesAccounts,rial} from './sales-contract';
import type {Session} from './permissions';
import {trainingContext} from './training-context';
export async function networkActor(u:Session){const members=await leadMembers();if(trainingContext.getStore())fail('این بخش در اطلاعات شرکت اجرا می‌شود.',403);if(!u.isAdmin){const m=members.find(m=>m.status==='active'&&(m.subject===u.userId||'local:'+m.id===u.userId));if(!m)fail('دسترسی فعال لازم است.',403);u={...u,permissions:JSON.parse(m.permissions)};}if(!salesRead(u))fail('دسترسی فروش لازم است.',403);return {u,members};}
export async function readNetwork(actor:Session){const {u}=await networkActor(actor),rows=await salesRows(),today=dayAt(),agents=[];for(const a of rows.filter(r=>r.type==='sales_agent'))if(await salesVisible(u,a)&&(!salesRep(u)||a.data.active))agents.push(a);const ids=new Set(agents.map(a=>a.id));
 const portfolio=agents.map(a=>{const own=rows.filter(r=>r.data.agentId===a.id),invoices=own.filter(r=>r.type==='sales_invoice'),contacts=own.filter(r=>r.type==='sales_contact'),lastPurchase=invoices.map(r=>r.data.day).sort().at(-1)||'',lastContact=contacts.map(r=>r.data.day).sort().at(-1)||'',nextContact=contacts.sort((a,b)=>b.created.localeCompare(a.created))[0]?.data.nextDue||addDay(lastContact||a.created.slice(0,10),a.data.contactDays||30),reorderDue=addDay(lastPurchase||a.created.slice(0,10),a.data.reorderDays||60);return {agentId:a.id,lastPurchase,lastContact,nextContact,reorderDue,contactLate:nextContact<=today,inactive:reorderDue<=today,account:salesAccounts(rows,a.id,today),commission:commissionAccount(rows,a.id)};});
 return {today,help:networkHelp,roles:{manager:salesManager(u),finance:salesFinance(u),staff:salesStaff(u),agent:salesRep(u)},agents,portfolio,templates:rows.filter(r=>r.type==='sales_template'),records:rows.filter(r=>ids.has(r.data.agentId)&&['sales_contact','sales_case','sales_contract','sales_commission_settlement'].includes(r.type))};}
export async function applyNetwork(actor:Session,b:any){const {u,members}=await networkActor(actor),db=storage(),now=new Date().toISOString(),today=dayAt();if(b.confirmed!==true||!networkModes.includes(b.mode)||! /^[0-9a-f-]{36}$/i.test(b.id))fail('تأیید و شناسه معتبر عملیات لازم است.');
 const manager=salesManager(u),finance=salesFinance(u),staff=salesStaff(u);if(['template','partner','contract'].includes(b.mode)?!manager:['contract_review','commission_review','commission_pay','commission_cancel','check_link'].includes(b.mode)?!finance:!(staff||manager||finance||salesRep(u)))fail('مجوز این مرحله را ندارید.',403);
 const a=b.mode==='template'?null:await salesScope(u,sreq(b.agentId)),signature=JSON.stringify(b),prior:any=await db.prepare('SELECT actor,payload FROM inventory_operations WHERE id=?').bind(b.id).first();if(prior){if(prior.actor!==u.userId||prior.payload!==signature)fail('شناسه قبلاً استفاده شده است.',409);return {saved:true,repeated:true};}
 const checks=await salesLock(db,b.id),rows=await salesRows(),notes=sreq(b.notes,4000),stmts:D1PreparedStatement[]=[];checks.push(leadMemberGuard(db,b.id,members));if(a)checks.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN guard ELSE 0 END WHERE id=?').bind(a.id,a.revision,b.id));
 const put=(id:string,type:string,data:any,old?:any)=>{const d={...data,history:[...(old?.data.history||[]),{actor:u.userId,mode:b.mode,notes,at:now}]};stmts.push(old?db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=? AND revision=?').bind(JSON.stringify(d),now,id,old.revision):db.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').bind(id,type,JSON.stringify(d),now,now));};
 const current=(type:string)=>{const r=rows.find(r=>r.type===type&&r.id===b.recordId&&r.data.agentId===a!.id);if(!r)fail('پرونده در دسترسی نیست.',404);if(r!.revision!==b.revision)fail('نسخه تغییر کرده؛ تازه‌سازی کنید.',409);return r!;};
 const next=()=>{const due=sday(b.nextDue);if(due<today)fail('موعد بعدی در گذشته نباشد.');return {nextDue:due,nextAction:sreq(b.nextAction,1000)};};
 if(b.mode==='template'){if(!['representative','reseller'].includes(b.kind))fail('نوع الگو معتبر نیست.');const previous=rows.filter(r=>r.type==='sales_template'&&r.data.kind===b.kind).sort((a,b)=>(b.data.version||0)-(a.data.version||0)||b.created.localeCompare(a.created)||b.id.localeCompare(a.id))[0];if((previous?.id||'')!==(b.previousId||''))fail('الگو تغییر کرده؛ تازه‌سازی کنید.',409);put(b.id,'sales_template',{kind:b.kind,title:sreq(b.title),cashBps:integer(b.cashBps,0,10000),months:integer(b.months,0,12),version:(previous?.data.version||0)+1,previousId:previous?.id||'',notes});}
 else if(b.mode==='partner'){if(a!.revision!==b.revision)fail('نسخه تغییر کرده است.',409);if(!Object.hasOwn(partnerKinds,b.kind)||!leadEligible(members.find(m=>m.id===b.ownerId)))fail('نوع همکاری و مسئول فروش فعال لازم است.');if((a!.data.kind==='referrer')!==(b.kind==='referrer')&&rows.some(r=>r.data.agentId===a!.id&&['sales_order','sales_invoice','sales_contract','sales_payment'].includes(r.type)))fail('نوع حساب دارای سابقه مالی قابل تبدیل نیست؛ پرونده جدا ایجاد کنید.');put(a!.id,'sales_agent',{...a!.data,kind:b.kind,ownerId:b.ownerId,contactDays:integer(b.contactDays,1,365),reorderDays:integer(b.reorderDays,1,365)},a);}
 else if(b.mode==='check_link'){const r=current('sales_payment');if(r.data.method!=='check'||!['received','bounced'].includes(r.data.state)||rows.some(v=>v.type==='sales_allocation'&&v.data.creditId===r.id))fail('فقط چک بدون تخصیص قبلی قابل اتصال است.');const invoice=rows.find(v=>v.type==='sales_invoice'&&v.id===b.invoiceId&&v.data.agentId===a!.id);if(!invoice)fail('فاکتور همین شریک لازم است.');put(r.id,r.type,{...r.data,checkInvoiceId:invoice.id},r);}
 else if(b.mode==='commission_cancel'){const r=current('sales_commission_settlement');if(!['pending','approved'].includes(r.data.state))fail('تسویه پرداخت‌شده قابل لغو نیست.');put(r.id,r.type,{...r.data,state:'cancelled',cancelledBy:u.userId},r);}
 else if(b.mode==='contact'){if(!staff)fail('ثبت تماس با کارشناس فروش است.',403);if(!['call','visit','meeting','message'].includes(b.channel))fail('نوع ارتباط معتبر نیست.');const day=sday(b.day);if(day>today)fail('تاریخ تماس در آینده نیست.');put(b.id,'sales_contact',{agentId:a!.id,channel:b.channel,day,notes,...next()});}
 else if(b.mode==='case'){if(!['training','marketing','support','complaint','development'].includes(b.kind))fail('نوع پرونده معتبر نیست.');if(!a!.data.ownerId)fail('ابتدا مسئول این شریک تعیین شود.');put(b.id,'sales_case',{agentId:a!.id,kind:b.kind,title:sreq(b.title),notes,...next(),state:'open'});}
 else if(b.mode==='case_update'){if(!staff)fail('پیگیری پرونده با کارشناس است.',403);const r=current('sales_case');if(!['open','closed'].includes(b.state))fail('وضعیت معتبر نیست.');put(r.id,r.type,{...r.data,state:b.state,notes,...(b.state==='open'?next():{resolution:notes,closedAt:now})},r);}
 else if(b.mode==='contract'){if(a!.data.kind!=='referrer')fail('قرارداد پورسانت فقط برای عامل معرف است.');const start=sday(b.start),end=sday(b.end);if(start>end||end<today)fail('بازه قرارداد معتبر نیست.');put(b.id,'sales_contract',{agentId:a!.id,reference:sreq(b.reference),start,end,bps:integer(b.bps,0,10000),state:'pending',preparedBy:u.userId,notes,basis:'net-collected-v1'});}
 else if(b.mode==='contract_review'){const r=current('sales_contract');if(r.data.state!=='pending'||r.data.preparedBy===u.userId||typeof b.approved!=='boolean')fail('بررسی مستقل قراردادِ در انتظار لازم است.');if(b.approved&&rows.some(v=>v.type==='sales_contract'&&v.data.agentId===a!.id&&v.data.state==='approved'&&v.data.start<=r.data.end&&v.data.end>=r.data.start))fail('قرارداد مصوب همپوشان وجود دارد.');put(r.id,r.type,{...r.data,state:b.approved?'approved':'rejected',reviewedBy:u.userId},r);}
 else if(b.mode==='commission_settlement'){if(a!.data.kind!=='referrer')fail('حساب پورسانتی لازم است.');const amount=money(b.amount,true),c=commissionAccount(rows,a!.id);if(rial(amount)>rial(c.available))fail('مبلغ بیش از پورسانت آزاد وصول‌شده است.');put(b.id,'sales_commission_settlement',{agentId:a!.id,amount,state:'pending',preparedBy:u.userId,notes});}
 else {const r=current('sales_commission_settlement'),c=commissionAccount(rows,a!.id);if(b.mode==='commission_review'){if(r.data.state!=='pending'||r.data.preparedBy===u.userId||typeof b.approved!=='boolean')fail('بررسی مستقل تسویه در انتظار لازم است.');if(b.approved&&rial(c.available)<BigInt(0))fail('پس از برگشت وصول یا کالا، پورسانت کافی نیست.');put(r.id,r.type,{...r.data,state:b.approved?'approved':'rejected',reviewedBy:u.userId},r);}else{if(r.data.state!=='approved'||rial(c.available)<BigInt(0))fail('تسویه مصوب و پورسانت کافی لازم است.');const reference=sreq(b.reference,300),day=sday(b.day);if(day>today||rows.some(v=>v.type==='sales_commission_settlement'&&v.data.state==='paid'&&v.data.reference===reference))fail('تاریخ یا مرجع پرداخت معتبر نیست.');put(r.id,r.type,{...r.data,state:'paid',reference,day,paidBy:u.userId},r);}}
 await db.batch([db.prepare('INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,?,?,?,?,1)').bind(b.id,'sales_network_'+b.mode,signature,u.userId,now),...checks,...stmts,db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,b.recordId||a?.id||b.id,'sales_network_'+b.mode,signature,now)]);return {saved:true};}
