import {salesAccounts,salesOrderProgress,rial,total} from './sales-contract';
import {localDay,solarParts,solarToIso,solarMonthDays,formatDate} from './persian-date';
export const reportKinds:Record<string,string>={daily:'روزانه',weekly:'هفتگی',quarterly:'فصلی'};
export const alertKinds:Record<string,string>={bounced_check:'چک برگشتی',overdue:'مطالبات معوق',goal_gap:'فاصله از هدف فروش',late_delivery:'تأخیر تحویل',pending_payment:'رسید منتظر مالی',repeat_returns:'برگشتی پرتکرار'};
export const alertStates:Record<string,string>={open:'نیازمند پیگیری',acknowledged:'در حال پیگیری',resolved:'رفع شده',reviewed:'جمع‌بندی پایان دوره'};
export const monitorDefaults={enabled:true,dailyTime:'08:30',weeklyTime:'09:00',quarterlyTime:'09:00',overdueDays:30,overdueAmount:'0',goalElapsed:50,goalAchievement:35,goalFinalElapsed:80,goalFinalAchievement:65,deliveryLateDays:2,paymentHours:24,returnCount:3,returnDays:30,responseHours:24,escalationHours:48};
export const monitorHelp=[
 'گزارش روزانه: گردش دیروز، مقایسه با همان روز هفته قبل و پیگیری امروز. هفتگی: شنبه ساعت تعیین‌شده، هفته کامل شنبه تا جمعه. فصلی: ابتدای فصل شمسی، فصل کامل قبل. مانده و کارهای باز تصویر زمان تهیه‌اند؛ جای مانده تاریخی پایان دوره نیستند.',
 'هدف فروش مصوب مستقل از پلکان تخفیف است. مبلغ/تعداد خالص فاکتورهای همان دوره و محصولات هدف شمرده می‌شود؛ افتتاحیه و سفارش تأییدنشده هدف را پر نمی‌کنند. برگشت تأییدشده از دوره فاکتور اصلی کم می‌شود.',
 'گزارش و اولویت‌ها از داده ثبت‌شده محاسبه می‌شوند؛ علت افت، سود یا پوشش کامل سوابق حدس زده نمی‌شود. خلاصه آماده بدون نیاز به مدل خارجی تولید می‌شود؛ دستیار همین گزارش را می‌خواند و برای اقدام تأیید می‌گیرد.',
 'هشدار مستقل از گزارش روزانه پس از تغییر فروش/حمل و در زمان‌بند بررسی می‌شود. مشاهده یا پاسخ، هشدار را نمی‌بندد. تکرار یک وضعیت اعلان تازه نمی‌سازد؛ بدتر شدن مهم، بازگشایی یا عبور از مهلت دوباره اطلاع داده می‌شود.',
 'چک برگشتی فقط با ثبت ارتباط وصول جایگزین توسط مالی رفع می‌شود. این ارتباط دوباره اعتبار ایجاد یا قسط را تسویه نمی‌کند؛ تخصیص اعتبار در گردش مالی انجام می‌شود. برگشت وصول جایگزین، هشدار را دوباره باز می‌کند.',
 'اجرای وقتی صفحه بسته است نیازمند زمان‌بند سرور یا اتصال مجاز خودکار است. زمان آخرین اجرای پس‌زمینه در این صفحه مشخص است؛ باز کردن صفحه به معنی فعال بودن زمان‌بند نیست. اعلان‌ها داخل سامانه‌اند.'
];
const dayMs=86400000;
export const shiftDay=(d:string,n:number)=>new Date(Date.parse(d+'T12:00:00Z')+n*dayMs).toISOString().slice(0,10);
export const dayDiff=(a:string,b:string)=>Math.round((Date.parse(a)-Date.parse(b))/dayMs);
const positive=(v:bigint)=>v>BigInt(0)?v:BigInt(0);
export function goalProgress(goal:any,rows:any[],today:string){
 const d=goal.data,invoices=rows.filter(r=>r.type==='sales_invoice'&&!r.data.openingId&&r.data.agentId===d.agentId&&r.data.day>=d.start&&r.data.day<=d.end),ids=new Set(invoices.map(r=>r.id));
 const measure=(lines:any[])=>total(lines.filter(l=>!d.productIds.length||d.productIds.includes(l.productId)),l=>d.basis==='units'?l.quantity:l.net);
 const actual=BigInt(total(invoices,i=>measure(i.data.lines)))-BigInt(total(rows.filter(r=>r.type==='sales_return'&&r.data.state==='credited'&&ids.has(r.data.invoiceId)),r=>measure(r.data.lines)));
 const days=dayDiff(d.end,d.start)+1,elapsed=Math.max(0,Math.min(days,dayDiff(today,d.start)+1)),remaining=positive(rial(d.amount)-actual),remainingDays=Math.max(0,dayDiff(d.end,today));
 return {actual:String(actual),amount:d.amount,achievementBps:Number(positive(actual)*BigInt(10000)/rial(d.amount)),elapsedBps:Math.floor(elapsed*10000/days),remaining:String(remaining),remainingDays,requiredPerDay:remainingDays?String((remaining+BigInt(remainingDays)-BigInt(1))/BigInt(remainingDays)):null,started:today>=d.start,ended:today>d.end};
}
function quarterStart(day:string){const p=solarParts(day);return solarToIso(p.year,Math.floor((p.month-1)/3)*3+1,1);}
function previousQuarter(start:string){const p=solarParts(start),month=p.month===1?10:p.month-3,year=p.month===1?p.year-1:p.year;return {start:solarToIso(year,month,1),end:shiftDay(start,-1)};}
export type ReportPeriod={start:string;end:string;previousStart:string;previousEnd:string;yearAgoStart?:string;yearAgoEnd?:string};
export function reportPeriod(kind:string,today:string):ReportPeriod{
 if(kind==='daily'){const end=shiftDay(today,-1);return {start:end,end,previousStart:shiftDay(end,-7),previousEnd:shiftDay(end,-7)};}
 if(kind==='weekly'){const day=new Date(today+'T12:00:00Z').getUTCDay(),startThis=shiftDay(today,-((day+1)%7)),end=shiftDay(startThis,-1),start=shiftDay(end,-6);return {start,end,previousStart:shiftDay(start,-7),previousEnd:shiftDay(end,-7)};}
 const q=previousQuarter(quarterStart(today)),previous=previousQuarter(q.start),a=solarParts(q.start),b=solarParts(q.end);return {...q,previousStart:previous.start,previousEnd:previous.end,yearAgoStart:solarToIso(a.year-1,a.month,1),yearAgoEnd:solarToIso(b.year-1,b.month,solarMonthDays(b.year-1,b.month))};
}
export function dueReports(now:Date,policy:any){
 const today=localDay(now),time=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Tehran',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(now),startDay=policy.startedDay||today;
 return Object.keys(reportKinds).flatMap(kind=>{let scheduled=kind==='daily'?today:kind==='weekly'?shiftDay(today,-((new Date(today+'T12:00:00Z').getUTCDay()+1)%7)):quarterStart(today);const at=policy[kind+'Time'];if(scheduled===today&&time<at){scheduled=kind==='daily'?shiftDay(today,-1):kind==='weekly'?shiftDay(today,-7):previousQuarter(scheduled).start;}return scheduled<startDay?[]:[{kind,scheduled,...reportPeriod(kind,scheduled)}];});
}
export function checkRecovery(payment:any,rows:any[]){const valid=rows.filter(r=>r.type==='sales_check_recovery'&&r.data.paymentId===payment.id&&rows.some(p=>p.type==='sales_payment'&&p.id===r.data.creditId&&p.data.agentId===payment.data.agentId&&p.data.state==='cleared'));return {recovered:String(total(valid,r=>r.data.amount)),remaining:String(positive(rial(payment.data.amount)-total(valid,r=>r.data.amount)))};}
export function detectSalesAlerts(rows:any[],deliveries:any[],now:Date,policy:any){
 const today=localDay(now),agents=rows.filter(r=>r.type==='sales_agent'),result:any[]=[];
 const add=(kind:string,agent:any,sourceId:string,severity:string,summary:string,evidence:any,action:string,weight:bigint=BigInt(0))=>result.push({key:kind+':'+sourceId,kind,agentId:agent.id,sourceId,severity,title:alertKinds[kind]+' · '+agent.data.name,summary,evidence,action,weight:String(weight)});
 for(const a of agents){const account=salesAccounts(rows,a.id,today),unpaid=account.invoices.flatMap(i=>i.installments.map((p:any)=>({...p,invoiceId:i.id,reference:i.data.reference}))).filter(p=>p.overdue),oldest=Math.max(0,...unpaid.map(p=>-p.days));
  if(rial(account.overdue)>BigInt(0)&&(oldest>=policy.overdueDays||rial(policy.overdueAmount)>BigInt(0)&&rial(account.overdue)>=rial(policy.overdueAmount)))add('overdue',a,a.id,'critical','مطالبات معوق از حد پیگیری عبور کرده است.',{amount:account.overdue,oldestDays:oldest,freeCredit:account.credit,installments:unpaid.map(p=>({invoiceId:p.invoiceId,installmentId:p.id,reference:p.reference,due:p.due,remaining:p.remaining}))},'تماس با نماینده، ثبت تعهد پرداخت و پیگیری تطبیق/تخصیص با مالی.',rial(account.overdue));
  for(const p of account.payments){if(p.data.state==='bounced'){const recovery=checkRecovery(p,rows);if(rial(recovery.remaining)>BigInt(0))add('bounced_check',a,p.id,'critical','چک برگشتی هنوز وصول جایگزین تأییدشده کافی ندارد.',{paymentId:p.id,reference:p.data.reference,bank:p.data.bank,amount:p.data.amount,...recovery},'پیگیری وصول جایگزین؛ مالی ارتباط پرداخت وصول‌شده با چک را ثبت کند.',rial(recovery.remaining));}
   if(p.data.state==='pending'&&(now.getTime()-Date.parse(p.updated))/3600000>=policy.paymentHours)add('pending_payment',a,p.id,'warning','اعلام پرداخت بیش از مهلت تعیین‌شده در انتظار مالی است.',{paymentId:p.id,reference:p.data.reference,amount:p.data.amount,since:p.updated},'رسید را با بانک تطبیق دهید؛ تأیید یا رد مستند توسط مالی.',rial(p.data.amount));}
  for(const o of rows.filter(r=>r.type==='sales_order'&&r.data.agentId===a.id)){const p=salesOrderProgress(o,deliveries,today);if(p.late&&dayDiff(today,o.data.promisedDay)>=policy.deliveryLateDays)add('late_delivery',a,o.id,'warning','موعد وعده‌داده‌شده گذشته و تحویل کامل نشده است.',{orderId:o.id,code:o.data.code,promisedDay:o.data.promisedDay,remaining:p.remaining,stage:p.stage,recordedBlocker:o.data.progressNote||''},'مانع را از مسئول مرحله بگیرید و برنامه تحویل را با نماینده هماهنگ کنید.',rial(o.data.amount));}
  for(const g of rows.filter(r=>r.type==='sales_goal'&&r.data.state==='active'&&r.data.agentId===a.id)){const p=goalProgress(g,rows,today),threshold=p.elapsedBps>=policy.goalFinalElapsed*100?policy.goalFinalAchievement:p.elapsedBps>=policy.goalElapsed*100?policy.goalAchievement:0;if(p.started&&(p.ended?p.achievementBps<10000:threshold>0&&p.achievementBps<threshold*100))add('goal_gap',a,g.id,p.ended||p.elapsedBps>=policy.goalFinalElapsed*100?'critical':'warning','تحقق هدف مصوب با زمان سپری‌شده تناسب ندارد.',{goalId:g.id,title:g.data.title,basis:g.data.basis,start:g.data.start,end:g.data.end,...p},p.ended?'جمع‌بندی پایان دوره و برنامه اصلاحی مستند مدیر.':'بررسی فرصت‌های واقعی فروش، موجودی و برنامه جبران کارشناس.',rial(p.remaining));}
  const returns=account.returns.filter(r=>['returned','credited'].includes(r.data.state)&&localDay(r.data.receivedAt||r.updated)>=shiftDay(today,-policy.returnDays+1));if(returns.length>=policy.returnCount)add('repeat_returns',a,a.id,'warning','تعداد پرونده‌های برگشتی دریافت‌شده از حد بررسی عبور کرده است.',{count:returns.length,days:policy.returnDays,returnIds:returns.map(r=>r.id)},'دلایل ثبت‌شده برگشت را با واحد مرتبط بررسی کنید؛ علت مشترک را بدون شواهد فرض نکنید.',BigInt(returns.length));
 }
 return result;
}
function periodMetrics(rows:any[],start:string,end:string){
 const within=(d:string)=>!!d&&d>=start&&d<=end,invoices=rows.filter(r=>r.type==='sales_invoice'&&!r.data.openingId&&within(r.data.day)),returns=rows.filter(r=>r.type==='sales_return'&&r.data.state==='credited'&&within(localDay(r.data.reviewedAt||r.updated))),payments=rows.filter(r=>r.type==='sales_payment'&&!r.data.openingId).flatMap(r=>(r.data.financialEvents||[]).filter((e:any)=>within(e.day)).map((e:any)=>({...e,agentId:r.data.agentId}))),orders=rows.filter(r=>r.type==='sales_order'&&within(localDay(r.created)));
 const invoiceAmount=total(invoices,r=>r.data.amount),returnAmount=total(returns,r=>r.data.amount);
 return {newOrders:orders.length,newOrderAmount:String(total(orders,r=>r.data.amount)),invoices:invoices.length,invoiced:String(invoiceAmount),returns:String(returnAmount),netSales:String(invoiceAmount-returnAmount),collections:String(total(payments,e=>e.delta)),discounts:String(total(invoices,r=>r.data.discount)),cancelled:rows.filter(r=>r.type==='sales_order'&&r.data.history?.some((h:any)=>h.mode==='order_cancel'&&within(localDay(h.at)))).length};
}
export function buildSalesReport(kind:string,rows:any[],deliveries:any[],tasks:any[],alerts:any[],members:any[],now:Date,period=reportPeriod(kind,localDay(now))){
 const today=localDay(now),agents=rows.filter(r=>r.type==='sales_agent'),current=periodMetrics(rows,period.start,period.end),previous=periodMetrics(rows,period.previousStart,period.previousEnd),accounts=agents.map(a=>({agentId:a.id,...salesAccounts(rows,a.id,today)}));
 const byAgent=agents.map(a=>{const own=rows.filter(r=>r.data.agentId===a.id),ac=accounts.find(v=>v.agentId===a.id)!;return {id:a.id,name:a.data.name,province:a.data.province,ownerId:a.data.ownerId,ownerName:members.find(m=>m.id===a.data.ownerId)?.name||'تعیین نشده',...periodMetrics(own,period.start,period.end),debt:ac.debt,credit:ac.credit,balance:ac.balance,overdue:ac.overdue,goals:own.filter(r=>r.type==='sales_goal'&&r.data.state==='active'&&r.data.start<=period.end&&r.data.end>=period.start).map(g=>({id:g.id,title:g.data.title,basis:g.data.basis,...goalProgress(g,rows,today)}))};});
 const invoices=rows.filter(r=>r.type==='sales_invoice'&&!r.data.openingId&&r.data.day>=period.start&&r.data.day<=period.end),returns=rows.filter(r=>r.type==='sales_return'&&r.data.state==='credited'&&localDay(r.data.reviewedAt||r.updated)>=period.start&&localDay(r.data.reviewedAt||r.updated)<=period.end);
 const productIds=Array.from(new Set([...invoices,...returns].flatMap(i=>i.data.lines.map((l:any)=>l.productId))));
 const products=productIds.map(id=>{const lines=invoices.flatMap(i=>i.data.lines).filter(l=>l.productId===id),back=returns.flatMap(i=>i.data.lines).filter(l=>l.productId===id);return {id,name:[...lines,...back][0]?.name||id,quantity:lines.reduce((n,l)=>n+l.quantity,0)-back.reduce((n,l)=>n+l.quantity,0),netSales:String(total(lines,l=>l.net)-total(back,l=>l.net)),returns:String(total(back,l=>l.net))};});
 const openTasks=tasks.filter(t=>t.data.salesWorkflow&&!t.data.salesReport&& !['completed','cancelled'].includes(t.state));
 const team=members.filter(m=>m.sales).map(m=>{const own=byAgent.filter(a=>a.ownerId===m.id),work=openTasks.filter(t=>t.assignee===m.id);return {id:m.id,name:m.name,representatives:own.length,netSales:String(total(own,a=>a.netSales)),collections:String(total(own,a=>a.collections)),overdue:String(total(own,a=>a.overdue)),openTasks:work.length,lateTasks:work.filter(t=>t.due<now.toISOString()).length};});
 const pipeline=rows.filter(r=>r.type==='sales_order'&&!['cancelled','rejected'].includes(r.data.state)).map(o=>({code:o.data.code,amount:o.data.amount,promisedDay:o.data.promisedDay,recordedBlocker:o.data.progressNote||'',...salesOrderProgress(o,deliveries,today)})).filter(p=>p.stage!=='delivered');
 const due=accounts.flatMap(a=>a.invoices.flatMap(i=>i.installments.filter((p:any)=>rial(p.remaining)>BigInt(0)&&p.days>=0&&p.days<=7).map((p:any)=>({agentId:a.agentId,invoiceId:i.id,reference:i.data.reference,...p}))));
 const checksDue=rows.filter(r=>r.type==='sales_payment'&&r.data.method==='check'&&r.data.state==='received'&&r.data.checkDue<=shiftDay(today,7)).map(r=>({id:r.id,agentId:r.data.agentId,reference:r.data.reference,amount:r.data.amount,due:r.data.checkDue,overdue:r.data.checkDue<today}));
 const priority=alerts.filter(a=>!['resolved','reviewed'].includes(a.data.state)).sort((a,b)=>(a.data.severity==='critical'?0:1)-(b.data.severity==='critical'?0:1)||a.created.localeCompare(b.created)).slice(0,5).map(a=>({id:a.id,agentId:a.data.agentId,title:a.data.title,summary:a.data.summary,action:a.data.action,ownerId:a.data.ownerId,ownerName:members.find(m=>m.id===a.data.ownerId)?.name||'نیازمند تعیین مسئول',due:a.data.due,severity:a.data.severity}));
 const inactive=kind==='daily'?[]:agents.flatMap(a=>{const days=rows.filter(r=>r.type==='sales_invoice'&&!r.data.openingId&&r.data.agentId===a.id).map(r=>r.data.day).sort(),unique=Array.from(new Set(days));if(unique.length<4)return [];const last=unique.at(-1)!,recent=unique.slice(-4),interval=Math.round((dayDiff(recent[1],recent[0])+dayDiff(recent[2],recent[1])+dayDiff(recent[3],recent[2]))/3),idleDays=dayDiff(today,last);return a.data.active&&idleDays>Math.max(14,interval*2)?[{agentId:a.id,name:a.data.name,lastPurchase:last,usualDays:interval,idleDays,reason:'وقفه بیشتر از دو برابر میانگین سه فاصله خرید اخیر؛ علت نیازمند پیگیری است.'}]:[];});
 const ranked=[...byAgent].sort((a,b)=>rial(a.netSales)>rial(b.netSales)?-1:1),positiveSales=total(byAgent,a=>positive(rial(a.netSales))),concentration=ranked.slice(0,5).map(a=>({agentId:a.id,name:a.name,netSales:a.netSales,shareBps:positiveSales>BigInt(0)?Number(positive(rial(a.netSales))*BigInt(10000)/BigInt(positiveSales)):null}));
 const coverageStart=rows.filter(r=>r.type==='sales_invoice'&&!r.data.openingId).map(r=>r.data.day).sort()[0]||null;
 const n=(v:string)=>rial(v).toLocaleString('fa-IR'),summary=[`در بازه ${formatDate(period.start)} تا ${formatDate(period.end)}، ${current.newOrders.toLocaleString('fa-IR')} سفارش جدید و ${current.invoices.toLocaleString('fa-IR')} فاکتور ثبت شده است.`,`فروش خالص ثبت‌شده ${n(current.netSales)} ریال و وصول خالص ثبت‌شده ${n(current.collections)} ریال است.`,`مطالبات معوق در زمان تهیه گزارش ${n(String(total(accounts,a=>a.overdue)))} ریال است؛ ${pipeline.filter(p=>p.late).length.toLocaleString('fa-IR')} سفارش از موعد تحویل گذشته است.`,priority.length?`${priority.length.toLocaleString('fa-IR')} مورد اولویت‌دار برای پیگیری مدیر مشخص شده است.`:'هشدار باز در داده‌های بررسی‌شده ثبت نشده است.'];
 const pastAlerts=alerts.filter(a=>localDay(a.created)<=period.end&&(!a.data.resolvedAt||localDay(a.data.resolvedAt)>=period.start)).map(a=>({id:a.id,title:a.data.title,state:a.data.state,ownerId:a.data.ownerId,lastAction:a.data.history?.at(-1)?.notes||'',resolvedAt:a.data.resolvedAt||''}));
 return {kind,...period,yearAgo:period.yearAgoStart?periodMetrics(rows,period.yearAgoStart,period.yearAgoEnd!):null,inactive,concentration,asOf:now.toISOString(),today,current,previous,comparisonComplete:false,coverageStart,summary,byAgent,products,team,pipeline,due,checksDue,priority,pastAlerts,totals:{debt:String(total(accounts,a=>a.debt)),credit:String(total(accounts,a=>a.credit)),overdue:String(total(accounts,a=>a.overdue)),pending:String(total(accounts,a=>a.pending)),uncollectedChecks:String(total(accounts,a=>a.uncollectedChecks))},notes:['فروش خالص = فاکتورهای دوره منهای برگشت تأییدشده در دوره؛ وصول خالص = رویدادهای وصول منهای برگشت پرداخت در دوره. افتتاحیه در گردش فروش/وصول شمرده نمی‌شود.','مانده، کارهای باز، تحقق اهداف و وضعیت هشدارها تصویر زمان تهیه گزارش‌اند. ارقام مقایسه فقط داده ثبت‌شده‌اند؛ کامل بودن سوابق دوره قبل تأیید نشده و درصد رشد قطعی اعلام نمی‌شود.','انتساب عملکرد به کارشناس بر اساس مسئول فعلی نماینده است؛ تغییر مسئول به معنی بازسازی مالکیت تاریخی نیست. سود، علت افت و فروش آتی برآورد نشده‌اند.']};
}
