/** Same scoped aggregates for UI and MCP; never a personnel ranking or causal verdict. */
export function serviceReport(all:any[],from:string,to:string){
 const cases=all.filter(c=>c.data.contactDay>=from&&c.data.contactDay<=to),faults:Record<string,any>={},people:Record<string,any>={},agents:Record<string,any>={};
 for(const c of cases){const d=c.data;for(const l of d.lines||[]){const key=l.partCode+'|'+(l.oldBatchId||'unknown'),p=faults[key]||={partCode:l.partCode,name:l.name,batchId:l.oldBatchId||'',quantity:0,serials:[]};p.quantity+=l.quantity;if(!p.serials.includes(d.serial))p.serials.push(d.serial);}
  for(const [map,key] of [[people,d.repairedByName],[agents,d.agentId||'office']] as [Record<string,any>,string][]){if(!key)continue;const p=map[key]||={key,cases:0,repaired:0,delivered:0,failedTest:0,rated:0,ratingTotal:0,days:0};p.cases++;if(d.repairedAt)p.repaired++;if(d.deliveredDay){p.delivered++;p.days+=(Date.parse(d.deliveredDay)-Date.parse(d.intake?.day||d.contactDay))/86400000;}if(d.tests?.some((t:any)=>!t.pass))p.failedTest++;if(d.confirmation?.rating>0){p.rated++;p.ratingTotal+=d.confirmation.rating;}}
 }
 const finish=(m:Record<string,any>)=>Object.values(m).map(p=>({...p,meanRating:p.rated?p.ratingTotal/p.rated:null,meanCalendarDays:p.delivered?p.days/p.delivered:null}));
 return {from,to,cases:cases.length,delivered:cases.filter(c=>c.data.deliveredDay).length,resolvedByPhone:cases.filter(c=>c.data.state==='resolved').length,returnedUnrepaired:cases.filter(c=>c.data.state==='returned').length,partsCostRial:cases.reduce((n:bigint,c:any)=>n+BigInt(c.data.internalPartsCost||0),BigInt(0)).toString(),faults:Object.values(faults).map(p=>({...p,deviceCount:p.serials.length,serials:undefined})),people:finish(people),agents:finish(agents),basis:'Cases with contact day in inclusive range. Calendar duration includes waiting for parts/customer. Fault counts are not failure rates; unknown batches are retained separately. Ratings show their response counts.'};
}
