export const shipmentDocumentKinds:Record<string,string>={proforma:'پروفرما',invoice:'اینویس',packing:'پکینگ لیست',green_sheet:'برگ سبز',permit:'مجوز واردات',registration:'ثبت سفارش',technical:'مشخصات فنی'};
export const shipmentStates:Record<string,string>={draft:'پیش‌نویس',registered:'ثبت سفارش اولیه',permitted:'مجوز واردات ثبت‌شده',loaded:'بارگیری و پکینگ واقعی',amended:'ثبت سفارش اصلاح‌شده'};
export const shipmentHelp='هر ردیف وزن خالص و ناخالص به کیلوگرم و حجم به مترمکعب دارد. در محموله چندکالایی، سهم واقعی هر ردیف را از پکینگ وارد کنید؛ وزن کل را برای هر کالا تکرار نکنید. پیش‌بینی از پکینگ‌های واقعی همان کالا، تأمین‌کننده، مشخصات و نوع بسته‌بندی است؛ قیمت پیش‌بینی نمی‌شود. ثبت مراحل در این سامانه جای ثبت در سامانه تجارت نیست.';
export function packingPrediction(shipments:any[],line:any){
 const samples=shipments.filter(s=>['loaded','amended'].includes(s.data.state)).flatMap(s=>(s.data.actual?.lines||[]).filter((l:any)=>l.linkId===line.linkId&&l.supplierSpecs===line.supplierSpecs&&l.generalSpecs===line.generalSpecs&&l.packaging===line.packaging&&l.unit===line.unit).map((l:any)=>({shipmentId:s.id,day:s.data.actual.day,...l}))).filter(l=>Number(l.quantity)>0&&Number(l.netKg)>0&&Number(l.grossKg)>=Number(l.netKg)&&Number(l.volumeM3)>0).sort((a,b)=>b.day.localeCompare(a.day)).slice(0,10);
 if(!samples.length)return {available:false,sampleCount:0,reason:'پکینگ واقعی با مشخصات و بسته‌بندی یکسان ثبت نشده است.'};
 const quantity=samples.reduce((n,l)=>n+Number(l.quantity),0),target=Number(line.quantity),estimate=(k:string)=>Number((samples.reduce((n,l)=>n+Number(l[k]),0)/quantity*target).toFixed(6));
 return {available:true,sampleCount:samples.length,method:'میانگین وزنی مقدار در آخرین ۱۰ پکینگ منطبق',netKg:estimate('netKg'),grossKg:estimate('grossKg'),volumeM3:estimate('volumeM3'),sources:samples.map(s=>({shipmentId:s.shipmentId,day:s.day,quantity:s.quantity,netKg:s.netKg,grossKg:s.grossKg,volumeM3:s.volumeM3})),range:Object.fromEntries(['netKg','grossKg','volumeM3'].map(k=>[k,{min:Number((Math.min(...samples.map(s=>Number(s[k])/Number(s.quantity)))*target).toFixed(6)),max:Number((Math.max(...samples.map(s=>Number(s[k])/Number(s.quantity)))*target).toFixed(6))}]))};
}
