import {storage} from './storage';
import {AccessError} from './authorization';
import {dayAt} from './duties';
import type {Session} from './permissions';
export const supplierTypes=['supplier','supplier_material','supplier_review'];
export const supplierRead=(u:Session)=>technicalAuthorities(u).length>0||u.isAdmin||!!u.permissions.supplyRoles?.some(r=>['ceo','engineering','finance','domestic','foreign','inventory'].includes(r))||!!u.permissions.flowRoles?.some(r=>['qc','inventory','procurement'].includes(r));
export const supplierManage=(u:Session)=>u.isAdmin||!!u.permissions.supplyRoles?.some(r=>['domestic','foreign','engineering'].includes(r))||!!u.permissions.flowRoles?.includes('procurement');
export const supplierQuality=(u:Session)=>technicalAuthorities(u).includes('quality');
export const supplierCommercial=(u:Session,route:string)=>u.isAdmin||!!u.permissions.supplyRoles?.some(r=>['ceo','finance','commerce_manager',route].includes(r));
export const supplierRoute=(u:Session,route:string)=>technicalAuthorities(u).length>0||u.isAdmin||!!u.permissions.supplyRoles?.some(r=>['ceo','engineering','finance','inventory',route].includes(r))||!!u.permissions.flowRoles?.some(r=>['qc','inventory','procurement'].includes(r));
export async function supplierRows(type:string){return (await storage().prepare('SELECT * FROM flow_entities WHERE type=? ORDER BY created,id').bind(type).all()).results.map((r:any)=>({...r,data:JSON.parse(r.data)}));}
export async function supplierEntity(id:string,type:string){const r:any=await storage().prepare('SELECT * FROM flow_entities WHERE id=? AND type=?').bind(id,type).first();if(!r)throw new AccessError('رکورد مرتبط یافت نشد.',404);return {...r,data:JSON.parse(r.data)};}
export function technicalAuthorities(u:Session){const p=u.permissions,internal=!p.salesAgentId&&!p.serviceAgentId&&!p.hospitalCenterId&&!p.salesRoles?.includes('agent')&&!p.serviceRoles?.includes('agent');return internal?['engineering','quality'].filter(r=>u.isAdmin||(r==='engineering'?p.supplyRoles?.includes('engineering'):p.flowRoles?.includes('qc')||p.qmsRoles?.some(x=>['qa','qc'].includes(x)))):[];}
export function technicalBlock(e:any){const held=Object.entries(e?.data?.technicalControls||{}).find(([,v]:any)=>v.held);return held?'توقف فنی '+(e.type==='material'?'کالا':'تأمین‌کننده این کالا')+': '+(held[1] as any).reason:'';}
export async function checkPurchaseTechnical(materialId:string,linkId='',expected?:{specs?:string;designVersion?:number;supplierSpecs?:string}){
 const material=await supplierEntity(materialId,'material'),link=linkId?await supplierEntity(linkId,'supplier_material'):null;
 if(link&&link.data.materialId!==material.id)throw new AccessError('منبع تأمین متعلق به این کالا نیست.',409);
 const reason=technicalBlock(material)||technicalBlock(link);if(reason)throw new AccessError(reason,409);
 if(expected&&((expected.specs||'')!==(material.data.specs||'')||(expected.designVersion||0)!==(material.data.designVersion||0)||expected.supplierSpecs!==undefined&&expected.supplierSpecs!==(link?.data.supplierSpecs||'')))throw new AccessError('طراحی یا مشخصات تغییر کرده؛ دور استعلام یا انتخاب خرید تازه لازم است.',409);
 if(!link&&(await supplierRows('supplier_material')).some(l=>l.data.materialId===material.id))throw new AccessError('منبع خرید باید با شناسه تأمین‌کننده همین کالا مشخص شود؛ نام متنی برای کنترل محدودیت کافی نیست.',409);
 return {material,...(link?{link}:{})};
}
export function qualification(link:any,supplier:any,material:any,amount=0){const d=link.data;const technical=technicalBlock(material)||technicalBlock(link);if(technical)return technical;if(!supplier.data.active)return 'تأمین‌کننده غیرفعال است';if(!['approved','conditional'].includes(d.status))return 'صلاحیت خرید تأیید نشده است';if(!d.reviewDue||d.reviewDue<dayAt())return 'موعد ارزیابی مجدد گذشته است';if(d.specs!==(material.data.specs||'')||d.unit!==material.data.unit)return 'مشخصات کالا تغییر کرده؛ ارزیابی تازه لازم است';if(d.supplierRevision!==supplier.revision)return 'پرونده تأمین‌کننده تغییر کرده؛ ارزیابی تازه لازم است';if(d.status==='conditional'&&(!d.maxQuantity||amount>d.maxQuantity))return 'مقدار از سقف خرید مشروط بیشتر است';return '';}
export async function supplierEvidenceBlock(link:any){for(const id of link.data.requiredDocumentIds||[]){let e:any;try{e=await supplierEntity(id,'supplier_document');}catch{return 'مدرک الزامی موجود نیست';}if(e.data.linkId!==link.id||e.data.state!=='approved'||e.data.expiresOn&&e.data.expiresOn<dayAt())return 'مدرک الزامی معتبر نیست: '+e.data.title;}if((await supplierRows('supplier_capa')).some(e=>e.data.linkId===link.id&&e.data.state!=='closed'&&e.data.holdPurchase))return 'خرید به دلیل اقدام اصلاحی باز متوقف است';return '';}
export async function checkSupplierPurchase(linkId:string,materialId:string,route:string,amount:number){const link=await supplierEntity(linkId,'supplier_material'),supplier=await supplierEntity(link.data.supplierId,'supplier'),material=await supplierEntity(materialId,'material');if(link.data.materialId!==materialId||supplier.data.route!==route)throw new AccessError('تأمین‌کننده با کالا یا مسیر خرید منطبق نیست.',400);const reason=qualification(link,supplier,material,amount)||await supplierEvidenceBlock(link);if(reason)throw new AccessError(reason,409);return {link,supplier,material};}
export async function supplierMetrics(link:any){
 const orders=(await supplierRows('purchase_order')).filter(o=>o.data.supplierLinkId===link.id&&o.data.state!=='cancelled'),receipts=(await supplierRows('receipt')).filter(r=>orders.some(o=>o.id===r.data.purchaseOrderId)),checked=receipts.filter(r=>r.data.state!=='pending_qc');
 const inspected=checked.reduce((n,r)=>n+(r.data.accepted||0)+(r.data.rejected||0),0),rejected=checked.reduce((n,r)=>n+(r.data.rejected||0),0);
 const completed=orders.filter(o=>receipts.filter(r=>r.data.purchaseOrderId===o.id).reduce((n,r)=>n+r.data.quantity,0)>=o.data.quantity),onTime=completed.filter(o=>{const rs=receipts.filter(r=>r.data.purchaseOrderId===o.id).sort((a,b)=>(a.data.day||a.created).localeCompare(b.data.day||b.created));let n=0;for(const r of rs){n+=r.data.quantity;if(n>=o.data.quantity)return (r.data.day||r.created.slice(0,10))<=(o.data.promisedEta||o.data.eta);}return false;}).length;
 return {orders:orders.length,receipts:receipts.length,inspectedQuantity:inspected,rejectedQuantity:rejected,quality:inspected?Math.round(10000*(inspected-rejected)/inspected)/100:null,completedOrders:completed.length,onTimeOrders:onTime,delivery:completed.length?Math.round(10000*onTime/completed.length)/100:null,latestPurchase:orders.at(-1)?.created||null};
}
export async function buildSupplierTargets(lines:any[],existing:any[]=[]){
 const links=await supplierRows('supplier_material'),suppliers=await supplierRows('supplier');const targets:any[]=[];
 for(const l of lines){if(!links.some(x=>x.data.materialId===l.materialId))continue;for(const route of l.routes||[]){const old=existing.filter(t=>t.partCode===l.partCode&&t.round===l.round&&t.route===route);if(old.length){targets.push(...old);continue;}
 const candidates=links.filter(x=>x.data.materialId===l.materialId).flatMap(link=>{const s=suppliers.find(s=>s.id===link.data.supplierId);return s&&s.data.active&&s.data.route===route&&!['suspended','rejected'].includes(link.data.status)?[{link,s}]:[];});
 if(!candidates.length)targets.push({partCode:l.partCode,round:l.round,route,missing:true});
 for(const {link,s} of candidates)targets.push({partCode:l.partCode,round:l.round,route,linkId:link.id,supplierId:s.id,name:s.data.name,contact:s.data.contact,phone:s.data.phone,email:s.data.email,messenger:s.data.messenger,status:link.data.status,quantity:l.shortage,unit:l.unit,specs:l.specs||'',materialRevision:l.materialRevision});
 }}return targets;
}
export function rfqComplete(plan:any,line:any,quotes:any[]){const targets=(plan.data.supplierTargets||[]).filter((t:any)=>t.partCode===line.partCode&&t.round===line.round);return !targets.length||targets.every((t:any)=>!t.missing&&quotes.some(q=>q.data.planId===plan.id&&q.data.partCode===line.partCode&&q.data.round===line.round&&q.data.supplierLinkId===t.linkId&&q.data.route===t.route&&q.data.quantity===line.shortage));}
export function supplierWork(plan:any,steps:any[],quotes:any[],lines:any[]){const result:any[]=[];for(const s of steps){if(!s.key.startsWith('quote:')){result.push(s);continue;}const [,code,round,route]=s.key.split(':'),targets=(plan.data.supplierTargets||[]).filter((t:any)=>t.partCode===code&&String(t.round)===round&&t.route===route);if(!targets.length){result.push(s);continue;}for(const t of targets){if(t.missing){result.push({...s,key:s.key+':missing',title:'معرفی منبع تأمین برای '+code,instructions:'برای این کالا در مسیر '+route+' منبع فعال ثبت نشده است. پرونده تأمین‌کنندگان کالا را تکمیل و فهرست استعلام را تازه کنید.'});continue;}const line=lines.find(l=>l.partCode===code);if(quotes.some(q=>q.data.planId===plan.id&&q.data.partCode===code&&q.data.round===t.round&&q.data.supplierLinkId===t.linkId&&q.data.quantity===line?.shortage))continue;result.push({...s,key:s.key+':'+t.supplierId,title:s.title+' از '+t.name,instructions:'استعلام از '+t.name+'؛ مسئول: '+t.contact+'؛ تلفن: '+t.phone+'؛ ایمیل: '+t.email+'؛ پیام‌رسان: '+t.messenger+'\nکد کالا: '+code+'؛ مقدار: '+((line?.shortage||0)/1000)+' '+t.unit+'؛ مشخصات: '+t.specs+'\nموعد نیاز: '+plan.data.needBy+'؛ قیمت، ارز، هزینه‌های جانبی، زمان تحویل، شرایط پرداخت، اعتبار پیشنهاد و مرجع مدرک را ثبت کنید. اگر پاسخ ندارید، نتیجه و سابقه پیگیری را ثبت کنید. این متن مجوز سفارش نیست.'});}}
 return result;
}
