import {storage} from './storage';
import {AccessError} from './authorization';
import {dayAt,addDay} from './duties';
import {supplierEntity,supplierRows,supplierRead,supplierRoute,supplierManage,supplierQuality,supplierCommercial} from './suppliers';
import type {Session} from './permissions';
export const sqFail=(m:string,s=400):never=>{throw new AccessError(m,s)};
export async function supplierScope(u:Session,supplierId:string,linkId=''){if(!supplierRead(u))sqFail('دسترسی پرونده تأمین‌کننده ندارید.',403);const supplier=await supplierEntity(supplierId,'supplier');if(!supplierRoute(u,supplier.data.route))sqFail('دسترسی مسیر تأمین ندارید.',403);const link=linkId?await supplierEntity(linkId,'supplier_material'):null;if(link&&link.data.supplierId!==supplier.id)sqFail('ارتباط کالا متعلق به این تأمین‌کننده نیست.');return {supplier,link};}
export const documentVisible=(u:Session,d:any,route:string)=>d.visibility!=='commercial'||supplierCommercial(u,route);
export function publicDocument(e:any){const {objectKey,uploadSignature,...data}=e.data;return {...e,data};}
export async function qualityMember(id:string,route:string,role:'owner'|'reviewer'){const m:any=await storage().prepare("SELECT * FROM app_members WHERE id=? AND status='active'").bind(id).first();if(!m)sqFail('مسئول فعال انتخاب کنید.');const p=JSON.parse(m.permissions),u={isAdmin:false,permissions:p} as Session;if(!supplierRoute(u,route)||(role==='reviewer'?!supplierQuality(u):!supplierManage(u)&&!supplierQuality(u)))sqFail('مسئول انتخاب‌شده مجوز این مرحله را ندارد.');return m;}
export async function qualityDirectory(route:string){const rows=(await storage().prepare("SELECT id,name,permissions FROM app_members WHERE status='active' ORDER BY name").all()).results as any[];return rows.flatMap(m=>{const u={isAdmin:false,permissions:JSON.parse(m.permissions)} as Session;return supplierRoute(u,route)&&(supplierManage(u)||supplierQuality(u))?[{id:m.id,name:m.name,reviewer:supplierQuality(u),commercial:supplierCommercial(u,route)}]:[];});}
export async function supplierQualityTasks(entity:any,now=new Date().toISOString()){
 const db=storage(),d=entity.data,today=dayAt(new Date(now)),steps:any[]=[],prefix='supplier-quality:'+entity.id+':';
 if(entity.type==='supplier_document'){
  if(d.state==='pending')steps.push({key:'review',owner:d.reviewerId,supervisor:d.ownerId,due:addDay(entity.created.slice(0,10),7),title:'بررسی مدرک '+d.title});
  if(d.state==='approved'&&d.expiresOn&&d.expiresOn<=addDay(today,30))steps.push({key:'renew',owner:d.ownerId,supervisor:d.reviewerId,due:d.expiresOn,title:'تمدید مدرک '+d.title});
 }else if(d.state!=='closed')steps.push({key:d.state+':'+(d.cycle||1),owner:d.state==='verification'?d.reviewerId:d.ownerId,supervisor:d.state==='verification'?d.ownerId:d.reviewerId,due:d.state==='verification'?d.verificationDue:d.responseDue,title:(d.state==='verification'?'بررسی اثربخشی: ':'پیگیری اقدام اصلاحی: ')+d.title});
 const previous=(await db.prepare('SELECT * FROM duty_runs WHERE template_id LIKE ?').bind(prefix+'%').all()).results as any[],statements:D1PreparedStatement[]=[];
 const active=new Set(steps.map(s=>prefix+s.key+':'+s.owner));
 for(const r of previous)if(!active.has(r.id)&&!['completed','cancelled'].includes(r.state))statements.push(db.prepare("UPDATE duty_runs SET state='completed',revision=revision+1,updated=? WHERE id=? AND revision=?").bind(now,r.id,r.revision));
 for(const s of steps){const owner:any=await db.prepare("SELECT id,permissions FROM app_members WHERE id=? AND status='active'").bind(s.owner).first();if(!owner)continue;const key=prefix+s.key,id=key+':'+s.owner,prior=previous.find(r=>r.id===id),data={...(prior?JSON.parse(prior.data):{}),title:s.title,instructions:'پرونده «مدارک و اقدامات اصلاحی» تأمین‌کننده '+d.supplierName+' را باز کنید. مرجع: '+entity.id+'؛ '+(entity.type==='supplier_capa'?'شرح مشکل: '+d.description:'نسخه '+d.version+' · '+d.filename)+'؛ نتیجه را در همان پرونده ثبت کنید.',sourceSection:JSON.parse(owner.permissions).supplyRoles?.length?'sourcing':'flow',supplierQualityWorkflow:true,supplierId:d.supplierId,supplierRoute:d.route,documentVisibility:d.visibility||'quality',remindHours:24,escalateHours:48,evidence:'text',history:prior?JSON.parse(prior.data).history:[],answer:prior?JSON.parse(prior.data).answer:'',extensionRequested:''};
 const due=s.due+'T16:00:00+03:30';if(prior&&['open','blocked'].includes(prior.state)&&prior.due===due&&prior.data===JSON.stringify(data))continue;
 statements.push(prior?db.prepare("UPDATE duty_runs SET state=CASE WHEN state IN ('completed','cancelled') THEN 'open' ELSE state END,due=?,data=?,revision=revision+1,updated=? WHERE id=? AND revision=?").bind(due,JSON.stringify(data),now,id,prior.revision):db.prepare("INSERT INTO duty_runs(id,template_id,period,assignee,supervisor,due,state,data,revision,created,updated) VALUES(?,?,?,?,?,?,'open',?,1,?,?)").bind(id,key,'workflow',s.owner,s.supervisor||null,due,JSON.stringify(data),now,now));}
 return statements;
}
export async function syncSupplierQuality(){for(const type of ['supplier_document','supplier_capa'])for(const e of await supplierRows(type)){const statements=await supplierQualityTasks(e);if(!statements.length)continue;const db=storage(),id=crypto.randomUUID(),now=new Date().toISOString();try{await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'supplier_quality_tasks','{}','scheduler',?,CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN 1 ELSE 0 END)").bind(id,now,e.id,e.revision),...statements]);}catch(err){if(!/constraint|guard/i.test(String(err)))throw err;}}}
