import {storage} from './storage';
import type {Session} from './permissions';
import {normalizePosition} from './duty-starter-install';
import {transportRoles} from './transport-contract';
/** One-time, atomic consolidation; keep archived definitions and all histories. */
export async function unifyTransportPositions(u:Session){
 if(!u.isAdmin)return;const db=storage(),marker='transport-position-unification:v1';if(await db.prepare('SELECT id FROM flow_entities WHERE id=?').bind(marker).first())return;
 const now=new Date().toISOString(),op=crypto.randomUUID(),canonical='transport-position:driver',rows=(await db.prepare("SELECT * FROM flow_entities WHERE type='position'").all()).results.map((r:any)=>({...r,data:JSON.parse(r.data)}));
 const aliases=['کارشناس تدارکات / راننده','کارشناس تدارکات و حمل‌ونقل','تدارکات خدمات — تجهیزات خانگی','تدارکات خدمات — تجهیزات بیمارستانی','تدارکات خدمات — خانگی','تدارکات خدمات — بیمارستانی'].map(normalizePosition);
 const sources=rows.filter((p:any)=>p.id===canonical||['service-position:home:logistics','service-position:hospital:logistics'].includes(p.id)||aliases.includes(normalizePosition(p.data.name)));
 const target=sources.find((p:any)=>p.id===canonical);if(!target)throw new Error('Install canonical transport position before consolidation');
 const others=sources.filter((p:any)=>p.id!==canonical),oldIds=new Set(others.map((p:any)=>p.id)),members=[...new Set(sources.flatMap((p:any)=>p.data.members||[]))];
 const merged={...target.data,name:transportRoles.driver,unit:'تدارکات و حمل‌ونقل',members,mission:'انجام مأموریت‌های تخصیص‌یافته فروش، خدمات خانگی، خدمات بیمارستانی و دریافت خرید در یک کارتابل.',responsibilities:'دریافت و کنترل ظاهری بسته؛ ثبت تحویل، بارنامه و رهگیری؛ حمل دستگاه و قطعات خدمات خانگی و بیمارستانی؛ دریافت کالای خریداری‌شده؛ تحویل مستند به مسئول مقصد.',handoffs:'فروش، خدمات خانگی، خدمات بیمارستانی، بازرگانی داخلی و خارجی، انبار، نماینده و باربری',previousProfile:target.data,mergedPositions:others.map((p:any)=>({id:p.id,name:p.data.name,supervisor:p.data.supervisor||'',profile:p.data}))};
 const checks:D1PreparedStatement[]=[],writes:D1PreparedStatement[]=[];
 const put=(r:any,data:any)=>{checks.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN guard ELSE 0 END WHERE id=?').bind(r.id,r.revision,op));writes.push(db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=? AND revision=?').bind(JSON.stringify(data),now,r.id,r.revision));};
 put(target,merged);for(const p of others)put(p,{...p.data,active:false,mergedInto:canonical,mergedAt:now});
 const dependent=(await db.prepare("SELECT * FROM flow_entities WHERE type IN ('duty_template','inbox_thread')").all()).results.map((r:any)=>({...r,data:JSON.parse(r.data)}));
 for(const r of dependent){if(r.type==='duty_template'&&oldIds.has(r.data.positionId))put(r,{...r.data,positionId:canonical,mergedFromPosition:r.data.positionId});if(r.type==='inbox_thread'&&r.data.recipientType==='position'&&oldIds.has(r.data.recipientId))put(r,{...r.data,recipientId:canonical,recipientName:transportRoles.driver,mergedFromPosition:r.data.recipientId});}
 const accounts=(await db.prepare('SELECT id,permissions,revision FROM app_members').all()).results as any[];let accountsUpdated=0;
 for(const a of accounts){const p=JSON.parse(a.permissions);if(p.serviceAgentId||!p.serviceRoles?.includes('logistics')&&!p.flowRoles?.includes('logistics'))continue;const serviceRoles=(p.serviceRoles||[]).filter((x:string)=>x!=='logistics'),permissions={...p,transportRoles:[...new Set([...(p.transportRoles||[]),'driver'])],flowRoles:(p.flowRoles||[]).filter((x:string)=>x!=='logistics'),serviceRoles,serviceDomains:serviceRoles.length?p.serviceDomains||[]:[]};checks.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN EXISTS(SELECT 1 FROM app_members WHERE id=? AND revision=?) THEN guard ELSE 0 END WHERE id=?').bind(a.id,a.revision,op));writes.push(db.prepare('UPDATE app_members SET permissions=?,revision=revision+1,updated=? WHERE id=? AND revision=?').bind(JSON.stringify(permissions),now,a.id,a.revision),db.prepare('INSERT INTO access_audit(id,actor,target,action,before,after,at) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,a.id,'unify_transport_permissions',a.permissions,JSON.stringify(permissions),now));accountsUpdated++;}
 const summary={canonical,positions:others.map((p:any)=>p.id),members:members.length,accountsUpdated,at:now};try{await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'unify_transport','{}',?,?,1)").bind(op,u.userId,now),...checks,...writes,db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,'transport_migration',?,1,?,?)").bind(marker,JSON.stringify(summary),now,now),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,canonical,'unify_transport_positions',JSON.stringify(summary),now)]);}catch(e){if(await db.prepare('SELECT id FROM flow_entities WHERE id=?').bind(marker).first())return;throw e;}
}
