"use client";
export type TransportDraft={id:string;accountId:string;missionId:string;missionCode:string;createdAt:number;kind:'operation'|'file';payload?:Record<string,any>;file?:File;purpose?:string;revision?:number};
const expiry=7*24*60*60*1000,maxBytes=100*1024*1024;
function openDatabase():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open('nafasyar-transport-drafts',1);request.onupgradeneeded=()=>request.result.createObjectStore('drafts',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(Error('ذخیرهٔ پیش‌نویس در این مرورگر ممکن نیست.'))})}
async function transaction<T>(mode:IDBTransactionMode,work:(store:IDBObjectStore,set:(value:T)=>void)=>void):Promise<T>{const db=await openDatabase();return new Promise((resolve,reject)=>{const tx=db.transaction('drafts',mode);let value:T;work(tx.objectStore('drafts'),next=>{value=next});tx.oncomplete=()=>{db.close();resolve(value)};tx.onerror=tx.onabort=()=>{db.close();reject(Error('ذخیره یا خواندن پیش‌نویس انجام نشد؛ فضای مرورگر را بررسی کنید.'))}})}
export async function transportDrafts(accountId:string){return transaction<TransportDraft[]>('readwrite',(store,set)=>{const req=store.getAll();req.onsuccess=()=>{const rows=req.result as TransportDraft[];for(const row of rows)if(Date.now()-row.createdAt>expiry)store.delete(row.id);set(rows.filter(row=>row.accountId===accountId&&Date.now()-row.createdAt<=expiry))}})}
export async function saveTransportDraft(row:TransportDraft){
 if(!row.accountId||!row.missionId||row.kind==='file'&&(!row.file||row.file.size>10*1024*1024))throw Error('یک مأموریت و فایل حداکثر ۱۰ مگابایت لازم است.');
 const db=await openDatabase();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('drafts','readwrite'),store=tx.objectStore('drafts'),req=store.getAll();let reason='ذخیره در این مرورگر انجام نشد.';req.onsuccess=()=>{const all=req.result as TransportDraft[];if(all.some(r=>r.id===row.id&&r.accountId!==row.accountId)){reason='این پیش‌نویس متعلق به حساب دیگری است.';tx.abort();return}for(const r of all)if(Date.now()-r.createdAt>expiry)store.delete(r.id);const rows=all.filter(r=>r.accountId===row.accountId&&r.id!==row.id&&Date.now()-r.createdAt<=expiry);if(rows.length>=30||rows.reduce((n,r)=>n+(r.file?.size||0),0)+(row.file?.size||0)>maxBytes){reason='حداکثر ۳۰ پیش‌نویس و ۱۰۰ مگابایت؛ موارد ارسال‌شده را حذف کنید.';tx.abort();return}store.put(row)};tx.oncomplete=()=>{db.close();resolve()};tx.onerror=tx.onabort=()=>{db.close();reject(Error(reason))}});
}
export async function removeTransportDraft(accountId:string,id:string){return transaction<void>('readwrite',(store,set)=>{const req=store.get(id);req.onsuccess=()=>{if(req.result?.accountId===accountId)store.delete(id);set(undefined)}})}
