import {salesRep,salesStaff} from './sales';
import {storage} from './storage';
import type {Session} from './permissions';
import {memberId} from './duties';
import {fail,list,entity,domainAccess,isAgent,role} from './after-sales';
import {warehouseAccess,flowRole} from './material-flow';
import {unifyTransportPositions} from './transport-positions';
import {transportStates,transportRoles} from './transport-contract';
export const transportManager=(u:Session)=>u.isAdmin||!!u.permissions.transportRoles?.includes('manager');
export const transportDriver=(u:Session)=>!!u.permissions.transportRoles?.includes('driver')||!!u.permissions.flowRoles?.includes('logistics');
export const transportFinance=(u:Session)=>u.isAdmin||!isAgent(u)&&u.permissions.finance==='write';
export const purchaseTransportRequester=(u:Session,s?:any)=>!isAgent(u)&&(!!u.permissions.supplyRoles?.includes('inventory')||!!u.permissions.supplyRoles?.includes(s?.data.route)||!s&&!!u.permissions.supplyRoles?.some(r=>['domestic','foreign'].includes(r)));
export const purchaseReceiver=(p:any)=>!p.serviceAgentId&&(p.supplyRoles?.includes('inventory')||p.flowRoles?.includes('inventory')&&(!p.warehouses||p.warehouses.includes('quarantine')));
export function transportUnit(d:any){return d.kind==='sale'?'فروش':d.kind==='purchase_order'?(d.purchaseRoute==='foreign'?'بازرگانی خارجی':'بازرگانی داخلی'):d.domain==='hospital'?'خدمات بیمارستانی':'خدمات خانگی';}
export const transportEntry=(u:Session)=>u.isAdmin||salesRep(u)||salesStaff(u)||!!u.permissions.transportRoles?.length||!!u.permissions.flowRoles?.some(r=>['inventory','sales','logistics'].includes(r))||!!u.permissions.serviceRoles?.length||u.permissions.finance==='write'||purchaseTransportRequester(u);
export async function transportCanSee(u:Session,m:any,mid?:string){
 if(u.isAdmin||transportManager(u))return true;const d=m.data;mid=mid??await memberId(u);
 if(salesRep(u)){const a:any=await storage().prepare("SELECT data FROM flow_entities WHERE type='sales_agent' AND id=?").bind(u.permissions.salesAgentId).first();return !!a&&JSON.parse(a.data).active&&d.kind==='sale'&&d.salesAgentId===u.permissions.salesAgentId;}
 if(isAgent(u)){const a:any=await storage().prepare("SELECT data FROM flow_entities WHERE type='as_agent' AND id=?").bind(u.permissions.serviceAgentId).first();return !!a&&JSON.parse(a.data).active&&d.agentId===u.permissions.serviceAgentId&&domainAccess(u,d.domain);}
 if(transportFinance(u))return true;
 if(transportDriver(u)&&mid===d.driverId)return true;
 if(d.kind==='purchase_order')return purchaseReceiver(u.permissions)||purchaseTransportRequester(u,{data:{route:d.purchaseRoute}});
 if(d.kind==='sale')return warehouseAccess(u,'finished')||salesStaff(u);
 return domainAccess(u,d.domain)&&(['manager','coordinator'].some(r=>role(u,r))||d.kind==='as_shipment'&&role(u,'inventory')||mid===d.receiverId&&(d.kind==='as_case'?role(u,'intake'):role(u,'inventory')));
}
export async function transportAccess(u:Session,id:string){const m=await entity(id,'transport');if(!await transportCanSee(u,m))fail('مأموریت پیدا نشد یا دسترسی ندارید.',404);return m;}
export async function transportPublic(u:Session,m:any){const d={...m.data,requestingUnit:transportUnit(m.data)};delete d.sourceSnapshot;const finances=transportManager(u)||transportFinance(u);if(!finances){const mid=await memberId(u);d.expenses=isAgent(u)||salesRep(u)?[]:(d.expenses||[]).filter((e:any)=>e.byMember===mid);d.history=(d.history||[]).filter((h:any)=>!['expense','expense_review'].includes(h.mode)&&!(h.mode==='file'&&h.purpose==='expense'));}if(isAgent(u)||salesRep(u)){delete d.driverId;delete d.driverName;delete d.vehicleId;delete d.vehicleName;delete d.receiverId;d.history=(d.history||[]).map(({actor,actorName,...h}:any)=>h);}return {...m,data:d};}
export async function sourceSummary(s:any){const d=s.data;let agentId=d.agentId||'',domain=d.domain||'',name='',phone='',address='',items:any[]=[];
 if(s.type==='purchase_order'){name=d.supplier;const receipts=(await list('receipt')).filter(r=>r.data.purchaseOrderId===s.id);const committed=receipts.reduce((n,r)=>n+(r.data.state==='pending_qc'?r.data.quantity:r.data.accepted),0);const remaining=Math.max(0,d.quantity-committed);items=[{partCode:d.partCode,unit:d.unit,quantity:remaining/1000}];}
 else if(s.type==='sale'){const p=await entity(d.partyId,'party');agentId=p.data.serviceAgentId||'';if(agentId){const a=await entity(agentId,'as_agent');if(!a.data.active)agentId='';else domain=a.data.domain;}name=d.recipient?.name||p.data.name;phone=d.recipient?.phone||'';address=d.recipient?.address||'';for(const id of d.deviceIds){const r:any=await storage().prepare("SELECT payload FROM records WHERE id=? AND kind='device'").bind(id).first();if(r){const p=JSON.parse(r.payload);items.push({deviceId:id,serial:p.code,model:p.model,quantity:1});}}}
 else {if(agentId){const a=await entity(agentId,'as_agent');name=a.data.name;phone=a.data.phone;address=a.data.address;}if(s.type==='as_shipment')items=d.lines.map((l:any)=>({batchId:l.batchId,partCode:l.partCode,quantity:l.quantity/1000}));else if(s.type==='as_claim')items=[{serial:d.serial,partCode:d.partCode,batchId:d.oldBatchId||'',quantity:d.quantity/1000}];else {name=d.customerName||d.customer||name;phone=d.phone||phone;items=[{serial:d.serial,model:d.model||'',quantity:1}];}}
 return {salesAgentId:s.type==='sale'?d.salesAgentId||'':'',key:s.type+':'+s.id,id:s.id,kind:s.type,purchaseRoute:s.type==='purchase_order'?d.route:'',agentId,domain,name,phone,address,items,state:d.state,revision:s.revision};
}
export function canRequest(u:Session,s:any){if(transportManager(u))return true;if(s.type==='purchase_order')return purchaseTransportRequester(u,s)||purchaseReceiver(u.permissions);if(s.type==='sale')return warehouseAccess(u,'finished')||salesStaff(u);if(!domainAccess(u,s.data.domain))return false;if(isAgent(u))return ['as_claim','as_case'].includes(s.type)&&s.data.agentId===u.permissions.serviceAgentId;return ['coordinator','manager',...(s.type==='as_shipment'?['inventory']:['intake'])].some(r=>role(u,r));}
export function sourceReady(s:any){return s.type==='purchase_order'?['issued','paid','preparing','shipped'].includes(s.data.state):s.type==='sale'?s.data.state==='in_transit':s.type==='as_shipment'?s.data.state==='prepared':s.type==='as_claim'?['sent','awaiting_return'].includes(s.data.state):!['closed','returned','delivered'].includes(s.data.state);}
export async function transportFiles(u:Session,m:any){const files=(await list('transport_file')).filter(f=>f.data.missionId===m.id);return files.filter(f=>f.data.purpose!=='expense'||!isAgent(u)&&!salesRep(u)&&(transportManager(u)||transportFinance(u)||f.data.actor===u.userId)).map(f=>{const {objectKey,...data}=f.data;return {...f,data};});}
export async function installTransportPositions(u:Session){if(!u.isAdmin)return;const now=new Date().toISOString(),db=storage();for(const [key,name] of Object.entries(transportRoles)){const id='transport-position:'+key,data={name,unit:'تدارکات و حمل‌ونقل',active:true,members:[],supervisor:'',mission:key==='manager'?'تخصیص و پیگیری حمل‌های رفت و برگشت':'تحویل‌گیری و تحویل مستند محموله‌های مأموریت',responsibilities:key==='manager'?'تخصیص راننده و خودرو؛ پیگیری موعد و مدارک؛ رفع مغایرت؛ هماهنگی انبار، فروش و خدمات.':'دریافت بسته؛ ثبت وضعیت ظاهری؛ تحویل باربری و بارنامه؛ دریافت برگشتی؛ تحویل به مسئول مقصد.',authorityBoundaries:'تأیید حمل جای تأیید گارانتی، داغی، موجودی یا پرداخت نیست؛ دسترسی مستقل حساب لازم است.',reportingTo:key==='manager'?'مدیرعامل':'مسئول تدارکات و حمل‌ونقل',handoffs:'انبار، فروش، خدمات، نماینده، باربری و مالی',metrics:'تأخیر مأموریت، مدارک ناقص، مغایرت دریافت و زمان تحویل'};await db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) SELECT ?,'position',?,1,?,? WHERE NOT EXISTS(SELECT 1 FROM flow_entities WHERE type='position' AND (id=? OR (?='manager' AND json_extract(data,'$.name')=?)))").bind(id,JSON.stringify(data),now,now,id,key,name).run();}await unifyTransportPositions(u);}
export async function syncTransportTasks(){const db=storage(),now=new Date().toISOString(),members=(await db.prepare("SELECT id,name,subject,permissions FROM app_members WHERE status='active'").all()).results as any[];for(const m of await list('transport')){const d=m.data,prefix='transport:'+m.id+':',wanted=new Set<string>(),stmts:D1PreparedStatement[]=[];const old=(await db.prepare('SELECT * FROM duty_runs WHERE template_id LIKE ?').bind(prefix+'%').all()).results as any[];
 const candidates=members.filter(a=>{const p=JSON.parse(a.permissions);if(['cancelled','delivered'].includes(d.state)&&!d.missingDocuments)return false;if(d.state==='requested'||d.state==='disputed')return p.transportRoles?.includes('manager');if(['assigned','collected'].includes(d.state)||d.missingDocuments)return a.id===d.driverId&&(p.transportRoles?.includes('driver')||p.flowRoles?.includes('logistics'));if(['carrier','offered'].includes(d.state))return d.inbound?a.id===d.receiverId:p.salesAgentId===d.salesAgentId&&!!d.salesAgentId||p.serviceAgentId===d.agentId&&!!d.agentId||p.transportRoles?.includes('manager');return false;});
 for(const a of candidates){const p=JSON.parse(a.permissions),u:Session={userId:'local:'+a.id,name:a.name,email:'',isAdmin:false,permissions:p};if(!await transportCanSee(u,m,a.id))continue;const tid=prefix+d.state+':'+(d.missingDocuments?'docs:':'')+a.id;wanted.add(tid);const existing=old.find(t=>t.id===tid);if(existing&&!['completed','cancelled'].includes(existing.state)&&existing.due===d.due+'T12:30:00Z')continue;const data={title:(d.missingDocuments?'تکمیل بارنامه':transportStates[d.state])+' · '+d.code+' · '+transportUnit(d),instructions:'مأموریت '+d.code+' را در تدارکات باز کنید و مرحله واقعی را ثبت کنید. پاسخ متنی جای دریافت یا بارنامه نیست.',evidence:'text',positionName:'تدارکات و حمل‌ونقل',sourceSection:'transport',transportWorkflow:true,transportMissionId:m.id,remindHours:24,escalateHours:24,history:[],answer:'',extensionRequested:''};stmts.push(db.prepare("INSERT INTO duty_runs(id,template_id,period,assignee,supervisor,due,state,data,revision,created,updated) VALUES(?,?,?, ?,NULL,?,'open',?,1,?,?) ON CONFLICT(id) DO UPDATE SET due=excluded.due,state=CASE WHEN duty_runs.state IN ('completed','cancelled') THEN 'open' ELSE duty_runs.state END,revision=duty_runs.revision+1,updated=excluded.updated").bind(tid,prefix+d.state,'workflow',a.id,d.due+'T12:30:00Z',JSON.stringify(data),now,now));}
 for(const t of old)if(!wanted.has(t.id)&&!['completed','cancelled'].includes(t.state))stmts.push(db.prepare("UPDATE duty_runs SET state='completed',revision=revision+1,updated=? WHERE id=? AND revision=?").bind(now,t.id,t.revision));if(stmts.length)try{await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'transport_tasks','{}','scheduler',?,CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN 1 ELSE 0 END)").bind(crypto.randomUUID(),now,m.id,m.revision),...stmts]);}catch(e){if(!/constraint/i.test(String(e)))throw e;}}
}
