import {financialWorkflowRole, type FinancialWorkflowRole} from './financial-workflow-roles';
import {storage} from './storage';
import {treasuryRows,tToday,treasuryNeedsCeo,treasuryPaymentAuthorized} from './treasury';
import {trainingContext} from './training-context';
export async function syncTreasuryTasks(date=new Date()){
 if(trainingContext.getStore())return {generated:0,missingOwners:[]};
 const db=storage(),rows=await treasuryRows(),today=tToday(),now=date.toISOString(),members=(await db.prepare('SELECT id,subject,status,permissions FROM app_members ORDER BY id').all()).results as any[];
 const owners=(role:FinancialWorkflowRole)=>members.filter(m=>m.status==='active'&&financialWorkflowRole(JSON.parse(m.permissions),m.id,rows,role)).map(m=>m.id);
 const roles={treasury:owners('treasury'),manager:owners('manager'),accountant:owners('accountant'),ceo:owners('ceo')},desired=new Set<string>(),missingOwners=new Set<string>(),existing=(await db.prepare("SELECT * FROM duty_runs WHERE id LIKE 'treasury:%'").all()).results as any[],statements:any[]=[];let generated=0;
 const job=(r:any,key:string,role:keyof typeof roles,title:string,due:string)=>{if(!roles[role].length)missingOwners.add(role);for(const assignee of roles[role]){const id='treasury:'+r.id+':'+key+':'+assignee,old=existing.find(t=>t.id===id),data={treasuryWorkflow:true,recordId:r.id,workflowRole:role,sourceSection:'treasury',sourceId:r.id,title:title+' — '+(r.data.title||r.data.number||r.data.filename),instructions:'مرحله واقعی را در خزانه‌داری انجام دهید؛ پاسخ وظیفه جای تأیید یا اجرا نیست.',evidence:'مدرک واقعی و نتیجه بررسی مستقل',history:old?JSON.parse(old.data).history||[]:[],answer:old?JSON.parse(old.data).answer||'':''},deadline=(old&&key==='review'?old.due:due+'T09:00:00+03:30');desired.add(id);
  if(!old){statements.push(db.prepare("INSERT INTO duty_runs(id,template_id,period,assignee,supervisor,due,state,data,revision,created,updated) VALUES(?,?,?,?,?,?,'open',?,1,?,?)").bind(id,id,today,assignee,roles.manager[0]||'@admin',deadline,JSON.stringify(data),now,now));generated++;}
  else if(!['open','blocked'].includes(old.state)||old.due!==deadline||old.supervisor!==(roles.manager[0]||'@admin'))statements.push(db.prepare("UPDATE duty_runs SET state='open',due=?,data=?,supervisor=?,revision=revision+1,updated=? WHERE id=?").bind(deadline,JSON.stringify(data),roles.manager[0]||'@admin',now,id));
  if(due<=today){for(const recipient of new Set([assignee,...(due<today?roles.manager:[])]))statements.push(db.prepare('INSERT OR IGNORE INTO duty_notices(id,task_id,recipient,phase,message,created) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),id,recipient,'treasury:'+today,(due<today?'معوق: ':'موعد اقدام: ')+data.title,now));}
 }};
 for(const r of rows){if(r.type==='treasury_account'&&r.data.state==='review')job(r,'review','manager','تأیید حساب و مانده اولیه',today);
  if(r.type==='treasury_request'){if(r.data.state==='review')job(r,'review','manager','بررسی درخواست و حساب مقصد',today);if(treasuryNeedsCeo(r.data))job(r,'ceo','ceo','مجوز نهایی پرداخت به خزانه‌دار',r.data.due);if(['approved','partial'].includes(r.data.state)&&treasuryPaymentAuthorized(r.data))job(r,'execute','treasury','پیگیری اجرای دریافت / پرداخت',r.data.due);}
  if(r.type==='treasury_check'){if(r.data.state==='review')job(r,'review','manager','بررسی چک',today);if(r.data.state==='issued'&&(r.data.direction==='in'||rows.some(q=>q.id===r.data.requestId&&treasuryPaymentAuthorized(q.data))))job(r,'settle','treasury','پیگیری سررسید و نتیجه واقعی چک',r.data.due);}
  if(r.type==='treasury_expense'&&r.data.state==='review')job(r,'review','manager','بررسی مدرک هزینه تنخواه',today);
  if(r.type==='treasury_statement'&&r.data.rows.some((b:any)=>!b.match))job(r,'reconcile','accountant','تطبیق مستقل صورتحساب',r.data.to);
 }
 for(const old of existing.filter(t=>!desired.has(t.id)&&!['completed','cancelled'].includes(t.state))){const d=JSON.parse(old.data),authorized=(roles[d.workflowRole as keyof typeof roles]||[]).includes(old.assignee);statements.push(db.prepare('UPDATE duty_runs SET state=?,revision=revision+1,updated=? WHERE id=?').bind(authorized?'completed':'cancelled',now,old.id));}
 if(statements.length){const op=crypto.randomUUID();const guards=rows.filter(r=>r.type==='position'||r.type.startsWith('treasury_')).map(r=>db.prepare('UPDATE inventory_operations SET guard=CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN 1 ELSE 0 END WHERE id=?').bind(r.id,r.revision,op));const taskGuards=existing.map(t=>db.prepare('UPDATE inventory_operations SET guard=CASE WHEN EXISTS(SELECT 1 FROM duty_runs WHERE id=? AND revision=?) THEN 1 ELSE 0 END WHERE id=?').bind(t.id,t.revision,op));await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'treasury_tasks','{}','scheduler',?,CASE WHEN (SELECT json_group_array(json_object('id',id,'subject',subject,'status',status,'permissions',permissions)) FROM (SELECT id,subject,status,permissions FROM app_members ORDER BY id))=? THEN 1 ELSE 0 END)").bind(op,now,JSON.stringify(members)),...guards,...taskGuards,...statements]);}
 return {generated,missingOwners:[...missingOwners]};
}
