export type WorkCalendar={weekdays:number[];start:string;end:string;holidays:string[]};
export const defaultCalendar:WorkCalendar={weekdays:[6,0,1,2,3],start:'08:00',end:'17:00',holidays:[]};
const minute=(s:string)=>Number(s.slice(0,2))*60+Number(s.slice(3));
export function localParts(at:Date){const local=new Date(at.getTime()+210*60000);return {day:local.toISOString().slice(0,10),weekday:local.getUTCDay(),minute:local.getUTCHours()*60+local.getUTCMinutes()};}
export function workWindow(day:string,c:WorkCalendar){const weekday=new Date(day+'T12:00:00Z').getUTCDay();if(!c.weekdays.includes(weekday)||c.holidays.includes(day))return null;return [Date.parse(day+'T'+c.start+':00+03:30'),Date.parse(day+'T'+c.end+':00+03:30')];}
export function workingNow(at:Date,c:WorkCalendar){const p=localParts(at),w=workWindow(p.day,c);return !!w&&at.getTime()>=w[0]&&at.getTime()<w[1];}
export function workingMinutes(from:Date,to:Date,c:WorkCalendar):number{if(to<from)return -workingMinutes(to,from,c);let day=localParts(from).day,total=0;for(let i=0;i<3700&&day<=localParts(to).day;i++){const w=workWindow(day,c);if(w)total+=Math.max(0,Math.min(to.getTime(),w[1])-Math.max(from.getTime(),w[0]))/60000;day=new Date(Date.parse(day+'T12:00:00Z')+86400000).toISOString().slice(0,10);}return total;}
export function addWorkingMinutes(from:Date,n:number,c:WorkCalendar){let day=localParts(from).day,at=from.getTime();for(let i=0;i<3700;i++){const w=workWindow(day,c);if(w){const start=Math.max(at,w[0]),free=Math.max(0,(w[1]-start)/60000);if(free>=n)return new Date(start+n*60000).toISOString();n-=free;}day=new Date(Date.parse(day+'T12:00:00Z')+86400000).toISOString().slice(0,10);at=Date.parse(day+'T00:00:00+03:30');}throw Error('تقویم کاری برای مهلت انتخاب‌شده کافی نیست.');}
export function validCalendar(c:any):c is WorkCalendar{return !!c&&Array.isArray(c.weekdays)&&c.weekdays.length>0&&c.weekdays.every((n:any)=>Number.isInteger(n)&&n>=0&&n<=6)&&typeof c.start==='string'&&typeof c.end==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(c.start)&&/^([01]\d|2[0-3]):[0-5]\d$/.test(c.end)&&minute(c.end)>minute(c.start)&&Array.isArray(c.holidays)&&c.holidays.length<=366&&c.holidays.every((d:any)=>typeof d==='string'&&/^\d{4}-\d\d-\d\d$/.test(d)&&Number.isFinite(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d);}
