import {requireAccess,checkOrigin,accessResponse,AccessError} from '@/lib/authorization';
import {storage} from '@/lib/storage';
import {taskAccess} from '@/lib/duties';
import {firmwareBucket,boundedBody} from '@/lib/firmware-storage';
import {sha256} from '@/lib/firmware';
import {validateFinanceFile,MAX_FINANCE_BYTES} from '@/lib/finance-control';
const present=(r:any)=>{const {object_key,...safe}=r;return safe};
export async function GET(request:Request){try{const u=await requireAccess(),q=new URL(request.url).searchParams,task=q.get('task')||'';await taskAccess(task,u);const db=storage(),id=q.get('id');if(!id)return Response.json({files:(await db.prepare('SELECT * FROM duty_files WHERE task_id=? ORDER BY created DESC').bind(task).all()).results.map(present)},{headers:{'Cache-Control':'private, no-store'}});
 const f:any=await db.prepare('SELECT * FROM duty_files WHERE id=? AND task_id=?').bind(id,task).first();if(!f)throw new AccessError('فایل پیدا نشد.',404);const object=await firmwareBucket().get(f.object_key);if(!object)throw new Error('missing');const bytes=await object.arrayBuffer();if(await sha256(bytes)!==f.sha256)throw new Error('integrity');return new Response(bytes,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':"attachment; filename=task-file; filename*=UTF-8''"+encodeURIComponent(f.filename).replace(/['()*]/g,c=>'%'+c.charCodeAt(0).toString(16)),'X-Content-Type-Options':'nosniff','Content-Security-Policy':"sandbox; default-src 'none'",'Cache-Control':'private, no-store'}});
 }catch(e){return accessResponse(e)||Response.json({error:'دریافت مدرک انجام نشد.'},{status:503})}}
export async function POST(request:Request){let key='',id='';try{checkOrigin(request);const u=await requireAccess(),q=new URL(request.url).searchParams,task=q.get('task')||'',t=await taskAccess(task,u,true);if(!['open','blocked'].includes(t.state))throw new AccessError('فقط وظیفه باز مدرک می‌پذیرد.',400);id=q.get('requestId')||'';if(!/^[a-f0-9-]{36}$/i.test(id))throw new AccessError('شناسه فایل معتبر نیست.',400);
 const ct=request.headers.get('content-type')||'',bytes=await boundedBody(request,MAX_FINANCE_BYTES+128000),form=await new Response(bytes,{headers:{'Content-Type':ct}}).formData(),file=form.get('file');if(!file||typeof file==='string'||form.getAll('file').length!==1)throw new AccessError('یک فایل انتخاب کنید.',400);try{validateFinanceFile(file.name,file.size)}catch(e){throw new AccessError((e as Error).message,400)}const buffer=await file.arrayBuffer(),hash=await sha256(buffer),db=storage(),old:any=await db.prepare('SELECT * FROM duty_files WHERE id=?').bind(id).first();if(old){if(old.task_id!==task||old.sha256!==hash||old.filename!==file.name||old.uploaded_by!==u.userId)throw new AccessError('شناسه فایل تکراری است.',409);return Response.json({file:present(old)})}
 key='duty-files/'+id+'/'+crypto.randomUUID();await firmwareBucket().put(key,buffer,{httpMetadata:{contentType:'application/octet-stream'},sha256:hash});const now=new Date().toISOString();const f={id,task_id:task,object_key:key,filename:file.name,byte_size:buffer.byteLength,sha256:hash,uploaded_by:u.userId,created:now};
 await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'duty_file','{}',?,?,CASE WHEN EXISTS(SELECT 1 FROM duty_runs WHERE id=? AND revision=? AND state IN ('open','blocked')) THEN 1 ELSE 0 END)").bind(crypto.randomUUID(),u.userId,now,task,t.revision),db.prepare('INSERT INTO duty_files(id,task_id,object_key,filename,byte_size,sha256,uploaded_by,created) VALUES(?,?,?,?,?,?,?,?)').bind(id,task,key,file.name,buffer.byteLength,hash,u.userId,now),db.prepare('UPDATE duty_runs SET revision=revision+1,updated=? WHERE id=?').bind(now,task),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,task,'duty_file',JSON.stringify(present(f)),now)]);return Response.json({file:present(f)},{status:201});
 }catch(e){if(key&&id)try{const linked:any=await storage().prepare('SELECT * FROM duty_files WHERE id=?').bind(id).first();if(linked?.object_key===key)return Response.json({file:present(linked)},{status:201});await firmwareBucket().delete(key)}catch{}return accessResponse(e)||Response.json({error:'مدرک ذخیره نشد؛ فهرست را تازه کنید.'},{status:409})}}
