import {requireAccess, can, checkOrigin, accessResponse, AccessError} from "@/lib/authorization";
import {asciiDigits} from "@/lib/batch-number";
import {storage} from "@/lib/storage";
import {fields,validate,editable,type Kind} from "@/lib/model";
export async function GET(){try{const user=await requireAccess();const readable=user.permissions.read;if(!readable.length)return Response.json({records:[]},{headers:{"Cache-Control":"no-store"}});const db=storage();const rows=await db.prepare("SELECT * FROM records WHERE kind IN ("+readable.map(()=>"?").join(",")+") ORDER BY created DESC, id").bind(...readable).all();return Response.json({records:rows.results.map((r:any)=>({id:r.id,kind:r.kind,created:r.created,data:JSON.parse(r.payload)}))},{headers:{"Cache-Control":"no-store"}});}catch(e){console.error(e);const denied=accessResponse(e);if(denied)return denied;return Response.json({error:"دریافت اطلاعات ممکن نشد؛ دوباره تلاش کنید."},{status:503});}}
export async function POST(request:Request){
 if(request.headers.get("origin")&&request.headers.get("origin")!==new URL(request.url).origin)return Response.json({error:"درخواست نامعتبر است."},{status:403});
 try{checkOrigin(request);const body=await request.json() as {kind:Kind;data:Record<string,string>};const kind=body.kind as Kind;if(kind==="distribution"||kind==="firmware")throw new AccessError("ثبت این اطلاعات از بخش اختصاصی آن انجام می‌شود.",400);const actor=await requireAccess(kind,"write");const data=body.data; if(!data||typeof data!=="object"||Array.isArray(data)||Object.values(data).some(v=>typeof v!=="string"))throw new Error("اطلاعات معتبر نیست.");if(kind==="product")data.code=asciiDigits(data.code||"").trim().toUpperCase();let productPayload:string|undefined;const db=storage();if(kind==="device"){if(!can(actor,"product","read"))throw new AccessError("برای ثبت دستگاه، مدیر باید دسترسی مشاهده محصولات را به حساب شما بدهد.",403);const product:any=await db.prepare("SELECT payload FROM records WHERE id=? AND kind='product'").bind(data.product||"").first();if(!product)throw new Error("ابتدا محصول دستگاه را از فهرست انتخاب کنید.");productPayload=product.payload;const p=JSON.parse(product.payload);if(p.status!=="فعال")throw new Error("برای محصول متوقف‌شده نمی‌توان دستگاه جدید ثبت کرد.");data.model=p.model;data.productName=p.name;data.productCode=p.code;data.warrantyMonths=p.warrantyMonths;}if(kind==="batch"){data.code=asciiDigits(data.code||"").trim().toUpperCase();if(data.partCode)data.partCode=asciiDigits(data.partCode).trim();}validate(kind,data);if(kind==="event"&&!actor.isAdmin&&!actor.permissions.eventStages.includes(data.stage))throw new AccessError("ثبت این مرحله برای واحد شما مجاز نیست.",403);
 for(const f of fields[kind])if(f.ref&&data[f.key]){const ref:any=await db.prepare("SELECT kind,payload FROM records WHERE id=?").bind(data[f.key]).first();if(!ref||ref.kind!==f.ref)throw new Error("رکورد مرتبط یافت نشد.");if((kind==="event"&&data.stage==="مصرف قطعه"&&f.key==="batch"||kind==="service"&&f.key==="replacement")&&JSON.parse(ref.payload).status!=="تأیید")throw new Error("فقط بچ تأییدشده قابل مصرف است.");}
 if(kind==="service"&&data.batch){const linked=await db.prepare("SELECT id FROM records WHERE (kind='event' AND json_extract(payload,'$.device')=? AND json_extract(payload,'$.batch')=?) OR (kind='service' AND json_extract(payload,'$.device')=? AND json_extract(payload,'$.replacement')=?)").bind(data.device,data.batch,data.device,data.batch).first();if(!linked)throw new Error("بچ انتخابی در سابقه این دستگاه ثبت نشده است.");}
 const id=kind==="batch"||kind==="device"||kind==="product"?kind+":"+data.code.trim().toUpperCase():crypto.randomUUID();
 const row={id,kind,data,created:new Date().toISOString()};const insert=kind==="device"?db.prepare("INSERT INTO records(id,kind,payload,created) SELECT ?,?,?,? FROM records WHERE id=? AND kind='product' AND payload=?").bind(id,kind,JSON.stringify(data),row.created,data.product,productPayload):db.prepare("INSERT INTO records(id,kind,payload,created) VALUES(?,?,?,?)").bind(id,kind,JSON.stringify(data),row.created);const result=await db.batch([insert,db.prepare("INSERT INTO access_audit(id,actor,target,action,after,at) SELECT ?,?,?,?,?,? FROM records WHERE id=?").bind(crypto.randomUUID(),actor.userId,id,"create_record",JSON.stringify(row),row.created,id)]);if(!result[0].meta.changes)throw new AccessError("مشخصات محصول تغییر کرده است؛ صفحه را تازه کنید و دوباره ثبت کنید.",409);return Response.json({record:row},{status:201});
 }catch(e){console.error(e);const denied=accessResponse(e);if(denied)return denied;const message=e instanceof Error?e.message:"";const duplicate=message.includes("UNIQUE constraint");const database=/D1|SQLITE|Database|binding/.test(message);return Response.json({error:duplicate?"این سریال، کد محصول یا کد بچ قبلاً ثبت شده است. برای بچ، «بررسی مجدد» را بزنید و پیشنهاد جدید را اعمال کنید.":database?"ذخیره انجام نشد؛ دوباره تلاش کنید.":message||"اطلاعات معتبر نیست."},{status:duplicate?409:database?503:400});}
}
export async function PATCH(request:Request){
 if(request.headers.get("origin")&&request.headers.get("origin")!==new URL(request.url).origin)return Response.json({error:"درخواست نامعتبر است."},{status:403});
 try{checkOrigin(request);const actor=await requireAccess();const {id,data,previous}=await request.json() as {id:string;data:Record<string,string>;previous:string};if(typeof id!=="string"||!data||Object.values(data).some(v=>typeof v!=="string"))throw new Error("اطلاعات معتبر نیست.");const db=storage();const old:any=await db.prepare("SELECT * FROM records WHERE id=?").bind(id).first();if(old&&!can(actor,old.kind as Kind,"write"))throw new AccessError("ویرایش این بخش برای شما مجاز نیست.",403);if(!old||!editable[old.kind as Kind])throw new Error("این رکورد قابل به‌روزرسانی نیست.");validate(old.kind as Kind,data);const oldData=JSON.parse(old.payload);for(const key of new Set([...Object.keys(data),...Object.keys(oldData)]))if(!editable[old.kind as Kind]!.includes(key)&&data[key]!==oldData[key])throw new Error("اطلاعات هویتی و ارتباطات رکورد قابل تغییر نیست.");if(old.payload!==previous)return Response.json({error:"این پرونده تغییر کرده است؛ صفحه را تازه کنید."},{status:409});for(const key of ["batch","device"])if(data[key]!==JSON.parse(old.payload)[key])throw new Error("ارتباط پرونده قابل تغییر نیست.");const results=await db.batch([db.prepare("INSERT INTO access_audit(id,actor,target,action,before,after,at) SELECT ?,?,?,?,?,?,? FROM records WHERE id=? AND payload=?").bind(crypto.randomUUID(),actor.userId,id,"update_record",previous,JSON.stringify(data),new Date().toISOString(),id,previous),db.prepare("UPDATE records SET payload=? WHERE id=? AND payload=?").bind(JSON.stringify(data),id,previous)]);const updated=results[1];if(!updated.meta.changes)return Response.json({error:"این پرونده تغییر کرده است؛ صفحه را تازه کنید."},{status:409});return Response.json({record:{id,kind:old.kind,created:old.created,data}});}catch(e){console.error(e);const denied=accessResponse(e);if(denied)return denied;return Response.json({error:e instanceof Error&&!/D1|SQLITE/.test(e.message)?e.message:"به‌روزرسانی انجام نشد."},{status:400});}
}
