import {storage} from "@/lib/storage";
import {fields,validate,editable,type Kind} from "@/lib/model";
export async function GET(){try{const db=storage();const rows=await db.prepare("SELECT * FROM records ORDER BY created DESC, id").all();return Response.json({records:rows.results.map((r:any)=>({id:r.id,kind:r.kind,created:r.created,data:JSON.parse(r.payload)}))},{headers:{"Cache-Control":"no-store"}});}catch(e){console.error(e);return Response.json({error:"دریافت اطلاعات ممکن نشد؛ دوباره تلاش کنید."},{status:503});}}
export async function POST(request:Request){
 if(request.headers.get("origin")&&request.headers.get("origin")!==new URL(request.url).origin)return Response.json({error:"درخواست نامعتبر است."},{status:403});
 try{const body=await request.json() as {kind:Kind;data:Record<string,string>};const kind=body.kind as Kind;const data=body.data; if(!data||typeof data!=="object"||Array.isArray(data)||Object.values(data).some(v=>typeof v!=="string"))throw new Error("اطلاعات معتبر نیست.");validate(kind,data);
 const db=storage();for(const f of fields[kind])if(f.ref&&data[f.key]){const ref:any=await db.prepare("SELECT kind,payload FROM records WHERE id=?").bind(data[f.key]).first();if(!ref||ref.kind!==f.ref)throw new Error("رکورد مرتبط یافت نشد.");if((kind==="event"&&data.stage==="مصرف قطعه"&&f.key==="batch"||kind==="service"&&f.key==="replacement")&&JSON.parse(ref.payload).status!=="تأیید")throw new Error("فقط بچ تأییدشده قابل مصرف است.");}
 if(kind==="service"&&data.batch){const linked=await db.prepare("SELECT id FROM records WHERE (kind='event' AND json_extract(payload,'$.device')=? AND json_extract(payload,'$.batch')=?) OR (kind='service' AND json_extract(payload,'$.device')=? AND json_extract(payload,'$.replacement')=?)").bind(data.device,data.batch,data.device,data.batch).first();if(!linked)throw new Error("بچ انتخابی در سابقه این دستگاه ثبت نشده است.");}
 const id=kind==="batch"||kind==="device"?kind+":"+data.code.trim().toUpperCase():crypto.randomUUID();
 const row={id,kind,data,created:new Date().toISOString()};await db.prepare("INSERT INTO records(id,kind,payload,created) VALUES(?,?,?,?)").bind(id,kind,JSON.stringify(data),row.created).run();return Response.json({record:row},{status:201});
 }catch(e){console.error(e);const message=e instanceof Error?e.message:"";const duplicate=message.includes("UNIQUE constraint");const database=/D1|SQLITE|Database|binding/.test(message);return Response.json({error:duplicate?"این سریال یا کد بچ قبلاً ثبت شده است.":database?"ذخیره انجام نشد؛ دوباره تلاش کنید.":message||"اطلاعات معتبر نیست."},{status:database?503:400});}
}
export async function PATCH(request:Request){
 if(request.headers.get("origin")&&request.headers.get("origin")!==new URL(request.url).origin)return Response.json({error:"درخواست نامعتبر است."},{status:403});
 try{const {id,data,previous}=await request.json() as {id:string;data:Record<string,string>;previous:string};if(typeof id!=="string"||!data||Object.values(data).some(v=>typeof v!=="string"))throw new Error("اطلاعات معتبر نیست.");const db=storage();const old:any=await db.prepare("SELECT * FROM records WHERE id=?").bind(id).first();if(!old||!editable[old.kind as Kind])throw new Error("این رکورد قابل به‌روزرسانی نیست.");validate(old.kind as Kind,data);const oldData=JSON.parse(old.payload);for(const key of new Set([...Object.keys(data),...Object.keys(oldData)]))if(!editable[old.kind as Kind]!.includes(key)&&data[key]!==oldData[key])throw new Error("اطلاعات هویتی و ارتباطات رکورد قابل تغییر نیست.");if(old.payload!==previous)return Response.json({error:"این پرونده تغییر کرده است؛ صفحه را تازه کنید."},{status:409});for(const key of ["batch","device"])if(data[key]!==JSON.parse(old.payload)[key])throw new Error("ارتباط پرونده قابل تغییر نیست.");const updated=await db.prepare("UPDATE records SET payload=? WHERE id=? AND payload=?").bind(JSON.stringify(data),id,previous).run();if(!updated.meta.changes)return Response.json({error:"این پرونده تغییر کرده است؛ صفحه را تازه کنید."},{status:409});return Response.json({record:{id,kind:old.kind,created:old.created,data}});}catch(e){console.error(e);return Response.json({error:e instanceof Error&&!/D1|SQLITE/.test(e.message)?e.message:"به‌روزرسانی انجام نشد."},{status:400});}
}
