import {checkOrigin,accessResponse} from '@/lib/authorization';
import {storage} from '@/lib/storage';
import {boundedBody} from '@/lib/firmware-storage';
import {sha256} from '@/lib/firmware';
import {reminderModes,reminderLinks,reminderTriggers,reminderConditions} from '@/lib/reminder-contract';
import {reminderActor,reminderFail as fail,reminderDecode,reminderSources,reminderTarget,reminderPublic,reminderMembers,reminderGuard} from '@/lib/reminders';
const json=(d:unknown)=>Response.json(d,{headers:{'Cache-Control':'private, no-store','Vary':'Cookie, Authorization'}});
const text=(v:any,max:number)=>{if(typeof v!=='string'||v.length>max)fail('متن معتبر با طول مجاز وارد کنید.');return v.trim()};
const date=(v:any,previous?:string)=>{const s=text(v,40),n=Date.parse(s),day=s.slice(0,10);if(!/^\d{4}-\d{2}-\d{2}T([01]\d|2[0-3]):[0-5]\d(:[0-5]\d(\.\d{3})?)?(Z|[+-](0\d|1[0-4]):[0-5]\d)$/.test(s)||!Number.isFinite(n)||new Date(day).toISOString().slice(0,10)!==day||n<=Date.now()&&n!==Date.parse(previous||''))fail('تاریخ و ساعت آینده با منطقه زمانی لازم است.');return new Date(n).toISOString()};
function account(r:Request,u:any){const a=r.headers.get('x-assistant-account');if(a&&a!==u.userId)fail('حساب ورود تغییر کرده است؛ صفحه را تازه کنید.',409)}
export async function GET(request:Request){try{const u=await reminderActor();account(request,u);const q=new URL(request.url).searchParams;
 if(q.get('view')==='links'){const kind=q.get('kind')||'none';if(!Object.hasOwn(reminderLinks,kind))fail('فرایند معتبر نیست.');const query=(q.get('query')||'').trim().toLocaleLowerCase(),links=(await reminderSources(u,kind,undefined,query)).filter(r=>r.title.toLocaleLowerCase().includes(query));return json({accountId:u.userId,links:links.slice(0,200),limited:links.length>200});}
 const raw=(await storage().prepare("SELECT * FROM personal_reminders WHERE owner=? ORDER BY CASE WHEN json_extract(data,'$.state')='active' THEN 0 ELSE 1 END,updated DESC,id DESC LIMIT 500").bind(u.userId).all()).results.map(reminderDecode),targets=new Map(),sources=new Map(),rows=[];for(const r of raw)rows.push(await reminderPublic(r,u,targets,sources));return json({accountId:u.userId,reminders:rows,limited:rows.length===500});
 }catch(e){return accessResponse(e)||Response.json({error:'یادآورها دریافت نشدند؛ نسخه پایگاه داده را بررسی کنید.'},{status:503})}}
export async function POST(request:Request){try{checkOrigin(request);const u=await reminderActor();account(request,u);const b=JSON.parse(new TextDecoder().decode(await boundedBody(request,16000)));
 if(!b||Array.isArray(b)||Object.keys(b).some(k=>!['id','confirmed','mode','reminderId','revision','title','notes','dueAt','trigger','linkType','linkId','eventField','eventCondition','eventValue'].includes(k)))fail('فیلد درخواست معتبر نیست.');if(b.confirmed!==true||!Object.hasOwn(reminderModes,b.mode)||typeof b.id!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(b.id))fail('نوع عملیات، تأیید و شناسه معتبر لازم است.');
 const db=storage(),members=await reminderMembers(),signature=await sha256(new TextEncoder().encode(JSON.stringify(b)).buffer),previous:any=await db.prepare('SELECT actor,payload,kind FROM inventory_operations WHERE id=?').bind(b.id).first();if(previous){if(previous.actor!==u.userId||previous.payload!==signature||previous.kind!=='personal_reminder')fail('شناسه تکراری نامعتبر است.',409);return json({saved:true,repeated:true,accountId:u.userId,id:b.reminderId||b.id});}
 const raw:any=b.reminderId?await db.prepare('SELECT * FROM personal_reminders WHERE id=? AND owner=?').bind(b.reminderId,u.userId).first():null;if(b.reminderId&&!raw)fail('یادآور در دسترس نیست.',404);if(!raw&&b.mode!=='save')fail('یادآور را انتخاب کنید.');if(b.revision!==(raw?.revision||0))fail('یادآور تغییر کرده است؛ تازه‌سازی کنید.',409);
 const old=raw?reminderDecode(raw):null,id=raw?.id||b.id,now=new Date().toISOString();let d:any=old?structuredClone(old.data):{ownerEmail:u.email,state:'active',alerts:[]};
 if(b.mode==='save'){
 if(old&&d.state!=='active')fail('یادآور بسته شده است.');const title=text(b.title,200);if(!title)fail('عنوان لازم است.');const notes=text(b.notes||'',4000),dueAt=b.trigger==='event'&&!b.dueAt?null:date(b.dueAt,d.dueAt);if(!Object.hasOwn(reminderTriggers,b.trigger)||!Object.hasOwn(reminderLinks,b.linkType))fail('نوع یادآوری و پیوند معتبر لازم است.');const linkId=b.linkType==='none'?'':text(b.linkId,200),target=b.linkType==='none'?null:await reminderTarget(u,{linkType:b.linkType,linkId});if(b.linkType!=='none'&&!target)fail('پرونده مرتبط در دسترس نیست.',404);
 let eventField='',eventCondition='',eventValue='';if(b.trigger==='event'){if(!target)fail('فرایند و پرونده رویداد را انتخاب کنید.');eventField=text(b.eventField,60);eventCondition=text(b.eventCondition,20);if(!Object.hasOwn(target!.fields,eventField)||!Object.hasOwn(reminderConditions,eventCondition))fail('شرط رویداد معتبر نیست.');if(eventCondition==='equals'){eventValue=text(b.eventValue,200);if(!eventValue||eventField==='updated'||eventField.endsWith('At'))fail('برای این مشخصه شرط تغییر را انتخاب کنید.');if(!Object.hasOwn(target!.fields[eventField].options,eventValue))fail('مرحله را از گزینه‌های همین فرایند انتخاب کنید.');}}
 const resetEvent=d.linkType!==b.linkType||d.linkId!==linkId||d.trigger!==b.trigger||d.eventField!==eventField||d.eventCondition!==eventCondition||d.eventValue!==eventValue;d={...d,title,notes,dueAt,trigger:b.trigger,linkType:b.linkType,linkId,entityType:target?.type||'',eventField,eventCondition,eventValue,alerts:resetEvent?[]:d.alerts.filter((a:any)=>a.kind==='event'||d.dueAt===dueAt),...(resetEvent?{eventAt:null,eventPending:null}:{})};
 if(target){const live:any=await (target.type==='duty_run'?db.prepare('SELECT revision FROM duty_runs WHERE id=?').bind(target.id):db.prepare('SELECT revision FROM flow_entities WHERE id=? AND type=?').bind(target.id,target.type)).first();if(!live)fail('پرونده تغییر کرده است.',409);d.targetRevision=live.revision;}

 }else if(b.mode==='snooze'){if(d.state!=='active')fail('یادآور بسته شده است.');d.dueAt=date(b.dueAt);d.alerts=d.alerts.filter((a:any)=>a.kind==='event').map((a:any)=>({...a,readAt:now}));}
 else if(b.mode==='seen'){d.alerts=d.alerts.map((a:any)=>({...a,readAt:a.readAt||now}));}
 else{if(d.state!=='active')fail('یادآور قبلاً بسته شده است.');d.state=b.mode==='done'?'done':'cancelled';d.completedAt=now;d.alerts=d.alerts.map((a:any)=>({...a,readAt:a.readAt||now}));}
 const writes=[db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'personal_reminder',?,?,?,1)").bind(b.id,signature,u.userId,now),reminderGuard(db,b.id,members)];
 if(b.mode==='save'&&d.linkType!=='none')writes.push(d.entityType==='duty_run'?db.prepare('UPDATE inventory_operations SET guard=CASE WHEN EXISTS(SELECT 1 FROM duty_runs WHERE id=? AND revision=?) THEN guard ELSE 0 END WHERE id=?').bind(d.linkId,d.targetRevision,b.id):db.prepare('UPDATE inventory_operations SET guard=CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND type=? AND revision=?) THEN guard ELSE 0 END WHERE id=?').bind(d.linkId,d.entityType,d.targetRevision,b.id));
 if(old)writes.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN EXISTS(SELECT 1 FROM personal_reminders WHERE id=? AND owner=? AND revision=?) THEN guard ELSE 0 END WHERE id=?').bind(id,u.userId,old.revision,b.id));
 else writes.push(db.prepare("UPDATE inventory_operations SET guard=CASE WHEN (SELECT COUNT(*) FROM personal_reminders WHERE owner=? AND json_extract(data,'$.state')='active')<200 THEN guard ELSE 0 END WHERE id=?").bind(u.userId,b.id));
 writes.push(old?db.prepare('UPDATE personal_reminders SET data=?,revision=revision+1,updated=? WHERE id=? AND owner=?').bind(JSON.stringify(d),now,id,u.userId):db.prepare('INSERT INTO personal_reminders(id,owner,data,revision,created,updated) VALUES(?,?,?,1,?,?)').bind(id,u.userId,JSON.stringify(d),now,now));writes.push(db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(b.id,u.userId,id,'personal_reminder_'+b.mode,JSON.stringify({state:d.state}),now));await db.batch(writes);return json({saved:true,id,accountId:u.userId});
 }catch(e){return accessResponse(e)||Response.json({error:'ثبت تأیید نشد؛ یادآورها را تازه کنید و با همان درخواست دوباره تلاش کنید.'},{status:409})}}
