import {requireAccess,checkOrigin,accessResponse} from '@/lib/authorization';
import {firmwareBucket,boundedBody} from '@/lib/firmware-storage';
import {storage} from '@/lib/storage';
import {leadMembers} from '@/lib/sales-leads';
import {qactor,qrows,qfind,qwrite,qfail,qr,qid,qsignature,qretry,qcommit,qpresent} from '@/lib/qms';
import {QMS_PART_SIZE} from '@/lib/qms-contract';
import {qheaders} from '../route';
const hash=async(bytes:Uint8Array)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes as Uint8Array<ArrayBuffer>))).map(x=>x.toString(16).padStart(2,'0')).join('');
async function partsFor(fileId:string){return (await storage().prepare("SELECT * FROM flow_entities WHERE type='qms_part' AND json_extract(data,'$.fileId')=? ORDER BY CAST(json_extract(data,'$.index') AS INTEGER)").bind(fileId).all()).results.map((r:any)=>({...r,data:JSON.parse(r.data)}));}
async function context(){const u=await requireAccess(),members=await leadMembers(),a=await qactor(u,members),rows=await qrows();return {u,members,a,rows};}
function writable(file:any,parent:any,a:any){if(!qwrite(parent.data,a)||file.data.createdBy!==a.id)qfail('فقط بارگذار مجاز می‌تواند ادامه دهد.',403);if(parent.data.state!=='draft'||file.data.state!=='uploading')qfail('بارگذاری یا پرونده دیگر قابل تغییر نیست.',409);}
export async function POST(request:Request){try{checkOrigin(request);const {u,members,a,rows}=await context(),b=JSON.parse(new TextDecoder().decode(await boundedBody(request,5000))),op=qid(b.id);if(b.confirmed!==true)qfail('تأیید لازم است.');const signature=await qsignature(b);let file=b.fileId?qfind(rows,b.fileId,a,'qms_file'):null,parent=qfind(rows,file?.data.parentId||qr(b.parentId,200),a);if(!qwrite(parent.data,a))qfail('مجوز بارگذاری لازم است.',403);if(await qretry(u,op,signature))return Response.json({saved:true,id:file?.id||op,repeated:true},{headers:qheaders});
 if(b.mode==='start'){if(file||parent.data.state!=='draft')qfail('پیوست فقط به پیش‌نویس افزوده می‌شود.');if(!Number.isSafeInteger(b.size)||b.size<1)qfail('اندازه فایل معتبر نیست.');const filename=qr(b.filename,240).replace(/[\r\n\\/]/g,'_');file={id:op,type:'qms_file',revision:0,data:{parentId:parent.id,filename,size:b.size,parts:Math.ceil(b.size/QMS_PART_SIZE),createdBy:a.id,state:'uploading'}};
 }else{if(!file)qfail('بارگذاری پیدا نشد.',404);writable(file,parent,a);file={...file,data:{...file.data}};
  if(b.mode==='complete'){const parts=await partsFor(file.id);if(parts.length!==file.data.parts||parts.some((p,i)=>p.data.index!==i||p.data.size!==Math.min(QMS_PART_SIZE,file.data.size-i*QMS_PART_SIZE)))qfail('تمام بخش‌های فایل هنوز دریافت نشده است.',409);file.data.state='ready';file.data.completedAt=new Date().toISOString();}
  else if(b.mode==='cancel')file.data.state='cancelled';else qfail('عملیات فایل معتبر نیست.');
 }
 await qcommit(u,op,signature,rows,members,[file,...(b.mode==='start'?[{...parent,data:{...parent.data,editors:[...new Set([...parent.data.editors,a.id])]}}]:[])],'file_'+b.mode);return Response.json({saved:true,id:file.id,partSize:QMS_PART_SIZE},{headers:qheaders});
 }catch(e){return accessResponse(e)||Response.json({error:'ثبت فایل انجام نشد؛ بارگذاری قابل ادامه است.'},{status:409,headers:qheaders})}}
export async function PUT(request:Request){try{checkOrigin(request);const {u,members,a,rows}=await context(),q=new URL(request.url).searchParams,file=qfind(rows,q.get('fileId')||'',a,'qms_file'),parent=qfind(rows,file.data.parentId,a),index=Number(q.get('part'));writable(file,parent,a);if(!q.has('part')||!Number.isSafeInteger(index)||index<0||index>=file.data.parts)qfail('شماره بخش معتبر نیست.');const bytes=await boundedBody(request,QMS_PART_SIZE);if(bytes.length!==Math.min(QMS_PART_SIZE,file.data.size-index*QMS_PART_SIZE))qfail('اندازه بخش با فایل تطابق ندارد.');const sha256=await hash(bytes),partId='qms-part:'+file.id+':'+index,old:any=await storage().prepare("SELECT data FROM flow_entities WHERE id=? AND type='qms_part'").bind(partId).first();if(old){if(JSON.parse(old.data).sha256!==sha256)qfail('فایل انتخاب‌شده با بارگذاری قبلی متفاوت است.',409);return Response.json({saved:true,repeated:true,index,sha256},{headers:qheaders});}
 // Content-addressed immutable chunk keys prevent an interrupted concurrent retry overwriting committed bytes.
 const objectKey='qms/v1/'+file.id+'/'+index+'/'+sha256;await firmwareBucket().put(objectKey,bytes,{httpMetadata:{contentType:'application/octet-stream'},sha256});const op=qid(request.headers.get('x-operation-id'));await qcommit(u,op,await qsignature({fileId:file.id,index,sha256}),rows,members,[{id:partId,type:'qms_part',revision:0,data:{fileId:file.id,parentId:parent.id,index,objectKey,size:bytes.length,sha256,filename:file.data.filename+'.part'+index}},file],'part');return Response.json({saved:true,index,sha256},{headers:qheaders});
 }catch(e){return accessResponse(e)||Response.json({error:'این بخش ثبت نشد؛ دوباره تلاش کنید.'},{status:409,headers:qheaders})}}
export async function GET(request:Request){try{const {u,a,rows}=await context(),q=new URL(request.url).searchParams,file=qfind(rows,q.get('fileId')||'',a,'qms_file'),parts=await partsFor(file.id);
 if(q.get('download')!=='1')return Response.json({file:qpresent(file),partSize:QMS_PART_SIZE,received:parts.map(p=>({index:p.data.index,sha256:p.data.sha256,size:p.data.size}))},{headers:qheaders});
 if(file.data.state!=='ready'||parts.length!==file.data.parts)qfail('فایل آماده دریافت نیست.',409);const selected=q.has('part')?parts.filter(p=>p.data.index===Number(q.get('part'))):parts;if(!selected.length)qfail('بخش فایل پیدا نشد.',404);
 await storage().prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,file.id,'qms_download','{}',new Date().toISOString()).run();
 let i=0;const stream=new ReadableStream<Uint8Array>({async pull(controller){try{if(i>=selected.length){controller.close();return;}const current=await qactor(u),currentRows=await qrows();qfind(currentRows,file.id,current,'qms_file');const part=selected[i++],object=await firmwareBucket().get(part.data.objectKey);if(!object)throw Error('Missing file part');const bytes=new Uint8Array(await object.arrayBuffer());if(await hash(bytes)!==part.data.sha256)throw Error('File integrity mismatch');controller.enqueue(bytes);}catch(e){controller.error(e);}}});
 return new Response(stream,{headers:{...qheaders,'Content-Type':'application/octet-stream','Content-Length':String(selected.reduce((s,p)=>s+p.data.size,0)),'Content-Security-Policy':"sandbox; default-src 'none'",'Content-Disposition':"attachment; filename=qms-file; filename*=UTF-8''"+encodeURIComponent(file.data.filename).replace(/['()*]/g,c=>'%'+c.charCodeAt(0).toString(16))}});
 }catch(e){return accessResponse(e)||Response.json({error:'دریافت فایل ممکن نشد.'},{status:503,headers:qheaders})}}
