import {requireAccess,requireAdmin,checkOrigin,accessResponse,AccessError} from '@/lib/authorization';
import {storage} from '@/lib/storage';
import {boundedBody} from '@/lib/firmware-storage';
import {replenishmentPolicy,replenishmentRoles,eligibleRole,shortageSnapshot,scanReplenishment} from '@/lib/replenishment';
import {supplyEntities,syncSourcingFollowups} from '@/lib/sourcing';
import {validCalendar} from '@/lib/workflow-calendar';
const json=(v:unknown)=>Response.json(v,{headers:{'Cache-Control':'private, no-store'}});
export async function GET(){try{const u=await requireAccess();if(!u.isAdmin&&!u.permissions.supplyRoles?.length)throw new AccessError('دسترسی تأمین لازم است.',403);const db=storage(),policy=await replenishmentPolicy(),members=(await db.prepare("SELECT id,name,status,permissions FROM app_members WHERE status='active'").all()).results as any[],health:any=await db.prepare("SELECT data,updated FROM flow_entities WHERE id='replenishment-background'").first(),issues=Object.keys(replenishmentRoles).filter(r=>!members.some(m=>m.id===policy.data.owners[r]&&eligibleRole(m,r))).map(r=>'مسئول فعال و مجاز تعیین نشده: '+replenishmentRoles[r]);if(!members.some(m=>m.id===policy.data.supervisor))issues.push('سرپرست فعال تعیین نشده است.');
 const materials=await supplyEntities('material'),plans=await supplyEntities('sourcing_plan'),legacy=await supplyEntities('supply'),stock=[];
 for(const m of materials){const s=await shortageSnapshot(m,policy.data.leadDays);if(s.low)stock.push({id:m.id,name:m.data.name,code:m.data.code,unit:m.data.unit,...s,openPlan:plans.find(p=>p.data.origin==='replenishment'&&p.data.materialId===m.id&&!['completed','released','cancelled','rejected'].includes(p.data.state))?.id,otherDemand:plans.some(p=>p.data.origin!=='replenishment'&&!['completed','released','cancelled','rejected'].includes(p.data.state)&&(p.data.lines||[]).some((l:any)=>l.partCode===m.data.code)),legacyOpen:legacy.some(s=>s.data.materialId===m.id&&s.data.state==='open')});}
 return json({admin:u.isAdmin,policy,roles:replenishmentRoles,eligible:u.isAdmin?Object.fromEntries(Object.keys(replenishmentRoles).map(role=>[role,members.filter(m=>eligibleRole(m,role)).map(m=>({id:m.id,name:m.name}))])):{},supervisors:u.isAdmin?members.filter(m=>JSON.parse(m.permissions).supplyRoles?.length).map(m=>({id:m.id,name:m.name})):[],issues,stock,backgroundLastAt:health?.updated||null,backgroundStale:!health||Date.now()-Date.parse(health.updated)>15*60000});
 }catch(e){return accessResponse(e)||Response.json({error:'پایش تأمین در دسترس نیست.'},{status:503})}}
export async function POST(request:Request){try{checkOrigin(request);const u=await requireAdmin(),db=storage(),b=JSON.parse(new TextDecoder().decode(await boundedBody(request,40000)));if(b.mode==='scan'){const result=await scanReplenishment();await syncSourcingFollowups();return json(result);}if(b.mode!=='policy'||!b.confirmed)throw new AccessError('ذخیره تنظیمات به تأیید مدیر نیاز دارد.',400);const old=await replenishmentPolicy();if(b.revision!==old.revision)throw new AccessError('تنظیمات تغییر کرده؛ تازه‌سازی کنید.',409);const p=b.policy;
 if(!p||typeof p.enabled!=='boolean'||!validCalendar(p.calendar)||!p.owners||typeof p.owners!=='object'||typeof p.supervisor!=='string')throw new AccessError('تقویم و مسئول‌ها معتبر نیستند.',400);
 for(const [key,min,max] of [['slaMinutes',30,10080],['reminderMinutes',30,1440],['escalationMinutes',30,10080],['criticalSlaMinutes',15,480],['leadDays',1,365]] as [string,number,number][])if(!Number.isInteger(p[key])||p[key]<min||p[key]>max)throw new AccessError('زمان‌بندی خارج از محدوده مجاز است.',400);
 const members=(await db.prepare("SELECT id,status,permissions FROM app_members WHERE status='active'").all()).results as any[];
 for(const role of Object.keys(replenishmentRoles)){if(typeof (p.owners[role]||'')!=='string'||p.owners[role]&&!members.some(m=>m.id===p.owners[role]&&eligibleRole(m,role)))throw new AccessError('مسئول '+replenishmentRoles[role]+' دسترسی لازم را ندارد.',400);if(p.enabled&&!p.owners[role])throw new AccessError('پیش از فعال‌سازی مسئول '+replenishmentRoles[role]+' را تعیین کنید.',400);}
 if(p.supervisor&&!members.some(m=>m.id===p.supervisor&&JSON.parse(m.permissions).supplyRoles?.length)||p.enabled&&!p.supervisor)throw new AccessError('سرپرست فعال دارای دسترسی تأمین لازم است.',400);
 const data={enabled:p.enabled,calendar:p.calendar,owners:Object.fromEntries(Object.keys(replenishmentRoles).map(r=>[r,p.owners[r]||''])),supervisor:p.supervisor,slaMinutes:p.slaMinutes,reminderMinutes:p.reminderMinutes,escalationMinutes:p.escalationMinutes,criticalSlaMinutes:p.criticalSlaMinutes,leadDays:p.leadDays},now=new Date().toISOString(),id=crypto.randomUUID();
 await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'replenishment_policy',?,?,?,CASE WHEN COALESCE((SELECT revision FROM flow_entities WHERE id='replenishment-policy'),0)=? THEN 1 ELSE 0 END)").bind(id,JSON.stringify(data),u.userId,now,old.revision),db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES('replenishment-policy','replenishment_policy',?,1,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,revision=flow_entities.revision+1,updated=excluded.updated").bind(JSON.stringify(data),now,now),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(id,u.userId,'replenishment-policy','configure_replenishment',JSON.stringify(data),now)]);return json({saved:true});
 }catch(e){return accessResponse(e)||Response.json({error:'ذخیره انجام نشد؛ تنظیمات را تازه‌سازی کنید.'},{status:409})}}
