import {checkOrigin,AccessError,accessResponse} from '@/lib/authorization';
import {boundedBody} from '@/lib/firmware-storage';
import {storage} from '@/lib/storage';
import {hospitalFinance,hospitalManager,hreq,htext,hrow} from '@/lib/hospital';
import {expenseUser,expenseRows,expenseMembers,expenseVisible,expenseJob,expensePolicy,expenseControl,expenseStates,syncExpenseTasks} from '@/lib/hospital-expenses';
import {memberId,dayAt} from '@/lib/duties';
import {money,sday,salesLock} from '@/lib/sales';
const json=(d:unknown,status=200)=>Response.json(d,{status,headers:{'Cache-Control':'private, no-store'}});
const fail=(s:string,status=400):never=>{throw new AccessError(s,status)};
export async function GET(){try{const u=await expenseUser(),mid=await memberId(u)||'',all=await expenseRows(),members=await expenseMembers();const claims=all.filter(r=>r.type==='expense_claim'&&expenseVisible(u,mid,r)),policies=all.filter(r=>r.type==='expense_policy');const jobs=(await storage().prepare("SELECT * FROM flow_entities WHERE type='hospital_job'").all()).results.map((r:any)=>({...r,data:JSON.parse(r.data)})).filter(r=>(hospitalManager(u)||r.data.technicianId===mid)&&['scheduled','dispatched','completed','confirmed','disputed'].includes(r.data.state));return json({mid,roles:{configure:!!hospitalFinance(u),manager:!!hospitalManager(u),finance:!!hospitalFinance(u)},policies,claims,jobs,members:members.filter(m=>u.isAdmin||hospitalFinance(u)||m.id===mid||claims.some(r=>[r.data.managerId,r.data.financeId].includes(m.id))),states:expenseStates});}catch(e){return accessResponse(e)||json({error:'دریافت تنخواه انجام نشد.'},503)}}
export async function POST(request:Request){try{checkOrigin(request);const u=await expenseUser(),mid=await memberId(u)||'',b=JSON.parse(new TextDecoder().decode(await boundedBody(request,60000))),id=hreq(b.id),mode=hreq(b.mode),db=storage(),now=new Date().toISOString();if(!/^[0-9a-f-]{36}$/i.test(id)||b.confirmed!==true)fail('شناسه عملیات و تأیید لازم است.');const signature=JSON.stringify(b),prior:any=await db.prepare('SELECT actor,payload FROM inventory_operations WHERE id=?').bind(id).first();if(prior){if(prior.actor!==u.userId||prior.payload!==signature)fail('شناسه تکراری با درخواست متفاوت.',409);return json({saved:true,repeated:true});}
 const checks=await salesLock(db,id),rows=await expenseRows(),members=await expenseMembers(),stmts:D1PreparedStatement[]=[];
 const put=(eid:string,type:string,data:any,old?:any)=>{const d={...data,history:[...(old?.data.history||[]),{mode,by:u.userId,name:u.name,at:now,notes:b.notes||''}]};stmts.push(old?db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=? AND revision=?').bind(JSON.stringify(d),now,eid,old.revision):db.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').bind(eid,type,JSON.stringify(d),now,now));};
 if(mode==='policy'){
  if(!hospitalFinance(u))fail('تعریف سقف و تأییدکنندگان با مسئول مالی است.',403);
  const old=b.policyId?rows.find(r=>r.id===b.policyId&&r.type==='expense_policy'):null;if(b.policyId&&(!old||old.revision!==b.revision))fail('نسخه سیاست تغییر کرده است.',409);
  if(old&&rows.some(r=>r.type==='expense_claim'&&r.data.policyId===old.id))fail('سیاست استفاده‌شده ثابت است؛ برای بازه بعد سیاست جدید ثبت کنید.');
  const start=sday(b.start),end=sday(b.end);if(end<start)fail('بازه نامعتبر است.');if(rows.some(r=>r.type==='expense_policy'&&r.id!==old?.id&&r.data.start<=end&&r.data.end>=start))fail('بازه سقف‌ها نباید هم‌پوشانی داشته باشد.');
  if(!Array.isArray(b.groups)||!b.groups.length||b.groups.length>20||!Array.isArray(b.categories)||!b.categories.length||b.categories.length>40||!Array.isArray(b.assignments)||b.assignments.length>300)fail('گروه هزینه، نوع هزینه و مسئول‌ها را کامل کنید.');
  const key=(v:any)=>{const s=hreq(v,50);if(!/^[a-z][a-z0-9_-]*$/.test(s))fail('کد لاتین معتبر لازم است.');return s;};
  const groups=b.groups.map((g:any)=>({id:key(g.id),name:hreq(g.name,100),limit:money(g.limit)}));if(new Set(groups.map((g:any)=>g.id)).size!==groups.length)fail('کد گروه تکراری است.');
  const categories=b.categories.map((c:any)=>({id:key(c.id),name:hreq(c.name,100),groupId:key(c.groupId)}));if(new Set(categories.map((c:any)=>c.id)).size!==categories.length||categories.some((c:any)=>!groups.some((g:any)=>g.id===c.groupId)))fail('نوع هزینه و گروه آن معتبر نیست.');
  // Stable category/group identity makes cumulative caps consistent across policy revisions.
  for(const p of rows.filter(r=>r.type==='expense_policy'&&r.id!==old?.id))for(const c of categories){const prev=p.data.categories.find((x:any)=>x.id===c.id);if(prev&&prev.groupId!==c.groupId)fail('گروه یک نوع هزینه ثبت‌شده قابل تغییر نیست.');}
  const assignments=b.assignments.map((a:any)=>{const ownerId=hreq(a.ownerId),managerId=hreq(a.managerId),financeId=hreq(a.financeId);if(new Set([ownerId,managerId,financeId]).size!==3||!members.some(m=>m.id===ownerId&&m.tech)||!members.some(m=>m.id===managerId&&m.manager)||!members.some(m=>m.id===financeId&&m.finance))fail('تکنسین، مدیر مستقیم و تأییدکننده مالی باید سه حساب فعال با دسترسی مربوط باشند.');return {ownerId,managerId,financeId};});if(new Set(assignments.map((a:any)=>a.ownerId)).size!==assignments.length)fail('تکنسین تکراری است.');put(old?.id||id,'expense_policy',{title:hreq(b.title),start,end,groups,categories,assignments},old);
 }else if(mode==='submit'){
  if(!mid)fail('حساب پرسنلی لازم است.',403);const job=await expenseJob(u,hreq(b.jobId));if(job.data.technicianId!==mid)fail('هزینه فقط توسط تکنسین مأموریت ثبت می‌شود.',403);
  const day=sday(b.day);if(day>dayAt())fail('تاریخ هزینه نباید در آینده باشد.');const policy=expensePolicy(rows,day);if(!policy)fail('برای تاریخ هزینه سقف و مسئول‌های تنخواه تعریف نشده است.');const assignment=policy.data.assignments.find((a:any)=>a.ownerId===mid);if(!assignment)fail('مدیر مستقیم و مسئول تنخواه شما تعیین نشده‌اند.');if(!members.some(m=>m.id===assignment.managerId&&m.manager)||!members.some(m=>m.id===assignment.financeId&&m.finance))fail('تأییدکننده فعال با دسترسی مربوط لازم است.');
  const category=policy.data.categories.find((c:any)=>c.id===b.categoryId);if(!category)fail('نوع هزینه معتبر انتخاب کنید.');const group=policy.data.groups.find((g:any)=>g.id===category.groupId),amount=money(b.amount,true),control=expenseControl(rows,mid,day,group.id,group.limit,amount);
  if(!Array.isArray(b.fileIds)||!b.fileIds.length||b.fileIds.length>8||new Set(b.fileIds).size!==b.fileIds.length)fail('یک تا هشت سند هزینه بارگذاری کنید.');const files=[];for(const fid of b.fileIds){const f=await hrow(hreq(fid),'expense_file');if(f.data.ownerId!==mid||f.data.jobId!==job.id)fail('فاکتور متعلق به همین تکنسین و مأموریت لازم است.',403);if(rows.some(r=>r.type==='expense_claim'&&r.data.state!=='rejected'&&r.data.fileHashes?.includes(f.data.sha256)))fail('این تصویر فاکتور قبلاً در هزینه دیگری ثبت شده است.');files.push(f);}
  const vendor=hreq(b.vendor,200),reference=hreq(b.reference,150);if(rows.some(r=>r.type==='expense_claim'&&r.data.ownerId===mid&&r.data.day===day&&r.data.vendor===vendor&&r.data.reference===reference&&r.data.state!=='rejected'))fail('این فاکتور قبلاً ثبت شده است.');const notes=htext(b.notes||'',3000),explanation=htext(b.explanation||'',3000);if(BigInt(control.excess)>BigInt(0)&&!explanation)fail('علت عبور از سقف روزانه را بنویسید.');
  put(id,'expense_claim',{...assignment,ownerName:u.name,jobId:job.id,serial:job.data.serial,centerId:job.data.centerId,day,categoryId:category.id,categoryName:category.name,groupId:group.id,groupName:group.name,amount,vendor,reference,notes,explanation,fileIds:files.map(f=>f.id),fileHashes:files.map(f=>f.data.sha256),policyId:policy.id,policyRevision:policy.revision,control,state:'manager',managerReview:null,financeReview:null});
 }else if(['manager_review','finance_review'].includes(mode)){
  const r=rows.find(r=>r.id===b.claimId&&r.type==='expense_claim');if(!r||!expenseVisible(u,mid,r))fail('هزینه پیدا نشد.',404);if(r.revision!==b.revision)fail('نسخه هزینه تغییر کرده است.',409);const d=r.data,managerStage=mode==='manager_review';if(d.state!==(managerStage?'manager':'finance'))fail('ترتیب تأیید مدیر و سپس مالی رعایت شود.',409);if(mid===d.ownerId||mid!==(managerStage?d.managerId:d.financeId)||!(managerStage?hospitalManager(u):hospitalFinance(u)))fail('فقط تأییدکننده تعیین‌شده و مستقل از ثبت‌کننده مجاز است.',403);if(!managerStage&&d.managerReview?.memberId===mid)fail('مدیر و مالی باید دو نفر مستقل باشند.',403);if(typeof b.approved!=='boolean')fail('نتیجه تأیید لازم است.');const notes=hreq(b.notes,3000),cap=d.control.limit,current=expenseControl(rows,d.ownerId,d.day,d.groupId,cap,d.amount,r.id),over=BigInt(current.excess)>BigInt(0)||BigInt(d.control.excess)>BigInt(0);
  if(b.approved&&over&&b.acceptOverLimit!==true)fail('هزینه از سقف عبور کرده؛ تأیید صریح استثنا لازم است.');const review={approved:b.approved,notes,acceptOverLimit:over&&b.approved,control:current,memberId:mid,by:u.userId,name:u.name,at:now};put(r.id,r.type,{...d,state:b.approved?(managerStage?'finance':'approved'):'rejected',[managerStage?'managerReview':'financeReview']:review},r);
 }else fail('عملیات ناشناخته.');
 await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'expense_action',?,?,?,1)").bind(id,signature,u.userId,now),...checks,...stmts,db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,b.claimId||b.policyId||id,'expense_'+mode,signature,now)]);try{await syncExpenseTasks();}catch{return json({saved:true,id,followupPending:true});}return json({saved:true,id});
 }catch(e){return accessResponse(e)||json({error:/constraint|SQLITE/i.test(String(e))?'اطلاعات هم‌زمان تغییر کرده؛ تازه‌سازی و دوباره ثبت کنید.':'ثبت تنخواه انجام نشد.'},409)}}
