import {requireFinance,checkOrigin,accessResponse,AccessError} from '@/lib/authorization';
import {storage} from '@/lib/storage';
import {boundedBody} from '@/lib/firmware-storage';
import {validFinanceReport,type FinanceNote} from '@/lib/finance-control';

import {financeScope as scope} from '@/lib/finance-scope';
export async function GET(request:Request){try{await requireFinance();const {cadence,period}=scope(new URL(request.url).searchParams);const db=storage();const [files,notes]=await Promise.all([db.prepare('SELECT id,cadence,period,report_id,filename,byte_size,sha256,uploaded_at,uploaded_by FROM finance_files WHERE cadence=? AND period=? ORDER BY uploaded_at,id').bind(cadence,period).all(),db.prepare('SELECT * FROM finance_notes WHERE cadence=? AND period=? ORDER BY created,id').bind(cadence,period).all()]);return Response.json({files:files.results,notes:notes.results},{headers:{'Cache-Control':'private, no-store'}})}catch(e){return accessResponse(e)||Response.json({error:'دریافت کنترل مالی انجام نشد؛ دوباره تلاش کنید.'},{status:503})}}
export async function POST(request:Request){try{checkOrigin(request);const actor=await requireFinance(true);const {cadence,period}=scope(new URL(request.url).searchParams);let value:any;try{value=JSON.parse(new TextDecoder().decode(await boundedBody(request,24000)))}catch(e){if(e instanceof AccessError)throw e;throw new AccessError('اطلاعات معتبر نیست.',400)}
const {id,report_id,kind,body,responsible='',parent_id=null}=value||{};
if(typeof id!=='string'||! /^[0-9a-f-]{36}$/i.test(id)||!validFinanceReport(cadence,report_id)||!['result','question','answer','closure'].includes(kind)||typeof body!=='string'||!body.trim()||body.length>5000||typeof responsible!=='string'||responsible.length>150)throw new AccessError('متن، نوع یادداشت یا گزارش معتبر نیست.',400);
if(kind==='question'&&!responsible.trim())throw new AccessError('مسئول پاسخ را وارد کنید.',400);
const db=storage();if(['answer','closure'].includes(kind)){const parent=typeof parent_id==='string'?await db.prepare("SELECT id FROM finance_notes WHERE id=? AND cadence=? AND period=? AND report_id=? AND kind='question'").bind(parent_id,cadence,period,report_id).first():null;if(!parent)throw new AccessError('سؤال مرتبط پیدا نشد.',400)}else if(parent_id!==null)throw new AccessError('ارجاع یادداشت معتبر نیست.',400);
const old=await db.prepare('SELECT * FROM finance_notes WHERE id=?').bind(id).first<FinanceNote>();if(old){if(old.cadence!==cadence||old.period!==period||old.report_id!==report_id||old.kind!==kind||old.body!==body.trim()||old.responsible!==responsible.trim()||old.parent_id!==parent_id)throw new AccessError('شناسه برای یادداشت دیگری استفاده شده است.',409);return Response.json({note:old})}
const now=new Date().toISOString();const note={id,cadence,period,report_id,kind,body:body.trim(),responsible:responsible.trim(),parent_id,created:now,created_by:actor.name};
await db.batch([db.prepare('INSERT INTO finance_notes(id,cadence,period,report_id,kind,body,responsible,parent_id,created,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id,cadence,period,report_id,kind,note.body,note.responsible,parent_id,now,actor.name),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),actor.userId,id,'finance_note',JSON.stringify(note),now)]);return Response.json({note},{status:201});
}catch(e){return accessResponse(e)||Response.json({error:'ثبت یادداشت تأیید نشد؛ پیش از تلاش دوباره فهرست را تازه کنید.'},{status:503})}}
