import {requireAccess,checkOrigin,accessResponse} from '@/lib/authorization';
import {boundedBody} from '@/lib/firmware-storage';
import {leadMembers} from '@/lib/sales-leads';
import {hrActor,hrRows,hrVisible,presentHr,applyPersonnel,internal,leaveBalance,workSummary,range,responsible,hrFail} from '@/lib/personnel';
import {advanceSummary,personnelHelp,personnelKinds,personnelStates,personnelRoles} from '@/lib/personnel-contract';
import {dayAt,addDay} from '@/lib/duties';
import {syncPersonnelTasks} from '@/lib/personnel-tasks';
const headers={'Cache-Control':'private, no-store','Vary':'Cookie, Authorization'};
export async function GET(request:Request){try{const u=await requireAccess(),members=await leadMembers(),a=await hrActor(u,members),rows=await hrRows(),q=new URL(request.url).searchParams,dates=range(q.get('from')||addDay(dayAt(),-30),q.get('to')||dayAt(),93),visible=rows.filter(r=>hrVisible(r,a,rows)),employees=visible.filter(r=>r.type==='hr_employee'),summaries=employees.filter(r=>r.data.memberId===a.id||a.has('hr')||a.has('payroll')||!a.roles.length).map(r=>{try{return {memberId:r.data.memberId,...workSummary(rows,r.data.memberId,dates.start,dates.end)}}catch(e){return {memberId:r.data.memberId,error:(e as Error).message}}});
 const records=visible.filter(r=>r.type!=='hr_file'||visible.some(p=>p.id===r.data.caseId)).map(r=>({...presentHr(r,a,rows),reviewers:responsible(r,rows,members)}));
 return Response.json({advances:employees.filter(r=>r.data.memberId===a.id||a.has('hr')||a.has('payroll')||a.has('finance')||a.has('treasury')).map(r=>advanceSummary(rows,r.data.memberId,dayAt())),records,me:a.id,roles:a.roles,admin:a.admin,today:dayAt(),...dates,summaries,balances:employees.filter(r=>r.data.memberId===a.id||a.has('hr')).map(r=>({memberId:r.data.memberId,availableMinutes:leaveBalance(rows,r.data.memberId)})),members:members.filter(internal).filter(m=>a.has('hr')||m.id===a.id||employees.some(e=>e.data.memberId===m.id||e.data.managerId===m.id)||a.roles.length>0).map(m=>({id:m.id,name:m.name})),help:personnelHelp,kinds:personnelKinds,states:personnelStates,roleLabels:personnelRoles,device:{connected:false,message:'اتصال دستگاه پس از دریافت مستندات؛ ثبت دستی فقط با مسئول اداری.'}},{headers});}catch(e){return accessResponse(e)||Response.json({error:'دریافت پرتال پرسنلی ممکن نشد.'},{status:503,headers})}}
export async function POST(request:Request){try{checkOrigin(request);const u=await requireAccess(),b=JSON.parse(new TextDecoder().decode(await boundedBody(request,64000)));const result=await applyPersonnel(u,b);let followupPending=false;try{await syncPersonnelTasks()}catch{followupPending=true}return Response.json({...result,followupPending},{headers});}catch(e){return accessResponse(e)||Response.json({error:'ثبت انجام نشد؛ نسخه اطلاعات را تازه و دوباره بررسی کنید.'},{status:409,headers})}}
