import {formatDate} from '@/lib/persian-date';
import {requireAccess,accessResponse,AccessError} from "@/lib/authorization";
import {storage} from "@/lib/storage";
const esc=(value:unknown)=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
export async function GET(request:Request){try{
 await requireAccess("device");const url=new URL(request.url),id=url.searchParams.get("id")||"",layout=url.searchParams.get("layout")==="thermal"?"thermal":"a4";
 const db=storage(),run:any=await db.prepare("SELECT * FROM serial_runs WHERE id=?").bind(id).first();if(!run)throw new AccessError("نوبت تولید سریال پیدا نشد.",404);
 const rows=await db.prepare("SELECT serial FROM serial_reservations WHERE run_id=? ORDER BY serial").bind(id).all<{serial:string}>();const p=JSON.parse(run.payload);
 const small=url.searchParams.get('label')==='small';const copies=small?Math.max(1,Math.min(20,Number(p.smallLabels)||1)):1;
 const labels=rows.results.flatMap(r=>Array.from({length:copies},()=>r)).map(r=>`<article class="${small?'small':''}"><div class="brand"><img src="/brand/nafasyar-logo.png" alt="نفس‌یار"><span>با من نفس بکش</span></div><div class="product">${esc(p.name)} · ${esc(p.model)}</div><div class="serial" dir="ltr">${esc(r.serial)}</div><small>تاریخ تخصیص سریال: ${esc(formatDate(run.day))}</small></article>`).join("");
 return new Response(`<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>چاپ سریال‌های ${esc(p.name)}</title><style>
@font-face{font-family:"Vazirmatn";src:url("/fonts/Vazirmatn.woff2") format("woff2");font-weight:100 900;font-style:normal;font-display:swap;}
 *{box-sizing:border-box}body{margin:0;font-family:"Vazirmatn",sans-serif;background:#eef2f7;color:#111}header{padding:20px;line-height:1.8}button{font:inherit;padding:8px 20px;cursor:pointer}.sheet{display:grid;grid-template-columns:${layout==="thermal"?"60mm":"repeat(3,62mm)"};gap:${layout==="thermal"?"0":"2mm"};width:max-content;margin:20px auto}article{width:${layout==="thermal"?"60mm":"62mm"};height:30mm;background:white;border:1px solid #bbb;padding:2mm;display:flex;flex-direction:column;justify-content:space-between;break-inside:avoid;overflow:hidden}.brand{display:flex;align-items:center;justify-content:space-between;gap:2mm}.brand img{width:19mm;height:10mm;object-fit:contain}.brand span{font-size:8pt}.product{font-size:8pt;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.serial{font-family:"Vazirmatn",sans-serif;font-weight:bold;font-size:${p.code.length>25?"6":"9"}pt;overflow-wrap:anywhere;text-align:center}small{font-size:7pt;text-align:center}@page{size:${layout==="thermal"?"60mm 30mm":"A4"};margin:${layout==="thermal"?"0":"8mm"}}@media print{body{background:white}header{display:none}.sheet{margin:0;${layout==="thermal"?"display:block":""}}article{border:0;${layout==="thermal"?"break-after:page":""}}article:last-child{break-after:auto}}
 article.small{height:15mm;width:35mm;padding:1mm}article.small .brand,article.small small,article.small .product{display:none}article.small .serial{font-size:8pt}${small?' .sheet{grid-template-columns:repeat(5,35mm)}':''}
 </style></head><body><header><strong>${rows.results.length} برچسب سریال · ${esc(p.name)}</strong><p>${layout==="thermal"?"برچسب تکی ۶۰ × ۳۰ میلی‌متر":"کاغذ A4؛ برچسب ۶۲ × ۳۰ میلی‌متر، فاصله ۲ میلی‌متر"} · اندازه چاپ ۱۰۰٪؛ سربرگ و پابرگ مرورگر خاموش باشد. ابتدا یک صفحه آزمایشی چاپ کنید.</p><button onclick="document.fonts.ready.then(() => window.print())">چاپ / ذخیره PDF</button><p>چاپ مجدد همین شماره‌ها را چاپ می‌کند و سریال جدیدی نمی‌سازد.</p></header><main class="sheet">${labels}</main></body></html>`,{headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff","Content-Security-Policy":"default-src 'none'; img-src 'self'; font-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'self'"}});
 }catch(e){console.error(e);return accessResponse(e)||Response.json({error:"آماده‌سازی چاپ انجام نشد؛ دوباره تلاش کنید."},{status:503});}}
