import {checkOrigin,AccessError} from '@/lib/authorization';
import {storage} from '@/lib/storage';
import {boundedBody} from '@/lib/firmware-storage';
import {qualityValues} from '@/lib/quality';
import {qualityAccess,qualityRecord,qualityTemplate,qualityReport,qualityError} from '@/lib/quality-storage';
export async function GET(request:Request){try{await qualityAccess();const device=new URL(request.url).searchParams.get('device')||'';await qualityRecord(device,'device');const rows=await storage().prepare('SELECT id FROM quality_reports WHERE device_id=? ORDER BY created DESC,id').bind(device).all<{id:string}>();return Response.json({reports:await Promise.all(rows.results.map(r=>qualityReport(r.id)))},{headers:{'Cache-Control':'no-store'}});}catch(e){return qualityError(e);}}
export async function POST(request:Request){try{checkOrigin(request);const actor=await qualityAccess(true),b=JSON.parse(new TextDecoder().decode(await boundedBody(request,128*1024)));
 if(typeof b.deviceId!=='string'||typeof b.templateId!=='string'||typeof b.notes!=='string'||b.notes.length>4000||!['pass','fail'].includes(b.verdict)||typeof b.requestId!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(b.requestId))throw new AccessError('مشخصات آزمون معتبر نیست.',400);
 const device=await qualityRecord(b.deviceId,'device'),template=await qualityTemplate(b.templateId);if(template.product_id!==device.product)throw new AccessError('این فرم متعلق به محصول دستگاه نیست.',400);
 const {values,failed}=qualityValues(template.fields,b.values);if(failed&&b.verdict==='pass')throw new AccessError('معیار مردود یا خارج از محدوده وجود دارد؛ نتیجه نهایی نمی‌تواند تأیید باشد.',400);
 const db=storage(),existing=await db.prepare('SELECT id FROM quality_reports WHERE id=?').bind(b.requestId).first();if(existing){const old=await qualityReport(b.requestId);if(old.device_id!==b.deviceId||old.template_id!==b.templateId||JSON.stringify(old.values)!==JSON.stringify(values)||old.verdict!==b.verdict||old.notes!==b.notes.trim())throw new AccessError('شناسه برای آزمون دیگری استفاده شده است.',409);return Response.json({report:old});}
 const flow:any=await db.prepare("SELECT * FROM flow_entities WHERE id=? AND type='build'").bind(b.deviceId).first();
 const build=flow?JSON.parse(flow.data):null;
 if(build&&(build.state!=='assembled'||build.templateId!==b.templateId))throw new AccessError('ابتدا برگ تولید تکمیل شود؛ آزمون باید با فرم متصل به همین سریال باشد.',400);
 const cause=b.cause||'unknown';if(!['part','assembly','design','test','unknown'].includes(cause))throw new AccessError('علت مردودی معتبر نیست.',400);
 if(b.verdict==='fail'&&!b.notes.trim())throw new AccessError('شرح مردودی اولیه یا مجدد لازم است.',400);
 const now=new Date().toISOString(),report={id:b.requestId,device_id:b.deviceId,template_id:b.templateId,values,verdict:b.verdict,notes:b.notes.trim(),created:now,created_by:actor.name,template};
 const event={id:'qc-event:'+report.id,kind:'event',created:now,data:{device:b.deviceId,stage:'آزمون نهایی',date:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tehran',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),operator:actor.name,result:b.verdict==='pass'?'تأیید':'مردود',notes:template.title+' · نسخه '+template.version+(report.notes?' · '+report.notes:''),qcReportId:report.id}};
 await db.batch([
 ...(flow?[db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) SELECT ?,'finaltest',?,1,?,? FROM flow_entities WHERE id=? AND revision=?").bind('test:'+report.id,JSON.stringify({deviceId:b.deviceId,reportId:report.id,buildRevision:flow.revision,assembler:build.assembler,verdict:b.verdict,cause,notes:b.notes,by:actor.name,at:now}),now,now,flow.id,flow.revision),db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'flow_qc','{}',?,?,CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=?) THEN 1 ELSE 0 END)").bind('qc:'+report.id,actor.userId,now,'test:'+report.id)]:[]),
 db.prepare('INSERT INTO quality_reports(id,device_id,template_id,"values",verdict,notes,created,created_by) VALUES(?,?,?,?,?,?,?,?)').bind(report.id,report.device_id,report.template_id,JSON.stringify(values),report.verdict,report.notes,now,actor.name),db.prepare('INSERT INTO records(id,kind,payload,created) VALUES(?,?,?,?)').bind(event.id,event.kind,JSON.stringify(event.data),now),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),actor.userId,b.deviceId,'record_quality_report',JSON.stringify({report,event}),now)]);
 return Response.json({report,event},{status:201});}catch(e){return qualityError(e);}}
