import {requireAccess,checkOrigin,accessResponse} from '@/lib/authorization';
import {serviceActor,serviceBy,serviceRows,serviceOutputAllowed,serviceFail as fail} from '@/lib/purchase-services';
import {boundedBody,firmwareBucket} from '@/lib/firmware-storage';
import {validateBatchFile,MAX_BATCH_FILE_BYTES} from '@/lib/batch-files';
import {sha256} from '@/lib/firmware';
import {storage} from '@/lib/storage';
import {settleText as txt} from '@/lib/purchase-settlement';
import {leadMemberGuard} from '@/lib/sales-leads';
export async function GET(r:Request){try{const u=await requireAccess(),a=await serviceActor(u),rows=await serviceRows(),q=new URL(r.url).searchParams,f=rows.find(x=>x.id===q.get('id')&&x.type==='payable_file'&&x.data.serviceId);if(!f)fail('فایل در دسترس نیست.',404);const s=serviceBy(u,a,rows,f.data.serviceId);if(!serviceOutputAllowed(a,s))fail('دسترسی خروجی ندارید.',403);const o=await firmwareBucket().get(f.data.objectKey);if(!o)fail('فایل در دسترس نیست.',404);const bytes=await o!.arrayBuffer();if(bytes.byteLength!==f.data.byteSize||await sha256(bytes)!==f.data.sha256)fail('یکپارچگی فایل تأیید نشد.',503);return new Response(bytes,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(f.data.filename),'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"sandbox; default-src 'none'"}});}catch(e){return accessResponse(e)||Response.json({error:'دریافت مدرک ممکن نشد.'},{status:503});}}
export async function POST(r:Request){let key='';try{checkOrigin(r);const u=await requireAccess(),a=await serviceActor(u),rows=await serviceRows(),q=new URL(r.url).searchParams,id=txt(q.get('id')),sid=txt(q.get('serviceId')),filename=txt(q.get('filename'),180),s=serviceBy(u,a,rows,sid);if(!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(id))fail('شناسه معتبر لازم است.');if(s.data.design)fail('خروجی طراحی را در پرونده محرمانه تحقیق‌وتوسعه بارگذاری کنید.');if(a.mid!==s.data.ownerId||!['open','returned'].includes(s.data.state))fail('بارگذاری با مسئول دریافت و در مرحله تحویل است.',403);const bytes=await boundedBody(r,MAX_BATCH_FILE_BYTES);validateBatchFile(filename,bytes.length);const hash=await sha256(bytes.buffer as ArrayBuffer),old=rows.find(x=>x.id===id);if(old){if(old.type!=='payable_file'||old.data.serviceId!==sid||old.data.actor!==u.userId||old.data.sha256!==hash||old.data.filename!==filename)fail('شناسه تکراری متفاوت است.',409);return Response.json({id,repeated:true});}const db=storage(),now=new Date().toISOString(),op=crypto.randomUUID();key='purchase-payables/'+s.data.caseId+'/'+id+'/'+crypto.randomUUID();await firmwareBucket().put(key,bytes);await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'service_output_upload',?,?,?,CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN 1 ELSE 0 END)").bind(op,JSON.stringify({id,sid,hash}),u.userId,now,sid,s.revision),leadMemberGuard(db,op,a.members),db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,'payable_file',?,1,?,?)").bind(id,JSON.stringify({caseId:s.data.caseId,serviceId:sid,filename,sha256:hash,byteSize:bytes.length,actor:u.userId,objectKey:key}),now,now),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,sid,'service_output_upload',JSON.stringify({id,hash}),now)]);return Response.json({id},{headers:{'Cache-Control':'no-store'}});}catch(e){if(key){try{if(!await storage().prepare("SELECT id FROM flow_entities WHERE type='payable_file' AND json_extract(data,'$.objectKey')=?").bind(key).first())await firmwareBucket().delete(key);}catch{}}return accessResponse(e)||Response.json({error:'بارگذاری تأیید نشد.'},{status:409});}}
