"use client";
import {useEffect,useRef,useState} from 'react';
import {formatDateTime} from '@/lib/persian-date';
type Entry={id:string;deviceCode:string;activationCode:string;reason?:string;created?:string};
export function ActivationCodePanel({accountId,demo}:{accountId:string;demo:boolean}){
 const [code,setCode]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<Entry|null>(null),[history,setHistory]=useState<Entry[]>([]),[historyError,setHistoryError]=useState(''),[copied,setCopied]=useState(false);
 const pending=useRef<{key:string;id:string}|null>(null),alive=useRef(true),lock=useRef(false);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);
 async function refresh(){try{const r=await fetch('/api/activation-code',{cache:'no-store',headers:{'x-assistant-account':accountId}}),d:any=await r.json();if(!r.ok||d.accountId!==accountId)throw new Error(d.error||'حساب ورود تغییر کرده است.');if(alive.current){setHistory(d.history);setHistoryError('')}}catch(e){if(alive.current)setHistoryError((e as Error).message)}}
 useEffect(()=>{if(!demo)void refresh()},[accountId,demo]);
 async function submit(e:React.FormEvent){e.preventDefault();if(lock.current||demo)return;lock.current=true;setBusy(true);setError('');setResult(null);setCopied(false);
 const key=JSON.stringify([code,reason]);if(pending.current?.key!==key)pending.current={key,id:crypto.randomUUID()};
 try{const r=await fetch('/api/activation-code',{method:'POST',headers:{'Content-Type':'application/json','x-assistant-account':accountId},body:JSON.stringify({id:pending.current.id,deviceCode:code,reason,confirmed:true})}),d:any=await r.json();if(!r.ok||d.accountId!==accountId)throw new Error(d.error||'حساب ورود تغییر کرده است.');if(alive.current){setResult(d);void refresh()}}catch(e){if(alive.current)setError((e as Error).message)}finally{lock.current=false;if(alive.current)setBusy(false)}}
 return <section className="panel inside" dir="rtl"><h2>تولید کد پنج‌رقمی</h2><p className="subtle">کد ۱۰رقمی نمایش‌داده‌شده روی دستگاه مشتری را وارد کنید. این اقدام فقط کد می‌سازد و گارانتی دستگاه را ثبت یا تمدید نمی‌کند. هویت کاربر، زمان و علت تولید در سابقه ثبت می‌شود.</p>{demo?<p className="notice">برای تولید کد، به محیط «اطلاعات شرکت» بروید.</p>:<><form onSubmit={submit}><div className="formgrid"><label className="field"><span>کد ۱۰رقمی دستگاه *</span><input dir="ltr" inputMode="numeric" autoComplete="off" required maxLength={10} value={code} disabled={busy} onChange={e=>{setCode(e.target.value);setResult(null);setCopied(false)}}/></label><label className="field"><span>علت تولید کد / شماره پیگیری مشتری *</span><textarea required maxLength={500} value={reason} disabled={busy} onChange={e=>{setReason(e.target.value);setResult(null)}}/></label></div><button className="btn primary" type="submit" disabled={busy}>{busy?'در حال تولید…':'تأیید و تولید کد پنج‌رقمی'}</button></form>{error&&<p className="notice error" role="alert">{error}</p>}{result&&<div className="notice" role="status"><p>کد دستگاه: <b dir="ltr">{result.deviceCode}</b></p><p>کد پنج‌رقمی مشتری: <strong dir="ltr" style={{fontSize:32,letterSpacing:4}}>{result.activationCode}</strong></p><button className="btn" onClick={async()=>{try{await navigator.clipboard.writeText(result.activationCode);setCopied(true)}catch{setError('کپی خودکار ممکن نشد؛ کد را دستی انتخاب و کپی کنید.')}}}>{copied?'کپی شد':'کپی کد پنج‌رقمی'}</button></div>}<h3>۲۰ کد اخیر تولیدشده توسط شما</h3><button type="button" className="link" disabled={busy} onClick={()=>void refresh()}>تازه‌سازی سابقه</button>{historyError&&<p role="alert">{historyError} <button className="link" onClick={()=>void refresh()}>تلاش دوباره</button></p>}{!history.length&&!historyError&&<p className="subtle">سابقه‌ای برای نمایش وجود ندارد.</p>}{history.map(h=><div className="recordline" key={h.id}><div><p>کد دستگاه: <b dir="ltr">{h.deviceCode}</b> · کد مشتری: <b dir="ltr">{h.activationCode}</b></p><p>{h.reason}</p><span className="subtle">{formatDateTime(h.created!)}</span></div></div>)}</>}</section>
}
