'use client';
import {formatDate,parseCalendarDay,localDay} from '@/lib/persian-date';
import {useEffect,useState,useRef} from 'react';
import {Headset,Plus,RefreshCw,Printer,Upload,ArrowRight,ClipboardCheck} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {SolarDate} from './solar-date';
import {ServiceAgentAccounts} from './service-agent-accounts';
import {serviceReport} from '@/lib/service-report';
import {serviceRoles,serviceDomains,caseStates,serviceActions} from '@/lib/after-sales-labels';
import {serviceForms,type ServiceField} from '@/lib/after-sales-contract';
import type {Session} from '@/lib/permissions';
const today=()=>localDay();
const fa=(v:any)=>Number(v).toLocaleString('fa-IR'),date=(v:string)=>v?formatDate(v):'—';
const money=(v:any)=>{try{return BigInt(v||0).toLocaleString('fa-IR')+' ریال'}catch{return '—'}};
const statuses:Record<string,string>={...caseStates,requested:'درخواست جدید',approved:'تأییدشده',rejected:'ردشده',prepared:'بسته آماده',shipped:'در راه',received:'دریافت‌شده',awaiting_return:'منتظر داغی',sent:'داغی ارسال‌شده',credited:'بستانکاری ثبت شد'};
const ledgerNames:Record<string,string>={invoice:'فاکتور قطعات',order_cancel:'اصلاح درخواست ردشده',return_credit:'بستانکاری داغی',labor_credit:'اجرت گارانتی',payment_received:'دریافت از نماینده',payment_paid:'پرداخت به نماینده'};
function seed(fields:ServiceField[]):any{return Object.fromEntries(fields.map(f=>[f.key,f.type==='rows'?[]:f.type==='boolean'?false:f.type==='date'?today():f.type==='money'?'0':f.options?.[0]?.[0]||'']));}
function Fields({fields,value,onChange,options}:{fields:ServiceField[];value:any;onChange:(v:any)=>void;options:(s:string)=>string[][]}){return <>{fields.map(f=>{const v=value[f.key],set=(x:any)=>onChange({...value,[f.key]:x});
 if(f.type==='rows')return <fieldset className="wide as-rows" key={f.key}><legend>{f.label}</legend>{(v||[]).map((row:any,i:number)=><div className="as-row" key={i}><strong>ردیف {fa(i+1)}</strong><div className="formgrid"><Fields fields={f.fields!} value={row} options={options} onChange={x=>set(v.map((a:any,n:number)=>n===i?x:a))}/></div><button type="button" className="link" onClick={()=>set(v.filter((_:any,n:number)=>n!==i))}>حذف ردیف</button></div>)}<button type="button" className="btn" disabled={(v||[]).length>=40} onClick={()=>set([...(v||[]),seed(f.fields!)])}><Plus size={16}/>افزودن ردیف</button></fieldset>;
 if(f.type==='date')return <SolarDate key={f.key} label={f.label} value={v||''} required={!f.optional} onChange={set}/>;
 if(f.type==='boolean')return <label className="field as-check" key={f.key}><input type="checkbox" checked={v===true} onChange={e=>set(e.target.checked)}/>{f.label}</label>;
 return <label className={'field '+(f.type==='textarea'?'wide':'')} key={f.key}>{f.label}{f.optional?' (اختیاری)':''}{f.type==='select'?<select required={!f.optional} value={v||''} onChange={e=>set(e.target.value)}><option value="">انتخاب کنید</option>{(f.options||options(f.source||'')).map(([k,l])=><option value={k} key={k}>{l}</option>)}</select>:f.type==='textarea'?<textarea rows={3} required={!f.optional} maxLength={4000} value={v||''} onChange={e=>set(e.target.value)}/>:<input required={!f.optional} maxLength={f.type==='money'?18:1000} inputMode={['money','quantity'].includes(f.type||'')?'decimal':undefined} dir={['money','quantity'].includes(f.type||'')?'ltr':undefined} value={v??''} onChange={e=>set(e.target.value.replace(/[۰-۹]/g,c=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(c))).replace(/[٠-٩]/g,c=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(c))))}/>}</label>})}</>}
export function AfterSalesPanel({demo,user,onNavigate}:{demo:boolean;user:Session;onNavigate:(s:string)=>void}){
 const domains=user.isAdmin?Object.keys(serviceDomains):user.permissions.serviceDomains||[],[domain,setDomain]=useState(domains[0]||'home'),[tab,setTab]=useState('cases'),[data,setData]=useState<any>(null),[detail,setDetail]=useState<any>(null),[selected,setSelected]=useState(''),[account,setAccount]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[draft,setDraft]=useState<any>(null),[context,setContext]=useState<any>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[preview,setPreview]=useState<any[]>([]),[purpose,setPurpose]=useState('before');
 const requestNumber=useRef(0);
 const can=(...roles:string[])=>data?.roles?.includes('manager')||roles.some(r=>data?.roles?.includes(r));
 async function read(extra=''){const r=await fetch('/api/after-sales?domain='+domain+extra,{cache:'no-store'}),d=await r.json() as any;if(!r.ok)throw Error(d.error);return d;}
 async function refresh(id=selected,agent=account){const n=++requestNumber.current;setLoading(true);try{const d=await read(agent?'&agent='+encodeURIComponent(agent):'');const full=id?await read('&case='+encodeURIComponent(id)):null;if(n!==requestNumber.current)return;setData(d);setDetail(full);setError('');}catch(e){if(n===requestNumber.current)setError((e as Error).message)}finally{if(n===requestNumber.current)setLoading(false)}}
 useEffect(()=>{setData(null);setDetail(null);setSelected('');setAccount('');if(!demo)void refresh('','');},[domain,demo]); // workspace is scoped by account and domain
 async function open(id:string){setSelected(id);await refresh(id);}
 function start(mode:string,e:any=null,extra:any={}){const d={...seed(serviceForms[mode]||[]),id:crypto.randomUUID(),domain,mode,...extra};setContext(e);setPreview([]);setError('');
 if(e){d.revision=e.revision;const key=e.type==='as_case'?'caseId':e.type==='as_order'?'orderId':e.type==='as_shipment'?'shipmentId':e.type==='as_claim'?'claimId':e.type==='as_agent'?'agentId':'tariffId';d[key]=e.id;}
 if(mode==='agent'||mode==='tariff'){d.active=true;if(e)Object.assign(d,e.data);}
 if(['order','payment','offset'].includes(mode))d.agentId=data.ownAgent||account||'';
 if(mode==='create'&&data.ownAgent)d.agentId=data.ownAgent;
 if(mode==='diagnose'&&e){d.lines=e.data.lines.map((l:any)=>({...l,quantity:String(l.quantity/1000)}));d.laborLines=e.data.laborLines.map((l:any)=>({...l}));d.notes=e.data.diagnosis||'';}
 if(mode==='reserve'&&e)d.allocations=e.data.lines.map((l:any)=>({lineId:l.id,lotId:'',quantity:String(l.quantity/1000)}));
 if(mode==='prepare'&&e)d.allocations=e.data.lines.filter((l:any)=>l.prepared<l.quantity).map((l:any)=>({lineId:l.id,batchId:'',location:'',quantity:String((l.quantity-l.prepared)/1000)}));
 if(mode==='authorize'||mode==='approve_order'||mode==='return_review')d.approved=true;
 setDraft(d);
 }
 async function send(body:any){const r=await fetch('/api/after-sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json() as any;if(!r.ok)throw Error(d.error);return d;}
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const result=await send(draft);if(draft.mode==='activation_preview'){setPreview(result.preview);setMessage('نتیجه بررسی فایل آماده است؛ هنوز وارد نشده.');}else{setDraft(null);setMessage('ثبت شد. سوابق و کارتابل به‌روز شدند.');const id=draft.mode==='create'?result.id:selected;setSelected(id);await refresh(id);window.dispatchEvent(new Event('nafasyar-tasks-changed'));}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function upload(file:File){if(!detail)return;setBusy(true);setError('');try{const form=new FormData();form.set('file',file);const r=await fetch('/api/after-sales/files?case='+detail.case.id+'&purpose='+purpose+'&requestId='+crypto.randomUUID(),{method:'POST',body:form}),d=await r.json() as any;if(!r.ok)throw Error(d.error);await refresh();setMessage('مدرک به پرونده پیوست شد.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function importFile(file:File){setBusy(true);setError('');try{let rows:any[][];if(file.name.toLowerCase().endsWith('.xlsx')){const mod=await import('read-excel-file/browser');rows=await mod.readSheet(file) as any[][];}else{const lines=(await file.text()).replace(/^\uFEFF/,'').trim().split(/\r?\n/);rows=lines.map(l=>l.split(l.includes('\t')?'\t':','));}if(rows.length>201)throw Error('در هر نوبت حداکثر ۲۰۰ ردیف وارد کنید.');const headers=rows.shift()!.map(x=>String(x).trim()),idx=(en:string,fa:string)=>headers.findIndex(h=>h===en||h===fa),si=idx('serial','سریال'),di=idx('day','تاریخ'),mi=idx('months','ماه');if([si,di,mi].some(i=>i<0))throw Error('ستون‌ها باید serial، day و months باشند. تاریخ شمسی مانند ۱۴۰۵/۰۷/۱۱؛ تاریخ استاندارد اکسل هم پذیرفته می‌شود.');setDraft({...seed(serviceForms.activation_preview),mode:'activation_preview',id:crypto.randomUUID(),domain,source:file.name,rows:rows.map(r=>({serial:String(r[si]||''),day:parseCalendarDay(r[di])||String(r[di]||''),months:String(r[mi]||'')}))});setPreview([]);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const c=detail?.case,d=c?.data,agentName=(id:string)=>data?.agents.find((a:any)=>a.id===id)?.data.name||'دفتر شرکت';
 function options(s:string):string[][]{const a=data||{};switch(s){case 'agents':return a.agents?.filter((r:any)=>r.data.active).map((r:any)=>[r.id,r.data.name])||[];case 'materials':return a.materials?.map((r:any)=>[r.code,r.code+' · '+r.name+' · '+r.unit])||[];case 'partTariffs':case 'laborTariffs':return a.tariffs?.filter((r:any)=>r.data.active&&r.data.kind===(s==='partTariffs'?'part':'labor')).map((r:any)=>[r.id,r.data.name+' · '+money(r.data.priceRial)])||[];case 'cases':return a.cases?.filter((r:any)=>!draft?.agentId||r.data.agentId===draft.agentId).map((r:any)=>[r.id,r.data.serial+' · '+r.data.customer])||[];case 'raw':return a.raw?.map((r:any)=>[r.id,r.code+' · '+r.part+' · '+fa(r.available/1000)+' · محل '+(r.location||'—')]).filter((r:any,i:number,x:any[])=>x.findIndex(a=>a[0]===r[0])===i)||[];case 'installed':return detail?.lineage?.map((r:any)=>[r.batchId,r.batchId+' · '+fa(r.quantity/1000)]).filter((r:any,i:number,x:any[])=>x.findIndex(a=>a[0]===r[0])===i)||[];case 'caseLines':return context?.data.lines.map((l:any)=>[l.id,l.name+' · '+fa(l.quantity/1000)])||[];case 'orderLines':return context?.data.lines.map((l:any)=>[l.id,l.name+' · مانده '+fa((l.quantity-l.prepared)/1000)])||[];case 'caseLots':return a.lots?.filter((l:any)=>l.owner===(context?.data.agentId||'office')&&l.quantity>0).map((l:any)=>[l.id,l.batch.part+' · بچ '+l.batch.code+' · آزاد '+fa((l.quantity-l.reserved)/1000)])||[];case 'members':return a.members?.filter((m:any)=>!m.roles?.includes('agent')).map((m:any)=>[m.id,m.name])||[];case 'debits':case 'credits':return a.account?.filter((r:any)=>BigInt(r.remaining)>BigInt(0)&&BigInt(s==='debits'?r.debit:r.credit)>BigInt(0)).map((r:any)=>[r.id,(ledgerNames[r.kind]||r.kind)+' · '+money(r.remaining)+' · '+date(r.created)])||[];default:return []}}
 const action=(mode:string,e:any=c)=> <button type="button" className="btn" key={mode} disabled={busy} onClick={()=>start(mode,e)}>{serviceActions[mode]||mode}</button>;
 const print=(kind:string,label:string)=><a className="btn" href={'/api/after-sales/print?case='+c.id+'&kind='+kind} target="_blank" rel="noreferrer"><Printer size={16}/>{label}</a>;
 if(demo)return <div className="panel"><h2>خدمات پس از فروش</h2><p>برای ثبت پرونده و حساب واقعی نماینده، «اطلاعات شرکت» را انتخاب کنید. در این بخش داده مالی نمونه ساخته نمی‌شود.</p></div>;
 return <section className="after-sales"><div className="panelhead"><div><h2><Headset style={{display:'inline',marginLeft:8}}/>خدمات پس از فروش</h2><p className="subtle">از اولین تماس تا تحویل، داغی و تسویه نماینده</p></div><div className="tools"><button className="btn" onClick={()=>onNavigate('transport')}>رهگیری ارسال‌ها و برگشتی‌ها</button><label>حوزه <select aria-label="حوزه خدمات" value={domain} onChange={e=>setDomain(e.target.value)}>{domains.map(k=><option value={k} key={k}>{serviceDomains[k]}</option>)}</select></label><button className="btn" onClick={()=>void refresh()} disabled={loading}><RefreshCw size={16}/>تازه‌سازی</button></div></div>
 {domain==='hospital'&&<p className="notice">دسترسی حوزه بیمارستانی جداست. فرم‌های این نسخه عمومی‌اند؛ گردش قرارداد، سرویس دوره‌ای و مراجعه بیمارستان هنوز تعریف نشده است.</p>}
 {error&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}
 <nav className="tools as-tabs" aria-label="بخش‌های خدمات">{[['cases','پرونده‌ها'],['orders','قطعات و داغی'],['stock','موجودی خدمات'],['accounts','حساب نماینده'],['reports','گزارش عملکرد'],...(can('manager')?[['settings','تنظیمات و فعال‌سازی']]:[])].map(([k,label])=><button className={'btn '+(tab===k?'primary':'')} key={k} onClick={()=>setTab(k)}>{label}</button>)}</nav>
 {!data?<p className="empty">{loading?'در حال دریافت…':'اطلاعات در دسترس نیست.'}</p>:<>
 {tab==='settings'&&can('manager')&&<ServiceAgentAccounts key={user.userId+':'+domain} domain={domain} agents={data.agents} accountId={user.userId}/>}
 {tab==='cases'&&<>{!c?<><div className="tools"><input aria-label="جست‌وجوی خدمات" placeholder="سریال، نام یا تلفن مشتری…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="وضعیت پرونده" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">همه وضعیت‌ها</option>{Object.entries(caseStates).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>{can('support','intake','agent')&&<button className="btn primary" onClick={()=>start('create')}><Plus size={16}/>تماس / مراجعه جدید</button>}</div><div className="as-grid">{data.cases.filter((r:any)=>(!filter||r.data.state===filter)&&[r.data.serial,r.data.customer,r.data.phone].join(' ').toLowerCase().includes(query.toLowerCase())).map((r:any)=><article className="flow-card" key={r.id}><span className="as-badge">{caseStates[r.data.state]}</span><h3 dir="ltr">{r.data.serial}</h3><p>{r.data.customer} · {r.data.phone}</p><p>{r.data.model} · {agentName(r.data.agentId)}</p><p>{r.data.complaint}</p><p className="subtle">تماس {date(r.data.contactDay)} · آخرین تغییر {date(r.updated)}</p><button className="btn" onClick={()=>void open(r.id)}>باز کردن پرونده</button></article>)}</div>{!data.cases.length&&<p className="empty">هنوز پرونده‌ای ثبت نشده. تماس تلفنی و مراجعه مستقیم هر دو از «تماس / مراجعه جدید» آغاز می‌شوند.</p>}</>:<>
 <button className="btn" onClick={()=>{setSelected('');setDetail(null)}}><ArrowRight size={16}/>فهرست پرونده‌ها</button><article className="panel as-case"><div className="panelhead"><div><h2>{d.serial} · {d.model}</h2><p>{d.customer} · {d.phone} · {agentName(d.agentId)}</p></div><span className="as-badge">{caseStates[d.state]}</span></div><p>{d.complaint}</p><p>گارانتی در پذیرش: <strong>{({active:'در بازه زمانی',expired:'خارج از بازه',unknown:'سابقه نامشخص'} as any)[d.warranty.state]}</strong> · فعال‌سازی {date(d.warranty.activatedAt)} · پایان {date(d.warranty.endsAt)}</p><p className="subtle">قرارداشتن در بازه زمانی به‌تنهایی تأیید پوشش فنی نیست. آب‌خوردگی، ضربه و شرایط قطعه در عیب‌یابی بررسی می‌شود.</p><p>برآورد قابل پرداخت مشتری: <strong>{money(d.customerTotal)}</strong> · نسخه {fa(d.estimateVersion||0)}</p>
 <div className="tools">{['contact','followup','referred'].includes(d.state)&&<>{can('support','agent')&&action('contact')}{can('intake','agent')&&action('intake')}</>}{['received','diagnosed','approved'].includes(d.state)&&can('technician','agent')&&action('diagnose')}{d.state==='diagnosed'&&can('coordinator')&&action('authorize')}{['diagnosed','approved'].includes(d.state)&&d.customerTotal!=='0'&&can('support','agent')&&action('consent')}{d.state==='approved'&&can('technician','agent')&&<>{action('reserve')}{action('repair')}</>}{['repaired','tested'].includes(d.state)&&can('technician','agent')&&action('test')}{d.state==='declined'&&can('intake','agent')&&action('return_unrepaired')}{d.state==='tested'&&can('intake','agent')&&action('deliver')}{d.state==='delivered'&&can('support')&&action('confirm')}{d.agentId&&d.confirmation?.result==='confirmed'&&!d.laborApproved&&can('coordinator')&&action('labor')}{can('support','intake','technician','coordinator','agent')&&action('followup')}{d.intake&&print('receipt','رسید پذیرش دو نسخه')}{d.repairedAt&&print('invoice','صورتحساب خدمات')}{d.deliveredDay&&<>{print('warranty','گارانتی قطعات')}<button className="btn" onClick={async()=>{try{const r=await fetch('/api/after-sales/print?case='+c.id+'&kind=warranty&format=text'),s=await r.json() as any;if(!r.ok)throw Error(s.error);setMessage(s.text+' (این متن ارسال نشده است.)');}catch(e){setError((e as Error).message)}}}>متن گارانتی برای مشتری</button></>}</div>
 {!!detail.steps.length&&<div className="notice"><strong>گام‌های در انتظار</strong>{detail.steps.map((s:any)=><p key={s.key}>{s.title} · {serviceRoles[s.role]} · {date(s.due)}</p>)}</div>}
 {d.lines.length>0&&<div className="as-table"><table><thead><tr><th>قطعه / عیب</th><th>مقدار</th><th>پوشش</th><th>بچ خارج‌شده</th><th>علت اولیه</th></tr></thead><tbody>{d.lines.map((l:any)=><tr key={l.id}><td>{l.name}<p>{l.fault}</p></td><td>{fa(l.quantity/1000)} {l.unit}</td><td>{({warranty:'گارانتی دستگاه',part_warranty:'گارانتی قطعه',paid:'غیرگارانتی'} as any)[l.coverage]}<p>{l.coverageReason}</p></td><td>{l.oldBatchId||'نامشخص: '+l.unknownReason}</td><td>{l.cause}</td></tr>)}</tbody></table></div>}
 {d.authorization&&<p>بررسی شرکت: {d.authorization.notes} {d.authorization.exceptionReason}</p>}{d.consent&&<p>پاسخ مشتری: {d.consent.approved?'تأیید':'عدم تأیید'} · {d.consent.person} · {d.consent.notes}</p>}
 {!!detail.reservations.length&&<p>قطعات رزروشده: {fa(detail.reservations.reduce((n:number,r:any)=>n+r.quantity/1000,0))} واحد طبق ردیف‌های برآورد</p>}
 {(d.repairs||[]).map((r:any,i:number)=><p key={i}>مصرف واقعی: {r.partCode} · بچ {r.batchId} · {fa(r.quantity/1000)}</p>)}
 {(d.tests||[]).map((t:any,i:number)=><details key={i}><summary>آزمون {fa(i+1)} · {t.pass?'قبول':'رد'} · {date(t.at)}</summary>{t.results.map((r:any,j:number)=><p key={j}>{r.name}: {r.value} {r.unit} · {r.passed?'قبول':'رد'}</p>)}<p>{t.notes}</p></details>)}
 {d.returnedDay&&<p>عودت بدون تعمیر: {date(d.returnedDay)} به {d.returnedTo} · {d.returnReference}</p>}{d.deliveredDay&&<p>تحویل: {date(d.deliveredDay)} به {d.deliveredTo} · گارانتی قطعات تا پیش از {date(d.partWarrantyEnd)}</p>}{d.confirmation&&<p>تماس تأیید مشتری: {({confirmed:'تأیید شد',no_answer:'پاسخ نداد',problem:'نیازمند رسیدگی'} as any)[d.confirmation.result]} · {d.confirmation.notes}</p>}
 <h3>مدارک پرونده</h3><p className="subtle">قبل از تعمیر گارانتی توسط نماینده، عکس یا فیلمی که سریال و ایراد را نشان دهد بارگذاری شود. کارشناس شرکت محتوا را بررسی می‌کند.</p><div className="tools">{can('support','intake','technician','coordinator','agent')&&<><select aria-label="نوع مدرک" value={purpose} onChange={e=>setPurpose(e.target.value)}>{[['before','قبل از تعمیر / سریال و عیب'],['intake','پذیرش'],['diagnosis','عیب‌یابی'],['after','پس از تعمیر'],['delivery','تحویل'],['other','سایر']].map(([k,l])=><option key={k} value={k}>{l}</option>)}</select><label className="btn"><Upload size={16}/>افزودن عکس، فیلم یا PDF<input type="file" hidden disabled={busy} accept=".jpg,.jpeg,.png,.webp,.pdf,.mp4,.mov,.webm" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value=''}}/></label></>}</div><ul>{detail.files.map((f:any)=><li key={f.id}><a className="link" href={'/api/after-sales/files?case='+c.id+'&id='+f.id}>{f.filename}</a> · {date(f.created)}</li>)}</ul>
 <details><summary>تاریخچه پرونده و برآوردها</summary>{d.history.map((h:any,i:number)=><p key={i}>{date(h.at)} · {serviceActions[h.mode]||h.mode} · {h.by||h.actor} · {h.notes}</p>)}{(d.estimates||[]).map((e:any)=><p key={e.version}>برآورد نسخه {fa(e.version)} · {money(e.total)} · {e.lines.map((l:any)=>l.name).join('، ')}</p>)}</details>
 </article></> }</>}
 {tab==='orders'&&<><div className="tools">{can('coordinator','agent')&&<button className="btn primary" onClick={()=>start('order')}><Plus size={16}/>درخواست قطعه و صدور فاکتور</button>}</div><p className="notice">فاکتور در زمان درخواست صادر می‌شود؛ سررسید یک ماه شمسی است. داغی تأییدشده فقط مبلغ مرتبط را بستانکار می‌کند. اجرت پس از تأیید مشتری جداگانه ثبت می‌شود.</p>
 <h3>درخواست‌ها</h3><div className="as-grid">{data.orders.map((o:any)=><article className="flow-card" key={o.id}><h3>{agentName(o.data.agentId)}</h3><p>{statuses[o.data.state]} · {date(o.created)}</p>{o.data.lines.map((l:any)=><p key={l.id}>{l.name} · سفارش {fa(l.quantity/1000)} · بسته‌بندی {fa(l.prepared/1000)} · دریافت {fa(l.received/1000)}</p>)}<p>{money(o.data.totalRial)} · سررسید {date(o.data.due)}</p><div className="tools">{o.data.state==='requested'&&can('coordinator')&&action('approve_order',o)}{o.data.state==='approved'&&can('inventory')&&o.data.lines.some((l:any)=>l.prepared<l.quantity)&&action('prepare',o)}</div></article>)}</div>
 <h3>بسته‌ها</h3><div className="as-grid">{data.shipments.map((s:any)=><article className="flow-card" key={s.id}><h3>{agentName(s.data.agentId)} · {statuses[s.data.state]}</h3>{s.data.lines.map((l:any,i:number)=><p key={i}>قطعه {l.partCode} · {fa(l.quantity/1000)} · بچ {l.batchId}</p>)}<p>{s.data.carrier} · {s.data.tracking}</p><div className="tools">{s.data.state==='prepared'&&can('logistics')&&action('ship',s)}{s.data.state==='shipped'&&can('agent','coordinator')&&action('receive',s)}</div></article>)}</div>
 <h3>داغی قطعات</h3><div className="as-grid">{data.claims.map((r:any)=><article className="flow-card" key={r.id}><h3>{r.data.serial} · قطعه {r.data.partCode}</h3><p>{agentName(r.data.agentId)} · {statuses[r.data.state]}</p><p>{fa(r.data.quantity/1000)} · {money(r.data.amountRial)}</p><p>سررسید فاکتور {date(r.data.due)} · دریافت داغی {date(r.data.receivedDay)}</p>{r.data.receivedDay>r.data.due&&<p className="subtle">داغی پس از سررسید رسیده است؛ سابقه تأخیر باقی می‌ماند.</p>}<div className="tools">{['awaiting_return','rejected'].includes(r.data.state)&&can('agent','coordinator')&&action('return_send',r)}{['sent','awaiting_return'].includes(r.data.state)&&can('inventory')&&action('return_receive',r)}{r.data.state==='received'&&can('coordinator')&&action('return_review',r)}{r.data.state==='approved'&&can('finance')&&action('credit',r)}</div></article>)}</div></>}
 {tab==='stock'&&<><div className="tools">{can('inventory')&&<button className="btn primary" onClick={()=>start('office_stock')}>تحویل قطعه از مواد اولیه به خدمات دفتر</button>}</div><p className="subtle">برداشت تعمیر فقط از موجودی همان مرکز، با بچ واقعی و بدون مصرف دوباره موجودی رزروشده مجاز است.</p><div className="as-table"><table><thead><tr><th>مرکز</th><th>قطعه / بچ</th><th>موجود</th><th>رزرو</th><th>آزاد</th></tr></thead><tbody>{data.lots.map((l:any)=><tr key={l.id}><td>{l.owner==='office'?'دفتر شرکت':agentName(l.owner)}</td><td>{l.batch.part} · {l.batch.code}</td><td>{fa(l.quantity/1000)}</td><td>{fa(l.reserved/1000)}</td><td>{fa((l.quantity-l.reserved)/1000)}</td></tr>)}</tbody></table></div></>}
 {tab==='accounts'&&<>{!data.ownAgent&&!can('finance','coordinator')?<p className="empty">مجوز مشاهده حساب نماینده لازم است.</p>:<><label className="field">نماینده<select value={account} onChange={e=>{setAccount(e.target.value);void refresh(selected,e.target.value)}}><option value="">انتخاب کنید</option>{data.agents.map((a:any)=><option value={a.id} key={a.id}>{a.data.name}</option>)}</select></label>{account&&<><p className="notice">مانده خالص بدهکار نماینده: {money(data.account.reduce((n:bigint,r:any)=>n+BigInt(r.debit)-BigInt(r.credit),BigInt(0)))} · عدد منفی یعنی بستانکاری نماینده.</p><div className="tools">{can('finance')&&<><button className="btn" onClick={()=>start('payment')}>ثبت پرداخت / دریافت</button><button className="btn" onClick={()=>start('offset')}>تخصیص وجه / تهاتر</button></>}</div><div className="as-table"><table><thead><tr><th>تاریخ / سند</th><th>بدهکار</th><th>بستانکار</th><th>مانده تخصیص‌نیافته</th><th>سررسید</th></tr></thead><tbody>{data.account.map((r:any)=><tr key={r.id}><td>{date(r.created)} · {ledgerNames[r.kind]||r.kind}</td><td>{money(r.debit)}</td><td>{money(r.credit)}</td><td>{money(r.remaining)}</td><td>{date(r.due)}{r.due<today()&&BigInt(r.remaining)>BigInt(0)&&' · گذشته از موعد'}</td></tr>)}</tbody></table></div><p className="subtle">ثبت دریافت و پرداخت، ثبت سابقه داخلی است و تراکنش بانکی انجام نمی‌دهد. تهاتر فقط بین ردیف‌های همین نماینده با مانده کافی ثبت می‌شود.</p></>}</>}</>}
 {tab==='settings'&&can('manager')&&<><div className="tools"><button className="btn primary" onClick={()=>start('agent')}>تعریف نماینده</button><button className="btn" onClick={()=>start('tariff')}>تعریف تعرفه قطعه / اجرت</button>{user.isAdmin&&<button className="btn" onClick={()=>onNavigate('users')}>حساب‌ها و دسترسی‌ها</button>}<button className="btn" onClick={()=>start('activation_preview')}>ورود سوابق فعال‌سازی</button><label className="btn"><Upload size={16}/>اکسل / CSV فعال‌سازی<input hidden type="file" accept=".xlsx,.csv,.tsv" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);e.target.value=''}}/></label></div><p className="subtle">فایل فعال‌سازی: ستون‌های serial، day (تاریخ شمسی مانند ۱۴۰۵/۰۷/۱۱)، months. تا ۲۰۰ ردیف در هر نوبت؛ پیش‌نمایش قبل از ثبت. فایل CSV ساده بدون ویرگول داخل مقدار؛ برای متن پیچیده از XLSX استفاده کنید.</p><h3>نمایندگی‌ها</h3><div className="as-grid">{data.agents.map((a:any)=><article className="flow-card" key={a.id}><h3>{a.data.name} · {a.data.code}</h3><p>{a.data.city} · {a.data.phone} · {a.data.active?'فعال':'غیرفعال'}</p>{action('agent',a)}</article>)}</div><h3>تعرفه‌ها</h3><div className="as-grid">{data.tariffs.map((t:any)=><article className="flow-card" key={t.id}><h3>{t.data.name}</h3><p>{t.data.kind==='part'?'قطعه':'اجرت'} · {money(t.data.priceRial)}</p><p>{date(t.data.validFrom)} · {t.data.active?'فعال':'غیرفعال'}</p>{action('tariff',t)}</article>)}</div></>}
 {tab==='reports'&&<ServiceReport data={data}/>}
 </>}
 <Dialog open={!!draft} onOpenChange={open=>{if(!open&&!busy)setDraft(null)}}><DialogContent dir="rtl" className="as-dialog"><DialogTitle>{serviceActions[draft?.mode]||'عملیات خدمات'}</DialogTitle><DialogDescription>عملیات با حساب شما ثبت می‌شود. تأیید تحویل، پاسخ مشتری و اندازه‌گیری‌ها را فقط بر اساس اقدام واقعی وارد کنید.</DialogDescription>{draft&&<form onSubmit={submit}><div className="formgrid"><Fields fields={serviceForms[draft.mode==='activation_import'?'activation_preview':draft.mode]||[]} value={draft} onChange={v=>{setDraft(v);setPreview([])}} options={options}/></div>{draft.mode==='repair'&&<p className="notice">با ثبت تعمیر، قطعات رزروشده از موجودی کسر و در شناسنامه دستگاه ثبت می‌شوند.</p>}{draft.mode==='order'&&<p className="notice">این درخواست فاکتور واقعی داخلی با مهلت یک ماه ایجاد می‌کند.</p>}{error&&<p className="notice error" role="alert">{error}</p>}{preview.length>0&&<><h3>پیش‌نمایش واردکردن</h3>{preview.map(r=><p key={r.row}>ردیف {fa(r.row)} · {r.serial} · {({new:'جدید',same:'قبلاً ثبت شده',conflict:'تعارض با سابقه',invalid:'نامعتبر'} as any)[r.status]} {r.error}</p>)}</>}<div className="tools"><button type="submit" className="btn primary" disabled={busy}>{busy?'در حال ثبت…':draft.mode==='activation_preview'?'بررسی بدون ثبت':'ثبت و اعمال'}</button>{preview.length>0&&!preview.some(r=>['invalid','conflict'].includes(r.status))&&<button type="button" className="btn primary" disabled={busy} onClick={async()=>{setBusy(true);try{await send({...draft,mode:'activation_import',id:crypto.randomUUID()});setDraft(null);setMessage('سوابق جدید وارد شدند؛ سابقه موجود بازنویسی نشد.');await refresh();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>تأیید و واردکردن ردیف‌های جدید</button>}<button type="button" className="btn" disabled={busy} onClick={()=>setDraft(null)}>انصراف</button></div></form>}</DialogContent></Dialog>
 </section>;
}
function ServiceReport({data}:{data:any}){
 const [from,setFrom]=useState(today().slice(0,8)+'01'),[to,setTo]=useState(today()),r=serviceReport(data.cases,from,to);
 const personTable=(people:any[],agent=false)=><div className="as-table"><table><thead><tr><th>{agent?'مرکز خدمات':'کارشناس'}</th><th>پرونده / تعمیر</th><th>تحویل</th><th>آزمون مردود</th><th>میانگین روز تا تحویل</th><th>رضایت / تعداد پاسخ</th></tr></thead><tbody>{people.map(p=><tr key={p.key}><td>{agent?(p.key==='office'?'دفتر شرکت':data.agents.find((a:any)=>a.id===p.key)?.data.name||p.key):p.key}</td><td>{fa(p.cases)} / {fa(p.repaired)}</td><td>{fa(p.delivered)}</td><td>{fa(p.failedTest)}</td><td>{p.meanCalendarDays===null?'—':fa(p.meanCalendarDays)}</td><td>{p.meanRating===null?'—':fa(p.meanRating)} / {fa(p.rated)}</td></tr>)}</tbody></table></div>;
 return <div className="panel"><h2><ClipboardCheck style={{display:'inline'}}/>عملکرد خدمات</h2><div className="formgrid"><SolarDate label="از تاریخ تماس" value={from} onChange={setFrom}/><SolarDate label="تا تاریخ تماس" value={to} onChange={setTo}/></div>{from>to?<p className="notice error">ابتدای بازه بعد از انتهاست.</p>:<><div className="as-grid"><div className="flow-card">پرونده‌های بازه<h2>{fa(r.cases)}</h2></div><div className="flow-card">تحویل‌شده از همین پرونده‌ها<h2>{fa(r.delivered)}</h2></div><div className="flow-card">رفع مشکل تلفنی<h2>{fa(r.resolvedByPhone)}</h2></div><div className="flow-card">ارزش مصرف به نرخ ثبت‌شده<h3>{money(r.partsCostRial)}</h3></div></div><h3>خرابی گزارش‌شده به تفکیک بچ خارج‌شده</h3><div className="as-table"><table><thead><tr><th>قطعه / بچ</th><th>مقدار گزارش‌شده</th><th>دستگاه یکتا</th></tr></thead><tbody>{r.faults.map((p:any)=><tr key={p.partCode+'|'+p.batchId}><td>{p.name} · {p.batchId||'نامشخص'}</td><td>{fa(p.quantity/1000)}</td><td>{fa(p.deviceCount)}</td></tr>)}</tbody></table></div><p className="subtle">این اعداد تعداد گزارش‌اند، نه نرخ خرابی کل تولید. بچ نامشخص جداست؛ علت اولیه نتیجه قطعی درباره قطعه یا مونتاژکار نیست.</p><h3>کارشناسان تعمیر</h3>{personTable(r.people)}<h3>دفتر و نمایندگان</h3>{personTable(r.agents,true)}<p className="subtle">بازه بر اساس تاریخ تماس است. زمان تا تحویل شامل انتظار قطعه و پاسخ مشتری هم می‌شود. ارزش مصرف، نرخ ورودی خدمات دفتر یا نرخ فاکتور نماینده است و جای حسابداری بهای تمام‌شده را نمی‌گیرد. ارزیابی افراد باید پیچیدگی عیب، حجم پرونده و تعداد پاسخ مشتری را در نظر بگیرد؛ رتبه‌بندی خودکار انجام نشده است.</p></>}</div>;
}
