'use client';
import {useEffect,useRef,useState} from 'react';
import {Box,ArrowRightLeft,ClipboardCheck,FileText,RefreshCw,Plus,Users} from 'lucide-react';
import {ProgramWorkspace,SubprogramNavigation,IconActions,LayoutAccountProvider} from './program-workspace';
import {SolarDate} from './solar-date';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {assetHolderKinds,assetConditions} from '@/lib/assets-contract';
import {formatDate,formatDateTime,localDay} from '@/lib/persian-date';
const modeLabels:Record<string,string>={register:'ثبت مال جدید',edit:'ویرایش مشخصات',transfer:'تحویل / برگشت مال',confirm_annual:'ثبت تأیید کتبی پیمانکار',request_clearance:'درخواست تسویه اموال ترک کار',approve_clearance:'تأیید تسویه اموال',cancel_clearance:'لغو فرایند ترک کار'};
export function AssetsPanel({demo=false,targetId='',memberId='',embedded=false}:{demo?:boolean;targetId?:string;memberId?:string;embedded?:boolean}){
const detailAnchor=useRef<HTMLElement|null>(null);
const [data,setData]=useState<any>(null),[selected,setSelected]=useState(targetId),[view,setView]=useState('mine'),[query,setQuery]=useState(''),[mode,setMode]=useState(''),[draft,setDraft]=useState<any>({}),[op,setOp]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
async function load(){if(demo)return;const r=await fetch('/api/assets',{cache:'no-store'}),j:any=await r.json();if(!r.ok)throw Error(j.error||'دریافت اموال انجام نشد.');setData(j)}
useEffect(()=>{void load().catch(e=>setError(e.message))},[demo]);useEffect(()=>{if(targetId){setSelected(targetId);setView('all')}},[targetId]);
useEffect(()=>{if(selected&&data){detailAnchor.current?.scrollIntoView({block:'start',behavior:'smooth'});detailAnchor.current?.focus({preventScroll:true})}},[selected,data?.accountId]);
const record=data?.records.find((r:any)=>r.id===selected),d=record?.data,items=data?.records.filter((r:any)=>r.type==='asset_item')||[],me=memberId||data?.me,mine=items.filter((r:any)=>r.data.holderKind==='employee'&&r.data.holderId===me),clearances=data?.records.filter((r:any)=>r.type==='asset_clearance')||[];
function start(m:string,r:any=null){setMode(m);setOp(crypto.randomUUID());setError('');setMessage('');setDraft({day:localDay(),holderKind:'stock',condition:'good',memberId:data.me,...(r?.data||{}),contractorCode:r?.data?.holderKind==='contractor'?r.data.holderId:'',recordId:r?.id||'',revision:r?.revision||0,notes:'',...(m==='confirm_annual'?{day:localDay(),reference:'',signer:'',fileId:'',actualConfirmation:false}:{})})}
const change=(k:string,v:any)=>setDraft((p:any)=>({...p,[k]:v}));
async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const payload={id:op,confirmed:true,mode,revision:draft.revision,notes:draft.notes,...(draft.recordId?{recordId:draft.recordId}:{})};const fields=mode==='register'||mode==='edit'?['code','name','category','brand','model','serial','specifications','condition',...(mode==='register'?['location','day','reference']:[])]:mode==='transfer'?['holderKind','holderId','holderName','contractorCode','contractorContact','location','condition','day','reference','purpose']:mode==='confirm_annual'?['day','signer','reference','fileId','actualConfirmation','location','condition']:mode==='request_clearance'?['memberId']:mode==='approve_clearance'?['reference']:[];const body={...payload,...Object.fromEntries(fields.filter(k=>draft[k]!==undefined).map(k=>[k,draft[k]]))};const r=await fetch('/api/assets',{method:'POST',headers:{'Content-Type':'application/json','x-asset-account':data.accountId},body:JSON.stringify(body)}),j:any=await r.json();if(!r.ok)throw Error(j.error||'ثبت انجام نشد.');setMode('');await load();setSelected(j.id);setMessage(j.followupPending?'ثبت شد؛ تسک در همگام‌سازی بعدی به‌روز می‌شود.':'ثبت شد و کارتابل به‌روز شد.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function upload(file:File){if(!record)return;setBusy(true);setError('');try{const q=new URLSearchParams({id:crypto.randomUUID(),assetId:record.id,revision:String(record.revision),filename:file.name,confirmed:'true'}),r=await fetch('/api/assets/files?'+q,{method:'POST',headers:{'Content-Type':'application/octet-stream','x-asset-account':data.accountId},body:file}),j:any=await r.json();if(!r.ok)throw Error(j.error);await load();change('fileId',j.id);setMessage('نامه پیوست شد؛ مشخصات تأیید را تکمیل و ثبت کنید.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function installPosition(){setBusy(true);try{const r=await fetch('/api/assets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),confirmed:true,mode:'install_position',revision:0,notes:'تعریف سمت اموال‌دار برای واگذاری بعدی'})}),j:any=await r.json();if(!r.ok)throw Error(j.error);setMessage('سمت اموال‌دار در سمت‌ها و برنامه وظایف آماده است؛ فرد را آنجا تعیین و در کاربران، دسترسی اموال‌دار را فعال کنید.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
const input=(k:string,label:string,required=true,long=false)=><label className="field" key={k}>{label}{long?<textarea required={required} rows={3} maxLength={k==='specifications'?6000:4000} value={draft[k]||''} onChange={e=>change(k,e.target.value)}/>:<input required={required} maxLength={300} value={draft[k]||''} onChange={e=>change(k,e.target.value)}/>}</label>;
const pick=(k:string,label:string,choices:Record<string,string>)=><label className="field">{label}<select required value={draft[k]||''} onChange={e=>change(k,e.target.value)}><option value="">انتخاب کنید</option>{Object.entries(choices).map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label>;
if(demo)return <section className="panel inside">اموال شرکت در محیط واقعی قابل مشاهده و ثبت است.</section>;
if(!data)return <section className="panel inside"><p role={error?'alert':'status'}>{error||'در حال دریافت اموال…'}</p><button className="btn" onClick={()=>void load().catch(e=>setError(e.message))}>تازه‌سازی</button></section>;
const current=embedded?'mine':view,filtered=(current==='clearance'?clearances:current==='mine'?mine:items.filter((r:any)=>current==='contractors'?r.data.holderKind==='contractor':current==='due'?r.data.holderKind==='contractor'&&r.data.annualDue<=localDay():true)).filter((r:any)=>!query||[r.data.name,r.data.code,r.data.holderName,r.data.location,r.data.memberName].join(' ').includes(query));
const content=<section className="panel inside assets-panel"><div className="tools"><Box/><h2>{embedded?'اموال امانی من / پرونده پرسنلی':'اموال شرکت'}</h2></div><p>هر مال: مشخصات، محل، تحویل‌گیرنده و سابقهٔ تحویل. تسویهٔ اموال جدا از تسویهٔ مالی است.</p>
{error&&<p className="notice error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
{!embedded&&<><SubprogramNavigation value={view} onChange={v=>{setView(v);setSelected('')}} items={[['mine','اموال امانی من'],...(data.custodian?[['all','دفتر اموال'],['contractors','اموال نزد پیمانکار'],['due','تأییدهای سررسیدشده']] as [string,string][]:[]),['clearance','تسویه اموال ترک کار']]}/><IconActions scope="asset-main-actions">{data.custodian&&<button className="btn primary" disabled={busy} onClick={()=>start('register')}><Plus/>ثبت مال جدید</button>}<button className="btn" disabled={busy} onClick={()=>start('request_clearance')}><ClipboardCheck/>درخواست تسویه اموال</button>{data.admin&&<button className="btn" disabled={busy} onClick={()=>void installPosition()}><Users/>ایجاد سمت اموال‌دار</button>}<button className="btn" disabled={busy} onClick={()=>void load().catch(e=>setError(e.message))}><RefreshCw/>تازه‌سازی</button></IconActions></>}
<label className="field">جست‌وجوی اموال<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="نام، کد، تحویل‌گیرنده یا محل"/></label>
{record&&(!embedded||record.type==='asset_item'&&record.data.holderId===me)&&<section ref={detailAnchor} className="panel inside" tabIndex={-1} style={{scrollMarginTop:80}}><h3>{d.name||d.memberName}</h3>{record.type==='asset_item'?<><dl>{Object.entries({code:'کد اموال',category:'گروه',brand:'برند',model:'مدل',serial:'سریال',specifications:'مشخصات',holderName:'تحویل‌گیرنده',location:'محل',reference:'مرجع تحویل',lastSigner:'امضاکننده آخرین تأیید',lastConfirmationReference:'شماره آخرین نامه تأیید',contractorContact:'راه تماس پیمانکار',purpose:'هدف استفاده'}).map(([k,label])=><div key={k}><dt>{label}</dt><dd style={{whiteSpace:'pre-wrap'}}>{d[k]||'—'}</dd></div>)}</dl><p>تاریخ تحویل: {formatDate(d.handedDay)} · تأیید قبلی: {formatDate(d.lastConfirmedDay)} · تأیید بعدی: {formatDate(d.annualDue)}</p>{!embedded&&data.custodian&&<IconActions scope="asset-item-actions"><button className="btn" disabled={busy} onClick={()=>start('edit',record)}>ویرایش مشخصات</button><button className="btn" disabled={busy} onClick={()=>start('transfer',record)}><ArrowRightLeft/>تحویل / برگشت</button>{d.holderKind==='contractor'&&<button className="btn" disabled={busy} onClick={()=>start('confirm_annual',record)}><ClipboardCheck/>ثبت تأیید کتبی سالانه</button>}</IconActions>}
<h4>تأییدهای کتبی این تحویل</h4>{data.records.filter((c:any)=>c.type==='asset_confirmation'&&c.data.assetId===record.id&&c.data.custodyId===d.custodyId).map((c:any)=><div className="flow-card" key={c.id}><p>{formatDate(c.data.day)} · امضاکننده: {c.data.signer} · شماره نامه: {c.data.reference}</p><p>{assetConditions[c.data.condition]} · {c.data.location}</p><a href={'/api/assets/files?id='+encodeURIComponent(c.data.fileId)}>دریافت نامه تأیید</a></div>)}<h4>نامه‌های این تحویل</h4>{data.records.filter((f:any)=>f.type==='asset_file'&&f.data.assetId===record.id&&f.data.custodyId===d.custodyId).map((f:any)=><p key={f.id}><a href={'/api/assets/files?id='+encodeURIComponent(f.id)}>{f.data.filename}</a></p>)}</>:<><p>اموال باقیمانده: {items.filter((x:any)=>x.data.holderKind==='employee'&&x.data.holderId===d.memberId).length.toLocaleString('fa-IR')} مورد</p><p>شماره تأیید: {d.reference||'—'} · تأییدکننده: {d.approvedName||'—'}</p><IconActions scope="asset-clearance-actions">{data.custodian&&d.state==='open'&&<button className="btn" disabled={busy||items.some((x:any)=>x.data.holderKind==='employee'&&x.data.holderId===d.memberId)} onClick={()=>start('approve_clearance',record)}>تأیید تسویه اموال</button>}{data.hr&&d.state!=='cancelled'&&<button className="btn" disabled={busy} onClick={()=>start('cancel_clearance',record)}>لغو فرایند ترک کار</button>}</IconActions></>}
<h4>سابقه</h4>{(d.history||[]).map((h:any,i:number)=><div className="flow-card" key={i}><strong>{modeLabels[h.mode]||h.mode} · {h.name}</strong><p>{formatDateTime(h.at)} · {h.holderName} · {h.location}</p><p>{h.notes}</p></div>)}<button className="btn" onClick={()=>setSelected('')}>بستن جزئیات</button></section>}

<div className="flow-grid">{filtered.map((r:any)=><article className="flow-card" key={r.id}><h3>{r.type==='asset_item'?r.data.name:r.data.memberName}</h3>{r.type==='asset_item'?<><p>کد اموال: <bdi>{r.data.code}</bdi> · {assetConditions[r.data.condition]}</p><p>{assetHolderKinds[r.data.holderKind]}: {r.data.holderName} · محل: {r.data.location}</p>{r.data.annualDue&&<p>تأیید بعدی: {formatDate(r.data.annualDue)} {r.data.annualDue<=localDay()?'· سررسیدشده':''}</p>}</>:<p>{r.data.state==='open'?'در انتظار برگشت و تأیید اموال‌دار':r.data.state==='cleared'?'تسویه اموال تأیید شده':'فرایند لغو شده'} · {formatDate(r.data.requestedDay)}</p>}<button className="btn" onClick={()=>setSelected(r.id)}><FileText size={16}/>مشخصات و سابقه</button></article>)}</div>{!filtered.length&&<p className="empty">موردی در این فهرست نیست.</p>}
<Dialog open={!!mode} onOpenChange={v=>{if(!v&&!busy)setMode('')}}><DialogContent dir="rtl" style={{maxHeight:'90vh',overflowY:'auto'}}><DialogHeader><DialogTitle>{modeLabels[mode]||'اموال'}</DialogTitle><DialogDescription>اطلاعات واقعی را ثبت کنید؛ سابقهٔ پیشین حفظ می‌شود.</DialogDescription></DialogHeader><form onSubmit={save}><fieldset disabled={busy}>
{['register','edit'].includes(mode)&&<>{input('code','کد یکتای اموال')}{input('name','نام مال')}{input('category','گروه اموال (مثلاً قالب تزریق پلاستیک)')}{input('brand','برند',false)}{input('model','مدل',false)}{input('serial','سریال',false)}{input('specifications','مشخصات فنی',false,true)}{pick('condition','وضعیت سلامت',assetConditions)}{mode==='register'&&<>{input('location','انبار / محل اولیه')}{input('reference','مرجع ورود یا رسید')}<SolarDate label="تاریخ ورود" value={draft.day} onChange={v=>change('day',v)}/></>}</>}
{mode==='transfer'&&<>{pick('holderKind','نوع تحویل‌گیرنده',assetHolderKinds)}{draft.holderKind==='employee'&&pick('holderId','کارمند تحویل‌گیرنده',Object.fromEntries(data.members.map((m:any)=>[m.id,m.name])))}{draft.holderKind==='contractor'&&<>{input('contractorCode','شناسه / کد پیمانکار')}{input('holderName','نام پیمانکار')}{input('contractorContact','راه تماس پیمانکار',false)}</>}{input('location','انبار یا محل دقیق استقرار')}{input('reference','شماره رسید تحویل یا برگشت')}{input('purpose','هدف استفاده',false,true)}{pick('condition','وضعیت سلامت هنگام تحویل',assetConditions)}<SolarDate label="تاریخ تحویل واقعی" value={draft.day} onChange={v=>change('day',v)}/><p>برای برگشت، نوع تحویل‌گیرنده را «انبار / محل شرکت» انتخاب کنید.</p></>}
{mode==='confirm_annual'&&<><SolarDate label="تاریخ تأیید واقعی پیمانکار" value={draft.day} onChange={v=>change('day',v)}/>{input('signer','نام امضاکننده نامه')}{input('reference','شماره نامه تأیید')}{input('location','محل تأییدشده مال')}{pick('condition','وضعیت تأییدشده',assetConditions)}<label className="field">پیوست نامه (حداکثر ۱۰ مگابایت)<input type="file" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/></label>{pick('fileId','نامه این تأیید',Object.fromEntries(data.records.filter((f:any)=>f.type==='asset_file'&&f.data.assetId===record?.id&&f.data.custodyId===record?.data.custodyId&&!data.records.some((c:any)=>c.type==='asset_confirmation'&&c.data.fileId===f.id)).map((f:any)=>[f.id,f.data.filename])))}<label><input type="checkbox" required checked={!!draft.actualConfirmation} onChange={e=>change('actualConfirmation',e.target.checked)}/> تأیید کتبی واقعی پیمانکار دریافت شده است.</label></>}
{mode==='request_clearance'&&(data.custodian||data.hr)&&pick('memberId','فرد در حال ترک کار',Object.fromEntries(data.members.map((m:any)=>[m.id,m.name])))}{mode==='approve_clearance'&&input('reference','شماره تأیید تسویه اموال')}{input('notes','توضیح و علت',true,true)}<button className="btn primary" disabled={busy}>{busy?'در حال ثبت…':'تأیید اطلاعات و ثبت'}</button>{error&&<p role="alert">{error}</p>}</fieldset></form></DialogContent></Dialog>
</section>;
return <LayoutAccountProvider accountId={data.accountId}>{embedded?content:<ProgramWorkspace programId="assets" title="اموال شرکت" direct={!!targetId}>{content}</ProgramWorkspace>}</LayoutAccountProvider>;
}
