'use client';
import {displayDateField} from '@/lib/persian-date';
import {inboxModes} from '@/lib/inbox-contract';
import {useState} from 'react';
import {names} from '@/lib/model';
import {serviceRoles,serviceDomains} from '@/lib/after-sales-labels';
import {supplyRoles} from '@/lib/sourcing-labels';
export type AssistantAction={id:string;turnId:string;tool:string;title:string;args:Record<string,any>;state:string;result:any;expires:string;section:string};
const labels:Record<string,string>={startDate:'تاریخ شروع',needBy:'موعد نیاز',availableOn:'تاریخ تأمین وجه',fxDate:'تاریخ نرخ ارز',eta:'موعد دریافت',validFrom:'شروع اعتبار',validUntil:'پایان اعتبار',newDue:'مهلت جدید',recipientName:'نام گیرنده',threadId:'گفت‌وگو',recipientType:'نوع گیرنده',recipientId:'گیرنده',priority:'اولویت',until:'زمان یادآوری',link:'پرونده مرتبط',section:'بخش',mode:'اقدام',transportRoles:'نقش‌های تدارکات',sourceKey:'مرجع حمل',missionId:'مأموریت',driverId:'راننده',vehicleId:'خودرو',receiverId:'مسئول دریافت',packages:'تعداد بسته',pickup:'محل دریافت',destination:'مقصد',recipient:'تحویل‌گیرنده',phone:'تلفن',waybill:'بارنامه',tracking:'کد رهگیری',carrier:'باربری',due:'موعد',username:'نام کاربری',permissions:'دسترسی‌ها',read:'مشاهده',write:'ثبت و ویرایش',eventStages:'مراحل تولید',flowRoles:'نقش گردش مواد',supplyRoles:'نقش تأمین',serviceRoles:'نقش خدمات',serviceDomains:'حوزه خدمات',serviceAgentId:'نمایندگی',warehouses:'انبارهای مجاز',finance:'کنترل مالی',group:'گروه محصول',kind:'نوع رکورد',data:'اطلاعات',code:'کد',name:'نام',model:'مدل',status:'وضعیت',category:'گروه',warrantyMonths:'گارانتی (ماه)',partCode:'کد قطعه',part:'قطعه',supplier:'تأمین‌کننده',maker:'سازنده',date:'تاریخ',day:'تاریخ',quantity:'تعداد / مقدار',count:'تعداد',unit:'واحد',notes:'توضیحات',reason:'دلیل',productId:'شناسه محصول',deviceId:'شناسه دستگاه',deviceIds:'شناسه دستگاه‌ها',batchId:'شناسه بچ',materialId:'شناسه کالا',receiptId:'شناسه رسید',requestId:'شناسه درخواست',planId:'شناسه برنامه',supplyId:'شناسه تأمین',id:'شناسه',revision:'نسخه رکورد',previousVersion:'نسخه قبلی',previous:'اطلاعات پیش از ویرایش',allocations:'بچ‌ها و مقدار مصرف',location:'مکان انبار',from:'از انبار',to:'به انبار',operator:'مسئول',assembler:'مونتاژکار',title:'عنوان',body:'متن',responsible:'مسئول پاسخ',report_id:'گزارش',period:'بازه',cadence:'دوره',values:'مقادیر اندازه‌گیری',verdict:'نتیجه',cause:'علت',accepted:'مقدار قبول',rejected:'مقدار رد',design:'نسخه طراحی',firmware:'نسخه نرم‌افزار',capacity:'ظرفیت',smallLabels:'تعداد برچسب کوچک',specs:'مشخصات',defaultLocation:'مکان پیش‌فرض',reorderPoint:'حد سفارش',targetStock:'موجودی هدف',fields:'فیلدهای کنترل کیفیت',qcOwner:'مسئول کنترل کیفیت',warehouseOwner:'مسئول انبار',procurementOwner:'مسئول تأمین',expiry:'انقضا',manufacturerLot:'بچ سازنده',purchase:'مرجع خرید',lines:'اقلام BOM',oldBatchId:'بچ قبلی',newBatchId:'بچ جایگزین',result:'نتیجه',device:'دستگاه',templateId:'فرم کنترل کیفیت',bomId:'نسخه BOM',orderId:'برگ تولید'};
const values:Record<string,string>={...names,...supplyRoles,...serviceRoles,...serviceDomains,active:'فعال',disabled:'غیرفعال',none:'بدون دسترسی',read:'مشاهده',write:'مشاهده و ثبت',raw:'مواد اولیه',line:'خط تولید',quarantine:'قرنطینه',nonconforming:'نامنطبق',finished:'محصول نهایی',qc:'کنترل کیفیت',production:'تولید',procurement:'تأمین',sales:'فروش'};
function Details({value,field=''}:{value:any;field?:string}){if(field==='previous'&&typeof value==='string'){try{return <Details value={JSON.parse(value)}/>}catch{}}if(value===null||typeof value!=='object')return <span>{(field==='mode'?inboxModes[String(value)]:undefined)||(['status','permissions','read','write','flowRoles','supplyRoles','serviceRoles','serviceDomains','warehouses','finance'].includes(field)?values[String(value)]:undefined)||String(displayDateField(field,value)??'—')||'—'}</span>;if(Array.isArray(value))return <span>{value.length?value.map((v,i)=><span key={i}>{i>0?'، ':''}{typeof v==='object'?<Details value={v}/>:<Details value={values[String(v)]||v} field={field}/>}</span>):'هیچ‌کدام'}</span>;return <dl className="assistant-arguments">{Object.entries(value).filter(([k])=>k!=='confirmed').map(([k,v])=><div key={k}><dt>{labels[k]||k}</dt><dd><Details value={v} field={k}/></dd></div>)}</dl>}
const states:Record<string,string>={pending:'در انتظار تأیید شما',running:'در حال اجرا؛ از تکرار فرمان خودداری کنید',review:'نیاز به بررسی نتیجه',succeeded:'اجرا شد',cancelled:'لغو شد',expired:'مهلت تأیید تمام شده'};
export function ActionCards({actions,busy,onDecide,onOpen}:{actions:AssistantAction[];busy:boolean;onDecide:(id:string,decision:'confirm'|'cancel',password?:string)=>void;onOpen:(section:string)=>void}){const [passwords,setPasswords]=useState<Record<string,string>>({});return <div className="assistant-actions">{actions.map(a=><article className="assistant-action-card" key={a.id}><strong>{a.title}</strong><p role="status">{states[a.state]||a.state}</p>{a.state==='pending'?<><p className="subtle">این تغییر روی اطلاعات واقعی شرکت ثبت می‌شود. جزئیات را بررسی کنید.</p><Details value={a.args}/>{a.tool==='create_password_user'&&<label className="field">رمز عبور حساب جدید<input type="password" autoComplete="new-password" minLength={10} maxLength={128} value={passwords[a.id]||''} onChange={e=>setPasswords(p=>({...p,[a.id]:e.target.value}))}/><span className="subtle">رمز فقط هنگام ثبت ارسال می‌شود؛ در گفتگو یا مدل ذخیره نمی‌شود.</span></label>}<div className="tools"><button className="btn primary" disabled={busy||(a.tool==='create_password_user'&&(passwords[a.id]||'').length<10)} onClick={()=>{onDecide(a.id,'confirm',passwords[a.id]);setPasswords(p=>({...p,[a.id]:''}));}}>تأیید و اجرا</button><button className="btn" disabled={busy} onClick={()=>onDecide(a.id,'cancel')}>لغو</button></div><p className="subtle">{a.tool==='create_password_user'?'برای ایجاد حساب، رمز را وارد کنید و دکمهٔ تأیید و اجرا را بزنید.':'می‌توانید «تأیید اجرا» یا «لغو فرمان» را هم بگویید و ارسال کنید.'}</p></>:<details><summary>جزئیات فرمان و نتیجه</summary><Details value={a.args}/>{a.result&&<Details value={a.result}/>}</details>}{a.result?.error&&<p role="alert">{a.result.error}</p>}<button className="link" onClick={()=>onOpen(a.section)}>نمایش بخش مربوطه</button></article>)}</div>}
