'use client';
import {useEffect,useState} from 'react';
import {formPresentation,fieldTitle,displayedValue} from '@/lib/assistant-form-presentation';
import {type OperationForm} from '@/lib/assistant-workspace';
import {ActionCards,Details,type AssistantAction} from './assistant-actions';
import {SolarDate} from './solar-date';
import {MoneyInput} from './money-input';
export function AssistantWorkspace({form,accountId,onChange,onSaved,onClose}:{form:OperationForm;accountId:string;onChange:(v:OperationForm)=>void;onSaved:()=>void;onClose:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[changed,setChanged]=useState<string[]>([]);
 useEffect(()=>{setChanged(Object.keys(form.args).filter(k=>form.args[k]!==undefined&&form.args[k]!==null&&form.args[k]!==''));setError('');},[form]);
 const presentation=formPresentation(form.tool,form.args,form.schema,form.title);
 const locked=busy||!!form.actionId;
 function editor(value:any,schema:any,key:string,path:string[],required?:boolean):any{
  if(schema?.uiHidden)return null;
  const name=fieldTitle(form.tool,key,schema),set=(v:any)=>{const next=structuredClone(form.args);let target=next;for(const k of path.slice(0,-1)){target[k]??={};target=target[k];}target[path.at(-1)!]=v;onChange({...form,args:next});};
  if(key==='mode')return <label className="field" key={path.join('.')}><span>اقدام</span><input aria-label="اقدام" readOnly value={displayedValue(form.tool,path,value,schema)||'هنوز مشخص نشده'}/></label>;
  if(schema?.type==='object'||value&&typeof value==='object'&&!Array.isArray(value)){const entries={...(schema?.properties||{}),...Object.fromEntries(Object.keys(value||{}).map(k=>[k,schema?.properties?.[k]||{}]))};return <fieldset key={path.join('.')} className="wide" style={{gridColumn:"1 / -1",minWidth:0}}><legend>{name}</legend><div className="formgrid">{Object.entries(entries).filter(([k])=>!['confirmed','password','token','secret'].includes(k)).map(([k,s])=>editor(value?.[k],s,k,[...path,k],schema?.required?.includes(k)))}</div></fieldset>;}
  if(Array.isArray(value)||schema?.type==='array')return <fieldset key={path.join('.')} className="wide" style={{gridColumn:"1 / -1",minWidth:0}}><legend>{name}</legend>{(value||[]).map((v:any,i:number)=><div key={i}>{editor(v,schema?.items||{},key,[...path,String(i)],required)}{!locked&&<button className="link" onClick={()=>set(value.filter((_:any,n:number)=>n!==i))}>حذف ردیف {i+1}</button>}</div>)}{!locked&&<button className="btn" onClick={()=>set([...(value||[]),schema?.items?.type==='object'?{}:schema?.items?.type==='number'?0:''])}>افزودن ردیف</button>}</fieldset>;
  const readonly=['id','requestId','revision','previousVersion','quoteHash','previous'].includes(key)||key.endsWith('Id');
  if(schema?.format==='money')return <label className="field" key={path.join('.')} style={{background:changed.includes(path[0])&&value!==undefined&&value!==''?'#eef8f3':undefined,borderRadius:8,padding:8}}><span>{name}{required?' *':''}</span><MoneyInput aria-label={name} readOnly={readonly} disabled={locked} required={required} value={value??''} onChange={set}/><small>ریال</small></label>;
  if(!readonly&&(schema?.format==='date'||/^(date|day|due|eta|expiry|needBy|.*Day|.*Date|validFrom|validUntil|availableOn)$/.test(key)))return <SolarDate key={path.join('.')} label={name} value={value||''} required={required??false} showOptional={required!==undefined} disabled={locked} onChange={set}/>;
  return <label className="field" key={path.join('.')} style={{background:changed.includes(path[0])&&value!==undefined&&value!==null&&value!==''?'#eef8f3':undefined,borderRadius:8,padding:8}}><span>{name}{required?' *':''}</span>{schema?.enum?<select disabled={locked||readonly} value={value??''} onChange={e=>set(e.target.value)}><option value="">انتخاب کنید</option>{schema.enum.map((v:any)=><option key={String(v)} value={String(v)}>{displayedValue(form.tool,path,v,schema)}</option>)}</select>:schema?.type==='boolean'||typeof value==='boolean'?<select disabled={locked} value={value===undefined?'':String(value)} onChange={e=>set(e.target.value===''?undefined:e.target.value==='true')}><option value="">انتخاب کنید</option><option value="true">بله</option><option value="false">خیر</option></select>:schema?.multiline?<textarea aria-label={name} disabled={locked} value={value??''} placeholder="هنوز تکمیل نشده" onChange={e=>set(e.target.value)}/>:<input aria-label={name} readOnly={readonly} disabled={locked} value={value??''} placeholder={readonly?'پس از انتخاب پرونده مشخص می‌شود':'هنوز تکمیل نشده'} type={schema?.type==='number'||schema?.type==='integer'?'number':'text'} onChange={e=>set(schema?.type==='number'||schema?.type==='integer'?e.target.value===''?undefined:Number(e.target.value):e.target.value)}/>}</label>;
 }
 async function request(path:string,body:any){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','x-assistant-account':accountId},body:JSON.stringify(body)}),d:any=await r.json();if(!r.ok)throw Error(d.error||'فرم آماده نشد.');if(d.accountId!==accountId)throw Error('حساب ورود تغییر کرده است.');return d;}
 function showAction(a:AssistantAction){onChange({...form,args:a.args,actionId:a.id,state:a.state,result:a.result});window.dispatchEvent(new CustomEvent('nafasyar-form-action',{detail:{accountId,action:a}}));}
 async function prepare(){setBusy(true);setError('');try{const d=await request('/api/assistant/forms',{id:crypto.randomUUID(),tool:form.tool,args:form.args});showAction(d.action);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function decide(id:string,decision:'confirm'|'cancel',password?:string){setBusy(true);setError('');try{const d=await request('/api/assistant/actions',{id,decision,confirmed:decision==='confirm',...(password?{password}:{})});showAction(d.action);if(d.action.state==='succeeded'){onSaved();window.dispatchEvent(new Event('nafasyar-tasks-changed'));window.dispatchEvent(new Event('nafasyar-inbox-changed'));}return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 const action:AssistantAction={id:form.actionId||'',turnId:'',tool:form.tool,title:presentation.title,args:form.args,state:form.state||'draft',result:form.result,expires:'',section:form.section};
 return <section className="panel inside" aria-label="فرم همراه دستیار" dir="rtl" style={{marginBottom:20,border:'2px solid #77ab95'}}><div className="panelhead"><div><h2>{presentation.title}</h2><p role="status">{form.state==='succeeded'?'ثبت انجام شد؛ نتیجه در همین بخش قابل بررسی است.':form.state==='review'?'نتیجه نیاز به بررسی دارد؛ قبل از تکرار سوابق را ببینید.':'فرم همراه دستیار؛ فیلدها با پاسخ‌های شما تکمیل می‌شوند.'}</p></div><button className="link" onClick={onClose} disabled={busy}>بستن فرم همراه</button></div><p className="subtle">فیلدهای سبز اطلاعات دریافت‌شده را نشان می‌دهند. موارد خالی هنوز مشخص نشده‌اند. می‌توانید فرم را دستی تکمیل کنید؛ آماده‌سازی فرم به معنی ثبت نیست.</p><div className="formgrid">{Object.entries(presentation.schema.properties||{}).filter(([k])=>!['id','requestId','confirmed'].includes(k)).map(([k,s])=>editor(form.args[k],s,k,[k],presentation.schema.required?.includes(k)))}</div>{error&&<p className="notice error" role="alert">{error}</p>}{!form.actionId&&<button className="btn primary" disabled={busy} onClick={prepare}>بررسی و آماده‌سازی برای تأیید</button>}{form.actionId&&<ActionCards actions={[action]} busy={busy} onDecide={decide}/>}{form.state==='succeeded'&&<Details value={form.result||{saved:true}}/>}{['cancelled','expired'].includes(form.state||'')&&<button className="btn" onClick={()=>onChange({...form,actionId:undefined,state:undefined,result:undefined})}>اصلاح و آماده‌سازی دوباره</button>}</section>;
}
