'use client';
import {formPresentation,fieldTitle,displayedValue} from '@/lib/assistant-form-presentation';
import {displayDateField} from '@/lib/persian-date';
import {useEffect,useState} from 'react';
export type AssistantAction={id:string;turnId:string;tool:string;title:string;args:Record<string,any>;state:string;result:any;expires:string;section:string};
export {fieldTitles as labels} from '@/lib/form-vocabulary';
export function Details({value,field='',tool='',schema,path=[]}:{value:any;field?:string;tool?:string;schema?:any;path?:string[]}){
 if(field==='previous'&&typeof value==='string'){try{return <Details value={JSON.parse(value)} tool={tool}/>}catch{}}
 if(value===null||typeof value!=='object')return <span>{String(displayDateField(field,displayedValue(tool,path,value,schema))??'—')||'—'}</span>;
 if(Array.isArray(value))return <span>{value.length?value.map((v,i)=><span key={i}>{i>0?'، ':''}<Details value={v} field={field} tool={tool} schema={schema?.items} path={[...path,'*']}/></span>):'هیچ‌کدام'}</span>;
 return <dl className="assistant-arguments">{Object.entries(value).filter(([k])=>!['confirmed','requestId','revision','previousVersion','previousRevision','quoteHash','catalogSnapshot'].includes(k)&&!/password|token|secret|cipher|api.?key/i.test(k)).map(([k,v])=><div key={k}><dt>{fieldTitle(tool,k,schema?.properties?.[k])}</dt><dd><Details value={v} field={k} tool={tool} schema={schema?.properties?.[k]} path={[...path,k]}/></dd></div>)}</dl>;
}
function ActionDetails({action}:{action:AssistantAction}){
 const p=formPresentation(action.tool,action.args,{type:'object',properties:{}},action.title);
 const args={...action.args};if(!['update_record','delete_record','update_user','delete_user'].includes(action.tool))delete args.id;
 return <Details value={args} tool={action.tool} schema={p.schema}/>;
}
const states:Record<string,string>={pending:'در انتظار تأیید شما',running:'در حال اجرا؛ از تکرار فرمان خودداری کنید',review:'نیاز به بررسی نتیجه',succeeded:'اجرا شد',cancelled:'لغو شد',expired:'مهلت تأیید تمام شده'};
export function ActionCards({actions,busy,onDecide,onOpen}:{actions:AssistantAction[];busy:boolean;onDecide:(id:string,decision:'confirm'|'cancel',password?:string)=>Promise<boolean|undefined>;onOpen?:(section:string)=>void}){const [passwords,setPasswords]=useState<Record<string,string>>({});const [visible,setVisible]=useState<Record<string,boolean>>({});const [dismissed,setDismissed]=useState<Record<string,boolean>>({});useEffect(()=>{setPasswords(p=>Object.fromEntries(Object.entries(p).filter(([id])=>actions.some(a=>a.id===id&&a.state==='pending'))));},[actions]);return <div className="assistant-actions">{actions.filter(a=>!["succeeded","cancelled","expired"].includes(a.state)&&!dismissed[a.id]).map(a=><article className="assistant-action-card" key={a.id}><strong>{formPresentation(a.tool,a.args,{type:'object',properties:{}},a.title).title}</strong><p role="status">{states[a.state]||a.state}</p>{a.state==='pending'?<><p className="subtle">این تغییر روی اطلاعات واقعی شرکت ثبت می‌شود. جزئیات را بررسی کنید.</p><ActionDetails action={a}/>{a.tool==='create_password_user'&&<label className="field">رمز عبور حساب جدید<input type={visible[a.id]?"text":"password"} dir="ltr" spellCheck={false} autoCapitalize="none" autoComplete="new-password" minLength={10} maxLength={128} value={passwords[a.id]||''} onChange={e=>setPasswords(p=>({...p,[a.id]:e.target.value}))}/><button type="button" className="link" aria-pressed={!!visible[a.id]} onClick={()=>setVisible(p=>({...p,[a.id]:!p[a.id]}))}>{visible[a.id]?"پنهان کردن رمز":"نمایش رمز"}</button><span className="subtle">۱۰ تا ۱۲۸ کاراکتر؛ حروف بزرگ و کوچک و فاصله‌ها دقیقاً حفظ می‌شوند. رمز فقط هنگام ثبت ارسال می‌شود؛ در گفتگو یا مدل ذخیره نمی‌شود.</span></label>}<div className="tools"><button className="btn primary" disabled={busy||(a.tool==='create_password_user'&&(passwords[a.id]||'').length<10)} onClick={async()=>{if(await onDecide(a.id,'confirm',passwords[a.id])){setPasswords(p=>({...p,[a.id]:''}));setVisible(p=>({...p,[a.id]:false}));}}}>تأیید و اجرا</button><button className="btn" disabled={busy} onClick={async()=>{if(await onDecide(a.id,'cancel')){setPasswords(p=>({...p,[a.id]:''}));setDismissed(p=>({...p,[a.id]:true}));}}}>لغو</button></div><p className="subtle">{a.tool==='create_password_user'?'برای ایجاد حساب، رمز را وارد کنید و دکمهٔ تأیید و اجرا را بزنید.':'می‌توانید «تأیید اجرا» یا «لغو فرمان» را هم بگویید و ارسال کنید.'}</p></>:<details><summary>جزئیات فرمان و نتیجه</summary><ActionDetails action={a}/>{a.result&&<Details value={a.result}/>}</details>}{a.result?.error&&<p role="alert">{a.result.error}</p>}{onOpen&&<button className="link" onClick={()=>onOpen(a.section)}>نمایش بخش مربوطه</button>}</article>)}</div>}
