'use client';
import {useEffect,useRef,useState} from 'react';
import {readBomFile} from '@/lib/bom-import-file';
import {applyApprovedFiveLitre,importUnits,type ImportDraft} from '@/lib/bom-import';
export function BomImport({productId,previousVersion,onSaved,disabled}:{productId:string;previousVersion:number;onSaved:()=>void;disabled:boolean}){
 const [draft,setDraft]=useState<ImportDraft|null>(null),[source,setSource]=useState(''),[preview,setPreview]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const requestId=useRef(''),epoch=useRef(0);
 useEffect(()=>{epoch.current++;setPreview(null);setMessage('');requestId.current='';},[productId,previousVersion]);
 useEffect(()=>()=>{epoch.current++;},[]);
 const edit=(i:number,k:'unit'|'quantity',v:string)=>{setDraft(d=>d?{...d,lines:d.lines.map((l,j)=>j===i?{...l,[k]:v}:l)}:d);setPreview(null);requestId.current='';setMessage('');};
 async function choose(file?:File){if(!file)return;const generation=++epoch.current;setBusy(true);setError('');setMessage('');setPreview(null);setDraft(null);requestId.current='';try{const d=await readBomFile(file);if(generation!==epoch.current)return;setDraft(d);setSource(file.name);}catch(e){if(generation===epoch.current)setError(e instanceof Error?e.message:'فایل خوانده نشد.');}finally{setBusy(false);}}
 async function run(commit=false){if(!draft||!productId||busy)return;const generation=epoch.current;setBusy(true);setError('');setMessage('');if(commit&&!requestId.current)requestId.current=crypto.randomUUID();try{
 const r=await fetch('/api/bom-import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:commit?'commit':'preview',productId,previousVersion,source:source+' · فرمول '+draft.formulaCode,lines:draft.lines,...(commit?{confirmed:true,id:requestId.current,catalogSnapshot:preview.catalogSnapshot}:{})})});const d=await r.json() as any;if(generation!==epoch.current)return;if(!r.ok)throw Error(d.error);
 if(commit){setDraft(null);setPreview(null);onSaved();setMessage(d.unchanged?'همین BOM و مواد قبلاً ثبت شده‌اند؛ نسخه تکراری ایجاد نشد.':'مواد اولیه و نسخه BOM ثبت شدند. فرم کنترل کیفیت مواد جدید را در گردش مواد تکمیل کنید.');}else setPreview(d);
 }catch(e){if(generation===epoch.current)setError(e instanceof Error?e.message:'عملیات ناموفق بود.');}finally{setBusy(false);}}
 return <details className="panel" style={{margin:'16px 0',padding:16}}><summary><strong>ورود مواد و BOM از اکسل</strong></summary><fieldset disabled={disabled||busy} style={{border:0,padding:0}}><p>خروجی «گزارش فرمول ساخت» حسابداری (XLS از نوع XML یا XLSX). محصول مقصد را بالا انتخاب کنید. موجودی و بچ از این فایل ساخته نمی‌شود.</p><label className="field">فایل گزارش<input type="file" accept=".xls,.xlsx" onChange={e=>void choose(e.target.files?.[0])}/></label>{busy&&<p role="status">در حال بررسی…</p>}{draft&&<><p>محصول فایل: {draft.productName} · کد {draft.productCode} · فرمول {draft.formulaCode} · تعداد مبنا: {draft.baseQuantity||'نامشخص'} · {draft.lines.length} قلم</p><p className="notice">مقادیر زیر باید مصرف برای یک دستگاه باشند. نام واحد و مقدار را بررسی کنید؛ مواد مشترک با کد کالا تطبیق داده می‌شوند. نام و فرم QC کالاهای موجود تغییر نمی‌کند.</p>{draft.productCode==='30100012'&&draft.formulaCode==='2040001358'&&<button type="button" className="btn" onClick={()=>{setDraft(applyApprovedFiveLitre(draft));setPreview(null);requestId.current='';}}>اعمال واحدهای تأییدشده سوشیا ۵ لیتری و لوله ۱۰۷ گرم</button>}<div style={{maxHeight:420,overflow:'auto'}}><table className="stocktable"><thead><tr><th>کد کالا</th><th>نام</th><th>مقدار اصلی فایل</th><th>مقدار فرعی فایل</th><th>مصرف یک دستگاه</th><th>واحد</th><th>توضیح</th></tr></thead><tbody>{draft.lines.map((l,i)=><tr key={l.partCode}><td>{l.partCode}</td><td>{l.name}</td><td>{l.sourceQuantity}</td><td>{l.sourceSecondary}</td><td><input aria-label={'مصرف '+l.partCode} value={l.quantity} onChange={e=>edit(i,'quantity',e.target.value)} style={{width:100}}/></td><td><select aria-label={'واحد '+l.partCode} value={l.unit} onChange={e=>edit(i,'unit',e.target.value)}><option value="">انتخاب واحد</option>{importUnits.map(u=><option key={u}>{u}</option>)}</select></td><td>{l.note}</td></tr>)}</tbody></table></div><button type="button" className="btn" disabled={!productId} onClick={()=>void run()}>بررسی و پیش‌نمایش ثبت</button>{preview&&<div className="notice"><p>مواد جدید: {preview.newCodes.length} · مواد موجود: {draft.lines.length-preview.newCodes.length} · ردیف تغییرکرده: {preview.changed.length} · حذف از BOM جدید: {preview.removed.length}</p>{preview.removed.map((l:any)=><p key={l.partCode}>حذف از نسخه جدید: {l.partCode} · {l.name}</p>)}{preview.warnings.map((s:string)=><p key={s}>{s}</p>)}{preview.errors.map((s:string)=><p role="alert" key={s}>{s}</p>)}<p>تعریف مواد جدید بدون موجودی و بدون معیار QC است؛ پیش از دریافت بچ، فرم QC باید تکمیل شود. نسخه‌های قبلی و BOM دستگاه‌های تولیدشده حفظ می‌شوند.</p><button type="button" className="btn primary" disabled={!!preview.errors.length} onClick={()=>void run(true)}>{preview.unchanged?'تأیید بدون ایجاد نسخه تکراری':'تأیید و ثبت مواد و نسخه BOM'}</button></div>}</>}</fieldset>{error&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}</details>;
}
