'use client';
import {IconDisclosure,IconActions} from "./program-workspace";
import {IconSections} from "./program-workspace";
import {ProgramWorkspace,SubprogramNavigation} from "./program-workspace";
import {useState,useEffect} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {SolarDate} from './solar-date';
import {formatDate,formatDateTime,localDay,latinDigits} from '@/lib/persian-date';
const money=(v:any)=>v===null||v===undefined?'ناقص':Number(v).toLocaleString('fa-IR',{maximumFractionDigits:2})+' ریال';
const labels:Record<string,string>={shortage:'ارجاع کسری به تأمین',create:'تعریف پروژه ساخت',unit:'افزودن تجهیز',bom:'ویرایش BOM پروژه',approve_bom:'تأیید نسخه BOM',budget:'بودجه و برآورد باقی‌مانده',request:'درخواست قطعه از انبار',reserve:'رزرو بچ‌های انبار',issue:'تحویل قطعات به پروژه',cancel_request:'لغو درخواست و آزادسازی رزرو',consume:'ثبت مصرف واقعی',return:'برگشت سالم به انبار',scrap:'ثبت قطعه خراب / نامنطبق',time:'ثبت زمان کار',approve_time:'تأیید زمان و نرخ',expense:'ثبت هزینه و تخصیص',commitment:'ثبت تعهد خرید',close_commitment:'تعیین تکلیف تعهد',issue_note:'ثبت نقص و پیگیری',resolve_note:'تأیید رفع نقص',quality:'تأیید فنی و کیفیت تجهیز',void:'ابطال مستند',close:'نهایی‌سازی مالی پروژه',reopen:'بازگشایی پروژه'};
export function BuildProjectsPanel({demo=false,targetId=''}:{demo?:boolean;targetId?:string}){
 const [data,setData]=useState<any>(null),[selected,setSelected]=useState(targetId),[tab,setTab]=useState('overview'),[draft,setDraft]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){const r=await fetch('/api/build-projects',{cache:'no-store'}),v:any=await r.json();if(!r.ok)throw Error(v.error);setData(v);}
 useEffect(()=>{if(!demo)void load().catch(e=>setError(e.message));},[demo]);useEffect(()=>{if(targetId)setSelected(targetId)},[targetId]);
 const project=data?.projects.find((x:any)=>x.id===selected),p=project?.data,roles=data?.roles||{},report=project?.report;
 const begin=(mode:string,extra:any={})=>{setError('');setDraft({mode,id:crypto.randomUUID(),confirmed:true,revision:project?.revision||0,projectId:project?.id,notes:'',day:localDay(),...extra});};
 const btn=(mode:string,label:string,extra:any={},disabled=false)=><button className="btn" disabled={busy||disabled||p?.state==='closed'&&mode!=='reopen'&&mode!=='create'} onClick={()=>begin(mode,extra)}>{label}</button>;
 const field=(k:string,value:any)=>setDraft((x:any)=>({...x,[k]:value}));
 const input=(k:string,label:string,numeric=false,required=true)=><label className="field">{label}<input required={required} value={draft[k]??''} inputMode={numeric?'decimal':undefined} onChange={e=>field(k,numeric?latinDigits(e.target.value):e.target.value)}/></label>;
 const pick=(k:string,label:string,items:any[],required=true)=><label className="field">{label}<select required={required} value={draft[k]||''} onChange={e=>field(k,e.target.value)}><option value="">انتخاب کنید</option>{items.map((x:any)=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label>;
 const unitTitle=(id:string)=>p?.units.find((x:any)=>x.id===id)?.title||id;
 const table=(heads:string[],rows:any[][])=><div style={{overflowX:'auto'}}><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,n)=><tr key={n}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="empty">هنوز موردی ثبت نشده است.</p>}</div>;
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const body={...draft};if(body.mode==='time')body.minutes=Number(body.minutes);if(body.lineIndex!==undefined&&body.lineIndex!=='')body.lineIndex=Number(body.lineIndex);const r=await fetch('/api/build-projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),out:any=await r.json();if(!r.ok)throw Error(out.error);await load();setSelected(out.id);setDraft(null);setMessage('ثبت شد؛ موجودی و گزارش پروژه به‌روز شدند.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 if(demo)return <p className="notice">برای پروژه واقعی و موجودی انبار وارد اطلاعات شرکت شوید.</p>;
 if(!data)return <div className="panel"><p>{error||'در حال خواندن پروژه‌های ساخت…'}</p><button className="btn" onClick={()=>void load().catch(e=>setError(e.message))}>تلاش دوباره</button></div>;
 const units=p?.units.map((u:any)=>[u.id,u.title])||[],person=(id:string)=>data.members.find((m:any)=>m.id===id)?.name||id;
 const stocks=p?.requests.filter((r:any)=>r.state==='issued').flatMap((r:any)=>r.lots.map((l:any)=>({...l,unitId:r.unitId,partCode:r.partCode,unit:r.unit,remaining:l.quantity-p.movements.filter((m:any)=>m.lotId===l.id).reduce((n:number,m:any)=>n+m.quantity,0)})))||[];
 return <ProgramWorkspace programId="build-projects" direct={!!targetId} title="پروژه ساخت"><section className="panel" dir="rtl"><div className="panelhead"><div><h2>پروژه‌های ساخت بیمارستانی</h2><p>قطعات پایه و سفارشی · موجودی نزد پروژه · هزینه واقعی ساخت و اجرا</p></div><IconActions scope="build-projects-panel-actions-5d7056349e">{roles.engineering&&btn('create','پروژه جدید',{projectId:undefined,revision:0})}<button className="btn" onClick={()=>void load().catch(e=>setError(e.message))}>تازه‌سازی</button></IconActions></div>
 {error&&!draft&&<p role="alert" className="notice error">{error}</p>}{message&&<p role="status">{message}</p>}
 <label className="field">پروژه<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">انتخاب کنید</option>{data.projects.map((r:any)=><option key={r.id} value={r.id}>{r.data.title} · {r.data.customer} · {r.data.state==='closed'?'بسته':'باز'}</option>)}</select></label>
 {!project&&<p className="empty">پروژه را بسازید؛ سپس تجهیزات و BOM پایه یا اختصاصی آن را تعریف کنید.</p>}
 {project&&<><h3>{p.title} · {p.customer}</h3>{p.unassignedWork?.length>0&&<p className="notice">کار بدون مسئول مجاز: {p.unassignedWork.join(' / ')}. مدیر دسترسی نقش مربوط را تکمیل کند.</p>}<p>قرارداد: {p.contract} · مسئول: {person(p.ownerId)} · موعد: {formatDate(p.due)} · کد پروژه: {project.id}</p><SubprogramNavigation items={(Object.entries({overview:'گزارش پروژه',bom:'تجهیزات و BOM',materials:'درخواست و مصرف قطعات',time:'زمان کار',...(roles.financial?{finance:'هزینه و تعهدات'}:{}),close:'نواقص و پایان پروژه'})).map(([key,title])=>[String(key),String(title)] as [string,string])} value={tab} onChange={setTab}/>
 {tab==='overview'&&<>{roles.financial&&<><div className="form-grid">{[['بودجه اولیه',report.initialBudget],['بودجه اصلاح‌شده',report.budget],['هزینه واقعی تأییدشده',report.actual],['هزینه‌های معلوم تا این لحظه',report.knownActual],['خدمات خریداری‌شده متصل به پروژه',report.serviceTotal],['تعهدات خرید باز',report.openCommitments],['برآورد باقیمانده',report.remaining],['پیش‌بینی هزینه نهایی',report.forecast],['اختلاف واقعی با بودجه',report.variance]].map(([label,v])=><article className="flow-card" key={label}><p>{label}</p><strong>{money(v)}</strong></article>)}</div><p className="subtle">خدمات خریداری‌شده متصل در جمع هزینه کل پروژه محاسبه می‌شوند و در ردیف هزینه هر تجهیز تکرار نمی‌شوند.</p><p className="notice">تعهدات باز با برآورد باقیمانده هم‌پوشانی دارند و خودکار با هم جمع نمی‌شوند. تا رفع نواقص، بهای پروژه موقت است.</p>{table(['تجهیز','مواد','دستمزد','بهای ساخت','هزینه کل اجرا'],report.units.map((u:any)=>[u.title,money(u.material),money(u.labor),money(u.manufacturing),money(u.execution)]))}{roles.finance&&btn('budget','ثبت بودجه / برآورد جدید',{amount:report.budget||'',remaining:report.remaining||'0',contractAmount:p.contractAmount||'0'})}</>}
 {!roles.financial&&<p>مقادیر، مصرف و مراحل پروژه در تب‌های مربوط دیده می‌شود؛ مبالغ فقط برای مالی و مدیریت قابل مشاهده‌اند.</p>}<IconDisclosure scope="build-projects-panel-details-bf9035f28e" title={<> راهنما و مسئولیت مراحل </>}><ul>{data.help.map((s:string)=><li key={s}>{s}</li>)}</ul></IconDisclosure></>}
 {tab==='bom'&&<>{roles.engineering&&btn('unit','افزودن تجهیز / دستگاه')}{p.units.map((u:any)=><article className="flow-card" key={u.id}><h3>{u.title}</h3><p>نسخه {u.versions.length} · {u.approved?'BOM تأییدشده':'در انتظار تأیید مدیریت'} · {u.quality?'کیفیت تأییدشده':'کیفیت تکمیل نشده'}</p>{table(['کد','نام قطعه','مقدار','واحد',''],u.lines.map((l:any)=>[l.partCode,l.name,l.quantity/1000,l.unit,(roles.production||roles.engineering)&&btn('request','درخواست از انبار',{unitId:u.id,lineId:l.id,quantity:String(l.quantity/1000)},!u.approved)]))}<div className="tools">{roles.engineering&&btn('bom','اصلاح اختصاصی BOM',{unitId:u.id,lines:u.lines.map((l:any)=>({...l,quantity:String(l.quantity/1000)}))})}{roles.manager&&btn('approve_bom','تأیید نسخه',{unitId:u.id})}{roles.quality&&btn('quality','تأیید فنی و کیفیت',{unitId:u.id})}</div><IconDisclosure scope="build-projects-panel-details-f4bb0b3113" title={<> نسخه‌های قبلی و مبنای اولیه </>}>{u.versions.map((v:any)=><div key={v.number}><p>نسخه {v.number} · {formatDateTime(v.at)} · {v.notes}</p>{v.lines.map((l:any)=><span key={l.id} style={{display:'block'}}>{l.name} · {l.quantity/1000} {l.unit}</span>)}</div>)}</IconDisclosure></article>)}</>}
 {tab==='materials'&&<><IconSections scope="build-projects-panel-sections-1" items={[{key:"section-0",title:"درخواست‌های انبار",content:<><h3>درخواست‌های انبار</h3>{table(['تجهیز','قطعه','مقدار','وضعیت',''],p.requests.map((r:any)=>[unitTitle(r.unitId),r.partCode,r.quantity/1000+' '+r.unit,({pending:'در انتظار انبار',reserved:'رزروشده',issued:'تحویل پروژه',cancelled:'لغوشده'} as any)[r.state],roles.warehouse&&<>{r.state==='pending'&&<>{btn('reserve','انتخاب بچ و رزرو',{itemId:r.id,allocations:[]})}{btn('shortage','ارجاع کسری به تأمین',{itemId:r.id})}</>}{r.state==='reserved'&&btn('issue','تحویل به پروژه',{itemId:r.id})}{['pending','reserved'].includes(r.state)&&btn('cancel_request','لغو و آزادسازی',{itemId:r.id})}</>]))}
 </>},{key:"section-1",title:"قطعات نزد پروژه",content:<><h3>قطعات نزد پروژه</h3>{table(['تجهیز','قطعه / بچ','تحویل‌شده','باقی‌مانده',''],stocks.map((l:any)=>[unitTitle(l.unitId),l.partCode+' / '+l.batchId,l.quantity/1000,l.remaining/1000+' '+l.unit,<>{(roles.production||roles.engineering)&&<>{btn('consume','مصرف',{lotId:l.id,quantity:String(l.remaining/1000)},!l.remaining)}{btn('scrap','خرابی',{lotId:l.id,quantity:''},!l.remaining)}</>}{roles.warehouse&&btn('return','برگشت سالم',{lotId:l.id,quantity:String(l.remaining/1000),location:l.location},!l.remaining)}</>]))}
 </>},{key:"section-2",title:"گردش مصرف و برگشت",content:<><h3>گردش مصرف و برگشت</h3>{table(['زمان','تجهیز','بچ','نوع','مقدار'],p.movements.map((m:any)=>[formatDateTime(m.at),unitTitle(m.unitId),m.batchId,labels[m.kind],m.quantity/1000]))}</>}]}/></>}
 {tab==='time'&&<>{(roles.production||roles.engineering||roles.finance)&&btn('time','ثبت کار انجام‌شده')}{table(['تجهیز','فرد','تاریخ','دقیقه','وضعیت',''],p.times.filter((t:any)=>!t.voided).map((t:any)=>[unitTitle(t.unitId),person(t.memberId),formatDate(t.day),t.minutes,t.approved?'تأیید مالی':'نیازمند نرخ و تأیید',roles.finance&&<>{btn('approve_time','نرخ / تأیید',{itemId:t.id,rate:t.rate||''})}{btn('void','ابطال',{kind:'times',itemId:t.id})}</>]))}</>}
 {tab==='finance'&&roles.financial&&<><div className="tools">{roles.finance&&<>{btn('expense','هزینه مستقیم یا مشترک',{shares:p.units.map((u:any)=>({unitId:u.id,amount:'0'})),bucket:'manufacturing',allocationMethod:'manual'})}{btn('commitment','تعهد خرید باز')}</>}</div><IconSections scope="build-projects-panel-sections-2" items={[{key:"section-0",title:"هزینه‌ها",content:<><h3>هزینه‌ها</h3>{table(['عنوان','مرجع','نوع','مبلغ',''],p.expenses.filter((e:any)=>!e.voided).map((e:any)=>[e.title,e.reference,({manufacturing:'ساخت / سربار',execution:'حمل / نصب / اجرا',loss:'زیان / مخارج خارج از ساخت'} as any)[e.bucket],money(e.amount),roles.finance&&btn('void','ابطال',{kind:'expenses',itemId:e.id})]))}</>},{key:"section-1",title:"تعهدات خرید",content:<><h3>تعهدات خرید</h3>{table(['موضوع','سفارش','مبلغ باز','وضعیت',''],p.commitments.map((c:any)=>[c.title,c.orderId||'مدرک در توضیحات',money(c.amount),c.closed?'تعیین تکلیف‌شده':'باز',roles.finance&&!c.closed&&btn('close_commitment','تعیین تکلیف',{itemId:c.id})]))}<IconDisclosure scope="build-projects-panel-details-b63e0b2f46" title={<> سابقه بودجه </>}>{p.budgets.map((b:any,n:number)=><p key={n}>{formatDateTime(b.at)} · {money(b.amount)} · {b.notes}</p>)}</IconDisclosure></>}]}/></>}
 {tab==='close'&&<>{(roles.engineering||roles.finance||roles.production)&&btn('issue_note','ثبت نقص و ارجاع')}{table(['موضوع','مسئول','موعد','وضعیت',''],p.issues.map((i:any)=>[i.title,person(i.ownerId),formatDate(i.due),i.resolved?'رفع‌شده':'باز',roles.finance&&!i.resolved&&btn('resolve_note','تأیید رفع نقص',{itemId:i.id})]))}{report&&<><h3>{report.complete?'آماده نهایی‌سازی':'بهای موقت؛ موارد باز'}</h3><ul>{report.problems.map((s:string)=><li key={s}>{s}</li>)}</ul>{roles.finance&&(p.state==='closed'?btn('reopen','بازگشایی مستند'):btn('close','تأیید و بستن مالی',{token:project.token},!report.complete))}{project.closes.map((c:any)=><article className="flow-card" key={c.id}><h4>گزارش نهایی {formatDateTime(c.at)}</h4><p>{c.stale?'منابع تغییر کرده‌اند؛ نیازمند بازبینی':'منطبق با منابع فعلی'}</p><p>هزینه اجرا: {money(c.report.actual)} · بهای ساخت: {money(c.report.manufacturing)}</p>{table(['تجهیز','بهای ساخت','هزینه اجرا'],c.report.units.map((u:any)=>[u.title,money(u.manufacturing),money(u.execution)]))}</article>)}</>}<IconDisclosure scope="build-projects-panel-details-8878ca8e03" title={<> سابقه عملیات پروژه </>}>{p.history.map((h:any,n:number)=><p key={n}>{formatDateTime(h.at)} · {labels[h.mode]} · {h.name} · {h.notes}</p>)}</IconDisclosure></>}
 </>}
 <Dialog open={!!draft} onOpenChange={o=>!o&&!busy&&setDraft(null)}><DialogContent style={{maxWidth:1000,maxHeight:'92vh',overflow:'auto'}}><DialogTitle>{labels[draft?.mode]}</DialogTitle><DialogDescription>اطلاعات واقعی و دلیل اقدام را بررسی کنید؛ ثبت همراه با سابقه انجام می‌شود.</DialogDescription>{draft&&<form onSubmit={save}><div className="form-grid">
 {draft.mode==='create'&&<>{input('title','عنوان پروژه')}{input('customer','بیمارستان / مشتری')}{input('contract','شماره قرارداد / مرجع سفارش')}{pick('ownerId','مسئول پروژه',data.members.map((m:any)=>[m.id,m.name]))}<SolarDate label="موعد تحویل" value={draft.due||''} onChange={v=>field('due',v)}/></>}
 {draft.mode==='unit'&&<>{input('title','عنوان دستگاه / تجهیز')}{pick('bomId','BOM پایه (اختیاری)',data.boms.map((b:any)=>[b.id,(data.products.find((p:any)=>p.id===b.product_id)?.name||b.product_id)+' · نسخه '+b.version]),false)}</>}
 {draft.mode==='bom'&&<div style={{gridColumn:'1 / -1'}}><p>زیرمجموعه کامل و قطعات داخل آن را هم‌زمان وارد نکنید. اصلاح فقط روی این پروژه اثر دارد.</p>{draft.lines.map((l:any,n:number)=><div className="form-grid" key={n}><label className="field">قطعه<select required value={l.materialId} onChange={e=>field('lines',draft.lines.map((x:any,j:number)=>j===n?{...x,materialId:e.target.value}:x))}><option value="">انتخاب کنید</option>{data.materials.map((m:any)=><option key={m.id} value={m.id}>{m.code} · {m.name} · {m.unit}</option>)}</select></label><label className="field">مقدار<input required value={l.quantity} onChange={e=>field('lines',draft.lines.map((x:any,j:number)=>j===n?{...x,quantity:latinDigits(e.target.value)}:x))}/></label><button type="button" className="btn" onClick={()=>field('lines',draft.lines.filter((_:any,j:number)=>j!==n))}>حذف ردیف</button></div>)}<button type="button" className="btn" onClick={()=>field('lines',[...draft.lines,{materialId:'',quantity:''}])}>افزودن قطعه اختصاصی</button></div>}
 {draft.mode==='budget'&&<>{input('amount','بودجه اصلاح‌شده کل پروژه (ریال)',true)}{input('contractAmount','مبلغ قرارداد (ریال)',true)}{input('remaining','برآورد کل هزینه باقیمانده، شامل خریدهای باز (ریال)',true)}</>}
 {['request','consume','return','scrap'].includes(draft.mode)&&input('quantity','مقدار در واحد اصلی قطعه',true)}{draft.mode==='return'&&input('location','محل برگشت: راهرو-قفسه-طبقه-خانه')}
 {draft.mode==='reserve'&&<div style={{gridColumn:'1 / -1'}}><p>جمع رزرو باید با مقدار درخواست برابر باشد؛ فقط بچ‌های تأییدشده و غیرمنقضی قابل تحویل‌اند.</p>{draft.allocations.map((a:any,n:number)=><div className="form-grid" key={n}><label className="field">محل و بچ<select required value={a.location} onChange={e=>{const slot=data.slots.find((s:any)=>s.location===e.target.value);field('allocations',draft.allocations.map((x:any,j:number)=>j===n?{...x,location:slot.location,batchId:slot.batch_id}:x))}}><option value="">انتخاب کنید</option>{data.slots.filter((s:any)=>s.quantity>0&&data.batches.some((b:any)=>b.id===s.batch_id&&b.partCode===p.requests.find((r:any)=>r.id===draft.itemId)?.partCode)).map((s:any)=><option key={s.location} value={s.location}>{s.location} · {s.batch_id} · موجودی {s.quantity/1000}</option>)}</select></label><label className="field">مقدار<input required value={a.quantity} onChange={e=>field('allocations',draft.allocations.map((x:any,j:number)=>j===n?{...x,quantity:latinDigits(e.target.value)}:x))}/></label><button className="btn" type="button" onClick={()=>field('allocations',draft.allocations.filter((_:any,j:number)=>j!==n))}>حذف</button></div>)}<button type="button" className="btn" onClick={()=>field('allocations',[...draft.allocations,{location:'',batchId:'',quantity:''}])}>انتخاب محل برداشت</button></div>}
 {draft.mode==='time'&&<>{pick('unitId','تجهیز',units)}{pick('memberId','فرد انجام‌دهنده',data.members.map((m:any)=>[m.id,m.name]))}<SolarDate label="روز کار" value={draft.day} onChange={v=>field('day',v)}/>{input('minutes','زمان واقعی (دقیقه)',true)}</>}
 {draft.mode==='approve_time'&&input('rate','نرخ هر ساعت کار (ریال)',true)}
 {draft.mode==='expense'&&<>{input('title','عنوان هزینه')}{input('reference','مرجع یکتای مدرک یا سهم پروژه')}{input('amount','مبلغ هزینه (ریال)',true)}{pick('bucket','نحوه احتساب',[['manufacturing','بهای ساخت / سربار'],['execution','حمل، نصب و اجرای قرارداد'],['loss','زیان / هزینه خارج از ساخت']])}{pick('allocationMethod','روش تقسیم هزینه',[['manual','مبلغ دستی / مستقیم'],['time','بر اساس دقیقه کار تأییدشده']])}{input('basis','مبنای تخصیص و تأیید مالی')}{pick('sourceId','مدرک ثبت و تشخیص هزینه (اختیاری)',data.expenses.map((e:any)=>[e.id,e.data.reference]),false)}{draft.sourceId&&input('lineIndex','شماره ردیف منبع از صفر',true)}<div style={{gridColumn:'1 / -1'}}><p>هزینه مستقیم: فقط سهم تجهیز مربوط را وارد کنید. هزینه مشترک: سهم هر تجهیز را طبق مبنا وارد کنید؛ جمع باید برابر مبلغ باشد.</p>{draft.allocationMethod!=='time'&&draft.shares.map((s:any,n:number)=><label className="field" key={s.unitId}>{unitTitle(s.unitId)}<input required value={s.amount} onChange={e=>field('shares',draft.shares.map((x:any,j:number)=>j===n?{...x,amount:latinDigits(e.target.value)}:x))}/></label>)}</div></>}
 {draft.mode==='commitment'&&<>{input('title','موضوع خرید / تعهد')}{input('amount','مبلغ تعهد باز (ریال)',true)}{pick('orderId','سفارش خرید مرتبط (اختیاری)',data.purchaseOrders.map((o:any)=>[o.id,o.title]),false)}</>}
 {draft.mode==='issue_note'&&<>{input('title','مدرک یا موضوع ناقص')}{pick('ownerId','مسئول پیگیری',data.members.map((m:any)=>[m.id,m.name]))}<SolarDate label="موعد" value={draft.due||''} onChange={v=>field('due',v)}/></>}
 {draft.mode==='quality'&&input('reference','مرجع آزمون و تحویل فنی تجهیز')}
 {draft.mode==='close'&&<><p className="notice">گزارش تأییدشده ذخیره و پروژه قفل می‌شود. این اقدام سند حسابداری یا شناسایی درآمد ایجاد نمی‌کند.</p><label className="field"><span><input required type="checkbox" checked={draft.completeCostsConfirmed===true} onChange={e=>field('completeCostsConfirmed',e.target.checked)}/> تأیید می‌کنم همه صورتحساب‌ها، ساعات کار، سربار و تعهدات پروژه تعیین تکلیف شده‌اند.</span></label></>}
 {input('notes','توضیح، دلیل تغییر یا مدرک تأیید')}
 </div>{error&&<p role="alert" className="notice error">{error}</p>}<button className="btn primary" type="submit" disabled={busy}>{busy?'در حال ثبت…':'تأیید و ثبت'}</button></form>}</DialogContent></Dialog>
 </section></ProgramWorkspace>;
}
