'use client';
import {IconSections} from "./program-workspace";
import {ProgramWorkspace,SubprogramNavigation} from "./program-workspace";
import {PurchasePayablesPanel} from './purchase-payables-panel';
import {ExpenseRegisterPanel} from './expense-register-panel';
import {PurchaseSettlementPanel} from './purchase-settlement-panel';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {SolarDate} from './solar-date';
import {formatDate,formatDateTime,localDay,latinDigits} from '@/lib/persian-date';
const money=(v:any)=>v===null||v===undefined?'ناقص':Number(v).toLocaleString('fa-IR',{maximumFractionDigits:0})+' ریال';
const labels:Record<string,string>={price:'قیمت مستند بچ',material:'نرخ استاندارد قطعه',standard:'زمان و نرخ استاندارد',time:'زمان واقعی دستگاه',period:'هزینه‌های دوره',close:'تأیید و ذخیره گزارش نهایی'};
export function CostingPanel({demo=false}:{demo?:boolean}){
 const [data,setData]=useState<any>(null),[tab,setTab]=useState('devices'),[draft,setDraft]=useState<any>(null),[detail,setDetail]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){const r=await fetch('/api/costing',{cache:'no-store'}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setData(d);}
 useEffect(()=>{if(!demo)void load().catch(e=>setError(e.message));},[demo]);
 if(demo)return <div className="panel"><p className="empty">برای محاسبه بهای واقعی، وارد اطلاعات شرکت شوید. در نمایش نمونه هزینه مالی ساخته نمی‌شود.</p></div>;
 const begin=(mode:string,extra:any={})=>{setError('');setDraft({mode,id:crypto.randomUUID(),confirmed:true,revision:0,notes:'',...extra});};
 const edit=(mode:string,row:any,extra:any={})=>begin(mode,{...(row?.data||{}),...extra,revision:row?.revision||0});
 const field=(k:string,v:any)=>setDraft((d:any)=>({...d,[k]:v}));
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const body={...draft};delete body.history;const r=await fetch('/api/costing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setDraft(null);setMessage('ثبت شد؛ محاسبات به‌روز شدند.');await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 if(!data)return <div className="panel"><p role="status">{error||'در حال محاسبه بهای تمام‌شده…'}</p><button className="btn" onClick={()=>void load().catch(e=>setError(e.message))}>تلاش دوباره</button></div>;
 const product=(id:string)=>data.products.find((p:any)=>p.id===id)?.name||id;
 const bomName=(b:any)=>product(b.product_id)+' — نسخه '+b.version;
 const input=(key:string,label:string,numeric=false)=> <label className="field">{label}<input required value={draft[key]??''} inputMode={numeric?'decimal':undefined} onChange={e=>field(key,numeric?latinDigits(e.target.value):e.target.value)}/></label>;
 const intInput=(key:string,label:string)=> <label className="field">{label}<input required type="number" min="1" step="1" value={draft[key]??''} onChange={e=>field(key,Number(e.target.value))}/></label>;
 const table=(heads:string[],rows:any[][])=><div style={{overflowX:'auto'}}><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="empty">هنوز رکوردی ثبت نشده است.</p>}</div>;
 return <ProgramWorkspace programId="costing-panel" title="هزینه و مالی"><div className="panel"><div className="panelhead"><div><h2>بهای تمام‌شده</h2><p>مواد، دستمزد و سربار تولید · همه مبالغ ریال</p></div><button className="btn" disabled={busy} onClick={()=>void load().catch(e=>setError(e.message))}>تازه‌سازی</button></div>
 <SubprogramNavigation items={(Object.entries({payables:'بدهی و پرداخت خرید',expenses:'ثبت و تشخیص هزینه',settlements:'تسویه خرید',devices:'هزینه دستگاه‌ها',prices:'قیمت خرید و موجودی',standards:'استاندارد تولید',periods:'دوره مالی',guide:'راهنما'})).map(([key,title])=>[String(key),String(title)] as [string,string])} value={tab} onChange={setTab}/>
 <p className="notice">بهای واقعی تا تکمیل قیمت‌ها و تأیید مالی موقت است. انتقال خودکار اطلاعات از سپیدار هنوز برقرار نشده است.</p>{error&&!draft&&<p className="notice error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 {tab==='payables'&&<PurchasePayablesPanel/>}
 {tab==='expenses'&&<ExpenseRegisterPanel/>}
 {tab==='settlements'&&<PurchaseSettlementPanel/>}
 {tab==='guide'&&<ul>{data.help.map((s:string)=><li key={s} style={{marginBottom:12}}>{s}</li>)}</ul>}
 {tab==='devices'&&<>{table(['سریال','محصول','وضعیت','مواد واقعی تجمعی','مواد استاندارد','اختلاف مواد','بررسی'],data.devices.map((d:any)=>[d.serial,product(d.productId),d.state==='finished'?'تحویل انبار نهایی':'در جریان ساخت',money(d.material),money(d.standard?.complete?d.standard.materials:null),money(d.materialVariance),<button className="btn" onClick={()=>setDetail(d)}>مصرف و زمان</button>]))}<p className="footnote">فقط دستگاه دارای خروج واقعی مواد نمایش داده می‌شود. رزرو و آماده‌سازی برگ تولید هزینه مصرف ایجاد نمی‌کند.</p></>}
 {tab==='prices'&&<><IconSections scope="costing-panel-sections-1" items={[{key:"section-0",title:"قیمت تمام‌شده هر واحد بچ",content:<><h3>قیمت تمام‌شده هر واحد بچ</h3>{table(['بچ','کد قطعه','واحد اصلی','قیمت واحد','مدرک',''],data.batches.map((b:any)=>[b.code||b.id,b.partCode,b.unit,money(b.price?.data.unitCost),b.price?.data.reference||'ثبت نشده',data.write&&!b.price?.data.settlementId&&<button className="btn" onClick={()=>edit('price',b.price,{batchId:b.id,unit:b.unit})}>ثبت / اصلاح قیمت</button>]))}</>},{key:"section-1",title:"موجودی قابل مصرف و میانگین متحرک",content:<><h3>موجودی قابل مصرف و میانگین متحرک</h3>{table(['کد قطعه','مقدار','واحد','میانگین واحد','ارزش موجودی'],data.pools.map((p:any)=>[p.partCode,p.quantity,p.unit,money(p.unitCost),money(p.value)]))}{data.warnings.length>0&&<details><summary>موارد ناقص ({data.warnings.length})</summary><ul>{data.warnings.map((w:string)=><li key={w}>{w}</li>)}</ul></details>}</>}]}/></>}
 {tab==='standards'&&<><IconSections scope="costing-panel-sections-2" items={[{key:"section-0",title:"نرخ استاندارد مواد",content:<><h3>نرخ استاندارد مواد</h3>{table(['قطعه','واحد','نرخ / زیرمجموعه',''],data.materials.map((m:any)=>[m.name+' — '+m.code,m.unit,m.rate?.data.childBomId?bomName(data.boms.find((b:any)=>b.id===m.rate.data.childBomId)||{}):money(m.rate?.data.unitCost),data.write&&<button className="btn" onClick={()=>edit('material',m.rate,{partCode:m.code,unit:m.unit})}>تنظیم استاندارد</button>]))}</>},{key:"section-1",title:"بهای استاندارد نسخه BOM",content:<><h3>بهای استاندارد نسخه BOM</h3>{table(['محصول / نسخه','مواد','دستمزد','سربار','جمع',''],data.standards.map((s:any)=>[product(s.productId)+' / '+s.version,money(s.complete?s.materials:null),money(s.labor),money(s.overhead),money(s.total),<div><button className="btn" onClick={()=>setDetail({standardOnly:s})}>جزئیات</button>{data.write&&<button className="btn" onClick={()=>edit('standard',data.settings.find((e:any)=>e.type==='cost_standard'&&e.data.bomId===s.bomId),{bomId:s.bomId})}>زمان و نرخ</button>}</div>]))}</>}]}/></>}
 {tab==='periods'&&<>{data.write&&<button className="btn primary" onClick={()=>begin('period',{start:'',end:'',laborTotal:'',fixedOverhead:'',variableOverhead:'',nonproduction:'',methodConfirmed:false})}>تعریف دوره مالی</button>}{data.periods.map((p:any)=><article className="flow-card" key={p.id}><h3>{p.data.title}</h3><p>{formatDate(p.data.start)} تا {formatDate(p.data.end)} · زمان واقعی: {p.preview.minutes.toLocaleString('fa-IR')} دقیقه</p><p>سربار ثابت جذب‌نشده: {money(p.preview.unabsorbedFixed)} · هزینه غیرتولیدی: {money(p.preview.nonproduction)}</p>{p.preview.blockers.length>0&&<ul>{p.preview.blockers.map((b:string)=><li key={b}>{b}</li>)}</ul>}{table(['سریال','مواد دوره','دستمزد','سربار','جمع دوره'],p.preview.devices.map((d:any)=>[d.serial,money(d.material),money(d.labor),money(d.overhead),money(d.total)]))}<div className="tools">{data.write&&<><button className="btn" onClick={()=>edit('period',p)}>اصلاح هزینه‌های دوره</button><button className="btn primary" disabled={!p.preview.complete} onClick={()=>begin('close',{periodId:p.id,token:data.token,title:p.data.title})}>بررسی و نهایی‌سازی</button></>}</div>{p.preview.unassigned.length>0&&<details><summary>خروج‌های خارج از هزینه مستقیم دستگاه ({p.preview.unassigned.length})</summary>{table(['نوع','قطعه','مقدار','مبلغ'],p.preview.unassigned.map((l:any)=>[l.kind,l.partCode,l.quantity,money(l.cost)]))}</details>}</article>)}<h3>گزارش‌های نهایی ذخیره‌شده</h3>{data.closes.map((c:any)=><article className="flow-card" key={c.id}><h4>{c.data.period.title}</h4><p>{formatDateTime(c.data.closedAt)} · {c.data.closedBy} · {c.stale?'منابع تغییر کرده‌اند؛ نیازمند بازبینی':'منطبق با منابع فعلی'}</p><button className="btn" onClick={()=>setDetail({closed:c})}>گزارش ثابت</button></article>)}</>}
 <Dialog open={!!detail} onOpenChange={o=>!o&&setDetail(null)}><DialogContent style={{maxWidth:1000,maxHeight:'90vh',overflow:'auto'}}><DialogTitle>{detail?.serial||'جزئیات بهای تمام‌شده'}</DialogTitle><DialogDescription>مبالغ ریال؛ داده ناقص به معنی هزینه صفر نیست.</DialogDescription>{detail?.id&&<>{table(['زمان ثبت','قطعه','مقدار','میانگین واحد','هزینه'],detail.lines.map((l:any)=>[formatDateTime(l.at),l.partCode,l.quantity,money(l.unitCost),money(l.cost)]))}{data.write&&<button className="btn" onClick={()=>{edit('time',data.settings.find((e:any)=>e.type==='cost_time'&&e.data.deviceId===detail.id&&e.data.day===localDay()),{deviceId:detail.id,day:localDay()});setDetail(null);}}>ثبت زمان واقعی</button>}{data.settings.filter((e:any)=>e.type==='cost_time'&&e.data.deviceId===detail.id).map((e:any)=><p key={e.id}>{formatDate(e.data.day)}: {e.data.minutes} دقیقه {data.write&&<button className="btn" onClick={()=>{edit('time',e);setDetail(null);}}>اصلاح</button>}</p>)}</>}{detail?.standardOnly&&<>{table(['قطعه','مقدار','نرخ','هزینه'],detail.standardOnly.lines.map((l:any)=>[l.name,l.quantity,money(l.unitCost),money(l.cost)]))}<ul>{detail.standardOnly.missing.map((s:string,i:number)=><li key={i}>{s}</li>)}</ul></>}{detail?.closed&&<>{table(['سریال','وضعیت هنگام گزارش','مواد','دستمزد','سربار','جمع'],detail.closed.data.report.devices.map((d:any)=>[d.serial,d.state==='finished'?'نهایی':'در جریان ساخت',money(d.material),money(d.labor),money(d.overhead),money(d.total)]))}<p>{detail.closed.data.report.note}</p></>}</DialogContent></Dialog>
 <Dialog open={!!draft} onOpenChange={o=>!o&&!busy&&setDraft(null)}><DialogContent style={{maxWidth:760,maxHeight:'90vh',overflow:'auto'}}><DialogTitle>{labels[draft?.mode]}</DialogTitle><DialogDescription>ثبت با دسترسی مالی و نگهداری سابقه تغییر انجام می‌شود.</DialogDescription>{draft&&<form onSubmit={save} className="form-grid">
 {draft.mode==='price'&&<><p>واحد اصلی: {draft.unit}</p>{input('unitCost','بهای تمام‌شده واحد، شامل هزینه مستقیم خرید (ریال)',true)}{input('reference','شماره سند خرید / مدرک قیمت')}</>}
 {draft.mode==='material'&&<><label className="field">BOM مجموعه ساخت داخل (اختیاری)<select value={draft.childBomId||''} onChange={e=>field('childBomId',e.target.value)}><option value="">قطعه با نرخ مستقیم</option>{data.boms.map((b:any)=><option key={b.id} value={b.id}>{bomName(b)}</option>)}</select></label>{!draft.childBomId&&input('unitCost','نرخ استاندارد هر '+draft.unit+' (ریال)',true)}</>}
 {draft.mode==='standard'&&<>{intInput('minutes','زمان استاندارد هر دستگاه (دقیقه)')}{input('laborHourly','نرخ ساعتی دستمزد (ریال)',true)}{input('overheadHourly','نرخ ساعتی سربار (ریال)',true)}</>}
 {draft.mode==='time'&&<><SolarDate label="روز انجام کار" value={draft.day} onChange={v=>{const old=data.settings.find((e:any)=>e.type==='cost_time'&&e.data.deviceId===draft.deviceId&&e.data.day===v);setDraft((d:any)=>({...d,...(old?.data||{}),day:v,revision:old?.revision||0}));}}/>{intInput('minutes','مجموع زمان واقعی این دستگاه در روز (دقیقه)')}<p>مجموع روز ثبت می‌شود؛ ثبت مجدد همان روز، مقدار قبلی را با حفظ سابقه اصلاح می‌کند.</p></>}
 {draft.mode==='period'&&<>{input('title','عنوان دوره')}<SolarDate label="شروع دوره" value={draft.start} disabled={draft.revision>0} onChange={v=>field('start',v)}/><SolarDate label="پایان دوره" value={draft.end} onChange={v=>field('end',v)}/>{input('laborTotal','کل دستمزد مستقیم دوره (ریال)',true)}{input('fixedOverhead','کل سربار ثابت تولید (ریال)',true)}{input('variableOverhead','کل سربار متغیر تولید (ریال)',true)}{intInput('normalMinutes','ظرفیت عادی دوره، دقیقه کار مستقیم')}{input('nonproduction','هزینه اداری و فروش، جدا از تولید (ریال)',true)}<label><input type="checkbox" checked={draft.methodConfirmed||false} onChange={e=>field('methodConfirmed',e.target.checked)}/> روش میانگین موزون متحرک و مبنای تخصیص با حسابداری تطبیق و تأیید شده است.</label></>}
 {draft.mode==='close'&&<p>گزارش «{draft.title}» با منابع پیش‌نمایش ذخیره می‌شود. هزینه‌ها و کامل‌بودن زمان‌های واقعی را پیش از تأیید بررسی کنید. این اقدام سند سپیدار صادر نمی‌کند.</p>}
 <label className="field">توضیح و مستند تصمیم<textarea required value={draft.notes||''} onChange={e=>field('notes',e.target.value)}/></label>{error&&<p role="alert" className="notice error">{error}</p>}<button className="btn primary" disabled={busy}>{busy?'در حال ثبت…':'تأیید و ثبت'}</button></form>}</DialogContent></Dialog>
 </div></ProgramWorkspace>;
}
