'use client';
import {useEffect,useRef,useState} from 'react';
import {Lightbulb,Plus,Copy,RefreshCw,MessageSquare,Bot,ArrowRight,ArrowLeft} from 'lucide-react';
import {developmentFields,developmentKinds,developmentStates,developmentSources,developmentCopy,type DevelopmentRequest} from '@/lib/development-contract';
import {formatDateTime} from '@/lib/persian-date';
const blank=()=>({kind:'feature',title:'',section:'',problem:'',desired:'',impact:'',example:''});
const nf=(n:number)=>n.toLocaleString('fa-IR');
export function DevelopmentPanel({accountId,demo,onReal}:{accountId:string;demo:boolean;onReal:()=>void}){
 const [data,setData]=useState<any>(null),[selected,setSelected]=useState<DevelopmentRequest|null>(null),[draft,setDraft]=useState(blank),[form,setForm]=useState(false);
 const [state,setState]=useState(''),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[tick,setTick]=useState(0);
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[note,setNote]=useState(''),[review,setReview]=useState('reviewing'),[copyFallback,setCopyFallback]=useState('');
 const alive=useRef(true),detailGeneration=useRef(0),pending=useRef<{signature:string;id:string}|null>(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;detailGeneration.current++}},[]);
 const headers={'Content-Type':'application/json','x-assistant-account':accountId};
 useEffect(()=>{if(demo){setLoading(false);return;}let active=true;const c=new AbortController();setLoading(true);setError('');
  fetch('/api/development?'+new URLSearchParams({state,query:search,offset:String(offset)}),{cache:'no-store',headers:{'x-assistant-account':accountId},signal:c.signal}).then(async r=>{const d:any=await r.json();if(!active)return;if(!r.ok||d.accountId!==accountId)throw new Error(d.error||'حساب تغییر کرده است؛ صفحه را تازه کنید.');setData(d);}).catch(e=>{if(active)setError(e.message||'دریافت ممکن نشد.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false;c.abort()};
 },[accountId,demo,state,search,offset,tick]);
 async function open(id:string){const generation=++detailGeneration.current;setError('');setSelected(null);setCopyFallback('');setNote('');try{const r=await fetch('/api/development?requestId='+encodeURIComponent(id),{cache:'no-store',headers}),d:any=await r.json();if(!alive.current||generation!==detailGeneration.current)return;if(!r.ok||d.accountId!==accountId)throw new Error(d.error||'دریافت انجام نشد.');setSelected(d.request);setReview(d.request.data.state);}catch(e){if(alive.current&&generation===detailGeneration.current)setError(e instanceof Error?e.message:'دریافت انجام نشد.')}}
 async function save(body:Record<string,any>){if(busy||demo)return;setBusy(true);setError('');setNotice('');const signature=JSON.stringify(body);if(pending.current?.signature!==signature)pending.current={signature,id:crypto.randomUUID()};
  try{const r=await fetch('/api/development',{method:'POST',headers,body:JSON.stringify({...body,id:pending.current.id,confirmed:true})}),d:any=await r.json();if(!alive.current)return;if(!r.ok||d.accountId!==accountId)throw new Error(d.error||'ثبت انجام نشد؛ نتیجه را با تازه‌سازی بررسی کنید.');pending.current=null;setDraft(blank());setForm(false);setNote('');setTick(t=>t+1);setNotice(d.duplicate?'این نیاز باز قبلاً ثبت شده است؛ همان درخواست باز شد.':'ثبت شد؛ درخواست و پیگیری آن در همین بخش قابل مشاهده است.');window.dispatchEvent(new Event('nafasyar-development-changed'));await open(d.requestId);
  }catch(e){if(alive.current)setError(e instanceof Error?e.message:'نتیجه ثبت قطعی نیست؛ ابتدا فهرست را تازه کنید.');}finally{if(alive.current)setBusy(false);}}
 async function copy(r:DevelopmentRequest){const text=developmentCopy(r);try{await navigator.clipboard.writeText(text);if(alive.current)setNotice('متن درخواست برای توسعه کپی شد.')}catch{if(alive.current){setCopyFallback(text);setNotice('کپی خودکار ممکن نشد؛ متن زیر را انتخاب و کپی کنید.');}}}
 if(demo)return <section className="panel inside development-intro"><Lightbulb size={32}/><h2>هم‌نفس را با نیازهای تیم توسعه بدهیم</h2><p>نیاز جدید یا اشکال نرم‌افزار را مستقیم ثبت کنید، یا از دستیار بخواهید با چند سؤال درخواست شما را آماده کند. مدیر درخواست‌ها را بررسی می‌کند و وضعیت پیگیری برای شما می‌ماند.</p><button className="btn primary" onClick={onReal}>ورود به درخواست‌های واقعی</button></section>;
 return <div className="development-panel">
  <section className="panel inside development-intro"><div className="tools"><Lightbulb size={28}/><h2>نیاز شما، مسیر توسعه هم‌نفس</h2></div><p>{data?.admin?'درخواست‌های همه همکاران را بررسی کنید، نتیجه را بنویسید و متن آماده را برای توسعه کپی کنید.':'درخواست‌های خودتان و پاسخ مدیر را اینجا دنبال کنید. همکاران دیگر به متن درخواست شما دسترسی ندارند.'}</p><div className="tools"><button className="btn primary" disabled={busy} onClick={()=>{setForm(v=>!v);setNotice('')}}><Plus size={17}/>{form?'بستن فرم':'درخواست جدید'}</button><button className="btn" onClick={()=>window.dispatchEvent(new CustomEvent('nafasyar-duty-prompt',{detail:{text:'می‌خواهم یک نیاز نرم‌افزاری برای مدیر ثبت کنم. راهنمای درخواست‌های توسعه را بخوان، هر بار یک سؤال بپرس و قبل از ثبت متن نهایی را برای تأیید نشان بده.'}}))}><Bot size={18}/>با کمک دستیار</button><span className="subtle">{data?nf(data.summary.total)+' درخواست · '+nf(data.summary.attention)+' نیازمند رسیدگی':''}</span></div></section>
  {error&&<p className="notice error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
  {form&&<form className="panel inside" onSubmit={e=>{e.preventDefault();void save({mode:'create',...draft})}}><h2>ثبت نیاز یا اشکال</h2><p className="subtle">متن برای مدیر سامانه ارسال می‌شود. اطلاعات بیمار، رمز عبور و جزئیات محرمانه را وارد نکنید.</p><fieldset disabled={busy} className="development-fields"><label className="field">نوع درخواست<select value={draft.kind} onChange={e=>setDraft(d=>({...d,kind:e.target.value}))}>{Object.entries(developmentKinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{Object.entries(developmentFields).map(([k,f])=><label key={k} className={'field '+(f.max>180?'development-wide':'')}>{f.label}{f.required?' *':' (اختیاری)'}{f.max>180?<textarea required={f.required} rows={3} maxLength={f.max} value={draft[k as keyof typeof draft]} onChange={e=>setDraft(d=>({...d,[k]:e.target.value}))}/>:<input required={f.required} maxLength={f.max} value={draft[k as keyof typeof draft]} onChange={e=>setDraft(d=>({...d,[k]:e.target.value}))}/>}</label>)}</fieldset><button className="btn primary" disabled={busy}>تأیید متن و ارسال برای مدیر</button></form>}
  <section className="panel"><form className="panelhead tools" onSubmit={e=>{e.preventDefault();setSearch(query);setOffset(0)}}><label className="field">جست‌وجو<input value={query} maxLength={180} onChange={e=>setQuery(e.target.value)} placeholder="عنوان، نام همکار یا بخش"/></label><label className="field">وضعیت<select value={state} onChange={e=>{setState(e.target.value);setOffset(0)}}><option value="">همه وضعیت‌ها</option>{Object.entries(developmentStates).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><button className="btn" type="submit">جست‌وجو</button><button className="btn" type="button" disabled={loading||busy} onClick={()=>{setTick(t=>t+1);if(selected)void open(selected.id)}}><RefreshCw size={16}/>تازه‌سازی</button></form>
   <div className="inside">{loading?<p role="status">در حال دریافت درخواست‌ها…</p>:data?.requests.length?<div className="development-list">{data.requests.map((r:DevelopmentRequest)=><article key={r.id} className={'development-row'+(selected?.id===r.id?' selected':'')}><button className="link" onClick={()=>void open(r.id)}><strong>{r.data.title}</strong><span className="badge">{developmentStates[r.data.state]}</span></button><p className="subtle">{r.data.requester} · {r.data.unit||'واحد ثبت نشده'} · {r.data.section} · {formatDateTime(r.created)}</p><p className="subtle">{developmentKinds[r.data.kind]} · {developmentSources[r.data.source]}</p><div className="tools"><button className="link" onClick={()=>void open(r.id)}>جزئیات و پیگیری</button><button className="link" onClick={()=>void copy(r)}><Copy size={15}/>کپی برای توسعه</button></div></article>)}</div>:<p className="empty">{search||state?'درخواستی با این فیلتر پیدا نشد.':'هنوز درخواستی ثبت نشده؛ نیازتان را از «درخواست جدید» بنویسید.'}</p>}</div>
   {data&&<div className="panelhead tools"><span className="subtle">{nf(data.total)} مورد در این فیلتر</span><button className="btn" disabled={offset===0||loading} onClick={()=>setOffset(n=>Math.max(0,n-50))}><ArrowRight size={16}/>قبلی</button><button className="btn" disabled={data.nextOffset===null||loading} onClick={()=>setOffset(data.nextOffset)}>بعدی<ArrowLeft size={16}/></button></div>}
  </section>
  {selected&&<section className="panel inside development-detail"><div className="tools"><MessageSquare size={22}/><h2>{selected.data.title}</h2><span className="badge">{developmentStates[selected.data.state]}</span></div><p className="subtle">{selected.data.requester} · {selected.data.unit||'واحد ثبت نشده'} · {developmentSources[selected.data.source]} · {formatDateTime(selected.created)}</p><p className="subtle">شناسه پیگیری: <bdi>{selected.id}</bdi></p><dl>{Object.entries(developmentFields).filter(([k])=>k!=='title').map(([k,f])=><div key={k}><dt>{f.label}</dt><dd>{String(selected.data[k as keyof typeof selected.data]||'—')}</dd></div>)}</dl><button className="btn" onClick={()=>void copy(selected)}><Copy size={16}/>کپی متن کامل برای توسعه</button>
   <h3>سابقه پیگیری</h3>{selected.data.history.length?selected.data.history.map((h,i)=><div className="development-history" key={i}><strong>{h.author} · {h.role==='admin'?'مدیر':'درخواست‌کننده'}</strong><p className="subtle">{formatDateTime(h.at)} · {developmentStates[h.state]}</p><p>{h.note}</p></div>):<p className="subtle">هنوز بررسی ثبت نشده است.</p>}
   <form onSubmit={e=>{e.preventDefault();void save({mode:data?.admin?'review':'clarify',requestId:selected.id,revision:selected.revision,note,...(data?.admin?{state:review}:{})})}}><fieldset disabled={busy}><h3>{data?.admin?'نتیجه بررسی مدیر':'توضیح تکمیلی'}</h3>{data?.admin&&<label className="field">وضعیت جدید<select value={review} onChange={e=>setReview(e.target.value)}>{Object.entries(developmentStates).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>}<label className="field">{data?.admin?'پاسخ یا سؤال از درخواست‌کننده':'پاسخ و توضیحات شما'}<textarea required rows={3} maxLength={4000} value={note} onChange={e=>setNote(e.target.value)}/></label><button className="btn primary" disabled={busy}>تأیید و ثبت پیگیری</button></fieldset></form>
  </section>}
  {copyFallback&&<section className="panel inside"><label className="field">متن آماده برای کپی<textarea rows={14} readOnly value={copyFallback} onFocus={e=>e.target.select()}/></label><button className="btn" onClick={()=>setCopyFallback('')}>بستن متن</button></section>}
 </div>;
}

export function DevelopmentNotifier({accountId,onOpen}:{accountId:string;onOpen:()=>void}){
 const [count,setCount]=useState(0);
 useEffect(()=>{let active=true;const c=new AbortController();setCount(0);async function refresh(){if(document.visibilityState==='hidden')return;try{const r=await fetch('/api/development?view=summary',{cache:'no-store',headers:{'x-assistant-account':accountId},signal:c.signal}),d:any=await r.json();if(active){setCount(r.ok&&d.accountId===accountId?d.summary.attention:0);}}catch{}}
 const wake=()=>void refresh();void refresh();const timer=setInterval(wake,60000);window.addEventListener('nafasyar-development-changed',wake);document.addEventListener('visibilitychange',wake);return()=>{active=false;c.abort();clearInterval(timer);window.removeEventListener('nafasyar-development-changed',wake);document.removeEventListener('visibilitychange',wake)}},[accountId]);
 return <button className="btn development-notifier" onClick={onOpen} title="درخواست‌های توسعه" aria-label={'درخواست‌های توسعه؛ '+nf(count)+' نیازمند رسیدگی'}><Lightbulb size={18}/><span>درخواست توسعه</span>{count>0&&<b>{nf(count)}</b>}</button>;
}
