'use client';
import {formatDate} from '@/lib/persian-date';
import {useEffect,useState,useRef} from 'react';
import {Upload,FileText,MessageSquare,ClipboardCheck,RefreshCw,BookOpen} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {SolarDate} from './solar-date';
import {localDay} from '@/lib/device-analytics';
import {financeReports,financePeriod,validateFinanceFile,type Cadence,type FinanceFile,type FinanceNote} from '@/lib/finance-control';
const date=(s:string)=>formatDate(s);
const num=(n:number)=>new Intl.NumberFormat('fa-IR').format(n);
function NoteBox({report,notes,write,onSave}:{report:string;notes:FinanceNote[];write:boolean;onSave:(data:Partial<FinanceNote>)=>Promise<void>}){
 const [kind,setKind]=useState<FinanceNote['kind']>('result'),[body,setBody]=useState(''),[responsible,setResponsible]=useState(''),[parent,setParent]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const related=notes.filter(n=>n.report_id===report);const roots=related.filter(n=>!n.parent_id);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await onSave({id:crypto.randomUUID(),report_id:report,kind,body,responsible:kind==='question'?responsible:'',parent_id:parent});setBody('');setResponsible('');setParent(null);setKind('result')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function reply(id:string,type:'answer'|'closure'){setParent(id);setKind(type);setBody('');setError('')}
 return <div className="finance-notes"><h3><MessageSquare size={17}/>نتیجهٔ بررسی و پرسش‌ها</h3>{!roots.length&&<p className="subtle">هنوز بررسی یا سؤالی ثبت نشده است.</p>}{roots.map(n=>{const children=related.filter(c=>c.parent_id===n.id),closed=children.some(c=>c.kind==='closure');return <article className="finance-note" key={n.id}><div className="finance-note-head"><strong>{n.kind==='question'?'سؤال از '+n.responsible:'نتیجهٔ بررسی'}</strong>{n.kind==='question'&&<span className={'badge '+(closed?'good':'warn')}>{closed?'رسیدگی‌شده':'باز'}</span>}</div><p className="finance-text">{n.body}</p><small>{n.created_by} · {date(n.created)}</small>{children.map(c=><div className="finance-reply" key={c.id}><strong>{c.kind==='closure'?'نتیجهٔ رسیدگی':'پاسخ'} · {c.created_by}</strong><p className="finance-text">{c.body}</p><small>{date(c.created)}</small></div>)}{write&&n.kind==='question'&&!closed&&<div className="tools"><button type="button" className="link" onClick={()=>reply(n.id,'answer')}>ثبت پاسخ</button><button type="button" className="link" onClick={()=>reply(n.id,'closure')}>ثبت نتیجه و بستن سؤال</button></div>}</article>})}
 {write&&<form onSubmit={save} className="finance-note-form" data-finance-dirty={body.trim()?"true":"false"}><div className="tools">{parent?<><strong>{kind==='answer'?'پاسخ به سؤال':'نتیجهٔ رسیدگی به سؤال'}</strong><button type="button" className="link" disabled={busy} onClick={()=>{setParent(null);setKind('result')}}>انصراف از پاسخ</button></>:<Select value={kind} onValueChange={v=>setKind(v as FinanceNote['kind'])} disabled={busy} dir="rtl"><SelectTrigger aria-label="نوع یادداشت"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="result">نتیجهٔ بررسی</SelectItem><SelectItem value="question">سؤال از مسئول مربوطه</SelectItem></SelectContent></Select>}{kind==='question'&&<label className="field">مسئول پاسخ<input value={responsible} onChange={e=>setResponsible(e.target.value)} required maxLength={150} placeholder="نام شخص یا واحد" disabled={busy}/></label>}</div>{parent&&<p className="subtle">{related.find(n=>n.id===parent)?.body}</p>}<label className="field">{parent?'متن پاسخ / نتیجهٔ رسیدگی':'متن نتیجه یا سؤال'}<textarea required maxLength={5000} rows={3} value={body} onChange={e=>setBody(e.target.value)} disabled={busy} placeholder="شماره سند، ردیف فایل و توضیح مورد بررسی را بنویسید."/></label>{error&&<p className="notice error" role="alert">{error}</p>}<button className="btn" disabled={busy||!body.trim()}>{busy?'در حال ثبت…':parent&&kind==='closure'?'ثبت نتیجه و بستن سؤال':'ثبت یادداشت'}</button></form>}
 </div>
}
function ReportCard({report,files,notes,write,query,onSave,onFile}:{report:typeof financeReports[number];files:FinanceFile[];notes:FinanceNote[];write:boolean;query:string;onSave:(data:Partial<FinanceNote>)=>Promise<void>;onFile:(file:FinanceFile)=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const mine=files.filter(f=>f.report_id===report.id);const reviewed=notes.some(n=>n.report_id===report.id&&n.kind==='result');
 async function upload(input:HTMLInputElement){const selected=input.files?.[0];if(!selected)return;setError('');setBusy(true);try{validateFinanceFile(selected.name,selected.size);const data=new FormData();data.append('file',selected);const r=await fetch('/api/finance/files?'+query+'&report='+report.id+'&requestId='+crypto.randomUUID(),{method:'POST',body:data});const out=await r.json() as {file:FinanceFile;error?:string};if(!r.ok)throw new Error(out.error);onFile(out.file);input.value=''}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <article className="panel finance-card"><div className="panelhead"><div><h2>{report.title}</h2><p className="subtle">{report.purpose}</p></div><span className={'badge '+(reviewed?'good':mine.length?'warn':'')}>{reviewed?'بررسی ثبت شده':mine.length?'فایل دریافت شده':'در انتظار فایل'}</span></div><div className="inside"><p><strong>فایل‌های موردنیاز: </strong>{report.files}</p><div className="finance-files">{mine.map(f=><a key={f.id} className="finance-file" href={'/api/finance/files?'+query+'&report='+report.id+'&id='+f.id}><FileText size={19}/><span><strong>{f.filename}</strong><small>{num(Math.ceil(f.byte_size/1024))} کیلوبایت · {f.uploaded_by} · {date(f.uploaded_at)}</small></span></a>)}</div>{write&&<label className="finance-upload"><Upload size={18}/><span>{busy?'در حال بارگذاری…':'افزودن فایل گزارش'}</span><input type="file" aria-label={'بارگذاری '+report.title} accept=".xlsx,.xls,.csv,.pdf,.png,.jpg,.jpeg,.docx,.zip" disabled={busy} onChange={e=>void upload(e.currentTarget)}/></label>}<p className="subtle">هر فایل حداکثر ۲۰ مگابایت · امکان افزودن چند فایل به هر گزارش</p>{error&&<p className="notice error" role="alert">{error}</p>}<details className="finance-guide"><summary><BookOpen size={17}/>روش گزارش‌گیری</summary><p>در انتظار راهنمای سپیدار. پس از دریافت فایل‌های آموزشی، مسیر منوها و تصاویر مراحل برای این گزارش اضافه می‌شود.</p><p className="subtle">فعلاً بازه، حساب یا انبار، واحد مبلغ و همهٔ ردیف‌های خروجی را بررسی کنید.</p></details><NoteBox report={report.id} notes={notes} write={write} onSave={onSave}/></div></article>
}
export function FinanceControl({write,demo}:{write:boolean;demo:boolean}){
 const [cadence,setCadence]=useState<Cadence>('daily'),[day,setDay]=useState(()=>localDay(new Date().toISOString())),[files,setFiles]=useState<FinanceFile[]>([]),[notes,setNotes]=useState<FinanceNote[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 function allowPeriodChange(){return !document.querySelector('[data-finance-dirty="true"]')||window.confirm('متن ذخیره‌نشده دارید. بدون ثبت آن دوره را تغییر می‌دهید؟')}
 const period=financePeriod(cadence,day),query=new URLSearchParams({cadence,period}).toString();const currentQuery=useRef(query);currentQuery.current=query;const reports=financeReports.filter(r=>r.cadence===cadence);const end=new Date(period+'T12:00:00Z');if(cadence==='weekly')end.setUTCDate(end.getUTCDate()+6);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setFiles([]);setNotes([]);fetch('/api/finance?'+query,{signal:controller.signal}).then(async r=>{const d=await r.json() as {files:FinanceFile[];notes:FinanceNote[];error?:string};if(!r.ok)throw new Error(d.error);setFiles(d.files);setNotes(d.notes)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[query,retry]);
 async function save(data:Partial<FinanceNote>){const r=await fetch('/api/finance?'+query,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const out=await r.json() as {note:FinanceNote;error?:string};if(!r.ok)throw new Error(out.error);if(currentQuery.current===query)setNotes(old=>[...old.filter(n=>n.id!==out.note.id),out.note])}
 const received=reports.filter(r=>files.some(f=>f.report_id===r.id)).length;const open=notes.filter(n=>n.kind==='question'&&!notes.some(c=>c.parent_id===n.id&&c.kind==='closure')).length;
 return <section className="finance-control"><div className="panel inside"><p className="subtle">مالی / کنترل مالی</p><h2>کنترل مالی</h2><p>فایل‌های گزارش را تحویل بگیرید، نتیجهٔ بررسی را ثبت کنید و پاسخ مسئول مربوطه را پیگیری کنید.</p><div className="finance-toolbar"><Tabs value={cadence} onValueChange={v=>{if(allowPeriodChange())setCadence(v as Cadence)}} dir="rtl"><TabsList aria-label="دوره کنترل"><TabsTrigger value="daily">روزانه</TabsTrigger><TabsTrigger value="weekly">هفتگی</TabsTrigger></TabsList></Tabs><SolarDate label={cadence==='daily'?'روز گزارش':'یک روز از هفتهٔ گزارش'} value={day} onChange={v=>{if(v&&allowPeriodChange())setDay(v)}}/><button className="btn" disabled={loading} onClick={()=>setRetry(n=>n+1)}><RefreshCw size={16}/>تازه‌سازی</button></div><p><strong>{cadence==='daily'?'گزارش روز '+date(period):'هفتهٔ '+date(period)+' تا '+date(end.toISOString().slice(0,10))}</strong></p><p className="subtle">دورهٔ هفتگی: شنبه تا جمعه. فایل‌ها و یادداشت‌های هر دوره مستقل ذخیره می‌شوند.</p>{demo&&<p className="notice">این بخش حتی در نمای نمونه، اطلاعات واقعی کنترل مالی را ذخیره می‌کند.</p>}<p className="subtle">بررسی این نسخه دستی است؛ بارگذاری فایل به معنی تأیید صحت یا مغایرت‌گیری خودکار نیست. ثبت سؤال اعلان یا پیام بیرونی ارسال نمی‌کند.</p></div>
 {error?<div className="notice error" role="alert">{error}<button className="btn" onClick={()=>setRetry(n=>n+1)}>تلاش مجدد</button></div>:loading?<p role="status" className="panel inside">در حال دریافت پروندهٔ این دوره…</p>:<div key={query}><div className="finance-counters"><span><FileText size={18}/>{num(received)} از {num(reports.length)} گزارش دارای فایل</span><span><MessageSquare size={18}/>{num(open)} سؤال باز در این دوره</span><span><ClipboardCheck size={18}/>{num(reports.filter(r=>notes.some(n=>n.report_id===r.id&&n.kind==='result')).length)} گزارش با نتیجهٔ ثبت‌شده</span></div><section className="panel inside finance-summary"><h2>{cadence==='daily'?'جمع‌بندی بررسی روزانه':'جمع‌بندی بررسی هفتگی'}</h2><p className="subtle">نتیجهٔ کلی دوره و سؤال‌هایی که به یک گزارش خاص محدود نیستند.</p><NoteBox report="summary" notes={notes} write={write} onSave={save}/></section><div className="finance-report-grid">{reports.map(report=><ReportCard key={report.id} report={report} files={files} notes={notes} write={write} query={query} onSave={save} onFile={file=>{if(currentQuery.current===query)setFiles(old=>[...old.filter(f=>f.id!==file.id),file])}}/>)}</div></div>}
 </section>
}
