'use client';
import {formatDateTime} from '@/lib/persian-date';
import {useEffect,useState} from 'react';
import {Plus,Upload,Download,Search,RefreshCw,FileCode2} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {fields,type Row} from '@/lib/model';
import {MAX_HEX_BYTES} from '@/lib/firmware';
const sample:Row[]=[{id:'sample-firmware',kind:'firmware',created:'2026-09-01T08:00:00.000Z',data:{name:'کنترل اکسیژن‌ساز — نمونه آموزشی',version:'1.2.0',deviceModel:'NF5',board:'CTRL-R2',notes:'نمونه برای بررسی فرم؛ فایل واقعی ندارد.',createdBy:'داده آموزشی'}}];
const date=(s:string)=>formatDateTime(s);
export function FirmwarePanel({demo,write,onSaved}:{demo:boolean;write:boolean;onSaved:(row:Row)=>void}){
 const [versions,setVersions]=useState<Row[]>(demo?sample:[]),[loading,setLoading]=useState(!demo),[error,setError]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState('');
 const [open,setOpen]=useState(false),[target,setTarget]=useState<Row|null>(null),[draft,setDraft]=useState<Record<string,string>>({}),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[formError,setFormError]=useState(''),[progress,setProgress]=useState('');
 const [downloading,setDownloading]=useState(''),[detail,setDetail]=useState<Row|null>(null);
 async function reload(){if(demo)return;setLoading(true);setError('');try{const response=await fetch('/api/firmware');const body=await response.json() as {records:Row[];error?:string};if(!response.ok)throw new Error(body.error);setVersions(body.records);}catch(e){setError((e as Error).message||'دریافت نسخه‌ها انجام نشد.');}finally{setLoading(false);}}
 useEffect(()=>{void reload();},[]);
 function saveRow(row:Row){setVersions(p=>[row,...p.filter(v=>v.id!==row.id)]);onSaved(row);}
 function start(row?:Row){setTarget(row||null);setDraft(row?{...row.data}:{});setFile(null);setFormError('');setProgress('');setOpen(true);}
 async function submit(event:React.FormEvent){
  event.preventDefault();if(busy||demo)return;
  if(file&&(!/\.hex$/i.test(file.name)||file.size===0||file.size>MAX_HEX_BYTES)){setFormError('فایل با پسوند .hex، غیرخالی و حداکثر ۱۰ مگابایت انتخاب کنید.');return;}
  if(target&&!file){setFormError('فایل HEX را انتخاب کنید.');return;}
  setBusy(true);setFormError('');let version=target;
  try{
   if(!version){setProgress('در حال ثبت نسخه…');const response=await fetch('/api/firmware',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const body=await response.json() as {record:Row;error?:string};if(!response.ok)throw new Error(body.error);version=body.record;saveRow(version);setTarget(version);}
   if(file){setProgress('نسخه ثبت شده؛ در حال بارگذاری و بررسی فایل HEX…');const payload=new FormData();payload.set('file',file);const response=await fetch('/api/firmware/files?'+new URLSearchParams({version:version.id}),{method:'POST',body:payload});const body=await response.json() as {record:Row;error?:string};if(!response.ok)throw new Error(body.error);saveRow(body.record);}
   setMessage(file?'نسخه و فایل HEX با موفقیت ذخیره شدند.':'نسخه ثبت شد؛ می‌توانید فایل HEX را بعداً کنارش بارگذاری کنید.');setOpen(false);
  }catch(e){setFormError((version?'نسخه ثبت شده و حفظ می‌شود؛ ':'')+((e as Error).message||'ذخیره تأیید نشد؛ فهرست را تازه کنید.'));}finally{setBusy(false);setProgress('');}
 }
 async function download(row:Row){if(downloading||demo)return;setDownloading(row.id);setError('');try{
  const response=await fetch('/api/firmware/files?'+new URLSearchParams({version:row.id}));if(!response.ok){const body=await response.json() as {error?:string};throw new Error(body.error);}
  const blob=await response.blob();const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=row.data.fileName;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);
 }catch(e){setError((e as Error).message||'دانلود انجام نشد؛ دوباره تلاش کنید.');}finally{setDownloading('');}}
 const visible=versions.filter(row=>JSON.stringify(row.data).toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
 return <section className="panel"><div className="panelhead"><div><h2>نسخه‌های نرم‌افزار و فایل HEX</h2><p className="subtle">نام، شماره نسخه و فایل متناظر برای هر مدل دستگاه یا برد</p></div><div className="tools"><button className="btn" onClick={reload} disabled={demo||loading}><RefreshCw size={16}/>تازه‌سازی</button>{write&&<button className="btn primary" onClick={()=>start()}><Plus size={16}/>تعریف نسخه</button>}</div></div>
 <div className="inside"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="جست‌وجوی نسخه نرم‌افزار" placeholder="نام نرم‌افزار، نسخه، مدل دستگاه یا برد…"/></div>{error&&<p className="notice error" role="alert" style={{marginTop:12}}>{error}</p>}{message&&<p className="notice" role="status" style={{marginTop:12}}>{message}</p>}</div>
 {loading?<div className="empty" role="status">در حال دریافت نسخه‌ها…</div>:visible.length?<Table><TableHeader><TableRow>{['نام نرم‌افزار / نسخه','دستگاه و برد','فایل HEX','ثبت نسخه',''].map((h,i)=><TableHead className="tablehead" key={i}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{visible.map(row=><TableRow key={row.id}><TableCell className="tablecell"><button className="link" onClick={()=>setDetail(row)}>{row.data.name}</button><p className="code">{row.data.version}</p></TableCell><TableCell className="tablecell"><p>{row.data.deviceModel||'مشخص نشده'}</p><p className="subtle">برد: <span className="code">{row.data.board||'مشخص نشده'}</span></p></TableCell><TableCell className="tablecell">{row.data.fileName?<><button className="link firmware-filename" disabled={!!downloading} onClick={()=>download(row)}><Download size={16}/><span dir="ltr">{downloading===row.id?'در حال دانلود…':row.data.fileName}</span></button><p className="subtle">{Math.ceil(Number(row.data.fileSize)/1024).toLocaleString('fa-IR')} کیلوبایت · فایل محفوظ</p></>:<><span className="badge warn">بدون فایل</span>{write&&<button className="btn" style={{marginInlineStart:10}} onClick={()=>start(row)}><Upload size={15}/>بارگذاری HEX</button>}</>}</TableCell><TableCell className="tablecell"><p>{date(row.created)}</p><p className="subtle">{row.data.createdBy}</p></TableCell><TableCell className="tablecell"><button className="link" onClick={()=>setDetail(row)}>جزئیات</button></TableCell></TableRow>)}</TableBody></Table>:<div className="empty"><FileCode2 size={30}/><h3>{query?'نسخه‌ای پیدا نشد':'هنوز نسخه‌ای تعریف نشده است'}</h3><p className="subtle">{query?'عبارت جست‌وجو را تغییر دهید.':'از «تعریف نسخه» شروع کنید؛ فایل HEX اختیاری است و بعداً هم می‌توان آن را اضافه کرد.'}</p></div>}
 <p className="footnote">فایل ثبت‌شده جایگزین نمی‌شود؛ برای فایل متفاوت، نسخه جدید تعریف کنید. ذخیره فایل به معنی تأیید عملکرد یا نصب آن روی دستگاه نیست.</p>
 <Dialog open={open} onOpenChange={v=>!busy&&setOpen(v)}><DialogContent className="modal sm:max-w-2xl"><DialogTitle style={{paddingRight:22}}>{target?'بارگذاری فایل HEX برای '+target.data.name+' — '+target.data.version:'تعریف نسخه نرم‌افزار'}</DialogTitle><DialogDescription>{demo?'نمای آموزشی؛ برای ذخیره به اطلاعات شرکت بروید.':target?'فایل به همین نسخه متصل می‌شود و قابل جایگزینی نخواهد بود.':'نام و شماره نسخه الزامی‌اند. مشخصات هویتی نسخه پس از ثبت ثابت می‌ماند.'}</DialogDescription><form onSubmit={submit}><div className="formgrid">{!target&&fields.firmware.map(f=><label className={'field '+(f.type==='textarea'?'wide':'')} key={f.key}><span>{f.label}{f.required?' *':''}</span>{f.type==='textarea'?<textarea maxLength={4000} value={draft[f.key]||''} onChange={e=>setDraft({...draft,[f.key]:e.target.value})}/>:<input required={f.required} maxLength={160} dir={['version','board'].includes(f.key)?'ltr':undefined} value={draft[f.key]||''} onChange={e=>setDraft({...draft,[f.key]:e.target.value})}/>}</label>)}<label className="field wide"><span>فایل HEX {target?'*':'(اختیاری)'}</span><input type="file" accept=".hex" required={!!target} disabled={busy} onChange={e=>{setFile(e.target.files?.[0]||null);setFormError('');}}/><span className="subtle">Intel HEX، حداکثر ۱۰ مگابایت؛ ساختار و checksum فایل بررسی می‌شود.</span>{file&&<span className="subtle" dir="ltr">{file.name}</span>}</label></div>{formError&&<p className="notice error" role="alert" style={{marginTop:12}}>{formError}</p>}{progress&&<p role="status" style={{marginTop:12}}>{progress}</p>}<div className="tools" style={{marginTop:18}}><button className="btn primary" disabled={busy||demo}>{busy?'در حال ذخیره…':target?'بارگذاری و اتصال فایل':'ثبت نسخه'}</button><button type="button" className="btn" disabled={busy} onClick={()=>setOpen(false)}>بستن</button></div></form></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><DialogContent className="modal sm:max-w-2xl"><DialogTitle style={{paddingRight:22}}>{detail?.data.name} <span className="code">{detail?.data.version}</span></DialogTitle><DialogDescription>مشخصات نسخه ثبت‌شده و فایل متناظر</DialogDescription>{error&&<p className="notice error" role="alert">{error}</p>}{detail&&<><div className="detailgrid">{fields.firmware.filter(f=>detail.data[f.key]).map(f=><div className="kv" key={f.key}><p>{f.label}</p><strong>{detail.data[f.key]}</strong></div>)}</div>{detail.data.fileName?<><div className="kv"><p>فایل HEX</p><strong className="code">{detail.data.fileName}</strong><p>{date(detail.data.fileUploadedAt)} · {detail.data.fileUploadedBy}</p></div><div className="kv"><p>اثر انگشت فایل (SHA-256)</p><strong className="firmware-hash" dir="ltr">{detail.data.fileHash}</strong></div><button className="btn primary" disabled={!!downloading} onClick={()=>download(detail)}><Download size={16}/>دانلود فایل HEX</button></>:<p className="notice">هنوز فایل HEX به این نسخه متصل نشده است.</p>}</>}</DialogContent></Dialog>
 </section>;
}
