'use client';
import {useEffect,useState} from 'react';
import {SolarDate} from './solar-date';
import {formatDate,formatDateTime,localDay,parseCalendarDay,latinDigits} from '@/lib/persian-date';
import {foreignModeTitles,foreignSelectionStates,foreignPhysicalStates,foreignFileKinds,foreignMoney,foreignMoneyText} from '@/lib/foreign-purchase-contract';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {SubprogramNavigation,IconActions,IconDisclosure} from './program-workspace';
import {PurchaseShipmentsPanel} from './purchase-shipments-panel';
import {PurchaseSettlementPanel} from './purchase-settlement-panel';
const modeTitles=foreignModeTitles;
const evidenceKinds:Record<string,string>={sample_received:'sample',sample_review:'sample',register:'registration',permit:'permit',fx_allocate:'fx_allocation',fx_buy:'fx_purchase',obligation_close:'obligation',order:'production_order',prepayment:'payment',actual:'packing',ship:'shipping',clearing:'shipping',clear:'green_sheet',cost_add:'cost',amend:'registration'};
type Grid=unknown[][];
export function ForeignPurchasesPanel({targetId=''}:{targetId?:string}){
 const [data,setData]=useState<any>(null),[view,setView]=useState('shipments'),[search,setSearch]=useState(''),[focus,setFocus]=useState(targetId),[draft,setDraft]=useState<any>(null),[upload,setUpload]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[showInitial,setShowInitial]=useState(false),[settlement,setSettlement]=useState(''),[statement,setStatement]=useState<any>(null),[grid,setGrid]=useState<Grid>([]),[mapping,setMapping]=useState<Record<string,string>>({day:'0',currency:'1',amount:'2',reference:'3'}),[preview,setPreview]=useState<any[]>([]),[sheetLoaded,setSheetLoaded]=useState(false),[previewReady,setPreviewReady]=useState(false);
 async function load(){const r=await fetch('/api/foreign-purchases?'+new URLSearchParams({search}),{cache:'no-store'}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setData(d);}
 useEffect(()=>{setFocus(targetId);setView('shipments');void load().catch(e=>setError(e.message));},[targetId]);
 const roles=data?.roles||{},cases=[...(data?.shipments||[]),...(data?.selections||[])];
 function begin(mode:string,s?:any,extra:any={}){setError('');const f=s?.data.foreign||{};setDraft({id:crypto.randomUUID(),confirmed:true,mode,caseId:s?.id,revision:s?.revision,day:localDay(),due:'',reference:'',notes:'',ownerId:f.ownerId||s?.data.ownerId||'',managerId:f.managerId||s?.data.managerId||'',logisticsId:f.logisticsId||'',inventoryId:f.inventoryId||'',receiptDays:f.receiptDays||10,reminderDays:(f.reminderDays||[14,7,3,1]).join(','),deliveryDay:f.deliveryDay||'',amount:'',amountRial:'',basis:'weight',approved:true,finish:true,lines:s?.data.initial?.lines?.map((l:any)=>({...l}))||[],...extra});}
 const change=(k:string,v:any)=>setDraft((d:any)=>({...d,[k]:v}));
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const b={...draft};if(b.mode==='configure')b.reminderDays=String(b.reminderDays).split(',').filter(Boolean).map((v:string)=>Number(latinDigits(v.trim())));if(b.mode==='receive')b.lines=b.lines.filter((l:any)=>l.quantity&&Number(latinDigits(l.quantity))>0);if(b.mode==='cost_review'&&b.basis==='manual')b.manual=b.manual.filter((l:any)=>l.amountRial!=='');const r=await fetch('/api/foreign-purchases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setDraft(null);await load();window.dispatchEvent(new Event('nafasyar-tasks-changed'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const field=(k:string,label:string,required=true,type='text')=><label className="field" key={k}>{label}<input required={required} type={type} value={draft?.[k]??''} onChange={e=>change(k,e.target.value)}/></label>;
 const pick=(k:string,label:string,items:[string,string][],required=true)=><label className="field">{label}<select required={required} value={draft?.[k]||''} onChange={e=>change(k,e.target.value)}><option value="">انتخاب کنید</option>{items.map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label>;
 const person=(k:string,label:string,role:string)=>pick(k,label,(data?.members||[]).filter((m:any)=>m.roles.includes(role)).map((m:any)=>[m.id,m.name]));
 const action=(mode:string,s:any,extra:any={})=><button className="btn" onClick={()=>begin(mode,s,extra)}>{modeTitles[mode]}</button>;
 const fileList=(s:any)=><>{(roles.buyer||roles.finance||roles.engineering||roles.logistics)&&<IconActions scope={'foreign-doc-actions:'+s.id}><button className="btn" onClick={()=>{setError('');setUpload({id:crypto.randomUUID(),caseId:s.id,revision:s.revision,kind:s.type==='foreign_selection'?'sample':roles.buyer?'packing':roles.finance?'fx_statement':roles.engineering?'technical':'shipping',issuedOn:localDay(),reference:'',file:null});}}>بارگذاری مدرک تاریخ‌دار</button></IconActions>}{(data.files||[]).filter((f:any)=>f.data.caseId===s.id).map((f:any)=><p key={f.id}>{foreignFileKinds[f.data.kind]} · {formatDate(f.data.issuedOn)} · {f.data.reference} · <a href={'/api/foreign-purchases/files?id='+encodeURIComponent(f.id)}>{f.data.filename}</a></p>)}</>;
 const packing=(s:any)=><div style={{overflowX:'auto'}}><Table><TableHeader><TableRow>{['کالا و کد تأمین‌کننده','مشخصات محصول خرید','مقدار','نت kg','گروس kg','حجم m³',...(roles.commercial?['قیمت واحد / '+s.data.currency]:[])].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{(s.data.actual?.lines||s.data.initial.lines).map((l:any)=><TableRow key={l.linkId}><TableCell>{l.name} · {l.code}<p>{l.supplierCode}</p></TableCell><TableCell>{l.supplierSpecs}<p>{l.packaging}</p></TableCell><TableCell>{l.quantity} {l.unit}</TableCell><TableCell>{l.netKg}</TableCell><TableCell>{l.grossKg}</TableCell><TableCell>{l.volumeM3}</TableCell>{roles.commercial&&<TableCell>{l.unitPrice}</TableCell>}</TableRow>)}</TableBody></Table></div>;
 const remaining=(s:any,l:any)=>{const received=(s.data.foreign?.receiving||[]).filter((r:any)=>r.linkId===l.linkId).reduce((n:number,r:any)=>n+r.quantity,0);return String(Math.max(0,Number(l.quantity)-received/1000));};
 async function sendFile(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const {file,...meta}=upload,q=new URLSearchParams({...meta,filename:file.name,confirmed:'true'}),r=await fetch('/api/foreign-purchases/files?'+q,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setUpload(null);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function readSheet(file:File){setSheetLoaded(false);setPreviewReady(false);try{const read=(await import('read-excel-file/browser')).readSheet,rows=await read(file);setGrid(rows);setPreview([]);setSheetLoaded(true);setError('');}catch(e){setError((e as Error).message);}}
 async function registeredSheet(id:string){const f=data.files.find((f:any)=>f.id===id);if(!f)return;try{const r=await fetch('/api/foreign-purchases/files?id='+encodeURIComponent(id));if(!r.ok)throw Error('خواندن فایل اصلی ممکن نشد.');await readSheet(new File([await r.blob()],f.data.filename));}catch(e){setError((e as Error).message);}}
 function mapPreview(){try{if(!sheetLoaded)throw Error('فایل اصلی حساب را انتخاب و خواندن آن را کامل کنید.');const rows=grid.slice(1).filter(row=>row.some(c=>c!==null&&c!==''));if(rows.length>500)throw Error('حداکثر ۵۰۰ ردیف را در هر فایل وارد کنید.');setPreview(rows.map((row,i)=>{const day=parseCalendarDay(row[Number(mapping.day)]),currency=String(row[Number(mapping.currency)]||'').trim().toUpperCase(),amount=latinDigits(String(row[Number(mapping.amount)]??'')).trim().replace(/[,٬]/g,''),reference=String(row[Number(mapping.reference)]||'').trim();if(!day||!['USD','EUR','CNY','IRR','IRT'].includes(currency)||foreignMoney(amount)<=BigInt(0)||!reference)throw Error('تاریخ، ارز، مبلغ یا مرجع در ردیف '+(i+2)+' معتبر نیست. فقط ردیف‌های واریز را وارد کنید.');return {day,currency,amount,reference};}));setPreviewReady(true);}catch(e){setPreview([]);setPreviewReady(false);setError((e as Error).message);}}
 async function importStatement(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/foreign-purchases/statements',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...statement,confirmed:true,rows:preview})}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setStatement(null);setGrid([]);setPreview([]);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel" dir="rtl"><div className="panelhead"><h2>بازرگانی خارجی</h2><IconActions scope="foreign-top"><button className="btn" onClick={()=>void load().catch(e=>setError(e.message))}>تازه‌سازی</button>{roles.buyer&&<><button className="btn" onClick={()=>begin('selection_create')}>انتخاب منبع / نمونه جدید</button><button className="btn" onClick={()=>setShowInitial(v=>!v)}>مشخصات و محموله جدید</button></>}</IconActions></div><div className="inside">{error&&!draft&&!upload&&!statement&&<p className="notice error" role="alert">{error}</p>}{!data&&<p>در حال دریافت…</p>}{data&&<><p className="notice">{data.help}</p><p>مدیر بازرگانی و مسئول‌های هر مرحله را در کاربران و دسترسی‌ها و سپس در هر پرونده تعیین کنید. مهلت‌ها به وقت تهران‌اند.</p>{showInitial&&<PurchaseShipmentsPanel/>}{settlement&&<><button className="btn" onClick={()=>setSettlement('')}>بستن تسویه خرید</button><PurchaseSettlementPanel planId={settlement}/></>}
 <SubprogramNavigation items={[["shipments","خرید و حمل"],["selection","انتخاب منبع و نمونه"],["alerts","پیگیری‌ها"],...(roles.commercial?[["statements","حساب صراف و دریافت‌ها"]] as [string,string][]:[])]} value={view} onChange={setView}/><form onSubmit={e=>{e.preventDefault();void load().catch(e=>setError(e.message));}}><label className="field">جست‌وجوی کالا یا تأمین‌کننده<input value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="btn">جست‌وجو</button>{focus&&<button className="btn" type="button" onClick={()=>setFocus('')}>نمایش همه پرونده‌ها</button>}</form>
 {focus&&data.selections.some((s:any)=>s.id===focus)&&view==='shipments'&&<button className="btn" onClick={()=>setView('selection')}>باز کردن پرونده نمونه</button>}{view==='selection'&&(data.selections||[]).filter((s:any)=>!focus||s.id===focus).map((s:any)=><article className="flow-card" key={s.id}><h3>{s.data.name} · {foreignSelectionStates[s.data.state]}</h3><p>دور {s.data.round} · موعد {formatDate(s.data.sampleDue||s.data.due)} · {s.data.supplierName}</p><p>{s.data.generalSpecs} · {s.data.supplierSpecs}</p><IconActions scope={'foreign-selection:'+s.id}>{roles.buyer&&['searching','rejected'].includes(s.data.state)&&action('selection_candidate',s)}{roles.buyer&&s.data.state==='awaiting_sample'&&action('sample_received',s)}{roles.engineering&&s.data.state==='review'&&action('sample_review',s)}{roles.buyer&&action('selection_reopen',s)}</IconActions><IconDisclosure scope={'foreign-selection-files:'+s.id} title="نمونه و مدارک">{fileList(s)}</IconDisclosure><IconDisclosure scope={'foreign-selection-history:'+s.id} title="تاریخچه انتخاب و بررسی">{s.data.history.map((h:any,i:number)=><p key={i}>{formatDateTime(h.at)} · {modeTitles[h.mode]} · {h.notes}</p>)}</IconDisclosure></article>)}
 {view==='shipments'&&(data.shipments||[]).filter((s:any)=>!focus||s.id===focus).map((s:any)=>{const f=s.data.foreign||{};return <article className="flow-card" key={s.id}><h3>{s.data.title} · {s.data.supplierName}</h3><p className={f.allocation?'notice':'notice error'}>{s.labels.allocation} · {s.labels.administrative} · {s.labels.physical}</p>{f.deliveryDay&&<p>تحویل وعده‌داده‌شده: {formatDate(f.deliveryDay)}</p>}
 <IconDisclosure scope={'foreign-packing:'+s.id} title={s.data.actual?'پکینگ واقعی در اختیار انبار':'برآورد اولیه؛ پکینگ واقعی هنوز ثبت نشده'}>{packing(s)}{(f.receiving||[]).map((r:any)=><p key={r.batchId}>دریافت {r.quantity/1000} · {formatDate(r.day)} · بچ {r.batchId} · {r.discrepancy} · منتظر کنترل کیفیت</p>)}</IconDisclosure>
 <IconActions scope={'foreign-config:'+s.id}>{roles.buyer&&action('configure',s)}{roles.buyer&&!s.data.registration&&action('register',s)}{roles.buyer&&s.data.registration&&!s.data.permit&&action('permit',s)}{roles.buyer&&s.data.actual&&action('amend',s)}{roles.commercial&&f.orderIds?.length>0&&<button className="btn" onClick={()=>setSettlement(s.id)}>تسویه خرید و قیمت بچ‌های این بار</button>}</IconActions>
 {roles.commercial&&<IconDisclosure scope={'foreign-fx:'+s.id} title="مجوز، تخصیص و تعهد ارزی"><IconActions scope={'foreign-fx-actions:'+s.id}>{roles.buyer&&!f.queue&&!f.allocation&&action('fx_queue',s)}{roles.buyer&&f.queue&&!f.allocation&&action('fx_allocate',s)}{roles.finance&&f.allocation&&action('fx_buy',s)}</IconActions>{f.queue&&<p>صف تخصیص: {f.queue.reference} · {formatDate(f.queue.day)}</p>}{f.allocation&&<p>تخصیص: {f.allocation.amount} {f.allocation.currency} · {formatDate(f.allocation.day)}</p>}{(f.fxPurchases||[]).map((p:any)=><div className="notice" key={p.id}><p>خرید ارز: {p.amount} {p.currency} · {formatDate(p.day)} · {p.reference} · حساب {p.account}</p><p>دریافت صراف: {p.received?'تأییدشده':'منتظر تأیید'} · موعد پیگیری {formatDate(p.receiptDue)}</p><p className={!p.obligationDue&&!p.closed?'notice error':''}>رفع تعهد: {p.closed?'ثبت‌شده در '+formatDate(p.closed.day):p.obligationDue?'موعد '+formatDate(p.obligationDue):'تاریخ باید توسط مدیر بازرگانی تعیین شود'}</p><IconActions scope={'foreign-fx-item:'+p.id}>{roles.manager&&!p.closed&&action('obligation_due',s,{fxId:p.id,due:p.obligationDue||''})}{roles.manager&&p.obligationDue&&!p.closed&&action('obligation_close',s,{fxId:p.id})}</IconActions>{roles.finance&&!p.received&&(data.candidates.find((c:any)=>c.caseId===s.id&&c.fxId===p.id)?.rows||[]).map((r:any)=><p key={r.id}>{formatDate(r.data.day)} · {r.data.reference} · قابل تخصیص {r.available} {r.data.currency} {r.exactReference?'· مرجع منطبق':''} <button className="btn" onClick={()=>begin('fx_receipt',s,{fxId:p.id,rowId:r.id,amount:foreignMoneyText([foreignMoney(r.available),foreignMoney(p.amount)-(p.matches||[]).reduce((n:bigint,x:any)=>n+foreignMoney(x.amount),BigInt(0))].reduce((a,b)=>a<b?a:b))})}>بررسی و تأیید دریافت</button></p>)}{(p.matches||[]).map((m:any)=><p key={m.rowId}>دریافت تأییدشده {m.amount} · {m.reference} · {formatDate(m.day)} {roles.finance&&!p.closed&&<button className="btn" onClick={()=>begin('fx_receipt_undo',s,{fxId:p.id,rowId:m.rowId})}>ابطال تطبیق با علت</button>}</p>)}</div>)}</IconDisclosure>}
 <IconDisclosure scope={'foreign-physical:'+s.id} title="سفارش تولید، پیش‌پرداخت و حمل"><p>{foreignPhysicalStates[f.physical||'planned']}</p><IconActions scope={'foreign-physical-actions:'+s.id}>{roles.buyer&&(!f.physical||f.physical==='planned')&&action('order',s)}{roles.finance&&f.order&&action('prepayment',s)}{roles.buyer&&['ordered','preparing'].includes(f.physical)&&action('delivery',s)}{roles.buyer&&!s.data.actual&&action('actual',s)}{roles.buyer&&['ordered','preparing'].includes(f.physical)&&action('ready',s)}{(roles.buyer||roles.logistics)&&f.physical==='ready'&&action('ship',s)}{(roles.buyer||roles.logistics)&&f.physical==='shipping'&&action('clearing',s)}{roles.buyer&&f.physical==='clearing'&&action('clear',s)}{roles.inventory&&f.physical==='cleared'&&action('receive',s,{lines:s.data.actual.lines.map((l:any)=>({...l,quantity:remaining(s,l),discrepancy:''}))})}</IconActions>{roles.commercial&&(f.prepayments||[]).map((p:any)=><p key={p.id}>پیش‌پرداخت {p.amount} {p.currency} · {p.reference} · {formatDate(p.day)}</p>)}</IconDisclosure>
 {roles.commercial&&<IconDisclosure scope={'foreign-costs:'+s.id} title="هزینه‌های همین بار و تخصیص مالی"><p>تخصیص هزینه این صفحه سابقهٔ بررسی بار است؛ قیمت بچ از مسیر «تسویه خرید» پس از پذیرش انبار و کیفیت تأیید می‌شود.</p>{roles.buyer&&action('cost_add',s)}{(f.costs||[]).map((c:any)=><div className="notice" key={c.id}><p>{c.title} · {c.amountRial} ریال · {formatDate(c.day)} · {c.state==='approved'?'تأییدشده':c.state==='rejected'?'ردشده':'منتظر مالی'}</p>{roles.finance&&c.state==='review'&&action('cost_review',s,{costId:c.id,manual:(s.data.actual?.lines||[]).map((l:any)=>({linkId:l.linkId,amountRial:''}))})}{c.allocations?.map((a:any)=><p key={a.linkId}>{s.data.initial.lines.find((l:any)=>l.linkId===a.linkId)?.name} · سهم {a.amountRial} ریال</p>)}</div>)}</IconDisclosure>}
 <IconDisclosure scope={'foreign-files:'+s.id} title="مدارک تاریخ‌دار">{fileList(s)}</IconDisclosure>{roles.commercial&&<IconDisclosure scope={'foreign-history:'+s.id} title="سابقه مراحل">{s.data.history.map((h:any,i:number)=><p key={i}>{formatDateTime(h.at)} · {modeTitles[h.mode]||h.mode} · {h.notes}</p>)}</IconDisclosure>}</article>;})}
 {view==='alerts'&&<>{!data.alerts.length&&<p>پیگیری بازی نیست.</p>}{data.alerts.map((a:any)=><div className="notice" key={a.caseId+a.key}><p>{a.title} · موعد {formatDate(a.due)}</p><button className="btn" onClick={()=>{setFocus(a.caseId);setView('shipments');}}>باز کردن پرونده</button></div>)}</>}
 {view==='statements'&&roles.commercial&&<>{roles.finance&&<button className="btn" onClick={()=>{setError('');setGrid([]);setPreview([]);setSheetLoaded(false);setPreviewReady(false);setStatement({id:crypto.randomUUID(),account:'',from:localDay(),to:localDay(),fileId:'',notes:''});}}>ورود اکسل حساب صراف</button>}<p>فایل اکسل اصلی را ابتدا در مدارک یکی از محموله‌ها با نوع «اکسل حساب صراف» بارگذاری کنید؛ سپس ستون‌ها و بازه پوشش را مشخص کنید. تطبیق پیشنهادی خودکار دریافت را تأیید نمی‌کند.</p>{data.statements.map((s:any)=><p key={s.id}>{s.data.account} · {formatDate(s.data.from)} تا {formatDate(s.data.to)} · {s.data.rowIds.length} ردیف واریز</p>)}</>}
 </>}</div>
 <Dialog open={!!draft} onOpenChange={v=>{if(!busy&&!v)setDraft(null);}}><DialogContent className="modal sm:max-w-4xl"><DialogTitle>{modeTitles[draft?.mode]}</DialogTitle><DialogDescription>ثبت با نام شما، مدرک مرتبط و حفظ سابقه انجام می‌شود. نبود تخصیص ارز مانع مراحل خرید و حمل نیست.</DialogDescription>{draft&&<form onSubmit={save}><fieldset disabled={busy} style={{border:0}}><div className="formgrid">{field('notes','شرح اقدام / علت')}<SolarDate label="تاریخ واقعی مرحله" value={draft.day} onChange={v=>change('day',v)}/>
 {draft.mode==='selection_create'&&<>{pick('materialId','کالا',data.materials.map((m:any)=>[m.id,m.code+' · '+m.name]))}{person('ownerId','کارشناس بازرگانی','buyer')}{person('managerId','مدیر بازرگانی','manager')}<SolarDate label="موعد انتخاب منبع" value={draft.due} onChange={v=>change('due',v)}/></>}
 {draft.mode==='selection_candidate'&&<>{pick('linkId','محصول تأمین‌کننده',data.links.filter((l:any)=>l.data.materialId===cases.find(s=>s.id===draft.caseId)?.data.materialId).map((l:any)=>[l.id,data.suppliers.find((s:any)=>s.id===l.data.supplierId)?.data.name+' · '+l.data.supplierCode]))}<SolarDate label="موعد دریافت نمونه" value={draft.sampleDue||''} onChange={v=>change('sampleDue',v)}/></>}
 {['selection_reopen','obligation_due'].includes(draft.mode)&&<SolarDate label={draft.mode==='obligation_due'?'تاریخ رفع تعهد تعیین‌شده توسط مدیر':'موعد دور جدید انتخاب'} value={draft.due} onChange={v=>change('due',v)}/>}
 {draft.mode==='configure'&&<>{person('ownerId','کارشناس بازرگانی','buyer')}{person('managerId','مدیر بازرگانی','manager')}{person('logisticsId','مسئول تدارکات','logistics')}{person('inventoryId','مسئول انبار','inventory')}{field('receiptDays','مهلت پیگیری دریافت صراف / روز',true,'number')}{field('reminderDays','روزهای یادآوری قبل از موعد، با ویرگول')}</>}
 {['sample_received','register','permit','fx_queue','fx_allocate','fx_buy','order','prepayment','ship','clearing','clear','cost_add','amend'].includes(draft.mode)&&field('reference','شماره / مرجع واقعی')}
 {['fx_allocate','fx_buy','prepayment','fx_receipt'].includes(draft.mode)&&field('amount','مبلغ به ارز پرونده')}{draft.mode==='fx_buy'&&<>{field('account','شناسه حساب صراف')}{field('expectedReference','مرجع مورد انتظار در حساب، اگر معلوم است',false)}<p>پس از ثبت، تعیین موعد رفع تعهد در کارتابل مدیر بازرگانی قرار می‌گیرد.</p></>}
 {['order','delivery'].includes(draft.mode)&&<SolarDate label="تاریخ تحویل وعده‌داده‌شده" value={draft.deliveryDay} onChange={v=>change('deliveryDay',v)}/>}
 {['sample_review','cost_review'].includes(draft.mode)&&<label className="field">تصمیم<select value={draft.approved?'yes':'no'} onChange={e=>change('approved',e.target.value==='yes')}><option value="yes">تأیید</option><option value="no">رد با شرح علت</option></select></label>}
 {draft.mode==='cost_add'&&<>{field('title','نوع و عنوان هزینه')}{field('amountRial','مبلغ هزینه / ریال')}</>}{draft.mode==='cost_review'&&draft.approved&&<>{pick('basis','روش تخصیص',[['weight','وزن ناخالص واقعی'],['value','ارزش واقعی اقلام'],['manual','تخصیص دستی']])}{draft.basis==='manual'&&draft.manual.map((l:any,i:number)=><label className="field" key={l.linkId}>سهم ریال {cases.find(s=>s.id===draft.caseId)?.data.initial.lines.find((x:any)=>x.linkId===l.linkId)?.name}<input required value={l.amountRial} onChange={e=>change('manual',draft.manual.map((x:any,j:number)=>i===j?{...x,amountRial:e.target.value}:x))}/></label>)}</>}
 {evidenceKinds[draft.mode]&&pick('documentId','مدرک همین مرحله',data.files.filter((f:any)=>f.data.caseId===draft.caseId&&f.data.kind===evidenceKinds[draft.mode]).map((f:any)=>[f.id,f.data.reference+' · '+f.data.filename]))}
 {['actual','receive'].includes(draft.mode)&&draft.lines.map((l:any,i:number)=><div className="notice wide" key={l.linkId}><strong>{l.name} · {l.code} · {l.packaging}</strong><div className="formgrid">{Object.entries(draft.mode==='receive'?{quantity:'مقدار واقعی دریافت / '+l.unit,discrepancy:'شرح کسری، دریافت جزئی یا اضافه',manufacturerLot:'لات سازنده'}:{quantity:'مقدار / '+l.unit,unitPrice:'قیمت واحد / ارز پرونده',packaging:'نوع بسته‌بندی',netKg:'نت kg',grossKg:'گروس kg',volumeM3:'حجم m³'}).map(([k,t])=><label className="field" key={k}>{t}<input required={draft.mode!=='receive'||k==='quantity'} value={l[k]??''} onChange={e=>change('lines',draft.lines.map((x:any,j:number)=>i===j?{...x,[k]:e.target.value}:x))}/></label>)}</div></div>)}{draft.mode==='receive'&&<><label className="field"><Checkbox checked={draft.finish} onCheckedChange={v=>change('finish',v===true)}/>پایان دریافت؛ ادامه با کنترل کیفیت</label>{field('discrepancyResolution','تعیین تکلیف مغایرت نهایی، اگر وجود دارد',false)}</>}
 </div>{error&&<p className="notice error" role="alert">{error}</p>}<button className="btn primary">تأیید و ثبت</button></fieldset></form>}</DialogContent></Dialog>
 <Dialog open={!!upload} onOpenChange={v=>{if(!busy&&!v)setUpload(null);}}><DialogContent className="modal"><DialogTitle>مدرک تاریخ‌دار پرونده</DialogTitle><DialogDescription>نسخه‌های قبلی مدارک حفظ می‌شوند.</DialogDescription>{upload&&<form onSubmit={sendFile}><fieldset disabled={busy} style={{border:0}}><label className="field">نوع<select value={upload.kind} onChange={e=>setUpload({...upload,kind:e.target.value})}>{Object.entries(foreignFileKinds).filter(([k])=>roles.buyer||roles.finance&&['payment','cost','fx_statement','fx_purchase','obligation'].includes(k)||roles.engineering&&['sample','technical'].includes(k)||roles.logistics&&k==='shipping').map(([k,t])=><option value={k} key={k}>{t}</option>)}</select></label><SolarDate label="تاریخ صدور" value={upload.issuedOn} onChange={v=>setUpload({...upload,issuedOn:v})}/><label className="field">شماره / مرجع<input required value={upload.reference} onChange={e=>setUpload({...upload,reference:e.target.value})}/></label><label className="field">فایل<input type="file" required onChange={e=>setUpload({...upload,file:e.target.files?.[0]})}/></label>{error&&<p role="alert">{error}</p>}<button className="btn primary">تأیید و بارگذاری</button></fieldset></form>}</DialogContent></Dialog>
 <Dialog open={!!statement} onOpenChange={v=>{if(!busy&&!v)setStatement(null);}}><DialogContent className="modal sm:max-w-4xl"><DialogTitle>ورود و پیش‌نمایش اکسل حساب صراف</DialogTitle><DialogDescription>فقط واریزها؛ ارز و حساب دقیق، بازه پوشش واقعی و مرجع هر تراکنش را ثبت کنید. حساب بدون واریز نیز قابل ثبت است.</DialogDescription>{statement&&<form onSubmit={importStatement}><fieldset disabled={busy} style={{border:0}}><div className="formgrid"><label className="field">حساب صراف<input required value={statement.account} onChange={e=>setStatement({...statement,account:e.target.value})}/></label><SolarDate label="از تاریخ" value={statement.from} onChange={v=>setStatement({...statement,from:v})}/><SolarDate label="تا تاریخ" value={statement.to} onChange={v=>setStatement({...statement,to:v})}/><label className="field">فایل اصلی ثبت‌شده<select required value={statement.fileId} onChange={e=>{setStatement({...statement,fileId:e.target.value});setSheetLoaded(false);setPreviewReady(false);void registeredSheet(e.target.value);}}><option value="">انتخاب کنید</option>{data.files.filter((f:any)=>f.data.kind==='fx_statement').map((f:any)=><option key={f.id} value={f.id}>{f.data.filename} · {f.data.reference}</option>)}</select></label><label className="field">شرح واردسازی<input required value={statement.notes} onChange={e=>setStatement({...statement,notes:e.target.value})}/></label>{Object.entries({day:'تاریخ واریز',currency:'ارز',amount:'مبلغ واریز',reference:'مرجع تراکنش'}).map(([k,t])=><label className="field" key={k}>{t}<select value={mapping[k]} onChange={e=>{setMapping({...mapping,[k]:e.target.value});setPreview([]);setPreviewReady(false);}}>{(grid[0]||[]).map((cell,i)=><option key={i} value={String(i)}>{String(cell||'ستون '+(i+1))}</option>)}</select></label>)}</div><button className="btn" type="button" onClick={mapPreview}>پیش‌نمایش ردیف‌ها</button><p>{preview.length} ردیف واریز برای ثبت؛ پیش‌نمایش خالی یعنی در این بازه واریزی وجود نداشته است.</p><div style={{maxHeight:260,overflow:'auto'}}><Table><TableHeader><TableRow>{['تاریخ','ارز','مبلغ','مرجع'].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{preview.map((r,i)=><TableRow key={i}><TableCell>{formatDate(r.day)}</TableCell><TableCell>{r.currency}</TableCell><TableCell>{r.amount}</TableCell><TableCell>{r.reference}</TableCell></TableRow>)}</TableBody></Table></div>{error&&<p role="alert">{error}</p>}<button className="btn primary" disabled={!sheetLoaded||!previewReady}>تأیید بازه و ردیف‌های پیش‌نمایش</button></fieldset></form>}</DialogContent></Dialog>
 </section>;
}
