'use client';
import {ProgramWorkspace,SubprogramNavigation} from "./program-workspace";
import {formatDateTime} from '@/lib/persian-date';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
const labels:Record<string,string>={delivered:'تحویل نهایی مقصد',planned:'در انتظار مونتاژ',prepared:'در انتظار تأیید برگ تولید',assembled:'برگ تولید ثبت‌شده',awaiting_receipt:'در انتظار دریافت انبار',finished:'آزاد در انبار',reserved:'رزروشده',in_transit:'تحویل تدارکات / در مسیر',cancelled:'لغوشده',pending:'در انتظار دریافت',closed:'بسته'};
const kinds:Record<string,string>={agent:'عامل فروش',representative:'نماینده فروش',branch:'شعبه'};
const date=(v:string)=>v?formatDateTime(v):'—';
function Pick({label,value,items,onChange}:{label:string;value:string;items:[string,string][];onChange:(v:string)=>void}){return <label className="field">{label}<Select dir="rtl" value={value||''} onValueChange={onChange}><SelectTrigger><SelectValue placeholder="انتخاب کنید"/></SelectTrigger><SelectContent>{items.map(([id,name])=><SelectItem value={id} key={id}>{name}</SelectItem>)}</SelectContent></Select></label>}
export function FulfillmentPanel({demo,onSaved}:{demo:boolean;onSaved:()=>void}){
 const [data,setData]=useState<any>(null),[tab,setTab]=useState('handoff'),[query,setQuery]=useState(''),[product,setProduct]=useState(''),[selected,setSelected]=useState<string[]>([]),[draft,setDraft]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
 async function load(){if(demo)return;setLoading(true);try{const r=await fetch('/api/fulfillment',{cache:'no-store'}),d=await r.json() as any;if(!r.ok)throw new Error(d.error);setData(d)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[demo]);
 useEffect(()=>{if(data&&!data.roles.production&&tab==='handoff')setTab(data.roles.inventory?'receive':data.roles.sales?'sales':'dispatch')},[data,tab]);
 const rows=data?.rows||[],builds=data?.builds||[],roles=data?.roles||{},handoffs=data?.handoffs||[],sales=data?.sales||[],parties=data?.parties||[];
 const rec=(id:string)=>rows.find((r:any)=>r.id===id)?.data||{},serial=(id:string)=>rec(id).code||id;
 const products:[string,string][]=rows.filter((r:any)=>r.kind==='product').map((r:any)=>[r.id,r.data.name+' · '+r.data.model]);
 const ready=(b:any)=>b.data.state==='assembled'&&b.data.latestQc?.verdict==='pass';
 const candidates=builds.filter((b:any)=>b.printRecorded&&['planned','prepared','assembled'].includes(b.data.state)&&(!product||rec(b.id).product===product)&&(!query||serial(b.id).toLowerCase().includes(query.trim().toLowerCase())));
 function start(mode:string,extra:any={}){setError('');setMessage('');setDraft({id:crypto.randomUUID(),mode,...extra})}
 const change=(key:string,value:any)=>setDraft((d:any)=>({...d,[key]:value}));
 function check(id:string,list:string[],set:(v:string[])=>void){set(list.includes(id)?list.filter(x=>x!==id):[...list,id])}
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/fulfillment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)}),d=await r.json() as any;if(!r.ok)throw new Error(d.error);setDraft(null);setSelected([]);setMessage('عملیات ثبت شد؛ کارتابل و موجودی به‌روز شدند.');await load();onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(demo)return <p className="notice">برای تحویل و ارسال دستگاه وارد اطلاعات شرکت شوید.</p>;
 const mode=draft?.mode;
 const reservedSale=sales.find((s:any)=>s.id===draft?.saleId);
 const dispatchCandidates=builds.filter((b:any)=>rec(b.id).product===reservedSale?.data.productId&&(b.data.state==='finished'||b.data.state==='reserved'&&b.data.saleId===reservedSale?.id));
 const shipmentCards=(items:any[])=>items.map((s:any)=><article className="flow-card" key={s.id}><h3>{s.data.recipient.name} · {s.data.count.toLocaleString('fa-IR')} دستگاه</h3><p>{labels[s.data.state]} · {date(s.created)} · فروش: {s.data.by}</p><p>{s.data.recipient.address} · {s.data.recipient.phone}</p><details><summary>سریال‌ها و سابقه تحویل</summary>{s.data.deviceIds.map((id:string)=><p dir="ltr" key={id}>{serial(id)}</p>)}<p>{s.data.notes}</p>{s.data.transportId&&<p>رهگیری و بارنامه این حواله در بخش «تدارکات و حمل‌ونقل» در دسترس است.</p>}{s.data.dispatchedAt&&<p>خروج: {date(s.data.dispatchedAt)} · انباردار: {s.data.dispatchedBy} · تدارکات: {s.data.carrierName}</p>}{s.data.receiptReference&&<p>شماره رسید: {s.data.receiptReference}</p>}{s.data.acknowledgedAt&&<p>تأیید تحویل‌گیرنده: {s.data.acknowledgedBy} · {date(s.data.acknowledgedAt)}</p>}</details><div className="tools">{s.data.state==='reserved'&&roles.inventory&&<button className="btn primary" onClick={()=>start('dispatch',{saleId:s.id,deviceIds:s.data.deviceIds,carrierId:'',reason:'',receiptReference:'',handedOver:false})}>آماده‌سازی و تحویل به تدارکات</button>}{s.data.state==='reserved'&&roles.sales&&<button className="btn" onClick={()=>start('cancel_sale',{saleId:s.id,reason:''})}>لغو رزرو</button>}{s.data.state==='in_transit'&&!s.data.acknowledgedAt&&!s.data.transportId&&roles.logistics&&<button className="btn primary" onClick={()=>start('acknowledge',{saleId:s.id,notes:''})}>تأیید دریافت از انبار</button>}</div></article>);
 return <ProgramWorkspace programId="fulfillment-panel" title="تحویل و ارسال"><section className="panel"><div className="panelhead"><div><h2>محصول نهایی و ارسال</h2><p className="subtle">تحویل تولید ← دریافت انبار ← رزرو فروش ← خروج به تدارکات</p></div><button className="btn" disabled={loading||busy} onClick={()=>void load()}>تازه‌سازی</button></div><div className="inside">
 <SubprogramNavigation items={([['handoff','تحویل از خط تولید',roles.production],['receive','کارتابل دریافت انبار',roles.inventory],['sales','موجودی و فروش',roles.sales||roles.inventory],['dispatch','کارتابل ارسال',roles.inventory||roles.logistics],['parties','گیرندگان',roles.sales]].filter(x=>x[2])).map(([key,title])=>[String(key),String(title)] as [string,string])} value={tab} onChange={key=>{setTab(key);setSelected([])}}/>
 {error&&!draft&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}{loading&&<p>در حال دریافت…</p>}
 {tab==='handoff'&&roles.production&&<><p className="notice">سریال‌هایی که چاپشان ثبت شده و هنوز از خط تولید تحویل انبار نشده‌اند. فقط دستگاه دارای برگ تولید و کنترل کیفیت قبول‌شده قابل ارجاع است. سریال‌های در انتظار دریافت پایین صفحه‌اند.</p><div className="formgrid"><label className="field">جست‌وجوی سریال<input value={query} onChange={e=>setQuery(e.target.value)} dir="ltr"/></label><Pick label="محصول" value={product} items={products} onChange={setProduct}/><button className="btn" onClick={()=>{setProduct('');setQuery('')}}>نمایش همه</button></div><div className="tools"><button className="btn" onClick={()=>setSelected(candidates.filter(ready).slice(0,100).map((b:any)=>b.id))}>انتخاب آماده‌های این فهرست</button><button className="btn primary" disabled={!selected.length} onClick={()=>start('handoff',{deviceIds:selected,packaged:false,notes:''})}>ارجاع {selected.length.toLocaleString('fa-IR')} دستگاه به انبار</button></div>{!candidates.length&&<p className="empty">سریال چاپ‌شده‌ای در این فهرست نیست.</p>}{candidates.map((b:any)=><label className="flow-card flow-check" key={b.id}><Checkbox disabled={!ready(b)} checked={selected.includes(b.id)} onCheckedChange={()=>check(b.id,selected,setSelected)}/><span><strong dir="ltr">{serial(b.id)}</strong><p>{rec(b.id).productName} · {labels[b.data.state]}</p><p>کنترل کیفیت: {b.data.latestQc?.verdict==='pass'?'قبول':b.data.latestQc?.verdict==='fail'?'مردود':'ثبت نشده'} · {b.data.latestQc?.by||'—'} · مونتاژکار: {b.data.assembler||'—'}</p></span></label>)}</>}
 {((tab==='handoff'&&roles.production)||(tab==='receive'&&roles.inventory))&&<><h3>درخواست‌های تحویل</h3>{!handoffs.length&&<p className="empty">درخواستی ثبت نشده است.</p>}{handoffs.map((h:any)=><article className="flow-card" key={h.id}><h3>{h.data.by} · {date(h.created)}</h3><p>کل: {h.data.deviceIds.length} · دریافت‌شده: {h.data.received.length} · باقی‌مانده: {h.data.pending.length}</p><p>{h.data.notes}</p><details><summary>سریال‌ها و سوابق</summary>{h.data.deviceIds.map((d:string)=><p key={d}>{serial(d)} · {h.data.received.includes(d)?'دریافت‌شده':h.data.pending.includes(d)?'در انتظار':'برگشت به خط'}</p>)}{h.data.history.map((x:any,i:number)=><p key={i}>{x.by} · {date(x.at)} · {x.deviceIds.length} دستگاه · {x.notes}</p>)}</details>{h.data.state==='pending'&&<div className="tools">{roles.inventory&&<button className="btn primary" onClick={()=>start('receive',{handoffId:h.id,deviceIds:h.data.pending,notes:''})}>ثبت دریافت فیزیکی</button>}{roles.production&&<button className="btn" onClick={()=>start('cancel_handoff',{handoffId:h.id,deviceIds:h.data.pending,notes:''})}>بازگرداندن درخواست به خط</button>}</div>}</article>)}</>}
 {tab==='sales'&&<><div className="tools">{roles.sales&&<button className="btn primary" onClick={()=>start('reserve',{productId:'',partyId:'',count:1,deviceIds:[],notes:''})}>تخصیص و رزرو برای گیرنده</button>}</div>{products.map(([id,name])=><article className="flow-card" key={id}><h3>{name}</h3><p>آزاد: {builds.filter((b:any)=>rec(b.id).product===id&&b.data.state==='finished').length} · رزرو: {builds.filter((b:any)=>rec(b.id).product===id&&b.data.state==='reserved').length} · تحویل تدارکات: {builds.filter((b:any)=>rec(b.id).product===id&&b.data.state==='in_transit').length}</p><details><summary>سریال‌های انبار</summary>{builds.filter((b:any)=>rec(b.id).product===id&&['finished','reserved'].includes(b.data.state)).map((b:any)=><p key={b.id}>{serial(b.id)} · {labels[b.data.state]}</p>)}</details></article>)}<h3>حواله‌های فروش</h3>{shipmentCards(sales)}</>}
 {tab==='dispatch'&&<><p className="notice">خروج هنگام تحویل فیزیکی به تدارکات ثبت می‌شود. تأیید تدارکات به معنی رسیدن به مقصد یا فعال‌شدن گارانتی نیست.</p>{!sales.length&&<p className="empty">حواله‌ای در کارتابل نیست.</p>}{shipmentCards(sales.filter((s:any)=>s.data.state!=='cancelled'))}</>}
 {tab==='parties'&&roles.sales&&<><button className="btn primary" onClick={()=>start('party',{name:'',kind:'representative',phone:'',address:'',active:true})}>تعریف گیرنده</button>{parties.map((p:any)=><article className="flow-card" key={p.id}><h3>{p.data.name} · {kinds[p.data.kind]}</h3><p>{p.data.address} · {p.data.phone} · {p.data.active?'فعال':'غیرفعال'}</p><button className="btn" onClick={()=>start('party',{...p.data,partyId:p.id,revision:p.revision})}>ویرایش</button></article>)}</>}
 </div><Dialog open={!!draft} onOpenChange={v=>{if(!v&&!busy)setDraft(null)}}><DialogContent className="modal sm:max-w-2xl"><DialogTitle>{({handoff:'ارجاع به انبار محصول نهایی',receive:'تأیید دریافت انبار',cancel_handoff:'بازگرداندن درخواست به خط',reserve:'رزرو فروش',dispatch:'خروج و تحویل تدارکات',acknowledge:'تأیید دریافت تدارکات',party:'مشخصات گیرنده',cancel_sale:'لغو رزرو'} as any)[mode]}</DialogTitle><DialogDescription>قبل از ثبت، مشخصات و سریال‌ها را بررسی کنید.</DialogDescription>{draft&&<form onSubmit={submit}><fieldset disabled={busy} style={{border:0,padding:0}}>
 {mode==='party'&&<><label className="field">نام گیرنده<input required value={draft.name} onChange={e=>change('name',e.target.value)}/></label><Pick label="نوع گیرنده" value={draft.kind} items={Object.entries(kinds)} onChange={v=>change('kind',v)}/><label className="field">تلفن<input value={draft.phone} onChange={e=>change('phone',e.target.value)}/></label><label className="field">نشانی<textarea required value={draft.address} onChange={e=>change('address',e.target.value)}/></label><label className="flow-check"><Checkbox checked={draft.active} onCheckedChange={v=>change('active',v===true)}/>فعال</label></>}
 {mode==='reserve'&&<><Pick label="محصول" value={draft.productId} items={products} onChange={v=>{change('productId',v);change('deviceIds',[])}}/><Pick label="گیرنده" value={draft.partyId} items={parties.filter((p:any)=>p.data.active).map((p:any)=>[p.id,p.data.name+' · '+kinds[p.data.kind]])} onChange={v=>change('partyId',v)}/><label className="field">تعداد<input required type="number" min={1} max={100} value={draft.count} onChange={e=>change('count',Number(e.target.value))}/></label><p className="subtle">اگر سریال مشخصی انتخاب نکنید، قدیمی‌ترین دستگاه‌های آزاد پیشنهاد و رزرو می‌شوند.</p><details><summary>انتخاب سریال مشخص (اختیاری)</summary>{builds.filter((b:any)=>b.data.state==='finished'&&rec(b.id).product===draft.productId).map((b:any)=><label className="flow-check" key={b.id}><Checkbox checked={draft.deviceIds.includes(b.id)} onCheckedChange={()=>check(b.id,draft.deviceIds,v=>change('deviceIds',v))}/>{serial(b.id)}</label>)}</details></>}
 {['handoff','receive','cancel_handoff'].includes(mode)&&<>{(mode==='handoff'?draft.deviceIds:handoffs.find((h:any)=>h.id===draft.handoffId)?.data.pending||[]).map((d:string)=><label className="flow-check" key={d}>{mode!=='handoff'&&<Checkbox checked={draft.deviceIds.includes(d)} onCheckedChange={()=>check(d,draft.deviceIds,v=>change('deviceIds',v))}/>}<span dir="ltr">{serial(d)}</span></label>)}{mode==='handoff'&&<label className="flow-check"><Checkbox checked={draft.packaged} onCheckedChange={v=>change('packaged',v===true)}/>بسته‌بندی انجام شده و برچسب سریال روی دستگاه‌ها نصب است.</label>}</>}
 {mode==='dispatch'&&<><p>مقصد: {reservedSale?.data.recipient.name} · تعداد: {reservedSale?.data.count}</p>{dispatchCandidates.map((b:any)=><label className="flow-check" key={b.id}><Checkbox checked={draft.deviceIds.includes(b.id)} onCheckedChange={()=>check(b.id,draft.deviceIds,v=>change('deviceIds',v))}/>{serial(b.id)} · {labels[b.data.state]}</label>)}<Pick label="تحویل‌گیرنده تدارکات" value={draft.carrierId} items={(data?.carriers||[]).map((m:any)=>[m.id,m.name])} onChange={v=>change('carrierId',v)}/><p className="subtle">تحویل‌گیرنده باید حساب فعال با نقش تدارکات داشته باشد.</p><label className="field">شماره رسید تحویل (اختیاری)<input value={draft.receiptReference} onChange={e=>change('receiptReference',e.target.value)}/></label><label className="field">علت تغییر سریال‌ها<textarea value={draft.reason} onChange={e=>change('reason',e.target.value)}/></label><label className="flow-check"><Checkbox checked={draft.handedOver} onCheckedChange={v=>change('handedOver',v===true)}/>دستگاه‌ها به شخص انتخاب‌شده تحویل فیزیکی شدند.</label></>}
 {mode==='cancel_sale'?<label className="field">علت لغو<textarea required value={draft.reason} onChange={e=>change('reason',e.target.value)}/></label>:!['party','dispatch'].includes(mode)&&<label className="field">توضیحات / علت تحویل جزئی<textarea value={draft.notes} onChange={e=>change('notes',e.target.value)}/></label>}
 {error&&<p className="notice error" role="alert">{error}</p>}<div className="tools" style={{marginTop:16}}><button className="btn primary" disabled={busy}>{busy?'در حال ثبت…':'تأیید و ثبت'}</button><button className="btn" type="button" onClick={()=>setDraft(null)}>انصراف</button></div></fieldset></form>}</DialogContent></Dialog></section></ProgramWorkspace>
}
