'use client';
import {IconSections,IconActions} from "./program-workspace";
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {SolarDate} from './solar-date';
import {formatDate,formatDateTime,localDay} from '@/lib/persian-date';
const titles:Record<string,string>={return_review:'برگشت برای اصلاح',cancel_amendment:'لغو اصلاح پیشنهادی',save:'ثبت / ویرایش پرونده',submit:'ارسال برای تأیید مالی',approve:'تأیید مستقل مالی',issue:'ثبت صدور / دریافت',request_extension:'درخواست تمدید',request_release:'درخواست آزادسازی',followup:'ثبت پیگیری',amend:'پیشنهاد تمدید / تغییر مبلغ',approve_amendment:'تأیید اصلاح',confirm_amendment:'ثبت اصلاح بانکی',demand:'ثبت مطالبه',collection:'ثبت وصول / پرداخت مطالبه',resolve_demand:'تعیین تکلیف مطالبه',terminate:'ثبت خاتمه تعهد',return_original:'استرداد اصل سند',release_collateral:'آزادسازی سپرده و وثیقه',close:'بستن نهایی پرونده'};
const kinds:Record<string,string>={tender:'شرکت در مناقصه',performance:'حسن انجام تعهد',advance:'پیش‌پرداخت',other:'سایر'};
export function GuaranteesPanel({demo=false,targetId}:{demo?:boolean;targetId?:string}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState(''),[query,setQuery]=useState(''),[mode,setMode]=useState(''),[form,setForm]=useState<any>({}),[operation,setOperation]=useState('');
 const load=async()=>{if(demo)return;try{const r=await fetch('/api/guarantees',{cache:'no-store'}),j:any=await r.json();if(!r.ok)throw Error(j.error);setData(j);}catch(e){setError((e as Error).message)}};
 useEffect(()=>{void load()},[demo]);useEffect(()=>{if(targetId)setSelected(targetId)},[targetId]);
 const records=data?.records||[],record=records.find((r:any)=>r.id===selected),d=record?.data,files=(data?.files||[]).filter((f:any)=>f.data.caseId===selected);
 const change=(key:string,value:any)=>setForm((f:any)=>({...f,[key]:value}));
 const start=(action:string,r=record)=>{setMode(action);setOperation(crypto.randomUUID());setError('');setForm(action==='save'?{direction:'outgoing',kind:'performance',currency:'IRR',issueDate:localDay(),actionDeadline:'',expiry:'',deposit:'0',fees:'0',alertDays:[30,15,7,1],viewerIds:[],...(r?.data||{}),notes:''}:{notes:'',...(action==='amend'?{amount:r.data.amount,expiry:r.data.expiry,actionDeadline:r.data.actionDeadline}:{}),...(action==='release_collateral'?{amount:'0'}:{})});};
 async function save(){setBusy(true);setError('');try{const body={...form,id:operation,mode,guaranteeId:record?.id,revision:record?.revision||0,confirmed:true};if(mode==='save'){if(body.linkId==='none')body.linkId='';delete body.history;delete body.requests;delete body.demands;}const r=await fetch('/api/guarantees',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j:any=await r.json();if(!r.ok)throw Error(j.error);setSelected(j.id);setMode('');await load();if(j.tasksPending)setError('پرونده ذخیره شد؛ همگام‌سازی وظایف در نوبت بعد انجام می‌شود.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function upload(file:File){setBusy(true);setError('');try{const q=new URLSearchParams({id:crypto.randomUUID(),caseId:selected,filename:file.name}),r=await fetch('/api/guarantees/files?'+q,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file}),j:any=await r.json();if(!r.ok)throw Error(j.error);await load();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const input=(key:string,label:string,required=true)=><label className="field" key={key}>{label}<input required={required} value={form[key]||''} onChange={e=>change(key,e.target.value)}/></label>;
 const select=(key:string,label:string,options:Record<string,string>)=><label className="field" key={key}>{label}<Select dir="rtl" value={form[key]||''} onValueChange={v=>change(key,v)}><SelectTrigger aria-label={label}><SelectValue placeholder="انتخاب کنید"/></SelectTrigger><SelectContent>{Object.entries(options).map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select></label>;
 const date=(key:string,label:string,required=true)=><SolarDate key={key} label={label} value={form[key]||''} required={required} onChange={v=>change(key,v)}/>;
 const proofModes=['issue','confirm_amendment','demand','collection','resolve_demand','terminate','return_original','release_collateral'];
 const actions=!d?[]:d.state==='draft'?['save','submit']:d.state==='review'?['approve','return_review']:d.state==='approved'?['issue','followup']:d.state==='terminated'?['return_original','release_collateral','resolve_demand','collection','followup','close']:d.state==='active'?['request_extension','request_release','followup',...(d.amendment?[d.amendment.approved?'confirm_amendment':'approve_amendment','cancel_amendment']:['amend']),'demand','collection','resolve_demand','terminate']:[];
 const allowed=actions.filter(a=>['return_review','cancel_amendment','approve','approve_amendment','resolve_demand','close'].includes(a)?data?.roles.manager:a.startsWith('request_')?true:data?.roles.treasury);
 return <div className="panel" dir="rtl" style={{fontSize:16}}><div className="panelhead"><h2>ضمانت‌نامه‌ها</h2><IconActions scope="guarantees-panel-actions-802f2886e7"><button className="btn" disabled={busy||demo} onClick={()=>void load()}>تازه‌سازی</button>{data?.roles.treasury&&<button className="btn primary" disabled={busy} onClick={()=>{setSelected('');start('save',null)}}>ضمانت‌نامه جدید</button>}</IconActions></div>
 {demo?<p className="empty">ثبت ضمانت‌نامه فقط در محیط شرکت فعال است.</p>:!data&&!error?<p role="status">در حال دریافت…</p>:null}
 {error&&<p role="alert" className="error">{error}</p>}
 {data&&<><p className="footnote">{data.help}</p><p>مسئولان از جایگاه‌های «خزانه دار» و «مدیر مالی» با دسترسی نوشتن مالی تعیین می‌شوند؛ عضویت را در بخش وظایف و سمت‌ها مدیریت کنید.</p>
 {data.roles.read&&(!data.owners.treasury.length||!data.owners.manager.length)&&<p role="alert">هشدار: برای جایگاه {!data.owners.treasury.length?'خزانه‌دار ':''}{!data.owners.manager.length?'مدیر مالی':''} عضو فعال با دسترسی نوشتن مالی تعیین نشده است؛ وظایف آن مرحله تا تعیین مسئول ساخته نمی‌شوند.</p>}{data.dashboard&&<div className="grid">{Object.entries(data.dashboard.currencies).map(([currency,v]:any)=><div className="card" key={currency}><strong>{currency}</strong><p>مبلغ فعال: {v.active}</p><p>سپرده مسدود: {v.deposit}</p></div>)}<div className="card">نزدیک موعد: {data.dashboard.near} · اقدام معوق: {data.dashboard.overdue} · پیگیری استرداد: {data.dashboard.release}</div></div>}
 <label className="field">جست‌وجو در شماره، بانک و طرف حساب<input value={query} onChange={e=>setQuery(e.target.value)}/></label>
 <div style={{overflowX:'auto'}}><table><thead><tr><th>شماره / بانک</th><th>جهت</th><th>مبلغ</th><th>وضعیت</th><th>مهلت اقدام</th><th>پرونده</th></tr></thead><tbody>{records.filter((r:any)=>JSON.stringify([r.data.number,r.data.bank,r.data.applicant,r.data.beneficiary]).includes(query)).map((r:any)=><tr key={r.id}><td>{r.data.number} — {r.data.bank}</td><td>{r.data.direction==='outgoing'?'صادره':'دریافتی'}</td><td>{r.data.amount?`${r.data.amount} ${r.data.currency}`:'—'}</td><td>{data.states[r.data.state]}</td><td>{formatDate(r.data.actionDeadline)}</td><td><button className="btn" onClick={()=>setSelected(r.id)}>باز کردن</button></td></tr>)}</tbody></table></div>{!records.length&&<p className="empty">پرونده‌ای در دسترس نیست.</p>}
 {d&&<section aria-label="پرونده ضمانت‌نامه"><h3>{d.number} — {d.bank}</h3><p>{data.states[d.state]} · اعتبار: {d.expiry?formatDate(d.expiry):'بدون تاریخ انقضا'} · اقدام: {formatDate(d.actionDeadline)}</p>{data.roles.read&&<><p>متقاضی: {d.applicant} · ذی‌نفع: {d.beneficiary} · شعبه: {d.branch||'—'}</p><p>قرارداد / پروژه / طرف حساب: {d.contract||'—'}</p><p>اصل سند: {d.originalLocation} · استرداد: {d.originalReturned?'انجام شده':'در انتظار'}</p><p>سپرده: {d.deposit} {d.currency} · آزادشده: {d.releasedDeposit} · کارمزد: {d.fees}</p><p>وثایق: {d.collateral||'ندارد'} · {d.collateralReleased?'آزاد شده':'تعیین تکلیف نشده'}</p>{d.nextDue&&<p>پیگیری بعدی: {d.nextAction} — {formatDate(d.nextDue)}</p>}</>}
 <IconActions scope="guarantees-panel-actions-a036d536d9">{allowed.map(a=><button className="btn" key={a} disabled={busy} onClick={()=>start(a)}>{titles[a]}</button>)}</IconActions>
 {data.roles.read&&<><IconSections scope="guarantees-panel-sections-67f0b59ade" items={[{key:"مدارک خصوصی",title:"مدارک خصوصی",content:<><h4>مدارک خصوصی</h4>{files.map((f:any)=><p key={f.id}><a href={'/api/guarantees/files?id='+encodeURIComponent(f.id)}>{f.data.filename}</a></p>)}{data.roles.treasury&&d.state!=='closed'&&<label className="field">بارگذاری مدرک<input type="file" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value=''}}/></label>}</>},{key:"مطالبات",title:"مطالبات",content:<><h4>مطالبات</h4>{d.demands?.map((x:any)=><p key={x.id}>{x.reference}: {x.amount} {d.currency} · وصول / پرداخت: {x.collected} · {x.resolved?'تعیین تکلیف شده':'باز'}</p>)}</>},{key:"تاریخچه",title:"تاریخچه",content:<><h4>تاریخچه</h4>{[...(d.history||[])].reverse().map((h:any,i:number)=><p key={i}>{formatDateTime(h.at)} · {h.name} · {titles[h.mode]}: {h.notes}</p>)}</>}]}/></>}
 <h4>درخواست‌های مرتبط</h4>{d.requests?.map((x:any)=><p key={x.id}>{titles[x.kind]}: {x.notes} — {formatDate(x.due)} · {x.resolved?'انجام شده':'باز'}</p>)}</section>}
 </>}
 <Dialog open={!!mode} onOpenChange={open=>{if(!busy&&!open)setMode('')}}><DialogContent style={{maxWidth:780,maxHeight:'90vh',overflowY:'auto'}} dir="rtl"><DialogHeader><DialogTitle>{titles[mode]}</DialogTitle><DialogDescription>{record?`${d.number} — ${data.states[d.state]} · نسخه ${record.revision}`:'ثبت پرونده جدید'}؛ با تأیید، این عملیات در تاریخچه ثبت می‌شود.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();void save()}}>
 <div className="grid">{mode==='save'&&<>{select('direction','جهت',{outgoing:'صادره',incoming:'دریافتی'})}{select('kind','نوع',kinds)}{input('number','شماره ضمانت‌نامه')}{input('bank','بانک')}{input('branch','شعبه',false)}{input('applicant','متقاضی')}{input('beneficiary','ذی‌نفع')}{select('currency','ارز',Object.fromEntries(['IRR','USD','EUR','AED','CNY','GBP','TRY'].map(v=>[v,v])))}{input('amount','مبلغ')}{input('deposit','سپرده نقدی؛ به همان ارز')}{input('fees','کارمزد؛ به همان ارز')}{date('issueDate','تاریخ صدور')}{date('expiry','انقضا',false)}{date('actionDeadline','آخرین مهلت اقدام')}{select('linkId','اتصال به پروژه / سفارش / طرف حساب',Object.fromEntries([['none','بدون اتصال'],...(data?.links||[]).map((l:any)=>[l.id,l.title])]))}{input('contract','شماره قرارداد یا توضیح ارتباط',false)}{input('originalLocation','محل نگهداری اصل سند')}{input('collateral','شرح وثایق',false)}<label className="field">بازه هشدار؛ روزهای پیش از موعد<input value={(form.alertDays||[]).join(',')} onChange={e=>change('alertDays',e.target.value.split(',').map(Number))}/></label><fieldset className="field"><legend>کاربران مرتبط با قرارداد / پروژه</legend>{(data?.members||[]).map((m:any)=><label key={m.id}><Checkbox checked={(form.viewerIds||[]).includes(m.id)} onCheckedChange={checked=>change('viewerIds',checked===true?[...(form.viewerIds||[]),m.id]:(form.viewerIds||[]).filter((id:string)=>id!==m.id))}/>{m.name} — {m.unit}</label>)}</fieldset></>}
 {mode==='amend'&&<>{input('amount','مبلغ جدید')}{date('expiry','انقضای جدید',false)}{date('actionDeadline','مهلت اقدام جدید')}</>}
 {['request_extension','request_release','followup'].includes(mode)&&date('due','موعد پیگیری')}{mode==='followup'&&input('nextAction','اقدام بعدی')}
 {['demand','collection','release_collateral'].includes(mode)&&input('amount','مبلغ به ارز پرونده')}{['demand','collection'].includes(mode)&&<>{date('day','تاریخ واقعی')}{input('reference','شماره مرجع واقعی')}</>}
 {['collection','resolve_demand'].includes(mode)&&select('demandId','مطالبه باز',Object.fromEntries((d?.demands||[]).filter((x:any)=>!x.resolved).map((x:any)=>[x.id,`${x.reference} — ${x.amount}`])))}
 {proofModes.includes(mode)&&select('fileId','مدرک همین پرونده',Object.fromEntries(files.map((f:any)=>[f.id,f.data.filename])))}
 {mode==='release_collateral'&&<label><Checkbox checked={form.allCollateralReleased===true} onCheckedChange={checked=>change('allCollateralReleased',checked===true)}/> تمام وثایق غیرنقدی آزاد شده‌اند</label>}
 </div><label className="field">شرح و مستند تصمیم<textarea required maxLength={4000} value={form.notes||''} onChange={e=>change('notes',e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<div className="tools"><button type="button" className="btn" disabled={busy} onClick={()=>setMode('')}>انصراف</button><button className="btn primary" disabled={busy}>{busy?'در حال ثبت…':'تأیید و ثبت'}</button></div></form></DialogContent></Dialog>
 </div>;
}
