'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {SolarDate} from './solar-date';
import {formatDate,formatDateTime,localDay} from '@/lib/persian-date';
const money=(s:any)=>{try{return BigInt(s||0).toLocaleString('fa-IR')+' ریال'}catch{return '—'}};
function Pick({label,value,items,onChange}:{label:string;value:string;items:{id:string;name:string}[];onChange:(v:string)=>void}){return <label className="field"><span>{label}</span><Select dir="rtl" value={value||'__none'} onValueChange={v=>onChange(v==='__none'?'':v)}><SelectTrigger><SelectValue placeholder="انتخاب کنید"/></SelectTrigger><SelectContent><SelectItem value="__none">انتخاب کنید</SelectItem>{items.map(i=><SelectItem value={i.id} key={i.id}>{i.name}</SelectItem>)}</SelectContent></Select></label>}
export function HospitalPanel(){
 const [data,setData]=useState<any>(null),[center,setCenter]=useState(''),[asset,setAsset]=useState(''),[tab,setTab]=useState('devices'),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[draft,setDraft]=useState<any>(null),[question,setQuestion]=useState(''),[answer,setAnswer]=useState<any>(null),[accounts,setAccounts]=useState<any[]>([]);
 async function load(){setError('');try{const r=await fetch('/api/hospital',{cache:'no-store'}),d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);setCenter(c=>d.centers.some((v:any)=>v.id===c)?c:d.centers[0]?.id||'');if(d.roles.manager){const a=await fetch('/api/hospital/accounts'),v:any=await a.json();if(a.ok)setAccounts(v.accounts||[]);}}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load()},[]);
 const rows=data?.rows||[],centers=data?.centers||[],c=centers.find((v:any)=>v.id===center),assets=rows.filter((r:any)=>r.type==='hospital_asset'&&r.data.centerId===center),selected=assets.find((r:any)=>r.id===asset),own=data?.own,roles=data?.roles||{};
 const scoped=(type:string)=>rows.filter((r:any)=>r.type===type&&r.data.centerId===center&&(!asset||r.data.assetId===asset)),jobs=scoped('hospital_job'),invoices=rows.filter((r:any)=>r.type==='hospital_invoice'&&r.data.centerId===center),payments=rows.filter((r:any)=>r.type==='hospital_payment'&&r.data.centerId===center),balance=data?.balances.find((v:any)=>v.centerId===center);
 function start(mode:string,extra:any={}){setError('');setDraft({id:crypto.randomUUID(),mode,centerId:center,assetId:asset,notes:'',day:localDay(),due:localDay(),installedOn:localDay(),active:true,kind:'fault',urgency:'normal',contact:'',lines:[{kind:'labor',label:'',quantity:1,unitPrice:'0',partCode:''}],validUntil:localDay(),approved:true,rating:5,state:'published',fields:[{key:'f1',label:'',type:'result',unit:'',min:'',max:'',required:true}],...extra});}
 const change=(k:string,v:any)=>setDraft((d:any)=>({...d,[k]:v}));
 function input(key:string,label:string,type='text',required=true){return <label className={'field '+(type==='textarea'?'wide':'')}><span>{label}</span>{type==='textarea'?<textarea required={required} rows={4} value={draft[key]||''} onChange={e=>change(key,e.target.value)}/>:<input type={type} required={required} value={draft[key]??''} onChange={e=>change(key,e.target.value)} autoComplete={type==='password'?'new-password':'off'}/>}</label>}
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const endpoint=draft.mode==='account'?'/api/hospital/accounts':'/api/hospital',body=draft.mode==='account'?{id:draft.id,centerId,revision:c.revision,name:draft.name,username:draft.username,password:draft.password,confirmed:true}:{...draft,confirmed:true};const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d:any=await r.json();if(!r.ok)throw Error(d.error);setDraft(null);setMessage(d.followupPending?'ثبت شد؛ اعلان‌ها نیازمند تازه‌سازی کارتابل‌اند.':'ثبت شد.');await load();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const centerId=center;
 async function upload(file?:File){if(!file||busy)return;setBusy(true);setError('');try{const purpose=draft.mode==='manual'?'manual':'payment',q=new URLSearchParams({id:crypto.randomUUID(),center,asset:draft.assetId||'',purpose,filename:file.name}),r=await fetch('/api/hospital/files?'+q,{method:'POST',headers:{'Content-Type':file.type},body:file}),d:any=await r.json();if(!r.ok)throw Error(d.error);change('fileId',d.id);change('fileName',file.name);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function ask(){if(!asset||!question.trim()||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/hospital/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),assetId:asset,question,confirmed:true})}),d:any=await r.json();if(!r.ok)throw Error(d.error);setAnswer(d);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!data)return <div className="panel">{error?<p role="alert">{error}<button className="btn" onClick={load}>تلاش مجدد</button></p>:<p>در حال دریافت پنل بیمارستانی…</p>}</div>;
 const label:any={contacts:'افراد تماس مرکز',center:'تعریف مرکز',asset:'شناسنامه دستگاه مرکز',request:'درخواست خدمات / اعلام خرابی',quote:'پیش‌فاکتور خدمات و قطعات',consent:'پاسخ مرکز به پیش‌فاکتور',schedule:'برنامه‌ریزی اعزام',dispatch:'ثبت اعزام',complete:'گزارش کار تکنسین',confirm:'تأیید عملکرد خدمات',invoice:'ثبت فاکتور مرکز',payment:'اعلام پرداخت',payment_review:'بررسی پرداخت',manual:'انتشار راهنمای دستگاه',form:'انتشار فرم کنترلی',form_submit:'تکمیل فرم کنترلی',check_review:'بررسی فرم نامنطبق',history:'ثبت سابقه خدمات قبلی',account:'حساب مسئول مرکز'};
 return <div className="panel"><div className="tools"><h2>مرکز و دستگاه‌های بیمارستانی</h2><button className="btn" onClick={load} disabled={busy}>تازه‌سازی</button>{roles.manager&&<button className="btn primary" onClick={()=>start('center',{centerId:'',profileId:''})}>مرکز جدید</button>}</div>
 {!centers.length?<p className="notice">هنوز مرکزی تعریف نشده است. مدیر خدمات ابتدا مرکز و دستگاه‌های آن را ثبت می‌کند.</p>:<><div className="formgrid"><Pick label="مرکز" value={center} items={centers.map((v:any)=>({id:v.id,name:v.data.name}))} onChange={v=>{setCenter(v);setAsset('');setAnswer(null)}}/><Pick label="دستگاه / محدوده نمایش" value={asset} items={assets.map((v:any)=>({id:v.id,name:v.data.name+' · '+v.data.serial}))} onChange={v=>{setAsset(v);setAnswer(null)}}/></div>{c&&<p className="subtle">{c.data.address} · {c.data.phone}</p>}
 {roles.manager&&c&&<div className="tools"><button className="btn" onClick={()=>start('asset')}>افزودن دستگاه مرکز</button><button className="btn" onClick={()=>start('account')}>حساب مسئول مرکز</button><button className="btn" onClick={()=>start('center',{...c.data,centerId:c.id,revision:c.revision})}>تنظیمات مرکز و دستیار</button></div>}
 <section className="flow-card"><div className="tools"><h3>افراد تماس بیمارستان</h3>{roles.manager&&c&&<button className="btn" onClick={()=>start('contacts',{centerId:c.id,revision:c.revision,contacts:c.data.contacts||[]})}>مدیریت افراد تماس</button>}</div>{(c?.data.contacts||[]).filter((v:any)=>v.active&&(!asset||!v.assetId||v.assetId===asset)).map((v:any)=><article className="flow-card" key={v.id}><strong>{v.name} · {v.role}</strong><p>{v.assetId?assets.find((a:any)=>a.id===v.assetId)?.data.name:'تمام دستگاه‌های مرکز'}</p><div className="tools">{v.mobile&&<a className="btn" href={'tel:'+v.mobile.replace(/[^+0-9]/g,'')}>همراه: <bdi>{v.mobile}</bdi></a>}{v.landline&&<a className="btn" href={'tel:'+v.landline.replace(/[^+0-9]/g,'')}>ثابت: <bdi>{v.landline}</bdi></a>}{v.extension&&<span>داخلی: <bdi>{v.extension}</bdi></span>}</div>{v.notes&&<p>{v.notes}</p>}</article>)}{!(c?.data.contacts||[]).some((v:any)=>v.active&&(!asset||!v.assetId||v.assetId===asset))&&<p>فرد تماس فعالی برای این محدوده ثبت نشده است.</p>}</section>
 <div className="stats" style={{marginTop:18}}><div className="stat"><div><p>دستگاه‌های مرکز</p><strong>{assets.length.toLocaleString('fa-IR')}</strong></div></div><div className="stat"><div><p>درخواست‌های باز</p><strong>{jobs.filter((j:any)=>j.data.state!=='confirmed').length.toLocaleString('fa-IR')}</strong></div></div><div className="stat"><div><p>مانده تأییدشده</p><strong style={{fontSize:20}}>{money(balance?.balance)}</strong></div></div></div>
 <Tabs value={tab} onValueChange={setTab} dir="rtl"><TabsList className="tools" style={{height:'auto',flexWrap:'wrap',margin:'18px 0'}}>{[['devices','شناسنامه و سوابق'],['jobs','درخواست و خدمات'],['account','حساب و پرداخت'],['manuals','راهنما و دستیار'],['forms','فرم‌های کنترلی']].map(([id,title])=><TabsTrigger value={id} key={id}>{title}</TabsTrigger>)}</TabsList>
 <TabsContent value="devices">{(selected?[selected]:assets).map((a:any)=><article className="flow-card" key={a.id}><h3>{a.data.name}</h3><div className="detailgrid">{[['سریال',a.data.serial],['مدل',a.data.model],['نسخه طراحی',a.data.design||'—'],['نسخه نرم‌افزار',a.data.firmware||'—'],['گارانتی (ماه)',a.data.warrantyMonths||'—'],['بخش',a.data.department],['محل نصب',a.data.location],['تاریخ نصب',formatDate(a.data.installedOn)]].map(([k,v])=><div className="kv" key={k}><p>{k}</p><strong>{v}</strong></div>)}</div><p>{a.data.notes}</p><div className="tools"><button className="btn primary" onClick={()=>{setAsset(a.id);start('request',{assetId:a.id})}}>اعلام خرابی / درخواست سرویس</button><button className="btn" onClick={()=>{setAsset(a.id);setTab('manuals')}}>راهنمای این دستگاه</button>{roles.manager&&<><button className="btn" onClick={()=>start('asset',{...a.data,assetId:a.id,revision:a.revision})}>ویرایش پروفایل</button><button className="btn" onClick={()=>start('history',{assetId:a.id})}>سابقه خدمات قبلی</button></>}</div>{rows.filter((h:any)=>h.type==='hospital_history'&&h.data.assetId===a.id).map((h:any)=><p key={h.id}>{formatDate(h.data.day)} · {h.data.title} — {h.data.notes} ({h.data.reference})</p>)}{rows.filter((j:any)=>j.type==='hospital_job'&&j.data.assetId===a.id).map((j:any)=><p key={j.id}>{formatDateTime(j.created)} · {j.data.description} — {data.states[j.data.state]}{j.data.report&&' · '+j.data.report.work}</p>)}</article>)}</TabsContent>
 <TabsContent value="jobs"><button className="btn primary" disabled={!asset} onClick={()=>start('request')}>درخواست جدید برای دستگاه انتخاب‌شده</button>{!asset&&<p className="subtle">برای درخواست جدید، دستگاه را انتخاب کنید.</p>}{jobs.map((j:any)=>{const d=j.data;return <article className="flow-card" key={j.id}><h3>{d.serial} · {data.states[d.state]}</h3><p>{d.description}</p><p className="subtle">{d.contact} · {d.urgency==='stopped'?'دستگاه متوقف':d.urgency==='urgent'?'فوری':'عادی'} · {formatDateTime(j.created)}</p>{d.quote&&<details open><summary>پیش‌فاکتور نسخه {d.quoteVersion} · {money(d.quote.total)}</summary><p>معتبر تا {formatDate(d.quote.validUntil)}</p>{d.quote.lines.map((l:any,i:number)=><p key={i}>{l.label} · {l.quantity} × {money(l.unitPrice)}</p>)}<p>{d.quote.notes}</p>{d.consent&&<p>پاسخ مرکز: {d.consent.approved?'تأیید':'رد'} · {d.consent.name} · {d.consent.notes}</p>}</details>}{d.schedule&&<p>تاریخ اعزام: {formatDate(d.schedule.day)} · {d.schedule.notes}</p>}{d.report&&<div className="notice"><strong>گزارش تکنسین {d.report.name}</strong><p style={{whiteSpace:'pre-wrap'}}>{d.report.work}</p><p>قطعات: {d.report.parts||'گزارش نشده'}</p><p>نتیجه آزمون: {d.report.test}</p></div>}{d.confirmation&&<p>نظر مرکز: {d.confirmation.notes} · امتیاز {d.confirmation.rating}</p>}
 <div className="tools">{roles.tech&&!['dispatched','completed','confirmed'].includes(d.state)&&!invoices.some((v:any)=>v.data.jobId===j.id)&&<button className="btn" onClick={()=>start('quote',{jobId:j.id,revision:j.revision,lines:d.quote?.lines||[{kind:'labor',label:'',quantity:1,unitPrice:'0',partCode:''}]})}>تنظیم / اصلاح پیش‌فاکتور</button>}{own&&d.state==='quoted'&&<button className="btn primary" onClick={()=>start('consent',{jobId:j.id,revision:j.revision,quoteVersion:d.quoteVersion,quoteTotal:d.quote.total})}>تأیید یا رد پیش‌فاکتور</button>}{roles.manager&&['accepted','scheduled'].includes(d.state)&&<button className="btn" onClick={()=>start('schedule',{jobId:j.id,revision:j.revision})}>تعیین تکنسین و موعد</button>}{roles.tech&&d.state==='scheduled'&&<button className="btn" onClick={()=>start('dispatch',{jobId:j.id,revision:j.revision})}>ثبت اعزام</button>}{roles.tech&&d.state==='dispatched'&&<button className="btn" onClick={()=>start('complete',{jobId:j.id,revision:j.revision})}>ثبت گزارش کار</button>}{own&&['completed','disputed'].includes(d.state)&&<button className="btn primary" onClick={()=>start('confirm',{jobId:j.id,revision:j.revision})}>تأیید عملکرد / اعلام مشکل</button>}{roles.finance&&d.consent?.approved&&!invoices.some((v:any)=>v.data.jobId===j.id)&&<button className="btn" onClick={()=>start('invoice',{jobId:j.id,revision:j.revision})}>ثبت فاکتور</button>}</div></article>})}</TabsContent>
 <TabsContent value="account"><p className="notice">پیش‌فاکتور بدهی ایجاد نمی‌کند؛ مانده از فاکتورهای ثبت‌شده و پرداخت‌های تأییدشده محاسبه می‌شود. پرداخت منتظر بررسی، از حساب کسر نمی‌شود.</p><p>جمع فاکتور: {money(balance?.debit)} · پرداخت تأییدشده: {money(balance?.credit)}</p>{balance?.invoices.map((i:any)=><article className="flow-card" key={i.id}><h3>{i.data.reference}</h3><p>{money(i.data.amount)} · سررسید {formatDate(i.data.due)} · مانده این فاکتور {money(i.remaining)}</p>{own&&<button className="btn" onClick={()=>start('payment',{invoiceId:i.id,amount:i.remaining})}>ثبت پرداخت و رسید</button>}</article>)}{payments.map((p:any)=><article className="flow-card" key={p.id}><strong>{money(p.data.amount)} — {({pending:'منتظر بررسی مالی',approved:'تأییدشده',rejected:'ردشده'} as any)[p.data.state]}</strong><p>{p.data.reference} · {formatDate(p.data.day)}</p><a className="btn" href={'/api/hospital/files?id='+encodeURIComponent(p.data.fileId)} target="_blank" rel="noreferrer">دریافت رسید</a>{roles.finance&&p.data.state==='pending'&&<button className="btn" onClick={()=>start('payment_review',{paymentId:p.id,revision:p.revision})}>بررسی رسید</button>}{p.data.review&&<p>{p.data.review.notes}</p>}</article>)}</TabsContent>
 <TabsContent value="manuals">{!asset?<p>ابتدا دستگاه را انتخاب کنید.</p>:<>{roles.manager&&<button className="btn" onClick={()=>start('manual')}>راهنمای جدید</button>}{scoped('hospital_manual').map((m:any)=><article className="flow-card" key={m.id}><h3>{m.data.title} · نسخه {m.data.version}</h3><p className="subtle">{m.data.reference} · {m.data.state==='published'?'منتشرشده':m.data.state==='draft'?'پیش‌نویس':'نسخه قبلی'}</p><p style={{whiteSpace:'pre-wrap'}}>{m.data.body}</p>{m.data.fileId&&<a className="btn" href={'/api/hospital/files?id='+m.data.fileId} target="_blank" rel="noreferrer">دریافت فایل راهنما</a>}{roles.manager&&m.data.state!=='superseded'&&<button className="btn" onClick={()=>start('manual',{...m.data,previousId:m.id,revision:m.revision})}>نسخه جدید / انتشار</button>}</article>)}<section className="flow-card"><h3>دستیار راهنمای همین دستگاه</h3><p>پاسخ از متن راهنمای تأییدشده انتخاب می‌شود. سؤال و راهنما به مدل فعال مرکز ارسال می‌شود؛ اطلاعات بیمار وارد نکنید.</p><label className="field">سؤال شما<textarea value={question} maxLength={3000} onChange={e=>setQuestion(e.target.value)}/></label><button className="btn primary" disabled={busy||!question.trim()} onClick={ask}>{busy?'در حال بررسی…':'ارسال سؤال به دستیار'}</button>{answer&&<div><p style={{whiteSpace:'pre-wrap'}}>{answer.answer}</p>{answer.sources.map((s:any)=><p className="subtle" key={s.id}>منبع: {s.title}، نسخه {s.version} · {s.reference}</p>)}</div>}</section></>}</TabsContent>
 <TabsContent value="forms">{!asset?<p>ابتدا دستگاه را انتخاب کنید.</p>:<>{roles.manager&&<button className="btn" onClick={()=>start('form')}>فرم کنترلی جدید</button>}{scoped('hospital_form').map((f:any)=><article className="flow-card" key={f.id}><h3>{f.data.title} · نسخه {f.data.version}</h3><p>{f.data.reference} · {f.data.state==='published'?'منتشرشده':'نسخه غیرجاری'}</p>{own&&f.data.state==='published'&&<button className="btn primary" onClick={()=>start('form_submit',{formId:f.id,revision:f.revision,fields:f.data.fields,values:{}})}>تکمیل فرم</button>}{roles.manager&&f.data.state!=='superseded'&&<button className="btn" onClick={()=>start('form',{...f.data,previousId:f.id,revision:f.revision})}>نسخه جدید فرم</button>}</article>)}{scoped('hospital_check').map((r:any)=><article className="flow-card" key={r.id}><h3>{r.data.title} · نسخه {r.data.formVersion}</h3><p>{formatDateTime(r.created)} · {r.data.name} · {r.data.failed?'نیازمند بررسی خدمات':'مطابق معیارهای فرم'}</p>{r.data.fields.map((f:any)=><p key={f.key}>{f.label}: {r.data.values[f.key]==='pass'?'تأیید':r.data.values[f.key]==='fail'?'مردود':r.data.values[f.key]}</p>)}<p>{r.data.notes}</p>{r.data.review?<p>بررسی خدمات: {r.data.review.notes}</p>:roles.manager&&r.data.failed&&<button className="btn" onClick={()=>start('check_review',{checkId:r.id,revision:r.revision})}>ثبت بررسی و اقدام</button>}</article>)}</>}</TabsContent>
 </Tabs>{roles.manager&&accounts.filter(a=>a.centerId===center).length>0&&<details><summary>حساب‌های مسئولان این مرکز</summary>{accounts.filter(a=>a.centerId===center).map(a=><p key={a.id}>{a.name} · {a.username} · {a.status==='active'?'فعال':'غیرفعال'}</p>)}</details>}</>}
 {message&&<p className="notice" role="status">{message}</p>}{error&&!draft&&<p className="notice error" role="alert">{error}</p>}
 <Dialog open={!!draft} onOpenChange={v=>{if(!v&&!busy)setDraft(null)}}><DialogContent className="modal sm:max-w-3xl"><DialogTitle>{label[draft?.mode]}</DialogTitle><DialogDescription>ثبت با حساب شما و نگهداری سابقه انجام می‌شود. مبالغ ریال‌اند.</DialogDescription>{draft&&<form onSubmit={save}><div className="formgrid">
 {draft.mode==='contacts'&&<div className="wide"><p>افراد عمومی برای همه دستگاه‌ها نمایش داده می‌شوند. ثبت تماس، حساب ورود یا مجوز ایجاد نمی‌کند.</p>{draft.contacts.map((v:any,i:number)=><div className="flow-card formgrid" key={v.id}>{[['name','نام و نام خانوادگی'],['role','سمت / واحد'],['mobile','شماره همراه'],['landline','تلفن ثابت'],['extension','داخلی'],['notes','زمان مناسب تماس / توضیحات']].map(([key,title])=><label className="field" key={key}>{title}<input required={['name','role'].includes(key)} value={v[key]||''} onChange={e=>change('contacts',draft.contacts.map((x:any,n:number)=>n===i?{...x,[key]:e.target.value}:x))}/></label>)}<Pick label="دستگاه مرتبط (خالی: تمام مرکز)" value={v.assetId||''} items={assets.map((a:any)=>({id:a.id,name:a.data.name+' · '+a.data.serial}))} onChange={val=>change('contacts',draft.contacts.map((x:any,n:number)=>n===i?{...x,assetId:val}:x))}/><label className="field"><span>تماس فعال</span><input type="checkbox" checked={v.active} onChange={e=>change('contacts',draft.contacts.map((x:any,n:number)=>n===i?{...x,active:e.target.checked}:x))}/></label><button type="button" className="btn" onClick={()=>change('contacts',draft.contacts.filter((_:any,n:number)=>n!==i))}>حذف فرد از فهرست</button></div>)}<button type="button" className="btn" disabled={draft.contacts.length>=50} onClick={()=>change('contacts',[...draft.contacts,{id:crypto.randomUUID(),name:'',role:'',mobile:'',landline:'',extension:'',assetId:'',active:true,notes:''}])}>افزودن فرد تماس</button></div>}
 {draft.mode==='center'&&<>{input('name','نام مرکز')}{input('phone','شماره تماس')}{input('address','نشانی','textarea')}<Pick label="مدل دستیار مرکز (اختیاری)" value={draft.profileId||''} items={data.profiles||[]} onChange={v=>change('profileId',v)}/><Pick label="وضعیت مرکز" value={draft.active?'yes':'no'} items={[{id:'yes',name:'فعال'},{id:'no',name:'غیرفعال'}]} onChange={v=>change('active',v==='yes')}/></>}
 {draft.mode==='asset'&&<><Pick label="دستگاه ثبت‌شده" value={draft.deviceId||''} items={data.devices.map((d:any)=>({id:d.id,name:d.code+' · '+d.model}))} onChange={v=>change('deviceId',v)}/>{input('name','نام دستگاه در مرکز')}{input('department','بخش مرکز')}{input('location','محل نصب')}<SolarDate label="تاریخ نصب" value={draft.installedOn} onChange={v=>change('installedOn',v)}/>{input('notes','توضیحات','textarea',false)}</>}
 {draft.mode==='request'&&<><Pick label="نوع درخواست" value={draft.kind} items={[{id:'fault',name:'اعلام خرابی'},{id:'service',name:'درخواست سرویس'}]} onChange={v=>change('kind',v)}/><Pick label="وضعیت دستگاه" value={draft.urgency} items={[{id:'normal',name:'عادی'},{id:'urgent',name:'فوری'},{id:'stopped',name:'متوقف'}]} onChange={v=>change('urgency',v)}/>{input('contact','مسئول تماس و شماره')}{input('description','شرح درخواست / خرابی','textarea')}</>}
 {draft.mode==='quote'&&<><div className="wide">{draft.lines.map((l:any,i:number)=><div className="flow-card formgrid" key={i}><Pick label="نوع ردیف" value={l.kind} items={[{id:'labor',name:'خدمت'},{id:'part',name:'قطعه'},{id:'travel',name:'ایاب و ذهاب'}]} onChange={v=>change('lines',draft.lines.map((x:any,n:number)=>n===i?{...x,kind:v}:x))}/>{[['label','شرح'],['quantity','تعداد'],['unitPrice','قیمت واحد (ریال)'],...(l.kind==='part'?[['partCode','کد ماده اولیه']]:[])].map(([key,title])=><label className="field" key={key}>{title}<input required value={l[key]} type={key==='quantity'?'number':'text'} onChange={e=>change('lines',draft.lines.map((x:any,n:number)=>n===i?{...x,[key]:key==='quantity'?Number(e.target.value):e.target.value}:x))}/></label>)}{draft.lines.length>1&&<button type="button" className="btn" onClick={()=>change('lines',draft.lines.filter((_:any,n:number)=>n!==i))}>حذف ردیف</button>}</div>)}<button type="button" className="btn" onClick={()=>change('lines',[...draft.lines,{kind:'labor',label:'',quantity:1,unitPrice:'0',partCode:''}])}>افزودن ردیف</button></div><SolarDate label="اعتبار پیش‌فاکتور" value={draft.validUntil} onChange={v=>change('validUntil',v)}/>{input('notes','شرح برآورد و شرایط','textarea')}</>}
 {['consent','confirm','payment_review'].includes(draft.mode)&&<><Pick label={draft.mode==='confirm'?'آیا عملکرد خدمات را تأیید می‌کنید؟':'نتیجه بررسی'} value={draft.approved?'yes':'no'} items={[{id:'yes',name:'تأیید'},{id:'no',name:'رد / اعلام مشکل'}]} onChange={v=>change('approved',v==='yes')}/>{draft.mode==='consent'&&<p>نسخه {draft.quoteVersion} — مبلغ {money(draft.quoteTotal)}</p>}{draft.mode==='confirm'&&<Pick label="امتیاز عملکرد" value={String(draft.rating)} items={[1,2,3,4,5].map(n=>({id:String(n),name:String(n)}))} onChange={v=>change('rating',Number(v))}/ >}{input('notes','توضیح نتیجه','textarea')}</>}
 {draft.mode==='schedule'&&<><Pick label="تکنسین بیمارستانی" value={draft.technicianId||''} items={data.staff} onChange={v=>change('technicianId',v)}/><SolarDate label="تاریخ اعزام" value={draft.day} onChange={v=>change('day',v)}/>{input('notes','هماهنگی اعزام و قطعات مورد نیاز','textarea')}</>}
 {['dispatch','check_review'].includes(draft.mode)&&input('notes',draft.mode==='dispatch'?'شرح اعزام و اقلام همراه (ثبت این شرح حواله انبار نیست)':'نتیجه بررسی و اقدام پیگیری','textarea')}
 {draft.mode==='complete'&&<>{input('work','خدمات انجام‌شده','textarea')}{input('parts','قطعات مصرف‌شده / تعویض‌شده','textarea',false)}{input('test','شرح آزمون عملکرد و نتیجه واقعی','textarea')}</>}
 {draft.mode==='invoice'&&<>{input('reference','شماره فاکتور')}<SolarDate label="سررسید" value={draft.due} onChange={v=>change('due',v)}/></>}
 {draft.mode==='payment'&&<>{input('amount','مبلغ پرداخت (ریال)')}{input('reference','شماره پیگیری بانک')}<SolarDate label="تاریخ پرداخت" value={draft.day} onChange={v=>change('day',v)}/>{input('notes','توضیحات','textarea',false)}</>}
 {['manual','form','history'].includes(draft.mode)&&<>{input('title','عنوان')}{input('reference','مرجع سند / دستورالعمل')}{draft.mode!=='history'&&<Pick label="وضعیت" value={draft.state} items={[{id:'draft',name:'پیش‌نویس'},{id:'published',name:'تأیید و انتشار برای مرکز'}]} onChange={v=>change('state',v)}/>}</>}
 {draft.mode==='manual'&&input('body','متن تأییدشده راهنمای کاربر (منبع پاسخ دستیار)','textarea')}
 {draft.mode==='history'&&<><SolarDate label="تاریخ خدمات قبلی" value={draft.day} onChange={v=>change('day',v)}/>{input('notes','شرح خدمات قابل نمایش به مرکز','textarea')}</>}
 {['manual','payment'].includes(draft.mode)&&<label className="field wide">{draft.mode==='payment'?'رسید پرداخت الزامی':'فایل راهنما اختیاری'} — PDF یا عکس تا ۱۰ مگابایت<input type="file" accept="application/pdf,image/png,image/jpeg" disabled={busy} onChange={e=>upload(e.target.files?.[0])}/>{draft.fileId&&<span>فایل بارگذاری شد: {draft.fileName||draft.fileId}</span>}</label>}
 {draft.mode==='form'&&<div className="wide">{draft.fields.map((f:any,i:number)=><div className="flow-card formgrid" key={i}><label className="field">عنوان معیار<input required value={f.label} onChange={e=>change('fields',draft.fields.map((x:any,n:number)=>n===i?{...x,label:e.target.value}:x))}/></label><Pick label="نوع پاسخ" value={f.type} items={[{id:'result',name:'تأیید / مردود'},{id:'number',name:'اندازه‌گیری عددی'},{id:'text',name:'متن'}]} onChange={v=>change('fields',draft.fields.map((x:any,n:number)=>n===i?{...x,type:v}:x))}/>{f.type==='number'&&[['unit','واحد'],['min','حد پذیرش پایین'],['max','حد پذیرش بالا']].map(([key,title])=><label className="field" key={key}>{title}<input value={f[key]} onChange={e=>change('fields',draft.fields.map((x:any,n:number)=>n===i?{...x,[key]:e.target.value}:x))}/></label>)}</div>)}<button className="btn" type="button" onClick={()=>change('fields',[...draft.fields,{key:'f'+(draft.fields.length+1),label:'',type:'result',unit:'',min:'',max:'',required:true}])}>افزودن معیار</button></div>}
 {draft.mode==='form_submit'&&<>{draft.fields.map((f:any)=>f.type==='result'?<Pick key={f.key} label={f.label} value={draft.values[f.key]||''} items={[{id:'pass',name:'تأیید'},{id:'fail',name:'مردود'}]} onChange={v=>change('values',{...draft.values,[f.key]:v})}/>:<label className="field" key={f.key}>{f.label} {f.unit}<input required={f.required} type={f.type==='number'?'number':'text'} step="any" value={draft.values[f.key]||''} onChange={e=>change('values',{...draft.values,[f.key]:e.target.value})}/></label>)}{input('notes','توضیحات مشاهده','textarea',false)}</>}
 {draft.mode==='account'&&<>{input('name','نام مسئول مرکز')}{input('username','نام کاربری لاتین')}{input('password','رمز اولیه امن','password')}<p className="subtle wide">این حساب فقط دستگاه‌ها و پرونده‌های همین مرکز را می‌بیند. رمز را خارج از گفتگو، مستقیم به مسئول مرکز تحویل دهید.</p></>}</div>{error&&<p className="notice error" role="alert">{error}</p>}<div className="tools" style={{marginTop:18}}><button className="btn primary" disabled={busy||draft.mode==='payment'&&!draft.fileId}>{busy?'در حال ثبت…':'تأیید و ثبت'}</button><button type="button" className="btn" disabled={busy} onClick={()=>setDraft(null)}>انصراف</button></div></form>}</DialogContent></Dialog>
 </div>;
}
