'use client';
import {IconActions,IconDisclosure} from "./program-workspace";
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {SolarDate} from './solar-date';
import {formatDate,formatDateTime,localDay} from '@/lib/persian-date';
const cash=(s:any)=>{try{return BigInt(s||0).toLocaleString('fa-IR')+' ریال'}catch{return '—'}};
const initialGroups=[{id:'food',name:'غذا در روز',limit:''},{id:'transport',name:'رفت‌وآمد در روز',limit:''},{id:'lodging',name:'اقامت در روز',limit:''}];
const initialCategories=[{id:'breakfast',name:'صبحانه',groupId:'food'},{id:'lunch',name:'ناهار',groupId:'food'},{id:'dinner',name:'شام',groupId:'food'},{id:'transport',name:'رفت‌وآمد',groupId:'transport'},{id:'lodging',name:'اقامت',groupId:'lodging'}];
function Pick({label,value,onChange,items}:{label:string;value:string;onChange:(s:string)=>void;items:any[]}){return <label className="field"><span>{label}</span><select required value={value||''} onChange={e=>onChange(e.target.value)}><option value="">انتخاب کنید</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label>}
export function HospitalExpensesPanel(){
 const [data,setData]=useState<any>(null),[draft,setDraft]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[filter,setFilter]=useState('open');
 async function load(){try{const r=await fetch('/api/hospital/expenses',{cache:'no-store'}),v:any=await r.json();if(!r.ok)throw Error(v.error);setData(v);}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load()},[]);
 const change=(k:string,v:any)=>setDraft((d:any)=>({...d,[k]:v}));
 const start=(mode:string,extra:any={})=>{setError('');setNotice('');setDraft({id:crypto.randomUUID(),mode,day:localDay(),notes:'',explanation:'',fileIds:[],files:[],approved:true,...extra});};
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/hospital/expenses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,confirmed:true})}),v:any=await r.json();if(!r.ok)throw Error(v.error);setDraft(null);setNotice(v.followupPending?'ثبت شد؛ اعلان کارتابل هنوز نیاز به همگام‌سازی دارد.':'ثبت شد.');await load();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function upload(file?:File){if(!file||busy)return;if(!draft.jobId){setError('ابتدا مأموریت را انتخاب کنید.');return;}setBusy(true);setError('');try{const q=new URLSearchParams({id:crypto.randomUUID(),job:draft.jobId,filename:file.name}),r=await fetch('/api/hospital/expenses/files?'+q,{method:'POST',headers:{'Content-Type':file.type},body:file}),v:any=await r.json();if(!r.ok)throw Error(v.error);setDraft((d:any)=>({...d,fileIds:[...d.fileIds,v.id],files:[...d.files,{id:v.id,name:file.name}]}));}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const input=(key:string,label:string,required=true)=> <label className="field"><span>{label}</span><input required={required} value={draft[key]||''} onChange={e=>change(key,e.target.value)}/></label>;
 if(!data)return <p>{error||'در حال دریافت تنخواه…'}</p>;
 const policies=data.policies,claims=data.claims,policy=draft?.mode==='submit'?policies.find((p:any)=>p.data.start<=draft.day&&p.data.end>=draft.day):null,category=policy?.data.categories.find((c:any)=>c.id===draft?.categoryId),group=policy?.data.groups.find((g:any)=>g.id===category?.groupId);
 const spent=group?claims.filter((r:any)=>r.data.ownerId===data.mid&&r.data.day===draft.day&&r.data.groupId===group.id&&r.data.state!=='rejected').reduce((n:bigint,r:any)=>n+BigInt(r.data.amount),BigInt(0)):BigInt(0),cap=BigInt(group?.limit||0),amount=/^\d+$/.test(draft?.amount||'')?BigInt(draft.amount):BigInt(0),over=group&&spent+amount>cap?spent+amount-cap:BigInt(0);
 const visible=claims.filter((r:any)=>filter==='all'||filter==='excess'&&BigInt(r.data.control.excess)>BigInt(0)||filter==='open'&&['manager','finance'].includes(r.data.state));
 return <section className="flow-card" dir="rtl"><IconActions scope="hospital-expenses-panel-actions-8783f8f8ad"><h3>تنخواه و هزینه‌های مأموریت</h3><button className="btn" disabled={busy} onClick={load}>تازه‌سازی</button>{data.jobs.some((j:any)=>j.data.technicianId===data.mid)&&<button className="btn primary" onClick={()=>start('submit')}>ثبت هزینه و فاکتور</button>}{data.roles.configure&&<button className="btn" onClick={()=>start('policy',{title:'سقف هزینه‌های مأموریت',start:localDay(),end:localDay(),groups:initialGroups,categories:initialCategories,assignments:[{ownerId:'',managerId:'',financeId:''}]})}>تعریف سقف و تأییدکنندگان</button>}</IconActions>
 <p className="subtle">مبالغ به ریال است. هزینه هر روز در تمام مأموریت‌ها جمع می‌شود. تأیید نهایی هزینه به معنی پرداخت وجه یا تسویه مانده تنخواه نیست.</p>
 {notice&&<p className="notice" role="status">{notice}</p>}{error&&!draft&&<p className="notice error" role="alert">{error}</p>}
 {!policies.length&&<p className="notice">ابتدا مسئول مالی سقف‌ها، بازه اعتبار، مدیر مستقیم و تأییدکننده تنخواه هر تکنسین را تعریف کند.</p>}
 <IconDisclosure scope="hospital-expenses-panel-details-5b5f9ecdc9" title={<> سقف‌های مصوب و زنجیره تأیید </>}>{policies.map((p:any)=><article className="flow-card" key={p.id}><strong>{p.data.title}</strong><p>{formatDate(p.data.start)} تا {formatDate(p.data.end)}</p>{p.data.groups.map((g:any)=><p key={g.id}>{g.name}: {cash(g.limit)} در روز — {p.data.categories.filter((c:any)=>c.groupId===g.id).map((c:any)=>c.name).join('، ')}</p>)}{p.data.assignments.filter((a:any)=>data.roles.configure||a.ownerId===data.mid).map((a:any)=><p key={a.ownerId}>تکنسین: {data.members.find((m:any)=>m.id===a.ownerId)?.name||a.ownerId} · مدیر: {data.members.find((m:any)=>m.id===a.managerId)?.name||a.managerId} · مالی: {data.members.find((m:any)=>m.id===a.financeId)?.name||a.financeId}</p>)}{data.roles.configure&&!claims.some((r:any)=>r.data.policyId===p.id)&&<button className="btn" onClick={()=>start('policy',{...p.data,policyId:p.id,revision:p.revision})}>ویرایش سیاست استفاده‌نشده</button>}</article>)}</IconDisclosure>
 <IconActions scope="hospital-expenses-panel-actions-9adcb1039c">{[['open','منتظر تأیید'],['excess','گزارش عبور از سقف'],['all','همه و سوابق']].map(([id,label])=><button key={id} className={'btn '+(filter===id?'primary':'')} onClick={()=>setFilter(id)}>{label}</button>)}</IconActions>
 {!visible.length&&<p>هزینه‌ای در این فهرست نیست.</p>}{visible.map((r:any)=>{const d=r.data;return <article key={r.id} className="flow-card"><div className="tools"><strong>{d.categoryName} · {cash(d.amount)}</strong><span>{data.states[d.state]}</span></div><p>{d.ownerName} · {formatDate(d.day)} · دستگاه {d.serial}</p><p>فروشنده: {d.vendor} · شماره فاکتور: {d.reference}</p><p>سقف {d.groupName}: {cash(d.control.limit)} · جمع روز هنگام ثبت: {cash(d.control.total)}</p>{BigInt(d.control.excess)>BigInt(0)&&<p className="notice error">گزارش کنترلی: جمع روز {cash(d.control.excess)} بالاتر از سقف است. علت: {d.explanation}</p>}<p>{d.notes}</p><div className="tools">{d.fileIds.map((id:string,i:number)=><a key={id} className="btn" href={'/api/hospital/expenses/files?id='+encodeURIComponent(id)} target="_blank" rel="noreferrer">مدرک هزینه {i+1}</a>)}</div>{['managerReview','financeReview'].map(k=>d[k]&&<p key={k}>{k==='managerReview'?'مدیر':'مالی'}: {d[k].approved?'تأیید':'رد'} · {d[k].name} · {formatDateTime(d[k].at)} — {d[k].notes}{d[k].acceptOverLimit?' — استثنای سقف تأیید شد':''}</p>)}{((d.state==='manager'&&d.managerId===data.mid&&data.roles.manager)||(d.state==='finance'&&d.financeId===data.mid&&data.roles.finance))&&<button className="btn primary" onClick={()=>start(d.state+'_review',{claimId:r.id,revision:r.revision,claim:d,acceptOverLimit:false})}>بررسی و تصمیم</button>}</article>})}
 <Dialog open={!!draft} onOpenChange={v=>!v&&!busy&&setDraft(null)}><DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto" dir="rtl"><DialogTitle>{draft?.mode==='policy'?'سقف و مسئول‌های تنخواه':draft?.mode==='submit'?'ثبت هزینه مأموریت':'بررسی هزینه'}</DialogTitle><DialogDescription>فاکتور و مبلغ واقعی را ثبت کنید؛ هر تصمیم در سابقه نگهداری می‌شود.</DialogDescription>{draft&&<form onSubmit={save}><div className="formgrid">
 {draft.mode==='submit'&&<><Pick label="مأموریت" value={draft.jobId} items={data.jobs.filter((j:any)=>j.data.technicianId===data.mid).map((j:any)=>({id:j.id,name:j.data.serial+' · '+j.data.description}))} onChange={v=>setDraft((d:any)=>({...d,jobId:v,fileIds:[],files:[]}))}/><SolarDate label="تاریخ هزینه" value={draft.day} onChange={v=>{change('day',v);change('categoryId','')}}/>{!policy?<p className="notice">سیاست معتبر برای این روز تعریف نشده است.</p>:<Pick label="نوع هزینه" value={draft.categoryId} items={policy.data.categories} onChange={v=>change('categoryId',v)}/ >}{input('amount','مبلغ واقعی فاکتور (ریال)')}{input('vendor','نام فروشنده')}{input('reference','شماره فاکتور / مرجع سند')}{group&&<p className="notice wide">سقف {group.name}: {cash(cap)} · هزینه ثبت‌شده روز: {cash(spent)} · مانده پیش از این فاکتور: {cash(cap>spent?cap-spent:BigInt(0))}{over>BigInt(0)&&<><br/>جمع روز با این فاکتور {cash(over)} بالاتر از سقف است؛ برای مدیر گزارش می‌شود.</>}</p>}{over>BigInt(0)&&input('explanation','علت هزینه بالاتر از سقف')}<label className="field wide">تصویر فاکتور / PDF، حداکثر ۸ فایل، هر فایل ۱۰ مگابایت<input type="file" accept="image/jpeg,image/png,application/pdf" disabled={busy||draft.fileIds.length>=8} onChange={e=>{void upload(e.target.files?.[0]);e.target.value=''}}/>{draft.files.map((f:any)=><span key={f.id}>{f.name} <button type="button" className="btn" onClick={()=>setDraft((d:any)=>({...d,fileIds:d.fileIds.filter((id:string)=>id!==f.id),files:d.files.filter((x:any)=>x.id!==f.id)}))}>حذف از درخواست</button></span>)}</label></>}
 {draft.mode==='policy'&&<>{input('title','عنوان سیاست')}<SolarDate label="از تاریخ" value={draft.start} onChange={v=>change('start',v)}/><SolarDate label="تا تاریخ" value={draft.end} onChange={v=>change('end',v)}/><p className="notice wide">سقف صفر یعنی هزینه مجاز صفر. سقف‌ها روزانه و برای هر نفر هستند. سیاست پس از اولین هزینه ثابت می‌ماند؛ بازه‌های بعدی را جدا تعریف کنید.</p><div className="wide"><h4>گروه‌های سقف روزانه</h4>{draft.groups.map((g:any,i:number)=><div className="formgrid" key={i}>{[['id','کد لاتین ثابت'],['name','نام گروه'],['limit','سقف روزانه (ریال)']].map(([key,label])=><label className="field" key={key}>{label}<input required value={g[key]} onChange={e=>change('groups',draft.groups.map((x:any,n:number)=>n===i?{...x,[key]:e.target.value}:x))}/></label>)}</div>)}<button className="btn" type="button" onClick={()=>change('groups',[...draft.groups,{id:'group'+draft.groups.length,name:'',limit:''}])}>افزودن گروه</button><h4>انواع هزینه</h4>{draft.categories.map((c:any,i:number)=><div className="formgrid" key={i}>{[['id','کد لاتین ثابت'],['name','نام هزینه']].map(([key,label])=><label className="field" key={key}>{label}<input required value={c[key]} onChange={e=>change('categories',draft.categories.map((x:any,n:number)=>n===i?{...x,[key]:e.target.value}:x))}/></label>)}<Pick label="گروه سقف مشترک" value={c.groupId} items={draft.groups} onChange={v=>change('categories',draft.categories.map((x:any,n:number)=>n===i?{...x,groupId:v}:x))}/></div>)}<button className="btn" type="button" onClick={()=>change('categories',[...draft.categories,{id:'cost'+draft.categories.length,name:'',groupId:''}])}>افزودن نوع هزینه</button><h4>تکنسین و دو تأییدکننده مستقل</h4>{draft.assignments.map((a:any,i:number)=><div className="formgrid" key={i}>{[['ownerId','تکنسین','tech'],['managerId','مدیر مستقیم','manager'],['financeId','مسئول تأیید تنخواه مالی','finance']].map(([key,label,role])=><Pick key={key} label={label} value={a[key]} items={data.members.filter((m:any)=>m[role])} onChange={v=>change('assignments',draft.assignments.map((x:any,n:number)=>n===i?{...x,[key]:v}:x))}/>)}</div>)}<button className="btn" type="button" onClick={()=>change('assignments',[...draft.assignments,{ownerId:'',managerId:'',financeId:''}])}>افزودن تکنسین</button></div></>}
 {draft.mode.endsWith('_review')&&<><p className="notice wide">{draft.claim.ownerName} · {draft.claim.categoryName} · {cash(draft.claim.amount)}<br/>جمع روز هنگام ثبت: {cash(draft.claim.control.total)} · سقف: {cash(draft.claim.control.limit)}</p><Pick label="تصمیم" value={draft.approved?'yes':'no'} items={[{id:'yes',name:'تأیید'},{id:'no',name:'رد'}]} onChange={v=>change('approved',v==='yes')}/><label className="field wide"><span><input type="checkbox" checked={draft.acceptOverLimit} onChange={e=>change('acceptOverLimit',e.target.checked)}/> در صورت عبور مجموع روز از سقف، استثنا را با توضیح زیر تأیید می‌کنم.</span></label></>}
 <label className="field wide">{draft.mode.endsWith('_review')?'دلیل تصمیم (الزامی)':'توضیحات'}<textarea required={draft.mode.endsWith('_review')} rows={3} value={draft.notes} onChange={e=>change('notes',e.target.value)}/></label></div>{error&&<p className="notice error" role="alert">{error}</p>}<div className="tools"><button className="btn primary" disabled={busy||draft.mode==='submit'&&(!policy||!draft.fileIds.length)}>{busy?'در حال ثبت…':'تأیید و ثبت'}</button><button type="button" className="btn" disabled={busy} onClick={()=>setDraft(null)}>انصراف</button></div></form>}</DialogContent></Dialog>
 </section>;
}
