"use client";
import {useEffect,useState} from 'react';
import {Plus,Save,Trash2,Copy,KeyRound,RefreshCw} from 'lucide-react';
import type {LlmProfile} from '@/lib/llm-config';
type Token={id:string;name:string;scope:string;expires:string;revoked:number};
type Draft={id:string;revision:number;name:string;model:string;baseUrl:string;systemPrompt:string;temperature:number;maxTokens:number;apiToken:string;clearToken:boolean};
const blank=():Draft=>({id:crypto.randomUUID(),revision:0,name:'',model:'',baseUrl:'https://api.openai.com/v1',systemPrompt:'شما دستیار سامانه نفس‌یار هستید. فقط در محدوده دسترسی کاربر کار کنید. پیش از تغییر داده‌ها تأیید بگیرید. نتیجه نامشخص را موفق گزارش نکنید.',temperature:0.3,maxTokens:2048,apiToken:'',clearToken:false});
async function response(r:Response){const d:any=await r.json();if(!r.ok)throw new Error(d.error||'عملیات انجام نشد.');return d;}
export function LlmSettings(){
 const [profiles,setProfiles]=useState<LlmProfile[]>([]),[tokens,setTokens]=useState<Token[]>([]),[tools,setTools]=useState<{name:string;description:string;annotations:{readOnlyHint:boolean}}[]>([]),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[ready,setReady]=useState(false);
 const [checks,setChecks]=useState<Record<string,{models?:string[];listed?:boolean;message?:string;error?:string}>>({});
 function notifyModels(){window.dispatchEvent(new Event('nafasyar-models-changed'));if(typeof BroadcastChannel!=='undefined'){const c=new BroadcastChannel('nafasyar-models');c.postMessage('changed');c.close()}}
 const [tokenName,setTokenName]=useState('Cursor'),[scope,setScope]=useState('read'),[days,setDays]=useState(30),[secret,setSecret]=useState(''),[origin,setOrigin]=useState('');
 async function refresh(){setLoading(true);try{const results=await Promise.allSettled([fetch('/api/llm-config',{cache:'no-store'}).then(response),fetch('/api/mcp-tokens',{cache:'no-store'}).then(response),fetch('/api/mcp-info',{cache:'no-store'}).then(response)]);if(results[0].status==='fulfilled'){setProfiles(results[0].value.profiles);setReady(results[0].value.encryptionReady)}if(results[1].status==='fulfilled')setTokens(results[1].value.tokens);if(results[2].status==='fulfilled')setTools(results[2].value.tools);setError(results.filter(r=>r.status==='rejected').map(r=>(r as PromiseRejectedResult).reason.message).join(' · '))}finally{setLoading(false)}}
 async function test(p:LlmProfile,mode:'models'|'probe'){if(busy)return;setBusy(true);setChecks(c=>({...c,[p.id]:{message:'در حال بررسی…'}}));try{const d=await fetch('/api/llm-config/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:p.id,mode,confirmed:true})}).then(response);setChecks(c=>({...c,[p.id]:{models:d.models,listed:d.listed,message:d.message||d.notice}}))}catch(e){setChecks(c=>({...c,[p.id]:{error:(e as Error).message}}))}finally{setBusy(false)}}

 useEffect(()=>{setOrigin(window.location.origin);void refresh();},[]);
 const edit=(p:LlmProfile)=>{setDraft({id:p.id,revision:p.revision,name:p.name,model:p.model,baseUrl:p.baseUrl,systemPrompt:p.systemPrompt,temperature:p.temperature,maxTokens:p.maxTokens,apiToken:'',clearToken:false});setMessage('');};
 const patch=(v:Partial<Draft>)=>setDraft(d=>d?{...d,...v}:d);
 async function save(e:React.FormEvent){e.preventDefault();if(!draft||busy)return;setBusy(true);setError('');try{await fetch('/api/llm-config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)}).then(response);setDraft(null);notifyModels();setMessage('تنظیمات ذخیره شد.');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(p:LlmProfile){if(!window.confirm('پروفایل «'+p.name+'» حذف شود؟'))return;setBusy(true);try{await fetch('/api/llm-config?id='+encodeURIComponent(p.id)+'&revision='+p.revision,{method:'DELETE'}).then(response);if(draft?.id===p.id)setDraft(null);notifyModels();await refresh();setMessage('پروفایل حذف شد.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function createToken(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setSecret('');setError('');try{const d=await fetch('/api/mcp-tokens',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:tokenName,scope,days})}).then(response);setSecret(d.token);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function revoke(t:Token){if(!window.confirm('اتصال «'+t.name+'» لغو شود؟'))return;setBusy(true);try{await fetch('/api/mcp-tokens?id='+encodeURIComponent(t.id),{method:'DELETE'}).then(response);setSecret('');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const sse=origin+'/sse?token='+secret,config=JSON.stringify({mcpServers:{nafasyar:{url:sse}}},null,2);
 async function copy(value:string){try{await navigator.clipboard.writeText(value);setMessage('کپی شد.');}catch{setError('کپی خودکار ممکن نشد؛ متن را انتخاب و کپی کنید.');}}
 return <div className="llm-settings">
 {error&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}
 <div className="panel"><div className="panelhead"><h2>پروفایل‌های مدل زبانی</h2><div className="tools"><button className="btn" disabled={busy||loading} onClick={()=>void refresh()}><RefreshCw size={16}/>تازه‌سازی</button><button className="btn primary" disabled={busy} onClick={()=>setDraft(blank())}><Plus size={16}/>پروفایل جدید</button></div></div>
 <div className="inside"><p className="subtle">محیط فعلی: <span dir="ltr">{origin}</span> · {profiles.length} پروفایل ذخیره‌شده</p><p className="subtle">دستیار چت پایین صفحه از این مدل‌ها استفاده می‌کند. ارائه‌دهنده باید از Chat Completions و ابزارها پشتیبانی کند. ارسال پیام ممکن است هزینه API داشته باشد. ذخیره پروفایل هیچ درخواست پولی ارسال نمی‌کند؛ مدل یا System Prompt نرم‌افزار Cursor و ChatGPT را تغییر نمی‌دهد. فرمان صوتی نیز از مدل انتخاب‌شده در همان پنجره دستیار استفاده می‌کند. «آزمون پاسخ» یک درخواست کوتاه با هزینه احتمالی API می‌فرستد.</p>
 {loading?<p role="status">در حال دریافت تنظیمات…</p>:!profiles.length?<p>هنوز پروفایلی تعریف نشده است.</p>:profiles.map(p=><div key={p.id}><div className="recordline"><div><strong>{p.name}</strong><p dir="ltr">{p.model}</p><small>{p.hasToken?'توکن ذخیره شده':'بدون توکن'} · نسخه {p.revision}</small></div><div className="tools"><button className="btn" disabled={busy} onClick={()=>edit(p)}>ویرایش</button><button className="btn" disabled={busy} onClick={()=>void test(p,'models')}>مدل‌های سرویس</button><button className="btn" disabled={busy} onClick={()=>void test(p,'probe')}>آزمون پاسخ</button><button className="btn" disabled={busy} onClick={()=>void remove(p)} aria-label={'حذف '+p.name}><Trash2 size={16}/></button></div></div>{checks[p.id]&&<div className="notice" role="status">{checks[p.id].error||checks[p.id].message}{checks[p.id].models&&<><p>{checks[p.id].listed?'مدل ذخیره‌شده در فهرست سرویس وجود دارد.':'مدل ذخیره‌شده در فهرست برگشتی این سرویس نیست؛ قبل از تغییر، سازگاری و دسترسی آن را بررسی کنید.'}</p><details><summary>فهرست مدل‌های در دسترس ({checks[p.id].models!.length})</summary><p>شناسه دقیق مدل مناسب چت و ابزار را در ویرایش پروفایل وارد کنید.</p><div style={{maxHeight:220,overflow:'auto'}}>{checks[p.id].models!.map(m=><p dir="ltr" key={m}>{m}</p>)}</div></details></>}</div>}</div>)}
 {draft&&<form onSubmit={save} className="llm-form"><div className="formgrid">
 <label className="field">نام پروفایل<input required maxLength={100} value={draft.name} onChange={e=>patch({name:e.target.value})}/></label>
 <label className="field">Model<input required dir="ltr" maxLength={160} value={draft.model} onChange={e=>patch({model:e.target.value})}/></label>
 <label className="field wide">Base URL<input required type="url" dir="ltr" value={draft.baseUrl} onChange={e=>patch({baseUrl:e.target.value})}/><small>نشانی HTTPS سرویس؛ با تغییر آن، توکن قبلی را حذف یا جایگزین کنید.</small></label>
 <label className="field wide">System Prompt<textarea rows={6} maxLength={16000} value={draft.systemPrompt} onChange={e=>patch({systemPrompt:e.target.value})}/></label>
 <label className="field">Temperature<input type="number" required min={0} max={2} step="0.01" value={draft.temperature} onChange={e=>patch({temperature:Number(e.target.value)})}/></label>
 <label className="field">حداکثر توکن خروجی<input required type="number" min={1} max={131072} step={1} value={draft.maxTokens} onChange={e=>patch({maxTokens:Number(e.target.value)})}/></label>
 <label className="field wide">API Token<input type="password" autoComplete="new-password" dir="ltr" disabled={!ready} value={draft.apiToken} onChange={e=>patch({apiToken:e.target.value,clearToken:false})} placeholder="خالی بماند: توکن فعلی حفظ می‌شود"/><small>توکن رمزگذاری می‌شود و پس از ذخیره دوباره نمایش داده نمی‌شود.</small></label>
 <label className="llm-check"><input type="checkbox" checked={draft.clearToken} onChange={e=>patch({clearToken:e.target.checked,apiToken:''})}/>حذف توکن ذخیره‌شده</label>
 </div>{!ready&&<p className="notice error">ذخیره توکن تا تنظیم کلید رمزگذاری سرور غیرفعال است.</p>}<div className="tools"><button type="submit" className="btn primary" disabled={busy}><Save size={16}/>{busy?'در حال ذخیره…':'ذخیره تنظیمات'}</button><button type="button" className="btn" disabled={busy} onClick={()=>setDraft(null)}>انصراف</button></div></form>}
 </div></div>
 <section className="panel"><div className="panelhead"><h2>اتصال MCP — Cursor و سایر دستیارها</h2><span>{tools.length} ابزار</span></div><div className="inside">
 <p>Streamable HTTP: <code dir="ltr">{origin}/mcp</code></p><p>Legacy SSE: <code dir="ltr">{origin}/sse?token=REFERENCE_TOKEN</code></p>
 <p className="notice">این سایت خصوصی است. توکن مرجع جایگزین ورود به میزبان نیست؛ برای اتصال بیرونی به این نسخه از OAuth میزبان استفاده کنید. اتصال صرفاً با لینک SSE روی میزبانی‌ای کار می‌کند که مسیرهای MCP را به برنامه برساند.</p>
 <p className="subtle">توکن مرجع مخصوص اتصال MCP است و با API Token مدل تفاوت دارد. اعتبار و دسترسی حساب در هر درخواست بررسی می‌شود. لینک دارای توکن را مانند رمز عبور نگه دارید.</p>
 <form className="formgrid llm-form" onSubmit={createToken}><label className="field">نام اتصال<input required value={tokenName} maxLength={100} onChange={e=>setTokenName(e.target.value)}/></label><label className="field">دسترسی<select value={scope} onChange={e=>setScope(e.target.value)}><option value="read">فقط مشاهده</option><option value="read_write">مشاهده و تغییر با مجوز حساب</option></select></label><label className="field">اعتبار (روز)<input required type="number" min={1} max={90} value={days} onChange={e=>setDays(Number(e.target.value))}/></label><button className="btn primary" type="submit" disabled={busy}><KeyRound size={16}/>ساخت توکن مرجع</button></form>
 {secret&&<div className="llm-secret"><strong>فقط همین بار نمایش داده می‌شود</strong><label className="field">لینک SSE<textarea readOnly dir="ltr" value={sse}/></label><button className="btn" onClick={()=>void copy(sse)}><Copy size={16}/>کپی لینک</button><label className="field">پیکربندی MCP برای Cursor<textarea readOnly dir="ltr" rows={6} value={config}/></label><div className="tools"><button className="btn" onClick={()=>void copy(config)}>کپی پیکربندی</button><button className="btn" onClick={()=>setSecret('')}>پنهان کردن</button></div></div>}
 {tokens.map(t=><div className="recordline" key={t.id}><div><strong>{t.name}</strong><p className="subtle">{t.scope==='read'?'فقط مشاهده':'مشاهده و تغییر'} · انقضا: {new Date(t.expires).toLocaleDateString('fa-IR')} · {t.revoked?'لغوشده':Date.parse(t.expires)<Date.now()?'منقضی':'فعال'}</p></div><button className="btn" disabled={busy||!!t.revoked} onClick={()=>void revoke(t)}>لغو دسترسی</button></div>)}
 <details className="finance-guide"><summary>فهرست ابزارها و محدوده عملکرد</summary><p>عملیات روی داده واقعی شرکت اجرا می‌شود. ابزار چاپ فایل آماده چاپ می‌دهد و چاپگر را کنترل نمی‌کند. رابط حسابداری ویندوز و تولید کد گارانتیِ پیاده‌سازی‌نشده، از طریق MCP قابل اجرا نیستند.</p>{tools.map(t=><div className="recordline" key={t.name}><div><strong dir="ltr">{t.name}</strong><p dir="ltr" className="subtle">{t.description}</p></div><span>{t.annotations.readOnlyHint?'مشاهده':'تغییر'}</span></div>)}</details>
 </div></section></div>;
}
