'use client';
import {formatDate} from '@/lib/persian-date';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {SolarDate} from './solar-date';
import {SupplierPanel} from './supplier-panel';
import {QualityPanel} from './quality-panel';
import {BatchFilesPanel} from './batch-files-panel';
import {roleNames,qty} from '@/lib/material-flow';
import {tehranDay} from '@/lib/serials';
import {type QField} from '@/lib/quality';
import type {Row} from '@/lib/model';
const blankField=(key='check_1'):QField=>({key,label:'',type:'number',unit:'',min:'',max:'',required:true});
const n=(x:number)=>Number(x||0).toLocaleString('fa-IR');
const when=(s:string)=>s?formatDate(s):'—';
const states:Record<string,string>={pending_qc:'در انتظار کنترل ورودی',awaiting_warehouse:'در انتظار انتقال انباردار',stored:'انبارشده',rejected:'مردود در قرنطینه',pending:'در انتظار تحویل',issued:'تحویل خط',prepared:'بچ‌های مصرفی ثبت‌شده',awaiting_receipt:'در انتظار دریافت انبار',finished:'در انبار محصول نهایی',reserved:'رزروشده فروش',in_transit:'تحویل تدارکات',planned:'در انتظار مونتاژ',assembled:'برگ تولید ثبت‌شده',open:'باز',closed:'بسته'};
function Input({label,value,onChange,type='text',required=false}:{label:string;value:any;onChange:(s:string)=>void;type?:string;required?:boolean}){return <label className="field"><span>{label}</span>{type==='textarea'?<textarea required={required} value={value??''} onChange={e=>onChange(e.target.value)}/>:<input required={required} type={type} step={type==='number'?'0.001':undefined} value={value??''} onChange={e=>onChange(e.target.value)}/>}</label>}
function Select({label,value,onChange,options}:{label:string;value:any;onChange:(v:string)=>void;options:[string,string][]}){return <label className="field"><span>{label}</span><select value={value||''} onChange={e=>onChange(e.target.value)}><option value="">انتخاب کنید</option>{options.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>}
export function MaterialFlow({demo,onSaved,onOpen,initialTab='tasks'}:{initialTab?:string;demo:boolean;onSaved:()=>void;onOpen:(r:Row)=>void}){
 const [supplierMaterial,setSupplierMaterial]=useState('');
 const [state,setState]=useState<any>(null),[tab,setTab]=useState(initialTab),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[draft,setDraft]=useState<any>(null),[qc,setQc]=useState(''),[fileBatch,setFileBatch]=useState('');
 async function load(){if(demo)return;setLoading(true);try{const r=await fetch('/api/flow',{cache:'no-store'}),d=await r.json() as any;if(!r.ok)throw new Error(d.error);setState(d)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[demo]);
 const all=state?.entities||[],rows=state?.rows||[],roles=state?.roles||[],balances=state?.balances||[],slots=state?.slots||[];
 const of=(type:string)=>all.filter((e:any)=>e.type===type),find=(id:string)=>all.find((e:any)=>e.id===id),rec=(id:string)=>rows.find((r:any)=>r.id===id),mat=(id:string)=>find(id)?.data;
 const materials=of('material'),receipts=of('receipt'),plans=of('plan'),builds=of('build'),requests=of('request'),supplies=of('supply');
 const materialOptions: [string,string][]=materials.map((m:any)=>[m.id,m.data.code+' · '+m.data.name]);
 const stock=(id:string,wh='line')=>balances.find((b:any)=>b.item_id===id&&b.warehouse===wh)?.quantity||0;
 const materialName=(id:string)=>mat(id)?.name||id;
 const serial=(id:string)=>rec(id)?.data.code||id;
 const label=(e:any)=>e.type==='receipt'?rec(e.id)?.data.code:materialName(e.data.materialId);
 const has=(role:string)=>roles.includes(role);
 function start(mode:string,data:any={}){setError('');setMessage('');setDraft({id:crypto.randomUUID(),mode,...data});}
 function change(key:string,v:any){setDraft((p:any)=>({...p,[key]:v}))}
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/flow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)}),d=await r.json() as any;if(!r.ok)throw new Error(d.error);setDraft(null);setMessage('عملیات ثبت شد و کارتابل به‌روز شد.');await load();onSaved();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function newReceipt(materialId:string){const m=find(materialId);const previous=receipts.find((r:any)=>r.data.materialId===materialId),old=previous?rec(previous.id)?.data:{};return {materialId,day:tehranDay(),quantity:'',supplier:old?.supplier||'',maker:old?.maker||'',specs:old?.specs??m?.data.specs??'',manufacturerLot:'',purchase:'',notes:'',expiry:''};}
 function place(r:any){const previous=receipts.find((v:any)=>v.data.materialId===r.data.materialId&&v.data.location)?.data.location||mat(r.data.materialId)?.defaultLocation||'';if(!slots.some((s:any)=>s.location===previous&&s.batch_id!==r.id))return previous;const parts=previous.split('-');if(parts.length!==4)return '';for(let i=1;i<1000;i++){const candidate=[...parts.slice(0,3),String(i)].join('-');if(!slots.some((s:any)=>s.location===candidate))return candidate;}return '';}
 function candidates(materialId:string){return receipts.filter((r:any)=>r.data.materialId===materialId&&r.data.state==='stored'&&(!r.data.expiry||r.data.expiry>=tehranDay())).flatMap((r:any)=>slots.filter((s:any)=>s.batch_id===r.id&&s.quantity>0).map((s:any)=>({...s,receipt:r}))).sort((a:any,b:any)=>(a.receipt.data.expiry||'9999').localeCompare(b.receipt.data.expiry||'9999')||a.receipt.data.day.localeCompare(b.receipt.data.day)||a.receipt.created.localeCompare(b.receipt.created));}
 function issue(r:any){let remaining=r.data.quantity;const allocations=[];for(const c of candidates(r.data.materialId)){const amount=Math.min(remaining,c.quantity);if(amount>0)allocations.push({batchId:c.batch_id,location:c.location,quantity:qty(amount)});remaining-=amount;if(!remaining)break;}start('issue',{requestId:r.id,allocations,reason:''});}
 function buildForm(b:any){const bom=state.boms.find((x:any)=>x.id===b.data.bomId),lines=bom?JSON.parse(bom.lines):[];const allocations:any[]=[];if(b.data.materials?.length){for(const m of b.data.materials.filter((m:any)=>m.quantity>0))allocations.push({partCode:m.partCode,batchId:m.batchId,quantity:qty(m.quantity)});}else for(const l of lines){let remaining=Math.round(Number(l.quantity)*1000);const options=receipts.filter((r:any)=>rec(r.id)?.data.partCode===l.partCode&&rec(r.id)?.data.status==='تأیید'&&stock(r.id)>0&&(!r.data.expiry||r.data.expiry>=tehranDay())).sort((a:any,b:any)=>a.data.day.localeCompare(b.data.day)||a.created.localeCompare(b.created));for(const r of options){const amount=Math.min(remaining,stock(r.id));if(amount>0)allocations.push({partCode:l.partCode,batchId:r.id,quantity:qty(amount)});remaining-=amount;if(!remaining)break;}if(remaining)allocations.push({partCode:l.partCode,batchId:'',quantity:qty(remaining)});}start(b.data.workflowVersion===2?'prepare':'build',{deviceId:b.id,allocations,notes:b.data.notes||''});}
 function capacitySuggestion(productId:string){const config=find('capacity:'+productId)?.data,bom=state?.boms.find((x:any)=>x.product_id===productId);const booked=plans.filter((p:any)=>p.data.productId===productId&&p.data.day===tehranDay()).reduce((s:number,p:any)=>s+p.data.count,0),unfinished=builds.filter((b:any)=>b.data.state==='planned'&&rec(b.id)?.data.product===productId).length;
 let possible=Infinity;if(bom)for(const l of JSON.parse(bom.lines)){const m=materials.find((m:any)=>m.data.code===l.partCode),stat=state.lowStock.find((x:any)=>x.materialId===m?.id);possible=Math.min(possible,Math.floor(Math.max(0,stat?.available||0)/(Number(l.quantity)*1000)));}else possible=0;
 return {capacity:config?.capacity||0,booked,unfinished,materials:Number.isFinite(possible)?possible:0,count:Math.max(0,Math.min((config?.capacity||0)-booked,Number.isFinite(possible)?possible:0))};}
 async function printPlan(p:any,small=false){if(busy)return;setBusy(true);try{const r=await fetch('/api/flow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),mode:'print',planId:p.id,notes:small?'برچسب قطعات':'برچسب پشت دستگاه'})});if(!r.ok)throw new Error((await r.json() as any).error);window.open('/api/serials/print?id='+encodeURIComponent(p.id)+(small?'&label=small':''),'_blank');setMessage('صفحه چاپ باز شد؛ چاپ فیزیکی را در پنجره مرورگر تأیید کنید.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(demo)return <div className="notice">برای گردش مواد و تولید وارد «اطلاعات شرکت» شوید. موجودی نمونه در عملیات واقعی استفاده نمی‌شود.</div>;
 const tasks=all.filter((e:any)=>e.type==='receipt'&&(e.data.state==='pending_qc'&&has('qc')||e.data.state==='awaiting_warehouse'&&has('inventory')&&state?.warehouseIds?.includes('raw')&&state?.warehouseIds?.includes('quarantine'))||e.type==='request'&&e.data.state==='pending'&&has('inventory')&&state?.warehouseIds?.includes('raw')||e.type==='supply'&&e.data.state==='open'&&has('procurement')||e.type==='build'&&['prepared','assembled'].includes(e.data.state)&&has('qc')&&e.data.latestQc?.verdict!=='pass');
 function receiptActions(r:any){return <div className="tools">{r.data.state==='pending_qc'&&has('qc')&&<button className="btn primary" onClick={()=>start('incoming_qc',{receiptId:r.id,accepted:'',rejected:'',values:{},notes:''})}>کنترل ورودی</button>}{r.data.state==='awaiting_warehouse'&&has('inventory')&&<button className="btn primary" onClick={()=>start('shelve',{receiptId:r.id,location:place(r)})}>تأیید دریافت و جانمایی</button>}<button className="btn" onClick={()=>setFileBatch(r.id)}>فایل و نقشه</button><button className="btn" onClick={()=>onOpen(rec(r.id))}>شناسنامه بچ</button></div>}
 const mode=draft?.mode;
 return <section className="flow-panel"><div className="panelhead"><div><h2>گردش مواد و تولید</h2><p className="subtle">دریافت ← قرنطینه ← کنترل ورودی ← انبار ← خط تولید ← کنترل نهایی</p></div><button className="btn" disabled={loading||busy} onClick={()=>void load()}>تازه‌سازی</button></div>
 <div className="flow-tabs">{Object.entries({tasks:'کارتابل',materials:'کالاها',receipts:'دریافت و قرنطینه',requests:'درخواست مواد',plans:'برنامه و سریال',builds:'مونتاژ و آزمون',supply:'تأمین',analysis:'گزارش کیفیت'}).filter(([k])=>!['plans','builds','analysis'].includes(k)||has('production')||has('qc')).map(([k,v])=><button key={k} className={'btn '+(tab===k?'primary':'')} onClick={()=>setTab(k)}>{v}{k==='tasks'?' ('+n(tasks.length)+')':''}</button>)}</div>
 {error&&!draft&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice">{message}</p>}{loading&&<p role="status">در حال دریافت…</p>}
 {state&&<>
 {tab==='tasks'&&<><p className="notice">اعلان‌ها در همین کارتابل نمایش داده می‌شوند. مسئول تعیین‌شده در شناسنامه کالا (یا مدیر) مرحله مربوطه را انجام می‌دهد.</p>{!tasks.length&&<p className="empty">کار بازی در این مرحله ندارید.</p>}{tasks.map((e:any)=><article className="flow-card" key={e.id}><h3>{e.type==='build'?serial(e.id):label(e)}</h3><p>{states[e.data.state]} · {when(e.created)}</p>{e.type==='receipt'?receiptActions(e):e.type==='request'?<button className="btn primary" onClick={()=>issue(e)}>تحویل {n(e.data.quantity/1000)} به خط</button>:e.type==='supply'?<button className="btn" onClick={()=>start('supply_close',{supplyId:e.id,result:''})}>ثبت نتیجه تأمین</button>:<button className="btn primary" onClick={()=>setQc(e.id)}>فرم کنترل نهایی / آزمون مجدد</button>}</article>)}</>}
 {tab==='materials'&&<>{has('inventory')&&<button className="btn primary" onClick={()=>start('material',{code:'',name:'',unit:'عدد',specs:'',defaultLocation:'',reorderPoint:'0',targetStock:'0',fields:[blankField()],qcOwner:'',warehouseOwner:'',procurementOwner:'',revision:0})}>تعریف کالا</button>}{supplierMaterial&&<><button className="btn" onClick={()=>setSupplierMaterial('')}>بستن تأمین‌کنندگان کالا</button><SupplierPanel key={supplierMaterial} materialId={supplierMaterial}/></>}{materials.map((m:any)=><article className="flow-card" key={m.id}><h3>{m.data.code} · {m.data.name}</h3>{['inventory','qc','procurement'].some(has)&&<button className="btn" onClick={()=>setSupplierMaterial(m.id)}>تأمین‌کنندگان این کالا</button>}<p>{m.data.specs||'بدون مشخصات تکمیلی'} · واحد: {m.data.unit}</p><p>حد سفارش: {n(m.data.reorderPoint/1000)} · هدف: {n(m.data.targetStock/1000)} · نسخه {n(m.revision)}</p><div className="tools">{has('inventory')&&<><button className="btn" onClick={()=>start('material',{...m.data,revision:m.revision,reorderPoint:qty(m.data.reorderPoint),targetStock:qty(m.data.targetStock)})}>ویرایش کالا و فرم ورودی</button><button className="btn primary" onClick={()=>start('receipt',newReceipt(m.id))}>دریافت بچ جدید</button></>}</div></article>)}</>}
 {tab==='receipts'&&<>{has('inventory')&&<button className="btn primary" onClick={()=>start('receipt',newReceipt(materials[0]?.id||''))}>ثبت دریافت به قرنطینه</button>}{receipts.map((r:any)=><article className="flow-card" key={r.id}><h3>{materialName(r.data.materialId)} · {serial(r.id)}</h3><p>{states[r.data.state]} · ورودی {n(r.data.quantity/1000)} · پذیرفته {n(r.data.accepted/1000)} · رد {n(r.data.rejected/1000)}</p><p>محل: {r.data.location||'قرنطینه'} · تاریخ: {when(r.data.day)}</p>{r.data.qc&&<details><summary>نتایج کنترل ورودی</summary>{r.data.fields.map((f:any)=><p key={f.key}>{f.label}: {r.data.qc.values[f.key]||'—'} {f.unit}</p>)}<p>{r.data.qc.notes} · {r.data.qc.by}</p></details>}{receiptActions(r)}</article>)}</>}
 {tab==='requests'&&<><div className="tools">{has('production')&&<><button className="btn primary" onClick={()=>start('request',{materialId:'',quantity:'',planId:'',notes:''})}>درخواست مواد از انبار</button><button className="btn" onClick={()=>start('reject',{batchId:'',quantity:'',reason:''})}>انتقال قطعه خط به نامنطبق</button></>}</div>{requests.map((r:any)=><article className="flow-card" key={r.id}><h3>{materialName(r.data.materialId)} · {n(r.data.quantity/1000)}</h3><p>{states[r.data.state]} · درخواست‌کننده: {r.data.requestedBy}</p>{r.data.state==='pending'&&has('inventory')&&<button className="btn primary" onClick={()=>issue(r)}>تأیید و تحویل بچ‌های پیشنهادی</button>}{r.data.allocations?.map((a:any,i:number)=><p key={i}>{serial(a.batchId)} · {a.location} · {a.quantity}</p>)}{r.data.reason&&<p>دلیل تغییر اولویت: {r.data.reason}</p>}</article>)}</>}
 {tab==='plans'&&<><div className="tools">{has('production')&&<><button className="btn" onClick={()=>start('capacity',{productId:'',capacity:'',smallLabels:3,revision:0})}>ظرفیت و برچسب محصول</button><button className="btn primary" onClick={()=>start('plan',{productId:'',count:'',design:'',firmware:'',reason:''})}>برنامه امروز و تولید سریال</button></>}</div>{plans.map((p:any)=><article className="flow-card" key={p.id}><h3>{rec(p.data.productId)?.data.name} · {when(p.data.day)} · {n(p.data.count)} دستگاه</h3><div className="tools"><button className="btn" disabled={busy} onClick={()=>void printPlan(p)}>چاپ برچسب پشت دستگاه</button>{p.data.smallLabels>0&&<button className="btn" disabled={busy} onClick={()=>void printPlan(p,true)}>چاپ برچسب کوچک قطعات</button>}{has('production')&&<button className="btn primary" onClick={()=>start('assign',{deviceIds:builds.filter((b:any)=>b.data.planId===p.id&&b.data.state==='planned').map((b:any)=>b.id),assembler:'',reason:'',planId:p.id})}>تخصیص سریال به مونتاژکار</button>}</div><p className="subtle">چاپ مجدد همان سریال‌ها را چاپ می‌کند؛ تأیید چاپ با مرورگر است.</p></article>)}</>}
 {tab==='builds'&&builds.map((b:any)=>{const tests=of('finaltest').filter((t:any)=>t.data.deviceId===b.id),current=b.data.latestQc?{data:b.data.latestQc}:tests.find((t:any)=>t.data.buildRevision===b.revision);return <article className="flow-card" key={b.id}><h3 dir="ltr">{serial(b.id)}</h3><p>مونتاژکار: {b.data.assembler||'تخصیص داده نشده'} · {states[b.data.state]} · آخرین آزمون معتبر: {current?(current.data.verdict==='pass'?'تأیید':'مردود'):'در انتظار آزمون'}</p><details><summary>قطعات نصب‌شده و سابقه تعویض</summary>{b.data.materials?.filter((m:any)=>m.quantity>0).map((m:any)=><p key={m.batchId}>{rec(m.batchId)?.data.part} · بچ {serial(m.batchId)} · {n(m.quantity/1000)}</p>)}{of('repair').filter((r:any)=>r.data.deviceId===b.id).map((r:any)=><p key={r.id}>تعویض {serial(r.data.oldBatchId)} با {serial(r.data.newBatchId)} · {n(r.data.quantity/1000)} · {r.data.reason} · {r.data.by}</p>)}</details><div className="tools">{['planned','prepared'].includes(b.data.state) &&has('production')&&<button className="btn primary" onClick={()=>buildForm(b)}>ثبت / ویرایش بچ‌های مصرفی</button>}{['prepared','assembled'].includes(b.data.state)&&<><button className="btn" onClick={()=>setQc(b.id)}>کنترل کیفیت و سوابق</button>{has('production')&&<button className="btn" onClick={()=>start('repair',{deviceId:b.id,oldBatchId:'',newBatchId:'',quantity:'',cause:'unknown',reason:''})}>تعویض قطعه و ثبت علت</button>}</>}{b.data.state==='prepared'&&b.data.latestQc?.verdict==='pass'&&has('production')&&<button className="btn primary" onClick={()=>start('build',{deviceId:b.id,allocations:b.data.materials.filter((m:any)=>m.quantity>0).map((m:any)=>({batchId:m.batchId,quantity:qty(m.quantity)})),notes:b.data.notes||''})}>تأیید برگ تولید و کسر مواد</button>}<button className="btn" onClick={()=>onOpen(rec(b.id))}>شناسنامه دستگاه</button></div></article>})}
 {tab==='supply'&&<>{state.lowStock.filter((x:any)=>x.low||supplies.some((s:any)=>s.data.materialId===x.materialId&&s.data.state==='open')).map((x:any)=>{const open=supplies.find((s:any)=>s.data.materialId===x.materialId&&s.data.state==='open');return <article className="flow-card" key={x.materialId}><h3>{materialName(x.materialId)} {x.low?'· زیر حد سفارش':''}</h3><p>انبار مواد: {n(x.raw/1000)} · انبار و خط: {n(x.total/1000)} · نیاز برنامه باز: {n(x.demand/1000)} · پیشنهاد تأمین: {n(x.proposed/1000)}</p><p>{mat(x.materialId)?.specs}</p>{open?<><p>درخواست باز: {n(open.data.quantity/1000)} · {open.data.notes}</p>{has('procurement')&&<button className="btn" onClick={()=>start('supply_close',{supplyId:open.id,result:''})}>ثبت نتیجه تأمین</button>}</>:has('inventory')&&<button className="btn primary" onClick={()=>start('supply',{materialId:x.materialId,quantity:qty(x.proposed),notes:'تأمین برای موجودی هدف و برنامه تولید باز'})}>تأیید / اصلاح مقدار و ارسال به تأمین</button>}</article>})}<h3>سوابق درخواست تأمین</h3>{supplies.map((s:any)=><p key={s.id}>{materialName(s.data.materialId)} · {n(s.data.quantity/1000)} · {states[s.data.state]} · {s.data.result||s.data.notes}</p>)}</>}
 {tab==='analysis'&&<><p className="notice">مردودی آزمون اول از قبولی پس از تعمیر جدا نگهداری می‌شود. علت احتمالی، به‌تنهایی اثبات خطای مونتاژکار نیست.</p><div className="flow-table"><table><thead><tr><th>مونتاژکار / محصول</th><th>تعداد آزمون‌شده</th><th>مردودی آزمون اول</th><th>نرخ مردودی</th></tr></thead><tbody>{Array.from(new Set(builds.map((b:any)=>(b.data.assembler||'بدون نام')+'|'+(rec(b.id)?.data.product||'')))).map((key:any)=>{const [assembler,product]=key.split('|'),bs=builds.filter((b:any)=>(b.data.assembler||'بدون نام')===assembler&&rec(b.id)?.data.product===product),tests=bs.map((b:any)=>of('finaltest').filter((t:any)=>t.data.deviceId===b.id).sort((a:any,b:any)=>a.created.localeCompare(b.created))[0]).filter(Boolean),fails=tests.filter((t:any)=>t.data.verdict==='fail');return <tr key={key}><td>{assembler} / {rec(product)?.data.name}</td><td>{n(tests.length)}</td><td>{n(fails.length)}</td><td>{tests.length?n(100*fails.length/tests.length)+'٪':'—'}</td></tr>})}</tbody></table></div>{of('finaltest').filter((t:any)=>t.data.verdict==='fail').map((t:any)=><p key={t.id}>{serial(t.data.deviceId)} · علت: {({part:'قطعه',assembly:'مونتاژ',design:'طراحی',test:'آزمون',unknown:'نامشخص'} as any)[t.data.cause]} · {t.data.notes} · آزمون‌کننده: {t.data.by}</p>)}</>}
 </>}
 <Dialog open={!!draft} onOpenChange={v=>{if(!busy&&!v)setDraft(null)}}><DialogContent className="modal sm:max-w-3xl"><DialogTitle>{({material:'شناسنامه کالا و فرم کنترل ورودی',receipt:'دریافت بچ به قرنطینه',incoming_qc:'کنترل کیفیت ورودی',shelve:'تأیید انباردار و جانمایی',request:'درخواست مواد خط تولید',issue:'برداشت و تحویل به خط',supply:'درخواست تأمین',supply_close:'نتیجه تأمین',capacity:'ظرفیت روزانه محصول',plan:'برنامه امروز و ایجاد سریال',assign:'تخصیص مونتاژکار',prepare:'ثبت بچ‌های مصرفی پیش از کنترل کیفیت',build:'برگ تولید و مصرف قطعات',reject:'نامنطبق خط تولید',repair:'تعویض قطعه نصب‌شده'} as any)[mode]}</DialogTitle><DialogDescription>ثبت این فرم سوابق گردش کار و موجودی مربوطه را به‌روز می‌کند.</DialogDescription>{draft&&<form onSubmit={submit}><fieldset disabled={busy} className="flow-fieldset"><div className="formgrid">
 {mode==='material'&&<><Input label="کد ثابت کالا (۲ تا ۱۲ رقم)" value={draft.code} onChange={v=>change('code',v)} required/><Input label="نام کالا" value={draft.name} onChange={v=>change('name',v)} required/><Select label="واحد" value={draft.unit} onChange={v=>change('unit',v)} options={['عدد','کیلوگرم','گرم','متر','سانتی‌متر','سانتی‌متر مربع','لیتر'].map(v=>[v,v])}/><Input label="مشخصات فنی / نقشه مرجع" value={draft.specs} onChange={v=>change('specs',v)} type="textarea"/><Input label="محل معمول: راهرو-قفسه-طبقه-خانه" value={draft.defaultLocation} onChange={v=>change('defaultLocation',v)}/><Input label="حد سفارش" value={draft.reorderPoint} onChange={v=>change('reorderPoint',v)} type="number"/><Input label="موجودی هدف" value={draft.targetStock} onChange={v=>change('targetStock',v)} type="number"/>{[['qcOwner','qc'],['warehouseOwner','inventory'],['procurementOwner','procurement']].map(([key,role])=><Select key={key} label={'مسئول '+roleNames[role]+' (خالی = کارتابل واحد)'} value={draft[key]} onChange={v=>change(key,v)} options={state.members.filter((m:any)=>m.roles.includes(role)).map((m:any)=>[m.id,m.name])}/>)}</>}
 {mode==='receipt'&&<><Select label="کالا" value={draft.materialId} onChange={v=>setDraft({...draft,...newReceipt(v)})} options={materialOptions}/><SolarDate label="تاریخ ورود" value={draft.day} onChange={v=>change('day',v)}/><Input label="مقدار ورودی" type="number" value={draft.quantity} onChange={v=>change('quantity',v)} required/>{[['supplier','تأمین‌کننده'],['maker','سازنده'],['manufacturerLot','لات سازنده (این محموله)'],['purchase','شماره خرید / فاکتور (این محموله)'],['specs','مشخصات فنی این بچ'],['notes','تفاوت با بچ قبلی / توضیحات']].map(([key,label])=><Input key={key} label={label} value={draft[key]} onChange={v=>change(key,v)} required={key==='supplier'}/>)}<label className="field"><span>تاریخ انقضا دارد</span><input type="checkbox" checked={!!draft.expiry} onChange={e=>change('expiry',e.target.checked?tehranDay():'')}/></label>{draft.expiry&&<SolarDate label="انقضا" value={draft.expiry} onChange={v=>change('expiry',v)}/>}<p className="subtle">کد بچ جدید خودکار ساخته می‌شود. نتیجه کنترل و فایل‌های محموله قبلی کپی نمی‌شوند.</p></>}
 {mode==='incoming_qc'&&<>{(find(draft.receiptId)?.data.fields||[]).map((f:any)=><label className="field" key={f.key}><span>{f.label} {f.unit} {f.required?'*':''}</span>{f.type==='result'?<select value={draft.values[f.key]||''} required={f.required} onChange={e=>change('values',{...draft.values,[f.key]:e.target.value})}><option value="">آزمون نشده</option><option value="pass">تأیید</option><option value="fail">مردود</option></select>:<input required={f.required} value={draft.values[f.key]||''} onChange={e=>change('values',{...draft.values,[f.key]:e.target.value})}/>}<small>حد پذیرش: {f.min||'—'} تا {f.max||'—'}</small></label>)}<Input label="تعداد پذیرفته‌شده" type="number" value={draft.accepted} onChange={v=>change('accepted',v)} required/><Input label="تعداد ردشده" type="number" value={draft.rejected} onChange={v=>change('rejected',v)} required/><Input label="شرح بررسی و تفکیک بخش پذیرفته / ردشده" value={draft.notes} onChange={v=>change('notes',v)} type="textarea" required/></>}
 {mode==='shelve'&&<><p>پذیرفته‌شده: {n(find(draft.receiptId)?.data.accepted/1000)}؛ بخش ردشده در قرنطینه می‌ماند.</p><Input label="محل: راهرو-قفسه-طبقه-خانه" value={draft.location} onChange={v=>change('location',v)} required/></>}
 {['request','supply'].includes(mode)&&<><Select label="کالا" value={draft.materialId} onChange={v=>change('materialId',v)} options={materialOptions}/><Input label="مقدار" type="number" value={draft.quantity} onChange={v=>change('quantity',v)} required/>{mode==='request'&&<Select label="برنامه تولید مرتبط (اختیاری)" value={draft.planId} onChange={v=>change('planId',v)} options={plans.map((p:any)=>[p.id,(rec(p.data.productId)?.data.name||'')+' · '+when(p.data.day)])}/>}<Input label="توضیحات" type="textarea" value={draft.notes} onChange={v=>change('notes',v)}/></>}
 {mode==='supply_close'&&<Input label="نتیجه اقدام تأمین" type="textarea" value={draft.result} onChange={v=>change('result',v)} required/>}
 {['capacity','plan'].includes(mode)&&<Select label="محصول" value={draft.productId} onChange={v=>{const c=find('capacity:'+v);setDraft({...draft,productId:v,...(mode==='capacity'?{capacity:c?.data.capacity||'',smallLabels:c?.data.smallLabels??3,revision:c?.revision||0}:{count:capacitySuggestion(v).count||''})})}} options={rows.filter((r:any)=>r.kind==='product').map((r:any)=>[r.id,r.data.name+' · '+r.data.model])}/>}
 {mode==='capacity'&&<><Input label="ظرفیت دستگاه در روز" type="number" value={draft.capacity} onChange={v=>change('capacity',v)} required/><Input label="تعداد برچسب کوچک برای هر دستگاه" type="number" value={draft.smallLabels} onChange={v=>change('smallLabels',v)} required/></>}
 {mode==='plan'&&<>{draft.productId&&<p className="notice">ظرفیت: {n(capacitySuggestion(draft.productId).capacity)} · برنامه امروز: {n(capacitySuggestion(draft.productId).booked)} · کار ناتمام: {n(capacitySuggestion(draft.productId).unfinished)} · قابل تأمین از مواد پس از نیاز باز: {n(capacitySuggestion(draft.productId).materials)} · پیشنهاد: {n(capacitySuggestion(draft.productId).count)}</p>}<Input label="تعداد تأییدشده برای امروز" type="number" value={draft.count} onChange={v=>change('count',v)} required/><Input label="نسخه طراحی" value={draft.design} onChange={v=>change('design',v)} required/><Input label="نسخه نرم‌افزار" value={draft.firmware} onChange={v=>change('firmware',v)}/><Input label="دلیل تغییر پیشنهاد / عبور از ظرفیت" value={draft.reason} onChange={v=>change('reason',v)}/></>}
 {mode==='assign'&&<><Input label="نام مونتاژکار" value={draft.assembler} onChange={v=>change('assembler',v)} required/><Input label="علت تغییر تخصیص قبلی" value={draft.reason} onChange={v=>change('reason',v)}/><div>{builds.filter((b:any)=>b.data.planId===draft.planId&&b.data.state==='planned').map((b:any)=><label className="flow-check" key={b.id}><input type="checkbox" checked={draft.deviceIds.includes(b.id)} onChange={e=>change('deviceIds',e.target.checked?[...draft.deviceIds,b.id]:draft.deviceIds.filter((id:string)=>id!==b.id))}/>{serial(b.id)} · {b.data.assembler||'بدون مسئول'}</label>)}</div></>}
 {(['issue','prepare'].includes(mode)||mode==='build'&&find(draft.deviceId)?.data.workflowVersion!==2)&&<div className="wide">{draft.allocations.map((a:any,i:number)=><div className="flow-allocation" key={i}>{mode==='issue'?<Select label="بچ و محل برداشت" value={a.location} onChange={v=>{const c=candidates(find(draft.requestId)?.data.materialId).find((c:any)=>c.location===v);change('allocations',draft.allocations.map((x:any,j:number)=>j===i?{...x,location:v,batchId:c?.batch_id||''}:x))}} options={candidates(find(draft.requestId)?.data.materialId).map((c:any)=>[c.location,serial(c.batch_id)+' · '+c.location+' · موجودی '+n(c.quantity/1000)])}/>:<><Select label="کد قطعه BOM" value={a.partCode} onChange={v=>change('allocations',draft.allocations.map((x:any,j:number)=>j===i?{...x,partCode:v,batchId:''}:x))} options={JSON.parse(state.boms.find((x:any)=>x.id===find(draft.deviceId)?.data.bomId)?.lines||'[]').map((l:any)=>[l.partCode,l.name+' · '+l.partCode])}/><Select label="بچ مصرفی از خط" value={a.batchId} onChange={v=>change('allocations',draft.allocations.map((x:any,j:number)=>j===i?{...x,batchId:v}:x))} options={receipts.filter((r:any)=>rec(r.id)?.data.partCode===a.partCode&&stock(r.id)>0).map((r:any)=>[r.id,serial(r.id)+' · موجودی '+n(stock(r.id)/1000)])}/></>}<Input label="مقدار واقعی" type="number" value={a.quantity} onChange={v=>change('allocations',draft.allocations.map((x:any,j:number)=>j===i?{...x,quantity:v}:x))} required/><button className="btn" type="button" onClick={()=>change('allocations',draft.allocations.filter((_:any,j:number)=>j!==i))}>حذف ردیف</button></div>)}<button type="button" className="btn" onClick={()=>change('allocations',[...draft.allocations,{batchId:'',location:'',partCode:'',quantity:''}])}>افزودن بچ دیگر</button><Input label={mode==='issue'?'دلیل فنی تغییر اولویت بچ':'توضیح تفاوت مقدار مصرف یا تغییر بچ پیشنهادی'} value={draft[mode==='issue'?'reason':'notes']} onChange={v=>change(mode==='issue'?'reason':'notes',v)} type="textarea"/></div>}
 {mode==='build'&&find(draft.deviceId)?.data.workflowVersion===2&&<div className="wide"><p className="notice">با تأیید برگ تولید، مصرف این بچ‌ها از خط تولید کسر می‌شود. کنترل کیفیت: {find(draft.deviceId)?.data.latestQc?.by} · BOM متصل به سریال حفظ می‌شود.</p>{draft.allocations.map((a:any)=><p key={a.batchId}>{serial(a.batchId)} · {a.quantity}</p>)}</div>}
 {['reject','repair'].includes(mode)&&<>{mode==='repair'&&<Select label="بچ قطعه خارج‌شده از دستگاه" value={draft.oldBatchId} onChange={v=>change('oldBatchId',v)} options={(find(draft.deviceId)?.data.materials||[]).filter((m:any)=>m.quantity>0).map((m:any)=>[m.batchId,serial(m.batchId)+' · نصب‌شده '+n(m.quantity/1000)])}/>}<Select label={mode==='repair'?'بچ قطعه جایگزین از خط':'بچ نامنطبق از خط'} value={draft[mode==='repair'?'newBatchId':'batchId']} onChange={v=>change(mode==='repair'?'newBatchId':'batchId',v)} options={receipts.filter((r:any)=>stock(r.id)>0).map((r:any)=>[r.id,materialName(r.data.materialId)+' · '+serial(r.id)+' · '+n(stock(r.id)/1000)])}/><Input label="تعداد" type="number" value={draft.quantity} onChange={v=>change('quantity',v)} required/>{mode==='repair'&&<Select label="علت احتمالی" value={draft.cause} onChange={v=>change('cause',v)} options={[["part","قطعه"],["assembly","مونتاژ"],["design","طراحی"],["test","آزمون"],["unknown","نامشخص"]]}/>}<Input label="شرح ایراد و اقدام" type="textarea" value={draft.reason} onChange={v=>change('reason',v)} required/></>}
 </div>
 {mode==='material'&&<section><h3>فرم کنترل کیفیت ورودی</h3>{draft.fields.map((f:QField,i:number)=>{const patch=(d:any)=>change('fields',draft.fields.map((v:any,j:number)=>j===i?{...v,...d}:v));return <div className="flow-card" key={i}><div className="formgrid"><Input label="عنوان معیار" value={f.label} onChange={v=>patch({label:v})} required/><Input label="کد انگلیسی یکتا" value={f.key} onChange={v=>patch({key:v})} required/><Select label="نوع" value={f.type} onChange={v=>patch({type:v})} options={[["number","عدد"],["text","متن"],["result","قبول / رد"]]}/>{f.type==='number'&&<><Input label="واحد" value={f.unit} onChange={v=>patch({unit:v})}/><Input label="حد پایین" value={f.min} onChange={v=>patch({min:v})}/><Input label="حد بالا" value={f.max} onChange={v=>patch({max:v})}/></>}</div><label className="flow-check"><input type="checkbox" checked={f.required} onChange={e=>patch({required:e.target.checked})}/>الزامی</label><button className="btn" type="button" disabled={draft.fields.length===1} onClick={()=>change('fields',draft.fields.filter((_:any,j:number)=>j!==i))}>حذف معیار</button></div>})}<button type="button" className="btn" onClick={()=>change('fields',[...draft.fields,blankField('check_'+crypto.randomUUID().slice(0,8))])}>افزودن معیار</button></section>}
 {error&&<p className="notice error" role="alert">{error}</p>}<div className="tools" style={{marginTop:20}}><button className="btn primary" disabled={busy}>{busy?'در حال ثبت…':'تأیید و ثبت'}</button><button type="button" className="btn" disabled={busy} onClick={()=>setDraft(null)}>انصراف</button></div></fieldset></form>}</DialogContent></Dialog>
 <Dialog open={!!qc} onOpenChange={v=>{if(!v){setQc('');void load()}}}><DialogContent className="modal sm:max-w-3xl"><DialogTitle>کنترل کیفیت {serial(qc)}</DialogTitle><DialogDescription>هر آزمون و مردودی اولیه جداگانه نگهداری می‌شود.</DialogDescription>{qc&&<QualityPanel key={qc} id={qc} fixedTemplateId={find(qc)?.data.templateId} mode="device" demo={false} write={has('qc')} onSaved={()=>{void load();onSaved()}}/>}</DialogContent></Dialog>
 <Dialog open={!!fileBatch} onOpenChange={v=>!v&&setFileBatch('')}><DialogContent className="modal sm:max-w-2xl"><DialogTitle>مدارک بچ {serial(fileBatch)}</DialogTitle><DialogDescription>فایل‌های این محموله و نتایج کنترل ورودی</DialogDescription>{fileBatch&&<BatchFilesPanel batchId={fileBatch} demo={false} write={has('inventory')||has('qc')}/>}</DialogContent></Dialog>
 </section>;
}
