'use client';
import {useState} from 'react';
import type {Session} from '@/lib/permissions';
import {PasswordField} from './password-field';
export function MyAccount({user,onChanged,onLogout}:{user:Session;onChanged:()=>void;onLogout:()=>void}){
 const [current,setCurrent]=useState(''),[next,setNext]=useState(''),[repeat,setRepeat]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <section className="panel inside my-account-panel" dir="rtl"><h2>{user.mustChangePassword?'تعیین رمز شخصی برای ادامه ورود':'حساب من · تغییر رمز عبور'}</h2><p>{user.name} <span dir="ltr">{user.username}</span></p>
 {user.authType!=='password'?<p className="notice">این حساب از ورود مدیر / حساب قدیمی استفاده می‌کند و رمز محلی ندارد.</p>:<>
 <p className="notice">{user.mustChangePassword?'برای ورود به بخش‌های کاری، رمز اولیه‌ای را که دریافت کرده‌اید تغییر دهید. ':''}مدیر سامانه با تأیید هویت و ثبت سابقه می‌تواند رمز جدید را مشاهده کند. رمز مخصوص همین سامانه انتخاب کنید.</p>
 <form onSubmit={async e=>{e.preventDefault();if(busy)return;setError('');if(next!==repeat){setError('رمز جدید و تکرار آن یکسان نیستند.');return;}setBusy(true);try{const r=await fetch('/api/auth/password',{method:'POST',headers:{'Content-Type':'application/json','x-assistant-account':user.userId},body:JSON.stringify({currentPassword:current,newPassword:next,repeatPassword:repeat,confirmed:true})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||'تغییر رمز انجام نشد.');setCurrent('');setNext('');setRepeat('');onChanged();}catch(e){setError(e instanceof Error?e.message:'تغییر رمز انجام نشد.');}finally{setBusy(false)}}}>
 <fieldset disabled={busy} className="password-form-fields"><PasswordField label="رمز فعلی" required autoComplete="current-password" maxLength={128} value={current} onChange={e=>setCurrent(e.target.value)}/><PasswordField label="رمز جدید؛ حداقل ۱۰ نویسه" required autoComplete="new-password" minLength={10} maxLength={128} value={next} onChange={e=>setNext(e.target.value)}/><PasswordField label="تکرار رمز جدید" required autoComplete="new-password" minLength={10} maxLength={128} value={repeat} onChange={e=>setRepeat(e.target.value)}/><p className="subtle">پس از ذخیره، نشست‌های قبلی بسته می‌شوند و با رمز جدید وارد می‌شوید.</p>{error&&<p className="notice error" role="alert">{error}</p>}<button className="btn primary">{busy?'در حال ذخیره…':'ذخیره رمز جدید'}</button></fieldset></form></>}
 {user.mustChangePassword&&<button type="button" className="btn" style={{marginTop:16}} disabled={busy} onClick={onLogout}>خروج از حساب</button>}</section>;
}
