'use client';
import {ProgramWorkspace,SubprogramNavigation} from "./program-workspace";
import {BomImport} from './bom-import';
import {SolarDate} from './solar-date';
import {formatDate,localDay} from '@/lib/persian-date';
import {useEffect,useState} from 'react';
import {type Row,label} from '@/lib/model';
import type {Session} from '@/lib/permissions';
import {warehouses,warehouseName,type BomLine} from '@/lib/production';
const number=(n:number)=>new Intl.NumberFormat('fa-IR',{maximumFractionDigits:3}).format(n);
const day=(s:string)=>formatDate(s);
const empty={materialCatalog:[],boms:[],balances:[],initialized:[],orders:[],materials:[],operations:[]} as any;
export function ProductionPanel({records,user,demo,onSaved,view='production',productId}:{records:Row[];user:Session;demo:boolean;onSaved:()=>void;view?:'production'|'stock'|'bom';productId?:string}){
 const [data,setData]=useState<any>(empty),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [device,setDevice]=useState(''),[date,setDate]=useState(localDay()),[operator,setOperator]=useState(user.name||''),[notes,setNotes]=useState(''),[alloc,setAlloc]=useState<Record<string,{batchId:string;warehouse:string}>>({});
 const [product,setProduct]=useState(productId||''),[bomLines,setBomLines]=useState<BomLine[]>([]),[previousVersion,setPreviousVersion]=useState(0);
 const [batch,setBatch]=useState(''),[amount,setAmount]=useState(''),[from,setFrom]=useState('raw'),[to,setTo]=useState('line');
 const [stockFilter,setStockFilter]=useState('all');
 const read=(k:any)=>user.permissions.read.includes(k),write=(k:any)=>user.permissions.write.includes(k);
 const productionWrite=user.isAdmin||(write('event')&&read('device')&&read('batch')&&read('product')&&user.permissions.eventStages.includes('مونتاژ'));
 const find=(id:string)=>records.find(r=>r.id===id),batches=records.filter(r=>r.kind==='batch');
 const latest=(id:string)=>data.boms.filter((b:any)=>b.product_id===id).sort((a:any,b:any)=>b.version-a.version)[0];
 const selectedDevice=find(device),bom=latest(selectedDevice?.data.product||'');const lines:BomLine[]=bom?JSON.parse(bom.lines):[];
 const initialized=data.initialized.some((r:any)=>r.batch_id===batch);
 async function reload(){if(demo){setData(empty);setLoading(false);return;}setLoading(true);try{const r=await fetch('/api/production');const d=await r.json() as any;if(!r.ok)throw new Error(d.error);setData(d);setError('');}catch(e){setError(e instanceof Error?e.message:'دریافت ممکن نشد.');}finally{setLoading(false);}}
 useEffect(()=>{void reload()},[demo]);
 useEffect(()=>{const b=latest(product);setBomLines(b?JSON.parse(b.lines):[]);setPreviousVersion(b?.version||0)},[product,data.boms]);
 async function save(body:any){if(demo){setError('برای ثبت، وارد محیط اطلاعات شرکت شوید.');return;}if(busy)return;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/production',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,id:crypto.randomUUID()})});const d=await r.json() as any;if(!r.ok)throw new Error(d.error);await reload();onSaved();setMessage(d.repeated?'این انتقال قبلاً انجام شده است.':'اطلاعات با موفقیت ثبت شد.');if(body.mode==='order'){setDevice('');setAlloc({});setNotes('');}if(body.mode==='move'||body.mode==='opening')setAmount('');}catch(e){setError(e instanceof Error?e.message:'ذخیره نشد.')}finally{setBusy(false);}}
 const input=(title:string,value:string,set:(v:string)=>void,type='text')=>type==='date'?<SolarDate label={title} value={value} onChange={set}/>:<label className="field"><span>{title}</span><input type={type} value={value} onChange={e=>set(e.target.value)} required/></label>;
 return <ProgramWorkspace programId={"production:"+view} title="انبارها و موجودی" direct={view!=="stock"}><section className="panel"><div className="panelhead"><div><h2>{view==='production'?'برگ تولید و انتقال محصول':view==='stock'?'انبارها و موجودی':'فهرست مواد محصول (BOM)'}</h2><p className="subtle">{view==='production'?'۱. ثبت برگ تولید برای سریال دستگاه  ۲. انتقال محصول نهایی و کسر خودکار مواد':view==='stock'?'موجودی هر بچ به تفکیک انبار؛ مقادیر تا سه رقم اعشار':'مقدار مصرف هر قطعه برای ساخت یک دستگاه؛ هر ذخیره یک نسخه جدید است.'}</p></div><button className="btn" disabled={loading||busy} onClick={()=>void reload()}>تازه‌سازی</button></div><div className="inside">
 {demo&&<p className="notice">این بخش با موجودی واقعی شرکت کار می‌کند. برای ثبت، از بالای صفحه «اطلاعات شرکت» را انتخاب کنید.</p>}{error&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}{loading?<p>در حال دریافت…</p>:<>
 {view==='bom'&&<><label className="field"><span>محصول</span><select value={product} disabled={!!productId} onChange={e=>setProduct(e.target.value)}><option value="">انتخاب محصول</option>{records.filter(r=>r.kind==='product').map(r=><option key={r.id} value={r.id}>{label(r)}</option>)}</select></label>{(user.isAdmin||write('product')&&user.permissions.flowRoles?.includes('inventory'))&&<BomImport productId={product} previousVersion={previousVersion} disabled={demo||busy} onSaved={()=>{void reload();onSaved()}}/>}<p className="subtle">نسخه جاری: {number(previousVersion)} — کد قطعه و واحد باید دقیقاً با بچ‌های انبار یکسان باشند.</p>{bomLines.map((l,i)=><div className="bomline" key={i}><label className="field"><span>انتخاب از شناسنامه مواد اولیه</span><select disabled={!write('product')||busy} value={(data.materialCatalog||[]).some((m:any)=>m.data.code===l.partCode)?l.partCode:''} onChange={e=>{const m=data.materialCatalog.find((m:any)=>m.data.code===e.target.value);if(m)setBomLines(bomLines.map((v,n)=>n===i?{...v,partCode:m.data.code,name:m.data.name,unit:m.data.unit}:v))}}><option value="">انتخاب کالا</option>{(data.materialCatalog||[]).map((m:any)=><option key={m.id} value={m.data.code}>{m.data.code} · {m.data.name}</option>)}</select></label>{(['partCode','name','quantity'] as const).map((k,j)=><label className="field" key={k}><span>{['کد ثابت قطعه','نام قطعه','مقدار برای یک دستگاه'][j]}</span><input disabled={!write('product')||busy} value={l[k]} onChange={e=>setBomLines(bomLines.map((v,n)=>n===i?{...v,[k]:e.target.value}:v))}/></label>)}<label className="field"><span>واحد</span><select disabled={!write('product')||busy} value={l.unit} onChange={e=>setBomLines(bomLines.map((v,n)=>n===i?{...v,unit:e.target.value}:v))}>{['عدد','کیلوگرم','گرم','متر','سانتی‌متر','سانتی‌متر مربع','لیتر'].map(v=><option key={v}>{v}</option>)}</select></label>{write('product')&&<button className="btn" onClick={()=>setBomLines(bomLines.filter((_,n)=>n!==i))}>حذف ردیف</button>}</div>)}{write('product')&&<div className="tools"><button className="btn" disabled={busy||bomLines.length>=200} onClick={()=>setBomLines([...bomLines,{partCode:'',name:'',quantity:'1',unit:'عدد'}])}>افزودن قطعه</button><button className="btn primary" disabled={busy||demo||!product||!bomLines.length} onClick={()=>void save({mode:'bom',productId:product,previousVersion,lines:bomLines})}>ذخیره نسخه BOM</button></div>}</>}
 {view==='production'&&<>{productionWrite&&<form onSubmit={e=>{e.preventDefault();void save({mode:'order',deviceId:device,bomId:bom?.id,day:date,operator,notes,allocations:lines.map(l=>({partCode:l.partCode,...alloc[l.partCode]}))})}}><div className="formgrid"><label className="field wide"><span>سریال دستگاه</span><select required value={device} onChange={e=>{setDevice(e.target.value);setAlloc({})}}><option value="">دستگاه ثبت‌شده را انتخاب کنید</option>{records.filter(r=>r.kind==='device'&&!data.orders.some((o:any)=>o.device_id===r.id)&&!records.some(e=>e.kind==='event'&&e.data.device===r.id&&e.data.stage==='مصرف قطعه')).map(r=><option value={r.id} key={r.id}>{r.data.code} — {r.data.productName||r.data.model}</option>)}</select></label>{input('تاریخ برگ تولید',date,setDate,'date')}{input('مسئول تولید',operator,setOperator)}<label className="field wide"><span>توضیحات برگ تولید</span><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label></div>{device&&!bom&&<p className="notice error">این محصول BOM ندارد. از «تعریف محصولات ← مشاهده محصول ← فهرست مواد» آن را تعریف کنید.</p>}{bom&&<><p>نسخه BOM: {number(bom.version)} · مقدار مواد برای یک دستگاه</p>{lines.map(l=><div className="bomline" key={l.partCode}><div><strong>{l.name}</strong><p className="subtle">{l.partCode} · {l.quantity} {l.unit}</p></div><label className="field"><span>بچ مصرفی</span><select required value={alloc[l.partCode]?.batchId||''} onChange={e=>setAlloc({...alloc,[l.partCode]:{warehouse:alloc[l.partCode]?.warehouse||'line',batchId:e.target.value}})}><option value="">انتخاب بچ تأییدشده</option>{batches.filter(b=>b.data.partCode===l.partCode&&b.data.unit===l.unit&&b.data.status==='تأیید').map(b=><option key={b.id} value={b.id}>{b.data.code} — {b.data.supplier}</option>)}</select></label><label className="field"><span>انبار مصرف</span><select value={alloc[l.partCode]?.warehouse||'line'} onChange={e=>setAlloc({...alloc,[l.partCode]:{batchId:alloc[l.partCode]?.batchId||'',warehouse:e.target.value}})}><option value="line">خط تولید</option><option value="raw">مواد اولیه</option></select></label><span>موجودی: {number((data.balances.find((b:any)=>b.item_id===alloc[l.partCode]?.batchId&&b.warehouse===(alloc[l.partCode]?.warehouse||'line'))?.quantity||0)/1000)}</span></div>)}</>}<p className="subtle">ثبت برگ تولید هنوز مواد را کسر یا رزرو نمی‌کند؛ کسر قطعات فقط با انتقال محصول نهایی انجام می‌شود.</p><button className="btn primary" disabled={busy||demo||!device||!bom}>ثبت برگ تولید</button></form>}
 <h3 style={{marginTop:28}}>برگ‌های تولید</h3>{!data.orders.length&&<p className="subtle">هنوز برگ تولیدی ثبت نشده است. ابتدا دستگاه را با سریال در «شناسنامه دستگاه‌ها» ثبت کنید.</p>}{data.orders.map((o:any)=><article className="production-order" key={o.id}><div className="tools"><strong>{find(o.device_id)?.data.code||o.device_id}</strong><span>{day(o.day)} · {o.operator}</span><span className="badge">{o.transferred?'در انبار محصول نهایی':'برگ تولید ثبت شده'}</span></div><p>{o.notes}</p><details><summary>مواد و بچ‌های برگ تولید</summary>{data.materials.filter((m:any)=>m.order_id===o.id).map((m:any)=><p key={m.id}>{find(m.batch_id)?.data.part} · {find(m.batch_id)?.data.code||m.batch_id} · {number(m.quantity/1000)} {find(m.batch_id)?.data.unit} · {warehouseName(m.warehouse)}</p>)}</details>{!o.transferred&&productionWrite&&<button className="btn primary" disabled={busy||demo} onClick={()=>{if(window.confirm('مواد طبق BOM کسر و این دستگاه وارد انبار محصول نهایی شود؟'))void save({mode:'finish',orderId:o.id})}}>انتقال به انبار محصول نهایی</button>}</article>)}</>}
 {view==='stock'&&<><SubprogramNavigation items={[["all","همه انبارها"],...warehouses.map(w=>[w.id,w.name] as [string,string])]} value={stockFilter} onChange={setStockFilter}/><div style={{overflowX:'auto',margin:'20px 0'}}><table className="stocktable"><thead><tr><th>کالا / سریال</th><th>بچ</th><th>انبار</th><th>موجودی</th><th>واحد</th></tr></thead><tbody>{data.balances.filter((b:any)=>stockFilter==='all'||b.warehouse===stockFilter).map((b:any)=>{const r=JSON.parse(b.payload);return <tr key={b.id}><td>{b.kind==='device'?r.code:r.part}</td><td>{b.kind==='batch'?r.code:'—'}</td><td>{warehouseName(b.warehouse)}</td><td>{number(b.quantity/1000)}</td><td>{b.kind==='device'?'دستگاه':r.unit}</td></tr>})}</tbody></table></div>{!data.balances.length&&<p className="notice">هنوز موجودی آغازین ثبت نشده است؛ مقدار ورود بچ به‌تنهایی موجودی قابل‌مصرف محسوب نمی‌شود.</p>}
 {write('batch')&&<form onSubmit={e=>{e.preventDefault();void save({mode:initialized?'move':'opening',batchId:batch,quantity:amount,to,...(initialized?{from}:{})})}}><h3>ورود موجودی / انتقال بین انبارها</h3><p className="subtle">قطعات واسط تأییدشده در نیمه‌ساخته (۳۵۱) نگهداری می‌شوند. برای مصرف، مقدار لازم را به خط منتقل کنید. انتقال، مصرف یا تولید دوباره محسوب نمی‌شود.</p><div className="formgrid"><label className="field wide"><span>بچ کالا</span><select required value={batch} onChange={e=>{setBatch(e.target.value);setAmount('')}}><option value="">انتخاب بچ</option>{batches.map(b=><option key={b.id} value={b.id}>{b.data.code} — {b.data.part}</option>)}</select></label>{initialized&&<label className="field"><span>انبار مبدأ</span><select value={from} onChange={e=>setFrom(e.target.value)}>{warehouses.filter(w=>w.id!=='finished').map(w=><option value={w.id} key={w.id}>{w.name}</option>)}</select></label>}<label className="field"><span>انبار مقصد</span><select value={to} onChange={e=>setTo(e.target.value)}>{warehouses.filter(w=>w.id!=='finished').map(w=><option value={w.id} key={w.id}>{w.name}</option>)}</select></label>{input('مقدار ('+(find(batch)?.data.unit||'واحد بچ')+')',amount,setAmount)}</div>{!initialized&&<p className="notice">ادمین باید موجودی واقعی باقی‌مانده این بچ را یک‌بار تأیید کند. این مقدار را با شمارش انبار تطبیق دهید؛ مصرف‌های قدیمی نباید دوباره موجودی شوند.</p>}<button className="btn primary" disabled={busy||demo||!batch||(!initialized&&!user.isAdmin)}>{initialized?'ثبت انتقال مواد':'تأیید و ثبت موجودی آغازین'}</button></form>}</>}
 </>}</div></section></ProgramWorkspace>;
}
