'use client';
import {IconDisclosure,IconActions} from "./program-workspace";
import {IconSections} from "./program-workspace";
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {SolarDate} from './solar-date';
import {formatDate,formatDateTime,localDay,latinDigits} from '@/lib/persian-date';
const money=(v:any)=>Number(v||0).toLocaleString('fa-IR',{maximumFractionDigits:2})+' ریال';
const names:Record<string,string>={dispute:'تعیین مبلغ اختلاف و توقف آن',clear_dispute:'رفع اختلاف',close_advance:'بستن مانده برنامه پیش‌پرداخت',create:'پرونده خرید جدید',invoice:'ثبت / اصلاح فاکتور',match:'تطبیق رسیدهای انبار',payment:'ثبت پرداخت انجام‌شده',recognize:'تأیید بدهی',unrecognize:'برگشت تأیید بدهی',allocate:'تخصیص پرداخت به فاکتور',schedule:'شرایط و اقساط پرداخت',release:'اجازه پرداخت',hold:'توقف پرداخت',advance:'برنامه پیش‌پرداخت',release_advance:'اجازه پیش‌پرداخت',issue:'پیگیری نقص و مدرک',resolve_issue:'تأیید رفع نقص',void:'ابطال مستند'};
export function PurchasePayablesPanel(){
 const [data,setData]=useState<any>(null),[selected,setSelected]=useState(''),[draft,setDraft]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){const r=await fetch('/api/purchase-payables',{cache:'no-store'}),d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 const c=data?.cases.find((x:any)=>x.id===selected),d=c?.data,v=c?.view;
 const orders=data?.orders.filter((o:any)=>o.data.supplierId===d?.supplierId&&o.data.route===d?.route&&o.data.state!=='cancelled')||[];
 const title=(o:any)=>o.data.partCode+' · '+(o.data.quantity/1000).toLocaleString('fa-IR')+' '+o.data.unit+' · '+o.id;
 function begin(mode:string,extra:any={}){setError('');setDraft({mode,id:crypto.randomUUID(),confirmed:true,caseId:c?.id,revision:c?.revision||0,notes:'',day:localDay(),lines:[],schedule:[],...extra});}
 const field=(k:string,value:any)=>setDraft((x:any)=>({...x,[k]:value}));
 const text=(k:string,label:string,numeric=false,required=true)=><label className="field">{label}<input required={required} value={draft[k]||''} inputMode={numeric?'decimal':undefined} onChange={e=>field(k,numeric?latinDigits(e.target.value):e.target.value)}/></label>;
 const pick=(k:string,label:string,options:any[],required=true)=><label className="field">{label}<select required={required} value={draft[k]||''} onChange={e=>field(k,e.target.value)}><option value="">انتخاب کنید</option>{options.map((o:any)=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select></label>;
 const btn=(mode:string,label:string,extra:any={},disabled=false)=><button className="btn" disabled={disabled||busy} onClick={()=>begin(mode,extra)}>{label}</button>;
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/purchase-payables',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)}),out:any=await r.json();if(!r.ok)throw Error(out.error);await load();setSelected(out.id);setDraft(null);setMessage('ثبت شد؛ مانده و صف پرداخت به‌روز شدند.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function upload(file:File){if(!c||busy)return;setBusy(true);setError('');try{const q=new URLSearchParams({id:crypto.randomUUID(),caseId:c.id,filename:file.name});const r=await fetch('/api/purchase-payables/files?'+q,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});const out:any=await r.json();if(!r.ok)throw Error(out.error);await load();setMessage('مدرک پیوست شد؛ شناسه آن را در مرجع فاکتور یا پرداخت وارد کنید.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const table=(heads:string[],rows:any[][])=><div style={{overflowX:'auto'}}><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="empty">موردی ثبت نشده است.</p>}</div>;
 if(!data)return <div className="panel"><p role="status">{error||'در حال خواندن بدهی و پرداخت خرید…'}</p><button className="btn" onClick={()=>void load().catch(e=>setError(e.message))}>تلاش دوباره</button></div>;
 const editable=!!c&&data.routes.includes(d.route);
 const allQueue=data.cases.flatMap((x:any)=>[...x.view.invoices.flatMap((i:any)=>i.queue.filter((q:any)=>Number(q.remaining)>0).map((q:any)=>({...q,caseId:x.id,supplier:x.data.supplier,reference:i.reference,kind:'تسویه فاکتور'}))),...x.view.advances.filter((a:any)=>Number(a.remaining)>0).map((a:any)=>({...a,caseId:x.id,supplier:x.data.supplier,reference:a.condition,kind:'پیش‌پرداخت',blockers:a.released?[]:['نیازمند اجازه مالی / رفع مانع']}))]).sort((a:any,b:any)=>a.due.localeCompare(b.due));
 return <section className="panel" dir="rtl"><div className="panelhead"><h2>بدهی و پرداخت خرید</h2><IconActions scope="purchase-payables-panel-actions-406595cdb7">{data.routes.length>0&&btn('create','پرونده جدید',{caseId:undefined,revision:0})}<button className="btn" onClick={()=>void load().catch(e=>setError(e.message))}>تازه‌سازی</button></IconActions></div>
 <p className="notice">مبالغ ریال · ثبت بدهی، اجازه پرداخت و ثبت پرداخت واقعی سه مرحله مستقل‌اند. سند سپیدار یا انتقال بانکی صادر نمی‌شود.</p>
 {error&&!draft&&<p role="alert" className="notice error">{error}</p>}{message&&<p role="status">{message}</p>}
 <IconDisclosure scope="purchase-payables-panel-details-ad546b249d" title={<> راهنمای گردش و دستیار </>}><ul>{data.help.map((h:string)=><li key={h}>{h}</li>)}</ul></IconDisclosure>
 <h3>صف پرداخت همه پرونده‌های مجاز</h3>{table(['تأمین‌کننده','نوع / مرجع','سررسید','مانده','وضعیت','پرونده'],allQueue.map((q:any)=>[q.supplier,q.kind+' / '+q.reference,formatDate(q.due),money(q.remaining),q.released?(q.due<=localDay()?'آماده پرداخت و سررسیدشده':'آماده؛ موعد آینده'):(q.blockers||[]).join(' / '),<button className="btn" onClick={()=>setSelected(q.caseId)}>بازکردن</button>]))}
 <label className="field">پرونده خرید<select value={selected} onChange={e=>{setSelected(e.target.value);setMessage('')}}><option value="">انتخاب کنید</option>{data.cases.map((x:any)=><option key={x.id} value={x.id}>{x.data.supplier} · {x.data.title}</option>)}</select></label>
 {c&&<><h3>{d.title} · {d.supplier}</h3>{d.unassignedWork?.length>0&&<p className="notice">مسئول فعال برای این کارها تعریف نشده است: {d.unassignedWork.join(' / ')}. مدیر، دسترسی نقش مربوط را تکمیل کند.</p>}<p>مانده بدهی تأییدشده: <strong>{money(v.liability)}</strong> · پرداخت تخصیص‌نیافته: <strong>{money(v.unallocated)}</strong></p>
 <div className="tools" style={{flexWrap:'wrap'}}>{editable&&btn('invoice','ثبت فاکتور',{amount:'',reference:'',purpose:'',terms:'',evidence:'',lines:[]})}{data.finance&&<>{btn('payment','ثبت پرداخت واقعی')}{btn('advance','برنامه پیش‌پرداخت')}</>}{editable&&btn('issue','ثبت نقص و ارجاع')}</div>
 <IconSections scope="purchase-payables-panel-sections-1" items={[{key:"section-0",title:"مدارک پرونده",content:<><h3>مدارک پرونده</h3>{editable&&<label className="field">پیوست فاکتور، قرارداد یا رسید پرداخت (حداکثر ۱۰ مگابایت)<input type="file" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value=''}}/></label>}{c.files.map((f:any)=><p key={f.id}><a href={'/api/purchase-payables/files?id='+encodeURIComponent(f.id)}>{f.filename}</a> · مرجع: {f.id}</p>)}
 </>},{key:"section-1",title:"فاکتورها و تطبیق دریافت",content:<><h3>فاکتورها و تطبیق دریافت</h3>{v.invoices.map((i:any)=><article className="flow-card" key={i.id}><h4>فاکتور {i.reference} · {money(i.amount)}</h4><p>{formatDate(i.day)} · {i.recognition?'بدهی تأییدشده':'پیش‌نویس بدهی'} · تخصیص‌شده {money(i.paid)} · مانده {money(i.remaining)} · مبلغ مورد اختلاف {money(i.disputed)}</p><p>هدف: {i.purpose} · شرایط خرید: {i.terms}</p><p>مدرک: {i.evidence||'ناقص'} · پیشنهاد تشخیص: {i.classification.reason}</p>{i.recognition&&<p>حساب: {i.recognition.account} · مبنای شناسایی: {i.recognition.basis}</p>}
 {table(['سفارش / قطعه','مقدار سفارش','فاکتور','دریافت','پذیرفته','مردود'],i.match.lines.map((l:any)=>[l.partCode||l.orderId,(l.ordered||0)/1000,l.invoice/1000,l.received/1000,l.accepted/1000,l.rejected/1000]))}
 {i.blockers.length>0&&<p className="notice">{i.blockers.join(' / ')}</p>}
 <div className="tools" style={{flexWrap:'wrap'}}>{editable&&<>{!i.recognition&&btn('invoice','اصلاح فاکتور',{itemId:i.id,...Object.fromEntries(['reference','day','amount','evidence','purpose','terms','settlementId'].map(k=>[k,i[k]])),lines:i.lines.map((l:any)=>({...l,quantity:String(l.quantity/1000)}))})}{btn('match','انتخاب رسیدهای انبار',{itemId:i.id,lines:i.lines.map((l:any)=>({...l,quantity:String(l.quantity/1000)}))})}</>}{data.finance&&<>{!i.recognition?btn('recognize','تأیید بدهی',{itemId:i.id}):<>{btn('allocate','تخصیص پیش‌پرداخت',{invoiceId:i.id,amount:i.remaining})}{btn('schedule','شرایط / اقساط',{itemId:i.id,schedule:i.schedule.length?i.schedule:[{amount:i.amount,due:'',condition:i.terms}]})}{btn('release','تأیید اجازه پرداخت',{itemId:i.id},!!i.blockers.length||!i.schedule.length)}{btn('hold','توقف پرداخت',{itemId:i.id})}{btn('dispute','تعیین مبلغ اختلاف',{itemId:i.id})}{i.dispute&&btn('clear_dispute','رفع اختلاف',{itemId:i.id})}{btn('unrecognize','برگشت بدهی',{itemId:i.id},Number(i.paid)>0)}</>}{!i.recognition&&btn('void','ابطال فاکتور',{itemId:i.id,kind:'invoices'})}</>}</div>
 <IconDisclosure scope="purchase-payables-panel-details-f780327200" title={<> پیشنهادهای پرداخت برای این فاکتور </>}>{v.payments.filter((p:any)=>Number(p.available)>0&&(!p.orderId||i.lines.some((l:any)=>l.orderId===p.orderId))).map((p:any)=><p key={p.id}>{p.reference} · {formatDate(p.day)} · مانده {money(p.available)} · {p.orderId?'سفارش مشترک':'تأمین‌کننده و پرونده مشترک؛ نیازمند بررسی هدف پرداخت'}</p>)}<p>اتصال خودکار انجام نمی‌شود؛ مرجع، هدف و شرایط را مالی بررسی می‌کند.</p></IconDisclosure></article>)}
 </>},{key:"section-2",title:"پرداخت‌های واقعی",content:<><h3>پرداخت‌های واقعی</h3>{table(['مرجع','تاریخ','هدف','مبلغ','تخصیص‌نیافته',''],v.payments.map((p:any)=>[p.reference,formatDate(p.day),p.purpose,money(p.amount),money(p.available),data.finance&&btn('void','ابطال',{itemId:p.id,kind:'payments'},Number(p.allocated)>0)]))}
 </>},{key:"section-3",title:"تخصیص‌ها",content:<><h3>تخصیص‌ها</h3>{table(['فاکتور','پرداخت','مبلغ',''],d.allocations.filter((a:any)=>!a.voided).map((a:any)=>[d.invoices.find((i:any)=>i.id===a.invoiceId)?.reference,d.payments.find((p:any)=>p.id===a.paymentId)?.reference,money(a.amount),data.finance&&btn('void','برگشت تخصیص',{itemId:a.id,kind:'allocations'})]))}
 </>},{key:"section-4",title:"برنامه‌های پیش‌پرداخت",content:<><h3>برنامه‌های پیش‌پرداخت</h3>{table(['شرط / قرارداد','سررسید','مبلغ','مانده',''],v.advances.map((a:any)=>[a.condition,formatDate(a.due),money(a.amount),money(a.remaining),data.finance&&<>{!a.closed&&btn('close_advance','بستن مانده برنامه',{itemId:a.id})}{btn('release_advance','اجازه پیش‌پرداخت',{itemId:a.id},!!a.closed)}{btn('payment','ثبت پرداخت انجام‌شده',{advanceId:a.id,orderId:a.orderId,amount:a.remaining,purpose:a.condition})}{btn('void','ابطال برنامه',{kind:'advances',itemId:a.id})}</>]))}
 </>},{key:"section-5",title:"نواقص و پیگیری",content:<><h3>نواقص و پیگیری</h3>{table(['موضوع','مسئول','موعد','وضعیت',''],d.issues.filter((x:any)=>!x.voided).map((x:any)=>[x.title,data.members.find((m:any)=>m.id===x.ownerId)?.name||x.ownerId,formatDate(x.due),x.state==='resolved'?'رفع‌شده':x.due<localDay()?'باز و عقب‌افتاده':'باز',data.finance&&x.state!=='resolved'&&btn('resolve_issue','تأیید رفع نقص',{itemId:x.id})]))}
 <IconDisclosure scope="purchase-payables-panel-details-9c7bba813b" title={<> سابقه عملیات </>}>{d.history.map((h:any,n:number)=><p key={n}>{formatDateTime(h.at)} · {names[h.mode]||h.mode} · {h.notes}</p>)}</IconDisclosure></>}]}/></>}
 <Dialog open={!!draft} onOpenChange={o=>!o&&!busy&&setDraft(null)}><DialogContent style={{maxWidth:980,maxHeight:'92vh',overflow:'auto'}}><DialogTitle>{names[draft?.mode]||'بررسی'}</DialogTitle><DialogDescription>اطلاعات و مرجع واقعی را بررسی کنید؛ دکمه تأیید همین عملیات را ثبت می‌کند.</DialogDescription>{draft&&<form onSubmit={save}><div className="form-grid">
 {draft.mode==='create'&&<>{text('title','عنوان خرید / محموله')}{pick('supplierId','تأمین‌کننده',data.suppliers.map((s:any)=>[s.id,s.name]))}{pick('route','مسیر خرید',data.routes.map((r:string)=>[r,r==='domestic'?'داخلی':'خارجی']))}<p>برای پرداخت قبلی همین خرید، پرونده موجود را انتخاب کنید.</p></>}
 {['invoice','payment'].includes(draft.mode)&&<>{text('reference',draft.mode==='invoice'?'شماره فاکتور':'مرجع یکتای پرداخت / شماره پیگیری بانکی')}{text('amount','مبلغ کل ریالی',true)}<SolarDate label="تاریخ مدرک" value={draft.day} onChange={v=>field('day',v)}/>{text('purpose','هدف خرید یا پرداخت')}{text('evidence','مرجع مدرک / محل پرونده / شرح ارز و نرخ',false,draft.mode==='payment')}</>}
 {draft.mode==='invoice'&&<>{text('terms','شرایط واقعی خرید و سررسید قرارداد')}{pick('settlementId','اتصال به تسویه خرید و قیمت بچ (اختیاری)',data.settlements.filter((s:any)=>s.data.supplierId===d.supplierId&&s.data.route===d.route).map((s:any)=>[s.id,s.data.invoiceNumber]),false)}</>}
 {['invoice','match'].includes(draft.mode)&&<div style={{gridColumn:'1 / -1'}}>{draft.lines.map((l:any,n:number)=><fieldset key={n} style={{marginBottom:16,padding:12}}><legend>ردیف {n+1}</legend><label className="field">سفارش<select required disabled={draft.mode==='match'} value={l.orderId} onChange={e=>field('lines',draft.lines.map((x:any,j:number)=>j===n?{...x,orderId:e.target.value,receiptIds:[]}:x))}><option value="">انتخاب کنید</option>{orders.map((o:any)=><option key={o.id} value={o.id}>{title(o)}</option>)}</select></label>{draft.mode==='invoice'&&<><label className="field">مقدار فاکتور (واحد اصلی)<input required value={l.quantity} onChange={e=>field('lines',draft.lines.map((x:any,j:number)=>j===n?{...x,quantity:latinDigits(e.target.value)}:x))}/></label><label className="field">مبلغ ریالی ردیف، شامل سهم مالیات/تخفیف<input required value={l.amount} onChange={e=>field('lines',draft.lines.map((x:any,j:number)=>j===n?{...x,amount:latinDigits(e.target.value)}:x))}/></label></>}
 <p>رسیدهای واقعی این ردیف؛ پیش از ورود کالا می‌تواند خالی باشد.</p>{data.receipts.filter((r:any)=>r.data.purchaseOrderId===l.orderId).map((r:any)=><label key={r.id} style={{display:'block',padding:6}}><input type="checkbox" checked={l.receiptIds.includes(r.id)} onChange={e=>field('lines',draft.lines.map((x:any,j:number)=>j===n?{...x,receiptIds:e.target.checked?[...x.receiptIds,r.id]:x.receiptIds.filter((id:string)=>id!==r.id)}:x))}/> {r.data.batchCode||r.data.batchId||r.id} · دریافت {(r.data.quantity||0)/1000} · پذیرفته {(r.data.accepted||0)/1000}</label>)}{draft.mode==='invoice'&&<button type="button" className="btn" onClick={()=>field('lines',draft.lines.filter((_:any,j:number)=>j!==n))}>حذف ردیف</button>}</fieldset>)}{draft.mode==='invoice'&&<button type="button" className="btn" onClick={()=>field('lines',[...draft.lines,{orderId:'',quantity:'',amount:'',receiptIds:[]}])}>افزودن ردیف فاکتور</button>}</div>}
 {draft.mode==='recognize'&&<>{text('account','کد و عنوان حساب واقعی')}{text('basis','مبنای شناسایی بدهی مطابق شرایط خرید')}</>}
 {draft.mode==='allocate'&&<>{pick('paymentId','پرداخت قابل تخصیص',v.payments.filter((p:any)=>Number(p.available)>0).map((p:any)=>[p.id,p.reference+' · مانده '+money(p.available)]))}{text('amount','مبلغ تخصیص ریالی',true)}<p>فاکتور: {d.invoices.find((i:any)=>i.id===draft.invoiceId)?.reference}؛ تخصیص فقط از مانده موجود انجام می‌شود.</p></>}
 {draft.mode==='schedule'&&<div style={{gridColumn:'1 / -1'}}><p>اقساط کل مبلغ فاکتور را وارد کنید. پرداخت تخصیص‌یافته از اولین سررسیدها کم می‌شود.</p>{draft.schedule.map((s:any,n:number)=><fieldset key={n}><SolarDate label="سررسید" value={s.due} onChange={v=>field('schedule',draft.schedule.map((x:any,j:number)=>j===n?{...x,due:v}:x))}/>{['amount','condition'].map(k=><label className="field" key={k}>{k==='amount'?'مبلغ ریالی':'شرط پرداخت طبق قرارداد'}<input required value={s[k]} onChange={e=>field('schedule',draft.schedule.map((x:any,j:number)=>j===n?{...x,[k]:k==='amount'?latinDigits(e.target.value):e.target.value}:x))}/></label>)}<button type="button" className="btn" onClick={()=>field('schedule',draft.schedule.filter((_:any,j:number)=>j!==n))}>حذف قسط</button></fieldset>)}<button type="button" className="btn" onClick={()=>field('schedule',[...draft.schedule,{amount:'',due:'',condition:''}])}>افزودن قسط</button></div>}
 {['advance','payment'].includes(draft.mode)&&pick('orderId','سفارش مرتبط (اختیاری)',orders.map((o:any)=>[o.id,title(o)]),false)}
 {draft.mode==='advance'&&<>{text('amount','مبلغ ریالی پیش‌پرداخت',true)}<SolarDate label="سررسید پیش‌پرداخت" value={draft.due||''} onChange={v=>field('due',v)}/>{text('condition','شرط پیش‌پرداخت طبق قرارداد')}{text('evidence','مرجع قرارداد و مدرک')}</>}
 {draft.mode==='issue'&&<>{text('title','مدرک یا مغایرت مورد پیگیری')}{pick('ownerId','مسئول پیگیری',data.members.map((m:any)=>[m.id,m.name]))}<SolarDate label="موعد پیگیری" value={draft.due||''} onChange={v=>field('due',v)}/></>}
 {draft.mode==='dispute'&&<>{text('amount','مبلغ اختلاف که از صف پرداخت کنار گذاشته شود (ریال)',true)}{text('evidence','مرجع بررسی کسری / رد کیفی و تصمیم مالی')}<p>این مبلغ از بدهی حذف نمی‌شود. فقط بخش بدون اختلاف پس از اجازه مالی قابل پرداخت خواهد بود.</p></>}
 {draft.mode==='resolve_issue'&&text('evidence','مدرک رفع نقص / نتیجه بررسی')}
 {['release','release_advance'].includes(draft.mode)&&<p className="notice">با تأیید، تکمیل شروط قرارداد و صحت مدارک را تأیید می‌کنید. سررسید آینده در صف مشخص باقی می‌ماند.</p>}
 {['void','unrecognize'].includes(draft.mode)&&<p className="notice">این اقدام سابقه را حذف نمی‌کند؛ دلیل و مدرک اصلاح را بنویسید.</p>}
 {text('notes','توضیح و دلیل تأیید این عملیات')}
 </div>{error&&<p className="notice error" role="alert">{error}</p>}<button className="btn primary" disabled={busy} type="submit">{busy?'در حال ثبت…':'تأیید و ثبت'}</button></form>}</DialogContent></Dialog>
 </section>;
}
