'use client';
import {IconDisclosure,IconActions} from "./program-workspace";
import {useEffect,useState} from 'react';
import {SolarDate} from './solar-date';
import {formatDate,formatDateTime,localDay,latinDigits} from '@/lib/persian-date';
const money=(v:any)=>v===null||v===undefined?'—':Number(v).toLocaleString('fa-IR',{maximumFractionDigits:2})+' ریال';
const states:Record<string,string>={draft:'پیش‌نویس بازرگانی',submitted:'منتظر تأیید مالی',returned:'برگشت برای اصلاح',approved:'تأیید و قیمت‌گذاری‌شده',reopened:'بازگشایی برای اصلاح'};
export function PurchaseSettlementPanel({planId='',initialOrderId=''}:{planId?:string;initialOrderId?:string}){
 const [catalog,setCatalog]=useState<any>(null),[detail,setDetail]=useState<any>(null),[draft,setDraft]=useState<any>(null),[action,setAction]=useState<any>(null),[review,setReview]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const base='/api/purchase-settlement';
 async function read(url:string){const r=await fetch(url,{cache:'no-store'}),d=await r.json() as any;if(!r.ok)throw Error(d.error);return d;}
 async function load(){setCatalog(await read(base+(planId?'?plan='+encodeURIComponent(planId):'')));}
 async function open(id:string){setDraft(null);setReview(null);setAction(null);setError('');setDetail(await read(base+'?id='+encodeURIComponent(id)));}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[planId]);
 const set=(k:string,v:any)=>setDraft((d:any)=>({...d,[k]:v}));
 const setLine=(i:number,k:string,v:any)=>setDraft((d:any)=>({...d,lines:d.lines.map((l:any,n:number)=>i===n?{...l,[k]:v}:l)}));
 function start(s?:any){setReview(null);setAction(null);const candidates=catalog.receipts.filter((r:any)=>(!r.claimedBy||r.claimedBy===s?.id)&&(!initialOrderId||r.data.purchaseOrderId===initialOrderId));
  const rows=s?.data.lines||(initialOrderId?candidates:[]).map((r:any)=>({receiptId:r.id,invoiceQuantity:String((r.data.quantityCheck?.invoiceQuantity||r.data.quantity)/1000),unitPrice:'',discount:'0',notes:'مطابق فاکتور'}));
  setDraft({...s?.data,mode:'save',id:crypto.randomUUID(),confirmed:true,settlementId:s?.id,revision:s?.revision||0,invoiceNumber:s?.data.invoiceNumber||'',invoiceDay:s?.data.invoiceDay||localDay(),currency:s?.data.currency||'IRR',fxRate:s?.data.fxRate||'1',fxDate:s?.data.fxDate||localDay(),fxSource:s?.data.fxSource||'',shipmentScope:s?.data.shipmentScope||'',lines:rows,expenses:s?.data.expenses||[],recoverableTaxRial:s?.data.recoverableTaxRial||'0',reportedPaidRial:s?.data.reportedPaidRial||'0',paymentReference:s?.data.paymentReference||'پرداخت گزارش نشده',notes:''});
 }
 async function post(b:any){if(busy)return;setBusy(true);setError('');try{const r=await fetch(base,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setMessage(b.mode==='approve'?'تأیید شد؛ قیمت بچ‌های پذیرفته‌شده در بهای تمام‌شده ثبت شد.':'ثبت شد.');await load();await open(d.id);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 function act(mode:string){setAction({mode,id:crypto.randomUUID(),confirmed:true,settlementId:detail.settlement.id,revision:detail.settlement.revision,token:detail.preview.token,notes:''});setDraft(null);setReview(null);}
 function startReview(){const d=detail.settlement.data,f=d.finance||{};setReview({mode:'review',id:crypto.randomUUID(),confirmed:true,settlementId:detail.settlement.id,revision:detail.settlement.revision,fxRate:f.fxRate||d.fxRate,fxDate:f.fxDate||d.fxDate,fxSource:f.fxSource||d.fxSource,allocation:f.allocation||'value',notes:'',lines:detail.preview.lines.map((l:any)=>{const old=f.lines?.find((x:any)=>x.receiptId===l.receiptId);return {receiptId:l.receiptId,weight:old?.weight||'0',extrasRial:old?.extrasRial||l.extras,excludedRial:old?.excludedRial??l.suggestedExcluded,disposition:old?.disposition||''};})});setAction(null);}
 async function upload(file:File){if(busy)return;const id=crypto.randomUUID();setBusy(true);setError('');try{const r=await fetch(base+'/files?id='+id+'&settlement='+encodeURIComponent(detail.settlement.id)+'&filename='+encodeURIComponent(file.name),{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file}),d=await r.json() as any;if(!r.ok)throw Error(d.error);await open(detail.settlement.id);setMessage('مدرک پیوست شد.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const table=(heads:string[],rows:any[][])=><div style={{overflowX:'auto'}}><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>;
 if(!catalog)return <p role="status">{error||'دریافت پرونده‌های تسویه خرید…'}</p>;
 const s=detail?.settlement,d=s?.data,p=detail?.preview;
 const input=(key:string,label:string,numeric=false)=><label className="field">{label}<input required value={draft[key]??''} onChange={e=>set(key,numeric?latinDigits(e.target.value):e.target.value)}/></label>;
 const eligible=catalog.receipts.filter((r:any)=>!r.claimedBy||r.claimedBy===draft?.settlementId);
 return <div><h2>تسویه خرید و قیمت‌گذاری بچ</h2><p>فاکتور نهایی و مدارک با بازرگانی؛ تخصیص هزینه و تأیید قیمت با مالی.</p>{error&&<p className="notice error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 <IconActions scope="purchase-settlement-panel-actions-8d5ea69260"><button className="btn" disabled={busy} onClick={()=>{setDetail(null);setDraft(null);setReview(null);setAction(null);void load().catch(e=>setError(e.message));}}>فهرست / تازه‌سازی</button>{catalog.buyerRoutes.length>0&&<button className="btn primary" disabled={busy} onClick={()=>{setDetail(null);start();}}>پرونده جدید</button>}</IconActions>
 {!detail&&!draft&&<>{!catalog.settlements.length&&<p className="empty">پرونده تسویه‌ای ثبت نشده است. بعد از دریافت کالا، بازرگانی پرونده را ایجاد و فاکتور را پیوست کند.</p>}{catalog.settlements.filter((s:any)=>!initialOrderId||s.data.lines.some((l:any)=>catalog.receipts.find((r:any)=>r.id===l.receiptId)?.data.purchaseOrderId===initialOrderId)).map((s:any)=><article className="flow-card" key={s.id}><h3>{s.data.supplier} · فاکتور {s.data.invoiceNumber}</h3><p>{states[s.data.state]} · {formatDate(s.data.invoiceDay)}</p><button className="btn" disabled={busy} onClick={()=>void open(s.id).catch(e=>setError(e.message))}>باز کردن پرونده</button></article>)}</>}
 {detail&&!draft&&<><h3>{d.supplier} · فاکتور {d.invoiceNumber}</h3><p>{states[d.state]} · {formatDate(d.invoiceDay)} · ارز {d.currency}</p><p>محدوده فاکتور/محموله: {d.shipmentScope}</p><p>نرخ ریالی فعلی: {p.fxRate} · منبع: {d.finance?.fxSource||d.fxSource}</p>{d.returnNote&&<p className="notice">علت برگشت: {d.returnNote}</p>}{d.approvals?.length>0&&d.state!=='approved'&&<p className="notice">قیمت تأیید قبلی تا تأیید اصلاحیه برقرار است.</p>}
 {table(['بچ / قطعه','فاکتور','دریافت','تأیید / رد','خالص کالا','سهم هزینه','خارج از موجودی','قیمت واحد فعلی','قیمت واحد پیشنهادی'],p.lines.map((l:any)=>[l.receiptId+' / '+l.partCode,l.invoiceQuantity,l.received/1000,(l.accepted/1000)+' / '+(l.rejected/1000),money(l.net),money(l.extras),money(l.excluded),money(l.currentUnitCost),money(l.unitCost)]))}
 <p>جمع کالا و هزینه مستقیم: {money(p.total)} · مالیات قابل بازیافت، خارج از قیمت موجودی: {money(d.recoverableTaxRial)}</p><p>پرداخت اعلام‌شده: {money(d.reportedPaidRial)} · مرجع: {d.paymentReference} (بدون ثبت سند پرداخت)</p>
 {d.expenses.length>0&&<IconDisclosure scope="purchase-settlement-panel-details-81637ccb90" title={<> ریز هزینه‌های جانبی </>}>{table(['عنوان','مبلغ ریالی','مرجع'],d.expenses.map((e:any)=>[e.title,money(e.amountRial),e.reference]))}</IconDisclosure>}
 {p.problems.length>0&&<IconDisclosure scope="purchase-settlement-panel-details-036dfcdb3d" title={<> موارد لازم قبل از تأیید مالی </>}><ul>{p.problems.map((t:string)=><li key={t}>{t}</li>)}</ul></IconDisclosure>}
 <h4>مدارک خرید</h4>{detail.files.map((f:any)=><p key={f.id}><a href={base+'/files?id='+encodeURIComponent(f.id)} target="_blank" rel="noreferrer">{f.filename}</a></p>)}{(detail.buyer&&['draft','returned','reopened'].includes(d.state)||detail.finance&&d.state==='submitted')&&<label className="field">پیوست فاکتور / رسید هزینه (حداکثر ۱۰ مگابایت)<input type="file" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value='';}}/></label>}
 <IconActions scope="purchase-settlement-panel-actions-c4665a5402">{detail.buyer&&['draft','returned','reopened'].includes(d.state)&&<><button className="btn" disabled={busy} onClick={()=>start(s)}>ویرایش بازرگانی</button><button className="btn primary" disabled={busy||!detail.files.length} onClick={()=>act('submit')}>ارسال به مالی</button></>}{detail.finance&&d.state==='submitted'&&<><button className="btn" disabled={busy} onClick={startReview}>نرخ و تخصیص مالی</button><button className="btn" disabled={busy} onClick={()=>act('return')}>برگشت برای اصلاح</button><button className="btn primary" disabled={busy||!p.ready||!d.finance} onClick={()=>act('approve')}>تأیید و انتقال قیمت به بچ‌ها</button></>}{detail.finance&&d.state==='approved'&&<button className="btn" disabled={busy} onClick={()=>act('reopen')}>بازگشایی برای اصلاح</button>}</IconActions>
 <IconDisclosure scope="purchase-settlement-panel-details-20ca5c0f37" title={<> تاریخچه و تأییدهای قبلی </>}>{d.history?.map((h:any,i:number)=><p key={i}>{formatDateTime(h.at)} · {h.name} · {h.mode} · {h.notes}</p>)}{d.approvals?.map((a:any,i:number)=><article key={i}><h4>تأیید {i+1} · {a.name} · {formatDateTime(a.at)}</h4>{table(['بچ','مقدار پذیرفته','قیمت واحد تأییدشده'],a.preview.lines.map((l:any)=>[l.receiptId,l.accepted/1000,money(l.unitCost)]))}</article>)}</IconDisclosure></>}
 {draft&&<form onSubmit={e=>{e.preventDefault();void post(draft);}}><h3>ثبت اطلاعات واقعی خرید</h3><div className="form-grid">{input('invoiceNumber','شماره فاکتور نهایی')}<SolarDate label="تاریخ فاکتور" value={draft.invoiceDay} onChange={v=>set('invoiceDay',v)}/><label className="field">ارز<select value={draft.currency} onChange={e=>{set('currency',e.target.value);if(e.target.value==='IRR')set('fxRate','1');if(e.target.value==='IRT')set('fxRate','10');}}>{['IRR','IRT','USD','CNY','EUR'].map(c=><option key={c}>{c}</option>)}</select></label>{input('fxRate','هر واحد ارز، چند ریال؟',true)}<SolarDate label="تاریخ مبنای تبدیل" value={draft.fxDate} onChange={v=>set('fxDate',v)}/>{input('fxSource','مدرک / منبع نرخ تبدیل')}{input('shipmentScope','این فاکتور یا سهم آن مربوط به کدام محموله است؟')}{input('recoverableTaxRial','مالیات قابل بازیافت، جدا از قیمت (ریال)',true)}{input('reportedPaidRial','مبلغ پرداخت اعلام‌شده (ریال)',true)}{input('paymentReference','مرجع پرداخت یا «پرداخت گزارش نشده»')}</div>
 <p>هر بچ فقط در یک تسویه قرار می‌گیرد. برای چند تحویل از یک فاکتور، سهم این محموله را وارد کنید.</p><label className="field">افزودن بچ دریافت‌شده<select value="" onChange={e=>{const r=eligible.find((r:any)=>r.id===e.target.value);if(r&&!draft.lines.some((l:any)=>l.receiptId===r.id))set('lines',[...draft.lines,{receiptId:r.id,invoiceQuantity:String((r.data.quantityCheck?.invoiceQuantity||r.data.quantity)/1000),unitPrice:'',discount:'0',notes:'مطابق فاکتور'}]);}}><option value="">انتخاب رسید همان تأمین‌کننده و پرونده</option>{eligible.map((r:any)=><option key={r.id} value={r.id}>{r.id} · {catalog.orders.find((o:any)=>o.id===r.data.purchaseOrderId)?.data.supplier} · دریافت {r.data.quantity/1000}</option>)}</select></label>
 {draft.lines.map((l:any,i:number)=><article className="flow-card" key={l.receiptId}><h4>{l.receiptId}</h4><div className="form-grid">{[['invoiceQuantity','مقدار سهم این ردیف فاکتور'],['unitPrice','قیمت واحد به ارز فاکتور'],['discount','تخفیف کل این ردیف به ارز فاکتور'],['notes','توضیح ردیف']].map(([k,label])=><label className="field" key={k}>{label}<input required value={l[k]} onChange={e=>setLine(i,k,k==='notes'?e.target.value:latinDigits(e.target.value))}/></label>)}</div><button type="button" className="btn" onClick={()=>set('lines',draft.lines.filter((_:any,n:number)=>n!==i))}>حذف از این پیش‌نویس</button></article>)}
 <h4>هزینه‌های واقعی مشترک</h4>{draft.expenses.map((x:any,i:number)=><div className="form-grid" key={i}>{[['title','حمل / بیمه / گمرک / سایر'],['amountRial','مبلغ ریالی'],['reference','شماره مدرک هزینه']].map(([k,l])=><label key={k} className="field">{l}<input required value={x[k]} onChange={e=>set('expenses',draft.expenses.map((v:any,n:number)=>n===i?{...v,[k]:k==='amountRial'?latinDigits(e.target.value):e.target.value}:v))}/></label>)}<button type="button" className="btn" onClick={()=>set('expenses',draft.expenses.filter((_:any,n:number)=>n!==i))}>حذف هزینه</button></div>)}<button type="button" className="btn" onClick={()=>set('expenses',[...draft.expenses,{title:'',amountRial:'',reference:''}])}>افزودن هزینه</button><label className="field">توضیح ثبت / اصلاح<textarea required value={draft.notes} onChange={e=>set('notes',e.target.value)}/></label><p>ابتدا ذخیره کنید؛ سپس فاکتور و مدارک را پیوست و پرونده را به مالی ارسال کنید.</p><button className="btn primary" disabled={busy||!draft.lines.length}>ذخیره پیش‌نویس</button><button type="button" className="btn" disabled={busy} onClick={()=>setDraft(null)}>انصراف</button></form>}
 {review&&<form onSubmit={e=>{e.preventDefault();void post(review);}}><h3>بررسی مالی و تخصیص هزینه</h3><div className="form-grid">{[['fxRate','نرخ تبدیل تأییدشده به ریال'],['fxSource','مدرک نرخ تأییدشده']].map(([k,l])=><label className="field" key={k}>{l}<input required value={review[k]} onChange={e=>setReview({...review,[k]:k==='fxRate'?latinDigits(e.target.value):e.target.value})}/></label>)}<SolarDate label="تاریخ نرخ تأییدشده" value={review.fxDate} onChange={v=>setReview({...review,fxDate:v})}/><label className="field">مبنای هزینه مشترک<select value={review.allocation} onChange={e=>setReview({...review,allocation:e.target.value})}><option value="value">ارزش خالص کالا</option><option value="weight">وزن</option><option value="manual">مبلغ دستی هر ردیف</option></select></label></div><p>مبلغ خارج از موجودی، سهم کسری/رد و سایر اقلام قابل پیگیری است. بعد از تغییر نرخ یا مبنای تخصیص، مبلغ این بخش را هم بازبینی کنید. ابتدا بررسی را ذخیره کنید و سپس پیش‌نمایش تازه را تأیید کنید.</p>
 {review.lines.map((l:any,i:number)=><article className="flow-card" key={l.receiptId}><h4>{l.receiptId}</h4>{[['weight','وزن ردیف؛ واحد یکسان برای همه'],['extrasRial','سهم هزینه مشترک در تخصیص دستی (ریال)'],['excludedRial','مبلغ خارج از ارزش موجودی پذیرفته‌شده (ریال)'],['disposition','تعیین تکلیف: مطالبه وجه / تعویض / سایر و علت']].filter(([k])=>k!=='weight'||review.allocation==='weight').filter(([k])=>k!=='extrasRial'||review.allocation==='manual').map(([k,label])=><label className="field" key={k}>{label}<input required={k!=='disposition'} value={l[k]} onChange={e=>setReview({...review,lines:review.lines.map((v:any,n:number)=>n===i?{...v,[k]:k==='disposition'?e.target.value:latinDigits(e.target.value)}:v)})}/></label>)}</article>)}<label className="field">توضیح بررسی مالی<textarea required value={review.notes} onChange={e=>setReview({...review,notes:e.target.value})}/></label><button className="btn primary" disabled={busy}>ذخیره بررسی و محاسبه پیش‌نمایش تازه</button></form>}
 {action&&<form onSubmit={e=>{e.preventDefault();void post(action);}} className="flow-card"><h3>{({submit:'ارسال پرونده به مالی',return:'برگشت به بازرگانی',approve:'تأیید نهایی و ثبت قیمت بچ‌ها',reopen:'بازگشایی پرونده'} as any)[action.mode]}</h3>{action.mode==='approve'&&<p>قیمت‌های واحد جدول بالا جایگزین قیمت فعلی بچ‌های پذیرفته‌شده می‌شوند. سابقه قبلی حفظ می‌شود. این اقدام پرداخت یا سند سپیدار ایجاد نمی‌کند.</p>}<label className="field">توضیح و مبنای تصمیم<textarea required value={action.notes} onChange={e=>setAction({...action,notes:e.target.value})}/></label><button className="btn primary" disabled={busy}>تأیید و ثبت</button></form>}
 <IconDisclosure scope="purchase-settlement-panel-details-b769bf776e" title={<> راهنمای تسویه خرید </>} style={{marginTop:20}}><ul>{catalog.help.map((h:string)=><li key={h}>{h}</li>)}</ul></IconDisclosure>
 </div>;
}
