'use client';
import {useEffect,useState} from 'react';
import {SolarDate} from './solar-date';
import {formatDate,formatDateTime} from '@/lib/persian-date';
import {invoiceTaxStates} from '@/lib/purchase-invoice-contract';
export function PurchaseInvoiceReport({onOpen,revision}:{onOpen:(id:string)=>void;revision:string}){
 const [filters,setFilters]=useState({supplier:'',product:'',reference:'',from:'',to:'',state:''}),[offset,setOffset]=useState(0),[reload,setReload]=useState(0),[result,setResult]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{const timer=setInterval(()=>setReload(n=>n+1),60000),focus=()=>setReload(n=>n+1);window.addEventListener('focus',focus);return()=>{clearInterval(timer);window.removeEventListener('focus',focus)}},[]);
 useEffect(()=>{const abort=new AbortController();setResult(null);setError('');const timer=setTimeout(()=>{const q=new URLSearchParams({view:'formal',...filters,offset:String(offset)});fetch('/api/purchase-payables?'+q,{cache:'no-store',signal:abort.signal}).then(async r=>{const d:any=await r.json();if(!r.ok)throw Error(d.error);return d}).then(d=>{if(!abort.signal.aborted)setResult(d)}).catch(e=>{if(!abort.signal.aborted)setError(e.message)})},200);return()=>{clearTimeout(timer);abort.abort()}},[filters,offset,reload,revision]);
 const change=(k:string,v:string)=>{setFilters(f=>({...f,[k]:v}));setOffset(0)};
 return <section><h3>گزارش فاکتورهای رسمی و پیگیری مؤدیان</h3><p className="subtle">فروشنده در سامانه مؤدیان ثبت و ارسال می‌کند. نتیجه بررسی در اینجا دستی ثبت می‌شود؛ این صفحه به سامانه مؤدیان متصل نیست. تازه‌سازی خودکار هر دقیقه و هنگام بازگشت به صفحه.</p><div className="formgrid">{[['supplier','نام تأمین‌کننده'],['product','نام یا کد کالا'],['reference','شماره فاکتور / شناسه مالیاتی']].map(([k,label])=><label className="field" key={k}>{label}<input value={filters[k as keyof typeof filters]} onChange={e=>change(k,e.target.value)}/></label>)}<SolarDate label="تاریخ فاکتور از" value={filters.from} onChange={v=>change('from',v)}/><SolarDate label="تاریخ فاکتور تا" value={filters.to} onChange={v=>change('to',v)}/><label className="field">وضعیت مؤدیان<select value={filters.state} onChange={e=>change('state',e.target.value)}><option value="">همه وضعیت‌ها</option>{Object.entries(invoiceTaxStates).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><button className="btn" onClick={()=>setReload(n=>n+1)}>تازه‌سازی گزارش</button>{error&&<p role="alert">{error}</p>}{!result&&!error&&<p role="status">در حال دریافت گزارش…</p>}{result&&<><p>{result.total.toLocaleString('fa-IR')} فاکتور · آخرین دریافت: {formatDateTime(result.asOf)}</p><div style={{overflowX:'auto'}}><table><thead><tr>{['تأمین‌کننده','فاکتور / تاریخ','کالا','مبلغ (ریال)','وضعیت مؤدیان','سند و پرونده'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{result.items.map((i:any)=><tr key={i.invoiceId}><td>{i.supplier}</td><td>{i.reference}<br/>{formatDate(i.day)}</td><td>{i.products.join('، ')}</td><td>{Number(i.amount).toLocaleString('fa-IR')}</td><td>{invoiceTaxStates[i.taxState]}<br/>{i.taxId}<br/>{i.taxDay&&formatDate(i.taxDay)}<br/>{i.taxNote}</td><td>{i.document?<a href={'/api/purchase-payables/files?id='+encodeURIComponent(i.document.id)}>{i.document.filename}</a>:'سند بارگذاری نشده'}<br/><button className="link" onClick={()=>onOpen(i.caseId)}>بازکردن پرونده و ثبت نتیجه</button></td></tr>)}</tbody></table></div>{!result.total&&<p>فاکتور رسمی مطابق جست‌وجو یافت نشد.</p>}<button className="btn" disabled={!offset} onClick={()=>setOffset(n=>Math.max(0,n-100))}>صفحه قبل</button><button className="btn" disabled={result.nextOffset===null} onClick={()=>setOffset(result.nextOffset)}>صفحه بعد</button></>}</section>
}
