'use client';
import {useEffect,useState} from 'react';
import {SolarDate} from './solar-date';
import {formatDate,localDay} from '@/lib/persian-date';
import {shipmentDocumentKinds,shipmentStates} from '@/lib/shipment-contract';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export function PurchaseShipmentsPanel({supplierId='',materialId=''}:{supplierId?:string;materialId?:string}){
 const [data,setData]=useState<any>(null),[search,setSearch]=useState(''),[draft,setDraft]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[upload,setUpload]=useState<any>(null);
 async function load(){const q=new URLSearchParams({search,supplier:supplierId,material:materialId}),r=await fetch('/api/purchase-shipments?'+q,{cache:'no-store'}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setData(d);}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[supplierId,materialId]);
 const begin=(mode:string,extra:any={})=>{setError('');setDraft({id:crypto.randomUUID(),confirmed:true,mode,day:localDay(),notes:'',currency:'USD',lines:[],...extra});};
 const change=(k:string,v:any)=>setDraft((d:any)=>({...d,[k]:v}));
 const lineChange=(i:number,k:string,v:string)=>setDraft((d:any)=>({...d,lines:d.lines.map((l:any,j:number)=>i===j?{...l,[k]:v}:l)}));
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/purchase-shipments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setDraft(null);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function predict(i:number){try{const l=draft.lines[i],q=new URLSearchParams({link:l.linkId,quantity:l.quantity,packaging:l.packaging}),r=await fetch('/api/purchase-shipments?'+q),d=await r.json() as any;if(!r.ok)throw Error(d.error);setDraft((old:any)=>({...old,lines:old.lines.map((row:any,j:number)=>j===i?{...row,prediction:d.prediction}:row)}));}catch(e){setError((e as Error).message);}}
 async function sendFile(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const {file,...meta}=upload,q=new URLSearchParams({...meta,filename:file.name,confirmed:'true'}),r=await fetch('/api/purchase-shipments/files?'+q,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setUpload(null);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const field=(k:string,label:string)=><label className="field" key={k}>{label}<input required value={draft?.[k]||''} onChange={e=>change(k,e.target.value)}/></label>;
 const renderLines=(lines:any[],currency:string)=><div style={{overflowX:'auto'}}><table className="table"><thead><tr>{['کالا و مشخصات خرید','مقدار','قیمت واحد / '+currency,'بسته‌بندی','نت kg','گروس kg','حجم m³'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{lines.map((l:any)=><tr key={l.linkId}><td>{l.code} · {l.name}<p>عمومی: {l.generalSpecs}</p><p>تأمین‌کننده: {l.supplierSpecs}</p></td><td>{l.quantity} {l.unit}</td><td>{l.unitPrice}</td><td>{l.packaging}</td><td>{l.netKg}</td><td>{l.grossKg}</td><td>{l.volumeM3}</td></tr>)}</tbody></table></div>;
 return <section className="panel" dir="rtl"><div className="panelhead"><h2>مشخصات و سوابق محموله‌های خرید</h2>{data&&Object.values(data.canWrite).some(Boolean)&&<button className="btn primary" onClick={()=>begin('create',{supplierId})}>محموله / ثبت سفارش جدید</button>}</div><div className="inside"><p className="notice">{data?.help}</p>{error&&!draft&&!upload&&<p role="alert">{error}</p>}
 <form onSubmit={e=>{e.preventDefault();void load().catch(e=>setError(e.message));}}><label className="field">جست‌وجوی کالا، کد، مشخصات یا تأمین‌کننده<input value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="btn">جست‌وجو و تازه‌سازی</button></form>
 {data?.links.filter((l:any)=>(!supplierId||l.data.supplierId===supplierId)&&(!materialId||l.data.materialId===materialId)&&(!search||(l.material?.data.name+' '+l.material?.data.code+' '+l.data.supplierSpecs+' '+data.suppliers.find((s:any)=>s.id===l.data.supplierId)?.data.name).includes(search))).map((l:any)=><details key={l.id} className="notice"><summary>{l.material?.data.name} · {data.suppliers.find((s:any)=>s.id===l.data.supplierId)?.data.name}</summary><p>مشخصات عمومی: {l.material?.data.specs||'ثبت نشده'}</p><p>مشخصات محصول این تأمین‌کننده: {l.data.supplierSpecs||'ثبت نشده'}</p>{data.canWrite[data.suppliers.find((s:any)=>s.id===l.data.supplierId)?.data.route]&&<button className="btn" onClick={()=>begin('specifications',{linkId:l.id,revision:l.revision,materialRevision:l.material.revision,generalSpecs:l.material.data.specs||'',supplierSpecs:l.data.supplierSpecs||''})}>ثبت / اصلاح مشخصات فنی</button>}{data.specifications.filter((s:any)=>s.data.linkId===l.id).map((s:any)=><p key={s.id}>{formatDate(s.data.day)} · {s.data.generalSpecs} · {s.data.supplierSpecs} · {s.data.notes}</p>)}</details>)}
 {data?.orders.length>0&&<details><summary>سفارش‌های قبلی موجود در گردش تأمین</summary>{data.orders.map((o:any)=><p key={o.id}>{formatDate(o.created)} · {o.data.supplier} · {o.data.partCode} · {o.data.quantity/1000} {o.data.unit} · {o.data.unitPrice||'قیمت واحد ثبت نشده'} {o.data.currency} · مبلغ ریال {o.data.totalRial??'ثبت نشده'} · {o.data.specs||'مشخصات ثبت نشده'} · وزن و حجم این سفارش از پکینگ مستند ثبت شود.</p>)}</details>}{data?.shipments.map((s:any)=><article key={s.id} className="flow-card"><h3>{s.data.title} · {s.data.supplierName}</h3><p>{s.data.reference} · {shipmentStates[s.data.state]} · {formatDate(s.data.initial.day)}</p><details open><summary>ثبت سفارش اولیه و مشخصات مبنا</summary>{renderLines(s.data.initial.lines,s.data.currency)}{s.data.initial.lines.map((l:any)=>l.prediction?.available&&<p key={l.linkId}>مبنای برآورد {l.name}: {l.prediction.sampleCount} پکینگ · {l.prediction.sources.map((x:any)=>x.shipmentId+' / '+formatDate(x.day)).join('، ')}</p>)}</details>{s.data.actual&&<details open><summary>قیمت و پکینگ واقعی · {formatDate(s.data.actual.day)}</summary>{renderLines(s.data.actual.lines,s.data.currency)}</details>}{s.data.amendments?.map((a:any,i:number)=><details key={i}><summary>اصلاح ثبت سفارش {i+1} · {a.reference} · {formatDate(a.day)}</summary>{renderLines(a.lines,s.data.currency)}<p>{a.notes}</p></details>)}
 <h4>مدارک تاریخ‌دار محموله</h4>{data.files.filter((f:any)=>f.data.shipmentId===s.id).map((f:any)=><p key={f.id}>{shipmentDocumentKinds[f.data.kind]} · {formatDate(f.data.issuedOn)} · {f.data.reference} · <a href={'/api/purchase-shipments/files?id='+encodeURIComponent(f.id)}>{f.data.filename}</a></p>)}
 {data.canWrite[s.data.route]&&<div className="actions"><button className="btn" onClick={()=>{setError('');setUpload({id:crypto.randomUUID(),shipment:s.id,revision:String(s.revision),kind:'proforma',issuedOn:localDay(),reference:'',file:null});}}>افزودن پروفرما، اینویس، پکینگ و مدارک</button>{({draft:'register',registered:'permit',permitted:'actual',loaded:'amend',amended:'amend'} as any)[s.data.state]&&<button className="btn" onClick={()=>begin(({draft:'register',registered:'permit',permitted:'actual',loaded:'amend',amended:'amend'} as any)[s.data.state],{shipmentId:s.id,revision:s.revision,lines:s.data.initial.lines})}>{({draft:'ثبت سفارش اولیه',registered:'ثبت مجوز واردات',permitted:'ثبت بارگیری و پکینگ واقعی',loaded:'ثبت اصلاح سفارش',amended:'ثبت اصلاح بعدی'} as any)[s.data.state]}</button>}{s.data.state==='draft'&&<button className="btn" onClick={()=>begin('historical',{shipmentId:s.id,revision:s.revision,lines:s.data.initial.lines})}>ثبت خرید قبلی با پکینگ واقعی</button>}</div>}<details><summary>سابقه مراحل</summary>{s.data.history.map((h:any,i:number)=><p key={i}>{formatDate(h.at)} · {h.mode} · {h.notes}</p>)}</details></article>)}{data&&!data.shipments.length&&<p>محموله‌ای با این جست‌وجو ثبت نشده است.</p>}
 </div><Dialog open={!!draft} onOpenChange={v=>{if(!busy&&!v)setDraft(null);}}><DialogContent className="modal sm:max-w-4xl"><DialogTitle>{draft?.mode==='specifications'?'مشخصات فنی':'پرونده محموله و ثبت سفارش'}</DialogTitle><DialogDescription>مقادیر و مدارک واقعی را وارد کنید. ثبت اولیه و اصلاحات به همراه مشخصات و تاریخ حفظ می‌شوند.</DialogDescription>{draft&&<form onSubmit={save}><fieldset disabled={busy} style={{border:0}}><div className="formgrid"><SolarDate label="تاریخ مرحله / مدرک" value={draft.day} onChange={v=>change('day',v)}/>{field('notes','شرح و علت ثبت')}
 {draft.mode==='specifications'?<>{['generalSpecs','supplierSpecs'].map(k=><label className="field wide" key={k}>{k==='generalSpecs'?'مشخصات فنی عمومی کالا':'مشخصات فنی محصول این تأمین‌کننده'}<textarea required maxLength={10000} value={draft[k]} onChange={e=>change(k,e.target.value)}/></label>)}<p>تغییر مشخصات نیاز به ارزیابی دوباره صلاحیت خرید دارد.</p></>:<>{draft.mode==='create'&&<><label className="field">تأمین‌کننده<select required value={draft.supplierId||''} onChange={e=>{change('supplierId',e.target.value);change('lines',[]);}}><option value="">انتخاب کنید</option>{data.suppliers.filter((s:any)=>data.canWrite[s.data.route]).map((s:any)=><option key={s.id} value={s.id}>{s.data.name}</option>)}</select></label>{field('title','عنوان محموله')}<label className="field">ارز<select value={draft.currency} onChange={e=>change('currency',e.target.value)}>{['USD','EUR','CNY','IRR','IRT'].map(c=><option key={c}>{c}</option>)}</select></label></>}{!['actual','historical'].includes(draft.mode)&&field('reference','شماره / مرجع ثبت سفارش یا مجوز')}
 {draft.mode!=='create'&&<label className="field">مدرک همین مرحله<select required value={draft.documentId||''} onChange={e=>change('documentId',e.target.value)}><option value="">انتخاب کنید</option>{data.files.filter((f:any)=>f.data.shipmentId===draft.shipmentId&&f.data.kind===(['actual','historical'].includes(draft.mode)?'packing':draft.mode==='permit'?'permit':'registration')).map((f:any)=><option key={f.id} value={f.id}>{f.data.reference} · {f.data.filename}</option>)}</select></label>}
 {['create','actual','historical'].includes(draft.mode)&&<div className="wide">{draft.lines.map((l:any,i:number)=><div className="notice formgrid" key={i}><label className="field">کالا<select required disabled={draft.mode!=='create'} value={l.linkId} onChange={e=>lineChange(i,'linkId',e.target.value)}><option value="">انتخاب کنید</option>{data.links.filter((x:any)=>x.data.supplierId===(draft.supplierId||data.shipments.find((s:any)=>s.id===draft.shipmentId)?.data.supplierId)).map((x:any)=><option key={x.id} value={x.id}>{x.material.data.code} · {x.material.data.name}</option>)}</select></label>{Object.entries({quantity:'مقدار در واحد کالا',unitPrice:'قیمت واحد به ارز محموله',packaging:'نوع و الگوی بسته‌بندی',netKg:'وزن نت / kg',grossKg:'وزن گروس / kg',volumeM3:'حجم / m³'}).map(([k,t])=><label className="field" key={k}>{t}<input required value={l[k]||''} onChange={e=>lineChange(i,k,e.target.value)}/></label>)}{draft.mode==='create'&&<><button type="button" className="btn" onClick={()=>void predict(i)}>پیش‌بینی از پکینگ‌های قبلی</button>{l.prediction&&<div className="wide">{l.prediction.available?<><p>{l.prediction.sampleCount} پکینگ منطبق؛ نت {l.prediction.netKg}، گروس {l.prediction.grossKg}، حجم {l.prediction.volumeM3}</p><p>بازه سوابق: نت {l.prediction.range.netKg.min} تا {l.prediction.range.netKg.max}؛ گروس {l.prediction.range.grossKg.min} تا {l.prediction.range.grossKg.max}؛ حجم {l.prediction.range.volumeM3.min} تا {l.prediction.range.volumeM3.max}</p><button type="button" className="btn" onClick={()=>{for(const k of ['netKg','grossKg','volumeM3'])lineChange(i,k,String(l.prediction[k]));}}>استفاده از برآورد</button></>:<p>{l.prediction.reason}</p>}</div>}<button type="button" className="btn" onClick={()=>change('lines',draft.lines.filter((_:any,j:number)=>i!==j))}>حذف ردیف پیش‌نویس</button></>}</div>)}{draft.mode==='create'&&<button className="btn" type="button" onClick={()=>change('lines',[...draft.lines,{linkId:'',quantity:'',unitPrice:'',packaging:'',netKg:'',grossKg:'',volumeM3:''}])}>افزودن کالا</button>}</div>}</>}
 </div>{error&&<p role="alert">{error}</p>}<button className="btn primary" disabled={busy}>تأیید و ثبت</button></fieldset></form>}</DialogContent></Dialog>
 <Dialog open={!!upload} onOpenChange={v=>{if(!busy&&!v)setUpload(null);}}><DialogContent className="modal"><DialogTitle>مدرک تاریخ‌دار محموله</DialogTitle><DialogDescription>مدرک به‌صورت خصوصی و بدون بازنویسی نسخه‌های قبلی نگهداری می‌شود.</DialogDescription>{upload&&<form onSubmit={sendFile}><fieldset disabled={busy} style={{border:0}}><label className="field">نوع مدرک<select value={upload.kind} onChange={e=>setUpload({...upload,kind:e.target.value})}>{Object.entries(shipmentDocumentKinds).map(([k,t])=><option key={k} value={k}>{t}</option>)}</select></label><SolarDate label="تاریخ صدور" value={upload.issuedOn} onChange={v=>setUpload({...upload,issuedOn:v})}/><label className="field">شماره / مرجع<input required value={upload.reference} onChange={e=>setUpload({...upload,reference:e.target.value})}/></label><label className="field">فایل<input type="file" required onChange={e=>setUpload({...upload,file:e.target.files?.[0]})}/></label>{error&&<p role="alert">{error}</p>}<button className="btn primary">تأیید و بارگذاری</button></fieldset></form>}</DialogContent></Dialog></section>;
}
