'use client';
import {useEffect,useState} from 'react';
import {SolarDate} from './solar-date';
import {formatDate,latinDigits} from '@/lib/persian-date';
import {serviceStates} from '@/lib/purchase-fulfillment';
const names:Record<string,string>={create:'تعهد خدمت جدید',deliver:'ارائه خروجی واقعی',accept:'تأیید دریافت خدمت',return:'برگشت خروجی برای اصلاح',reassign:'تغییر مسئول یا موعد',cost:'تأیید تخصیص هزینه',undo_cost:'برگشت تخصیص هزینه',reopen:'بازگشایی دریافت'};
const money=(s:any)=>Number(s||0).toLocaleString('fa-IR')+' ریال';
export function PurchaseServicesPanel({onNavigate}:{onNavigate?:(s:string)=>void}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[draft,setDraft]=useState<any>(null),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all'),[search,setSearch]=useState('');
 async function load(){const r=await fetch('/api/purchase-services',{cache:'no-store'}),d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);}
 useEffect(()=>{void load().catch(e=>setError(e.message));const f=()=>void load().catch(e=>setError(e.message));window.addEventListener('focus',f);const t=setInterval(f,60000);return()=>{clearInterval(t);window.removeEventListener('focus',f)}},[]);
 const start=(mode:string,s?:any)=>{setError('');setDraft({mode,id:crypto.randomUUID(),confirmed:true,revision:s?.revision||0,serviceId:s?.id,notes:'',costs:[],ownerId:s?.data.ownerId||'',due:s?.data.due||'',amount:s?.data.amount||''});};
 const field=(k:string,v:any)=>setDraft({...draft,[k]:v});
 const text=(k:string,label:string)=><label className="field">{label}<input required value={draft[k]||''} onChange={e=>field(k,k==='amount'?latinDigits(e.target.value):e.target.value)}/></label>;
 const select=(k:string,label:string,options:any[])=><label className="field">{label}<select required value={draft[k]||''} onChange={e=>field(k,e.target.value)}><option value="">انتخاب کنید</option>{options.map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label>;
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/purchase-services',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)}),d:any=await r.json();if(!r.ok)throw Error(d.error);await load();setDraft(null);window.dispatchEvent(new Event('nafasyar-tasks-changed'));}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function upload(s:any,file:File){setBusy(true);setError('');try{const r=await fetch('/api/purchase-services/files?'+new URLSearchParams({id:crypto.randomUUID(),serviceId:s.id,filename:file.name}),{method:'POST',body:file}),d:any=await r.json();if(!r.ok)throw Error(d.error);await load();start('deliver',s);setDraft((p:any)=>({...p,fileId:d.id}));}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(!data)return <div><p role="status">{error||'در حال دریافت تعهدات خرید…'}</p><button className="btn" onClick={()=>void load().catch(e=>setError(e.message))}>تلاش دوباره</button></div>;
 const current=data.services.find((s:any)=>s.id===draft?.serviceId),list=data.services.filter((s:any)=>(s.data.title+' '+s.data.expected).includes(search)&&(filter==='all'?true:filter==='paid'?Number(s.summary.paid)>0&&s.data.state!=='accepted':filter==='overdue'?s.summary.overdue:!s.summary.complete));
 return <section className="panel" dir="rtl"><h3>تحویل خرید و خدمات</h3><p>پرداخت، دریافت و تخصیص هزینه مستقل‌اند. پرونده تا تکمیل هر سه باز می‌ماند. خروجی طراحی را فقط در پرونده محرمانه تحقیق‌وتوسعه نگه دارید.</p>{error&&<p className="notice error" role="alert">{error}</p>}
 <div className="tools">{data.cases.length>0&&<button className="btn" onClick={()=>start('create')}>تعهد خدمت جدید</button>}<button className="btn" onClick={()=>void load().catch(e=>setError(e.message))}>تازه‌سازی</button><label>جست‌وجوی خدمت<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>وضعیت پیگیری<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">همه</option><option value="paid">پرداخت‌شده؛ تحویل تأیید نشده</option><option value="overdue">تحویل عقب‌افتاده</option><option value="open">پرونده‌های ناتمام</option></select></label></div>
 {list.map((s:any)=><article className="flow-card" key={s.id}><h4>{s.data.title}</h4><p>خروجی مورد انتظار: {s.data.expected}</p><p>مسئول دریافت: {data.members.find((m:any)=>m.id===s.data.ownerId)?.name||(s.canReceive?'شما':s.data.ownerId)} · موعد: {formatDate(s.data.due)}</p><p><strong>{serviceStates[s.data.state]}</strong> · تعهد: {money(s.data.amount)} · فاکتور: {money(s.summary.billed)} · پرداخت مرتبط: {money(s.summary.paid)} · تخصیص‌نیافته: {money(s.summary.unallocated)} · {s.summary.cost}</p>{s.summary.overdue&&<p className="notice error">موعد دریافت گذشته است؛ علت تأخیر و خروجی را پیگیری کنید.</p>}<p>{s.summary.complete?'تحویل، تخصیص و تسویه کامل است.':s.summary.blockers.join(' / ')}</p>
 {s.data.delivery?.fileId&&<p><a href={s.data.design?'/api/qms/files?download=1&fileId='+encodeURIComponent(s.data.delivery.fileId):'/api/purchase-services/files?id='+encodeURIComponent(s.data.delivery.fileId)}>مشاهده مدرک تحویل</a></p>}
 <div className="tools">{s.canReceive&&['open','returned'].includes(s.data.state)&&<>{s.data.design?<><p>فایل حجیم را در پرونده محرمانه تحقیق‌وتوسعه بارگذاری و سپس در «ارائه خروجی» انتخاب کنید.</p>{onNavigate&&<button className="btn" onClick={()=>onNavigate('qms')}>باز کردن تحقیق‌وتوسعه</button>}</>:<label className="field">بارگذاری مدرک تحویل (تا ۱۰ مگابایت)<input type="file" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(s,f);e.target.value=''}}/></label>}<button className="btn" onClick={()=>start('deliver',s)}>ارائه خروجی واقعی</button></>}{s.canReceive&&s.data.state==='submitted'&&<><button className="btn" onClick={()=>start('accept',s)}>تأیید دریافت مطابق درخواست</button><button className="btn" onClick={()=>start('return',s)}>خروجی ناقص؛ برگشت</button></>}{data.finance&&<>{s.data.state!=='accepted'&&<button className="btn" onClick={()=>start('reassign',s)}>تغییر مسئول / موعد</button>}{s.data.state==='accepted'&&!s.data.costApproval&&<><button className="btn" onClick={()=>start('cost',s)}>تخصیص هزینه به کالا یا پروژه</button><button className="btn" onClick={()=>start('reopen',s)}>بازگشایی دریافت</button></>}{s.data.costApproval&&<button className="btn" onClick={()=>start('undo_cost',s)}>برگشت تخصیص</button>}</>}</div>
 {(s.data.costs||[]).map((a:any)=><p key={a.kind+a.targetId}>مقصد هزینه: {data.targets.find((t:any)=>t.id===a.targetId)?.title||a.targetId} · {money(a.amount)}</p>)}</article>)}{!list.length&&<p>خدمتی در این فیلتر نیست.</p>}
 {data.cases.length>0&&<details><summary>وضعیت سه‌گانه پرونده‌های خرید کالا و خدمت</summary>{data.cases.map((c:any)=><article key={c.id}><h4>{c.supplier} · {c.title}</h4><p>تحویل: {c.completion.delivery.length?c.completion.delivery.join(' / '):'تکمیل'}</p><p>مالی: {c.completion.financial.length?c.completion.financial.join(' / '):'تکمیل'}</p><p>تخصیص هزینه: {c.completion.cost.length?c.completion.cost.join(' / '):'تکمیل'}</p><p>{c.completion.closed?'بسته‌شده':c.completion.ready?'آماده تأیید نهایی مالی':'باز و نیازمند پیگیری'}</p></article>)}</details>}
 {data.projectCosts.length>0&&<details><summary>هزینه خدمات به تفکیک پروژه</summary>{data.projectCosts.map((p:any)=><article key={p.id}><h4>{p.title}</h4>{p.items.map((x:any)=><p key={x.key}>{x.title}: {money(x.amount)}</p>)}</article>)}</details>}
 {draft&&<form onSubmit={save} className="flow-card"><h4>{names[draft.mode]}</h4><p>اطلاعات را بررسی کنید؛ دکمه تأیید، همین عملیات را ثبت می‌کند.</p><div className="form-grid">
 {draft.mode==='create'&&<>{select('caseId','پرونده خرید و تأمین‌کننده',data.cases.filter((c:any)=>!c.completion.closed).map((c:any)=>[c.id,c.supplier+' · '+c.title]))}{text('title','عنوان خدمت')}{text('expected','خروجی قابل تحویل و معیار پذیرش')}{text('amount','مبلغ کل تعهد خدمت (ریال)')}<label><input type="checkbox" checked={!!draft.design} onChange={e=>field('design',e.target.checked)}/> خروجی محرمانه طراحی / تحقیق‌وتوسعه</label></>}
 {['create','reassign'].includes(draft.mode)&&<>{select('ownerId','مسئول واقعی تأیید دریافت',data.members.filter((m:any)=>!(draft.design||current?.data.design)||m.design).map((m:any)=>[m.id,m.name]))}<SolarDate label="موعد تحویل خدمت" value={draft.due||''} onChange={v=>field('due',v)}/></>}
 {draft.mode==='deliver'&&select('fileId','فایل واقعی خروجی خدمت',(current?.data.design?data.qmsFiles:current?.files||[]).map((f:any)=>[f.id,f.filename]))}
 {draft.mode==='cost'&&<div><p>جمع سهم‌ها باید دقیقاً {money(current?.data.amount)} باشد. هزینه متصل به بچ در پیش‌نمایش تسویه خرید خودکار اضافه می‌شود؛ آن را دوباره هزینه جانبی ثبت نکنید.</p>{draft.costs.map((a:any,i:number)=><div key={i}><label>کالا / پروژه مقصد<select required value={a.kind+':'+a.targetId} onChange={e=>{const t=data.targets.find((t:any)=>t.kind+':'+t.id===e.target.value);field('costs',draft.costs.map((x:any,j:number)=>j===i?{...x,kind:t.kind,targetId:t.id}:x))}}><option value=":">انتخاب کنید</option>{data.targets.map((t:any)=><option key={t.kind+':'+t.id} value={t.kind+':'+t.id}>{t.kind==='receipt'?'بچ کالا':t.kind==='qms'?'تحقیق‌وتوسعه':'پروژه'} · {t.title}</option>)}</select></label><label>سهم ریالی<input required value={a.amount} onChange={e=>field('costs',draft.costs.map((x:any,j:number)=>j===i?{...x,amount:latinDigits(e.target.value)}:x))}/></label><button type="button" onClick={()=>field('costs',draft.costs.filter((_:any,j:number)=>j!==i))}>حذف این سهم</button></div>)}<button type="button" className="btn" onClick={()=>field('costs',[...draft.costs,{kind:'',targetId:'',amount:''}])}>افزودن مقصد هزینه</button></div>}
 {text('notes',draft.mode==='accept'?'توضیح تأیید واقعی دریافت مطابق درخواست':'توضیح و دلیل عملیات')}</div><button className="btn primary" disabled={busy}>تأیید و ثبت</button><button type="button" className="btn" disabled={busy} onClick={()=>setDraft(null)}>انصراف</button></form>}
 </section>;
}
