"use client";
import {useEffect,useRef,useState} from 'react';
import {Plus,ShieldCheck,FileText,Upload,RefreshCw,Download} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {ProgramWorkspace,SubprogramNavigation} from './program-workspace';
import {SolarDate} from './solar-date';
import {formatDate,localDay} from '@/lib/persian-date';
import {qmsKinds,qmsStates,qmsHelp,type QField} from '@/lib/qms-contract';
const labels:Record<string,string>={submit:'ارسال برای بررسی',approve:'تأیید مستقل',return:'برگشت برای اصلاح',close:'ثبت اثربخشی و بستن',revise:'ساخت نسخه جدید',acknowledge:'مطالعه کردم',hold:'توقف آزادسازی'};
function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:Record<string,string>;label:string}){return <label className="field">{label}<Select value={value||'__none'} onValueChange={v=>onChange(v==='__none'?'':v||'')}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="__none">انتخاب کنید</SelectItem>{Object.entries(options).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select></label>}
export function QmsPanel({demo=false,targetId=''}:{demo?:boolean;targetId?:string}){
 const [query,setQuery]=useState(''),[onlyMine,setOnlyMine]=useState(false);
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[kind,setKind]=useState('document'),[product,setProduct]=useState(''),[selected,setSelected]=useState(''),[draft,setDraft]=useState<any>(null),[action,setAction]=useState(''),[note,setNote]=useState(''),[evidence,setEvidence]=useState(''),[progress,setProgress]=useState(''),[operation,setOperation]=useState('');const stop=useRef(false);
 async function load(){if(demo)return;const r=await fetch('/api/qms',{cache:'no-store'}),j:any=await r.json();if(!r.ok)throw Error(j.error);setData(j);}
 useEffect(()=>{void load().catch(e=>setError(e.message));return()=>{stop.current=true}},[demo]);useEffect(()=>{if(targetId)setSelected(targetId)},[targetId]);
 const records=data?.records||[],record=records.find((r:any)=>r.id===selected&&r.type==='qms_record'),d=record?.data;
 const canWrite=(v:any)=>v.private?data?.design:data?.ceo||qmsKinds[v.kind]?.roles.some(r=>data?.roles.includes(r));
 const canReview=d&&d.reviewerId===data?.me&&!d.editors.includes(data?.me)&&canWrite(d);
 const members=(privateOnly=false)=>Object.fromEntries((data?.members||[]).filter((m:any)=>!privateOnly||m.design).map((m:any)=>[m.id,m.name]));
 const fields=draft?(draft.kind==='response'?records.find((r:any)=>r.id===draft.templateId)?.data.fields||draft.template?.fields||[]:qmsKinds[draft.kind].fields):[];
 async function post(body:any,path='/api/qms'){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j:any=await r.json();if(!r.ok)throw Error(j.error);return j;}
 async function execute(body:any){setError('');setBusy(true);try{const j=await post({id:operation||crypto.randomUUID(),confirmed:true,...body});await load();if(j.id)setSelected(j.id);setDraft(null);setAction('');setMessage(j.followupPending?'پرونده ثبت شد؛ همگام‌سازی کارتابل در اجرای بعدی زمان‌بند تکرار می‌شود.':'ثبت شد.');setOperation('');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function create(){setDraft({kind,title:'',productId:product,private:!!qmsKinds[kind].private||!!data?.design&&kind==='form',ownerId:data?.me,reviewerId:'',due:localDay(),values:{},fields:[{key:'field_1',label:'',type:'text',required:true}],links:[]});setOperation(crypto.randomUUID());setNote('');setError('');}
 function edit(){setDraft({...structuredClone(d),recordId:record.id,revision:record.revision,templateId:d.template?.id});setOperation(crypto.randomUUID());setNote('');setError('');}
 const patch=(key:string,v:any)=>setDraft((f:any)=>({...f,[key]:v}));
 async function upload(file:File,resumeId=''){
  if(!record||busy)return;setBusy(true);setError('');stop.current=false;let fileId=resumeId;
  try{if(!fileId){const j=await post({id:crypto.randomUUID(),confirmed:true,mode:'start',parentId:record.id,filename:file.name,size:file.size},'/api/qms/files');fileId=j.id;}const status=await fetch('/api/qms/files?fileId='+encodeURIComponent(fileId),{cache:'no-store'}),j:any=await status.json();if(!status.ok)throw Error(j.error);if(j.file.data.size!==file.size||j.file.data.filename!==file.name)throw Error('برای ادامه همان فایل قبلی را انتخاب کنید.');
   for(let i=0;i<j.file.data.parts;i++){if(stop.current){setMessage('بارگذاری متوقف شد؛ با انتخاب دوباره فایل قابل ادامه است.');return;}const chunk=await file.slice(i*j.partSize,Math.min(file.size,(i+1)*j.partSize)).arrayBuffer(),sha=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',chunk))).map(x=>x.toString(16).padStart(2,'0')).join(''),old=j.received.find((p:any)=>p.index===i);if(old&&old.sha256!==sha)throw Error('محتوای فایل با بخش‌های قبلی متفاوت است.');if(!old){let last='';for(let attempt=0;attempt<3;attempt++){try{const r=await fetch('/api/qms/files?fileId='+fileId+'&part='+i,{method:'PUT',headers:{'Content-Type':'application/octet-stream','X-Operation-Id':crypto.randomUUID()},body:chunk});const p:any=await r.json();if(!r.ok)throw Error(p.error);last='';break;}catch(e){last=(e as Error).message;if(attempt<2)await new Promise(resolve=>setTimeout(resolve,500*(attempt+1)));}}if(last)throw Error(last);}setProgress(Math.round((i+1)/j.file.data.parts*100)+'٪');}
   await post({id:crypto.randomUUID(),confirmed:true,mode:'complete',fileId},'/api/qms/files');setMessage('فایل کامل و خصوصی ثبت شد.');
  }catch(e){setError((e as Error).message+' — بخش‌های دریافت‌شده محفوظ‌اند.')}finally{setBusy(false);setProgress('');await load().catch(e=>setError(e.message));}
 }
 if(demo)return <p className="notice">برای پرونده‌های واقعی کیفیت وارد اطلاعات شرکت شوید.</p>;
 if(!data)return <p className="notice">{error||'در حال دریافت پرونده‌های کیفیت…'}</p>;
 return <ProgramWorkspace programId="qms-panel" direct={!!targetId} title="کیفیت و تحقیق‌وتوسعه"><section dir="rtl" className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold flex gap-2"><ShieldCheck/> کیفیت، تحقیق‌وتوسعه و مجوزها</h2><p className="text-sm text-muted-foreground">پروندهٔ محصول، فرم‌ها، مدارک و پیگیری تأییدها</p></div><button className="btn" disabled={busy} onClick={()=>void load().catch(e=>setError(e.message))}><RefreshCw size={16}/> تازه‌سازی</button></div>
 {error&&<p role="alert" className="notice danger">{error}</p>}{message&&<p role="status" className="notice">{message}</p>}
 <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{Object.entries({total:'پرونده',review:'در انتظار بررسی',overdue:'موعد گذشته',expiring:'اعتبار تا ۳۰ روز آینده'}).map(([k,l])=><div key={k} className="rounded-xl border p-4"><strong className="text-2xl">{data.summary[k].toLocaleString('fa-IR')}</strong><p>{l}</p></div>)}</div>
 <SubprogramNavigation items={Object.entries(data.kinds).map(([key,value]:any)=>[key,value.title])} value={kind} onChange={value=>{setKind(value);setSelected('')}}/>
 <div className="grid md:grid-cols-2 gap-3"><Choice label="نوع پرونده" value={kind} onChange={v=>{if(v){setKind(v);setSelected('')}}} options={Object.fromEntries(Object.entries(data.kinds).map(([k,v]:any)=>[k,v.title]))}/><Choice label="محصول (خالی: همه محصولات)" value={product} onChange={setProduct} options={Object.fromEntries(data.products.map((p:any)=>[p.id,p.name]))}/></div>
 <div className="flex flex-wrap gap-3"><label className="field"><span>جست‌وجوی پرونده</span><input aria-label="جست‌وجوی پرونده" placeholder="جست‌وجوی نام پرونده…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="flex gap-2"><Checkbox checked={onlyMine} onCheckedChange={v=>setOnlyMine(v===true)}/>پرونده‌های مربوط به من</label></div>
 <div className="flex gap-2 flex-wrap"><button className="btn primary" disabled={busy||!canWrite({kind,private:qmsKinds[kind].private||data.design&&['form','response'].includes(kind)})} onClick={create}><Plus size={16}/> پرونده جدید</button>{(data.admin||data.ceo)&&<button className="btn" disabled={busy} onClick={()=>{setOperation(crypto.randomUUID());setAction('install_positions');setNote('')}}>تعریف جایگاه‌های سازمانی</button>}</div>
 <div className="grid lg:grid-cols-[minmax(230px,1fr)_minmax(0,2fr)] gap-4"><div className="space-y-2">{records.filter((r:any)=>r.type==='qms_record'&&r.data.kind===kind&&(!product||r.data.productId===product)&&(!query||r.data.title.includes(query))&&(!onlyMine||r.data.ownerId===data.me||r.data.reviewerId===data.me)).map((r:any)=><button key={r.id} onClick={()=>setSelected(r.id)} className={'w-full rounded-xl border p-3 text-right '+(selected===r.id?'border-primary bg-muted':'')}><strong>{r.data.title}</strong><p className="text-sm">{qmsStates[r.data.state]} · نسخه {r.data.version} {r.data.private?'· محرمانه':''}</p><p className="text-xs">موعد: {formatDate(r.data.due)}</p></button>)}</div>
 <div className="rounded-xl border p-5 space-y-4">{d?<><h3 className="font-bold text-lg">{d.title}</h3><p>{qmsStates[d.state]} · نسخه {d.version} · {d.private?'محرمانه — تحقیق‌وتوسعه و مدیرعامل':'کیفیت و واحدهای مجاز'}</p><p>مسئول: {members()[d.ownerId]} · بررسی‌کننده: {members()[d.reviewerId]}</p>
 {d.previousId&&<button className="btn" onClick={()=>setSelected(d.previousId)}>مشاهده نسخه قبلی و مدارک آن</button>}
 <div className="flex flex-wrap gap-2">{d.state==='draft'&&canWrite(d)&&<><button className="btn" disabled={busy} onClick={edit}>ویرایش</button><button className="btn primary" disabled={busy} onClick={()=>{setAction('submit');setOperation(crypto.randomUUID());setNote('')}}>ارسال برای بررسی</button></>}{['approve','return','close','revise','acknowledge','hold'].filter(mode=>mode==='approve'||mode==='return'?canReview&&d.state==='review':mode==='close'?canReview&&d.state==='approved'&&['capa','complaint','audit','management'].includes(d.kind):mode==='revise'?canWrite(d)&&['approved','closed','hold'].includes(d.state):mode==='hold'?d.kind==='release'&&['approved','review'].includes(d.state)&&(data.ceo||data.roles.includes('qa')):d.state==='approved').map(mode=><button className="btn" disabled={busy} key={mode} onClick={()=>{setAction(mode);setOperation(crypto.randomUUID());setNote('');setEvidence('')}}>{labels[mode]}</button>)}</div>
 {(d.kind==='response'?d.template.fields:qmsKinds[d.kind].fields).map((f:QField)=><div key={f.key}><strong className="text-sm">{f.label}</strong><p className="whitespace-pre-wrap text-sm">{f.type==='date'&&d.values[f.key]?formatDate(d.values[f.key]):f.type==='boolean'?({yes:'بله',no:'خیر'} as any)[d.values[f.key]]||'—':d.values[f.key]||'—'}</p></div>)}
 {d.kind==='form'&&<div><strong>فیلدهای فرم</strong>{d.fields.map((f:QField)=><p key={f.key}>{f.label}{f.required?' *':''}</p>)}</div>}
 {!!d.links?.length&&<div><strong>پرونده‌های مرتبط</strong>{d.links.map((id:string)=><button className="btn" key={id} onClick={()=>setSelected(id)}>{records.find((r:any)=>r.id===id)?.data.title||'پرونده مرتبط'}</button>)}</div>}
 <div className="border-t pt-4"><h4 className="font-bold flex gap-2"><FileText size={18}/>مدارک و فایل‌ها</h4><p className="text-xs my-2">فایل‌های حجیم چندبخشی ارسال می‌شوند. برای ادامه، همان فایل را دوباره انتخاب کنید.</p>{d.state==='draft'&&canWrite(d)&&<label className="btn"><Upload size={16}/> افزودن فایل<input type="file" className="sr-only" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value=''}}/></label>}
 {progress&&<p role="status">بارگذاری {progress} <button className="btn" onClick={()=>{stop.current=true}}>توقف بعد از این بخش</button></p>}
 {records.filter((r:any)=>r.type==='qms_file'&&r.data.parentId===record.id&&r.data.state!=='cancelled').map((f:any)=><div key={f.id} className="flex flex-wrap items-center gap-3 border-b py-3"><span className="break-all">{f.data.filename} · {(f.data.size/1024/1024).toLocaleString('fa-IR',{maximumFractionDigits:1})} مگابایت</span>{f.data.state==='ready'?<a className="btn" href={'/api/qms/files?download=1&fileId='+f.id}><Download size={16}/>دریافت</a>:<><span>ناتمام</span>{d.state==='draft'&&f.data.createdBy===data.me&&canWrite(d)&&<><label className="btn">ادامه<input type="file" className="sr-only" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file,f.id);e.target.value=''}}/></label><button className="btn" disabled={busy} onClick={async()=>{setBusy(true);try{await post({id:crypto.randomUUID(),confirmed:true,mode:'cancel',fileId:f.id},'/api/qms/files');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>لغو بارگذاری</button></>}</>}</div>)}</div>
 <details><summary>تاریخچه و اعلام مطالعه</summary>{(d.history||[]).map((h:any,i:number)=><p key={i} className="text-sm my-2">{formatDate(h.at)} · {members()[h.by]||h.by} · {labels[h.mode]||'ثبت'}: {h.notes}</p>)}{(d.acknowledgments||[]).map((x:any)=><p key={x.memberId}>{members()[x.memberId]} · {formatDate(x.at)}</p>)}</details></>:<p className="text-muted-foreground">یک پرونده انتخاب کنید یا پرونده جدید بسازید.</p>}</div></div>
 <details className="rounded-xl border p-4"><summary>راهنمای کار و جایگاه‌ها</summary>{qmsHelp.map(x=><p className="text-sm my-3" key={x}>{x}</p>)}{Object.entries(data.roleLabels).map(([k,v]:any)=><p key={k}>{v}</p>)}<p>تحقیق‌وتوسعه و مدیرعامل: نقش‌های صریح در دسترسی برنامه‌ریزی تأمین. تعریف جایگاه به‌تنهایی به هیچ حسابی مجوز نمی‌دهد.</p></details>
 <Dialog open={!!draft} onOpenChange={v=>{if(!v&&!busy)setDraft(null)}}><DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto" dir="rtl"><DialogTitle>{draft?.recordId?'ویرایش پرونده':'پرونده جدید'}</DialogTitle><DialogDescription>پیش‌نویس را ذخیره کنید، مدارک را اضافه کنید و سپس برای بررسی بفرستید.</DialogDescription>{draft&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();void execute({...draft,mode:'save',revision:draft.revision||0,notes:note})}}><label className="field">نام پرونده / فرم<input className="input" required value={draft.title} onChange={e=>patch('title',e.target.value)}/></label><Choice label="محصول" value={draft.productId} onChange={v=>{if(!draft.recordId)patch('productId',v)}} options={Object.fromEntries(data.products.map((p:any)=>[p.id,p.name]))}/>{!draft.recordId&&!qmsKinds[draft.kind].private&&draft.kind!=='response'&&data.design&&<label className="flex gap-2"><Checkbox checked={draft.private} onCheckedChange={v=>patch('private',v===true)}/>محرمانه برای تحقیق‌وتوسعه و مدیرعامل</label>}
 {draft.kind==='response'&&!draft.recordId&&<Choice label="فرم مصوب محصول" value={draft.templateId||''} onChange={v=>{const t=records.find((r:any)=>r.id===v);setDraft({...draft,templateId:v,private:t?.data.private,values:{}})}} options={Object.fromEntries(records.filter((r:any)=>r.type==='qms_record'&&r.data.kind==='form'&&r.data.state==='approved'&&r.data.productId===draft.productId).map((r:any)=>[r.id,r.data.title+' — نسخه '+r.data.version]))}/>}
 <div className="grid md:grid-cols-2 gap-3"><Choice label="مسئول" value={draft.ownerId} onChange={v=>patch('ownerId',v)} options={members(draft.private)}/><Choice label="بررسی‌کننده مستقل" value={draft.reviewerId} onChange={v=>patch('reviewerId',v)} options={Object.fromEntries(data.members.filter((m:any)=>m.id!==draft.ownerId&&(draft.private?m.design:m.ceo||qmsKinds[draft.kind].roles.some(r=>m.roles.includes(r)))).map((m:any)=>[m.id,m.name]))}/><label className="field">موعد پیگیری<SolarDate label="موعد پیگیری" value={draft.due} onChange={v=>patch('due',v)}/></label></div>
 {fields.map((f:QField)=><label className="field" key={f.key}>{f.label}{f.required?' *':''}{f.type==='date'?<SolarDate label={f.label} required={false} value={draft.values[f.key]||''} onChange={v=>patch('values',{...draft.values,[f.key]:v})}/>:f.type==='choice'||f.type==='boolean'?<Choice label="" value={draft.values[f.key]||''} onChange={v=>patch('values',{...draft.values,[f.key]:v})} options={f.type==='boolean'?{yes:'بله',no:'خیر'}:Object.fromEntries((f.options||[]).map(x=>[x,x]))}/>:<textarea className="input min-h-20" value={draft.values[f.key]||''} onChange={e=>patch('values',{...draft.values,[f.key]:e.target.value})}/>}</label>)}
 {draft.kind==='form'&&<div className="space-y-3"><h4>ساخت فیلدهای فرم</h4>{draft.fields.map((f:QField,i:number)=><div key={i} className="border rounded-lg p-3 space-y-2"><label className="field">عنوان فیلد<input className="input" required value={f.label} onChange={e=>patch('fields',draft.fields.map((x:QField,j:number)=>j===i?{...x,label:e.target.value}:x))}/></label><Choice label="نوع پاسخ" value={f.type} options={{text:'متن',number:'عدد',date:'تاریخ',choice:'انتخابی',boolean:'بله / خیر'}} onChange={v=>patch('fields',draft.fields.map((x:QField,j:number)=>j===i?{...x,type:v}:x))}/>{f.type==='choice'&&<label className="field">گزینه‌ها (هر خط یک گزینه)<textarea className="input" value={(f.options||[]).join('\n')} onChange={e=>patch('fields',draft.fields.map((x:QField,j:number)=>j===i?{...x,options:e.target.value.split('\n')}:x))}/></label>}<label className="flex gap-2"><Checkbox checked={f.required} onCheckedChange={v=>patch('fields',draft.fields.map((x:QField,j:number)=>j===i?{...x,required:v===true}:x))}/>الزامی</label><button type="button" className="btn" onClick={()=>patch('fields',draft.fields.filter((_:any,j:number)=>j!==i))}>حذف فیلد</button></div>)}<button type="button" className="btn" onClick={()=>patch('fields',[...draft.fields,{key:'f_'+crypto.randomUUID().replaceAll('-',''),label:'',type:'text',required:true}])}>افزودن فیلد</button></div>}
 <Choice label="افزودن پرونده مرتبط" value="" options={Object.fromEntries(records.filter((r:any)=>r.type==='qms_record'&&r.id!==draft.recordId&&(!r.data.private||draft.private)&&!draft.links?.includes(r.id)).map((r:any)=>[r.id,r.data.title]))} onChange={v=>{if(v)patch('links',[...(draft.links||[]),v])}}/>{draft.links?.map((id:string)=><button type="button" className="btn" key={id} onClick={()=>patch('links',draft.links.filter((x:string)=>x!==id))}>{records.find((r:any)=>r.id===id)?.data.title} ×</button>)}
 <label className="field">علت ثبت / ویرایش<textarea className="input" required value={note} onChange={e=>setNote(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button className="btn primary" disabled={busy}>ذخیره پیش‌نویس</button></form>}</DialogContent></Dialog>
 <Dialog open={!!action} onOpenChange={v=>{if(!v&&!busy)setAction('')}}><DialogContent dir="rtl"><DialogTitle>{labels[action]||'تعریف جایگاه‌ها'}</DialogTitle><DialogDescription>{action==='install_positions'?'جایگاه‌ها بدون تعیین عضو یا اعطای مجوز ساخته می‌شوند.':'عملیات روی همین نسخه ثبت می‌شود و در تاریخچه باقی می‌ماند.'}</DialogDescription><form className="space-y-3" onSubmit={e=>{e.preventDefault();void execute({mode:action,...(action==='install_positions'?{}:{recordId:record.id,revision:record.revision}),notes:note,evidence})}}><label className="field">توضیح و مستند تصمیم<textarea required className="input" value={note} onChange={e=>setNote(e.target.value)}/></label>{action==='close'&&<label className="field">شواهد واقعی اثربخشی<textarea required className="input" value={evidence} onChange={e=>setEvidence(e.target.value)}/></label>}{error&&<p role="alert">{error}</p>}<button className="btn primary" disabled={busy}>تأیید و ثبت</button></form></DialogContent></Dialog>
 </section></ProgramWorkspace>;
}
