"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {SolarDate} from './solar-date';
import {reminderTriggers,reminderLinks,reminderConditions,reminderFields,reminderHelp} from '@/lib/reminder-contract';
const display=(s:string)=>s?new Intl.DateTimeFormat('fa-IR',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Tehran'}).format(new Date(s)):'بدون موعد پیگیری';
const blank=()=>({title:'',notes:'',trigger:'time',linkType:'none',linkId:'',eventField:'updated',eventCondition:'changed',eventValue:'',day:'',time:'09:00'});
async function request(accountId:string,path:string,body?:any,signal?:AbortSignal){const r=await fetch(path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','x-assistant-account':accountId},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store',signal});const d:any=await r.json();if(!r.ok)throw Error(d.error||'ارتباط برقرار نشد.');if(d.accountId!==accountId)throw Error('حساب تغییر کرده؛ صفحه را تازه کنید.');return d;}
export function RemindersPanel({accountId,demo=false}:{accountId:string;demo?:boolean}){
 const [rows,setRows]=useState<any[]>([]),[draft,setDraft]=useState(blank),[editing,setEditing]=useState<any>(null),[links,setLinks]=useState<any[]>([]),[query,setQuery]=useState(''),[limited,setLimited]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[showClosed,setShowClosed]=useState(false);const retry=useRef<{key:string;id:string}|null>(null);
 const load=useCallback(async()=>{if(demo)return;try{const d=await request(accountId,'/api/reminders');setRows(d.reminders);}catch(e){setError((e as Error).message);}},[accountId,demo]);
 useEffect(()=>{void load();const f=()=>void load();window.addEventListener('nafasyar-reminders-changed',f);return()=>window.removeEventListener('nafasyar-reminders-changed',f);},[load]);
 useEffect(()=>{setLinks([]);if(demo||draft.linkType==='none')return;const c=new AbortController();const timer=setTimeout(()=>{void request(accountId,'/api/reminders?view=links&kind='+encodeURIComponent(draft.linkType)+'&query='+encodeURIComponent(query),undefined,c.signal).then(d=>{setLinks(d.links);setLimited(d.limited);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});},250);return()=>{clearTimeout(timer);c.abort();};},[accountId,demo,draft.linkType,query]);
 const selected=links.find(r=>r.id===draft.linkId),field=selected?.fields[draft.eventField];
 function change(key:string,value:string){setDraft(d=>({...d,[key]:value}));}
 async function apply(body:any){if(busy||demo)return;setBusy(true);setError('');setMessage('');const key=JSON.stringify(body);if(retry.current?.key!==key)retry.current={key,id:crypto.randomUUID()};try{await request(accountId,'/api/reminders',{...body,id:retry.current.id,confirmed:true});retry.current=null;setMessage('یادآور ذخیره شد.');if(body.mode==='save'){setEditing(null);setDraft(blank());}await load();window.dispatchEvent(new Event('nafasyar-reminders-changed'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function edit(r:any){const d=r.data;let day='',time='09:00';if(d.dueAt){const local=new Date(Date.parse(d.dueAt)+210*60000).toISOString();day=local.slice(0,10);time=local.slice(11,16);}setEditing(r);setQuery('');setDraft({...blank(),...d,day,time});}
 if(demo)return <p className="notice">یادآور شخصی در محیط اطلاعات شرکت در دسترس است.</p>;
 return <section dir="rtl" className="panel"><h2>یادآورهای من</h2><p className="subtle">{reminderHelp}</p>{error&&<p role="alert" className="notice">{error}</p>}{message&&<p role="status">{message}</p>}
 <form onSubmit={e=>{e.preventDefault();void apply({mode:'save',reminderId:editing?.id,revision:editing?.revision||0,title:draft.title,notes:draft.notes,trigger:draft.trigger,linkType:draft.linkType,linkId:draft.linkId,eventField:draft.eventField,eventCondition:draft.eventCondition,eventValue:draft.eventValue,dueAt:draft.day?new Date(draft.day+'T'+draft.time+':00+03:30').toISOString():''});}}>
 <fieldset disabled={busy} style={{border:0,padding:0,display:'grid',gap:14}}><legend>{editing?'ویرایش یادآور':'یادآور جدید'}</legend>
 <label className="field">عنوان یادآور<input required maxLength={200} value={draft.title} onChange={e=>change('title',e.target.value)}/></label>
 <label className="field">توضیحات و کاری که باید پیگیری کنم<textarea maxLength={4000} value={draft.notes} onChange={e=>change('notes',e.target.value)} placeholder="مثلاً اسناد داخل جعبهٔ مشخص را از انباردار بخواهم"/></label>
 <label className="field">نوع یادآوری<select value={draft.trigger} onChange={e=>change('trigger',e.target.value)}>{Object.entries(reminderTriggers).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>
 <label className="field">فرایند مرتبط {draft.trigger==='time'?'(اختیاری)':'(الزامی)'}<select required value={draft.linkType} onChange={e=>setDraft(d=>({...d,linkType:e.target.value,linkId:'',eventField:'updated',eventCondition:'changed',eventValue:''}))}>{Object.entries(reminderLinks).filter(([k])=>draft.trigger==='time'||k!=='none').map(([v,t])=><option key={v} value={v}>{t}</option>)}{draft.trigger==='event'&&draft.linkType==='none'&&<option value="none">فرایند را انتخاب کنید</option>}</select></label>
 {draft.linkType!=='none'&&<><label className="field">جست‌وجوی پرونده یا پروژه<input value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="field">پرونده یا پروژهٔ موردنظر<select required value={draft.linkId} onChange={e=>setDraft(d=>({...d,linkId:e.target.value,eventField:'updated',eventCondition:'changed',eventValue:''}))}><option value="">انتخاب کنید</option>{links.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label>{limited&&<p>فهرست محدود است؛ جست‌وجو را دقیق‌تر کنید.</p>}{!links.length&&<p>پرونده‌ای با دسترسی شما و این عبارت پیدا نشد.</p>}</>}
 {draft.trigger==='event'&&selected&&<><label className="field">نقطهٔ موردنظر در فرایند<select value={draft.eventField} onChange={e=>setDraft(d=>({...d,eventField:e.target.value,eventCondition:'changed',eventValue:''}))}>{Object.entries(selected.fields).map(([v,f]:any)=><option key={v} value={v}>{f.label}</option>)}</select></label><label className="field">شرط رخداد<select value={draft.eventCondition} onChange={e=>change('eventCondition',e.target.value)}>{Object.entries(reminderConditions).filter(([k])=>k==='changed'||draft.eventField!=='updated'&&!draft.eventField.endsWith('At')).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>{draft.eventCondition==='equals'&&<label className="field">مرحلهٔ مقصد<select required value={draft.eventValue} onChange={e=>change('eventValue',e.target.value)}><option value="">انتخاب کنید</option>{Object.entries(field?.options||{}).map(([v,t]:any)=><option key={v} value={v}>{t}</option>)}</select></label>}<p>این شرط برای تغییرات بعد از ذخیره است. اگر پرونده هم‌اکنون در مرحلهٔ مقصد باشد، صرف ذخیره اعلان ایجاد نمی‌کند.</p></>}
 <SolarDate label={draft.trigger==='time'?'تاریخ یادآوری':'اگر رویداد اتفاق نیفتاد، تاریخ پیگیری'} required={draft.trigger==='time'} value={draft.day} onChange={v=>change('day',v)}/><label className="field">ساعت به وقت ایران<input type="time" required={!!draft.day||draft.trigger==='time'} value={draft.time} onChange={e=>change('time',e.target.value)}/></label>{draft.trigger==='event'&&draft.day&&<button type="button" onClick={()=>change('day','')}>حذف موعد پیگیری</button>}
 <button type="submit" disabled={draft.trigger==='event'&&(!selected||!field)}>{busy?'در حال ثبت…':editing?'ذخیره تغییرات':'ثبت یادآور'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setDraft(blank());}}>انصراف از ویرایش</button>}</fieldset></form>
 <hr/><label><input type="checkbox" checked={showClosed} onChange={e=>setShowClosed(e.target.checked)}/> نمایش انجام‌شده‌ها و لغوشده‌ها</label><button type="button" onClick={()=>void load()}>تازه‌سازی</button>
 {rows.filter(r=>showClosed||r.data.state==='active').map(r=><article key={r.id} className="panel" style={{marginTop:12}}><h3>{r.data.title}</h3><p style={{whiteSpace:'pre-wrap'}}>{r.data.notes}</p><p>{reminderTriggers[r.data.trigger]} · {display(r.data.dueAt)}</p>{r.data.linkType!=='none'&&<p>{reminderLinks[r.data.linkType]} · {r.data.linkAvailable?r.data.linkLabel:'دسترسی به پرونده مرتبط اکنون در دسترس نیست'}</p>}{r.data.trigger==='event'&&<p>{reminderFields[r.data.eventField]} · {reminderConditions[r.data.eventCondition]}{r.data.eventCondition==='equals'?': '+r.data.eventValueLabel:''}</p>}{r.data.alerts.map((a:any)=><p key={a.key} role={a.readAt?undefined:'status'}>{a.kind==='event'?'رویداد موردنظر ثبت شد؛ اکنون پیگیری کنید.':a.kind==='followup'?'موعد پیگیری رسیده؛ وقوع رویداد هنوز تأیید نشده است.':'زمان یادآوری رسیده است.'} {display(a.at)}{a.readAt?' — خوانده‌شده':''}</p>)}<p>{r.data.state==='done'?'انجام‌شده':r.data.state==='cancelled'?'لغوشده':'فعال'}</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{r.data.alerts.some((a:any)=>!a.readAt)&&<button disabled={busy} onClick={()=>void apply({mode:'seen',reminderId:r.id,revision:r.revision})}>خواندم</button>}{r.data.state==='active'&&<><button disabled={busy} onClick={()=>edit(r)}>ویرایش / تغییر زمان</button><button disabled={busy} onClick={()=>void apply({mode:'done',reminderId:r.id,revision:r.revision})}>انجام شد</button><button disabled={busy} onClick={()=>void apply({mode:'cancel',reminderId:r.id,revision:r.revision})}>لغو یادآور</button></>}</div></article>)}{!rows.length&&<p>هنوز یادآوری ثبت نکرده‌اید.</p>}</section>;
}
export function ReminderNotifier({accountId,onOpen}:{accountId:string;onOpen:()=>void}){
 const [count,setCount]=useState(0),[error,setError]=useState('');
 useEffect(()=>{let alive=true,running=false;const c=new AbortController();async function check(){if(running||document.hidden)return;running=true;try{await request(accountId,'/api/reminders/check',{},c.signal);const d=await request(accountId,'/api/reminders',undefined,c.signal);if(alive){setCount(d.reminders.reduce((n:number,r:any)=>n+r.data.alerts.filter((a:any)=>!a.readAt).length,0));setError('');}}catch(e){if(alive)setError('بررسی یادآورها موقتاً انجام نشد');}finally{running=false;}}void check();const timer=setInterval(check,60000);window.addEventListener('focus',check);document.addEventListener('visibilitychange',check);window.addEventListener('nafasyar-reminders-changed',check);return()=>{alive=false;c.abort();clearInterval(timer);window.removeEventListener('focus',check);document.removeEventListener('visibilitychange',check);window.removeEventListener('nafasyar-reminders-changed',check);};},[accountId]);
 return count||error?<button type="button" onClick={onOpen} className="notice" style={{position:'fixed',top:90,left:16,zIndex:40}}>{count?count.toLocaleString('fa-IR')+' یادآوری برای شما':error}</button>:null;
}
