'use client';
import {useEffect,useState} from 'react';
import {SolarDate} from './solar-date';
import {formatDate,formatDateTime} from '@/lib/persian-date';
export function ReplenishmentPanel({onOpen}:{onOpen:(id:string)=>void}){
 const [data,setData]=useState<any>(null),[draft,setDraft]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[holiday,setHoliday]=useState('');
 async function refresh(){const r=await fetch('/api/replenishment',{cache:'no-store'}),d=await r.json() as any;if(!r.ok||d.error)throw Error(d.error||'دریافت نشد');setData(d);setDraft(structuredClone(d.policy.data));}
 useEffect(()=>{void refresh().catch(e=>setError(e.message))},[]);
 async function send(mode:string){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/replenishment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,revision:data.policy.revision,policy:draft,confirmed:true})}),d=await r.json() as any;if(!r.ok)throw Error(d.error);await refresh();setMessage(mode==='scan'?'پایش انجام شد؛ پرونده‌ها و کارتابل را بررسی کنید.':'تنظیمات ذخیره شد. تغییر مهلت‌ها برای مرحله‌های جدید است.');window.dispatchEvent(new Event('nafasyar-tasks-changed'));}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="replenishment-panel"><div className="panelhead"><div><h3>پایش کسری و پیگیری تأمین</h3><p>تشخیص نیاز ← بررسی انبار ← استعلام ← انتخاب و مالی ← خرید ← پذیرش انبار</p></div>{data?.admin&&<button className="btn" disabled={busy||!data.policy.data.enabled} onClick={()=>void send('scan')}>پایش همین حالا</button>}</div>{error&&<p role="alert" className="notice error">{error}</p>}{message&&<p role="status" className="notice">{message}</p>}
 {data&&<><p className="notice">{data.policy.data.enabled?'پایش فعال است.':'پایش خودکار هنوز فعال نشده؛ مدیر ابتدا مسئول‌ها و ساعت کاری را ذخیره کند.'}</p>{data.backgroundStale&&<p className="notice error">اجرای زمان‌بند پس‌زمینه در ۱۵ دقیقه اخیر تأیید نشده است. وقتی برنامه بسته است، پیگیری قابل اتکا نیست؛ زمان‌بند سرور باید هر ۵ دقیقه اجرا شود.</p>}{data.backgroundLastAt&&<p>آخرین اجرای پس‌زمینه: {formatDateTime(data.backgroundLastAt)}</p>}{data.issues.map((s:string)=><p className="notice error" key={s}>{s}</p>)}
 {data.admin&&draft&&<details><summary>تنظیم مسئول‌ها، تقویم کاری و یادآوری</summary><form onSubmit={e=>{e.preventDefault();void send('policy')}}><fieldset disabled={busy}><div className="formgrid">{Object.entries(data.roles).map(([role,title])=><label className="field" key={role}>{String(title)}<select value={draft.owners[role]||''} onChange={e=>setDraft({...draft,owners:{...draft.owners,[role]:e.target.value}})}><option value="">انتخاب مسئول</option>{data.eligible[role].map((m:any)=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>)}<label className="field">سرپرست پیگیری تأخیر<select value={draft.supervisor} onChange={e=>setDraft({...draft,supervisor:e.target.value})}><option value="">انتخاب سرپرست</option>{data.supervisors.map((m:any)=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>
 <label className="field">شروع شیفت، تهران<input type="time" required value={draft.calendar.start} onChange={e=>setDraft({...draft,calendar:{...draft.calendar,start:e.target.value}})}/></label><label className="field">پایان شیفت، تهران<input type="time" required value={draft.calendar.end} onChange={e=>setDraft({...draft,calendar:{...draft.calendar,end:e.target.value}})}/></label>
 {([['slaMinutes','مهلت هر مرحله عادی، دقیقه کاری',30,10080],['criticalSlaMinutes','مهلت مرحله با موجودی صفر، دقیقه کاری',15,480],['reminderMinutes','فاصله یادآوری پس از سررسید، دقیقه کاری',30,1440],['escalationMinutes','ارجاع به سرپرست پس از چند دقیقه تأخیر کاری',30,10080],['leadDays','افق محاسبه خریدهای در راه، روز تقویمی',1,365]] as [string,string,number,number][]).map(([key,label,min,max])=><label className="field" key={key}>{label}<input type="number" min={min} max={max} required value={draft[key]} onChange={e=>setDraft({...draft,[key]:Number(e.target.value)})}/></label>)}
 <div className="wide">روزهای کاری<div className="tools">{[['شنبه',6],['یکشنبه',0],['دوشنبه',1],['سه‌شنبه',2],['چهارشنبه',3],['پنجشنبه',4],['جمعه',5]].map(([title,n])=><label key={n} className="flow-check"><input type="checkbox" checked={draft.calendar.weekdays.includes(n)} onChange={e=>setDraft({...draft,calendar:{...draft.calendar,weekdays:e.target.checked?[...draft.calendar.weekdays,n]:draft.calendar.weekdays.filter((v:number)=>v!==n)}})}/>{title}</label>)}</div></div>
 <div className="wide"><SolarDate label="تعطیلی شرکت" value={holiday} onChange={setHoliday}/><button type="button" className="btn" disabled={!holiday} onClick={()=>{setDraft({...draft,calendar:{...draft.calendar,holidays:[...new Set([...draft.calendar.holidays,holiday])]}});setHoliday('')}}>افزودن تعطیلی</button>{draft.calendar.holidays.map((d:string)=><button key={d} type="button" className="btn" onClick={()=>setDraft({...draft,calendar:{...draft.calendar,holidays:draft.calendar.holidays.filter((v:string)=>v!==d)}})}>{formatDate(d)} · حذف</button>)}</div>
 <label className="flow-check wide"><input type="checkbox" checked={draft.enabled} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/>فعال‌سازی ایجاد خودکار پرونده کمبود</label><p className="wide subtle">مجوز افراد در «کاربران و دسترسی‌ها» تعیین می‌شود؛ این تنظیمات مجوز جدید نمی‌دهد. هر نقش یک مسئول پاسخ‌گو دارد؛ در QC و جانمایی، مسئول تعیین‌شده روی محموله اولویت دارد. خرید، پرداخت و QC همچنان به تأیید فرد مجاز نیاز دارند.</p></div><button className="btn primary" disabled={busy}>ذخیره و تأیید تنظیمات</button></fieldset></form></details>}
 <div className="replenishment-stock">{data.stock.length===0?<p>کسری مؤثر زیر حد سفارش پیدا نشد.</p>:data.stock.map((s:any)=><article className="flow-card" key={s.id}><h4>{s.name} · {s.code}</h4><p>موجودی آزاد: {(s.free/1000).toLocaleString('fa-IR')} {s.unit} · خرید آزاد در راه: {(s.incoming/1000).toLocaleString('fa-IR')} · قرنطینه: {(s.quarantine/1000).toLocaleString('fa-IR')}</p><p>پیشنهاد تأمین: {(s.proposed/1000).toLocaleString('fa-IR')} {s.unit}</p>{s.openPlan?<button className="btn primary" onClick={()=>onOpen(s.openPlan)}>بازکردن پرونده کمبود</button>:s.legacyOpen||s.otherDemand?<p className="notice">درخواست تأمین یا برنامه مرتبط باز وجود دارد؛ برای جلوگیری از خرید تکراری پرونده خودکار دیگری ساخته نمی‌شود. آن درخواست را بررسی کنید.</p>:<p>پس از فعال‌سازی پایش، برای بررسی انبار پرونده ایجاد می‌شود.</p>}</article>)}</div></>}
 </div>;
}
