'use client';
import {IconDisclosure} from "./program-workspace";
import {ProgramWorkspace,SubprogramNavigation} from "./program-workspace";
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {SolarDate} from './solar-date';
import {formatDate,localDay,latinDigits} from '@/lib/persian-date';
const names:Record<string,string>={policy:'نسخه تنظیم زمان مفید',route:'نسخه مسیر ساخت و کارسنجی',lot:'بچ ساخت قطعه واسط',assign:'تخصیص کار روزانه',adjust:'اصلاح زمان در دسترس',output:'ثبت خروجی و مصرف',close:'بستن کار روز',reason:'توضیح کارگر',review:'نتیجه بررسی سرکارگر',quality:'تأیید کیفیت و رسید نیمه‌ساخته',cost:'نهایی‌سازی بهای بچ'};
const n=(v:any)=>v===null||v===undefined?'—':Number(v).toLocaleString('fa-IR',{maximumFractionDigits:2});
const time=(m:number)=>String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0');
export function RoutineProductionPanel({demo=false}:{demo?:boolean}){
 const [data,setData]=useState<any>(null),[tab,setTab]=useState('jobs'),[day,setDay]=useState(localDay()),[lotId,setLotId]=useState(''),[draft,setDraft]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(){const r=await fetch('/api/routine-production',{cache:'no-store'}),v:any=await r.json();if(!r.ok)throw Error(v.error);setData(v);}
 useEffect(()=>{if(!demo)void load().catch(e=>setError(e.message));},[demo]);
 const begin=(mode:string,extra:any={})=>{setError('');setDraft({id:crypto.randomUUID(),confirmed:true,mode,notes:'',...extra});};
 const field=(key:string,v:any)=>setDraft((d:any)=>({...d,[key]:v}));
 const input=(k:string,label:string,type='text',required=true)=><label className="field">{label}<input type={type} required={required} value={draft[k]??''} onChange={e=>field(k,type==='number'?(e.target.value===''?null:Number(latinDigits(e.target.value))):e.target.value)}/></label>;
 const pick=(k:string,label:string,items:any[])=><label className="field">{label}<select required value={draft[k]??''} onChange={e=>field(k,e.target.value)}><option value="">انتخاب کنید</option>{items.map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label>;
 const button=(mode:string,extra:any={},label=names[mode])=><button className="btn" disabled={busy} onClick={()=>begin(mode,extra)}>{label}</button>;
 const table=(headers:string[],rows:any[][])=><div style={{overflowX:'auto'}}><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="empty">هنوز موردی ثبت نشده است.</p>}</div>;
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const body={...draft};if(body.stage!==undefined)body.stage=Number(body.stage);const r=await fetch('/api/routine-production',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),v:any=await r.json();if(!r.ok)throw Error(v.error);await load();setDraft(null);setMessage('ثبت شد. گزارش کار و موجودی مرتبط به‌روز شدند.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 if(demo)return <p className="notice">کنترل روزانه تولید در اطلاعات شرکت در دسترس است.</p>;
 if(!data)return <section className="panel"><p role="status">{error||'در حال دریافت تولید روزانه…'}</p><button className="btn" onClick={()=>void load().catch(e=>setError(e.message))}>تلاش دوباره</button></section>;
 const roles=data.roles,lot=data.lots.find((l:any)=>l.id===lotId),jobs=data.jobs.filter((j:any)=>j.data.day===day),draftJob=data.jobs.find((j:any)=>j.id===draft?.jobId),draftLot=data.lots.find((l:any)=>l.id===draft?.lotId),route=draftLot?.data.route;
 const daily=Object.values(jobs.reduce((a:any,j:any)=>{const d=j.data,r=d.report,v=a[d.memberId]||{name:d.memberName,minutes:0,earned:0,low:0,high:0,provisional:false};v.minutes+=r.usefulMinutes;v.earned+=r.regular*d.step.seconds/60;v.low+=r.shortfall;v.provisional||=r.provisional;a[d.memberId]=v;return a;},{})) as any[];
 return <ProgramWorkspace programId="routine-production-panel" title="تولید روزانه"><section className="panel" dir="rtl"><div className="panelhead"><div><h2>کار روزانه و ساخت قطعات واسط</h2><p>هدف کار · خروجی عملیات · موجودی در جریان ساخت</p></div><button className="btn" onClick={()=>void load().catch(e=>setError(e.message))}>تازه‌سازی</button></div>
 {error&&!draft&&<p className="notice error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 <SubprogramNavigation items={(Object.entries({jobs:'کار روزانه',...(roles.staff?{lots:'ساخت و موجودی',routes:'مسیر و کارسنجی',policies:'زمان مفید'}:{}),help:'راهنما'})).map(([key,title])=>[String(key),String(title)] as [string,string])} value={tab} onChange={setTab}/>
 {tab==='jobs'&&<><div className="form-grid"><label className="field">روز کاری<SolarDate label="تاریخ" value={day} onChange={setDay}/></label>{roles.foreman&&<div>{button('assign',{lotId:lotId||'',day,start:'',end:'',count:1,stage:0,rework:false,revision:lot?.revision})}</div>}</div>
 {daily.length>0&&table(['کارگر','زمان مفید (دقیقه)','دقیقه استاندارد خروجی سالم','تحقق وزنی روز'],daily.map(v=>[v.name,n(v.minutes),n(v.earned),v.provisional?'موقت؛ تنظیمات کامل نیست':v.minutes?n(v.earned/v.minutes*100)+'٪':'بدون زمان مفید']))}
 {table(['کارگر و عملیات','بازه حضور','هدف و بازه','سالم عادی / اضافه‌کاری','درصد تحقق','وضعیت و اقدام'],jobs.map((j:any)=>{const d=j.data,r=d.report;return [<><strong>{d.memberName}</strong><br/>{d.partName} · {d.step.title}{d.rework&&' · دوباره‌کاری'}<br/>{d.lotTitle}</>,time(d.start)+' تا '+time(d.end),<>{n(r.target)} قطعه<br/>{n(r.lower)} تا {n(r.upper)}<br/>{d.rework?'دوباره‌کاری؛ هدف ارزیابی موقت':r.provisional?'موقت':'طبق نسخه ثبت‌شده'}<br/>{n(r.usefulMinutes)} دقیقه مفید</>,n(r.regular)+' / '+n(r.overtime),n(r.attainment)+(r.attainment===null?'':'٪'),<><p>{d.state==='closed'?'بسته‌شده':'باز'} · باقی‌مانده {n(d.remaining)} · فاصله از کف هدف {n(r.shortfall)}</p><div className="tools" style={{flexWrap:'wrap'}}>{roles.foreman&&d.state==='open'&&<>{button('adjust',{jobId:j.id,revision:j.revision,leaveMinutes:d.leaveMinutes,downtimeMinutes:d.downtimeMinutes,setupMinutes:d.setupMinutes,restMinutes:d.restMinutes??null,overtimeApproved:d.overtimeApproved||false})}{button('output',{jobId:j.id,revision:j.revision,good:0,scrap:0,reworkCount:0,overtime:false,allocations:[]})}{button('close',{jobId:j.id,revision:j.revision,actualMinutes:null,overtimeMinutes:0})}</>}{button('reason',{jobId:j.id,revision:j.revision,notes:d.workerReason||''})}{roles.foreman&&d.state==='closed'&&button('review',{jobId:j.id,revision:j.revision})}</div><IconDisclosure scope="routine-production-panel-details-e71436ee64" title={<> سوابق و توضیحات </>}><p>توضیح کارگر: {d.workerReason||'ثبت نشده'} · بررسی: {d.review?.notes||'انجام نشده'}</p>{d.state==='closed'&&<p>زمان واقعی: {n(d.actualMinutes)} دقیقه · اضافه‌کاری: {n(d.overtimeMinutes)} دقیقه</p>}{table(['سالم','ضایعات','دوباره‌کاری','نوع','توضیح'],d.outputs.map((o:any)=>[n(o.good),n(o.scrap),n(o.rework),o.overtime?'اضافه‌کاری':'عادی',o.notes]))}</IconDisclosure></>];}))}</>}
 {tab==='lots'&&<>{roles.foreman&&button('lot',{count:1})}<label className="field">بچ ساخت<select value={lotId} onChange={e=>setLotId(e.target.value)}><option value="">انتخاب کنید</option>{data.lots.map((l:any)=><option key={l.id} value={l.id}>{l.data.title} · {l.data.route.name}</option>)}</select></label>{lot&&<><h3>{lot.data.title} · {lot.data.route.name}</h3><p>تعداد آغاز: {n(lot.data.count)} · منتظر کیفیت: {n(lot.data.pending)} · مجموع رسید تأییدشده: {n(lot.data.received)} · ضایعات: {n(lot.data.scrap)}</p>{table(['مرحله','آماده تخصیص','منتظر دوباره‌کاری','نزد کارگر'],lot.data.route.steps.map((s:any,i:number)=>[s.title,n(lot.data.ready[i]),n(lot.data.rework[i]),n(data.jobs.filter((j:any)=>j.data.lotId===lot.id&&j.data.stage===i&&j.data.state==='open').reduce((a:number,j:any)=>a+j.data.remaining,0))]))}<div className="tools" style={{flexWrap:'wrap'}}>{roles.foreman&&!lot.data.cost&&button('assign',{lotId:lot.id,revision:lot.revision,day,start:'',end:'',count:1,stage:0,rework:false})}{roles.quality&&lot.data.pending>0&&button('quality',{lotId:lot.id,revision:lot.revision,good:lot.data.pending,scrap:0,reworkCount:0})}{roles.finance&&!lot.data.cost&&button('cost',{lotId:lot.id,revision:lot.revision,overhead:'',rates:data.jobs.filter((j:any)=>j.data.lotId===lot.id).map((j:any)=>({jobId:j.id,hourly:'',overtimeHourly:'0'}))})}</div>{lot.data.cost&&<p>بهای واحد: {n(lot.data.cost.unitCost)} ریال · مواد: {n(lot.data.cost.materials)} · دستمزد: {n(lot.data.cost.labor)} · سربار: {n(lot.data.cost.overhead)}</p>}<IconDisclosure scope="routine-production-panel-details-fa920bcc5c" title={<> مصرف مواد و کیفیت </>}>{table(['بچ مصرفی','مقدار','توضیح'],lot.data.movements.map((m:any)=>[data.line.find((l:any)=>l.item_id===m.batchId)?.code||m.batchId,n(m.quantity/1000),m.notes]))}{table(['سالم','ضایعات','دوباره‌کاری','مرجع'],lot.data.quality.map((q:any)=>[n(q.good),n(q.scrap),n(q.rework),q.reference]))}</IconDisclosure></>}
 <h3>موجودی قابل مصرف خط</h3>{table(['بچ','قطعه','موجودی','واحد'],data.line.map((b:any)=>[b.code||b.item_id,b.part||b.partCode,n(b.quantity/1000),b.unit]))}</>}
 {tab==='routes'&&<>{roles.engineering&&button('route',{steps:[{title:'',seconds:60,allowancesIncluded:null,bom:[]}]})}{data.routes.map((r:any)=><IconDisclosure scope="routine-production-panel-details-81d4e06342" title={<> {r.data.name} · نسخه {n(r.data.version)} </>}>{table(['مرحله','ثانیه هر قطعه','استراحت در استاندارد','مواد هر قطعه'],r.data.steps.map((s:any)=>[s.title,n(s.seconds),s.allowancesIncluded===null?'تعیین‌نشده':s.allowancesIncluded?'لحاظ شده':'لحاظ نشده',s.bom.map((l:any)=>l.name+' '+n(l.quantity/1000)+' '+l.unit).join('، ')]))}{roles.engineering&&button('route',{materialId:r.data.materialId,steps:r.data.steps.map((s:any)=>({...s,bom:s.bom.map((l:any)=>({materialId:l.materialId,quantity:String(l.quantity/1000)}))}))},'نسخه جدید از این مسیر')}</IconDisclosure>)}</>}
 {tab==='policies'&&<><p className="notice">مقادیر خالی تعیین‌نشده‌اند. نسخه جدید فقط به تخصیص‌های بعدی اعمال می‌شود. زمان استراحت و آماده‌سازی برای بازه تخصیص است؛ هر فرد می‌تواند چند بازه بدون هم‌پوشانی داشته باشد.</p>{roles.manager&&button('policy',{effective:day,restMinutes:null,setupMinutes:null,efficiencyPercent:null,lowerPercent:null,upperPercent:null})}{table(['از تاریخ','استراحت / آماده‌سازی (دقیقه)','ضریب زمان مفید','کف / سقف هدف'],data.policies.map((p:any)=>[formatDate(p.data.effective),n(p.data.restMinutes)+' / '+n(p.data.setupMinutes),n(p.data.efficiencyPercent)+'٪',n(p.data.lowerPercent)+'٪ / '+n(p.data.upperPercent)+'٪']))}</>}
 {tab==='help'&&<ol>{data.help.map((h:string)=><li key={h} style={{marginBottom:16}}>{h}</li>)}</ol>}
 <Dialog open={!!draft} onOpenChange={v=>{if(!v&&!busy)setDraft(null)}}><DialogContent dir="rtl" style={{maxWidth:900,maxHeight:'90vh',overflowY:'auto'}}><DialogTitle>{names[draft?.mode]}</DialogTitle><DialogDescription>پس از بررسی مقادیر، ثبت را تأیید کنید.</DialogDescription>{draft&&<form onSubmit={save}>{error&&<p role="alert" className="notice error">{error}</p>}<div className="form-grid">
 {draft.mode==='policy'&&<><label className="field">تاریخ اجرا<SolarDate label="تاریخ" value={draft.effective} onChange={v=>field('effective',v)}/></label>{input('restMinutes','استراحت؛ خالی = تعیین‌نشده','number',false)}{input('setupMinutes','آماده‌سازی؛ خالی = تعیین‌نشده','number',false)}{input('efficiencyPercent','درصد زمان مفید (۱ تا ۱۰۰)','number',false)}{input('lowerPercent','کف بازه، درصد استاندارد (۰ تا ۱۰۰)','number',false)}{input('upperPercent','سقف بازه، درصد استاندارد (۱۰۰ تا ۲۰۰)','number',false)}</>}
 {draft.mode==='route'&&pick('materialId','قطعه واسط',data.materials.filter((m:any)=>m.unit==='عدد').map((m:any)=>[m.id,m.code+' · '+m.name]))}
 {draft.mode==='lot'&&<>{input('title','عنوان / شماره بچ ساخت')}{pick('routeId','نسخه مسیر ساخت',data.routes.map((r:any)=>[r.id,r.data.name+' · نسخه '+r.data.version]))}{input('count','تعداد آغاز ساخت','number')}</>}
 {draft.mode==='assign'&&<><label className="field">بچ<select required value={draft.lotId||''} onChange={e=>{const l=data.lots.find((l:any)=>l.id===e.target.value);setDraft({...draft,lotId:e.target.value,revision:l?.revision,stage:0});}}><option value="">انتخاب کنید</option>{data.lots.map((l:any)=><option key={l.id} value={l.id}>{l.data.title}</option>)}</select></label>{pick('stage','مرحله',(route?.steps||[]).map((s:any,i:number)=>[i,s.title+' · موجود: '+(draft.rework?draftLot.data.rework[i]:draftLot.data.ready[i])]))}{pick('memberId','کارگر',data.members.map((m:any)=>[m.id,m.name]))}<label className="field">روز<SolarDate label="تاریخ" value={draft.day} onChange={v=>field('day',v)}/></label>{input('start','شروع بازه','time')}{input('end','پایان بازه','time')}{input('count','تعداد تحویلی به فرد','number')}<label><input type="checkbox" checked={draft.rework} onChange={e=>field('rework',e.target.checked)}/> تخصیص از صف دوباره‌کاری</label></>}
 {draft.mode==='adjust'&&<>{input('leaveMinutes','مرخصی (دقیقه)','number')}{input('downtimeMinutes','توقف تأییدشده؛ کمبود مواد، خرابی و… (دقیقه)','number')}{input('setupMinutes','آماده‌سازی همین کار؛ خالی = سیاست','number',false)}{input('restMinutes','استراحت همین بازه؛ خالی = سیاست','number',false)}<label><input type="checkbox" checked={draft.overtimeApproved} onChange={e=>field('overtimeApproved',e.target.checked)}/> اضافه‌کاری این کار مجاز است</label></>}
 {['output','quality'].includes(draft.mode)&&<>{input('good','تعداد سالم','number')}{input('scrap','تعداد ضایعات','number')}{input('reworkCount','تعداد نیازمند دوباره‌کاری','number')}</>}
 {draft.mode==='output'&&<><label><input type="checkbox" checked={draft.overtime} onChange={e=>field('overtime',e.target.checked)}/> خروجی اضافه‌کاری</label>{draft.overtime&&input('overtimeReference','مرجع تأیید اضافه‌کاری')}{input('varianceReason','دلیل مغایرت مصرف / مواد دوباره‌کاری','text',false)}</>}
 {draft.mode==='close'&&<>{input('actualMinutes','زمان واقعی کار عادی (دقیقه)','number')}{input('overtimeMinutes','زمان واقعی اضافه‌کاری (دقیقه)','number')}{input('overtimeReference','مرجع اضافه‌کاری','text',!!draft.overtimeMinutes)}</>}
 {draft.mode==='quality'&&input('reference','شماره / مرجع کنترل کیفیت')}
 {draft.mode==='cost'&&<>{input('overhead','سربار تخصیصی (ریال؛ صفر را صریح وارد کنید)')}{input('basis','مبنای مصوب تخصیص سربار')}{input('reference','مرجع تأیید مالی')}</>}
 </div>
 {draft.mode==='route'&&<>{draft.steps.map((s:any,i:number)=>{const set=(k:string,v:any)=>field('steps',draft.steps.map((x:any,j:number)=>j===i?{...x,[k]:v}:x));return <fieldset key={i}><legend>مرحله {n(i+1)}</legend><div className="form-grid"><label className="field">نام عملیات<input required value={s.title} onChange={e=>set('title',e.target.value)}/></label><label className="field">ثانیه هر قطعه<input required type="number" min="1" value={s.seconds} onChange={e=>set('seconds',Number(e.target.value))}/></label><label className="field">استراحت در زمان استاندارد<select value={s.allowancesIncluded===null?'':String(s.allowancesIncluded)} onChange={e=>set('allowancesIncluded',e.target.value===''?null:e.target.value==='true')}><option value="">تعیین‌نشده</option><option value="true">لحاظ شده است</option><option value="false">جدا کسر شود</option></select></label></div>{s.bom.map((l:any,k:number)=><div className="form-grid" key={k}><label className="field">ماده مصرفی<select required value={l.materialId} onChange={e=>set('bom',s.bom.map((a:any,z:number)=>z===k?{...a,materialId:e.target.value}:a))}><option value="">انتخاب کنید</option>{data.materials.map((m:any)=><option key={m.id} value={m.id}>{m.code} · {m.name} ({m.unit})</option>)}</select></label><label className="field">مصرف هر قطعه<input required value={l.quantity} onChange={e=>set('bom',s.bom.map((a:any,z:number)=>z===k?{...a,quantity:latinDigits(e.target.value)}:a))}/></label><button type="button" className="btn" onClick={()=>set('bom',s.bom.filter((_:any,z:number)=>z!==k))}>حذف ماده</button></div>)}<div className="tools"><button type="button" className="btn" onClick={()=>set('bom',[...s.bom,{materialId:'',quantity:''}])}>افزودن ماده به مرحله</button><button type="button" className="btn" onClick={()=>field('steps',draft.steps.filter((_:any,j:number)=>j!==i))}>حذف مرحله</button></div></fieldset>})}<button className="btn" type="button" onClick={()=>field('steps',[...draft.steps,{title:'',seconds:60,allowancesIncluded:null,bom:[]}])}>افزودن مرحله بعد</button></>}
 {draft.mode==='output'&&<><h3>مصرف واقعی از خط</h3><p>مصرف پیشنهادی برای خروجی این ثبت: {draftJob?.data.step.bom.map((l:any)=>l.name+' '+n(draftJob.data.rework?0:l.quantity/1000*(draft.good+draft.scrap+draft.reworkCount))+' '+l.unit).join('، ')||'این مرحله ماده مصرفی ندارد.'}</p>{draft.allocations.map((a:any,i:number)=><div key={i} className="form-grid"><label className="field">بچ موجود در خط<select required value={a.batchId} onChange={e=>field('allocations',draft.allocations.map((x:any,j:number)=>j===i?{...x,batchId:e.target.value}:x))}><option value="">انتخاب کنید</option>{data.line.filter((b:any)=>draftJob?.data.step.bom.some((l:any)=>l.partCode===b.partCode&&l.unit===b.unit)).map((b:any)=><option key={b.item_id} value={b.item_id}>{b.code||b.item_id} · {b.part||b.partCode} · {n(b.quantity/1000)} {b.unit}</option>)}</select></label><label className="field">مصرف واقعی<input required value={a.quantity} onChange={e=>field('allocations',draft.allocations.map((x:any,j:number)=>j===i?{...x,quantity:latinDigits(e.target.value)}:x))}/></label><button type="button" className="btn" onClick={()=>field('allocations',draft.allocations.filter((_:any,j:number)=>j!==i))}>حذف</button></div>)}<button type="button" className="btn" onClick={()=>field('allocations',[...draft.allocations,{batchId:'',quantity:''}])}>افزودن مصرف از بچ</button></>}
 {draft.mode==='cost'&&draft.rates.map((r:any,i:number)=>{const j=data.jobs.find((j:any)=>j.id===r.jobId);return <fieldset key={r.jobId}><legend>{j?.data.memberName} · {j?.data.step.title} · {formatDate(j?.data.day)} · عادی {n(j?.data.actualMinutes)} / اضافه {n(j?.data.overtimeMinutes)} دقیقه</legend><div className="form-grid">{[['hourly','نرخ ساعت عادی (ریال)'],['overtimeHourly','نرخ ساعت اضافه‌کاری (ریال)']].map(([k,label])=><label key={k} className="field">{label}<input required value={r[k]} onChange={e=>field('rates',draft.rates.map((v:any,z:number)=>z===i?{...v,[k]:latinDigits(e.target.value)}:v))}/></label>)}</div></fieldset>})}
 <label className="field">{draft.mode==='reason'?'توضیح کارگر':draft.mode==='review'?'نتیجه بررسی و اقدام بعدی':'توضیح و مستند ثبت'}<textarea required value={draft.notes} onChange={e=>field('notes',e.target.value)}/></label><p className="subtle">ثبت عملکرد، حقوق یا مزایای فرد را تغییر نمی‌دهد.</p><button className="btn primary" disabled={busy}>{busy?'در حال ثبت…':'تأیید و ثبت'}</button></form>}</DialogContent></Dialog>
 </section></ProgramWorkspace>;
}
