'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {SolarDate} from './solar-date';
import {formatDate,formatDateTime,localDay} from '@/lib/persian-date';
const actions:Record<string,string>={save:'ثبت / ویرایش سرنخ',stage:'تغییر مرحله',activity:'ثبت تماس و پیگیری',assign:'انتقال مسئولیت',lose:'ثبت فروش ازدست‌رفته',reopen:'بازگشایی',link_order:'اتصال سفارش موجود',convert:'تبدیل به سفارش'};
const activities:Record<string,string>={call:'تماس تلفنی',meeting:'جلسه',email:'ایمیل',message:'پیام',visit:'مراجعه'};
const amount=(s:string)=>s?BigInt(s).toLocaleString('fa-IR')+' ریال':'نامشخص';
const digits=(s:string)=>s.replace(/[۰-۹]/g,c=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(c))).replace(/[٠-٩]/g,c=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(c))).replace(/[,٬]/g,'');
export function SalesLeadsPanel({targetId='',refreshKey,onConvert}:{targetId?:string;refreshKey?:unknown;onConvert:(lead:any)=>void}){
 const [data,setData]=useState<any>(null),[selected,setSelected]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[mode,setMode]=useState(''),[form,setForm]=useState<any>({}),[op,setOp]=useState(''),[query,setQuery]=useState(''),[queue,setQueue]=useState('all'),[stage,setStage]=useState('all'),[owner,setOwner]=useState('all'),[segment,setSegment]=useState('all'),[from,setFrom]=useState(''),[to,setTo]=useState('');
 async function load(){const q=new URLSearchParams({from,to}),r=await fetch('/api/sales/leads?'+q,{cache:'no-store'}),j:any=await r.json();if(!r.ok)throw Error(j.error);setData(j);}
 useEffect(()=>{void load().catch(e=>setError(e.message))},[refreshKey]);
 useEffect(()=>{if(targetId.startsWith('lead:')){setSelected(targetId.slice(5));setQueue('all');setQuery('');}},[targetId]);
 const record=data?.records.find((r:any)=>r.id===selected),d=record?.data,isOpen=d&&!['lost','converted'].includes(d.stage),member=(id:string)=>data?.members.find((m:any)=>m.id===id)?.name||'مسئول غیرفعال / نامشخص',product=(id:string)=>data?.products.find((p:any)=>p.id===id)?.name||'محصول پیشین';
 const change=(key:string,value:any)=>setForm((f:any)=>({...f,[key]:value}));
 function start(action:string,r=record){setError('');setMessage('');setMode(action);setOp(crypto.randomUUID());setForm(action==='save'?{title:'',contactName:'',company:'',phone:'',city:'',source:'',segment:'home',ownerId:data.me,items:[],agentId:'',interest:'',estimatedAmount:'',nextAction:'',nextDue:localDay(),...(r?.data||{}),notes:''}:{ownerId:r?.data.ownerId,stage:r?.data.stage,nextAction:r?.data.nextAction||'',nextDue:r?.data.nextDue||localDay(),day:localDay(),notes:''});}
 async function submit(){setBusy(true);setError('');try{const body={...form,id:op,mode,confirmed:true,leadId:record?.id,revision:record?.revision||0};delete body.history;if(body.agentId==='none')body.agentId='';const r=await fetch('/api/sales/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j:any=await r.json();if(!r.ok)throw Error(j.error);setSelected(j.id);setMode('');await load();setMessage(j.followupPending?'پرونده ثبت شد؛ همگام‌سازی کارتابل در نوبت بعد انجام می‌شود.':'ثبت شد.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const input=(key:string,label:string,required=true,numeric=false)=><label className="field" key={key}>{label}<input required={required} value={form[key]??''} maxLength={key==='interest'?2000:500} onChange={e=>change(key,numeric?digits(e.target.value):e.target.value)}/></label>;
 const pick=(label:string,value:string,options:Record<string,string>,set:(v:string)=>void)=><label className="field">{label}<Select dir="rtl" value={value||''} onValueChange={set}><SelectTrigger aria-label={label}><SelectValue placeholder="انتخاب کنید"/></SelectTrigger><SelectContent>{Object.entries(options).map(([id,name])=><SelectItem key={id} value={id}>{name}</SelectItem>)}</SelectContent></Select></label>;
 const date=(key:string,label:string,required=true)=><SolarDate label={label} value={form[key]||''} required={required} onChange={v=>change(key,v)}/>;
 if(!data)return <div className="inside"><p role={error?'alert':'status'}>{error||'در حال دریافت سرنخ‌ها…'}</p><button className="btn" onClick={()=>void load().catch(e=>setError(e.message))}>تازه‌سازی</button></div>;
 const dash=data.dashboard,filtered=data.records.filter((r:any)=>{const x=r.data,open=!['lost','converted'].includes(x.stage);return (stage==='all'||x.stage===stage)&&(owner==='all'||x.ownerId===owner)&&(segment==='all'||x.segment===segment)&&(queue==='all'||queue==='today'&&open&&x.nextDue<=data.today||queue==='late'&&open&&x.nextDue<data.today||queue==='stalled'&&open&&Date.parse(data.today)-Date.parse(x.lastContact?.day||x.createdDay)>=7*86400000)&&(!query||[x.title,x.contactName,x.company,x.phone,x.city].join(' ').includes(query));});
 const summarize=(title:string,buckets:any,labels:(key:string)=>string)=><div className="flow-card"><h4>{title}</h4>{Object.entries(buckets).map(([key,v]:any)=><p key={key}>{labels(key)}: {v.total} پرونده · {v.open} باز · {v.converted} تبدیل به سفارش</p>)}</div>;
 return <section aria-label="سرنخ‌ها و فرصت‌های فروش" dir="rtl"><div className="tools"><h3>سرنخ‌ها و فرصت‌های فروش</h3><button className="btn primary" disabled={busy} onClick={()=>{setSelected('');start('save',null)}}>سرنخ جدید</button><button className="btn" disabled={busy} onClick={()=>void load().catch(e=>setError(e.message))}>تازه‌سازی</button></div>
 <p className="footnote">{data.help}</p>{error&&<p className="notice error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 <div className="formgrid"><SolarDate label="ایجاد از تاریخ" required={false} value={from} onChange={setFrom}/><SolarDate label="ایجاد تا تاریخ" required={false} value={to} onChange={setTo}/><button className="btn" onClick={()=>void load().catch(e=>setError(e.message))}>اعمال بازه گزارش</button></div>
 <div className="flow-card"><strong>گزارش پرونده‌های ایجادشده در بازه انتخابی</strong><p>کل: {dash.total} · باز: {dash.open} · تبدیل به سفارش: {dash.converted} · نرخ تبدیل: {dash.conversionRate===null?'—':dash.conversionRate+'٪'}</p><p>پیگیری معوق: {dash.overdue} · بدون تماس در هفت روز اخیر: {dash.stalled} · مسئول غیرفعال: {dash.inactiveOwners}</p><p>مبلغ تخمینی فرصت‌های باز: {amount(dash.estimatedOpenRial)} · {dash.unknownEstimates} پرونده بدون برآورد</p></div>
 <details><summary>گزارش تفکیکی تیم، کانال و محصول</summary><div className="formgrid">{summarize('مرحله',dash.byStage,k=>data.stages[k])}{data.manager&&summarize('کارشناس',dash.byOwner,member)}{summarize('منبع آشنایی',dash.bySource,k=>data.sources[k])}{summarize('مسیر فروش',dash.bySegment,k=>k==='home'?'خانگی':'بیمارستانی')}<div className="flow-card"><h4>محصول</h4>{dash.byProduct.map((p:any)=><p key={p.id}>{p.name}: {p.total} پرونده · {p.converted} تبدیل</p>)}</div><div className="flow-card"><h4>دلایل ازدست‌رفتن فروش</h4>{Object.entries(dash.lossReasons).map(([k,n]:any)=><p key={k}>{data.losses[k]}: {n}</p>)}</div></div></details>
 <div className="formgrid"><label className="field">جست‌وجوی پرونده<input value={query} onChange={e=>setQuery(e.target.value)}/></label>{pick('کارتابل',queue,{all:'همه',today:'پیگیری امروز و عقب‌افتاده',late:'فقط معوق',stalled:'بدون تماس در هفت روز'},setQueue)}{pick('مرحله',stage,{all:'همه',...data.stages},setStage)}{pick('مسیر فروش',segment,{all:'همه',home:'خانگی',hospital:'بیمارستانی'},setSegment)}{data.manager&&pick('مسئول',owner,{all:'همه',...Object.fromEntries(data.members.map((m:any)=>[m.id,m.name]))},setOwner)}</div>
 <div style={{overflowX:'auto'}}><table><thead><tr><th>سرنخ / مشتری</th><th>مرحله</th><th>مسئول</th><th>اقدام بعدی</th><th>پرونده</th></tr></thead><tbody>{filtered.map((r:any)=><tr key={r.id}><td>{r.data.title}<br/>{r.data.contactName} · {r.data.company}</td><td>{data.stages[r.data.stage]}</td><td>{member(r.data.ownerId)}</td><td>{!['lost','converted'].includes(r.data.stage)?<>{r.data.nextAction}<br/>{formatDate(r.data.nextDue)}{r.data.nextDue<data.today?' — معوق':''}</>:'بسته'}</td><td><button className="btn" onClick={()=>setSelected(r.id)}>باز کردن</button></td></tr>)}</tbody></table>{!filtered.length&&<p className="empty">سرنخی با این فیلترها وجود ندارد.</p>}</div>
 {d&&<article className="flow-card"><h3>{d.title} — {data.stages[d.stage]}</h3><p>{d.contactName} · {d.company||'بدون نام شرکت'} · {d.city} · <a href={'tel:'+d.phone}>{d.phone}</a> · {d.email}</p><p>مسئول: {member(d.ownerId)} · منبع: {data.sources[d.source]} / {d.sourceDetail}</p><p>نیاز مشتری: {d.interest}</p><p>محصولات: {d.items.map((l:any)=>product(l.productId)+' × '+l.quantity).join('، ')||'هنوز تعیین نشده'}</p><p>برآورد: {amount(d.estimatedAmount)} · زمان احتمالی خرید: {d.expectedDay?formatDate(d.expectedDay):'نامشخص'} · رقیب: {d.competitor||'نامشخص'}</p>{d.segment==='hospital'&&<p>تصمیم‌گیر: {d.decisionMaker||'نامشخص'} · موعد مناقصه: {d.tenderDeadline?formatDate(d.tenderDeadline):'نامشخص'}</p>}<p>طرف حساب سفارش: {data.agents.find((a:any)=>a.id===d.agentId)?.name||'هنوز متصل نشده؛ برای تبدیل، پرونده را ویرایش و طرف حساب فعال را انتخاب کنید.'}</p>{d.orderId&&<p>سفارش مرتبط: {data.orders.find((o:any)=>o.id===d.orderId)?.code||'ثبت‌شده'} · وضعیت: {({submitted:'بررسی فروش',sales_approved:'بررسی مالی',approved:'فاکتور شده',rejected:'رد شده',cancelled:'لغو شده'} as any)[data.orders.find((o:any)=>o.id===d.orderId)?.state]||'—'}؛ سابقه تبدیل با لغو سفارش حذف نمی‌شود.</p>}{d.lossReason&&<p>دلیل عدم فروش: {data.losses[d.lossReason]} — {d.lossDetail}</p>}
 <div className="tools" style={{flexWrap:'wrap'}}>{isOpen&&['save','activity','stage','lose',...(data.manager?['assign']:[]),'link_order'].map(a=><button className="btn" key={a} disabled={busy} onClick={()=>start(a)}>{actions[a]}</button>)}{isOpen&&<button className="btn primary" disabled={busy||!d.agentId||!d.items.length} onClick={()=>onConvert(record)}>ساخت سفارش از این فرصت</button>}{data.manager&&d.stage==='lost'&&<button className="btn" onClick={()=>start('reopen')}>بازگشایی</button>}</div>
 <h4>سابقه تماس‌ها و تصمیم‌ها</h4>{[...(d.history||[])].reverse().map((h:any,i:number)=><p key={i}>{formatDateTime(h.at)} · {h.name} · {activities[h.activityType]||actions[h.mode]||h.mode}{h.day?' ('+formatDate(h.day)+')':''}: {h.notes}</p>)}</article>}
 <Dialog open={!!mode} onOpenChange={v=>{if(!v&&!busy)setMode('')}}><DialogContent dir="rtl" style={{maxWidth:820,maxHeight:'90vh',overflowY:'auto'}}><DialogHeader><DialogTitle>{actions[mode]}</DialogTitle><DialogDescription>{record?d.title:'پرونده جدید'}؛ نتیجه و اقدام بعدی را بر اساس گفت‌وگوی واقعی ثبت کنید.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();void submit()}}><div className="formgrid">
 {mode==='save'&&<>{input('title','عنوان فرصت')}{input('contactName','نام مخاطب')}{input('company','شرکت / مرکز',false)}{input('phone','شماره تماس کامل')}{input('email','ایمیل',false)}{input('city','شهر')}{pick('مسیر فروش',form.segment,{home:'خانگی',hospital:'بیمارستانی'},v=>change('segment',v))}{pick('منبع آشنایی',form.source,data.sources,v=>change('source',v))}{input('sourceDetail','جزئیات منبع / معرف',false)}{input('interest','نیاز مشتری')}{input('estimatedAmount','مبلغ تخمینی به ریال؛ خالی یعنی نامشخص',false,true)}{date('expectedDay','زمان احتمالی خرید',false)}{input('competitor','رقیب / گزینه جایگزین',false)}{form.segment==='hospital'&&<>{input('decisionMaker','تصمیم‌گیران مرکز',false)}{date('tenderDeadline','آخرین مهلت مناقصه',false)}</>}{pick('طرف حساب در فروش',form.agentId||'none',{none:'هنوز انتخاب نشده',...Object.fromEntries(data.agents.filter((a:any)=>a.active).map((a:any)=>[a.id,a.name]))},v=>change('agentId',v))}
 <fieldset className="field wide"><legend>محصولات موردنیاز</legend>{(form.items||[]).map((l:any,i:number)=><div className="tools" key={i}>{pick('محصول '+(i+1),l.productId,Object.fromEntries(data.products.filter((p:any)=>p.active).map((p:any)=>[p.id,p.name])),v=>change('items',form.items.map((x:any,j:number)=>j===i?{...x,productId:v}:x)))}<label className="field">تعداد<input type="number" min={1} max={10000} required value={l.quantity} onChange={e=>change('items',form.items.map((x:any,j:number)=>j===i?{...x,quantity:Number(e.target.value)}:x))}/></label><button type="button" className="btn" onClick={()=>change('items',form.items.filter((_:any,j:number)=>j!==i))}>حذف ردیف</button></div>)}<button type="button" className="btn" disabled={form.items?.length>=30} onClick={()=>change('items',[...(form.items||[]),{productId:'',quantity:1}])}>افزودن محصول</button></fieldset></>}
 {['save','assign','reopen'].includes(mode)&&(data.manager?pick('کارشناس مسئول',form.ownerId,Object.fromEntries(data.members.map((m:any)=>[m.id,m.name])),v=>change('ownerId',v)):<p>مسئول: {member(data.me)}</p>)}
 {mode==='stage'&&pick('مرحله بعدی',form.stage,Object.fromEntries(Object.entries(data.stages).filter(([k])=>!['lost','converted'].includes(k))) as Record<string,string>,v=>change('stage',v))}
 {mode==='activity'&&<>{pick('نوع ارتباط',form.activityType,activities,v=>change('activityType',v))}{date('day','تاریخ ارتباط واقعی')}</>}
 {mode==='lose'&&pick('دلیل ازدست‌رفتن',form.lossReason,data.losses,v=>change('lossReason',v))}
 {mode==='link_order'&&pick('سفارش مرتبط',form.orderId,Object.fromEntries(data.orders.filter((o:any)=>o.agentId===d.agentId&&(!o.leadId||o.leadId===selected)&&['submitted','sales_approved','approved'].includes(o.state)).map((o:any)=>[o.id,o.code+' — '+amount(o.amount)])),v=>change('orderId',v))}
 {!['lose','link_order'].includes(mode)&&<>{input('nextAction','اقدام بعدی')}{date('nextDue','موعد پیگیری بعدی')}</>}
 </div><label className="field">{mode==='activity'?'نتیجه تماس / جلسه':'شرح و دلیل اقدام'}<textarea required maxLength={4000} value={form.notes||''} onChange={e=>change('notes',e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<div className="tools"><button type="button" className="btn" disabled={busy} onClick={()=>setMode('')}>انصراف</button><button className="btn primary" disabled={busy}>{busy?'در حال ثبت…':'تأیید و ثبت'}</button></div></form></DialogContent></Dialog>
 </section>;
}
