'use client';
import {SalesMonitorPanel} from './sales-monitor-panel';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {SolarDate} from './solar-date';
import {formatDate,localDay} from '@/lib/persian-date';
import {salesActions,salesStates,salesMilestones,salesRequestChannels,salesProxyModes,salesPipelineStages,rial,total} from '@/lib/sales-contract';
const money=(v:any)=>BigInt(v||'0').toLocaleString('fa-IR')+' ریال';
const n=(v:number)=>v.toLocaleString('fa-IR');
const date=(v:string)=>v?formatDate(v):'تعیین نشده';
const digits=(s:string)=>s.replace(/[۰-۹]/g,c=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(c))).replace(/[٠-٩]/g,c=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(c))).replace(/[,٬]/g,'');
const plusDay=(day:string,days:number)=>new Date(Date.parse(day+'T12:00:00Z')+days*86400000).toISOString().slice(0,10);
export function SalesPanel({demo,onNavigate,targetId=''}:{targetId?:string;demo:boolean;onNavigate:(s:string)=>void}){
 const [data,setData]=useState<any>(null),[selected,setSelected]=useState(''),[view,setView]=useState('home'),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[draft,setDraft]=useState<any>(null),[quote,setQuote]=useState<any>(null),[file,setFile]=useState<File|null>(null),[accounts,setAccounts]=useState<any[]>([]),[search,setSearch]=useState(''),[province,setProvince]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[stage,setStage]=useState('');
 async function load(){if(demo)return;const r=await fetch('/api/sales',{cache:'no-store'}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setData(d);if(d.roles.manager){const a=await fetch('/api/sales/accounts',{cache:'no-store'});if(a.ok)setAccounts(((await a.json()) as any).accounts);}if(d.roles.agent&&d.agents[0])setSelected(d.agents[0].id);}
 useEffect(()=>{if(!demo)void load().catch(e=>setError(e.message))},[demo]);
 useEffect(()=>{if(targetId){setSelected(targetId);setView('orders')}},[targetId]);
 const change=(k:string,v:any)=>{setDraft((d:any)=>({...d,[k]:v,...(k==='agentId'?{fileId:'',invoiceId:'',deviceIds:[],...(d.requestSource?{requestSource:{...d.requestSource,contactName:'',reference:''}}:{})}:{}),...(k==='invoiceId'?{deviceIds:[]}:{}),...(k==='result'?{receiptFileId:'',fileRequestId:crypto.randomUUID()}:{}),}));if(draft?.mode==='order')setQuote(null);};
 const begin=(mode:string,extra:any={})=>{setError('');setQuote(null);setFile(null);setDraft({mode,id:crypto.randomUUID(),confirmed:true,agentId:selected||data?.agents[0]?.id||'',active:true,approved:true,day:localDay(),basis:'net',method:'bank',creditLimit:'0',termDays:0,ownerId:'',financeId:'',items:[{productId:'',quantity:1}],tiers:[{threshold:'',discountBps:100}],productIds:[],fileRequestId:crypto.randomUUID(),...(!data?.roles.agent&&[...salesProxyModes,'receipt'].includes(mode)?{requestSource:{channel:'phone',contactName:'',day:localDay(),reference:''}}:{}),...extra});};
 const agents=(data?.agents||[]).filter((a:any)=>(!selected||a.id===selected)&&(!province||a.data.province===province)),agentIds=new Set(agents.map((a:any)=>a.id));
 const acs=(data?.accounts||[]).filter((a:any)=>agentIds.has(a.agentId));const records=(kind:string)=>(data?.[kind]||[]).filter((r:any)=>agentIds.has(r.data.agentId));const agentName=(id:string)=>data?.agents.find((a:any)=>a.id===id)?.data.name||'—';const productName=(id:string)=>data?.products?.find((p:any)=>p.id===id)?.name||id;
 const action=(mode:string,label:string,extra:any={},disabled=false)=><button type="button" className="btn" disabled={disabled} onClick={()=>begin(mode,extra)}>{label}</button>;
 async function send(path:string,body:any){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json() as any;if(!r.ok)throw Error(d.error||'ثبت انجام نشد.');return d;}
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{
  let {fileRequestId,...b}=draft;
  if(b.mode==='order'&&!quote){setQuote(await send('/api/sales/quote',{agentId:b.agentId,items:b.items}));setBusy(false);return;}
  if(b.mode==='order')b.quoteHash=quote.quoteHash;
  if(b.mode==='receipt'&&!data.roles.agent&&!b.receiptFileId){if(!file)throw Error('مستند دریافت این محموله را انتخاب کنید.');const fd=new FormData();fd.set('file',file);const q=new URLSearchParams({mission:b.missionId,purpose:b.result==='complete'?'receipt':'condition',requestId:fileRequestId,revision:String(b.revision)}),r=await fetch('/api/transport/files?'+q,{method:'POST',body:fd}),d=await r.json() as any;if(!r.ok)throw Error(d.error);b.receiptFileId=d.id;b.revision=d.revision;setDraft((v:any)=>({...v,receiptFileId:d.id,revision:d.revision}));}
  if(b.mode!=='receipt'&&file&&!b.fileId){const fd=new FormData();fd.set('metadata',JSON.stringify({id:fileRequestId,agentId:b.agentId,title:b.title||'رسید پرداخت',confirmed:true}));fd.set('file',file);const r=await fetch('/api/sales/files',{method:'POST',body:fd}),d=await r.json() as any;if(!r.ok)throw Error(d.error);b.fileId=d.id;setDraft((v:any)=>({...v,fileId:d.id}));}
  let result:any;
  if(b.mode==='file'){if(!b.fileId)throw Error('فایل انتخاب کنید.');result={saved:true};}
  else if(b.mode==='account'){result=await send('/api/sales/accounts',{id:b.id,agentId:b.agentId,revision:b.revision,name:b.name,username:b.username,password:b.password,confirmed:true});}
  else if(b.mode==='reserve'){result=await send('/api/fulfillment',{id:b.id,mode:'reserve',salesOrderId:b.orderId,productId:b.productId,count:b.count,notes:b.notes||''});}
  else if(b.mode==='receipt'){result=await send('/api/transport',{id:b.id,mode:'receipt',missionId:b.missionId,revision:b.revision,packages:b.packages,day:b.day,result:b.result,notes:b.notes,requestSource:b.requestSource,receiptFileId:b.receiptFileId,confirmed:true});}
  else result=await send('/api/sales',b);
  setDraft(null);setQuote(null);setFile(null);setMessage(result.followupPending?'ثبت شد؛ همگام‌سازی کارتابل در اجرای بعدی زمان‌بند انجام می‌شود.':'ثبت شد و سابقه عملیات محفوظ است.');await load();
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const field=(key:string,label:string,required=true,numeric=false)=><label className="field" key={key}>{label}<input required={required} value={draft?.[key]??''} inputMode={numeric?'numeric':undefined} onChange={e=>change(key,numeric?digits(e.target.value):e.target.value)}/></label>;
 const number=(key:string,label:string,min=0,max=10000)=><label className="field">{label}<input type="number" required min={min} max={max} value={draft?.[key]??0} onChange={e=>change(key,Number(e.target.value))}/></label>;
 const pick=(key:string,label:string,items:Record<string,string>,required=true)=><label className="field">{label}<select required={required} value={draft?.[key]??''} onChange={e=>change(key,e.target.value)}><option value="">انتخاب کنید</option>{Object.entries(items).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>;
 const check=(key:string,label:string)=><label className="flow-check"><input type="checkbox" checked={!!draft?.[key]} onChange={e=>change(key,e.target.checked)}/>{label}</label>;
 const solar=(key:string,label:string)=><SolarDate label={label} value={draft?.[key]||''} onChange={v=>change(key,v)}/>;
 const note=()=>field('notes','توضیح و دلیل تصمیم');
 const submission=(v:any)=>v?<span> · ثبت‌کننده: {v.actorName||v.actor} · {v.onBehalf?'از طرف نماینده / '+(salesRequestChannels[v.channel]||v.channel)+' / '+v.contactName+' / '+date(v.day)+' / '+v.reference:'ثبت مستقیم نماینده'}</span>:null;
 const history=(r:any)=><details><summary>سابقه اقدامات</summary>{(r.data.history||[]).map((h:any,i:number)=><p key={i}>{date(h.at)} · {salesActions[h.mode]||h.mode} · {h.notes||'ثبت در سامانه'}{h.submission?submission(h.submission):<span> · {h.actorName||h.actor||'ثبت‌کننده قبلی'}</span>}</p>)}</details>;
 const setRow=(key:string,index:number,field:string,value:any)=>change(key,draft[key].map((r:any,i:number)=>i===index?{...r,[field]:value}:r));
 const files=(agentId:string)=>(data?.files||[]).filter((f:any)=>f.data.agentId===agentId);
 const finance=!!data?.roles.finance,staff=!!data?.roles.staff,rep=!!data?.roles.agent;
 if(demo)return <section className="panel"><div className="inside"><h2>فروش و نمایندگان</h2><p>برای تعریف نماینده و ثبت سفارش، به «اطلاعات شرکت» بروید. این بخش داده آزمایشی ساختگی ایجاد نمی‌کند.</p></div></section>;
 if(!data)return <section className="panel"><div className="inside"><p role={error?'alert':'status'}>{error||'در حال دریافت پرتال فروش…'}</p><button className="btn" onClick={()=>void load().catch(e=>setError(e.message))}>تازه‌سازی</button></div></section>;
 const reportsInvoices=acs.flatMap((a:any)=>a.invoices).filter((i:any)=>!i.data.openingId&&(!from||i.data.day>=from)&&(!to||i.data.day<=to));const reportsReturns=acs.flatMap((a:any)=>a.returns).filter((r:any)=>r.data.state==='credited'&&(!from||r.data.reviewedAt.slice(0,10)>=from)&&(!to||r.data.reviewedAt.slice(0,10)<=to));const reportsPayments=acs.flatMap((a:any)=>a.payments).filter((p:any)=>!p.data.openingId).flatMap((p:any)=>(p.data.financialEvents||[]).map((e:any)=>({...e,agentId:p.data.agentId}))).filter((e:any)=>(!from||e.day>=from)&&(!to||e.day<=to));
 const pipeline=(data.pipeline||[]).filter((p:any)=>agentIds.has(p.agentId)),tasks=(data.tasks||[]).filter((t:any)=>agentIds.has(t.agentId));
 const tabs=data.warehouseOnly?{returns:'دریافت برگشتی'}:{...(!rep&&(staff||finance)?{monitor:'گزارش مدیر و هشدارها'}:{}),home:rep?'نمای من':'گزارش فروش',orders:'سفارش‌ها',account:'حساب و پرداخت',targets:'تارگت و تخفیف',returns:'برگشت کالا',profiles:'پرونده نمایندگان',...(!rep?{setup:'قیمت و افتتاحیه'}:{})};
 return <section className="panel sales-portal" dir="rtl"><div className="panelhead"><h2>{rep?'پرتال نماینده فروش':'فروش و نمایندگان'}</h2><div className="tools">{!data.warehouseOnly&&(rep||staff)&&action('order','سفارش جدید',{},!data.agents.length)}{!data.warehouseOnly&&(rep||staff||finance)&&action('payment','ثبت پرداخت',{},!data.agents.length)}<button className="btn" onClick={()=>void load().catch(e=>setError(e.message))}>تازه‌سازی</button></div></div><div className="inside">
 {!rep&&<div className="formgrid"><label className="field">نماینده<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">همه نمایندگان</option>{data.agents.map((a:any)=><option value={a.id} key={a.id}>{a.data.name}</option>)}</select></label>{!data.warehouseOnly&&<label className="field">استان<select value={province} onChange={e=>setProvince(e.target.value)}><option value="">همه استان‌ها</option>{Array.from(new Set<string>(data.agents.map((a:any)=>a.data.province))).map(p=><option key={p}>{p}</option>)}</select></label>}</div>}
 {!rep&&!data.warehouseOnly&&selected&&<p className="notice">حساب شما: <b>{data.meName}</b> · پرونده انتخاب‌شده: <b>{agentName(selected)}</b>. درخواست نماینده را از همین حساب ثبت کنید؛ ثبت‌کننده واقعی در سابقه می‌ماند.</p>}
 <nav className="tools sales-tabs" aria-label="بخش‌های فروش">{Object.entries(tabs).map(([key,label])=><button className={'btn '+((data.warehouseOnly?'returns':view)===key?'primary':'')} key={key} onClick={()=>setView(key)}>{label}</button>)}</nav>
 {error&&!draft&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}
 {!data.warehouseOnly&&!rep&&(staff||finance)&&view==='monitor'&&<SalesMonitorPanel onTasks={()=>onNavigate('tasks')} onOpenAgent={(id,section)=>{setSelected(id);setProvince('');setStage('');setSearch('');setView(section)}}/>}
 {!data.warehouseOnly&&view==='home'&&<><div className="stats">{[{t:'مانده بدهی فاکتورها',v:total(acs,a=>a.debt)},{t:'اعتبار تخصیص‌نیافته',v:total(acs,a=>a.credit)},{t:'بدهی سررسیدگذشته',v:total(acs,a=>a.overdue)},{t:'پرداخت در انتظار تأیید',v:total(acs,a=>a.pending)}].map(s=><div className="stat" key={s.t}><div><p>{s.t}</p><strong style={{fontSize:'1.2rem'}}>{money(s.v)}</strong></div></div>)}</div><p className="notice">مانده خالص فعلی: <b>{money(total(acs,a=>a.balance))}</b> · مبلغ منفی یعنی بستانکاری. اعتبار آزاد تا تخصیص مالی، سررسید یک فاکتور مشخص را تسویه نمی‌کند.</p>
 <h3>وضعیت جاری سفارش‌ها و پیگیری‌ها</h3><p>تحویل از محموله‌های واقعی محاسبه می‌شود. این گزارش و کارهای باز، به بازه گردش مالی محدود نیستند.</p><div className="tools">{Object.entries(salesPipelineStages).map(([key,label])=>{const rows=pipeline.filter((p:any)=>p.stage===key);return rows.length?<button className="btn" key={key} onClick={()=>{setStage(key);setSearch('');setView('orders')}}>{label}: {n(rows.length)}</button>:null})}<button className="btn" onClick={()=>{setStage('late');setSearch('');setView('orders')}}>تحویل عقب‌افتاده: {n(pipeline.filter((p:any)=>p.late).length)}</button></div>
 <h3>{data.roles.manager?'کارهای باز تیم':'پیگیری‌های شما'}</h3><div className="tools"><span>باز: {n(tasks.length)} · عقب‌افتاده: {n(tasks.filter((t:any)=>t.late).length)}</span><button className="btn" onClick={()=>onNavigate('tasks')}>باز کردن کارتابل</button></div>
 {data.roles.manager&&<div className="sales-table"><table><caption>بار کاری و تأخیر مسئولان</caption><thead><tr><th>مسئول</th><th>کار باز</th><th>عقب‌افتاده</th></tr></thead><tbody>{Array.from(new Set<string>(tasks.map((t:any)=>t.assignee))).map(id=>{const own=tasks.filter((t:any)=>t.assignee===id);return <tr key={id}><td>{own[0].assigneeName}</td><td>{n(own.length)}</td><td>{n(own.filter((t:any)=>t.late).length)}</td></tr>})}</tbody></table></div>}
 <div className="sales-table"><table><caption>پیگیری‌های باز به ترتیب مهلت</caption><thead><tr><th>کار / نماینده</th><th>مسئول</th><th>مهلت</th><th>وضعیت</th></tr></thead><tbody>{[...tasks].sort((a:any,b:any)=>a.due.localeCompare(b.due)).map((t:any)=><tr key={t.id}><td><button className="link" onClick={()=>{setSelected(t.agentId);setProvince('');setView(t.title.includes('سررسید')||t.title.includes('پرداخت')||t.title.includes('چک')?'account':t.title.includes('تارگت')?'targets':t.title.includes('برگشت')?'returns':t.title.includes('افتتاحیه')?'setup':'orders');setStage('');setSearch('')}}>{t.title}</button></td><td>{t.assigneeName}</td><td>{date(t.due)}</td><td>{t.late?'از مهلت گذشته':t.state==='blocked'?'دارای مانع':'در پیگیری'}</td></tr>)}</tbody></table></div>{!tasks.length&&<p>پیگیری بازی در دسترسی و فیلتر فعلی نیست.</p>}
 {!rep&&<><div className="formgrid"><SolarDate label="گزارش گردش از تاریخ" value={from} onChange={setFrom}/><SolarDate label="تا تاریخ" value={to} onChange={setTo}/></div><p>بازه تاریخ فقط گردش فروش و وصول زیر را فیلتر می‌کند؛ مانده‌ها وضعیت جاری‌اند.</p></>}
 <div className="stats">{[{t:'فاکتورهای صادرشده',v:total(reportsInvoices,i=>i.data.amount)},{t:'خالص وصول پس از برگشت پرداخت',v:total(reportsPayments,p=>p.delta)},{t:'تخفیف ثبت‌شده',v:total(reportsInvoices,i=>i.data.discount)},{t:'برگشت تأییدشده',v:total(reportsReturns,r=>r.data.amount)}].map(s=><div className="stat" key={s.t}><div><p>{s.t}</p><b>{money(s.v)}</b></div></div>)}</div>
 {!rep&&<div className="sales-table"><table><caption>گزارش نمایندگان و سنی مطالبات</caption><thead><tr><th>نماینده / استان</th><th>فروش بازه</th><th>وصول بازه</th><th>مانده فعلی</th><th>معوق</th></tr></thead><tbody>{agents.map((a:any)=>{const ac=acs.find((v:any)=>v.agentId===a.id);return <tr key={a.id}><td><button className="link" onClick={()=>{setSelected(a.id);setView('account')}}>{a.data.name}</button><small>{a.data.province}</small></td><td>{money(total(reportsInvoices.filter((i:any)=>i.data.agentId===a.id),i=>i.data.amount))}</td><td>{money(total(reportsPayments.filter((p:any)=>p.agentId===a.id),p=>p.delta))}</td><td>{money(ac?.balance)}</td><td>{money(ac?.overdue)}</td></tr>})}</tbody></table></div>}
 {acs.map((a:any)=><div className="flow-card" key={a.agentId}><h3>سنی مطالبات · {agentName(a.agentId)}</h3><div className="tools">{a.aging.map((b:any)=><span className="notice" key={b.label}>{b.label}: {money(b.amount)}</span>)}</div></div>)}
 <div className="sales-table"><table><caption>فروش بر حسب محصول در بازه انتخابی</caption><thead><tr><th>محصول</th><th>تعداد فاکتورشده</th><th>مبلغ فاکتور</th><th>برگشت</th></tr></thead><tbody>{data.products.map((p:any)=>{const ls=reportsInvoices.flatMap((i:any)=>i.data.lines).filter((l:any)=>l.productId===p.id),rs=reportsReturns.flatMap((r:any)=>r.data.lines).filter((l:any)=>l.productId===p.id);return ls.length||rs.length?<tr key={p.id}><td>{p.name}</td><td>{n(ls.reduce((v:number,l:any)=>v+l.quantity,0))}</td><td>{money(total(ls,l=>l.net))}</td><td>{money(total(rs,l=>l.net))}</td></tr>:null})}</tbody></table></div>
 {!data.agents.length&&<p className="empty">برای شروع، مدیر فروش پرونده نماینده و قیمت محصولات را تعریف کند. سپس مالی سقف اعتبار و مهلت خرید را تعیین کند.</p>}
 </>}
 {!data.warehouseOnly&&view==='orders'&&<><label className="field">مرحله سفارش<select value={stage} onChange={e=>setStage(e.target.value)}><option value="">همه مراحل</option>{Object.entries(salesPipelineStages).map(([k,v])=><option key={k} value={k}>{v}</option>)}<option value="late">تحویل عقب‌افتاده</option></select></label><label className="field">جست‌وجوی سفارش<input value={search} onChange={e=>setSearch(e.target.value)}/></label>{records('orders').filter((o:any)=>!stage||pipeline.some((p:any)=>p.orderId===o.id&&(stage==='late'?p.late:p.stage===stage))).filter((o:any)=>(o.data.code+' '+agentName(o.data.agentId)+' '+o.data.customerReference).includes(search)).map((o:any)=>{const ds=data.deliveries.filter((s:any)=>s.orderId===o.id&&s.state!=='cancelled');const progress=pipeline.find((p:any)=>p.orderId===o.id);return <article className="flow-card" key={o.id}><h3>{o.data.code} · {agentName(o.data.agentId)} <span className="badge">{salesStates[o.data.state]}</span></h3><p>{progress&&<>{salesPipelineStages[progress.stage]} · {n(progress.daysSinceRequest)} روز از درخواست · {progress.late?'موعد تحویل گذشته است':'تحویل باقیمانده: '+n(progress.remaining)} · </>}{date(o.created)} · جمع خرید {money(o.data.amount)} · تخفیف {money(o.data.discount)} · مهلت پرداخت {n(o.data.termDays)} روز</p><p>موعد وعده داده‌شده: {date(o.data.promisedDay)} · {o.data.lines.every((l:any)=>ds.filter((s:any)=>s.productId===l.productId&&s.state==='delivered').reduce((v:number,s:any)=>v+s.count,0)>=l.quantity)?'تحویل کامل':ds.some((s:any)=>s.state==='in_transit'||s.state==='delivered')?'در حال ارسال / تحویل جزئی':ds.some((s:any)=>s.state==='reserved')?'رزرو انبار / آماده‌سازی':salesMilestones[o.data.milestone]} · {o.data.progressNote||''}</p>
 <div className="sales-table"><table><thead><tr><th>کالا</th><th>سفارش</th><th>رزرو/ارسال</th><th>تحویل‌شده</th><th>قیمت واحد پس از تخفیف</th><th>اقدام</th></tr></thead><tbody>{o.data.lines.map((l:any)=>{const reserved=ds.filter((s:any)=>s.productId===l.productId).reduce((n:number,s:any)=>n+s.count,0),delivered=ds.filter((s:any)=>s.productId===l.productId&&s.state==='delivered').reduce((n:number,s:any)=>n+s.count,0);return <tr key={l.productId}><td>{l.name}</td><td>{n(l.quantity)}</td><td>{n(reserved)}</td><td>{n(delivered)}</td><td>{money(l.unitNet)}</td><td>{staff&&o.data.state==='approved'&&reserved<l.quantity&&action('reserve','رزرو و حواله جزئی',{agentId:o.data.agentId,orderId:o.id,productId:l.productId,count:Math.min(100,l.quantity-reserved),remaining:l.quantity-reserved})}</td></tr>})}</tbody></table></div>
 <div className="tools">{staff&&o.data.state==='submitted'&&action('order_review','بررسی فروش',{agentId:o.data.agentId,orderId:o.id,revision:o.revision})}{finance&&o.data.state==='sales_approved'&&action('invoice','تأیید مالی و فاکتور',{agentId:o.data.agentId,orderId:o.id,revision:o.revision,amount:o.data.amount,installments:[{due:plusDay(data.today,o.data.termDays),amount:o.data.amount}],creditException:false})}{staff&&['sales_approved','approved'].includes(o.data.state)&&action('order_progress','موعد و مرحله',{agentId:o.data.agentId,orderId:o.id,revision:o.revision,milestone:o.data.milestone,promisedDay:o.data.promisedDay})}{(rep||staff||finance)&&['submitted','sales_approved'].includes(o.data.state)&&action('order_cancel','لغو سفارش',{agentId:o.data.agentId,orderId:o.id,revision:o.revision})}{staff&&o.data.state==='approved'&&<button className="btn" onClick={()=>onNavigate('fulfillment')}>انبار و ارسال</button>}</div>
 {ds.map((s:any)=><div className="notice" key={s.id}><p>{productName(s.productId)} · {n(s.count)} دستگاه · {salesStates[s.state]}{s.transport&&<> · باربری: {s.transport.carrier||'تحویل مستقیم'} · بارنامه: <bdi>{s.transport.waybill||'ثبت نشده'}</bdi> · موعد حمل: {date(s.transport.due)}</>}</p>{(rep||staff)&&s.transport&&['carrier','offered'].includes(s.transport.state)&&action('receipt','تأیید دریافت / اعلام مغایرت',{agentId:o.data.agentId,missionId:s.transport.id,revision:s.transport.revision,packages:s.transport.packages,result:'complete',day:data.today})}{s.transport?.receipt&&<p>نتیجه دریافت: {s.transport.receipt.result==='complete'?'کامل':s.transport.receipt.result==='shortage'?'کسری':'آسیب‌دیدگی'} · {s.transport.receipt.byName||s.transport.receipt.by}{submission(s.transport.receipt.submission)}{s.transport.receipt.fileId&&<a className="link" href={'/api/transport/files?mission='+encodeURIComponent(s.transport.id)+'&id='+encodeURIComponent(s.transport.receipt.fileId)}> · مستند دریافت</a>}</p>}</div>)}{history(o)}</article>})}{!records('orders').length&&<p className="empty">هنوز سفارشی در این فیلتر ثبت نشده است.</p>}</>}
 {!data.warehouseOnly&&view==='account'&&acs.map((a:any)=><article className="flow-card" key={a.agentId}><h3>{agentName(a.agentId)} · مانده خالص {money(a.balance)}</h3><p>اعتبار آزاد {money(a.credit)} · چک وصول‌نشده {money(a.uncollectedChecks)}</p>{a.invoices.map((i:any)=><div className="notice" key={i.id}><h4>فاکتور {i.data.reference} · {i.data.openingId?'مانده منتقل‌شده':'خرید ثبت‌شده'} · {date(i.data.day)}</h4><p>مبلغ {money(i.data.amount)} · مانده {money(i.remaining)}</p><div className="sales-table"><table><thead><tr><th>قسط</th><th>سررسید</th><th>تا موعد</th><th>مبلغ</th><th>تسویه</th><th>مانده</th></tr></thead><tbody>{i.installments.map((p:any)=><tr key={p.id}><td>{p.id}</td><td>{date(p.due)}</td><td>{rial(p.remaining)===BigInt(0)?'تسویه':p.days<0?n(-p.days)+' روز تأخیر':p.days===0?'امروز':n(p.days)+' روز'}</td><td>{money(p.amount)}</td><td>{money(p.paid)}</td><td>{money(p.remaining)}</td></tr>)}</tbody></table></div></div>)}
 <h4>پرداخت‌ها و چک‌ها</h4>{a.payments.map((p:any)=><div className="notice" key={p.id}><p><b>{money(p.data.amount)}</b> · {p.data.method==='check'?'چک':p.data.method==='opening'?'اعتبار افتتاحیه':'پرداخت'} · {salesStates[p.data.state]} · مرجع <bdi>{p.data.reference}</bdi> · {p.data.bank} · {date(p.data.day)}{p.data.method==='check'&&<> · سررسید چک {date(p.data.checkDue)}</>}</p>{p.data.fileId&&<a className="link" href={'/api/sales/files?id='+encodeURIComponent(p.data.fileId)}>دریافت رسید</a>}<div className="tools">{(rep||staff||finance)&&['pending','rejected'].includes(p.data.state)&&!p.data.openingId&&action('payment','اصلاح پرداخت',{...p.data,paymentId:p.id,revision:p.revision})}{finance&&p.data.state==='pending'&&action('payment_review','تطبیق و بررسی',{agentId:a.agentId,paymentId:p.id,revision:p.revision})}{finance&&p.data.method==='check'&&['received','cleared'].includes(p.data.state)&&action('check_status','وصول / برگشت چک',{agentId:a.agentId,paymentId:p.id,revision:p.revision,state:p.data.state==='received'?'cleared':'bounced'})}{finance&&p.data.state==='cleared'&&action('payment_reverse','برگشت ثبت مالی',{agentId:a.agentId,paymentId:p.id,revision:p.revision})}</div>{history(p)}</div>)}
 <h4>اعتبار قابل تخصیص</h4>{a.credits.filter((c:any)=>rial(c.available)>BigInt(0)).map((c:any)=><p className="notice" key={c.id}>{c.type==='sales_return'?'اعتبار برگشت کالا':c.data.reference} · {money(c.available)} {finance&&action('allocate','تخصیص به اقساط',{agentId:a.agentId,creditId:c.id,available:c.available,allocations:[{invoiceId:'',installmentId:'',amount:''}]})}</p>)}<details><summary>سوابق تخصیص اعتبار</summary>{a.allocations.map((l:any)=><p key={l.id}>{date(l.created)} · {money(l.data.amount)} · فاکتور {a.invoices.find((i:any)=>i.id===l.data.invoiceId)?.data.reference} · قسط {l.data.installmentId}{!a.credits.some((c:any)=>c.id===l.data.creditId)&&' · پرداخت برگشت خورده؛ تخصیص در مانده اثر ندارد'}</p>)}</details>
 </article>)}
 {!data.warehouseOnly&&view==='targets'&&<><h3>اهداف مصوب فروش</h3>{records('goals').map((g:any)=><article className="flow-card" key={g.id}><h4>{g.data.title} · {agentName(g.data.agentId)}</h4><p>{date(g.data.start)} تا {date(g.data.end)} · هدف {g.data.basis==='net'?money(g.data.amount):n(Number(g.data.amount))+' دستگاه'} · تحقق {n(g.progress.achievementBps/100)}٪ · مانده {g.data.basis==='net'?money(g.progress.remaining):n(Number(g.progress.remaining))+' دستگاه'}</p></article>)}{!records('goals').length&&<p>هدف مصوب مستقلی در این فیلتر تعریف نشده است.</p>}<h3>پلکان تخفیف</h3>{data.roles.manager&&action('target','تارگت جدید',{start:data.today,end:plusDay(data.today,30)})}<p className="notice">مبنای تخفیف: خرید خالص فاکتورشده دوره، برای سفارش بعدی. بدهی معوق تخفیف جدید را متوقف می‌کند. هر ۱۰۰ واحد نرخ برابر ۱٪ است؛ در فرم درصد نمایش داده می‌شود.</p>{records('targets').map((t:any)=><article className="flow-card" key={t.id}><h3>{t.data.title} · {agentName(t.data.agentId)} · نسخه {n(t.data.version)} {t.data.state==='retired'?'· جایگزین‌شده':''}</h3><p>{date(t.data.start)} تا {date(t.data.end)} · {t.data.productIds.length?t.data.productIds.map(productName).join('، '):'همه محصولات'}</p><p>عملکرد: {t.data.basis==='units'?n(Number(t.progress.progress))+' دستگاه':money(t.progress.progress)} · تخفیف پلکان کسب‌شده: {n(t.progress.earnedBps/100)}٪{t.progress.overdue&&' · به علت بدهی معوق، تخفیف سفارش جدید متوقف است'}</p>{t.progress.next?<p>تا تخفیف {n(t.progress.next.discountBps/100)}٪: {t.data.basis==='units'?n(Number(t.progress.next.remaining))+' دستگاه':money(t.progress.next.remaining)} باقی مانده است.</p>:<p>پلکان پایانی تکمیل شده است.</p>}<div className="tools">{t.data.tiers.map((v:any,i:number)=><span className="notice" key={i}>{t.data.basis==='units'?n(Number(v.threshold))+' دستگاه':money(v.threshold)} ← {n(v.discountBps/100)}٪</span>)}</div>{data.roles.manager&&t.data.state==='active'&&action('target','انتشار نسخه جدید',{...t.data,previousId:t.id,revision:t.revision})}</article>)}</>}
 {(data.warehouseOnly||view==='returns')&&<>{!data.warehouseOnly&&(rep||staff||finance)&&action('return_request','درخواست برگشت')}<p className="notice">برگشتی باید به سریال تحویل‌شده همان فاکتور متصل باشد. دریافت انبار، کالا را به قرنطینه می‌برد؛ اعتبار فقط با تأیید مالی ایجاد می‌شود.</p>{(data.warehouseOnly?data.returns:acs.flatMap((a:any)=>a.returns)).filter((r:any)=>agentIds.has(r.data.agentId)).map((r:any)=><article className="flow-card" key={r.id}><h3>{agentName(r.data.agentId)} · {salesStates[r.data.state]}</h3><p>{r.data.serials.join('، ')} · {r.data.reason}</p>{!data.warehouseOnly&&<p>{money(r.data.amount)}</p>}<div className="tools">{data.roles.warehouse&&r.data.state==='requested'&&action('return_receive','ثبت دریافت فیزیکی',{agentId:r.data.agentId,returnId:r.id,revision:r.revision,physicallyReceived:false})}{finance&&['requested','returned'].includes(r.data.state)&&action('return_review',r.data.state==='returned'?'تأیید اعتبار برگشت':'رد درخواست برگشت',{agentId:r.data.agentId,returnId:r.id,revision:r.revision,approved:r.data.state==='returned'})}</div>{!data.warehouseOnly&&history(r)}</article>)}</>}
 {!data.warehouseOnly&&view==='profiles'&&<>{data.roles.manager&&action('agent','تعریف نماینده',{agentId:''})}{agents.map((a:any)=><article className="flow-card" key={a.id}><h3>{a.data.name} · {a.data.active?'فعال':'غیرفعال'}</h3><p>{a.data.contact} · <bdi>{a.data.phone}</bdi> · {a.data.province} / {a.data.city}</p><p>{a.data.address}</p><p>مرجع قرارداد: {a.data.contractRef||'ثبت نشده'} · سقف اعتبار: {money(a.data.creditLimit)} · مهلت خرید: {n(a.data.termDays)} روز</p>{!rep&&<p>کارشناس فروش: {data.members.find((m:any)=>m.id===a.data.ownerId)?.name||'اعضای نقش فروش'} · مسئول مالی: {data.members.find((m:any)=>m.id===a.data.financeId)?.name||'اعضای نقش مالی فروش'} · مدیر پیگیری: {data.members.find((m:any)=>m.id===a.data.managerId)?.name||'مدیر فروش فعال موجود'}</p>}<div className="tools">{staff&&<button className="btn primary" onClick={()=>{setSelected(a.id);setProvince('');setStage('');setView('orders')}}>کارهای این نماینده</button>}{data.roles.manager&&action('agent','ویرایش پرونده',{...a.data,agentId:a.id,revision:a.revision})}{finance&&action('terms','سقف و مهلت اعتباری',{agentId:a.id,revision:a.revision,creditLimit:a.data.creditLimit,termDays:a.data.termDays})}{data.roles.manager&&a.data.active&&action('account','ساخت حساب ورود',{agentId:a.id,revision:a.revision,name:a.data.contact})}{(rep||staff||finance)&&action('file','افزودن قرارداد / مدرک',{agentId:a.id,title:''})}</div>{data.roles.manager&&accounts.filter(c=>c.agentId===a.id).map(c=><p key={c.id}>حساب: <bdi>{c.username}</bdi> · {c.name} · {c.status==='active'?'فعال':'غیرفعال'} · مدیریت رمز و غیرفعال‌سازی در کاربران توسط مدیر سامانه</p>)}{files(a.id).map((f:any)=><p key={f.id}><a href={'/api/sales/files?id='+encodeURIComponent(f.id)}>{f.data.title} · {f.data.filename}</a></p>)}</article>)}</>}
 {!data.warehouseOnly&&view==='setup'&&<><h3>قیمت نهایی واحد محصول، ریال</h3>{data.roles.manager&&action('price','تعریف قیمت',{agentId:'',reference:''})}<p>قیمت اختصاصی نماینده بر قیمت عمومی اولویت دارد؛ سفارش‌های تأییدشده با ویرایش قیمت تغییر نمی‌کنند.</p>{data.prices.filter((p:any)=>!p.data.agentId||agentIds.has(p.data.agentId)).map((p:any)=><div className="notice" key={p.id}>{productName(p.data.productId)} · {p.data.agentId?agentName(p.data.agentId):'همه نمایندگان'} · {money(p.data.unitPrice)} · {p.data.active?'فعال':'غیرفعال'} {data.roles.manager&&action('price','ویرایش',{...p.data,priceId:p.id,revision:p.revision})}</div>)}
 <h3>انتقال مانده افتتاحیه</h3><p className="notice">فقط مانده باز هر قسط و اعتبار موجود را وارد کنید. جمع‌ها و مرجع منبع قبل از تأیید مالی کنترل می‌شوند. این ورود، سوابق تولید یا گارانتی دستگاه‌ها را منتقل نمی‌کند.</p>{(staff||finance)&&action('opening','پیش‌نویس افتتاحیه',{asOf:data.today,source:'',expectedDebt:'0',expectedCredit:'0',items:[{kind:'invoice',legacyId:'',reference:'',amount:'',day:data.today,due:data.today,bank:''}]})}
 {records('openings').map((o:any)=><article className="flow-card" key={o.id}><h4>{agentName(o.data.agentId)} · {o.data.source} / {o.data.reference} · {salesStates[o.data.state]}</h4><p>مبنا {date(o.data.asOf)} · بدهی {money(o.data.debt)} · اعتبار {money(o.data.credit)}</p>{o.data.items.map((i:any)=><p key={i.index}>{i.legacyId} · {i.kind==='invoice'?'قسط فاکتور':i.kind==='check'?'چک وصول‌نشده':'اعتبار'} · {i.reference} · {money(i.amount)} · {date(i.due||i.day)}</p>)}{finance&&o.data.state==='pending'&&action('opening_review','تطبیق و تأیید انتقال',{agentId:o.data.agentId,openingId:o.id,revision:o.revision})}{history(o)}</article>)}</>}
 <details style={{marginTop:24}}><summary>قواعد حساب، تخفیف و پیگیری</summary>{data.help.map((h:string,i:number)=><p key={i}>{h}</p>)}</details>
 </div>
 <Dialog open={!!draft} onOpenChange={v=>{if(!busy&&!v){setDraft(null);setFile(null);setQuote(null)}}}><DialogContent className="modal sm:max-w-4xl"><DialogTitle>{salesActions[draft?.mode]||({account:'ساخت حساب نماینده',reserve:'رزرو از موجودی واقعی انبار',receipt:'دریافت محموله',file:'مدرک نماینده'} as any)[draft?.mode]}</DialogTitle><DialogDescription>مبلغ‌ها ریال هستند. ثبت با نام حساب شما و همراه سابقه انجام می‌شود.</DialogDescription>{draft&&<form onSubmit={save}><fieldset disabled={busy} style={{border:0,padding:0}}><div className="formgrid">
 {!rep&&['order','payment','return_request','target','opening','price'].includes(draft.mode)&&pick('agentId',draft.mode==='price'?'نماینده (خالی: قیمت عمومی)':'نماینده',Object.fromEntries(data.agents.map((a:any)=>[a.id,a.data.name])),draft.mode!=='price')}
 {!rep&&[...salesProxyModes,'receipt'].includes(draft.mode)&&<div className="flow-card wide"><h3>ثبت از طرف {agentName(draft.agentId)}</h3><p>ثبت‌کننده: {data.meName}. اطلاعات درخواست واقعی و توافق نماینده را وارد کنید.</p><div className="formgrid"><label className="field">روش دریافت درخواست<select required value={draft.requestSource?.channel||''} onChange={e=>change('requestSource',{...draft.requestSource,channel:e.target.value})}>{Object.entries(salesRequestChannels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field">نام شخص تماس‌گیرنده / تأییدکننده<input required maxLength={200} value={draft.requestSource?.contactName||''} onChange={e=>change('requestSource',{...draft.requestSource,contactName:e.target.value})}/></label><SolarDate label="تاریخ دریافت درخواست" value={draft.requestSource?.day||''} onChange={v=>change('requestSource',{...draft.requestSource,day:v})}/><label className="field wide">مرجع پیام یا نامه / خلاصه تماس و توافق<textarea required maxLength={1000} value={draft.requestSource?.reference||''} onChange={e=>change('requestSource',{...draft.requestSource,reference:e.target.value})}/></label></div></div>}
 {draft.mode==='agent'&&<>{field('name','نام نمایندگی')}{field('contact','مسئول تماس')}{field('phone','شماره تماس')}{field('province','استان')}{field('city','شهر')}{field('address','نشانی تحویل')}{field('contractRef','مرجع قرارداد',false)}{pick('ownerId','کارشناس مسئول (خالی: اعضای نقش فروش)',Object.fromEntries(data.members.filter((m:any)=>m.sales).map((m:any)=>[m.id,m.name])),false)}{pick('financeId','مسئول مالی (خالی: اعضای نقش مالی)',Object.fromEntries(data.members.filter((m:any)=>m.finance).map((m:any)=>[m.id,m.name])),false)}{pick('managerId','مدیر پیگیری (خالی: مدیر فروش فعال موجود)',Object.fromEntries(data.members.filter((m:any)=>m.manager).map((m:any)=>[m.id,m.name])),false)}{check('active','نمایندگی فعال است')}</>}
 {draft.mode==='terms'&&<>{field('creditLimit','سقف بدهی مجاز، ریال',true,true)}{number('termDays','مهلت خرید، روز',0,365)}{note()}</>}
 {draft.mode==='price'&&<>{pick('productId','محصول',Object.fromEntries(data.products.map((p:any)=>[p.id,p.name])))}{field('unitPrice','قیمت نهایی واحد، ریال',true,true)}{field('reference','مرجع تصویب قیمت')}{check('active','قیمت فعال')}</>}
 {draft.mode==='target'&&<>{field('title','عنوان تارگت')}{solar('start','شروع دوره')}{solar('end','پایان دوره')}{pick('basis','مبنای محاسبه',{net:'مبلغ خالص فاکتور',units:'تعداد دستگاه'})}<div className="wide"><p>محصولات مشمول (بدون انتخاب: همه محصولات)</p>{data.products.map((p:any)=><label className="flow-check" key={p.id}><input type="checkbox" checked={draft.productIds.includes(p.id)} onChange={e=>change('productIds',e.target.checked?[...draft.productIds,p.id]:draft.productIds.filter((v:string)=>v!==p.id))}/>{p.name}</label>)}</div><div className="wide">{draft.tiers.map((t:any,i:number)=><div className="formgrid" key={i}><label className="field">آستانه {draft.basis==='units'?'تعداد':'ریال'}<input required inputMode="numeric" value={t.threshold} onChange={e=>setRow('tiers',i,'threshold',digits(e.target.value))}/></label><label className="field">درصد تخفیف<input required type="number" min="0" max="90" step="0.01" value={t.discountBps/100} onChange={e=>setRow('tiers',i,'discountBps',Math.round(Number(e.target.value)*100))}/></label><button className="btn" type="button" disabled={draft.tiers.length===1} onClick={()=>change('tiers',draft.tiers.filter((_:any,j:number)=>i!==j))}>حذف پلکان</button></div>)}<button className="btn" type="button" onClick={()=>change('tiers',[...draft.tiers,{threshold:'',discountBps:100}])}>افزودن پلکان</button></div>{note()}</>}
 {draft.mode==='order'&&<><div className="wide">{draft.items.map((l:any,i:number)=><div className="formgrid" key={i}><label className="field">محصول<select required value={l.productId} onChange={e=>setRow('items',i,'productId',e.target.value)}><option value="">انتخاب کنید</option>{data.products.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="field">تعداد<input type="number" required min="1" max="10000" value={l.quantity} onChange={e=>setRow('items',i,'quantity',Number(e.target.value))}/></label><button type="button" className="btn" disabled={draft.items.length===1} onClick={()=>change('items',draft.items.filter((_:any,j:number)=>i!==j))}>حذف ردیف</button></div>)}<button type="button" className="btn" onClick={()=>change('items',[...draft.items,{productId:'',quantity:1}])}>افزودن کالا</button></div>{field('customerReference','شماره درخواست نماینده',false)}{field('notes','توضیح سفارش',false)}{quote&&<div className="notice wide"><h3>پیش‌فاکتور قابل تأیید</h3>{quote.lines.map((l:any)=><p key={l.productId}>{l.name} × {n(l.quantity)} · واحد {money(l.unitNet)} · جمع {money(l.net)}</p>)}<p>جمع نهایی <b>{money(quote.amount)}</b> · تخفیف {money(quote.discount)} ({n(quote.discountBps/100)}٪) · مهلت پرداخت {n(quote.termDays)} روز</p><p>مقصد: {quote.recipient.address}</p><p>با تأیید، همین قیمت و شرایط ثبت می‌شود. زمان تحویل پس از بررسی شرکت اعلام خواهد شد.</p></div>}</>}
 {['order_review','payment_review','opening_review'].includes(draft.mode)&&<>{check('approved','تأیید می‌کنم (برداشتن علامت: رد درخواست)')}{note()}</>}
 {draft.mode==='return_review'&&<><p className="notice wide">{draft.approved?'دریافت انبار ثبت شده است. تأیید، اعتبار برگشت را ایجاد می‌کند.':'این اقدام درخواست برگشت دریافت‌نشده را رد می‌کند.'}</p>{note()}</>}
 {['order_cancel','payment_reverse'].includes(draft.mode)&&<><p className="notice wide">{draft.mode==='payment_reverse'?'برگشت پرداخت، اثر همه تخصیص‌های این پرداخت را از مانده فاکتورها حذف می‌کند و بدهی دوباره باز می‌شود.':'سفارش پیش از صدور فاکتور لغو می‌شود.'}</p>{note()}</>}
 {draft.mode==='order_progress'&&<>{pick('milestone','مرحله',salesMilestones)}{solar('promisedDay','موعد جدید تحویل')}{note()}</>}
 {draft.mode==='invoice'&&<>{field('reference','شماره فاکتور / مرجع حسابداری')}<p className="notice wide">مبلغ فاکتور: {money(draft.amount)} · جمع اقساط باید دقیقاً همین مبلغ باشد.</p><div className="wide">{draft.installments.map((p:any,i:number)=><div className="formgrid" key={i}><SolarDate label={'سررسید قسط '+n(i+1)} value={p.due} onChange={v=>setRow('installments',i,'due',v)}/><label className="field">مبلغ، ریال<input required value={p.amount} inputMode="numeric" onChange={e=>setRow('installments',i,'amount',digits(e.target.value))}/></label><button type="button" className="btn" disabled={draft.installments.length===1} onClick={()=>change('installments',draft.installments.filter((_:any,j:number)=>i!==j))}>حذف</button></div>)}<button type="button" className="btn" onClick={()=>change('installments',[...draft.installments,{due:data.today,amount:''}])}>افزودن قسط</button></div>{check('creditException','استثنای سقف اعتبار یا بدهی معوق را تأیید می‌کنم')}{draft.creditException&&field('exceptionReason','دلیل و مرجع اجازه استثنا')}{field('notes','یادداشت مالی',false)}</>}
 {draft.mode==='payment'&&<>{pick('method','روش',{bank:'واریز بانکی',cash:'نقد با رسید',check:'چک'})}{field('amount','مبلغ، ریال',true,true)}{solar('day','تاریخ پرداخت / تحویل چک')}{field('bank','بانک',draft.method!=='cash')}{field('reference',draft.method==='check'?'شناسه چک':'شماره پیگیری / رسید')}{draft.method==='check'&&solar('checkDue','سررسید چک')}{field('notes','توضیح پرداخت',false)}<label className="field">انتخاب رسید قبلاً بارگذاری‌شده<select value={draft.fileId||''} onChange={e=>change('fileId',e.target.value)}><option value="">بارگذاری فایل جدید</option>{files(draft.agentId).map((f:any)=><option key={f.id} value={f.id}>{f.data.title} · {f.data.filename}</option>)}</select></label><p className="notice wide">اعلام پرداخت یا تحویل چک هنوز بدهی را کم نمی‌کند. مالی باید وصول و تخصیص به فاکتور را تأیید کند.</p></>}
 {['file','payment'].includes(draft.mode)&&!draft.fileId&&<>{draft.mode==='file'&&field('title','عنوان مدرک')}<label className="field">فایل خصوصی (حداکثر ۱۰ مگابایت)<input type="file" required={draft.mode==='file'||draft.method!=='cash'} onChange={e=>setFile(e.target.files?.[0]||null)}/></label></>}
 {draft.mode==='check_status'&&<>{pick('state','نتیجه',{cleared:'وصول شد',bounced:'برگشت خورد'})}{note()}</>}
 {draft.mode==='allocate'&&<><p className="notice wide">اعتبار آزاد: {money(draft.available)}</p><div className="wide">{draft.allocations.map((l:any,i:number)=>{const ac=data.accounts.find((a:any)=>a.agentId===draft.agentId),invoices=ac.invoices.filter((v:any)=>rial(v.remaining)>BigInt(0));return <div className="formgrid" key={i}><label className="field">فاکتور<select required value={l.invoiceId} onChange={e=>change('allocations',draft.allocations.map((a:any,j:number)=>j===i?{...a,invoiceId:e.target.value,installmentId:''}:a))}><option value="">انتخاب کنید</option>{invoices.map((v:any)=><option key={v.id} value={v.id}>{v.data.reference}</option>)}</select></label><label className="field">قسط<select required value={l.installmentId} onChange={e=>setRow('allocations',i,'installmentId',e.target.value)}><option value="">انتخاب کنید</option>{(invoices.find((v:any)=>v.id===l.invoiceId)?.installments||[]).filter((p:any)=>rial(p.remaining)>BigInt(0)).map((p:any)=><option key={p.id} value={p.id}>{p.id} · {date(p.due)} · مانده {money(p.remaining)}</option>)}</select></label><label className="field">تخصیص، ریال<input required value={l.amount} inputMode="numeric" onChange={e=>setRow('allocations',i,'amount',digits(e.target.value))}/></label><button type="button" className="btn" disabled={draft.allocations.length===1} onClick={()=>change('allocations',draft.allocations.filter((_:any,j:number)=>i!==j))}>حذف</button></div>})}<button type="button" className="btn" onClick={()=>change('allocations',[...draft.allocations,{invoiceId:'',installmentId:'',amount:''}])}>افزودن تخصیص</button></div>{note()}</>}
 {draft.mode==='return_request'&&<>{pick('invoiceId','فاکتور',Object.fromEntries((data.accounts.find((a:any)=>a.agentId===draft.agentId)?.invoices||[]).filter((i:any)=>!i.data.openingId).map((i:any)=>[i.id,i.data.reference])))}<div className="wide"><p>سریال‌های تحویل‌شده این فاکتور</p>{data.deliveries.filter((s:any)=>s.state==='delivered'&&s.orderId===(data.accounts.find((a:any)=>a.agentId===draft.agentId)?.invoices.find((i:any)=>i.id===draft.invoiceId)?.data.orderId)).flatMap((s:any)=>s.deviceIds.map((did:string)=><label key={did} className="flow-check"><input type="checkbox" checked={(draft.deviceIds||[]).includes(did)} onChange={e=>change('deviceIds',e.target.checked?[...(draft.deviceIds||[]),did]:(draft.deviceIds||[]).filter((v:string)=>v!==did))}/>{productName(s.productId)} · <bdi>{s.devices.find((v:any)=>v.id===did)?.serial||did}</bdi></label>))}</div>{note()}</>}
 {draft.mode==='return_receive'&&<>{field('receipt','شماره رسید انبار')}{check('physicallyReceived','همه سریال‌های این درخواست را فیزیکی دریافت و کنترل کردم')}{field('notes','وضعیت ظاهری و محل قرنطینه')}</>}
 {draft.mode==='opening'&&<>{field('source','نام سامانه / منبع قبلی')}{field('reference','شماره گزارش منبع')}{solar('asOf','تاریخ مبنا')}{field('expectedDebt','جمع بدهی باز در منبع، ریال',true,true)}{field('expectedCredit','جمع اعتبار در منبع، ریال',true,true)}<p className="notice wide">جمع ردیف‌های فعلی: بدهی {money(total(draft.items.filter((i:any)=>i.kind==='invoice'&&/^\d+$/.test(i.amount)),i=>i.amount))} · اعتبار {money(total(draft.items.filter((i:any)=>i.kind==='credit'&&/^\d+$/.test(i.amount)),i=>i.amount))}</p><div className="wide">{draft.items.map((l:any,i:number)=><div className="flow-card" key={i}><div className="formgrid"><label className="field">نوع<select value={l.kind} onChange={e=>setRow('items',i,'kind',e.target.value)}><option value="invoice">مانده قسط فاکتور</option><option value="credit">اعتبار / پیش‌پرداخت</option><option value="check">چک وصول‌نشده</option></select></label>{[['legacyId','شناسه یکتای ردیف قدیمی'],['reference','شماره فاکتور / رسید / چک'],['amount','مانده، ریال'],...(l.kind==='check'?[['bank','بانک']]:[])].map(([key,label])=><label className="field" key={key}>{label}<input required value={l[key]} onChange={e=>setRow('items',i,key,key==='amount'?digits(e.target.value):e.target.value)}/></label>)}<SolarDate label="تاریخ سند" value={l.day} onChange={v=>setRow('items',i,'day',v)}/>{l.kind!=='credit'&&<SolarDate label="سررسید" value={l.due} onChange={v=>setRow('items',i,'due',v)}/>}</div><button type="button" className="btn" disabled={draft.items.length===1} onClick={()=>change('items',draft.items.filter((_:any,j:number)=>i!==j))}>حذف ردیف</button></div>)}<button type="button" className="btn" onClick={()=>change('items',[...draft.items,{kind:'invoice',legacyId:'',reference:'',amount:'',bank:'',day:data.today,due:data.today}])}>افزودن ردیف</button></div>{note()}</>}
 {draft.mode==='account'&&<>{field('name','نام کاربر')}{field('username','نام کاربری انگلیسی')}<label className="field">رمز اولیه<input type="password" autoComplete="new-password" required minLength={10} maxLength={128} value={draft.password||''} onChange={e=>change('password',e.target.value)}/></label><p className="notice wide">این حساب فقط اطلاعات همین نماینده را می‌بیند. رمز را فقط در این فرم وارد کنید؛ در گفتگو ثبت نکنید.</p></>}
 {draft.mode==='reserve'&&<><p className="notice wide">{productName(draft.productId)} · باقیمانده سفارش {n(draft.remaining)} دستگاه. سریال آزاد واقعی به ترتیب دریافت انبار رزرو می‌شود.</p>{number('count','تعداد این حواله',1,Math.min(100,draft.remaining))}{field('notes','توضیح حواله',false)}</>}
 {draft.mode==='receipt'&&<>{!rep&&<label className="field wide">مستند دریافت نماینده / مغایرت همین محموله (PDF یا تصویر، تا ۱۰ مگابایت)<input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" required={!draft.receiptFileId} onChange={e=>{setFile(e.target.files?.[0]||null);setDraft((d:any)=>({...d,receiptFileId:'',fileRequestId:crypto.randomUUID()}))}}/></label>}{number('packages','تعداد بسته دریافت‌شده',1,10000)}{solar('day','تاریخ دریافت')}{pick('result','نتیجه',{complete:'کامل و سالم',shortage:'کسری',damage:'آسیب‌دیدگی'})}{note()}</>}
 </div>{error&&<p role="alert" className="notice error">{error}</p>}<div className="tools"><button className="btn primary" disabled={busy}>{busy?'در حال ثبت…':draft.mode==='order'&&!quote?'محاسبه و نمایش پیش‌فاکتور':'تأیید و ثبت'}</button><button type="button" className="btn" disabled={busy} onClick={()=>setDraft(null)}>انصراف</button></div></fieldset></form>}</DialogContent></Dialog>
 </section>;
}
