'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {SolarDate} from './solar-date';
import {formatDate,formatDateTime,localDay,latinDigits} from '@/lib/persian-date';
import {reportKinds,alertKinds,alertStates,monitorDefaults} from '@/lib/sales-monitor-contract';
import {salesPipelineStages,rial} from '@/lib/sales-contract';
const money=(v:any)=>rial(v).toLocaleString('fa-IR')+' ریال',num=(v:number)=>v.toLocaleString('fa-IR');
export function SalesMonitorPanel({onOpenAgent,onTasks}:{onOpenAgent:(id:string,section:string)=>void;onTasks:()=>void}){
 const [data,setData]=useState<any>(null),[tab,setTab]=useState('alerts'),[kind,setKind]=useState('daily'),[report,setReport]=useState<any>(null),[draft,setDraft]=useState<any>(null),[filter,setFilter]=useState('open'),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[settings,setSettings]=useState<any>(null);
 async function read(url:string){const r=await fetch(url,{cache:'no-store'}),d=await r.json() as any;if(!r.ok)throw Error(d.error||'دریافت انجام نشد.');return d;}
 async function load(){const d=await read('/api/sales/monitor');setData(d);setSettings(d.policy?.data||monitorDefaults);}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 const begin=(mode:string,extra:any={})=>{setError('');setDraft({mode,id:crypto.randomUUID(),confirmed:true,notes:'',...extra});};
 const set=(key:string,value:any)=>setDraft((d:any)=>({...d,[key]:value}));
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const b={...draft};if(b.mode==='assign'){b.due=b.dueDay+'T16:00:00+03:30';delete b.dueDay;}const r=await fetch('/api/sales/monitor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setDraft(null);setMessage(d.followupPending?'ثبت شد؛ ارزیابی مجدد در اجرای بعدی انجام می‌شود.':'ثبت شد.');await load();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function showReport(query:string){setError('');try{setReport((await read('/api/sales/monitor?'+query)).report);}catch(e){setError((e as Error).message)}}
 const text=(key:string,label:string,numeric=false)=><label className="field">{label}<input required value={draft?.[key]||''} inputMode={numeric?'numeric':undefined} onChange={e=>set(key,numeric?latinDigits(e.target.value).replace(/[,٬]/g,''):e.target.value)}/></label>;
 if(!data)return <p role={error?'alert':'status'}>{error||'در حال دریافت پایش فروش…'}</p>;
 const agentName=(id:string)=>data.agents.find((a:any)=>a.id===id)?.name||id,memberName=(id:string)=>data.members.find((m:any)=>m.id===id)?.name||'تعیین نشده';
 const alerts=data.alerts.filter((a:any)=>filter==='all'||filter==='closed'?filter==='all'||['resolved','reviewed'].includes(a.data.state):!['resolved','reviewed'].includes(a.data.state));
 const reportData=report?.data;
 return <div className="sales-monitor"><div className="tools"><button className={'btn '+(tab==='alerts'?'primary':'')} onClick={()=>setTab('alerts')}>هشدارها و پیگیری</button>{data.manager&&<button className={'btn '+(tab==='reports'?'primary':'')} onClick={()=>setTab('reports')}>گزارش‌های مدیر</button>}<button className={'btn '+(tab==='goals'?'primary':'')} onClick={()=>setTab('goals')}>اهداف مصوب فروش</button>{data.manager&&<button className={'btn '+(tab==='settings'?'primary':'')} onClick={()=>setTab('settings')}>قواعد و زمان‌بندی</button>}<button className="btn" onClick={()=>void load().catch(e=>setError(e.message))}>تازه‌سازی</button><button className="btn" onClick={onTasks}>کارتابل</button></div>
 <p className={'notice '+(data.health.backgroundStale?'error':'')}>آخرین بررسی: {formatDateTime(data.health.lastScan)} · بررسی پس‌زمینه: {formatDateTime(data.health.lastBackground)}{data.health.backgroundStale?' — اجرای منظم پس‌زمینه تأیید نشده؛ گزارش به‌موقع با صفحه بسته تضمین نمی‌شود.':' — اجرای پس‌زمینه اخیراً ثبت شده است.'}{data.health.managers===0?' مدیر فروش فعالی برای اعلان کارتابل تعریف نشده است.':''}{data.policy&&!data.policy.data.enabled?' پایش متوقف است.':''}</p>
 {error&&!draft&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}
 {tab==='alerts'&&<><div className="tools"><label className="field">نمایش<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">باز و در پیگیری</option><option value="closed">بسته‌شده</option><option value="all">همه سوابق</option></select></label>{data.manager&&<button className="btn" onClick={()=>begin('scan')}>بررسی الآن و تهیه گزارش‌های سررسیده</button>}</div>{!alerts.length&&<p className="empty">هشداری در این فیلتر و دسترسی ثبت نشده است. زمان آخرین بررسی را در بالای صفحه ببینید.</p>}
 {alerts.map((a:any)=>{const d=a.data,closed=['resolved','reviewed'].includes(d.state);return <article className="flow-card" key={a.id}><h3>{d.title} <span className="badge">{d.severity==='critical'?'مهم':'نیازمند بررسی'}</span></h3><p>{d.summary}</p><p>{alertStates[d.state]} · مسئول: {memberName(d.ownerId)} · مهلت: {formatDateTime(d.due)}</p><p><b>اقدام پیشنهادی:</b> {d.action}</p>
 {d.kind==='overdue'&&<p>معوق: {money(d.evidence.amount)} · قدیمی‌ترین تأخیر: {num(d.evidence.oldestDays)} روز · اعتبار آزاد: {money(d.evidence.freeCredit)}</p>}
 {d.kind==='bounced_check'&&<p>چک: {d.evidence.reference} · مبلغ: {money(d.evidence.amount)} · وصول جایگزین: {money(d.evidence.recovered)} · باقی‌مانده: {money(d.evidence.remaining)}</p>}
 {d.kind==='goal_gap'&&<p>تحقق {num(d.evidence.achievementBps/100)}٪ · زمان سپری‌شده {num(d.evidence.elapsedBps/100)}٪ · فاصله {d.evidence.basis==='net'?money(d.evidence.remaining):num(Number(d.evidence.remaining))+' دستگاه'} · پایان {formatDate(d.evidence.end)}</p>}
 {d.kind==='late_delivery'&&<p>{d.evidence.code} · وعده {formatDate(d.evidence.promisedDay)} · مانده تحویل {num(d.evidence.remaining)} · {salesPipelineStages[d.evidence.stage]} · مانع ثبت‌شده: {d.evidence.recordedBlocker||'ثبت نشده'}</p>}
 {d.kind==='pending_payment'&&<p>رسید {d.evidence.reference} · مبلغ {money(d.evidence.amount)} · از {formatDateTime(d.evidence.since)}</p>}
 {d.kind==='repeat_returns'&&<p>{num(d.evidence.count)} پرونده دریافت‌شده در {num(d.evidence.days)} روز؛ علت مشترک نیازمند بررسی است.</p>}
 {d.lastFollowup&&<p>آخرین پیگیری: {d.lastFollowup} · اقدام بعدی: {d.nextAction}</p>}<div className="tools"><button className="btn" onClick={()=>onOpenAgent(d.agentId,['late_delivery'].includes(d.kind)?'orders':d.kind==='repeat_returns'?'returns':'account')}>پرونده نماینده</button>{!closed&&<button className="btn primary" onClick={()=>begin('followup',{alertId:a.id,revision:a.revision,nextAction:d.nextAction||''})}>ثبت نتیجه و اقدام بعدی</button>}{!closed&&data.manager&&<button className="btn" onClick={()=>begin('assign',{alertId:a.id,revision:a.revision,ownerId:d.ownerId,dueDay:localDay(new Date(Date.now()+86400000)),financeOwner:d.kind==='pending_payment'})}>مسئول و مهلت</button>}{!closed&&data.manager&&d.kind==='goal_gap'&&d.evidence.ended&&<button className="btn" onClick={()=>begin('review_goal',{alertId:a.id,revision:a.revision})}>جمع‌بندی پایان هدف</button>}{!closed&&data.finance&&d.kind==='bounced_check'&&<button className="btn" onClick={()=>{const p=data.bounced.find((p:any)=>p.id===d.sourceId);if(p)begin('recover_check',{paymentId:p.id,revision:p.revision,agentId:d.agentId,amount:p.recovery.remaining,creditId:''});}}>ثبت وصول جایگزین چک</button>}</div>
 <details><summary>سابقه پیگیری</summary>{d.history.map((h:any,i:number)=><p key={i}>{formatDateTime(h.at)} · {h.actorName||'پایش سامانه'} · {h.notes}</p>)}</details></article>})}</>}
 {tab==='reports'&&data.manager&&<><div className="formgrid"><label className="field">دوره<select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(reportKinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><div className="tools"><button className="btn primary" onClick={()=>void showReport('preview='+kind)}>پیش‌نمایش با داده فعلی</button><button className="btn" onClick={()=>begin('scan')}>تهیه گزارش‌های سررسیده</button></div></div><p>گزارش‌های ذخیره‌شده تصویر زمان تهیه هستند؛ پیش‌نمایش با داده فعلی دوباره محاسبه می‌شود. آخرین ۹۰ گزارش در فهرست است.</p>
 <label className="field">گزارش‌های آماده<select value={report?.id||''} onChange={e=>{if(e.target.value)void showReport('report='+encodeURIComponent(e.target.value))}}><option value="">انتخاب گزارش</option>{data.reports.filter((r:any)=>r.kind===kind).map((r:any)=><option key={r.id} value={r.id}>{reportKinds[r.kind]} · {formatDate(r.start)} تا {formatDate(r.end)} · تهیه {formatDateTime(r.created)}</option>)}</select></label>
 {reportData&&<article className="flow-card"><h3>گزارش {reportKinds[reportData.kind]} · {formatDate(reportData.start)} تا {formatDate(reportData.end)}</h3><p>زمان تهیه و تصویر وضعیت جاری: {formatDateTime(reportData.asOf)}{!report.id?' · پیش‌نمایش ذخیره‌نشده':''}</p>{reportData.summary.map((s:string,i:number)=><p key={i}>{s}</p>)}
 <div className="sales-table"><table><caption>گردش دوره و مقایسه ثبت‌شده</caption><thead><tr><th>شاخص</th><th>دوره گزارش</th><th>{formatDate(reportData.previousStart)} تا {formatDate(reportData.previousEnd)}</th>{reportData.yearAgo&&<th>فصل مشابه سال قبل</th>}</tr></thead><tbody>{[['netSales','فروش خالص'],['collections','وصول خالص'],['discounts','تخفیف'],['returns','برگشت تأییدشده']].map(([k,v])=><tr key={k}><td>{v}</td><td>{money(reportData.current[k])}</td><td>{money(reportData.previous[k])}</td>{reportData.yearAgo&&<td>{money(reportData.yearAgo[k])}</td>}</tr>)}</tbody></table></div>
 <details><summary>تمرکز فروش و نمایندگان کم‌فعال</summary><p>سهم از مجموع فروش خالص مثبت ثبت‌شده دوره؛ اعتبار یا برگشتی خالص منفی در مخرج سهم نیست.</p>{reportData.concentration.map((a:any)=><p key={a.agentId}>{a.name}: {money(a.netSales)} · سهم {a.shareBps===null?'قابل محاسبه نیست':num(a.shareBps/100)+'٪'}</p>)}{reportData.inactive.map((a:any)=><p key={a.agentId}>{a.name} · آخرین خرید {formatDate(a.lastPurchase)} · فاصله معمول {num(a.usualDays)} روز · وقفه فعلی {num(a.idleDays)} روز · {a.reason}</p>)}{!reportData.inactive.length&&<p>مورد کم‌فعال با سابقه کافی پیدا نشد؛ حداقل چهار روز خرید مستقل برای مقایسه لازم است.</p>}</details>
 <h4>اولویت‌های مدیر</h4>{reportData.priority.map((a:any)=><div className="notice" key={a.id}><b>{a.title}</b><p>{a.action}</p><p>{a.ownerName} · مهلت {formatDateTime(a.due)}</p><button className="btn" onClick={()=>setTab('alerts')}>باز کردن پیگیری‌ها</button></div>)}{!reportData.priority.length&&<p>هشدار بازی در زمان تهیه گزارش ثبت نشده است.</p>}
 <div className="sales-table"><table><caption>نمایندگان و مطالبات در زمان تهیه</caption><thead><tr><th>نماینده / استان</th><th>کارشناس فعلی</th><th>فروش خالص</th><th>وصول</th><th>مانده</th><th>معوق</th></tr></thead><tbody>{reportData.byAgent.map((a:any)=><tr key={a.id}><td><button className="link" onClick={()=>onOpenAgent(a.id,'account')}>{a.name}</button><small>{a.province}</small></td><td>{a.ownerName}</td><td>{money(a.netSales)}</td><td>{money(a.collections)}</td><td>{money(a.balance)}</td><td>{money(a.overdue)}</td></tr>)}</tbody></table></div>
 <div className="sales-table"><table><caption>عملکرد بر اساس مسئول فعلی پرونده و کارهای باز</caption><thead><tr><th>کارشناس</th><th>نماینده</th><th>فروش</th><th>وصول</th><th>معوق</th><th>کار باز / عقب‌افتاده</th></tr></thead><tbody>{reportData.team.map((m:any)=><tr key={m.id}><td>{m.name}</td><td>{num(m.representatives)}</td><td>{money(m.netSales)}</td><td>{money(m.collections)}</td><td>{money(m.overdue)}</td><td>{num(m.openTasks)} / {num(m.lateTasks)}</td></tr>)}</tbody></table></div>
 <div className="sales-table"><table><caption>محصولات دوره</caption><thead><tr><th>محصول</th><th>تعداد خالص</th><th>فروش خالص</th><th>برگشتی</th></tr></thead><tbody>{reportData.products.map((p:any)=><tr key={p.id}><td>{p.name}</td><td>{num(p.quantity)}</td><td>{money(p.netSales)}</td><td>{money(p.returns)}</td></tr>)}</tbody></table></div>
 <details><summary>سفارش‌های باز و سررسیدهای هفت روز آینده</summary>{reportData.pipeline.map((p:any)=><p key={p.orderId}>{p.code} · {agentName(p.agentId)} · {salesPipelineStages[p.stage]} · {num(p.daysSinceRequest)} روز از درخواست · موعد {formatDate(p.promisedDay)} · {p.late?'عقب‌افتاده':'در مسیر پیگیری'}{p.recordedBlocker?' · '+p.recordedBlocker:''}</p>)}{reportData.due.map((p:any)=><p key={p.invoiceId+':'+p.id}>{agentName(p.agentId)} · فاکتور {p.reference} · {formatDate(p.due)} · {money(p.remaining)}</p>)}{reportData.checksDue.map((p:any)=><p key={p.id}>چک {p.reference} · {agentName(p.agentId)} · سررسید {formatDate(p.due)} · {money(p.amount)} · {p.overdue?'از سررسید گذشته':'در هفته پیش رو'}؛ هنوز وصول نشده است.</p>)}</details>
 <details><summary>نتیجه پیگیری هشدارهای مرتبط با دوره</summary>{reportData.pastAlerts.map((a:any)=><p key={a.id}>{a.title} · {alertStates[a.state]} · {a.lastAction} · {a.resolvedAt?formatDateTime(a.resolvedAt):'هنوز باز'}</p>)}</details>
 {reportData.notes.map((s:string,i:number)=><p className="subtle" key={i}>{s}</p>)}{report.id&&<button className="btn" onClick={()=>begin('report_read',{reportId:report.id})}>گزارش را بررسی کردم</button>}</article>}</>}
 {tab==='goals'&&<><p className="notice">این اهداف برای ارزیابی فروش‌اند. پلکان تخفیف در تب «تارگت و تخفیف» مستقل تنظیم می‌شود.</p>{data.manager&&<button className="btn primary" onClick={()=>begin('goal',{agentId:data.agents.find((a:any)=>a.active)?.id||'',title:'',start:data.today,end:data.today,basis:'net',amount:'',productIds:[]})}>تعریف هدف مصوب</button>}
 {data.goals.map((g:any)=><article className="flow-card" key={g.id}><h3>{g.data.title} · {agentName(g.data.agentId)} · نسخه {num(g.data.version)} · {g.data.state==='active'?'فعال':'جایگزین/متوقف'}</h3><p>{formatDate(g.data.start)} تا {formatDate(g.data.end)} · هدف {g.data.basis==='net'?money(g.data.amount):num(Number(g.data.amount))+' دستگاه'}</p><p>تحقق {num(g.progress.achievementBps/100)}٪ · سپری‌شده {num(g.progress.elapsedBps/100)}٪ · مانده {g.data.basis==='net'?money(g.progress.remaining):num(Number(g.progress.remaining))+' دستگاه'}</p>{g.progress.requiredPerDay&&<p>برای رسیدن به هدف در {num(g.progress.remainingDays)} روز بعد: میانگین روزانه {g.data.basis==='net'?money(g.progress.requiredPerDay):num(Number(g.progress.requiredPerDay))+' دستگاه'}؛ این مقدار نیاز محاسباتی است، پیش‌بینی فروش نیست.</p>}{data.manager&&g.data.state==='active'&&<div className="tools"><button className="btn" onClick={()=>begin('goal',{...g.data,previousId:g.id,revision:g.revision})}>نسخه تازه هدف</button><button className="btn" onClick={()=>begin('retire_goal',{goalId:g.id,revision:g.revision})}>توقف با دلیل</button></div>}</article>)}</>}
 {tab==='settings'&&data.manager&&settings&&<><h3>قواعد پایش و زمان گزارش‌ها</h3><p>زمان‌ها به وقت تهران‌اند. گزارش هفتگی شنبه و گزارش فصلی ابتدای فصل شمسی تهیه می‌شود.</p><div className="formgrid"><label className="flow-check"><input type="checkbox" checked={settings.enabled} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/>پایش فعال باشد</label>{[['dailyTime','ساعت گزارش روزانه'],['weeklyTime','ساعت گزارش هفتگی'],['quarterlyTime','ساعت گزارش فصلی']].map(([k,v])=><label className="field" key={k}>{v}<input type="time" required value={settings[k]} onChange={e=>setSettings({...settings,[k]:e.target.value})}/></label>)}
 {Object.entries({overdueDays:'تأخیر معوق، روز',overdueAmount:'آستانه مبلغ معوق، ریال (صفر: فقط روز)',goalElapsed:'درصد اول زمان سپری‌شده',goalAchievement:'حداقل درصد تحقق در حد اول',goalFinalElapsed:'درصد دوم زمان سپری‌شده',goalFinalAchievement:'حداقل درصد تحقق در حد دوم',deliveryLateDays:'تأخیر تحویل، روز',paymentHours:'انتظار بررسی رسید، ساعت',returnCount:'تعداد پرونده برگشتی برای بررسی',returnDays:'بازه بررسی برگشتی، روز',responseHours:'مهلت اولیه پیگیری هشدار، ساعت',escalationHours:'ارجاع به مدیر پس از مهلت، ساعت'}).map(([k,v])=><label className="field" key={k}>{v}<input value={settings[k]} inputMode="numeric" onChange={e=>{const value=latinDigits(e.target.value).replace(/[,٬]/g,'');setSettings({...settings,[k]:k==='overdueAmount'?value:Number(value)})}}/></label>)}</div><button className="btn primary" onClick={()=>begin('configure',{revision:data.policy.revision,settings})}>بررسی و ذخیره قواعد</button><p>چک برگشتی از زمان ثبت مالی هشدار می‌دهد. آستانه مبلغ معوق با شرط روز به صورت «هرکدام برقرار بود» بررسی می‌شود. تغییر قواعد با نام مدیر و دلیل نگه داشته می‌شود.</p></>}
 <details><summary>روش محاسبه و حدود گزارش</summary>{data.help.map((s:string,i:number)=><p key={i}>{s}</p>)}</details>
 <Dialog open={!!draft} onOpenChange={v=>{if(!busy&&!v)setDraft(null)}}><DialogContent className="modal sm:max-w-3xl"><DialogTitle>{({configure:'تأیید قواعد پایش',goal:'هدف مصوب فروش',retire_goal:'توقف هدف',scan:'بررسی پایش فروش',followup:'نتیجه پیگیری',assign:'تعیین مسئول و مهلت',review_goal:'جمع‌بندی پایان دوره',report_read:'ثبت بررسی گزارش',recover_check:'وصول جایگزین چک'} as any)[draft?.mode]}</DialogTitle><DialogDescription>با نام حساب شما ثبت می‌شود. این اقدامات به‌تنهایی فروش، وصول یا تحویل کالا ایجاد نمی‌کنند.</DialogDescription>{draft&&<form onSubmit={save}><fieldset disabled={busy} style={{border:0,padding:0}}><div className="formgrid">
 {draft.mode==='goal'&&<><label className="field">نماینده<select required disabled={!!draft.previousId} value={draft.agentId} onChange={e=>set('agentId',e.target.value)}><option value="">انتخاب کنید</option>{data.agents.filter((a:any)=>a.active).map((a:any)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{text('title','عنوان هدف')}<SolarDate label="شروع" value={draft.start} onChange={v=>set('start',v)}/><SolarDate label="پایان" value={draft.end} onChange={v=>set('end',v)}/><label className="field">مبنا<select value={draft.basis} onChange={e=>set('basis',e.target.value)}><option value="net">فروش خالص، ریال</option><option value="units">تعداد خالص دستگاه</option></select></label>{text('amount','مقدار هدف',true)}<div className="wide"><p>محصولات مشمول (خالی: همه)</p>{data.products.map((p:any)=><label className="flow-check" key={p.id}><input type="checkbox" checked={draft.productIds.includes(p.id)} onChange={e=>set('productIds',e.target.checked?[...draft.productIds,p.id]:draft.productIds.filter((id:string)=>id!==p.id))}/>{p.name}</label>)}</div></>}
 {draft.mode==='followup'&&text('nextAction','اقدام بعدی مشخص')}
 {draft.mode==='assign'&&<><label className="field">مسئول<select required value={draft.ownerId} onChange={e=>set('ownerId',e.target.value)}><option value="">انتخاب کنید</option>{data.members.filter((m:any)=>draft.financeOwner?m.finance:m.sales).map((m:any)=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><SolarDate label="مهلت جدید، ساعت ۱۶ تهران" value={draft.dueDay} onChange={v=>set('dueDay',v)}/></>}
 {draft.mode==='recover_check'&&<><p className="notice wide">فقط مالی: وصول جایگزین واقعی را به چک مرتبط کنید. اعتبار و تسویه قسط دوباره ایجاد نمی‌شود؛ تخصیص مالی جدا انجام می‌شود.</p><label className="field">وصول تأییدشده نماینده<select required value={draft.creditId} onChange={e=>set('creditId',e.target.value)}><option value="">انتخاب کنید</option>{data.credits.filter((c:any)=>c.agentId===draft.agentId&&rial(c.recoveryAvailable)>BigInt(0)).map((c:any)=><option key={c.id} value={c.id}>{c.reference} · ظرفیت ارتباط {money(c.recoveryAvailable)}</option>)}</select></label>{text('amount','مبلغ وصول جایگزین، ریال',true)}</>}
 {draft.mode==='configure'&&<p className="notice wide">وضعیت: {draft.settings.enabled?'فعال':'متوقف'} · روزانه {draft.settings.dailyTime} · هفتگی {draft.settings.weeklyTime} · فصلی {draft.settings.quarterlyTime} · معوق {num(draft.settings.overdueDays)} روز یا {money(draft.settings.overdueAmount)} (صفر یعنی بدون حد مبلغ). سایر آستانه‌ها مطابق فرم بررسی‌شده ذخیره می‌شوند.</p>}
 {draft.mode==='review_goal'&&<p className="notice wide">این اقدام، هدف محقق‌نشده پایان دوره را با جمع‌بندی مدیریتی می‌بندد؛ هدف را محقق‌شده اعلام نمی‌کند. علت مستند و برنامه اصلاحی را بنویسید.</p>}
 {!['scan','report_read'].includes(draft.mode)&&<label className="field wide">توضیح، دلیل یا نتیجه مستند<textarea required maxLength={4000} rows={3} value={draft.notes} onChange={e=>set('notes',e.target.value)}/></label>}
 </div>{error&&<p className="notice error" role="alert">{error}</p>}<div className="tools"><button className="btn primary" disabled={busy}>{busy?'در حال ثبت…':'تأیید و ثبت'}</button><button type="button" className="btn" onClick={()=>setDraft(null)}>انصراف</button></div></fieldset></form>}</DialogContent></Dialog>
 </div>;
}
