'use client';
import {IconDisclosure,IconActions} from "./program-workspace";
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {SolarDate} from './solar-date';
import {formatDate,localDay} from '@/lib/persian-date';
import {partnerKinds} from '@/lib/sales-network-contract';
const cash=(s:any)=>BigInt(s||0).toLocaleString('fa-IR')+' ریال';
const modes:Record<string,string>={commission_cancel:'لغو تسویه پرداخت‌نشده',check_link:'اتصال چک به خرید',template:'الگوی عمومی فروش',partner:'نوع همکاری و برنامه پیگیری',contact:'ثبت تماس یا بازدید',case:'درخواست همکاری و پشتیبانی',case_update:'پیگیری / بستن پرونده',contract:'قرارداد پورسانت',contract_review:'بررسی مالی قرارداد',commission_settlement:'درخواست تسویه پورسانت',commission_review:'بررسی تسویه',commission_pay:'ثبت پرداخت واقعی پورسانت'};
export function SalesNetworkPanel({selected,members,onChange}:{selected:string;members:any[];onChange:()=>void}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[draft,setDraft]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){const r=await fetch('/api/sales/network',{cache:'no-store'}),d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);}
 useEffect(()=>{void load().catch(e=>setError(e.message))},[]);
 const begin=(mode:string,a:any=null,r:any=null)=>{setError('');setDraft({id:crypto.randomUUID(),confirmed:true,mode,agentId:a?.id||'',recordId:r?.id,revision:r?.revision||a?.revision||0,kind:a?.data.kind||'representative',ownerId:a?.data.ownerId||'',contactDays:a?.data.contactDays||30,reorderDays:a?.data.reorderDays||60,day:localDay(),start:localDay(),end:'',nextDue:localDay(),nextAction:'',channel:'call',state:'open',cashBps:5000,months:1,bps:0,approved:true,notes:'',...(['case_update'].includes(mode)?{state:r.data.state}:{}),...(mode==='template'?{previousId:data.templates.filter((r:any)=>r.data.kind==='representative').sort((a:any,b:any)=>(b.data.version||0)-(a.data.version||0)||b.created.localeCompare(a.created)||b.id.localeCompare(a.id))[0]?.id||''}:{})});};
 const update=(k:string,v:any)=>setDraft((d:any)=>({...d,[k]:v,...(d.mode==='template'&&k==='kind'?{previousId:data.templates.filter((r:any)=>r.data.kind===v).sort((a:any,b:any)=>(b.data.version||0)-(a.data.version||0)||b.created.localeCompare(a.created)||b.id.localeCompare(a.id))[0]?.id||''}:{})}));
 const field=(k:string,label:string,type='text',max=10000)=><label className="field">{label}<input required type={type} min="0" max={max} value={draft[k]??''} onChange={e=>update(k,type==='number'?Number(e.target.value):e.target.value)}/></label>;
 const pick=(k:string,label:string,values:Record<string,string>)=><label className="field">{label}<select required value={draft[k]||''} onChange={e=>update(k,e.target.value)}><option value="">انتخاب کنید</option>{Object.entries(values).map(([v,t])=><option value={v} key={v}>{t}</option>)}</select></label>;
 const percent=(k:string,label:string)=><label className="field">{label}<input required type="number" min="0" max="100" step="0.01" value={(draft[k]||0)/100} onChange={e=>update(k,Math.round(Number(e.target.value)*100))}/></label>;
 const date=(k:string,label:string)=><SolarDate label={label} value={draft[k]||''} onChange={v=>update(k,v)}/>;
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/sales/network',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)}),d:any=await r.json();if(!r.ok)throw Error(d.error);setDraft(null);setMessage(d.followupPending?'ثبت شد؛ کارتابل در اجرای بعدی زمان‌بند همگام می‌شود.':'ثبت شد.');await load();onChange();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!data)return <p role="status">{error||'در حال دریافت شبکه فروش…'}</p>;
 const agents=data.agents.filter((a:any)=>!selected||a.id===selected),roles=data.roles,ps=data.portfolio.filter((p:any)=>agents.some((a:any)=>a.id===p.agentId&&a.data.active));
 return <section><h3>{roles.agent?'پرونده همکاری من':'نمایندگان و عاملین من'}</h3><p>{data.help}</p>{message&&<p role="status">{message}</p>}{error&&!draft&&<p role="alert">{error}</p>}
 <IconActions scope="sales-network-panel-actions-e936035070">{roles.manager&&<button className="btn" onClick={()=>begin('template')}>تعریف نسخه جدید الگوی فروش</button>}<button className="btn" onClick={()=>void load().catch(e=>setError(e.message))}>تازه‌سازی گزارش</button></IconActions>
 <p>شریک فعال: {ps.length} · نیازمند تماس: {ps.filter((p:any)=>p.contactLate).length} · خرید مجدد عقب‌افتاده: {ps.filter((p:any)=>p.inactive&&agents.find((a:any)=>a.id===p.agentId)?.data.kind!=='referrer').length} · پوشش پیگیری به‌موقع: {ps.length?Math.round(ps.filter((p:any)=>p.lastContact&&!p.contactLate).length*100/ps.length):0}٪</p>
 <IconDisclosure scope="sales-network-panel-details-70f5009426" title={<> الگوهای عمومی و نسخه‌ها </>}>{[...data.templates].reverse().map((r:any)=><p key={r.id}>{partnerKinds[r.data.kind]} · نسخه {r.data.version} · {r.data.title} · نقد {r.data.cashBps/100}٪ · باقیمانده {r.data.months} ماه شمسی</p>)}</IconDisclosure>
 {agents.map((a:any)=>{const p=data.portfolio.find((p:any)=>p.agentId===a.id),ac=p.account,records=data.records.filter((r:any)=>r.data.agentId===a.id);return <article className="notice" key={a.id}><h3>{a.data.name} · {partnerKinds[a.data.kind||'representative']}</h3>
 <p>آخرین خرید: {p.lastPurchase?formatDate(p.lastPurchase):'هنوز خرید ندارد'} · آخرین تماس: {p.lastContact?formatDate(p.lastContact):'ثبت نشده'} · تماس بعدی: {formatDate(p.nextContact)}</p>
 {a.data.active&&<p role="status">{p.contactLate?'⚠ موعد تماس رسیده است. ':''}{p.inactive&&a.data.kind!=='referrer'?'⚠ موعد خرید مجدد گذشته است. ':''}{BigInt(ac.overdue)>0?'⚠ بدهی سررسیدگذشته دارد.':''}</p>}
 <IconActions scope="sales-network-panel-actions-b1cbeaed81">{roles.manager&&<button className="btn" onClick={()=>begin('partner',a)}>تنظیم همکاری</button>}{roles.staff&&<button className="btn" onClick={()=>begin('contact',a)}>تماس / بازدید</button>}{(roles.staff||roles.agent||roles.finance)&&<button className="btn" onClick={()=>{begin('case',a);setDraft((d:any)=>({...d,kind:'support'}))}}>درخواست همکاری</button>}{roles.manager&&a.data.kind==='referrer'&&<button className="btn" onClick={()=>begin('contract',a)}>قرارداد پورسانت</button>}</IconActions>
 {a.data.kind==='referrer'?<><p>پورسانت وصول‌شده: {cash(p.commission.earned)} · پرداخت‌شده: {cash(p.commission.paid)} · در انتظار تسویه: {cash(p.commission.reserved)} · قابل درخواست: {cash(p.commission.available)}</p>{BigInt(p.commission.available)<0&&<p role="alert">به علت برگشت فروش یا وصول، مانده پورسانت نیاز به تعدیل دارد؛ پرداخت جدید متوقف است.</p>}{(roles.staff||roles.finance||roles.agent)&&<button className="btn" onClick={()=>begin('commission_settlement',a)}>درخواست تسویه</button>}<div className="sales-table"><table><caption>پورسانت فروش‌های معرفی‌شده</caption><thead><tr><th>فاکتور</th><th>وصول خالص</th><th>نرخ</th><th>پورسانت</th></tr></thead><tbody>{p.commission.invoices.map((i:any)=><tr key={i.invoiceId}><td>{i.reference}</td><td>{cash(i.collected)}</td><td>{i.bps/100}٪</td><td>{cash(i.earned)}</td></tr>)}</tbody></table></div></>:<><p>مانده کل خالص: <b>{cash(ac.balance)}</b> · بدهی فاکتورها: {cash(ac.debt)} · وجه تخصیص‌نیافته: {cash(ac.credit)} · معوق: {cash(ac.overdue)}</p><div className="sales-table"><table><caption>تسویه هر خرید و زمان باقیمانده</caption><thead><tr><th>خرید</th><th>مانده</th><th>وضعیت تسویه</th><th>سررسید اقساط باز</th></tr></thead><tbody>{ac.invoices.map((i:any)=>{const paid=BigInt(i.data.amount)-BigInt(i.remaining),pct=Number(paid*BigInt(10000)/BigInt(i.data.amount))/100;return <tr key={i.id}><td>{i.data.reference}<br/>{formatDate(i.data.day)}</td><td>{cash(i.remaining)}</td><td><progress aria-label={'تسویه '+i.data.reference} max="100" value={pct}/><br/>{pct}٪</td><td>{i.installments.filter((v:any)=>BigInt(v.remaining)>0).map((v:any)=><p key={v.id}>{cash(v.remaining)} · {formatDate(v.due)} · {v.days<0?(-v.days)+' روز تأخیر':v.days+' روز باقی‌مانده'}</p>)}</td></tr>})}</tbody></table></div><h4>سن بدهی</h4>{ac.aging.map((v:any)=><p key={v.label}>{v.label} <meter aria-label={v.label} min="0" max="100" value={BigInt(ac.debt)>0?Number(BigInt(v.amount)*BigInt(100)/BigInt(ac.debt)):0}/> {cash(v.amount)}</p>)}</>}
 {ac.payments.some((p:any)=>p.data.state==='bounced')&&<div className="notice"><h4>چک‌های برگشتی (جزء مانده خرید، بدون جمع دوباره)</h4>{ac.payments.filter((p:any)=>p.data.state==='bounced').map((p:any)=><p key={p.id}>{p.data.reference} · مبلغ چک {cash(p.data.amount)}{!p.data.checkInvoiceId&&!ac.allocations.some((l:any)=>l.data.creditId===p.id)&&<><span> · ارتباط خرید مشخص نیست؛ اولویت وجه نقد خرید جدید متوقف است. </span>{roles.finance&&<button className="btn" onClick={()=>begin('check_link',a,p)}>اتصال به خرید</button>}</>}</p>)}</div>}
 <IconDisclosure scope="sales-network-panel-details-14dbdf3fdf" title={<> سوابق تماس، همکاری، قرارداد و تسویه ({records.length}) </>}>{[...records].reverse().map((r:any)=><div key={r.id}><h4>{r.data.title||r.data.reference||modes[r.type.replace('sales_','')]||({'sales_contact':'تماس / بازدید','sales_contract':'قرارداد پورسانت','sales_commission_settlement':'تسویه پورسانت'} as any)[r.type]}</h4><p>{r.data.notes} · {({pending:'در انتظار بررسی',approved:'تأییدشده',rejected:'ردشده',paid:'پرداخت‌شده',cancelled:'لغوشده',open:'باز',closed:'بسته'} as any)[r.data.state]||''}{r.data.nextDue?' · '+formatDate(r.data.nextDue)+' · '+r.data.nextAction:''}{r.data.amount?' · '+cash(r.data.amount):''}{r.type==='sales_contract'?' · '+r.data.bps/100+'٪ · '+formatDate(r.data.start)+' تا '+formatDate(r.data.end):''}</p>{roles.staff&&r.type==='sales_case'&&<button className="btn" onClick={()=>begin('case_update',a,r)}>پیگیری</button>}{roles.finance&&r.type==='sales_contract'&&r.data.state==='pending'&&<button className="btn" onClick={()=>begin('contract_review',a,r)}>بررسی</button>}{roles.finance&&r.type==='sales_commission_settlement'&&r.data.state==='pending'&&<button className="btn" onClick={()=>begin('commission_review',a,r)}>بررسی تسویه</button>}{roles.finance&&r.type==='sales_commission_settlement'&&['pending','approved'].includes(r.data.state)&&<button className="btn" onClick={()=>begin('commission_cancel',a,r)}>لغو با دلیل</button>}{roles.finance&&r.type==='sales_commission_settlement'&&r.data.state==='approved'&&<button className="btn" onClick={()=>begin('commission_pay',a,r)}>ثبت پرداخت</button>}<IconDisclosure scope="sales-network-panel-details-1df43f26ae" title={<> سابقه اقدامات </>}>{r.data.history?.map((h:any,i:number)=><p key={i}>{formatDate(h.at)} · {modes[h.mode]} · {h.notes}</p>)}</IconDisclosure></div>)}</IconDisclosure></article>})}
 {!agents.length&&<p>پرونده‌ای به شما تخصیص داده نشده است؛ مدیر فروش مسئول پرونده را تعیین کند.</p>}
 <Dialog open={!!draft} onOpenChange={o=>{if(!o&&!busy)setDraft(null)}}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogTitle>{draft?modes[draft.mode]:''}</DialogTitle><DialogDescription>مبالغ به ریال و مهلت‌ها به ماه تقویمی شمسی هستند. ثبت پرداخت، انتقال بانکی انجام نمی‌دهد.</DialogDescription>{draft&&<form onSubmit={save}><fieldset disabled={busy}><div className="formgrid">
 {draft.mode==='template'&&<>{pick('kind','الگو برای',{representative:partnerKinds.representative,reseller:partnerKinds.reseller})}{field('title','عنوان')}{percent('cashBps','سهم نقد، درصد')}{field('months','مهلت باقیمانده، ماه شمسی','number',12)}</>}
 {draft.mode==='partner'&&<>{pick('kind','نوع همکاری',partnerKinds)}{pick('ownerId','کارشناس مسئول',Object.fromEntries(members.filter(m=>m.sales).map(m=>[m.id,m.name])))}{field('contactDays','فاصله تماس، روز','number',365)}{field('reorderDays','فاصله خرید مجدد، روز','number',365)}</>}
 {draft.mode==='contact'&&<>{pick('channel','روش ارتباط',{call:'تماس',visit:'بازدید',meeting:'جلسه',message:'پیام'})}{date('day','تاریخ واقعی ارتباط')}</>}
 {draft.mode==='case'&&<>{pick('kind','موضوع',{training:'آموزش',marketing:'بازاریابی',support:'پشتیبانی',complaint:'شکایت',development:'توسعه همکاری'})}{field('title','عنوان درخواست')}</>}
 {draft.mode==='case_update'&&pick('state','وضعیت',{open:'باز',closed:'بسته با نتیجه'})}
 {(['contact','case'].includes(draft.mode)||draft.mode==='case_update'&&draft.state==='open')&&<>{field('nextAction','اقدام بعدی')}{date('nextDue','موعد پیگیری')}</>}
 {draft.mode==='contract'&&<>{field('reference','مرجع قرارداد')}{percent('bps','نرخ پورسانت، درصد')}{date('start','شروع قرارداد')}{date('end','پایان قرارداد')}</>}
 {draft.mode==='check_link'&&pick('invoiceId','فاکتور مرتبط',Object.fromEntries((data.portfolio.find((p:any)=>p.agentId===draft.agentId)?.account.invoices||[]).map((i:any)=>[i.id,i.data.reference])))}
 {draft.mode==='commission_settlement'&&field('amount','مبلغ تسویه، ریال')}
 {draft.mode.endsWith('_review')&&<label className="field">نتیجه<select value={String(draft.approved)} onChange={e=>update('approved',e.target.value==='true')}><option value="true">تأیید</option><option value="false">رد با دلیل</option></select></label>}
 {draft.mode==='commission_pay'&&<>{field('reference','مرجع واقعی پرداخت')}{date('day','تاریخ پرداخت')}</>}
 {field('notes','شرح، نتیجه یا مستند تصمیم (در پرونده شریک قابل مشاهده است)')}</div>{error&&<p role="alert">{error}</p>}<button className="btn primary" disabled={busy}>{busy?'در حال ثبت…':'تأیید و ثبت'}</button></fieldset></form>}</DialogContent></Dialog></section>;
}
