"use client";
import {formatDate} from '@/lib/persian-date';
import {SolarDate} from './solar-date';
import {useEffect,useRef,useState} from "react";
import {Printer,RefreshCw,Plus} from "lucide-react";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from "@/components/ui/table";
import type {Row} from "@/lib/model";
import {tehranDay,serialPrefix,type SerialRun,type ReservedSerial} from "@/lib/serials";
export function SerialsPanel({records,demo,write,productRead,onRegister,onOpen}:{records:Row[];demo:boolean;write:boolean;productRead:boolean;onRegister:(data:Record<string,string>)=>void;onOpen:(row:Row)=>void}){
 const [product,setProduct]=useState(""),[count,setCount]=useState("10"),[day,setDay]=useState(tehranDay),[runs,setRuns]=useState<SerialRun[]>([]),[selected,setSelected]=useState<SerialRun|null>(null),[serials,setSerials]=useState<ReservedSerial[]>([]),[layout,setLayout]=useState("a4"),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[detailLoading,setDetailLoading]=useState(false),[error,setError]=useState("");
 const request=useRef<{key:string;id:string}|null>(null),detailVersion=useRef(0),listVersion=useRef(0),inFlight=useRef(false);
 const products=records.filter(r=>r.kind==="product"&&r.data.status==="فعال"),chosen=products.find(r=>r.id===product);
 async function load(date=day){if(demo)return;const version=++listVersion.current;setLoading(true);setError("");try{const r=await fetch('/api/serials?day='+encodeURIComponent(date)),d=await r.json() as {error?:string;runs:SerialRun[];run:SerialRun;serials:ReservedSerial[]};if(!r.ok)throw new Error(d.error);if(version===listVersion.current)setRuns(d.runs);}catch(e){if(version===listVersion.current)setError(e instanceof Error?e.message:"دریافت انجام نشد.");}finally{if(version===listVersion.current)setLoading(false)}}
 useEffect(()=>{void load(day);return()=>{listVersion.current++}},[day,demo]);
 async function open(run:SerialRun){const version=++detailVersion.current;setSelected(run);setSerials([]);setDetailLoading(true);setError("");try{const r=await fetch('/api/serials?id='+encodeURIComponent(run.id)),d=await r.json() as {error?:string;runs:SerialRun[];run:SerialRun;serials:ReservedSerial[]};if(!r.ok)throw new Error(d.error);if(version===detailVersion.current){setSelected(d.run);setSerials(d.serials)}}catch(e){if(version===detailVersion.current)setError(e instanceof Error?e.message:"دریافت انجام نشد.");}finally{if(version===detailVersion.current)setDetailLoading(false)}}
 async function generate(e:React.FormEvent){e.preventDefault();if(inFlight.current||demo)return;inFlight.current=true;setBusy(true);setError("");const quantity=Number(count),key=JSON.stringify([product,quantity]);if(request.current?.key!==key)request.current={key,id:crypto.randomUUID()};try{const r=await fetch('/api/serials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:request.current.id,productId:product,count:quantity})}),d=await r.json() as {error?:string;runs:SerialRun[];run:SerialRun;serials:ReservedSerial[]};if(!r.ok)throw new Error(d.error);request.current=null;setDay(d.run.day);await load(d.run.day);await open(d.run);}catch(e){setError(e instanceof Error?e.message:"پاسخ دریافت نشد؛ دوباره تلاش کنید.");}finally{inFlight.current=false;setBusy(false)}}
 const printUrl=selected?'/api/serials/print?id='+encodeURIComponent(selected.id)+'&layout='+layout:'';
 return <section className="serial-workspace"><div className="serial-flow" aria-label="مراحل آماده‌سازی"><span><b>۱</b> انتخاب محصول و تعداد</span><span><b>۲</b> رزرو سریال‌های یکتا</span><span><b>۳</b> چاپ برچسب</span></div><div className="panel serial-create"><div className="panelhead"><div><h2>سریال‌های جدید</h2><p className="subtle">محصول را انتخاب کنید؛ سریال‌ها رزرو و برای چاپ آماده می‌شوند.</p></div></div><div className="inside serial-create-content"><div>
 {demo?<p className="notice">برای تولید و چاپ سریال واقعی، از بالای صفحه «شروع ثبت اطلاعات شرکت» را بزنید.</p>:write?<form onSubmit={generate}><div className="formgrid"><label className="field">محصول<Select dir="rtl" value={product||"none"} onValueChange={v=>setProduct(v==="none"?"":v)} disabled={busy||!productRead}><SelectTrigger className="full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">انتخاب محصول</SelectItem>{products.map(p=><SelectItem value={p.id} key={p.id}>{p.data.code} · {p.data.name} · {p.data.model}</SelectItem>)}</SelectContent></Select></label><label className="field">تعداد سریال (۱ تا ۱۰۰)<input type="number" required min={1} max={100} step={1} value={count} disabled={busy} onChange={e=>setCount(e.target.value)}/></label></div><p className="subtle" style={{marginTop:12}}>الگو: کد محصول ـ تاریخ شمسی تخصیص ـ شماره ترتیب روز {chosen&&<bdi className="code">{serialPrefix(chosen.data.code,tehranDay())}0001</bdi>} · شماره ترتیب از آخرین سریال ادامه پیدا می‌کند.</p>{!productRead?<p className="notice">مدیر باید دسترسی مشاهده محصولات را به حساب شما بدهد.</p>:!products.length&&<p className="notice">ابتدا یک محصول فعال در «تعریف محصولات» ثبت کنید.</p>}<button className="btn primary" type="submit" disabled={busy||!chosen||!productRead} style={{marginTop:16}}><Plus size={16}/>{busy?"در حال رزرو سریال‌ها…":"تولید و رزرو سریال‌ها"}</button></form>:<p>دسترسی شما فقط مشاهده و چاپ سریال‌های موجود است.</p>}
 </div><aside className="serial-label-preview"><div className="preview-heading"><Printer size={17}/><span>پیش‌نمایش قالب برچسب</span></div><div className="label-example"><img src="/brand/nafasyar-logo.png" alt="نفس‌یار"/><strong>{chosen?.data.name||"نام محصول"}</strong><span>{chosen?.data.model||"مدل دستگاه"}</span><bdi className="label-serial">{chosen?serialPrefix(chosen.data.code,tehranDay())+"…":"PRODUCT-YYYYMMDD-0001"}</bdi><small>با من نفس بکش</small></div><p className="subtle">شماره نهایی بعد از رزرو مشخص می‌شود.</p></aside></div><p className="footnote">تخصیص سریال، تاریخ تولید یا شروع گارانتی نیست. بعداً از کنار هر سریال، شناسنامه دستگاه را تکمیل کنید.</p></div>
 {error&&<p className="notice error" role="alert">{error}</p>}
 {!demo&&<div className="panel" style={{marginTop:18}}><div className="panelhead"><h2>سوابق و چاپ مجدد</h2><div className="tools"><SolarDate label="روز تخصیص سریال" value={day} disabled={busy} onChange={setDay}/><button className="btn" disabled={loading||busy} onClick={()=>load()}><RefreshCw size={16}/>تازه‌سازی</button></div></div>{loading?<p className="inside" role="status">در حال دریافت…</p>:runs.length?<Table><TableHeader><TableRow>{["محصول","تعداد","ثبت‌کننده","زمان",""].map(h=><TableHead className="tablehead" key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{runs.map(run=><TableRow key={run.id}><TableCell className="tablecell">{run.data.name}<p className="subtle">{run.data.code} · {run.data.model}</p></TableCell><TableCell className="tablecell">{run.data.count}</TableCell><TableCell className="tablecell">{run.data.operator}</TableCell><TableCell className="tablecell">{new Date(run.created).toLocaleTimeString('fa-IR',{timeZone:'Asia/Tehran',hour:'2-digit',minute:'2-digit'})}</TableCell><TableCell className="tablecell"><button className="link" disabled={busy} onClick={()=>open(run)}>سریال‌ها و چاپ</button></TableCell></TableRow>)}</TableBody></Table>:<p className="empty">در این روز سریالی تخصیص داده نشده است.</p>}{runs.length===200&&<p className="footnote">۲۰۰ نوبت اخیر این روز نمایش داده می‌شود.</p>}</div>}
 {selected&&<div className="panel" style={{marginTop:18}}><div className="panelhead"><div><h2>{selected.data.name} · {selected.data.count} سریال</h2><p className="subtle">تخصیص {formatDate(selected.day)} · {selected.data.operator}</p></div><div className="tools"><Select dir="rtl" value={layout} onValueChange={setLayout}><SelectTrigger aria-label="قالب چاپ"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="a4">A4 · برچسب ۶۲ × ۳۰</SelectItem><SelectItem value="thermal">برچسب تکی ۶۰ × ۳۰</SelectItem></SelectContent></Select>{!detailLoading&&serials.length>0&&<a className="btn primary" href={printUrl} target="_blank" rel="noopener noreferrer"><Printer size={16}/>باز کردن صفحه چاپ</a>}</div></div>{detailLoading?<p className="inside" role="status">در حال دریافت سریال‌ها…</p>:<Table><TableHeader><TableRow><TableHead className="tablehead">سریال رزروشده</TableHead><TableHead className="tablehead">شناسنامه</TableHead></TableRow></TableHeader><TableBody>{serials.map(s=>{const device=records.find(r=>r.id===s.deviceId)||records.find(r=>r.kind==="device"&&r.data.code===s.serial);return <TableRow key={s.serial}><TableCell className="tablecell"><bdi className="code">{s.serial}</bdi></TableCell><TableCell className="tablecell">{device?<button className="link" onClick={()=>onOpen(device)}>مشاهده شناسنامه</button>:s.deviceId?<span>ثبت‌شده · صفحه را تازه کنید</span>:write?<button className="link" onClick={()=>onRegister({code:s.serial,product:selected.productId,model:records.find(r=>r.id===selected.productId)?.data.model||selected.data.model})}>تکمیل شناسنامه</button>:"در انتظار ثبت دستگاه"}</TableCell></TableRow>})}</TableBody></Table>}</div>}
 </section>;
}
