'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export function ServiceAgentAccounts({domain,agents,accountId}:{domain:string;agents:any[];accountId:string}){
 const [accounts,setAccounts]=useState<any[]>([]),[draft,setDraft]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const lock=useRef(false);
 async function refresh(){const r=await fetch('/api/after-sales/agent-accounts?domain='+domain,{cache:'no-store'}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setAccounts(d.accounts)}
 useEffect(()=>{let live=true;fetch('/api/after-sales/agent-accounts?domain='+domain,{cache:'no-store'}).then(async r=>{const d=await r.json() as any;if(!r.ok)throw Error(d.error);if(live)setAccounts(d.accounts)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[domain]);
 async function submit(e:React.FormEvent){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const r=await fetch('/api/after-sales/agent-accounts',{method:'POST',headers:{'Content-Type':'application/json','x-assistant-account':accountId},body:JSON.stringify({...draft,domain,confirmed:true})}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setDraft(null);setMessage('حساب '+d.username+' ساخته شد. نام کاربری و رمزی را که تعیین کردید از مسیر امن به نماینده تحویل دهید.');await refresh()}catch(e){setError((e as Error).message)}finally{lock.current=false;setBusy(false)}}
 return <section className="panel"><h3>حساب ورود نمایندگان</h3><p className="subtle">پس از «تعریف نماینده»، برای نمایندگی فعال نام کاربری و رمز تعیین کنید. این حساب فقط به اطلاعات همان نمایندگی دسترسی دارد؛ مدیریت حساب‌های دیگر در اختیار مدیر سامانه است.</p>{message&&<p role="status" className="notice">{message}</p>}{!draft&&error&&<p role="alert" className="notice error">{error}</p>}<button className="btn primary" disabled={!agents.some(a=>a.data.active)} onClick={()=>{setError('');setMessage('');setDraft({id:crypto.randomUUID(),agentId:'',revision:0,name:'',username:'',password:''})}}>ساخت حساب نماینده</button><div className="as-table"><table><thead><tr><th>نمایندگی</th><th>نام</th><th>نام کاربری</th><th>وضعیت</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td>{agents.find(g=>g.id===a.agentId)?.data.name||'—'}</td><td>{a.name}</td><td dir="ltr">{a.username}</td><td>{a.status==='active'?'فعال':'غیرفعال'}</td></tr>)}</tbody></table></div>
 <Dialog open={!!draft} onOpenChange={open=>{if(!open&&!busy){setDraft(null);setError('')}}}><DialogContent dir="rtl"><DialogTitle>ساخت حساب نماینده خدمات</DialogTitle><DialogDescription>رمز حداقل ۱۰ کاراکتر است؛ آن را در گفتگو با دستیار وارد نکنید. ثبت این فرم حساب فعال ایجاد می‌کند.</DialogDescription>{draft&&<form onSubmit={submit}><fieldset disabled={busy} className="formgrid"><label className="field">نمایندگی<select required value={draft.agentId} onChange={e=>{const a=agents.find(a=>a.id===e.target.value);setDraft({...draft,agentId:e.target.value,revision:a?.revision||0,name:a?.data.name||''})}}><option value="">انتخاب کنید</option>{agents.filter(a=>a.data.active).map(a=><option key={a.id} value={a.id}>{a.data.name}</option>)}</select></label><label className="field">نام صاحب حساب<input required maxLength={100} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="field">نام کاربری (حروف انگلیسی و عدد)<input required dir="ltr" autoComplete="off" minLength={3} maxLength={40} pattern="[a-zA-Z0-9][a-zA-Z0-9._\-]{2,39}" value={draft.username} onChange={e=>setDraft({...draft,username:e.target.value})}/></label><label className="field">رمز عبور<input required dir="ltr" type="password" autoComplete="new-password" minLength={10} maxLength={128} value={draft.password} onChange={e=>setDraft({...draft,password:e.target.value})}/></label></fieldset>{error&&<p role="alert" className="notice error">{error}</p>}<button className="btn primary" disabled={busy}>{busy?'در حال ثبت…':'تأیید و ساخت حساب'}</button></form>}</DialogContent></Dialog></section>
}
