'use client';
import {SupplierPanel} from './supplier-panel';
import {ReplenishmentPanel} from './replenishment-panel';
import {formatDate,formatDateTime} from '@/lib/persian-date';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {SolarDate} from './solar-date';
import {tehranDay} from '@/lib/serials';
import {supplyRoles,supplyStates} from '@/lib/sourcing-labels';
const fa=(n:number)=>n.toLocaleString('fa-IR');const qty=(n:number)=>fa(n/1000);const date=(s:string)=>s?formatDate(s):'—';
const money=(s:string)=>s===undefined?'—':BigInt(s).toLocaleString('fa-IR')+' ریال';
const routeName=(r:string)=>r==='domestic'?'داخلی':'خارجی';
const orderNames:Record<string,string>={awaiting_funding:'منتظر تأمین مالی',issued:'دستور خرید صادرشده',paid:'گزارش پرداخت',preparing:'آماده‌سازی',shipped:'حمل',closed:'پذیرفته و بسته‌شده',cancelled:'لغوشده'};
const actionNames:Record<string,string>={financial_review:'کنترل مالی پیشنهاد',refresh_suppliers:'شروع دور تازه استعلام',stock_confirm:'تأیید کسری و مقدار تأمین',stock_reject:'رد نیاز با ثبت علت',finish_replenishment:'پایان تأمین و آزادسازی موجودی',create:'درخواست تولید',approve:'تأیید برنامه تولید',reject:'رد درخواست',bom:'تثبیت نسخه BOM',finance:'برنامه مالی',calculate:'کنترل و تخصیص موجودی',routes:'مسیرهای مجاز تأمین',quote:'ثبت استعلام',technical:'بررسی فنی پیشنهاد',award:'انتخاب مسیر تأمین',issue_order:'صدور دستور خرید',track:'گزارش مرحله سفارش',receive:'دریافت کالا در قرنطینه',close_order:'بستن سفارش پذیرفته‌شده',cancel_order:'لغو انتخاب یا سفارش',ready:'اعلام آمادگی مواد',release:'تحویل برنامه به تولید',cancel:'لغو برنامه',followup:'ثبت پیگیری / بازسازی کارتابل'};
function Pick({label,value,items,onChange}:{label:string;value:string;items:[string,string][];onChange:(v:string)=>void}){return <label className="field">{label}<Select dir="rtl" value={value||'none'} onValueChange={v=>onChange(v==='none'?'':v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">انتخاب کنید</SelectItem>{items.map(([id,title])=><SelectItem value={id} key={id}>{title}</SelectItem>)}</SelectContent></Select></label>}
export function SourcingPanel({demo,onNavigate,targetId=''}:{targetId?:string;demo:boolean;onNavigate:(s:string)=>void}){
 const [suppliersOpen,setSuppliersOpen]=useState(false);
 const [catalog,setCatalog]=useState<any>(null),[detail,setDetail]=useState<any>(null),[selected,setSelected]=useState(''),[draft,setDraft]=useState<any>(null),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function read(id=''){const r=await fetch('/api/sourcing'+(id?'?id='+encodeURIComponent(id):''),{cache:'no-store'});const d=await r.json() as any;if(!r.ok)throw new Error(d.error);return d;}
 async function refresh(id=selected){try{setError('');setCatalog(await read());if(id)setDetail(await read(id));}catch(e){setError((e as Error).message)}}
 useEffect(()=>{if(!demo){setSelected(targetId);void refresh(targetId)}},[demo,targetId]);
 async function open(id:string){setSelected(id);setDetail(null);try{setDetail(await read(id))}catch(e){setError((e as Error).message)}}
 const roles=catalog?.roles||[],can=(r:string)=>roles.includes(r),plan=detail?.plan,lines=detail?.lines||[],orders=detail?.orders||[],quotes=detail?.quotes||[];
 const change=(key:string,value:any)=>setDraft((d:any)=>({...d,[key]:value}));
 function start(mode:string,extra:any={}){setError('');setMessage('');setDraft({id:crypto.randomUUID(),mode,planId:plan?.id,revision:plan?.revision,notes:'',reference:'',count:plan?.data.count||1,needBy:plan?.data.needBy||tehranDay(),origin:'forecast',forecastId:'',productId:'',bomId:'',routes:[],status:'planned',budgetRial:'0',availableOn:tehranDay(),route:'domestic',unavailable:false,supplier:'',unitPrice:'',currency:'IRR',fxRate:'1',fxDate:tehranDay(),fxSource:'',extrasRial:'0',costNotes:'',paymentTerms:'',specs:'',eta:plan?.data.needBy||tehranDay(),validUntil:tehranDay(),result:'pass',stage:'update',day:tehranDay(),quantity:plan?.data.stockSnapshot?String(plan.data.stockSnapshot.proposed/1000):'',manufacturerLot:'',expiry:'',reason:'',...extra});}
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/sourcing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)}),d=await r.json() as any;if(!r.ok)throw new Error(d.error);setDraft(null);setMessage('ثبت شد.');const next=d.planId||selected;setSelected(next);await refresh(next);window.dispatchEvent(new Event('nafasyar-tasks-changed'));}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const input=(key:string,label:string,opts:{type?:string;required?:boolean;wide?:boolean}={})=><label className={'field '+(opts.wide?'wide':'')} key={key}>{label}<input type={opts.type||'text'} required={opts.required!==false} value={draft[key]??''} onChange={e=>change(key,e.target.value)}/></label>;
 const textarea=(key:string,label:string)=><label className="field wide" key={key}>{label}<textarea required rows={3} value={draft[key]||''} onChange={e=>change(key,e.target.value)}/></label>;
 if(demo)return <p className="notice">برنامه تولید و تأمین در اطلاعات واقعی شرکت در دسترس است.</p>;
 return <section className="panel"><div className="panelhead"><div><h2>برنامه تولید و تأمین</h2><p className="subtle">درخواست فروش، مواد، استعلام موازی و خرید مسیر منتخب</p></div><div className="tools"><button className="btn" onClick={()=>setSuppliersOpen(!suppliersOpen)}>تأمین‌کنندگان</button>{can('sales')&&<button className="btn primary" onClick={()=>start('create')}>درخواست تولید</button>}<button className="btn" disabled={busy} onClick={()=>void refresh()}>تازه‌سازی</button></div></div><div className="inside">{suppliersOpen&&<SupplierPanel/>}{!selected&&<ReplenishmentPanel onOpen={id=>void open(id)}/>}
 {error&&!draft&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice">{message}</p>}
 {!selected&&<><label className="field">جست‌وجوی محصول یا مرجع درخواست<input value={search} onChange={e=>setSearch(e.target.value)}/></label>{catalog?.plans.length===0&&<p className="empty">اولین درخواست تولید را از پیش‌بینی فروش یا سفارش مشتری ثبت کنید.</p>}{catalog?.plans.filter((p:any)=>(p.productName+' '+p.reference).includes(search)).map((p:any)=><article className="flow-card" key={p.id}><h3>{p.productName}{p.origin!=='replenishment'&&<> · {fa(p.count)} دستگاه</>}</h3><p>{supplyStates[p.state]} · نیاز تا {date(p.needBy)} · {p.origin==='replenishment'?'تأمین کسری موجودی':p.origin==='forecast'?'پیش‌بینی فروش':'سفارش مشتری'}</p><p>{p.reference}</p><button className="btn primary" onClick={()=>void open(p.id)}>باز کردن پرونده</button></article>)}</>}
 {selected&&<><button className="btn" onClick={()=>{setSelected('');setDetail(null)}}>فهرست برنامه‌ها</button>{!detail&&<p>در حال دریافت…</p>}{plan&&<>
 <div className="sourcing-summary"><h3>{plan.data.productName}{plan.data.origin!=='replenishment'&&<> · {fa(plan.data.count)} دستگاه</>}</h3><p>{supplyStates[plan.data.state]} · موعد {date(plan.data.needBy)} · مرجع: {plan.data.reference}</p><p className="subtle">{plan.data.origin==='replenishment'?'پرونده حد سفارش کالا':<>BOM: {plan.data.bom?'نسخه '+fa(plan.data.bom.version):'تعیین نشده'}</>} · برنامه مالی: {({pending:'در انتظار بررسی',planned:'برآورد اولیه',approved:'تأییدشده'} as any)[plan.data.finance.status]}</p>{plan.data.finance.budgetRial!==undefined&&<p>بودجه: {money(plan.data.finance.budgetRial)} · تاریخ وجه: {date(plan.data.finance.availableOn)}</p>}{plan.data.customerAllocations?.length>0&&<details><summary>سفارش‌های مشتری مرتبط با پیش‌بینی</summary>{plan.data.customerAllocations.map((a:any,i:number)=><p key={i}>{a.reference} · {fa(a.count)} دستگاه · {date(a.needBy)}</p>)}</details>}</div>
 {plan.data.origin==='replenishment'&&<div className="notice"><p>این پرونده از حد سفارش کالا شروع شده و به ساخت محصول وابسته نیست. موجودی پیشنهادی هنگام تأیید دوباره محاسبه می‌شود.</p>{plan.data.stockSnapshot&&<p>موجودی آزاد هنگام بررسی: {qty(plan.data.stockSnapshot.free)} · پیشنهاد: {qty(plan.data.stockSnapshot.proposed)}</p>}{plan.data.stockNote&&<p>نتیجه بررسی: {plan.data.stockNote}</p>}{plan.data.state==='stock_rejected'&&<p>این نیاز تا تغییر موجودی دوباره ساخته نمی‌شود. مغایرت واقعی را از مسیر مجاز موجودی بررسی کنید.</p>}{can('inventory')&&plan.data.state==='stock_check'&&<div className="tools"><button className="btn primary" onClick={()=>start('stock_confirm')}>تأیید مقدار و ارسال برای استعلام</button><button className="btn" onClick={()=>start('stock_reject')}>نیاز تأیید نشد</button></div>}{can('engineering')&&plan.data.state==='stock_check'&&<button className="btn" onClick={()=>{const m=catalog.materials.find((m:any)=>m.id===plan.data.materialId);start('routes',{materialId:m.id,revision:m.revision,routes:m.routes})}}>تعیین مسیرهای مجاز استعلام</button>}{can('inventory')&&plan.data.state==='sourcing'&&<button className="btn" onClick={()=>start('finish_replenishment')}>پایان تأمین پس از پذیرش کامل</button>}</div>}
 <div className="tools">{plan.data.state==='pending'&&can('ceo')&&<><button className="btn primary" onClick={()=>start('approve')}>تأیید / اصلاح تعداد و موعد</button><button className="btn" onClick={()=>start('reject')}>رد درخواست</button></>}{plan.data.state==='waiting_bom'&&can('engineering')&&<><button className="btn primary" onClick={()=>start('bom')}>معرفی BOM</button><button className="btn" onClick={()=>onNavigate('product')}>تعریف BOM در محصولات</button></>}{!['stock_check','stock_rejected','completed','pending','rejected','cancelled','released'].includes(plan.data.state)&&can('finance')&&<button className="btn" onClick={()=>start('finance',{...plan.data.finance})}>برنامه تأمین مالی</button>}{plan.data.origin!=='replenishment'&&['approved','sourcing','ready'].includes(plan.data.state)&&can('inventory')&&<button className="btn" onClick={()=>start('calculate')}>محاسبه و تخصیص مواد</button>}{can('ceo')&&!['completed','released','rejected','cancelled'].includes(plan.data.state)&&<button className="btn" onClick={()=>start('cancel')}>لغو برنامه</button>}<button className="btn" onClick={()=>start('followup')}>ثبت پیگیری</button></div>
 {can('engineering')&&plan.data.state==='sourcing'&&<button className="btn" onClick={()=>start('refresh_suppliers')}>دور تازه استعلام و منابع</button>}
 {detail.work.length>0&&<div className="sourcing-work">{detail.work.map((w:any)=><div className="notice" key={w.key}><strong>{w.title}</strong>{w.instructions&&<p style={{whiteSpace:'pre-wrap'}}>{w.instructions}</p>}<p>{supplyRoles[w.role]} · {w.mine?'در کارتابل شما':'در انتظار واحد مربوط'}</p>{!w.assignedCount&&<p>هنوز کاربری با دسترسی این مرحله تعیین نشده؛ مدیر در «کاربران و دسترسی‌ها» نقش را مشخص کند.</p>}</div>)}</div>}
 {lines.length>0&&<><h3>نیاز مواد و پوشش تا موعد</h3><p className="subtle">خرید باز فقط در صورت موعد معتبر محاسبه می‌شود. استعلام و انتخابِ منتظر وجه، موجودی آماده نیستند.</p><div style={{overflowX:'auto'}}><Table><TableHeader><TableRow>{['کالا / واحد','نیاز','موجود و تخصیص‌یافته','خرید باز تا موعد','کسری پوشش','مسیر استعلام','اقدام'].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{lines.map((l:any)=><TableRow key={l.partCode}><TableCell>{l.name}<br/>{l.partCode} · {l.unit}</TableCell><TableCell>{qty(l.required)}</TableCell><TableCell>{qty(l.stock)}</TableCell><TableCell>{qty(l.pipeline)}</TableCell><TableCell>{qty(l.shortage)}</TableCell><TableCell>{l.routes.map(routeName).join(' و ')||'تعیین نشده'}</TableCell><TableCell><div className="tools">{can('engineering')&&<button className="btn" onClick={()=>{const m=catalog.materials.find((m:any)=>m.id===l.materialId);start('routes',{materialId:m.id,revision:m.revision,routes:m.routes})}}>مسیر مجاز</button>}{l.shortage>0&&l.routes.filter((r:string)=>can(r)).map((r:string)=><button className="btn" key={r} onClick={()=>start('quote',{partCode:l.partCode,route:r,specs:l.specs})}>استعلام {routeName(r)}</button>)}</div></TableCell></TableRow>)}</TableBody></Table></div><p className="subtle">پس از تعیین مسیرهای ماده، محاسبه مواد را دوباره ثبت کنید تا دور جدید استعلام بر اساس آن باز شود.</p></>}
 {quotes.length>0&&<><h3>مقایسه پیشنهادها</h3><p className="notice">دو مسیر، یک نیاز: قیمت و هزینه جانبی به ریال محاسبه می‌شود. اعتبار، موعد، تأیید فنی و شرایط پرداخت در انتخاب لحاظ شوند. هر ردیف فقط یک انتخاب خرید فعال دارد.</p>{lines.map((l:any)=>{const qs=quotes.filter((q:any)=>q.data.partCode===l.partCode&&q.data.round===l.round);const eligible=qs.filter((q:any)=>!q.data.unavailable&&!q.data.supplierBlock&&(!q.data.supplierLinkId||q.data.financial==='pass')&&q.data.technical==='pass'&&q.data.validUntil>=tehranDay()&&q.data.eta<=plan.data.needBy&&q.data.quantity===l.shortage&&q.data.totalRial!==undefined).sort((a:any,b:any)=>BigInt(a.data.totalRial)<BigInt(b.data.totalRial)?-1:1);return qs.map((q:any)=><article className="flow-card" key={q.id}><h4>{l.name} · {routeName(q.data.route)} · {q.data.supplier||'بدون پیشنهاد'}</h4>{q.data.supplierBlock&&<p className="notice error">مانع خرید: {q.data.supplierBlock}</p>}{q.data.unavailable?<p>عدم امکان استعلام: {q.data.reason}</p>:<><p>{money(q.data.totalRial)} · تحویل {date(q.data.eta)} · فنی: {({pending:'در انتظار بررسی',pass:'تأیید',fail:'رد'} as any)[q.data.technical]}</p>{eligible[0]?.id===q.id&&<p className="notice">کمترین قیمت تمام‌شده در پیشنهادهای قابل مقایسه و به‌موقع</p>}<details><summary>مشخصات و شرایط پیشنهاد</summary>{q.data.totalRial!==undefined&&<><p>مقدار: {qty(q.data.quantity||0)} {q.data.unit} · قیمت واحد: {q.data.unitPrice} {q.data.currency}</p><p>نرخ تبدیل به ریال: {q.data.fxRate} · {date(q.data.fxDate)} · {q.data.fxSource}</p><p>هزینه جانبی: {money(q.data.extrasRial)} · {q.data.costNotes}</p><p>اعتبار تا: {date(q.data.validUntil)} · پرداخت: {q.data.paymentTerms}</p></>}<p>{q.data.specs}</p><p>مرجع: {q.data.reference} · بررسی فنی: {q.data.technicalNote}</p></details></>}<div className="tools">{can(q.data.route)&&<button className="btn" onClick={()=>start('quote',{...q.data,quoteId:q.id,quoteRevision:q.revision})}>ویرایش پیشنهاد</button>}{can('engineering')&&!q.data.unavailable&&<button className="btn" onClick={()=>start('technical',{quoteId:q.id,quoteRevision:q.revision})}>بررسی فنی</button>}{can('finance')&&q.data.supplierLinkId&&!q.data.unavailable&&<button className="btn" onClick={()=>start('financial_review',{quoteId:q.id,quoteRevision:q.revision})}>کنترل مالی · {q.data.financial==='pass'?'تأیید':q.data.financial==='fail'?'رد':'منتظر بررسی'}</button>}{can('ceo')&&!q.data.unavailable&&<button className="btn primary" onClick={()=>start('award',{quoteId:q.id,partCode:l.partCode})}>انتخاب این مسیر</button>}</div></article>)})}</>}
 {orders.length>0&&<><h3>دستورها و پیگیری خرید</h3>{orders.map((o:any)=><article className="flow-card" key={o.id}><h4>{o.data.supplier} · {routeName(o.data.route)} · {o.data.partCode}</h4><p>{orderNames[o.data.state]} · {qty(o.data.quantity)} {o.data.unit} · موعد {date(o.data.eta)}</p>{o.data.totalRial!==undefined&&<p>{money(o.data.totalRial)}</p>}<p className="subtle">مرجع سفارش: {o.id}</p><div className="tools">{o.data.state==='awaiting_funding'&&can('finance')&&<button className="btn primary" onClick={()=>start('issue_order',{orderId:o.id})}>تأیید وجه و صدور خرید</button>}{['issued','paid','preparing','shipped'].includes(o.data.state)&&<>{(can(o.data.route)||can('finance'))&&<button className="btn" onClick={()=>start('track',{orderId:o.id,eta:o.data.eta})}>گزارش مرحله</button>}{can('inventory')&&<><button className="btn" onClick={()=>start('receive',{orderId:o.id})}>دریافت در قرنطینه</button><button className="btn" onClick={()=>onNavigate('flow')}>کنترل کیفیت و جانمایی</button><button className="btn" onClick={()=>start('close_order',{orderId:o.id})}>بستن پس از پذیرش کامل</button></>}</>}{can('ceo')&&!['closed','cancelled'].includes(o.data.state)&&<button className="btn" onClick={()=>start('cancel_order',{orderId:o.id})}>لغو سفارش</button>}</div><details><summary>گزارش مراحل</summary>{o.data.history?.map((h:any,i:number)=><p key={i}>{h.stage} · {h.notes} · {h.reference} · موعد {date(h.eta)}</p>)}</details></article>)}</>}
 {detail.receipts?.length>0&&<details><summary>رسیدها و نتیجه پذیرش</summary>{detail.receipts.map((r:any)=><p key={r.id}>{r.batchId} · ورودی {qty(r.quantity)} · پذیرفته {qty(r.accepted)} · مردود {qty(r.rejected)} · {r.state==='stored'?'انتقال به مواد اولیه انجام شده':r.state}</p>)}</details>}
 {plan.data.origin!=='replenishment'&&lines.length>0&&can('inventory')&&['sourcing','ready'].includes(plan.data.state)&&<div className="tools"><button className="btn" onClick={()=>start('ready')}>اعلام آماده‌بودن مواد</button><button className="btn primary" onClick={()=>start('release')}>تحویل برنامه و آزادسازی برای تولید</button></div>}
 <details style={{marginTop:20}}><summary>سابقه پرونده</summary>{plan.data.history?.map((h:any,i:number)=><p key={i}>{h.name} · {actionNames[h.mode]||h.mode} · {h.notes} · {formatDateTime(h.at)}</p>)}</details>
 </>}</>}
 </div><Dialog open={!!draft} onOpenChange={v=>{if(!busy&&!v)setDraft(null)}}><DialogContent className="modal sm:max-w-3xl"><DialogTitle>{draft&&actionNames[draft.mode]}</DialogTitle><DialogDescription>ثبت این فرم همراه با نام شما در سابقه پرونده می‌ماند.</DialogDescription>{draft&&<form onSubmit={submit}><fieldset disabled={busy} style={{border:0,padding:0}}><div className="formgrid">
 {draft.mode==='create'&&<><Pick label="نوع درخواست" value={draft.origin} items={ [['forecast','پیش‌بینی و تارگت فروش'],['customer','سفارش مشتری']] } onChange={v=>change('origin',v)}/><Pick label="محصول" value={draft.productId} items={catalog.products.map((p:any)=>[p.id,p.name])} onChange={v=>change('productId',v)}/>{input('reference','مرجع پیش‌بینی یا سفارش مشتری')}{draft.origin==='customer'&&<Pick label="از محل پیش‌بینی قبلی (اختیاری)" value={draft.forecastId} items={catalog.plans.filter((p:any)=>p.origin==='forecast'&&p.productId===draft.productId&&!['cancelled','rejected','released'].includes(p.state)).map((p:any)=>[p.id,p.productName+' · '+p.reference])} onChange={v=>change('forecastId',v)}/>}</>}
 {['create','approve'].includes(draft.mode)&&<>{input('count','تعداد دستگاه',{type:'number'})}<SolarDate label="موعد نیاز" value={draft.needBy} onChange={v=>change('needBy',v)}/></>}
 {draft.mode==='stock_confirm'&&<>{input('quantity','مقدار مورد نیاز (واحد کالا)')}<SolarDate label="موعد نیاز" value={draft.needBy} onChange={v=>change('needBy',v)}/><p className="notice wide">تأیید نیاز، مجوز خرید نیست؛ ابتدا استعلام و انتخاب مسیر انجام می‌شود.</p></>}
 {draft.mode==='bom'&&<Pick label="نسخه BOM این محصول" value={draft.bomId} items={detail.boms.map((b:any)=>[b.id,'نسخه '+fa(b.version)])} onChange={v=>change('bomId',v)}/>}
 {draft.mode==='routes'&&<fieldset className="wide"><legend>مسیرهای مجاز استعلام این ماده</legend>{['domestic','foreign'].map(r=><label className="flow-check" key={r}><Checkbox checked={draft.routes.includes(r)} onCheckedChange={v=>change('routes',v?[...draft.routes,r]:draft.routes.filter((x:string)=>x!==r))}/>{routeName(r)}</label>)}<p>انتخاب هر دو یعنی استعلام موازی؛ پس از مقایسه، یک مسیر برای خرید انتخاب می‌شود.</p></fieldset>}
 {draft.mode==='finance'&&<><Pick label="وضعیت برنامه وجه" value={draft.status} items={ [['planned','برآورد / برنامه اولیه'],['approved','بودجه و تأمین وجه تأییدشده']] } onChange={v=>change('status',v)}/>{input('budgetRial','سقف بودجه همین پرونده، ریال')}<SolarDate label="تاریخ دسترسی به وجه" value={draft.availableOn} onChange={v=>change('availableOn',v)}/><p className="notice wide">ثبت برنامه مالی، انتقال بانکی نیست. پرداخت واقعی در خزانه انجام و مرجع آن گزارش می‌شود.</p></>}
 {draft.mode==='quote'&&<>{(plan.data.supplierTargets||[]).some((t:any)=>t.partCode===draft.partCode&&t.route===draft.route)&&<Pick label="تأمین‌کننده این استعلام" value={draft.supplierLinkId||''} items={(plan.data.supplierTargets||[]).filter((t:any)=>t.partCode===draft.partCode&&t.route===draft.route&&!t.missing).map((t:any)=>[t.linkId,t.name+' · '+t.phone])} onChange={v=>{const t=plan.data.supplierTargets.find((t:any)=>t.linkId===v);change('supplierLinkId',v);change('supplier',t?.name||'')}}/>}<p className="wide">استعلام {routeName(draft.route)}؛ مقدار و واحد از کسری همین نیاز محاسبه می‌شود.</p><label className="flow-check"><Checkbox checked={draft.unavailable} onCheckedChange={v=>change('unavailable',v===true)}/>در این مسیر پیشنهاد قابل ارائه نداریم</label>{draft.unavailable?textarea('reason','علت عدم امکان استعلام'):<>{input('supplier','نام تأمین‌کننده')}{input('unitPrice','قیمت واحد در ارز پیشنهاد')}<Pick label="ارز قیمت" value={draft.currency} items={ [['IRR','ریال'],['IRT','تومان'],['USD','دلار'],['CNY','یوان'],['EUR','یورو']] } onChange={v=>{change('currency',v);if(v==='IRR')change('fxRate','1');if(v==='IRT')change('fxRate','10');}}/>{input('fxRate','هر واحد ارز چند ریال؟')}<SolarDate label="تاریخ نرخ تبدیل" value={draft.fxDate} onChange={v=>change('fxDate',v)}/>{input('fxSource','منبع نرخ / مبنای محاسبه')}{input('extrasRial','جمع هزینه‌های جانبی همین مقدار، ریال')}{textarea('costNotes','تفکیک هزینه حمل، بیمه، گمرک و سایر هزینه‌های برآوردی')}<SolarDate label="موعد رسیدن به شرکت" value={draft.eta} onChange={v=>change('eta',v)}/><SolarDate label="اعتبار پیشنهاد تا" value={draft.validUntil} onChange={v=>change('validUntil',v)}/>{textarea('paymentTerms','شرایط پرداخت')}{textarea('specs','مشخصات فنی پیشنهادی')}{input('reference','شماره یا مرجع پیشنهاد / پیش‌فاکتور')}</>}</>}
 {['technical','financial_review'].includes(draft.mode)&&<Pick label="نتیجه تطبیق فنی" value={draft.result} items={ [['pass','تأیید'],['fail','رد']] } onChange={v=>change('result',v)}/>}
 {draft.mode==='refresh_suppliers'&&<p className="notice wide">منابع و مشخصات جاری کالا خوانده می‌شوند و دور تازه‌ای برای همه ردیف‌ها آغاز می‌شود. پاسخ‌های قبلی در سابقه می‌مانند و برای انتخاب خرید در این دور معتبر نیستند.</p>}{draft.mode==='award'&&<p className="notice wide">فقط این پیشنهاد انتخاب می‌شود؛ پس از تأیید وجه، دستور خرید همین مسیر صادر خواهد شد. اگر ارزان‌ترین پیشنهاد به‌موقع را انتخاب نمی‌کنید، علت را توضیح دهید.</p>}
 {['issue_order','release'].includes(draft.mode)&&input('reference',draft.mode==='release'?'مرجع تحویل برنامه به تولید':'مرجع تأیید وجه / بودجه')}
 {draft.mode==='track'&&<><Pick label="مرحله گزارش" value={draft.stage} items={ [['update','به‌روزرسانی / مانع'],...(can('finance')?[['paid','گزارش پرداخت']] as [string,string][]:[]),['preparing','آماده‌سازی'],['shipped','حمل']] } onChange={v=>change('stage',v)}/><SolarDate label="موعد دریافت به‌روز" value={draft.eta} onChange={v=>change('eta',v)}/>{input('reference','مرجع رسید، مکاتبه یا بارنامه')}</>}
 {draft.mode==='receive'&&<><SolarDate label="تاریخ دریافت" value={draft.day} onChange={v=>change('day',v)}/><p className="notice wide">مقدار کل سفارش: {qty(orders.find((o:any)=>o.id===draft.orderId)?.data.quantity||0)} {orders.find((o:any)=>o.id===draft.orderId)?.data.unit}؛ تعداد واقعی را انباردار شمارش می‌کند.</p>{input('invoiceQuantity','مقدار فاکتور این محموله')}{input('quantity','مقدار واقعی دریافت‌شده (واحد سفارش)')}{input('purchase','شماره فاکتور / مرجع محموله')}{input('discrepancyNotes','شرح مغایرت تعداد / تحویل جایگزین',{required:false})}<p className="notice wide">اختلاف دریافت با فاکتور: {draft.quantity&&draft.invoiceQuantity?qty(Math.round(Number(draft.quantity)*1000)-Math.round(Number(draft.invoiceQuantity)*1000)):'—'}؛ منفی یعنی کسری و مثبت یعنی اضافه‌دریافت.</p>{input('manufacturerLot','بچ سازنده (اختیاری)',{required:false})}<label className="flow-check"><Checkbox checked={!!draft.expiry} onCheckedChange={v=>change('expiry',v?tehranDay():'')}/>دارای تاریخ انقضا</label>{draft.expiry&&<SolarDate label="تاریخ انقضا" value={draft.expiry} onChange={v=>change('expiry',v)}/>}<p className="notice wide">بچ جدید در قرنطینه ایجاد می‌شود. نقش انبار در گردش مواد و دسترسی قرنطینه لازم است؛ QC و جانمایی از همان بخش انجام می‌شود.</p></>}
 {!['routes','quote'].includes(draft.mode)&&textarea('notes','نتیجه، توضیح تصمیم، مانع یا اقدام بعدی')}
 </div>{error&&<p className="notice error" role="alert">{error}</p>}<div className="tools" style={{marginTop:20}}><button className="btn primary" disabled={busy}>ثبت</button><button className="btn" type="button" onClick={()=>setDraft(null)}>بستن</button></div></fieldset></form>}</DialogContent></Dialog></section>;
}
