'use client';
import {useEffect,useState} from 'react';
import {supplierFields,supplierStates,supplierRisks} from '@/lib/supplier-contract';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {SolarDate} from './solar-date';
import {formatDate} from '@/lib/persian-date';
export function SupplierPanel({materialId=''}:{materialId?:string}){
 const [data,setData]=useState<any>(null),[material,setMaterial]=useState(materialId),[draft,setDraft]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('');
 async function load(){const r=await fetch('/api/suppliers',{cache:'no-store'}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setData(d);}
 useEffect(()=>{void load().catch(e=>setError(e.message))},[]);
 const begin=(mode:string,extra:any={})=>{setError('');setDraft({id:crypto.randomUUID(),confirmed:true,mode,route:'domestic',kind:'manufacturer',active:true,country:'ایران',materialId:material,status:'pending',qualityRisk:'high',supplyRisk:'high',reviewDue:'',scores:{},...extra});};
 const change=(k:string,v:any)=>setDraft((d:any)=>({...d,[k]:v}));
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/suppliers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setDraft(null);await load();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const field=(k:string,label:string,required=false)=><label className="field" key={k}>{label}<input required={required} value={draft?.[k]??''} onChange={e=>change(k,e.target.value)}/></label>;
 const pick=(k:string,label:string,items:Record<string,string>)=><label className="field">{label}<select required value={draft?.[k]||''} onChange={e=>change(k,e.target.value)}><option value="">انتخاب کنید</option>{Object.entries(items).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>;
 const pct=(n:number|null)=>n===null?'سابقه کافی ثبت نشده':n.toLocaleString('fa-IR')+'٪';
 return <section className="panel" dir="rtl"><div className="panelhead"><h2>تأمین‌کنندگان و ارزیابی</h2>{data?.canManage&&<button className="btn primary" onClick={()=>begin('supplier')}>تأمین‌کننده جدید</button>}</div><div className="inside">
 <p className="notice">صلاحیت خرید برای هر کالا جداست. امتیاز ارزیابی کارشناسی با سابقه واقعی پذیرش و تحویل نمایش داده می‌شود؛ امتیاز بالا جای تأیید صلاحیت را نمی‌گیرد.</p>
 {error&&!draft&&<p role="alert" className="notice error">{error}</p>}{!data&&<p>در حال دریافت…</p>}
 {data&&<><div className="formgrid"><label className="field">کالا<select value={material} onChange={e=>setMaterial(e.target.value)}><option value="">همه کالاها</option>{data.materials.map((m:any)=><option key={m.id} value={m.id}>{m.code} · {m.name}</option>)}</select></label><label className="field">جست‌وجوی تأمین‌کننده<input value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
 {data.canManage&&<button className="btn" onClick={()=>begin('link')}>اتصال تأمین‌کننده به کالا</button>}
 {data.suppliers.filter((s:any)=>(s.data.name+' '+s.data.phone).includes(search)&&(!material||data.links.some((l:any)=>l.data.materialId===material&&l.data.supplierId===s.id))).map((s:any)=><article key={s.id} className="flow-card"><h3>{s.data.name} · {s.data.route==='domestic'?'داخلی':'خارجی'}{!s.data.active?' · غیرفعال':''}</h3><p>{s.data.country} · {s.data.contact} · <bdi>{s.data.phone}</bdi> · <bdi>{s.data.email}</bdi></p><p>{s.data.kind==='manufacturer'?'سازنده':'واسطه / بازرگان'} · {s.data.manufacturer} · {s.data.factory}</p><p>{s.data.address} · {s.data.messenger}</p>{data.canManage&&<button className="btn" onClick={()=>begin('supplier',{...s.data,supplierId:s.id,revision:s.revision})}>ویرایش پرونده</button>}
 {data.links.filter((l:any)=>l.data.supplierId===s.id&&(!material||l.data.materialId===material)).map((l:any)=>{const m=data.materials.find((m:any)=>m.id===l.data.materialId),last=l.reviews.at(-1);return <div className="notice" key={l.id}><h4>{m?.name} · {l.data.partCode} · {supplierStates[l.data.status]}</h4><p>کد نزد تأمین‌کننده: {l.data.supplierCode||'—'} · بازبینی: {l.data.reviewDue?formatDate(l.data.reviewDue):'تعیین نشده'}</p><p>ریسک کیفیت: {supplierRisks[l.data.qualityRisk]} · ریسک تأمین: {supplierRisks[l.data.supplyRisk]}</p>{l.block&&<p role="status">مانع خرید: {l.block}</p>}{l.data.status==='conditional'&&<p>سقف هر سفارش: {l.data.maxQuantity/1000} {l.data.unit} · {l.data.restrictions}</p>}<p>پذیرش کیفی: {pct(l.metrics.quality)} · تحویل به‌موقع: {pct(l.metrics.delivery)} · سفارش‌ها: {l.metrics.orders}</p>{l.commercial&&<p>امتیاز کارشناسی آخرین ارزیابی: {last?.data.score??'تکمیل نشده'} از ۱۰۰</p>}{data.canQuality&&<button className="btn" onClick={()=>begin('review',{linkId:l.id,revision:l.revision,status:l.data.status,qualityRisk:l.data.qualityRisk,supplyRisk:l.data.supplyRisk,reviewDue:l.data.reviewDue,restrictions:l.data.restrictions,maxQuantity:l.data.maxQuantity?String(l.data.maxQuantity/1000):''})}>ثبت ارزیابی و صلاحیت</button>}
 <details><summary>سوابق ارزیابی و خرید</summary>{l.reviews.map((r:any)=><div key={r.id}><p>{formatDate(r.data.at)} · {supplierStates[r.data.status]} · {r.data.rationale}</p><p>مرجع شواهد: {r.data.evidence} · بازبینی: {formatDate(r.data.reviewDue)}</p>{r.data.score!=null&&<p>امتیاز کارشناسی: {r.data.score}</p>}</div>)}{data.orders.filter((o:any)=>o.data.supplierLinkId===l.id).map((o:any)=><p key={o.id}>{formatDate(o.created)} · {o.data.quantity/1000} {o.data.unit} · {o.data.state}{o.data.totalRial!==undefined?' · '+BigInt(o.data.totalRial).toLocaleString('fa-IR')+' ریال':''}</p>)}</details></div>})}</article>)}
 {!data.suppliers.length&&<p className="empty">هنوز تأمین‌کننده‌ای ثبت نشده است. با ثبت پرونده و اتصال آن به کالا شروع کنید.</p>}
 <details><summary>روش کار و امتیازدهی</summary>{Object.values(data.help).map((t:any,i)=><p key={i}>{t}</p>)}</details></>}
 </div><Dialog open={!!draft} onOpenChange={v=>{if(!busy&&!v)setDraft(null)}}><DialogContent className="modal sm:max-w-3xl"><DialogTitle>{draft?.mode==='review'?'ارزیابی و صلاحیت کالا':draft?.mode==='link'?'اتصال به کالا':'پرونده تأمین‌کننده'}</DialogTitle><DialogDescription>ثبت با نام شما و همراه سابقه انجام می‌شود. تغییر پرونده، ارزیابی مجدد کالاهای مرتبط را لازم می‌کند.</DialogDescription>{draft&&<form onSubmit={save}><fieldset disabled={busy} style={{border:0,padding:0}}><div className="formgrid">
 {draft.mode==='supplier'&&<>{pick('route','مسیر',{domestic:'داخلی',foreign:'خارجی'})}{pick('kind','نوع',{manufacturer:'سازنده',trader:'واسطه / بازرگان'})}{Object.entries(supplierFields).map(([k,t])=>field(k,t,['name','country','contact','phone'].includes(k)))}<label className="field"><input type="checkbox" checked={draft.active} onChange={e=>change('active',e.target.checked)}/>فعال</label></>}
 {draft.mode==='link'&&<>{pick('supplierId','تأمین‌کننده',Object.fromEntries(data.suppliers.map((s:any)=>[s.id,s.data.name])))}{pick('materialId','کالا',Object.fromEntries(data.materials.map((m:any)=>[m.id,m.code+' · '+m.name])))}{field('supplierCode','کد کالا نزد تأمین‌کننده')}{field('notes','یادداشت ارتباط')}</>}
 {draft.mode==='review'&&<>{pick('status','نتیجه صلاحیت',supplierStates)}{pick('qualityRisk','ریسک کیفیت',supplierRisks)}{pick('supplyRisk','ریسک تأمین',supplierRisks)}<SolarDate label="موعد بازبینی" value={draft.reviewDue} onChange={v=>change('reviewDue',v)}/>{field('rationale','دلایل تصمیم',true)}{field('evidence','مرجع شواهد، ممیزی، آزمون یا مدارک بررسی‌شده',true)}{field('restrictions','محدودیت و کنترل اضافی',draft.status==='conditional')}{draft.status==='conditional'&&field('maxQuantity','سقف مقدار هر سفارش مشروط، واحد کالا',true)}<p className="notice wide">امتیازها کارشناسی و اختیاری‌اند. بدون تکمیل همه موارد، امتیاز کل ساخته نمی‌شود. وزن‌ها سیاست پیشنهادی شرکت‌اند، نه امتیاز اجباری استاندارد.</p>{Object.entries({quality:'کیفیت (۴۰٪)',delivery:'تحویل (۲۰٪)',cost:'هزینه (۲۰٪)',response:'پاسخ‌گویی (۱۰٪)',documents:'مدارک (۱۰٪)'}).map(([k,t])=><label className="field" key={k}>{t}<input type="number" min="0" max="100" step="any" value={draft.scores[k]??''} onChange={e=>change('scores',{...draft.scores,[k]:e.target.value===''?null:Number(e.target.value)})}/></label>)}</>}
 </div>{error&&<p className="notice error" role="alert">{error}</p>}<button className="btn primary" disabled={busy}>تأیید و ثبت</button></fieldset></form>}</DialogContent></Dialog></section>;
}
