'use client';
import {useEffect,useRef,useState} from 'react';
import {ShieldAlert,Download,KeyRound,RefreshCw,Copy} from 'lucide-react';
import {resetScopes,resetPreserved,resetCatalog} from '@/lib/reset-contract';
import {formatDateTime} from '@/lib/persian-date';
const phases:Record<string,string>={testing:'پیش از شروع اصلی',maintenance:'توقف ثبت برای پاک‌سازی',live:'شروع اصلی؛ پاک‌سازی قفل است'};
const jobStates:Record<string,string>={preparing:'در حال پشتیبان‌گیری',ready:'آماده تأیید نهایی',cancelled:'لغو شده',failed:'ناموفق؛ حذف انجام نشده',succeeded:'پاک‌سازی انجام شد'};
export function SystemResetPanel({accountId}:{accountId:string}){
 const [data,setData]=useState<any>(null),[scope,setScope]=useState('operations'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[tick,setTick]=useState(0);
 const [secret,setSecret]=useState(''),[nextSecret,setNextSecret]=useState(''),[showSecret,setShowSecret]=useState(false),[phrase,setPhrase]=useState(''),[ack,setAck]=useState(false),[readyCheck,setReadyCheck]=useState(false),[files,setFiles]=useState<any>(null),[finished,setFinished]=useState(false);
 const alive=useRef(true),prepareId=useRef(''),headers={'Content-Type':'application/json','x-assistant-account':accountId};
 useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);
 useEffect(()=>{let active=true;const c=new AbortController();fetch('/api/system-reset?scope='+scope,{headers:{'x-assistant-account':accountId},cache:'no-store',signal:c.signal}).then(async r=>{const d:any=await r.json();if(!active)return;if(!r.ok||d.accountId!==accountId)throw Error(d.error||'حساب تغییر کرده است.');setData(d);if(d.jobs.some((j:any)=>j.id===prepareId.current&&['failed','cancelled'].includes(j.state)))prepareId.current='';}).catch(e=>{if(active)setError(e.message)});return()=>{active=false;c.abort()}},[accountId,scope,tick]);
 const refresh=()=>{setTick(n=>n+1);window.dispatchEvent(new Event('hamnafas-reset-changed'))};
 async function post(body:any){if(busy)return;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/system-reset',{method:'POST',headers,body:JSON.stringify({...body,confirmed:true})}),d:any=await r.json();if(!alive.current)return;if(!r.ok||d.accountId!==accountId)throw Error(d.error||'عملیات انجام نشد؛ وضعیت را تازه کنید.');if(body.mode==='password'){setNextSecret('');setSecret('');setShowSecret(false);setMessage('رمز مستقل ذخیره شد؛ برای پاک‌سازی این رمز را نگه دارید.');}else if(body.mode==='prepare'){setMessage('پشتیبان ساخته شد. اکنون محدوده نهایی را بررسی و فایل پشتیبان را دریافت کنید.');setPhrase('');setAck(false);}else if(body.mode==='cancel'){prepareId.current='';setMessage('لغو شد؛ داده‌ها حفظ شده‌اند و ثبت دوباره آزاد است.');}else {setSecret('');setFinished(true);}refresh();}catch(e){if(alive.current){setError(e instanceof Error?e.message:'نتیجه قطعی نیست؛ وضعیت را تازه کنید.');refresh();}}finally{if(alive.current)setBusy(false)}}
 async function download(job:any){setError('');try{const r=await fetch('/api/system-reset/backup?id='+job.id,{headers,cache:'no-store'});if(!r.ok)throw Error((await r.json() as any).error);const blob=await r.blob();if(!alive.current)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='hamnafas-before-reset-'+job.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);setMessage('فایل داده دریافت شد؛ فهرست پیوست‌های سرور نیز در همین بخش قابل دریافت است.');refresh();}catch(e){if(alive.current)setError(e instanceof Error?e.message:'دریافت انجام نشد.')}}
 async function showFiles(job:any){try{const r=await fetch('/api/system-reset/backup?id='+job.id+'&view=files',{headers,cache:'no-store'}),d:any=await r.json();if(!alive.current)return;if(!r.ok)throw Error(d.error);setFiles({jobId:job.id,rows:d.files});}catch(e){if(alive.current)setError(e instanceof Error?e.message:'دریافت انجام نشد.')}}
 function generate(){setNextSecret('HN-'+Array.from(crypto.getRandomValues(new Uint8Array(14))).map(x=>x.toString(16).padStart(2,'0')).join(''));setShowSecret(true);setMessage('رمز پیشنهادی ساخته شد؛ آن را کپی و سپس ذخیره کنید.');}
 if(finished)return <section className="panel inside"><h2>پاک‌سازی انجام شد؛ شروع اصلی فعال است.</h2><p>حساب‌ها و تنظیمات حفظ شده‌اند. برای جلوگیری از استفاده از صفحات قدیمی، همه کاربران دوباره وارد شوند. الگوهای وظایف پس از بررسی شما فعال شوند.</p><button className="btn primary" onClick={()=>window.location.reload()}>ورود دوباره و شروع کار</button></section>;
 const job=data?.jobs.find((j:any)=>j.id===data.activeJobId&&['preparing','ready'].includes(j.state));
 return <div className="reset-panel">
  <section className="panel inside"><div className="tools"><ShieldAlert size={28}/><h2>پاک‌سازی داده‌های آزمایشی</h2><button className="btn" disabled={busy} onClick={refresh}><RefreshCw size={16}/>تازه‌سازی وضعیت</button></div><p className="reset-warning">این کار همه اطلاعات محدوده انتخاب‌شده را از این نصب پاک می‌کند؛ داده واقعی و آزمایشی قابل تشخیص خودکار نیستند. پیش از اجرا، ورود اطلاعات را با همکاران متوقف کنید.</p><p><strong>{data?phases[data.phase]:'در حال دریافت وضعیت…'}</strong></p><p>اجرای این صفحه مستقل از حالت «محیط نمونه» است و فقط ادمین دسترسی دارد.</p></section>
  {error&&<p role="alert" className="notice error">{error}</p>}{message&&<p role="status" className="notice">{message}</p>}
  {data&&<section className="panel inside"><h3>این موارد حفظ می‌شوند</h3><ul>{resetPreserved.map(s=><li key={s}>{s}</li>)}</ul><p className="subtle">فایل‌های قبلی برای بازیابی در مخزن خصوصی سرور نگه داشته می‌شوند و بعد از پاک‌سازی از بخش‌های کاری قابل مشاهده نیستند. این عملیات حذف دائمی پشتیبان‌ها نیست.</p></section>}
  {data?.phase==='testing'&&<>
   <details className="panel inside" open={!data.hasPassword}><summary><KeyRound size={18} style={{display:'inline'}}/> {data.hasPassword?'تغییر رمز مستقل پاک‌سازی':'۱. تعیین رمز مستقل پاک‌سازی'}</summary><form onSubmit={e=>{e.preventDefault();void post({mode:'password',revision:data.revision,password:nextSecret,...(data.hasPassword?{currentPassword:secret}:{})})}}><fieldset disabled={busy}>{data.hasPassword&&<label className="field">رمز فعلی پاک‌سازی<input type="password" autoComplete="off" value={secret} onChange={e=>setSecret(e.target.value)} required/></label>}<label className="field">رمز جدید؛ حداقل ۱۰ نویسه<input type={showSecret?'text':'password'} autoComplete="new-password" minLength={10} maxLength={128} dir="ltr" value={nextSecret} onChange={e=>setNextSecret(e.target.value)} required/></label><div className="tools"><button type="button" className="btn" onClick={generate}>ساخت رمز پیشنهادی</button><button type="button" className="btn" disabled={!nextSecret} onClick={async()=>{try{await navigator.clipboard.writeText(nextSecret);setMessage('رمز کپی شد.')}catch{setShowSecret(true);setMessage('رمز را از کادر انتخاب و کپی کنید.')}}}><Copy size={16}/>کپی رمز</button><label><input type="checkbox" checked={showSecret} onChange={e=>setShowSecret(e.target.checked)}/> نمایش رمز</label><button className="btn primary">ذخیره رمز</button></div><p className="subtle">این رمز با رمز ورود متفاوت است؛ در چت دستیار واردش نکنید. رمز ثابت یا پیش‌فرض در نرم‌افزار وجود ندارد.</p></fieldset></form></details>
   <section className="panel inside"><h3>۲. انتخاب محدوده و ساخت پشتیبان</h3><label className="field">محدوده<select value={scope} disabled={busy} onChange={e=>{setScope(e.target.value);prepareId.current='';setReadyCheck(false)}}>{Object.entries(resetScopes).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><p>{scope==='full'?'این تعاریف هم حذف می‌شوند:':'این تعاریف حفظ می‌شوند:'}</p><ul>{resetCatalog.map(s=><li key={s}>{s}</li>)}</ul><Counts rows={data.counts}/><form onSubmit={e=>{e.preventDefault();if(!prepareId.current)prepareId.current=crypto.randomUUID();void post({mode:'prepare',id:prepareId.current,scope,password:secret})}}><fieldset disabled={busy||!data.hasPassword}><label className="field">رمز پاک‌سازی<input type="password" autoComplete="off" required value={secret} onChange={e=>setSecret(e.target.value)}/></label><label className="reset-check"><input type="checkbox" required checked={readyCheck} onChange={e=>setReadyCheck(e.target.checked)}/>محدوده را بررسی کردم و ورود اطلاعات همکاران متوقف است؛ آماده‌سازی پشتیبان، ثبت جدید را موقتاً متوقف کند.</label><button className="btn" disabled={!readyCheck||busy||!data.hasPassword}>{busy?'در حال انجام…':'ساخت پشتیبان و پیش‌نمایش نهایی'}</button></fieldset></form></section>
  </>}
  {job&&<section className="panel inside"><h3>۳. بررسی نهایی — هنوز داده‌ای حذف نشده است</h3><p>{resetScopes[job.scope]} · {jobStates[job.state]}</p><p>مهلت تأیید: {formatDateTime(job.expires)}. اگر منصرف شدید یا زمان تمام شد، «لغو و آزادکردن ثبت» را بزنید.</p>{job.summary&&<Counts rows={job.summary.counts}/>}<div className="tools">{job.hasBackup&&<><button className="btn" disabled={busy} onClick={()=>void download(job)}><Download size={17}/>دریافت پشتیبان داده‌ها</button><button className="btn" onClick={()=>void showFiles(job)}>فهرست پیوست‌های پشتیبان ({job.summary?.files||0})</button></>}<button className="btn" disabled={busy} onClick={()=>void post({mode:'cancel',id:job.id})}>لغو و آزادکردن ثبت</button></div><p className="subtle">فایل JSON شامل رکوردها و فهرست پیوست‌هاست؛ بایت پیوست‌ها در مخزن سرور باقی می‌ماند و از فهرست بالا جداگانه قابل دریافت است. بازیابی با همکار فنی انجام می‌شود.</p>
   {job.state==='ready'&&<form onSubmit={e=>{e.preventDefault();void post({mode:'execute',id:job.id,password:secret,confirmationCode:phrase,backupAcknowledged:ack})}}><fieldset disabled={busy}><label className="field">رمز پاک‌سازی<input type="password" autoComplete="off" required value={secret} onChange={e=>setSecret(e.target.value)}/></label><label className="field">برای تأیید نهایی، عبارت <bdi>{job.confirmationCode}</bdi> را بنویسید<input dir="ltr" required autoComplete="off" value={phrase} onChange={e=>setPhrase(e.target.value)}/></label><label className="reset-check"><input type="checkbox" required checked={ack} onChange={e=>setAck(e.target.checked)}/>پشتیبان را دریافت و محدوده حذف را بررسی کردم. اطلاعات این محدوده حذف شود و شروع اصلی فعال شود؛ پاک‌سازی بعدی قفل خواهد شد.</label><button className="btn reset-danger" disabled={busy||!ack||!job.downloadedAt||phrase!==job.confirmationCode}>{busy?'در حال انجام…':'حذف اطلاعات انتخاب‌شده و آغاز کار اصلی'}</button></fieldset></form>}
  </section>}
  {!!data?.jobs.length&&<section className="panel inside"><h3>سابقه پاک‌سازی و پشتیبان‌ها</h3>{data.jobs.map((j:any)=><div className="reset-history" key={j.id}><strong>{jobStates[j.state]}</strong><p>{formatDateTime(j.created)} · {resetScopes[j.scope]}</p>{j.hasBackup&&<div className="tools"><button className="link" onClick={()=>void download(j)}>دریافت داده‌های پشتیبان</button><button className="link" onClick={()=>void showFiles(j)}>پیوست‌ها</button></div>}</div>)}</section>}
  {files&&<section className="panel inside"><h3>پیوست‌های پشتیبان</h3>{files.rows.length?files.rows.map((f:any)=><p key={f.index}><a className="link" href={'/api/system-reset/backup?id='+files.jobId+'&file='+f.index} download>{f.filename}</a> · {Number(f.size||0).toLocaleString('fa-IR')} بایت</p>):<p>پیوستی در محدوده حذف نیست.</p>}<button className="btn" onClick={()=>setFiles(null)}>بستن</button></section>}
 </div>;
}
function Counts({rows}:{rows:any[]}){return <details className="reset-counts" open><summary>تعداد اطلاعات در محدوده انتخاب‌شده</summary><div>{rows.filter(r=>r.count>0).map(r=><p key={r.table}><span>{r.label}</span><strong>{Number(r.count).toLocaleString('fa-IR')}</strong></p>)}{!rows.some(r=>r.count>0)&&<p>اطلاعاتی برای حذف در این محدوده وجود ندارد.</p>}</div></details>}
export function ResetNotice({accountId,admin,onOpen}:{accountId:string;admin:boolean;onOpen:()=>void}){
 const [phase,setPhase]=useState('');useEffect(()=>{let active=true;const c=new AbortController();setPhase('');const refresh=async()=>{if(document.visibilityState==='hidden')return;try{const r=await fetch('/api/system-reset?view=state',{headers:{'x-assistant-account':accountId},cache:'no-store',signal:c.signal}),d:any=await r.json();if(active&&r.ok&&d.accountId===accountId)setPhase(d.phase)}catch{}};const wake=()=>void refresh();void refresh();const t=setInterval(wake,45000);window.addEventListener('hamnafas-reset-changed',wake);document.addEventListener('visibilitychange',wake);return()=>{active=false;c.abort();clearInterval(t);window.removeEventListener('hamnafas-reset-changed',wake);document.removeEventListener('visibilitychange',wake)}},[accountId]);
 return phase==='maintenance'?<div className="notice error" role="alert">سامانه برای پشتیبان‌گیری و پاک‌سازی در حال نگهداری است؛ ثبت داده موقتاً متوقف شده است.{admin&&<button className="link" onClick={onOpen}>بررسی یا لغو پاک‌سازی</button>}</div>:null;
}
