'use client';
import {useEffect,useState} from 'react';
import {Bell,Bot} from 'lucide-react';
export function TaskNotifier({accountId,onOpen}:{accountId:string;onOpen:()=>void}){
 const [count,setCount]=useState(0),[title,setTitle]=useState(''),[messages,setMessages]=useState(0),[work,setWork]=useState<any>(null);
 useEffect(()=>{let active=true;const controller=new AbortController();setCount(0);setMessages(0);setTitle('');setWork(null);async function refresh(){if(document.visibilityState==='hidden')return;try{await fetch('/api/tasks/tick',{method:'POST',signal:controller.signal});const r=await fetch('/api/tasks',{cache:'no-store',signal:controller.signal}),d=await r.json() as any;if(!active||!r.ok||d.accountId!==accountId)return;setWork(d.tasks.find((t:any)=>t.assignee===d.memberId&&t.data.replenishmentWorkflow&&['open','blocked'].includes(t.state))||null);const unread=d.notifications.filter((n:any)=>!n.read_at);setCount(unread.length);setTitle(unread[0]?.message||'');const ir=await fetch('/api/inbox',{cache:'no-store',signal:controller.signal}),ib=await ir.json() as any;if(active&&ir.ok&&ib.accountId===accountId)setMessages(ib.summary.attention);}catch{}}
 const wake=()=>void refresh();void refresh();const timer=setInterval(wake,60000);window.addEventListener('nafasyar-tasks-changed',wake);document.addEventListener('visibilitychange',wake);return()=>{active=false;controller.abort();clearInterval(timer);window.removeEventListener('nafasyar-tasks-changed',wake);document.removeEventListener('visibilitychange',wake)}},[accountId]);
 if(!count&&!messages&&!work)return null;return <div className="task-nudge"><button className="link" onClick={onOpen} title={title} aria-label={count+' اعلان وظیفه؛ باز کردن کارتابل'}><Bell size={18}/>{work&&<span className="task-question">{work.data.title}: نتیجه آماده است یا مانعی دارید؟</span>}<span>{count.toLocaleString('fa-IR')} اعلان کار · {messages.toLocaleString('fa-IR')} پیام نیازمند رسیدگی</span></button><button className="link" onClick={()=>window.dispatchEvent(new CustomEvent('nafasyar-duty-prompt',{detail:{text:work?('وظیفه '+work.id+' و پرونده '+work.data.sourcePlanId+' را بخوان. برای انجام مرحله '+work.data.title+' یک سؤال از من بپرس؛ ثبت عملیات فقط با تأیید من باشد.'):'کارتابل و صندوق پیام من را بخوان، خلاصه کارهای امروز را بگو و برای مهم‌ترین درخواست یک سؤال بپرس؛ ارسال پاسخ فقط با تأیید من باشد.'}}))}><Bot size={18}/>با هم رسیدگی کنیم</button></div>
}
