'use client';
import {InboxPanel} from './inbox-panel';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {SolarDate} from './solar-date';
import {tehranDay} from '@/lib/serials';
const states:Record<string,string>={open:'باز',blocked:'دارای مانع',submitted:'در انتظار بررسی',completed:'تکمیل‌شده',cancelled:'لغوشده'};
const modes:Record<string,string>={answer:'ذخیره پاسخ',submit:'ارسال پاسخ برای بررسی',blocked:'ثبت مانع انجام کار',request_extension:'درخواست تمدید',approve:'تأیید و تکمیل',return:'درخواست اصلاح پاسخ',extend:'تمدید مهلت',cancel:'لغو وظیفه',reassign:'انتقال مسئولیت'};
const dayNames=['یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه','شنبه'];
const cadenceNames:Record<string,string>={once:'یک‌باره',daily:'روزانه',weekly:'هفتگی',monthly:'ماهیانه'};
const profileLabels:Record<string,string>={mission:'هدف سمت',responsibilities:'شرح مسئولیت‌ها',authorityBoundaries:'حدود اختیار و تفکیک مسئولیت',reportingTo:'گزارش‌دهی پیشنهادی به',handoffs:'ارتباط با سایر واحدها',metrics:'شاخص‌های پیشنهادی ارزیابی'};
function PositionProfile({position}:{position:any}){return <dl className="position-profile">{Object.entries(profileLabels).filter(([key])=>position[key]).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{position[key]}</dd></div>)}</dl>}
const fa=(s:string)=>new Date(s).toLocaleString('fa-IR');
function Pick({label,value,items,onChange}:{label:string;value:string;items:[string,string][];onChange:(v:string)=>void}){return <label className="field">{label}<Select dir="rtl" value={value} onValueChange={onChange}><SelectTrigger><SelectValue placeholder="انتخاب کنید"/></SelectTrigger><SelectContent>{items.map(([id,title])=><SelectItem key={id} value={id}>{title}</SelectItem>)}</SelectContent></Select></label>}
export function TasksPanel({demo,onNavigate}:{demo:boolean;onNavigate:(s:string)=>void}){
 const [data,setData]=useState<any>(null),[tab,setTab]=useState('inbox'),[draft,setDraft]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[files,setFiles]=useState<any[]>([]),[loading,setLoading]=useState(false),[search,setSearch]=useState(''),[cadence,setCadence]=useState('all');
 async function load(){if(demo)return;setLoading(true);try{let r=await fetch('/api/tasks',{cache:'no-store'}),d=await r.json() as any;if(!r.ok)throw new Error(d.error);if(d.isAdmin&&!d.starterInstalled){const install=await fetch('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),mode:'install_starter'})});const result=await install.json() as any;if(!install.ok)throw new Error(result.error||'تعریف برنامه‌های اولیه انجام نشد؛ تازه‌سازی کنید.');r=await fetch('/api/tasks',{cache:'no-store'});d=await r.json() as any;if(!r.ok)throw new Error(d.error);}setData(d)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[demo]);
 const defs=data?.definitions||[],members=data?.members||[],positions=defs.filter((d:any)=>d.type==='position'),templates=defs.filter((d:any)=>d.type==='duty_template');
 const change=(key:string,v:any)=>setDraft((d:any)=>({...d,[key]:v}));
 function start(d:any){setError('');setMessage('');setFiles([]);setDraft({id:crypto.randomUUID(),mission:'',responsibilities:'',authorityBoundaries:'',reportingTo:'',handoffs:'',metrics:'',...d})}
 async function show(t:any){start({mode:t.state==='submitted'?'approve':'answer',taskId:t.id,revision:t.revision,note:t.data.answer||'',task:t,newDue:'',dueDay:tehranDay(),dueTime:'16:00',assignee:''});const r=await fetch('/api/tasks/files?task='+encodeURIComponent(t.id));const d=await r.json() as any;if(r.ok)setFiles(d.files);else setError(d.error)}
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const {task,dueDay,dueTime,...payload}=draft;if(payload.mode==='extend')payload.newDue=dueDay+'T'+dueTime+':00+03:30';const r=await fetch('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json() as any;if(!r.ok)throw new Error(d.error);setDraft(null);setMessage('ثبت شد.');await load();window.dispatchEvent(new Event('nafasyar-tasks-changed'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function upload(file:File){if(busy)return;setBusy(true);setError('');try{const fd=new FormData();fd.set('file',file);const r=await fetch('/api/tasks/files?task='+encodeURIComponent(draft.taskId)+'&requestId='+crypto.randomUUID(),{method:'POST',body:fd}),d=await r.json() as any;if(!r.ok)throw new Error(d.error);setFiles(f=>[d.file,...f]);const response=await fetch('/api/tasks',{cache:'no-store'}),fresh=await response.json() as any;if(!response.ok)throw new Error(fresh.error);setData(fresh);const t=fresh.tasks.find((t:any)=>t.id===draft.taskId);if(t)setDraft((p:any)=>({...p,id:crypto.randomUUID(),revision:t.revision,task:t}));}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function readNotice(noticeId:string){try{const r=await fetch('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),mode:'read_notice',noticeId})});if(!r.ok)throw new Error('ثبت مشاهده اعلان انجام نشد.');await load();window.dispatchEvent(new Event('nafasyar-tasks-changed'))}catch(e){setError((e as Error).message)}}
 async function tick(){setBusy(true);try{const r=await fetch('/api/tasks/tick',{method:'POST'}),d=await r.json() as any;if(!r.ok)throw new Error(d.error);await load();setMessage(d.skipped?'زمان‌بند در یک دقیقه اخیر بررسی کرده است.':'سررسیدها بررسی شدند.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(demo)return <p className="notice">کارتابل وظایف در اطلاعات واقعی شرکت فعال است.</p>;
 const tasks=(data?.tasks||[]).filter((t:any)=>tab==='mine'?t.assignee===data.memberId:tab==='review'?t.supervisor===data.memberId||data.isAdmin:true);
 const actions=draft?.task?Object.entries(modes).filter(([m])=>!(draft.task.data.serviceWorkflow||draft.task.data.transportWorkflow)||['answer','blocked','request_extension'].includes(m)).filter(([m])=>['answer','submit','blocked','request_extension'].includes(m)?(data.isAdmin||draft.task.assignee===data.memberId)&&!['submitted','completed','cancelled'].includes(draft.task.state):(data.isAdmin||draft.task.supervisor===data.memberId)&&(!['approve','return'].includes(m)||draft.task.state==='submitted')&&(m!=='reassign'||data.isAdmin)):[];
 return <section className="panel"><div className="panelhead"><div><h2>کارتابل و صندوق پیام</h2><p className="subtle">کارهای من، مدارک، پیگیری مهلت و بررسی پاسخ‌ها</p></div><div className="tools"><button className="btn" disabled={busy||loading} onClick={()=>void load()}>تازه‌سازی</button><button className="btn" disabled={busy} onClick={()=>void tick()}>بررسی سررسیدها</button></div></div><div className="inside"><div className="flow-tabs">{[['inbox','پیام‌های همکاران'],['mine','کارهای فرایندی من'],['review','پیگیری و بررسی'],...(data?.isAdmin?[['definitions','سمت‌ها و برنامه وظایف']]:[])].map(([key,title])=><button className={'btn '+(tab===key?'primary':'')} key={key} onClick={()=>setTab(key)}>{title}</button>)}</div>{error&&!draft&&<p role="alert" className="notice error">{error}</p>}{message&&<p className="notice">{message}</p>}{loading&&<p>در حال دریافت…</p>}
 {tab!=='definitions'&&tab!=='inbox'&&(data?.notifications||[]).some((n:any)=>!n.read_at)&&<details open><summary>اعلان‌های خوانده‌نشده</summary>{data.notifications.filter((n:any)=>!n.read_at).map((n:any)=><div className="notice" key={n.id}><p>{n.message} · {fa(n.created)}</p><button className="btn" onClick={()=>void readNotice(n.id)}>خواندم</button></div>)}</details>}
 <div hidden={tab!=='inbox'}><InboxPanel onNavigate={onNavigate}/></div>
 {tab==='mine'&&(data?.ownPositions||[]).map((p:any)=><details className="flow-card" key={p.id}><summary>شرح سمت من: {p.name}</summary><PositionProfile position={p}/></details>)}
 {tab!=='definitions'&&<>{!tasks.length&&<p className="empty">وظیفه‌ای در این فهرست نیست. برای شروع، افراد هر سمت را مشخص و برنامه‌های موردنظر را فعال کنید.</p>}{data?.limited&&<p className="notice">حداکثر ۳۰۰ وظیفه اخیر نمایش داده می‌شود.</p>}{tasks.map((t:any)=><article className="flow-card" key={t.id}><h3>{t.data.title}</h3><p>{t.data.positionName} · {states[t.state]} · مهلت: {fa(t.due)}</p>{!['completed','cancelled','submitted'].includes(t.state)&&Date.parse(t.due)<Date.now()&&<p className="notice error">از مهلت گذشته است</p>}<p style={{whiteSpace:'pre-wrap'}}>{t.data.instructions}</p><p>مدرک لازم: {t.data.evidence==='file'?'فایل به همراه توضیح':'پاسخ متنی'} · مسئول: {members.find((m:any)=>m.id===t.assignee)?.name||(t.assignee===data.memberId?'شما':t.assignee)}</p><div className="tools"><button className="btn" onClick={()=>{setTab('inbox');window.dispatchEvent(new CustomEvent('nafasyar-compose-message',{detail:{section:'tasks',id:t.id,title:'پیگیری: '+t.data.title}}))}}>پیام مرتبط با این کار</button><button className="btn primary" onClick={()=>void show(t)}>پاسخ، مدارک و سابقه</button><button className="btn" onClick={()=>window.dispatchEvent(new CustomEvent('nafasyar-duty-prompt',{detail:{text:'در انجام این وظیفه کمکم کن؛ اطلاعات فعلی را با ابزار کارتابل بخوان و مرحله‌به‌مرحله یک سؤال بپرس. شناسه وظیفه: '+t.id}}))}>کمک دستیار</button>{t.data.sourceSection&&<button className="btn" onClick={()=>onNavigate(t.data.sourceSection)}>باز کردن بخش مرتبط</button>}</div></article>)}</>}
 {tab==='definitions'&&data?.isAdmin&&<>
 <p className="notice">سمت‌ها و برنامه‌های اولیه آماده‌اند؛ سمت‌های تخصصی خدمات و تأمین نیز اضافه شده‌اند. شرح‌ها و برنامه‌ها قابل ویرایش‌اند. ابتدا افراد و بررسی‌کننده را تعیین کنید، سپس برنامه دلخواه را با تاریخ شروع فعال کنید؛ برنامه‌های پیشنهادی ابتدا متوقف‌اند.</p>
 <p className="subtle">زمان‌ها به وقت تهران‌اند. پیش‌فرض: روزانه شنبه تا پنجشنبه، هفتگی پنجشنبه، ماهیانه روز پنجم ماه شمسی؛ ساعت ۱۶. تعطیلات رسمی و ساعت کاری را متناسب با شرکت تنظیم کنید. انتساب سمت، دسترسی مالی یا انبار ایجاد نمی‌کند.</p>
 <p className="subtle">آخرین بررسی زمان‌بند: {data.scheduler?fa(data.scheduler.lastTick)+' · '+(data.scheduler.source==='background'?'اجرای پس‌زمینه سرور':'بررسی هنگام استفاده از سامانه'):'هنوز اجرا نشده'}. اجرای مستقل از بازبودن صفحه نیاز به راه‌اندازی زمان‌بند سرور دارد.</p>
 <div className="tools"><button className="btn primary" onClick={()=>start({mode:'position',name:'',unit:'',members:[],supervisor:'',active:true})}>تعریف سمت</button><button className="btn primary" disabled={!positions.length} onClick={()=>start({mode:'template',positionId:'',title:'',instructions:'',cadence:'daily',evidence:'text',startDate:tehranDay(),time:'16:00',weekdays:[6,0,1,2,3,4],weekday:4,monthDay:5,remindHours:24,escalateHours:24,active:false,sourceSection:''})}>افزودن برنامه وظیفه</button></div>
 <div className="formgrid" style={{marginTop:16}}><label className="field">جست‌وجوی سمت یا واحد<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="مثلاً انبار یا بازرگانی"/></label><Pick label="دوره برنامه‌ها" value={cadence} items={ [['all','همه دوره‌ها'],...Object.entries(cadenceNames)] } onChange={setCadence}/></div>
 <p className="subtle">{positions.length.toLocaleString('fa-IR')} سمت · {templates.length.toLocaleString('fa-IR')} برنامه · {templates.filter((t:any)=>t.data.active).length.toLocaleString('fa-IR')} برنامه فعال</p>
 {positions.filter((p:any)=>(p.data.name+' '+p.data.unit).replace(/\s|‌/g,'').includes(search.replace(/\s|‌/g,''))).map((p:any)=>{const plans=templates.filter((t:any)=>t.data.positionId===p.id&&(cadence==='all'||t.data.cadence===cadence));return <article className="flow-card position-card" key={p.id}>
 <div className="panelhead"><div><h3>{p.data.name}</h3><p className="subtle">{p.data.unit} · {p.data.active?'فعال':'متوقف'} · {p.data.members.length?p.data.members.map((id:string)=>members.find((m:any)=>m.id===id)?.name||id).join('، '):'فردی تعیین نشده'} · بررسی‌کننده: {members.find((m:any)=>m.id===p.data.supervisor)?.name||'مدیر سامانه'}</p></div><button className="btn" onClick={()=>start({...p.data,mode:'position',definitionId:p.id,revision:p.revision})}>ویرایش شرح سمت و افراد</button></div>
 {p.data.mission&&<p>{p.data.mission}</p>}<details><summary>شرح وظایف و حدود اختیار</summary><PositionProfile position={p.data}/></details>
 <details className="position-plans"><summary>برنامه‌ها و گزارش‌ها · {plans.length.toLocaleString('fa-IR')}</summary>{!plans.length&&<p className="empty">برنامه‌ای در این دوره نیست.</p>}{plans.map((t:any)=><div className="duty-template" key={t.id}><h4>{t.data.title}</h4><p className="subtle">{cadenceNames[t.data.cadence]} · {t.data.active?'فعال':'متوقف؛ قابل ویرایش و فعال‌سازی'} · {t.data.evidence==='file'?'فایل و توضیح':'پاسخ متنی'} · {t.data.time}</p><details><summary>مراحل انجام، خروجی و معیار پذیرش</summary><p style={{whiteSpace:'pre-wrap'}}>{t.data.instructions}</p></details><button className="btn" onClick={()=>start({...t.data,mode:'template',definitionId:t.id,revision:t.revision})}>ویرایش برنامه و زمان‌بندی</button></div>)}</details>
 </article>})}</>}
 </div><Dialog open={!!draft} onOpenChange={v=>{if(!busy&&!v)setDraft(null)}}><DialogContent className="modal sm:max-w-3xl"><DialogTitle>{draft?.task?draft.task.data.title:draft?.mode==='position'?'سمت سازمانی':'برنامه وظیفه'}</DialogTitle><DialogDescription>تغییرات همراه با نام انجام‌دهنده و زمان ثبت می‌شوند.</DialogDescription>{draft&&<form onSubmit={submit}><fieldset disabled={busy} style={{border:0,padding:0}}><div className="formgrid">
 {draft.mode==='position'&&<><label className="field">نام سمت<input required value={draft.name} onChange={e=>change('name',e.target.value)}/></label><label className="field">واحد سازمانی<input required value={draft.unit} onChange={e=>change('unit',e.target.value)}/></label><Pick label="بررسی‌کننده / مدیر مستقیم" value={draft.supervisor||'@admin'} onChange={v=>change('supervisor',v==='@admin'?'':v)} items={ [['@admin','مدیر سامانه'],...members.filter((m:any)=>m.status==='active').map((m:any)=>[m.id,m.name] as [string,string])]}/><p className="notice wide">بررسی‌کننده انتخاب‌شده، یک فرد واقعی برای بررسی پاسخ‌هاست. عنوان گزارش‌دهی پیشنهادی در شرح سمت صرفاً راهنماست. انتخاب چند نفر، برای هر نفر یک وظیفه مستقل می‌سازد.</p><fieldset className="wide"><legend>افراد مسئول این سمت</legend>{members.filter((m:any)=>m.status==='active').map((m:any)=><label className="flow-check" key={m.id}><Checkbox checked={draft.members.includes(m.id)} onCheckedChange={v=>change('members',v?[...draft.members,m.id]:draft.members.filter((id:string)=>id!==m.id))}/>{m.name} · {m.unit}</label>)}</fieldset>{Object.entries(profileLabels).map(([key,label])=><label className="field wide" key={key}>{label}<textarea rows={key==='responsibilities'?4:2} maxLength={8000} value={draft[key]||''} onChange={e=>change(key,e.target.value)}/></label>)}</>}
 {draft.mode==='template'&&<><Pick label="سمت" value={draft.positionId} items={positions.map((p:any)=>[p.id,p.data.name])} onChange={v=>change('positionId',v)}/><label className="field">عنوان وظیفه<input required value={draft.title} onChange={e=>change('title',e.target.value)}/></label><label className="field wide">راهنمای گام‌به‌گام و معیار پذیرش<textarea required rows={5} value={draft.instructions} onChange={e=>change('instructions',e.target.value)}/></label><Pick label="تکرار" value={draft.cadence} items={ [['once','یک‌باره'],['daily','روزانه'],['weekly','هفتگی'],['monthly','ماهیانه شمسی']] } onChange={v=>change('cadence',v)}/><Pick label="مدرک لازم" value={draft.evidence} items={ [['text','پاسخ متنی'],['file','فایل و توضیح']] } onChange={v=>change('evidence',v)}/><SolarDate label="تاریخ شروع" value={draft.startDate} onChange={v=>change('startDate',v)}/><label className="field">ساعت مهلت به وقت تهران<input type="time" required value={draft.time} onChange={e=>change('time',e.target.value)}/></label>{draft.cadence==='daily'&&<fieldset className="wide"><legend>روزهای کاری</legend>{dayNames.map((name,i)=><label className="flow-check" key={name}><Checkbox checked={draft.weekdays.includes(i)} onCheckedChange={v=>change('weekdays',v?[...draft.weekdays,i]:draft.weekdays.filter((d:number)=>d!==i))}/>{name}</label>)}</fieldset>}{draft.cadence==='weekly'&&<Pick label="روز هفته" value={String(draft.weekday)} items={dayNames.map((n,i)=>[String(i),n])} onChange={v=>change('weekday',Number(v))}/>} {draft.cadence==='monthly'&&<label className="field">روز ماه شمسی (در ماه کوتاه، روز آخر)<input type="number" min={1} max={31} value={draft.monthDay} onChange={e=>change('monthDay',Number(e.target.value))}/></label>}{[['remindHours','فاصله یادآوری پس از تأخیر (ساعت)',4,168],['escalateHours','ارجاع تأخیر به بررسی‌کننده پس از (ساعت)',1,720]].map(([key,label,min,max])=><label className="field" key={key}>{label}<input type="number" min={Number(min)} max={Number(max)} value={draft[key]} onChange={e=>change(String(key),Number(e.target.value))}/></label>)}<Pick label="بخش مرتبط" value={draft.sourceSection||'none'} items={ [['transport','تدارکات و حمل‌ونقل'],['after-sales','خدمات پس از فروش'],['sourcing','برنامه تولید و تأمین'],['none','بدون بخش'],['finance-control','کنترل مالی'],['fulfillment','محصول نهایی و ارسال'],['flow','گردش مواد'],['inventory','موجودی'],['product','محصولات']] } onChange={v=>change('sourceSection',v==='none'?'':v)}/></>}
 {draft.mode==='template'&&<p className="notice wide">فعال‌سازی برنامه متوقف‌شده از تاریخ شروع امروز یا آینده است؛ وظایف قدیمی تغییر نمی‌کنند. برای کم‌کردن برنامه‌ها، تیک فعال را بردارید.</p>}
 {!draft.task&&<label className="flow-check"><Checkbox checked={draft.active} onCheckedChange={v=>{change('active',v===true);if(v===true&&draft.mode==='template'&&draft.startDate<tehranDay())change('startDate',tehranDay());}}/>فعال</label>}
 {draft.task&&<><p className="wide">{draft.task.data.instructions}</p>{!['completed','cancelled'].includes(draft.task.state)&&<><Pick label="اقدام" value={draft.mode} items={actions} onChange={v=>change('mode',v)}/><label className="field wide">پاسخ / توضیح اقدام<textarea required rows={4} value={draft.note} onChange={e=>change('note',e.target.value)}/></label>{draft.mode==='extend'&&<><SolarDate label="مهلت جدید" value={draft.dueDay} onChange={v=>change('dueDay',v)}/><label className="field">ساعت<input type="time" value={draft.dueTime} onChange={e=>change('dueTime',e.target.value)}/></label></>}{draft.mode==='reassign'&&<Pick label="مسئول جدید" value={draft.assignee} items={members.filter((m:any)=>m.status==='active').map((m:any)=>[m.id,m.name])} onChange={v=>change('assignee',v)}/>}</>}<div className="wide"><h3>مدارک</h3>{files.map(f=><p key={f.id}><a className="link" href={'/api/tasks/files?task='+encodeURIComponent(draft.taskId)+'&id='+encodeURIComponent(f.id)}>{f.filename}</a></p>)}{['open','blocked'].includes(draft.task.state)&&(data.isAdmin||draft.task.assignee===data.memberId)&&<label className="field">بارگذاری مدرک (تا ۲۰ مگابایت)<input type="file" accept=".xlsx,.xls,.csv,.pdf,.png,.jpg,.jpeg,.docx,.zip" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value=''}}/></label>}<details><summary>سابقه پیگیری</summary>{draft.task.data.history.map((h:any,i:number)=><p key={i}>{h.name} · {fa(h.at)} · {modes[h.mode]||h.mode}: {h.note}</p>)}</details></div></>}
 </div>{error&&<p className="notice error" role="alert">{error}</p>}<div className="tools" style={{marginTop:18}}>{(!draft.task||!['completed','cancelled'].includes(draft.task.state)&&actions.length>0)&&<button className="btn primary" disabled={busy}>ثبت</button>}<button className="btn" type="button" onClick={()=>setDraft(null)}>بستن</button></div></fieldset></form>}</DialogContent></Dialog></section>;
}
