'use client';
import {IconSections,IconActions} from "./program-workspace";
import {ProgramWorkspace,SubprogramNavigation} from "./program-workspace";
import {formatDate,localDay} from '@/lib/persian-date';
import {useEffect,useRef,useState} from 'react';
import {Truck,Plus,RefreshCw,Upload,ArrowRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {SolarDate} from './solar-date';
import {transportForms,transportActions,transportStates,transportKinds,transportBlockerReasons,transportChecklistLabels} from '@/lib/transport-contract';
import {TransportDraftPanel} from './transport-draft-panel';
import {saveTransportDraft,removeTransportDraft,type TransportDraft} from '@/lib/transport-drafts';
import './transport-driver.css';
import type {Session} from '@/lib/permissions';
const today=()=>localDay(),fa=(n:any)=>Number(n).toLocaleString('fa-IR'),date=(s:string)=>s?formatDate(s):'—';
const purposes:Record<string,string>={waybill:'بارنامه',receipt:'رسید تحویل',condition:'وضعیت / آسیب بسته',expense:'رسید هزینه'};
export function TransportPanel({user,demo,targetId=''}:{targetId?:string;user:Session;demo:boolean}){
 const [data,setData]=useState<any>(null),[detail,setDetail]=useState<any>(null),[selected,setSelected]=useState(''),[tab,setTab]=useState('missions'),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[unitFilter,setUnitFilter]=useState(''),[draft,setDraft]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[purpose,setPurpose]=useState('waybill');const seq=useRef(0),accountEpoch=useRef(0);
 const [online,setOnline]=useState(true);
 useEffect(()=>{const update=()=>setOnline(navigator.onLine);update();window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update)}},[]);
 useEffect(()=>{accountEpoch.current++;setDraft(null);setData(null);setDetail(null);setSelected('');setMessage('');setError('');setBusy(false);setTab(user.permissions.transportRoles?.includes('driver')?'today':'missions');return()=>{accountEpoch.current++}},[user.userId]);
 async function read(extra=''){const r=await fetch('/api/transport'+extra,{cache:'no-store',headers:{'X-Transport-Account':user.userId}}),d=await r.json() as any;if(!r.ok)throw Error(d.error);return d;}
 async function refresh(id=selected){const n=++seq.current;try{const [d,m]=await Promise.all([read(),id?read('?id='+encodeURIComponent(id)):Promise.resolve(null)]);if(n!==seq.current)return;setData(d);setDetail(m);if(m)setPurpose(d.roles.driver||d.roles.manager?'waybill':'receipt');setError('');}catch(e){if(n===seq.current)setError((e as Error).message);}}
 useEffect(()=>{if(!demo){setSelected(targetId);void refresh(targetId);}return()=>{seq.current++}},[demo,user.userId,targetId]);
 function start(mode:string,row?:any){const v:any={id:crypto.randomUUID(),mode};for(const f of transportForms[mode])v[f.key]=f.type==='boolean'?mode!=='checklist':f.type==='date'?today():f.type==='number'?(f.optional?'':'1'):f.options?.[0]?.[0]||'';if(row){v.revision=row.revision;if(mode==='vehicle'){Object.assign(v,row.data);v.vehicleId=row.id;}else {v.missionId=row.id;v.packages=String(row.data.packages);v.due=row.data.due;v.carrier=row.data.carrier||'';v.waybill=row.data.waybill||'';v.tracking=row.data.tracking||'';v.driverId=row.data.driverId||'';v.vehicleId=row.data.vehicleId||'';v.receiverId=row.data.receiverId||'';}}setDraft(v);setError('');}
 function change(k:string,v:any){setDraft((d:any)=>{const next={...d,[k]:v};if(k==='sourceKey'){const s=data.sources.find((s:any)=>s.key===v);if(s){const inbound=['purchase_order','as_claim','as_case'].includes(s.kind);Object.assign(next,{recipient:inbound?(s.kind==='purchase_order'?'انبار قرنطینه':'پذیرش / انبار خدمات'):s.name,phone:s.phone||'',pickup:inbound?(s.address||s.name):'انبار شرکت',destination:inbound?(s.kind==='purchase_order'?'انبار قرنطینه شرکت':'دفتر خدمات / محل دریافت داغی'):s.address});}}return next;});}
 function options(source:string):string[][]{if(source==='sources')return (data?.sources||[]).map((s:any)=>[s.key,transportKinds[s.kind]+' · '+(s.name||'بدون نام')+' · '+s.items.map((i:any)=>i.serial||i.partCode).join('، ')+' · '+s.id.slice(0,8)]);if(source==='expenses')return (detail?.mission.data.expenses||[]).filter((e:any)=>e.state==='pending').map((e:any)=>[e.id,fa(e.amountRial)+' ریال · '+e.reference]);return (data?.[source]||[]).map((x:any)=>[x.id,x.name||x.data.name+(x.data.plate?' · '+x.data.plate:'')]);}
 const offlineModes=['checklist','collect','carrier','offer','documents','expense','blocker','blocker_resolve','vehicle_report'];
 async function keepDraft(value=draft){if(!value?.missionId)throw Error('پیش‌نویس برای مأموریت مشخص لازم است.');await saveTransportDraft({id:value.id,kind:'operation',accountId:user.userId,missionId:value.missionId,missionCode:detail?.mission.data.code||value.missionId,createdAt:Date.now(),payload:value});window.dispatchEvent(new Event('nafasyar-transport-drafts'));}
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;const current=accountEpoch.current,value={...draft};setBusy(true);setError('');try{
  if(offlineModes.includes(value.mode)){try{await keepDraft(value)}catch(e){if(!navigator.onLine)throw e}}if(current!==accountEpoch.current)return;
  if(!navigator.onLine){if(!offlineModes.includes(value.mode))throw Error('این عملیات نیاز به اتصال دارد.');setMessage('پیش‌نویس ذخیره شد؛ پس از اتصال از «پیش‌نویس‌ها» ارسال کنید.');setDraft(null);return;}
  const r=await fetch('/api/transport',{method:'POST',headers:{'Content-Type':'application/json','X-Transport-Account':user.userId},body:JSON.stringify(value)}),d=await r.json() as any;if(!r.ok)throw Error(d.error);if(offlineModes.includes(value.mode))await removeTransportDraft(user.userId,value.id).catch(()=>{});if(current!==accountEpoch.current)return;window.dispatchEvent(new Event('nafasyar-transport-drafts'));setDraft(null);setMessage(d.followupPending?'عملیات ثبت شد؛ کارتابل در نوبت بعد به‌روز می‌شود.':'عملیات ثبت شد.');const id=['vehicle','link_party'].includes(value.mode)?selected:d.id||value.missionId;setSelected(id);await refresh(id);
 }catch(e){if(current===accountEpoch.current)setError((e as Error).message+(offlineModes.includes(value.mode)?' متن فرم حفظ شد؛ پیش‌نویس‌ها را بررسی کنید.':''))}finally{if(current===accountEpoch.current)setBusy(false)}}
 async function reviewDraft(row:TransportDraft){const current=accountEpoch.current,full=await read('?id='+encodeURIComponent(row.missionId));if(current!==accountEpoch.current)return;setSelected(row.missionId);setDetail(full);setTab('missions');setDraft({...row.payload});setMessage('وضعیت جدید خوانده شد؛ اطلاعات پیش‌نویس را بازبینی و سپس ثبت کنید.');}
 async function upload(file:File|null){if(!file||!selected||busy)return;const current=accountEpoch.current,id=crypto.randomUUID(),missionId=selected;setBusy(true);setError('');try{try{await saveTransportDraft({id,kind:'file',accountId:user.userId,missionId,missionCode:detail?.mission.data.code||missionId,createdAt:Date.now(),file,purpose,revision:detail?.mission.revision})}catch(e){if(!navigator.onLine)throw e}if(current!==accountEpoch.current)return;window.dispatchEvent(new Event('nafasyar-transport-drafts'));if(!navigator.onLine){setMessage('مدرک در پیش‌نویس‌ها ذخیره شد؛ هنوز به سرور ارسال نشده.');return}const f=new FormData();f.append('file',file);const r=await fetch('/api/transport/files?'+new URLSearchParams({mission:missionId,purpose,requestId:id,revision:String(detail?.mission.revision)}),{method:'POST',headers:{'X-Transport-Account':user.userId},body:f}),d=await r.json() as any;if(!r.ok)throw Error(d.error);await removeTransportDraft(user.userId,id).catch(()=>{});if(current!==accountEpoch.current)return;window.dispatchEvent(new Event('nafasyar-transport-drafts'));setMessage('مدرک بارگذاری شد.');await refresh(missionId)}catch(e){if(current===accountEpoch.current)setError((e as Error).message+' مدرک ارسال‌نشده را در پیش‌نویس‌ها بررسی کنید.')}finally{if(current===accountEpoch.current)setBusy(false)}}
 if(demo)return <div className="notice">تدارکات با اطلاعات واقعی حساب شما کار می‌کند؛ از حالت نمونه خارج شوید.</div>;
 const m=detail?.mission,d=m?.data,manager=data?.roles.manager,driver=d&&(user.isAdmin||data?.roles.driver&&d.driverId===data.me),receiver=d&&(user.isAdmin||d.inbound&&d.receiverId===data?.me||!d.inbound&&(data?.roles.agent&&d.agentId===user.permissions.serviceAgentId||manager&&!d.agentId));
 const actions:string[]=[];if(d){if(manager&&['requested','assigned'].includes(d.state))actions.push('assign','cancel');if(driver&&d.state==='assigned')actions.push('checklist','collect');if(driver&&d.state==='collected')actions.push(d.inbound||d.route==='direct'?'offer':'carrier');if(driver&&d.route==='carrier'&&d.state!=='cancelled')actions.push('documents');if(receiver&&['carrier','offered'].includes(d.state))actions.push('receipt');if(manager&&d.state==='disputed')actions.push('resolve');if(driver&&d.state!=='cancelled')actions.push('expense');if(driver&&!['delivered','cancelled'].includes(d.state))actions.push(d.blocker?.state==='open'?'blocker_resolve':'blocker');if(manager&&d.blocker?.state==='open'&&!driver)actions.push('blocker_resolve');if(driver&&d.vehicleId&&d.state!=='cancelled')actions.push('vehicle_report');if(data?.roles.finance&&d.expenses?.some((e:any)=>e.state==='pending'))actions.push('expense_review');}
 const driverWorkspace=!!data?.roles.driver||!!user.permissions.transportRoles?.includes('driver')||!!user.permissions.flowRoles?.includes('logistics');
 const tabTitles:Record<string,string>={today:'کارهای امروز',collect:'دریافت بار',deliver:'تحویل بار',documents:'مدارک',expenses:'هزینه‌های من',followups:'پیگیری‌ها',missions:'همه مأموریت‌ها','vehicle-reports':'گزارش خودرو',drafts:'پیش‌نویس‌ها',vehicles:'خودروها'};
 const scopeMissions=(data?.missions||[]).filter((m:any)=>{const d=m.data,active=!['delivered','cancelled'].includes(d.state);if(tab==='today')return active&&(d.due<=today()||['collected','carrier','offered'].includes(d.state));if(tab==='collect')return d.state==='assigned';if(tab==='deliver')return ['collected','carrier','offered'].includes(d.state);if(tab==='documents')return d.state!=='cancelled';if(tab==='expenses')return d.state!=='cancelled';if(tab==='followups')return d.blocker?.state==='open'||d.state==='disputed'||d.missingDocuments||active&&d.due<today();return true;});
 const missions=scopeMissions.filter((m:any)=>(!filter||m.data.state===filter)&&(!unitFilter||m.data.requestingUnit===unitFilter)&&(!query||JSON.stringify(m.data).toLowerCase().includes(query.toLowerCase())));
 return <ProgramWorkspace programId="transport" direct={!!targetId} title="کارهای تدارکات و راننده"><section><div className="panelhead"><div><h2><Truck size={24}/> تدارکات و حمل‌ونقل</h2><p className="subtle">یک کارتابل مشترک برای فروش، خدمات خانگی، بیمارستانی و دریافت خرید</p></div><IconActions scope="transport-panel-actions-79748fa74d"><button className="btn" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={16}/>تازه‌سازی</button>{!!data?.sources.length&&<button className="btn primary" onClick={()=>start('create')}><Plus size={16}/>درخواست حمل</button>}</IconActions></div>
 {error&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}
 <div className="tools"><SubprogramNavigation items={(driverWorkspace?["today","collect","deliver","documents","expenses","followups","missions","vehicle-reports","drafts"]:["missions",...(manager?["vehicles","followups","vehicle-reports"]:[]),"drafts"]).map(key=>[key,tabTitles[key]] as [string,string])} value={tab} onChange={key=>{setTab(key);setSelected('');setDetail(null);setFilter('')}}/>{manager&&<button className="btn" onClick={()=>start("link_party")}>اتصال گیرنده فروش به نمایندگی</button>}</div>
 {!online&&<p className="notice" role="status">اتصال قطع است؛ متن و عکس را در پیش‌نویس‌ها نگه دارید و بعداً ارسال کنید.</p>}
 {tab==='drafts'?<TransportDraftPanel accountId={user.userId} onReview={reviewDraft} onSent={()=>void refresh()}/>:!data?<p>در حال دریافت…</p>:tab==='vehicle-reports'?<section><h2>گزارش خودرو</h2><p>گزارش را از مأموریت مرتبط ثبت کنید. رسید سوخت به‌تنهایی هزینهٔ تأییدشده یا پرداخت نیست.</p>{!(data.vehicleReports||[]).length&&<p className="empty">گزارشی ثبت نشده است.</p>}{(data.vehicleReports||[]).map((r:any)=><article className="flow-card" key={r.id}><h3>{r.vehicleName} · {r.missionCode}</h3><p>{date(r.day)} · {r.kind==='fault'?'خرابی':r.kind==='fuel'?'سوخت‌گیری':'قرائت کیلومتر'}</p>{r.odometer!==undefined&&<p>{fa(r.odometer)} کیلومتر</p>}{r.fuelLitres!==undefined&&<p>{fa(r.fuelLitres)} لیتر · {fa(r.fuelCostRial)} ریال · {r.reference}</p>}<p>{r.notes}</p><button className="btn" onClick={()=>{setTab('missions');setSelected(r.missionId);void refresh(r.missionId)}}>بازکردن مأموریت</button></article>)}</section>:tab==='vehicles'?<div className="panel"><div className="panelhead"><h3>خودروهای شرکت</h3><button className="btn primary" onClick={()=>start('vehicle')}>تعریف خودرو</button></div>{data.vehicles.map((v:any)=><div className="notice" key={v.id}><div><strong>{v.data.name} · {v.data.plate}</strong><p>{v.data.active?'فعال':'غیرفعال'}</p></div><button className="btn" onClick={()=>start('vehicle',v)}>ویرایش</button></div>)}</div>:d?<div className="panel"><button className="link" onClick={()=>{setSelected('');setDetail(null);}}><ArrowRight size={16}/>بازگشت به فهرست</button><div className="panelhead"><div><h3 dir="ltr">{d.code}</h3><p>{d.requestingUnit} · {transportKinds[d.kind]} · {transportStates[d.state]}</p></div><span className={'badge '+(d.missingDocuments?'bad':'')}>{d.missingDocuments?'مدرک بارنامه ناقص':'موعد: '+date(d.due)}</span></div>
 <div className="transport-contact tools">{d.phone&&<a className="btn" href={'tel:'+d.phone.replace(/[^+0-9]/g,'')}>تماس با مقصد</a>}{d.pickup&&<a className="btn" href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(d.pickup)} target="_blank" rel="noreferrer">نقشهٔ مبدأ</a>}{d.destination&&<a className="btn" href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(d.destination)} target="_blank" rel="noreferrer">نقشهٔ مقصد</a>}</div>
 {d.blocker?.state==='open'&&<p className="notice error">مانع: {transportBlockerReasons[d.blocker.reason]} · پیگیری {date(d.blocker.retryDay)} · {d.blocker.notes}</p>}{d.checklist&&<div className="notice"><strong>چک‌لیست بررسی‌شده</strong><p>{Object.entries(transportChecklistLabels).filter(([key])=>d.checklist[key]).map(([,label])=>label).join(' · ')}</p></div>}
 <div className="formgrid">{[['واحد درخواست‌کننده',d.requestingUnit],['مبدأ',d.pickup],['مقصد',d.destination],['تحویل‌گیرنده',d.recipient],['تلفن',d.phone],['تعداد بسته',fa(d.packages)],['راننده',d.driverName||'تعیین نشده'],['خودرو',d.vehicleName||'تعیین نشده'],['باربری',d.carrier||'—'],['بارنامه',d.waybill||'—'],['کد رهگیری',d.tracking||'—']].map(([k,v])=><div className="kv" key={k}><p>{k}</p><strong>{v}</strong></div>)}</div><p>{d.notes}</p>{d.kind==='purchase_order'&&<p className="notice">دریافت این مأموریت فقط تحویل فیزیکی بسته‌هاست؛ مقدار واقعی، بچ و رسید قرنطینه باید از مسیر دریافت خرید ثبت شود.</p>}<IconSections scope="transport-panel-sections-f3b1bddfe3" items={[{key:"محتویات محموله",title:"محتویات محموله",content:<><h4>محتویات محموله</h4>{d.items.map((i:any,n:number)=><p key={n}>{i.serial||i.partCode} {i.model||''} · تعداد {fa(i.quantity)}{i.batchId?' · بچ '+i.batchId:''}</p>)}<IconActions scope="transport-panel-actions-27b064f5c9">{actions.map(a=><button className="btn primary" disabled={busy} key={a} onClick={()=>start(a,m)}>{transportActions[a]}</button>)}</IconActions>{d.state==='disputed'&&<p className="notice error">دریافت دارای مغایرت است. موجودی مقصد یا تأیید داغی ثبت نشده؛ بررسی و تأیید دریافت مجدد لازم است.</p>}</>},{key:"مدارک حمل",title:"مدارک حمل",content:<><h4>مدارک حمل</h4>{detail.files.map((f:any)=><p key={f.id}><a href={'/api/transport/files?mission='+m.id+'&id='+f.id} target="_blank" rel="noreferrer">{purposes[f.data.purpose]} · {f.data.filename}</a></p>)}{(manager||driver||receiver||data.roles.agent)&&d.state!=='cancelled'&&<div className="tools"><label className="field"><span>نوع مدرک</span><select aria-label="نوع مدرک" value={purpose} onChange={e=>setPurpose(e.target.value)}>{Object.entries(purposes).filter(([k])=>!data.roles.agent||['waybill','receipt','condition'].includes(k)).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="btn"><Upload size={16}/>بارگذاری مدرک<input type="file" accept=".jpg,.jpeg,.png,.webp,.pdf" capture="environment" disabled={busy} onChange={e=>void upload(e.target.files?.[0]||null)} style={{maxWidth:220}}/></label><span className="subtle">حداکثر ۱۰ مگابایت</span></div>}{!!d.expenses?.length&&<><h4>هزینه‌های حمل</h4>{d.expenses.map((e:any)=><p key={e.id}>{fa(e.amountRial)} ریال · {e.reference} · {e.state==='pending'?'در انتظار مالی':e.state==='approved'?'تأیید شد':'رد شد'} · {e.reviewNotes||e.notes}</p>)}</>}</>},{key:"سابقه تحویل و پیگیری",title:"سابقه تحویل و پیگیری",content:<><h4>سابقه تحویل و پیگیری</h4>{d.history.map((h:any,i:number)=><div className="notice" key={i}><div><strong>{transportActions[h.mode]|| (h.mode==='file'?'بارگذاری مدرک':h.mode)} · {date(h.at)}{h.actorName?' · '+h.actorName:''}</strong><p>{h.notes||h.filename}{h.result?' · '+({complete:'کامل',shortage:'کسری',damage:'آسیب'} as any)[h.result]:''}</p></div></div>)}<p className="subtle">وضعیت‌ها براساس ثبت مسئولان هستند؛ اتصال خودکار به سامانهٔ باربری فعال نیست.</p></>}]}/></div>:<>
 <h3>{tabTitles[tab]}</h3><div className="notice">{fa(data.missions.filter((m:any)=>!['delivered','cancelled'].includes(m.data.state)&&m.data.due<today()).length)} مأموریت عقب‌افتاده · {fa(data.missions.filter((m:any)=>m.data.missingDocuments).length)} بارنامه ناقص</div><div className="tools" style={{margin:'16px 0'}}><label className="field"><span>جستجوی حمل</span><input aria-label="جستجوی حمل" placeholder="کد حمل، سریال، نماینده یا بارنامه…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="field"><span>وضعیت حمل</span><select aria-label="وضعیت حمل" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">همه وضعیت‌ها</option>{Object.entries(transportStates).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field"><span>واحد درخواست‌کننده</span><select aria-label="واحد درخواست‌کننده" value={unitFilter} onChange={e=>setUnitFilter(e.target.value)}><option value="">همه واحدها</option>{['فروش','خدمات خانگی','خدمات بیمارستانی','بازرگانی داخلی','بازرگانی خارجی'].map(x=><option key={x}>{x}</option>)}</select></label></div>
 {!missions.length&&<div className="empty">مأموریتی در این فهرست نیست. درخواست حمل از حوالهٔ خارج‌شده، بستهٔ آمادهٔ خدمات پروندهٔ برگشتی یا سفارش خرید صادرشده ایجاد می‌شود.</div>}<div className="transport-grid">{missions.map((m:any)=><button className="panel transport-card" key={m.id} onClick={()=>{setSelected(m.id);void refresh(m.id)}}><strong>{m.data.code} · {transportKinds[m.data.kind]}</strong><p>{m.data.requestingUnit}</p><p>از {m.data.pickup} به {m.data.destination}</p><p>{m.data.recipient} · {fa(m.data.packages)} بسته</p><p>{transportStates[m.data.state]} · موعد {date(m.data.due)}</p>{m.data.blocker?.state==='open'&&<p>مانع: {transportBlockerReasons[m.data.blocker.reason]} · پیگیری {date(m.data.blocker.retryDay)}</p>}{tab==='expenses'&&<p>{fa((m.data.expenses||[]).length)} هزینه · {(m.data.expenses||[]).filter((e:any)=>e.state==='pending').length} منتظر بررسی</p>}{m.data.missingDocuments&&<span className="badge bad">بارنامه ناقص</span>}</button>)}</div></>}
 <Dialog open={!!draft} onOpenChange={v=>{if(!v&&!busy)setDraft(null)}}><DialogContent className="modal sm:max-w-2xl"><DialogTitle>{draft?transportActions[draft.mode]:''}</DialogTitle><DialogDescription>اطلاعات واقعی را ثبت کنید. دریافت محموله، تأیید فنی یا گارانتی آن نیست.</DialogDescription>{draft&&<form onSubmit={save}><div className="formgrid">{transportForms[draft.mode].filter(f=>draft.mode!=='vehicle_report'||!['fuelLitres','fuelCostRial','reference'].includes(f.key)||draft.reportKind==='fuel').map(f=>f.type==='date'?<SolarDate key={f.key} label={f.label} required={!f.optional} value={draft[f.key]} onChange={v=>change(f.key,v)}/>:f.type==='boolean'?<label className="field" key={f.key}><input type="checkbox" checked={draft[f.key]===true} onChange={e=>change(f.key,e.target.checked)}/>{f.label}</label>:<label className={'field '+(f.type==='textarea'?'wide':'')} key={f.key}>{f.label}{f.optional?' (اختیاری)':''}{f.type==='select'?<select required={!f.optional} value={draft[f.key]||''} onChange={e=>change(f.key,e.target.value)}><option value="">انتخاب کنید</option>{(f.options||options(f.source||'')).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select>:f.type==='textarea'?<textarea required={!f.optional} rows={3} maxLength={4000} value={draft[f.key]||''} onChange={e=>change(f.key,e.target.value)}/>:<input required={!f.optional} type={f.type==='number'?'number':'text'} min={['amountRial','odometer'].includes(f.key)?0:1} step={1} maxLength={1000} value={draft[f.key]??''} onChange={e=>change(f.key,e.target.value)}/>}</label>)}</div>{error&&<p className="notice error" role="alert">{error}</p>}<div className="tools" style={{marginTop:20}}><button className="btn primary" disabled={busy}>{busy?'در حال ثبت…':!online&&offlineModes.includes(draft.mode)?'ذخیره پیش‌نویس':'تأیید و ثبت'}</button>{offlineModes.includes(draft.mode)&&<button type="button" className="btn" disabled={busy} onClick={async()=>{try{await keepDraft();setMessage('پیش‌نویس در همین مرورگر ذخیره شد؛ هنوز ارسال نشده.');setDraft(null)}catch(e){setError((e as Error).message)}}}>ذخیره برای بعد</button>}<button type="button" className="btn" disabled={busy} onClick={()=>setDraft(null)}>انصراف</button></div></form>}</DialogContent></Dialog>
 </section></ProgramWorkspace>;
}
