'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {SolarDate} from './solar-date';
import {formatDate,formatDateTime,localDay,latinDigits} from '@/lib/persian-date';
import {IconActions} from './program-workspace';
const titles:Record<string,string>={account:'تعریف بانک / صندوق',approve_account:'تأیید مستقل حساب',request:'درخواست دریافت / پرداخت',approve:'تأیید پرداخت و حساب مقصد',reject:'رد درخواست',cancel:'توقف مانده درخواست',execute:'ثبت اجرای واقعی',statement:'ورود صورتحساب اکسل',match:'تأیید تطبیق بانکی',unmatch:'برگشت تطبیق',check:'ثبت چک',check_issue:'تأیید صدور / دریافت چک',check_settle:'ثبت وصول واقعی چک',check_cancel:'ابطال / برگشت چک',expense:'ثبت هزینه تنخواه',expense_review:'بررسی مستقل هزینه',advance_return:'ثبت برگشت مانده تنخواه'};
const states:Record<string,string>={review:'در انتظار تأیید',active:'فعال',approved:'مصوب',partial:'پرداخت جزئی',paid:'تکمیل اجرا',rejected:'ردشده',cancelled:'متوقف / باطل',issued:'چک باز',settled:'وصول‌شده',imported:'صورتحساب ثبت‌شده'};
const cash=(v:any,c='IRR')=>`${Number(v||0).toLocaleString('fa-IR',{maximumFractionDigits:6})} ${c==='IRR'?'ریال':c}`;
export function TreasuryPanel({demo=false,targetId=''}:{demo?:boolean;targetId?:string}){
 const [data,setData]=useState<any>(null),[tab,setTab]=useState('requests'),[selected,setSelected]=useState(''),[query,setQuery]=useState(''),[mode,setMode]=useState(''),[form,setForm]=useState<any>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[sheet,setSheet]=useState<any[]>([]),[grid,setGrid]=useState<any[][]>([]);
 async function load(){const r=await fetch('/api/treasury',{cache:'no-store'}),d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);}
 useEffect(()=>{if(!demo)void load().catch(e=>setError(e.message));},[demo]);
 useEffect(()=>{if(targetId){setSelected(targetId);setTab('requests');}},[targetId]);
 const record=[...(data?.requests||[]),...(data?.accounts||[]),...(data?.checks||[]),...(data?.expenses||[]),...(data?.statements||[])].find((r:any)=>r.id===selected);
 useEffect(()=>{if(record)setTab(({treasury_request:'requests',treasury_account:'accounts',treasury_check:'checks',treasury_expense:'expenses',treasury_statement:'bank'} as Record<string,string>)[record.type]||'requests');},[record?.type,selected]);
 function start(m:string,r:any=null,extra:any={}){setError('');setMode(m);setSheet([]);setGrid([]);setForm({id:crypto.randomUUID(),entityId:r?.id,revision:r?.revision||0,notes:'',day:localDay(),due:localDay(),from:localDay(),to:localDay(),direction:'out',category:'expense',currency:'IRR',kind:'bank',opening:'0',closing:'0',accountId:data?.accounts.find((a:any)=>a.data.state==='active')?.id||'',amount:r?.remaining||r?.data?.amount||'',accepted:true,...extra});}
 const change=(k:string,v:any)=>setForm((f:any)=>({...f,[k]:v}));
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/treasury',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,mode,confirmed:true,...(mode==='statement'?{rows:sheet}:{})})}),d:any=await r.json();if(!r.ok)throw Error(d.error);setMessage('ثبت شد؛ نتیجه در پرونده و تاریخچه نمایش داده می‌شود.');setSelected(d.id);setMode('');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(file:File){if(!record)return;setBusy(true);try{const q=new URLSearchParams({id:crypto.randomUUID(),caseId:record.id,filename:file.name}),r=await fetch('/api/treasury/files?'+q,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file}),d:any=await r.json();if(!r.ok)throw Error(d.error);setMessage('مدرک بارگذاری شد.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function readSheet(file:File){setError('');setSheet([]);try{if(file.size>10*1024*1024)throw Error('حداکثر حجم اکسل ۱۰ مگابایت است.');const read=(await import('read-excel-file/browser')).readSheet,rows=await read(file);if(rows.length>1001)throw Error('حداکثر ۱۰۰۰ ردیف در هر فایل.');setGrid(rows as any[][]);change('filename',file.name);}catch(e){setError((e as Error).message);}}
 function preview(){try{const rows=grid.slice(1).filter(r=>r.some(v=>v!==null&&v!=='')),entries=rows.map((r,n)=>{const day=r[0] instanceof Date?r[0].toISOString().slice(0,10):latinDigits(String(r[0]||'')).trim(),bankId=String(r[1]||'').trim(),reference=String(r[2]||'').trim(),incoming=latinDigits(String(r[3]??'0')).trim(),outgoing=latinDigits(String(r[4]??'0')).trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(day)||!bankId||![incoming,outgoing].every(v=>/^\d{1,15}(\.\d{1,6})?$/.test(v))||(Number(incoming)>0)===(Number(outgoing)>0))throw Error(`ردیف ${n+2}: تاریخ، شناسه بانک و یک مبلغ دریافت یا پرداخت معتبر لازم است.`);return {day,bankId,reference,amount:Number(incoming)>0?incoming:outgoing,direction:Number(incoming)>0?'in':'out',description:String(r[5]||'')};});if(!entries.length)throw Error('صورتحساب خالی است.');setSheet(entries);setError('');}catch(e){setError((e as Error).message);}}
 const input=(k:string,label:string,required=true)=><label className="field" key={k}>{label}<input required={required} value={form[k]||''} onChange={e=>change(k,latinDigits(e.target.value))}/></label>;
 const select=(k:string,label:string,items:Record<string,string>,required=true)=><label className="field" key={k}>{label}<select required={required} value={form[k]??''} onChange={e=>change(k,e.target.value)}><option value="">انتخاب کنید</option>{Object.entries(items).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>;
 const date=(k:string,label:string)=><SolarDate key={k} label={label} value={form[k]||''} onChange={v=>change(k,v)}/>;
 const accountItems=Object.fromEntries((data?.accounts||[]).filter((a:any)=>a.data.state==='active').map((a:any)=>[a.id,a.data.title+' — '+a.data.currency]));
 const requestItems=Object.fromEntries((data?.requests||[]).filter((r:any)=>['approved','partial'].includes(r.data.state)&&r.data.direction==='out').map((r:any)=>[r.id,r.data.title+' — '+cash(r.remaining,r.data.currency)]));
 const files=(data?.files||[]).filter((f:any)=>f.caseId===form.entityId);
 const proof=()=>select('fileId','مدرک بارگذاری‌شده همین پرونده',Object.fromEntries(files.map((f:any)=>[f.id,f.filename])));
 const button=(m:string,r?:any,extra?:any)=><button type="button" className="btn" disabled={busy||demo} onClick={()=>start(m,r,extra)}>{titles[m]}</button>;
 const filtered=(a:any[])=>a.filter(r=>JSON.stringify([r.data.title,r.data.party,r.data.number,r.data.reference,r.data.state,r.data.referenceDocument,r.data.destination,r.data.currency]).includes(query));
 return <section className="panel" dir="rtl"><div className="panelhead"><h2>خزانه‌داری</h2><button className="btn" disabled={busy||demo} onClick={()=>void load().catch(e=>setError(e.message))}>تازه‌سازی</button></div>{demo?<p>خزانه‌داری فقط در محیط شرکت فعال است.</p>:!data&&!error?<p role="status">در حال دریافت…</p>:null}{error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 {data&&<><p className="footnote">مدیر مالی: تأیید · خزانه‌دار: اجرا · مدیر حسابداری: تطبیق مستقل. سمت‌ها و مجوز نوشتن مالی را در تنظیمات کاربران و سمت‌ها تعیین کنید.</p><div className="grid"><div className="card">در انتظار تأیید: {data.requests.filter((r:any)=>r.data.state==='review').length}</div><div className="card">پرداخت معوق: {data.requests.filter((r:any)=>r.overdue).length}</div><div className="card">چک باز: {data.checks.filter((r:any)=>r.data.state==='issued').length}</div><div className="card">بانک بدون تطبیق: {data.bankRows.filter((r:any)=>!r.match).length} · دفتر بدون تطبیق: {data.unmatched.length}</div></div>
 <IconActions scope="treasury-create">{data.roles.write&&button('request')}{data.roles.treasury&&<>{button('account')}{button('statement')}{button('check')}</>}{data.roles.write&&button('expense')}</IconActions>
 <nav aria-label="بخش‌های خزانه" style={{display:'flex',gap:8,flexWrap:'wrap',margin:'16px 0'}}>{Object.entries({requests:'دریافت و پرداخت',accounts:'بانک و صندوق',bank:'تطبیق بانک',checks:'چک‌ها',expenses:'تنخواه',forecast:'پیش‌بینی نقدینگی'}).map(([k,l])=><button key={k} className={'btn '+(tab===k?'primary':'')} onClick={()=>{setTab(k);setSelected('')}}>{l}</button>)}</nav>
 <label className="field">جست‌وجو<input value={query} onChange={e=>setQuery(e.target.value)}/></label>
 {tab==='requests'&&<div style={{overflowX:'auto'}}><table><thead><tr><th>درخواست / طرف حساب</th><th>موعد</th><th>مبلغ / مانده</th><th>وضعیت</th><th>پرونده</th></tr></thead><tbody>{filtered(data.requests).map(r=><tr key={r.id}><td>{r.data.title}<br/>{r.data.party} · {r.data.direction==='out'?'پرداخت':'دریافت'}</td><td>{formatDate(r.data.due)}{r.overdue&&' — معوق'}</td><td>{cash(r.data.amount,r.data.currency)}<br/>مانده: {cash(r.remaining,r.data.currency)} · رزرو چک: {cash(r.reserved,r.data.currency)}</td><td>{states[r.data.state]}</td><td><button className="btn" onClick={()=>setSelected(r.id)}>باز کردن</button></td></tr>)}</tbody></table>{!data.requests.length&&<p className="empty">درخواستی ثبت نشده است.</p>}</div>}
 {tab==='accounts'&&<div className="grid">{filtered(data.accounts).map(a=><article className="card" key={a.id}><h3>{a.data.title}</h3><p>{a.data.number} · {states[a.data.state]}</p><p>مانده دفتر: {cash(a.ledger,a.data.currency)}</p><p>آخرین صورتحساب: {a.latestStatement?`${cash(a.latestStatement.closing,a.data.currency)} — ${formatDate(a.latestStatement.to)}`:'وارد نشده'}</p>{a.data.state==='review'&&data.roles.manager&&button('approve_account',a)}</article>)}</div>}
 {tab==='bank'&&<><p>پیشنهاد بر اساس حساب، مبلغ، جهت، تاریخ و مرجع یکسان است. تأیید نهایی مستقل لازم است.</p><div style={{overflowX:'auto'}}><table><thead><tr><th>تاریخ / شناسه بانک</th><th>مرجع / شرح</th><th>مبلغ</th><th>تطبیق</th></tr></thead><tbody>{data.bankRows.filter((r:any)=>JSON.stringify([r.reference,r.description,r.bankId]).includes(query)).map((r:any)=>{const s=data.statements.find((s:any)=>s.id===r.statementId);return <tr key={r.id}><td>{formatDate(r.day)}<br/>{r.bankId}</td><td>{r.reference||'بدون مرجع'}<br/>{r.description}</td><td>{r.direction==='in'?'دریافت':'پرداخت'} {cash(r.amount,r.currency)}</td><td>{r.match?<>{`تأیید شده ${formatDateTime(r.match.at)}`}{data.roles.accountant&&button('unmatch',s,{rowId:r.id})}</>:<>{r.candidates.length===1?'یک پیشنهاد منطبق':r.candidates.length?'چند پیشنهاد؛ بررسی لازم است':'بدون پیشنهاد'}{data.roles.accountant&&button('match',s,{rowId:r.id,movementId:r.candidates.length===1?r.candidates[0].id:''})}</>}</td></tr>})}</tbody></table></div><h3>گردش دفتر بدون تطبیق</h3>{data.unmatched.map((m:any)=><p key={m.id}>{formatDate(m.data.day)} — {m.data.party} — {m.data.reference} — {cash(m.data.amount,m.data.currency)}</p>)}</>}
 {tab==='checks'&&<div className="grid">{filtered(data.checks).map(c=><article className="card" key={c.id}><h3>چک {c.data.number} — {c.data.bank}</h3><p>{c.data.party} · {cash(c.data.amount,c.data.currency)}</p><p>{formatDate(c.data.due)} · {states[c.data.state]}{c.data.state==='issued'&&c.data.due<localDay()?' — معوق':''}</p><p>محل نگهداری: {c.data.location}</p><button className="btn" onClick={()=>setSelected(c.id)}>باز کردن</button></article>)}</div>}
 {tab==='expenses'&&<><h3>تنخواه‌های پرداخت‌شده</h3>{data.requests.filter((r:any)=>r.data.category==='advance'&&Number(r.paid)>0).map((r:any)=>{const used=data.expenses.filter((e:any)=>e.data.requestId===r.id&&e.data.state==='approved').reduce((n:number,e:any)=>n+Number(e.data.amount),0),returned=data.movements.filter((m:any)=>m.data.requestId===r.id&&m.data.kind==='advance_return').reduce((n:number,m:any)=>n+Number(m.data.amount),0);return <article className="card" key={r.id}><strong>{r.data.title} — {r.data.party}</strong><p>تحویل: {cash(r.paid,r.data.currency)} · هزینه تأییدشده: {cash(used,r.data.currency)} · برگشت: {cash(returned,r.data.currency)} · مانده تسویه: {cash(Number(r.paid)-used-returned,r.data.currency)}</p><button className="btn" onClick={()=>setSelected(r.id)}>پرونده</button></article>})}<h3>هزینه‌ها</h3>{filtered(data.expenses).map(e=><p key={e.id}>{e.data.title} — {cash(e.data.amount,e.data.currency)} — {states[e.data.state]} <button className="btn" onClick={()=>setSelected(e.id)}>باز کردن</button></p>)}</>}
 {tab==='forecast'&&<><p>بر پایه مانده دفتر و درخواست‌های مصوب؛ شامل معوقات است. چک‌های رزروشده دوباره جمع نمی‌شوند. حقوق و تعهداتی که وارد این دفتر نشده‌اند در برآورد نیستند.</p><div className="grid">{data.forecast.map((f:any)=><article className="card" key={f.days}><h3>{f.days} روز آینده</h3>{f.currencies.map((c:any)=><div key={c.currency}><strong>{c.currency}</strong><p>موجودی دفتر: {cash(c.opening,c.currency)}</p><p>دریافت مورد انتظار: {cash(c.in,c.currency)} · پرداخت: {cash(c.out,c.currency)}</p><p>مانده برآوردی: {cash(c.projected,c.currency)}</p></div>)}</article>)}</div></>}
 {record&&<section className="card" aria-label="پرونده خزانه"><h3>{record.data.title||record.data.number} — {states[record.data.state]}</h3>{record.type==='treasury_request'&&<><p>ذی‌نفع: {record.data.party} · حساب مقصد: {record.data.destination}</p><p>مرجع: {record.data.referenceDocument}</p>{record.data.source&&<p>خرید مرتبط: {record.data.source.title}</p>}<IconActions scope="treasury-request">{record.data.state==='review'&&data.roles.manager&&<>{button('approve',record)}{button('reject',record)}</>}{['approved','partial'].includes(record.data.state)&&<>{data.roles.treasury&&button('execute',record)}{data.roles.manager&&button('cancel',record)}</>}{record.data.category==='advance'&&<>{data.roles.write&&button('expense',null,{requestId:record.id})}{data.roles.treasury&&['partial','paid','cancelled'].includes(record.data.state)&&button('advance_return',record)}</>}</IconActions><h4>اجراهای ثبت‌شده</h4>{data.movements.filter((m:any)=>m.data.requestId===record.id).map((m:any)=><p key={m.id}>{formatDate(m.data.day)} — {cash(m.data.amount,m.data.currency)} — {m.data.reference} — {m.data.kind==='advance_return'?'برگشت تنخواه':'اجرا'}</p>)}</>}
 {record.type==='treasury_check'&&<IconActions scope="treasury-check">{record.data.state==='review'&&data.roles.manager&&button('check_issue',record)}{['review','issued'].includes(record.data.state)&&data.roles.manager&&button('check_cancel',record)}{record.data.state==='issued'&&data.roles.treasury&&button('check_settle',record)}</IconActions>}{record.type==='treasury_expense'&&record.data.state==='review'&&data.roles.manager&&button('expense_review',record)}
 <h4>مدارک</h4>{data.files.filter((f:any)=>f.caseId===record.id).map((f:any)=><p key={f.id}><a href={'/api/treasury/files?id='+encodeURIComponent(f.id)}>{f.filename}</a></p>)}{data.roles.write&&<label className="field">بارگذاری رسید / سند<input type="file" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value=''}}/></label>}
 <details><summary>تاریخچه</summary>{[...(record.data.history||[])].reverse().map((h:any,n:number)=><p key={n}>{formatDateTime(h.at)} — {titles[h.mode]} — {h.notes}</p>)}</details></section>}
 <details><summary>راهنمای کار</summary>{data.help.map((h:string,n:number)=><p key={n}>{h}</p>)}</details></>}
 <Dialog open={!!mode} onOpenChange={open=>{if(!busy&&!open)setMode('')}}><DialogContent dir="rtl" style={{maxWidth:850,maxHeight:'90vh',overflowY:'auto'}}><DialogTitle>{titles[mode]}</DialogTitle><DialogDescription>اطلاعات را بررسی کنید؛ با تأیید، عملیات و سابقه آن ثبت می‌شود.</DialogDescription><form onSubmit={e=>{e.preventDefault();void save()}}><div className="grid">
 {mode==='account'&&<>{input('title','عنوان حساب')}{input('number','شماره حساب / شناسه صندوق')}{select('kind','نوع',{bank:'بانک',cash:'صندوق'})}{select('currency','ارز',Object.fromEntries(['IRR','USD','EUR','AED','CNY','GBP','TRY'].map(c=>[c,c])))}{input('opening','مانده اولیه')}{date('day','تاریخ مانده اولیه')}</>}
 {mode==='request'&&<>{input('title','عنوان درخواست')}{select('direction','جهت',{out:'پرداخت',in:'دریافت'})}{select('category','گروه',{purchase:'خرید از پرونده موجود',expense:'هزینه',advance:'تنخواه',foreign:'پرداخت ارزی / صراف',sales:'دریافت فروش',other:'سایر'})}{form.category==='purchase'&&<label className="field">قسط / پیش‌پرداخت آزادشده<select required value={form.sourceKey||''} onChange={e=>{const s=data.sources.find((s:any)=>s.key===e.target.value);setForm((f:any)=>({...f,sourceKey:s?.key||'',party:s?.party||'',amount:s?.amount||'',due:s?.due||f.due,currency:'IRR',direction:'out'}))}}><option value="">انتخاب کنید</option>{data?.sources.map((s:any)=><option key={s.key} value={s.key}>{s.title} — {cash(s.amount)} — {formatDate(s.due)}</option>)}</select></label>}{input('party','طرف حساب')}{input('destination','شماره حساب تأییدشونده ذی‌نفع / مقصد')}{input('beneficiaryMemberId','شناسه کارمند ذی‌نفع؛ در پرداخت به کارکنان',false)}{select('currency','ارز',Object.fromEntries(['IRR','USD','EUR','AED','CNY','GBP','TRY'].map(c=>[c,c])))}{input('amount','مبلغ')}{date('due','موعد')}{input('referenceDocument','مرجع قرارداد / فاکتور / پرونده')}</>}
 {['execute','advance_return'].includes(mode)&&<>{select('accountId','حساب اجرای واقعی',accountItems)}{input('amount','مبلغ واقعی')}{date('day','تاریخ اجرا')}{input('reference','شماره پیگیری یکتا')}{proof()}</>}
 {mode==='statement'&&<>{select('accountId','حساب صورتحساب',accountItems)}{date('from','از تاریخ')}{date('to','تا تاریخ')}{input('opening','مانده اول صورتحساب')}{input('closing','مانده آخر صورتحساب')}{input('referenceDocument','مرجع صورتحساب بانک')}<label className="field">اکسل بانک<input type="file" accept=".xlsx" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void readSheet(f);e.target.value=''}}/></label><p>ردیف اول عنوان ستون‌ها؛ ترتیب: تاریخ میلادی، شناسه یکتای تراکنش، مرجع، دریافت، پرداخت، شرح.</p>{grid.length>0&&<button type="button" className="btn" onClick={preview}>نمایش ردیف‌ها پیش از ثبت</button>}</>}
 {mode==='match'&&select('movementId','گردش دفتر برای تطبیق',Object.fromEntries((data?.unmatched||[]).filter((m:any)=>{const r=data?.bankRows.find((r:any)=>r.id===form.rowId);return r&&m.data.accountId===r.accountId&&m.data.direction===r.direction&&m.data.amount===r.amount}).map((m:any)=>[m.id,`${m.data.party} — ${m.data.reference} — ${formatDate(m.data.day)}`])))}
 {mode==='check'&&<>{input('number','شماره چک')}{input('bank','بانک')}{select('direction','جهت',{out:'پرداختی',in:'دریافتی'})}{select('accountId','حساب مرتبط',accountItems)}{form.direction==='out'?select('requestId','درخواست پرداخت مصوب',requestItems):input('party','صادرکننده چک')}{input('amount','مبلغ چک')}{date('due','سررسید')}{input('location','محل نگهداری / تحویل')}</>}
 {['check_issue','check_cancel'].includes(mode)&&proof()}{mode==='check_settle'&&<>{date('day','تاریخ وصول واقعی')}{input('reference','مرجع بانکی وصول')}{proof()}</>}
 {mode==='expense'&&<>{select('requestId','تنخواه پرداخت‌شده',Object.fromEntries((data?.requests||[]).filter((r:any)=>r.data.category==='advance'&&Number(r.paid)>0).map((r:any)=>[r.id,r.data.title])))}{input('title','شرح هزینه')}{input('amount','مبلغ به ارز تنخواه')}{date('day','تاریخ هزینه')}{input('reference','شناسه یکتای رسید')}{input('referenceDocument','مرجع مدرک هزینه')}</>}
 {mode==='expense_review'&&form.accepted&&proof()}{mode==='expense_review'&&<label className="field">نتیجه بررسی<select value={String(form.accepted)} onChange={e=>change('accepted',e.target.value==='true')}><option value="true">تأیید هزینه</option><option value="false">رد هزینه</option></select></label>}
 </div>{mode==='statement'&&sheet.length>0&&<div style={{maxHeight:240,overflow:'auto'}}><p>{sheet.length} ردیف آماده ثبت</p><table><thead><tr><th>تاریخ</th><th>شناسه</th><th>مرجع</th><th>جهت</th><th>مبلغ</th></tr></thead><tbody>{sheet.map((r,n)=><tr key={n}><td>{formatDate(r.day)}</td><td>{r.bankId}</td><td>{r.reference}</td><td>{r.direction==='in'?'دریافت':'پرداخت'}</td><td>{r.amount}</td></tr>)}</tbody></table></div>}
 {input('notes','توضیح و نتیجه بررسی')}{error&&<p role="alert" className="error">{error}</p>}<p className="footnote">این ثبت، عملیات بانکی انجام نمی‌دهد.</p><button className="btn primary" disabled={busy||mode==='statement'&&!sheet.length} type="submit">{busy?'در حال ثبت…':'تأیید و ثبت'}</button></form></DialogContent></Dialog>
 </section>;
}
