'use client';
import {useEffect,useRef,useState} from 'react';
import {UserRound,Camera,X} from 'lucide-react';
export function UserProfile({accountId,name}:{accountId:string;name:string}){
 const [open,setOpen]=useState(false),[profile,setProfile]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const input=useRef<HTMLInputElement>(null);
 const url='/api/profile?account='+encodeURIComponent(accountId);
 async function refresh(){const r=await fetch(url,{cache:'no-store'}),d=await r.json() as any;if(!r.ok)throw Error(d.error);if(d.accountId!==accountId)throw Error('حساب تغییر کرده است.');setProfile(d)}
 useEffect(()=>{let active=true;fetch(url,{cache:'no-store'}).then(async r=>{const d=await r.json() as any;if(active){if(r.ok&&d.accountId===accountId)setProfile(d);else setError(d.error||'پروفایل دریافت نشد.')}}).catch(()=>{if(active)setError('دریافت پروفایل انجام نشد؛ دوباره باز کنید.')});return()=>{active=false}},[url,accountId]);
 async function save(mode:string,file?:File){setBusy(true);setError('');setMessage('');try{let image='';if(file){if(file.size>8*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('عکس JPG، PNG یا WebP حداکثر ۸ مگابایت انتخاب کنید.');const source=URL.createObjectURL(file);try{const img=new Image();img.src=source;await img.decode();const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const ctx=canvas.getContext('2d');if(!ctx)throw Error('آماده‌سازی عکس ممکن نشد.');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,256,256);const side=Math.min(img.width,img.height);ctx.drawImage(img,(img.width-side)/2,(img.height-side)/2,side,side,0,0,256,256);image=canvas.toDataURL('image/jpeg',0.8).split(',')[1];}finally{URL.revokeObjectURL(source)}}
 const r=await fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json','x-profile-account':accountId},body:JSON.stringify({mode,revision:profile.revision,image,confirmed:true})}),d=await r.json() as any;if(!r.ok)throw Error(d.error);await refresh();setMessage('پروفایل ذخیره شد.');}catch(e){setError((e as Error).message)}finally{setBusy(false);if(input.current)input.current.value=''}}
 const photo=profile?.hasPhoto?url+'&image=1&v='+profile.revision:'';
 return <div className="user-profile"><button className="user-profile-button" onClick={()=>{setOpen(!open);if(!open)void refresh().catch(e=>setError(e.message))}} aria-expanded={open} aria-label="پروفایل من">{photo?<img src={photo} alt="عکس پروفایل من"/>:<UserRound size={22}/>}<span><strong>{name}</strong><small>نسخهٔ پروفایل ۱</small></span></button>{open&&<section className="user-profile-card" aria-label="ویرایش عکس پروفایل"><button className="link" aria-label="بستن پروفایل" onClick={()=>setOpen(false)}><X size={18}/></button><h3>{name}</h3><p>عکس پروفایل خودت را انتخاب کن؛ بخش میانی عکس به‌صورت مربع ذخیره می‌شود.</p><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void save('upload',f)}}/><button className="btn" disabled={busy||!profile} onClick={()=>input.current?.click()}><Camera size={18}/> {busy?'در حال ذخیره…':'انتخاب عکس'}</button>{photo&&<button className="btn" disabled={busy} onClick={()=>void save('remove')}>حذف عکس من</button>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</section>}</div>;
}
