'use client';
import {useEffect,useRef,useState} from 'react';
import {formatDateTime} from '@/lib/persian-date';
const statuses:Record<string,string>={passed:'بررسی شد',attention:'نیازمند رسیدگی',unknown:'هنوز قابل تأیید نیست',on_submit:'کنترل هنگام ثبت'};
export function WorkflowGuide({taskId,threadId,revision,accountId}:{taskId?:string;threadId?:string;revision:number;accountId:string}){
 const root=useRef<HTMLDivElement>(null),[visible,setVisible]=useState(false),[guide,setGuide]=useState<any>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 useEffect(()=>{const node=root.current;if(!node)return;const observer=new IntersectionObserver(entries=>setVisible(entries.some(e=>e.isIntersecting)));observer.observe(node);return()=>observer.disconnect();},[]);
 useEffect(()=>{setGuide(null);setError('');if(!visible)return;let active=true,busy=false;const controller=new AbortController();const load=async()=>{if(busy||document.hidden)return;busy=true;try{const q=new URLSearchParams(taskId?{taskId}:{threadId:threadId||''}),r=await fetch('/api/tasks/guide?'+q,{cache:'no-store',signal:controller.signal}),d:any=await r.json();if(!active)return;if(!r.ok||d.accountId!==accountId)throw Error(d.error||'دسترسی راهنمای کار تغییر کرده است.');setGuide(d);setError('');}catch(e){if(active){setGuide(null);setError((e as Error).message);}}finally{busy=false;}};void load();const timer=setInterval(()=>void load(),60000),wake=()=>void load();window.addEventListener('focus',wake);return()=>{active=false;controller.abort();clearInterval(timer);window.removeEventListener('focus',wake);};},[taskId,threadId,revision,accountId,visible,refresh]);
 const help=()=>window.dispatchEvent(new CustomEvent('nafasyar-duty-prompt',{detail:{text:'ابتدا get_workflow_guidance را برای '+(taskId?'taskId: '+taskId:'threadId: '+threadId)+' بخوان. بگو الان چه کاری دارم، کدام کنترل واقعاً انجام شده، کدام مورد نامشخص یا مانع است و کدام کار با من است. سپس فقط یک سؤال درباره اولین مورد ناقص بپرس. on_submit را تأییدشده نگو. ثبت یا ارسال فقط بعد از تأیید من.'}}));
 return <div ref={root} className="workflow-guide" aria-label="راهنمای همراه کار"><h4>الان چه کاری باید انجام بدهم؟</h4>{error?<p role="alert" className="notice error">{error}</p>:!guide?<p role="status">در حال بررسی وضعیت فعلی کار…</p>:<><ol>{guide.steps.map((s:string,i:number)=><li key={i}>{s}</li>)}</ol><p><strong>مدرک و خروجی لازم: </strong>{guide.evidence}</p><details><summary>بررسی‌های سامانه، موارد ناقص و بررسی انسانی</summary><p>آخرین بررسی: {formatDateTime(guide.at)}؛ این راهنما مجوز اجرا نیست.</p><ul>{guide.checks.map((c:any)=><li key={c.key}><strong>{c.label} — {statuses[c.status]}: </strong>{c.detail}</li>)}</ul><h5>بررسی با شما</h5><ul>{guide.humanChecks.map((s:string,i:number)=><li key={i}>{s}</li>)}</ul><h5>کنترل‌هایی که هنگام ثبت اجرا می‌شوند</h5><ul>{guide.submitChecks.map((c:any)=><li key={c.key}>{c.label}؛ {c.detail}</li>)}</ul><p><strong>معیار تکمیل: </strong>{guide.completion}</p></details>{guide.checks.some((c:any)=>c.status==='attention'||c.status==='unknown')&&<p className="notice">{guide.checks.filter((c:any)=>c.status==='attention'||c.status==='unknown').map((c:any)=>c.label+': '+c.detail).join(' / ')}</p>}<p>{guide.nextQuestion}</p></>}<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn" type="button" onClick={()=>setRefresh(n=>n+1)}>بررسی دوباره وضعیت</button><button className="btn" type="button" onClick={help}>با دستیار مرحله‌به‌مرحله انجام بده</button></div></div>;
}
