import {salesRep,salesStaff} from '@/lib/sales';
import {requireAccess,checkOrigin,accessResponse} from '@/lib/authorization';
import {storage} from '@/lib/storage';
import {firmwareBucket,boundedBody} from '@/lib/firmware-storage';
import {sha256} from '@/lib/firmware';
import {memberId} from '@/lib/duties';
import {fail,entity,isAgent} from '@/lib/after-sales';
import {transportAccess,transportFiles,transportDriver,transportManager,transportFinance} from '@/lib/transport';
function mime(bytes:ArrayBuffer,name:string){const b=new Uint8Array(bytes),s=new TextDecoder().decode(b.slice(0,16)),ext=name.split('.').pop()?.toLowerCase();if(['jpg','jpeg'].includes(ext||'')&&b[0]===255&&b[1]===216&&b[2]===255)return 'image/jpeg';if(ext==='png'&&[137,80,78,71,13,10,26,10].every((v,i)=>b[i]===v))return 'image/png';if(ext==='webp'&&s.startsWith('RIFF')&&s.slice(8,12)==='WEBP')return 'image/webp';if(ext==='pdf'&&s.startsWith('%PDF-'))return 'application/pdf';return fail('فایل معتبر JPG، PNG، WEBP یا PDF انتخاب کنید.');}
export async function GET(request:Request){try{const u=await requireAccess(),q=new URL(request.url).searchParams,m=await transportAccess(u,q.get('mission')||''),id=q.get('id'),files=await transportFiles(u,m);if(!id)return Response.json({files},{headers:{'Cache-Control':'private, no-store'}});if(!files.some(f=>f.id===id))fail('مدرک یافت نشد.',404);const f=await entity(id,'transport_file');if(f.data.purpose==='expense'&&!transportManager(u)&&!transportFinance(u)&&f.data.actor!==u.userId)fail('مدرک هزینه در دسترس نیست.',403);const o=await firmwareBucket().get(f.data.objectKey);if(!o)throw Error('missing');const bytes=await o.arrayBuffer();if(await sha256(bytes)!==f.data.sha256)throw Error('integrity');return new Response(bytes,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':"attachment; filename=transport-document; filename*=UTF-8''"+encodeURIComponent(f.data.filename).replace(/['()*]/g,c=>'%'+c.charCodeAt(0).toString(16)),'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"sandbox; default-src 'none'"}});}catch(e){return accessResponse(e)||Response.json({error:'دریافت مدرک حمل انجام نشد.'},{status:503})}}
export async function POST(request:Request){let key='',id='';try{checkOrigin(request);const u=await requireAccess(),q=new URL(request.url).searchParams,m=await transportAccess(u,q.get('mission')||''),mid=await memberId(u),purpose=q.get('purpose')||'';id=q.get('requestId')||'';
 if(!/^[a-f0-9-]{36}$/i.test(id)||!['waybill','receipt','condition','expense'].includes(purpose))fail('نوع مدرک یا شناسه معتبر نیست.');if(m.data.state==='cancelled')fail('مأموریت لغو شده است.');const delegate=salesStaff(u)&&m.data.kind==='sale'&&!m.data.inbound&&!!m.data.salesAgentId;const assigned=transportDriver(u)&&mid===m.data.driverId,receiver=mid===m.data.receiverId,agent=isAgent(u)&&m.data.agentId===u.permissions.serviceAgentId||salesRep(u)&&m.data.salesAgentId===u.permissions.salesAgentId;
 if(!transportManager(u)&&!assigned&&!(['receipt','condition'].includes(purpose)&&(receiver||agent||delegate))&&!(agent&&m.data.inbound&&purpose==='waybill'))fail('اجازه بارگذاری این مدرک را ندارید.',403);
 const raw=await boundedBody(request,10*1024*1024+128000),form=await new Response(raw,{headers:{'Content-Type':request.headers.get('content-type')||''}}).formData(),f=form.get('file');if(!f||typeof f==='string'||!f.size||f.size>10*1024*1024||f.name.length>180||form.getAll('file').length!==1)fail('یک فایل تا ۱۰ مگابایت انتخاب کنید.');const bytes=await f.arrayBuffer(),hash=await sha256(bytes),type=mime(bytes,f.name),db=storage();
 const prior:any=await db.prepare("SELECT * FROM flow_entities WHERE id=?").bind(id).first();if(prior){const d=JSON.parse(prior.data);if(prior.type!=='transport_file'||d.missionId!==m.id||d.sha256!==hash||d.purpose!==purpose||d.actor!==u.userId||d.filename!==f.name)fail('شناسه مدرک تکراری متفاوت.',409);return Response.json({saved:true,repeated:true,id,revision:d.uploadRevision?d.uploadRevision+1:m.revision});}
 const expected=q.get('revision');if(expected!==null&&(!/^\d+$/.test(expected)||Number(expected)!==m.revision))fail('مأموریت تغییر کرده است؛ تازه‌سازی کنید.',409);
 if((await transportFiles(u,m)).length>=60)fail('حداکثر ۶۰ مدرک برای مأموریت.');key='transport/'+id+'/'+crypto.randomUUID();await firmwareBucket().put(key,bytes,{httpMetadata:{contentType:'application/octet-stream'},sha256:hash});const now=new Date().toISOString(),data={missionId:m.id,uploadRevision:m.revision,purpose,objectKey:key,filename:f.name,mime:type,size:f.size,sha256:hash,actor:u.userId};const next={...m.data,history:[...m.data.history,{mode:'file',purpose,filename:f.name,actor:u.userId,at:now}],...(purpose==='waybill'&&m.data.waybill?{missingDocuments:false}:{})};
 await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'transport_file','{}',?,?,CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN 1 ELSE 0 END)").bind(crypto.randomUUID(),u.userId,now,m.id,m.revision),db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,'transport_file',?,1,?,?)").bind(id,JSON.stringify(data),now,now),db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=? AND revision=?').bind(JSON.stringify(next),now,m.id,m.revision),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,m.id,'transport_file',JSON.stringify({id,purpose,filename:f.name,sha256:hash}),now)]);return Response.json({saved:true,id,revision:m.revision+1},{status:201});
 }catch(e){if(key&&id)try{const r:any=await storage().prepare('SELECT data FROM flow_entities WHERE id=?').bind(id).first();if(!r||JSON.parse(r.data).objectKey!==key)await firmwareBucket().delete(key);}catch{}return accessResponse(e)||Response.json({error:'مدرک ثبت نشد؛ مأموریت را تازه‌سازی کنید.'},{status:409})}}
