import {serviceProvince,coverageRows,suggestedServiceAgents} from '@/lib/service-coverage';
import {serviceReport} from '@/lib/service-report';
import {requireAccess,checkOrigin,accessResponse} from '@/lib/authorization';
import {storage} from '@/lib/storage';
import {boundedBody} from '@/lib/firmware-storage';
import {dayAt} from '@/lib/duties';
import {normalizeSerial} from '@/lib/distribution';
import {supplyLock,holdChecks} from '@/lib/sourcing';
import {serviceRoles,serviceDomains} from '@/lib/after-sales-labels';
import {fail,req,txt,decode,isAgent,role,domainAccess,need,visible,entity,list,date,past,monthsAfter,amount,qty,total,array,unique,warehouse,warranty,lineage,ledger,serviceSteps,syncServiceTasks} from '@/lib/after-sales';
const json=(v:unknown,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'private, no-store','Vary':'Cookie, Authorization'}});
export async function GET(request:Request){try{
 const u=await requireAccess(),db=storage(),q=new URL(request.url).searchParams,domain=q.get('domain')||'home';if(!domainAccess(u,domain))fail('دسترسی این حوزه خدمات را ندارید.',403);
 const own=isAgent(u)?u.permissions.serviceAgentId:'',filter=(r:any)=>r.data.domain===domain&&(!own||r.data.agentId===own||r.type==='as_agent'&&r.id===own);if(own)await visible(u,{data:{domain,agentId:own}});
 const cases=(await list('as_case')).filter(filter).filter(c=>!q.get('serial')||c.data.serial===normalizeSerial(q.get('serial')!)),agents=(await list('as_agent')).filter(filter),tariffs=(await list('as_tariff')).filter(r=>r.data.domain===domain).map(r=>own?{...r,data:{...r.data,costRial:undefined}}:r);
 if(q.get('suggestAgents')==='1')return json({suggestions:suggestedServiceAgents(agents,domain,serviceProvince(q.get('province')||''),txt(q.get('city')||'',200)),automaticAssignment:false});
 if(q.get('report')==='1'){const from=date(q.get('from')),to=date(q.get('to'));if(from>to)fail('ابتدای بازه بعد از انتهاست.');return json(serviceReport(cases,from,to));}
 const orders=(await list('as_order')).filter(filter),shipments=(await list('as_shipment')).filter(filter),claims=(await list('as_claim')).filter(filter);
 const lots=(await db.prepare('SELECT l.*,r.payload,COALESCE((SELECT SUM(quantity) FROM service_reservations s WHERE s.lot_id=l.id),0) reserved FROM service_lots l JOIN records r ON r.id=l.batch_id WHERE l.domain=?'+(own?' AND l.owner=?':'')).bind(domain,...(own?[own]:[])).all()).results.map((r:any)=>{const p=JSON.parse(r.payload);return {...r,batch:{code:p.code,part:p.part,partCode:p.partCode,unit:p.unit,status:p.status,expiry:p.expiry},payload:undefined}});
 const caseId=q.get('case');if(caseId){const c=cases.find(c=>c.id===caseId);if(!c)fail('پرونده پیدا نشد.',404);const f=(await db.prepare('SELECT id,purpose,filename,mime,byte_size,sha256,created,actor FROM service_files WHERE case_id=? ORDER BY created').bind(caseId).all()).results;return json({case:c,files:f,steps:await serviceSteps(c),reservations:(await db.prepare('SELECT * FROM service_reservations WHERE case_id=?').bind(caseId).all()).results,claims:claims.filter(r=>r.data.caseId===caseId),lineage:(await lineage(c.data.serial)).map(a=>({batchId:a.batchId,partCode:a.partCode||'',quantity:a.quantity,warrantyStart:a.warrantyStart||'',warrantyEnd:a.warrantyEnd||''}))});}
 const account=q.get('agent');let accountRows:any[]=[];if(account){if(own&&account!==own||!own&&!role(u,'finance')&&!role(u,'coordinator'))fail('دسترسی حساب ندارید.',403);if(!agents.some(a=>a.id===account))fail('نماینده پیدا نشد.',404);accountRows=await ledger(account);}
 const raw=!own&&(role(u,'inventory')||role(u,'technician'))?(await db.prepare("SELECT r.id,r.payload,i.quantity,s.location FROM records r JOIN inventory_balances i ON i.item_id=r.id LEFT JOIN flow_slots s ON s.batch_id=r.id AND s.quantity>0 WHERE r.kind='batch' AND i.warehouse='raw' AND i.quantity>0 AND json_extract(r.payload,'$.status')='تأیید'").all()).results.map((r:any)=>({id:r.id,...JSON.parse(r.payload),available:r.quantity,location:r.location})):[];
 const members=!own?(await db.prepare("SELECT id,name,permissions FROM app_members WHERE status='active'").all()).results.filter((m:any)=>JSON.parse(m.permissions).serviceDomains?.includes(domain)).map((m:any)=>({id:m.id,name:m.name,roles:JSON.parse(m.permissions).serviceRoles})):[];
 return json({domain,roles:u.isAdmin?Object.keys(serviceRoles):u.permissions.serviceRoles,ownAgent:own||'',cases,agents,tariffs,orders,shipments,claims,lots,raw,members,materials:(await list('material')).map(r=>({id:r.id,code:r.data.code,name:r.data.name,unit:r.data.unit})),account:accountRows,products:(await db.prepare("SELECT id,payload FROM records WHERE kind='product'").all()).results.map((r:any)=>({id:r.id,code:JSON.parse(r.payload).code,name:JSON.parse(r.payload).name,model:JSON.parse(r.payload).model}))});
 }catch(e){return accessResponse(e)||json({error:'اطلاعات خدمات در دسترس نیست؛ مهاجرت 0015 را بررسی کنید.'},503)}}

export async function POST(request:Request){try{
 checkOrigin(request);const u=await requireAccess(),db=storage(),b=JSON.parse(new TextDecoder().decode(await boundedBody(request,250000))),mode=req(b.mode),id=req(b.id),domain=req(b.domain),now=new Date().toISOString(),today=dayAt();if(!/^[a-f0-9-]{36}$/i.test(id))fail('شناسه عملیات معتبر نیست.');if(!domainAccess(u,domain))fail('مجوز این حوزه را ندارید.',403);if(isAgent(u)&&b.agentId&&b.agentId!==u.permissions.serviceAgentId)fail('نماینده دیگری قابل انتخاب نیست.',403);
 if(['consent','authorize','approve_order','return_review'].includes(mode)&&typeof b.approved!=='boolean')fail('نتیجه تأیید یا رد باید مشخص باشد.');
 const signature=JSON.stringify(b),oldOp:any=await db.prepare('SELECT * FROM inventory_operations WHERE id=?').bind(id).first();if(oldOp){if(oldOp.actor!==u.userId||oldOp.payload!==signature)fail('شناسه تکراری عملیات.',409);return json({saved:true,repeated:true});}
 const stmts:D1PreparedStatement[]=[],checks=await supplyLock(db,id),touched:string[]=[];let target=id;
 const guard=(test:string,...args:any[])=>checks.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN '+test+' THEN guard ELSE 0 END WHERE id=?').bind(...args,id));
 const get=async(eid:string,type:string)=>{const e=await visible(u,await entity(eid,type));if(e.data.domain!==domain)fail('حوزه رکورد متفاوت است.',403);guard('EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?)',e.id,e.revision);return e;};
 const put=(eid:string,type:string,data:any,old?:any)=>{stmts.push(old?db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=? AND revision=?').bind(JSON.stringify(data),now,eid,old.revision):db.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').bind(eid,type,JSON.stringify(data),now,now));};
 const entry=(batch:string,wh:string,delta:number)=>{touched.push(batch);stmts.push(db.prepare('INSERT INTO inventory_balances(id,item_id,warehouse,quantity) VALUES(?,?,?,0) ON CONFLICT(id) DO NOTHING').bind(batch+'@'+wh,batch,wh),db.prepare('UPDATE inventory_balances SET quantity=quantity+? WHERE item_id=? AND warehouse=?').bind(delta,batch,wh),db.prepare('INSERT INTO inventory_entries(id,operation_id,item_id,warehouse,delta) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),id,batch,wh,delta));};
 const book=(agent:string,kind:string,source:string,debit:string,credit:string,due:string|null,data:any)=>{const eid=crypto.randomUUID();stmts.push(db.prepare('INSERT INTO service_ledger(id,agent_id,domain,kind,source_id,debit,credit,due,data,created,actor) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(eid,agent,domain,kind,source,debit,credit,due,JSON.stringify(data),now,u.userId));return eid;};
 async function agentCheck(agentId:string){const a=await entity(agentId,'as_agent');if(!a.data.active||a.data.domain!==domain||isAgent(u)&&agentId!==u.permissions.serviceAgentId)fail('نماینده مجاز نیست.',403);guard('EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?)',a.id,a.revision);return a;}
 async function takeRaw(batchId:string,q:number,location:string){const raw:any=await db.prepare("SELECT * FROM records WHERE id=? AND kind='batch'").bind(batchId).first();if(!raw)fail('بچ پیدا نشد.');const data=JSON.parse(raw.payload);if(data.status!=='تأیید'||data.expiry&&data.expiry<today)fail('بچ تأییدشده و معتبر لازم است.');guard('EXISTS(SELECT 1 FROM records WHERE id=? AND payload=?)',batchId,raw.payload);if(!u.isAdmin&&!u.permissions.warehouses?.includes('raw'))fail('مجوز انبار مواد اولیه لازم است.',403);
 if(await db.prepare("SELECT id FROM flow_entities WHERE id=? AND type='receipt'").bind(batchId).first()){if(!location)fail('کد محل برداشت لازم است.');guard('EXISTS(SELECT 1 FROM flow_slots WHERE location=? AND batch_id=? AND quantity>=?)',location,batchId,q);stmts.push(db.prepare('UPDATE flow_slots SET quantity=quantity-? WHERE location=? AND batch_id=?').bind(q,location,batchId));}entry(batchId,'raw',-q);return data;}
 function version(e:any){if(b.revision!==e.revision)fail('اطلاعات تغییر کرده؛ تازه‌سازی کنید.',409);target=e.id;}
 if(['activation_preview','activation_import'].includes(mode)){
 need(u,domain,'manager');const rows=array(b.rows,200),seen=new Set<string>(),preview:any[]=[];for(const [i,r] of rows.entries()){try{const serial=normalizeSerial(req(r.serial,160));if(seen.has(serial))fail('سریال تکراری در فایل.');seen.add(serial);const day=past(r.day),months=Number(r.months);if(!Number.isInteger(months)||months<1||months>120)fail('مدت گارانتی ۱ تا ۱۲۰ ماه باشد.');const imported:any=await db.prepare('SELECT * FROM service_activations WHERE serial=?').bind(serial).first(),native=await warranty(serial,day),existing=imported||(native.activatedAt?{day:native.activatedAt,months:native.months}:null);const data={serial,day,months,source:req(b.source,500)};preview.push({row:i+1,...data,status:existing?(existing.day===day&&existing.months===months?'same':'conflict'):'new'});}catch(e){preview.push({row:i+1,status:'invalid',error:(e as Error).message});}}
 if(mode==='activation_preview')return json({preview});if(preview.some(r=>['conflict','invalid'].includes(r.status)))fail('ابتدا ردیف‌های نامعتبر یا متعارض را اصلاح کنید.');for(const r of preview.filter(r=>r.status==='new'))stmts.push(db.prepare('INSERT INTO service_activations(serial,day,months,source,created,actor) VALUES(?,?,?,?,?,?)').bind(r.serial,r.day,r.months,r.source,now,u.userId));
 }else if(mode==='agent'){
 need(u,domain,'manager');const old=b.agentId?await entity(req(b.agentId),'as_agent'):null;if(old){if(old.data.domain!==domain)fail('حوزه نماینده ثابت است.');version(old);}const agentId=old?.id||id;guard("NOT EXISTS(SELECT 1 FROM flow_entities WHERE type='as_agent' AND json_extract(data,'$.code')=? AND id<>?)",req(b.code,80),agentId);put(agentId,'as_agent',{domain,agentId,name:req(b.name),code:req(b.code,80),city:req(b.city),province:serviceProvince(b.province===undefined?old?.data.province:b.province),coverage:coverageRows(b.coverage===undefined?old?.data.coverage:b.coverage),phone:req(b.phone,30),address:req(b.address,1000),active:b.active===true},old);
 }else if(mode==='tariff'){
 need(u,domain,'manager');const old=b.tariffId?await get(req(b.tariffId),'as_tariff'):null;if(old)version(old);if(!['part','labor'].includes(b.kind))fail('نوع تعرفه معتبر نیست.');if(b.kind==='part'){const m=await entity('material:'+req(b.partCode,12),'material');if(!m)fail('کالا تعریف نشده.');}
 put(old?.id||id,'as_tariff',{domain,kind:b.kind,name:req(b.name),partCode:b.kind==='part'?req(b.partCode,12):'',priceRial:amount(b.priceRial),costRial:amount(b.costRial),validFrom:date(b.validFrom),active:b.active===true},old);
 }else if(mode==='create'){
 need(u,domain,'support','intake','agent');const agentId=isAgent(u)?u.permissions.serviceAgentId||'':txt(b.agentId,200);if(agentId)await agentCheck(agentId);const serial=normalizeSerial(req(b.serial,160)),contactDay=past(b.day);const w=await warranty(serial,contactDay);guard("NOT EXISTS(SELECT 1 FROM flow_entities WHERE type='as_case' AND json_extract(data,'$.serial')=? AND json_extract(data,'$.state') NOT IN ('closed','resolved','returned'))",serial);
 put(id,'as_case',{domain,agentId,serial,model:txt(b.model)||w.model,customer:req(b.customer),phone:req(b.phone,30),city:txt(b.city),province:serviceProvince(b.province),complaint:req(b.complaint),contactDay,warranty:w,state:'contact',lines:[],laborLines:[],customerTotal:'0',history:[{mode,by:u.name,actor:u.userId,at:now,notes:txt(b.complaint)}]});
 }else if(mode==='office_stock'){
 need(u,domain,'inventory');const q=qty(b.quantity),batch=req(b.batchId),data=await takeRaw(batch,q,txt(b.location,100));entry(batch,warehouse('office',domain),q);stmts.push(db.prepare('INSERT INTO service_lots(id,owner,domain,batch_id,quantity,unit_rial,created) VALUES(?,?,?,?,?,?,?)').bind(id,'office',domain,batch,q,amount(b.costRial),now));
 }else if(mode==='order'){
 need(u,domain,'coordinator','agent');const agentId=isAgent(u)?u.permissions.serviceAgentId||'':req(b.agentId);await agentCheck(agentId);const caseId=txt(b.caseId,200);if(caseId){const c=await get(caseId,'as_case');if(c.data.agentId!==agentId)fail('نماینده پرونده با سفارش متفاوت است.');}
 const rows=array(b.lines);if(!rows.length||!unique(rows.map(x=>x.tariffId)))fail('ردیف‌های سفارش خالی یا تکراری‌اند.');let sum=BigInt(0);const lines=[];for(const r of rows){const t=await entity(req(r.tariffId),'as_tariff');if(t.data.domain!==domain||t.data.kind!=='part'||!t.data.active||t.data.validFrom>today)fail('تعرفه قطعه معتبر نیست.');guard('EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?)',t.id,t.revision);const q=qty(r.quantity),cost=total(t.data.priceRial,q);sum+=BigInt(cost);lines.push({id:crypto.randomUUID(),partCode:t.data.partCode,name:t.data.name,quantity:q,unitRial:t.data.priceRial,totalRial:cost,prepared:0,received:0,tariffRevision:t.revision});}
 const due=monthsAfter(today,1),ledgerId=book(agentId,'invoice',id,sum.toString(),'0',due,{lines});put(id,'as_order',{domain,agentId,caseId,state:'requested',lines,totalRial:sum.toString(),due,invoiceId:ledgerId,notes:txt(b.notes),history:[]});
 }else if(['approve_order','prepare'].includes(mode)){
 need(u,domain,mode==='prepare'?'inventory':'coordinator');const o=await get(req(b.orderId),'as_order');version(o);const d=o.data;
 if(mode==='approve_order'){if(d.state!=='requested')fail('درخواست قبلاً بررسی شده.');d.state=b.approved===true?'approved':'rejected';d.decision=req(b.notes);if(d.state==='rejected'){const cr=book(d.agentId,'order_cancel',o.id,'0',d.totalRial,null,{notes:d.decision});const invoice=(await ledger(d.agentId)).find(r=>r.id===d.invoiceId),n=invoice?invoice.remaining:'0';if(BigInt(n)>BigInt(0))stmts.push(db.prepare('INSERT INTO service_offsets(id,debit_id,credit_id,amount,created,actor) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),d.invoiceId,cr,n,now,u.userId));}}
 else{if(d.state!=='approved')fail('درخواست تأییدشده لازم است.');const allocations=array(b.allocations);if(!allocations.length)fail('قطعات بسته را انتخاب کنید.');const rows=[];for(const a of allocations){const l=d.lines.find((l:any)=>l.id===a.lineId);if(!l)fail('ردیف سفارش معتبر نیست.');const q=qty(a.quantity);if(l.prepared+q>l.quantity)fail('بیش از مانده سفارش است.');const batch=req(a.batchId),raw=await takeRaw(batch,q,txt(a.location,100));if(raw.partCode!==l.partCode)fail('بچ با قطعه سفارش متفاوت است.');l.prepared+=q;entry(batch,'service:transit:'+id,q);rows.push({lineId:l.id,batchId:batch,partCode:l.partCode,quantity:q,unitRial:l.unitRial});}put(id,'as_shipment',{domain,agentId:d.agentId,orderId:o.id,state:'prepared',lines:rows,history:[],notes:txt(b.notes)});}
 put(o.id,'as_order',d,o);
 }else if(['ship','receive'].includes(mode)){
 const s=await get(req(b.shipmentId),'as_shipment');version(s);if(s.data.transportId)fail('این محموله در تدارکات مدیریت می‌شود؛ دریافت و بارنامه را در مأموریت حمل ثبت کنید.');const d=s.data,o=await get(d.orderId,'as_order');
 if(mode==='ship'){need(u,domain,'logistics');if(d.state!=='prepared')fail('بسته آماده نیست.');d.state='shipped';d.tracking=req(b.tracking,500);d.carrier=req(b.carrier);d.eta=date(b.eta);d.shippedAt=now;}
 else{need(u,domain,'agent','coordinator');if(d.state!=='shipped'||b.confirmedReceived!==true)fail('دریافت تمام اقلام همین بسته باید تأیید شود.');d.state='received';d.receivedAt=now;d.receivedBy=u.userId;for(const [i,l] of d.lines.entries()){entry(l.batchId,'service:transit:'+s.id,-l.quantity);entry(l.batchId,warehouse(d.agentId,domain),l.quantity);stmts.push(db.prepare('INSERT INTO service_lots(id,owner,domain,batch_id,order_id,line_id,quantity,unit_rial,created) VALUES(?,?,?,?,?,?,?,?,?)').bind(s.id+':'+i,d.agentId,domain,l.batchId,o.id,l.lineId,l.quantity,l.unitRial,now));o.data.lines.find((x:any)=>x.id===l.lineId).received+=l.quantity;}if(o.data.lines.every((l:any)=>l.received===l.quantity))o.data.state='received';put(o.id,'as_order',o.data,o);}
 d.history.push({mode,at:now,actor:u.userId,notes:req(b.notes)});put(s.id,'as_shipment',d,s);
 }else if(['return_send','return_receive','return_review','credit'].includes(mode)){
 const c=await get(req(b.claimId),'as_claim');version(c);const d=c.data;
 if(mode==='return_send'){need(u,domain,'agent','coordinator');if(!['awaiting_return','rejected'].includes(d.state))fail('داغی در مرحله ارسال نیست.');d.state='sent';d.tracking=req(b.tracking,500);d.sentAt=now;}
 if(mode==='return_receive'&&d.transportId)fail('دریافت این داغی در مأموریت تدارکات ثبت می‌شود.');
 if(mode==='return_receive'){need(u,domain,'inventory');if(!['sent','awaiting_return'].includes(d.state))fail('داغی قابل دریافت نیست.');d.receivedDay=past(b.day);if(d.receivedDay<dayAt(new Date(c.created)))fail('دریافت قبل از ثبت تعمیر معتبر نیست.');d.state='received';d.receivedAt=now;d.receivedBy=u.userId;d.location=req(b.location,100);}
 if(mode==='return_review'){need(u,domain,'coordinator');if(d.state!=='received')fail('ابتدا دریافت داغی ثبت شود.');d.state=b.approved===true?'approved':'rejected';d.reviewedAt=now;d.reviewedBy=u.userId;d.review=req(b.notes);}
 if(mode==='credit'){need(u,domain,'finance');if(d.state!=='approved')fail('داغی تأییدشده لازم است.');const cr=book(d.agentId,'return_credit',c.id,'0',d.amountRial,null,{caseId:d.caseId,orderId:d.orderId,receivedDay:d.receivedDay,late:d.receivedDay>d.due}),rows=await ledger(d.agentId),invoice=rows.find(r=>r.kind==='invoice'&&r.source_id===d.orderId),n=invoice?BigInt(invoice.remaining)<BigInt(d.amountRial)?BigInt(invoice.remaining):BigInt(d.amountRial):BigInt(0);if(n>BigInt(0))stmts.push(db.prepare('INSERT INTO service_offsets(id,debit_id,credit_id,amount,created,actor) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),invoice.id,cr,n.toString(),now,u.userId));d.state='credited';d.creditId=cr;d.creditedAt=now;}
 d.history=[...(d.history||[]),{mode,at:now,actor:u.userId,notes:req(b.notes)}];put(c.id,'as_claim',d,c);
 }else if(['payment','offset'].includes(mode)){
 need(u,domain,'finance');const agentId=req(b.agentId);await agentCheck(agentId);const n=amount(b.amountRial);if(BigInt(n)<=BigInt(0))fail('مبلغ مثبت لازم است.');
 if(mode==='payment'){if(!['received','paid'].includes(b.direction))fail('جهت پرداخت معتبر نیست.');book(agentId,b.direction==='received'?'payment_received':'payment_paid',id,b.direction==='paid'?n:'0',b.direction==='received'?n:'0',null,{reference:req(b.reference,500),day:past(b.day),notes:req(b.notes)});}
 else{const rows=await ledger(agentId),debit=rows.find(r=>r.id===b.debitId),credit=rows.find(r=>r.id===b.creditId);if(!debit||!credit||BigInt(debit.debit)<=BigInt(0)||BigInt(credit.credit)<=BigInt(0)||BigInt(n)>BigInt(debit.remaining)||BigInt(n)>BigInt(credit.remaining))fail('ردیف یا مانده قابل تهاتر معتبر نیست.');stmts.push(db.prepare('INSERT INTO service_offsets(id,debit_id,credit_id,amount,created,actor) VALUES(?,?,?,?,?,?)').bind(id,debit.id,credit.id,n,now,u.userId));}
 }else{
 const c=await get(req(b.caseId),'as_case');version(c);const d=c.data,previousState=d.state,owner=d.agentId||'office';const history=(notes:string)=>d.history.push({mode,at:now,actor:u.userId,by:u.name,notes});
 if(mode==='contact'){need(u,domain,'support','agent');if(!['contact','followup','referred'].includes(d.state))fail('پرونده از مرحله تماس گذشته است.');if(!['resolved','followup','referred'].includes(b.result))fail('نتیجه تماس معتبر نیست.');d.state=b.result;d.guidance=req(b.notes);d.nextDue=date(b.nextDue||today);}
 else if(mode==='intake'){need(u,domain,'intake','agent');if(!['contact','referred','followup'].includes(d.state))fail('پذیرش قبلاً ثبت شده است.');const day=past(b.day);if(day<d.contactDay)fail('تاریخ پذیرش قبل از تماس است.');d.state='received';d.intake={day,hours:txt(b.hours,30),deliverer:req(b.deliverer),accessories:req(b.accessories),appearance:req(b.appearance),by:u.name,at:now};if(d.intake.hours&&!/^\d+(\.\d{1,2})?$/.test(d.intake.hours))fail('ساعت کارکرد عدد نامنفی یا خالی باشد.');d.warranty=await warranty(d.serial,day);}
 else if(mode==='diagnose'){need(u,domain,'technician','agent');if(!['received','diagnosed','approved'].includes(d.state)||d.repairs?.length)fail('پرونده قابل عیب‌یابی مجدد نیست.');const lines=[];let sum=BigInt(0);for(const r of array(b.lines)){const m=await entity('material:'+req(r.partCode,12),'material');if(!['warranty','paid','part_warranty'].includes(r.coverage))fail('پوشش قطعه معتبر نیست.');const q=qty(r.quantity),price=amount(r.customerUnitRial);if(r.coverage!=='paid'&&price!=='0')fail('مبلغ مشتری برای پوشش گارانتی صفر است.');sum+=BigInt(total(price,q));const oldBatch=txt(r.oldBatchId,200),known=await lineage(d.serial);if(oldBatch){if(!known.some(a=>a.batchId===oldBatch&&a.quantity>=q))fail('بچ خارج‌شده در سابقه این سریال نیست؛ در صورت نامشخص بودن، خالی ثبت کنید.');}
 if(r.coverage==='part_warranty'&&!known.some(a=>a.batchId===oldBatch&&a.quantity>=q&&a.warrantyStart&&d.intake.day>=a.warrantyStart&&d.intake.day<a.warrantyEnd))fail('این قطعه سابقه معتبر گارانتی شش‌ماهه از تحویل ندارد.');
 lines.push({id:crypto.randomUUID(),partCode:r.partCode,name:m.data.name,unit:m.data.unit,quantity:q,customerUnitRial:price,coverage:r.coverage,oldBatchId:oldBatch,unknownReason:oldBatch?'':req(r.unknownReason),fault:req(r.fault),cause:req(r.cause),coverageReason:req(r.coverageReason)});}
 const installed=await lineage(d.serial),removed:Record<string,number>={};for(const l of lines){if(l.oldBatchId){removed[l.oldBatchId]=(removed[l.oldBatchId]||0)+l.quantity;if(removed[l.oldBatchId]>installed.filter(a=>a.batchId===l.oldBatchId).reduce((n,a)=>n+a.quantity,0))fail('مجموع قطعات خارج‌شده از موجودی نصب‌شده بیشتر است.');}}
 const laborLines=[];for(const r of array(b.laborLines)){const t=await entity(req(r.tariffId),'as_tariff');if(t.data.kind!=='labor'||!t.data.active||t.data.domain!==domain||t.data.validFrom>today)fail('تعرفه خدمت معتبر نیست.');const price=amount(r.customerRial);if(r.covered===true&&price!=='0')fail('اجرت گارانتی از مشتری دریافت نمی‌شود.');sum+=BigInt(price);laborLines.push({tariffId:t.id,name:t.data.name,companyRial:t.data.priceRial,customerRial:price,covered:r.covered===true,tariffRevision:t.revision});}
 if(!lines.length&&!laborLines.length)fail('حداقل یک قطعه یا خدمت لازم است.');if(!unique(laborLines.map(l=>l.tariffId)))fail('خدمت تکراری است.');d.estimates=[...(d.estimates||[]),...(d.estimateVersion?[{version:d.estimateVersion,lines:d.lines,laborLines:d.laborLines,total:d.customerTotal,authorization:d.authorization,consent:d.consent,at:now}]:[])];d.diagnosis=req(b.notes);d.lines=lines;d.laborLines=laborLines;d.customerTotal=sum.toString();d.estimateVersion=(d.estimateVersion||0)+1;d.authorization=null;d.consent=null;d.state='diagnosed';stmts.push(db.prepare('DELETE FROM service_reservations WHERE case_id=?').bind(c.id));}
 else if(mode==='authorize'){need(u,domain,'coordinator');if(d.state!=='diagnosed')fail('پرونده در انتظار بررسی نیست.');const covered=d.lines.some((l:any)=>l.coverage!=='paid')||d.laborLines.some((l:any)=>l.covered);if(covered&&d.agentId){const evidence:any=await db.prepare("SELECT COUNT(*) n FROM service_files WHERE case_id=? AND purpose='before' AND (mime LIKE 'image/%' OR mime LIKE 'video/%')").bind(c.id).first();if(!evidence.n)fail('عکس یا فیلم قبل از تعمیر با سریال و ایراد لازم است.');}
 if((d.lines.some((l:any)=>l.coverage==='warranty')||d.laborLines.some((l:any)=>l.covered))&&d.warranty.state!=='active'&&!txt(b.exceptionReason))fail('گارانتی زمانی فعال نیست یا سابقه نامشخص است؛ دلیل بررسی پوشش قطعه یا استثنا لازم است.');d.authorization={approved:b.approved===true,notes:req(b.notes),exceptionReason:txt(b.exceptionReason),by:u.userId,at:now,version:d.estimateVersion};if(!d.authorization.approved)fail('برای اصلاح یا رد پوشش، عیب‌یابی و برآورد را اصلاح کنید.');if(d.customerTotal==='0'||d.consent?.approved===true)d.state='approved';}
 else if(mode==='consent'){need(u,domain,'support','agent');if(!['diagnosed','approved'].includes(d.state))fail('برآورد قابل تأیید نیست.');d.consent={approved:b.approved===true,person:req(b.person),method:req(b.method),notes:req(b.notes),at:now,by:u.userId,version:d.estimateVersion,amountRial:d.customerTotal};if(!b.approved){d.state='declined';stmts.push(db.prepare('DELETE FROM service_reservations WHERE case_id=?').bind(c.id));}else if(d.authorization?.approved)d.state='approved';}
 else if(mode==='reserve'){
 need(u,domain,'technician','agent');if(d.state!=='approved')fail('ابتدا مجوز و تأیید هزینه تکمیل شود.');
 const allocations=array(b.allocations,80);if(!unique(allocations.map(a=>a.lineId+':'+a.lotId)))fail('تخصیص تکراری است.');
 const sums:Record<string,number>={},lotSums:Record<string,number>={};stmts.push(db.prepare('DELETE FROM service_reservations WHERE case_id=?').bind(c.id));
 for(const a of allocations){const l=d.lines.find((l:any)=>l.id===a.lineId),q=qty(a.quantity),lot:any=await db.prepare('SELECT l.*,r.payload FROM service_lots l JOIN records r ON r.id=l.batch_id WHERE l.id=?').bind(req(a.lotId)).first();
 if(!l||!lot||lot.owner!==owner||lot.domain!==domain)fail('قطعه یا موجودی متعلق به این مرکز نیست.');const r=JSON.parse(lot.payload);if(r.partCode!==l.partCode||r.unit!==l.unit||r.status!=='تأیید'||r.expiry&&r.expiry<today)fail('بچ قابل مصرف نیست.');
 sums[l.id]=(sums[l.id]||0)+q;lotSums[lot.id]=(lotSums[lot.id]||0)+q;
 const held:any=await db.prepare('SELECT COALESCE(SUM(quantity),0) n FROM service_reservations WHERE lot_id=? AND case_id<>?').bind(lot.id,c.id).first();if(lotSums[lot.id]>lot.quantity-held.n)fail('موجودی آزاد کافی نیست.',409);
 stmts.push(db.prepare('INSERT INTO service_reservations(id,case_id,line_id,lot_id,quantity) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),c.id,l.id,lot.id,q));}
 if(d.lines.some((l:any)=>sums[l.id]!==l.quantity))fail('تعداد تخصیص هر قطعه با برآورد منطبق نیست.');}
 else if(mode==='repair'){need(u,domain,'technician','agent');if(d.state!=='approved')fail('مجوز تعمیر و تأیید هزینه لازم است.');const res=(await db.prepare('SELECT s.*,l.batch_id,l.owner,l.unit_rial,l.order_id,l.line_id AS invoice_line FROM service_reservations s JOIN service_lots l ON l.id=s.lot_id WHERE s.case_id=?').bind(c.id).all()).results as any[];if(d.lines.some((l:any)=>res.filter(a=>a.line_id===l.id).reduce((n,a)=>n+a.quantity,0)!==l.quantity))fail('ابتدا قطعات مصرفی را رزرو کنید.');d.repairs=[];const priorClaims=await list('as_claim'),claimTotals:Record<string,bigint>={};for(const a of res){const l=d.lines.find((l:any)=>l.id===a.line_id);const batch:any=await db.prepare("SELECT payload FROM records WHERE id=? AND kind='batch'").bind(a.batch_id).first();const p=batch?JSON.parse(batch.payload):null;if(a.owner!==owner||!p||p.partCode!==l.partCode||p.status!=='تأیید'||p.expiry&&p.expiry<today)fail('بچ رزروشده دیگر قابل مصرف نیست؛ تخصیص را اصلاح کنید.');guard('EXISTS(SELECT 1 FROM records WHERE id=? AND payload=?)',a.batch_id,batch.payload);stmts.push(db.prepare('UPDATE service_lots SET quantity=quantity-? WHERE id=?').bind(a.quantity,a.lot_id));entry(a.batch_id,warehouse(owner,domain),-a.quantity);const replacement={lineId:l.id,name:l.name,partCode:l.partCode,batchId:a.batch_id,oldBatchId:l.oldBatchId,quantity:a.quantity,costRial:total(a.unit_rial,a.quantity),coverage:l.coverage,lotId:a.lot_id};d.repairs.push(replacement);
 if(d.agentId&&l.coverage!=='paid'){if(!a.order_id)fail('برای جبران گارانتی، قطعه باید از فاکتور شرکت قابل رهگیری باشد.');const o=await entity(a.order_id,'as_order'),invoiceLine=o.data.lines.find((l:any)=>l.id===a.invoice_line);if(!invoiceLine||o.data.agentId!==d.agentId)fail('ردیف فاکتور قطعه منطبق نیست.');const ck=o.id+':'+a.invoice_line;const prior=claimTotals[ck]??priorClaims.filter(c=>c.data.orderId===o.id&&c.data.invoiceLineId===a.invoice_line).reduce((n,c)=>n+BigInt(c.data.amountRial),BigInt(0)),left=BigInt(invoiceLine.totalRial)-prior,price=BigInt(total(a.unit_rial,a.quantity)),claimAmount=price<left?price:left;if(claimAmount<BigInt(0))fail('مانده قابل جبران فاکتور معتبر نیست.');claimTotals[ck]=prior+claimAmount;put(crypto.randomUUID(),'as_claim',{domain,agentId:d.agentId,caseId:c.id,serial:d.serial,orderId:o.id,invoiceLineId:a.invoice_line,partCode:l.partCode,oldBatchId:l.oldBatchId,quantity:a.quantity,amountRial:claimAmount.toString(),due:o.data.due,state:'awaiting_return',history:[]});}
 if(d.warranty.deviceId){stmts.push(db.prepare("INSERT INTO records(id,kind,payload,created) VALUES(?,'service',?,?)").bind(crypto.randomUUID(),JSON.stringify({device:d.warranty.deviceId,batch:l.oldBatchId,replacement:a.batch_id,quantity:String(a.quantity/1000),date:today,complaint:d.complaint,diagnosis:d.diagnosis+' · '+l.fault,notes:req(b.notes,4000),operator:u.name,hours:d.intake.hours,status:'تعمیرشده',serviceCase:c.id,cause:l.cause}),now));}}
 stmts.push(db.prepare('DELETE FROM service_reservations WHERE case_id=?').bind(c.id));d.state='repaired';d.repairedAt=now;d.repairedBy=u.userId;d.repairedByName=u.name;d.repairNotes=req(b.notes);d.internalPartsCost=d.repairs.reduce((n:bigint,a:any)=>n+BigInt(a.costRial),BigInt(0)).toString();}
 else if(mode==='test'){need(u,domain,'technician','agent');if(!['repaired','tested'].includes(d.state))fail('ابتدا تعمیر ثبت شود.');const tests=array(b.tests);if(!tests.length)fail('نتایج آزمون را وارد کنید.');const results=tests.map(t=>({name:req(t.name),value:req(t.value),min:txt(t.min,50),max:txt(t.max,50),unit:txt(t.unit,30),passed:t.passed===true}));for(const t of results){if(t.min!==''||t.max!==''){const v=Number(t.value),lo=t.min===''?-Infinity:Number(t.min),hi=t.max===''?Infinity:Number(t.max);if(!Number.isFinite(v)||Number.isNaN(lo)||Number.isNaN(hi)||lo>hi)fail('بازه یا مقدار آزمون معتبر نیست.');if((v<lo||v>hi)&&t.passed)fail('آزمون خارج از بازه قابل تأیید نیست.');}}const pass=results.every(t=>t.passed);d.tests=[...(d.tests||[]),{at:now,by:u.userId,results,pass,notes:req(b.notes)}];d.state=pass?'tested':'repaired';}
 else if(mode==='return_unrepaired'){need(u,domain,'intake','agent');if(d.state!=='declined'||d.repairedAt)fail('فقط دستگاه با انصراف مشتری و بدون تعمیر قابل عودت است.');const day=past(b.day);if(day<d.intake.day)fail('عودت قبل از پذیرش نیست.');d.returnedDay=day;d.returnedTo=req(b.person);d.returnReference=req(b.reference);d.returnNotes=req(b.notes);d.state='returned';}
 else if(mode==='deliver'){need(u,domain,'intake','agent');if(d.state!=='tested')fail('تست نهایی تأیید نشده است.');const day=past(b.day);if(day<dayAt(new Date(d.repairedAt)))fail('تحویل قبل از تعمیر نیست.');d.deliveredDay=day;d.deliveredTo=req(b.person);d.deliveredBy=u.userId;d.deliveryReference=req(b.reference);d.state='delivered';d.partWarrantyEnd=monthsAfter(day,6);}
 else if(mode==='confirm'){need(u,domain,'support');if(!['delivered','closed'].includes(d.state)||d.laborApproved)fail('پرونده قابل ثبت تأیید مشتری نیست.');if(!['confirmed','no_answer','problem'].includes(b.result))fail('نتیجه تماس معتبر نیست.');const rating=Number(b.rating);if(!Number.isInteger(rating)||rating<0||rating>5)fail('امتیاز صفر (نامشخص) تا پنج است.');d.confirmation={result:b.result,person:req(b.person),notes:req(b.notes),paidRial:amount(b.paidRial),rating,by:u.userId,at:now};if(d.customerTotal==='0'&&d.confirmation.paidRial!=='0'&&b.result==='confirmed')fail('دریافت وجه برای پرونده تمام‌گارانتی باید ابتدا بررسی شود.');if(!d.agentId&&b.result==='confirmed')d.state='closed';}
 else if(mode==='labor'){need(u,domain,'coordinator');if(!d.agentId||d.confirmation?.result!=='confirmed'||d.laborApproved)fail('تحویل و تأیید مشتری لازم است یا اجرت قبلاً ثبت شده.');const n=d.laborLines.filter((l:any)=>l.covered).reduce((n:bigint,l:any)=>n+BigInt(l.companyRial),BigInt(0));if(n>BigInt(0))book(d.agentId,'labor_credit',c.id,'0',n.toString(),null,{serial:d.serial,lines:d.laborLines,notes:req(b.notes)});d.laborApproved={amountRial:n.toString(),by:u.userId,at:now};d.state='closed';}
 else if(mode==='followup'){need(u,domain,'support','intake','technician','coordinator','agent');d.nextDue=date(b.nextDue);if(b.ownerId){if(isAgent(u))fail('تغییر مسئول شرکت مجاز نیست.',403);const m:any=await db.prepare("SELECT permissions FROM app_members WHERE id=? AND status='active'").bind(req(b.ownerId)).first();if(!m||!JSON.parse(m.permissions).serviceDomains?.includes(domain)||JSON.parse(m.permissions).serviceAgentId)fail('مسئول معتبر این حوزه را انتخاب کنید.');d.ownerId=b.ownerId;}d.followup=req(b.notes);}
 else fail('عملیات خدمات ناشناخته است.');
 if(d.state!==previousState)d.stageSince=now;history(txt(b.notes));put(c.id,'as_case',d,c);
 }
 await db.batch([db.prepare('INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,?,?,?,?,1)').bind(id,'after_sales_'+mode,signature,u.userId,now),...checks,...stmts,...holdChecks(db,id,touched),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,target,'after_sales_'+mode,signature,now)]);
 try{await syncServiceTasks()}catch{console.error('Service task projection deferred');}
 return json({saved:true,id:target});
 }catch(e){return accessResponse(e)||json({error:/constraint|SQLITE|D1/i.test(String(e))?'موجودی یا پرونده هم‌زمان تغییر کرده؛ هیچ عملیات ناقصی ثبت نشد.':e instanceof Error?e.message:'ثبت خدمات انجام نشد.'},409)}}
