import {tehranDay} from '@/lib/serials';
import {warehouseAccess} from '@/lib/material-flow';
import {storage} from '@/lib/storage';
import {holdChecks,supplyLock} from '@/lib/sourcing';
import {requireAccess,can,checkOrigin,AccessError,accessResponse} from '@/lib/authorization';
import {warehouses,scaled,validateBom,type BomLine} from '@/lib/production';
const fail=(message:string,status=400):never=>{throw new AccessError(message,status)};
const uuid=(v:unknown)=>{if(typeof v!=='string'||! /^[a-f0-9-]{36}$/i.test(v))fail('شناسه درخواست معتبر نیست.');return v as string;};
const str=(v:unknown,max=4000)=>{if(typeof v!=='string'||v.length>max)fail('متن معتبر نیست.');return v as string;};
const respond=(v:unknown)=>Response.json(v,{headers:{'Cache-Control':'no-store'}});
export async function GET(){try{const u=await requireAccess();const db=storage();const production=can(u,'event','read')&&can(u,'device','read')&&can(u,'batch','read');const stock=can(u,'batch','read');const product=can(u,'product','read');if(!stock&&!product)fail('دسترسی مشاهده ندارید.',403);
 const boms=product?(await db.prepare('SELECT * FROM bom_versions ORDER BY created DESC, version DESC').all()).results:[];
 const balances=stock?(await db.prepare("SELECT b.*,r.kind,r.payload FROM inventory_balances b JOIN records r ON r.id=b.item_id WHERE r.kind='batch' OR ?=1").bind(production?1:0).all()).results:[];
 const materialCatalog=product?(await db.prepare("SELECT * FROM flow_entities WHERE type='material' ORDER BY id").all()).results.map((m:any)=>({...m,data:JSON.parse(m.data)})):[];
 return respond({warehouses,materialCatalog,boms,balances,initialized:stock?(await db.prepare('SELECT * FROM inventory_batches').all()).results:[],orders:production?(await db.prepare('SELECT o.*,r.created AS transferred FROM production_orders o LEFT JOIN production_receipts r ON r.order_id=o.id ORDER BY o.created DESC').all()).results:[],materials:production?(await db.prepare('SELECT * FROM production_materials').all()).results:[],operations:u.isAdmin?(await db.prepare('SELECT * FROM inventory_operations ORDER BY created DESC LIMIT 100').all()).results:[]});
 }catch(e){return accessResponse(e)||Response.json({error:'دریافت تولید و موجودی ممکن نشد.'},{status:503});}}
export async function POST(request:Request){try{checkOrigin(request);const u=await requireAccess();const body=await request.json() as any;const db=storage(),now=new Date().toISOString();const mode=body.mode;
 const productionWrite=u.isAdmin||(can(u,'event','write')&&can(u,'device','read')&&can(u,'batch','read')&&can(u,'product','read')&&u.permissions.eventStages.includes('مونتاژ'));
 if(mode==='bom'){if(!can(u,'product','write'))fail('دسترسی ویرایش محصول ندارید.',403);const id=uuid(body.id),productId=str(body.productId,200),lines=validateBom(body.lines);for(const l of lines){const m:any=await db.prepare("SELECT data FROM flow_entities WHERE id=? AND type='material'").bind('material:'+l.partCode).first();if(m&&JSON.parse(m.data).unit!==l.unit)fail('واحد BOM با شناسنامه ماده اولیه یکسان نیست.');}
 const product:any=await db.prepare("SELECT payload FROM records WHERE id=? AND kind='product'").bind(productId).first();if(!product)fail('محصول پیدا نشد.');const old:any=await db.prepare('SELECT * FROM bom_versions WHERE id=?').bind(id).first();if(old){if(old.product_id!==productId||old.lines!==JSON.stringify(lines))fail('شناسه درخواست تکراری است.',409);return respond({saved:true});}const max:any=await db.prepare('SELECT COALESCE(MAX(version),0) AS n FROM bom_versions WHERE product_id=?').bind(productId).first();if(body.previousVersion!==max.n)fail('نسخه BOM تغییر کرده است؛ تازه‌سازی کنید.',409);
 await db.batch([db.prepare('INSERT INTO bom_versions(id,product_id,version,lines,created,actor) VALUES(?,?,?,?,?,?)').bind(id,productId,max.n+1,JSON.stringify(lines),now,u.userId),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,productId,'save_bom',JSON.stringify({id,lines,version:max.n+1}),now)]);return respond({saved:true});}
 if(['order','finish'].includes(mode)&&!productionWrite)fail('دسترسی ثبت تولید ندارید.',403);if(['opening','move'].includes(mode)&&!can(u,'batch','write'))fail('دسترسی ثبت انبار ندارید.',403);
 const id=uuid(body.id);const signature=JSON.stringify(body);
 const prior:any=await db.prepare('SELECT payload FROM inventory_operations WHERE id=?').bind(id).first();if(prior){if(prior.payload!==signature)fail('این شناسه برای درخواست دیگری استفاده شده است.',409);return respond({saved:true,repeated:true});}
 const sourcingChecks=await supplyLock(db,id);
 const statements:D1PreparedStatement[]=[];const guards:string[]=[];const params:any[]=[];const guardChecks:D1PreparedStatement[]=[];
 const guardRecord=(r:any)=>{if(params.length+2>75){guardChecks.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN '+guards.join(' AND ')+' THEN 1 ELSE 0 END WHERE id=?').bind(...params,id));guards.length=0;params.length=0;}guards.push('EXISTS(SELECT 1 FROM records WHERE id=? AND payload=?)');params.push(r.id,r.payload);};
 const record=async(id:string,kind:string)=>{const r:any=await db.prepare('SELECT * FROM records WHERE id=? AND kind=?').bind(id,kind).first();if(!r)fail('رکورد مرتبط پیدا نشد.');guardRecord(r);return {...r,data:JSON.parse(r.payload)};};
 const touchedStock:string[]=[];
 const entry=(item:string,warehouse:string,delta:number)=>{touchedStock.push(item);const balanceId=item+'@'+warehouse;statements.push(db.prepare('INSERT INTO inventory_balances(id,item_id,warehouse,quantity) VALUES(?,?,?,0) ON CONFLICT(id) DO NOTHING').bind(balanceId,item,warehouse),db.prepare('UPDATE inventory_balances SET quantity=quantity+? WHERE id=?').bind(delta,balanceId),db.prepare('INSERT INTO inventory_entries(id,operation_id,item_id,warehouse,delta) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),id,item,warehouse,delta));};
 if(mode==='opening'||mode==='move'){if(!can(u,'batch','write'))fail('دسترسی ثبت انبار ندارید.',403);const batch=await record(str(body.batchId,200),'batch');const receipt:any=await db.prepare("SELECT * FROM flow_entities WHERE id=? AND type='receipt'").bind(batch.id).first();if(receipt){const rd=JSON.parse(receipt.data);if(mode!=='move'||!['semi','line'].includes(body.from)||!['semi','line'].includes(body.to))fail('این بچ را از گردش مواد و تولید جابه‌جا کنید.');if(rd.state!=='stored'||batch.data.status!=='تأیید'||rd.expiry&&rd.expiry<tehranDay())fail('انتقال نیمه‌ساخته فقط برای بچ تأییدشده و غیرمنقضی مجاز است.');guards.push('EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?)');params.push(receipt.id,receipt.revision);} const amount=scaled(body.quantity),to=str(body.to,30);if(!warehouses.some(w=>w.id===to&&w.id!=='finished'))fail('انبار مقصد معتبر نیست.');if(['raw','semi','line'].includes(to)&&batch.data.status!=='تأیید')fail('مواد تأییدنشده فقط در قرنطینه یا نامنطبق نگهداری می‌شوند.');
 if(mode==='opening'){if(!u.isAdmin)fail('ثبت موجودی آغازین فقط برای ادمین مجاز است.',403);if(!/^\d{2,12}$/.test(batch.data.partCode||''))fail('ابتدا کد ثابت قطعه را در بچ تعریف کنید.');if(amount>scaled(batch.data.quantity))fail('موجودی آغازین نمی‌تواند از مقدار ورودی بچ بیشتر باشد.');statements.push(db.prepare('INSERT INTO inventory_batches(batch_id,part_code,unit,created) VALUES(?,?,?,?)').bind(batch.id,batch.data.partCode,batch.data.unit,now));entry(batch.id,to,amount);
 }else{const from=str(body.from,30);if(!warehouseAccess(u,from)||!warehouseAccess(u,to))fail('انبار مبدأ یا مقصد در مسئولیت شما نیست.',403);if(from===to||!warehouses.some(w=>w.id===from&&w.id!=='finished'))fail('مبدأ و مقصد معتبر و متفاوت انتخاب کنید.');if(!(await db.prepare('SELECT batch_id FROM inventory_batches WHERE batch_id=?').bind(batch.id).first()))fail('موجودی این بچ هنوز تعیین نشده است.');entry(batch.id,from,-amount);entry(batch.id,to,amount);}
 }else if(mode==='order'){if(!productionWrite)fail('ثبت برگ تولید به دسترسی تولید (مونتاژ) نیاز دارد.',403);const device=await record(str(body.deviceId,200),'device');if(await db.prepare("SELECT id FROM flow_entities WHERE id=? AND type='build'").bind(device.id).first())fail('برای این سریال از گردش مواد و تولید استفاده کنید.');const bom:any=await db.prepare('SELECT * FROM bom_versions WHERE id=? AND product_id=?').bind(str(body.bomId,200),device.data.product).first();if(!bom)fail('BOM این محصول را انتخاب کنید.');const day=str(body.day,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(day)||new Date(day+'T12:00:00Z').toISOString().slice(0,10)!==day)fail('تاریخ معتبر نیست.');const operator=str(body.operator,200).trim();if(!operator)fail('مسئول تولید را وارد کنید.');const lines=JSON.parse(bom.lines) as BomLine[];if(!Array.isArray(body.allocations)||body.allocations.length!==lines.length)fail('برای هر قطعه BOM یک بچ انتخاب کنید.');const materialRows=[];
 for(const l of lines){const matches=body.allocations.filter((a:any)=>a.partCode===l.partCode);if(matches.length!==1)fail('انتخاب بچ‌های BOM ناقص یا تکراری است.');const a=matches[0];if(!['raw','line'].includes(a.warehouse))fail('مصرف فقط از مواد اولیه یا خط تولید مجاز است.');const b=await record(str(a.batchId,200),'batch');if(b.data.partCode!==l.partCode||b.data.unit!==l.unit||b.data.status!=='تأیید')fail('بچ باید تأییدشده و کد قطعه و واحد آن مطابق BOM باشد.');materialRows.push({batch:b.id,warehouse:a.warehouse,quantity:scaled(l.quantity)});}
 // Legacy material events cannot be charged a second time through the new flow.
 guards.push("NOT EXISTS(SELECT 1 FROM records WHERE kind='event' AND json_extract(payload,'$.device')=? AND json_extract(payload,'$.stage')='مصرف قطعه')");params.push(device.id);
 statements.push(db.prepare('INSERT INTO production_orders(id,device_id,bom_id,day,operator,notes,actor,created) VALUES(?,?,?,?,?,?,?,?)').bind(id,device.id,bom.id,day,operator,str(body.notes||''),u.userId,now));for(const m of materialRows)statements.push(db.prepare('INSERT INTO production_materials(id,order_id,batch_id,warehouse,quantity) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),id,m.batch,m.warehouse,m.quantity));
 }else if(mode==='finish'){if(!warehouseAccess(u,'finished'))fail('مجوز دریافت انبار محصول نهایی لازم است.',403);if(!productionWrite)fail('انتقال محصول به دسترسی تولید (مونتاژ) نیاز دارد.',403);const orderId=str(body.orderId,200),o:any=await db.prepare('SELECT * FROM production_orders WHERE id=?').bind(orderId).first();if(!o)fail('برگ تولید پیدا نشد.');if(await db.prepare('SELECT order_id FROM production_receipts WHERE order_id=?').bind(orderId).first())return respond({saved:true,repeated:true});const ms:any[]=(await db.prepare('SELECT * FROM production_materials WHERE order_id=?').bind(orderId).all()).results;const day=now.slice(0,10);
 for(const m of ms){const b=await record(m.batch_id,'batch');if(b.data.status!=='تأیید')fail('یکی از بچ‌ها اکنون تأییدشده نیست.');const inv:any=await db.prepare('SELECT * FROM inventory_batches WHERE batch_id=?').bind(b.id).first();if(!inv||inv.part_code!==b.data.partCode||inv.unit!==b.data.unit)fail('موجودی یا واحد بچ تعیین نشده است.');entry(b.id,m.warehouse,-m.quantity);const payload={device:o.device_id,stage:'مصرف قطعه',date:day,operator:o.operator,batch:b.id,quantity:String(m.quantity/1000),productionOrder:orderId,notes:'مصرف خودکار طبق BOM هنگام انتقال محصول نهایی'};statements.push(db.prepare("INSERT INTO records(id,kind,payload,created) VALUES(?,'event',?,?)").bind(crypto.randomUUID(),JSON.stringify(payload),now));}
 entry(o.device_id,'finished',1000);statements.push(db.prepare('INSERT INTO production_receipts(order_id,operation_id,created) VALUES(?,?,?)').bind(orderId,id,now),db.prepare("INSERT INTO records(id,kind,payload,created) VALUES(?,'event',?,?)").bind(crypto.randomUUID(),JSON.stringify({device:o.device_id,stage:'انتقال به انبار محصول نهایی',date:day,operator:o.operator,productionOrder:orderId,notes:o.notes}),now));
 }else fail('عملیات ناشناخته است.');
 const gate=db.prepare('INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,?,?,?,?,CASE WHEN '+(guards.join(' AND ')||'1')+' THEN 1 ELSE 0 END)').bind(id,mode,signature,u.userId,now,...params);
 await db.batch([gate,...guardChecks,...sourcingChecks,...statements,...holdChecks(db,id,touchedStock),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,id,'production_'+mode,signature,now)]);return respond({saved:true});
 }catch(e){const denied=accessResponse(e);if(denied)return denied;const msg=e instanceof Error?e.message:'';console.error('Production operation failed',msg);if(/inventory_nonnegative/.test(msg))return Response.json({error:'موجودی کافی نیست؛ هیچ ماده‌ای کسر و هیچ محصولی منتقل نشد.'},{status:409});if(/UNIQUE|inventory_operation_guard|FOREIGN KEY/.test(msg))return Response.json({error:'رکورد تکراری یا اطلاعات تغییرکرده است؛ تازه‌سازی کنید. هیچ تغییری ثبت نشد.'},{status:409});return Response.json({error:/D1|SQLITE|Database/.test(msg)?'عملیات ذخیره نشد؛ دوباره بررسی کنید.':msg||'اطلاعات معتبر نیست.'},{status:400});}}
