import {salesRep} from '@/lib/sales';
import {requireAccess,checkOrigin,accessResponse} from '@/lib/authorization';
import {storage} from '@/lib/storage';
import {boundedBody} from '@/lib/firmware-storage';
import {memberId,dayAt} from '@/lib/duties';
import {fail,req,txt,list,entity,date,past,amount,domainAccess,role,isAgent,warehouse} from '@/lib/after-sales';
import {supplyLock} from '@/lib/sourcing';
import {transportManager,transportDriver,transportFinance,transportEntry,transportAccess,transportCanSee,transportPublic,transportFiles,sourceSummary,purchaseReceiver,canRequest,sourceReady,syncTransportTasks} from '@/lib/transport';
import {transportForms,transportActions,transportHelp} from '@/lib/transport-contract';
const json=(v:unknown,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'private, no-store','Vary':'Cookie, Authorization'}});
export async function GET(request:Request){try{const u=await requireAccess();if(!transportEntry(u))fail('دسترسی تدارکات ندارید.',403);const mid=await memberId(u),q=new URL(request.url).searchParams,id=q.get('id');if(id){const m=await transportAccess(u,id);return json({mission:await transportPublic(u,m),files:await transportFiles(u,m)});}
 const missions=[];for(const m of await list('transport'))if(await transportCanSee(u,m,mid))missions.push(await transportPublic(u,m));const sources=[];for(const type of ['purchase_order','sale','as_shipment','as_claim','as_case'])for(const s of await list(type))if(sourceReady(s)&&!s.data.transportId&&canRequest(u,s)){const summary=await sourceSummary(s);if(summary.items.some((i:any)=>i.quantity>0))sources.push(summary);}
 const manager=transportManager(u),members=(await storage().prepare("SELECT id,name,permissions FROM app_members WHERE status='active'").all()).results as any[];
 const drivers=manager?members.filter(m=>{const p=JSON.parse(m.permissions);return !p.serviceAgentId&&(p.transportRoles?.includes('driver')||p.flowRoles?.includes('logistics'));}).map(m=>({id:m.id,name:m.name})):[];
 const receivers=!isAgent(u)&&!salesRep(u)?members.filter(m=>{const p=JSON.parse(m.permissions);return purchaseReceiver(p)||!p.serviceAgentId&&p.serviceRoles?.some((r:string)=>['intake','inventory','manager'].includes(r));}).map(m=>({id:m.id,name:m.name})):[];
 return json({missions,sources,drivers,receivers,vehicles:manager?await list('transport_vehicle'):[],parties:manager?await list('party'):[],agents:manager?(await list('as_agent')).filter(a=>a.data.active).map(a=>({id:a.id,name:a.data.name})):[],me:mid,roles:{manager,driver:transportDriver(u),finance:transportFinance(u),agent:isAgent(u)||salesRep(u)},forms:transportForms,help:transportHelp});
 }catch(e){return accessResponse(e)||json({error:'دریافت تدارکات انجام نشد.'},503)}}
export async function POST(request:Request){try{checkOrigin(request);const u=await requireAccess();if(!transportEntry(u))fail('دسترسی تدارکات ندارید.',403);const b=JSON.parse(new TextDecoder().decode(await boundedBody(request,100000))),mode=req(b.mode),op=req(b.id),db=storage(),now=new Date().toISOString(),mid=await memberId(u);if(!/^[a-f0-9-]{36}$/i.test(op)||!transportActions[mode])fail('شناسه یا عملیات معتبر نیست.');
 const signature=JSON.stringify(b),prior:any=await db.prepare('SELECT * FROM inventory_operations WHERE id=?').bind(op).first();if(prior){if(prior.actor!==u.userId||prior.payload!==signature)fail('شناسه تکراری متفاوت.',409);return json({saved:true,repeated:true});}
 const stmts:D1PreparedStatement[]=[],checks=await supplyLock(db,op);let target=op;
 const guard=(sql:string,...args:any[])=>checks.push(db.prepare('UPDATE inventory_operations SET guard=CASE WHEN '+sql+' THEN guard ELSE 0 END WHERE id=?').bind(...args,op));
 const get=async(id:string,type:string)=>{const e=await entity(id,type);guard('EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?)',e.id,e.revision);return e;};
 const put=(id:string,type:string,data:any,old?:any)=>stmts.push(old?db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=? AND revision=?').bind(JSON.stringify(data),now,id,old.revision):db.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').bind(id,type,JSON.stringify(data),now,now));
 const entry=(item:string,wh:string,delta:number)=>{stmts.push(db.prepare('INSERT INTO inventory_balances(id,item_id,warehouse,quantity) VALUES(?,?,?,0) ON CONFLICT(id) DO NOTHING').bind(item+'@'+wh,item,wh),db.prepare('UPDATE inventory_balances SET quantity=quantity+? WHERE item_id=? AND warehouse=?').bind(delta,item,wh),db.prepare('INSERT INTO inventory_entries(id,operation_id,item_id,warehouse,delta) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),op,item,wh,delta));};
 const requireManager=()=>{if(!transportManager(u))fail('تخصیص و مدیریت فقط برای مسئول تدارکات مجاز است.',403);};
 const packs=(v:any)=>{const n=Number(v);if(!Number.isInteger(n)||n<1||n>10000)fail('تعداد بسته ۱ تا ۱۰۰۰۰ باشد.');return n;};
 async function staff(id:string,test:(p:any)=>boolean){const r:any=await db.prepare("SELECT * FROM app_members WHERE id=? AND status='active'").bind(id).first();if(!r||!test(JSON.parse(r.permissions)))fail('مسئول فعال با دسترسی مناسب انتخاب کنید.');guard("EXISTS(SELECT 1 FROM app_members WHERE id=? AND status='active' AND permissions=?)",id,r.permissions);return r;}
 if(mode==='vehicle'){requireManager();const old=b.vehicleId?await get(req(b.vehicleId),'transport_vehicle'):null;if(old&&old.revision!==b.revision)fail('خودرو تغییر کرده است.',409);target=old?.id||op;const plate=req(b.plate,50),name=req(b.name,100);if(typeof b.active!=='boolean')fail('وضعیت خودرو مشخص شود.');guard("NOT EXISTS(SELECT 1 FROM flow_entities WHERE type='transport_vehicle' AND json_extract(data,'$.plate')=? AND id<>?)",plate,target);if(old&&b.active===false&& (await list('transport')).some(m=>m.data.vehicleId===old.id&&!['delivered','cancelled'].includes(m.data.state)))fail('خودرو مأموریت باز دارد.');put(target,'transport_vehicle',{name,plate,active:b.active},old);
 }else if(mode==='link_party'){requireManager();const p=await get(req(b.partyId),'party'),a=await get(req(b.agentId),'as_agent');if(!a.data.active)fail('نماینده فعال انتخاب شود.');req(b.notes);put(p.id,'party',{...p.data,serviceAgentId:a.id},p);target=p.id;
 }else if(mode==='create'){const key=req(b.sourceKey,300),sep=key.indexOf(':'),kind=key.slice(0,sep),id=key.slice(sep+1);if(!['purchase_order','sale','as_shipment','as_claim','as_case'].includes(kind))fail('نوع مرجع معتبر نیست.');const s=await get(id,kind);if(!canRequest(u,s))fail('مجوز درخواست این حمل را ندارید.',403);if(!sourceReady(s)||s.data.transportId)fail('مرجع آماده حمل نیست یا مأموریت دارد.',409);const summary=await sourceSummary(s),inbound=['purchase_order','as_claim','as_case'].includes(kind);if(!summary.items.some((i:any)=>i.quantity>0))fail('سفارش مانده قابل حمل ندارد.');if(summary.agentId){const a=await get(summary.agentId,'as_agent');if(!a.data.active)fail('نمایندگی غیرفعال است.');}if(kind==='sale')await get(s.data.partyId,'party');
 const receiverId=txt(b.receiverId,200);if(inbound&&receiverId)await staff(receiverId,p=>kind==='purchase_order'?purchaseReceiver(p):!p.serviceAgentId&&p.serviceDomains?.includes(summary.domain)&&p.serviceRoles?.some((r:string)=>['manager',kind==='as_case'?'intake':'inventory'].includes(r)));if(inbound&&!receiverId&&!isAgent(u))fail('مسئول دریافت داخل شرکت تعیین شود.');if(!['carrier','direct'].includes(b.route))fail('روش حمل انتخاب شود.');const due=date(b.due);if(due<dayAt())fail('موعد جدید در گذشته نباشد.');
 put(op,'transport',{code:'TR-'+op.slice(0,8).toUpperCase(),kind,salesAgentId:summary.salesAgentId,sourceId:s.id,sourceRevision:s.revision,domain:summary.domain,purchaseRoute:summary.purchaseRoute,agentId:summary.agentId,inbound,items:summary.items,route:b.route,state:'requested',packages:packs(b.packages),pickup:req(b.pickup,1000),destination:req(b.destination,1000),recipient:req(b.recipient),phone:req(b.phone,50),due,receiverId,driverId:'',vehicleId:'',carrier:s.data.carrier||'',waybill:s.data.tracking||'',tracking:s.data.tracking||'',missingDocuments:false,notes:req(b.notes),expenses:[],history:[{mode,actor:u.userId,actorName:u.name,at:now,notes:txt(b.notes)}]});put(s.id,kind,{...s.data,transportId:op},s);
 }else{const m=await transportAccess(u,req(b.missionId));await get(m.id,'transport');if(m.revision!==b.revision)fail('مأموریت تغییر کرده است؛ تازه‌سازی کنید.',409);target=m.id;const d=m.data,notes=req(b.notes,4000);const driver=()=>{if(!u.isAdmin&&(!transportDriver(u)||mid!==d.driverId))fail('فقط راننده تعیین‌شده مجاز است.',403);};const open=()=>{if(['delivered','cancelled'].includes(d.state))fail('مأموریت بسته شده است.');};let detail:any={};
 if(mode==='assign'){requireManager();open();if(!['requested','assigned'].includes(d.state))fail('پس از دریافت فیزیکی، تغییر راننده مجاز نیست.');const a=await staff(req(b.driverId),p=>!p.serviceAgentId&&(p.transportRoles?.includes('driver')||p.flowRoles?.includes('logistics'))),v=await get(req(b.vehicleId),'transport_vehicle');if(!v.data.active)fail('خودرو غیرفعال است.');const due=date(b.due);if(due<dayAt())fail('موعد در گذشته نباشد.');if(d.inbound&&!d.receiverId){const rid=req(b.receiverId);await staff(rid,p=>d.kind==='purchase_order'?purchaseReceiver(p):!p.serviceAgentId&&p.serviceDomains?.includes(d.domain)&&p.serviceRoles?.some((r:string)=>['manager',d.kind==='as_case'?'intake':'inventory'].includes(r)));d.receiverId=rid;}detail={previousDriver:d.driverName||'',driver:a.name,vehicle:v.data.plate};d.driverId=a.id;d.driverName=a.name;d.vehicleId=v.id;d.vehicleName=v.data.name+' · '+v.data.plate;d.due=due;d.state='assigned';if(d.kind==='sale'){const s=await get(d.sourceId,'sale');put(s.id,s.type,{...s.data,carrierId:a.id,carrierSubject:a.subject||'',carrierName:a.name},s);}
 }else if(mode==='collect'){driver();if(d.state!=='assigned')fail('مأموریت تخصیص‌یافته لازم است.');const n=packs(b.packages);if(n!==d.packages)fail('تعداد بسته با مأموریت متفاوت است؛ پیش از دریافت با مسئول تدارکات هماهنگ کنید.');const actual=past(b.day);if(actual<m.created.slice(0,10))fail('دریافت قبل از درخواست نیست.');d.collectedDay=actual;d.condition=req(b.condition);d.state='collected';detail={packages:n,day:actual,condition:d.condition};if(d.kind==='sale'){const s=await get(d.sourceId,'sale');if(s.data.state!=='in_transit')fail('حواله در مسیر حمل نیست.');put(s.id,s.type,{...s.data,acknowledgedAt:now,acknowledgedBy:u.name,acknowledgedActor:u.userId,transportDriverId:d.driverId},s);}
 }else if(mode==='carrier'||mode==='documents'){driver();if(d.state==='cancelled')fail('مأموریت لغو شده است.');if(d.route!=='carrier')fail('این مأموریت تحویل مستقیم است.');if(mode==='carrier'&&(d.inbound||d.state!=='collected'))fail('تحویل به باربری برای حمل خروجی دریافت‌شده است.');d.carrier=req(b.carrier);d.waybill=txt(b.waybill,300);d.tracking=txt(b.tracking,300);const files=await transportFiles(u,m);if(!d.waybill&&!files.some(f=>f.data.purpose==='waybill'))fail('شماره بارنامه یا تصویر آن لازم است.');d.missingDocuments=!d.waybill||!files.some(f=>f.data.purpose==='waybill');if(mode==='carrier'){const actual=past(b.day);if(actual<d.collectedDay)fail('تاریخ باربری قبل از دریافت نیست.');d.carrierDay=actual;d.state='carrier';if(d.kind==='as_shipment'){const s=await get(d.sourceId,'as_shipment');if(s.data.state!=='prepared')fail('بسته آماده نیست.');put(s.id,s.type,{...s.data,state:'shipped',carrier:d.carrier,tracking:d.tracking||d.waybill||d.code,eta:d.due,shippedAt:now},s);}}detail={carrier:d.carrier,waybill:d.waybill,tracking:d.tracking};
 }else if(mode==='offer'){driver();if(d.state!=='collected'||!d.inbound&&d.route!=='direct')fail('محموله قابل تحویل مستقیم نیست.');d.handoverTo=req(b.handoverTo);d.offeredDay=past(b.day);if(d.offeredDay<d.collectedDay)fail('تاریخ تحویل قبل از دریافت نیست.');d.state='offered';detail={handoverTo:d.handoverTo,day:d.offeredDay};
 }else if(mode==='receipt'){open();if(!['carrier','offered'].includes(d.state))fail('محموله هنوز به مرحله دریافت مقصد نرسیده.');if(d.inbound){if(!u.isAdmin&&(mid!==d.receiverId||(d.kind==='purchase_order'?!purchaseReceiver(u.permissions):!domainAccess(u,d.domain)||!role(u,d.kind==='as_case'?'intake':'inventory'))))fail('فقط مسئول دریافت مقصد مجاز است.',403);}else if(!u.isAdmin){const allowed=salesRep(u)&&d.salesAgentId===u.permissions.salesAgentId||isAgent(u)&&d.agentId===u.permissions.serviceAgentId||transportManager(u)&&!d.agentId&&!d.salesAgentId;if(!allowed)fail('تأیید نهایی با نماینده مقصد است؛ برای مقصد فاقد حساب مسئول تدارکات رسید را ثبت می‌کند.',403);}
 const n=packs(b.packages),actual=past(b.day);if(actual<(d.carrierDay||d.offeredDay||d.collectedDay))fail('دریافت قبل از تحویل نیست.');if(!['complete','shortage','damage'].includes(b.result))fail('نتیجه دریافت انتخاب شود.');if(b.result==='complete'&&n!==d.packages)fail('تعداد کامل با تعداد محموله برابر نیست.');const files=await transportFiles(u,m);if(!d.agentId&&!d.salesAgentId&&!d.inbound&&!files.some(f=>f.data.purpose==='receipt'))fail('برای تأیید مقصد فاقد حساب، رسید تحویل را بارگذاری کنید.');d.receipt={packages:n,day:actual,result:b.result,by:u.userId,notes};detail=d.receipt;
 if(b.result!=='complete'){d.previousState=d.state;d.state='disputed';}
 else {const s=await get(d.sourceId,d.kind);if(s.data.transportId!==m.id)fail('ارتباط مرجع حمل تغییر کرده است.',409);
 if(d.kind==='sale'){if(s.data.state!=='in_transit')fail('حواله قبلاً دریافت شده است.',409);for(const id of s.data.deviceIds){const build=await get(id,'build');if(build.data.state!=='in_transit'||build.data.saleId!==s.id)fail('سریال با حواله منطبق نیست.');entry(id,'in_transit',-1000);put(id,'build',{...build.data,state:'delivered',deliveredAt:now},build);stmts.push(db.prepare("INSERT INTO records(id,kind,payload,created) VALUES(?,'event',?,?)").bind(crypto.randomUUID(),JSON.stringify({device:id,stage:'تحویل مقصد',date:actual,operator:u.name,transportId:m.id,notes}),now));}put(s.id,s.type,{...s.data,state:'delivered',deliveredAt:now,deliveredBy:u.userId},s);
 }else if(d.kind==='as_shipment'){if(!['prepared','shipped'].includes(s.data.state))fail('بسته قبلاً دریافت شده است.',409);const o=await get(s.data.orderId,'as_order');for(const [i,l] of s.data.lines.entries()){entry(l.batchId,'service:transit:'+s.id,-l.quantity);entry(l.batchId,warehouse(s.data.agentId,s.data.domain),l.quantity);stmts.push(db.prepare('INSERT INTO service_lots(id,owner,domain,batch_id,order_id,line_id,quantity,unit_rial,created) VALUES(?,?,?,?,?,?,?,?,?)').bind(s.id+':'+i,s.data.agentId,s.data.domain,l.batchId,o.id,l.lineId,l.quantity,l.unitRial,now));const line=o.data.lines.find((x:any)=>x.id===l.lineId);if(!line)fail('ردیف سفارش یافت نشد.');line.received+=l.quantity;}if(o.data.lines.every((l:any)=>l.received===l.quantity))o.data.state='received';put(o.id,o.type,o.data,o);put(s.id,s.type,{...s.data,state:'received',receivedAt:now,receivedBy:u.userId},s);
 }else if(d.kind==='as_claim'){if(!['sent','awaiting_return'].includes(s.data.state))fail('داغی قبلاً دریافت یا بررسی شده است.');put(s.id,s.type,{...s.data,state:'received',receivedDay:actual,receivedAt:now,receivedBy:u.userId,location:req(b.location,100)},s);
 }else if(d.kind==='purchase_order'){if(!sourceReady(s))fail('سفارش خرید دیگر قابل دریافت نیست.');put(s.id,s.type,{...s.data,physicalArrival:{day:actual,by:u.userId,transportId:m.id,packages:n,notes},transportHistory:[...(s.data.transportHistory||[]),{transportId:m.id,day:actual,packages:n}]},s);
 }else put(s.id,s.type,{...s.data,physicalArrival:{day:actual,by:u.userId,transportId:m.id,notes}},s);
 d.state='delivered';d.deliveredAt=now;}
 }else if(mode==='resolve'){requireManager();if(d.state!=='disputed'||!['retry','accepted'].includes(b.resolution))fail('مغایرت باز و نتیجه بررسی لازم است.');d.state=d.previousState||'offered';detail={resolution:b.resolution};
 }else if(mode==='cancel'){requireManager();if(!['requested','assigned'].includes(d.state))fail('فقط پیش از دریافت فیزیکی قابل لغو است.');const s=await get(d.sourceId,d.kind);if(s.data.transportId===m.id){delete s.data.transportId;put(s.id,s.type,s.data,s);}d.state='cancelled';
 }else if(mode==='expense'){driver();if(d.state==='cancelled')fail('مأموریت لغو شده است.');const cost={id:op,amountRial:amount(b.amountRial),reference:req(b.reference,300),notes,state:'pending',byMember:mid,at:now};d.expenses.push(cost);detail=cost;
 }else if(mode==='expense_review'){if(!transportFinance(u))fail('تأیید هزینه با مالی است.',403);const cost=d.expenses.find((e:any)=>e.id===b.expenseId);if(!cost||cost.state!=='pending'||typeof b.approved!=='boolean')fail('هزینه بررسی‌نشده لازم است.');if(!u.isAdmin&&cost.byMember===mid)fail('ثبت‌کننده هزینه نمی‌تواند تأییدکننده خودش باشد.',403);cost.state=b.approved?'approved':'rejected';cost.reviewedBy=u.userId;cost.reviewNotes=notes;detail={expenseId:cost.id,approved:b.approved};}
 d.history.push({mode,actor:u.userId,at:now,notes,...detail});put(m.id,'transport',d,m);
 }
 await db.batch([db.prepare('INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,?,?,?,?,1)').bind(op,'transport_'+mode,signature,u.userId,now),...checks,...stmts,db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,target,'transport_'+mode,signature,now)]);
 let followup=true;try{await syncTransportTasks();}catch{followup=false;}return json({saved:true,id:target,followupPending:!followup});
 }catch(e){return accessResponse(e)||json({error:'ثبت حمل انجام نشد؛ وضعیت هم‌زمان تغییر کرده است. تازه‌سازی و بررسی کنید.'},409)}}
