import {requireAccess,checkOrigin,AccessError,accessResponse} from '@/lib/authorization';
import {storage} from '@/lib/storage';
import {boundedBody} from '@/lib/firmware-storage';
import {costRead,costWrite,moneyMicro} from '@/lib/costing';
import {expenseGroups,expenseTreatments,suggestExpense,normalizeExpense} from '@/lib/expense-register';
const fail=(m:string,s=400):never=>{throw new AccessError(m,s)};
const txt=(v:any,max=500)=>{if(typeof v!=='string'||!v.trim()||v.length>max)fail('متن الزامی یا نامعتبر است.');return v.trim();};
const json=(v:any)=>Response.json(v,{headers:{'Cache-Control':'private, no-store'}});
async function rows(){return (await storage().prepare("SELECT * FROM flow_entities WHERE type IN ('expense_register','expense_rule','build_project','purchase_payable','purchase_settlement','purchase_order','hospital_job','cost_period') ORDER BY updated DESC").all()).results.map((r:any)=>({...r,data:JSON.parse(r.data)}));}
export async function GET(){try{const u=await requireAccess();if(!costRead(u))fail('دسترسی مالی لازم است.',403);const all=await rows();return json({write:costWrite(u),groups:expenseGroups,treatments:expenseTreatments,records:all.filter(r=>r.type==='expense_register'),rules:all.filter(r=>r.type==='expense_rule'),links:all.filter(r=>!['expense_register','expense_rule'].includes(r.type)).map(r=>({id:r.id,type:r.type,title:r.data.title||r.data.invoiceNumber||r.data.description||r.id})),note:'طبقه‌بندی و حساب پیشنهادی؛ ثبت سند سپیدار یا انتقال مبلغ به دوره مالی انجام نمی‌شود. مبالغ مرتبط با تسویه خرید دوباره به قیمت بچ اضافه نمی‌شوند.'});}catch(e){return accessResponse(e)||Response.json({error:'خواندن هزینه‌ها ممکن نشد.'},{status:503});}}
export async function POST(request:Request){try{checkOrigin(request);const u=await requireAccess();if(!costWrite(u))fail('دسترسی نوشتن مالی لازم است.',403);const b=JSON.parse(new TextDecoder().decode(await boundedBody(request,64000))),all=await rows();if(b.mode==='suggest')return json(suggestExpense(txt(b.description,2000),all.filter(r=>r.type==='expense_rule')));
 if(b.confirmed!==true||! /^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(b.id))fail('تأیید و UUID معتبر لازم است.');
 const db=storage(),signature=JSON.stringify(b),prior:any=await db.prepare('SELECT payload,actor FROM inventory_operations WHERE id=?').bind(b.id).first();if(prior){if(prior.payload!==signature||prior.actor!==u.userId)fail('شناسه عملیات تکراری نامعتبر است.',409);return json({saved:true,repeated:true});}
 const now=new Date().toISOString(),target=b.recordId||b.id,old=all.find(r=>r.id===target);if(old&&!['expense_register','expense_rule'].includes(old.type))fail('نوع رکورد نادرست است.');if(!Number.isSafeInteger(b.revision)||b.revision!==(old?.revision||0))fail('نسخه تغییر کرده است.',409);let data:any,type='expense_register';const notes=txt(b.notes,4000);
 if(b.mode==='save'){
 if(old&&(old.type!=='expense_register'||old.data.state==='approved'))fail('ابتدا پرونده تأییدشده را بازگشایی کنید.');
 const day=txt(b.day,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(day)||!Number.isFinite(Date.parse(day))||new Date(day).toISOString().slice(0,10)!==day)fail('تاریخ معتبر لازم است.');
 if(!Array.isArray(b.lines)||!b.lines.length||b.lines.length>40)fail('۱ تا ۴۰ ردیف لازم است.');const total=moneyMicro(b.total);if(total<=BigInt(0))fail('مبلغ مثبت لازم است.');
 const lines=b.lines.map((l:any)=>{const amount=moneyMicro(l.amount);if(amount<=BigInt(0))fail('مبلغ ردیف مثبت باشد.');const description=txt(l.description,2000),suggestion=suggestExpense(description,all.filter(r=>r.type==='expense_rule'));const group=l.group||'',treatment=l.treatment||'review';if(group&&!expenseGroups[group]||!expenseTreatments[treatment])fail('طبقه‌بندی معتبر نیست.');const linkId=l.linkId||'';if(linkId&&!all.some(r=>r.id===linkId&&!['expense_register','expense_rule'].includes(r.type)))fail('مرجع مرتبط یافت نشد.');return {description,amount:l.amount,group,treatment,center:typeof l.center==='string'?l.center.slice(0,200):'',account:typeof l.account==='string'?l.account.slice(0,200):'',linkId,suggestion};});if(lines.reduce((n:bigint,l:any)=>n+moneyMicro(l.amount),BigInt(0))!==total)fail('جمع ردیف‌ها با مبلغ مدرک برابر نیست.');
 const reference=txt(b.reference),supplier=txt(b.supplier,200);if(all.some(r=>r.type==='expense_register'&&r.id!==target&&normalizeExpense(r.data.reference)===normalizeExpense(reference)&&normalizeExpense(r.data.supplier)===normalizeExpense(supplier)))fail('این مدرک برای همین طرف حساب قبلاً ثبت شده است.',409);
 data={day,total:b.total,reference,supplier,lines,state:'draft'};
 }else if(b.mode==='approve'||b.mode==='reopen'){
 if(!old||old.type!=='expense_register')fail('پرونده یافت نشد.');data={...old.data};if(b.mode==='approve'){if(data.state==='approved')fail('قبلاً تأیید شده است.');if(data.lines.some((l:any)=>l.treatment==='review'||!l.account.trim()||!l.center.trim()||(['period','production','inventory'].includes(l.treatment)&&!l.group)))fail('دسته، مرکز هزینه و حساب معین تمام ردیف‌ها را تکمیل کنید.');data.state='approved';data.approvedBy=u.userId;data.approvedAt=now;}else{if(data.state!=='approved')fail('فقط پرونده تأییدشده بازگشایی می‌شود.');data.state='draft';delete data.approvedAt;delete data.approvedBy;}
 }else if(b.mode==='retire_rule'){
 if(!old||old.type!=='expense_rule')fail('قاعده یافت نشد.');type='expense_rule';data={...old.data,active:false};
 }else if(b.mode==='rule'){
 const record=all.find(r=>r.type==='expense_register'&&r.id===b.sourceId&&r.data.state==='approved');if(!record||!Number.isSafeInteger(b.lineIndex)||!record.data.lines[b.lineIndex])fail('ردیف تأییدشده لازم است.');if(old&&old.type!=='expense_rule')fail('نوع رکورد نادرست است.');const l=record.data.lines[b.lineIndex];if(all.some(r=>r.type==='expense_rule'&&r.id!==target&&r.data.active&&normalizeExpense(r.data.description)===normalizeExpense(l.description)))fail('قاعده فعال برای این شرح وجود دارد؛ ابتدا آن را غیرفعال کنید.',409);type='expense_rule';data={description:l.description,classification:{group:l.group,treatment:l.treatment,center:l.center,account:l.account},active:b.active!==false,sourceId:record.id};
 }else fail('عملیات نامعتبر است.');
 data.history=[...(old?.data.history||[]),{at:now,actor:u.userId,name:u.name,notes,previous:old?{...old.data,history:undefined}:null}];
 const guard=db.prepare('UPDATE inventory_operations SET guard=CASE WHEN COALESCE((SELECT revision FROM flow_entities WHERE id=?),0)=? AND (SELECT COALESCE(SUM(revision),0) FROM flow_entities WHERE type IN (\'expense_register\',\'expense_rule\',\'build_project\',\'purchase_payable\',\'purchase_settlement\',\'purchase_order\',\'hospital_job\',\'cost_period\'))=? THEN 1 ELSE 0 END WHERE id=?').bind(target,old?.revision||0,all.reduce((n,r)=>n+r.revision,0),b.id);
 await db.batch([db.prepare('INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,?,?,?,?,1)').bind(b.id,'expense_register_'+b.mode,signature,u.userId,now),guard,old?db.prepare('UPDATE flow_entities SET data=?,revision=revision+1,updated=? WHERE id=?').bind(JSON.stringify(data),now,target):db.prepare('INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,?,?,1,?,?)').bind(target,type,JSON.stringify(data),now,now),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,target,'expense_register_'+b.mode,JSON.stringify(data),now)]);return json({saved:true,id:target});
 }catch(e){return accessResponse(e)||Response.json({error:'ثبت انجام نشد؛ مبلغ و اطلاعات را بررسی و تازه‌سازی کنید.'},{status:409});}}
