import {requireAccess,checkOrigin,accessResponse} from '@/lib/authorization';
import {boundedBody,firmwareBucket} from '@/lib/firmware-storage';
import {validateBatchFile,MAX_BATCH_FILE_BYTES} from '@/lib/batch-files';
import {sha256} from '@/lib/firmware';
import {storage} from '@/lib/storage';
import {foreignBy,foreignFileVisible,foreignFileWrite,foreignFail as fail} from '@/lib/foreign-purchase';
import {foreignFileKinds} from '@/lib/foreign-purchase-contract';
import {supplierEntity} from '@/lib/suppliers';
import {validDay,dayAt,taskRequired as req} from '@/lib/duties';
export async function GET(request:Request){try{const u=await requireAccess(),raw:any=await storage().prepare("SELECT * FROM flow_entities WHERE id=? AND type IN ('foreign_file','shipment_file')").bind(new URL(request.url).searchParams.get('id')||'').first();if(!raw)fail('مدرک یافت نشد.',404);const f={...raw,data:JSON.parse(raw.data)};await foreignBy(u,f.data.caseId||f.data.shipmentId);if(!foreignFileVisible(u,f.data))fail('مجوز دریافت این مدرک را ندارید.',403);const o=await firmwareBucket().get(f.data.objectKey);if(!o)fail('فایل در دسترس نیست.',404);const bytes=await o!.arrayBuffer();if(bytes.byteLength!==f.data.byteSize||await sha256(bytes)!==f.data.sha256)fail('یکپارچگی فایل تأیید نشد.',503);return new Response(bytes,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(f.data.filename),'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"sandbox; default-src 'none'"}});}catch(e){return accessResponse(e)||Response.json({error:'دریافت مدرک انجام نشد.'},{status:503});}}
export async function POST(request:Request){let key='';try{checkOrigin(request);const u=await requireAccess(),q=new URL(request.url).searchParams,id=req(q.get('id'),80),caseId=req(q.get('caseId')),filename=req(q.get('filename'),180),kind=req(q.get('kind'),40),issuedOn=req(q.get('issuedOn'),10),reference=req(q.get('reference'),200);if(q.get('confirmed')!=='true'||!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(id)||!Object.hasOwn(foreignFileKinds,kind)||!validDay(issuedOn)||issuedOn>dayAt())fail('شناسه، نوع، تاریخ و تأیید معتبر لازم است.');const s=await foreignBy(u,caseId);if(!foreignFileWrite(u,kind)||s.type==='foreign_selection'&&!['sample','technical','proforma'].includes(kind))fail('بارگذاری این مدرک مجاز نیست.',403);if(Number(q.get('revision'))!==s.revision)fail('پرونده تغییر کرده است.',409);const bytes=await boundedBody(request,MAX_BATCH_FILE_BYTES);validateBatchFile(filename,bytes.length);const hash=await sha256(bytes.buffer as ArrayBuffer),signature=JSON.stringify({caseId,filename,kind,issuedOn,reference,hash}),db=storage(),old:any=await db.prepare('SELECT * FROM flow_entities WHERE id=?').bind(id).first();if(old){const d=JSON.parse(old.data);if(old.type!=='foreign_file'||d.signature!==signature||d.actor!==u.userId)fail('شناسه قبلاً استفاده شده است.',409);return Response.json({id,repeated:true});}const now=new Date().toISOString();key='foreign-purchases/'+caseId+'/'+id+'/'+crypto.randomUUID();await firmwareBucket().put(key,bytes,{httpMetadata:{contentType:'application/octet-stream'}});await db.batch([db.prepare("INSERT INTO inventory_operations(id,kind,payload,actor,created,guard) VALUES(?,'foreign_upload',?,?,?,CASE WHEN EXISTS(SELECT 1 FROM flow_entities WHERE id=? AND revision=?) THEN 1 ELSE 0 END)").bind(id,signature,u.userId,now,caseId,s.revision),db.prepare("INSERT INTO flow_entities(id,type,data,revision,created,updated) VALUES(?,'foreign_file',?,1,?,?)").bind(id,JSON.stringify({caseId,shipmentId:s.type==='purchase_shipment'?caseId:'',filename,kind,issuedOn,reference,sha256:hash,byteSize:bytes.length,actor:u.userId,objectKey:key,signature}),now,now),db.prepare('INSERT INTO access_audit(id,actor,target,action,after,at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,caseId,'foreign_upload',signature,now)]);return Response.json({id},{headers:{'Cache-Control':'no-store'}});}catch(e){if(key)try{const r=await storage().prepare("SELECT id FROM flow_entities WHERE type='foreign_file' AND json_extract(data,'$.objectKey')=?").bind(key).first();if(!r)await firmwareBucket().delete(key);}catch{}return accessResponse(e)||Response.json({error:'مدرک ثبت نشد؛ با همان شناسه تلاش کنید.'},{status:409});}}
